### ISSUE TITLE
[Suggestion] Make the yellow-search-box-darken-screen thingie activate using a button

### ISSUE THREAD

**Issue by Vexatos** [mezz/JustEnoughItems#1]
Not by double clicking the search bar.

**Comment by mezz** [comment]
I'm not sure I want to add this feature at all.

**Comment by TheDoctorSoda** [comment]
It's useful, but it could be put in an addon.

**Comment by modmuss50** [comment]
Could just render a glow around the item or something

**Comment by einsteinsci** [comment]
I'd have to agree with the OP on this. Double-clicking the search bar is much less intuitive than a toggle button. When I was first using NEI I turned it on by accident, and had to do some googling before I found out what the gold search bar meant and how to turn it off.

**Comment by mezz** [comment]
Now that JEI exposes the search bar in the API (https://github.com/mezz/JustEnoughItems/issues/88), I think I will leave this feature to an addon.
