### ISSUE TITLE
Allow exporting and importing of enabled blocks / Items

### ISSUE THREAD

**Issue by dredhorse** [mezz/JustEnoughItems#100]
Have an option which allows to enable / disable specific blocks / items, either granulary or via mods.

Allow the export / import / saving of this config.

This would help to cut down on clutter, perhaps even add an option to switch between several of those configs.

One reason is that I play with my kids and all of the unneeded blocks just confuse them, an other reason would be to be able to let pack authors show only certain blocks.

**Comment by TehNut** [comment]
There is a blacklist implemented. You can access it in-game via the settings button at the bottom right. It doesn't let you dynamically load different "configurations" of hidden entries, however.
