### ISSUE TITLE
Rendering ingredient(1.12.1) crash when looking up recipe

### ISSUE THREAD

**Issue by SDUBZ** [mezz/JustEnoughItems#1003]
Forge:1.12.1-2485
jei: 4.7.11.100
Random things: 4.0.6

this crash occurred when i was looking up @th in jei

crash:
https://gist.github.com/SDUBZ/4b9c455d25b89dc4455e22ee17281f78

**Comment by SDUBZ** [comment]
also happens with jei_1.12.2-4.7.11.101 https://gist.github.com/SDUBZ/a7c9a3155c5593c0811ecb7d2e04e9cf

not sure if mezz's side or random things @lumien231

**Comment by danielhickman** [comment]
Reverting to release worked for me for now. Unsure how I got to the beta channel. I also had the same crash when looking up `im` and a Lime Luminous block appeared in the list.

**Comment by SDUBZ** [comment]
i will try that @danielhickman thanks for info

**Comment by mezz** [comment]
Thanks for the report!
This was reported to Random Things here: https://github.com/lumien231/Random-Things/issues/242
And fixed in the latest version of Random Things and JEI: https://minecraft.curseforge.com/projects/random-things/files/2484374

**Comment by SDUBZ** [comment]
good to hear mezz :D
