### ISSUE TITLE
Suggestion involving vanilla crafting guide

### ISSUE THREAD

**Issue by Spleenczar** [mezz/JustEnoughItems#1005]
Having JEI installed renders the vanilla crafting guide obsolete. Because of this, I have a suggestion, although as someone who isn't familiar with programming I'm not sure how feasible this is to do.
JEI should remove the vanilla crafting guide but keep the book icon in the inventory. The book icon can be clicked to toggle JEI on and off. This way, JEI acts as a full, polished replacement to the vanilla crafting guide.

**Comment by TehNut** [comment]
#922

**Comment by mezz** [comment]
Thanks for the suggestion.
This could be implemented by a simple addon, but I do not want to alter vanilla in JEI directly.
