### ISSUE TITLE
Debugging - Chisel and JEI Minecraft 1.12.2 - forge stable 91

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#1006]
Issues rendering air tiles
https://gist.github.com/P3rf3ctXZer0/772e6e7ce4dba4d17c1412e0d1fa12c1

WIP Investigation

**Comment by mezz** [comment]
Thanks for the report!
This is a Chisel issue, it looks like they are registering a description page for an empty itemstack.
