### ISSUE TITLE
Crash after Loading the game

### ISSUE THREAD

**Issue by RogoShum** [mezz/JustEnoughItems#1007]
minecraft verson:1.11.2
Crash after loading the game progress bar
Only forge and Jei are installed

http://mcpc.oss-cn-zhangjiakou.aliyuncs.com/crash-2017-09-28_22.35.27-client.txt
http://mcpc.oss-cn-zhangjiakou.aliyuncs.com/fml-client-latest.log

**Comment by mezz** [comment]
Thanks for the report!
It looks like your game has a "null" language somehow. I have never seen something like that before.
There is another error at the end the log when trying to get language:
`Current Language: ~~ERROR~~ NullPointerException: null`

Do you have the Chinese version of Forge, a cracked Minecraft client, or anything else that is unusual?

**Comment by RogoShum** [comment]
When I change a launcher, the game can be opend，its my first time see conflict between mod and launcher,very strange
If I used the previous one，the game will crash in here
http://mcpc.oss-cn-zhangjiakou.aliyuncs.com/2017-09-29.png

this launcher can update my server's mod,is there any way I can get two?

**Comment by mezz** [comment]
Sorry I do not know what is wrong with that launcher.
Please report this issue to them and put a link here. I can help if they have questions.

**Comment by RogoShum** [comment]
Thank you, but no need, I can directly change the launcher, and the launcher's author is often absent, I will find time to give him feedback.
