### ISSUE TITLE
[1.12.x] missing fluid textures in JEI

### ISSUE THREAD

**Issue by WesTroy** [mezz/JustEnoughItems#1011]
mezz - thanks for your amazing contributions to modding. Keep up the great work!
Quick bug report:

Latest **jei_1.12.2-4.7.11.102** causes many mod fluids to have blank textures in JEI.
Tested both 1.12.1 and 1.12.2, with only JEI and Forestry as a base for the test.
Many other mods are also affected (ImmersiveEngineering, etc.), but there are also mods where this does not occur (BiomesOPlenty, ThermalFoundation, and TConstruct work fine, for example).

Hope this helps! Have a great day.

1.12.1 test:
- Forge versions 1.12.1-14.22.1.2478 (recommended) and 1.12.1-14-22.1.2485 (latest)
- forestry_1.12.2-5.5.6.198
- **jei_1.12.2-4.7.11.101** works fine, shows all Forestry fluids (forestry:fluid.*)
- **jei_1.12.2-4.7.11.102** shows blank Forestry fluid textures in JEI

1.12.2 test:
- Forge versions 1.12.2-14.23.0.2491 (recommended) and 1.12.2-14.23.0.2495 (latest)
- forestry_1.12.2-5.5.6.198
- **jei_1.12.2-4.7.11.101** works fine, shows all Forestry fluids (forestry:fluid.*)
- **jei_1.12.2-4.7.11.102** shows blank Forestry fluid textures in JEI

**Comment by mezz** [comment]
Thanks for the report!
It looks like this is affecting the ItemStack version of fluids. I'll have a fix in the next release.
