### ISSUE TITLE
(1.12.2) Press R does not show crafting recipe

### ISSUE THREAD

**Issue by LordHellscream** [mezz/JustEnoughItems#1012]
Forge 2501
JEI version 8.0.103

Just updated my game to 1.12.2, and everything else seems to work but JEI doesn't show recipe when pressing R.
- there is NO conflicting control short-cut.
- tried both cheat and non-cheat mode.
- tried both in inventory and crafting table opened.
- R works for items that has mod-block-processing recipe (say pressing R on a cobblestone will show recipe of furnus mod, but NOT the vanilla furnace or any regular crafting)

**Comment by lag42** [comment]
i installed a couple extra recipe viewing mods like [just enough harvestcraft](https://minecraft.curseforge.com/projects/just-enough-harvestcraft) and [just enough pattern banners](https://minecraft.curseforge.com/projects/just-enough-pattern-banners) and their recipes showed up so the api is in place

**Comment by LordHellscream** [comment]
looks like this was caused by the Sync mod from iChun, closing this for now.

**Comment by lag42** [comment]
Also fixed in latest sync version

**Comment by mezz** [comment]
Thanks for letting me know.

**Comment by Yarden-zamir** [comment]
I'm having the same problem without sync mod

**Comment by mezz** [comment]
@PandaBoy444 please open a new issue, and I will need some more information to solve it. 
Please paste your full `fml-client-latest.log` to https://gist.github.com and link it in the new issue.
