### ISSUE TITLE
JEI overlay ontop of a different window

### ISSUE THREAD

**Issue by Dockter** [mezz/JustEnoughItems#1014]
Forge: 1.12.2 - Build 2501.
JEI: jei_1.12.2-4.8.0.103

Main issue, we use the SGCraft mod and when we click on the DHD to open the controller window the JEI item list renders on top of it.  Is there something I am suppose to be doing differently (code wise) when I open the window at the client or is this a bug with JEI?

We do not have NEI installed just to clarify.

Picture of issue:  http://www.almuramc.com/images/overlay.png

AlmuraDev's SGCraft repo for 1.12.x = https://github.com/AlmuraDev/SGCraft

**Comment by TehNut** [comment]
You seem to be setting your container size to 0x0

**Comment by Dockter** [comment]
TehNut, could you clarify?

**Comment by Dockter** [comment]
@TehNut @Zidane and I tried passing in 1 x 1 just for experimental purposes but it didn't change the result:
https://github.com/AlmuraDev/SGCraft/blob/1.12.1/src/mod/gcewing/sg/SGScreen.java#L41

**Comment by Dockter** [comment]
FYI, the intended screen doesn't have any slots.  Ideally JEI shouldn't be displayed on this screen at all.

**Comment by TehNut** [comment]
Why would a size of 1x1 pixel fix this? JEI scales itself based on the width of the open container. 

>Ideally JEI shouldn't be displayed on this screen at all.

JEI displays on all GuiContainers. If you don't have any slota, why are you using a container?

**Comment by mezz** [comment]
TehNut has the right idea, the solution here is to use `GuiScreen` when you have no slots. JEI displays on all `GuiContainers`.
