### ISSUE TITLE
Hiding from recipes

### ISSUE THREAD

**Issue by Mewr11** [mezz/JustEnoughItems#1016]
I'm not entirely sure if this is an bug or an intended feature (or both ;p), but hiding items via edit mode still lets them show up in recipes. I only bring this up because Chisel makes crafting everything a PITA in hardcore modded packs.

EDIT: Grammar are difficult, apparently.

**Comment by mezz** [comment]
Yes this is normal. Items can be hidden from the list but they are not hidden from recipes. The intention of item hiding is to get rid of item spam that you are not interested in seeing, which was a common issue in NEI with covers, multiparts, and things like that.
