### ISSUE TITLE
Recipe aware IRecipeCategory drawExtras

### ISSUE THREAD

**Issue by tomelfring** [mezz/JustEnoughItems#1019]
Hi!

With Mekanism we ran into a problem with `IRecipeCategory` drawExtras method. We have a recipe (RotaryCondensentrator) which has two modes to operate, and it draws some extras depending on which kind of recipe it is (Essentially an arrow to the left or right). This works perfectly, if only one recipe is on screen at a time. If multiple recipes are on the screen, it always renders the extras of the bottom recipe.

An example of what's happening:
![Example](https://user-images.githubusercontent.com/16061266/31309435-12d5ee54-ab54-11e7-83eb-0127eaca0353.png)

It looks like we totally misunderstood the way `IRecipeCategory` works, but I have no idea how to solve this nicely. I've done some technical analysis over at https://github.com/aidancbrady/Mekanism/issues/4751

Versions:
Minecraft: 1.12.1
Forge: 14.22.0.2446 & 14.22.0.2503
Mekanism: Current latest
JEI: 4.7.0.67 & 4.8.0.105

Would be great if you could point me in the right direction!

**Comment by mezz** [comment]
I recommend drawing recipe-specific things like the arrow in `IRecipeWrapper#drawInfo`.

**Comment by mezz** [comment]
Alternatively, you can break it into two recipe categories. One for condensentrating and one for decondensentrating.

**Comment by tomelfring** [comment]
Thank you! I totally didn't think of adding two categories to one machine, that would solve it!
