### ISSUE TITLE
Gated Recipes.

### ISSUE THREAD

**Issue by ryantheleach** [mezz/JustEnoughItems#1022]
Hey Mezz,

Would it be possible to tie into Vanilla's restricted crafting gamerule in order to gate / hide recipes in JEI if mods supported it correctly?

I've recently started playing modded Minecraft again with friends who have only played vanilla, and they very very quickly were overwhelmed by all the possible items that could be crafted.

I'd love to lower the barrier of entry into crafting with modpacks, but at current with the current mod pack designs literally none of them over the years (barring a few exceptions, that have books, or hard core quest modes made for them that show the recipe) have made their beginnings easily accessible to new-to-modding players.

I'd love to share the joy of modded minecraft with these players, without them having to trawl through getting started wiki pages like we all did when we started.

What do you say? Possible?

**Comment by ryantheleach** [comment]
Also, it would be good if you could force the recipes to show, that would allow people planning tech tree like to what they need to go to next, but hide the complexity 99% of the time.

**Comment by mezz** [comment]
Thanks for the suggestion!

This is a good idea and people have been thinking on it for a little while now. There are a couple packs that have worked closely with me to implement this feature, and currently you can hide and show recipes from JEI's API.
There is no built-in functionality to control this though, and the mods that intend to use it are still in development.

For gating vanilla recipes, there is an open issue here: https://github.com/mezz/JustEnoughItems/issues/937
