### ISSUE TITLE
Dupe bug with Ctrl+Click

### ISSUE THREAD

**Issue by xenoflot** [mezz/JustEnoughItems#1024]
Playing current (20171012) ver of FTB Beyond 1.10
MCP 9.19
FML 8.0.99.99
Forge 12.18.3.2422
ActuallyAdditions 1.10.2-r105
JEI 3.14.7.419
InvTweaks 1.61-58-a1fd884

Normal operation:

    Using Ctrl+Click on a vanilla inventory will transfer 1 item from a stack to/from the player's inventory.
    Ctrl+LeftClick drops the 1 item on an existing stack in the destination inventory.
    Ctrl+RightClick creates a new stack for each 1 item transferred.
    If Ctrl+Clicking with no GUI open, it will transfer 1 item between the hotbar and the player's main inventory.

Ctrl+Clicking with an AA machine GUI open (tested with Farmer, Canola Press and Coal Gen) results in JEI's spawn item functionality being triggered (even though spawn mode is currently disabled).

    A Ctrl+RightClick spawns a single item.
    A Crtl+LeftClick spawns the difference between the partial stack being clicked, and the max stack size.
    Tested with coal and canola.

Originally, I discovered this with ActuallyAdditions machines. Just now, I have also gotten this result when trying to Ctrl-Click a TiCo hammer into the Tool Forge. x-posting to InvTweaks Git.

Cheers!

**Comment by mezz** [comment]
Thanks for the report!
Sorry I missed this one.
I don't think this is caused by JEI, there doesn't seem to be a way to trigger this with just JEI alone.
