### ISSUE TITLE
[1.11.2] Ore dictionary custom recipes don't showing recipe

### ISSUE THREAD

**Issue by KorDum** [mezz/JustEnoughItems#1025]
![image](https://user-images.githubusercontent.com/1331559/31507208-836e8c66-af82-11e7-809d-34cc924c28ee.png)

![image](https://user-images.githubusercontent.com/1331559/31507252-b11837d4-af82-11e7-80de-1aff6bcc7da4.png)

I added `<plants:rubus_o>` into `listAllfruit` and `listAllberry` via `MineTweaker`. Recipes are work nice, but JEI does not show the recipes in which this item participates (by U key). But I see participation in a specific recipe (by R key).

**Comment by mezz** [comment]
Thanks for the report!
This is most likely an issue with Minetweaker adding the information later than JEI has resolved it.
This issue is fixed in 1.12, where Minetweaker does everything before JEI.

**Comment by KorDum** [comment]
Hm, but
```
val diorite = <ore:stoneDiorite>;
recipes.addShaped(<minecraft:cobblestone>, [
    [diorite, diorite, diorite],
    [diorite, <ore:dyeLightGray>, diorite],
    [diorite, diorite, diorite]
]);
```
works fine. Will this not clarify the situation?

**Comment by mezz** [comment]
By adding that recipe, Minetweaker adds the recipe to JEI after the oredictionary entry has been created.

If you add something to `<ore:stoneDiorite>` after adding the recipe, I think you will see the same problem.

**Comment by KorDum** [comment]
Thanks for answer!
