### ISSUE TITLE
Some items missing in JEI (too many items ?)

### ISSUE THREAD

**Issue by Thyriel** [mezz/JustEnoughItems#1026]
I'm not sure in what mod (or where) that problem comes from as it's behavior is pretty strange. Maybe someone has an idea what may cause this (and how i can solve it): 

Some items in JEI are missing for me, e.g. Tinker's Constructs Part Builder and Tool Stations. (And i'm sure quite some more)
They still work to be crafted but they don't show up in JEI.

What's rather strange on that is: 
I currently have over 100 mods installed (=19 pages of items at 1080p resolution and normal UI size setting). But trying to pinpoint the mod causing this it turned out to not be a specific mod. The items seem to always appear back when i remove one or some mods that add quite a lot items. (e.g. Binnie's mod, or Quark+ Viescraft+Primalcore, or Pam's harvestcraft + StorageDrawers+extra drawers)

So, can it be that JEI has a limit on how many items it can display ? Or any other idea what may cause this ?

**Comment by mezz** [comment]
JEI does not have a limit to what can be displayed overall, but it does have limits for items with many subtypes.
If tinker's construct creates hundreds of tool stations for example, only one will be shown.
This limit is configurable in `config/jei/jei.cfg` as `advanced maxSubtypes`, set to 300 by default.
This limit prevents JEI from getting slow from thousands of automatically registered subtypes for things like pipe covers.

**Comment by Thyriel** [comment]
Ok, but that doesn't explain why all tool stations/part builders are missing (Especially as i'm not near near the 300 limit)

**Comment by KnightMiner** [comment]
Tool stations and part builders all use the same block ID with the other tables, so they are variants of the same block. In addition, part builders display a variant for every log type and stencil tables for every plank type.

If it is too many variants due to the amount of wood variants you have, Tinkers does have a config option to show only oak in creative/JEI for each table type.
