### ISSUE TITLE
All Files on curse are currently only giving 1.12.2 version

### ISSUE THREAD

**Issue by 5DaysNoSleep** [mezz/JustEnoughItems#1027]
Trying to get your mod for 1.10.2, but every link I have clicked only downloads the jei_1.12.2-4.8.0.105.jar file. Not quite sure whose end this issue may be on, help?
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by TehNut** [comment]
Select a file manually from the files list. The main download button only grabs the latest version marked as release.

**Comment by mezz** [comment]
Here is the full list of downloads:
https://minecraft.curseforge.com/projects/just-enough-items-jei/files
Do not click the green download button at the top, click the "download file" button next to the version you want. You can use the dropdown at the top right to restrict the list to specific versions.
