### ISSUE TITLE
can't find 1.10.2! ;(

### ISSUE THREAD

**Issue by PLEASEHELPME12** [mezz/JustEnoughItems#1030]
I cant find the 1.10.2 versions of just enough items, and al the other ones are not working on forge minecraft 1.10.2 can someone please help me!?!?

**Comment by GirafiStudios** [comment]
Link to latest 1.10.2 version of JEI: https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2428966

**Comment by PLEASEHELPME12** [comment]
tnx
