### ISSUE TITLE
cant find that tinkers construct addon for jei :(

### ISSUE THREAD

**Issue by ismirwurscht** [mezz/JustEnoughItems#1031]
so, im playing on 1.8.9 and want to add that jei addone so that i can see that recepes and stuff.. surfing in internet and cant find that addon. so can u help me? please?

**Comment by mezz** [comment]
JEI compatibility is built-in to each mod. Tinker's for 1.8.9 may not have integration, or the integration may be broken. I'm not sure, I haven't played on that version in a long time. You can ask on their github here for a better answer: https://github.com/SlimeKnights/TinkersConstruct/issues
