### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by BHY4A** [mezz/JustEnoughItems#1032]
Always crash
Tried to delete NEI, but nothing

[Crash log](https://gist.github.com/BHY4A/f31b62bea129aa4aaf11e73cbbc8561e)

**Comment by KnightMiner** [comment]
The screen you saw when starting up was not a crash, it said you have an outdated Forge version and JEI needs a higher version (assuming this is the correct game logs). Install at least Forge 14.23.0.2500

**Comment by BHY4A** [comment]
But lol, i have last Forge

**Comment by TehNut** [comment]
Nope. As per the *second line* of that log, you have `14.23.0.2491`. Latest is `14.23.0.2515`.

**Comment by BHY4A** [comment]
Maybe problem in launcher, hm

**Comment by HostedDinner** [comment]
@mezz Had similar problem with "old" Forge version. Please release Stable Version matching to the stable version of Forge. The stable version of forge is `14.23.0.2491` and not the latest (`14.23.0.2517`)!

**Comment by mezz** [comment]
The latest JEI depends on features that are in the latest Forge. If you want, you can use an older version of JEI that works with older Forge. I do not really keep track of where "recommended" Forge is, in my experience it's almost always stable.

**Comment by p0kefreak** [comment]
https://gist.github.com/p0kefreak/9c1590a850c54aa1975a169719e6cd33

I keep getting an error that jei requires fml 2500 and above, i do have the latest forge (2529) but it still asks for fml 2500 or above, it seems like this just happened i swear it was working a few days ago. and i have been working around forge/mods for about 7 years so i know how to install forge and what version im using etc but for some reason jei keeps asking me for 2500 and above yet im using 2529.
 i hope i put this in the right spot have a great day!

EDIT
even in my logs it says im using the recommended version of forge hmm maybe this is on forges end but only jei gets effected.

**Comment by mezz** [comment]
Right at the top of your log it says `Forge Mod Loader version 14.23.0.2491` which is not 2500 and above.
