### ISSUE TITLE
[Suggestion] Move items into crafting window

### ISSUE THREAD

**Issue by Raelzaryn** [mezz/JustEnoughItems#1033]
I'm aware that you disabled the moving items into the crafting window for a reason.
But with 1.12 Minecraft has a built in recipe book at allows to do just that. Wouldn't it be possible to use that functionality to move the items?

**Comment by mezz** [comment]
Sorry I missed this issue.
It seems like a good idea.
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/916
