### ISSUE TITLE
[SUGGESTION] Item search: Search for string NOT in item name

### ISSUE THREAD

**Issue by profiluefter** [mezz/JustEnoughItems#1034]
Would be great if you can add this feature.

**Comment by mezz** [comment]
To help me understand better, can you give an example search string that would use this?

**Comment by liach** [comment]
Excluding ingredients with a certain string in their names?

**Comment by profiluefter** [comment]
Exactly what I meant. (Not native speaker)

**Comment by KnightMiner** [comment]
I think mezz was asking for a specific example where you would use this, so why you want it

**Comment by profiluefter** [comment]
Example: stone -cobble

**Comment by profiluefter** [comment]
Would be great in big modpacks

**Comment by mezz** [comment]
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/820
I am working on implementing it now.
