### ISSUE TITLE
Rendering Ingredient crash

### ISSUE THREAD

**Issue by Ozzymud** [mezz/JustEnoughItems#1035]
Pack: All The Mods 1.12.1
Forge: 14.22.1.2485
JEI: 4.7.8.95
NEI/FEI: n/a

Crashed when trying to craft a Mekanism Advanced Solar... errored on an IC2 item. Appears to be a similar issue as https://github.com/mezz/JustEnoughItems/issues/1003 that was caused by Random Things.

Didn't know if I should re-open that issue, or report this to the IC2 guys as it appears to not only affect one mod anymore.

Crashlog: https://pastebin.com/bJ2wmNAw  

Other info: Output was shift clicked out of the table to cause the crash, reloading the game and just taking it out did not reproduce. "solar" was typed into JEI.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to IC2 here: https://bt.industrial-craft.net
I am not really sure why it is crashing, but I think JEI is not involved directly.
