### ISSUE TITLE
Where is 1.7.10 ?

### ISSUE THREAD

**Issue by SkySectoR** [mezz/JustEnoughItems#1036]
I can't find 1.7.10. Found a modpack without TMI NEI JEI and wanted to download but no such thing as JEI 1.7.10 :(

**Comment by liach** [comment]
Use NEI instead.

**Comment by mezz** [comment]
JEI only exists in 1.8 and higher. If it did exist, it would have no mod support on 1.7.10 because everyone already integrated with NEI there.
