### ISSUE TITLE
[1.12.2] ExUtils 2 glitch

### ISSUE THREAD

**Issue by 016Nojr** [mezz/JustEnoughItems#1037]
When viewing ExUtils 2 items in JEI, they change appearance. The appearance change when viewing recipes for the glitched items.

https://gyazo.com/e6c201998aea0daae634e891a8bdd80f

This started happening after updating JEI to version 4.7.10.99 and has been reproduced in a fresh instance with only JEI and ExUtils 2

I assume you want more information, tell me and I'll provide it

**Comment by mezz** [comment]
Thanks for the report!
It looks like ExU2 is reusing baked models for several different items. I'll try to contact RWTema about it.

**Comment by 016Nojr** [comment]
Thank you

**Comment by angelnc1989** [comment]
I have the same thing happening for some Bibliocraft items and all Decocraft items.

**Comment by mezz** [comment]
Since this is affecting several mods, I don't want to ask everyone to fix their rendering just for JEI.
I have fixed this issue in the latest version of JEI, tested with ExU2, Bibliocraft, and Decocraft.

**Comment by 016Nojr** [comment]
Thanks! :)
