### ISSUE TITLE
Crash every time I try to see the recipe for an item

### ISSUE THREAD

**Issue by McChantel** [mezz/JustEnoughItems#1039]
I apologize if this issue has already been solved somewhere else, but I've been unable to find a solution. Every time I click on a recipe my game crashes. 

[crash-2017-11-05_11.34.56-client.txt](https://github.com/mezz/JustEnoughItems/files/1444446/crash-2017-11-05_11.34.56-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
```
-- Item being rendered --
Details:
	Item Type: com.rwtema.extrautils2.backend.XUItemBlock@f0c584b
	Item Aux: 0
	Item NBT: null
	Item Foil: false
```
This seems to be a render issue with Extra Utilities 2, not caused by JEI. Try updating or removing that mod.

**Comment by McChantel** [comment]
Thanks so much :D
