### ISSUE TITLE
Some recipes dont show.

### ISSUE THREAD

**Issue by zedner** [mezz/JustEnoughItems#104]
jei_1.8.9-2.16.0.74 dont show recipe for "iron backpack" from mod Iron backpacks.
jei_1.8.9-2.16.0.77 dont show even more recipes for example some recipes from mod Furnus
i remember iron backpack recipe being shown at previous versions of JEI.
EDIT: recipes are shown in creative menu but when i take items in my survival inventory and try to check recipe or usage if that item it doesnt show.

**Comment by TehNut** [comment]
IronBackpacks uses [custom recipe handlers](https://github.com/gr8pefish/IronBackpacks/blob/master-1.8.9/src/main/java/main/ironbackpacks/crafting/ItemRecipeRegistry.java#L33-L35). That would be on @gr8pefish to add support. 

I assume that Furnus also uses custom recipe handlers.

**Comment by gr8pefish** [comment]
Yes, I'm working on adding JEI support to the 1.8 version of Iron Backpacks, I assumed it needed special handling already.

**Comment by mezz** [comment]
Since the recipes are working from the creative menu, @gr8pefish probably just needs to add some NBT tags to the ignored-NBT list in the JEI API.
