### ISSUE TITLE
Allow crafting blocks to overlay buttons on ItemStacks in recipe

### ISSUE THREAD

**Issue by Ambeco** [mezz/JustEnoughItems#1040]
Proposal: 
IRecipeTransferHandler or something similar should allow a container to place small clickable status icons on top of ItemStacks of arbitrary IRecipeCategory recipes. 

Reasoning: 
Refined Storage (https://github.com/raoulvdberge/refinedstorage) has a neat feature where you can teach it to craft items and dependencies on demand, even for arbitrary IRecipeCategory recipes. This involves a confirmation dialog to inform/remind the user which items will be consumed in the crafting.  Unfortunately, this means "does the container/player have this item" for IRecipeTransferHandler is not a boolean. Some items are available, some are not available, and some are craftable. To sidestep this issue, raoulvdberge has simply made RecipeTransferHandlerGrid never return an error, which makes the recipes tricky to use.  
It would be much clearer if IRecipeTransferHandler.transferRecipe could return a IRecipeTransferError for craftable items, and show a "craftable" status icon for these stacks. Upon clicking this icon, Refined Storage should show the crafting confirmation dialog, then start crafting, and animate the status icon. When the crafting is complete, the status icon should go away. RecipeTransferErrorSlots is _almost_ powerful enough already, except it's only shown when RecipeTransferButton is hovered over, rather than all of the time.

**Comment by mezz** [comment]
This feature has been improved over time, and now mods like AE2 and RefinedStorage have support for transferring from JEI even if you don't have all the items.
