### ISSUE TITLE
JEI Crash

### ISSUE THREAD

**Issue by jusjudge** [mezz/JustEnoughItems#1042]
JEI continuously causes my client to crash whenever I try to look through any tabs related to crafting or obtaining obsidian.

**Comment by way2muchnoise** [comment]
You should include the crash log you get. That way we can see what is going wrong.

**Comment by jusjudge** [comment]
@way2muchnoise I actually am not sure how to post the crash log. Should I just post it on here as a copy and paste or is there a specific website you would like me to upload it too?

**Comment by KnightMiner** [comment]
Try gist.github.com or pastebin.com, make sure to post the link here afterwards

**Comment by jusjudge** [comment]
@way2muchnoise @KnightMiner 

https://pastebin.com/7T17xdvv

**Comment by mezz** [comment]
Thanks for the report!

```
-- Item being rendered --
Details:
    Item Type: com.grim3212.mc.pack.tools.items.ItemBetterMilkBucket@68c0d095
    Item Aux: 0
    Item NBT: {Fluid:{FluidName:"water",Amount:1000}}
    Item Foil: false
```
From the snippet above, I see this crash is caused by an item from grim3212's grim-pack.
Please report this to the grim-pack issue tracker here: https://github.com/grim3212/grim-pack/issues
