### ISSUE TITLE
Can’t use mouse button for key bind

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1046]
I tried to bind the “show previously viewed recipe” key to MOUSE4 (a button on the side of many mice), but it didn’t work. It did work when I bound it to a keyboard key, however.

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**JEI version**: 4.8.0.114

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the next version.

**Comment by ghost** [comment]
Awesome! Thanks.
