### ISSUE TITLE
[API] Visual Issue with JEI Descriptions for fluidStacks (IModRegistry)

### ISSUE THREAD

**Issue by kindlich** [mezz/JustEnoughItems#1048]
Heyho,

I just wanted to inform you that when using the IModRegistry to add JEI descriptions to fluids, the fluid pictures will not be shown in the window:

![image](https://user-images.githubusercontent.com/10351787/32979971-d0701a2c-cc5e-11e7-94c3-9ddc2bd07850.png)

Code used for the tests:
https://github.com/kindlich/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Mod-JEI/src/main/java/crafttweaker/mods/jei/actions/DescribeAction.java

Technically this method is being called with the following parameters if a fluidStack is used:
```java
modRegistry.addIngredientInfo(List<Object>, fluidStack.class, description)
```
With modRegistry being an instance of [IModRegistry](https://github.com/mezz/JustEnoughItems/blob/1.12/src/api/java/mezz/jei/api/IModRegistry.java)

EDIT:
Forge Version: 1.12.2-14.23.0.2545
JEI Version: jei_1.12.2:4.8.0.115

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the next version.
