### ISSUE TITLE
API Additions

### ISSUE THREAD

**Issue by superckl** [mezz/JustEnoughItems#105]
I've been working on an addon for JEI (2.16.2.78) and I've had a few issues with interacting with the mod. I'll list them here. I might add more later as I encounter them. If there is a direct or better way to do any of these, please let me know.
- [ ]  Add a way to retrieve the RecipesGui instance. Currently I'm reflecting `guiEventHandler` from `ProxyCommonClient` (gotten from the `JustEnoughItems` instance) and then reflecting that to get `recipesGui`. I would appreciate if a way was added. (Not necessarily in the API. Mods that are simply adding their recipes will probably not need to access the GUI instance.)
- [ ] Add a way to get `logic` from `RecipesGui`, currently using reflection. (Not necessarily in the API.)
- [ ] Add a way to set the specific page (by index) and category (by instance & index) in `IRecipeGuiLogic`. Currently using (a lot of) reflection.
- [x] The experience gained text in the furnace recipe gui extends past the width specified by the background. This causes the text to sometimes continue past the specified area for the recipe. Not entirely sure what can be done about this, maybe a way to move the text left if needed?

Another more general point - A lot of classes that I could foresee extending have all private fields. It would be useful if the classes that are likely to be extended have protected fields.

**Comment by superckl** [comment]
In response to your comment on #114, I'm going to list out the ways in which I am currently forced to interact with non-API classes.
- Retrieving the RecipesGui (required to open it, no proper abstraction in API) instance requires using `JustEnoughItems`, `ProxyCommonClient`, and `GuiEventHandler`.
- Retrieving RecipeLayouts from JEI properly requires using `Focus`, `Focus.Mode`, and `RecipeGuiLogic`. The needed methods are present in `IRecipeGuiLogic` (which isn't even in the API), but there is no way to get an instance that I know of without referencing `RecipeGuiLogic`.
- I am unable to abstract to `IRecipeLayout` since `IRecipeGuiLogic.getRecipeWidgets` returns a list of `RecipeLayout`.
- Retrieving any specific information from an `IRecipeWrapper` (e.g. `SmeltingRecipe`) requires referencing the wrapper class directly (and reflection in most cases).
- Retrieving `IRecipeTransferHandler` for a container requires referencing `Internal` to get a reference to `RecipeRegistry`. The required method is not present in `IRecipeRegistry`.
- Transferring a recipe should be done with `RecipeTransferUtil`, which is not in the  API.

Hope this helps.

**Comment by mezz** [comment]
Thanks, that is helpful.
I have two features that I need to finish before I can get to this: #81 and #65

**Comment by ColinGBos** [comment]
I agree, a way to open the recipes gui would be very helpful. I can't comment on the other things though.

**Comment by mezz** [comment]
A lot has happened since this issue was created. It should be possible to render recipes using the API only, although it's not like what's requested in this issue because most of the major API methods and internals have changed over the year.

**Comment by superckl** [comment]
I'll see what the current status is soon and let you know.

**Comment by mezz** [comment]
The main advancement from today is `IRecipeRegistry.createRecipeLayoutDrawable`. You should be able to look things up with the recipe registry, then use that method to create drawable recipes.

**Comment by superckl** [comment]
There's still a few issues I'm having when trying to use only the API.
1. `IRecipeGuiLogic` isn't an API class. I could probably get around this by making my own `RecipeGuiLogic` class, but that seems unnecessary seeing as the most of the code is already there, just not completely API ready.
2. `IRecipeGuiLogic.getRecipeLayouts` returns a `List<RecipeLayout>`. If it were to move to the API, I imagine this could be modified to safely return `List<? extends IRecipeLayoutDrawable>`.
3. A way to use `IRecipeRegistry.createRecipeLayoutDrawable` with an already existing `IRecipeLayoutDrawable`
4. `RecipeTransferUtil.transferRecipe` requires a `RecipeLayout`, which makes sense, but I don't have an instance of that to use... Any ideas?

Thanks for all the work you've done so far!

**Comment by mezz** [comment]
For 1 and 2, I think you should implement your own kind of `RecipeGuiLogic`, this is not something I want to expose in the API because it will change over time. Your own logic can be much much simpler.

3. I do not understand. What would that be used for?

4. Right, `RecipeTransferUtil` is internal and there is no way to implement that from the API currently. I think you could leave that function out for now.

**Comment by superckl** [comment]
Item 3 would be fixed if I make my own `RecipeGuiLogic`. Will work on that now.
