### ISSUE TITLE
Inventory Give Mode Not Displaying Correct ItemStack Names In Chat/Log

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#1050]
**JEI Version:** [1.12.2-4.8.1.120](https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2502105)

Item stack's obtained via. `giveMode=inventory` do not display their name correctly in the game chat/log.
It behaves perfectly fine with `giveMode=mouse_pickup`, displaying the item's name; it is only `inventory` that is broken.

**Screenshot of issue:** 

![Screenshot of issue](https://i.imgur.com/i0CmJA2.png)

**Comment by mezz** [comment]
Thanks for the report!
Hm interesting, I actually uncovered a bug in Forge with this :)
I'll release a quick fix for JEI first.
