### ISSUE TITLE
[Suggestion] Use Hotkeys To Spawn To Hotbar Slots

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#1051]
Now with the new mouse item grabbing mechanic implemented, I'd like to propose another feature akin to vanilla's inventory management. It would be quite useful to allow the number keys to be pressed whilst mousing over an item in JEI (cheat mode) to quick spawn it to the respective hotbar slot (provided that the slot is empty)

**Comment by mezz** [comment]
That sounds nice, thanks for the suggestion.
