### ISSUE TITLE
[Suggestion] "Scroll" Stack Size Under Cursor

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#1052]
It would be neat if you could adjust the stack size of the currently picked up stack from JEI by rolling the mouses scroll wheel. This might be better as an implementation within Mouse Tweaks / Inventory Sorter etc, but it's up to you; just wanted to put it here in case you think it'd be useful to players who don't typically use such inventory mods.

**Comment by mezz** [comment]
I think this is a good request, I'll try it out.

**Comment by mezz** [comment]
The UI for this is pretty complicated in JEI, unfortunately.
Normally, scrolling on the ingredient list will go through the pages.
I think it should only work when holding an item and hovering over the same item in the list, but it's not really clear to the player  when scrolling the item will work.
This feature would be pretty hidden, and it seems like a lot of work to get it right, so I will not add it.

I agree it might be useful to have a more special-purpose mod that increases the count of the held stack by scrolling
