### ISSUE TITLE
[CTD][JEI 4.8.4.129] When trying to show block from 2 mods with similar name, OR(|) operator

### ISSUE THREAD

**Issue by drakray** [mezz/JustEnoughItems#1055]
JEI 4.8.4.129
Forge 2554
Minecraft 1.12.2
https://pastebin.com/3h64hhgG
CTD when trying to show stuff from Ex Nihilo Creatio and Ex Compressum, by typing
`@excomp|@exnihil`
crashed at the second @e
`S:filterText=@excomp|@` in worldSettings.cfg

**Comment by drakray** [comment]
Doesn't crash when rolled back to 4.8.3.128

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the next version.
