### ISSUE TITLE
Crash when using the OR in heavily modded private Pack

### ISSUE THREAD

**Issue by Zanges** [mezz/JustEnoughItems#1056]
I get the following Crash(In my Private & heavily modded Pack) when using the OR Operator.

Crash Log:
https://gist.github.com/zanges/d4915afe97c455a5769e47f6795d5447

In worldSettings:
S:filterText=@ae | 
OR
S:filterText=@ae|@

**Comment by TehNut** [comment]
Duplicate of #1055

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the next version.
