### ISSUE TITLE
[1.10.2] Crafting recipes changed with CraftTweaker not indicated

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1057]
I was playing a 1.12.2 modpack, and crafting recipes changed with CraftTweaker were indicated when hovering over the item in JEI, but this doesn’t happen in a 1.10.2 modpack that I’m now playing.

Is this indicator only a feature for the 1.12.2 version of JEI or CraftTweaker?

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm) ([version 1.4](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm/files/2499719))
**Minecraft version**: 1.10.2
**Forge version**:  12.18.3.2511
**Just Enough Items version**: 3.14.7.420
**CraftTweaker version**: 3.0.26

**Comment by mezz** [comment]
This indicator only exists in 1.12 because recipes use a registry in that version.
Unfortunately there is no way to know which mod added a recipe in earlier versions.

**Comment by ghost** [comment]
@mezz Aww, that’s a bummer.
