### ISSUE TITLE
Cannot find /give item commands option in the config

### ISSUE THREAD

**Issue by Benroyz** [mezz/JustEnoughItems#1058]
Hi, 

As the title stated, I can't find the option to change /give command. I need to change it to /give {5} {1} due to the fact that I'm forced to use item data, you know, /give Benroy 276 1.

I've explored through JEI folder in .minecraft/config

**Comment by TehNut** [comment]
What? I'm confused. JEI handles everything already.

**Comment by Benroyz** [comment]
I am talking about this: ![Commands](http://img.benroyz.com/12855cbe9e89b5.png)

If it exists already, then where are the settings?

**Comment by adrwa** [comment]
do you mean the thing labeled item which says /give in the box?

**Comment by Benroyz** [comment]
Yes.

**Comment by mezz** [comment]
There is no setting for this in JEI.
Your server plugins should respect the vanilla `give` command, there's really no good reason for them to change the format...

**Comment by Benroyz** [comment]
Ok, I understand. But it would be really nice to have this feature. I will have to get used to changing NEI and JEI when it comes to item spawning.

Thanks!
