### ISSUE TITLE
Sub-Items not showing in Item List (even in edit mode)

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#106]
Here you can see the search (or even without searching) yields only metadata 0, but my creative tab shows all 4 variants just fine:

![2016-01-12_12 04 12](https://cloud.githubusercontent.com/assets/3887324/12270630/029aff34-b925-11e5-8720-2c29a058206b.png)

Let me know if it's something on my end! It was working before the 2.16.1.77 update.

**Comment by mezz** [comment]
Yikes, that's a huge bug.

**Comment by mezz** [comment]
Fixed in 2.16.2
