### ISSUE TITLE
[Suggestion] Config enforcement

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1060]
Would it be possible to implement config enforcement; if someone connects to a server with this mod installed that the server configs dictate what the client configurations should be and enforce them?
For example; Forcing the item overlay off, so that users can only utilize the recipe/use function

**Comment by mezz** [comment]
Thanks for the suggestion!
That's not really something I have considered. Players would most likely just find a way around it, the items are always there on the client.

**Comment by ghost** [comment]
I did think about that, the most common way around it would be to install other mods that display the items. However, there are mods that will disconnect the player if X mod is detected to be installed on the client etc to help keep a fair playing field for those connected to a server.
Would be a handy feature to have. ^-^ Thanks for reading!
