### ISSUE TITLE
[1.10.2] Multiple items in the same slot

### ISSUE THREAD

**Issue by soyouzpanda** [mezz/JustEnoughItems#1061]
JEI : 3.14.7.420
Forge : 12.18.3.2488 [1.10.2]

When I see a craft, I see this : 
![2017-11-30_21 19 49](https://user-images.githubusercontent.com/23421201/33453210-221dc8dc-d615-11e7-9a44-4b42e0503beb.png)
![2017-11-30_21 19 53](https://user-images.githubusercontent.com/23421201/33453261-43522e6c-d615-11e7-8eef-87d785345c6a.png)

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/443
Basically, some other mod is changing the number of items in the recipe. 
JEI is displaying the recipe as it really is, but vanilla crafting only takes the first item into consideration.
Please report this to the mod that has the broken recipes.

**Comment by soyouzpanda** [comment]
[info] This bug is caused by Aether II
