### ISSUE TITLE
[1.12] Scrolling recipes in JEI while in inventory moves items with Mouse Tweaks between inventories.

### ISSUE THREAD

**Issue by FoxAhead** [mezz/JustEnoughItems#1063]
There is cross-mod issue between JEI and Mouse Tweaks.
Reported issue to Mouse Tweaks developer here:
https://bitbucket.org/YaLTeR/mouse-tweaks/issues/14/scrolling-in-jei-while-in-inventory-moves

So I just rechecked in fresh install in MultiMC. Configuration:
Minecraft 1.12.2
Forge 14.23.1.2555
jei_1.12.2-4.8.4.131.jar
MouseTweaks-2.8-mc1.12.1.jar

The problem:
"if you open chest and then start inspecting some recipes in JEI without closing chest and scrolling recipes with mouse wheel then if mouse pointer is above place on the screen where items in chest are then that items are handled by Mouse Tweaks despite you don't see chest's inventory right now."

Answer from Mouse Tweaks dev:
"Huh, that's really odd. Without looking into it, I would say it's JEI's bug (using some weird way of showing its interface which doesn't actually make it the current GUI screen), but I can't say for sure right away."

Could you collaborate and fix that bug?

**Comment by mezz** [comment]
Thanks for the report!
I think they have a good point, I'll look into it.

**Comment by mezz** [comment]
Hm it looks like I'm already handling JEI's recipe gui as a normal GuiScreen, I'll contact them to see what the issue might be.

**Comment by codewarrior0** [comment]
On a related note, Modular Machinery wants to respond to mousewheel events in the recipe GUI window by scrolling a 3D structure preview - but without any help from JEI, it has to resort to reflecting into the Mouse class and tricking JEI into thinking no mousewheel event has happened.

**Comment by mezz** [comment]
I'm working with Mouse Tweaks on a solution here: https://github.com/YaLTeR/MouseTweaks/pull/20

**Comment by mezz** [comment]
This has been fixed in Mouse Tweaks.
