### ISSUE TITLE
JEI not showing up on server side

### ISSUE THREAD

**Issue by Renadarain** [mezz/JustEnoughItems#1064]
Hi :)

For some weird reason jei items are not showing on the right hand side of the inventory when logging onto a dedicated server but DO show on a localhost server.

MC: 1.12.2
Forge: forge-1.12.2-14.23.1.2559-universal
JEI: jei_1.12.2-4.8.4.131

I've tried this with all my mods installed and I've tried it with JEI on it's own, with a texture pack and without - it just makes no sense to me that it would work on a local server but not a dedicated one. (it always has done up until 1.12.1).

Please save my losing any more of my hair :( Uploaded two screenshots - one for localhost and one for dedicated).

![with-jei](https://user-images.githubusercontent.com/3536320/33530130-898e66f2-d872-11e7-8e70-74aec16c7a3c.png)
![no-jei](https://user-images.githubusercontent.com/3536320/33530132-8f7e8fba-d872-11e7-91a1-0f48e76f1c3b.png)

Regards,
Renada

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by Renadarain** [comment]
Latest client log for Mezz

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Latest client log for Mezz
 Latest client log for Mezz  |   |

  |

  |

 

Thanks for looking at this

**Comment by mezz** [comment]
@Renadarain it looks like your link did not work for some reason, I do not see your link to https://gist.github.com

**Comment by ChloeDawn** [comment]
I don't know what you did exactly when you tried to send the logs via email, but they weren't received correctly...

**Comment by Renadarain** [comment]
Sorry, I'll try again 

Latest client log for Mezz

https://pastebin.com/jJUkrBaj

https://gist.github.com/Renadarain/3eadcb48d488987d006c1080165f743e


Apparently it doesn't like email links :)

**Comment by mezz** [comment]
Thanks for the log.
Everything looks fine in the log, maybe you have JEI disabled accidentally by pressing Control-O ?
Try that hotkey to bring JEI back, and if it doesn't work then try deleting your JEI config folder.

**Comment by Renadarain** [comment]
Oh gosh what a numpty!! lol 
Thanks Mezz, it was the CTRL-O and my hair is now safe from destruction.

Just curious, using the same config files for both the localhost server and my dedicated server, why would it show up on one and not the other?

Thanks again. :)
Kind regards,
Renada

**Comment by mezz** [comment]
If you look in `/config/jei/worldSettings.cfg` you will see that there are separate values for each world. Certain config values like the filter text and whether JEI is open are stored there.
Glad that was the only issue!
