### ISSUE TITLE
After update, Item Hiding Mode not working with mouse clicks

### ISSUE THREAD

**Issue by KAfable** [mezz/JustEnoughItems#1066]
After updating to 4.8.5.132 (where the additional configs was added to give items either in inventory or mouse-click), using ctrl+click/rightclick or ctrl+shift+click only gives the items, and doesn't actually hide the items ingame anymore. This is also with Cheating Enabled, it works if I turn off Cheating Enabled, but before the item hiding would override the cheating and just hide the items.

Forge ver: 2556

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the next version.
