### ISSUE TITLE
Missing one item in player inventory shows all as missing on transfer button

### ISSUE THREAD

**Issue by GoryMoon** [mezz/JustEnoughItems#1069]
When looking at a recipe while being in the player inventory and missing one item for that recipe all items that has the exact amount required show as missing when holding over the transfer button.

As an example in this image I have a piece of coal in the inventory: 
![Example of Bug](https://i.imgur.com/Lq7C8gz.png)
The is caused by this row, the available items are decreased from the previous check and therefor not being valid in this one; https://github.com/mezz/JustEnoughItems/blob/9a024e25c6415279399748a68b6ff49644344173/src/main/java/mezz/jei/transfer/PlayerRecipeTransferHandler.java#L145

**Comment by mezz** [comment]
Thanks for the report!
Confirmed.

**Comment by mezz** [comment]
This bug has been fixed in 1.18
