### ISSUE TITLE
Damage Bar Render Issue in Item List

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#107]
I can't tell if this is BuildCraft or JEI, but since I've updated JEI and have not updated BuildCraft, my guess is that it's JEI. The rendering for the Gate Copier's damage bar shows as empty on one side... but on the other (til the end of my screen) is a rendering of a green damage bar.

![2016-01-12_19 05 42](https://cloud.githubusercontent.com/assets/3887324/12280905/a60a776e-b95f-11e5-9b4b-1c56477caa11.png)

Not at all a big deal - I never use it so I've just got it blacklisted for now :)

Note: On version 2.16.2.78

**Comment by TehNut** [comment]
A recent JEI version fixed a bug where damage bars weren't rendering. This could possibly be a BC issue that just wasn't seen until JEI started displaying it.

**Comment by oitsjustjose** [comment]
I'm on that version, actually. Forgot to mention that ;D

As far as who's to blame, I don't know. Seems weird it's just this one item that has the issue..

**Comment by GirafiStudios** [comment]
I can confirm, I get the same issue with the latest JEI.

**Comment by mezz** [comment]
This is certainly a BC issue. Here's what it looks like with the previous version, `buildcraft-7.2.0pre5`
![2016-01-12_16 21 32](https://cloud.githubusercontent.com/assets/916092/12281172/af81ad60-b948-11e5-871c-4677d2a34036.png)

**Comment by TehNut** [comment]
@oitsjustjose I know you're on that version. I wasn't saying that that fixed it. I'm saying that that caused the bars to start rendering. The issue is most likely BC.

**Comment by mezz** [comment]
I tried out BC pre6 but it looks the same as my screenshot above. 
Either way, durability of -32k is weird, please report the issue to buildcraft.

**Comment by GirafiStudios** [comment]
Actually it seems like it have nothing to do with the gate copier, but something else on the page.
Searching for gate copier:
https://gyazo.com/79880c6da83b92d96442f257b7213082

Scrolling through JEI:
https://gyazo.com/fd50a0f4a32c08bd5ec0e39c6b68336d

**Comment by mezz** [comment]
Oh, good find. can you try to narrow it down? I wasn't able to see the issue on my setup. 
JEI can search for multiple things if you do something like "gate copier|blood", that might help.

**Comment by oitsjustjose** [comment]
I'll try to narrow it down later if no one else has.

**Comment by GirafiStudios** [comment]
Found it: https://gyazo.com/70834e9fccddbcd99087006ce17bc6fa

**Comment by mezz** [comment]
Hey @williewillus, the Gaia Guardian Head probably does something weird to the OpenGL state, causing this unusual bug.

**Comment by oitsjustjose** [comment]
So now the question is: is it Botania or BC or JEI? I still feel like that damage value added to the creative menu list is way too weird.

**Comment by mezz** [comment]
To see if JEI has anything to do with it, put both items into your inventory and see if it still happens.
To see if BC is involved, try another damageable item after the Gaia Guardian Head.

**Comment by GirafiStudios** [comment]
Another item after the Gaia Guardian Head:
https://gyazo.com/460b9396cc8430281b60d9ce716f0b4a
I can't actually get the Gate Copier in my inventory without it having full durability.
But if the Gaia Guardian Head is in my inventory and the Gate Copier is in JEI, it still happens.

**Comment by mezz** [comment]
It's probably a combination of both BC and Botania.
Gaia Guardian Head does something weird to OpenGL, and BC Gate Copier in JEI has -32k damage (and magically fixes itself when spawned, wtf).

**Comment by williewillus** [comment]
Gaia Guardian head is using the TESR item hook, invoking the vanilla head renderer with a shader on top. The shader is released immediately after rendering.

I'll check it out in a little bit.

If it doesn't work out, I'll fall back to the old head texture (not TESR)

**Comment by williewillus** [comment]
Update: Yea, not sure what's happening on my end. Botania hooks the skull TESR, and uses it to apply a shader. The rest of the code matches vanilla.

For references: https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/client/render/tile/RenderTileSkullOverride.java

**Comment by mezz** [comment]
You don't undo your `GlStateManager.disableCull();`? Maybe culling is what keeps minecraft from drawing the -32k damage.

**Comment by williewillus** [comment]
The superclass tesr doesn't, either. So theoretically the issue would occur with any vanilla head

**Comment by mezz** [comment]
Tested and vanilla heads don't mess it up.  Let's just agree that the Buildcraft gate copier should not have that damage value and call it a day lol

**Comment by AEnterprise** [comment]
reported the extreme negative damage value

**Comment by AlexIIL** [comment]
What? The gate copier only uses meta values of 0 and 1...

**Comment by AlexIIL** [comment]
I will note that it is _metadata_ of 0 and 1 rather than a normal damage value, so shorts might not be handled correctly

**Comment by mezz** [comment]
Ok then the gate copier damage is a JEI bug after all, with a mistake handling the difference of meta and damage. Looking in the creative menu, the gate copier is correct. Thanks @AlexIIL
