### ISSUE TITLE
The server must have JEI installed appearing on move items button

### ISSUE THREAD

**Issue by TwistedAro** [mezz/JustEnoughItems#1074]
I have installed JEI on both my server and on my client but the move items [+] button that auto fills the crafting grid still reports this error message and remains greyed out.

Thanks in advance for any possible solutions.

![jei must be installed on the server](https://user-images.githubusercontent.com/34603007/34071715-6f750d3e-e272-11e7-82fa-897d8668a0e2.png)

**Comment by HorizonsMC** [comment]
Getting the same problem, did you find why?

**Comment by Mohron** [comment]
Same problem here with matching server and client versions.

**Comment by TwistedAro** [comment]
I just deleted it and reinstalled and the problem was fixed.

**Comment by Blazemakara** [comment]
I am having the same issue has anyone found a proper fix?
