### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by MakerTim** [mezz/JustEnoughItems#1078]
Someone tried to craft a piston with auto fill-in while someone was joining in the same chunks, dont know if that is related to something; but it is an java.lang.Error so something went really bad

https://pastebin.com/4dYvJjew

*sorry if im wrong to report it here; but jei is the last stacktracing of most steps

**Comment by mezz** [comment]
Thanks for the report!
I don't think this is a JEI issue, sorry. The way it crashed is very strange, I think there may be an issue somewhere else but I am not able to determine what it is from the crash log.

**Comment by MakerTim** [comment]
Can't reproduce since i updated forge; so calling it closed for now
*the odd thing is, it did happend by crafting pistons; even with fewer mods (and only vanilla materials)
