### ISSUE TITLE
[1.12.2] Give Mode Iinventory setting not working

### ISSUE THREAD

**Issue by Andronomos** [mezz/JustEnoughItems#1079]
After changing the give mode setting to inventory, items can no longer be grabbed. Clicking an item does nothing.

**Comment by lag42** [comment]
i have this issue too and it is really frustrating

**Comment by lag42** [comment]
fixed in alpha, but not release version

**Comment by mezz** [comment]
Thanks for the report!
This is fixed, and a duplicate of https://github.com/mezz/JustEnoughItems/issues/1077
I will mark the latest version as a release.
