### ISSUE TITLE
log spam from bc + jei

### ISSUE THREAD

**Issue by kurokuno** [mezz/JustEnoughItems#108]
http://pastebin.com/Fup8tNf9 this is most of the error i think its rather hard to just pull out 1 copy of it as its constant log spam 34 meg log in just under 6 mins of playing

**Comment by mezz** [comment]
Thanks for the report!
Please report to BuildCraft, it looks like their item rendering is broken.

I will see about reducing the log spam from broken items so that JEI is not just repeating the same issue over and over.

**Comment by wlhlm** [comment]
Please report to https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues

**Comment by mezz** [comment]
Looks like the log only happens once per item when JEI is loaded, it's just an incredible number of broken facades.

**Comment by mezz** [comment]
Reported to Buildcraft.
