### ISSUE TITLE
cheat mode refuses to give items in any screen other than the creative inventory

### ISSUE THREAD

**Issue by lag42** [mezz/JustEnoughItems#1080]
using release version cheat mode with cursor works fine in the creative inventory that you get by pressing e while in creative mode but clicking on an item with a different gui open does nothing

**Comment by mezz** [comment]
Thanks for the report!
This is fixed, and a duplicate of https://github.com/mezz/JustEnoughItems/issues/1077
I will mark the latest version as a release.
