### ISSUE TITLE
[suggestion] A Different hiding option

### ISSUE THREAD

**Issue by ThatGravyBoat** [mezz/JustEnoughItems#1081]
A hiding option where it hides stuff in the jei main page but when you search up that mod or that item it will show them blocks/items.

Thanks for reading 
-ThatGravyboat

**Comment by mezz** [comment]
Thanks for the suggestion but I don't think I will implement this. There are not many cases where you want to scroll through the ingredient list without a search filter, so I do not think this feature would used much, and it adds more complexity.
