### ISSUE TITLE
Unable to Use the Move Items Button - The server must have JEI installed (It is installed)

### ISSUE THREAD

**Issue by HorizonsMC** [mezz/JustEnoughItems#1083]
Getting an issue where I can not use the move items button to craft anything on a server that is running the latest version of JEI on 1.12.2. Any idea why? The mod is loading in the log and I have mods that are dependent on JEI so it has be loading.

https://i.imgur.com/Yt1C0qA.png

Edit: Here is the entire loading log (Yes I already tried removing SpongeForge and that wasn't the problem)

http://www.mediafire.com/file/6iyisae84c0011u/fml-junk-earlystartup.log

Also I noticed it does not generate any config files on the server if it is supposed to be doing that.

**Comment by Mohron** [comment]
Same issue using 1.12.2-4.8.5.132 on both client and server.

**Comment by HorizonsMC** [comment]
If anyone else has the same issue update DiscordSuite to 1.1.4, versions before this are causing the JEI button to break.

**Comment by Mohron** [comment]
How does that even happen...

**Comment by mezz** [comment]
Thanks for the report!
Try updating to JEI 4.8.5.138, there was an issue with packets and Forge in previous versions.

**Comment by HorizonsMC** [comment]
I was using 138 already, it's likely caused by the other mod not JEI. The dev disabled Multiplayer features till he can rewrite the code.

**Comment by mezz** [comment]
Ok, thanks for the info.
