### ISSUE TITLE
[1.12] Server crash crafting

### ISSUE THREAD

**Issue by MakerTim** [mezz/JustEnoughItems#1086]
Okay, so when you Shift Click the crafting in a Tinkers Crafting Table, and it needs items from the Tinkers Crafting Table next to it, this happens...

https://pastebin.com/0tSRt1ry
Server crash :s 

Dont know if it is tinkers or you, but the stack-tracing seems to lead to JEI

**Comment by TimGoll** [comment]
Same for me, but without a crashlog. "Autocrafting" is impossible
I think it is JEI. Because it happens after a JEI update

**Comment by mezz** [comment]
Thanks for the report!
I think JEI is hanging for a long time there, probably stuck in an infinite loop.

**Comment by TimGoll** [comment]
That might be true. Because the server does not crash and the players get a timeout exception

**Comment by MakerTim** [comment]
Server does crash, after 2minutes with the `hey im to long in one tick` msg

**Comment by Keaton1188** [comment]
Also having this issue.

**Comment by ALongStringOfNumbers** [comment]
To temporarily solve this, you can blacklist the tinkers construct crafting table in the Tinker construct config as an item that other Tinkers construct crafting tables can connect to.

**Comment by Ommina** [comment]
I'm not sure if there are two distinct issues being discussed here or not, but the infinite loop thing sounds an awful lot like https://github.com/SlimeKnights/TinkersConstruct/issues/3322 -- do those affected have multiple crafting stations?

**Comment by Andronomos** [comment]
This seems to be the same problem I am having in single player. Whenever I try to craft a coal block using JEI and a Tinker's Contruct crafting table, I lose the ability to interact with blocks in the world such as chests or machines. If I attempt to close the world, the client locks up indefinitely till I end the process in task manager.

I don't know if this is a bug with JEI or Tinker's Construct.

**JEI version:** 1.12.2-4.8.5.159
**Tinker's Construct version:** 1.12.2-2.9.1.65
**Installed mods:** https://pastebin.com/tg5fjq90

**Comment by Bucky420** [comment]
[crash-2018-11-28_15.07.49-server.txt](https://github.com/mezz/JustEnoughItems/files/2625494/crash-2018-11-28_15.07.49-server.txt)
when will thsi get fixed been a hole year ...

**Comment by mezz** [comment]
I think this old bug turned out to be a Tinker's construct bug, fixed: https://github.com/SlimeKnights/TinkersConstruct/issues/3322
