### ISSUE TITLE
highlight items in Inventorys doesn't work

### ISSUE THREAD

**Issue by Bircko** [mezz/JustEnoughItems#1088]
if i use search feature for inventorys it just highlight every inventory slot that isn't empty no matter what i search
Version: jei_1.12.2-4.8.5.138

![2017-12-22_21 13 27](https://user-images.githubusercontent.com/29576723/34311395-c68ac722-e75d-11e7-97a6-57626c531add.png)
![2017-12-22_21 19 28](https://user-images.githubusercontent.com/29576723/34311409-d3900572-e75d-11e7-9c80-4fa50d37f646.png)

**Comment by KnightMiner** [comment]
That is not a JEI feature, it is from an add-on (probably NEI)

**Comment by OrdinatorStouff** [comment]
It's from More Overlays:
https://github.com/feldim2425/MoreOverlays/issues/41
