### ISSUE TITLE
question: is there a server-side option to disable cheat mode on client

### ISSUE THREAD

**Issue by smmmadden** [mezz/JustEnoughItems#1094]
I just recently downloaded jei_1.12.2-4.8.5.138.jar and love what it can do.  Once I figured out what a "spanner" is, I was able to turn on the cheat mode to my test server.  I am an op as well, but my question is this.  If I create a modpack with this mod in it for my users who will not be OP'd, will they be able to enable cheats to my server?  If yes, is there a way to restrict it by permissions (allow some, not all)?

Thanks - and excellent work making finding blocks so much easier and their recipes. :-)
-Steve

**Comment by TehNut** [comment]
They can only use cheat mode if they can use `/give`.

**Comment by smmmadden** [comment]
excellent - then I should be good to go since it's covered under perms.  Thanks!
