### ISSUE TITLE
API Request: Add way to show all subtypes for items that have big amount of subtypes

### ISSUE THREAD

**Issue by Exidex** [mezz/JustEnoughItems#1095]
In the process of development we noticed that JEI doesn't show items that have more than 300 subtypes. In our mod we have item that has ~28 000 (yeah, a lot) subtypes but every subtype is basically a different item and we want to see it in JEI.

Currently there is way to set max amount of subtypes via config but the max is 10000 and you need to edit the config. 

So I wanted request way to disable this for certian items via ISubtypeRegistry. This is probably won't be needed in 1.13 but still. 

Thanks for your time

**Comment by mezz** [comment]
I have a hard time imagining why you would have 28,000 subtypes on a single item.
Why not break it into multiple items?

**Comment by mezz** [comment]
This shouldn't be stale, I still need to test some better solutions for this.

**Comment by jredfox** [comment]
Well this needs to get fixed my mod in the future is going to add 300+ spawners to the creative tab.

You can simply do block.getsubtypes() I believe and it returns and array from there you can add it to the jei tab. And if count is so many high maybe you could add a subset for it or something if your worried about that stuff.

**Comment by mezz** [comment]
I have removed the subtypes restriction in the next version. I think the issues from JEI slowdowns are less than the issues caused by this restriction.

**Comment by jredfox** [comment]
yeah and for the sub types that add like 28k they could simply blacklist the item example buildcraft
