### ISSUE TITLE
search box text should be cleared on closing of inventory

### ISSUE THREAD

**Issue by smmmadden** [mezz/JustEnoughItems#1096]
JEI build: 1.12.2-4.8.5.138
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-0c11218
SpongeForge: 1.12.2-2555-7.0.0-BETA-2758
Minecraft Forge: 14.23.1.2555

When a player uses the search field in the lower right corner of the screen and types in say "sign", the sign appears fine and all is working as it should.  However, if the player presses ESC or hit's E to close the inventory, the search still holds the value for the last searched word.  This can lead to confusion (at least for me being new to using it) thinking that I must have done something wrong because there is nothing in the inventory showing.  So the player has to remember to clear the search box each time they use it.
![image](https://user-images.githubusercontent.com/10309346/34459128-7d9a77ee-edb4-11e7-85c6-a419e82da094.png)

**Comment by TehNut** [comment]
No, it shouldn't. This is how item searching has functioned for *years*. As an opt-in config? Maybe. But definitely not by default.

**Comment by smmmadden** [comment]
at least with the vanilla inventory searches, you leave the screen it clears out the search value for the next time you go back in.  Having an option to reset the search box after leaving it would be better IMO since it takes more time, keystrokes to remove it than it does for a natural reset.  Goes towards usability even if it has been this way for years. :-)

**Comment by Ommina** [comment]
Except for me, at least, it is a dramatic step backwards in usability.

If a particular item has some number of sub-crafting steps associated with it, and some or any sub-step involves leaving JEI to craft it up, the last thing I want to do is retype the same thing each and every time until I finally make it to the end product.  I'd go mad.  Mad!

**Comment by mezz** [comment]
Sorry but it seems like changing this would really annoy just about everyone.
You can right click the search box to clear it.

**Comment by smmmadden** [comment]
The right click is a good workaround for this.  Thanks!
