### ISSUE TITLE
Cheat mode doesn't give items, only recipes

### ISSUE THREAD

**Issue by ranman00** [mezz/JustEnoughItems#1097]
I've tried re-installing newer versions and deleting NEI. As well as editing the config files and allowing cheats, however I'm still unable to retrieve items I click on in the menu and even cheat mode is enabled in the inventory options. Side note, gamemodes don't appear or aren't able to be turned on as well as inventory presets/saves.

**Comment by mezz** [comment]
Thanks for the report!
JEI doesn't have game modes controls or inventory presets and saves.
Please show a screenshot.
