### ISSUE TITLE
Just walking and crash... 

### ISSUE THREAD

**Issue by Toapoint** [mezz/JustEnoughItems#1098]
Ever since I right clicked dirt in the JEI GUI, I get this error CONSTANTLY... It crashes my game. 

https://pastebin.com/Zr0uPu68

**Comment by mezz** [comment]
Thanks for the report!
```
-- Item being rendered --
Details:
    Item Type: com.rwtema.extrautils2.backend.XUItemBlock@39b901b6
    Item Aux: 0
    Item NBT: null
    Item Foil: false
```
This seems to be a crash from extra utilities 2. Try removing the mod and see if that fixes the issue.
