### ISSUE TITLE
temp hiding JEI in a gui

### ISSUE THREAD

**Issue by AEnterprise** [mezz/JustEnoughItems#110]
could something be added to hide JEI item panel with a key or so like NEI had? some gui's display additional things next to the gui itself. an example is the interface for the BC gates, those display all possible trigers and actions next to the gui and you can drag 'n drop them to program the gate.

currently JEI renders over the actions part and catches clicks so it can't be used

**Comment by LuigiHutch** [comment]
Use Control O

**Comment by AEnterprise** [comment]
oh you have to press control as well, thanks
