### ISSUE TITLE
craft

### ISSUE THREAD

**Issue by demon57730** [mezz/JustEnoughItems#1100]
jei_1.11.2-4.5.1.296.jar

not compatible

forge 1.11.2 - 13.20.1.2579

	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	UCHIJA	crafttweakerjei{1.0.2} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.26.jar) 
	UCHIJE	jei{4.5.1.296} [Just Enough Items] (jei_1.11.2-4.5.1.296.jar) 
	UCHIJA	crafttweaker{3.0.26} [Crafttweaker] (CraftTweaker-1.11.2-3.0.26.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.26.jar) 

[14:53:44] [Client thread/INFO]: [STDOUT]: Loaded class registry: JEI mod support

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by demon57730** [comment]
this good actually in the log he had no error except what I gave but I find these a mod that fesais crash jei

the mod :   Immersive Engineering

**Comment by mezz** [comment]
I still need the log please.
