### ISSUE TITLE
[Suggestion/Enhancement] Option for the green recipe book button from Vanilla to open/close JEI instead

### ISSUE THREAD

**Issue by Luke616** [mezz/JustEnoughItems#1104]
In a typical modded environment, JEI completely outclasses the vanilla system in every way. I see no reason to have both recipe-lookup systems on my inventory screen at the same time, why not just have the button open & close JEI instead?

Thanks for your consideration.

**Comment by Guinaro** [comment]
Currently I'm using No Recipe Book, but if I could remove a mod in my load order in favor of a config tweak like this. +1 from me.

Options: Keep Minecraft Recipe Book; Show/hide JEI with Opening of Clicking on Recipe Book; Remove Recipe Book Icon and have JEI open by default.

Guinaro

**Comment by mezz** [comment]
Thanks for the suggestion!
Sorry this is out of scope for JEI. Several other mods can disable the recipe book and I don't see a need to put it into JEI directly.
