### ISSUE TITLE
game crash- multiple issues- just question

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1106]
I'm having an issue with forge 1.11.2 related worlds not being able to connect to the lan game.
In my game launcher log I am seeing this repeatedly for any mod that adds any blocks:

03:43:47 | game | [10:43:46] [Client thread/ERROR] [jei]: Recipe has too many inputs. net.minecraft.item.crafting.ShapedRecipes@2d83ea1b
-- | -- | --

I don't get the error on other machines, but I do on this one. can anyone give me any details that might help me solve this?

The mods folder has:
Custom NPC
Multihotbar
multipage chest
notes
RoguelikeDungeons
TombManyGraves
VarriedCommodities

Thanks for any info.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by ghost** [comment]
I found the mod that was causing the problem. Tried to upgrade to forge 1.12 and that cause a whole other set of issues! This all started after the last Minecraft update. Thanks though!
