### ISSUE TITLE
Stacks with NBT aren't cycled in recipes

### ISSUE THREAD

**Issue by ChiriVulpes** [mezz/JustEnoughItems#1107]
```java
public class IngredientPotentialEssence extends Ingredient {

	public static IngredientPotentialEssence INSTANCE = new IngredientPotentialEssence();

	public static ItemStack[] generateMatchingStacks() {
		List<ItemStack> stacks = new ArrayList<>();
		stacks.add(ItemStack.EMPTY);
		stacks.add(ModItems.ASH.getItemStack());
		for (EssenceConfig essenceConfig : Soulus.config.essences) {
			stacks.add(Essence.getStack(essenceConfig.essence));
		}
		return stacks.toArray(new ItemStack[0]);
	}

	public IngredientPotentialEssence() {
		super(generateMatchingStacks());
	}

	@Override
	public boolean apply(ItemStack input) {
		return input == null || input.isEmpty() || input.getItem() == ModItems.ESSENCE
				|| input.getItem() == ModItems.ASH;
	}

	@Override
	public boolean isSimple() {
		return false;
	}

	public static class Factory implements IIngredientFactory {
		@Override
		public Ingredient parse(JsonContext context, JsonObject json) {
			return new IngredientPotentialEssence();
		}
	}
}
```

This is my ingredient implementation. It passes to the Ingredient superclass the stacks which it should match, but the recipes I've created that use this ingredient, when shown via JEI, do not cycle through the possible stacks which are the same item and but have unique NBT. Is there a way I can support seeing these other stacks, or is that a limitation of JEI? If it's a limitation, would it be a possible future feature?

**Comment by TehNut** [comment]
Did you register your subtypes with JEI? By default it ignores NBT.

**Comment by ChiriVulpes** [comment]
So if I register the stacks with the unique NBTs, and then add them to the ingredient blacklist, it won't show up on the side but it will cycle through them in the recipe? (that's what I expected to happen by default, but it makes sense, that way for most recipes/ingredients/whatever it's unnecessary to touch the NBT, I assume?)

**Comment by ChiriVulpes** [comment]
Nvm, I should have looked at the actual subtype api before commenting again hah. Thanks for your help!
