### ISSUE TITLE
Get an error when trying to run the mod

### ISSUE THREAD

**Issue by redpanda212** [mezz/JustEnoughItems#1108]
I keep getting this error when i boot up minecraft I have the current version of FML
I have got the same error with other mods and have reported them there

![image](https://user-images.githubusercontent.com/35348344/34845761-9ed79970-f6db-11e7-902c-5e6497ab5ab2.png)

[fml-client-latest.log](https://github.com/mezz/JustEnoughItems/files/1624017/fml-client-latest.log)

**Comment by Ommina** [comment]
You do not, despite what you believe, have the current version of Forge.  You are using a version from mid-September.

If you _have_ downloaded the new version of Forge, then I can only speculate that it has been placed in the wrong folder, or something similar.  With that, I can't help.

**Comment by smmmadden** [comment]
@Ommina is correct - just look at the first 2 lines of your log to see what version you are on.
[14:23:02] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
**[14:23:02] [main/INFO] [FML/]: Forge Mod Loader version 14.23.0.2486 for Minecraft 1.12.2 loading**
[14:23:02] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25

You are also using a very old version of the JVM.  1.8.0_152 is the latest in the 1.8 series so from a security perspective, you should also update the JVM.
