### ISSUE TITLE
JEI is not reading actual item name after resource reload

### ISSUE THREAD

**Issue by labpaw** [mezz/JustEnoughItems#1109]
I discovered this while translating Forestry and I have clear guide how to reproduce this with minimal mod setup (I'm 99% sure this should be same with only Forge and JEI). It affects vanilla items too.

How to reproduce:
1) Start game go into the world, change language to any from English (supported by Forestry)
2) Shut down game, start again, change language back to English (before going into the world) and go into the world.
3) Type "mead" for example in JEI search and you'll find only meadows hive
4) Try type mead in language you used in past (if it's Russian it is "мёд") (which I used in test)
5) You will find mead-related stuff actually in English but you can't search for them in English (The actual names are in English but you only can find them using Russian translated string)
6) Shut down game, start and go into the world. Type mead and everything settled.
As I originally wanted to report it to Forestry I used Forestry items.

Using vanilla items:

1. Start game go into the world, change language to any from English (In my example Russian)
2) Shut down game, start again, change language back to English (before going into the world) and go into the world.
3) Type "Stone" for example in JEI search and you'll find nothing
4) Try type stone in language you used in past (if it's Russian it is "Камень") (You can just copy it from here)
5) You will find stone-related stuff actually in English but you can't search for them in English (The actual names are in English but you only can find them using Russian translated string)
6) Shut down game, start and go into the world. Type Stone and everything settled.

It also affects Tcon so I guess it affects everything, search in creative tab working as intended.
Forge used: 2587, java 8 u151
Mods used: https://i.imgur.com/rxp6dWG.png

**Comment by mezz** [comment]
Thanks for the report!
JEI has handling for this case, it must have been broken some time recently.

**Comment by mezz** [comment]
Is this fixed in the latest version of JEI? There were some cases where it would not reload properly, like when you changed the language from the main menu, and that should be fixed now.
