### ISSUE TITLE
Search bar alignment config

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#111]
To align the search bar in the centre, or further right like it is now.

**Comment by oitsjustjose** [comment]
I agree with this - as someone with an Ultrawide monitor, something being right justified means it's a _lot_ further right for me than most.

**Comment by mezz** [comment]
Since it will probably be a while before I implement this, just want to get the word out that "Control-F" will select the search bar.

**Comment by Prospector** [comment]
~~Hmm what if there was also an option to have JEI on the left side? It might be pointless but I mean it doesn't sound too hard to implement.~~

**Comment by mezz** [comment]
Why add complexity and support an option that nobody will use?

**Comment by Prospector** [comment]
That is true. I don't know why I thought that might be a good idea
