### ISSUE TITLE
crash when trying to display JEI menu

### ISSUE THREAD

**Issue by 0Navis0** [mezz/JustEnoughItems#1110]
I get this crash when trying to display JEI menu, it seems something goes wrong with CodeChickenLib. https://pastebin.com/CC9eaDS7

**Comment by KnightMiner** [comment]
This is an issue with the JEI add-on NEI, report it to that mods tracker.

**Comment by mezz** [comment]
Please report the issue here: https://github.com/TheCBProject/NotEnoughItems/issues
