### ISSUE TITLE
Menu for JEI missing when I open inventory

### ISSUE THREAD

**Issue by Jatomic77** [mezz/JustEnoughItems#1111]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.
![base profile screenshot 2018 01 19 - 21 08 07 86](https://user-images.githubusercontent.com/35620315/35180117-bcfdba6e-fd5d-11e7-988b-23075278c436.png)

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.
