### ISSUE TITLE
Changelog for 4.8.5.147 appears to read wrong?

### ISSUE THREAD

**Issue by BryanBoru** [mezz/JustEnoughItems#1114]
[Changelog on CurseForge](https://minecraft.curseforge.com/projects/jei/files/2522813) mentions update to Forge V14.23.1.2574, but upon installation, the game calls for 14.23.1..2594 citing JEI as requesting it.

>[10:49:36] [main/FATAL] [FML]: The mod jei (Just Enough Items) requires mod versions [forge@[14.23.1.2594,)] to be available

**Comment by mezz** [comment]
The changelog is automatically generated from commits.
The latest commit at the top `Use latest Forge ...` has updated Forge again to `14.23.1.2594`.
