### ISSUE TITLE
[1.10-1.11] Recipes are not removing / adding correctly

### ISSUE THREAD

**Issue by CJMinecraft01** [mezz/JustEnoughItems#1115]
So I have recently been using MineTweaker to adjust some recipes for a particular mod. And I know you said that if there is an issue, to report it to them and I did. They did some searching and the error only occurs on 1.10-1.11 versions of their mod. The issue is as follows:

For the NuclearCraft mod, I am trying to remove the recipes for graphite dust but unfortunately they do not get removed from JEI. They are however removed from the machine (as I can no longer get graphite dust from the machine). Every time I reloaded MineTweaker using `/mt reload` it added all of the graphite recipes again to JEI instead of removing them. I tried to reload the game and when I looked in JEI, the recipes were still there (although they were removed from the machine).

Now from the mod author's own investigations, this does not occur in the 1.12 version (due to the change in recipes (as they now take `.json` instead of `GameRegistry.addRecipe`)). I'm not sure if there is a way this can be fixed, but if so, that would be amazing. 

I'll put a link to the issue I posted here: https://github.com/turbodiesel4598/NuclearCraft/issues/222

Thanks in advance :+1:

**Comment by CJMinecraft01** [comment]
Yes this is still an issue, at the moment it hasn't effected me a lot however I think it's something which should get fixed. It's probably something simple but I'll continue to look into it.

**Comment by mezz** [comment]
Have you reported this to MineTweaker? It has had some issues with JEI in the past, most of that is worked out in 1.12 but unfortunately there may be some issues in older versions that require more fixes.

**Comment by CJMinecraft01** [comment]
That's an excellent idea. I'll ask over there and I'll keep you informed
