### ISSUE TITLE
FTBPresentsDirewolf20 Crashing

### ISSUE THREAD

**Issue by JosephHaykal** [mezz/JustEnoughItems#1116]
Hey I just updated my modpack on FTB launcher and whenever i try to launch it it crashes on the loading screen. Here is the crash report:
http://paste.feed-the-beast.com/view/e45439f5

**Comment by mezz** [comment]
Thanks for the report!
This is not related to JEI. Please report it to the pack here: 
https://forum.feed-the-beast.com/forum/ftb-presents-direwolf20-1-12.272/
