### ISSUE TITLE
Items disappear when using recipe add feature

### ISSUE THREAD

**Issue by Elite82pt** [mezz/JustEnoughItems#1117]
Greetings!!
I'm running a FTB revelation 1.4.0 server. And my community is having this issue: 
Issue in multiplayer - pick the item from JEI, press the plus button (move items) in the crafting window. items move to crafting table. pick the item you are making, it vanishes from the curser and the ingredients are used up at the same time.
Also, other player can't pick up the item they added to the crafting table.
This only happens in the server. Not in singleplayer. Any additional info just ask. 

Sincerely
Elite82pt

**Comment by mezz** [comment]
Thanks for the report!
Are you running a SpongeForge server? If so it may be this issue: 
https://github.com/SpongePowered/SpongeForge/issues/1976

**Comment by Elite82pt** [comment]
Yes! Thank you mezz for the help :D

**Comment by mezz** [comment]
This has been fixed in the latest SpongeForge.
