### ISSUE TITLE
Proof for 9minecraft that I am mezz

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#1119]
![mezz-proof](https://user-images.githubusercontent.com/916092/35547622-e97d60e8-052e-11e8-9c33-439d3307b6c5.png)

Hello, this is proof that I am mezz. Thank you.

**Comment by mezz** [comment]
JEI has been removed from 9minecraft.

**Comment by SheroxGG** [comment]
Hello I am new on this website. I dont know how to create a new message so you can help me. I have been reading this post https://github.com/mezz/JustEnoughItems/issues/381, I have the same problem as that guy, the game crashes when opening inventory or crafting table on a server. Could you please help me? What do I need to send you so you can help me? Thanks I hope you can help me.

**Comment by mezz** [comment]
@SheroxGG please open a new issue.

**Comment by SheroxGG** [comment]
I am really sorry of commenting on here again, I created an issue in somwhere https://github.com/mezz/JustEnoughItems/issues/1121

As I said I am new on this site sorry and ill remove this when you read it.

**Comment by SheroxGG** [comment]
I am really sorry of commenting on here again, I created an issue in somwhere https://github.com/mezz/JustEnoughItems/issues/1121

As I said I am new on this site sorry and ill remove this when you read it.
