### ISSUE TITLE
JEI Not showing full list of items for ModPack FTB Revalations.

### ISSUE THREAD

**Issue by hyattj07** [mezz/JustEnoughItems#1120]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

So as the Subject says, My JEI isn't showing the full list of item for the modpack. I can see part of it but not the whole thing. My buddy who is running the same modpack, has about 200 plus pages of items and I only show 40 pages. I've tried removing the Mod and reinstalling. Tried replacing the mod file with a new one thinking maybe it was corrupted. I'm out of idea's I'm relatively new to mods so I'm probably missing something rather obvious. But if you could help it would be appreciated

**Comment by hyattj07** [comment]
I should probably also state that the modpack I'm running is FTB Revelations. your mod is the only one I'm having issues with hence the post here and not on the Modpack forum first

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.
