### ISSUE TITLE
Unable to use move items into crafting grid at tinkers construct

### ISSUE THREAD

**Issue by MrRobin1512** [mezz/JustEnoughItems#1122]
![2018-01-31_22 15 17](https://user-images.githubusercontent.com/9063414/35647898-5754cf56-06d4-11e8-869a-c7c5f8a7bce5.png)
![2018-01-31_22 15 21](https://user-images.githubusercontent.com/9063414/35647899-57722d62-06d4-11e8-8fb9-469acb677381.png)

I have the problem that JEI at Tinkers Construct does not recognize that the required materials are in a chest next to it. When I have the materials in the inventory, everything works fine

Thank you for  reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Tinker's Construct: https://github.com/SlimeKnights/TinkersConstruct/issues
