### ISSUE TITLE
Crash report from lookin at an item in JEI 

### ISSUE THREAD

**Issue by JoeSGT** [mezz/JustEnoughItems#1124]
Thank you for reporting!

For issues:
https://pastebin.com/8J5zQ90z
it seem whenever i look at `extrautils2:generator_ender` i crash in jei
```
 -- Ingredient being rendered --
 Details:
Ingredient Mod: Extra Utilities 2
Ingredient Info: 1xtile.extrautils2:machine@0 extrautils2:machine nbt:{Type:"extrautils2:generator_ender"}
```
not sure how to fix this on my end but please take a look thanks you very much

versions that i am using is 
JEI: 4.8.5.147 
ExtraUtities 1.12-1.7.3
Forge: 14.23.1.2604 
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Extra Utilities https://github.com/rwtema/extrautilities/issues
Also something is really messed up with the issue template and your report.

**Comment by JoeSGT** [comment]
I would have report it there but the mod developer never reply or doesn't really look at his issues on github
can you see if you can possibly make a work around?

**Comment by mezz** [comment]
Sorry but I can't really fix a rendering crash in their mod, I expect it will crash outside of JEI as well.
You can try blacklisting the item in JEI, add `extrautils2:generator_ender` to the config blacklist.

**Comment by JoeSGT** [comment]
Thanks
