### ISSUE TITLE
JustEnoughItems [Hide/Missing/]

### ISSUE THREAD

**Issue by MrHsony** [mezz/JustEnoughItems#1126]
Menu for JEI missing when I open inventory
https://imgur.com/a/pUrdL
https://imgur.com/a/pUrdL
https://imgur.com/a/pUrdL
https://imgur.com/a/pUrdL
https://imgur.com/a/pUrdL

Log:-
https://gist.github.com/MrHsony/aa2029567b346f6290596b21b06a4eec

**Comment by MrHsony** [comment]
Log: 
https://gist.github.com/MrHsony/aa2029567b346f6290596b21b06a4eec

**Comment by TehNut** [comment]
Try `CTRL+O`. That toggles the visible state.

**Comment by MrHsony** [comment]
Not working :(

**Comment by mezz** [comment]
Thanks for the report!
Update JEI to the latest version, it is crashing because of an issue an old version had with the JEI Villagers addon.
