### ISSUE TITLE
Crash when opening inventory.(Resolved for me, you should still look)

### ISSUE THREAD

**Issue by KingEdward9830** [mezz/JustEnoughItems#1127]
Have tried multiple versions of JEI, Forge and removed all other mods. It keeps throwing me the same error. I will now post a crashlog:
https://gist.github.com/KingEdward9830/631c42dd3590de38ea79d9bde65c5290

**Comment by KingEdward9830** [comment]
This was not obtained with the most recent version, but with latest forge and latest JEI it still happens.

**Comment by KingEdward9830** [comment]
Oh wait, I just looked at closed issues. Turns out that that mudpack made the Jar into a Zip because that's what Curseforge does. Might wanna take a look at that.

**Comment by KingEdward9830** [comment]
Can confirm that changing the file extension manually fixes it.

**Comment by mezz** [comment]
Thanks for the report!
Where exactly did you get JEI as a zip file?

**Comment by KingEdward9830** [comment]
Sorry for the late reply,
https://minecraft.curseforge.com/projects/jei
Pretty sure it was here.
Wherever it was, I got the latest and the two before it during my testing, all of them were zips.

**Comment by mezz** [comment]
The other person with this issue was using a download-optimizer program because they live in a country far away from the curse servers. That program was turning the .jar into a .zip. Is that your issue as well? There are no .zip files hosted at the link you gave.

**Comment by KingEdward9830** [comment]
Hmm, not to my knowledge... I'll try downloading from the link I gave to see if I got the wrong site...
(Edit: Well, it downloads as a .jar now... That's really strange, either the site was having issues or I clicked on a mimic site by mistake. Well either way, I guess this is resolved.)

**Comment by mezz** [comment]
Ok, thanks for looking. We are removing support for .zip mods in Forge in 1.13 so it should not be a problem for much longer in any case.
