### ISSUE TITLE
Needs forge?

### ISSUE THREAD

**Issue by crosby-moe** [mezz/JustEnoughItems#1130]
I put Jei in my modpack but when i start the game it says i need forge? I already have forge and i don't know how to fix this problem. I don't know where is my forge but i know i have it because i have over 50 working mods.

**Comment by mezz** [comment]
Thanks for the report!
JEI will only say it needs Forge if you have an older version of Forge and JEI needs a newer version.
Try installing the latest version of Forge and the error will go away.

**Comment by crosby-moe** [comment]
I cant find my forge anywhere in my modpack, i downloaded a clean modpack on technic launcher.

**Comment by mezz** [comment]
If you are using a pre-made mod pack and it has this issue, please report it to the mod pack.
If you are changing the mod pack yourself or if it is your pack, you should find out how to update the version of Forge in a technic pack. I am not sure because I do not use the technic launcher, sorry.
