### ISSUE TITLE
JEI Necessary Ehancements

### ISSUE THREAD

**Issue by jredfox** [mezz/JustEnoughItems#1132]
Priority: Low , but please do it eventually

Unlike NEI JEI is lacking what NEI use to have **I am not sure what it's missing** but, here are the features that I think it might be missing since I haven't heard of them yet:

Images:
[redstone furance recipe](http://4.bp.blogspot.com/-HSERZNEI1qc/VGGax_gasOI/AAAAAAAAAVU/Dwef3DrLUuw/s1600/RedstoneFurnaceRawCarbon.PNG)
[missing features](https://i.ytimg.com/vi/Flf6sNBy_ws/maxresdefault.jpg)

My Request:
ability to use Config global config for all word's

*the easiest way to know what I am talking about is to pull up nei for 1.7.10*
NEI:
scrolling(by clicking selecting first? through crafting recipes to not just the main pages)
trash can(exiting inventory reverts it back to disabled)
magnet mode
the ability to change the amount per stack in cheat mode it gives you
the ability to filter what mod/mods are displaying on nei by clicking on buttons
the ability to reskin stuff using a texture pack like buttons
have the buttons to set night and day rain or shine
button to go to creative adventure and survival(I would prefer option to go into survival)
ability for you to click a question mark in recipes and it would outline what to place where so you don't have to look back and forth 20 times
**An Interface or something like it where other mods could register recipes addons for like TConstruct and tech mods and it would show their addon recipes. I believe it was pretty easy for mod makers to do so to except for the actual dev setup which jei doesn't have an issue with that**

**Comment by TehNut** [comment]
The goal of JEI is *not* to clone NEI. It is to provide a highly optimized item list and recipe viewer. Anything extra is the job of another mod.

You might be interested in [this](https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0) spreadsheet. 

>scrolling(by clicking selecting first? through crafting recipes to not just the main pages)

What?

>trash can(exiting inventory reverts it back to disabled)

What? If you're in cheat mod, drag the items into the item list. If you mean the button at the top left, that's for another mod.

>magnet mode

Job of another mod.

>the ability to change the amount per stack in cheat mode it gives you

Unnecessary. Use /give. You can already give yourself 64 or 1 by using left/right click.

>the ability to filter what mod/mods are displaying on nei by clicking on buttons

#163

>the ability to reskin stuff using a texture pack like buttons

[???](https://github.com/mezz/JustEnoughItems/tree/1.12/src/main/resources/assets/jei/textures/gui) Anything else it uses is from vanilla

>have the buttons to set night and day rain or shine

Job of another mod.

>button to go to creative adventure and survival(I would prefer option to go into survival)

Job of another mod.

>ability for you to click a question mark in recipes and it would outline what to place where so you don't have to look back and forth 20 times

This exists. Click the plus button.

>An Interface or something like it where other mods could register recipes addons for like TConstruct and tech mods and it would show their addon recipes. I believe it was pretty easy for mod makers to do so to except for the actual dev setup which jei doesn't have an issue with that

I don't understand this. Mods should be registering their recipes with the mod they add support for. Those mods should be properly adding those to JEI. Why would this be something on JEI's side?

**Comment by jredfox** [comment]
I think you misinterpreted the missing features I will post a video

**Comment by jredfox** [comment]
I wasn't asking you to be unoptimized just to consider either making these as an addon yourself since the real NEI is dead(no the addon for jei currently doesn't do anything) and the rest of these into your default mod themselves since I feel it should be in here like change the amount it gives you from clicking on your tab from 64 to I don't know 22. 

I am very tired I will post here again explaining what I am talking about when I wake up for the video

**Comment by jredfox** [comment]
I think FEI already does this
