### ISSUE TITLE
Suggestion: Option to disable vanilla recipe book

### ISSUE THREAD

**Issue by Ithronyar** [mezz/JustEnoughItems#1133]
JEI makes the game's built-in recipe system almost completely redundant, so it would be a nice configuration option to disable the vanilla recipe book, GUI elements, and "unlocked recipe" popups.

Edit: Since the vanilla system _can_ still be useful, maybe there could be an option to register all JEI-visible recipes in the vanilla recipe book, rather than making the player craft everything first. That way there are no incessant popups or arbitrarily hidden recipes that force you to switch to and from JEI. There just doesn't seem to be a simple and elegant solution to make everything work together with minimal redundancies/annoyances.

**Comment by TehNut** [comment]
If you look, this has been requested several times before. It will not be added as it is out of the project scope.

**Comment by mezz** [comment]
I haven't tried it but this looks promising: https://minecraft.curseforge.com/projects/no-recipe-book

**Comment by MauveCloud** [comment]
Alternatively, if you already have Quark installed, it includes an option to disable the recipe book button, and one to pre-unlock all recipes.
