### ISSUE TITLE
Inventory JEI Hud not showing 

### ISSUE THREAD

**Issue by JupiterYourHero** [mezz/JustEnoughItems#1134]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by JupiterYourHero** [comment]
Tried reinstalling did nothing

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.
