### ISSUE TITLE
requires Forge??

### ISSUE THREAD

**Issue by YoImErin** [mezz/JustEnoughItems#1135]
https://i.imgur.com/mSGLPaf.jpg

Okay, I thought it was resolved because I found the newest version, but even after installing the newest version, it gives me the same error!

EDIT: sorry i am new to github*

**Comment by TehNut** [comment]
Your instance is still using the outdated version.

**Comment by YoImErin** [comment]
well how do I update it? Installing a new version doesn't seem to change anything?

**Comment by YoImErin** [comment]
Oh, I believe I have fixed it, uninstalling and reinstalling seems to have worked, my bad
