### ISSUE TITLE
[1.10.2] Cheat mode resets on relaunch of game

### ISSUE THREAD

**Issue by Brycey92** [mezz/JustEnoughItems#1136]
I run a custom modpack using both JEI and NEI, along with a server for this pack. Every time the game is relaunched, JEI cheat mode gets turned off. This happens whether or not I select "Apply globally" when changing the setting. It should be noted that NEI cheat mode appropriately stays enabled, though both mods must be in cheat mode for it to work.

**Comment by TehNut** [comment]
Try without NEI

**Comment by Brycey92** [comment]
I removed NEI, and restarted once, and it didn't happen, but when I put NEI back in and restarted, it still didn't happen. I'll try to keep track of when it happens in the future so this issue can be handled.
