### ISSUE TITLE
The craft result disappear but it work

### ISSUE THREAD

**Issue by fujhofn** [mezz/JustEnoughItems#1138]
Description: I the 2x2 "crafting player table", if we the check a recipe of anything, and that there was a craft in it, the craft result dissapear (but it work anyway!).
Steps to reproduce:

- Open your Inventory
- Make a craft (for  exemple, bone meal) but without getting the result.
- Check the craft of anythings.

Expected result: The craft result is aldry here and it work.
Actual result: The craft result disappear but it work.

![](https://cdn.discordapp.com/attachments/372033596975742977/413040209194647552/2018-02-13_19.32.14.png)

Minecraft version: 1.12.2

List of mods:
- InventoryTweaks: v1.63
- JEI: v1.12.2-4.8.5.138
- Journeymap: v1.12.2-5.5.2
- Optifine: v1.12.2_HD_U_C7

System: Win10, x64

Cheers,
"fuji."

**Comment by mezz** [comment]
Thanks for the report!
If you are using SpongeForge, is this a duplicate of https://github.com/mezz/JustEnoughItems/issues/1117?

**Comment by fujhofn** [comment]
No, I use the last version of forge in 1.12.2.

**Comment by mezz** [comment]
I need some more information to solve this issue, can you please paste your full `fml-client-latest.log` to https://gist.github.com and link it here?
