### ISSUE TITLE
I can't see basic crafting recipes, from the crafting table, or any other basic crafting item.

### ISSUE THREAD

**Issue by muffinlumps** [mezz/JustEnoughItems#1140]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by muffinlumps** [comment]
I fixed it, Custom Npcs conflicts with JEI

**Comment by mezz** [comment]
Is there a bug reported to Custom Npcs somewhere for this?

**Comment by muffinlumps** [comment]
I don't know just deleted from my modpack and the crafting table tab worked.
