### ISSUE TITLE
[RECIPE] Firework rocket missing JEI 146

### ISSUE THREAD

**Issue by okid0kii** [mezz/JustEnoughItems#1142]

**Comment by Ricket** [comment]
This was overlooked and should remain open; please fix or confirm it has already been fixed.

**Comment by mezz** [comment]
Thanks for the report! 
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/91
It has not been fixed. Implementing many-ingredient-to-many-output recipes is tricky in JEI and requires some good design, so fixing this has not been a high priority.
