### ISSUE TITLE
Problem from starting mc with jei mod and nei saying: forge etc some numbers missing.

### ISSUE THREAD

**Issue by HelpMePleasepls** [mezz/JustEnoughItems#1143]
So i have the latest forge installation, not working. tried reinstalling, not working any suggestions?

**Comment by HelpMePleasepls** [comment]
help

**Comment by HelpMePleasepls** [comment]
![image](https://user-images.githubusercontent.com/36644879/36394768-663bde12-15be-11e8-8b70-786859647878.png)

**Comment by HelpMePleasepls** [comment]
![image](https://user-images.githubusercontent.com/36644879/36394793-7ba78a58-15be-11e8-906a-28c7bfd4250e.png)

**Comment by mezz** [comment]
Thanks for the report!
This error screen is never wrong, somehow you have an older Forge installed.
Please check your client log to see which version of Forge you have.
