### ISSUE TITLE
Game Client Crash -- JEI / Buildcraft

### ISSUE THREAD

**Issue by JoshReardon** [mezz/JustEnoughItems#1144]
Hey there! I recently was using creative mode and accessing my mods tabs, when clicking on the Buildcraft Facades tab, my game client crashed.

Now whenever I try to use the search function (the one with mod tabs) it crashes my client!
I have posted the crash report below, any help would be truly appreciated!
[crash-2018-02-19_16.03.42-client.txt](https://github.com/mezz/JustEnoughItems/files/1738182/crash-2018-02-19_16.03.42-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Buildcraft instead: https://github.com/BuildCraft/BuildCraft/issues. 
Based on the crash report, this is coming from the creative menu and Buildcraft, I do not think JEI is involved.
