### ISSUE TITLE
Item Blacklist Not Re-Applying After Resource Reload

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#1145]
When reloading resources during runtime (i.e changing mipmap levels, applying a resource pack, pressing F3+T...) the item blacklist is not re-applied, and all previously hidden items are displayed in JEI until the game is restarted or the item hiding mode is enabled then disabled via the in-game config. This bug applies to JEI's built-in blacklist file and blacklisting applied through CraftTweaker's integration. Presumably, this means all third-party blacklisting is broken too although I have not had the chance to test it.

**Mod version:** [1.12.2-4.8.5.157](https://minecraft.curseforge.com/projects/jei/files/2532615)
**Forge version:** [1.12.2-14.23.2.2618](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2618/forge-1.12.2-14.23.2.2618-changelog.txt)

**Comment by ChloeDawn** [comment]
Update: This seems to only occur whilst a world is loaded. I applied a resource pack and changed mipmap levels before entering a singleplayer world and the blacklist seemed to apply normally.

**Comment by mezz** [comment]
Fixed in JEI 4.8.5
