### ISSUE TITLE
Sugestion - Special Features Button

### ISSUE THREAD

**Issue by fredyarcol** [mezz/JustEnoughItems#1146]
HELLO!
Before everything i would like to say JEI is pretty good on what it does, anyway i am pretty sure there is other items/recipes to add.

This is my sugestion 
-Firework Spawner (as TMI before being discontinued)
-Some custom spawners (giant zombie spawner, ridding mobs etc)
-The differents fireworks kind
-The differents fireworks stars
-Lit furnace (wich somehow everyone forgots it after TMI)

I know a lot of those are difficult to make them as a item. So my suggestion is to make a small button nearby the inventory with a big S (like special features). In that button you just have icons and when you press the icon it automatically types the "/give_item" code for those specific custom items.

For example.
You press the button of special features, then you have another icon of "special items" and then i press the item i want (for example lit_furnace)
When i press the icon it writes the command "/give_item (condition to get the player name) lit_furnace"
The same for fireworks ""/give_item (condition to get the player name) firework_rocket{Fireworks:{Explosions:[{Type:3,Flicker:1,Colors:[I;1973019],FadeColors:[I;11743532]}],Flight:2}} 1"

That way it would be easyer than adding the items to the list because all you have to do is replace the same code with the different item and "location in the grid".

Thats just a sugestion =) Anyway, so far so good, you have the most downloaded inventory app.

**Comment by mezz** [comment]
Thanks for the suggestion!
I think this is a good idea, but it should be added by another mod. One of the goals of JEI is to keep it as small as possible, so that it is stable and reliable, and so that I can port it to new versions of Minecraft quickly. These extra features can be implemented by a separate mod without depending on JEI at all.
