### ISSUE TITLE
Cannot get decompiler to find the files

### ISSUE THREAD

**Issue by ServantGirl** [mezz/JustEnoughItems#1148]
I I keep getting 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'WorkSpace'.
> Could not resolve all dependencies for configuration ':deobfProvided'.
   > Could not find mezz.jei:jei_12.2.2:4.8.5.138.
     Searched in the following locations:
         http://files.minecraftforge.net/maven/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138.pom
         http://files.minecraftforge.net/maven/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138-api.jar
         https://repo1.maven.org/maven2/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138.pom
         https://repo1.maven.org/maven2/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138-api.jar
         https://libraries.minecraft.net/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138.pom
         https://libraries.minecraft.net/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138-api.jar
         http://dvs1.progwml6.com/files/maven/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138.pom
         http://dvs1.progwml6.com/files/maven/mezz/jei/jei_12.2.2/4.8.5.138/jei_12.2.2-4.8.5.138-api.jar

But I do not understand. As far as I can tell its looking in the exact location that the files should be. Infact I compared them and the match up verbatim here http://dvs1.progwml6.com/files/maven/mezz/jei/jei_1.12.2/4.8.5.138/

My build file is set up like this, Under Dependencies I have:
 `deobfProvided "mezz.jei:jei_12.2.2:4.8.5.138:api"

  runtime "mezz.jei:jei_12.2.2:4.8.5.138"`

Then under  Repositories  

maven {
    // location of the maven that hosts JEI files
    name = "Progwml6 maven"
    url = "http://dvs1.progwml6.com/files/maven"
  }
  maven {
    // location of a maven mirror for JEI files, as a fallback
    name = "ModMaven"
    url = "modmaven.k-4u.nl"
}

**Comment by liach** [comment]
your link to modmuss is wrong. add http

**Comment by ServantGirl** [comment]
Before "modmaven.k-4u.nl"?
What do you mean 'modmuss'

**Comment by liach** [comment]
I suggest you to ask at https://discord.gg/x9YurGA
