### ISSUE TITLE
Crash when holding shift and viewing recipe

### ISSUE THREAD

**Issue by superckl** [mezz/JustEnoughItems#115]
This is for version 2.17.1.81.

So far I've gotten this to work on pretty much any recipe with multiple item subtypes. This inclues
- Glass from sand or red sand.
- Crafting table from wooden planks.

Holding shift and pressing the view recipe hotkey causes JEI to crash with an `ArrayIndexOutOfBoundsException`.

http://pastebin.com/7q6CT797

I would guess the CycleTimer doesn't do it's initial setup since it's frozen?

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest build
