### ISSUE TITLE
Question: is there a way to control sort order of how items show up from a given mod

### ISSUE THREAD

**Issue by Lothrazar** [mezz/JustEnoughItems#1151]
What controls sort order?  Is there anything I can call to sort after registraiton?  Not a bug.

A user asked me to sort my items in JEI.  I looked through docs and wiki, didnt see anything.  (I do have a JEI plugin already for custom recipes and info text.)

If not possible please let me know.
https://github.com/PrinceOfAmber/Cyclic/issues/667

**Comment by TehNut** [comment]
I mean the reporter kinda answered it for you. JEI sorts by numeric ID within a mod which is based on registration order (on new worlds. on existing worlds with new objects, they're stuffed in at the end). The solution here would be for you to use an order preserving Map implementation.

**Comment by mezz** [comment]
The intention is to match the vanilla creative menu tabs more or less.
You can find the relevant code here to see what JEI is doing:
https://github.com/mezz/JustEnoughItems/blob/1.12/src/main/java/mezz/jei/plugins/vanilla/ingredients/ItemStackListFactory.java#L37

**Comment by Lothrazar** [comment]
Thanks for the responses! I think i have everything i need
