### ISSUE TITLE
[Enhancement] JEI Option GUI Recipe

### ISSUE THREAD

**Issue by jredfox** [mezz/JustEnoughItems#1152]
Idea: add an option that moves the button of the recipe page to the button and the other slightly down from where it is then the gui itself decreases slightly in size.  *I think this is a good option for jei in general* and my personal use would be to reskin it to look like nei.

![2018-02-24_01 59 52](https://user-images.githubusercontent.com/9736369/36627304-808ad26e-1906-11e8-81f1-1efb25a06170.png)
Question unrelated
 to this what happens when an item has like 10 things like furnace, redstone furnace, crafting bench does it have multiple page tab system or does it just not work?

Sorry for last issue requesting to much for something as simple as an enhancement request.

**Comment by Tahakk** [comment]
I have no idea why would you want it down there. It is more logical to have these buttons near each other, so that if you have pack with tones of recipes, you can scroll faster without moving your mouse up and down like mad man.

**Comment by jredfox** [comment]
No it's not they keep getting in the way and I am so confused by it it's less frustrating for me and people who actually enjoyed tmi and nei

by having this to the bottom and a slightly smaller gui I feel like I know where everything is and don't keep getting confuses since in jei hardcoded they are right on top of each other.  I don't care if the option disabled by default I myself keep getting confused when actually using this mod even with nei addon so I would prefer the option so I can set it down

Also if it wouldn't be too much of a mouse issue since the gui would slightly decrease height in that mode so it wouldn't be too much yet organized in my opinion.

**Comment by mezz** [comment]
You seem to be having trouble adapting to the JEI interface compared to NEI.
In the years this mod has been out, countless players have encountered these same changes and adapted.
I think if you give it some more time you will too.
I do not intend to make things work or look exactly like NEI, sorry.

**Comment by jredfox** [comment]
How is this "out of scope" for having a client end config option for the panel of button order to change? Just wondering because I keep accidentally clicking the top rather then the bottom this has nothing to do with nei it has to do with organization.

o well going to submit to nei again :(
