### ISSUE TITLE
[Enhancement] KeyBind to Hide All JEI Including Right Side

### ISSUE THREAD

**Issue by jredfox** [mezz/JustEnoughItems#1153]
Not 100% sure but, after looking for 6 minuets in keybinds and options in jei I can't find a hide jei all option only the left panel. The point of this would be your tired of it for a bit and want to remove it or you don't want others to think your cheating in survival. 

Default keybind:"o"

**Also keep the boolean public so modders can decide where and when to hide it**

**Comment by TehNut** [comment]
JEI doesn't have a left panel. The item list can be hidden with CTRL + O

**Comment by antoinegag** [comment]
> Also keep the boolean public so modders can decide where and when to hide it

Ever heard of [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming))?

**Comment by jredfox** [comment]
um key bind to hid the right panel control + o hides the left panel when addons are in 

@Poke1650 never said it had to be static or not static just a reference of the instance of the object and the boolean has to be changeable

**Comment by TehNut** [comment]
Then you should request those addons add their own keybind. They have absolutely nothing to do with JEI.

**Comment by jredfox** [comment]
No because the other addons can't hide jei jei needs to get hidden with a keybind or under specified conditions via boolean visible not the addon pannel.

NEI Addon:
needs to hide jei if player isn't in inventory
old nei keybind o = hide nei well if my request is made they don't have to

This has everything to do with JEI since I want to hide JEI did you see anything about a NEI request A: I want to hide it with nothing but, JEI B: Other addons need to hide it as well or really went to

**Comment by mezz** [comment]
JEI does not draw on the left side of the screen.
JEI's keybind for hiding itself (the right side ingredient list) is Control+O by default, and configurable in the controls menu.
If it is not working, or the behavior is changed, it's because some other mod is messing it up. Please find out which and report to them.

**Comment by jredfox** [comment]
Did You read I said right side

**Comment by mezz** [comment]
I am close to banning you from my issue tracker. Please respond in a less pedantic way.

**Comment by jredfox** [comment]
Keybind o to hide all JEI not just the left pannel that mods add. Your currnet setup in your JEI keybinds that I saw said to hide something and that something with addon was left pannel by itself it did nothing without any addons.

**Comment by jredfox** [comment]
FUCK YOU YOU DON'T FUCKING READ SHIT IT SAYS RIGHT SIDE THE RIGHT JEI PANNEL NOT PATHETIC

**Comment by mezz** [comment]
In your original post it says:

>Not 100% sure but, after looking for 6 minuets in keybinds and options in jei I can't find a hide jei all option only the left panel.

Pedantic does not mean pathetic, look it up. I think you are the one who isn't reading carefully. Goodbye.

**Comment by jredfox** [comment]
ok well actually this is a separate issue control + 0 did hide it but, with the addon it wasn't weird

maybe if you just told me it does hide the panel with control + o to the right I wouldn't have been pissed sorry

**Comment by mezz** [comment]
![wtf](https://user-images.githubusercontent.com/916092/36653312-26381b0a-1a69-11e8-973e-ff71ed7f4a78.png)

The very angry comment was deleted but I'm not putting up with that, I've blocked him now. :/
