### ISSUE TITLE
[Enhancement] Recipe Hint 

### ISSUE THREAD

**Issue by jredfox** [mezz/JustEnoughItems#1154]
In your current gui you have and you hit recipe for item you hit the + thing it it auto places them in the crafting table for you I don't like that.
![2018-02-24_07 00 08](https://user-images.githubusercontent.com/9736369/36630713-64b5fbf2-1930-11e8-84c2-c070943ac96c.png)
What I want is a button to only give me the shaded outline hints of what to put where I want 
to feel like I am actually doing something. The other issue is with the + button it only works if you have all items I don't care if I have everything I just want to view the recipe hints live not almost auto crafting it for me.

**Comment by mezz** [comment]
I'm sorry you do not like the way JEI works, but I am not interested in including this feature.

**Comment by jredfox** [comment]
ok :( respect that going to submit to nei
