### ISSUE TITLE
JEI Keeps crashing 1.12.2

### ISSUE THREAD

**Issue by eonrick** [mezz/JustEnoughItems#1155]
help me fix this is my link for you to help me diagnose the problem with it.
https://gist.github.com/anonymous/a40f34376b78bf6b325808f5a873e223

**Comment by mezz** [comment]
Thanks for the report!
```
Caught exception from jei (Just Enough Items)
java.lang.OutOfMemoryError: Java heap space
```
Looks like you need to allocate more ram to your Minecraft instance, it's running out of memory. In your java arguments you have `-Xmx2G` and it probably needs to be something more like 4G. Most Minecraft launchers have a setting for this that you can easily change.

**Comment by eonrick** [comment]
thanks so much mezz if i have any other problems ill make sure to you let one of you guys know thanks.

**Comment by mezz** [comment]
no problem!
