### ISSUE TITLE
Got A Problem With Something Cant Figure Out What It Is Please Help

### ISSUE THREAD

**Issue by eonrick** [mezz/JustEnoughItems#1158]
https://gist.github.com/eonrick/dc5f99cc22ebff37f1c577213d6990b5

**Comment by mezz** [comment]
Thanks for the report!
This is very vague, what is the issue you have?

**Comment by eonrick** [comment]
i keep getting a game crash an unexpected occured and the game has crashed. We're sorry for the inconvenience. and it crashed a couple times saying java i think my other error was either java.lang.outofmemoryerror java heap space
or java.lang.outofmemoryerror java heap size help pl0x and i have my gbs at 4gigs.

**Comment by mezz** [comment]
There is no crash shown in the log you posted.
I think you are looking at the wrong log, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.
You probably need to increase the amount of ram given to java, or remove some mods.
