### ISSUE TITLE
HOW DO I FIX THIS BUG!

### ISSUE THREAD

**Issue by DerpyCoder21** [mezz/JustEnoughItems#1159]
so when i have ANYTHING with this mod on and i click something in the creative inventory IT GIVES ME A STACK! R Click gives me 1 but anywho WHY IS THIS HAPPENING?

**Comment by mezz** [comment]
Thanks for the report!
Does this happen with just Forge and JEI, no other mods?

**Comment by DerpyCoder21** [comment]
i have JEI and another mod but i have a modpack with traincraft and this mod and it keeps doign that

**Comment by Ommina** [comment]
Traincraft?  Traincraft is 1.7.10; no JEI there.
