### ISSUE TITLE
Hiding JEI

### ISSUE THREAD

**Issue by jjc54** [mezz/JustEnoughItems#116]
NEI had a setting that allowed a keybind to hide the item list completely. This is extremely useful when reading long item tooltips or certain guis that don't push JEI away correctly. A random example of this would be when trying to read Thaumcraft's focal manipulator upgrade, the text information goes behind JEI and is unreadable. I've also read somewhere that disabling(hiding) NEI when you aren't using will improve your FPS, so this is also a good thing for low-end PC's. 

Not trying to push NEI like features on you, just thought this was worth mentioning. :)

**Comment by way2muchnoise** [comment]
ctrl + O and I do think you can rebind it

**Comment by mezz** [comment]
Control-O, which can be changed in the Minecraft controls.

Also the very latest JEI will render behind tooltips!
I'm very excited about it, it required a PR to Forge and now it _just works_.

![2016-01-14_14 50 57](https://cloud.githubusercontent.com/assets/916092/12340209/492b01e2-bace-11e5-9fcd-85e489c9adab.png)

**Comment by jjc54** [comment]
Awesome! Didn't know about the keybind, thanks for that :+1:

**Comment by jjc54** [comment]
@mezz So am I :)
