### ISSUE TITLE
Help with crashes plz i need this mod D: /URGENT/

### ISSUE THREAD

**Issue by Apexxxxxxx** [mezz/JustEnoughItems#1162]
[fml-client-latest.log](https://github.com/mezz/JustEnoughItems/files/1786606/fml-client-latest.log)

**Comment by Apexxxxxxx** [comment]
Help PLZZZ

**Comment by mezz** [comment]
```
[20:12:23] [main/ERROR] [FML/]: Caught exception from jei (Just Enough Items)
java.lang.OutOfMemoryError: Java heap space
```
`Memory: 26951032 bytes (25 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)`

You only have 1 GB of ram allocated to Java. Set it higher, to something like 2 GB and you should be fine.

**Comment by Apexxxxxxx** [comment]
tysm
