### ISSUE TITLE
Scripts problem with Server/client

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1163]
So we have a small problem and that the scripts that run on the server are not displayed on the client. only after the scripts with the actual client is present, this is displayed correctly.

this is best seen here:

This is wrong:
https://prnt.sc/ioqf99

This is right:
https://screen.pudding.tk/q2dxculz1o.png

the nei at that time had a function that indicated the scripts running on the server automatically to the client which the scripts did not have. could not you put that in here too?

**Comment by ghost** [comment]
dont forget it

**Comment by mezz** [comment]
JEI loads before you connect to any servers. What kind of scripts are you writing, using which mod? The mod you are using for scripting will need to tell JEI about any updates you make so that JEI can display the right thing.

**Comment by ghost** [comment]
Craftweaker, recipe, tooltip and more

**Comment by ghost** [comment]
like this https://screen.ilikepudding.tk/waufpg8h69.png

**Comment by mezz** [comment]
Thanks. Please report this to CraftTweaker here: https://github.com/CraftTweaker/CraftTweaker/issues
It is up to them to tell JEI about changes so that it can display the right thing.
