### ISSUE TITLE
[Enhancement Request] Client-option to hide crafting recipe tabs

### ISSUE THREAD

**Issue by AriinPHD** [mezz/JustEnoughItems#1164]
I don't know if this is even a JEI-thing or not, I'm only assuming that it is. Apologies if it's not.

If a part of JEI, I'm suggest enabling a client-side option to hide crafting tabs (the ones that let you see crafts by machine-type, at the very top of the JEI window) as some machines are not well integrated into JEI and appear multiple times and serve absolutely no purpose other than bogging down the window making it frustrating to use as you have to click the next-button so many times to get past these annoying repetitive machines. Please see screenshot of one example:

![2018-03-09_15 27 06](https://user-images.githubusercontent.com/5846389/37243436-8f1f07fe-2479-11e8-96be-32e1019e24c5.png)
In the screenshot this so called "Void Resource Miner" appears 6 times. The information below (two pipes, a block and percentages) is literal the only information shown on the JEI page. The only difference between the pages are the percentages... They obviously could have implemented a smoother way to show their recipes but this method just drown the JEI interface. Other mods do this as well and more mods to come certainly will.

It's not a mod I use, or even know what does (nor does it have an info page that describes the mod) so I wouldn't weep if it suddenly disappeared from my crafting menu :p

I hope you can consider such an option: To hide tabs of your choosing to clean up an annoyingly overfilled UI.

**Comment by KnightMiner** [comment]
Might I suggest you try and give feedback to the mod author on improving their JEI integration? There are likely people who enjoy the mod and would benefit from better docomentation.

In any case, I can see hiding JEI tabs being useful for modpacks which remove a particular machine from a mod while keeping other features.

**Comment by AriinPHD** [comment]
Yeah I wasn't sure if I should have reached out to just them or both, but ended up deciding that that I would also like to see this as an option either way; it could be useful. :)

**Comment by Guinaro** [comment]
I too would benefit from a Tab Removal System and possibly GameStage functionality.

- [ ] /ct JEI listAllTabs (prints to chat) or mods.jei.JEI.alltabs (logs tabnames in crafttweaker log)

- [ ] mods.jei.JEI.hideTab("TabName");

Bonus

- [ ] mods.jei.JEI.setTabStage("stage name", "TabName");

The Hidetab functionality could be used to simply remove a tab, which will never be used in game.
The setTabStage is more to implement an easy way to allow the modpack creator to hide certain machine outputs and it's recipes until that machine can actually be crafted. I would prefer that presence of the usage of machine and appearance of tab for said machine is split. This way you can guide the user in crafting the machine, requiring a certain output specifically for said machine, before you set the stage to show the full tab with all the possible recipes.
Non staged Tabs that aren't hidden, appear as usual.

Thank you for you consideration,
Guinaro

**Comment by KAfable** [comment]
Just wanted to follow up on this, I'm also interested in seeing a JEI tab hiding functionality as it could really help clean up the bloat that comes from larger mods.

**Comment by Husky110** [comment]
I would like to have that feature aswell and hopefully it will be available for 1.12.2, since most current modpacks run this version...

**Comment by mezz** [comment]
I recently added an API feature to hide entire recipe categories [here](https://github.com/mezz/JustEnoughItems/blob/4b483f7102af464c50a62b1f52d604975df32e23/src/api/java/mezz/jei/api/IRecipeRegistry.java#L141-L159) so that CraftTweaker, GameStages, etc can make use of it.
There is still no way to do it in-game though, I will need to get some time to come up with the proper UI and everything for it.

**Comment by Guinaro** [comment]
Would it be possible to also hide specific "crafting tables" out of a certain recipe category?
Eg. standard recipes have the minecraft crafting table, crafting table on a stick, sequential fabricator (Thermal Expansion), ... .
When configuring a modpack certain "crafting tables" or machines are not used in the pack, or you would like to hide the machine and unlocking it a certain game stage. E.g. I'm not using the Sequential Fabricator in my pack, but I cannot simple hide the standard crafting recipes aswell.

So would it be possible to hide the individual machines in a certain category too?

**Comment by mezz** [comment]
@Guinaro when you hide one of those from JEI in general, they also get hidden from the list of "catalysts" for any categories they were in.
So in your example, if you hide the vanilla crafting table, it will automatically be hidden from the list of catalysts for crafting recipes.

**Comment by mezz** [comment]
This API is used by GameStages and CraftTweaker so I will consider this issue resolved.
