### ISSUE TITLE
Scrolling Through JEI and Something is Crashing my Game

### ISSUE THREAD

**Issue by UnstableSparkey** [mezz/JustEnoughItems#1166]
Hope somebody can help me! When I search or just scroll through JEI it sometimes crashes. When scrolling through the pages, it crashes a couple pages in near Thaumcraft. I'm running 1.10.2 on a custom modpack. I've never had an issue like this before, but hope somebody can help!

https://gist.github.com/UnstableSparkey/ecd35a380cc8a34682810157c062cfb6

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Thaumcraft
	Ingredient Info: 1xitem.focus@0 thaumcraft:focus nbt:{core:{}}
```
It looks like the crash is from a Thaumcraft item being rendered. Please report to Thaumcraft here: https://github.com/Azanor/thaumcraft-5/issues

**Comment by UnstableSparkey** [comment]
Okay, thank you.
