### ISSUE TITLE
Add callbacks to inventories when user searches

### ISSUE THREAD

**Issue by borg286** [mezz/JustEnoughItems#1168]
Please add a callback to the GuiTextFieldFilter.java class so that when the user opens an inventory, the inventory can ask for callbacks when the user searches for something in JEI.
This might be something like adding a new method on JeiHelpers.java that reaches down to the text field to add a callback to an internal list of callbacks. Each of these callbacks are called on keypresses. When the JEI is closed all these callbacks are cleared. When an inventory is opened it is the burden is on the inventory to call into jei and provide a keypress callback method.

This would allow the inventory to highlight items that the user searches for in JEI.
This may already be done with ME systems, though it may be the reverse (whatever the user searches for in the ME system search field then JEI updates). 
An ActuallyAdditions Crate, for example, may want to let the user search for an item, and would love to use the existing JEI search field on the screen.  
The RFTools modular storage has a search field, as well as the 2 big contenders for ME systems (applied energistics, and Refined Storage), but the lowly Tinker's Construct + Storage Crate pair are missing out when it comes to casting accio thingamajigger.
If the other 3 big ME systems integrated with this new API, then moving the search bar to the center just became much more appealing and a one stop shop.

**Comment by mezz** [comment]
Thanks for the request!
I do not really intend for JEI to be a GUI extension for mods. I prefer solutions where mods do not depend on JEI's search box. Often players want to keep the JEI search on some items they are interested in, and it makes sense to have a separate text entry field for doing something else.

**Comment by borg286** [comment]
I can respect that. I believe you have a keybinding that lets the user hover their mouse over an item, press 't' and then inventories that have that item smoke. Would you consider extending this to a similar feature when viewing inside an inventory.
JEI would send some request to the inventory to highlight items matching a string. Or since you seem to already have access to nearby inventories and which chest has that item, you send it the item ID that should be highlighted.

**Comment by mezz** [comment]
That feature is added by something else, I do not have any inventory-searching features built in to JEI.
