### ISSUE TITLE
[Suggestion/Request] JEI support for Real World

### ISSUE THREAD

**Issue by Chefbarbie** [mezz/JustEnoughItems#1169]
Would like support for Real World special crafting. 

MOD: https://10paksmods.net/

**Comment by mezz** [comment]
Thanks for the request!
Every mod adds their own support to JEI.
I have tried to reach out to the Real World developer some time ago, but they have not responded.
Unfortunately I think that they will not add JEI support.
It is possible that an addon mod could be created to do it, but it must be done in a separate mod from JEI.
