### ISSUE TITLE
World Loading very slow - repeated error: [JEI]: Couldn't get ItemModel for itemStack.

### ISSUE THREAD

**Issue by TSM-EVO** [mezz/JustEnoughItems#117]
When loading the world, it is very slow, and MultiMC log keeps repeating this: 

[12:20:26] [Server thread/ERROR] [JEI]: Couldn't get ItemModel for itemStack.
java.lang.NullPointerException: null value in entry: None.002=null

http://pastebin.com/FENwXu70

The world loads eventually, but it takes longer than expected. It does this for existing worlds or new worlds.

**Comment by wlhlm** [comment]
This is a know problem with Buildcraft. See #108.
