### ISSUE TITLE
Click into crafting grid throws in extra items

### ISSUE THREAD

**Issue by austin-wiechman** [mezz/JustEnoughItems#1171]
I am using Minecraft version 1.10.2, JEI version 3.14.7.420. Most if not all the times that I click the “+” button to transfer my recipe into the crafting grid, another random item is thrown into the grid as well. This issue is nearly identical to the one found here: https://github.com/mezz/JustEnoughItems/issues/239. Any clue what is causing this issue or how it could be solved?

Thanks in advance,
GoWish

**Comment by mezz** [comment]
Thanks for the report!
Please try removing Mouse Tweaks or Inventory Tweaks if you have them installed. It may be an incompatibility with one of those mods, I have seen minor issues like this in the past and it may be back.

**Comment by Ozzymud** [comment]
In 1.12.2 playing all the mods 3 it is back, inventory tweaks seems to be it, removing it stops the problem, but it would be hard to live without inventory tweaks. Is this a thing on JEI's side or should it be reported to InvTweaks?

**Comment by mezz** [comment]
Try reporting it to InvTweaks: https://github.com/Inventory-Tweaks/inventory-tweaks/issues
It is probably an issue similar to the one with MouseTweaks https://github.com/YaLTeR/MouseTweaks/issues/2, where both mods are handling the same click or key press. JEI is canceling the key/mouse event when it uses the press/click, but maybe the other mod is consuming these inputs in a different way.
