### ISSUE TITLE
JEI ignores item's NBT tags

### ISSUE THREAD

**Issue by KrisBigK** [mezz/JustEnoughItems#1174]
When I open the recipes/uses of IC2's universal fluid cell(empty), all universal fluid cell's recipes come out. For example, when JEI displays the uses of an empty universal fluid cell, it also displays the recipe that a universal fluid cell containing 1000mB lava can be used as fuel in a furnace. This also happens with GT's metaitems. When I open the recipe of the flint sword, all sword recipes come out. I also noticed that all universal fluid cells and GT's swords have the same metadata value and name, but with different NBT tags. I can provide a full modlist if needed.
MC version:1.10.2
Forge version:1.10.2-forge1.10.2-12.18.3.2185

**Comment by TehNut** [comment]
IC2 needs to register a subtype interpreter for their item.
