### ISSUE TITLE
Can't open vanilla storage box

### ISSUE THREAD

**Issue by bdennis123** [mezz/JustEnoughItems#1175]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information, can you explain the issue?
Please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.
