### ISSUE TITLE
JEI overlay does not appear in inventory

### ISSUE THREAD

**Issue by DarkArachnid** [mezz/JustEnoughItems#1176]
When i open my inventory i dont see anything from JEI; it happens often and unreliably.

**Comment by mezz** [comment]
Thanks for the report!
I'm not really sure what the issue here is, but maybe looking at your client log would point me in the right direction. Please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by DarkArachnid** [comment]
nevermind, all i did was redownload after deleting config and the actual mod and it worked fine
