### ISSUE TITLE
[1.12.2] JEI Stuck in Recipe or Cheat Mode Reguardless of In Game Setting

### ISSUE THREAD

**Issue by Morpheus1101** [mezz/JustEnoughItems#1177]
Forge *.2631
JEI v4.8.35.159

Currently if your in Recipe mode irrespective if you enable cheats and have OP it will continue to be in recipe mode.  If you change the setting to cheat mode, exit the game and log back in, it is now permanently on Cheat mode regardless if you change it to recipe mode.

**Comment by mezz** [comment]
Thanks for the report!
Does this happen with just JEI and Forge? If there is a conflict with another mod please try to narrow it down and find the mod so I know what to test with.

**Comment by Morpheus1101** [comment]
I'll do some testing now and let you know whats going on as this isnt occuring in any other modpack or happend prev to the update of this one, so i will start tracking down whats going on.

**Comment by Morpheus1101** [comment]
Ok, so at this stage its deffinately a mod intereaction as with JEI on its own this dosent occur, now to track down what mod

**Comment by Morpheus1101** [comment]
And the lucky winner of the causing mod is...........SecretRooms, dev of which i can chat to directly and send them over to here as well

**Comment by Morpheus1101** [comment]
Being this was caused by another mod, im now closing this.

**Comment by mezz** [comment]
Cool, thanks for following up and linking to the other issue. It's nice to see this is fixed.
