### ISSUE TITLE
Error. Creative tab crashed while getting items [MC1.12.2]

### ISSUE THREAD

**Issue by kellixon** [mezz/JustEnoughItems#1178]
Minecraft: 1.12.2
Forge: all (last 14.23.2.2637)
Cyclic 1.14.6
JEI 4.8.5.159
Lines: 13996 (JEI-Cyclic)
Debug Log - https://drive.google.com/open?id=17dCrv1l_taOd9Js8wWa6RZbId6PPamuF

**Comment by mezz** [comment]
Thanks for the report!
I see you have already reported it to Cyclic here: https://github.com/PrinceOfAmber/Cyclic/issues/760
This is a Cyclic bug, so I will close this issue.
