### ISSUE TITLE
JEI claims that I don't have Forge 

### ISSUE THREAD

**Issue by Kargg** [mezz/JustEnoughItems#1179]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Kargg** [comment]
JEI 1.12.2-4.8.5.147 won't install, saying that it needs Forge to function, when I'm running a ton of other mods that also need Forge and are working just fine.

**Comment by mezz** [comment]
Thanks for the report!
You probably need a newer version of Forge. Try using the latest.
If you tried that and there is still an issue, please paste your full log to https://gist.github.com and link it here.

**Comment by Kargg** [comment]
That's the first thing I thought as well, but I'm pretty sure my Forge is all up to date. I'm not sure how to post the log you're asking for though.

**Comment by mezz** [comment]
In your Minecraft installation folder, next to the `mods` folder there is one for `logs`. I need either `fml-client-latest.log` or `latest.log`, you can copy-paste the contents of the log file to https://gist.github.com and put a link to it here.

**Comment by Kargg** [comment]
Done and done, here's the link.

https://gist.github.com/Kargg/7c4e13f38488f87b9fd850841725b429

**Comment by Ommina** [comment]
> [10:56:09] [main/INFO] [FML/]: MinecraftForge v14.23.1.2555 Initialized
> [10:56:12] [main/FATAL] [FML/]: The mod jei (Just Enough Items) requires mod versions [forge@[14.23.1.2594,)] to be available

So you need 2594, but you only have 2555 installed.  Update forge and you should be set.

**Comment by Kargg** [comment]
The thing is that I did update it, and it's doing the same thing. I must be
insane?

**Comment by Ommina** [comment]
While I certainly can't rule out any possible mental aberrations, let's leave open the possibility of a technical explanation instead.

Just do the same thing I did above.  Go to the (new) log file and open it up.   The very second line will give you your current forge version ("[10:55:59] [main/INFO] [FML/]: Forge Mod Loader version 14.23.1.2555 for Minecraft 1.12.2 loading" is from your link, above.)  There is a second instance about a third of the way down, below "System Details".

If it still reads "2555", then you know that your forge is not really updated.  You may be putting the new file in the wrong place, or there may be multiple versions available and the wrong version is being selected, or... something.

**Comment by BenjaminUrquhart** [comment]
You might be launching from the wrong profile - the forge installer doesn't remove old profiles.
