### ISSUE TITLE
Ability to save (favorite?) searches, or search history

### ISSUE THREAD

**Issue by keidrolis** [mezz/JustEnoughItems#1181]
I would like to request the ability to save favorite searches in JEI. Alternatively, a history list would be useful as well.

When I'm playing certain modpacks, I will perform certain searches dozens - if not hundreds - of time through my play. For example, in Modern Skyblock 3, I'm always searching "alchemical dust" to bring up all the dusts to make. It would be awesome to have a favorites for this.

**Comment by way2muchnoise** [comment]
iirc there is a history by pressing the up-arrow when focused in the search box.

**Comment by Ozzymud** [comment]
Thank you for that, the directional arrow key up worked like a charm. TIL :)

**Comment by scottosx** [comment]
On 1.12.2 -4.8.5.159 on a Mac I only get a red underscore (caret) when pressing my UP arrow after a search. I have to refocus the search field and right click to return to normal search. I assume this is a blank history?

Or maybe some issue with how the up arrow is interpreted (or mapped) It works as intended in every other circumstance in Minecraft.
