### ISSUE TITLE
& Resource Id searching

### ISSUE THREAD

**Issue by Ozzymud** [mezz/JustEnoughItems#1182]
Not sure if this is broke or if I am being a derp. But I cannot seem to search by ID. #5772/12 is the item id of an invar block in the current pack I am playing(I know they change between packs). Entering in &5772, &5772/12, or &5772:12 shows nothing. I have also tried with the setting to not require a prefix to no avail.

I know this is not a place to suggest from NEI, but if the & is for id's it would be really cool to search for several items like I used to: &1234|1001|1111, easier then typing in a lot of keywords/names.  

Is it broke or am I just a derp? :P

**Comment by KnightMiner** [comment]
`&` is the resource ID as a string, there is no good reason to search by number as those change in every pack, and are going to be removed in 1.13

**Comment by Ozzymud** [comment]
Set to require prefix, &minecraft:dirt reveals an empty search window. And it was much easier to tell someone in voice chat (especially when native languages differed), NEI for 4356 instead of NEI for Aluminum Sieve (fake item, but 2 common words that are spoken very different around the world).  

And I get that the IDs will only be serialized to disk and not visible in the future, I am not here reporting issues about 1.13, more so about 1.12.2 and even 1.10 (one current and one still very popular). As far as good reasons or not, it's subjective I guess, but they are my reasons.

**Comment by KnightMiner** [comment]
Try `&dirt`. You would use `@minecraft` for the mod ID

**Comment by Ozzymud** [comment]
That worked, trying to get JEI to **only** show 3:0|4990 which in my current pack is minecraft dirt and reinforced dirt. However, @minecraft &dirt|&reinforced dirt also shows coarse dirt, podzol, reinforced dirt stairs|fence|bricks|etc|etc  

The id way in NEI showed exactly 2 items, this is more of a problem with a list of like 10 items like I would have had in IE:E while crafting the AE wrench. I had a piped list of ids with about 10 items. In JEI I suspect using only words there would be many more items in a piped list of 10 then just the 10 I want to see.  

Edit: I also tried putting quotes both single and double in various combinations (&"dirt"). Tried even to use some regex type stuff like @minecraft &^dirt$ to no avail. My "good reason" to use numerical IDs is it would let me show exactly and **only** what I wanted to see.

**Comment by TehNut** [comment]
JEI's goal is not to clone NEI. Some features will not work exactly the same. Numeric IDs are deprecated and should not be used by anybody for anything. Just get used to using registry names.

**Comment by Ozzymud** [comment]
Right, I've got no worries learning a new way. But the simplest example is proving hard to learn how to do. I want to be able to type in one to X items and only see those exact items I searched for. So in the example of plain old dirt... I have thus far only learned how to get dirt PLUS some other items. Searching for `@minecraft &dirt` does indeed show dirt(`#3/0`), but it also shows coarse dirt(`#3/1`) as well as podzol(`#3/2`). In this particular example it's simple to ignore the extra 2 items. But consider trying to have the items to make some highly tweaked item, like the gated AE certus wrench in IE:E was. There was like a list of more then 10 items in my search, the extra items shown multiplied by 10 would have bee a LOT of items showing that had no relevance to the final item I wanted to craft. I would still be looking through a lot of items that I didn't need to craft instead of seeing just those that applied to my final outcome.  

That is where I made the comparison to NEI as it was easy to explain what I thought was lacking in an item search mod, 4567:8|2155:3|5642:2 would have shown me exactly 3 items without a lot of other garbage items in the results. Currently with all recommendations of how and what to search for, I cannot seem to grasp how to look up "minecraft:dirt:0" and only that one dirt.

**Comment by mezz** [comment]
I think you are trying to use JEI's search function for something it was never really intended to do.

Try using a JEI addon like [Bill of Materials](https://minecraft.curseforge.com/projects/thebomplugin) which seems similar to what you want. You can request features there and help improve that mod. There may be other addons out there that help you track items too.
