### ISSUE TITLE
Search bar is very long

### ISSUE THREAD

**Issue by PeteK85** [mezz/JustEnoughItems#1185]
Can you make search bar little bit shorter than now? Problem is with pixelmon mod, your search bar hide very important parts of pixelmon gui. I try to setup search bar to center or right bottom but its not good. Can you make selecting for position or put search bar to the left bottom or make search bar short???

**Comment by mezz** [comment]
Thanks for the report!
Can you post a screenshot? Maybe something is weird with the way the pixelmon gui is defined.

**Comment by PeteK85** [comment]
i send you photo when i come home from work :)
 
Have a nice day
PETE
 
______________________________________________________________
> Od: mezz <notifications@github.com>
> Komu: mezz/JustEnoughItems <JustEnoughItems@noreply.github.com>
> Datum: 12.04.2018 19:30
> Předmět: Re: [mezz/JustEnoughItems] Search bar is very long (#1185)
>
Thanks for the report!
 Can you post a screenshot? Maybe something is weird with the way the pixelmon gui is defined.
