### ISSUE TITLE
Add the ability to add spaces for list wrap

### ISSUE THREAD

**Issue by pauljoda** [mezz/JustEnoughItems#119]
Like NEI allowed for GUIs with tabs, lets the developer specify areas outside the normal GUI for the list to wrap around

**Comment by mezz** [comment]
The `IModRegistry` passed to your `IModPlugin` now has a method `addAdvancedGuiHandlers` which takes a small class that tells JEI where tabs are located for a specific GuiContainer.

Here's an example implementation: https://github.com/SlimeKnights/Mantle/pull/49

**Comment by pauljoda** [comment]
Awesome. Great job

**Comment by pauljoda** [comment]
Noticed something you may or may not care about with the wrapping change. Wrapping the list works great and I love your implementation; however, I have noticed that the delete area still is there. For instance, we were working with a slot on a tab outside the inventory, when we put the item in the slot it was picked up by your delete item ability. Granted, you have to be in cheat mode but if you are looking for complete wrapping of the JEI interface you may want to consider this. Just a thought

**Comment by mezz** [comment]
Oh interesting. I didn't consider that, definitely a bug. 
Consider a gui that has inventory slots on the side like Thermal Expansion, that would be bad.

**Comment by mezz** [comment]
Fixed in version 2.24.2
