### ISSUE TITLE
Ridiculous Loading times

### ISSUE THREAD

**Issue by CreedV** [mezz/JustEnoughItems#1191]
Just put together my own little pack and the loading times are absurd. It seems to be getting stuck on JEI's part. My friends can launch the pack without this happening.

https://i.imgur.com/Va67B23.png

Sometimes it gets past the recipes only to get stuck further on. 

My CPU usage is at 99% during loading.

Any ideas what could be causing this? Latest version of JEI and forge.

**Comment by CreedV** [comment]
Was able to reduce loading time by uninstalling java and reinstalling. Stopped crash by allocating 6gb RAM.

**Comment by mezz** [comment]
Ah, yeah when you start running out of RAM things get extremely slow.
Try using the foamfix mod as well, it helps reduce the amount of RAM used at startup.

**Comment by CreedV** [comment]
Yeah foamfix was the first thing I tried, it helped loads.
