### ISSUE TITLE
CraftTweaker Integration Doesn't Seem To Work

### ISSUE THREAD

**Issue by KAfable** [mezz/JustEnoughItems#1192]
`mods.jei.JEI.removeAndHide` doesn't seem to work in scripts to hide items.

Sorry if this is redundant, as Jared told me he already mentioned this to you, but I'm mostly making this issue also as a reminder for myself and as an alert to when it might get fixed. 

Example Script:  https://hastebin.com/hevokucema.coffeescript
Crafttweaker Log: https://hastebin.com/oluvaqoyuv.md

Relevant line in the log says in line 166 it is hiding the Immersive Engineering Iron Plate but is still visible ingame.

Thanks!

**Comment by mezz** [comment]
Thanks for the report!
Is this reported to the CraftTweaker github? Please include the url to the issue there so that they are linked.

**Comment by mezz** [comment]
This turned out to be an issue on JEI's side, it's fixed in version 4.9.1
