### ISSUE TITLE
JEI highlighting everything instead of the items from mods you search.

### ISSUE THREAD

**Issue by philip5203** [mezz/JustEnoughItems#1195]
when i search any mod with @ it will highlight everything even from a different mod

**Comment by mezz** [comment]
Thanks for the report!
Can you please post a screenshot so I can see what you mean?

**Comment by philip5203** [comment]
![2018-04-22_13 03 15](https://user-images.githubusercontent.com/38382455/39097682-9c5699ac-462d-11e8-85a4-a07ad763a705.png)

**Comment by mezz** [comment]
Ah thanks. That feature is actually not added by JEI. It's from either More Overlays or NEI, they kind of hack into the JEI search bar to make it work. Please report the issue to them.

**Comment by robzombie91** [comment]
I honestly dont see them fixing the issue on their end. Seems like they abandoned the mod all-together. Also there hasn't been any pr's or forks from other developers to try to fix the issue themselves.
