### ISSUE TITLE
Thermopneumatic Processing Plant's too long name conflicts with JEI's left and right arrows

### ISSUE THREAD

**Issue by Xiaminou** [mezz/JustEnoughItems#1197]
When trying to navigate JEI's recipe for the Thermopneumatic Processing Plant if you want to switch machine with the left and right arrow it will instead click the Thermopneumatic Processing Plant because the name is so long it overlaps with the left and right arrows.

![2018-04-22_13 35 18](https://user-images.githubusercontent.com/8670392/39094591-0a6bbf2c-4632-11e8-8032-eea7831168f8.png)

Notice how it still says Thermopneumatic Processing Plant while I'm hovering over the arrow.
I initially opened an issue for Pneumaticcraft but then I thought this behavior might need to be changed so that machine names that are too long do not overlap over arrows and are instead cut off.

Edit: My GUI scale is Large in case that matters.

**Comment by mezz** [comment]
Thanks for the report.
That's just silly. I'll truncate the name so it fits, it'll look like that on any gui scale.

**Comment by mezz** [comment]
![2018-04-22_12 13 08](https://user-images.githubusercontent.com/916092/39098934-b8d9d0a0-4626-11e8-9bcd-3f35ba951931.png)

Fixed, it looks like this now and you can click the buttons properly.

**Comment by Xiaminou** [comment]
Great, thank you.
