### ISSUE TITLE
Allow blacklisting an entire mod's items

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#120]

**Comment by Prospector** [comment]
Perhaps also just allow blacklisting of all items containing a certain word in their unlocalised name.

**Comment by Prospector** [comment]
Wait is there an option to only whitelisted certain items (effectively blacklisting everything except certain items)?

**Comment by mezz** [comment]
There is not a whitelist, and I don't think blacklist by name is a good idea. I don't want to make this more complicated than it has to be.
