### ISSUE TITLE
Modded Enchanted Books Shuffled / Incorrect

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#1202]
# Versions

Forge: 14.23.3.2655
JEI: 4.9.1.168
Full modlist: https://pastebin.com/7mM64ZDY

# The Issue

The video below best explains it. Enchanted books from other mods are getting scrambled around in JEI, making it impossible to figure out what enchantments are *actually* available and from which mods.

[![Video](https://img.youtube.com/vi/iERSZdoA5-8/0.jpg)](https://www.youtube.com/watch?v=iERSZdoA5-8)

**Comment by oitsjustjose** [comment]
Note: On a new world, everything is fine! This is just an issue in a world where the Registry hasn't been modified (such as mine, where I've removed a few enchantments).

**Comment by mezz** [comment]
Hm unfortunately the enchanted books hold an `int` ID for their enchantment instead of a registry name.
This means that when recipes are being created for JEI before connecting to a server, the IDs mean something different than they do after connecting.
I'm not really sure what the right way to solve this is.

**Comment by CplPibald** [comment]
Do you know what can cause the enchantment lists getting out of sync?  Is there a workaround?  If it's caused by a mod mishandling enchantment IDs, maybe you can suggest how to track down which mod?  Thanks.

**Comment by mezz** [comment]
Before the game loads, JEI figures out what each book is based on their ID (unfortunately there is no other way to do it).
When you connect to a server Forge syncs the IDs to the correct values. If the IDs have shifted on the server from mods being added or removed, the information JEI has cached during loading is wrong.

To work properly, vanilla should write the enchantment's registry name to the book. Instead they are writing the raw ID number. This is basically the only place they are still using the ID like this, so I think it is a mistake.

**Comment by CplPibald** [comment]
So you are saying the (likely) cause of this on a server is adding or removing mods without resetting the map?  Or is it caused by the client having a different mod list than the server?

I wonder if there is a way to delay building (or simply rebuild) the cache of enchantment IDs until after connecting to a server, and then request the data from Forge.  I admit I haven't looked into that part of Forge very much, but I appreciate that it's a difficult problem.

Hopefully the [1.13 Flattening](https://minecraft.gamepedia.com/1.13/Flattening) will solve the problem in the next version by getting rid of IDs (though looking at that page, I don't see anything about enchantments...)  

Thanks for investigating anyway.

**Comment by mezz** [comment]
JEI used to load when you joined the world, but it would cause timeouts if it took too long. Since there's no loading screen there the experience is a lot worse and I had to move things to load earlier.

I have looked at the code in 1.13 and unfortunately this is still an issue there.

**Comment by naqaden** [comment]
Is it possible to load only enchantments upon connecting, or update already-loaded enchantments after connecting? Alternatively, how can I update our server's enchantment IDs to match JEI's without breaking everyone's gear? I'm willing to make some tedious edits to spare my friends this confusion.

**Comment by mezz** [comment]
Unfortunately there is not a very simple solution. The enchanted items are stored all over the place, including in recipes.
I am looking into options like having JEI load on world connection, but with some ability to avoid timeouts.
I am also looking into 1.13 and how we can avoid this issue in the future.

**Comment by Slayer5934** [comment]
I don't know if you might be able to load everything at start and leave enchants out till the world loads? Not sure if that's possible or would work, just an idea I had.

**Comment by axieum** [comment]
Is there a way to remove enchantments from being obtained in loot tables, enchantment tables etc.? I can't seem to find a way, `removeAndHide()` works fine for the JEI GUI, but not physically.

**Comment by SlayerTheChikken** [comment]
@Axieum You should probably ask this somewhere else, this is for the mismatching enchant IDs issue.

**Comment by HenryLoenwind** [comment]
If this was just about the books in JEI, you could remove them and make Enchantments their own Ingredient. That way the'd create the books on-the-fly when being clicked.

Also, it seems books in recipes seem to be ok. At least the Ender IO Enchanter recipes are fine. So it actually may just be the books in the item list...

**Comment by LumberWizard** [comment]
Is it possible to patch it from Forge's side? I doubt any mod has to rely on the numerical ID being stored in the book for anything.

**Comment by naqaden** [comment]
I copied our server for testing and wiped out the enchantments registry so it would rebuild hopefully in the order JEI does it, but it didn't work. Shouldn't it have?
Another idea: could a server-side JEI help the client sort those IDs out on connection?

**Comment by naqaden** [comment]
@HenryLoenwind I tried your suggestion and it solves the search result issue. I'm not familiar enough yet to make it compatible with other mods though. ~~WAWLA for example used to add descriptions to enchanted book tooltips in JEI, but not with this workaround.~~ I have that working properly now [here](https://github.com/naqaden/JustEnoughItems/commit/71a8f7b5389c3b40ac9d3bcfb9d7fdb3d2b9a737).

**Comment by HenryLoenwind** [comment]
That sound good.

About the compatibility, a dynamic recipe for converting between enchantments and enchanted books may just be enough to bridge that. Being dynamic, it'd produce those with the correct runtime IDs. Not the nicest for the player to click through a seemingly nonsensical recipe, but workable.
