### ISSUE TITLE
[1.12.2] Duplicate fuel entries for items with multipe oredict

### ISSUE THREAD

**Issue by Lykrast** [mezz/JustEnoughItems#1203]
Forge : 14-23.2.2654 1.12.2
JEI : 1.12.2-4.9.1.169

I have a simple item that can burn as furnace fuel and has multiple ore dictionary tags for usage in other mods. When the other mods aren't here (and so this item is the only one with those tags) it appears multiple times as furnace fuel in JEI. For context on screenshots: 2 oredicts are from Rustic and 1 from Pam's Harvestcraft.

None of the other mods or Pam's Harvestcraft :
![image](https://user-images.githubusercontent.com/8684850/39273966-bfc4ec58-48e0-11e8-86ca-fa94fa889230.png)

Rustic (none of the 2 oredicted items corresponding to mine are furnace fuels) :
![image](https://user-images.githubusercontent.com/8684850/39274199-7c84b13e-48e1-11e8-9e2f-4d3b99da7bf3.png)

One of the 3 oredict tags removed (no other mods) :
![image](https://user-images.githubusercontent.com/8684850/39274592-ccbd5ae2-48e2-11e8-90bb-221670a69522.png)

[Item's class](https://github.com/Lykrast/MysticalWildlife/blob/master/src/main/java/lykrast/mysticalwildlife/common/item/ItemFuel.java) if that's of any help, but this same class worked perfectly fine with JEI for items that don't have multiple oredict, which leads me to think it's a JEI issue.

**Comment by mezz** [comment]
![2018-04-28_00 16 42](https://user-images.githubusercontent.com/916092/39393401-a502db4c-4a79-11e8-8255-8f1d5704219a.png)

Thanks for the report! Fixed this up so it should work properly now.
