### ISSUE TITLE
Random crash of the game when searching JEI

### ISSUE THREAD

**Issue by arjove** [mezz/JustEnoughItems#1204]
Hi, 

https://gist.github.com/arjove/41365479fc92a60e2e948f66446c76a7

The game crashes randomly when searching in the searchbar. 

Kind regards,

**Comment by mezz** [comment]
Thanks for the report!
This looks like an enderstorage issue, I see you have already reported it to the right place: https://github.com/TheCBProject/EnderStorage/issues/80
