### ISSUE TITLE
About JEI and the crafting book

### ISSUE THREAD

**Issue by Edwinchen1** [mezz/JustEnoughItems#1208]
just wondering why you remove the function of the crafting book in the inventory GUI in version 1.12.2 minecraft, 4.9.1.168 JEI. really annoying.

**Comment by Edwinchen1** [comment]
if ANYONE knows why, please tell me. thanks in advance.

**Comment by way2muchnoise** [comment]
I don't think this is JEI doing this. This was once [requested](https://github.com/mezz/JustEnoughItems/issues/922), but declared out of scope.  
Do you have any other mods installed?

**Comment by Edwinchen1** [comment]
I'm 100% for sure IS the JEI. test process:
1.remove every mod. crafting book works fine.
2. add random mods.such as avaritia , better fps, enderIO and so on. works fine.
3. add JEI&NEI&JER.RECIPES ONLY. NO quick craft.
4. remove JER. still no quick craft.
5. remove NEI. still.
6. remove JEI. PROBLEM SOLVED.
hence, 100% for sure it IS jei causing the issue.
however, it is not a big deal. just really annoying. don't want to be rude, just saying.
and thanks for replying me.

**Comment by KnightMiner** [comment]
I can also tell you JEI does not do this, try with only JEI. It sounds like some mod is disabling the book if JEI is detected.

**Comment by Edwinchen1** [comment]
![image](https://user-images.githubusercontent.com/38850233/39429009-141fc046-4cbc-11e8-862b-04a364f2c0a3.png)
you are 100% right. just as you said, if i delete everything but JEI, the crafting book works well(still looking for which particular one did this and if i find it could you leave a warning on the curse forge? that would be really nice.) . however, i find something funny. it is nothing to do with JEI, just FUNNY. as you can see in the pic, the icon for the crafting book become a brown book and while i mouse over it, it looks really strange(the icon becomes a gap between two books,the green one, as it should be, and the the brown one shown in the pic). again, i don't think it is something to do with JEI, just something funny and i want to show you.

**Comment by Edwinchen1** [comment]
it is the enderio. this mod just like ON FIRE. are you willing to add a warning on the curse forge? that would be really nice.

**Comment by mezz** [comment]
Thanks for the report!
Sorry but this is not from JEI, I really try to avoid making confusing changes like that.

Please slow down a bit next time when reporting, you jumped to some odd conclusions and the way you're writing comes across a bit past enthusiastic and bordering on unhinged :). From personal experience, you will get better responses if you try to stay very technical on github and freely vent about the issue to friends on discord.
