### ISSUE TITLE
JEI shows on screen when booted from server

### ISSUE THREAD

**Issue by Dyonovan** [mezz/JustEnoughItems#121]
https://gyazo.com/0a2e75ba7f0497fcf8e67408e115d003

**Comment by mezz** [comment]
Thanks for the report!
Weird.

**Comment by SDUBZ** [comment]
just thought id let you know this error appeared when loading up Couldn't get ItemModel for itemStack.
java.lang.NullPointerException: null value in entry: None.002=null

**Comment by mezz** [comment]
@SDUBZ is that related to this issue? Please make a new issue with the full log.

**Comment by SDUBZ** [comment]
okay

**Comment by mezz** [comment]
Should be fixed in the latest version (2.19.0.93) by this change: 
https://github.com/mezz/JustEnoughItems/commit/928d7f1b9124407e8d7e4ed6d5c0b64b491e4b08#diff-1bda8fd88faaa8106e6a71fb7c2df1c5L64

Please let me know if you find a way to make it happen again and I can reopen this issue.
