### ISSUE TITLE
add toggle for JEI recipe system taking over the vanilla crafting book

### ISSUE THREAD

**Issue by LemmaEOF** [mezz/JustEnoughItems#1210]
I can understand why putting the JEI recipe system in the place of the vanilla crafting book might be a good idea, but when you're in a pack with thousands of crafting recipes like most kitchen-sink packs do, it's really not very helpful. The advantages to the crafting book are that it can be filtered to only items currently craftable with items in the player inventory, has a search, and doesn't occlude the crafting table itself. Would it be possible to add a toggle for the crafting book takeover? Thank you.

**Comment by Ommina** [comment]
For your comfort and convenience, please see #922, #1005, and #1208.

The latter suggests that EnderIO does some changes to the vanilla crafting book, so if you've recently installed that, it may be a place to start researching.

**Comment by LemmaEOF** [comment]
Huh. Thought I hadn't seen any other issues about the recipe book, but guess there was.
