### ISSUE TITLE
Single player offline chat mode

### ISSUE THREAD

**Issue by zortag** [mezz/JustEnoughItems#1212]
When I play in offline mode (even if i start online then I'll disconnect from internet) i can't switch in cheat mode nor change the searchbar position nor any other option.
There is a workaround?

**Comment by mezz** [comment]
Thanks for the report!
I'm not familiar with "offline mode". Why are you in that mode, and how can I enter that mode to test?

**Comment by zortag** [comment]
just shut down your internet connection for example disconnect the lan cable. by doing that you'll be in offline mode. i'm having issues with my internet provider so i have to play offline and when i'm not logged on mojang jai not responds to option changes. for example i see the cheat mode in the option menu activated but it not works and the wrench don't turn red. it's the sam with other options like the searchbar position. that last is because i found the problem. i'm used to keep the bar in the centre like in nei style and i saw the bar on the right. by investigating about that i realized no one option working and all was set to default. sorry for my bad english, i hope you understand

**Comment by mezz** [comment]
I tried running a single player game and killed my connection, but JEI was not affected at all. 
Have you tried with just JEI and Forge? There may be some other mod that is causing an issue here.

**Comment by zortag** [comment]
no, it appened in a FTB modpack. so maybe the ftb utils pemissions interfere with jei. i'll check mod by mod when i can. thank you
