### ISSUE TITLE
Problem with searching for ore dictionary tags added to items by crafttweaker.

### ISSUE THREAD

**Issue by TeetoKaziim** [mezz/JustEnoughItems#1214]
Forge: 14.23.3.2678
Crafttweaker: 4.1.8
JEI: 4.9.1.173

Overall description of issue:
While working on my modpack, I discovered that I was unable to use the JEI ore dictionary search to find items by searching for their ore dictionary tag, if that tag was one I was adding with crafttweaker. However, I was still able to search for items by their ore dictionary tag if it was one that they had "naturally".

I tried out an instance of minecraft with just Forge, JEI, and Crafttweaker, and couldn't get the issue to reproduce. That is, until **after restarting my minecraft client**. Suddenly, I couldn't find the oredictionary tag I had added to cobblestone again.

Even **more** curious to me, was, that deleting JEI's config folder (``\config\jei``) and starting the client again seemed to fix the issue, that is, until the next time I restarted my client, at which point searching for the ore dictionary tag I had added proved fruitless again.

Steps to reproduce:
* Create a new instance with just JEI and Crafttweaker (versions listed at top).
* Don't start minecraft yet!
* Put the following super rad script into a ``\scripts\`` folder and save it as a text file named ``anything.zs``:
```
<ore:testStoneDictThing>.add(<minecraft:cobblestone>);
```
* NOW start minecraft.
* Go into JEI's configuration menu (the little wrench :3) and go to ``search options`` and set ``$OreDictionary`` to ``require_prefix``.
* Click done and done, and type ``$test`` into the JEI text search box.
* The game should show you cobblestone!
* Save, quit, and exit the game.
* Restart Minecraft.
* Reopen your world.
* Type ``$test`` into the search box again. The game will NOT show you cobblestone, because it is mad.
* Angrily save, quit, and exit the game, and delete the ``\config\jei`` folder in a fit of rage.
* Restart minecraft one last time, to see how JEI feels about that.
* Open your world, type ``$test`` into the search bar.
* JEI is happy to show you cobblestone again! Forgiveness and friendship abound... ``u n t i l t h e n e x t c l i e n t r e s t a r t . . .``

Thankyou for your time, and probably for your patience with my verbosity. The best to you.

**Comment by mezz** [comment]
Thanks for the report!
Have you reported this to crafttweaker as well?

**Comment by TeetoKaziim** [comment]
I ... I suppose I should! And will!

**Comment by mezz** [comment]
I discussed it with Jared and this is now fixed in CraftTweaker
