### ISSUE TITLE
Problem: Caught exception from Just Enough Items (jei)

### ISSUE THREAD

**Issue by Sonikana** [mezz/JustEnoughItems#1215]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

[crash-2018-05-01_21.50.57-client.txt](https://github.com/mezz/JustEnoughItems/files/1965022/crash-2018-05-01_21.50.57-client.txt)

We have the latest version of Minecraft and the mod. Looking forwards to hearing more about the subject.

**Comment by mezz** [comment]
Thanks for the report! This has been fixed in the latest version.
It looks like an ItemStack was crashing when generating its tooltip.
JEI will now log an error with more information, instead of crashing.

**Comment by Sonikana** [comment]
Awesome sauce, we found out that another problem for it. Or our personal problem was that it was not working with ThermalFoundaitons/Expansion.
