### ISSUE TITLE
[1.12.2] Most chisel blocks don't display their color in JEI

### ISSUE THREAD

**Issue by Alan19** [mezz/JustEnoughItems#1216]
Most chisel blocks are not showing their color when color search is enabled in JEI

![2018-04-21_11 14 14](https://user-images.githubusercontent.com/11682762/39085742-2f3aa42c-4555-11e8-93d1-83a4131db014.png)
![2018-04-21_11 14 20](https://user-images.githubusercontent.com/11682762/39085743-2f45d3ba-4555-11e8-84ba-348640bb9741.png)

I've also reported it to Chisel 
https://github.com/Chisel-Team/Chisel/issues/678

**Comment by mezz** [comment]
Thanks for the report!
I looked more into this and it seems to be a Chisel issue. I have replied in the other issue.
