### ISSUE TITLE
JEI Forge Version Issue

### ISSUE THREAD

**Issue by Buttered-Alex** [mezz/JustEnoughItems#1218]
I have the latest version of forge available (14.23.1.2555) however, every time I attempt to run Minecraft  I receive a message that JEI requires 14.23.1.2594, I have no idea as to where I am able to acquire it.
Please help!

**Comment by Buttered-Alex** [comment]
(when I say I have the latest version I mean that when I click the download button on the forge website, 14.23.1.2555 is the version that is downloaded.)

**Comment by MauveCloud** [comment]
Are you sure you're looking at the right website?  http://files.minecraftforge.net/ shows 14.23.3.2678 as the "latest" for MC 1.12.2 and 14.23.3.2655 as the "recommended" as I type this.  Alternatively, maybe you're only looking at the last two digits and just assuming it matches the one you've already got.
