### ISSUE TITLE
Add recipe transfer registration for portable crafting

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#122]
Portable crafting tables, chisels, and other stuff should be able to register themselves as valid recipe transfer targets for the [+] button.

**Comment by Prospector** [comment]
Do you plan to add a way to fill the grid as much as you can with the materials in your inventory? I really don't find the button to be terribly useful if I have to reclick it for every item I want to craft.

**Comment by mezz** [comment]
I'm working on it but it's hard so it's taking a while: https://github.com/mezz/JustEnoughItems/issues/65

**Comment by Prospector** [comment]
Ah alright. No rush, go at your own pace. <3 JEI

**Comment by gr8pefish** [comment]
Mezz, my portable crafting table can use the [+] just fine. I'm not sure if I'm misunderstanding something, but if you mean something like this: you go to say, a furnace in jei, and click the [+] with cobble in your inventory, my crafting table will fill up with 8 cobble in a circle just fine. Code: https://github.com/gr8pefish/PortableCrafting/blob/master/src/main/java/com/gr8pefish/portablecrafting/plugins/jei/JEIPlugin.java#L26

Edit: Ah, unless you mean to register it as a non-vanilla recipe category, in which case carry on.

**Comment by mezz** [comment]
Hm I think I will table this feature, I need to draw the line on how "automatic" JEI is.

**Comment by AEnterprise** [comment]
@mezz related to this an usefull feature could be an api hook to register a container as a valid + button target, not just for crafting.

say a mod adds a JEI recipe handler and an addon makes a machine/table that also uses those same recipes but with added functionality, right now they whould have to add there own handlers (basicly duplicating code)
