### ISSUE TITLE
Wiki page should be updated

### ISSUE THREAD

**Issue by fhntv24** [mezz/JustEnoughItems#1223]
At https://github.com/mezz/JustEnoughItems/wiki/Creating-Plugins , there is this tip:
```Tip: Your plugin can extend BlankModPlugin, so it can override only the sections it needs.```
But in API BlankModPlugin is deprecated, and it's not needed at all because IModPlugin has default impl. of methods.

**Comment by mezz** [comment]
Thanks, I have updated it now.
