### ISSUE TITLE
java.lang.UnsupportedOperationException: Calling old getTooltip is not supported.

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1224]
Hi,

I'm posting this issue on behalf of a friend, who despite having the exact same set of mods as I is running into a crash directly involving JEI. I've got them to try both the release and beta versions of the mod for 1.12.2, to no avail. The issue in question appears to involve the mod attempting to call an outdated method.

- Their latest.log: https://drive.google.com/open?id=1DkqPKuV80M4LErAXnF3w5rVT76kcsiiN
- Their crash report: https://drive.google.com/open?id=1wo5Nv2FM5hGRwzDw85dePE68aWu_QBA3

Unfortunately the text is too big for pastebin, and I don't know how to use gist, so hopefully this will suffice.

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix for this in the next version of JEI (4.9.1.179). Please try it out and let me know if your friend still has an issue.
