### ISSUE TITLE
Problem with java.

### ISSUE THREAD

**Issue by DrLeckyDreams** [mezz/JustEnoughItems#1225]
Hi, I don't know if I can send this to you. But I have a little problem with the Custom NPC mod with Pixelmon. I'm trying to create a pokemon model an all crash.

I hope you can help me.

Sorry its very long!^^

 Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12
.jar)
  FMLPlugin (elulib-0.1.12.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.12
.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/3/18 9:17 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity4Textures.getRealTexture(Entity4Textures.java:120)
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity4Textures.getTexture(Entity4Textures.java:92)
	at com.pixelmonmod.pixelmon.client.render.RenderPixelmon.getEntityTexture(RenderPixelmon.java:477)
	at com.pixelmonmod.pixelmon.client.render.RenderPixelmon.func_110775_a(RenderPixelmon.java:28)
	at net.minecraft.client.renderer.entity.NPCRendererHelper.getTexture(NPCRendererHelper.java:13)
	at noppes.npcs.client.gui.model.GuiCreationEntities.customScrollClicked(GuiCreationEntities.java:106)
	at noppes.npcs.client.gui.util.GuiCustomScroll.func_73864_a(GuiCustomScroll.java:217)
	at noppes.npcs.client.gui.util.GuiNPCInterface.func_73864_a(GuiNPCInterface.java:138)
	at noppes.npcs.client.gui.model.GuiCreationScreenInterface.func_73864_a(GuiCreationScreenInterface.java:123)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity4Textures.getRealTexture(Entity4Textures.java:120)
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity4Textures.getTexture(Entity4Textures.java:92)
	at com.pixelmonmod.pixelmon.client.render.RenderPixelmon.getEntityTexture(RenderPixelmon.java:477)
	at com.pixelmonmod.pixelmon.client.render.RenderPixelmon.func_110775_a(RenderPixelmon.java:28)
	at net.minecraft.client.renderer.entity.NPCRendererHelper.getTexture(NPCRendererHelper.java:13)
	at noppes.npcs.client.gui.model.GuiCreationEntities.customScrollClicked(GuiCreationEntities.java:106)
	at noppes.npcs.client.gui.util.GuiCustomScroll.func_73864_a(GuiCustomScroll.java:217)
	at noppes.npcs.client.gui.util.GuiNPCInterface.func_73864_a(GuiNPCInterface.java:138)
	at noppes.npcs.client.gui.model.GuiCreationScreenInterface.func_73864_a(GuiCreationScreenInterface.java:123)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: noppes.npcs.client.gui.model.GuiCreationEntities

-- Affected level --
Details:
	Level name: MpServer
	All players: 4 total; [EntityPlayerSP['YellowSt0ne'/7, l='MpServer', x=-70.11, y=65.87, z=45.02], EntityOtherPlayerMP['Speedy007_'/154, l='MpServer', x=-63.68, y=66.88, z=39.75], EntityOtherPlayerMP['James51'/98, l='MpServer', x=-61.04, y=67.01, z=45.13], EntityOtherPlayerMP['Denslas'/127, l='MpServer', x=-67.33, y=67.60, z=45.80]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (277,78,270), Chunk: (at 5,4,14 in 17,16; contains blocks 272,0,256 to 287,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 58148048 game time, 141371 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntityCustomNpc['Darkrai'/193, l='MpServer', x=-70.50, y=63.00, z=45.50], EntityOtherPlayerMP['Speedy007_'/145, l='MpServer', x=875.09, y=64.42, z=-794.43], EntityOtherPlayerMP['Mux99'/152, l='MpServer', x=882.21, y=95.00, z=-816.99], EntityOtherPlayerMP['Speedy007_'/154, l='MpServer', x=860.94, y=74.62, z=-761.60], EntityOtherPlayerMP['James51'/98, l='MpServer', x=855.01, y=78.28, z=-764.53], EntityOtherPlayerMP['Speedy007_'/154, l='MpServer', x=-63.68, y=66.88, z=39.75], EntityOtherPlayerMP['Mux99'/179, l='MpServer', x=662.97, y=86.34, z=-444.96], EntityOtherPlayerMP['James51'/98, l='MpServer', x=-61.04, y=67.01, z=45.13], EntityPlayerSP['YellowSt0ne'/7, l='MpServer', x=-70.11, y=65.87, z=45.02], EntityOtherPlayerMP['Speedy007_'/154, l='MpServer', x=-63.68, y=66.88, z=39.75], EntityOtherPlayerMP['James51'/98, l='MpServer', x=-61.04, y=67.01, z=45.13], EntityOtherPlayerMP['Denslas'/127, l='MpServer', x=-67.33, y=67.60, z=45.80], EntityOtherPlayerMP['Denslas'/127, l='MpServer', x=888.31, y=90.92, z=-799.87], EntityOtherPlayerMP['Denslas'/127, l='MpServer', x=-67.33, y=67.60, z=45.80]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 823330320 bytes (785 MB) / 3139436544 bytes (2994 MB) up to 3139436544 bytes (2994 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.26
55 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version           | Source                                  | Signature                                |
	|:------ |:----------------- |:----------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft         | 1.12.2            | minecraft.jar                           | None                                     |
	| UCHIJA | mcp               | 9.42              | minecraft.jar                           | None                                     |
	| UCHIJA | FML               | 8.0.99.99
         | modpack.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge             | 14.23.3.26
55      | modpack.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | elucore           | 1.0               | minecraft.jar                           | None                                     |
	| UCHIJA | quark             | r1.4-123          | Quark-r1.4-123.jar                      | None                                     |
	| UCHIJA | autoreglib        | 1.3-17            | AutoRegLib-1.3-17.jar                   | None                                     |
	| UCHIJA | betterfoliage     | 2.1.10            | BetterFoliage-MC1.12-2.1.10.jar         | None                                     |
	| UCHIJA | betterquesting    | 3.5.253           | BetterQuesting-3.5.253.jar              | None                                     |
	| UCHIJA | bibliocraft       | 2.4.3             | BiblioCraft[v2.4.3][MC1.12.0].jar       | None                                     |
	| UCHIJA | blockcraftery     | 0.1.3             | blockcraftery-0.1.3.jar                 | None                                     |
	| UCHIJA | ceramics          | 1.12-1.3.4        | Ceramics-1.12-1.3.4.jar                 | None                                     |
	| UCHIJA | ctm               | MC1.12-0.2.3.12
   | CTM-MC1.12-0.2.3.12
.jar                 | None                                     |
	| UCHIJA | chisel            | MC1.12.2-0.2.0.31
 | Chisel-MC1.12.2-0.2.0.31
.jar            | None                                     |
	| UCHIJA | controlling       | 3.0.6             | Controlling-3.0.6.jar                   | None                                     |
	| UCHIJA | customnpcs        | 1.12              | CustomNPCs_1.12.2(29oct17).jar          | None                                     |
	| UCHIJA | drpcore           | 0.3.5.4
           | Dark Roleplay Core Alpha-0.3.5e.jar     | None                                     |
	| UCHIJA | drpmedieval       | 0.2.4.3
           | Dark Roleplay Medieval Alpha-0.2.4c.jar | None                                     |
	| UCHIJA | dsurround         | 3.4.9.12
          | DynamicSurroundings-1.12.2-3.4.9.12
.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA | presets           | 3.4.9.12
          | DynamicSurroundings-1.12.2-3.4.9.12
.jar | None                                     |
	| UCHIJA | earthworks        | 1.3.4.3
           | Earthworks-1.12-1.3.6.jar               | None                                     |
	| UCHIJA | elevatorid        | 1.3.6             | ElevatorMod-1.12.2-1.3.6.jar            | None                                     |
	| UCHIJA | fairylights       | 2.1.2             | fairylights-2.1.2-1.12.x.jar            | None                                     |
	| UCHIJA | cfm               | 4.1.5             | furniture-4.1.5-1.12.2.jar              | None                                     |
	| UCHIJA | journeymap        | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar             | None                                     |
	| UCHIJA | moreplayermodels  | 1.12.2            | MorePlayerModels_1.12.2(18jan18).jar    | None                                     |
	| UCHIJA | pixelmon          | 6.2.3             | Pixelmon-1.12.2-6.2.3-universal.jar     | None                                     |
	| UCHIJA | reauth            | 3.5.2             | ReAuth-3.5.2.jar                        | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCHIJA | signpost          | 1.06.1            | signpost-1.12-1.06.1.jar                | None                                     |
	| UCHIJA | variedcommodities | 1.12.2            | VariedCommodities_1.12.2(06nov17).jar   | None                                     |
	| UCHIJA | wanionlib         | 1.12.2-1.5        | WanionLib-1.12.2-1.5.jar                | None                                     |
	| UCHIJA | elulib            | 0.1.12            | elulib-0.1.12.jar                       | None                                     |
	| UCHIJA | unidict           | 1.12.2-2.5b       | UniDict-1.12.2-2.5b.jar                 | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12
.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.12
.jar)
  org.blockartistry.DynSurround.asm.Transformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.31' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.26
55
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz

**Comment by TehNut** [comment]
This is an issue tracker for JEI. You don't even have JEI installed.

**Comment by DrLeckyDreams** [comment]
ok... That's true I'm sorry. I'm new on this web site.^^

tell me where to put my message?

**Comment by mezz** [comment]
Thanks for reporting bugs!
Please report this to pixelmon here: http://pixelmonmod.com/tracker.php?p=2&sid=b443da106f22d3b0fc76df7bd23aea2b
