### ISSUE TITLE
wierd issue while loading up with jei

### ISSUE THREAD

**Issue by SDUBZ** [mezz/JustEnoughItems#123]
full log had to be put on dropbox due it being to big for pastebin etc but important part of log is this line Couldn't get ItemModel for itemStack.
java.lang.NullPointerException: null value in entry: None.002=null
full log https://www.dropbox.com/s/ow9klkyxfmxxxyn/fml-client-latest.log?dl=0

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/109 and https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues/93
It looks like it should be fixed in the next version of Buildcraft.

**Comment by axzxc1236** [comment]
Just want to report same bug here lol.
I can confirm this can happen with Buildcraft,Chisel,Chisel&Bits and JEI install at the same time.
