### ISSUE TITLE
Ingredient list is no longer shown from 4.9.1.180.

### ISSUE THREAD

**Issue by koh-gh** [mezz/JustEnoughItems#1231]
Hi, I play in Japanese, and up to 4.9.1.179, it was possible to show ingredient list even if recipe is open. But from 4.9.1.180, it is impossible to show ingredient list when recipe is open, even though there is a width to show it. (Only config button is shown)

Please change to show ingredient list like a past version, if there is a width.

**Comment by mezz** [comment]
Thanks for the report!
I have tried running the game in Japanese but I do not see this bug.

![2018-05-14_20 57 05](https://user-images.githubusercontent.com/916092/40035960-75552dee-57b9-11e8-9d49-2b069bab280a.png)

Can you try with only JEI and Forge?
Maybe a screenshot will help too.

**Comment by mezz** [comment]
Thanks for the report!
I have set my game language to Japanese but I can not see this bug.

![2018-05-14_21 01 39](https://user-images.githubusercontent.com/916092/40036049-048ad572-57ba-11e8-807b-c8d5752edb4e.png)

Can you try with just JEI and Forge? Maybe another mod is causing an issue.

**Comment by koh-gh** [comment]
Sorry. It was short of words. My "recipe" means "vanilla recipe book", not "JEI recipe". Add some screenshots.

![2018-05-15_17 57 17](https://user-images.githubusercontent.com/36918206/40047287-153e4dd0-586a-11e8-99b0-e58f70ecbb83.png)
It's 4.9.1.179.

![2018-05-15_17 59 04](https://user-images.githubusercontent.com/36918206/40047329-2da3c120-586a-11e8-9e27-02ed245f64ba.png)
It's 4.9.1.180.

It may depend on screen resolution.

**Comment by mezz** [comment]
The minimum size for JEI right now is 4 columns, I think it was 3 before.
With only 3 columns the top part is not readable.
If your screen is a little wider or your gui size is set differently, JEI will fit.

**Comment by koh-gh** [comment]
I understood that this is as expected.
I'm a little sad, but thank you for your reply.
