### ISSUE TITLE
JEI catalyst still shown when staged

### ISSUE THREAD

**Issue by codetaylor** [mezz/JustEnoughItems#1232]
I'm not sure if this falls in the domain of JEI or ItemStages.

Cross posted from: https://github.com/Darkhax-Minecraft/ItemStages/issues/20

### What

When I log into a new world with zero stages unlocked, most, but not all, staged recipe catalysts are hidden by JEI properly. Hiding recipe categories when all their crafting catalysts are hidden was introduced in JEI v4.9.0.

I am able to consistently reproduce this issue with the HorsePower mod's `<horsepower:chopper>`. When I log in with zero stages unlocked, the catalyst remains visible:

![2018-05-16_12 55 20](https://user-images.githubusercontent.com/1240716/40140756-8de7607a-5908-11e8-9c24-79d96f057a9a.png)

If I run the command `/gamestage add @p artisan` then the command `/gamestage clear @p`, the catalyst disappears and is displayed (or rather *not* displayed) as expected:

![2018-05-16_12 56 09](https://user-images.githubusercontent.com/1240716/40140770-92f2ea6c-5908-11e8-8b59-30f40721d83e.png)

### Versions

* MC: 1.12.2
* Forge: 14.23.3.2675
* GameStages: 1.12.2-2.0.90
* ItemStages: 1.12.2-2.0.35
* JEI: 1.12.2-4.9.1.187

**Comment by mezz** [comment]
Thanks for the report! This seems like a JEI issue but I'm not entirely sure.

I have a `debugModeEnabled` config flag in `jei.cfg`. When you hover over an item with that enabled, it will show the UID that JEI uses internally to reference that item.
I am guessing the UID for the catalyst items does not match the UID of the items in the full list for some reason, so only one gets hidden.

Can you get two screenshots, one of that tooltip for the chopper catalyst and another of the tooltip for the same item in the item list?

**Comment by codetaylor** [comment]
Sure thing.

Here is a shot of the catalyst with zero stages unlocked:

![2018-05-17_06 56 41](https://user-images.githubusercontent.com/1240716/40182274-e0c7d580-599f-11e8-994b-b1ee5384e659.png)

Here is a shot of the catalyst item in the item list after running the command `/gamestage add @p artisan`:

![2018-05-17_06 57 59](https://user-images.githubusercontent.com/1240716/40182293-f2ddcaae-599f-11e8-833b-133c01f3e248.png)

**Comment by codetaylor** [comment]
I have some additional context:

* The [catalyst is registered](https://github.com/GoryMoon/HorsePower/blob/1.12/src/main/java/se/gory_moon/horsepower/jei/HorsePowerPlugin.java#L80) by Horse Power without metadata or tags.
* The [getSubBlocks method](https://github.com/GoryMoon/HorsePower/blob/1.12/src/main/java/se/gory_moon/horsepower/blocks/BlockHPChoppingBase.java#L147) for the chopper returns, at minimum, six chopper items with different tag data to describe each variant of vanilla log.
* I have used CraftTweaker's `mods.jei.JEI.removeAndHide()` to remove the six tagged choppers.
* I have staged the tagless chopper item with ItemStages.
* I have added a staged recipe using the ArtisanWorktables mod that is set to output the Horse Power chopper item with no metadata and no tags.

The following lists the entries in my remove and hide array:

```javascript
  // horsepower
  <horsepower:chopper>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 0 as short}}),
  <horsepower:chopper>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 1 as short}}),
  <horsepower:chopper>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 2 as short}}),
  <horsepower:chopper>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 3 as short}}),
  <horsepower:chopper>.withTag({textureBlock: {id: "minecraft:log2", Count: 1 as byte, Damage: 0 as short}}),
  <horsepower:chopper>.withTag({textureBlock: {id: "minecraft:log2", Count: 1 as byte, Damage: 1 as short}}),
```

The following is the ArtisanWorktable's recipe for the chopper:

```javascript
// horsepower chopper
builder()
  .setShaped([
    [<minecraft:lead>, <ore:stickWood>, <minecraft:lead>], 
    [<ore:plankWood>, <ore:artisansHandsaw>, <ore:plankWood>], 
    [<ore:plankWood>, <horsepower:chopping_block>, <ore:plankWood>]
  ])
  .addTool(<ore:artisansFramingHammer>, 16)
  .addOutput(<horsepower:chopper>)
  .create();
```

**Comment by codetaylor** [comment]
I have been able to get the desired behavior by doing the following:

* Fork Horse Power and change the catalyst registration to use the tagged oak variant.
* Use CraftTweaker's `mods.jei.JEI.removeAndHide()` to remove all choppers but the tagged oak variant.
* Change the ItemStages staged item to the tagged oak variant.
* Change the ArtisanWorktable recipe to output the tagged oak variant.

The catalyst remains hidden with zero stages unlocked:

![2018-05-17_07 46 01](https://user-images.githubusercontent.com/1240716/40185085-a4f56e4e-59a6-11e8-9387-df97f5aedf7e.png)

The catalyst is displayed as expected after running `/gamestage add @p artisan`:

![2018-05-17_07 46 59](https://user-images.githubusercontent.com/1240716/40185112-b592f6e0-59a6-11e8-8efb-a9138cef22a4.png)

I'm taking a wild stab here, but maybe JEI doesn't recognize the tagless item as an ingredient because it is never returned by the `getSubItems` method. Perhaps it does recognize it after adding the stage because ItemStages explicitly calls `IIngredientRegistry#addIngredientsAtRuntime`.

**Comment by codetaylor** [comment]
I've tested my theory by creating a utility that allows me to use CraftTweaker to add ingredients to JEI. When the CrT scripts are run, it aggregates ItemStacks in a collection, then passes the collection to `IIngredientRegistry#addIngredientsAtRuntime` during the call to `IModPlugin#onRuntimeAvailable`.

```javascript
import crafttweaker.item.IItemStack;

var itemsToAdd as IItemStack[] = [
  <horsepower:chopper>
];

mods.JEITweaks.addItemsAtRuntime(itemsToAdd);
```

When I explicitly add the ingredient this way, everything works as expected with the tagless version of `<horsepower:chopper>`.

I feel like this is more of a Horse Power problem because of the discrepancy between the catalyst and the actual item (or ingredient). Ensuring a correlation between the catalyst and item isn't the responsibility of JEI, and I don't think it's a problem that could be reliably solved in JEI's domain either.

I have found a solution that satisfies my requirements. Please feel free to close this issue at your discretion and thank you for your time. :)

**Comment by mezz** [comment]
Ok thanks. It looks like you're right in your analysis and this has been resolved.
I don't see a clear way to prevent this type of problem in JEI and I don't think it will come up very often, so I will just close this issue.
