### ISSUE TITLE
Bug with Geolosys coal variants

### ISSUE THREAD

**Issue by darthvader45** [mezz/JustEnoughItems#1234]
It seems that Geolosys coal variants are all labeled with burn times of 2400, even though oitsjustjose says they should be tiered.  Any confirmation of this bug, and if so, has it been fixed?

**Comment by mezz** [comment]
Thanks for the report!
I tested with the latest versions of JEI (4.9.1.187) and Geolosys (1.9.2) and they display with the correct burn time in JEI's fuel recipes. Can you confirm?

**Comment by darthvader45** [comment]
Will check, but my personal favorite world has corrupted and I'll need to get a new world running as fast as possible.  Will be exhausting, but worth it in the end.

Edit:  It works.  Thanks so much, the next release should have this fix, right?

**Comment by mezz** [comment]
Cool. I did some minor changes to the way fuel times are done last month so it should be fixed in the most recent versions.
