### ISSUE TITLE
[1.12.2] Lots of errors with Calculator

### ISSUE THREAD

**Issue by C0rn3j** [mezz/JustEnoughItems#1235]
Log: https://haste.c0rn3j.com/raw/tafudageso

Files: 
forge-1.12.2-14.23.3.2702
jei_1.12.2-4.9.1.187
calculator-1.12.2-5.0.4
sonarcore-1.12.2-5.0.9.jar

Unsure if this is JEI or Calculator fault, reporting on both repos.

Highlight from the log: 
```
[main/ERROR] [jei]: Failed to register mod plugin: class sonar.calculator.mod.integration.jei.CalculatorJEI
```

**Comment by mezz** [comment]
Thanks for the report!
This is a Calculator issue. I will close this issue but they should feel free to ask me if they have any questions about it.
