### ISSUE TITLE
Mod Name Drawn For Recipe Tabs When Disabled

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#1238]
Attempting to remove the mod name from JEI tooltips still draws it in recipe tab tooltips as unformatted text. The description of the Mod Name Format config indicates that leaving it blank should disable the tooltips entirely, so this is a bug.

**JEI version:** [1.12.2-4.9.1.186](https://minecraft.curseforge.com/projects/jei/files/2562113)

![screenshot](https://i.imgur.com/HLIowIP.png)

**Comment by mezz** [comment]
Thanks for the report, fixed in the next version.
