### ISSUE TITLE
Crash During loading with Mining well disabled.

### ISSUE THREAD

**Issue by any1seenjoe** [mezz/JustEnoughItems#124]
In objects.cfg, is     B:miningWellBlock=false Game will not load.

**Comment by TehNut** [comment]
This sounds more like a Buildcraft issue than a JEI one...

**Comment by AEnterprise** [comment]
depends, can you provide a crashlog?

**Comment by wlhlm** [comment]
I can reproduce this crash, but it is independent of whether JEI is installed or not.

Please report here: https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues
