### ISSUE TITLE
[1.12.2-4.9.2.195] Ghost slot dragging function is still active when you close the GUI and crashes when clicked in a non implemented "Ghost GUI"

### ISSUE THREAD

**Issue by Buuz135** [mezz/JustEnoughItems#1245]
JEI: 1.12.2-4.9.2.195
Forge: 1.12.2-14.23.3.2685

When you are dragging an item and you close the gui you keep dragging the item and clicking again it crashes the game.

Issue: https://streamable.com/z3grf

The crash: https://gist.github.com/9f7099539ee0e68d1eac5cfd5721a88c

**Comment by mezz** [comment]
Thanks for the report!

The crash seems to be caused be `target.getArea()` returning null. 
Your mod implements the target, so I think at least part of this bug may be on your side?

I will look into fixing the issues with JEI not ending the ghost drag when the GUI closes.
