### ISSUE TITLE
JEI/Reborn Core Crash with jei_1.12.2-4.9.2.195.jar and RebornCore-1.12.2-3.8.4.288 - reborncore.common.powerSystem.forge.ForgePowerItemManager.setEnergyInStack

### ISSUE THREAD

**Issue by NanoHeart** [mezz/JustEnoughItems#1246]
I got this crash while loading the newest version of JEI (Beta) and Reborn Core

https://gist.github.com/NanoHeart/e1caddd98592c6ada72d47572a11923c

I also get this crash with the newest and the last stable releases on curse

**Comment by mezz** [comment]
Thanks for the report!
I think this is an issue with Reborn Core, I will link to the issue there and subscribe to it so discussion is in one place:
https://github.com/TechReborn/RebornCore/issues/86
