### ISSUE TITLE
Disable Items for Clients

### ISSUE THREAD

**Issue by portres** [mezz/JustEnoughItems#1248]
Hello
First of all i would like to thank you for this great mod. I know that for myself I can use Item hide mode to not see stuff like Chisel or other unnecesary stuff. But once I have done this, is there a way that when I transfer my Modpack via Export in Twitch to my friends  that they will have the same Items?
Thank you already! Would be great because my Pack has 560 Pages and once Disabling the unwanted things only 180.

Best Regards
Portres

**Comment by mezz** [comment]
Hello,
The hidden items are saved to a config file automatically so that you can distribute it with your pack.
You can find the config at `config/jei/itemBlacklist.cfg`.
