### ISSUE TITLE
JEI Cannot search for items

### ISSUE THREAD

**Issue by Anguriaboy** [mezz/JustEnoughItems#1249]
Thank you for reporting!
I updated the latest version of jei_1.12.2-4.9.2.196.jar today，Found that the search items cannot use。The search item configuration has been completely opened, but it is still unusable.
![error](https://user-images.githubusercontent.com/39192846/40730367-1211aeb0-6461-11e8-84b6-024200b9add3.jpg)
![error1](https://user-images.githubusercontent.com/39192846/40730376-14fb70e8-6461-11e8-82ef-95c1935d4303.jpg)
![error2](https://user-images.githubusercontent.com/39192846/40730389-19a11486-6461-11e8-9c8a-415dc6635188.jpg)

**Comment by mezz** [comment]
Thanks for the report!
Have you tried with only JEI? I think another mod may be causing this issue.

**Comment by Anguriaboy** [comment]
@mezz Yes, I only used JEI, but there will be no problem before updating。

**Comment by Anguriaboy** [comment]
Any progress? I tried to use jei_1.12.2 -4.9.1.188, which is searchable.   However, opening the Synthesis of certain items will cause the problem of the number of frames dropped.

**Comment by mezz** [comment]
Do you know which version this problem started on? I have not found anything that would cause this.

**Comment by Anguriaboy** [comment]
@mezz I tested it one by one starting from version jei_1.12.2 -4.9.1.188 and found that jei_1.12.2 -4.9.1.192 made it impossible to search. Including the latest version of jei_1.12.2 -4.10.0.198 can not be searched.

**Comment by mezz** [comment]
I am testing on the latest version and I do not see an issue:

![2018-06-12_21 42 51](https://user-images.githubusercontent.com/916092/41330661-9e442ff2-6e89-11e8-89da-f3706efacf85.png)
![2018-06-12_21 42 26](https://user-images.githubusercontent.com/916092/41330662-9e5c6d60-6e89-11e8-8fdb-b963b5d1e0ab.png)

Please try removing all mods except JEI. I know there are some addons for JEI for searching more conveniently in Chinese, maybe it broke with my update.
