### ISSUE TITLE
Enhancement: Dropdown for mod filter.

### ISSUE THREAD

**Issue by Thiana** [mezz/JustEnoughItems#125]
It would be nice if we could have a dropdown somewhere with the list of installed mods. Selecting the mod in the dropdown would insert @&lt;modname&gt; into the search filter. 

Thanks.

**Comment by mezz** [comment]
The mod name search is a lot easier to type than in NEI, just type `@thaum` and you'll get Thaumcraft.

**Comment by Thiana** [comment]
I know, but that presumes you know the ingame name of the mod. For example if you see FRSM-1.5.50-1.8.9.jar in mods/, you'd expect `@fsrm` to show you it's items. In game though you'd have to search for `@Fex`

Plus sometimes you don't remember which mod an item belongs to but seeing the mod name triggers your memory.

Thanks.

**Comment by Prospector** [comment]
You can click ESC and go to Mods to view the mod list in game.

**Comment by Thiana** [comment]
Additionally for overlapping mod names, ie Random {Things, Utilities}, Fex's Random Stuff Mod. @Random is going to bring up all 3 mods. With the dropdown we wont have to type a long string in manually. Which once the multitude of thaumcraft mods start rolling over us is going to be more important.

**Comment by Prospector** [comment]
I like the idea, but it's not particularly important IMO.

**Comment by Thiana** [comment]
@TheDoctorSoda Actually I think that would only be a partial solution. (a) it's slows you down with the extra steps and (b) it presumes that the filename has some relation to the ingame name which isnt always the case.

And no, not particularly important yet but as we get more mods sharing similar names it becomes more an more annoying not having the feature.

**Comment by mezz** [comment]
You can also do stuff like `@rand @thin` and get random things.
Also it searches the mod id as well as the friendly mod name.
