### ISSUE TITLE
[4.9.1.188] Firework and Firework Star recipes missing

### ISSUE THREAD

**Issue by Sinxar** [mezz/JustEnoughItems#1250]
I just noticed the recipes for the Firework and Firework Stars (vanilla) are not viewable with JEI.

I tested this with JEI and Forge 2705, no other mods. There may be more but I am unsure as these are the only 2 I have come across that don't work ingame.

Thanks for you time.

**Comment by TehNut** [comment]
#91

**Comment by Sinxar** [comment]
Whoops sorry. I searched for the wrong thing.
