### ISSUE TITLE
[Server crash] GuiScreen

### ISSUE THREAD

**Issue by Discomanco** [mezz/JustEnoughItems#1251]
EDIT: May have found a cause, and it may not be JEI's fault directly (or at all) - will post updates as testing progresses
EDIT2: Seems to be caused by ExtraUtilities "Find Item in Inventories", when it actually finds something, or searches a lot of inventories around it

Sometimes, when searching in JEI, it can cause a server crash with GuiScreen. It seems very random what you have to search for, to cause it. Although `Bucket` seems to be pretty consistent. It will not cause a loop-crash (luckily), and will still show the results normally after the server has come up again.
We're not on the latest version, so it may be fixed already (haven't had a chance to update yet), but I haven't seen any reports of it.
https://pastebin.com/b9dtvNhq

MC 1.12.2
Forge .2689
JEI: 4.9.1.187

**Comment by mezz** [comment]
Thanks for the report!
I will close this since it seems to be an ExtraUtilities issue.
