### ISSUE TITLE
Minecraft crash cuz JEI

### ISSUE THREAD

**Issue by MOMO10002** [mezz/JustEnoughItems#1253]
I got the jei_1.12.2-4.9.2.196
my forge is forge-1.12.2-14.23.4.2705

I installed the JEI for the notenoughtitems mod. I got the codechickenlib but the issue isnt with that.

the Jei cuz me crash every time I am trying to open the mc...
https://gist.github.com/MOMO10002/cfbbbe2b9c6919c88c7fa1f37055140e

I Cant play now beause of this bug. what Can I do is the JEI not working with forge?

**Comment by MOMO10002** [comment]
can you tell me what version of the Jei works with forge-1.12.2-14.23.4.2705-installer-win
or with forge-1.12.2-14.23.4.2707-installer-win.

thats rly annoying bug you have with forge and now I cant play so thats not fun...

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
