### ISSUE TITLE
More wiki and API inconsistencies

### ISSUE THREAD

**Issue by fhntv24** [mezz/JustEnoughItems#1254]
At https://github.com/mezz/JustEnoughItems/wiki/Recipe-Category-Crafting-Items#implementation wiki suggests using `modRegistry.addRecipeCategoryCraftingItem`, witch is deprecated in API.
And at https://github.com/mezz/JustEnoughItems/wiki/Creating-Plugins doesn't list registerCategories .

https://github.com/mezz/JustEnoughItems/wiki/Recipe-Handlers is fully deprecated.

p.s. Is wiki really needed? Almost everything is in javadocs. Isn't it just better to generate GH pages from javadocs, and just add more stuff to it (If I'm not mistaking, you can add full static pages to it ) ?

p.s.s. Also, as it doesn't state anywhere in docs: Are IRecipeWrapper instances that IRecipeRegistryPlugin return's being saved anywhere ? I'm creating dynamic lookup, cuz recipe's are being loaded from server, and I don't know how "safe" it is.

**Comment by mezz** [comment]
Please feel free to edit the wiki when you see something outdated or wrong, it should be open to editing.

The wiki is not needed, it is intended as a gentle introduction for setting up gradle, and to give kind of an overview of how things fit together. The javadocs will always be more accurate and up-to-date.

`IRecipeWrapper` instances are kept around internally. They are generally all created at loading-time, and when you look something up it will return the same exact ones.
