### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by lebanni** [mezz/JustEnoughItems#1255]
I clicked on Basic Induction Cell from Mekanism and minecraft client crashed.

[crash-2018-06-05_00.30.30-client.txt](https://github.com/mezz/JustEnoughItems/files/2070174/crash-2018-06-05_00.30.30-client.txt)
[latest.log](https://github.com/mezz/JustEnoughItems/files/2070178/latest.log)

**Comment by mezz** [comment]
Thanks for the report!
It looks like this has been reported to Mekanism here: https://github.com/aidancbrady/Mekanism/issues/5069
I do not think it is a JEI issue, so I will close this one and follow the Mekanism issue in case something comes up.
