### ISSUE TITLE
Crash when searching for item

### ISSUE THREAD

**Issue by vrork** [mezz/JustEnoughItems#1257]
i have gotten this crash a few times with different search terms. Follow the logs:
Crash Report --> https://gist.github.com/vrork/c8722d07a75c3256d92991214224e581
latest.log --> https://gist.github.com/vrork/705d943b148fd7f0745705c89f2d4104
debug.log --> Attached (file too big)

Versions:
Minecraft: 1.12.2
Forge: 14.23.4.2707
JEI: 4.9.2.196

[debug-1.log.gz](https://github.com/mezz/JustEnoughItems/files/2082432/debug-1.log.gz)

Edit: just got a crash when trying to open the inventory in the same world
Edit2: Seems to be happening everytime something that should appear the name cobalt on screen
Edit3: seems to be a problem with Vanilla Fix. Going to link it there

**Comment by Runemoro** [comment]
Yes, this is a problem with VanillaFix. The texture optimization code is assuming that `quad.getSprite()` for all quads in all items, which is apparently not always true.

**Comment by mezz** [comment]
Thanks for the report!
Since this is a VanillaFix issue I will close this one and subscribe to the main issue there.
