### ISSUE TITLE
Startup crashing

### ISSUE THREAD

**Issue by el1xlv** [mezz/JustEnoughItems#1258]
For issues:
https://paste.feed-the-beast.com/view/a2e4f73d

**Comment by TehNut** [comment]
I had this issue reported to me a couple times. It's caused by the new Forgelin versions.

**Comment by Zenvioux** [comment]
Thank you. I was trying so many different mod combinations to find the culprit.

**Comment by mezz** [comment]
Thanks for the report!
Please subscribe to the Forgelin issue here: https://github.com/shadowfacts/Forgelin/issues/38
