### ISSUE TITLE
Client Crash on Rendering IC2 Ingredient

### ISSUE THREAD

**Issue by KAfable** [mezz/JustEnoughItems#1262]
https://hastebin.com/amuwarekoh.rb

**Comment by mezz** [comment]
Thanks for the report!
"I blame mezz, author of Just Enough Items." Interesting!

Please report this to IC2 here: https://bt.industrial-craft.net
At first glance it looks like a coremod is affecting the rendering and causing the crash when it encounters the IC2 item. I do not think JEI is involved in this one.

**Comment by Chocohead** [comment]
This, and #1268 for that matter, are from a bug within Vanilla Fix that has since been fixed.

**Comment by mezz** [comment]
Thanks @Chocohead. Do you have a link to the Vanilla Fix issue?

**Comment by Chocohead** [comment]
It's DimensionalDevelopment/VanillaFix#73, which also means these are both also duplicates of #1257
