### ISSUE TITLE
Weird Box on JEI

### ISSUE THREAD

**Issue by CluelessPhil** [mezz/JustEnoughItems#1264]
I've recently started developing a modpack and JEI has been... odd.
![capture](https://user-images.githubusercontent.com/14302401/41408575-25213098-6fa1-11e8-8bb2-f2ddfd2659cb.PNG)

**JEI: 4.10.0.198**
**Minecraft: 1.12.2**
**Forge: 14.23.4.2708**
### **Other Mods Present:**
> McJtyLib (by McJty)
> EFab (by McJty)
> Baubles (by azanor)
> Botania (by Vazkii)
> Astral Sorcery (by HellFirePvP)
> Guide-API (by TehNut)
> Blood Magic (by WayofTime)
> Thaumcraft (by azanor)
> Custom Main Menu (by lumien231)
> Resource Loader (by lumien231)
> Mantle (by mDiyo)
> Tinkers Construct (by mDiyo)
> CraftTweaker (by jaredlll08)
> Inventory Tweaks (by Kobata)
> MTLib (by jaredlll08)
> ModTweaker (by jaredlll08)
> Morpheus (by Quetzi)
> Mouse Tweaks (by YaLTeR97)
> The One Probe (by McJty)
> TOP Addons (by DrManganese)
> OpenModsLib (by OpenMods)
> Better Advancements (by Way2muchnoise)
> BNBGamingLib (by BloodNBonesGaming)
> BnBGamingCore (by BloodNBonesGaming)
> Triumph (by BloodNBonesGaming)
> Tinkers' Tool Leveling (by bonusboni)
> Tinkers Survival (by wendall911)
> No Mob Spawning on Trees (by oldjunyi)
> Cucumber Library (by BlakeBr0)
> Mystical Agriculture (by BlakeBr0)
> Mystical Agradditions (by BlakeBr0)
> Traverse (by ProfessorProspector)
> Just Enough Items (JEI) (by mezz)
> FTBLib (by FTB)
> FTB Utilities (by FTB)

```

**Comment by mezz** [comment]
Thanks for the report!
This is normal, I made some small changes to the UI recently.
