### ISSUE TITLE
Crash whilst editing with hide ingredients mode

### ISSUE THREAD

**Issue by Rongmario** [mezz/JustEnoughItems#1265]
https://paste.ee/p/ZNzfb

**Comment by mezz** [comment]
Thanks for the report!
It looks like this is an issue with a BuildCraft item, please report to them here: 
https://github.com/BuildCraft/BuildCraft/issues
```
-- Ingredient being rendered --
  Ingredient Mod: BC Transport
  Ingredient Info: 1xitem.PipeStructureCobblestone@0 buildcrafttransport:pipe_structure
```

There is also a second crash that happened inside VanillaFix after the BuildCraft rendering crash.
It's pretty complicated but isn't the cause of the problem you're having. I reported it to them here: https://github.com/DimensionalDevelopment/VanillaFix/issues/78
