### ISSUE TITLE
"Hide Ingredients" mode

### ISSUE THREAD

**Issue by Pyromanc3r** [mezz/JustEnoughItems#1266]
Combination Ctrl+Click and Ctrl+Right click not working. Namely the combination "Ctrl+". In this mode, you can hide items simply by right-clicking or left-clicking.
In this case, you can not take the items from jei before disabling "Hide Ingredients" mode. On the version jei_1.12.2-4.9.2.196 it was all OK

Minecraft 1.12.2
Forge 14.23.4.2705
jei_1.12.2-4.10.0.199

**Comment by mezz** [comment]
Thanks for the report!
Sorry I still need to look into this. At one point I was planning to change the hotkeys around along with the tooltip explanation. I thought I removed those changes but it sounds like I made a mistake somewhere.

**Comment by ghost** [comment]
Before I open another issue, is this the same where it is no longer possible to see the recipes when you are in "hide" mode? Since clicking on an item now hides it (opposed to ctrl-clicking).

**Comment by mezz** [comment]
Yes, this is the same problem.

**Comment by mezz** [comment]
This is fixed in the latest versions of JEI for 1.16, 1.17 and 1.18.
