### ISSUE TITLE
Jei is missing a mod that it depends on please help I really need this mod idk what to do

### ISSUE THREAD

**Issue by DarKkt** [mezz/JustEnoughItems#1267]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
The message means you need to add the missing mod. 
JEI only depends on Forge, so I assume you are using an old version of Forge and need to install a new one.

**Comment by DarKkt** [comment]
I use 1.12.2 - 14.23.4.2708 forge for 1.12.2 minecraft and here is all my mods I have 

Animania 1.12.2-1.4.3.jar

cfm-4.20-mc1.12.2.jar

Craftstudio-1.0.0.93-mc1.12-alpha.jar

Doggy+talents-1.12.2-1.14.2.317-universal

DrZharks Mocreatures mod- 12.0.4.jair

iChunUtil-1.12.2-7.1.4.jar

Mo'-Ores-And-Tools-Mod-1.12.2.jar 

Morph-1.12.2.jar

And           Torohealth-1.12.2-11.jar

**Comment by mezz** [comment]
Please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by DarKkt** [comment]
Never mind, the problem has been resolved I just did a tutorial and installed the same exact versions he installed and it's working fine.
