### ISSUE TITLE
Crash after trying to view fluid recipe

### ISSUE THREAD

**Issue by AdeptusAutumn** [mezz/JustEnoughItems#1268]
I crash after trying to view recipes for fluids.
Heres the crash https://gist.github.com/MrCreeperAG/fa769e6915ceb215c38fc34d5423332a

**Comment by mezz** [comment]
Thanks for the report!
It looks like a coremod is affecting the rendering of an IC2 item. It's not clear what mod is involved.
Please report this to the IC2 issue tracker here: https://bt.industrial-craft.net

**Comment by mezz** [comment]
This turned out to be a VanillaFix bug:  DimensionalDevelopment/VanillaFix#73
