### ISSUE TITLE
Inventory Highlight Not Going Away

### ISSUE THREAD

**Issue by RanaktheGreen** [mezz/JustEnoughItems#1269]
![2018-06-18_18 28 07](https://user-images.githubusercontent.com/40374286/41568847-61225ac2-7325-11e8-932c-9922c4d44acd.png)
So, the search box is yellow, and my inventory has highlighted spaces for things which match the search terms. I do not know how I turned this on, but in the settings I found nothing about how to turn it off.

**Comment by KnightMiner** [comment]
Double click is typically how you turn it off. It is not a JEI feature though, an addon (NotEnoughWidgets, NEI, etc.) adds the behavior.
