### ISSUE TITLE
[Suggestion] Config to enable Cheat mode when switching to creative mode

### ISSUE THREAD

**Issue by Razorskills** [mezz/JustEnoughItems#127]
I would like to see a config option that you could enable where when you switch to creative mode, it would also enable cheat mode. then when you switch back to survival or adventure mode, it would disable cheat mode. Might be a good default option, or perhaps not. That is up to you.

If you do not agree, then close this. :)

**Comment by mezz** [comment]
Hm sorry I couldn't come up with a way to do this without making it a bit confusing. 
I'm not sure it's a very needed feature.

**Comment by Prospector** [comment]
Plus you don't need to be opped to be in creative mode.
