### ISSUE TITLE
Some items are missing/invisible

### ISSUE THREAD

**Issue by Rydial** [mezz/JustEnoughItems#1271]
I only have about 30 mods including JEI, without NEI or FEI

I play on a forge modded server with exactly the same mods, though the server has one extra mod: spongeforge

So when I search things up for Tinker's Construct, it doesn't show any of the stations or parts of tool. If I hover my mouse over where they should be when I search them up, the name pops up but without the image of the item. 

I use a vanilla redstone resource pack.

Please help me solve this!

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
