### ISSUE TITLE
Just Enough Items is not displaying in my inventory

### ISSUE THREAD

**Issue by Flyer818** [mezz/JustEnoughItems#1272]
![pic](https://user-images.githubusercontent.com/40511405/41805451-a7fd475a-7667-11e8-89c1-7ca22323bb90.png)

Whenever I open my inventory, Just Enough Items is not showing in the right hand side of my screen. When I go into the mods settings, nothing will get it to reappear. Is there a certain key I need to press to enable it again? If it helps, I am currently running your mod through the Farming Valley modpack, and Minecraft Forge is what is running all my mods. Please help! Thanks, -Flyer818

**Comment by Flyer818** [comment]
Oh, i figured out what was wrong. I just needed to press a button.

**Comment by andreassando** [comment]
Just so I don't have to ask the same question again....what button did you have to press? :)
I have the same problem.
