### ISSUE TITLE
[1.12.2] Strange Interaction

### ISSUE THREAD

**Issue by Draskh** [mezz/JustEnoughItems#1276]
Maybe this is the wrong place to report this but I'm not sure which mod causes the issue. When I right click on a steel ingot (Thermal Foundation) in JEI the game crashes. There is more than one mod involved. 
https://gist.github.com/Sanofus/b5df74905457338a0d534cb5c73a398a

**Comment by TehNut** [comment]
Downgrade Forge until Chisel updates.

**Comment by mezz** [comment]
Thanks for the report!
Here's the cause of the crash: https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
