### ISSUE TITLE
Crash when using "show uses" for the "Tin Dust"

### ISSUE THREAD

**Issue by iBattery355** [mezz/JustEnoughItems#1277]
I don't really know what happened.
Just find that when I use "show uses" for "Tin Dust" no matter which mod it comes from, such as IC2 or TE, the game crashes.

Report:
[OpenEye] - http://openeye.openmods.info/crashes/c021106d14a7c0eff9f9291feb9cde37
[Minecraft Launcher] - https://gist.github.com/iBattery355/59ce7a3ee7119ebc37db76121f98d246

**Comment by TehNut** [comment]
Downgrade Forge until Chisel updates.

**Comment by iBattery355** [comment]
@TehNut 
Thanks! After downgrading to forge-14.23.4.2710, no crash again.

**Comment by mezz** [comment]
Thanks for the report!
Here's the cause of the crash: https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
