### ISSUE TITLE
Crash when looking up uses of Endstone (re-post from FTB Revelation Issue tracker)

### ISSUE THREAD

**Issue by tfox83** [mezz/JustEnoughItems#1278]
**Issue : Crashing when pressing u while hovering over endstone

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/aa4dc800

Original Issue: https://github.com/FTBTeam/FTB-Revelation-2/issues/39

**Comment by mezz** [comment]
Thanks for the report!
Based on the crash, this seems like an ExtraUtilities2 issue.
I tried to replicate it in the 2.1.0 version of the FTB Revelation pack but it didn't crash.
