### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by MagmaMagi** [mezz/JustEnoughItems#1279]
java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap

while reading the change log it states you switched to fastutil from trove  looks like you missed something. this same error happens on all crafting tables (tinkers,vanilla, refined storage crafting grid, wireless...) when the item I want to craft is clicked it crashes before the screen that pops up that you have to click to send it to the crafting grid..

**Comment by TehNut** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
