### ISSUE TITLE
TiCon Crafting Station Recipe Completion Bug

### ISSUE THREAD

**Issue by shadowfacts** [mezz/JustEnoughItems#128]
When using the JEI `+` button to fill in a recipe in a Tinker's Construct Crafting Station (_connected to a chest_), JEI says there are missing items unless all the required items are inside the chest, not in the player's inventory. If the Crafting Station is not adjacent to a chest, the recipe completion works fine using items in the player's inventory.

Reproducible using:
- Mantle 1.8.9-0.6.jenkins70
- TConstruct 1.8.9-2.0.1.jenkins50
- JEI 1.8.9-2.19.0.93

cc @bonii-xx

**Comment by bonii-xx** [comment]
Might need special casing in the crafting transfer handler thing

**Comment by mezz** [comment]
Since the slots for the player inventory shift depending on if there's a chest or not, you will have to implement an `IRecipeTransferInfo` to handle it. Only slightly harder than what's there, it's just to get the correct slots based on container.

**Comment by mezz** [comment]
Closing this, should be fixed by the PR above ^

**Comment by tetious** [comment]
This seems to be broken again, at least with the latest (current) versions of the mods:

- Mantle-1.10.2-1.1.3
- TConstruct-1.10.2-2.6.1
- jei_1.10.2-3.13.6.389

**Comment by KnightMiner** [comment]
Due to itemhandler limitations, we had to disable this feature to prevent a crash with placing items in slots they are not allowed. In any case, it is still fully on Tinkers side.
