### ISSUE TITLE
Catalysts registered with a wildcard show null category icon

### ISSUE THREAD

**Issue by axieum** [mezz/JustEnoughItems#1281]
I have recently setup a category of crafting for my mod, and I have a single Block which allows crafting however it does have variants. As a result, by using `OreDictionary.WILDCARD_VALUE` it works appropriately in the sidebar, etc. (with changing textures), but the icon just shows a purple/black missing texture.

Perhaps, just show the first variant, or allow an item stack to be returned in the `getIcon()` method?

**Comment by mezz** [comment]
Thanks for the report!
I think it's good practice to override `getIcon()`.
Since JEI 4.9.1 you can use `IGuiHelper#createDrawableIngredient` to easily make a drawable from an ItemStack and return that for `getIcon()`.

**Comment by axieum** [comment]
That's great, by using that method I was able to get it working!

Thanks for the quick reply 👍
