### ISSUE TITLE
JEI Crash when looking at EnderIO Paint Registry With Shift Key Held

### ISSUE THREAD

**Issue by drobt** [mezz/JustEnoughItems#1287]
When holding shift and right clicking on the EnderIO Painting Machine recipes the game will crash. This was done on Fluiducts and Itemducts from Thermal Expansion. 

Reproducable: Yes (With and without optifine.)

Crashlog: https://gist.github.com/Zenorant/affdc5e94ccae71cb4883ee88a5f4365

**Comment by mezz** [comment]
Thanks for the report!
Please report this to EnderIO here: https://github.com/SleepyTrousers/EnderIO/issues/new
