### ISSUE TITLE
Strange behavior w/ Liteloader

### ISSUE THREAD

**Issue by NotMyWing** [mezz/JustEnoughItems#1288]
Hey!

Possible duplicate of #1189. Here's the [log](https://github.com/mezz/JustEnoughItems/files/2172929/latest.zip).

I was trying to set things up for a private server based on Enigmatica modpack, but unfortunately ran into seemingly endless pre-mainmenu loading lock caused by JEI/Liteloader (...well, at least logs say so). This only happens if I add Liteloader as a mod/library. Removing Liteloader helps, but I really don't want to ditch mods I'd otherwise love to play with.

I tried
* downgrading Liteloader
* downgrading JEI
* adding Liteloader as a library instead of dropping it into /mods
* running Minecraft with ONLY Liteloader, few Liteloader mods and JEI present (could load the game!)

The game itself doesn't crash, but it doesn't stop wasting disk space, and eventually gets stuck loading.
I can narrow down the mod list if needed, though it'd take a lot of time; my laptop isn't the best.

**Comment by NotMyWing** [comment]
Narrowed it down.

Turns out the whole issue was caused by [FastWorkbench](https://minecraft.curseforge.com/projects/fastworkbench), which apparently has nothing to do with JEI.

The issue apparently has nothing to do with JEI as well, then.

**Comment by Shadows-of-Fire** [comment]
This issue appears to be caused by LiteLoader's incompatibility with forge registry replacements.  I don't know anything about how LiteLoader functions, but based on a couple issues, it does not play nice with registry replacements, as it also has issues with Diet Hoppers when any mod references the hopper.

**Comment by NotMyWing** [comment]
I have noticed a bunch of weird interactions between Liteloader and Forge mods before, and this time we had to disable FastWorkbench to play with these few mods we can’t play without. It would be nice to see this issue getting resolved in future, ~~but that’s probably Mumfrey’s job~~.

**Comment by mezz** [comment]
Thanks for the report!
I have looked into this a lot more and submitted a bug for it to LiteLoader here:
http://develop.liteloader.com/liteloader/LiteLoader/issues/53
