### ISSUE TITLE
JEI crashes when searching some letter-combinations

### ISSUE THREAD

**Issue by jannik2103** [mezz/JustEnoughItems#1289]
Hello there, 
when using the search-function from JEI, after typing in some combinations like...: ‚sol.....‘ ‚res......‘ ‚ul.....‘ the game closes without any error or something else. 
The same happens when scrolling through the pages from JEI. In my case it freezes after page 67+, another player got the issue after page 54, and so on. There was the carmod, that crashed when looking at these page. After deleting the mod it was bibliocraft, the next one in the row after our carmod. Im sure the version of our carmod + bibliocraft are OK, they seem to be stable...

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by jannik2103** [comment]
Hi Mezz, i found out that this is an issue we‘re expieriencing when using the mod ‚Carpenter‘s Blocks‘. I think it‘s not a bug housemade by JEI. I‘ll look up the report later and will attach it here. 
Carpenter‘s Blocks is for 1.12.2 still a developer-Version and carrys tons of bugs.... thanks for your reply!

**Comment by tazznl** [comment]
got same problem with Jei, no carpentersblocks in modpack. any solution to this problem? also crashing when scrolling through pages.

**Comment by mezz** [comment]
@tazznl please open a new issue, and include your crash log (pasted to gist.github.com) so I can take a look.

**Comment by tazznl** [comment]
> @tazznl please open a new issue, and include your crash log (pasted to gist.github.com) so I can take a look.

It is solved. ATM3 modpack has old(er) CTM mod what causes the problem
