### ISSUE TITLE
Issues setting up to make an addon

### ISSUE THREAD

**Issue by The-Fireplace** [mezz/JustEnoughItems#129]
When modifying build.gradle so I could add JEI support to a mod, the first issue I encountered was with useDepAts = true
"no such property: useDepAts for class: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated"
When I tried changing it to useDepAlts = true, the same thing happened. So I tried just removing that line and continuing, and it failed because of access denied.
http://paste.ubuntu.com/14568236/
Any chance you could fix that/update your instructions?

**Comment by way2muchnoise** [comment]
A paste or link of your build.gradle? Also version of gradle / forgegradle ?

**Comment by shadowfacts** [comment]
The instructions are correct.

`useDepAts = true` needs to be inside the `minecraft` block of the build.gradle [like so](https://github.com/shadowfacts/CraftingSlabs/blob/1.8.9/build.gradle#L30-L37).

You also need to add the Maven repository in the `repositories` block ([here](https://github.com/shadowfacts/CraftingSlabs/blob/1.8.9/build.gradle#L66-L69)).

**Comment by The-Fireplace** [comment]
Thanks, shadowfacts. I have updated my build.gradle after looking at yours. The Access Denied error was because I was putting the maven section next to the Forge maven section, instead of making a new repositories{} area
