### ISSUE TITLE
JEI Crash During Modpack Load

### ISSUE THREAD

**Issue by CluelessPhil** [mezz/JustEnoughItems#1290]
Crash because game likes them.

_Gist: **https://gist.github.com/DaggerTM/5a418719ad367fe26101694b6ea80d77**
Minecraft: **1.12.2**
Forge: **14.23.4.2732**
JEI: **4.11.0.202** 
YABBA: **1.1.2.11**
Astral Sorcery: **1.9.3**_

**I will be reporting to YABBA & Astral Sorcery I will link this issue.**

**I don't believe YABBA and/or Astral Sorcery are the problems, they're just in the area telling what caused the issue.**

**Comment by mezz** [comment]
Thanks for the report!
This seems to be a YABBA issue, it happens even without JEI: https://github.com/LatvianModder/YABBA/issues/91
