### ISSUE TITLE
Hiding/Adding Items at Runtime are Executed in the Wrong Order

### ISSUE THREAD

**Issue by SnowShock35** [mezz/JustEnoughItems#1291]
Hi @mezz,

I believe that I have encountered an issue with Just Enough Items (JEI). The following issue report details environment setup as well as a description of the issue and steps to reproduce it. 

### Environment Details

* Java 1.8.0_171 (64-bit)
* Minecraft 1.12.2
* Minecraft Forge 14.23.4.2732
* Just Enough Items (JEI) 4.11.0.202
* Additional Mods
  * CraftTweaker 4.1.9.486 (Tested w/ 4.1.9 - public release)

### Issue Description

I was attempting to remove all AE2 Facades from JEI. The simplest way for me to do this was through CraftTweaker, as I wanted to keep at least one facade and add a tooltip to it as well as a JEI description). However, upon restarting the game and loading up a world, I did not find the facade I had added in after removing them all in JEI.

To ensure that this wasn't an issue with other mods or NBT data I decided to attempt it in an instance with the two mods listed above and instead of removing facades I just used stone (The example I used can be found of the CraftTweaker documentation page [here](http://crafttweaker.readthedocs.io/en/latest/#Mods/JEI/JEI/).)

However, after multiple attempts and trying various tweaks and ordering of the script I was still unable to get this to work. 

My first thought was to speak with the author of CraftTweaker, @jaredlll08. After speaking to Jared about the issue and having him try a few things (hence the custom build from his build server being used) I still wasn't able to get the item to be removed then re-added.

Jared seems to think that the issue here is:
> "Hiding items at runtime is done after adding items at runtime, causing custom items to be hidden"

Personally, I cannot really know how or what is causing the issue however it's definitely something I feel should be resolved as without it would be disappointing as there are a lot of use cases for this sort of feature.

### Steps to Reproduce the Issue

In order to reproduce this issue, create a Minecraft 1.12.2 instance with Forge 14.23.4.2732 installed. Be sure to also add JEI and CraftTweaker to the mods folder and leave configurations at default. (Builds for both mods can be found on CurseForge.)

1. Launch the game once after environment setup and then close it down once you reach the main menu.
2. Open up the instance directory, navigate to the scripts directory and create a new file called script.zs.
3. Proceed to open the said file in your favourite text editor.
4. Copy and paste the first code snippet listed below into this script, save and close the script.
5. Load up the game and create a singleplayer world
6. Once in-game, open up the inventory and look through JEI for the item. You'll see that the item isn't listed anywhere.
7. Now going back to your instance directory you can check both the `crafttweaker.log` and `logs/latest.log`. In the CraftTweaker log you'll notice the statements in the script are being executed in the correct order. However, if you then proceed to check the `latest.log` you'll notice that the statements are reversed - it adds then removes the items. Meaning that the item you're adding is being added. However, it is then removed again. 

*** 

Code snippet to add to script for instruction 4 above. (This example is taken directly from the CraftTweaker documentation.) 

```
mods.jei.JEI.hide(<minecraft:stone>);
mods.jei.JEI.addItem(<minecraft:stone>.withTag({display:{Name: "Pickle",Lore:["What once was stone", "Is stone no more"]}}));
```

### Issue Attachments

I've enclosed copies of both my logs and my script file via pastebin.com links below. 

* [script.zs](https://pastebin.com/GZYznutR)
* [crafttweaker.log](https://pastebin.com/Z6yktz1D) - ln6-7
* [latest.log](https://pastebin.com/erJ6rbJL) - ln85-86

**Comment by jaredlll08** [comment]
Just going to add, in the custom version he is using, I remove items first, and then add them after that for loop as ran

**Comment by mezz** [comment]
I submitted a fix for this in AE2 here: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/3750
It should be fixed in the latest version, let me know if you run into similar issues.
