### ISSUE TITLE
1.10.2 don`t work with other mod`s

### ISSUE THREAD

**Issue by vesafra** [mezz/JustEnoughItems#1292]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Do you have an issue to report? I do not understand what you mean.

**Comment by vesafra** [comment]
don`t work with tooMachItems

**Comment by liach** [comment]
Can you post a crash report?
