### ISSUE TITLE
there is not enough space to display jei here

### ISSUE THREAD

**Issue by Dragonslayer1265** [mezz/JustEnoughItems#1293]
I use the twitch installer. and as soon as i installed another mod pack my just enough items wont work across the board. any fixes for this? or do i have to delete some modpacks?

**Comment by Dragonslayer1265** [comment]
hmm it seems that it just wouldnt work with my screen size.. does anyone know of a way to ajust invitory size manually so jei will work?

**Comment by mezz** [comment]
You can change your GUI Scale in Minecraft's Options, in the Video Settings section.
By default it is set to "Auto" which usually makes the GUI very large.
Set it to a smaller size and JEI will have enough room on your screen.
