### ISSUE TITLE
JEI Not Displaying Everything

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1295]
I have JEI installed on an FTB modpack I play with friends on a self-hosted server. I run the server on my computer in the background while I play on the server with my friends. I've been having issues with it not displaying all items from a mod, not just a single mod. I've seen the same kind of issue posted here where items aren't showing up from various mods, including multiplayer and singleplayer. I know that its not anything to do with config because my friend has 100+ pages of items and the exact same settings and I have only 91. The recipes still work, I just need my friend to tell me what they are. JEI and its configs are installed in the server folder. Same items don't show up in singleplayer.

I will provide answers to any questions, thank you for your time.

**Comment by mezz** [comment]
Thanks for the report!

Measuring by pages isn't always accurate. Different screen resolutions, window sizes, gui scales, and even the gui you have open will affect the number.

Also, check your config blacklist to see if you have some items hidden on your client config. That config will not be in sync with your friend's config if it has been changed by either person, the server does not control it.
If you still believe you are missing items, please try to find an item that one of you has but not the other, then we can start to narrow down what might be going wrong.
