### ISSUE TITLE
cobblestone "uses" crash

### ISSUE THREAD

**Issue by redgoblin88** [mezz/JustEnoughItems#1296]
when in creative (or survival) you press "u" over cobblestone to see what it can be used for, i crash. this has not only happened on my personal pack but also on my friends modpack

if you would like a list of mods or the other (public) modpack where this bug also occurs just ask :)

here is the crashlog posted on Gist (as requested)

https://gist.github.com/redgoblin88/d73bd8e300385b3aad4394150c3532a9

JEI version: 11.0.202
 Forge version: 14.23.4.2727

**Comment by mezz** [comment]
Thanks for the report!
This looks like it's a crash from FactoryTech, please report it here: https://github.com/dalapo/FactoryTech/issues
