### ISSUE TITLE
JEI finding something in mystcraft causing crash

### ISSUE THREAD

**Issue by NicosaurusRex99** [mezz/JustEnoughItems#1297]
1.12.2

For issues:
 *https://paste.dimdev.org/fobadiqibu.mccrash
https://github.com/XCompWiz/Mystcraft-Issues/issues/259#issuecomment-404966975

**Comment by mezz** [comment]
Thanks for the report!
This is probably caused by `jeivillagers` and JEI, I'll take a look.

**Comment by mezz** [comment]
This seems to be working fine with Mystcraft 0.13.5.00 and JEI 4.11.0.204.
Please try updating your mods and see if you still have this issue.

**Comment by NicosaurusRex99** [comment]
can confirm has been fixed since i posted the issue
