### ISSUE TITLE
Add CraftTweaker method for hiding a catalyst

### ISSUE THREAD

**Issue by axieum** [mezz/JustEnoughItems#1298]
When disabling machines or "catalyst" items from the game, when a mod doesn't remove it's recipes (such as Thermal Expansion), the catalyst/category still shows. It would be nice to be able to remove/hide a catalyst/tab/category so it doesn't show impossible recipes.

E.g. `mods.jei.JEI.hideCatalyst(<*>);`

**Comment by TehNut** [comment]
JEI does not add CrT support. This would be on Jared's end.

**Comment by axieum** [comment]
Ah, sorry, I'll head over there.

**Comment by axieum** [comment]
It is noted that in order for CraftTweaker to do such thing, will require an exposed method in Just Enough Item's API.
