### ISSUE TITLE
Minecraft carpet crash

### ISSUE THREAD

**Issue by mxnmnm** [mezz/JustEnoughItems#1299]
forge-1.12.2-14.23.4.2705
Jei-4.11.0.204

I looked up the uses for minecraft carpet and it caused me to crash...
The crash report is naming lots of mods so I chose this one because it's the one I was using.

https://paste.dimdev.org/qifufulemi.mccrash

If this is not an issue belonging to jei please tell me which mod so i can report it there, thanks!

**Comment by mezz** [comment]
Thanks for the report!
I don't think this is a JEI issue.
Try reporting to EnderIO, maybe their `PaintUtil.isValid` should try to catch errors. They should have a better idea of who to report to if this is not their bug. https://github.com/SleepyTrousers/EnderIO/issues

**Comment by mxnmnm** [comment]
it's the betweenlands that caused the issue and they already fixed it in a dev version so i guess it's just a waiting game until they release the update completely
