### ISSUE TITLE
crash when starting single player server

### ISSUE THREAD

**Issue by LlubNek** [mezz/JustEnoughItems#130]
JEI crashed when entering a newly created world.  Minecraft went to the main menu instead of exiting to the launcher.

Here's the log:
http://pastebin.com/YPm1u7k6

**Comment by iarspider** [comment]
Just the error, without tons of BS facade messages: http://pastebin.com/sC2ej3vC

**Comment by LlubNek** [comment]
this seems to happen only with RFTools Dimensions (rftoolsdim-1.8.9-4.20beta11.jar).

**Comment by iarspider** [comment]
No, doesn't happen with beta 22. Looks more like a change in the latest (1709) Forge.

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with obfuscation and java 8 lambda functions. I think it's still being worked on by ForgeGradle.
I will catch this error in JEI instead of crashing, at least until the underlying problem gets fixed (I'm sure some other mod will run into this issue).
