### ISSUE TITLE
Pressing 'u' on Cobblestone, possibly others crashes client.

### ISSUE THREAD

**Issue by kreezxil** [mezz/JustEnoughItems#1301]
**Description**
Pressing 'u' while looking at Cobblestone crashes client.

In the following crash report the initial culprit appears to be SecurityCraft. I have reported it there first. However, they use Google Docs for bug reporting and therefore there is no way to cross link the report.

The 2nd part in the Crash is Ender IO. I have reported it there and the rather huge report thread on it can be found at https://github.com/SleepyTrousers/EnderIO/issues/4755

This is a client crash, my dedicated server remains unaffected.
Client Crash Report: https://pastebin.com/aPvgw1Mx

Possible related crash reports:
https://github.com/mezz/JustEnoughItems/issues/1294

**Comment by iKurama** [comment]
Does removing any recipe-changing mod fix it? For me it appears to be related to the scripts. What I mean about that, is, if the scripts don't match yours on-the-dot, it will crash you. Singleplayer would work perfectly, fine, correct?

Edit: Think of it like this:
The server doesn't want you to see specific items, but your clientside wants to, but the server denies you, resulting in a loop and will crash you.

**Comment by kreezxil** [comment]
I tested it single player since my players were reporting it in multiplayer. So it's happening whether you connect or not.

However, that's a good idea. I'll temporarily remove crafttweaker and see what happens.

**Comment by kreezxil** [comment]
I just tried what you suggested iKurama and disabled my crafttweaker and I still crashed.

https://pastebin.com/GULYpMbM

**Comment by kreezxil** [comment]
gonna see if i can disable that block logger that's in securitycraft and see if that helps.

**Comment by kreezxil** [comment]
Nope, there's no way to disable that. Ok, i'll try without SecurityCraft and see what happens.

**Comment by kreezxil** [comment]
**SUCCESS**, removing security craft solved this issue for me. For those that don't know or are just getting here. While this might be something you are experiencing in another pack, we are experiencing it own my own mod pack [World of Dragons](https://minecraft.curseforge.com/projects/world-of-dragons). This wasn't an issue a few releases back on the pack. The ideal thing is that SecurityCraft issues an update, but they are slow on the dev and bugfix cycle, so I'll be moving backwards until I find a version that works without bugging out.

I'll leave this open just in case there is something Mezz can do. If Mezz can't do anything then I don't mind if it is closed.

**Comment by iKurama** [comment]
The bug appears on Foolcraft 3 as well, with some of the same mods included. This varies from ExU to EnderIO to Thaumcraft. How the bug is spread all around is a wonder.

**Comment by kreezxil** [comment]
Security Craft just released a fix on their end. I'll be testing it shortly. @iKurama check to see if Security Craft is in Foolcraft 3.

**Comment by iKurama** [comment]
It isn't. I've seen other mod issues for other mods with the same Usage bug. https://pastebin.com/KutmCmG7 Here's mine for reference (EnderIO). These look alike. Then I got one around ExU https://pastebin.com/fPZ1VuhW. All of these happened on a sponge (unsupported, I know, but they still happen without it) server.

**Comment by mezz** [comment]
Thanks for the report!
I do not try to work around rendering crashes because it can often leave the game in a bad render state. The best thing to do is to have the crashing mod release a fix, which is what happened here, so I will close this issue.
Please make sure to report issues to the mods that are crashing.
