### ISSUE TITLE
Ingredient List Overlay Crash

### ISSUE THREAD

**Issue by Peter04101998** [mezz/JustEnoughItems#1302]
i would theorize that an over mod has a broken recipe that is returning a invalid response.
the crash would happen wile or very soon after loading the world.

[crash-2018-07-20_23.02.13-client.txt](https://github.com/mezz/JustEnoughItems/files/2215641/crash-2018-07-20_23.02.13-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This seems to be an issue with LegibleNei, please report it to them here: https://minecraft.curseforge.com/projects/legiblenei/issues

**Comment by Peter04101998** [comment]
thank you for your response, now reported to Davenro
