### ISSUE TITLE
Crash when pressed "U" over invar ingot

### ISSUE THREAD

**Issue by SlyyJacob** [mezz/JustEnoughItems#1303]
My client crashes whenever I press "U" over invar ingot. 
In the log it mentions this item being the cause: net.minecraft.item.ItemBlock@3af7fe01
No idea what mod that comes from, no idea how to find out either, sorry.
Log: https://gist.github.com/SlyJacobTheBeast/bb99e500685d45dae88f9f39002fe8f7

**Comment by mezz** [comment]
Thanks for the report!
I'm not sure what the cause is here, but it might involve CodeChickenLib.
Please report the issue to them here: https://github.com/TheCBProject/Feedback/issues

**Comment by SlyyJacob** [comment]
https://github.com/TheCBProject/Feedback/issues/27#event-1747022345
I was told that someone's model is broken and nothing they can do about it.
Do you know how I could trace down which model is causing it?

**Comment by mezz** [comment]
Hmm based on the crash report I don't have enough information. I'll push a new version of JEI that tries to gather more information when it crashes here.

**Comment by mezz** [comment]
Please try with JEI `4.11.0.205` and reply here with your log like before.

**Comment by SlyyJacob** [comment]
https://gist.github.com/SlyJacobTheBeast/5ff4e4b7a616787d52f00442837600d6
Ok here it is. It looks like it's FactoryTech mod then (pipe), right?
Edit: just read your referenced issue, which confirms my question. Thank you, I will have to remove the mod factorytech.

**Comment by mezz** [comment]
Cool, glad that works.
Please report this issue to FactoryTech on their issue tracker so they can fix it: https://gitlab.com/dalapo/FactoryTech/issues
