### ISSUE TITLE
Cannot view usages and recipes when a ghost click handler is set

### ISSUE THREAD

**Issue by raoulvdberge** [mezz/JustEnoughItems#1307]
![x](https://drive.google.com/uc?id=1ZTydZgvMsEP6B3Fwo2mlEurUUMqK6fSU)

I expect the ghost click handler to kick in when I'm dragging, not just when I'm clicking.

`jei_1.12.2:4.11.0.204`

**Comment by mezz** [comment]
Fixed in JEI version 7.3.2 for 1.16.2

**Comment by raoulvdberge** [comment]
Thank you mezz. That was a satisfying TODO to remove. :D 

https://github.com/refinedmods/refinedstorage/commit/c621a16ab3d3d94be3926e72a77aba2636197e6c
