### ISSUE TITLE
Crash while attempting to look up recipes

### ISSUE THREAD

**Issue by thederpykrafter** [mezz/JustEnoughItems#1309]
Not sure if JEI is causing this but it didn't start happening until I updated JEI.

Crash happened on 3 separate occasions looking up different recipes/uses each time (only have logs from 2 of them)

https://pastebin.com/d8ASSsqM 
(while looking up the recipe for (cant remember but it was something from EnderIO) in player inventory)

https://pastebin.com/B57X14xa 
(while looking up uses for cobblestone while in the pattern terminal for Refined Storage)

If JEI is not causing this can you please tell me which mod is so i can report it to the correct author(s)?

**Comment by mezz** [comment]
Thanks for the report!
I don't think this is a JEI issue.
Try reporting to EnderIO, maybe their `PaintUtil.isValid` should try to catch errors. They should have a better idea of who to report to if this is not their bug. https://github.com/SleepyTrousers/EnderIO/issues
