### ISSUE TITLE
Request a 1.7.10 Branch

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#131]
This mod is awesome but it is only for 1.8.9 ... can you also port it to 1.7.10

**Comment by KnightMiner** [comment]
There already exists NotEnoughItems for 1.7.10, and I doubt mod authors who write for 1.7.10 want to add support for two interface mods.

**Comment by TehNut** [comment]
#77

**Comment by mezz** [comment]
It would be a very uphill battle to get mod support on 1.7.10, I don't think I will make a 1.7.10 version.
