### ISSUE TITLE
Crashes while finalizing minecraft loading...

### ISSUE THREAD

**Issue by xXDe4dLyV1PeRXx** [mezz/JustEnoughItems#1310]
Tried to load up minecraft and below shows what happened after it got through the final phases of launching minecraft aka completing minecraft initialization

[crash_image](http://oi65.tinypic.com/zy9bex.jpg)

Crash Log:

[crash log](https://paste.dimdev.org/obirisoxah.mccrash)

Now i went an opened my latest.log with Notepad ++ and hit control + F and typed [main/ERROR] and between lines 2146 and 178478 and it was telling me that their basically were recipes missing or corrupt with several mods shown below,

[crash_image_2](http://oi68.tinypic.com/iv94wp.jpg)

latest.log

[latest.log](https://github.com/mezz/JustEnoughItems/files/2238244/latest.log)

i will say this i looked somewhere and someone said that it has incompatibilities with four mods i have in my mod folder, i took JEI out and it loaded just fine, i then put it back in and it crashed the same way i was trouble shooting this issue all night last night after around 5PM EST

current mods installed

[current mods](http://oi65.tinypic.com/i42r28.jpg)

i hope this helps to solve any issue JEI might be having for the community! :)

**Comment by mezz** [comment]
Thanks for the report!
There is a known incompatibility with LiteLoader right now, reported here: https://github.com/mezz/JustEnoughItems/issues/1189
As a workaround until that is fixed, you can downgrade JEI to version 4.8.

**Comment by xXDe4dLyV1PeRXx** [comment]
thx for the tip and dont mind the duplicate post i did see the others of the same similar issue i was jus sharing my issue as well helpin as best as possible to fix these issues as everyone in the community would like them to be fixed lol :)
