### ISSUE TITLE
Crash with legiblenei

### ISSUE THREAD

**Issue by h3oCharles** [mezz/JustEnoughItems#1312]
https://gist.github.com/KarBoy2314PL/7e23a09c7a1730b097c8c2776938e714

plz help

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1302
The issue has been reported to legiblenei here: https://minecraft.curseforge.com/projects/legiblenei/issues/11
