### ISSUE TITLE
CRASH WHEN RIGHT CLICKING ON ENDERIO POWERED SPAWNER

### ISSUE THREAD

**Issue by tonimark** [mezz/JustEnoughItems#1314]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here:enderIO
 * Remove NEI and FEI to see if they are causing the issue before reporting:nope no nei or fei installled
 * If you crashed, please paste the crash log to  and link it here:https://gist.github.com/tonimark/9e2e86b83dcf6d7762b2ae447e80ba04
crash when right-clicking on powered spawner in ender io section "to see what can be crafted with" the game just crash log is up to 3rd <*>

**Comment by TheRealDadbeard** [comment]
For me most of right clicking items crashes instantly.

**Comment by mezz** [comment]
Thanks for the report!
Please update to JEI `4.11.0.205` or higher and report back with the new crash log. It will give more information about the item that is crashing while rendering.

**Comment by TheRealDadbeard** [comment]
Any way to fix it? Can I disable something in the config? Seems to be the painting machine, removing EnderIO stops crashing. Or who has to fix things??

https://pastebin.com/zKFvXavi
