### ISSUE TITLE
A bug with checking out for the recipe

### ISSUE THREAD

**Issue by Sarieldhd** [mezz/JustEnoughItems#1315]
hello,
first of all, thank you for making this fantastic mod. I used it since 1.10.2. My English is poor, so I hope you can understand the rest I mean.
Recently,when I play my 1.12.2 mods pack, I found a bug(?).
I can only check out the recipe that how to make stairs,but i cant check out how the stairs can make.
If I check,unfort,the game crashed.
I thought if it is caused by quark mod(because it changes the recipe of stairs) ,but it seems not.
Then I think maybe the foamfix mod,but it doesn't work again.
Finally I solved this problem when I changed my JEI to 1.12.2_4.8.5.147
If I use -4.9.2.196,-4.10.0.198 and even the newest -4.11.0.202, the problem still exist.
I'm from china and because of th GFW, I cant open the website you want me to upload the report.sry
I hope you can fix this problem and please tell me if you succeed.
Good luck

**Comment by mezz** [comment]
Thanks for the report!
Since you can't use gist, please paste your crash log in a comment here so I can see it.

**Comment by Sarieldhd** [comment]
thanks

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (【R键整理】InventoryTweaks-1.63.jar)
  EnderCorePlugin (【末影核心】EnderCore-1.12.2-0.5.35.jar)
  CTMCorePlugin (【连接材质-凿子前置】CTM-MC1.12.2-0.3.2.18.jar)
  CorePlugin (【平滑字体】SmoothFont-1.12.2-1.15.jar)
  DCASMPlugin (【温和气候前置】HeatAndClimateLib_1.12.2-2.5.6.jar)
  LoadingPlugin (【夸克】Quark-r1.4-125.jar)
  ForgePlugin (【万用皮肤补丁】CustomSkinLoader_Forge-14.9.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.11-core.jar)
  AstralCore (【星辉魔法】astralsorcery-1.12.2-1.9.4.jar)
  TransformerLoader (【开放式电脑】OpenComputers-MC1.12.2-1.7.2.67.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (【降低内存占用】foamfix-0.9.9.1-1.12.2-anarchy.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 8/1/18 5:16 PM
Description: Updating screen events

java.lang.RuntimeException: Fluid nc.fluid.FluidCoolant@1b1d208b (redstone_nak, class nc.fluid.FluidCoolant) from item 1xitem.forge.bucketFilled@0 returned an unregistered block from getBlock(). This is a major bug in the mod that fluid belongs to.
	at crazypants.enderio.base.paint.PaintUtil.getBlockFromItem(PaintUtil.java:280)
	at crazypants.enderio.base.paint.PaintSourceValidator.isValidSourceDefault(PaintSourceValidator.java:29)
	at crazypants.enderio.base.paint.PaintUtil.isValid(PaintUtil.java:40)
	at crazypants.enderio.base.recipe.painter.BasicPainterTemplate.isRecipe(BasicPainterTemplate.java:37)
	at crazypants.enderio.machines.integration.jei.PainterRegistryPlugin.getRecipeWrappers(PainterRegistryPlugin.java:170)
	at mezz.jei.recipes.RecipeRegistry.getRecipeWrappers(RecipeRegistry.java:610)
	at mezz.jei.recipes.RecipeRegistry.getRecipeCategories(RecipeRegistry.java:582)
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:46)
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:388)
	at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:243)
	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:219)
	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:201)
	at mezz.jei.input.InputHandler.onGuiKeyboardEvent(InputHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1753_InputHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:513)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at crazypants.enderio.base.paint.PaintUtil.getBlockFromItem(PaintUtil.java:280)
	at crazypants.enderio.base.paint.PaintSourceValidator.isValidSourceDefault(PaintSourceValidator.java:29)
	at crazypants.enderio.base.paint.PaintUtil.isValid(PaintUtil.java:40)
	at crazypants.enderio.base.recipe.painter.BasicPainterTemplate.isRecipe(BasicPainterTemplate.java:37)
	at crazypants.enderio.machines.integration.jei.PainterRegistryPlugin.getRecipeWrappers(PainterRegistryPlugin.java:170)
	at mezz.jei.recipes.RecipeRegistry.getRecipeWrappers(RecipeRegistry.java:610)
	at mezz.jei.recipes.RecipeRegistry.getRecipeCategories(RecipeRegistry.java:582)
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:46)
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:388)
	at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:243)
	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:219)
	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:201)
	at mezz.jei.input.InputHandler.onGuiKeyboardEvent(InputHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1753_InputHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:513)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Sarieldhd'/295, l='MpServer', x=173.53, y=64.00, z=159.93]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 07 - quark_realistic, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (172,64,160), Chunk: (at 12,4,0 in 10,10; contains blocks 160,0,160 to 175,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 265495 game time, 272484 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 58 total; [EntitySkeleton['骷髅'/128, l='MpServer', x=106.50, y=31.00, z=81.50], EntityEnderman['末影人'/129, l='MpServer', x=108.49, y=16.00, z=88.26], EntityCreeper['爬行者'/130, l='MpServer', x=97.50, y=27.00, z=93.50], EntityCreeper['爬行者'/515, l='MpServer', x=211.50, y=21.00, z=106.50], EntityVillager['村民'/133, l='MpServer', x=113.27, y=63.94, z=111.39], EntitySkeleton['骷髅'/517, l='MpServer', x=145.50, y=31.00, z=165.50], EntityVillager['村民'/135, l='MpServer', x=113.17, y=63.94, z=113.52], EntityZombie['僵尸'/519, l='MpServer', x=145.50, y=31.00, z=169.50], EntityBrainyZombie['红眼僵尸'/136, l='MpServer', x=111.50, y=31.00, z=137.50], EntityVillager['村民'/137, l='MpServer', x=111.76, y=72.00, z=141.67], EntityVillager['村民'/138, l='MpServer', x=109.62, y=73.00, z=143.50], EntityZombie['僵尸'/523, l='MpServer', x=146.50, y=31.00, z=169.50], EntityWitch['女巫'/140, l='MpServer', x=111.50, y=16.00, z=224.50], EntityCreeper['爬行者'/142, l='MpServer', x=112.50, y=21.00, z=90.50], EntityVillager['村民'/143, l='MpServer', x=113.96, y=64.00, z=113.43], EntityVillager['村民'/145, l='MpServer', x=117.48, y=63.00, z=105.70], EntityItem['item.item.bread'/529, l='MpServer', x=110.65, y=63.94, z=113.80], EntityVillager['村民'/146, l='MpServer', x=115.84, y=63.00, z=115.49], EntityVillager['村民'/147, l='MpServer', x=119.62, y=64.00, z=117.48], EntityVillager['村民'/148, l='MpServer', x=121.30, y=64.00, z=118.55], EntityVillager['村民'/149, l='MpServer', x=116.37, y=63.94, z=119.55], EntityVillager['村民'/150, l='MpServer', x=120.93, y=72.00, z=137.50], EntityVillager['村民'/151, l='MpServer', x=113.70, y=72.00, z=141.30], EntityVillager['村民'/152, l='MpServer', x=115.70, y=72.51, z=156.30], EntityVillager['村民'/153, l='MpServer', x=115.30, y=73.05, z=156.95], EntityVillager['村民'/154, l='MpServer', x=122.57, y=76.00, z=151.66], EntitySkeleton['骷髅'/538, l='MpServer', x=162.50, y=12.00, z=131.50], EntityPlayerSP['Sarieldhd'/295, l='MpServer', x=173.53, y=64.00, z=159.93], EntityVillager['村民'/169, l='MpServer', x=130.50, y=64.94, z=125.67], EntitySkeleton['骷髅'/170, l='MpServer', x=136.50, y=14.00, z=170.50], EntityZombieVillager['僵尸村民'/172, l='MpServer', x=142.50, y=11.00, z=178.50], EntityZombieVillager['僵尸村民'/173, l='MpServer', x=139.80, y=13.00, z=188.31], EntityHorse['马'/174, l='MpServer', x=132.14, y=72.00, z=207.09], EntityCreeper['爬行者'/187, l='MpServer', x=144.50, y=25.00, z=83.19], EntitySkeleton['骷髅'/189, l='MpServer', x=156.50, y=52.00, z=152.26], EntityCreeper['爬行者'/190, l='MpServer', x=157.58, y=33.00, z=205.81], EntityHorse['马'/191, l='MpServer', x=154.97, y=74.00, z=196.13], EntityHorse['马'/192, l='MpServer', x=151.04, y=74.00, z=206.12], EntitySkeleton['骷髅'/193, l='MpServer', x=144.43, y=18.00, z=224.34], EntityBat['蝙蝠'/195, l='MpServer', x=165.81, y=12.03, z=91.71], EntityCreeper['爬行者'/196, l='MpServer', x=169.86, y=57.00, z=99.54], EntityHorse['马'/197, l='MpServer', x=161.14, y=74.00, z=207.97], EntitySkeleton['骷髅'/198, l='MpServer', x=174.50, y=17.00, z=235.50], EntityCreeper['爬行者'/213, l='MpServer', x=187.17, y=19.00, z=92.46], EntityHorse['马'/214, l='MpServer', x=181.89, y=78.00, z=176.92], EntityCreeper['爬行者'/224, l='MpServer', x=201.50, y=26.00, z=94.50], EntityCreeper['爬行者'/225, l='MpServer', x=201.50, y=26.00, z=95.50], EntityWolf['狼'/226, l='MpServer', x=196.68, y=72.00, z=95.52], EntityWolf['狼'/235, l='MpServer', x=209.56, y=73.00, z=204.50], EntityZombie['僵尸'/236, l='MpServer', x=213.50, y=35.00, z=223.50], EntityCreeper['爬行者'/108, l='MpServer', x=92.63, y=18.00, z=84.02], EntityCreeper['爬行者'/110, l='MpServer', x=93.54, y=11.00, z=100.01], EntityWolf['狼'/241, l='MpServer', x=230.77, y=79.00, z=153.33], EntityBat['蝙蝠'/497, l='MpServer', x=177.25, y=45.83, z=186.25], EntityBat['蝙蝠'/498, l='MpServer', x=178.10, y=27.03, z=191.19], EntityBat['蝙蝠'/499, l='MpServer', x=186.57, y=30.40, z=189.25], EntityBat['蝙蝠'/500, l='MpServer', x=181.97, y=27.70, z=193.63], EntityBat['蝙蝠'/127, l='MpServer', x=102.36, y=28.94, z=86.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1132134840 bytes (1079 MB) / 2497323008 bytes (2381 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2745 Optifine OptiFine_1.12.2_HD_U_E2 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                | Version                      | Source                                                                | Signature                                |
	|:--------- |:--------------------------------- |:---------------------------- |:--------------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                       | minecraft.jar                                                         | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                         | minecraft.jar                                                         | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                    | forge-1.12.2-14.23.4.2745.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.4.2745                 | forge-1.12.2-14.23.4.2745.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | smoothfontcore                    | 1.12.2-1.14                  | minecraft.jar                                                         | None                                     |
	| UCHIJAAAA | dcs_asm                           | 2.0.1                        | minecraft.jar                                                         | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| UCHIJAAAA | opencomputers|core                | 1.7.2.67                     | minecraft.jar                                                         | None                                     |
	| UCHIJAAAA | foamfixcore                       | 7.7.4                        | minecraft.jar                                                         | None                                     |
	| UCHIJAAAA | smoothfont                        | 1.12.2-1.15                  | 【平滑字体】SmoothFont-1.12.2-1.15.jar                                      | None                                     |
	| UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184     | 【R键整理】InventoryTweaks-1.63.jar                                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | customskinloader                  | 14.9                         | 【万用皮肤补丁】CustomSkinLoader_Forge-14.9.jar                               | None                                     |
	| UCHIJAAAA | recipehandler                     | 0.11                         | 【不再有合成冲突】NoMoreRecipeConflict-0.11(1.12.2).jar                        | None                                     |
	| UCHIJAAAA | ctm                               | MC1.12.2-0.3.2.18            | 【连接材质-凿子前置】CTM-MC1.12.2-0.3.2.18.jar                                  | None                                     |
	| UCHIJAAAA | chisel                            | MC1.12.2-0.2.0.31            | 【凿子】Chisel-MC1.12.2-0.2.0.31.jar                                      | None                                     |
	| UCHIJAAAA | uncraftingtable                   | 1.8-beta6                    | 【分解工作台】[1.12]UncraftingTable-1.8-beta6.jar                            | None                                     |
	| UCHIJAAAA | craftstudioapi                    | 1.0.0                        | 【动物谷前置】CraftStudio-1.0.0.93-mc1.12-alpha.jar                          | None                                     |
	| UCHIJAAAA | quark                             | r1.4-125                     | 【夸克】Quark-r1.4-125.jar                                                | None                                     |
	| UCHIJAAAA | baubles                           | 1.5.2                        | 【饰品·魔法前置】Baubles-1.12-1.5.2.jar                                       | None                                     |
	| UCHIJAAAA | thaumcraft                        | 6.1.BETA19                   | 【神秘时代6】Thaumcraft-1.12.2-6.1.BETA19.jar                               | None                                     |
	| UCHIJAAAA | botania                           | r1.10-354                    | 【植物魔法】Botania+r1.10-354.jar                                           | None                                     |
	| UCHIJAAAA | animania                          | 1.4.7                        | 【动物谷】animania-1.12.2-1.4.8.jar                                        | None                                     |
	| UCHIJAAAA | mantle                            | 1.12-1.3.2.24                | 【地幔-匠魂前置】Mantle-1.12-1.3.2.24.jar                                     | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.35                | 【末影核心】EnderCore-1.12.2-0.5.35.jar                                     | None                                     |
	| UCHIJAAAA | jei                               | 4.11.0.202                   | 【物品合成查询】jei_1.12.2-4.11.0.202.jar                                     | None                                     |
	| UCHIJAAAA | enderio                           | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | tconstruct                        | 1.12.2-2.10.1.87             | 【匠魂】TConstruct-1.12.2-2.10.1.87.jar                                   | None                                     |
	| UCHIJAAAA | taiga                             | 1.3.2                        | 【匠魂合金附加】taiga-1.12.2-1.3.2.jar                                        | None                                     |
	| UCHIJAAAA | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957     | 【匠魂工具等级】TinkerToolLeveling-1.12.2-1.0.5.jar                           | None                                     |
	| UCHIJAAAA | conarm                            | 1.0.2                        | 【匠魂盔甲】conarm-1.12.2-1.0.2.jar                                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | morphtool                         | 1.2-16                       | 【变形工具】Morph-o-Tool-1.2-16.jar                                         | None                                     |
	| UCHIJAAAA | psi                               | r1.1-59                      | 【司波大爷】Psi-r1.1-59.jar                                                 | None                                     |
	| UCHIJAAAA | akashictome                       | 1.2-10                       | 【阿卡什-众书之书】AkashicTome-1.2-10.jar                                      | None                                     |
	| UCHIJAAAA | autoreglib                        | 1.3-18                       | 【变形工具众书之书·夸克前置】AutoRegLib-1.3-18.jar                                  | None                                     |
	| UCHIJAAAA | tombstone                         | 2.10.0                       | 【墓碑】tombstone-2.10.0-1.12.jar                                         | None                                     |
	| UCHIJAAAA | aether_legacy                     | 1.12.2-v3.2                  | 【天境2】aether_legacy-1.12.2-v3.2.jar                                    | None                                     |
	| UCHIJAAAA | orbis_api                         | 1.12.2-1.1.6                 | 【天境2前置】orbis_api-1.12.2-1.1.6.jar                                     | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJAAAA | worldedit                         | 6.1.8                        | 【小木斧】worldedit-forge-mc1.12-6.1.8-dist.jar                            | None                                     |
	| UCHIJAAAA | worldeditcuife2                   | 2.1.2-mf-1.12.2-14.23.0.2487 | 【小木斧辅助】WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12.2-14.23.0.2487.jar | None                                     |
	| UCHIJAAAA | opencomputers                     | 1.7.2.67                     | 【开放式电脑】OpenComputers-MC1.12.2-1.7.2.67.jar                            | None                                     |
	| UCHIJAAAA | carryon                           | 1.9.2                        | 【徒手搬运】CarryOn+MC1.12.2+v1.9.2.jar                                     | None                                     |
	| UCHIJAAAA | guideapi                          | 1.12-2.1.6-61                | 【指导书】Guide-API-1.12-2.1.6-61.jar                                      | None                                     |
	| UCHIJAAAA | torohealthmod                     | 1.12.2-11                    | 【敌人血量显示】torohealth-1.12.2-11.jar                                      | None                                     |
	| UCHIJAAAA | journeymap                        | 1.12-5.4.9                   | 【旅行地图】journeymap-1.12-5.4.9.jar                                       | None                                     |
	| UCHIJAAAA | astralsorcery                     | 1.9.4                        | 【星辉魔法】astralsorcery-1.12.2-1.9.4.jar                                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAAAA | twilightforest                    | 3.7.424                      | 【暮色森林】twilightforest-1.12.2-3.7.424-universal.jar                     | None                                     |
	| UCHIJAAAA | extrautils2                       | 1.0                          | 【更多实用设备】extrautils2-1.12-1.8.1.jar                                    | None                                     |
	| UCHIJAAAA | chiselsandbits                    | 14.20                        | 【雕凿工艺】chiselsandbits-14.20.jar                                        | None                                     |
	| UCHIJAAAA | extrabitmanipulation              | 1.12-3.2.1                   | 【更多雕凿工具】ExtraBitManipulation-1.12-3.2.1.jar                           | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.29                       | 【末影接口】EnderIO-1.12.2-5.0.29.jar                                       | None                                     |
	| UCHIJAAAA | nuclearcraft                      | 2.10p                        | 【核电工艺】NuclearCraft-2.10p--1.12.2.jar                                  | None                                     |
	| UCHIJAAAA | immersiveengineering              | 0.12-84                      | 【沉浸工程】ImmersiveEngineering-0.12-84.jar                                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersivepetroleum                | 1.1.9                        | 【沉浸原油】immersivepetroleum-1.12.2-1.1.9.jar                             | None                                     |
	| UCHIJAAAA | dcs_lib                           | 2.5.6                        | 【温和气候前置】HeatAndClimateLib_1.12.2-2.5.6.jar                            | None                                     |
	| UCHIJAAAA | dcs_climate                       | 2.5.7                        | 【温和气候】HeatAndClimateMod_1.12.2-2.5.7.jar                              | None                                     |
	| UCHIJAAAA | creeperconfetti                   | 1.4.2                        | 【烟火苦力怕】creeperconfetti-1.4.2.jar                                      | None                                     |
	| UCHIJAAAA | itemzoom                          | 1.10                         | 【物品缩放】itemzoom_1.12.1-1.10.jar                                        | None                                     |
	| UCHIJAAAA | ironbackpacks                     | 1.12.2-3.0.8-12              | 【特殊背包】IronBackpacks-1.12.2-3.0.8-12.jar                               | None                                     |
	| UCHIJAAAA | thaumicjei                        | 1.2.1                        | 【神秘时代jei辅助】ThaumicJEI-1.12.2-1.4.0-14.jar                             | None                                     |
	| UCHIJAAAA | openglider                        | @VERSION@                    | 【简易滑翔翼】OpenGlider-1.12.1-1.1.0.jar                                    | None                                     |
	| UCHIJAAAA | bloodmagic                        | 1.12.2-2.3.1-99              | 【血魔法】BloodMagic-1.12.2-2.3.1-99.jar                                   | None                                     |
	| UCHIJAAAA | mekanism                          | 1.12.2-9.4.13.349            | 【通用机械】Mekanism-1.12.2-9.4.13.349.jar                                  | None                                     |
	| UCHIJAAAA | mekanismgenerators                | 9.4.11                       | 【通用机械发电机】MekanismGenerators-1.12.2-9.4.13.349.jar                     | None                                     |
	| UCHIJAAAA | mekanismtools                     | 9.4.11                       | 【通用机械工具】MekanismTools-1.12.2-9.4.13.349.jar                           | None                                     |
	| UCHIJAAAA | foamfix                           | 0.9.9.1-1.12.2               | 【降低内存占用】foamfix-0.9.9.1-1.12.2-anarchy.jar                            | None                                     |
	| UCHIJAAAA | extraalchemy                      | 0.3.8.5-release              | 【额外药水】extraalchemy-0.3.8.5-release.jar                                | None                                     |
	| UCHIJAAAA | thebetweenlands                   | 3.3.11                       | 【交错维度】TheBetweenlands-3.3.11-universal.jar                            | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (【R键整理】InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (【末影核心】EnderCore-1.12.2-0.5.35.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (【连接材质-凿子前置】CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CorePlugin (【平滑字体】SmoothFont-1.12.2-1.15.jar)
  bre.smoothfont.asm.Transformer
DCASMPlugin (【温和气候前置】HeatAndClimateLib_1.12.2-2.5.6.jar)
  defeatedcrow.hac.asm.DCMethodTransformer
LoadingPlugin (【夸克】Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgePlugin (【万用皮肤补丁】CustomSkinLoader_Forge-14.9.jar)
  customskinloader.forge.TransformerManager
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.11-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
AstralCore (【星辉魔法】astralsorcery-1.12.2-1.9.4.jar)
  
TransformerLoader (【开放式电脑】OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (【降低内存占用】foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1060/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2745
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 【万用汉化】Minecraft-Mod-Language-Package-2.2.9.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.36
	OpenGlRenderer: GeForce GTX 1060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by mezz** [comment]
Please update JEI to 4.11.0.206, and update EnderIO to 5.0.31. Then paste the new crash log here, it will have better information about the issue.
