### ISSUE TITLE
JEI Not Showing Repair of Modded Repairable Items

### ISSUE THREAD

**Issue by KenyMylankca** [mezz/JustEnoughItems#1316]
Could you add check for the item #getIsRepairable and get the repairing item to show modded items repairing GUI(anvil) such like vanilla tools please?
I can see that i can repair a diamond pickaxe with a diamond on anvil by JEI, but a modded pickaxe. It would be so cool and enjoying that the player be able to see how can he repair his modded item.

**Comment by mezz** [comment]
Thanks for the suggestion!
Unfortunately `getIsRepairable` is very open-ended, and so it's not clear what items combinations result in a repair recipe. To find them all, I think JEI would have to try every combination of two items, which would take a very long time.

**Comment by KenyMylankca** [comment]
I know that open-ended condition, but it won't be at the point of the JEI, it will be about the stability(code quality) of the modded item. The JEI will keep being stable at that point, for me.

**Comment by KenyMylankca** [comment]
this needs a fix...really..
