### ISSUE TITLE
Can't load with mod installed

### ISSUE THREAD

**Issue by M6444** [mezz/JustEnoughItems#1320]
When I try to start the game I get this message, even though this is the right version of minecraft, forge and this mod

![minecraft](https://user-images.githubusercontent.com/42199213/43820154-40f560c2-9a9a-11e8-83d2-db016ee66340.PNG)

**Comment by MauveCloud** [comment]
> this is the right version of minecraft, forge and this mod

The error message strongly hints that you might be mistaken about that, so I suggest you specify the exact build numbers you are using.  Looking through the JEI files listed at CurseForge, builds of JEI newer than 4.7.11.102 are only listed as being compatible with MC 1.12.2, not MC 1.12

**Comment by M6444** [comment]
You're right i forgot to actually update in the launch options i forgot that was a thing, i have not done anything minecraft related in forever
