### ISSUE TITLE
Server does not have JEI(Eula is trua)

### ISSUE THREAD

**Issue by joshthemoose1** [mezz/JustEnoughItems#1321]
I had a server that had jei and industrial craft 2 and it worked fine. I made a new server and now i cant craft items from industrial craft and it says,"The server must have JEI installed." I have 1.12.2 and jei 4.9.11.170. Is it because the people i am playing with need a newer version or what? Please help?

**Comment by mezz** [comment]
Thanks for the report!
JEI will say that when you have it installed on your Client but not on your Server.
