### ISSUE TITLE
JEI crashing the game upon opening inventory

### ISSUE THREAD

**Issue by JBSTheGamer** [mezz/JustEnoughItems#1322]
The thing that happens is when i open up my inventory it makes my game crash on the latest version of JEI. The version of JEI i have is jei_1.12.2-4.11.0.205
The version of forge i have is 14.23.4.2718 for 1.12.2 minecraft
The crash report can been seen here https://paste.dimdev.org/mewevogope.mccrash

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
  Ingredient Mod: XNet
  Ingredient Info: 1xtile.xnet.facade@0 xnet:facade
```
Please report this to XNet here; https://github.com/McJtyMods/XNet/issues

**Comment by CandyRed** [comment]
At least you can go to the Menu, I can't even get past the Mojang screen because of a mod in a modpack.
