### ISSUE TITLE
I downloaded a modpack, but one of the mods is crashing my game

### ISSUE THREAD

**Issue by CandyRed** [mezz/JustEnoughItems#1323]
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
This is the Report that it gave me.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
