### ISSUE TITLE
possible JEI recipe registering bug?

### ISSUE THREAD

**Issue by redgoblin88** [mezz/JustEnoughItems#1325]
hey, there has been a recent confusion in the community as there is a known crash that is to do with looking up the uses for cobblestone. the crashlog it generates points towards the enderio painting machine however when it is reported there they claim it is the fault of mcjty's xnet mod but he also says it is not his fault

so were stuck with a dilema with two mods saying the crash is not their fault but one of their mods is the problem but i got wondering... in the many logs i got (happens with stairs, glowstone and cobblestone) there is a reference to JEI recipe handling so the bug could be JEI mis-handling the recipe added by enderio??

this is a big long shot but the community is starting to get annoyed and all are telling crazy pants there might be a bug with his mod which in turn is propably getting them annoyed with all the fingers being poked at.

if you are interested here is a crashlog refering to the bug:
https://pastebin.com/2SqN9jgf

i do hope this can get fixed eventually because its not just cobblestone... its not just vanilla glowstone... its not just vanilla dark oak stairs.... its an unknown quantity of blocks which can only be found out through trial and error and prevents the player learning what they want to know

**Comment by mezz** [comment]
Thanks for the report!
Can you link to the relevant issue in XNet? I was not aware that McJty was redirecting anyone.

You crash log is not an XNet issue though, it is from EnderIO's `PaintUtil` crashing on a `randomthings:plate_extraction` item.

**Comment by mezz** [comment]
I will work to catch the errors from EnderIO's `PaintUtil` for now, hopefully they will stop throwing errors in the future.

**Comment by TehNut** [comment]
It looks like they're trying to enforce a 1:1 item meta -> serialized state conversion which is just not valid whatsoever.

**Comment by mezz** [comment]
It never works out well when mods try to police other mods' errors by crashing...

I'll have a new build of JEI out soon that catches the crash and logs an error instead.
The build system is acting up right now so I'm just waiting on that to get fixed before I can release it.

**Comment by mezz** [comment]
JEI 4.11.0.212 is out now and will log this issue as an error instead of crashing.
It also looks like RandomThings has fixed this crash, you should update that mod too.

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/44113885-d4a02fea-a009-11e8-977f-6f4715b9368f.png)

**Comment by mezz** [comment]
It’s my opinion that I have turned a car explosion into a warning light (error log). For JEI recipe lookups I think that’s the right choice. For the rest of the game I can understand if you want to just crash, that’s your choice and fine. I did ask you about it before and you did not respond.
