### ISSUE TITLE
Opening my inventory crashes the game

### ISSUE THREAD

**Issue by FluxCube** [mezz/JustEnoughItems#1326]
Originally, I could open my inventory, and typing "bac" would crash the game, and when I reloaded the game, the search bar had reverted to my previous search, now my search bar has "ba" stuck in it and it crashes whenever I open my inventory.

Crash Report is here: [https://pastebin.com/fhFkVCzu](url)
JEI Version: jei_1.10.2-3.14.7.420
Minecraft version: 1.10.2 (modded) forge-12.18.3.2511

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by FluxCube** [comment]
latest.log: [https://gist.github.com/FluxCube/526e65867a4746668042ab0e4d3ad5f0](url)

**Comment by mezz** [comment]
This crash seems to be unrelated to JEI, it is a crash from GooglyEyes:
```
[17:44:23] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at me.ichun.mods.googlyeyes.common.core.EventHandler.onWorldTick(EventHandler.java:42) ~[EventHandler.class:?]
```
Please try removing that mod and see if that fixes the issue.

**Comment by FluxCube** [comment]
I removed that mod, and it appears to have fixed it, thanks for the help!

**Comment by mezz** [comment]
Cool, glad that was it.
