### ISSUE TITLE
Move items into crafting area" [+] 1.12.2

### ISSUE THREAD

**Issue by gamaleev0071** [mezz/JustEnoughItems#1328]
i not found " The "Move items into crafting area" [+] buttons." " (sorry my english)
in the single game 1.10.2 (3.14.7.417) this button is there !.
but in 1.12.2 (4.11.0.212) it is no longer there!
this upset me very much

**Comment by mezz** [comment]
Thanks for the report!
Can you show me a screenshot?

**Comment by gamaleev0071** [comment]
http://joxi.ru/52a19BPS4LGdv2 - screenshot
https://paste.ee/p/VwxJK - minecraft log with all possible information

**Comment by mezz** [comment]
That is very strange, I have not seen that happen before.

I think another mod is conflicting with JEI to cause the problem.
Can you try removing mods until it works, so we can find out which mod is causing the problem?

**Comment by gamaleev0071** [comment]
I know about this incompatibility only with the mod
crafting-tweaks but it's not worth it

**Comment by gamaleev0071** [comment]
LOOOOOOOL

I found a problem, and it is not in mods but in the width of the GUI xD
the value was from 350 to 450 and the button appeared
