### ISSUE TITLE
Unable to edit search query when there are no results

### ISSUE THREAD

**Issue by Virtuoel** [mezz/JustEnoughItems#133]
When no matches come up for the given search, the text turns red and can only be deleted from. This can be inconvenient if one wants to edit an earlier word or accidentally removes some text from an earlier word and then can't add it back without changing the query until the search is valid again.

**Comment by Prospector** [comment]
I don't really like the red preventing you from typing in the first place. It's annoying when I know I mistype a word, so I backspace however many lettees I think I messed up on, but then I delete it too much.

**Comment by mezz** [comment]
I will change it so it's red but allows you to type. Blocking typing is not a good feature.

**Comment by Prospector** [comment]
:)
