### ISSUE TITLE
build 214 & 215 forces NPE crash with Simple Storage Network

### ISSUE THREAD

**Issue by kreezxil** [mezz/JustEnoughItems#1331]
https://github.com/PrinceOfAmber/Storage-Network/issues/91

**Comment by mezz** [comment]
Thanks for the report!
Simple Storage Network was relying on JEI internal classes, so it broke when JEI updated. They will have to update their mod.

**Comment by Lothrazar** [comment]
Thanks mezz! Looks like all i had to do was use "getIngredientFilter" insetad of the deprecated getItemListOverlay
