### ISSUE TITLE
Crash when closing game

### ISSUE THREAD

**Issue by Fatmice** [mezz/JustEnoughItems#1332]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

https://paste.ee/p/Tjlxn

**Comment by mezz** [comment]
Thanks for the report!
This crash is from NEI, please report it to them here instead: https://github.com/TheCBProject/NotEnoughItems/issues
