### ISSUE TITLE
[enhancement] JEI and AppliedEnergetics integration

### ISSUE THREAD

**Issue by Foxgreat** [mezz/JustEnoughItems#1333]
Hello there!

I dont sure is it a bug or unsupported feature for exacly that mod but can you add auto-placement of items to AE2 Craft terminal please?

Vanilla Workbench
![image](https://user-images.githubusercontent.com/29230185/44255922-695f1d00-a229-11e8-8215-a12532170c5f.png)
AE2 Workbench terminal
![image](https://user-images.githubusercontent.com/29230185/44255941-7b40c000-a229-11e8-8763-156ee677d7d6.png)

**Comment by mezz** [comment]
Thanks for the suggestion!
This must be implemented by AE2, each mod adds their own integration with JEI.
Please request it here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues
