### ISSUE TITLE
strange main menu glitch

### ISSUE THREAD

**Issue by 10chaos1** [mezz/JustEnoughItems#1336]
not sure if this has been reported/fixed before but after installing nei via twitch my main menu acts strange for example clicking any menu gui e.g options gives me a blank (dirt texture) screen and nothing loads i also get an error in the minecraft game output  after some time has passed on that screen which is this:

Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$KeyboardInputEvent$Post@3fcc944c: java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay; 	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:125) 	at codechicken.nei.jei.gui.ContainerEventHandler.onKeyTypedPost(ContainerEventHandler.java:60) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1329_ContainerEventHandler_onKeyTypedPost_Post.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:513) 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
--
Index: 5 Listeners:
 0: NORMAL
1: ASM: codechicken.nei.handler.NEIClientEventHandler@549d2649 onKeyTypedPost(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
 2: ASM: INSTANCE onGuiKeyboardEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
 3: ASM: mezz.jei.input.InputHandler@53f4b6c9 onGuiKeyboardEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
 4: LOWEST
 5: ASM: codechicken.nei.jei.gui.ContainerEventHandler@5d8d8ef8 onKeyTypedPost(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V

**Comment by TehNut** [comment]
#1330
