### ISSUE TITLE
Prefer showing vanilla categories first

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#134]
When you lookup a recipe it should show vanilla crafting first.

**Comment by Prospector** [comment]
Also perhaps allow for a "priority" system. For example, I could make a handler for a maceragor, and I could set it to priority 0, so it would show up first. Or I could set my info page as a priority 9, so it shows up last.

**Comment by mezz** [comment]
I don't really like priority in general because then you get people battling for priority.

**Comment by Prospector** [comment]
Or perhaps just include Priority.LOW and Priority.HIGH, at least so mod authors have a little control.

EDIT: or simply lowPriority = true/false?

**Comment by mezz** [comment]
We may see a need for that in the future but for now it's working well.

**Comment by AEnterprise** [comment]
@mezz maybe an option to show certain recipes last would be usefull, for example items that can be made in 2 ways: by re-crafting with a dye or making them directly, if the recipes for re-crafting with a dye always show up first it could be annoying for to find the direct crafting recipe

**Comment by KnightMiner** [comment]
I can see setting the priority to low would be a lot less likely for mod authors to battle over, as no one really insists their recipes are the least important unless they actually are.

Though I have not seen any issues with the first recipe being the wrong one so far, I think the order they are registered has some effect that fixes that in most cases

**Comment by AEnterprise** [comment]
haven't seen the issue yet with JEI eighter, i just remember that with NEI things like colored cables from AE2 could be a bit of a hassle to find the recipe that you need
