### ISSUE TITLE
Hide Ingredients forces wildcard on AE2 Facades

### ISSUE THREAD

**Issue by Adam-Kay** [mezz/JustEnoughItems#1346]
### The Problem

When using the "Hide Ingredients" option, the wildcard option is forced for facades from AE2.
(I would have reported this to AE2 Github, but this seems like more of a JEI issue than anything.)

### Example 1: Correct Usage

Here is a video of me using the wildcard option correctly and as intended with the OpenBlocks tanks, which can be very irritating as they fill up the JEI window with various variants of tanks filled with different fluids. I use CTRL+Click to highlight all the fluid tanks, then un-highlight the empty tank so I can still see it for the recipe.

### Example 2: Bugged Usage

But when using it with Applied Energistics 2 facades, no matter whether I use CTRL or not, left click, right click, it will always select and deselect ALL of the facades, which means I can either hide all of them or none of them, which is inconvenient because I'd like to hide all of them apart from the Stone Facade, just so I remember the recipe. Here is an example of this occuring:

#### _[AE2 Usage (Bug)](https://drive.google.com/uc?id=17f01wXp_2Nxac5egJSKi51V6gCBu_Lxe)_

**Comment by TehNut** [comment]
My guess is that AE doesn't register a subtype interpreter for their facades, so JEI sees them as a single item.

**Comment by Adam-Kay** [comment]
@TehNut But if JEI sees them as a single item, why does it display every single one of them and give me like 4 pages of facades D:

**Comment by TehNut** [comment]
Because AE2 adds them in `getSubItems(...)`.

**Comment by mezz** [comment]
I submitted a fix for this in AE2 here: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/3750
It should be fixed in the latest version.
