### ISSUE TITLE
Incompatibilities With Custom Renderers

### ISSUE THREAD

**Issue by NullSector76** [mezz/JustEnoughItems#1347]
For issues:
The block/items render differently in the jei tab then that of the inventory ground and everything else.
For example anything that uses IITemRenderer by either LazzyModder or EvilNotchLib will result in the default vanilla render and nothing else

Steps to reproduce:
install silkspawners
observer no entities render inside of the spawners
click on the enderdragon and observe it starts to render the entity

this is also reproducible with mods that use lazzy modder IItemRenderer.

When are you getting the item renderer from the mc class maybe switching it to post init should resolve compatibility issues? Or are you hardcoding the block model render calls? 

Try this to your render code once in the tab and if it still doesn't work populate your IBakedModels in init or post init
`Minecraft.getMinecraft.getRenderItem().renderItemModelIntoGUI(stack,x,y,bakedModel);`

**Comment by mezz** [comment]
Thanks for the report!

JEI checks `IBakedModel#isBuiltInRenderer` to see if it should treat the item renderer like a TEISR.
I think if they set that property to `true`, JEI will render those items properly.
When the property is `false`, JEI treats the rendering as simple and batches the rendering of many items together for performance.

Are you in contact with those authors? Please make a bug report and link back to this issue and I can follow up if they have questions.

**Comment by quat1024** [comment]
keep in mind that `isBuiltInRenderer` can be set to true by setting the item model's parent (somewhere up the chain) to `minecraft:builtin/entity`, and a `TileEntityItemStackRenderer` can be assigned in newer Forges with `Item#setTileEntityItemStackRenderer`, which should be everything required to make a fully custom rendered item. I do exactly this in Incorporeal and it works completely seamlessly in JEI, I was surprised!

I never had to mess with replacing a `RenderItem` instance. Who *knows* what evilnotchlib is doing.

**Comment by mezz** [comment]
I tried to work with the author on this but they were adamant about JEI creating a custom solution for them, and ended up acting a bit hostile so I am leaving it up to them to solve the issue alone unfortunately. 

Every other mod works fine, so I think they will not have too much trouble coming up with a solution that works for their mods too.

**Comment by NullSector76** [comment]
No he said "that he doesn't create models nor mess with meta making it
impossible to do so otherwise without custom code on both sides.

No one was hostile and only a couples of lines of code was asked
@evilnotchteam dev"
