### ISSUE TITLE
Error: Caught exception from Just Enough Items (jei)

### ISSUE THREAD

**Issue by jomama123** [mezz/JustEnoughItems#1349]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

[crash-2018-08-31_17.56.38-client.txt](https://github.com/mezz/JustEnoughItems/files/2341114/crash-2018-08-31_17.56.38-client.txt)
[crash-2018-08-31_18.06.27-client.txt](https://github.com/mezz/JustEnoughItems/files/2341115/crash-2018-08-31_18.06.27-client.txt)

**Comment by Ommina** [comment]
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

You're running out of memory.

Presently, you are giving Minecraft 1GB of RAM, which is insufficient for all but the smallest of packs.

Increase the allocated RAM ('how to' will vary with the launcher used), and try again.

**Comment by DarkPrincessWarrior** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
I'm having this problem and need help to fix it. Please... 
[crash-2018-04-13_20.54.55-client.txt](https://github.com/mezz/JustEnoughItems/files/2417416/crash-2018-04-13_20.54.55-client.txt)

**Comment by mezz** [comment]
@DarkPrincessWarrior that is an unrelated crash, please open a new issue.
