### ISSUE TITLE
Search aliases

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#135]
For example, Thermal Expansion could add something like "wrench" as a search alias for the crescent hammer.

**Comment by mezz** [comment]
I don't think people would utilize this. It would be better to have it on the tooltip and have JEI search that.

**Comment by AEnterprise** [comment]
maybe have nei also search the tool type? for example if you search for "pickaxe" it show everything that has the pickaxe tool type for breaking blocks
