### ISSUE TITLE
Recipes showing for items disabled in those items' mod configs

### ISSUE THREAD

**Issue by phyne** [mezz/JustEnoughItems#1352]
![2018-09-01_23 14 05](https://user-images.githubusercontent.com/30962920/44951842-72f99f00-ae3d-11e8-8b18-5e29e5b95eee.png)

For example, this framed chest block from [Bibliocraft](https://minecraft.curseforge.com/projects/bibliocraft) has been disabled in that mod's config. It neither shows up in the right pane of JEI nor is craftable in game, yet when you bring up the recipes window (when showing the uses for birch wood in this case), it appears there with that tooltip error.

This occurs with any mod that has a config able to disable blocks/items.

Is this a problem with JEI, or am I doing something wrong?

**Comment by TehNut** [comment]
This would be an error with those mods still adding recipes for their items.

**Comment by mezz** [comment]
Thanks for the report!
Please report it to Bibliocraft here: https://github.com/Nuchaz/BiblioCraft/issues
