### ISSUE TITLE
IndexOutOfBoundsException 1.12

### ISSUE THREAD

**Issue by Ioandar** [mezz/JustEnoughItems#1353]
Hi! 

I am not sure if I report to the right place. Would you kindly take a look and see?

I could not re-produce it, but I thought I report it anyway, because maybe you can read something in it?

 `   java.lang.IndexOutOfBoundsException: Index: 40, Size: 40
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.getSlot(Container.java:120)
    at mezz.jei.transfer.BasicRecipeTransferInfo.getInventorySlots(BasicRecipeTransferInfo.java:56)`

Full logfile here: https://paste.dimdev.org/alirihirok.mccrash

**Comment by mezz** [comment]
Thanks for the report!
This most likely only happens when transferring a recipe into a specific modded GUI. I think they have specified the slots in the GUI incorrectly and JEI crashes when trying to transfer.

**Comment by Ioandar** [comment]
Okay, I think it was the "Simple Alloy Smelter" or "Simple Furnace" from EnderIO (EnderIO-1.12.2-5.0.31)

Should I report that to EnderIO and link or will you catch the Exception and kick Crazypants yourself :)

**Comment by mezz** [comment]
Please confirm the issue in-game and report it to EnderIO if they are the GUI involved.

**Comment by Ioandar** [comment]
Okay, will do. If it happens again, I will remember what UI it was and report it freshly over to EndeIO.

Thank you for your help and all your great work!

Closing this issue now, cheers
