### ISSUE TITLE
Stopwatch is not reset when measuring plugin method execution time

### ISSUE THREAD

**Issue by Virtuoel** [mezz/JustEnoughItems#1355]
Unlike in `JeiStarter$LoggedTimer`, the `Stopwatch` used in `RecipeRegistryPluginSafeWrapper.callPluginMethod` is not reset before starting the stopwatch, so the elapsed time will keep building up.

**Comment by mezz** [comment]
Good catch, this might have been causing a few weird issues with log spam.
