### ISSUE TITLE
API suggestion - a way to get the hovered item in recipe GUI

### ISSUE THREAD

**Issue by Hubry** [mezz/JustEnoughItems#1357]
I was looking for a way to get the currently hovered item from the recipe GUI. Sadly, [the IRecipesGui interface](mezz/JustEnoughItems/blob/f5acb392ccdbc5ed8b6de6181f30bf0e42442957/src/api/java/mezz/jei/api/IRecipesGui.java), the only interface in the public API that the recipe GUI implements, does not have a way to get the currently hovered item like the [IIngredientListOverlay](https://github.com/mezz/JustEnoughItems/blob/f5acb392ccdbc5ed8b6de6181f30bf0e42442957/src/api/java/mezz/jei/api/IIngredientListOverlay.java#L19) does. 
This is definitely possible if I use JEI internals, but that might not work at all in a few versions.

*Use case*: I reimplemented Botania's Corporea request keybind (press a button when hovering over and item to request it from a nearby Corporea Index, see Vazkii/Botania#2668), but sadly this can't be used when in the recipe GUI. I was thinking about this when making that PR, but I only decided I really want it when I actually made use of this feature in a playthrough and couldn't request some crafting ingredients easily.

**Comment by mezz** [comment]
Thanks for the suggestion!
This doesn't seem like a very high-priority item since you can get items from the list, but I can see the need for it. I would be happy to review a PR for it if you feel comfortable writing a JEI API method for it.
