### ISSUE TITLE
Using the + to add receipe into Refined Storage Crafting Grid disconnects client

### ISSUE THREAD

**Issue by TheRealDadbeard** [mezz/JustEnoughItems#1359]
I don't know who's at fault so I'm going from mod to mod. Heres the error in the log: https://pastebin.com/DhC7rriM

Forge 2759
Mc 1.12.2
jei_1.12.2-4.12.0.216

**Comment by flanigomik** [comment]
I have also seen this happen with spesific items, crafting them by hand inside the refined storage system is fine but JEI + button on spesific items crashes the client

**Comment by mezz** [comment]
Thanks for the report!
Refined Storage handles this on their side, please report it to them here: https://github.com/raoulvdberge/refinedstorage/issues
