### ISSUE TITLE
Add Shift+R to lookup uses

### ISSUE THREAD

**Issue by lanAnderson** [mezz/JustEnoughItems#136]
NEI let you press "Shift+R" to lookup uses so you don't have to move your hand. It's a little thing, but it is hard to go back to using "U".

**Comment by mezz** [comment]
I'm sort of waiting on a Forge update that will allow registering hotkeys with modifiers.
https://github.com/MinecraftForge/MinecraftForge/pull/2234

I guess I can just hard-code it in for now.
