### ISSUE TITLE
Recipes not showing

### ISSUE THREAD

**Issue by ibejared** [mezz/JustEnoughItems#1362]
Thanks in advance for any responses or help! This might be more of an "how to use" then a deep need. 

I installed JEI and it worked perfectly at first, but soon something happened that now renders it comepletely useless. I don't know if i pressed the wrong button or something, but it stopped showing the recipes for modded AND non modded items. It shows only how to smelt stuff and the outcomes of smelting (oddly) but not the recipes. To reiterate everything was working perfectly but one play through this happened. "hide recipes" is off, so that's not it. Checked mod folders and all mods and their corresponding support mods are installed. No clue what's happening!

**Comment by mezz** [comment]
Thanks for the report!
I'm not sure what the issue is, I have not heard of that happening before.
Try making a backup and then removing mods from your game to see if one mod is causing an issue.
