### ISSUE TITLE
Recipe category lag?

### ISSUE THREAD

**Issue by HaniXP** [mezz/JustEnoughItems#1363]
Hi there, my friend got crashed or lagged out because it said this in his latest logs : 

https://gist.github.com/AgentHani/0df1082d75334a87a45a40529ee7b187

------------------------------------

Any idea to solve this? , using 1.12.2 and playing in a modpack called HeartBeat Lite = 

https://www.technicpack.net/modpack/heartbeat-lite.1246190

**Comment by Ommina** [comment]
If there is an associated crash report, post a link to that instead.  I don't feel the five lines listed are likely to be the cause of the issue being experienced.

**Comment by mezz** [comment]
Thanks for the report!
JEI is saying the lookup is slow, but it shouldn't cause a crash or lag out. 
"Slow" here in the log is about 1/50th of a second, it's just a bit slow for JEI but you should barely be able to notice it.
