### ISSUE TITLE
JEI crashes when using the search bar

### ISSUE THREAD

**Issue by justamike** [mezz/JustEnoughItems#1365]
[hs_err_pid4372.log](https://github.com/mezz/JustEnoughItems/files/2406851/hs_err_pid4372.log)

Im a noob. JEI crashes my game occasionally when i use the search bar. im not versed in java crash codes

can any one tell me which mod is causing this?

btw i run 1.12.2 from multimc with direwolf 20's lets play pack

**Comment by mezz** [comment]
Thanks for the report!
`hs_err` is pretty serious, it means the Java Virtual Machine itself crashed, not Minecraft or JEI. 
Try updating your version of Java to see if it fixes the issues.

**Comment by ProsperCraft** [comment]
There isn't anything newer than 181 to my knowledge.

But perhaps a reinstall would help?

**Comment by justamike** [comment]
First, thanks for the responses

 so ive tried updating java, a fresh install of java to a different directory, updates of JEI and any mod that appears to have a problem loading from the event log in multimc.

I dont think its java because the game plays smoothly and indefinitely until I search for an item or recipe in JEI. i can click the search field and search for some items but others cause it to crash.

Ive also tried allocating more memory to java

so strange because i keep all of these files on a flash drive and play at home and school. I drag a folder containing multimc and java to the desktop and play from there as to not kill my flash drive (then save the world back to the flash drive when finished).
The school computer has never crashed due to a search in JEI. Ive tried to re create the problem there but it doesnt happen. (searching for the same item that crashes home pc)

I thought it may be a problem with my ram but ive run a memory diag and it came up clean. I also have a brand new ssd with a fresh install of windows and drivers for my other hardware

I thought it also may be because im running an older mod pack from 1.10.2 but that wouldnt explain me not being able to re create the problem on the school computer


 My GTX 680 died about a month ago due to bad memory and now im playing from integrated graphics(i7 3770k on a ASUS z77 sabertooth) 
 I wouldnt be surprised if something else on my system is slowly dying(even though everything else seems to run pretty well for the moment and is giving no errors)

It feels like theres a specific mod that is incompatible or missing some files that JEI uses for the search 
For now I will continue to go through the list of mods updating all 100 to the latest 1.10.2 to see if that works

I appreciate the help

**Comment by mezz** [comment]
`hs_err_pid####.log` is only generated by Java crashing.
A regular Minecraft crash log will be different.

I looked into it a bit deeper since it seems like you really put some effort into trying to figure this out and I'd like to help if I can.
Your bug seems to be these two: 
https://bugs.openjdk.java.net/browse/JDK-8145274
https://bugs.openjdk.java.net/browse/JDK-8172031

They were closed as an integrated intel graphics driver bug, which matches your story and makes sense.
Try looking for updated graphics drivers for your computer, or try out an old graphics card to see if it fixes your issue.

**Comment by justamike** [comment]
yay! i fixed it. Thanks for the help!

it was the graphics driver. The drivers on the ASUS website are older than the ones straight form the intel site

since the graphics card died, Mc is the only thing worth playing currently and im ELATED now that it works

THANK YOU THANK YOU THANK YOU

**Comment by mezz** [comment]
Glad that was it!
