### ISSUE TITLE
craash on starup

### ISSUE THREAD

**Issue by starkillerone** [mezz/JustEnoughItems#1366]
https://pastebin.com/g5fYeRzi  crash report

**Comment by Ommina** [comment]
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

You're running out of memory.

Presently, you are giving Minecraft 3GB of RAM.  Increase the allocated RAM ('how to' will vary with the launcher used), and try again.

**Comment by f0rgotten** [comment]
I have 6GB of RAM Allocated for Minecraft and it still crashes on startup for me aswell, using Forge 2770

**Comment by Ommina** [comment]
@f0rgotten 

Not all startup crashes are equal.  Create a new issue and include the crash-report.  Sadly, not much can be done with with what has been provided.
