### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pablojuanals** [mezz/JustEnoughItems#1368]
The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
