### ISSUE TITLE
Hello I have a problem in the search bar at the edges is golden as I turn it off

### ISSUE THREAD

**Issue by LaLoGG** [mezz/JustEnoughItems#1369]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by LaLoGG** [comment]
Hello I have a problem in the search bar to the edges is golden as I remove it

**Comment by mezz** [comment]
Thanks for the report!
Double-click the search bar to stop that. It is not a JEI feature, it is from NEI or some other mod that adds it on top of JEI.
