### ISSUE TITLE
JEI Catches Bottles as Uncraftable Potions In T.A.N.

### ISSUE THREAD

**Issue by KenyMylankca** [mezz/JustEnoughItems#1370]
https://github.com/Glitchfiend/ToughAsNails/issues/576#issuecomment-424191264
everything latest reproduces this (1.12.2)

**Comment by mezz** [comment]
Thanks for the report!
I think this issue belongs to ToughAsNails. They can ping me in their issue if they have any questions about it, I'd like to keep all the discussion in one place.
