### ISSUE TITLE
Request: a way or a section to pin items for fast acces

### ISSUE THREAD

**Issue by drunkgummyboy** [mezz/JustEnoughItems#1371]
Request: a way or a section to pin items for fast acces

**Comment by sapient** [comment]
Came here to post this EXACT request; this would be an AWESOME feature!

**Comment by IMarvinTPA** [comment]
This sounds like https://github.com/mezz/JustEnoughItems/pull/1408

**Comment by mezz** [comment]
This has been implemented in JEI 4.14.0 beta.
