### ISSUE TITLE
Client crash - java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES

### ISSUE THREAD

**Issue by ProsperCraft** [mezz/JustEnoughItems#1373]
Is this something you can help with?
at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:62)

https://github.com/InfinityRaider/InfinityLib/issues/24

**Comment by mezz** [comment]
Thanks for the report!

I think this is caused by CCL catching render exceptions. It does not clear your custom tesselator, so the next thing that renders crashes.
https://github.com/TheCBProject/CodeChickenLib/commit/e03fd65b6349908a446d8849a6da104ed3d1c449

@covers1624 can you work this out? This is the crash I warned you would happen when you implemented the render exception handling :P

**Comment by covers1624** [comment]
Its entirely gated behind a config option with large amounts of warnings, check your config and disable `attemptRecoveryOnItemRenderException` if its enabled.

**Comment by mezz** [comment]
Here's the old issue from when I had JEI catch rendering errors in the same way, I wasn't able to find it before because I didn't remember it was involving InfinityLib: https://github.com/InfinityRaider/InfinityLib/issues/20

**Comment by covers1624** [comment]
The bottom of that issue seems to implicate JourneyMap, Perhaps giving us the full log would help. I suspect the actual issue will be logged in the log file, that should be addressed not this crash.

**Comment by mezz** [comment]
Once I made JEI stop catching the errors, the thread shifted off topic to different crashes (the things that I was catching before).

**Comment by covers1624** [comment]
Ccl catches them, but enhances then rethrows unless that config value is true and it's not by default. We are gonna need the full log for this one.

**Comment by ProsperCraft** [comment]
I will have to reproduce the crash because I wiped my instance and reinstalled to be able to log back in to the server.
