### ISSUE TITLE
Problems with the mod on a Server

### ISSUE THREAD

**Issue by TheVexTv** [mezz/JustEnoughItems#1376]
Thank you for reporting!
[crash-2018-09-30_15.36.54-client.txt](https://github.com/mezz/JustEnoughItems/files/2442872/crash-2018-09-30_15.36.54-client.txt)
I can't look at recipes on a server, where the mod is installed. The mod is in the "coremods" folder, but it doesn't work. If you try to press R on an item, your game crashes and you get this crash report:

**Comment by mezz** [comment]
Thanks for the report!
The mod is a regular mod, it just goes in the "mods" folder.
Please try putting it in the mods folder, remove NEI, and see if you still have an issue.
