### ISSUE TITLE
Literally cannot enter cheatmode, it instantly disables itself

### ISSUE THREAD

**Issue by Straighten-Your-Back** [mezz/JustEnoughItems#1379]
Clicking the button to enable cheat mode only enables it for so long as that menu is open. As soon as I close the menu, cheat mode is disabled, meaning I can't use it.

After several tries of this, a message appeared in my chat, telling me I don't have permission for cheat mode.

The whole reason I installed this mod was for cheat mode. How do I enable it?

**Comment by mezz** [comment]
On a server, to enable JEI's cheat mode you need to be OP or creative on the server.
If you're playing singleplayer, you will need to play with cheats enabled.
This is to make sure players are not able to easily cheat on servers where they shouldn't be.

See [How to turn cheats on or off in Minecraft here.](https://gaming.stackexchange.com/questions/277542/how-to-turn-cheats-on-or-off/311481#311481)

**Comment by Straighten-Your-Back** [comment]
I'm in singleplayer.

What you're saying is I can't enable cheats unless cheats are already enabled?

**Comment by mezz** [comment]
Minecraft itself has an option for cheats being enabled or disabled in each singleplayer world, it's an option when you create the world. JEI looks at that option to decide if it should allow cheating in JEI.
See the link I put in my last comment for ways to enable cheats in your singleplayer world.

**Comment by Straighten-Your-Back** [comment]
I'm aware of that. I installed JEI because I wanted a mod to insert items into a save that has cheats disabled. 

However! It seems I don't actually need this mod for that at all, I can just enable creative on the save. Thank you.

**Comment by mezz** [comment]
Ah, ok. Yeah, JEI is not intended to be a cheating tool, it tries to go along with what vanilla is doing.
Glad you were able to resolve the issue.
