### ISSUE TITLE
Optifine prevent JEI from showing up?

### ISSUE THREAD

**Issue by SniperHauss89** [mezz/JustEnoughItems#138]
Hello, as the title says it seems with the latest version of Optifine it prevents JEI from showing up whether it's the most recent beta JEI build or the latest recommended one it does the same thing... is this a known bug? because I couldn't find anything about it.

Forge - 1.8.9-11.15.0.1715
Optifine - 1.8.9_HD_U_H2
JEI - 1.8.9-2.21.1.100

**Comment by mezz** [comment]
Thanks for the report!
I just loaded up a new instance with those mods and it works fine.
Can you paste your client log to gist.github.com and link it here?

**Comment by SniperHauss89** [comment]
Ok here it is https://gist.github.com/SniperHauss89/cea4882a3a8e6045b7cf and I forgot to add that I have JourneyMap 5.1.3 as well but it works with it as well unless I add Optifine...

**Comment by mezz** [comment]
Did you accidentally close JEI with control-O?

**Comment by SniperHauss89** [comment]
No, I tried that hotkey though and nothing happens and I just let Optifine generate a new options file and still nothing. also I went through toggling various Optifine settings on/off as well to see if one ore more are causing an issue and nothing with that either.

**Comment by mezz** [comment]
I have the exact mods and forge you have and it's working.
Are you connecting to a vanilla sever?

**Comment by SniperHauss89** [comment]
yes and no both connecting to single player and to a vanilla server doesn't work with Optifine in although without it, it still works on the server. I'm really at a loss at what could be happening I let it generate a new Optifine file and such.

EDIT: so I reset all of the configs and it works now oddly... Thanks for trying to help though ^.^

**Comment by mezz** [comment]
I'm sorry I really don't know. Try asking Optifine.
