### ISSUE TITLE
Crash When Searching

### ISSUE THREAD

**Issue by Enverex** [mezz/JustEnoughItems#1380]
I've recently had crashes (maybe one each day over many hours of play) where Minecraft will lock up for a good few seconds and then eventually crash out when searching for something in NEI. Only happens very rarely, as I'm continually using NEI and it's normally fine.

Crashlog - https://gist.githubusercontent.com/Enverex/33a65d3c7ac10cde58bfd2f3b9da1b46/raw/ad91c59991a672cb190001e541065891af489e70/gistfile1.txt

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Forestry
	Ingredient Info: 1xitem.crated.natura.materials.4@0 forestry:crated.natura.materials.4
```
Please report this to Forestry, it seems to be a Forestry or Natura issue.

**Comment by Enverex** [comment]
Thought that may be the case, thanks.
