### ISSUE TITLE
Rendering Screen Crash using beta jei_1.12.2-4.13.1.220

### ISSUE THREAD

**Issue by Parapetenia** [mezz/JustEnoughItems#1386]
Hello and thank you for the great mod.  I recently mashed some mods together and seem to be getting a semi-random crash while mousing over blocks and items in JEI.  No particular items seem to cause it, but I'll admit I have not really tested it.  It is easily reproduced by mousing over JEI overlays over and over(I did a figure eight this last time for the report).  At first it seemed rare, maybe only every other day, but the last few days it will crash constantly.  This is my first crash report, so my apologies in advance for my ignorance. ;)

Most recent PasteBin:
[https://pastebin.com/5aAWsHT3](https://pastebin.com/5aAWsHT3)

**Comment by mezz** [comment]
Thanks for the report!
It looks like you might have JEI's debug mode enabled in the config file.
It's only really intended for testing JEI itself and could cause problems, you should try disabling it.

**Comment by Parapetenia** [comment]
Oh goodness. Somehow overlooked that. Thank you.
