### ISSUE TITLE
Crash w/ Client JEI. Works fine on Server

### ISSUE THREAD

**Issue by Gamerbolts** [mezz/JustEnoughItems#1387]
HI there, I am creating a modpack and was testing some things, I got all the mods I wanted and then added JEI, the launcher goes to 6/7 and it gets stuck on JEI, not too sure why.

For some reason I get two crash logs, a minute apart from each other
https://pastebin.com/Q69ECHp7
https://pastebin.com/bWBn9QA1

They look identical, but wanted to post both just in case.

I know others have posted this before with the GC Overhead Limit. But as you can see from my log I have nearly 8GB allocated. The server I am running boots up just fine, so it's only the client that is having issues.

I have used both the beta and release versions to no avail. Any help is appreciated. thank you!

**Comment by temp1011** [comment]
Different things are loaded on the client and server starting up, so if you have enough memory for one you may not for the other.

**Comment by mezz** [comment]
Thanks for the report!
This is an `OutOfMemoryError` and so it's mostly unrelated to JEI. 

Based on the error message, you will need to try allocating more memory to Minecraft, even if you are at 8GB already.
I am not sure why your back needs so much memory, maybe some mod is hogging a lot of ram, or maybe you just have an incredible number of mods.
