### ISSUE TITLE
Name consistency through mods.

### ISSUE THREAD

**Issue by Maxwelljones** [mezz/JustEnoughItems#1389]
Hello!

Would you please be so nice and format your jar file with - instead of _ 
Like `jei-1.12.2-4.13.1.220.jar`
Every other mod do use the same standard. It would help us modpackers process your mod as fast as the others instead of renaming the zip file all the time.

Thank you in advance :)

**Comment by Ommina** [comment]
OK, for my own edification.  Why does this matter?

This being the Internet, I hasten to add, I don't ask to be snarky.  If there is a technical reason for avoiding the underscore, I'd quite like to learn what it is.

**Comment by Maxwelljones** [comment]
Hello! Thank you for your answer.

I am modpacker.
Packing mods is taking a long time through Solder: https://solder.io/
But when they are inside solder, I can easilly use the mods in various packs without starting from scratch each time.

Here's the procedure:
Every time I add a mod, I take the new mod (or new version) and pack it into a zip file (each mod version into a separate zip file). I managed to have the zip file created through a .bat and renaming the zip in lowercase letters.

Then when I do add it to Solder, it is automatically looking for the modname-version.zip
When it doesn't match, I would need to create a new version of the mod. Means each time I pack a new version: this is a very tedious work as I do need to manually input all the data corresponding to the mod: author name, author website, author donation link etc. so that in the end, everything works with the credits, links back and so on.

Easier is when all the mods have the same naming convention, which they all do except JEI and some newcomers with unknown mods.

I am happy to answer deeper to you if this is unclear or needs more detail here or on discord. You can find me in the following discords: "technic", "fdb", "modded minecraft" for example.

**Comment by TehNut** [comment]
What if *you* fixed your script to account for underscores?

**Comment by Maxwelljones** [comment]
in other mods underscores may be elsewhere. But I thought about it.

**Comment by TehNut** [comment]
Well I can assure you it is very possible.

**Comment by Maxwelljones** [comment]
Okay ^^ Probably with more than my knowledge in programming :D 
I'll try to get help on that matter.. or continue to change it every update manually ..

Thanks for giving me a clear position anyway ^^
