### ISSUE TITLE
Please remove useless items.

### ISSUE THREAD

**Issue by Devintrainer** [mezz/JustEnoughItems#139]
Waila shows me that the many useless items are from this mod. They have varied durability. An example of this is "lfgdwjtkqips". They also don't appear in the menu hat is the main purpose of JEI.
![2016-01-22_20 07 07](https://cloud.githubusercontent.com/assets/16846589/12527598/dce24b22-c143-11e5-954d-165ebc0dffea.png)
.

**Comment by mezz** [comment]
Thanks for the report!
Turn off Debug Mode in JEI's config under Advanced.
Why did you turn it on?

**Comment by mezz** [comment]
For the latest version, I hid the debug option away in the config file. 
It will no longer show up in the config gui as a tempting/misleading option.
