### ISSUE TITLE
Slow ingredient filter building is causing GC overhead limit to be exceeded

### ISSUE THREAD

**Issue by Alan19** [mezz/JustEnoughItems#1391]
When I was loading my modpack, JEI was only processing ~100 items at a time every few seconds when building the ingredient filter and eventually crashed. The game also seemed to freeze in between processing the items, possibly because of GC.

Log: https://gist.github.com/Alan19/e96a5692c59669aef7a50e359d68ed76
Crash log: https://gist.github.com/Alan19/0221f219eb617fb613bfe0371cd08cc6

**Comment by mezz** [comment]
Thanks for the report!
JEI loads last, so if you don't have enough memory it can be the thing that pushes it over the edge.
Try allocating more memory, this crash is an `OutOfMemoryError`.

**Comment by Alan19** [comment]
Somehow adding natural pledge and updating the rest of the mods caused the minimum amount of RAM to go to 7GB from 4.5

**Comment by Alan19** [comment]
I was able to load into the game with 5 gigs of RAM after removing JEI and natural pledge

**Comment by Alan19** [comment]
Downgrading EnderIO helped with the loading times a lot but I'm getting garbage collection lag at 5.5 GB of RAM when 5GB was enough before all of the mods updated. Removing JEI stops the garbage collection lag.

**Comment by HenryLoenwind** [comment]
Can you give me the Ender IO version numbers that changed memory consumption that much that it became noticeable for you?

**Comment by Alan19** [comment]
EnderIO, EnderZoo, and Endergy 5.0.37
Endercore 0.5.43

**Comment by HenryLoenwind** [comment]
and downgrading to which version helped? .36?

**Comment by Alan19** [comment]
Yes. The new version of JEI still causes a RAM increase when Ender IO is updated

**Comment by Alan19** [comment]
The newest version of EnderIO (.38) is still causing a RAM increase

**Comment by HenryLoenwind** [comment]
Our current guess is that that's caused by the extra Dark Steel Upgrades recipes. There's quite a lot of them (especially with Endergy installed) and .37 added some upgrades, which increased the amount of recipes.

**Comment by Alan19** [comment]
Is there any way EnderIO could reduce the RAM usage or is the only solution more RAM? Also, pulling Endergy makes the pack playable at 5GB of RAM but causes garbage collection lag spikes in singleplayer.

**Comment by Alan19** [comment]
Looks like one of the recent updates fixed this issue as well as removing Endergy
