### ISSUE TITLE
A more zealous blacklist

### ISSUE THREAD

**Issue by SimonMeskens** [mezz/JustEnoughItems#1392]
Right now the item blacklist only hides items from the list, can we get a blacklist that completely removes every vanilla/mod recipe that has that ingredient as part of it?

**Comment by TehNut** [comment]
That is out of scope of this project. You should use CraftTweaker for that.

**Comment by SimonMeskens** [comment]
I don't want to remove the recipes from the game, I simply want to hide them in JEI. As far as I know, CT can't do this and never will, since JEI doesn't have that functionality.

**Comment by mezz** [comment]
The item blacklist is mainly intended to hide items like facades from the list, where it is cluttering the list.
Recipes should still show those items if you look them up though.
If you need a more complete solution, removing the items and recipes with CraftTweaker will work.

**Comment by SimonMeskens** [comment]
again, I'm not sure if CT can remove recipes? Sure, I can remove recipes from the game with CT, but I don't see any way to remove a recipe just from JEI.

To put it differently: I want to make certain items completely unsearchable. You shouldn't be able to see it in any custom recipe handler at all or search for recipes or uses. Those recipes should still work in-game of course.

**Comment by mezz** [comment]
I don't think this particular case is supported by anything right out of the box.
Hiding recipes but allowing them to be crafted in-game still doesn't make much sense to me, but you could make an addon that can do it using JEI's existing API.

**Comment by SimonMeskens** [comment]
I might actually do that. I have a use case similar to Gamestages with more of a bend towards turning JEI into a discovery tool (as in, recipes for items only show up if you've discovered the item). It's kinda like the JEI version of the silly vanilla recipe book. I was trying to hack it, but creating a Gamestages addon shouldn't be too hard, looking at the JEI source. Thanks anyway.
