### ISSUE TITLE
JEI Crashing when using less than 6GB RAM

### ISSUE THREAD

**Issue by f0rgotten** [mezz/JustEnoughItems#1394]
For some reason regardless in having JEI Addons or not the game crashes when using less than 6GB of RAM it Crashes during the startup when it loads mods.

Ive tried plenty of Java Arguments and non of them work (Willing to try more lines though)

Java Arguments: -XX:+UseG1GC -Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Crash report: https://pastebin.com/SAzYZwf5

**Comment by mezz** [comment]
Thanks for the report!
The crash report you linked seems to be reporting some other issue:
```
SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.
```

**Comment by f0rgotten** [comment]
Ye I checked my video drivers and tried the disable the splash screen but nada

**Comment by mezz** [comment]
Based on the crash report, this issue doesn't seem to be caused by JEI.
Do you have some other information that shows JEI is the cause?

**Comment by f0rgotten** [comment]
Not really, im new to the whole making a modpack thing but i just made a new profile and added jei only and it loaded fine

**Comment by mezz** [comment]
You might want to try copying your mod pack to a new folder and removing some mods to see which one might be causing an issue. 
If it really is a graphics driver issue you may have a harder time tracking down the solution.

Unfortunately, in any case I don't think I can be much help here. If you are still stuck you should look for another place to discuss the issue or look on Discord for a modded minecraft channel where more people can help. Good luck!

**Comment by Ommina** [comment]
For what it is worth, it does show JEI as errored, but I wonder if this is just OutOfMemory in disguise.  While the titles says "less than 6GB", the crash report shows 4GB allocated, and with 263 mods loaded, that feels a bit tight to me.

**Comment by mezz** [comment]
I think you're right @Ommina .
Looking at Forge's splash screen code, the stack trace here might be cut off before showing actual cause of the crash. It logs it with the prefix "Splash thread Exception" in the log earlier, that should show the whole thing.

@f0rgotten, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by f0rgotten** [comment]
Ok so i understand that 4GB of RAM is pushing it with the amount of mods i have but i remember modpacks being easy to run at 6GB or less pretty easily, guess im just not that up to date on Java and modded minecraft anyways heres the latest.log https://gist.github.com/f0rgotten/6e1fa7244982e7f58107176b1b90d19e

**Comment by mezz** [comment]
Yeah now that the splash screen is gone you have a clear OutOfMemory error:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

When you have more mods it takes more memory to run. Some mods take lots more memory than others.
JEI loads last, so it's often the last straw and the game crashes with out of memory at that point.

**Comment by f0rgotten** [comment]
Huh fair enough sorry for bothering with a dumb little error lmao

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
