### ISSUE TITLE
worldSettings.cfg

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1395]
I would like to suggest moving worldSettings.cfg to somewhere other than the configuration folder. Perhaps having this information save to the world folder, or to an external folder, like journeymap does. As this file is in the configuration folder, it has to be excluded when exporting a pack before publishing to prevent conflicts.

**Comment by mezz** [comment]
This config has been moved to a subfolder using the world name, to avoid conflicts.
