### ISSUE TITLE
Specificity in IModRegistry#handleRecipes

### ISSUE THREAD

**Issue by LordMonoxide** [mezz/JustEnoughItems#1397]
I have a recipe type that extends ShapelessRecipes, and adds one additional piece of data.  Since it extends ShapelessRecipes, it's automatically handled by the vanilla plugin.  Unfortunately, I can't override that by registering my own handler for it.

It would be useful for JEI to send recipes to the **most specific** handler for that recipe class.

e.g.:
```
registry.handleRecipes(ShapelessRecipes.class, ...);
registry.handleRecipes(MyShapelessRecipes.class, ...);
```

If I view a MyShapelessRecipe, I would expect it to be matched by the handler for MyShapelessRecipe, even though it technically matches both.

**Comment by mezz** [comment]
Thanks for the request!
JEI is supposed to use the exact handler first, the code is like this (simplified a bit to remove some legacy handling code):
```java
// first try to find the exact handler for this recipeClass
for (IRecipeHandler<?> recipeHandler : recipeHandlers) {
	if (recipeHandler.getRecipeClass().equals(recipeClass)) {
		// noinspection unchecked
		return (IRecipeHandler<T>) recipeHandler;
	}
}

// fall back on any handler that can accept this recipeClass
for (IRecipeHandler<?> recipeHandler : recipeHandlers) {
	if (recipeHandler.getRecipeClass().isAssignableFrom(recipeClass)) {
		// noinspection unchecked
		return (IRecipeHandler<T>) recipeHandler;
	}
}
```
The full code for it is here: https://github.com/mezz/JustEnoughItems/blob/e20c3a588c20e41b44794b1909b11c7c840a497b/src/main/java/mezz/jei/recipes/RecipeRegistry.java#L450-L491

**Comment by LordMonoxide** [comment]
Hmm, that seems like it should handle the exact problem I was having properly.  I'll have to look into it a bit more closely and see what was going wrong.
