### ISSUE TITLE
Recipe registry plugin lagging

### ISSUE THREAD

**Issue by TJesionowski** [mezz/JustEnoughItems#1399]
I'm running JEI in the Stoneblock modpack with ~7GiB allocated to minecraft, about 1GiB of which is kept in swap on an SSD during normal operation. I've noticed a recurrent problem wherein using the JEI search bar or loading some crafting recipes sometimes causes a severe drop in framerate, even after the search is complete.
A quick glance at the log showed this message:
`[01:18:49] [main/WARN] [jei]: Recipe registry plugin is slow, took 134.7 ms. class mezz.jei.recipes.InternalRecipeRegistryPlugin
`
I just confirmed my suspicion that vanilla items do not have this problem, so I suspect the problem is that a large recipe list is stored as a linked list of some variety internally, requiring excessive pointer chasing to access the later items of the list, but not earlier items in the list (ie: vanilla iron bars).

Also probably related to #1356.

Writing this after midnight so not really sure, but probably could fix by grouping recipes into arrays rather than having a list node for each one, or increasing the array size if this is already done. I haven't looked at the code because midnight, but I'll try and give it a glance tomorrow.

**Comment by mezz** [comment]
Thanks for the report!

Please feel free to look into the code and try out performance improvements.
I've taken some care to design JEI with good data structures fundamentals, but (like other mods) it is intended to be fully loaded into ram at all times. If you're swapping ram to disk then things are going to be slow.
