### ISSUE TITLE
Thaumcraft aspects in items search (enhancement request)

### ISSUE THREAD

**Issue by MacChuck** [mezz/JustEnoughItems#140]
Would it be possible to make it so you can search JEI for a Thaumcraft aspect (say, Ordo), and click on it to get a list of what items are registered as having ordo in them? I know you can look in the Thauminomocon, but sometimes it is hard to tell what an item is when it is scrolling by.

**Comment by Prospector** [comment]
Sounds like an idea for JustEnoughResources.

**Comment by MacChuck** [comment]
Oh? I thought JEI itself added the Thaumcraft 5 recipes, hence why I requested it here.

**Comment by TehNut** [comment]
Nope, it's [JEIAddons](https://github.com/mezz/JEIAddons). JEI is _only_ vanilla.

**Comment by MacChuck** [comment]
Closing and opening a request on the JEIAddons tracker since it is more appropriate there.
