### ISSUE TITLE
JEI failing to show any recipes (restone++ behaving badly)

### ISSUE THREAD

**Issue by HoldYourWaffle** [mezz/JustEnoughItems#1400]
My JEI doesn't show any recipes, and displays any text I put in the search bar in red.

Screenshot:
![Screenshot](https://i.imgur.com/RjDs5MT.png)

I found [this](https://gist.github.com/HoldYourWaffle/0d19a2cb04b6469c4a041268ef648dc9) in the log. I have about 70 mods loaded, but it looks like it's a recipe from Thermal Foundation being weird. I'm not sure where I should report this, so I'm sorry if I chose wrongly (my choice was based on the fact that I think that one mod shouldn't cause JEI to fail completely).

If you need more information I'll gladly provide it.

**Comment by mezz** [comment]
Thanks for the report!
From the crash log it looks like some mod has replaced the crafting table with air.
Please try removing some of your mods and try to narrow down which mod is causing the problem.
Once you've narrowed it down, I can add some protections in JEI against this issue.

**Comment by HoldYourWaffle** [comment]
That'd explain the no-texture and broken crafting table issue I had. I did some testing; no idea what is going on here.

First I discovered that [Redstone++](https://minecraft.curseforge.com/projects/redstoneplusplus) was the bad behaving mod. However, loading just JEI & Redstone++ crashes the game on startup. (I reported this to them [here](https://minecraft.curseforge.com/projects/redstoneplusplus/issues/47)).

I tried to figure out at what point it changes from completely crashing to silently failing horribly (breaking JEI and the crafting table), but I can't determine which mod causes it. My results:

| Mods loaded  | Result |
| ------------- | ------------- |
| Everything except Redstone++  | Perfectly fine |
| JEI + Redstone++  | Crashes on startup |
| Mods of which I could *imagine* them having something to do with this | Crashes on startup |
| Loading everything | Silently failing |

I don't really want to test 70 mods individually to check which one causes the transition (I wouldn't be surprised if it were multiple together...), is this really necessary? It seems like Redstone++ just behaves very badly with JEI.

**Comment by mezz** [comment]
I tried just JEI and Redstone++ but things worked fine.
It does look like Redstone++ replaces the crafting table though, so it's most likely part of the issue.
Let me know if you find a reliable way to reproduce this problem.

**Comment by HoldYourWaffle** [comment]
Sorry, forgot about this.
I did some more testing with the latest versions of everything (non-beta) and forge 14.23.5.2768. I found out that the issue is 'catalysed' by [liteloader](http://www.liteloader.com/):

- *No liteloader* + JEI + Redstone++: everything works fine
- Liteloader + JEI: works fine
- Liteloader + Redstone++: works fine
- Liteloader + JEI + Redstone++: [crashes](https://pastebin.com/zzawYitX) on startup

I can't find a way to reproduce the original behavior anymore, so maybe that was caused by another mod in my pack.

**Comment by mezz** [comment]
I think this is related to an issue I have reported to Liteloader here:
http://develop.liteloader.com/liteloader/LiteLoader/issues/53

**Comment by HoldYourWaffle** [comment]
The liteloader issue hasn't had any activity in 5 months, is there any sign of this getting fixed soon?

**Comment by mezz** [comment]
There hasn't been a commit to Liteloader in over a year at this point, so unfortunately I do not think there will be a fix for this issue.

**Comment by HoldYourWaffle** [comment]
Hmmm that's unfortunate. Is there any way you can add a safeguard for this to JEI itself?

**Comment by mezz** [comment]
I don't fully understand the issue, unfortunately.
I created a test mod that can cause LiteLoader to break, but I do not know why it is breaking or how it impacts JEI so badly.

From JEI's perspective, it is seeing most item stacks are suddenly empty (the item inside is just "air" in your crash report). It is a really surprising bug, and when I looked into it I wasn't able to find a straightforward way to have JEI recover from it.

**Comment by HoldYourWaffle** [comment]
Maybe it's possible to add some kind of error message? I feel like there must be a better solution than having it break with no clue what caused it.

**Comment by mezz** [comment]
JEI has been written to try its hardest not to crash the game... I never really anticipated this situation where something is breaking every single item.

There should be a lot of errors in the log when this happens, but from JEI's perspective it really doesn't have any idea what's wrong.

We could try something like `if liteLoader exists and we have no items, crash`, but it would take a decent amount of extra work to properly test the error in various pack setups so I am going to leave it alone for now. If you have the time and can test it, I'd accept a PR to have JEI crash in that situation for 1.12.2.

**Comment by Sandro0000** [comment]
As the creator of Redstone++, I can confirm that Redstone++ is not compatible with LiteLoader under Minecraft 1.12.x due to this exact issue: http://develop.liteloader.com/liteloader/LiteLoader/issues/53. If both are installed, gameplay is unstable. This cannot be fixed by disabling anything in the config, nor can it be fixed on my end. You will have to drop either LiteLoader, and it's dependents, or Redstone++.

I am not aware of any issues with the latest stable version of Redstone++ (ver1.2d) and JEI.
