### ISSUE TITLE
Crash when viewing harvestcraft recipes

### ISSUE THREAD

**Issue by Scalegend** [mezz/JustEnoughItems#1401]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2018-11-18 02:10:20 EST
Description: Updating screen events

java.lang.IllegalArgumentException: Invalid ingredient found. Parameter Name: value Class: class net.minecraft.item.ItemStack Object: 1xitem.bubblywateritem@0
    at mezz.jei.util.ErrorUtil.checkIsValidIngredient(ErrorUtil.java:226)
    at mezz.jei.input.ClickedIngredient.<init>(ClickedIngredient.java:21)
    at mezz.jei.input.GuiContainerWrapper.getIngredientUnderMouse(GuiContainerWrapper.java:30)
    at mezz.jei.input.InputHandler.getIngredientUnderMouseForKey(InputHandler.java:153)
    at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:240)
    at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:219)
    at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:201)
    at mezz.jei.input.InputHandler.onGuiKeyboardEvent(InputHandler.java:68)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_461_InputHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:513)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1758)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4440)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Mitchell_Miller'/1519, l='MpServer', x=-129.69, y=70.00, z=32.41]]
  Chunk stats: MultiplayerChunkCache: 441, 441
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-130,64,51), Chunk: (at 14,4,3 in -9,3; contains blocks -144,0,48 to -129,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 17278 game time, 17278 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 72 total; [EntityZombie['Zombie'/11776, l='MpServer', x=-83.50, y=68.00, z=7.50], EntityZombie['Zombie'/11782, l='MpServer', x=-101.50, y=26.00, z=20.50], EntityZombie['Zombie'/11787, l='MpServer', x=-105.50, y=22.00, z=16.50], EntityZombie['Zombie'/11788, l='MpServer', x=-106.50, y=22.00, z=17.50], EntityZombie['Zombie'/11789, l='MpServer', x=-102.50, y=22.00, z=16.50], EntitySkeleton['Skeleton'/11790, l='MpServer', x=-102.50, y=22.00, z=14.50], EntitySpider['Spider'/11282, l='MpServer', x=-110.50, y=31.00, z=34.50], EntityZombie['Zombie'/11795, l='MpServer', x=-150.50, y=66.00, z=11.50], EntityZombie['Zombie'/11288, l='MpServer', x=-116.50, y=68.00, z=13.76], EntitySkeleton['Skeleton'/11800, l='MpServer', x=-79.50, y=26.00, z=57.50], EntityCreeper['Creeper'/11801, l='MpServer', x=-135.65, y=16.00, z=-11.49], EntityBat['Bat'/11805, l='MpServer', x=-57.47, y=20.96, z=51.45], EntityZombieVillager['Zombie Villager'/11807, l='MpServer', x=-129.50, y=18.00, z=-7.50], EntityZombieVillager['Zombie Villager'/11808, l='MpServer', x=-129.50, y=18.00, z=-10.50], EntityItem['item.item.egg'/11041, l='MpServer', x=-129.84, y=71.00, z=15.05], EntitySheep['Sheep'/10530, l='MpServer', x=-145.82, y=67.00, z=62.38], EntitySquid['Squid'/11559, l='MpServer', x=-191.28, y=46.39, z=92.32], EntitySquid['Squid'/11564, l='MpServer', x=-113.35, y=57.89, z=-29.61], EntitySkeleton['Skeleton'/11060, l='MpServer', x=-124.61, y=71.00, z=9.70], EntityChicken['Chicken'/11319, l='MpServer', x=-146.50, y=63.00, z=70.50], EntityZombie['Zombie'/11327, l='MpServer', x=-153.50, y=21.00, z=108.50], EntityZombie['Zombie'/11328, l='MpServer', x=-156.50, y=21.00, z=109.50], EntitySkeleton['Skeleton'/11341, l='MpServer', x=-116.83, y=70.00, z=7.95], EntityWitch['Witch'/11342, l='MpServer', x=-129.30, y=16.00, z=-11.50], EntitySkeleton['Skeleton'/11346, l='MpServer', x=-106.22, y=31.00, z=18.49], EntityItem['item.item.enderPearl'/11616, l='MpServer', x=-113.39, y=66.00, z=-1.96], EntityHorse['Horse'/11624, l='MpServer', x=-95.50, y=65.00, z=19.50], EntityPig['Pig'/11625, l='MpServer', x=-98.50, y=65.00, z=18.50], EntityChicken['Chicken'/11626, l='MpServer', x=-98.57, y=65.00, z=15.80], EntityCreeper['Creeper'/11638, l='MpServer', x=-185.18, y=13.00, z=38.58], EntitySkeleton['Skeleton'/10875, l='MpServer', x=-65.50, y=25.00, z=-10.50], EntityItem['item.item.egg'/11647, l='MpServer', x=-108.92, y=70.00, z=37.59], EntityBat['Bat'/11656, l='MpServer', x=-108.68, y=13.30, z=37.47], EntityCreeper['Creeper'/11658, l='MpServer', x=-147.51, y=69.00, z=18.80], EntityChicken['Chicken'/6029, l='MpServer', x=-131.51, y=71.00, z=12.82], EntityZombie['Zombie'/11661, l='MpServer', x=-153.15, y=66.00, z=31.41], EntityZombie['Zombie'/11662, l='MpServer', x=-95.50, y=63.00, z=3.50], EntityChicken['Chicken'/143, l='MpServer', x=-119.08, y=70.00, z=38.91], EntityChicken['Chicken'/145, l='MpServer', x=-111.77, y=67.00, z=17.12], EntityChicken['Chicken'/146, l='MpServer', x=-111.49, y=67.00, z=5.87], EntitySkeleton['Skeleton'/11675, l='MpServer', x=-121.50, y=15.00, z=30.50], EntitySquid['Squid'/11433, l='MpServer', x=-180.08, y=43.72, z=-10.81], EntitySkeleton['Skeleton'/11179, l='MpServer', x=-134.38, y=16.00, z=-10.62], EntitySquid['Squid'/11435, l='MpServer', x=-174.90, y=47.69, z=-7.28], EntityCreeper['Creeper'/11190, l='MpServer', x=-121.28, y=70.00, z=16.53], EntityCreeper['Creeper'/11191, l='MpServer', x=-117.31, y=70.00, z=5.51], EntityCreeper['Creeper'/11705, l='MpServer', x=-76.58, y=17.00, z=-12.82], EntitySpider['Spider'/11706, l='MpServer', x=-130.50, y=18.00, z=-9.50], EntityZombie['Zombie'/11707, l='MpServer', x=-119.50, y=65.00, z=-3.50], EntityPig['Pig'/6078, l='MpServer', x=-109.37, y=64.00, z=-2.93], EntityCreeper['Creeper'/11711, l='MpServer', x=-78.50, y=17.00, z=-14.50], EntitySheep['Sheep'/6080, l='MpServer', x=-112.18, y=67.00, z=1.76], EntityCreeper['Creeper'/11712, l='MpServer', x=-81.50, y=17.00, z=-15.50], EntitySheep['Sheep'/6082, l='MpServer', x=-121.21, y=71.00, z=28.34], EntitySkeleton['Skeleton'/11721, l='MpServer', x=-96.50, y=26.00, z=42.50], EntityItem['item.item.egg'/9930, l='MpServer', x=-112.72, y=66.00, z=20.61], EntityCreeper['Creeper'/11722, l='MpServer', x=-114.50, y=30.00, z=42.50], EntityItem['item.item.egg'/11725, l='MpServer', x=-114.30, y=68.00, z=9.17], EntityCreeper['Creeper'/11215, l='MpServer', x=-114.81, y=66.00, z=-0.48], EntitySpider['Spider'/11727, l='MpServer', x=-117.51, y=70.00, z=9.10], EntityZombie['Zombie'/11729, l='MpServer', x=-156.76, y=64.00, z=30.50], EntityCreeper['Creeper'/11731, l='MpServer', x=-119.50, y=26.00, z=27.50], EntityCreeper['Creeper'/11738, l='MpServer', x=-120.50, y=40.00, z=43.50], EntitySkeleton['Skeleton'/11745, l='MpServer', x=-59.50, y=24.00, z=-12.50], EntityPlayerSP['Mitchell_Miller'/1519, l='MpServer', x=-129.69, y=70.00, z=32.41], EntitySkeleton['Skeleton'/11751, l='MpServer', x=-80.50, y=17.00, z=-15.50], EntitySquid['Squid'/11499, l='MpServer', x=-75.10, y=62.42, z=-3.59], EntityZombie['Zombie'/11755, l='MpServer', x=-113.50, y=33.00, z=13.50], EntityCreeper['Creeper'/11756, l='MpServer', x=-183.50, y=13.00, z=37.50], EntityZombie['Zombie'/11762, l='MpServer', x=-180.50, y=14.00, z=1.50], EntityZombie['Zombie'/11763, l='MpServer', x=-186.50, y=14.00, z=-1.50], EntityZombie['Zombie'/11767, l='MpServer', x=-120.28, y=18.00, z=-14.47]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_192, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2136470144 bytes (2037 MB) / 4211081216 bytes (4016 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2775 Optifine OptiFine_1.12.2_HD_U_E2 73 mods loaded, 73 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State     | ID                      | Version                     | Source                                                       | Signature                                |
       |:--------- |:----------------------- |:--------------------------- |:------------------------------------------------------------ |:---------------------------------------- |
       | UCHIJAAAA | minecraft               | 1.12.2                      | minecraft.jar                                                | None                                     |
       | UCHIJAAAA | mcp                     | 9.42                        | minecraft.jar                                                | None                                     |
       | UCHIJAAAA | FML                     | 8.0.99.99                   | forge-1.12.2-14.23.5.2775.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | forge                   | 14.23.5.2775                | forge-1.12.2-14.23.5.2775.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | additionalstructures    | 1.7.0                       | Additional+Structures+1.12.2+by+XxRexRaptorxX++(v.1.7.0).jar | None                                     |
       | UCHIJAAAA | additionalbanners       | 1.5.36                      | AdditionalBanners-1.12.jar                                   | None                                     |
       | UCHIJAAAA | aiimprovements          | 0.0.1.3                     | AIImprovements-1.12-0.0.1b3.jar                              | None                                     |
       | UCHIJAAAA | aroma1997core           | 2.0.0.0.b161                | Aroma1997Core-1.12.2-2.0.0.0.b161.jar                        | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAA | aromabackup             | 3.0.0.0.b112                | AromaBackup-1.12.2-3.0.0.0.b112.jar                          | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAA | aromabackuprecovery     | 3.0.0.0.b112                | AromaBackup-1.12.2-3.0.0.0.b112.jar                          | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAA | attributefix            | 1.0.1                       | AttributeFix-1.12.2-1.0.1.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | bibliocraft             | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar                            | None                                     |
       | UCHIJAAAA | bottledmilk             | 1.0.0                       | BottledMilk-1.12-1.1.0.jar                                   | None                                     |
       | UCHIJAAAA | codechickenlib          | 3.2.2.353                   | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | chickenchunks           | 2.4.1.73                    | ChickenChunks-1.12.2-2.4.1.73-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | clienttweaks            | 3.1.11                      | ClientTweaks_1.12.2-3.1.11.jar                               | None                                     |
       | UCHIJAAAA | clumps                  | 3.1.1                       | Clumps-3.1.1.jar                                             | None                                     |
       | UCHIJAAAA | morpheus                | 1.12-3.3.2                  | Morpheus-1.12-3.3.2.jar                                      | None                                     |
       | UCHIJAAAA | comforts                | 1.3.1                       | comforts-1.12.2-1.3.1.jar                                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCHIJAAAA | controlling             | 3.0.6                       | Controlling-3.0.6.jar                                        | None                                     |
       | UCHIJAAAA | creativeplus            | 1.0.2                       | CreativePlus+MC1.12.2+v1.0.2.jar                             | None                                     |
       | UCHIJAAAA | creepingnether          | 2.0                         | Creeping+Nether-2.0.jar                                      | None                                     |
       | UCHIJAAAA | customnpcs              | 1.12                        | CustomNPCs_1.12.2(26aug18).jar                               | None                                     |
       | UCHIJAAAA | endercompass            | 1.2.6.2                     | EnderCompass-1.12-1.2.6.2.jar                                | None                                     |
       | UCHIJAAAA | expandedbonemeal        | 1.2.1                       | expandedbonemeal-1.11-1.2.1.jar                              | None                                     |
       | UCHIJAAAA | extraalchemy            | 0.3.8.6.1-release           | extraalchemy-0.3.8.6.1-release.jar                           | None                                     |
       | UCHIJAAAA | forgemultipartcbe       | 2.6.0.79                    | ForgeMultipart-1.12.2-2.6.0.79-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | microblockcbe           | 2.6.0.79                    | ForgeMultipart-1.12.2-2.6.0.79-universal.jar                 | None                                     |
       | UCHIJAAAA | minecraftmultipartcbe   | 2.6.0.79                    | ForgeMultipart-1.12.2-2.6.0.79-universal.jar                 | None                                     |
       | UCHIJAAAA | waila                   | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                                  | None                                     |
       | UCHIJAAAA | inventorytweaks         | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJAAAA | jei                     | 4.13.1.220                  | jei_1.12.2-4.13.1.220.jar                                    | None                                     |
       | UCHIJAAAA | harvestcraft            | 1.12.2z                     | Pam's+HarvestCraft+1.12.2za.jar                              | None                                     |
       | UCHIJAAAA | jehc                    | 1.12.2                      | JEHC-1.12.2-1.6.1.0.jar                                      | None                                     |
       | UCHIJAAAA | jeiintegration          | 1.5.1.36                    | jeiintegration_1.12.2-1.5.1.36.jar                           | None                                     |
       | UCHIJAAAA | jepb                    | 1.2.1                       | jepb-1.12-1.2.1.jar                                          | None                                     |
       | UCHIJAAAA | journeymap              | 1.12.2-5.5.2                | journeymap-1.12.2-5.5.2.jar                                  | None                                     |
       | UCHIJAAAA | jeresources             | 0.8.9.48                    | JustEnoughResources-1.12.2-0.8.9.48.jar                      | None                                     |
       | UCHIJAAAA | kc                      | 1.12                        | knobcontrol-1.12-4.0.20.jar                                  | None                                     |
       | UCHIJAAAA | morebeautifulplates     | 1.12.2-1.0.3                | morebeautifulplates-1.12.2-1.0.3.jar                         | None                                     |
       | UCHIJAAAA | mrtjpcore               | 2.1.3.35                    | MrTJPCore-1.12.2-2.1.3.35-universal.jar                      | None                                     |
       | UCHIJAAAA | naturescompass          | 1.5.1                       | NaturesCompass-1.12.2-1.5.1.jar                              | None                                     |
       | UCHIJAAAA | nbtedit                 | $version                    | NBTEdit-0.7.jar                                              | None                                     |
       | UCHIJAAAA | netherportalfix         | 5.3.17                      | NetherPortalFix_1.12.1-5.3.17.jar                            | None                                     |
       | UCHIJAAAA | norecipebook            | 1.2.1                       | noRecipeBook_v1.2.2formc1.12.2.jar                           | None                                     |
       | UCHIJAAAA | nei                     | 2.4.2                       | NotEnoughItems-1.12.2-2.4.2.240-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | pamscookables           | 1.1                         | pamscookables-1.1.jar                                        | None                                     |
       | UCHIJAAAA | persistentcake          | 2.0.0                       | persistentcake-1.12-2.0.0.jar                                | None                                     |
       | UCHIJAAAA | projectred-core         | 4.9.1.92                    | ProjectRed-1.12.2-4.9.1.92-Base.jar                          | None                                     |
       | UCHIJAAAA | projectred-compat       | 1.0                         | ProjectRed-1.12.2-4.9.1.92-compat.jar                        | None                                     |
       | UCHIJAAAA | projectred-integration  | 4.9.1.92                    | ProjectRed-1.12.2-4.9.1.92-integration.jar                   | None                                     |
       | UCHIJAAAA | projectred-transmission | 4.9.1.92                    | ProjectRed-1.12.2-4.9.1.92-integration.jar                   | None                                     |
       | UCHIJAAAA | projectred-fabrication  | 4.9.1.92                    | ProjectRed-1.12.2-4.9.1.92-fabrication.jar                   | None                                     |
       | UCHIJAAAA | projectred-illumination | 4.9.1.92                    | ProjectRed-1.12.2-4.9.1.92-lighting.jar                      | None                                     |
       | UCHIJAAAA | projectred-exploration  | 4.9.1.92                    | ProjectRed-1.12.2-4.9.1.92-world.jar                         | None                                     |
       | UCHIJAAAA | sandro                  | 1.3 BETA-2                  | Redstone+++ver1.3+BETA-2.jar                                 | None                                     |
       | UCHIJAAAA | redstoneplusplus        | 1.3 BETA-2                  | Redstone+++ver1.3+BETA-2.jar                                 | None                                     |
       | UCHIJAAAA | rbg                     | 1.12.2-1.2.0                | Rock-Be-Gone-1.12.2-1.2.0.0.jar                              | None                                     |
       | UCHIJAAAA | seedcopy                | 3.0.6                       | SeedCopy-1.9-3.0.6.jar                                       | None                                     |
       | UCHIJAAAA | snowvillage             | 1.12.2-1.0.0                | SnowVillage-1.12.2-1.0.0.jar                                 | None                                     |
       | UCHIJAAAA | sophisticatedwolves     | 3.13.4                      | SophisticatedWolves-1.12.2-3.13.4.jar                        | None                                     |
       | UCHIJAAAA | theeightfabledblades    | 1.0.0                       | TheEightFabledBlades+V2.0.01.jar                             | None                                     |
       | UCHIJAAAA | thirstybottles          | 1.1.4                       | ThirstyBottles-1.12.2-1.1.4.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | torohealthmod           | 1.12.2-11                   | torohealth-1.12.2-11.jar                                     | None                                     |
       | UCHIJAAAA | bspkrscore              | at_0.9                      | Treecapitator-1.12-at_0.9a.jar                               | None                                     |
       | UCHIJAAAA | treecapitator           | at_0.9                      | Treecapitator-1.12-at_0.9a.jar                               | None                                     |
       | UCHIJAAAA | vbe                     | GRADLE:VERSION-GRADLE:BUILD | Vanilla+Builders+Extension-1.12.2-1.0.8.jar                  | None                                     |
       | UCHIJAAAA | vanillafix              | 1.0.9-97                    | VanillaFix-1.0.9-97.jar                                      | None                                     |
       | UCHIJAAAA | villagenames            | 2.0                         | VillageNames-1.12.2-2.0.jar                                  | None                                     |
       | UCHIJAAAA | wailaharvestability     | 1.1.12                      | WailaHarvestability-mc1.12-1.1.12.jar                        | None                                     |
       | UCHIJAAAA | waystones               | 4.0.67                      | Waystones_1.12.2-4.0.67.jar                                  | None                                     |
       | UCHIJAAAA | worldedit               | 6.1.8                       | worldedit-forge-mc1.12-6.1.8-dist.jar                        | None                                     |
       | UCHIJAAAA | reauth                  | 3.6.0                       | reauth-3.6.0.jar                                             | daba0ec4df71b6da841768c49fb873def208a1e3 |
  Loaded coremods (and transformers): ComfortsCoreLoadingPlugin (comforts-1.12.2-1.3.1.jar)
                                        c4.comforts.asm.SleepTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
                                        com.chocohead.biab.BornInABarn
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b161.jar)
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13497 Compatibility Profile Context 23.20.768.12' Renderer: 'AMD Radeon(TM) R7 Graphics'
  Suspected Mods: Just Enough Items (jei)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: AMD Radeon(TM) R7 Graphics GL version 4.5.13497 Compatibility Profile Context 23.20.768.12, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
  Type: Client (map_client.txt)
  Resource Packs: Faithful+1.12.2-rv4.zip, ModdedFaithful+1.12.2-rv1.zip, Sphax32x_Proj_Red_MC1.12.zip, Refurin+-+SophisticatedWolves32x.zip (incompatible), Find Your Way 32x.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD A12-9700P RADEON R7, 10 COMPUTE CORES 4C+6G
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I've added some new logs to try to help resolve this issue.
Please try JEI version 4.13.1.224 and let me know if that helps.

**Comment by LlubNek** [comment]
found something vaguely similar...
```
01:57:17 | FML | Client thread | error | Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$KeyboardInputEvent$Post@2631005a:
java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.item.ItemStack
	at mezz.jei.ingredients.IngredientRegistry.getIngredientType(IngredientRegistry.java:310)
	at mezz.jei.ingredients.IngredientRegistry.getIngredientType(IngredientRegistry.java:292)
	at mezz.jei.ingredients.IngredientRegistry.getIngredientHelper(IngredientRegistry.java:140)
	at mezz.jei.input.ClickedIngredient.create(ClickedIngredient.java:26)
	at mezz.jei.input.GuiContainerWrapper.getIngredientUnderMouse(GuiContainerWrapper.java:33)
	at mezz.jei.input.InputHandler.getIngredientUnderMouseForKey(InputHandler.java:165)
	at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:257)
	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:231)
	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:213)
	at mezz.jei.input.InputHandler.onGuiKeyboardEvent(InputHandler.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3331_InputHandler_onGuiKeyboardEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:513)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
01:57:17 | FML | Client thread | error | Index: 12 Listeners:
01:57:17 | FML | Client thread | error | 0: NORMAL
01:57:17 | FML | Client thread | error | 1: ASM: vazkii.quark.management.feature.DeleteItems@2b36dbd0 keyboardEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 2: ASM: vazkii.quark.management.feature.FToSwitchItems@1048910d keyboardEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 3: ASM: vazkii.quark.management.feature.LinkItems@78589506 keyboardEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 4: ASM: vazkii.quark.base.client.ModKeybinds$KeybindButtonHandler@5a88c13c onKeyinput(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 5: ASM: vazkii.quark.base.client.ModKeybinds$KeybindButtonHandler@651c9f5f onKeyinput(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 6: ASM: vazkii.quark.base.client.ModKeybinds$KeybindButtonHandler@23deb2c8 onKeyinput(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 7: ASM: vazkii.quark.base.client.ModKeybinds$KeybindButtonHandler@3d8ca503 onKeyinput(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 8: ASM: vazkii.quark.base.client.ModKeybinds$KeybindButtonHandler@7965baee onKeyinput(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 9: ASM: vazkii.quark.base.client.ModKeybinds$KeybindButtonHandler@780224fa onKeyinput(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 10: ASM: vazkii.quark.base.client.ModKeybinds$KeybindButtonHandler@2e1c91c0 onKeyinput(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 11: ASM: net.blay09.mods.craftingtweaks.client.ClientProxy@43326b35 onGuiKeyboardEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 12: ASM: mezz.jei.input.InputHandler@44d633da onGuiKeyboardEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent$Post;)V
01:57:17 | FML | Client thread | error | 13: ASM: net.gegy1000.wts.WhatsThatSlot@372c3dbe onKeyPress(Lnet/minecraftforge/client/event/GuiScreenEvent$KeyboardInputEvent;)V
01:57:18 | org.dimdev.utils.ModIdentifier | Client thread | warn | Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3331_InputHandler_onGuiKeyboardEvent_Post (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3331_InputHandler_onGuiKeyboardEvent_Post)
```

[latest.zip](https://github.com/mezz/JustEnoughItems/files/2679035/latest.zip)
[crash-2018-12-14_01.57.55-client.txt](https://github.com/mezz/JustEnoughItems/files/2679037/crash-2018-12-14_01.57.55-client.txt)
