### ISSUE TITLE
Center search bar not centered after toggling overlay

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1405]
Steps to reproduce:
1. enable "Center Search Bar" in config
2. open inventory to see the JEI overlay
3. Press O to disable the JEI overlay
4. Close inventory
5. Open inventory again.
 Now the little wrench icon is in the bottom right corner and not centered. If you now enable the JEI overlay again the search bar is still in the bottom right corner.

If you now close and open the inventory again its back in the center.

![2018-11-21_21 22 19](https://user-images.githubusercontent.com/44787395/48866601-a19b6c00-edd3-11e8-8655-87228caf2dca.png)

**Comment by mezz** [comment]
Thanks for the report!
This issue is fixed in the next release.
