### ISSUE TITLE
Whong texture - #Inventory

### ISSUE THREAD

**Issue by 139229** [mezz/JustEnoughItems#1407]
Wrong texture:
micdoodle8/Galacticraft#3555 micdoodle8/Galacticraft#3469 micdoodle8/Galacticraft#3546

**Comment by mezz** [comment]
Thanks for the report!
I am not sure this is a JEI issue, people seem confused about the real cause.
Galacticraft developers can contact me if there is a problem from JEI or they need help debugging.

**Comment by PhysicalNova** [comment]
From what I have tested, the problem seems to be JEI. I don't understand why. JEI only adds recipes right ? (well, show them to the player)
Further more, it seems that it glitches out some other textures like the hydraulic lift, but I might be wrong.

**Comment by mezz** [comment]
It may be an issue with Galacticraft's JEI plugin.
