### ISSUE TITLE
Crash when holding shift to see tooltip

### ISSUE THREAD

**Issue by Ravalli03** [mezz/JustEnoughItems#1409]
Minecraft 1.12.2
JEI 4.13.1.225
Forge 14.23.5.2768

When hitting shift to see a tooltips, game crashes

https://pastebin.com/yarTTFjS

**Comment by HenryLoenwind** [comment]
Seems to be a bug in TechReborn(Core). It assumes that the item has an energy capability without doing any checking. No idea why the item that is being rendered doesn't have one, but as JEI doesn't produce those items, just displays them, I wouldn't pin that on it.

**Comment by Ravalli03** [comment]
ok, thank you for the quick reply. i'll open an issue with TechReborn.
