### ISSUE TITLE
NPE looping in the log when loading a single player world

### ISSUE THREAD

**Issue by BBoldt** [mezz/JustEnoughItems#141]
Drasticly increases the time it takes to open a single player world. Only started happening after I updated JEI to the latest version I think.

https://paste.ee/r/7VEdV
- VTweaks-1.8.x-1.4.6
- jei_1.8.9-2.22.3.105

**Comment by oitsjustjose** [comment]
Let me know if this is on me or if it's an issue with JEI - the stacktrace makes it look like it's V-Tweaks' fault, but I can't imagine how / why - and like BBoldt said, it's specific to the new release of JEI.

Also causes a full-on Connection Time Out on my server.

**Comment by mezz** [comment]
This is JEI's fault, it calls `itemStack.getTooltip` with a null player. I catch and ignore the exceptions there, but Forge does not like the exception that is thrown in its event and logs it.

**Comment by AEnterprise** [comment]
as jei calls that (our should) on the client only you could get the get player from MC

**Comment by mezz** [comment]
JEI tries to get the information before minecraft.thePlayer is set. I'll have to find the right point and spawn a background thread or something to do it.
