### ISSUE TITLE
Missing tooltips from PickleTweaks in JEI

### ISSUE THREAD

**Issue by kellixon** [mezz/JustEnoughItems#1410]
MC 1.12.2. Forge 14.23.5.2768. All settings all mods default (clear folder config). Missing tooltips in JEI, at Minecraft GUI have. Full logs - https://gist.github.com/kellixon/2e08cec3eb42f5fa26b2c9db26bfeb10.
ps. CucumberLibrary 1.1.2+JEI 4.13.1.225+PickleTweaks 2.0.17 = same thing
![2018-11-27_15 28 33](https://user-images.githubusercontent.com/22012731/49082218-47c6f600-f25a-11e8-9727-6fca103ff179.png)

**Comment by kellixon** [comment]
![2018-11-27_15 28 41](https://user-images.githubusercontent.com/22012731/49082219-47c6f600-f25a-11e8-97d0-17b508330389.png)

**Comment by mezz** [comment]
Thanks for the report!
I have replied in the PickleTweaks issue here: https://github.com/BlakeBr0/PickleTweaks/issues/24
I will close this issue so the discussion is in one place.
