### ISSUE TITLE
NBT-Specific IIngredientBlacklist

### ISSUE THREAD

**Issue by ThePuzzlemaker** [mezz/JustEnoughItems#1411]
Hello! I am creating a Minecraft mod, [Crystalline](https://github.com/ThePuzzlemaker/Crystalline), and I am adding JEI support to it. I am wondering if there is a way to hide items in JEI with a specific NBT tag (in this case, items that are the "null/unknown" type). I have tried using this code:
```java
IIngredientBlacklist blacklist = r.getJeiHelpers().getIngredientBlacklist();
ItemStack invalidReagent = new ItemStack(CrystallineItems.reagent);
CrystallineItems.reagent.setType(invalidReagent, BaseModReagents.reagent_null);
blacklist.addIngredientToBlacklist(invalidReagent);
```
However, it seems to hide **all** items of type `crystalline:reagent`, rather than only reagents with the NBT tag `type` of `crystalline:reagent_null`.
Is there a way to do this with the JEI API?

EDIT: RIP, I haven't updated my JEI version since August. Testing again in latest JEI update.
EDIT 2: Still happens in the latest update of JEI

**Comment by TehNut** [comment]
You need to [register a subtype interpreter](https://github.com/mezz/JustEnoughItems/blob/1.12/src/api/java/mezz/jei/api/IModPlugin.java#L17) so JEI knows there's a difference between your items.

**Comment by ThePuzzlemaker** [comment]
I have done that already. Here is its code:
```java
ISubtypeRegistry.ISubtypeInterpreter reagentSubtypeInterpreter = itemStack -> {
            IReagent reagentType = reagent.getType(itemStack);
            return reagentType == null ? ISubtypeRegistry.ISubtypeInterpreter.NONE : reagentType.getRegistryName().toString();
};
r.registerSubtypeInterpreter(reagent, reagentSubtypeInterpreter);
```
