### ISSUE TITLE
Jei and FTB join team icon conflict

### ISSUE THREAD

**Issue by captcookie** [mezz/JustEnoughItems#1417]
Basically big arrow icon for bookmarks is in the way and does not allow gui to open for FTB Utilities. It's a major mod conflict. Thanks.

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/237339636568031232/518871663396257794/ScreenHunter_1900_Dec._02_13.26.jpg

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/237339636568031232/518871663396257794/ScreenHunter_1900_Dec._02_13.26.jpg

Thus preventing players from joining a team and so forth. I did try ctrl o and all the icons work except the people one.

**Comment by captcookie** [comment]
It still has issues with the latest jei 227. I am able to remove the bookmark arrows but the ftb team icon still does not work. I further tested with only jei and ftb guide, lib, quests, and utilties. When jei is removed, the other mod properly works. Then, I learned that there are layers of clickable icons. I tried selecting and deselecting. I found that if you just barely click the outter edge of the team icon on the left, you can properly select it to work. 
https://cdn.discordapp.com/attachments/237339636568031232/518941361001463811/ScreenHunter_1908_Dec._02_18.03.jpg

https://cdn.discordapp.com/attachments/237339636568031232/518941363363119154/ScreenHunter_1909_Dec._02_18.06.jpg

https://cdn.discordapp.com/attachments/237339636568031232/518941365871312946/ScreenHunter_1910_Dec._02_18.06.jpg

https://cdn.discordapp.com/attachments/237339636568031232/518941367863607297/ScreenHunter_1911_Dec._02_18.06.jpg
 
I took screenshots of the variety layers... the arrow behind the team icon, clicking the team icon, the icon next to the team icon, and finally the image of barely clicking it to work, which is straight up by random chance.

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/237339636568031232/518960926662066197/ScreenHunter_1916_Dec._02_19.24.jpg on version 229 I can click the blue icons hand to get it work. Even after the arrow is removed by hovering a on an item and then removing it- to clear the arrows, only clicking on the blue icon hands will work. If there is a way to move the arrows permanently like custom move like journey can move, i think it would work better or resize it. Up to you really. Thanks for your time. https://cdn.discordapp.com/attachments/237339636568031232/518962249231106048/ScreenHunter_1917_Dec._02_19.28.jpg

**Comment by mezz** [comment]
Thanks for reporting!
I have pushed a fix for this here: https://github.com/LatvianModder/FTBLib/pull/76
Once it is accepted and FTBLib is updated, the two mods will work together.

**Comment by mezz** [comment]
This has been fixed in JEI 4.14.0.231 and FTBLib 5.4.0.69
