### ISSUE TITLE
JEI search crashing game.

### ISSUE THREAD

**Issue by Jondotzip** [mezz/JustEnoughItems#1420]
https://pastebin.com/jcRQxKyk 
that is my crash report.
So there are a few words that crash the game when searched in JEI some being "miner" and "soul"
It would be great to know why and if there is a fix to this issue how to remedy it it is causing a real problem with this modpack i've made.

**Comment by Ommina** [comment]
This looks like a crash inside the AE2 facade creation code, not within JEI.  See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3810

I've _pretty sure_ a fix by covers1624 is already pending.

**Comment by Jondotzip** [comment]
> This looks like a crash inside the AE2 facade creation code, not within JEI. See [AppliedEnergistics/Applied-Energistics-2#3810](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3810)
> 
> I've _pretty sure_ a fix by covers1624 is already pending.

Removing AE2 and replacing it with refined storage fixed the issue thanks

**Comment by SplenectomY** [comment]
Hello, I'm having a similar error which might imply that refined storage is not safe either (crashed during search, both JEI and RS are mentioned in the stacktrace). Should I report this to them? https://pastebin.com/dc8y1vTv

**Comment by Ommina** [comment]
For those interested:

https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/3844
