### ISSUE TITLE
[Suggestion] Custom ordering of items in JEI

### ISSUE THREAD

**Issue by xkforce** [mezz/JustEnoughItems#1422]
So the idea is to be able to set the display order of items or groups of items in JEI.  eg. you could have all slabs in a group and all stairs in a group and have the slabs displayed before or after the stair group depending on the order/priority you've set for those items or groups of items.

**Comment by IMarvinTPA** [comment]
What if it were done by InventoryTweaks? 
https://github.com/mezz/JustEnoughItems/pull/1383 
https://github.com/mezz/JustEnoughItems/issues/549
and
https://github.com/Inventory-Tweaks/inventory-tweaks/pull/562

IMarv

**Comment by xkforce** [comment]
I wonder if crafttweaker might be able to do it too given there's already some degree of JEI support there and the zenscript is pretty standard.

**Comment by IMarvinTPA** [comment]
I also added other sorting options to base JEI, of them, ore dictionary is one of them, so slabs should generally get grouped together if they have that going for them.  It would be a pretty massive script to assign ore dictionary names to so many things just for sorting purposes.
