### ISSUE TITLE
[1.12.2] JEI Tooltip Oddity?

### ISSUE THREAD

**Issue by SonicX8000** [mezz/JustEnoughItems#1424]
Minecraft: 1.12.2
Forge: 14.23.5.2795

Mods: 1+
*jei_1.12.2-4.14.0.229*

-----

Unsure if this is intended but before... you can view special tooltips on certain items such as Spice of Life: Carrot Edition's 'Not eaten yet' tooltips on food-items as well as Tinker's Construct items displaying different info in the JEI Menu... however in the JEI version that I'm using... apparently that special info isn't displaying.

![](https://cdn.discordapp.com/attachments/377171551155650560/520187167096569856/jeitooltipoddness.PNG)
Here's an image with Tinker's Contruct's as well as Spice of Life: Carrot Edition. The info in the JEI Menu either doesn't show special tooltips or it shows some other info... yet when those items are in my inventory the tooltip shows as well as other info being displayed.

![](https://cdn.discordapp.com/attachments/377171551155650560/520189068655722496/jeiiteminfoduringpause.PNG)
One more thing to note... you can view the JEI Menu while the game is paused... which... I don't think that's suppose to happen. If Cheats are enabled you can even spawn items while the game is paused.

-----

The version I was using before updating was 'jei_1.12.2-4.13.0.219' and it showed the tooltip info fine in the JEI Menu, also you couldn't spawn items while the game was paused, as seen in this image.
![](https://cdn.discordapp.com/attachments/377171551155650560/520190480739205131/tooltipinfooldjei.PNG)

**Comment by mezz** [comment]
Thanks for the report!

Tooltip handlers in mods are normally given the Player so they can write extra information (like whether the player has eaten fish recently).

JEI does not pass them the player. Some mods intend for you to craft the item and have it in your inventory before you get the extra information, so if JEI showed that data it would be cheating.

I am not sure why the Tinker's Construct tooltips are different, please report the issue to them and link back here.

The issue with the main menu has been fixed in later versions, it is unrelated to the tooltips.

**Comment by SonicX8000** [comment]
Sorry for the late reply. It's not only Tinker's displaying different info but for vanilla items, to name a few...

---Diamond Axe---
*JEI*
When in main hand.
-3 Attack Speed
+8 Attack Damage

*Inventory*
When in main hand.
1 Attack Speed
9 Attack Damage

---Golden Sword---
*JEI*
When in main hand.
-2.1 Attack Speed
+3 Attack Damage

*Inventory*
When in main hand.
1.6 Attack Speed
4 Attack Damage

The values listed between the two aren't the same, however in the old version that I listed which was 'jei_1.12.2-4.13.0.219' it showed the same value between the two... using the same items in a older JEI version...

---Diamond Axe---
*JEI & Inventory*
When in main hand.
1 Attack Speed
9 Attack Damage

---Golden Sword---
*JEI & Inventory*
When in main hand.
1.6 Attack Speed
4 Attack Damage

-----

'jei_1.12.2-4.13.1.222' and up, info is different between the two, sometimes being off a-la Tinker's. Versions below that... the info was the same between the two without being odd a-la Tinker's.

I can understand that viewing the info is cheating but I'm just curious if the info being different between Inventory & JEI is suppose to be like that now.

**Comment by mezz** [comment]
I looked into this a bit more and it is actually the vanilla tooltip's way of handling this situation.
You can read a bit more about it here: https://github.com/MinecraftForge/MinecraftForge/pull/5244

Basically, when the player is there (in the inventory) it shows the weapon's stats if it was held by the the player. Without the player (in JEI) it shows the weapon's relative stats that will be applied.

**Comment by SonicX8000** [comment]
Ah... I see. I gave a look at the linked issue and it's the same thing that I'm seeing.
