### ISSUE TITLE
FPS drop with some mods

### ISSUE THREAD

**Issue by mtdudek** [mezz/JustEnoughItems#1425]
Hi,

I have huge FPS drops from over 70 to low 40s and even as low as
20s. I run Stone Block 1.0.31. 

These mods make my FPS drop below 30:
- Immersive Engineering 
- Refined Storage
- Open Blocks
- Chisel
- Mekanism ,

but there are many more that lower FPS, as said before, to 40s.

Forge : 14.23.5.2768
JEI : 4.13.1.255

Problem was also existing with applied energistics 2 covers, but
was some what fixed with branch fix-3810-3813 (not as much drop as before,
but still existing).

**Comment by mezz** [comment]
Thanks for the report!
JEI renders lots of items, if rendering the items is slow then you will see an FPS drop.
Please report this issue to the mods that have slow item rendering, I am not able to improve the rendering performance on JEI's side.
