### ISSUE TITLE
startup

### ISSUE THREAD

**Issue by Kelpy0** [mezz/JustEnoughItems#1426]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Please open a new issue with more information, I do not see any information written here.
To write a good bug report, please follow the suggestions in the issue template.
