### ISSUE TITLE
Unable to join server

### ISSUE THREAD

**Issue by iarspider** [mezz/JustEnoughItems#143]
When I try to join server, I get kicked instantly. Error message (server-side): http://pastebin.com/piUEtK8A

Forge 1722, JEI 2.22.4.106.

**Comment by iarspider** [comment]
Rolling JEI back to .105 helps.

**Comment by mezz** [comment]
Thanks for the report!
I have no trouble joining a sever on the latest version.
This crash is from a modded packet, but JEI only sends packets for certain player actions, not at login.

The only difference between .105 and .106 is that JEI gets all the item tooltips properly.
My guess is that some modded item tries sending a broken packet when JEI requests its tooltip. It seems extremely unusual to me, modded items should not need to send packets to get their tooltip. Can you try narrowing down what the conflicting mod might be?

**Comment by iarspider** [comment]
Looks like it's [NotEnoughWands](http://minecraft.curseforge.com/projects/not-enough-wands).

**Comment by McJty** [comment]
Not Enough Wands uses packets to fetch their tooltips to show information that has to be calculated serverside. This is a practice that I use a lot. RFTools also does this. Why would this be a strange thing?
As to the broken packet I will look into that

**Comment by mezz** [comment]
Thanks @McJty, I've just never seen that before. If the data sync is triggered when the tooltip is requested, doesn't that mean there will be a lag? I would normally expect the server to push updates rather than the client polling for them, but I guess there must be cases where that isn't true.

So you know, JEI is requesting tooltips as soon as `Minecraft.getMinecraft().thePlayer` is available on the client. That may expose some strange things because it's so early.

**Comment by McJty** [comment]
Well it is done with a timeout. The packet is only sent every 500 (or 250) ms.

**Comment by McJty** [comment]
I see nothing wrong with how NotEnoughWands is handling the packet and the fromBytes/toBytes is symmetrical. The way this works is that the tooltip code sends (at timed intervals) a packet to the server to calculate some data (this is a small packet containing only an integer ID) and then the server calculates some stuff and sends a reply packet back to the client using:             PacketHandler.INSTANCE.sendTo(msg, player);

It works fine usually so I'm wondering what could go wrong if this is done too early and how I can protect against that?

**Comment by mezz** [comment]
I don't really know without stepping through NotEnoughWands sending and receiving the packet. I can try doing that later if you're still stumped.

**Comment by McJty** [comment]
I will first try to put latest jei in my dev env and see if I can reproduce it myself in my dev env. If I can't find it I'll let you know. Thanks

**Comment by mezz** [comment]
Talked more with McJty, and ended up making JEI friendlier to mods by loading later.
https://github.com/mezz/JustEnoughItems/commit/159bd71af22390e7e9c8c1bb42cc1254df731331
