### ISSUE TITLE
[Suggestion] Add config option to hide JEI in specific GUIs

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [mezz/JustEnoughItems#1431]
Please add an config option which allows players to add gui names, where JEI should be hidden so that this does not happen:
![image](https://user-images.githubusercontent.com/27149563/49701286-d0467e80-fbea-11e8-8d1a-06856be0b9ef.png)
(not only an pixelmon issue, this happens with some other mods too)

**Comment by mezz** [comment]
Thanks for the report!

This is mainly an issue with Pixelmon, I have helped them with it before and I think they'll know how to fix it.
Please make sure to report the issue to them.

In the meantime, you can use `Ctrl-O` (or any hotkey you set for it) to toggle JEI on and off. That will let you manually hide it on guis like this one.
