### ISSUE TITLE
Advanced Solar Panels JEI Error

### ISSUE THREAD

**Issue by bookerthegeek** [mezz/JustEnoughItems#1435]
# Heyo #
Just cross posting so you know, JEI is throwing an error with [Advanced Solar Panels](https://minecraft.curseforge.com/projects/advanced-solar-panels). I have the error it throws posted over [HERE](https://gist.github.com/bookerthegeek/4c281bcfc0f7f7f5db82bdd84b4755ca). Sadly they do not have a github or I would link it [HERE](https://minecraft.curseforge.com/projects/advanced-solar-panels?comment=94) but here is my post to them.

### Versions ### 
- Advanced Solar Panels-4.2.0
- jei_1.12.2-4.14.3.238

**Comment by mezz** [comment]
Thanks for the report!
@chocohead can you open an issue tracker somewhere for Advanced Solar Panels?

**Comment by bookerthegeek** [comment]
Still an issue.

**Comment by mezz** [comment]
Try posting in the forum thread:
https://forum.industrial-craft.net/thread/13494-ic2-exp-1-10-x-advanced-solar-panels-v4-0-4-hey-i-remember-that/

**Comment by bookerthegeek** [comment]
Gotcha.
