### ISSUE TITLE
Bookmarks Arrows Showing when not needed.

### ISSUE THREAD

**Issue by drunkripper** [mezz/JustEnoughItems#1436]
(Not a crash or error)
Forge Version: 14.23.5.2768
JEI Version: 4.14.3.237
MC version: 1.12.2

Issue: The arrows will show up even if no recipes are book marked, but will disappear if you book mark a recipe and then remove it. Maybe have it so the arrows don't show up on start unless there is items bookmarked?

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, it was never meant to show when there are no bookmarks.
