### ISSUE TITLE
crash when looking for recipe  for seeds

### ISSUE THREAD

**Issue by jotac0** [mezz/JustEnoughItems#144]
when i look for the usage for seeds, with JustEnoughtItems installed, and go to the other tab it crashes, i think it is JustEnoughtItems, because when i remove it, there is no tab, and no crash.

How to reproduce: start the game, look for usages for seeds, see all tabs, one should crash.

crash with little mods:
http://pastebin.com/M3JBbecT

crash with many mods:
http://pastebin.com/4aqr8mTf

i have no idea if you need more information, just ask if needed.

**Comment by way2muchnoise** [comment]
This is a JER issue you should post it [over there](https://github.com/way2muchnoise/JustEnoughResources/issues)

**Comment by jotac0** [comment]
i am sorry, i thought i checked 3 times i was on the correct repo ....
