### ISSUE TITLE
Loading times incredibly slow on high resolution

### ISSUE THREAD

**Issue by ArcanoxDragon** [mezz/JustEnoughItems#1442]
I've been having issues on my laptop with JEI taking excessively high amounts of time to load (particularly the "Indexing Ingredients" stage, which has taken over 20 minutes before). My laptop has 16GB of RAM and a 7th gen i7 processor, so it's not starved of power in any sense. My desktop with the same specs but a faster i7 loads much faster.

I decided to randomly try dragging the window down to a small size and loading MC again, instead of letting MultiMC maximize it, and the "indexing ingredients" phase completed in a matter of seconds.

My laptop has a 4K screen, so the maximized resolution is pretty large. My somewhat-educated guess is that each call from JEI to update the loading screen (it seems every item is logged on the progress bar) is blocked while the screen updates. The root cause of this might be in FML, but it could probably be rectified by JEI as well by logging progress at a more coarse level (by mod, perhaps).

**Comment by doritobob269** [comment]
#1446 Ah didn't realize this was basically the same issue I just posted about

**Comment by mezz** [comment]
Thanks for the report!

For some reason, the Enigmatica 2 packs have disabled the memory bar on the loading screen by default.
Please try enabling it in `config/spash.properties` by setting `showMemory=true`.

There is a chance that the pack has too little memory allocated and drawing the strings at loading time is causing garbage collection or something to happen. Having the memory bar there will show clearly if that is the issue since it'll be red and unhappy looking.

**Comment by mezz** [comment]
In the meantime I will work on making `indexing ingredients` show mod names instead of every item name, it's pretty excessive.

**Comment by doritobob269** [comment]
I was using version 1.17 of Enigmatica. I should've specified. This is JEI version jei_1.12.2-4.13.1.225
When I turned memory bar on (Copied an FTB splash.properties) I never ran out of memory.

**Comment by mezz** [comment]
I pushed changes that might help this. 
Please try with `jei_1.12.2-4.14.3.244` and let me know if it improves things for you.

**Comment by doritobob269** [comment]
Ran Once, Crashed, here's the report. I'll run it again to see if anything changes. Here's the file:
[crash-2019-01-01_17.13.11-client.txt](https://github.com/mezz/JustEnoughItems/files/2719678/crash-2019-01-01_17.13.11-client.txt)

**Comment by mezz** [comment]
It looks like foamfix is involved in that crash, try updating it or removing it.

**Comment by doritobob269** [comment]
In the process of loading with the same settings as the crash above. I'll disable foamfix after, but it seems to still be loading just as slowly

**Comment by ArcanoxDragon** [comment]
It's definitely not memory-related for me; I'm hitting this issue on the DW20 pack which shows the memory bar. I have 10 GB allocated to Java and it never goes above 4 during the loading process.

**Comment by mezz** [comment]
Ok, good to rule that out.
Can you try with the latest JEI version, 4.14.3.244?

**Comment by Akai1** [comment]
Problem still exists in 4.14.3.245 for me.

**Comment by mezz** [comment]
Can someone with the issue create a short video clip to show what's happening visually?
Unfortunately I don't have a 4k monitor to test on, so any extra clues for me to work from would be helpful.

**Comment by ArcanoxDragon** [comment]
I can try and record one when I get a chance in the next few days

**Comment by Akai1** [comment]
Here is a short [video](https://www.dropbox.com/s/bkdm1nh4escnjls/2019-01-06%2020-39-08.mkv?dl=0) of the problem. Even after loading I get big lag spikes.

**Comment by mezz** [comment]
@akai1 thanks for the video. 
In your case, the slowdown and lag spikes you are seeing are definitely caused by lack of memory allocated to java. The loading screen memory bar gets red and things really slow down.

**Comment by Akai1** [comment]
Thanks for your quick reply! I allocated 8GB instead of 6GB to Minecraft and now it takes "only" 5 minutes instead of 8 to start and the lag spikes are gone.

**Comment by ArcanoxDragon** [comment]
That's a different issue, yeah. Your "indexing ingredients" step was actually moving pretty fast aside from freezing every few seconds. On my 4K laptop, you can almost count each ingredient as it gets indexed because it's going so slow. I'll get a video soon.

**Comment by mezz** [comment]
Any update on this @briman0094 ?

**Comment by ArcanoxDragon** [comment]
I'll try and record/upload a video now, but I may have to wait until this evening (central time) to actually upload it.

**Comment by ArcanoxDragon** [comment]
Here's the video: https://www.youtube.com/watch?v=ZhGb6Mutfw0

At around 4:35 is when JEI starts loading and I maximize the window. At around 6:15 is when the Indexing Ingredients stage begins. Observe how remarkably slow it progresses through this step, and how often the title bar indicates "(Not Responding)". The couple times that I manage to un-maximize the window is when you can see how drastically the process speeds up with the smaller window size. It also doesn't encounter the "(Not Responding)" situation when it is at a smaller window size.

I'm not sure if this is a JEI problem or a Forge ModLoader issue, but it's documented now

**Comment by mezz** [comment]
@briman0094 it looks like you are not using the latest version of JEI that has the fix. 
Please try with JEI version `4.14.4.257`.

**Comment by ArcanoxDragon** [comment]
I can try that tomorrow; I think I may also relay this video to Forge or FML because this behavior can also be noticed on other steps (such as model baking and texture stitching) but I will see if the new JEI version has made it bearable in the meantime

**Comment by mezz** [comment]
It is probably an FML issue, but there’s also no real benefit to creating progress bars with 1 million steps so I feel ok about the workaround.

**Comment by mezz** [comment]
Any update on this issue @briman0094?

**Comment by ArcanoxDragon** [comment]
It is marginally faster with 4.14.4.257, but it is still **much** slower (to the point where it seems frozen) in 4K resolution than a small window. I think this is definitely something to do with FML's rendering of the loading screen...I have a feeling it's consuming a lot of CPU cycles it doesn't need to be (even when not actually updating anything) and leaving less for other mods to use during initialization.
