### ISSUE TITLE
JEI taking nearly half an hour to load Enigmatica 2 Expert Skyblock. Stuck on Building Ingredient Filter

### ISSUE THREAD

**Issue by doritobob269** [mezz/JustEnoughItems#1446]
I'm having an issue with Enigmatica 2 Expert Skyblock where it takes me nearly half an hour to load the pack and I've traced the issue down to JEI taking nearly 29 minutes to load. I've attached my log file for reference. The line to look at is line 7168. I have 10,240 MB dedicated to minecraft of my 16, so it shouldn't be an issue with low ram. (I realize it is well more than needed, but may as well use what I have). Thanks so much for everything you do Mezz. The pack does have a lot of blocks, but indexing seems to go so slowly that I am able to see the ones place of the splash screen counter changing individually. Not the usual 1000 change per second or so I've gotten with other packs with jei. Thanks again, here is my log file.
[doritobob269's Latest Log File](https://github.com/mezz/JustEnoughItems/files/2719181/doritobob269.s.Latest.Log.File.log)

**Comment by doritobob269** [comment]
#1442 Is basically the same issue. My laptop is also 4k

**Comment by doritobob269** [comment]
Setting screen resolution to a small number allows it to load drastically faster, but there still seems to be an issue on my 4k resolution.

**Comment by mezz** [comment]
Thanks for the report!
That sounds terrible, I'll take a look.

**Comment by doritobob269** [comment]
Thanks @mezz !
