### ISSUE TITLE
JEI stuck building recipe registry

### ISSUE THREAD

**Issue by Gijs-Hooghiemstra** [mezz/JustEnoughItems#1448]
I've built a custom modpack with JEI. The modpack loads quick until JEI is building the recipe registry. It will load after about two hours. I gave the minecraft instance over 8gb of RAM. The version of JEI used is 
jei_1.12.2-4.14.3.245. I don't have Optifine installed. A full console log can be found here: [latest.txt](https://gist.github.com/OfficialGHepic/a4e891931260cd3e2d7488149700d415#file-latest-txt). I've marked the places in the log where the loading starts taking ages.

Since I am no expert at modding I don't know if it's a mistake made by me or a bug in the mod.

**Comment by Ommina** [comment]
Feels a bit like https://github.com/Buuz135/Thaumic-JEI/issues/38

Which is a JEI plugin, not JEI itself.  Nonetheless, it may be worth removing Thaumic-JEI (or setting the option mentioned in that thread to disable the startup check) and see if that resolves your slight delay in startup.

**Comment by Gijs-Hooghiemstra** [comment]
I've tried launching the game without Thaumic JEI. Sadly it doesn't solve the problem. I've ran VisualVM while launching the game. It looks like there is a problem with JEI and Embers?
![jei recipe registry 1](https://user-images.githubusercontent.com/23342585/50631412-73698a00-0f44-11e9-9db3-ead88a1d4dcc.PNG)
![jei recipe registry 2](https://user-images.githubusercontent.com/23342585/50631423-7ebcb580-0f44-11e9-87b5-db5be88c7183.PNG)

I don't know if those images show the right problem.

**Comment by mezz** [comment]
Thanks for the report!

Based on the images, this does appear to be an issue with Embers.
First make sure you are not running out of memory though, if the memory bar on the loading screen is getting red then things will slow down no matter what. If the memory bar is disabled in your pack, you can re-enabled it in the `config/splash.properties` file.

If memory is not the issue, please report this to Embers here: https://github.com/EpicSquid/Embers/issues

**Comment by Gijs-Hooghiemstra** [comment]
Sorry for the late reaction.

I updated all my mods. Yet still the problem occurs. The client seems to never run out of memory according to the memory bar in the splash screen. I found the same issue reported to the embers github page [here](https://github.com/DaedalusGame/EmbersRekindled/issues/31) and [here](https://github.com/DaedalusGame/EmbersRekindled/issues/52). 

I don't know if the embers team is working on the issue.

**Comment by mezz** [comment]
Ok thanks for the update. 
This isn't really a JEI bug so I will close this issue and I will subscribe to the ember's issue here instead: https://github.com/DaedalusGame/EmbersRekindled/issues/52

**Comment by GordonHollow** [comment]
Submit this bug.
JEI stacks on loading mezz.jeiplugins,vanillaplugins when i have installed JustEnoughResourses and JustEnoughHarvestCraft. And i have no Embers in my modpack.

**Comment by GordonHollow** [comment]
https://pp.userapi.com/c846220/v846220723/17b4b6/F-aRdXl1YwU.jpg
This stack also when i extend up memory limit to 20gb

**Comment by GordonHollow** [comment]
Without JER and JEHC - all works fine

**Comment by mezz** [comment]
@GordonHollow please do not comment on old issues.
Also, it is not related. 
Please open a new issue instead.
