### ISSUE TITLE
JEI Letting TC Aspects Peek Through

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#145]
[Proof](http://puu.sh/mM9fZ/d9a79a7560.jpg)

Just a shot in the dark - is it because you don't close the player's inventory when you display the recipe GUI?

All I know is that if I have the JEI recipe window open and I hold Shift, the Thaumcraft Aspects show up over the hovered area if the original hovered area (before opening the JEI Recipe window) had an item.

Purely cosmetic ;D

**Comment by mezz** [comment]
Thanks for the report!
JEI draws its recipe gui on top of the existing one. That is not the best strategy, I should change it to open a new gui and go back to the old one when it's closed.
