### ISSUE TITLE
Request - GameStages Compatibility for hideCategory

### ISSUE THREAD

**Issue by NielsPilgaard** [mezz/JustEnoughItems#1450]
Hello!

I'd like to request GameStages compatibility for the CraftTweaker function `mods.jei.JEI.hideCategory(string category)`, in order to hide tabs that the player doesn't have access to, until the appropriate GameStage.
I imagine it would work like `hideCategory`, but with an addition string like so:

`mods.jei.JEI.hideCategory(string stage, string category);`

This feature would  most likely reduce player confusion in the early game for my upcoming pack, aswell as reduce the time players need to spend in JEI.

**Comment by mezz** [comment]
Thanks for the request!
CraftTweaker is calling a regular JEI API method in order to hide categories.
There isn't any special handling for these mods in JEI, please make this request to CraftTweaker or GameStages.

**Comment by NielsPilgaard** [comment]
Alright, thanks :)
