### ISSUE TITLE
JEI allows anyone to enable cheat mode without being OP

### ISSUE THREAD

**Issue by ovingiv** [mezz/JustEnoughItems#1451]
Using 4.14.3.246 JEI for MC 1.12.2 server, anyone is able to enable cheat mode and get items without being OP.

Is there away to either turn this off for non OP players?

**Comment by TehNut** [comment]
JEI only allows users to spawn items [if they have permission](https://github.com/mezz/JustEnoughItems/blob/65bd9a8ba53b69c0f9cfe0ee9ffb86d026ef2cc7/src/main/java/mezz/jei/util/CommandUtilServer.java#L70-L91) for the `/give` command. You should make sure none of your mods are breaking that permission check

**Comment by ovingiv** [comment]
I just deop my self and I still was able to give myself items.
And I'm pretty sure none of the other mods play with that command.

**Comment by ovingiv** [comment]
Here's my mod list https://paste.ee/p/QAJLx

**Comment by TehNut** [comment]
>forgeessentials-1.12.2-12.3.27-server.jar

It could very well be this

**Comment by ovingiv** [comment]
Well after doing some more searching and looking through the NEI config 
inventory.lockmode was set to -1. I set it to 1 and I'm about to see if that worked.
inventory.cheatmode was also set to 2 and I switched that to zero as well.
Edit: It did not work.

**Comment by ovingiv** [comment]
Within Forge Essentials I specifically denyed myself the give command and I still was able to take items.

**Comment by KnightMiner** [comment]
Does it happen if you remove Forge Essentials?

**Comment by ovingiv** [comment]
I will try that now.

**Comment by ovingiv** [comment]
Yes I can still take items without forge Essentials on the server and client.
I'm also in Recipe mode to clarify that.

**Comment by ovingiv** [comment]
I'm looking around and seeing that some people have a NEIServer config. I don't have that file. I just made one and restarting the server now.

**Comment by ovingiv** [comment]
ok That locked it down and set's it in Recipe mode.

However all someone needs to do is enable JEI and CTRL+click on the wrench and they can give themselves anything.

**Comment by mezz** [comment]
Please try removing forge essentials and NEI completely, then see if there is still an issue.

**Comment by ovingiv** [comment]
Doing that did not change anything. I even reset the config files and that didn't do anything either.
Edit: I was still oped for whatever reason. Removing both NEI and Forge fixed that issue. I'll create an issue saying that Forge Essentials breaks the permissions.

**Comment by ovingiv** [comment]
https://github.com/ForgeEssentials/ForgeEssentials/issues/2360
