### ISSUE TITLE
Shutting down internal servers when loading up my world

### ISSUE THREAD

**Issue by Nekogamer90** [mezz/JustEnoughItems#1453]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.
Hi, when ever I try to load a world, it will always say "Shutting down internal servers" after loading the world. I tried removing mods but it always came to the same conclusion with the mods. Please help me with this

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
