### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RadekWladcaPogody** [mezz/JustEnoughItems#1454]
Please add this. Is from mod toomanyitems. TooManyItems mod is not on version 1.12.2
[
![obraz](https://user-images.githubusercontent.com/45951536/50777092-e81d2b00-129a-11e9-8bf6-a3a9b9fb41ac.png)
](url)

**Comment by mezz** [comment]
What is it?

**Comment by RadekWladcaPogody** [comment]
Something like this. Screenshots.

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49639310_767014346990086_7149446803379716096_o.jpg?_nc_cat=111&_nc_ht=scontent.fpoz1-1.fna&oh=3e613b71d7e2554c703fd0b2c8efa329&oe=5CD3A632

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/50012339_767014363656751_8032464948128907264_o.jpg?_nc_cat=109&_nc_ht=scontent.fpoz1-1.fna&oh=414fdf14550b8ba69eae464192001126&oe=5CBB9B31

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49729326_767014383656749_946892490353410048_o.jpg?_nc_cat=105&_nc_ht=scontent.fpoz1-1.fna&oh=fbe247c1385192eab0ef9d8f23a58620&oe=5CB8641F

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49938397_767014396990081_8069639036832055296_o.jpg?_nc_cat=111&_nc_ht=scontent.fpoz1-1.fna&oh=3a7dc75cbf30ce850b5458a7d4d77f6e&oe=5C8D61DD

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49948275_767014430323411_7513807742595760128_o.jpg?_nc_cat=110&_nc_ht=scontent.fpoz1-1.fna&oh=17e043119d6f3e633f2a1a79a37e6b39&oe=5C8E484C

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49680377_767014456990075_182094634686611456_o.jpg?_nc_cat=108&_nc_ht=scontent.fpoz1-1.fna&oh=8c59d2a3b441fa8665a4060e8a1206c0&oe=5CC1109A

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49550356_767014500323404_6650841696344997888_o.jpg?_nc_cat=101&_nc_ht=scontent.fpoz1-1.fna&oh=ed142b0bc35d732f40112ae1eaa7e7bf&oe=5CC9D239

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49710277_767014526990068_1383128959943704576_o.jpg?_nc_cat=102&_nc_ht=scontent.fpoz1-1.fna&oh=745bc6ead6a019141aeca74b18969bd0&oe=5CC0CFF1

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49682671_767014553656732_3764553253149212672_o.jpg?_nc_cat=106&_nc_ht=scontent.fpoz1-1.fna&oh=16ad086141137bf3f21a58966b763915&oe=5CBAB388

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49656271_767014576990063_5317179743060099072_o.jpg?_nc_cat=110&_nc_ht=scontent.fpoz1-1.fna&oh=f1d0df9724d45adfa5c364430cec11d1&oe=5CCDA26D

https://scontent.fpoz1-1.fna.fbcdn.net/v/t1.0-9/49897000_767014606990060_3500539182512603136_o.jpg?_nc_cat=101&_nc_ht=scontent.fpoz1-1.fna&oh=f61127ace7f1b94b42ca0c8405631252&oe=5CC57B7F

Description TooManyItems mod https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272385-toomanyitems-the-inventory-editor-and-more-1-8

**Comment by mezz** [comment]
Ah ok, thanks. 

For "My items", JEI recently got a "Bookmarks" feature that lets you save items to a list on the left side.
For "Custom" and "Controls", I think those things could be done by a separate mod and do not belong in JEI directly.
Those features look pretty nice for creative players, but JEI tries to stay small so I do not want to add them directly to the mod. A very simple new mod could implement all of those features separately without depending on JEI or anything else.

**Comment by RadekWladcaPogody** [comment]
OK. Thank you for your response.

**Comment by Inve1951** [comment]
A bookmarks/todo list of items/recipes woul actually be pretty nice to have. I find myself searching for the same stuff over and over.
