### ISSUE TITLE
Crash when searching for smeltry

### ISSUE THREAD

**Issue by john01dav** [mezz/JustEnoughItems#1455]
Whenever I search for anything containing "smeltry" in JEI's search box my client crashes. I am doing this in a multiplayer server in FTB Revelations 2.6.0, with all default mod versions. I added Optifine. Each attached crash report is from a different instance of the crash.

[crash-2019-01-08_13.41.16-client.txt](https://github.com/mezz/JustEnoughItems/files/2738636/crash-2019-01-08_13.41.16-client.txt)
[crash-2019-01-08_14.24.16-client.txt](https://github.com/mezz/JustEnoughItems/files/2738637/crash-2019-01-08_14.24.16-client.txt)

**Comment by john01dav** [comment]
Here is a full log: https://gist.github.com/john01dav/5c5062f75b1272343b968872f584223a

**Comment by john01dav** [comment]
Removing Optifine fixes the issue. As such, there is a bug in either Optifine or JEI. I am leaving this report here in case it is the latter.

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue between OpenBlocks and Optifine. You can read more here:
https://github.com/OpenMods/OpenBlocks/issues/948
I'm not sure if it's fixed already, try updating OpenBlocks and ask them in the issue if you still have problems.
