### ISSUE TITLE
Cant Close the Search Menu

### ISSUE THREAD

**Issue by zarzwour** [mezz/JustEnoughItems#1459]
When i press CTRL+O it will only close the left side of the menu and not the right side (Search area)

**Comment by mezz** [comment]
Thanks for the report!
I have tried on the latest version, but it is working correctly.
Can you try on JEI version `4.14.4.251` and show a screenshot of the search menu?

**Comment by zarzwour** [comment]
I crash when i hit singelpayer with .251 i have forge forge-1.12.2-14.23.4.2705

Crash Log https://pastebin.com/4fsJ8GzS

**Comment by mezz** [comment]
Please remove NEI and try again.

**Comment by zarzwour** [comment]
latest works now without NEI, HWYLA, and WAWLA. But item IDS still wont show when i enable it. What NEI version should i use with this?

**Comment by mezz** [comment]
If it's an NEI bug you can report it here: https://github.com/TheCBProject/NotEnoughItems/issues

**Comment by zarzwour** [comment]
i updated everything and ti works thank you! but when i select show item ID in the search settings in JEI no IDS show

**Comment by mezz** [comment]
I'm not sure what you mean, JEI does not have settings to show item IDs.
