### ISSUE TITLE
[Crash] Client crash while looking at seed recipe

### ISSUE THREAD

**Issue by tjsd** [mezz/JustEnoughItems#146]
Crash Log:
http://pastebin.ubuntu.com/14688537/

Pack:
FTB Unstable v3.0.16

JEI Version:
jei_1.8.9-2.22.4.106

**Comment by mezz** [comment]
Thanks for the report!
This is a JustEnoughResources issue and has been fixed for the next version: https://github.com/way2muchnoise/JustEnoughResources/issues/30
