### ISSUE TITLE
While trying to get Recipie for item, game crashes [1.12.2]

### ISSUE THREAD

**Issue by ConnorTron110** [mezz/JustEnoughItems#1460]
dunno whats going on plz help
[crash-2019-01-12_17.15.57-client.txt](https://github.com/mezz/JustEnoughItems/files/2752326/crash-2019-01-12_17.15.57-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1189
