### ISSUE TITLE
New GUI Textures dont scale

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1463]
I use Faithful32 resource pack. JEI used to scale the Recipe_Background2 texture and all looked great

Now you have cut the Recipe_Background2 texture into individual files. I cut the Faithful32 into the relevant single files. The width and height of the textures are twice as big.

When bringing up JEI recipes the GUI is massively out of proportion. 

good JEI 247
![good](https://user-images.githubusercontent.com/10263667/51146907-2e046100-1850-11e9-92b2-094c939e1d82.jpg)

bad, JEI 248+ (the arrows I havnt yet cut, but I did the wrench, tabs, button/select/highlight)
![bad](https://user-images.githubusercontent.com/10263667/51146908-2e046100-1850-11e9-93d7-78205b83f975.jpg)

**Comment by mezz** [comment]
Thanks for the report!
Could you give me a .zip file with the 2x textures so I can test it properly?

**Comment by ghost** [comment]
Ive included the faithful32 recipe_background_2.png in the textures folder too

https://1drv.ms/u/s!ArSGAcC04KWskBPoytwz1F5HsqDx

**Comment by mezz** [comment]
Thanks, I pushed a fix for this.
To better support the large rounded corners you have, I had to change the texture sizes for `recipe_background` and `gui_background`, and I changed the texture for `catalyst_tab`.
Make sure to update those or it will look like things are still broken :)

**Comment by ghost** [comment]
sweet look forward to it. thank you

JEI is such a necessary mod and Faithful just makes things pretty, lol

**Comment by zISKo666** [comment]
Thank you for the fix.

Working for me @ 64²px texture.

zISKo

**Comment by ghost** [comment]
thankyou, the fix works perfect after I modified the file dimensions like you suggested
But I also tried the gui_background without changing its size (@ 64px) and got a division by zero error, dont know if this is important for future resource packs, just thought I would let you know

Crash log ->  https://pastebin.com/vcFXAZWG
