### ISSUE TITLE
Game crashes in startup using Java 6

### ISSUE THREAD

**Issue by DolphyBlueDrake** [mezz/JustEnoughItems#147]
While attempting to load JEI with the latest recommended Forge (11.15.1.1722), Minecraft crashes in the middle of startup and provides the following crash report:
[crash-2016-01-30_13.20.21-client.txt](https://github.com/mezz/JustEnoughItems/files/110983/crash-2016-01-30_13.20.21-client.txt)

NOTE:  Attempts have been made to start up Minecraft with JEI as the only mod, and the crash still results.  The crash doesn't result with versions earlier than 11.15.1.1700, but many mods are switching to the latest version of Forge, leaving JEI outdated and unusable.  

Please consider updating the mod to the latest version of forge for the best level of compatibility.

**Comment by TehNut** [comment]
Update to at least Java 7. You are using Java 6.

**Comment by Prospector** [comment]
Why 7? It's been unsupported for nearly a year.

**Comment by TehNut** [comment]
Because [JEI is compiled for 7](https://github.com/mezz/JustEnoughItems/blob/1.8.9/build.gradle#L29-L30). I meant it as a minimum, not a requirement.

**Comment by Prospector** [comment]
I don't think you should ever tell someone to update to a version with security risks.

**Comment by DolphyBlueDrake** [comment]
Updating to 7 is impossible for me.  I'm broke, and my computer can't support 7 or above.  I'd need a more powerful OS, and I can't afford a computer that would have enough RAM for an OS that comes with 7.  Mac computers use Mac java, which can only be updated by changing the OS.  This discrimination is at the very least rude in my opinion.

**Comment by wlhlm** [comment]
@DolphyBlueDrake Which version of the OS are you running? Apple have stopped supporting Java themselves some time ago. New Java versions are provided directly by Oracle.

You can get Java 8 for Mac OS X version 10.7 (Lion) and up.
https://www.java.com/en/download/manual.jsp#mac

**Comment by DolphyBlueDrake** [comment]
My computer can't run Lion.  Well, not without becoming slow as molasses, anyway.  It's far too old to run anything above Lion, but Lion requires 2 GB of RAM, and the max my computer can have is 3, which it has.  I simply can't upgrade.  It's out of the question.

**Comment by mezz** [comment]
What OS version do you have? Even Snow Leopard can run Java 7, it just takes a few steps to do it.

**Comment by DolphyBlueDrake** [comment]
Mac OS X Version 10.6.8.  the final version of Snow Leopard.  I don't know how to get Java 7.  I tried looking for a way, but I can't find one.  What are these steps?  And how can I install it and get it to run?  I found a few methods, but they didn't work, and I'm still stuck.

**Comment by mezz** [comment]
There are many results from a google search, but [this one seems to show every step exactly](https://www.youtube.com/watch?v=eFi-H-7-PD4), although it's not in English.

**Comment by DolphyBlueDrake** [comment]
I tried that one already.  It didn't work at all.  My Mac still defaulted to java 6, and if I turned off java 6 to force it to use 7, it wouldn't run Minecraft at all.

**Comment by shadowfacts** [comment]
You may have to manually change which version of Java is being used by the launcher.

**Comment by DolphyBlueDrake** [comment]
And how do I do that?  My computer doesn't even seem to recognize 7 at all.  It'll allow me to access it in the java preferences, but when I try to open Minecraft with 6 turned off, It claims that it can't find any version of Java 1.6+

EDIT:  I just tried altering the file inside Minecraft that checks what version of Java I'm using and changed it from 1.6 to 1.7, and it still didn't work.

**Comment by shadowfacts** [comment]
In the settings of whatever launcher you're using, there should be an option to change the java path.

**Comment by DolphyBlueDrake** [comment]
Okay.  I'll try that.

**Comment by DolphyBlueDrake** [comment]
IT WORKED!  Thanks so much, shadowfacts!  Unfortunately, I have another mod that's not working, but I can live without that one for now.  I'll send its author an error report when I feel like it.  But Mezz, PLEASE don't make it require a java later than 7.0_25 for as long as you can hold off from needing one later than it.  Minecraft wouldn't load the game with the final one (80), and 25 is the latest one that I can get it to work with.

**Comment by mezz** [comment]
Glad it's working for you Dolphy. Sorry but many mods are moving to Java 8, even the latest vanilla Minecraft is planning to move at some point as well. 

Java 6 users are a very tiny minority, the latest estimates put Java 6 usage at 0.03%, and I assume many of those are people who simply haven't updated. https://imgur.com/a/EWt6X

You shouldn't have to worry about specific Java 7 versions. Even if someone uses a later Java 7, yours will be compatible.
