### ISSUE TITLE
Clientside Pixelmon and JEI crash 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#1470]
https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/issues/5

**Comment by mezz** [comment]
Thanks for the report!
This doesn't seem to be related to JEI, it's not in the stack trace of the crash at all.

**Comment by P3rf3ctXZer0** [comment]
Any way I can help?

**Comment by mezz** [comment]
It seems like an issue with just Pixelmon. 
Most likely the item that you are cheating in from JEI is broken in some way and crashes.
Pixelmon is kind of off in its own corner of the modded universe so I do not think they normally test their mod against JEI.

**Comment by P3rf3ctXZer0** [comment]
Yeah they suggested - just downgrade forge - I explained Chisel and Silent Gems are benefiting greatly from the 805+ texture fixes by tterrag1098

**Comment by P3rf3ctXZer0** [comment]
How do I disable specific items in JEI?

**Comment by mezz** [comment]
You can hide items in JEI using the in-game ingredient hiding mode, or by using crafttweaker.

**Comment by P3rf3ctXZer0** [comment]
No I mean how XD Like a guide commands - I have never done it before

**Comment by mezz** [comment]
1. Click on the wrench on the bottom right of JEI's ingredient list to open the config menu.
2. Enable the "Hide Ingredients Mode" and exit the config menu.
4. Hover over an ingredient you want to hide.
4. Follow the instructions on the tooltip for how to hide the ingredient.
5. Click on the wrench again and disable "Hide Ingredients Mode".

**Comment by P3rf3ctXZer0** [comment]
Thank you :D

**Comment by P3rf3ctXZer0** [comment]
Okay doing that ingame still crashes - how can I do it out of game like JSON? @mezz

**Comment by mezz** [comment]
See the `config/jei/itemBlacklist.cfg` file to manually hide items.

**Comment by mezz** [comment]
If you hide some items in-game it will add them to that file too, so do that and it can serve as an example of what the entries should look like.

**Comment by P3rf3ctXZer0** [comment]
Thanks this time I will leave the issue open until I know it is a success :D
