### ISSUE TITLE
Some new GUI elements still scale incorrectly in packs

### ISSUE THREAD

**Issue by HanPrower** [mezz/JustEnoughItems#1471]
Using jei_1.12.2-4.14.4.260.jar

Related to https://github.com/mezz/JustEnoughItems/issues/1463 some elements still seem to scale badly.

The `gui_background.png`, `tab_selected.png`, `tab_unselected.png`, `icons/flame.png` still seem to scale oddly.

I think `icons/arrow_next.png`, `icons/arrow_previous.png` are also affected, but I haven't got custom textures in the following screenshot. Not sure about other elements.

![2019-01-20_10 41 37](https://user-images.githubusercontent.com/1781312/51438149-08d48000-1ca0-11e9-8db7-52fdc3829d92.png)

**Comment by Peppe-KSP** [comment]
Similar issues for https://minecraft.curseforge.com/projects/soartex-fanver-modded.

Are the JEI changes expected to require new resource packs?

**Comment by mezz** [comment]
Thanks for the report!
I think this is an issue where the textures are not a multiple size of the original texture (they need to be something like 2x or 4x, not 2.5x).
You should see an error in the log `Texture has the wrong dimensions. Expected a multiple of:`
I will look into removing that restriction.

@Peppe-KSP the changes require new assets (they are split into new files). JEI will just use the regular vanilla textures until the texture pack updates.

**Comment by mezz** [comment]
This should be fixed in version 4.14.4.262, please let me know if you see any issues.
