### ISSUE TITLE
Animalbikes and nbt data in recipes

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1474]
It seems that jei is having trouble registering fireworks and potions within recipes. Fireworks just don't show up at all and potions will show up as "Uncraftable Potion" and have the broken texture icon.

jei: 4.13.1.225
animal bikes: 1.11.2
minecraft: 1.12.2
forge: 2800

The problem occurs with the chinese dragon bike (uses fireworks around the outside) and the bat bike (uses night vision potions). I was directed to report to you by the mod dev.

**Comment by mezz** [comment]
Thanks for the report!
Can you link me back to the original issue?

**Comment by ghost** [comment]
Noppes doesn't have a formal bug tracker, everything goes through his discord group. This report is about as close to the original issue report as I can go.

**Comment by mezz** [comment]
I took a look and here's what I found so far:

The potion in Bat Bike recipe is using a potion items with meta value 8230, which is the way potions worked in 1.7.10. 
For 1.12.2 potions use NBT and have meta value 0, so I think the recipe just needs to be updated to show correctly.
As a result of that issue, the recipe itself seems to actually be broken:
![2019-01-26_19 26 36](https://user-images.githubusercontent.com/916092/51795969-540af900-21a0-11e9-98fd-a7486f9e74ce.png)

I'm not sure what's wrong with the chinese dragon bike recipe, it looks pretty normal to me, but the vanilla recipe book seems to have the same issue with it so I am not sure it is a JEI issue either:
![2019-01-26_19 22 26](https://user-images.githubusercontent.com/916092/51795943-d34bfd00-219f-11e9-986a-9e61f7bdde59.png)

**Comment by ghost** [comment]
The bat one you have to brew them, creative'd in ones don't work (his words, not mine). As for the Chinese one, I'm not sure what to say there, the default firework worked for me, the book may have another issue with them.

**Comment by mezz** [comment]
Crafted normally using a brewing stand:
![2019-01-26_19 54 15](https://user-images.githubusercontent.com/916092/51796264-32ac0c00-21a4-11e9-9ae1-85c6af3f9418.png)

Please test this out for yourself too.
I do not want to chase these bugs any further myself unless it really looks like a JEI issue.

**Comment by ghost** [comment]
My apologies, I automatically assumed you weren't aware of that quirk as I didn't mention it at the beginning. I have linked this report to Noppes for analysis. I'll close this for now.
