### ISSUE TITLE
Making custom mod pack and crashing trying to construct JEI

### ISSUE THREAD

**Issue by Arcanien** [mezz/JustEnoughItems#1475]
[https://gist.github.com/Arcanien/c903d87255b71a0ed138bddbcb1b212e](url)

I've tried rolling back forge a little and moving it to latest. I also updated my java and still getting this. I really tried seeing if I could figure it out. I know a bit about computers, but not a lot into programming to figure out exactly whats going on.

**Comment by bs2609** [comment]
This is an old Java issue actually: https://bugs.openjdk.java.net/browse/JDK-4523159

You need to use an instance name that doesn't end in the '!' character.

**Comment by mezz** [comment]
How strange. Thanks for identifying the solution bs2609!
