### ISSUE TITLE
Crash when opening any inventory after world load

### ISSUE THREAD

**Issue by Inve1951** [mezz/JustEnoughItems#1478]
[\<log file\>](https://gist.githubusercontent.com/Inve1951/63b0de32793e1c9dae9e66036b719997/raw/5707b05c0d5a950ca542b1f5b3d0b33c82834266/mc-jei-crash.log) `[02:17:24]` is when I right-clicked a double chest and the game froze/crashed.

I also reproduced this with an IC2 iron furnace and just the player inventory.

Edit:
This is v4.14.4.263, but I also had it happen on v4.13.1.225.

Edit2:
Was able to narrow it down a bit. Seems to happen only when a certain item is being rendered.
After clearing JEI's world cfg the crash stopped, but as soon as I typed `api` (apiary) into the search field it crashed again (this caused it the first time too).

Possible duplicate: #1453

**Comment by Inve1951** [comment]
I suspect that this is a side effect of removing mods from a modpack. However I have no idea as to how to debug/fix this.

**Comment by mezz** [comment]
Thanks for the report!
From the log:
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: OpenBlocks
	Ingredient Info: 1xitem.openblocks.glyph@65 openblocks:glyph
```
This seems to be an issue with OpenBlocks, please report it to them here: https://github.com/OpenMods/OpenBlocks/issues

**Comment by Inve1951** [comment]
Thanks for taking the time. You are correct.

This is indeed a duplicate of #1455 / https://github.com/OpenMods/OpenBlocks/issues/948 and closely related to #1124.

I tried adding `openblocks:glyph;` to `itemBlacklist.cfg` but the exact same crash still occures. I suspect I did it wrong.

[Here's the file](https://gist.githubusercontent.com/Inve1951/63b0de32793e1c9dae9e66036b719997/raw/3af149036f27af0506f5d6385ee753521631ce59/itemBlacklist.cfg) - It's the first list item.

Maybe you can tell me what the error is or point me in the right direction. I was unable to find documentation on it.

**Comment by mezz** [comment]
Most things in the item blacklist do not end in a semicolon (it is part of some item's unique ids, but it depends on the mod and the item), so I think it should just be `openblocks:glyph` like in the error log message.

**Comment by Inve1951** [comment]
That did the trick.

Wasn't aware of the list being newline separated. I thought the semicolon is a required terminator when there's no curlies after.

Thank you very much. :slightly_smiling_face:
