### ISSUE TITLE
Opening the Inventory will crash the Game

### ISSUE THREAD

**Issue by L1nsus** [mezz/JustEnoughItems#1479]
After opening the inventory the game hangs with the following [`crash report`](https://pastebin.com/raw/38YN67bB)
>**This happened without NEI to*

Thank you in advance

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by L1nsus** [comment]
[`latest.log`](https://pastebin.com/raw/W7nsKLMp)

**Comment by mezz** [comment]
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Dynamic Trees
	Ingredient Info: 1xtile.dynamictrees:oakbranchx@0 dynamictrees:oakbranchx
```
It looks like this may be an issue from Dynamic Trees.
Please try reporting it to them here: https://github.com/ferreusveritas/DynamicTrees/issues
