### ISSUE TITLE
Crashing when opening user interface.

### ISSUE THREAD

**Issue by DeanHippo** [mezz/JustEnoughItems#1480]
Crashing at random when opening user interface, for example opening a chest, the players inventory etc.
Error Log: https://gist.github.com/DeanHippo/ce379e0427e56623469b637405224fed
Thought it was an issue with journeymap as deleting the Journeymap folder fixed the issue for it to return an hour or so later, the' Journeymap guys checked the logs and said its an NEI issue and to contact yourselves.
This is the Project Ozone Lite modpack hosted on Twitch.

**Comment by mezz** [comment]
Thanks for the report!
There are tons of errors in this log, but I do not see the actual crash report.
Can you look in your `crash-reports` folder, paste the crash log to gist, and link it here?

**Comment by DeanHippo** [comment]
Haha yes that log confused me, heres the crash report from the folder
https://gist.github.com/DeanHippo/f412fa2117c52c294dcda05cbf4e7cc4

**Comment by mezz** [comment]
Thanks! Yeah this is definitely an NEI issue, you can report it here: https://github.com/TheCBProject/NotEnoughItems/issues

**Comment by DeanHippo** [comment]
done, thankyou: https://github.com/TheCBProject/NotEnoughItems/issues/203
