### ISSUE TITLE
jei Bookmarks Overlapping AE

### ISSUE THREAD

**Issue by Quest79** [mezz/JustEnoughItems#1484]
version: 4.1.4.1.235

I tried normal, large, auto, 4x, 5x etc, same issue. Seems to just need to take up less of a % of the left aligned portion of the screen? Just needs to back off 1 to 2 items.

This wouldn't be a big issue for me except that the bookmarks are taking priority over the AE buttons that are used far more.

![javaw_b6oqxaqd93](https://user-images.githubusercontent.com/635094/51965932-de14c500-241f-11e9-9cd6-d085d3ef7ef2.png)

**Comment by Quest79** [comment]
Issue present in jei_1.12.2-4.14.4.264.jar

**Comment by mezz** [comment]
Thanks for the report!

This needs to be implemented in AE's JEI plugin. I have created an issue for AE here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3922

If it helps you work around the issue, there is already an in-game config for setting the maximum width of JEI's ingredient lists. The issue you linked is just for setting a minimum width, which is not currently configurable.
