### ISSUE TITLE
[Feature Request] Config option for specifying a min width of the JEI overlays

### ISSUE THREAD

**Issue by Greg-21** [mezz/JustEnoughItems#1485]
As the title says, add an config option for specifying a minimum width of the JEI overlays (bookmarks and especially ingredients list).

Version 4.9.1.180 of JEI introduced a feature that always shows the button with wrench icon to inform user when JEI overlays are hidden, or when there is not enough space to display them. Its side effect is that it's now impossible to use JEI overlays on my PC with 1280×1024 screen (and probably others with "square" proportions) and "Auto" GUI scaling.

That's how it looks like on that 1280×1024 screen:
![ingredient-list-jei](https://user-images.githubusercontent.com/34160838/51994445-0ef10a80-24b1-11e9-99c4-8e7a91a6636f.png)

I know that having 3-column list is not the most convenient thing, but in combination with the search bar it was useful enough.

**Comment by Quest79** [comment]
Allowing width modifications in config would also help with #1484

**Comment by Greg-21** [comment]
Since a fix for this issue is not so important, I'm closing it. One less in the backlog.
