### ISSUE TITLE
Stoneblock 2 crashing when trying to install JEI

### ISSUE THREAD

**Issue by Darkheart747** [mezz/JustEnoughItems#1486]
Stoneblock 2 keeps crashing everytime I try and launch, the error stating JEI is the cause. Pack is unmodified and launching however the Twitch App installed it

https://paste.dimdev.org/irehiqupic.mccrash

That is the link the crash page gave me, don't make any sense to me as I don't understand code and such, can someone assist please.

**Comment by craymull** [comment]
I am having the same problem! I have seen the same crash on several other modpacks through the twitch app. Such as Direwolf20 1.12 pack  and the original Stoneblock.

https://paste.dimdev.org/lanatejoxi.mccrash

**Comment by Ommina** [comment]
In both cases:

Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

Give the pack more memory.  3GB is simply not sufficient for any sizable pack.

JEI is not at fault here.  It's simply taking the blame due to its position of loading last.

**Comment by kradee** [comment]
how can i do this?
EDIT: got it.
removed the -Xmx3072m command and added a -Xmx8G command in the launch options

**Comment by craymull** [comment]
Thank you for responding! I allocated more memory and it now works. I’m new to mods and wasn’t sure how to read the crash log either.
