### ISSUE TITLE
Recipie crash

### ISSUE THREAD

**Issue by logitechQ** [mezz/JustEnoughItems#1488]
I don't understand what's wrong

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.145.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 2/2/19 2:06 PM
Description: 
CCL Has caught an exception whilst rendering an item.
  Item Class:     class cofh.thermaldynamics.item.ItemCover
  Registry Name:  thermaldynamics:cover
  Metadata:       0
  NBT:            {Meta:0b,Block:"extrautils2:decorativesolidwood"}
  Model Class:    class net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1
  Model Location: thermaldynamics:cover#inventory
You can turn off player messages in the CCL config file.
If you want CCL to attempt to recover the game next time, enable it in the CCL config.

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at com.rwtema.extrautils2.backend.model.Textures.getModelResourceLocation(Textures.java:62)
	at com.rwtema.extrautils2.backend.model.Textures$ItemMesher.func_178113_a(Textures.java:375)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:242)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:393)
	at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderItemCover(CoverRenderer.java:168)
	at cofh.thermaldynamics.render.item.RenderItemCover.renderItem(RenderItemCover.java:57)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)
	at codechicken.lib.render.item.CCRenderItem.func_191962_a(CCRenderItem.java:270)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:337)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:29)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:22)
	at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:69)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:189)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_611_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at com.rwtema.extrautils2.backend.model.Textures.getModelResourceLocation(Textures.java:62)
	at com.rwtema.extrautils2.backend.model.Textures$ItemMesher.func_178113_a(Textures.java:375)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:52)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:242)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:393)
	at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderItemCover(CoverRenderer.java:168)
	at cofh.thermaldynamics.render.item.RenderItemCover.renderItem(RenderItemCover.java:57)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)

-- Item being rendered --
Details:
	Item Type: cofh.thermaldynamics.item.ItemCover@421ec4f4
	Item Aux: 0
	Item NBT: {Meta:0b,Block:"extrautils2:decorativesolidwood"}
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:343)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:29)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:22)
	at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:69)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:189)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_611_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Thermal Dynamics
	Ingredient Info: 1xitem.thermaldynamics.cover@0 thermaldynamics:cover nbt:{Meta:0b,Block:"extrautils2:decorativesolidwood"}

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (465, 13). Absolute: (1860, 963)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['logitech_Q'/495, l='MpServer', x=218.48, y=80.00, z=253.81]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (216,64,252), Chunk: (at 8,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 22162302 game time, 1355599 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 88 total; [EntityPlayerSP['logitech_Q'/495, l='MpServer', x=218.48, y=80.00, z=253.81], EntityCreeper['Creeper'/129, l='MpServer', x=184.50, y=31.00, z=193.50], EntitySkeleton['Skeleton'/130, l='MpServer', x=187.50, y=31.00, z=192.50], EntityCreeper['Creeper'/131, l='MpServer', x=190.50, y=33.00, z=198.50], MoCEntityFly['Fly'/133, l='MpServer', x=185.50, y=73.00, z=190.22], EntityItem['item.item.rottenFlesh'/134, l='MpServer', x=187.13, y=77.00, z=200.88], MoCEntityFirefly['Firefly'/135, l='MpServer', x=192.50, y=76.00, z=200.90], EntityZombie['Zombie'/136, l='MpServer', x=181.50, y=76.00, z=217.50], EntityCreeper['Creeper'/776, l='MpServer', x=182.50, y=38.00, z=264.50], MoCEntityCrab['Crab'/137, l='MpServer', x=184.50, y=63.00, z=233.50], EntitySkeleton['Skeleton'/777, l='MpServer', x=235.69, y=65.00, z=273.50], EntitySkeleton['Skeleton'/139, l='MpServer', x=185.50, y=30.00, z=275.50], EntitySkeleton['Skeleton'/140, l='MpServer', x=181.50, y=77.00, z=272.25], EntityZombie['Zombie'/1036, l='MpServer', x=171.50, y=51.00, z=196.50], MoCEntityRat['Rat'/141, l='MpServer', x=181.50, y=72.00, z=276.50], EntitySpider['Spider'/142, l='MpServer', x=184.50, y=77.00, z=294.50], EntityItem['item.item.rottenFlesh'/155, l='MpServer', x=194.54, y=76.00, z=191.56], EntityZombie['Zombie'/157, l='MpServer', x=196.50, y=19.00, z=194.50], EntityWitch['Witch'/158, l='MpServer', x=201.50, y=79.00, z=199.50], EntityItem['item.item.arrow'/159, l='MpServer', x=204.63, y=74.00, z=289.13], EntityItem['item.item.bone'/160, l='MpServer', x=204.48, y=74.00, z=289.13], EntityZombie['Zombie'/679, l='MpServer', x=185.50, y=77.00, z=276.50], EntityCreeper['Creeper'/681, l='MpServer', x=161.50, y=45.00, z=253.50], EntityCreeper['Creeper'/171, l='MpServer', x=215.50, y=80.00, z=197.50], MoCEntityButterfly['ButterFly'/172, l='MpServer', x=209.10, y=79.00, z=218.90], MoCEntityFirefly['Firefly'/173, l='MpServer', x=203.10, y=79.00, z=210.90], MoCEntityFirefly['Firefly'/174, l='MpServer', x=210.30, y=78.00, z=208.10], EntityCreeper['Creeper'/175, l='MpServer', x=217.50, y=21.00, z=291.50], MoCEntitySilverSkeleton['SilverSkeleton'/176, l='MpServer', x=218.50, y=18.00, z=298.50], EntitySkeleton['Skeleton'/944, l='MpServer', x=167.50, y=49.00, z=200.50], EntitySkeleton['Skeleton'/177, l='MpServer', x=216.50, y=34.00, z=297.50], EntityEnderman['Enderman'/178, l='MpServer', x=222.50, y=72.00, z=296.50], EntityCreeper['Creeper'/690, l='MpServer', x=186.50, y=14.00, z=210.50], EntityItem['item.item.rottenFlesh'/193, l='MpServer', x=228.19, y=87.00, z=196.69], EntitySkeleton['Skeleton'/194, l='MpServer', x=230.50, y=89.00, z=199.50], EntityCreeper['Creeper'/195, l='MpServer', x=230.50, y=90.00, z=204.50], EntityZombie['Zombie'/196, l='MpServer', x=237.50, y=21.00, z=216.50], EntityCreeper['Creeper'/197, l='MpServer', x=239.50, y=21.00, z=214.50], EntityEnderman['Enderman'/198, l='MpServer', x=238.91, y=52.00, z=286.52], MoCEntitySilverSkeleton['SilverSkeleton'/710, l='MpServer', x=263.50, y=77.00, z=228.50], MoCEntityButterfly['ButterFly'/199, l='MpServer', x=234.02, y=73.00, z=284.49], MoCEntityMaggot['Maggot'/200, l='MpServer', x=233.50, y=73.00, z=283.50], MoCEntityMaggot['Maggot'/201, l='MpServer', x=236.50, y=73.00, z=284.50], MoCEntityMaggot['Maggot'/202, l='MpServer', x=234.50, y=73.00, z=282.50], EntityCreeper['Creeper'/215, l='MpServer', x=255.50, y=28.00, z=205.50], EntitySkeleton['Skeleton'/217, l='MpServer', x=247.50, y=21.00, z=217.50], EntityZombie['Zombie'/219, l='MpServer', x=253.50, y=76.00, z=215.50], EntitySkeleton['Skeleton'/731, l='MpServer', x=195.50, y=19.00, z=195.50], EntitySkeleton['Skeleton'/220, l='MpServer', x=255.50, y=85.00, z=218.50], EntityCreeper['Creeper'/221, l='MpServer', x=254.50, y=52.00, z=238.50], EntityZombie['Zombie'/222, l='MpServer', x=255.50, y=50.00, z=246.50], EntitySpider['Spider'/223, l='MpServer', x=252.50, y=72.00, z=272.50], EntitySkeleton['Skeleton'/224, l='MpServer', x=255.50, y=74.00, z=295.50], EntityBasalz['Basalz'/102, l='MpServer', x=157.50, y=71.00, z=201.50], MoCEntityWraith['Wraith'/103, l='MpServer', x=144.75, y=91.50, z=272.75], EntityBlizz['Blizz'/234, l='MpServer', x=264.50, y=55.00, z=191.50], EntitySkeleton['Skeleton'/235, l='MpServer', x=264.50, y=56.00, z=189.50], EntitySkeleton['Skeleton'/108, l='MpServer', x=172.50, y=40.00, z=196.50], EntitySkeleton['Skeleton'/236, l='MpServer', x=265.50, y=21.00, z=202.50], EntityCreeper['Creeper'/109, l='MpServer', x=163.59, y=47.00, z=201.74], EntityEnderman['Enderman'/237, l='MpServer', x=259.50, y=21.00, z=204.50], EntitySkeleton['Skeleton'/110, l='MpServer', x=168.50, y=49.00, z=200.50], EntityCreeper['Creeper'/494, l='MpServer', x=170.50, y=64.00, z=213.50], EntitySkeleton['Skeleton'/238, l='MpServer', x=261.50, y=51.00, z=201.50], EntitySkeleton['Skeleton'/111, l='MpServer', x=167.50, y=48.00, z=202.50], EntityCreeper['Creeper'/239, l='MpServer', x=263.58, y=55.00, z=193.22], EntityWitch['Witch'/112, l='MpServer', x=170.50, y=50.00, z=199.50], EntityCreeper['Creeper'/240, l='MpServer', x=264.50, y=53.00, z=197.50], EntityZombie['Zombie'/113, l='MpServer', x=171.50, y=71.00, z=206.50], EntityZombie['Zombie'/241, l='MpServer', x=258.50, y=21.00, z=213.50], EntityItem['item.item.rottenFlesh'/114, l='MpServer', x=171.26, y=109.00, z=198.71], EntityCreeper['Creeper'/242, l='MpServer', x=258.50, y=21.00, z=212.50], EntitySpider['Spider'/243, l='MpServer', x=267.50, y=70.00, z=234.50], EntityZombie['Zombie'/116, l='MpServer', x=167.50, y=38.00, z=218.50], EntityZombie['Zombie'/244, l='MpServer', x=269.50, y=68.00, z=231.50], EntitySkeleton['Skeleton'/117, l='MpServer', x=163.50, y=37.00, z=218.50], EntitySpider['Spider'/245, l='MpServer', x=263.50, y=69.00, z=237.50], MoCEntityRat['Rat'/246, l='MpServer', x=271.50, y=86.00, z=226.50], EntitySpider['Spider'/119, l='MpServer', x=170.50, y=64.00, z=215.50], EntityZombie['Zombie'/247, l='MpServer', x=258.50, y=56.00, z=247.50], EntityBasalz['Basalz'/121, l='MpServer', x=173.50, y=24.00, z=277.50], EntitySkeleton['Skeleton'/249, l='MpServer', x=261.23, y=70.00, z=256.48], EntityZombie['Zombie'/122, l='MpServer', x=165.50, y=22.00, z=272.50], EntitySkeleton['Skeleton'/250, l='MpServer', x=267.50, y=79.00, z=279.50], EntitySkeleton['Skeleton'/123, l='MpServer', x=161.52, y=88.00, z=273.67], EntityItem['item.item.rottenFlesh'/251, l='MpServer', x=266.88, y=78.00, z=279.48], EntityCreeper['Creeper'/252, l='MpServer', x=256.50, y=59.00, z=298.50], EntityZombie['Zombie'/253, l='MpServer', x=258.50, y=58.00, z=305.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2788247832 bytes (2659 MB) / 4429185024 bytes (4224 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version              | Source                                          | Signature                                |
	|:------ |:--------------------------------- |:-------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                         | 1.12.2               | minecraft.jar                                   | None                                     |
	| UCHIJA | mcp                               | 9.42                 | minecraft.jar                                   | None                                     |
	| UCHIJA | FML                               | 8.0.99.99            | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                             | 14.23.5.2768         | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | jei                               | 4.14.4.260           | jei_1.12.2-4.14.4.260.jar                       | None                                     |
	| UCHIJA | appleskin                         | 1.0.9                | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJA | bno                               | 1.12.2-1.0.4.0       | BasicNetherOres-1.12.2-1.0.4.0.jar              | None                                     |
	| UCHIJA | codechickenlib                    | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | chickenchunks                     | 2.4.1.73             | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | coalgen                           | 1.0.1 - MC 1.12.2    | coalgen-1.0.1.jar                               | None                                     |
	| UCHIJA | redstoneflux                      | 2.1.0                | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | cofhcore                          | 4.6.1                | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UCHIJA | cofhworld                         | 1.3.0                | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | mocreatures                       | 12.0.5               | DrZharks MoCreatures Mod-12.0.5.jar             | None                                     |
	| UCHIJA | endercore                         | 1.12.2-0.5.43        | EnderCore-1.12.2-0.5.43.jar                     | None                                     |
	| UCHIJA | thermalfoundation                 | 2.6.1                | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | thermalexpansion                  | 5.5.2                | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | enderio                           | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderiointegrationtic             | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderiobase                       | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderioconduits                   | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderioconduitsappliedenergistics | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderioconduitsopencomputers      | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | refinedstorage                    | 1.6.12               | refinedstorage-1.6.12.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJA | enderioconduitsrefinedstorage     | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderiointegrationforestry        | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderiointegrationticlate         | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderiomachines                   | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | enderiopowertools                 | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| UCHIJA | foamflower                        | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar             | None                                     |
	| UCHIJA | enderpay                          | 1.12.2-1.0.1.0       | enderpay-1.12.2-1.0.1.0.jar                     | None                                     |
	| UCHIJA | extrautils2                       | 1.0                  | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| UCHIJA | zerocore                          | 1.12-0.1.2.3         | zerocore-1.12-0.1.2.3.jar                       | None                                     |
	| UCHIJA | bigreactors                       | 1.12.2-0.4.5.50      | ExtremeReactors-1.12.2-0.4.5.50.jar             | None                                     |
	| UCHIJA | waila                             | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHIJA | inventorytweaks                   | 1.64+dev.145.16d98f2 | InventoryTweaks-1.64+dev.145.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | journeymap                        | 1.12.2-5.5.3         | journeymap-1.12.2-5.5.3.jar                     | None                                     |
	| UCHIJA | jrftl                             | 1.1                  | JRFTL[1.12.2]-1.1.jar                           | None                                     |
	| UCHIJA | levelup2                          | ${version}           | Level+Up!+2-1.1.22-1.12.jar                     | None                                     |
	| UCHIJA | longfallboots                     | 1.2.1a               | longfallboots-1.2.1b.jar                        | None                                     |
	| UCHIJA | mcjtylib_ng                       | 3.1.1                | mcjtylib-1.12-3.1.1.jar                         | None                                     |
	| UCHIJA | rangedpumps                       | 0.5                  | rangedpumps-0.5.jar                             | None                                     |
	| UCHIJA | refinedstorageaddons              | 0.4.3                | refinedstorageaddons-0.4.3.jar                  | None                                     |
	| UCHIJA | roguelike                         | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHIJA | thermaldynamics                   | 2.5.3                | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | simplyjetpacks                    | 2.2.10.63            | SimplyJetpacks2-1.12.2-2.2.10.63.jar            | None                                     |
	| UCHIJA | thermalinnovation                 | 0.3.1                | ThermalInnovation-1.12.2-0.3.1.8-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | tramplestopper                    | 1.2.3                | tramplestopper-1.12.2-1.2.3-universal.jar       | None                                     |
	| UCHIJA | veinminer                         | 0.38.2               | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| UCHIJA | veinminermodsupport               | 0.38.2               | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| UCHIJA | vending                           | 1.12.2-3.0.1.2       | vending-1.12.2-3.0.1.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.145.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.11' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.11, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by logitechQ** [comment]
please help

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
Ingredient Mod: Thermal Dynamics
Ingredient Info: 1xitem.thermaldynamics.cover@0 thermaldynamics:cover nbt:{Meta:0b,Block:"extrautils2:decorativesolidwood"}
```
From the log, this seems to be an issue with a Thermal Dynamics Cover of an ExtraUtils2 block.
Please report this to Thermal Dynamics here: https://github.com/CoFH/Feedback/issues
