### ISSUE TITLE
I Can't open my Inventory

### ISSUE THREAD

**Issue by matiasfabrizio** [mezz/JustEnoughItems#1490]
When I use my modpack, it does not allow me to open the inventory when I install the JEI. If I uninstall it and try to open my inventory, there if I can open it, I do not know why it happens, but I would appreciate someone helping me solve it. I have the report of the game crash, in case something helps.
[crash-2019-02-04_18.22.06-client.txt](https://github.com/mezz/JustEnoughItems/files/2830176/crash-2019-02-04_18.22.06-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: OpenBlocks
	Ingredient Info: 1xitem.openblocks.glyph@51 openblocks:glyph
```
This appears to be an issue with OpenBlocks, you can report to them here: https://github.com/OpenMods/OpenBlocks/issues
