### ISSUE TITLE
API Request: Get bookmark overlay 

### ISSUE THREAD

**Issue by Towdium** [mezz/JustEnoughItems#1491]
Hi,

It seems there is no API related to bookmark overlay. Is there any way to get ingredient under mouse from bookmark overlay (like from ingredient overlay) without touching internal classes of JEI?

Since bookmark is relatively a new feature, It might be too early to make permanent APIs. It will not be a problem for me to wait or to keep track of internal classes.

**Comment by mezz** [comment]
I am mostly working on 1.13 right now, so it should be safe to use internal classes in 1.12 until I have some time to make a proper API for this.

**Comment by mezz** [comment]
The bookmark feature is still "beta" for now. I have a few issues (including this one) before I will make a new a release version of JEI.

**Comment by Towdium** [comment]
That makes sense. Thanks for the information.
