### ISSUE TITLE
Crash when looking up recipe

### ISSUE THREAD

**Issue by jeremygturpin** [mezz/JustEnoughItems#1492]
Hi, I'm getting the following error when looking up recipes. Only happens in server, not single player.
https://gist.github.com/jeremygturpin/d5bdc794b8bf62eeb7a028a044310fba

**Comment by mezz** [comment]
Thanks for the report!
```
-- Item being rendered --
Details:
	Item Type: com.rwtema.extrautils2.backend.XUItemBlock@ca521b
	Item Aux: 0
	Item NBT: null
	Item Foil: false
```
This seems to be an issue from ExtraUtilities2, please report to them here: https://github.com/rwtema/Extra-Utilities-2-Source/issues
