### ISSUE TITLE
I can't see all the items to the right of my inventory

### ISSUE THREAD

**Issue by Minkanuzo** [mezz/JustEnoughItems#1493]
Hi, i installed Forge and JEI, I can see the Recipes, Uses, The problem is i can't see all the items to the right of my inventory, and i don't know how to fix it
![screenshot_1](https://user-images.githubusercontent.com/47462075/52504739-165a9700-2bc8-11e9-966f-69109208690c.png)

Thanks!

**Comment by TehNut** [comment]
Not sure I understand the problem. Everything there seems to be rendering properly

**Comment by mezz** [comment]
Thanks for the report!
This screenshot looks normal, can you please explain?

**Comment by Minkanuzo** [comment]
> Not sure I understand the problem. Everything there seems to be rendering properly

Already Solved, i touched CTRL + O and now i can see the items of the image i posted before
(Sorry, my english is not the better)

Thanks for the Help!

**Comment by Minkanuzo** [comment]
> Thanks for the report!
> This screenshot looks normal, can you please explain?

Already Solved, i touched CTRL + O and now i can see the items of the image i posted before
(Sorry, my english is not the better)

Thanks for the Help!
