### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by KE7ZALCO4TL** [mezz/JustEnoughItems#1497]
![2019-02-14_01 48 13](https://user-images.githubusercontent.com/47614615/52749813-5fad4b00-2ffb-11e9-822e-98994cc4309c.png)
Hi! My interface gone wiered (look at the middle of screenshot) after random game start (this never happened before). I removed all the mods except JEI and deleted all config files but this didnt changed anything. Is there any way to fix it? 
Also i have another question, is there any way to completely remove bookmarks from GUI?

**Comment by KE7ZALCO4TL** [comment]
Also i have another question, is there any way to completely remove bookmarks from GUI?

**Comment by mezz** [comment]
Thanks for the report!
Are you using a texture pack? There may be an issue with the texture pack and the latest JEI updates.

**Comment by KE7ZALCO4TL** [comment]
> Thanks for the report!
> Are you using a texture pack? There may be an issue with the texture pack and the latest JEI updates.

Yes, im using texture pack, but previously everything was OK, and i didnt make any updates,

**Comment by DrakkenRex** [comment]
Just updated to 4.14.4.264 myself and encountered this same UI glitch on recipes. I had Faithful 32 (1.12.2-rv4) and Modded Faithful 32 (1.12.2-rv1) installed and tested removing them - the UI glitch does indeed go away.

**Comment by mezz** [comment]
This should be fixed in JEI 4.14.4.265
