### ISSUE TITLE
Sort Items in ItemList by ModID first, then ID

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#150]
Any chance this is something that could become implemented? It makes it so that if a mod adds content later, it's easier to find because then all of its items (regardless of world-assigned item ID) are still clustered together.

**Comment by mezz** [comment]
I need to look at organizing the list in general. Right now it's just "all blocks" then "all items".

**Comment by Prospector** [comment]
Yeah it's really annoying not having it sorted by modid.
