### ISSUE TITLE
missing texture with latest update

### ISSUE THREAD

**Issue by Trixz2018** [mezz/JustEnoughItems#1503]
![image](https://user-images.githubusercontent.com/8538100/53309680-cab61780-386e-11e9-9386-781ea2271b4b.png)

jei_1.12.2-4.14.4.265

This is with all recipes not just vanilla and no i am not using a texture pack never did. reverting back to update before this one does not have this issue

**Comment by mezz** [comment]
Thanks for the report!
Dumb mistake on my part, I just pushed a fix for it now.
