### ISSUE TITLE
jei_1.12.2-4.15.0.268 work not with the wings mod

### ISSUE THREAD

**Issue by Titoo8899** [mezz/JustEnoughItems#1506]
Hi,
can you a patch make for your mod who the compatiblität of the wings mod.

Links of Mod: [https://minecraft.curseforge.com/projects/wings](url)

Forge say: You must include the right dependencies for Wings:
Only compatible with Just Enough Items 4.8 or above, and below 4.15 (you have 4.15.0.268)

Please fix this problem.

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with the wings mod. I have reported it to the author and it has been reported on their github here: https://github.com/pau101/Wings/issues/26
