### ISSUE TITLE
StackHelper uidCache still takes about 35 MB of heap space while ingame

### ISSUE THREAD

**Issue by ichttt** [mezz/JustEnoughItems#1507]
Hi,
I'm doing some heap analysis on large packs right now and I saw that the uidCache still takes 33MB of space even though the comment says it should only be used during loading.
The cause for this seems that the array that backs IdentityHashMap stays at it's maximum size after clear, and so there is a huge array filled with nulls staying around.
![screenshot_2](https://user-images.githubusercontent.com/20151702/53799123-04a3af80-3f3a-11e9-9dc6-fbf2622f9690.png)

**Comment by mezz** [comment]
Thanks for the report!
I didn't expect a cleared map to hold on to that much memory, good find.
