### ISSUE TITLE
Reloading textures (F3+T) causes Astral sorcery custom recipes to not show in JEI (possibly other mods?)

### ISSUE THREAD

**Issue by Saereth** [mezz/JustEnoughItems#1508]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

Also posted to AS github here:
https://github.com/HellFirePvP/AstralSorcery/issues/1025

Basically if we run crafttweaker + jei + astral sorcery and add a custom recipe to its lightwell, crafting altar etc those recipe changes will show up fine but as soon as you reload textures in game with F3+T (or a mod does this like coop) the recipes will no longer show in JEI despite them still being valid recipes and working. Not sure if this issue is with JEI or Astral specifically but xposting for visibility. 

versions:
jei_1.12.2-4.15.0.268
Astral sorcery Jenkins build v82 (latest on his jenkins repo, although this also occurs with latest public stable release astralsorcery-1.12.2-1.10.12).
CraftTweaker2-1.12-4.1.15

**Comment by mezz** [comment]
Thanks for the report!
Looks like this has been marked as fixed on Astral Sorcery's side.
