### ISSUE TITLE
Random Fatal Error Kick alongside JEI/Plugins and Astral Sorcery 1.10.1+

### ISSUE THREAD

**Issue by SalmonSays** [mezz/JustEnoughItems#1509]
I'm cross-posting at the request of an Astral Sorcery Dev: https://github.com/HellFirePvP/AstralSorcery/issues/1020

The short version is that any version of AS *after* astralsorcery-1.12.2-1.9.4.jar coupled with JEI/JEI plugins (such as JustEnoughPetroleum, etc) appears to cause a Fatal Error kick (not crash) between Forge client and server (tested against 14.23.5.2768 and 14.23.5.2814) at random intervals. The problem does not occur in singleplayer instances.

**Comment by mezz** [comment]
Thanks for the report!
This doesn't look like a JEI issue but I'll subscribe to that issue and see if I can help out.
