### ISSUE TITLE
Option to center the JEI Search Box?

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#151]
Another suggestion - I'm only dropping these here because JEI has become just about damn perfect!! Any chance for the ability to have the JEI search box centered? Just a small thing that I really did like about NEI - mostly because I have an ultrawide monitor, so when something is right justified, it's a lot further right for me!

:heart:

**Comment by oitsjustjose** [comment]
Derp, this issue already existed.

**Comment by mezz** [comment]
dupe #111
