### ISSUE TITLE
[Question] Vanilla Search Tree Manager

### ISSUE THREAD

**Issue by ichttt** [mezz/JustEnoughItems#1510]
Hey @mezz, do you think it is possible to replace the vanilla search tree managers with managers provided by JEI, which use the JEI search methods?
Because I did some testing and found that search tree reloading takes about 13 secs on large modpacks (ATM3 remix) when connecting to a server.
![reload](https://user-images.githubusercontent.com/20151702/54363265-e2610e80-466a-11e9-9054-c5aa38469d5e.png)
Additionally, the vanilla search trees holds over 70MB of data while in game.
![Screenshot_3](https://user-images.githubusercontent.com/20151702/54363262-e12fe180-466a-11e9-8918-bcbeff20a6e9.png)

**Comment by mezz** [comment]
Not a bad suggestion, I believe foamfix does that by default. The feature is a bit too invasive for JEI to do by itself.

**Comment by mezz** [comment]
Yep this is done by foamfix here:
https://git.asie.pl/asie-minecraft/FoamFix/src/commit/2937230db822330fbe96dd904147632ec87fdf69/src/main/java/pl/asie/foamfix/coremod/patches/jei/SearchTreeJEIManagerInject.java
