### ISSUE TITLE
[1.13.2 - Forge 25.0.85] Error during plugin discovery

### ISSUE THREAD

**Issue by EdwinMindcraft** [mezz/JustEnoughItems#1514]
**I renamed META-INF/jei_at.cfg to META-INF/accesstransformer.cfg to be able to launch the game**

There is a compatibility error with Forge 25.0.85 during the plugin discovery : [Error Log](https://gist.github.com/EdwinMindcraft/a31f8566fc0dc6bdeed83e804134ef86) (I know JEI is built against 25.0.7-pre but I think it's still worth reporting).

JEI: 5.0.0.7

**Comment by mezz** [comment]
Thanks for the report!
I have just updated JEI to work with Forge 25.0.85 in `jei-1.13.2-5.0.0.8`.
