### ISSUE TITLE
JEI error "net.minecraftforge.fml.common.LoaderExceptionModCrash"

### ISSUE THREAD

**Issue by mechanikate** [mezz/JustEnoughItems#1515]
I am working on a mod called "Imbcraft" and I was trying to install NEI to test something. Game crashed.

Error report:
https://gist.github.com/MatthyPlayz/fe4cb199c7d77a3196ebcf0fbb584bf4

**Comment by bs2609** [comment]
Are you using Eclipse?

If so, please see https://github.com/MinecraftForge/ForgeGradle/issues/519.

**Comment by mechanikate** [comment]
Thanks for the help bs2609, the problem was as said there 

> Issue can be resolved by removing "-DFORGE_FORCE_FRAME_RECALC=true" from the VM arguments in ForgeGradle auto-generated launch configurations.
