### ISSUE TITLE
JEI Crash [1.10.2]

### ISSUE THREAD

**Issue by KingEevee** [mezz/JustEnoughItems#1519]
So I was making a little modpack to play with some friends, and it was working fine when I was testing it out in Singleplayer, but in the server, clicking on any item to view the recipe crashed the game.

Pastebin of the crash report: https://pastebin.com/cDmMWwVL

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue with Extra Utilities 2:
```
-- Item being rendered --
Details:
    Item Type: com.rwtema.extrautils2.backend.XUItemBlock@5eac67c9
    Item Aux: 0
    Item NBT: null
    Item Foil: false
```
Please report to them here: https://github.com/rwtema/Extra-Utilities-2-Source/issues
