### ISSUE TITLE
(feature request) light level indicator(yeah, like it was in nei)

### ISSUE THREAD

**Issue by NarigudoBR** [mezz/JustEnoughItems#152]
it would be very nice to have :P

**Comment by shadowfacts** [comment]
mezz has already stated that features like this from NEI aren't going to be included in JEI for several reasons:
- They bloat the mod, JEI is meant to be a recipe viewing mod and nothing more.
- ChickenBones is going to be creating a separate mod to contain these features from NEI.

(Also there's already a mod that does this: http://minecraft.curseforge.com/projects/light-level-overlay-reloaded)

**Comment by NarigudoBR** [comment]
thanks

**Comment by wlhlm** [comment]
Other mods that provide lightlevel overlays:
- Zyin's HUD
- FTBUtilities (not released yet)
