### ISSUE TITLE
Why does the server need the mod for auto fill?

### ISSUE THREAD

**Issue by Hi-ImKyle** [mezz/JustEnoughItems#1522]
I am terribly sorry if this has been asked/mentioned before but I can't seem to word my question correctly to the point where Google shows a reasonable page to answer my question.

Question is rather simple:
- Why can't I auto fill the crafting recipe when the server doesn't have JEI? Like what's stopping it.

Again sorry if this has already been asked,

**Comment by TehNut** [comment]
Containers are managed on the server side. JEI needs that server component in order to set each item in it's slot.

**Comment by Hi-ImKyle** [comment]
Is there no way to allow it to work for the client side considering the new recipe book Mojang added can do it?

Or better yet, is it possible that I can make JEI do it client side on my own. I have a small background in Java and don't mind getting my hands dirty, if someone can point me in the direction of where the auto fill is handled I'll try my best to do it on my own.

**Comment by mezz** [comment]
JEI handles auto-fill for all kinds of recipes, not just vanilla crafting recipes. 
It should be possible to add a special case for it now that Mojang handles it though.

Unfortunately the only way to handle it generally using just the client is to simulate player clicks rapidly, which is very error-prone, cheaty, and unsafe (could send items flying or cause other weird glitches when the player is interacting at the same time, lagging, etc).

The auto fill code in JEI is by far the ugliest nastiest code in the mod. I wouldn't really recommend jumping into it without at least a master's degree in confusing Mojang ItemStack + Inventory code.
