### ISSUE TITLE
(1.13.2) Crafting recipe showing in jei when there is no crafting recipe for it

### ISSUE THREAD

**Issue by TyrellPlayz** [mezz/JustEnoughItems#1528]
I created my own recipe type for my Crusher including added support for JEI but JEI sees it as a normal crafting recipe when it is not.
In JEI
![2019-03-28_17 47 34](https://user-images.githubusercontent.com/19235911/55138174-bcfff480-5182-11e9-91ef-301553fc8170.png)
In a crafing table
![2019-03-28_17 51 55](https://user-images.githubusercontent.com/19235911/55138179-c2f5d580-5182-11e9-9e87-48321b837971.png)
In JEI under custom category
![2019-03-28_17 57 45](https://user-images.githubusercontent.com/19235911/55138311-12d49c80-5183-11e9-9ed9-18f6b3aa79dc.png)
Code can be found [here](https://github.com/TyrellPlayz/Big-Industries/tree/dev/src/main/java/com/tyrellplayz/big_industries)

**Comment by Shadows-of-Fire** [comment]
It's possible mezz is accidentally pulling the global recipe list `RecipeManager#getRecipes` and treating those all as crafting recipes.

Instead, crafting recipes should be accessed via `RecipeManager#getRecipes(VanillaRecipeTypes.CRAFTING)`

**Comment by mezz** [comment]
Thanks for the report!
Yeah, I implemented this before the recipe separation PR, just so I had something showing. 
I'll fix it to use the new and improved system :)
