### ISSUE TITLE
[Feature request] Allow oredict name to be displayed in tooltip

### ISSUE THREAD

**Issue by K-4U** [mezz/JustEnoughItems#153]
Like NEI had, it would be awesome if the tooltip showed all the oredict names an item has.
So, if i hover over a copper ingot, the tooltip would show "ingotCopper".
More entries would go on multiple lines.

**Comment by TehNut** [comment]
NEI had this? I thought it was added by other mods such as EnderCore.

**Comment by K-4U** [comment]
Either NEI or NEIAddons

**Comment by Prospector** [comment]
It was NEI INTEGRATION :P

**Comment by mezz** [comment]
I can do this for recipes that have OreDict inputs (show the common OreDict for a rotating list of items). 

Doing this for all items in the game it outside the scope of JEI though.
You can look at @TheDoctorSoda's [AdvancedInfoTooltip](https://github.com/TheDoctorSoda/AdvancedInfoTooltip), which is forked from my [ModNameTooltip](https://github.com/mezz/ModNameTooltip).

**Comment by Prospector** [comment]
YES PLEASE! I was wondering why one recipe was using only vanilla logs and not logWood

**Comment by K-4U** [comment]
Well, would still be nice to have it in JEI

**Comment by TehNut** [comment]
Eh, leave JEI to the Item List and recipes. Just use the mod above. mezz already removed the modname tooltip from JEI for another mod.

**Comment by mezz** [comment]
![2016-02-02_22 56 23](https://cloud.githubusercontent.com/assets/916092/12775145/861fbd04-ca00-11e5-951d-b178f2836d74.png)

Rotating items in recipes will show oreDict if they share one in common. Single items will not show it since it's not necessary to know in that case.
