### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Ic4z** [mezz/JustEnoughItems#1532]
My game crashes every time when I try to type anything in the search. https://gist.github.com/Ic4z/75acff93cdd56cc1a9790235bce3f56f

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: OpenBlocks
	Ingredient Info: 1xitem.openblocks.glyph@53 openblocks:glyph
```
Looks like an issue with OpenBlocks, you can read more about how to work around it here: https://github.com/OpenMods/OpenBlocks/issues/948

**Comment by Ic4z** [comment]
Thank you this worked 👍

На нд, 31.03.2019 г., 0:11 mezz <notifications@github.com> написа:
