### ISSUE TITLE
Insanely slow game startup always repeated this line.

### ISSUE THREAD

**Issue by SirAron111** [mezz/JustEnoughItems#1534]
Insanely slow game startup literally took 1 hour to load https://pastebin.com/6gxESbmA always repeated this line.

**Comment by Sunconure11** [comment]
https://github.com/DaedalusGame/EmbersRekindled/issues/143

@mezz

**Comment by mezz** [comment]
Thanks for the report!
It looks like this has been fixed in Embers.
