### ISSUE TITLE
Missing recipes from multiple mods. (IE,Thermal Series, IC2)

### ISSUE THREAD

**Issue by SovietSputnik** [mezz/JustEnoughItems#1537]
Missing output recipe pages from special blocks like Power Generators, Fluid Transposers, etc; from multiple mods (Immersive Engineering and Thermal Series so far).

![3](https://user-images.githubusercontent.com/23246418/55373573-e0001080-54c2-11e9-9a67-85f36c7024a4.png)

![5](https://user-images.githubusercontent.com/23246418/55373715-4f760000-54c3-11e9-947b-c506df5d5173.png)

![6](https://user-images.githubusercontent.com/23246418/55373719-53098700-54c3-11e9-9f98-0f3a3ecc2142.png)

**Comment by SovietSputnik** [comment]
Single and Multiplayer alike. Also IC2

![7](https://user-images.githubusercontent.com/23246418/55373966-243fe080-54c4-11e9-8cc5-c69359c3ffa0.png)

**Comment by SovietSputnik** [comment]
Also the problem propagates across multiple versions. All the way to jei_1.12.2-4.15.0.268 More interesting is that it was working fine yesterday.

Update: All the way down to 1.12.2-4.13.1.225 Seems like a server update default setting.

**Comment by Brightmikal** [comment]
Sorry, when you say 'All the way to 1.12.2-4.13.1.225' do you mean the bug isn't in versions earlier than that? Have you tried newer JEI versions?

Else I'm having the same issue. Been running Sky Adventures 1.4.0 for over 100 hours and suddenly the recipes from the Fluid Transposer and others have disappeared. I've used them many times, so not sure whats triggered it.

On the TE Github [https://github.com/CoFH/Feedback/issues/1469](url) there's a post which seems to mirror the problem, they've traced it to JEI plugin crashing and possible rendering conflict.

Any idea how to fix the issue on current saves?

Also apologies for any faux pas/formatting issues, I don't post much on github.

**Comment by SovietSputnik** [comment]
> Sorry, when you say 'All the way to 1.12.2-4.13.1.225' do you mean the bug isn't in versions earlier than that? Have you tried newer JEI versions?
> 
> Else I'm having the same issue. Been running Sky Adventures 1.4.0 for over 100 hours and suddenly the recipes from the Fluid Transposer and others have disappeared. I've used them many times, so not sure whats triggered it.
> 
> On the TE Github [https://github.com/CoFH/Feedback/issues/1469](url) there's a post which seems to mirror the problem, they've traced it to JEI plugin crashing and possible rendering conflict.
> 
> Any idea how to fix the issue on current saves?
> 
> Also apologies for any faux pas/formatting issues, I don't post much on github.

I've tried updating it to the latest and downgrading it to 225. Seems like some config got changed on the fly from some code source outside the jar file.

**Comment by Brightmikal** [comment]
I have no idea what has happened, but the recipes are back.

Weirdly even re-downloading the modpack didn't fix the issue. Confirmed it wasn't a pc issue when a friend who downloaded the pack had the same problem from the start.

I went through all my mods toggling them on and off, sometimes the bug was there, sometimes it wasn't. But now even with all mods enabled the bug isn't present.

**Comment by SovietSputnik** [comment]
The issue has been solved somehow.
