### ISSUE TITLE
Crash on looking up "crop" or anything Crated in JEI?

### ISSUE THREAD

**Issue by Sataana** [mezz/JustEnoughItems#1538]
Not sure if a closed issue gets reopen when I comment on it, so just cross posting to make sure...

Having the same issue when I tried to look up "clay"
Inset huge crash report [here](https://gist.github.com/Sataana/dd96a1992dbd2593bd0e5221b2933952)
Does anyone know of a known fix?
Optifine not installed.
Did install FoamFix, BetterFPS & Surge

https://github.com/mezz/JustEnoughItems/issues/1462#issue-398636184

**Comment by mezz** [comment]
Thanks, I will reopen the other issue.
