### ISSUE TITLE
Unable to auto arrange recopies in a PortableCraft crafting table.

### ISSUE THREAD

**Issue by SpikeVanHellsing** [mezz/JustEnoughItems#1541]
Not a huge problem as items can still be moved manually. However, when moving items via the [+] it makes the click sound but moves nothing. jei vers 4.15.0.273 for 1.12.2

**Comment by mezz** [comment]
Thanks for the report!
Each mod handles their own [+] behavior, please report this issue to PortableCrafting here: https://github.com/gr8pefish/PortableCrafting/issues
