### ISSUE TITLE
JEI taking long time to load

### ISSUE THREAD

**Issue by Archilyte** [mezz/JustEnoughItems#1544]
I dont know if theres a solution for this but...
![Minecraft 1 12 2 4_6_2019 8_14_42 PM](https://user-images.githubusercontent.com/39607601/55676745-c2f38500-58a8-11e9-9fc3-98f4a49742a3.png)
jEI is taking a long time to load in this stage.
if i remove JEI, it works perfectly
(custom modpack btw)

**Comment by Archilyte** [comment]
Lower resolutions doesnt work

**Comment by Drag0nsaver** [comment]
Do you have Embers on the latest release (1.13 as of this note) in your pack? If so, try rolling it back to the previous version (1.12). I was getting a similar issue at this exact phase and that cleared it up for me.

Custom Pack here as well
MC V. 1.12.2 running Forge-14.23.5.2824

JEI 1.12.2-4.15.0.275 with Embers 1.13 results in incredibly slow load times on phase 6/7 - Loading recipes.

JEI 1.12.2-4.15.0.275 with Embers 1.12 gets through so much faster by comparison, but will slow down for a few seconds when processing Embers

**Comment by Archilyte** [comment]
Ok. I will notify you if that works. If it does, I will close this issue.

**Comment by Archilyte** [comment]
Yep! That was the fix! Thanks!

**Comment by mezz** [comment]
Please let Embers know it is still an issue here:
https://github.com/DaedalusGame/EmbersRekindled/issues/143
