### ISSUE TITLE
java.lang.IllegalAccessError in development environment [1.13.2]

### ISSUE THREAD

**Issue by PssbleTrngle** [mezz/JustEnoughItems#1548]
I included the newest 1.13.2 JEI version as a dependency in my modding environment, but when trying to run I get an [error](https://gist.github.com/PssbleTrngle/7d48f398f42dc72ac08c83a84565e8b4)

It is caused by the JeiTextureMap trying to add something to its own "sprites" member which is now private.

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with ATs from dependencies not getting applies. Try updating to the latest version of Forge and JEI to see if it is still an issue, I believe it has been fixed.

**Comment by PssbleTrngle** [comment]
My project did not seem to refresh my dependencies, I now am on the newest version of both JEI and Forge and it works, sorry to bother you.

**Comment by mezz** [comment]
Cool, glad it’s working.
