### ISSUE TITLE
Support rarity generalisation introduced in forge build 2816

### ISSUE THREAD

**Issue by LemADEC** [mezz/JustEnoughItems#1549]
As of 1.12.2-4.15.0.275, items rarity isn't supporting the new IRarity interface and related getForgeRarity() methods introduced here: https://github.com/MinecraftForge/MinecraftForge/pull/5182 .
Mods using this new system will show with white item names, while the creative inventory use the proper colors.

**Comment by mezz** [comment]
Thanks for the heads-up! Support has been added in the latest version of JEI.
