### ISSUE TITLE
JEI crash when typing in search box

### ISSUE THREAD

**Issue by Miosp** [mezz/JustEnoughItems#1554]
So, JEI crashes only when i type letter "v", "x", or type "pack" and delete last k. Now im kinda stuck with pack searched, because i can't delete it.

crash log:
https://gist.github.com/debilman/22907cb6fb630ed6de43bc15caa7849f

Mc launcher after crash displays only: 
java.lang.ArrayIndexOutOfBoundsException: -1

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: OpenBlocks
	Ingredient Info: 1xitem.openblocks.glyph@32 openblocks:glyph
```
Please report this to OpenBlocks here: https://github.com/OpenMods/OpenBlocks/issues

**Comment by liny-fox** [comment]
Can this be looked at more to see if it is JEI or other mod? As I have just gotten the same crash stack but it the log says its forestry. Maybe can a failsafe be added into JEI to prevent a bug in other mods from crashing it?
https://gist.github.com/liny-odell/d1ce1160db289797f36e77bb3ac63321

edit: link to crash instead of pasting the entire log
edit2: seems my crash is #1462 instead.

**Comment by mezz** [comment]
```
-- Ingredient being rendered --
  Ingredient Mod: Forestry
  Ingredient Info: 1xitem.crated.natura.edibles.4@0 forestry:crated.natura.edibles.4
```

Yes, that looks like Forestry to me. 

Unfortunately, rendering errors are complicated. Often when trying to prevent a render crash I may leave the rendering engine in a bad state and it will crash later from some other mod doing perfectly normal things. Then that mod will get reports and nobody will know the original cause.
Generally JEI will catch mod errors and log them, but for rendering errors I am forced to let them go through so I do not obscure the original cause of the crash.

Please open a new issue next time, I may not see comments on closed issues like this.

**Comment by liny-fox** [comment]
Fair enough reason to let them go through, and I would have but as a programmer myself avoiding duplicates is how I think, but now that I see there is a bug with the same mod and info listed, I linked that in my post.
