### ISSUE TITLE
allegedly wrong forge version

### ISSUE THREAD

**Issue by CForce1999** [mezz/JustEnoughItems#1559]
Hi, i like what the mod has to offer, but i can't solve this problem on my own: supposedly my forge version is too old to work with this mod, despite me using forge 14.23.5.2835 . strangely, this mod is the only one i know that has that problem, so i strongly believe that something with your mod might not be in order. any before you ask: yes, i got forge from https://files.minecraftforge.net/ .

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by DeathAdder516** [comment]
Hi mezz, I have the same issue but I have the log for you!
And here it is - https://pastebin.com/Zp91uhWq
And the GitHub version is here also - https://gist.github.com/DeathAdder516/9bd460088f95dc78b431b1d91711b293

**Comment by TehNut** [comment]
According to line 4 of your log, you are using Forge 14.23.5.2768.

**Comment by DeathAdder516** [comment]
Alright so updating it to the latest should fix this?

**Comment by DeathAdder516** [comment]
Download Latest
1.12.2 - 14.23.5.2836, This is the latest version.

**Comment by DeathAdder516** [comment]
She's working now thanks guys!
