### ISSUE TITLE
inventory duplication/deletion when adding items via recipe right click

### ISSUE THREAD

**Issue by BrewingCoder** [mezz/JustEnoughItems#156]
JEI ver:  2.25.3.131 with Cheats enabled.

JEI Add-Ons:  0.10.1.39

Can Repro in SMP and local but in both cases world rights exlist (op on server, local build world has cheats on).

When I'm reviewing recipes (either shapless, furnace, etc..) and right click on an item to receive said item it deletes a whole row of the users inventory then replicates it with the row above/below.

Please see the 3 attached screen shots showing the before, where I right clicked (sapling), and results.

This happens on all recipe screens, with all items, and in all cases.  

![cap1-rightclicksapling](https://cloud.githubusercontent.com/assets/6723474/12849524/036cca38-cbee-11e5-8db2-bdad61662053.PNG)
![cap1-before](https://cloud.githubusercontent.com/assets/6723474/12849526/03742ddc-cbee-11e5-996f-e0dc7fff641e.PNG)
![cap1-after](https://cloud.githubusercontent.com/assets/6723474/12849525/036e0a38-cbee-11e5-9117-dc856ef85d12.PNG)

**Comment by mezz** [comment]
Thanks for the report!
It looks like the duplicated items don't actually exist, if you click one they go away.
I'll try to find why it's doing this. JEI uses vanilla minecraft's `/give` command so it's pretty safe.

**Comment by mezz** [comment]
I will remove the ability to cheat items by clicking them in the recipe area.
It is not really an intended feature, and removing it fixes the glitch.

**Comment by BrewingCoder** [comment]
they exist here.. maybe it's another mod that's causing it.  I left that world open and just went in and stacked the items:

![image](https://cloud.githubusercontent.com/assets/6723474/12849907/0ad33904-cbf0-11e5-9894-9377930ff3ab.png)

so they are real; and items that had existed on the duplicated line are gone.

if you're just using the /give command it's either a Forge bug or maybe InvTweaks is doing something sketchy.

**Comment by mezz** [comment]
InvTweaks has been a bit glitchy in 1.8.9, maybe that's it? 
I wasn't able to get "real" duplication in singleplayer with just JEI.

**Comment by BrewingCoder** [comment]
the final test was SMP.  let me see if single player keeps the items.

**Comment by BrewingCoder** [comment]
it's InventoryTweaks.. damn.  sorry about that.  I wasn't even looking down that path.  Sorry to waste your time mezz. Keep up the good work.

**Comment by mezz** [comment]
No problem. I'll have some fixes relating to this soon, since cheating items from the recipe view shouldn't be possible. Also even with that removed, `/give` while the recipe view is open does weird visual stuff to the player inventory.

**Comment by mezz** [comment]
Also I recommend [cpw's Inventory Sorter](http://minecraft.curseforge.com/projects/inventory-sorter) for 1.8.9. It has fewer features but seems more reliable than inventory tweaks right now.

**Comment by mezz** [comment]
The latest version (2.25.6.140) should fix these issues even with Inventory Tweaks.
