### ISSUE TITLE
how do disable my Inventory highlight?

### ISSUE THREAD

**Issue by VictorTheDuck** [mezz/JustEnoughItems#1560]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Inventory highlight is not a feature added by JEI, it is added by some other mod.
Usually you enable or disable it by double-clicking the search bar, depending on the mod.

**Comment by frenchiveruti** [comment]
> 
> 
> Thanks for the report!
> Inventory highlight is not a feature added by JEI, it is added by some other mod.
> Usually you enable or disable it by double-clicking the search bar, depending on the mod.

Hello, but here it states that JEI has this feature:  
https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0

**Comment by mezz** [comment]
On that chart, the row for "Inventory Search" only has check marks for "More Overlays" and "Not Enough Items 1.8+".

**Comment by frenchiveruti** [comment]
> 
> 
> On that chart, the row for "Inventory Search" only has check marks for "More Overlays" and "Not Enough Items 1.8+".

Hello again, yes.  
I'm blind.  
Sorry,
