### ISSUE TITLE
Issues with items differentiated with NBT

### ISSUE THREAD

**Issue by justinrusso** [mezz/JustEnoughItems#1562]
It appears like items which are differentiated via NBT rather than metadata are not being handled correctly. In one mod, ResourceHogs, looking at the recipe for a single item shows every item of that same type (bacon), rather than a specific resource bacon as desired.

In another example, searching for slime (looking for the slime seed) ends up highlighting all of the Animal Crop seeds rather than the Slime Animal Crop seed 
![image](https://user-images.githubusercontent.com/25138621/56582659-c32c9980-65a5-11e9-82c1-807544721b79.png)

If I can assist in providing more examples I can look into it further, but SkyFactory 4 seems to have a few good examples of this happening.

### Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2836
JEI: 4.15.0.278

### Mods used in examples:
https://github.com/Darkhax-Minecraft/Resource-Hogs
https://github.com/KnightMiner/AnimalCrops

**Comment by KnightMiner** [comment]
Item highlighting is not a JEI feature, it's from NEI or another add-on. I'll also point out Animal Crops registers a subtype adapter, so it's on NEI/the other add-on to fix it, I've done what I can.

**Comment by justinrusso** [comment]
Huh, TIL. Not sure what's adding that in since I know we stopped using NEI...

Is the lack of a subtype adapter on ResourceHogs the probable cause for the behavior of recipe lookups in JEI?

With everything considered, I'm lead to believe this is caused by either the mods registering these items or the add-on mod doing the highlighting. I'll close this issue and report to them 👍

**Comment by KnightMiner** [comment]
Lack of a subtype adapter is most likely the reason for the weird behavior on recipe lookups, yes.

SkyFactory 4 uses More Overlays which I think adds this feature, I really doubt its the mods registering the item's fault as animal crops specifically works in both the JEI search and in the creative search, so likely a more overlays issue.
