### ISSUE TITLE
[1.12-2-4.15.0.277] crash while rendering item

### ISSUE THREAD

**Issue by kreezxil** [mezz/JustEnoughItems#1563]
A player of mine on my World of Dragons mod pack has reported that while browsing the items when they press 'U' while hovering over silverfish they get a crash.

https://pastebin.com/rswhFiPY

Upon inspection it appears that a dan200 skull, which is computercraft, or in my case CC:TWEAKED could be the issue as it is the item actually being rendered and not a silverfish.

I'll cross post there too.

**Comment by kreezxil** [comment]
also posted at https://github.com/SquidDev-CC/CC-Tweaked/issues/185

**Comment by mezz** [comment]
Thanks for the report!
I can't think of why a player skull would crash, it may be from a coremod.
Please try narrowing down which mods are involved, from what I can see it does not appear to be a JEI issue.
