### ISSUE TITLE
Change save location of Bookmarks.ini (bookmark save file)

### ISSUE THREAD

**Issue by LezChap** [mezz/JustEnoughItems#1564]
There's debate in other requests on whether bookmarks should exist per world, or be account-wide.  The decision on that MAY influence where you move the file's save location (within the World/Save folder, or the main MC directory like JourneyMap or Prestige's data), but is beyond the scope of my actual request.

My request?  Move the Bookmarks.ini file's save location SOMEWHERE outside the config folder.  When updating modpacks, this can result in the bookmarks file being erased.  Even if updated manually into a new instance, finding a file in the config folder to move over to a new MultiMC instance is a bit counter-intuitive.

Thanks!

**Comment by mezz** [comment]
Thanks for the report!
I think it makes sense to make it tied to the world.

**Comment by LezChap** [comment]
I could see making it carry over between worlds make sense also...For example, I'm looking at building some multiblock or other complex structure in my survival world, but I want to test it first...I favorite everything I use in the build in my test world, then move back in the survival world to actually build it.

**Comment by choekstr** [comment]
99.9999% of the people get their jei bookmarks overwritten by some useless items the packdev had in their config while testing, but that infinitesimally small amount of people that want to use the same bookmarks on a new world can copy over their config from another save folder. 

The way it is now, it's a permanent overwrite every pack update.
The proposed way would never overwrite and you can copy over from another world/save folder if needed. 

This should be a no brainer, why is there even a question on how this should be implemented?

**Comment by mezz** [comment]
Bookmark configs will now be stored in a nested folder.
For example, in my local test world they are in:
`/config/jei/world/local/testworld/bookmarks.ini`

If you want to keep bookmarks across worlds, you can copy-paste them from one world folder to another.

This structure should prevent the configs from being overwritten by pack devs, as long as their world name or server info is different from yours.

**Comment by Eric-01** [comment]
@mezz Couldn't JEI use the standard location where the vast majority of today's Forge mods save their world/server-specific configurations — at `~/.minecraft/saves/<the_world_name>/serverconfig` instead?

**Comment by mezz** [comment]
> @mezz Couldn't JEI use the standard location where the vast majority of today's Forge mods save their world/server-specific configurations — at `~/.minecraft/saves/<the_world_name>/serverconfig` instead?

I thought that this directory was only intended for configs synced from the server to the client, but if it's more widely used then I can take a look and see if this can work for these configs.

**Comment by mezz** [comment]
Yeah unfortunately it looks like this type of config is meant to be set on the server, and then it is synced to the client. 
That will not work for per-world configs that are set by the client.

Please let me know if you have a modded example of it working the way we need here and I can take another look.

**Comment by Eric-01** [comment]
Okay, so it seems that I misunderstood your intentions here. From what I understood, the author of this issue just wanted per-world/per-server JEI configurations, so I thought that configs enforced by the dedicated/internal server should suit their needs as well.
