### ISSUE TITLE
[1.12.2] [suggestion] Show hidden Items in Recipes

### ISSUE THREAD

**Issue by ToMe25** [mezz/JustEnoughItems#1567]
If someone uses a Item in a Recipe that is in no Creative Tab or hidden JEI displays an empty Slot, i think this shouldn't be the case.

**Comment by ToMe25** [comment]
By the Way Items being in no Creative Tab got rendered in Recipes in 1.10/1.11 so i think maybe it's a Bug that they don't render with JEI 1.12.2.

**Comment by mezz** [comment]
Thanks for the report!
In most cases, recipes should show hidden items. 
If there are a list of items for one slot, some are hidden and some are not, then only the unhidden items are shown. I believe that is the only case where items are hidden in recipes.
Do you have some other bug where an item is not rendering?

**Comment by ToMe25** [comment]
The Main Case i had was with Thermal Foundation.
Thermal Foundation adds some Tools(for example the Wooden Excavator) but don't adds them to a Creative Tab with Default Config and don't adds Recipes for them.
My Mod [Armor&ToolUpgrading](https://minecraft.curseforge.com/projects/armor-tool-upgrading) adds Recipes using that Tools and than the Tools aren't rendered in the Recipe.

I had that too with only Mods from other Persons but i don't know what Mods i used so i can't report that.

**Comment by ToMe25** [comment]
For Example Armor&ToolUpgrading makes you need the Wooden Excavator for the Stone one and in that Recipe there is an empty Slot instead of the Wooden Excavator.
And you need the Stone Excavator for the Copper one(the First visible).

**Comment by mezz** [comment]
Ok, interestingly this has the same underlying issue as https://github.com/mezz/JustEnoughItems/issues/1575, please take a look at my response there.
I will see if there is something I can do to display those items in recipes better.

**Comment by ToMe25** [comment]
I know i could add the Items to a Creative Tab or enable in the Thermal Foundation Config to add them to a Creative tab but i want it to work with the default Config and it's a Bug even if you can work around it.
I figured that out during testing before reporting.

**Comment by mezz** [comment]
I have pushed a "fix" for this where it will at least display something instead of a blank spot.
It is not entirely perfect because if there are multiple subtypes, JEI will just display the first one, but it should resolve this issue.

I tested with your mod and it seems to be displaying things properly.

**Comment by ToMe25** [comment]
ok thanks :)
