### ISSUE TITLE
JEI doesn't appear sometimes (Sponge on client)

### ISSUE THREAD

**Issue by gizmocodes** [mezz/JustEnoughItems#157]
Even when toggling JEI with Ctrl + O, when logging into a server and opening the inventory JEI doesn't appear. It throws no errors or anything.

I've managed to only get it to appear by logging off, going to single player, Ctrl + O and going to gamemode 1, switching back to survival and then Ctrl + O again. Then when heading back to multiplayer it appears. Its a crappy solution but it works.

**Comment by TehNut** [comment]
What version? This was recently fixed for Vanilla servers.

**Comment by gizmocodes** [comment]
2.25.3.131. Its a modded server, however.

**Comment by Prospector** [comment]
This happened to out server a while back. We updated some mods (but not JEI) and it suddenly it was gone. We updated JEI and it was fixed.

**Comment by mezz** [comment]
Thanks for the report!
Is the server spigot/kcauldron or something else like that?

**Comment by gizmocodes** [comment]
None of the above. Its running SpongePowered, primarily because me, and the owner, think its better than both KCauldron or Spigot/Bukkit.

**Comment by JoeSchmo2840** [comment]
GizmoCodes, the issue was having sponge installed client side. This issue was not with JEI but with sponge at the moment. However sponge will be a client side api in the distant future. So he can address that when the time comes.

**Comment by mezz** [comment]
It seems this can be resolved by removing sponge from the client-side.

**Comment by DarkArc** [comment]
Update Sponge to the latest build http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/1.8.9-1890-4.1.0-BETA-1320/spongeforge-1.8.9-1890-4.1.0-BETA-1320.jar

I'm not 100% sure what change fixed the issue, but it no longer seems to be an issue with this build in the client.
