### ISSUE TITLE
Random GUI overlays with red indicators on places they shouldn’t be. After updating the mod

### ISSUE THREAD

**Issue by SirAron111** [mezz/JustEnoughItems#1570]
Random GUI overlays with red indicators on places they shouldn’t be. After updating the mod here is some pictures
![2019-05-02_23 53 46](https://user-images.githubusercontent.com/39855956/57145528-aec97780-6dc3-11e9-8279-4620aa814912.png)
![2019-05-03_16 39 11](https://user-images.githubusercontent.com/39855956/57145535-b1c46800-6dc3-11e9-9243-c10c8533c8d6.png)
![unknown](https://user-images.githubusercontent.com/39855956/57145583-cdc80980-6dc3-11e9-8006-4de5abc65dd6.png)
is this intended? since the new updates?

**Comment by KnightMiner** [comment]
That is not a JEI bug/feature, [its from the Quark client module](https://quark.vazkii.net/#module-client). It highlights slots you cannot put the item in

**Comment by SirAron111** [comment]
a ok thx i tought it was jei since i updated this mod just a second before XD
