### ISSUE TITLE
JEI and embers rekindled Bug

### ISSUE THREAD

**Issue by SirAron111** [mezz/JustEnoughItems#1571]
Problem with JEI and Embers Rekindled is there no way to turn of the Stamper Renaming recipes they are confusing my Modpack players so much literally every item can be renamed and this shows as a recipe on every item making it super confusing as everyone starts to think they need a stamper to make everything. Could also be something with soot as the inscription stamp comes from there?

**Comment by SirAron111** [comment]
https://github.com/DaedalusGame/Soot/issues/91

**Comment by DaedalusGame** [comment]
on Soot's side, close please
