### ISSUE TITLE
[Crash] On Startup

### ISSUE THREAD

**Issue by ScienceDrummer** [mezz/JustEnoughItems#1573]
I seem to get a crash with this mod according to VanillaFix but I have a feeling it's another mod causing it. If this is the case, could you point me in the right direction?

Crash: https://paste.dimdev.org/acuqebizaq.mccrash

**Comment by TehNut** [comment]
#1189

**Comment by ScienceDrummer** [comment]
Weird, I haven't gotten the crash at all until recently. Might have an idea of which mod is causing it.

**Comment by ScienceDrummer** [comment]
I took out FastWorkbench and it seemed to load up fine. Maybe it's a problem between JEI, Fast, and Liteloader?

**Comment by bs2609** [comment]
https://github.com/mezz/JustEnoughItems/issues/1189#issuecomment-453878592

**Comment by ScienceDrummer** [comment]
Guess I won't have FastWorkbench then.
