### ISSUE TITLE
Crash using @open

### ISSUE THREAD

**Issue by Zarpyk** [mezz/JustEnoughItems#1574]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

Crash log: https://paste.dimdev.org/hapocacepi.mccrash
I put "@open" in the search area and it crash, and now I can't open inventory

And the UI is bug: 
![Captura](https://user-images.githubusercontent.com/30746531/57320628-988f2480-70ff-11e9-8d53-766845292e13.PNG)

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
  Ingredient Mod: OpenBlocks
  Ingredient Info: 1xitem.openblocks.glyph@32 openblocks:glyph
```
This is an issue with OpenBlocks, caused by Optifine. You can subscribe to the Optifine issue here: https://github.com/sp614x/optifine/issues/2267
