### ISSUE TITLE
Mushroom blocks not showing as ingredients

### ISSUE THREAD

**Issue by LemADEC** [mezz/JustEnoughItems#1575]
As of jei_1.12.2-4.15.0.278, Brown and Red mushroom blocks are visible in the full list and won't render recipe ingredients.
For example, this is a valid crafting recipe:
![image](https://user-images.githubusercontent.com/4776032/57447889-68a76480-7258-11e9-8fa6-573329854b3c.png)
but JEI don't render the ingredient in that recipe:
![image](https://user-images.githubusercontent.com/4776032/57447908-7bba3480-7258-11e9-98e5-e9ea911ac4d9.png)
(there's no item showing in the center, not even a tooltip)

Issue was reproduced in dev space.
Recipe is implemented using the original ShapedOreRecipe.

**Comment by LemADEC** [comment]
Issue isn't reproduced when mushroom blocks are added through ore dictionary.

**Comment by mezz** [comment]
Thanks for the report!
How strange.

**Comment by mezz** [comment]
I tested this out with a debugger to see what's happening.
When you create a ShapedOreRecipe with a Block ingredient, it gets put there with wildcard metadata.

See `net.minecraftforge.common.crafting.CraftingHelper#getIngredient(java.lang.Object)`

The mushroom block does not a creative menu item, so the resulting ingredient's `matchingStacksExploded` is empty. 
(see the case for `OreDictionary.WILDCARD_VALUE` in `net.minecraft.item.crafting.Ingredient#Ingredient(net.minecraft.item.ItemStack...)`)

To work around this issue you can use the ore dictionary or add them to the creative menu.
Both solutions should let your recipe work with the vanilla recipe book too.

**Comment by LemADEC** [comment]
Looks good to me, thanks!

**Comment by mezz** [comment]
I have pushed a "fix" for this where it will at least display something instead of a blank spot.
It is not entirely perfect because if there are multiple subtypes, JEI will just display the first one, but it should resolve this issue.
