### ISSUE TITLE
craft tweaker integration

### ISSUE THREAD

**Issue by tiarnia** [mezz/JustEnoughItems#158]
can it read craft tweaker recipes i know that NEI used to show the recipe right away after reloading the scripts this would be helpful as now i have to tell each player the recipes for anything i change

**Comment by mezz** [comment]
Thanks for the report!
I think this is an issue for Craft Tweaker. JEI can be "reset" by a mod if they change something in-game, so maybe they just need to tell each client's JEI to reset.
You can report the issue here: https://github.com/jaredlll08/CraftTweaker/issues
