### ISSUE TITLE
I cannot figure out how to use the new IModRegistry.addIngredientInfo() 

### ISSUE THREAD

**Issue by cj3636** [mezz/JustEnoughItems#1589]
The previous way I was using the method was:
`registry.addIngredientInfo(new ItemStack(ModItems.MYITEM), ItemRegistry.class, TextFormatting.LIGHT_PURPLE + "DESCRIPTION");`

It is now deprecated and requires `IIngredientType`. 

I cannot figure out how to use it for the life of me.
I am only trying to add it to items in my mod that are an extension of Item.class so I shouldn't have to make a new ingredient type, correct?

**Comment by TehNut** [comment]
https://github.com/mezz/JustEnoughItems/blob/a9e1fb9fe05a53e85fa7caf470ac30f226fae636/src/api/java/mezz/jei/api/constants/VanillaTypes.java#L12

**Comment by cj3636** [comment]
> https://github.com/mezz/JustEnoughItems/blob/a9e1fb9fe05a53e85fa7caf470ac30f226fae636/src/api/java/mezz/jei/api/constants/VanillaTypes.java#L12

Thank you for this.
