### ISSUE TITLE
Request: Server-Controlled config option to allow deleting of items even if cheat mode is disabled.

### ISSUE THREAD

**Issue by Entoarox** [mezz/JustEnoughItems#159]
As the title says, I would like to be able to allow my players to delete junk items easily, and allowing them access to JEI deletion would be perfect for this.

**Comment by mezz** [comment]
I strongly recommend [Trash Slot](http://www.curse.com/mc-mods/minecraft/235577-trashslot), it is a lot safer than deleting in JEI if you don't have creative.

**Comment by TehNut** [comment]
I second mezz's recommendation. If you accidentally delete something with JEI, it's gone for good. TrashSlot stores the item in it's slot until you overwrite it with a new item or logout.

**Comment by Entoarox** [comment]
@mezz The last time I tried trash slot it severely messed up any mods that interacted with the player inventory directly, so I actually removed it from my 1.7 pack for that reason, is the 1.8 version better in that regard?

**Comment by mezz** [comment]
I haven't had any issues yet, but I have found Inventory Tweaks to be very buggy (some hotkeys even crash) in 1.8 so I use cpw's much simpler [Inventory Sorter](http://minecraft.curseforge.com/projects/inventory-sorter) instead. 

You should definitely test it out, I spend much more time coding than playing, but I haven't seen or heard anything negative. [Make sure to report any issues](https://github.com/blay09/TrashSlot/issues), the mod author is pretty active.

**Comment by Entoarox** [comment]
@mezz Ok then, I will try it out and hope for the best! :)
