### ISSUE TITLE
Jei buttons not working as intended

### ISSUE THREAD

**Issue by AnkaraSoulreaver** [mezz/JustEnoughItems#1590]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by AnkaraSoulreaver** [comment]
I am finding the JEI search and crafting buttons not working as intended.  I am playing on the Direwolf20 1.12 modpack from FTB.  The pack is up to date and otherwise functioning normally.

Circumstances, I was trying to evaluate what items contain Instrumentum so that was the last search I completed.  In my example screen shots:

Image 1, I search for a simple recipe crafting table.  This works initially.
![image](https://user-images.githubusercontent.com/33983960/58922359-84434500-8708-11e9-83cd-9489b8b4aa4c.png)

Image 2, I press the + to push the pattern into a crafting station and JEI reverts to Instrumentum.
![image](https://user-images.githubusercontent.com/33983960/58922370-8d341680-8708-11e9-90f3-79366f3ded69.png)

Image 3, I right-click Oak planks to display craft recipes using that item.  Initially this works as intended.
![image](https://user-images.githubusercontent.com/33983960/58922382-9624e800-8708-11e9-96e2-ec6f561aa357.png)

Image 4, I press the "go forward 1 page to display page 2 of crafting table recipes" button and JEI reverts to Instrumentum.
![image](https://user-images.githubusercontent.com/33983960/58922390-9f15b980-8708-11e9-9aa5-b9c27d1c153e.png)

I started this pack less than a week ago and this has not worked since I started the issue.  I was hoping for an update but one has not yet presented.

Please advise.

**Comment by mezz** [comment]
Thanks for the report!
Surprisingly, I've never seen a bug like this before.
Have you modified the pack in any way (added, updated, or removed mods)?
Try removing Thaumic JEI to see if it resolves the issue. I believe it's the plugin that adds the Instrumentum recipe.

**Comment by AnkaraSoulreaver** [comment]
I have not modified the pack in any way.  I am playing FTB Presents
Direwolf20 version 2.5.0 "out of the box".  The only thing I've done is
tinker with the video settings, which I believe to be client side only, to
ensure my mouse was accurately selecting the buttons as intended.

Additionally I do not think it's related to Thaumic JEI as it occurs with
other recipes as well.  This just happened to be what I was doing before I
took screenshots.  In fact I've been struggling with this since I started
the pack and just been pushed to submit the report because I just got into
Thaum and it's making it pretty much impossible to proceed.  If you still
feel that Thaumic JEI is the culprit I will make the attempt, but I'm not
expecting this to be a solution.

Image 1, I right-click glass to evaluate recipes containing glass.
[image: image.png]

Image 2, I page forward on glass crafting recipes and it goes to this page,
which doesn't entirely make sense.
[image: image.png]

**Comment by AnkaraSoulreaver** [comment]
I've now tested by removing ThaumicJEI.  No change other than Thaumic recipes now do not show in JEI.  Bug is still present.

**Comment by mezz** [comment]
I downloaded a fresh copy of FTB Presents
Direwolf20 version 2.5.0 and I'm not seeing the same problem. Clicking the `+` puts items into the crafting area like normal.

![2019-06-06_22 30 20](https://user-images.githubusercontent.com/916092/59083088-c6a48780-88aa-11e9-8f11-c3fe45ea8a71.png)

Which crafting table are you using? Maybe if you are using a modded crafting table, that mod is causing an issue.

**Comment by AnkaraSoulreaver** [comment]
I'm using the crafting station (recraft the crafting table) but this occurs even when I'm just searching JEI away from the crafting table as well.  I suppose I may just need to reinstall the pack.  I need to figure out how to do that and preserve my world.

**Comment by AnkaraSoulreaver** [comment]
Ok, confirmed.  I reinstalled the entire pack and reinstalled my save file and it's fixed.  So apparently it's not a JEI bug per se, but a corruption in my copy of the pack.

Resolved :)  Thank you!

**Comment by mezz** [comment]
Ok good to hear! What a strange bug.
