### ISSUE TITLE
Frame rate drop makes game unplayable

### ISSUE THREAD

**Issue by TheQuadShot** [mezz/JustEnoughItems#1595]
jei_1.12.2-4.15.0.268
forge-14.23.5.2838

Mod List
https://pastebin.com/RT9gtjNJ

Latest Log
https://pastebin.com/SLgnf8XQ

Video (about 10 seconds)
https://www.youtube.com/watch?v=VdFBtYFwzvE&feature=youtu.be

This vid is with just JEI loaded ie none of the plug-ins added. The game is just fine as long as I don't enable JEI.
If you need anything else just let me know.
edit: sorry forgot version numbers

**Comment by Ommina** [comment]
While I make no promises, that _looks_ like garbage collection on the client.

You're presently allocating 3GB, which feels a bit light for 1.12.  Giving the client an additional GB or two would be an easy (potential) solution to try.

**Comment by TheQuadShot** [comment]
Thanks and sorry for the report. It didn't make sense to me how your mod could do this, anyway I doubled the allocation and it seems to be fine. Thanks for a Great Mod and all of your hard work!
