### ISSUE TITLE
Suggestion: Option to enable hidden items to show in creative mode.

### ISSUE THREAD

**Issue by SirAron111** [mezz/JustEnoughItems#1597]
I hide a lot of useless or not craftable etc items in my Modpack with the hide function to reduce the pages of JEI from 200 to 100 basically and help the players only seeing items they can craft and need. But since some update the Creative menu seems to be linked and I can’t for example grab the hidden items out of the creative menu when I am an admin or op player. Is it possible to ad an option to say when players are in creative mode they can see all items even hidden ones? Especially in the normal creative menu with the tabs! I can’t always reenable for example all mob spawn eggs to show if I want to grab a specific mob for testing or to spawn them for a player.

**Comment by mezz** [comment]
Thanks for the report!
The creative menu should not be linked to changes in JEI. The hide function in JEI should only hide items from JEI. Are you hiding them using CraftTweaker or something else?

**Comment by SirAron111** [comment]
Nop just hide them using JEI own function to hide them the one under the option to enable cheat mode

**Comment by bs2609** [comment]
Please provide a modlist, as I *strongly suspect* this is nothing to do with JEI itself.

To be sure, can you reproduce this with vanilla items with only JEI installed?

**Comment by SirAron111** [comment]
It did happen with vanilla and just JEI and hiding for example spawn eggs. But if you need a mod list the list is here https://minecraft.curseforge.com/projects/dimension-zero on the very bottom
