### ISSUE TITLE
1.14.2 - Buttons not working

### ISSUE THREAD

**Issue by Dazzah** [mezz/JustEnoughItems#1600]
jei-1.14.2-6.0.0.2.jar
Not sure if you wanted this reported as it is for the current Alpha version. I thought it better to mention rather than you not know at all.

The Wrench button to access the settings menu does not work.

**Comment by mezz** [comment]
Thanks for the report!
This is a known bug, you can read more here: https://github.com/mezz/JustEnoughItems/issues/1526
