### ISSUE TITLE
1.12.2 v4.15.0.283 - Crash when loading splash screen

### ISSUE THREAD

**Issue by PolarStar64** [mezz/JustEnoughItems#1601]
When I try to load into MC, it crashes the second it tries to load into the menu.

https://gist.github.com/PolarStar64/928de230ea7980068a6f2f7d969bc551

**Comment by mezz** [comment]
Thanks for the report!
This is a known issue with LiteLoader. Unfortunately they have not been around to fix it for a long time.
You can read more here: https://github.com/mezz/JustEnoughItems/issues/1189
