### ISSUE TITLE
1.14.2 - Vanilla RecipeTransferHandler transferring incorrect recipes

### ISSUE THREAD

**Issue by p455w0rd** [mezz/JustEnoughItems#1602]
![gif](https://puu.sh/DK5Fc/0295beb79b.gif)
Only happens when multiple use recipes are available (if you specifically look up stone sword, the transfer functions correctly)
These recipes are also overridden vanilla recipes where I replaced the sticks of stone tool recipes with the forge `rods/wooden` tag which I also added my sticks to in order to mimick <=1.12 OreDict functionality

Also, this is SMP

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the latest release, available shortly.
