### ISSUE TITLE
1.14.2 JEI Not appearing

### ISSUE THREAD

**Issue by VampireSultana** [mezz/JustEnoughItems#1605]
My launcher detects the mod, but it's not showing up in my worlds for some reason. It's just not there. Is there something I need to do to get it to appear?

**Comment by Darkhax** [comment]
I am running into the same issue with version 6.0.0.2 in a dev environment.

**Comment by mezz** [comment]
Thanks for the report!
Make sure you have the latest Forge, 6.0.0.2 is built against a really recent version (latest from yesterday).
Let me know if you still see the issue.

**Comment by lmeta** [comment]
I am still having the issue. I have everything updated and my friends playing on my server can see the mod.. Just not me. Maybe i did something wrong??

**Comment by VampireSultana** [comment]
> Thanks for the report!
> Make sure you have the latest Forge, 6.0.0.2 is built against a really recent version (latest from yesterday).
> Let me know if you still see the issue.

I upgraded to the latest forge, and I can now see the items! Unfortunately, I cannot click on the items and place them into my inventory on survival. I can only do this on Creative, but since this is a new problem, I opened a new issue, unless this is intentional?

**Comment by mezz** [comment]
The issue with cheating-in items has been reported here: https://github.com/mezz/JustEnoughItems/issues/1603
and it is fixed today in the latest version.
