### ISSUE TITLE
Download page

### ISSUE THREAD

**Issue by FormSans** [mezz/JustEnoughItems#1606]
I have been waiting for at least the 1.13 update come but on the Curse mod page, it ONLY has 1.12 on there. Is the 1.12 meant to work with the later versions or what is happening? I am severely confused.

Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by TehNut** [comment]
What? There's a download for 1.13 [here](https://minecraft.curseforge.com/projects/jei/files/2724419) and one for 1.14 [here](https://minecraft.curseforge.com/projects/jei/files/2728986)

**Comment by bs2609** [comment]
AFAIK, alpha versions aren't synced to Curse. You're probably better off just using [CurseForge](https://minecraft.curseforge.com/mc-mods) instead.

**Comment by mezz** [comment]
Thanks for the report!
This should hopefully be less confusing with the Curse site redesign.
You can see all the JEI versions here: https://www.curseforge.com/minecraft/mc-mods/jei/files/all
