### ISSUE TITLE
Showing Invalid Uses for Items (Extra Planets)

### ISSUE THREAD

**Issue by Danekjovax** [mezz/JustEnoughItems#1608]
I'm playing v 5.2 of Dungeons Dragons & Space Shuttles, using jei_1.12.2-4.15.0.268.

I've already posted this bug with both the modpack owner and the mod owner (see GitHub references below).
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/193
https://github.com/MJRLegends/ExtraPlanets/issues/441

In short, this issue seems to stem from JEI misrepresenting the uses of certain items.  The only specific example I can bring at this time is spacesuits from Extra Planets.  The Mod owner claims this is not a valid use for the space suit components and that JEI is the source of the issue.

If there is an easy way to get JEI to unregister these uses for these suits, that would resolve this issue.  Thanks.

Screenshots attached.
![2019-06-02_17 31 49](https://user-images.githubusercontent.com/10191173/60090957-86019680-9711-11e9-84d9-a82cbd731a48.png)
![2019-06-02_17 31 52](https://user-images.githubusercontent.com/10191173/60090964-89951d80-9711-11e9-8288-e3df6a09cea1.png)
![2019-06-02_17 29 32](https://user-images.githubusercontent.com/10191173/60090972-8e59d180-9711-11e9-9712-989b9c0dc2f5.png)

**Comment by MJRLegends** [comment]
Fyi my item class for this armour has the following which should be looked at by JEI?
 ```
	@Override

	public boolean isEnchantable(ItemStack stack) {

		return false;

	}

	@Override

	public boolean isBookEnchantable(ItemStack stack, ItemStack book) {

		return false;

	}
```

**Comment by TehNut** [comment]
I don't believe that enchantment plugin is added by JEI

**Comment by Danekjovax** [comment]
What is the JEI plugin?

**Comment by way2muchnoise** [comment]
This is added by JER, feel free to report it on [my issue tracker](https://github.com/way2muchnoise/JustEnoughResources/issues)

**Comment by mezz** [comment]
Thanks for the report!
Please open an issue for JER, linked above.
