### ISSUE TITLE
Add Ore Dictionary search and Creative Tab Name search

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#161]
JEI can search item names, tooltips, and mod names. Ore dictionary would be useful too.

**Comment by Prospector** [comment]
Oh this reminds me of a search filter idea. How about creative tab
filtering? Maybe something like !Building Blocks

**Comment by mezz** [comment]
Sure, why not?

**Comment by mezz** [comment]
I'm going down the US English keyboard for the prefixes though, so far I have `@ModName` and `#Tooltip`, so next is `$OreDict` and `%CreativeTab`

**Comment by mezz** [comment]
Ok looking good:

![2016-02-09_17 38 15](https://cloud.githubusercontent.com/assets/916092/12936521/48b770b6-cf54-11e5-997b-28c2e956c1a1.png)

![2016-02-09_17 39 09](https://cloud.githubusercontent.com/assets/916092/12936524/4b1b2d34-cf54-11e5-8b38-c1bbfd7bf0e9.png)

![2016-02-09_17 40 41](https://cloud.githubusercontent.com/assets/916092/12936525/4d4838ea-cf54-11e5-8a1c-af4c227b690e.png)

Also added config options so you can search without the prefixes if you want.
