### ISSUE TITLE
Crash on next recipe page

### ISSUE THREAD

**Issue by krejcar25** [mezz/JustEnoughItems#1611]
Game crashed when I tried to cycle the page in recipes display. In SevTech: Ages modpack, version 3.1.1, mod version 4.15.0.268. Crash report and game log in [gist](https://gist.github.com/krejcar25/f932f5e59c73082e39cffdb1fa88fc08).

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix in version 4.15.0.285
