### ISSUE TITLE
Wrong file number

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [mezz/JustEnoughItems#1613]
You uploaded jei_1.12.2-4.15.0.**268**

Should be 
jei_1.12.2-4.15.0.**286**

**Comment by Cr4fTJuNkiE** [comment]
Just an FYI

**Comment by mezz** [comment]
Thanks for the report!
The build and upload process is entirely automated, so that I can't make a typo like that.
For 1.12.2, the latest Release version is `4.15.0.268` and the latest Beta version is `4.15.0.285`.
I think it just appeared wrong because the new CurseForge layout is a bit different.

**Comment by Cr4fTJuNkiE** [comment]
Oh okay. *oops*
