### ISSUE TITLE
[1.12.2] Wrong Link

### ISSUE THREAD

**Issue by DoScripts** [mezz/JustEnoughItems#1614]
I was trying to find a mod named Just Enough Items, so I see this website. 
[https://www.curseforge.com/minecraft/mc-mods/jei]

I download it, and then I put it in the folder for mods, once again everything is set up properly I have no other difficulties running other mods. 

I open my Minecraft Launcher, launch it and then it says you have to have the most recent version, and I don't want to download the recent version just because I don't really like it. Is there any fix to it, links?

Screenshot(s):
[https://gyazo.com/5f2808fd7db78deb7d71dc2f655aa5f3]

**Comment by TehNut** [comment]
You need to update Forge

**Comment by DoScripts** [comment]
Links that I have contained in this reported letter:

https://www.curseforge.com/minecraft/mc-mods/jei

https://gyazo.com/5f2808fd7db78deb7d71dc2f655aa5f3

**Comment by DoScripts** [comment]
> You need to update Forge

How can I do it, and can you contact me on discord? 
TYLOO#0855
