### ISSUE TITLE
Despite client and server installation of JEI, Move Items button doesn't work

### ISSUE THREAD

**Issue by ThatPreston** [mezz/JustEnoughItems#1615]
Client log: https://pastebin.com/N23AXWjR
Server log: https://pastebin.com/VBTPDYsM
Mod list (client and server): https://docs.google.com/document/d/1rBoQBFB0vEVH5mkfoo7hasdZU-UHBNoYzNVaJVXa4fE/edit?usp=sharing
JEI version: 4.15.0.268

The only different between the server and client mods is that the server has Morpheus installed.

Basically, even though JEI is installed on the client and server (version 4.15.0.268) it still thinks it isn't installed on the server, which makes it so the move items button can't be used. (see picture) This is really annoying, and I have no idea why it is happening. I checked related issues on this github but they didn't have any solutions. Thanks for the help!

![example](https://user-images.githubusercontent.com/52404366/60424159-5214ee00-9bb5-11e9-8993-81a8805b1ba0.PNG)

**Comment by mezz** [comment]
Thanks for the report!
Can I see the part of the server log that is written when the server starts up? What you have linked is from later on, when a client tries to join.

**Comment by ThatPreston** [comment]
My bad, I thought that is what I sent. https://pastebin.com/DrKQNxgM
That link should be the startup log.

**Comment by ThatPreston** [comment]
Also, lately i have noticed that this only happens sometimes. Other times I join and it works fine (this is less of the time though.) Additionally, I have noticed that whether it works or not is also whether a lot of buttons such as claiming land or other things from FTBUtilities show up.

**Comment by mezz** [comment]
Unfortunately I'm not sure what is causing this.
I suspect it is a conflict with some other mod, because this never happens with JEI alone.
Please try backing up your mod pack and removing mods to see if you can figure out which mods are causing an issue here. Once you narrow it down, I can work on a fix or help you report it to that mod's author.

**Comment by mezz** [comment]
@Webber101 Please try backing up your mod pack and removing mods to see if you can figure out which mods are causing an issue here. Once you narrow it down, I can work on a fix or help you report it to that mod's author.
