### ISSUE TITLE
Conflicting Jei versions when making plugin - Forge Gradle

### ISSUE THREAD

**Issue by william-hollywood** [mezz/JustEnoughItems#1616]
I am currently trying to make my own plugin for JEI and i have setup an eclipse work space following your guide.
The problem im having is when i try and start up the client (from eclipse) the game does not start and says there are conflicting mod versions.  (At this point i have not written any code for my plugin)
how do i fix this? 
i have attached my gradle.properties, build.gradle, log report and a screenshot of the eclipse.
(I know gradle.properties, build.gradle arent meant to by .txt, ther're that for uploading purposes)

![JEI](https://user-images.githubusercontent.com/19204302/60426055-f182c100-9c47-11e9-8c28-de48f8a3c57a.PNG)

When clicking open mods folder there is also nothing there.

[latest.log](https://github.com/mezz/JustEnoughItems/files/3344855/latest.log)

[gradle.properties.txt](https://github.com/mezz/JustEnoughItems/files/3344862/gradle.properties.txt)

[build.gradle.txt](https://github.com/mezz/JustEnoughItems/files/3344863/build.gradle.txt)

**Comment by mezz** [comment]
Thanks for the report!
Please locate the 4.13.0.219 version of JEI is located and remove it from your project.
You can see some more detail in the error log:
```
[21:29:20] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.DuplicateModsFoundException: 
Duplicate Mods:
	jei : C:\Users\Will\.gradle\caches\modules-2\files-2.1\mezz.jei\jei_1.12.2\4.15.0.268\1fd0269994b2721ba110a64d8c0129448f1b985\jei_1.12.2-4.15.0.268.jar
	jei : C:\Users\Will\.gradle\caches\modules-2\files-2.1\mezz.jei\jei_1.12.2\4.13.0.219\d3695fffe71e7e491c1117bb406c36dc8f1792\jei_1.12.2-4.13.0.219.jar
```

**Comment by william-hollywood** [comment]
Fixed,
Also had to configure the build path as it was trying to include something that didn't exist anymore.
Closing thread
