### ISSUE TITLE
[1.14.3] JEI is crashing due to StartupProgressManager have been removed in FML

### ISSUE THREAD

**Issue by GirafiStudios** [mezz/JustEnoughItems#1617]
The legacy StartupProgress have been removed in Forge 27.0.17

Link to commit removing the legacy StartupProgress: https://github.com/MinecraftForge/MinecraftForge/commit/c8e5007913602b43d16e1ddcc8400e03fc58c129
Crashlog: https://gist.github.com/GirafiStudios/9f56404dfdb8f58179c8e89fbf17c2d8

**Comment by vizthex123** [comment]
I have the exact same problem!

**Comment by mezz** [comment]
Fixed in the next version (https://github.com/mezz/JustEnoughItems/issues/1619)
