### ISSUE TITLE
Crashing Due to STartupProgressManager not existing

### ISSUE THREAD

**Issue by vizthex123** [mezz/JustEnoughItems#1619]
That's what my crash is. Probably something to do with Forge being rewritten.

Crashlog: 
[crash-2019-07-01_13.17.19-client.txt](https://github.com/mezz/JustEnoughItems/files/3346863/crash-2019-07-01_13.17.19-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the next release.
