### ISSUE TITLE
Blood Magic Hellfire Forge JEI Integration Format error

### ISSUE THREAD

**Issue by Majestyc2k1** [mezz/JustEnoughItems#162]
Using Blood Magic 1.8.9-2.0.0-15 and JEI 1.8.9-2.25.7.145 (Forge 11.15.1.1736). Gives a format error for the Will values required for crafting in the recipes for the Hellfire Forge. No numerical values given.

**Comment by mezz** [comment]
Thanks for the report!
Every mod adds their own integration, so this is not a JEI issue. 
This has been reported to Blood Magic and fixed: https://github.com/WayofTime/BloodMagic/issues/599
