### ISSUE TITLE
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash : JEI

### ISSUE THREAD

**Issue by Antoinep02** [mezz/JustEnoughItems#1620]
Since yesterday i try to launch a modpack which is Ragnamod V and this appeared every time after the launcher crash here is my crash report can you help pls ? Thx
[crash-2019-07-02_12.43.30-client.txt](https://github.com/mezz/JustEnoughItems/files/3349687/crash-2019-07-02_12.43.30-client.txt)

**Comment by Tahakk** [comment]
add more RAM

**Comment by Antoinep02** [comment]
-Xmx6G -Xms1G -XX:PermSize=256m  this aint enough ?

**Comment by Tahakk** [comment]
`34: ...java.lang.OutOfMemoryError: GC overhead limit exceeded`
looks like no

**Comment by Antoinep02** [comment]
i'll try to remove JEI then

**Comment by Tahakk** [comment]
It's not only about JEI, if you are hitting memory limit any mod that is going to load at that time will give you error. 

If you want to play this pack I would recommend to increase memory limit, and if you don't have enough RAM in your system consider upgrading. 

Some packs are not just made for systems with low RAM capacity
