### ISSUE TITLE
Maven server has no 1.14.3 artefacts

### ISSUE THREAD

**Issue by cosmicdan** [mezz/JustEnoughItems#1624]
Title. Following the wiki, primary maven server returns 403 and the backup doesn't have new 1.14.3 builds.

In the meantime, if anybody else has the deobf jar, api jar and POM for 1.14.3 JEI (6.x) and could share then that'd be great (I could just manually add them for now, if the server is out for a while).

**Comment by mezz** [comment]
Thanks for the report!
progwml and I are looking into this now.
You can see the available builds here: https://dvs1.progwml6.com/files/maven/mezz/jei/jei-1.14.2/maven-metadata.xml
So for now, version 6.0.0.3 and lower should still be available.

**Comment by cosmicdan** [comment]
Nice, thanks! So the problem is just the server has gotten some stricter security settings it seems, not allowing directory listing for the maven repo.

Good luck!

**Comment by cosmicdan** [comment]
Title updated since the 403 error problem may not be a problem at all.

I see there is https://dvs1.progwml6.com/files/maven/mezz/jei/jei-1.14.3/maven-metadata.xml - is that new or has it been there a while? I haven't had a chance to test gradle dependency recently.

**Comment by mezz** [comment]
1.14.3 versions have been available for a while, it should just work.
The only issue I am aware of is that manually browsing the directory structure is not allowed.
Please let me know if you get a specific error message, I can look at the error and your build.gradle to try to help.

**Comment by Wabbit0101** [comment]
[build_gradle.zip](https://github.com/mezz/JustEnoughItems/files/3382005/build_gradle.zip)

I can confirm this still doesn't work (clicking the link manually from the jei github wiki or via build gradle). Snip of console-error-spam below for latest **1.14.3's 6.0.0.8** files: 

> Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find mezz.jei:jei-1.14.3-6.0.0.8:api.
> Searched in the following locations:
>   - file:/C:/Users/blablabla/.gradle/caches/forge_gradle/bundeled_repo/mezz/jei/jei-1.14.3-6.0.0.8/api/jei-1.14.3-6.0.0.8-a
> pi.pom
>   - file:/C:/Users/blablabla/.gradle/caches/forge_gradle/bundeled_repo/mezz/jei/jei-1.14.3-6.0.0.8/api/jei-1.14.3-6.0.0.8-a
> pi.jar
>   - https://files.minecraftforge.net/maven/mezz/jei/jei-1.14.3-6.0.0.8/api/jei-1.14.3-6.0.0.8-api.pom
>   - https://files.minecraftforge.net/maven/mezz/jei/jei-1.14.3-6.0.0.8/api/jei-1.14.3-6.0.0.8-api.jar
>   - https://libraries.minecraft.net/mezz/jei/jei-1.14.3-6.0.0.8/api/jei-1.14.3-6.0.0.8-api.jar
>   - https://repo.maven.apache.org/maven2/mezz/jei/jei-1.14.3-6.0.0.8/api/jei-1.14.3-6.0.0.8-api.pom
>   - https://repo.maven.apache.org/maven2/mezz/jei/jei-1.14.3-6.0.0.8/api/jei-1.14.3-6.0.0.8-api.jar
> Required by:

**Comment by GirafiStudios** [comment]
@Wabbit0101 according to that log file you've not specified the repository.
Look here for more information https://github.com/mezz/JustEnoughItems/wiki/Getting-Started

**Comment by Wabbit0101** [comment]
Sorry did not attach my build.gradle in original post...a snip from that file: 
```
buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        jcenter()
        mavenCentral()
        maven {
          // location of the maven that hosts JEI files
          name = "Progwml6 maven"
          url = "https://dvs1.progwml6.com/files/maven/"
        }
        maven {
          // location of a maven mirror for JEI files, as a fallback
          name = "ModMaven"
          url = "https://modmaven.k-4u.nl"
        }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.+', changing: true
    }
}
```
The meta file at https://dvs1.progwml6.com/files/maven/mezz/jei/jei-1.14.3/maven-metadata.xml is fine but gradle cannot pull the files.

**Comment by TehNut** [comment]
Repositories for project dependencies should not be listed in the `buildscript` block. That is for buildscript dependencies.

**Comment by Wabbit0101** [comment]
!@#$! aargh! you are correct!

**Comment by cosmicdan** [comment]
> Repositories for project dependencies should not be listed in the `buildscript` block. That is for buildscript dependencies.

This was the issue I had 😅 

Thank you!
