### ISSUE TITLE
[1.14.3} Server crash when pulling an item out with cheat mode - sidedness issue.

### ISSUE THREAD

**Issue by ProsperCraft** [mezz/JustEnoughItems#1625]
Crash report-
java.lang.NoClassDefFoundError: net/minecraft/client/util/InputMappings$Input

https://paste.fedoraproject.org/paste/kSx5Q-UFPEokGCcPvMsrdA

jei-1.14.3-6.0.0.7
forge-1.14.3-27.0.24

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in jei-1.14.3-6.0.0.8
