### ISSUE TITLE
JEI Crash

### ISSUE THREAD

**Issue by Executez** [mezz/JustEnoughItems#1628]
So my mc's been crashing while i was trying to load it while using JEI and here is the crash report

https://gist.github.com/Executez/1d000ba138890c633e7a490ce732d478

**Comment by mezz** [comment]
Thanks for the report!
`LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)`
Please report this issue to NEI here: https://github.com/TheCBProject/NotEnoughItems/issues
