### ISSUE TITLE
Jei cheat mode crashing server

### ISSUE THREAD

**Issue by emma2195** [mezz/JustEnoughItems#1630]
My friend and i made a server with jei but when ever we try to use cheat mode it crashes the server!

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your server crash log to https://gist.github.com and link it here.

**Comment by CrossedRhombus1** [comment]
Same happening to me, here's the log https://gist.github.com/CrossedRhombus1/41257c0c493bda8777b0c08fe3403b1e

**Comment by ProsperCraft** [comment]
I suspect this was related to my issue - https://github.com/mezz/JustEnoughItems/issues/1625

I bet if you update and test again it will no longer happen.
