### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by marcus-sparrow** [mezz/JustEnoughItems#1633]
Currently unable to run the current version of JEI with forge-1.14.3-27.0.25-installer.jar alongside Mine and Slash (Mine+and+Slash-1.14.3-2.0.18.jar), and curios (curios-FORGE-1.14.3-0.14.jar) .

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/progress/StartupProgressManager

[crash-2019-07-10_21.35.11-client.txt](https://github.com/mezz/JustEnoughItems/files/3377233/crash-2019-07-10_21.35.11-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
I think this has been fixed already, please use the latest version of JEI and see if that fixes the issue.

**Comment by marcus-sparrow** [comment]
The version on curseforge only works for 1.12.2, not 1.14.3.

**Comment by Ommina** [comment]
CurseForge's recent reorganization appears to be causing confusion in many.  On their "Files" tab, you should see the 1.14.3 link in the right hand panel.  Failing that, click the "View All" UI element, so Alpha releases are displayed in the All Files list.

**Comment by marcus-sparrow** [comment]
Thanks
