### ISSUE TITLE
[1.12.2] Bookmark icon hover re-colour causing seeming state leak

### ISSUE THREAD

**Issue by noobanidus** [mezz/JustEnoughItems#1635]
Forge: 2838
JEI: 4.15.0.285

Unfortunately when hovering over the Bookmarks button there appears to be a state leak from the recolouring of the icon to yellow that results in the GUIs of Arcane Archives (well, two of them) to render improperly:

![](https://i.imgur.com/ajRRDGj.gif)
![](https://i.imgur.com/ySmwiPO.gif)

I don't believe that this is a code issue with [our Chest GUI (link)(https://github.com/AranaiRa/ArcaneArchives/blob/master/src/main/java/com/aranaira/arcanearchives/client/gui/GUIRadiantChest.java) or [our Upgrades GUI (link)](https://github.com/AranaiRa/ArcaneArchives/blob/master/src/main/java/com/aranaira/arcanearchives/client/gui/GUIUpgrades.java) but of course, I could be mistaken.

I have yet to experiment with a solution on our side but I imagine it would be as simple matter as resetting the colour in the GlStateManager. However, I don't feel as though it's something that should be implemented on our side.

This happens both in a testing pack setting as well as (although the last time I checked was about a month ago) in a dev environment, leading me to believe that it's not an interaction from some other mod that's causing issues.

I'm not sure what there is specifically about our GUIs that makes them susceptible to this (as opposed to any other GUI), outside of the fact that ours are considerably more colourful by default.

**Comment by mezz** [comment]
Thanks for the report!
I think most GUIs start with a defensive call to reset the color (which is why I didn't see it before), but that is no excuse for JEI to leak the GL color state. I'll submit a fix soon.

**Comment by noobanidus** [comment]
Yeah, it's probably worth performing that defensively in our own GUIs, considering I've had enough issues with state leaks in the past. Being quite new to all of this is definitely making it interesting!
