### ISSUE TITLE
Odd behavior 

### ISSUE THREAD

**Issue by Notlucky101** [mezz/JustEnoughItems#1636]
jei_1.12.2-4.15.0.287
Forge 14.23.5.2838

Recipes show on crafting table, or just show crafting recipe.
Enderio Powered Crafters, logistics pipes requesting table I get this odd behavior
![2019-07-12_09 13 38](https://user-images.githubusercontent.com/42447191/61142760-6befe400-a485-11e9-9232-b8727358f792.png)

What is going on?
It was working and now its not. 
did  not add anything or change anything to the config, mods.etc

**Comment by mezz** [comment]
Thanks for the report!
This is a feature that lets you place items from JEI into a filter.
EnderIO and Logistics Pipes use this feature to allow you set filters using items you do not have in your inventory.

Sorry it is not intuitive, please let me know if you have ideas for how to make this more clear.

**Comment by Notlucky101** [comment]
have three set of button on top
1] Items mode
2] Recipe mode
3] Filter mode
4] help

**Comment by Notlucky101** [comment]
Yes I agree, works fine for logistics item filters, however I need the recipe to show not the resulting item, 
for example the new Lp request table displays the recipe and then in i click on the add button it will tell me what I am missing, so it is need to have the recipes show on both enderio and lp tables.

**Comment by Notlucky101** [comment]
Replied
