### ISSUE TITLE
[1.14.3] Recipe of uncraftable tipped arrow is shown

### ISSUE THREAD

**Issue by Snownee** [mezz/JustEnoughItems#1637]
![image](https://user-images.githubusercontent.com/16059084/61307005-18ccb700-a820-11e9-9a2a-d24699f2ec70.png)

**Comment by Snownee** [comment]
Can confirm this bug on 1.15.2

**Comment by mezz** [comment]
I think this has been fixed, does this bug still exist in 1.16 and 1.17?
If so, can you please leave steps to take to find this recipe?

**Comment by Snownee** [comment]
I think it has been fixed
