### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MagiENG** [mezz/JustEnoughItems#1638]
hi im getting a crash report on a modpack of jei im creating i am using the latest version of jei every time i launch minecraft it crashes when i removed it worked completly fine i added it back to get an log file 
[latest.log](https://github.com/mezz/JustEnoughItems/files/3398482/latest.log)

**Comment by mezz** [comment]
Thanks for the report!
From the log: 
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)
```

Please report this to CTM here: https://github.com/Chisel-Team/ConnectedTexturesMod/issues
