### ISSUE TITLE
Show Descriptions RecipeCategory last

### ISSUE THREAD

**Issue by P3pp3rF1y** [mezz/JustEnoughItems#164]
Would it be possible to add some way to set a priority at which a category that I am adding with my mod is coming up on left click?

I am using the description category for all the items and blocks and for those that are crafted in vanilla table it works well. But there are items that require custom crafting handler and the custom categories I have for those have "lower priority" than description category (or rather have higher index) so the description is the first thing that always comes up for those, when in most cases players would rather want to see how to craft those first.

I guess in my case even a simple sorting of the description category to the end of the list would work.

**Comment by TehNut** [comment]
This was discussed in #134

**Comment by P3pp3rF1y** [comment]
I guess it was partially, but not in relation to description category. 

After reading that one I agree that priorities are not a great idea, but I would still argue that descriptions should have the lowest as in most cases players would want to see recipe rather than description.

Otherwise if players of my mod find it annoying the only two options I see are
- just don't have descriptions for items in question
- or copy paste the description code to my mod and register "my custom" descriptions after the other categories

**Comment by mezz** [comment]
I can make sure descriptions load last, I already have special handling to make sure vanilla crafting loads first.
