### ISSUE TITLE
Crash with other mods

### ISSUE THREAD

**Issue by dianity** [mezz/JustEnoughItems#1640]
Im getting this crash and i dont know how to fix it the game launched when removed jei from the list. 
[crash-2019-07-19_18.11.01-client.txt](https://github.com/mezz/JustEnoughItems/files/3412985/crash-2019-07-19_18.11.01-client.txt)

**Comment by Ommina** [comment]
**Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded**

You're running out of allocated memory.  You're giving it 3GB, but for the number of mods you have, allocating five or six GB would not be inappropriate.

**Comment by dianity** [comment]
> **Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded**
> 
> You're running out of allocated memory. You're giving it 3GB, but for the number of mods you have, allocating five or six GB would not be inappropriate.

how can i increase the memory given

**Comment by Ommina** [comment]
_How_ will vary with whatever launcher you're using.

**Comment by dianity** [comment]
> _How_ will vary with whatever launcher you're using.

sorry i just got internet back im using the twitch app to combine the mod pack

**Comment by dianity** [comment]
[crash-2019-07-22_23.03.36-server.txt](https://github.com/mezz/JustEnoughItems/files/3420185/crash-2019-07-22_23.03.36-server.txt)
ok so ive gotten the game to launch using foam fix but now it crashes whenever i try to enter a world

**Comment by Ommina** [comment]
Not at all related to JEI.

Seems to be "Mystical Mod".  Their CurseForge entry has an (empty) issues page.  The crash should be reported to them there.
