### ISSUE TITLE
JEI crash with new Brewing System from Forge Build 27.0.58

### ISSUE THREAD

**Issue by SinobinU** [mezz/JustEnoughItems#1641]
Since Forge 27.0.58 is Brewing Methode:
from:
ItemStack, Ingredient, ItemStack
to: 
Ingredient, Ingredient, ItemStack

Result: Crash

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the latest version.

**Comment by Shadder-1-5** [comment]
has not been fixed here are crash files

[crash-2019-08-08_18.18.54-client.txt](https://github.com/mezz/JustEnoughItems/files/3484288/crash-2019-08-08_18.18.54-client.txt)

**Comment by mezz** [comment]
@Shadder-1-5 	thanks, that is a different crash reported here: https://github.com/mezz/JustEnoughItems/issues/1663
