### ISSUE TITLE
JEI isn't appearing in modpacks

### ISSUE THREAD

**Issue by clear0000** [mezz/JustEnoughItems#1642]
It shows in the modlist, but the disable button is greyed out. I can't enable it.

Ctrl + O doesn't work. Neither does installing a new version of it in my save. It's happened in several modpacks, notably Skyfactory 2 and Omnifactory off the twitch app. 

Thanks

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
