### ISSUE TITLE
JEI Crafting Table recipies show duplicated amount of Items in one crafting slot

### ISSUE THREAD

**Issue by MrLuxALot** [mezz/JustEnoughItems#1643]
I wanted to do Autocrafting with Refined Storage and did Crafting Table Recipies. This showed up in JEI:
http://prntscr.com/ohrf2o
http://prntscr.com/ohrf59
Wouldnt be a problem, but the Crafting Manager now says that you need 14 Iron for the *Crafting Table* recipe
Cant fix it by manually putting everthing in place

**Comment by Darkere** [comment]
The bug will get fixed in the RS release today. 

That will NOT fix the recipes for you. Sometimes restarting the game/server can fix it.
Otherwise, I made a short video on how to abuse the bug to fix it.
https://gfycat.com/jealousseriousleech

**Comment by mezz** [comment]
Thanks for the report!
Here's a link to the RS issue: https://github.com/raoulvdberge/refinedstorage/issues/2289
