### ISSUE TITLE
Jei shows leather as the repair material for an elytra

### ISSUE THREAD

**Issue by Tfarcenim** [mezz/JustEnoughItems#1644]
Jei shows leather as the repair material for elytra when it is in fact phantom membrane.

Can be reproduced with only forge and Jei 1.14.3
![2019-07-22_01-36-37](https://user-images.githubusercontent.com/44327798/61609060-e4dc0200-ac22-11e9-83d5-5276068a18f7.gif)

**Comment by mezz** [comment]
Thanks for the report!

**Comment by mezz** [comment]
This has been fixed by https://github.com/mezz/JustEnoughItems/pull/1790
