### ISSUE TITLE
Issue with saving recipes (moving to a left side)

### ISSUE THREAD

**Issue by ribaczek123** [mezz/JustEnoughItems#1648]
Hi!
I'm new to mods and i saw an interesting thing on a video:" if you click "a" button on a item that you wanna save (crafting recipe), it will move to the left side corner" like this:
![lolz](https://user-images.githubusercontent.com/53295061/61859339-3c4ecc00-aec8-11e9-81c0-7e2c013c3160.png)
It doesn't work for me. I couldn't find any control key setting in minecraft from jei.
Maybe i have too old version of jei (v4.13.1)
My modpack: Sky adventures
Modpack that i saw it: Sky Factory 4
Plz help

**Comment by Greg-21** [comment]
It looks like if you have the latest, stable version of the FTB Sky Adventures modpack, your JEI version should be exactly 4.13.1.225. An initial version of the JEI bookmarking system was added in JEI 4.13.1.226, and that's why it doesn't work for you.

**Comment by Greg-21** [comment]
It looks like if you have the newest at the moment of writing, stable version of the FTB Sky Adventures modpack, your JEI version should be exactly 4.13.1.225. An initial version of the JEI bookmarking system was added in JEI 4.13.1.226, and that's why it doesn't work for you.

**Comment by ribaczek123** [comment]
> It looks like if you have the newest at the moment of writing, stable version of the FTB Sky Adventures modpack, your JEI version should be exactly 4.13.1.225. An initial version of the JEI bookmarking system was added in JEI 4.13.1.226, and that's why it doesn't work for you.

Oh, thanks for info.
