### ISSUE TITLE
[+] button does not work on items with NBT that should be ignored

### ISSUE THREAD

**Issue by JasonYe4273** [mezz/JustEnoughItems#165]
How do you use ignoreNbtTags for blocks?  Do you call it on Item.getItemFromBlock?  I'm doing that, but clicking + to add a recipe to the crafting table doesn't seem to register it ([code](https://github.com/JasonILTG/Minecraft-Modding/blob/master/src/main/java/com/JasonILTG/ScienceMod/compat/jei/SMPluginJEI.java)).  I've tried doing the exact same thing with the same tags for an item, and it works.  I've also tried creating an identical ItemStack with identical tags and calling getNbt on it, but that seems to work, as the resulting NBTTagCompound is empty.  Is this a bug, or am I doing something wrong?

**Comment by mezz** [comment]
JEI does not deal with Blocks, everything is an Item. When you have a "block" in your inventory it's really the ItemBlock. When you do `new ItemStack(block)` it gets the Block's ItemBlock.

Does that help answer your question?

**Comment by JasonYe4273** [comment]
I already knew that; doesn't Item.getItemFromBlock(block) do the same thing?

Anyways, changing it from that to (new ItemStack(block)).getItem() (since you need the Item and not the ItemStack, right?) doesn't seem to help.  

Is there any reason why calling ignoreNbtTags would cause it to work with the getNbt method, but not with using the + to craft?  I've tried debugging by creating an identical ItemStack to the one I'm having trouble with, and then calling getNbt on it, and it seems to be ignoring the correct NBT tags, while the in-game + feature seems to be having trouble.

Actually, now that I've checked, it doesn't seem to be working for items, either.  I've been looking through your code: is isIdentical in StackHelper supposed to use ItemStack.areItemStackTagsEqual?  Shouldn't it be filtered through getNbt?

**Comment by mezz** [comment]
Ok I see what you're saying now. I'm sorry but it was not easy to understand you because you write like you're trying to debug through me, instead of stating a problem that I can solve.

Anyway yeah, `StackHelper.isIdentical` really should use something like `getUniqueIdentifierForStack` to work properly. I can confirm that the blood orb from blood magic has this issue too.

**Comment by JasonYe4273** [comment]
Thanks!  (And sorry for being hard to understand).

**Comment by mezz** [comment]
Fixed in 2.25.11, up on curse soon.
