### ISSUE TITLE
Error loading game on start up

### ISSUE THREAD

**Issue by B1adereaper** [mezz/JustEnoughItems#1650]
Hey having problems loading up the game crash log here https://paste.dimdev.org/ikijipanok.mccrash
thanks.

**Comment by Ommina** [comment]
(I need a hotkey for this reply.)

**java.lang.OutOfMemoryError: GC overhead limit exceeded**. It is simply running out of allocated memory. Looking at the mod count, I'd guess at least 4GB will be required.

**Comment by ProsperCraft** [comment]
Do this - https://youtu.be/-uUr1VAnkcs

And close issue :)

**Comment by B1adereaper** [comment]
> Do this - https://youtu.be/-uUr1VAnkcs
> 
> And close issue :)

Thank you so much,
you fixed everything.
