### ISSUE TITLE
Tooltips Displays Below JEI in LittleTiles GUIs

### ISSUE THREAD

**Issue by WenXin20** [mezz/JustEnoughItems#1654]
Minecraft 1.12.2
Forge v14.23.5.2838
[Little Tiles](https://www.curseforge.com/minecraft/mc-mods/littletiles)  v1.5.0-pre151
JEI v4.15.0.287

I noticed that in the Little Bag and other Little Tiles GUIs, tooltips of items render below the JEI menu. I reported it to CreativeMD/LittleTiles#217, but was recommended to report it here. Is there any way to fix this?
![2019-07-28_23 01 21](https://user-images.githubusercontent.com/12000593/62021945-84534480-b18f-11e9-8164-029301972aeb.png)

**Comment by mezz** [comment]
Thanks for the report!
I have replied in the other issue and will subscribe to it so that everything is in one place. I believe this is a LittleTiles issue.
