### ISSUE TITLE
Tab Prioritization

### ISSUE THREAD

**Issue by Boolyman** [mezz/JustEnoughItems#1657]
Hello,
   I think a very nice feature for JEI would be a Recipe Tab Prioritization list in the config.  It is very common that people playing custom recipe packs overlook recipes because they don't show up on the first tab when viewing them.  And quite often, if a vanilla recipe is removed, the first thing that shows up is useless anvil enchantments.

At the very least, adding the option to make any recipes that are added in Crafttweaker be on the first tab in "R" recipe view would be a big step in the right direction.  As a modpack maker, if I add a custom recipe, thats the recipe I expect the player to use... having to remember to search for the machine up top and hit the tab for it is just extra inconvenient steps that quite often makes the player think the recipe has been disabled.

**Comment by mezz** [comment]
Thanks for the request!
This feature was added a little while ago here: eafe59f2c4d4202ef57cd6d6bb30a7c4a2140064
You can now decide the global order of the recipe categories in the JEI config file.
