### ISSUE TITLE
When adding new trades to existing villagers' trades when JEI is installed item blocks are not added

### ISSUE THREAD

**Issue by SmellyModder** [mezz/JustEnoughItems#1658]
I've added some new trades to the wandering trader in one of my mods. When JEI is installed alongside the mod, the modded blocks we added to its trades don't appear, they're just gone. My testers noticed this and said when you remove JEI it works.

Steps to Reproduce:
1: Override one of the existing villager's trades
2: Add your own custom block to its trades
3: Run JEI alongside it; it will not be there

**Comment by mezz** [comment]
Thanks for the report!
What method are you using to override villager trades?
Can you please try with just Forge and JEI?

**Comment by SmellyModder** [comment]
There is no existing method to add onto existing trades sadly, so I did it by changing the trader's trade map field. With just Forge and JEI it still produces this issue

**Comment by SmellyModder** [comment]
Here is the code where I do it: https://github.com/minecraftabnormals/Upgrade-Aquatic/blob/master/src/main/java/com/teamabnormals/upgrade_aquatic/core/UpgradeAquatic.java#L110

**Comment by mezz** [comment]
JEI doesn't deal with villager trades at all so I am not sure that it's involved here.

I tried making a new pack with Upgrade Aquatic, Mod Name Tooltip, and JEI. It looks fine to me:
![2019-08-18_16 55 11](https://user-images.githubusercontent.com/916092/63232065-02c46480-c1d9-11e9-9d4c-4c98cb0d7bfd.png)

**Comment by SmellyModder** [comment]
Strange, maybe it's been fixed in forge recently. I noticed this bug no longer appears for me on later forge versions. I will close this now
