### ISSUE TITLE
I dont know what my problem is. I have several other friends that have the same mods, but its only affecting me. Every time i open a chest, my inventory, crafting table, furnace, etc; my game crashes.

### ISSUE THREAD

**Issue by ShiftyOrange1** [mezz/JustEnoughItems#1661]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2019-08-08 01:00:20 EDT
Description: Rendering ingredient

java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Ingredient being rendered --
  Ingredient Mod: OpenBlocks
  Ingredient Info: 1xitem.openblocks.glyph@50 openblocks:glyph

-- Screen render details --
  Screen name: net.minecraft.client.gui.inventory.GuiInventory
  Mouse location: Scaled: (320, 179). Absolute: (960, 540)
  Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3

-- Affected level --
  Level name: MpServer
  All players: 1 total; [GCEntityClientPlayerMP['ShiftyOrange1'/31046, l='MpServer', x=126.89, y=64.00, z=-2911.94]]
  Chunk stats: MultiplayerChunkCache: 441, 441
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (2210,76,-228), Chunk: (at 2,4,12 in 138,-15; contains blocks 2208,0,-240 to 2223,255,-225), Region: (4,-1; contains chunks 128,-32 to 159,-1, blocks 2048,0,-512 to 2559,255,-1)
  Level time: 22032620 game time, 23359904 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 73 total; [EntityPig['Pig'/31618, l='MpServer', x=203.24, y=63.00, z=-2979.37], EntityChicken['Chicken'/31620, l='MpServer', x=203.18, y=63.00, z=-2966.35], EntityChicken['Chicken'/31110, l='MpServer', x=110.82, y=63.00, z=-2927.55], EntityRabbit['Rabbit'/31624, l='MpServer', x=192.51, y=64.00, z=-2954.54], EntityZombie['Zombie'/32010, l='MpServer', x=197.50, y=32.00, z=-2897.50], EntityChicken['Chicken'/31500, l='MpServer', x=159.88, y=63.00, z=-2887.66], EntitySpider['Spider'/32012, l='MpServer', x=137.50, y=25.00, z=-2868.50], EntitySkeleton['Skeleton'/31374, l='MpServer', x=99.50, y=39.00, z=-2840.50], EntitySheep['Sheep'/31502, l='MpServer', x=177.51, y=63.00, z=-2902.76], EntityChicken['Chicken'/31503, l='MpServer', x=171.81, y=63.00, z=-2896.70], EntityChicken['Chicken'/31378, l='MpServer', x=127.80, y=63.00, z=-2845.47], EntityItem['item.item.egg'/31506, l='MpServer', x=165.85, y=63.00, z=-2894.76], EntityChicken['Chicken'/31507, l='MpServer', x=181.41, y=64.00, z=-2887.17], EntityItem['item.item.egg'/31509, l='MpServer', x=167.86, y=63.00, z=-2872.13], EntityZombie['Zombie'/31510, l='MpServer', x=148.24, y=45.00, z=-2836.84], EntityCreeper['Creeper'/31511, l='MpServer', x=155.20, y=46.00, z=-2841.52], EntityItem['item.item.egg'/31514, l='MpServer', x=183.47, y=64.00, z=-2865.68], EntityChicken['Chicken'/31515, l='MpServer', x=186.74, y=64.00, z=-2875.83], EntityMinecartChest['Minecart with Chest'/31517, l='MpServer', x=161.88, y=19.00, z=-2986.51], EntityRabbit['Rabbit'/31518, l='MpServer', x=179.69, y=63.24, z=-2977.94], EntityItem['item.item.egg'/31390, l='MpServer', x=139.76, y=64.00, z=-2853.82], EntityPig['Pig'/31391, l='MpServer', x=129.68, y=64.00, z=-2842.48], EntityRabbit['Rabbit'/31520, l='MpServer', x=178.28, y=63.00, z=-2972.30], EntityRabbit['Rabbit'/31522, l='MpServer', x=170.51, y=63.00, z=-2948.43], EntityRabbit['Rabbit'/31523, l='MpServer', x=162.50, y=63.00, z=-2955.50], EntityHat['unknown'/419, l='MpServer', x=60.92, y=64.00, z=-2875.65], EntityHat['unknown'/420, l='MpServer', x=183.27, y=3.00, z=-2966.90], EntityRabbit['Rabbit'/31397, l='MpServer', x=147.41, y=64.00, z=-2967.47], EntityChicken['Chicken'/31270, l='MpServer', x=75.69, y=64.00, z=-2875.88], EntityChicken['Chicken'/31526, l='MpServer', x=184.72, y=63.00, z=-2930.89], EntityItem['item.item.egg'/31271, l='MpServer', x=75.96, y=64.00, z=-2875.68], EntitySheep['Sheep'/31399, l='MpServer', x=144.02, y=63.00, z=-2947.50], EntitySheep['Sheep'/31401, l='MpServer', x=138.70, y=63.00, z=-2940.77], EntityZombieVillager['Zombie Villager'/31657, l='MpServer', x=183.27, y=3.00, z=-2966.90], EntityItem['item.item.egg'/31403, l='MpServer', x=82.84, y=64.00, z=-2877.96], EntitySpider['Spider'/31659, l='MpServer', x=188.50, y=4.00, z=-2966.50], EntityMinecartChest['Minecart with Chest'/31404, l='MpServer', x=138.50, y=32.06, z=-2921.12], EntityPainting['Painting'/31405, l='MpServer', x=133.97, y=66.50, z=-2924.00], EntityPainting['Painting'/31406, l='MpServer', x=131.50, y=71.50, z=-2919.03], EntityPainting['Painting'/31407, l='MpServer', x=133.97, y=70.50, z=-2924.50], EntityChicken['Chicken'/31280, l='MpServer', x=50.41, y=62.00, z=-2942.10], EntityChicken['Chicken'/31409, l='MpServer', x=105.50, y=64.00, z=-2885.15], EntityZombie['Zombie'/31411, l='MpServer', x=80.50, y=13.00, z=-2832.50], EntityChicken['Chicken'/31413, l='MpServer', x=157.09, y=63.00, z=-2908.34], EntityChicken['Chicken'/31286, l='MpServer', x=61.43, y=67.00, z=-2904.49], EntityChicken['Chicken'/31288, l='MpServer', x=69.52, y=64.00, z=-2919.88], EntityItem['item.item.egg'/31289, l='MpServer', x=73.16, y=64.00, z=-2925.84], EntityItem['item.item.egg'/31418, l='MpServer', x=110.87, y=64.00, z=-2968.00], EntityChicken['Chicken'/31419, l='MpServer', x=106.74, y=64.00, z=-2969.17], EntitySkeleton['Skeleton'/31931, l='MpServer', x=165.50, y=19.00, z=-2986.50], EntityChicken['Chicken'/31293, l='MpServer', x=80.16, y=66.00, z=-2913.48], EntityItem['item.item.rottenFlesh'/31295, l='MpServer', x=64.05, y=65.00, z=-2881.85], EntityCow['Cow'/31423, l='MpServer', x=97.60, y=63.00, z=-2947.79], EntityPig['Pig'/31296, l='MpServer', x=49.24, y=63.00, z=-2869.52], EntityZombie['Zombie'/31808, l='MpServer', x=199.50, y=10.00, z=-2924.50], EntityChicken['Chicken'/31297, l='MpServer', x=56.44, y=64.00, z=-2876.21], EntityMinecartChest['Minecart with Chest'/31425, l='MpServer', x=141.50, y=32.06, z=-2976.50], EntityChicken['Chicken'/31298, l='MpServer', x=50.13, y=64.00, z=-2876.57], EntityChicken['Chicken'/31300, l='MpServer', x=60.92, y=64.00, z=-2875.65], EntityRabbit['Rabbit'/31431, l='MpServer', x=158.79, y=63.00, z=-2989.79], EntityItem['item.item.egg'/31433, l='MpServer', x=100.49, y=64.00, z=-2919.28], EntityChicken['Chicken'/31308, l='MpServer', x=74.59, y=63.00, z=-2989.17], EntityChicken['Chicken'/31311, l='MpServer', x=70.85, y=64.00, z=-2977.17], GCEntityClientPlayerMP['ShiftyOrange1'/31046, l='MpServer', x=126.89, y=64.00, z=-2911.94], EntityLatchedRenderer['unknown'/348, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/367, l='MpServer', x=126.89, y=64.00, z=-2911.94], EntityZombie['Zombie'/31601, l='MpServer', x=179.53, y=12.00, z=-2836.26], EntityPainting['Painting'/31405, l='MpServer', x=133.97, y=66.50, z=-2924.00], EntityChicken['Chicken'/31602, l='MpServer', x=186.86, y=65.00, z=-2847.52], EntityPainting['Painting'/31406, l='MpServer', x=131.50, y=71.50, z=-2919.03], EntityItem['item.item.egg'/31859, l='MpServer', x=156.18, y=63.00, z=-2908.87], EntityPainting['Painting'/31407, l='MpServer', x=133.97, y=70.50, z=-2924.50], EntityChicken['Chicken'/31605, l='MpServer', x=201.78, y=68.00, z=-2836.50]]
  Retry entities: 1 total; [EntityLatchedRenderer['unknown'/348, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1040303176 bytes (992 MB) / 5398593536 bytes (5148 MB) up to 8112832512 bytes (7737 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8704m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 95 mods loaded, 95 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version           | Source                                             | Signature                                |
       |:------ |:--------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                               | 9.42              | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                             | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | micdoodlecore                     |                   | minecraft.jar                                      | None                                     |
       | LCHIJA | openmodscore                      | 0.12.2            | minecraft.jar                                      | None                                     |
       | LCHIJA | aether_legacy                     | 1.4.4             | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
       | LCHIJA | ctm                               | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | LCHIJA | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | betterbuilderswands               | 0.11.1            | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | LCHIJA | biomesoplenty                     | 7.0.1.2439        | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar      | None                                     |
       | LCHIJA | guideapi                          | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | LCHIJA | bloodmagic                        | 1.12.2-2.4.1-103  | BloodMagic-1.12.2-2.4.1-103.jar                    | None                                     |
       | LCHIJA | bookshelf                         | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | codechickenlib                    | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | brandonscore                      | 2.4.17            | BrandonsCore-1.12.2-2.4.17.208-universal.jar       | None                                     |
       | LCHIJA | chesttransporter                  | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | LCHIJA | sanlib                            | 1.5.1             | SanLib-1.12.2-1.5.1.jar                            | df48348748b5e141b1d118e2302a8d5be930b708 |
       | LCHIJA | claysoldiers                      | 3.0.0-beta.2      | ClaySoldiersMod-1.12.2-3.0.0-beta.2.jar            | None                                     |
       | LCHIJA | cofhcore                          | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
       | LCHIJA | cofhworld                         | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cosmeticarmorreworked             | 1.12.2-v4a        | CosmeticArmorReworked-1.12.2-v4a.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | cucumber                          | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
       | LCHIJA | dimdoors                          | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                     | None                                     |
       | LCHIJA | thermalfoundation                 | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | draconicevolution                 | 2.3.24            | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar | None                                     |
       | LCHIJA | dungeontactics                    | DT-0.16.5         | DungeonTactics-1.12.2-0.16.5.jar                   | None                                     |
       | LCHIJA | durabilityviewer                  | 1.4               | DurabilityViewer-1.12-forge14.21.1.2387-1.4.jar    | None                                     |
       | LCHIJA | eplus                             | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | endercore                         | 1.12.2-0.5.59     | EnderCore-1.12.2-0.5.59.jar                        | None                                     |
       | LCHIJA | jei                               | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCHIJA | thaumcraft                        | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | LCHIJA | thermalexpansion                  | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                           | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderiobase                       | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderioconduits                   | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | twilightforest                    | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
       | LCHIJA | tconstruct                        | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar                   | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderiomachines                   | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderiopowertools                 | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                          | None                                     |
       | LCHIJA | enderstorage                      | 2.4.5.135         | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | energyconverters                  | 1.3.0.15          | energyconverters_1.12.2-1.3.0.15.jar               | None                                     |
       | LCHIJA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LCHIJA | forgelin                          | 1.8.3             | Forgelin-1.8.3.jar                                 | None                                     |
       | LCHIJA | llibrary                          | 1.7.19            | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil                            | 8.0.2             | fossilsarcheology-8.0.2.jar                        | None                                     |
       | LCHIJA | ic2                               | 2.8.171-ex112     | industrialcraft-2-2.8.171-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | galacticraftcore                  | 4.0.2.220         | GalacticraftCore-1.12.2-4.0.2.224.jar              | None                                     |
       | LCHIJA | galacticraftplanets               | 4.0.2.220         | Galacticraft-Planets-1.12.2-4.0.2.224.jar          | None                                     |
       | LCHIJA | ichunutil                         | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | hats                              | 7.0.0             | Hats-1.12.2-7.0.2.jar                              | None                                     |
       | LCHIJA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | teslacorelib                      | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
       | LCHIJA | ironbackpacks                     | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
       | LCHIJA | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCHIJA | journeymap                        | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar                        | None                                     |
       | LCHIJA | jrftl                             | 1.1               | JRFTL[1.12.2]-1.1.jar                              | None                                     |
       | LCHIJA | numina                            | 1.12.2-1.0.38     | Numina-1.12.2-1.0.38.jar                           | None                                     |
       | LCHIJA | powersuits                        | 1.12.2-1.0.46     | ModularPowersuits-1.12.2-1.0.46.jar                | None                                     |
       | LCHIJA | mystcraft                         | 0.13.7.03         | mystcraft-1.12.2-0.13.7.03.jar                     | None                                     |
       | LCHIJA | mysticalagriculture               | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
       | LCHIJA | mysticalagradditions              | 1.3.2             | MysticalAgradditions-1.12.2-1.3.2.jar              | None                                     |
       | LCHIJA | natura                            | 1.12.2-4.3.2.69   | natura-1.12.2-4.3.2.69.jar                         | None                                     |
       | LCHIJA | netherendingores                  | 1.12.2-1.3        | Netherending-Ores-1.12.2-1.3.jar                   | None                                     |
       | LCHIJA | openmods                          | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                        | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | harvestcraft                      | 1.12.2zb          | Pam's HarvestCraft 1.12.2ze.jar                    | None                                     |
       | LCHIJA | portalgun                         | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | ptrmodellib                       | 1.0.4             | PTRLib-1.0.4.jar                                   | None                                     |
       | LCHIJA | quacklib                          | 2.2.5             | quacklib-2.2.5.jar                                 | None                                     |
       | LCHIJA | randomthings                      | 4.2.7.3           | RandomThings-MC1.12.2-4.2.7.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | redstonearsenal                   | 2.6.3             | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | xreliquary                        | 1.12.2-1.3.4.786  | Reliquary-1.12.2-1.3.4.786.jar                     | None                                     |
       | LCHIJA | sanplayermodel                    | 1.1.1             | SanLib-1.12.2-1.5.1.jar                            | None                                     |
       | LCHIJA | sereneseasons                     | 1.2.16            | SereneSeasons-1.12.2-1.2.16-universal.jar          | None                                     |
       | LCHIJA | thermaldynamics                   | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | simplyjetpacks                    | 2.2.12.65         | SimplyJetpacks2-1.12.2-2.2.12.65.jar               | None                                     |
       | LCHIJA | thermalcultivation                | 0.3.3             | ThermalCultivation-1.12.2-0.3.3.12-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalinnovation                 | 0.3.3             | ThermalInnovation-1.12.2-0.3.3.12-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | torohealthmod                     | 1.12.2-11         | torohealth-1.12.2-11.jar                           | None                                     |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | veinminer                         | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | LCHIJA | veinminermodsupport               | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | LCHIJA | technom                           | 1.12-1.1.0        | technomancy-1.12-1.1.0.jar                         | None                                     |
       | LCHIJA | teslacorelib_registries           | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.224.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.7.3.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      PluginLoader (MemoryTester-0.4.2.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.60' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
  Suspected Mods: Unknown
  Launched Version: forge-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with rendering an OpenBlocks item with Optifine:
```
-- Ingredient being rendered --
Ingredient Mod: OpenBlocks
Ingredient Info: 1xitem.openblocks.glyph@50 openblocks:glyph
```
Please see the Optifine issue here: https://github.com/sp614x/optifine/issues/2267
