### ISSUE TITLE
JEI crash on loading world

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1663]
JEI 1.14.4.6.0.0.9
Forge 28.0.45

Crash report when loading into a world

https://pastebin.com/0EXwsHff

**Comment by mezz** [comment]
Thanks for the report!
I am unable to build with Forge 28.0.45 right now, I think because of this: https://github.com/MinecraftForge/ForgeGradle/issues/611
So for now I am waiting on an update before I can make JEI work with that version.

**Comment by ghost** [comment]
Nice work so far. Love JEI. Thank you

**Comment by GrumpyZade** [comment]
Sadness;(

**Comment by wulfenbach-jpg** [comment]
I loaded it up with no other mods, and boom tick event crash, so yeah, it's still broken with the newest version of Forge.

**Comment by mezz** [comment]
I still haven't gotten things working in my IDE, but the fix for this issue was simple so I pushed an update manually. This should be fixed in the upcoming release.
