### ISSUE TITLE
jet 1.12.2 recipe wont show

### ISSUE THREAD

**Issue by umarik2000** [mezz/JustEnoughItems#1664]
I have the latest jei mod for 1.12.2 and basically every time I try to look up a recipe or uses for an item, modded or not modded items it doesn't show anything except smelting recipes

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
