### ISSUE TITLE
Minecraft crashes due to "Class Def Not Found" error when generating world

### ISSUE THREAD

**Issue by ironminer888** [mezz/JustEnoughItems#1667]
With JEI, Minecraft crashes when I attempt to generate a new world. After some looking around in the crash log, it appears that there is something wrong with a subprocess for an "ingredient filter." Attached is a few crash logs demonstrating the error in question:
* [crash-2019-08-08_19.49.24-client.txt](https://github.com/mezz/JustEnoughItems/files/3484345/crash-2019-08-08_19.49.24-client.txt)
* [crash-2019-08-08_19.51.59-client.txt](https://github.com/mezz/JustEnoughItems/files/3484346/crash-2019-08-08_19.51.59-client.txt)
* [crash-2019-08-08_21.21.25-client.txt](https://github.com/mezz/JustEnoughItems/files/3484343/crash-2019-08-08_21.21.25-client.txt)
* [crash-2019-08-08_21.40.05-client.txt](https://github.com/mezz/JustEnoughItems/files/3484342/crash-2019-08-08_21.40.05-client.txt)

**Comment by leeterry** [comment]
This looks like the same problem I and others have been having. If so this is not a jei issue but an issue with the latest version of forge and we are waiting for forge to update/fix the issue. Try using an older version of forge if your other mods will allow it or play without jei till forge gets fixed.

**Comment by ironminer888** [comment]
I see.
I've reverted to Forge 28.0.41, and downloaded some older versions of the mods I plan to use. Everything seems to work fine now. I just hope this bug gets fixed for recent versions of Forge soon.

**Comment by Ommina** [comment]
JEI 6.0.0.10 is available on Curse, which purports to work with Forge 28.0.45.  Give that a go.

**Comment by ironminer888** [comment]
Okay, will do. After some testing and updating my mods, everythind is working fine with the new JEI update. Thank you.
