### ISSUE TITLE
Crashes after opening inventory screen

### ISSUE THREAD

**Issue by ricenberg** [mezz/JustEnoughItems#1669]
Upon adding the latest version of NEI to my load order, the game launches fine but crashes when bringing up my inventory. As soon as I press the button, the game screen says "saving world" and crashes about a second after. Thanks for looking at my report.

**Comment by Mace68** [comment]
I'm getting the same behavior on Minecraft 1.14.4. I have the following mods loading:

Forge 28.0.45
- JEI 6.0.0.10
- Xaero's Minimap 1.17.6
- OptiFine 1.14.4 HD U F4 pre2

Crash report: https://pastebin.com/raw/SHAtdMam

**Comment by zed787** [comment]
I'm getting the same issue too,on  Forge 28.0.45 for Minecraft 1.14.4

Mods I have:

- JEI 6.0.0.10

- OptiFine 1.14.4 HD U F4 pre2

- Silent gear 1.3.5+54

- Silent lib 4.3.1+39

- Mining dimension 1.0.2

Here is the crash log:[crash-2019-08-10_12.06.44-client.txt](https://github.com/mezz/JustEnoughItems/files/3488503/crash-2019-08-10_12.06.44-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Please try without Optifine and see if the issue still occurs.

**Comment by ricenberg** [comment]
Just tried JEI without optifine on 1.14.4 and no crashes. The mod works perfectly. I only removed optifine, so I assume JEI doesn't like it.

**Comment by ghost** [comment]
this is the same as #1668

**Comment by mezz** [comment]
Thanks, please see the other issue (#1668) so we can keep the conversation in one place.

**Comment by anarche0** [comment]
Could you make it compatible with that version of optifine. I can't play minecraft without it. My computer sucks. Even with no mods, it runs poorly without it.

**Comment by PseudoResonance** [comment]
This is an OptiFine issue, JustEnoughItems is not responsible for the crash. Unfortunately, there is nothing that can be done until a new version of OptiFine comes out fixing the issue.
