### ISSUE TITLE
Dynamically change the hide/show keybinding according to current OS

### ISSUE THREAD

**Issue by Jerzerak** [mezz/JustEnoughItems#167]
Just a minor tweak that'll help reduce confusion among Mac users as the Hide/Show JEI keybinding displays as "CTRL + O" instead of "CMD + O" on OS X

**Comment by mezz** [comment]
Good point, I'll fix that. I really hope Forge adds keybinds with modifiers soon, it would make this a lot cleaner.

**Comment by Jerzerak** [comment]
@mezz Am I correct in thinking that [#2780](https://github.com/MinecraftForge/MinecraftForge/pull/2792) closes this issue?

**Comment by mezz** [comment]
Oh! Yes it does, thanks. I got this issue mixed up with the Forge one here https://github.com/MinecraftForge/MinecraftForge/issues/2780, thought they were one issue.

**Comment by Jerzerak** [comment]
No worries Mezz, you rock!
