### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by cbass55379** [mezz/JustEnoughItems#1670]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by cbass55379** [comment]
the mod does not work at all. :/ when I press ctrl + o it does not work, i went in the controls and changed it to m and still did not work :/

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by cbass55379** [comment]
it works now but thanks though!
