### ISSUE TITLE
[1.14] IIngredients no longer permits empty stacks

### ISSUE THREAD

**Issue by Shadows-of-Fire** [mezz/JustEnoughItems#1674]
As of JEI 6.0.0.10 (and probably earlier in the 1.14 cycle), `IRecipeCategory#setIngredients` no longer permits empty ingredients to be set to the passed `IIngredients` instance.  This causes the following error further down the line, a bit after the ingredients were set. https://gist.github.com/Shadows-of-Fire/fc280f099d53bed13053ddc5cb600f9d
This behavior was not invalid in 1.12.2

**Comment by mezz** [comment]
Thanks for the report!

Looking deeper at this, I think that this is actually working as intended.
In your log it shows a recipe that outputs air, which should definitely be considered invalid as a recipe and hidden from players.

Also see `net.minecraft.item.crafting.Ingredient#EMPTY`, it does not contain Air.

The one case I can easily think of where you need something to be empty is for displaying items in rotation in `setRecipe`. For that you can use null in a list like in 1.12 and earlier.

If your recipe does not have a bug and you think a change to JEI is still needed, can you explain with another example?

**Comment by Shadows-of-Fire** [comment]
While this is not specific to my case here, this may be a problem for mods that use optional secondary outputs (that may be represented as nothing using ItemStack.EMPTY).  That's how the Actually Additions crusher functions.

**Comment by mezz** [comment]
I think this might no longer be an issue in the latest versions of JEI, please let me know if you're still running into this problem.
