### ISSUE TITLE
 big problem of crash

### ISSUE THREAD

**Issue by Opiomn** [mezz/JustEnoughItems#1677]
Hello I noticed a problem between jei-1.14.4-6.0.0.10 and preview_OptiFine_1.14.4_HD_U_F4_pre2. the start of the game works very well but at the time of opening the inventory the game crash.

**Comment by Ommina** [comment]
I presume this is a duplicate of #1668 and, by extension, https://github.com/sp614x/optifine/issues/2737.

**Comment by ghost** [comment]
yes it is a known issue to Mezz, Need Optifine to update
