### ISSUE TITLE
changing resource pack causes crash

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1682]
JEI 1.14.4-6.0.0.10
Had this a couple of times with Forge 28.0.45 and 28.0.49

Change the resource pack and the game crashes.

No Resource pack installed
Go into a world
Exit the world
Change resource pack - I use Faithful 1.14.3.r1
Game crash

Crash log https://pastebin.com/LnW1fKtE

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by ghost** [comment]
debug.log https://pastebin.com/YcMuzG8E
latest.log https://pastebin.com/yDm6M0yn

**Comment by mezz** [comment]
Thanks!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1572, please follow that issue for updates so that the conversation is all in one place.
