### ISSUE TITLE
JEI menu not appearing ingame

### ISSUE THREAD

**Issue by Pyrolax** [mezz/JustEnoughItems#1684]
In-game the GUI doesn't appear, i've tried CTRL + O to toggle the menu and it doesnt appear nontheless. I can provide my log file if needed

**Comment by Felix2433** [comment]
I have exactly the same problem

**Comment by Ommina** [comment]
Logs would be good.

@Felix2433 create a new issue including your own logs.  While you may have exactly the same symptoms, let's not rush to conclude you have exactly the same problem.

**Comment by IchigoGames** [comment]
same issue on my modpack only for server tho it will show up in single player but no on server but you can load into singeplayer then get on server and it shows up. let me know what logs you need and ill send them btw jei-1.14.4-6.0.0.10 on forge 28.0.45

**Comment by IchigoGames** [comment]
what logs do you need

**Comment by IchigoGames** [comment]
[2019-08-17-7.log.gz](https://github.com/mezz/JustEnoughItems/files/3512779/2019-08-17-7.log.gz)
[latest.log](https://github.com/mezz/JustEnoughItems/files/3512780/latest.log)

**Comment by IchigoGames** [comment]
this is the pack tho i think this is a issue no mater what pack https://www.curseforge.com/minecraft/modpacks/the-oceanic-frontier?gameCategorySlug=modpacks&projectID=318351

**Comment by mezz** [comment]
Thanks for the report!

JEI works fine alone, so there must be a conflict between some mod and JEI.
Please make a back up copy of the pack, and remove half the mods at a time to see if you can find which mod is conflicting with JEI here.

When you have found one or two mods that cause this bug with JEI, I can look into fixing it, or I can help report the bug to another mod author.

**Comment by Vampy26** [comment]
So I have this same issue on my server same build and forge, and I looked through the above mod pack to see what mods I have installed that the mod pack has and they are:

MrCrayfish's Furniture Mod (by Mr_Crayfish) 
Xaero's World Map (by xaero96) 
Silent's Gems (by SilentChaos512) 
Silent Gear (by SilentChaos512) 
Xaero's Minimap (by xaero96) 
Chance Cubes (by turkey2349)

The weird thing is if I login to the server solo I can use JEI, but if anyone else logs into it when I press E again its gone and no one can use the command to open it back up including me, I know i'm not OP im just trying to help you as I love JEI and the silent mods are so difficult to navigate without it!

**Comment by IchigoGames** [comment]
ya this is going to be a hard one to test due to it working on singeplayer but not on server

**Comment by IchigoGames** [comment]
Found it was going to test all the mods listed above to start off so i picked the one i added the most recent as this use to not be a issue and it was Chance Cubes (by turkey2349) with it added to server no jei without it on server jei shows up. so ill go make a report on there next.

**Comment by IchigoGames** [comment]
ok down https://github.com/Turkey2349/ChanceCubes/issues/185

**Comment by IchigoGames** [comment]
ok may of been wrong about it being chance cubes connecting to the server twice turns jei back on

**Comment by IchigoGames** [comment]
ok may of been wrong about it being chance cubes connecting to the server twice turns jei back on
but it still does not work if you load the pack and join the first time even without chance cubes added. this one is a pain

**Comment by IchigoGames** [comment]
after alot more testing it looks like its Silent Gear https://github.com/SilentChaos512/Silent-Gear/issues/52

**Comment by ProsperCraft** [comment]
We are having this same issue on my 1.14.4 modpack https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

Players log in to the server, don't have JEI at all on the right, relog, then they do have it.

**Comment by ProsperCraft** [comment]
This has been resolved and can be closed.

**Comment by Rmdhn1** [comment]
Works on creative, doesn't show on survival

**Comment by jklw10** [comment]
this is happening to me on 1.16.4 with what i assume is the fault of mystical agriculture having incomplete recipes / recipes with certain items missing. i also have bonsai trees which was mentioned in the allthe mods discussion.

**Comment by K6ZXS** [comment]
hello im also having the same problem 
i have the mod in my folder but its not in the ingame mod tab

**Comment by mezz** [comment]
Please open a new issue if this is happening to you now. 
This issue is from 2019 and so it's really unlikely to be caused by the same bug.
