### ISSUE TITLE
Something is wrong with JEI in the Dungeons, Dragons and Space Shuttles modpack 1.12.2

### ISSUE THREAD

**Issue by For3verN1ght4** [mezz/JustEnoughItems#1688]
I have no clue what the problem is, but it seems there is a problem with JEI and it's not letting me load the modpack (for the first time). But, the report that was linked is below and I would really appreciate it if someone could help me with this issue. Thanks.
https://paste.dimdev.org/zeyuyesewu.mccrash

**Comment by TehNut** [comment]
You are running out of memory and need to allocate more.
