### ISSUE TITLE
crash when opening inventory

### ISSUE THREAD

**Issue by colemy** [mezz/JustEnoughItems#1691]
client crashes when opening inventory in new creative singeplayer worlds. this crash occurs when optifine is present. i tested optifine with dozens of other mods. the crash only occurs when optifine and jei are paired. tested with jei and optifine alone.

forge version 28.0.55
jei version 6.0.0.10
optifine version f4 pre 2 mod (extracted)

crash log
https://gist.github.com/cpm9/88bb4423cc3567282e1b6aa136d429a9

**Comment by TehNut** [comment]
#1668

**Comment by mezz** [comment]
Thanks for the report!
Please follow the Optifine issue here: sp614x/optifine#2748
