### ISSUE TITLE
JEI showing incorrect item amount

### ISSUE THREAD

**Issue by RoelofvdG** [mezz/JustEnoughItems#1694]
When I started playing at first everything was normal, but after a while JEI started to show incorrect recipes. More ingredients would be shown to be required than are actually needed. The recipes where this occurs and the amount of items that is shown seems to be a bit random, but it does appear to be consistent between reboots of the game or my PC. It has become especially annoying considering I am using Refined Storage as well, and this bug causes me to consume way more items than needed.

My observations and testing results are listed below:

 - Not every item is shown to need too much (see screenshot: 2x iron ingots but 1x stone gear)
 - The recipe still works with the correct amount of items
 - Vanilla _and_ modded items/recipes are subject to the bug (Vanilla iron ingots in 1st screenshot, Thermal Foundation copper in 2nd screenshot)
 - When shift-clicking the recipe in Refined Storage pattern grid, the correct amount of items is shown, but when creating the pattern the incorrect amount of items is written in the pattern
 - Not every recipe is subject to the bug (screenshot 5 and 6)
 - The amount of items shown as needed varies per recipe (2 in screenshot 1, 3 in screenshot 2, 10 in screenshot 7)
 - If you have the correct amount of items it does allow you to click the "+" to add them to the crafting grid and shows none as missing. Take screenshot 1 for example: when I have only 4 iron ingots intstead of the 8 shown in the recipe, I can still click the "+" to add the iron ingots to the crafting table and craft 1 iron gear.
 - When crafting an item with Refined Storage, the incorrect amount of items is consumed (as written in the pattern) instead of the correct amount, but only when autocrafting (with an incorrect pattern)
 - Turning off the "Oredict" option in the Refined Storage pattern grid causes the correct amount to be written to the pattern (but without Oredictionary support). Having the "Oredict" option enabled causes the wrong amount of items to be written to the pattern as is shown in the JEI interface (but only if that recipe has a wrong item count to begin with).

I have no idea what is causing this, which is why I am submitting this issue. I am playing on FTB Revelation 3.0.1 (JEI version 1.12.2-4.15.0.268).

![afbeelding](https://user-images.githubusercontent.com/33722364/63457790-ebdc7700-c451-11e9-8d81-54c9907dd713.png)
Screenshot 1: iron gear

![afbeelding](https://user-images.githubusercontent.com/33722364/63458087-6b6a4600-c452-11e9-9af1-cf9f6ef239b9.png)
Screenshot 2: arboreal extractor

![afbeelding](https://user-images.githubusercontent.com/33722364/63458272-ce5bdd00-c452-11e9-917e-d35e4e45dee6.png)
Screenshot 3: correct amount ot items shown in Refined Storage pattern grid

![afbeelding](https://user-images.githubusercontent.com/33722364/63458425-14b13c00-c453-11e9-8b89-4b7ce14e760d.png)
Screenshot 4: Incorrect amount written to Refined Storage pattern, should be 1x copper ingot instead of 3x

![afbeelding](https://user-images.githubusercontent.com/33722364/63458646-75d90f80-c453-11e9-9f12-385c203486f2.png)
Screenshot 5: Not every modded recipe is bugged

![afbeelding](https://user-images.githubusercontent.com/33722364/63458690-87bab280-c453-11e9-9806-a821cda6c97c.png)
Screenshot 6: Not every vanilla recipe is bugged

![afbeelding](https://user-images.githubusercontent.com/33722364/63458804-be90c880-c453-11e9-8d87-fbe5a3a45e1f.png)
Screenshot 7: The amount of items needed varies

**Comment by mezz** [comment]
Thanks for the report!
I have observed this in the past when a mod accidentally edits an oredictionary ingredient. They set the size directly instead of making a copy first, so it affects all recipes that use that oredict ingredient.
Please try removing mods to find the one that is causing this problem.

**Comment by Darkere** [comment]
This is a known issue with Refined Storage that was fixed a while ago. 

You can "fix" the problem by creating processing patterns with oredict that only have one item (1 iron for example) in them. Pressing the create pattern button overwrites the itemstack. This has been fixed in 1.6.15.
