### ISSUE TITLE
[1.14.4] Crashes on entering a world

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1697]
JEI crashes after ~30 seconds on the joining world page. JEI is the only mod loaded, and I have tried with a new world. I cannot find anything in the crash reports folder. No optifine.
JEI Version: 6.0.0.10 (Latest)
Forge Version: 28.0.55 (Latest)

**Comment by bleedoutkid** [comment]
same issue, no crash reports.
as well I've tested with optifine and it does load, but then I run into #1668 
things haven't been this finicky since 1.8 came out but hopefully things smooth out soon

**Comment by PseudoResonance** [comment]
Have you tried checking your game logs?

**Comment by ghost** [comment]
Do you mean the logs folder? I found a 'Latest'.

https://pastebin.com/SQDEyJjr

**Comment by bleedoutkid** [comment]
from what I can see, it looks like it could be something with a resource pack, I played around with different packs and with some it worked fine, with others it would do the same crash.
this might not be the issue at all, and it could be something else entirely, maybe something with how it renders the item previews and the resource pack is interfering in some way. try removing it and use the default textures or something like the developer art pack to see if it still happens for you

again I'm probably wrong but it's worth a shot

**Comment by ghost** [comment]
It didn't crash, I took out Vanilla Tweaks and it worked, I wonder why that is.
