### ISSUE TITLE
[1.14.4] Crash when loading into world with resource pack enabled.

### ISSUE THREAD

**Issue by Senmori** [mezz/JustEnoughItems#1698]
**Mods**:
Minecraft: 1.14.4
JEI - 1.14.4-6.0.0.10
Forge - 28.0.55

Light Level Overlay Reloaded - 1.2.4-mc1.14.4
Xaero's Minimap - 1.17.7
Xaero's World Map - 1.4.7

**Problem**:
JEI crashes when loading into a world when a resource pack is loaded.
This includes the 'Programmer Art' resource pack.

I can load into a world fine without any resource pack enabled.

**Logs**:
First: https://gist.github.com/Senmori/1e105dee21baf0f8011a91e335a778e8

Programmer Art resource pack log: https://gist.github.com/Senmori/05c0436768bf9b9cf9a182a8e6beb62b
(I can't seem to reproduce this problem since I caused this by accident and I don't know what I did to cause it.)

**Comment by mezz** [comment]
Thanks for the report!
I think this may be the same issue: https://github.com/mezz/JustEnoughItems/issues/1572
I have not been able to reproduce the bug, unfortunately. If you have a way to reliably cause the bug, it would be very helpful.

**Comment by Wonton3** [comment]
I'm having the same problem. I'm using a resource pack that tweaks vanilla textures and nothing else. I've tried uninstalling every other mods and it's been consistently crashing the game for me. I can load into a world, the moment I activate the resource pack the game crashes.

This is the resource pack I'm using:
[VanillaTweaks_r848538.zip](https://github.com/mezz/JustEnoughItems/files/3561892/VanillaTweaks_r848538.zip)

**Comment by Omni35** [comment]
I tested that VanillaTweaks resouce pack myself, it indeed crashes the game with no crash report generated and a message "An unexpected issue occurred and the game has crashed. We’re sorry for the inconvenience." 

First log is from loading the pack in the world, second from trying to load the world with the pack already selected. 
[latest.log](https://gist.github.com/Omni35/5103e0cc50b04e25406bb38e9c63ebf3)

**Comment by mezz** [comment]
I tested this and the error I'm getting is actually from the Java runtime itself:
```
[21:28:05] [Client thread/DEBUG] [me.je.in.IngredientFilter/]: Indexing ingredients: Minecraft
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000040445c7, pid=22316, tid=0x0000000000005534
#
# JRE version: Java(TM) SE Runtime Environment (8.0_221-b11) (build 1.8.0_221-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.221-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 8337 C2 net.minecraft.client.renderer.texture.NativeImage.getPixelRGBA(II)I (130 bytes) @ 0x00000000040445c7 [0x00000000040444e0+0xe7]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\code\JustEnoughItems1.14\run\hs_err_pid22316.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
AL lib: (EE) alc_cleanup: 1 device not closed
```

Are you also getting error logs like `hs_err_pid22316.log` generated in your minecraft  folders?

**Comment by mezz** [comment]
Thanks to @pau101 for figuring out this issue.

There is a bug in JEI that causes it to access out-of-bounds memory in images if the image is not square. The minecart texture in this resource pack is not square.

Normally this would result in a regular crash that is easy to understand, but there is a vanilla bug in `NativeImage` so it does not properly check the bounds are within the image, and it uses unsafe code to access memory directly and this crashes the JRE.
