### ISSUE TITLE
Trouble with ItemListOverlay API

### ISSUE THREAD

**Issue by Towdium** [mezz/JustEnoughItems#170]
I'm trying to make the JEI search bar synchronized with my searching textfield using
`JEIPlugin.runtime.getItemListOverlay().setFilterText("apple");`
However, it shows no change in GUI.

I think the function should be involked correctly, since the following code works fine
`JEIPlugin.runtime.getItemListOverlay().getFilterText()`
It gets the text correctly.

Another thing is when I set the text, the function getFilterText() returns the set value.

Sorry for my bad English...

**Comment by mezz** [comment]
Thanks for the report!
I must have broken it recently, I'll check it out.
