### ISSUE TITLE
JEI crashing on world start 

### ISSUE THREAD

**Issue by uzkaiser** [mezz/JustEnoughItems#1701]
Hello,

I have an issue with JEI 1.14.4-6.0.0.9, it makes my game crash as soon as my world is loading.
My game starts perfectly without JEI an i can't find what causes the issue ( i do not use optifine).

Forge version : 1.14.4-forge-28.0.45

https://gist.github.com/uzkaiser/b623eba68545b8aeed8ea4cedbd49981

Hoping someone has an idea or a solution.

Have an nice day !

**Comment by TehNut** [comment]
Update JEI

**Comment by uzkaiser** [comment]
> Update JEI

Well i did, and now i can start my world but my game crash as soons as i open my inventory
