### ISSUE TITLE
Dev issue: could not get resource 500

### ISSUE THREAD

**Issue by MichaelHillcox** [mezz/JustEnoughItems#1702]
Hi, not sure if this is your issue or if it lays with who ever hosts your maven project (forestry has the same issue but I've been able to downgrade by a single version for now) but when I'm trying to pull COFHCore for my project I'm hitting this error 

```
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve mezz.jei:jei_1.12.2:4.8.0.+.
     Required by:
         project : > cofh:CoFHCore:1.12.2-4.6.2.25
      > Could not resolve mezz.jei:jei_1.12.2:4.8.0.119.
         > Could not get resource 'https://modmaven.k-4u.nl/mezz/jei/jei_1.12.2/4.8.0.119/jei_1.12.2-4.8.0.119.pom'.
            > Could not HEAD 'https://modmaven.k-4u.nl/mezz/jei/jei_1.12.2/4.8.0.119/jei_1.12.2-4.8.0.119.pom'. Received status code 500 from server: Internal Server Error
```

The first thing I tried was to downgrade COFHCore but it would seem that they've been on your last build for a while. I've done a quick "just google it" and I've found that it may be that you just need to re-push. 

Failed resource: https://modmaven.k-4u.nl/mezz/jei/jei_1.12.2/4.8.0.119/jei_1.12.2-4.8.0.119.pom
Effected build: jei_1.12.2-4.8.0.119

json response at the time of posting: 
```{
  "errors" : [ {
    "status" : 500,
    "message" : "Could not process download request: Binary provider has no content for 'bbb75d947515f233f7c78cb1aee1554059a95510'"
  } ]
}
```

Hope it can be resolved soon :D

**Comment by MichaelHillcox** [comment]
Closing for now as I've gotten around the issue

**Comment by mezz** [comment]
Thanks for the report!
Glad you resolved the issue.
Please post the solution you found, for anyone else who googles this some day and has the same issue.

**Comment by MichaelHillcox** [comment]
Currently downgrading gradle. My IDE updated gradle to 4.x and I require 2.x for forge 1.12. maven seems to be fine for 2.x requests but throws that issue when you pull with something newer. I don't understand maven quite enough to understand if this is intended or not.
