### ISSUE TITLE
Cheat mode not working in survival?

### ISSUE THREAD

**Issue by VL4DST3R** [mezz/JustEnoughItems#1707]
I'm not sure if this is a known issue or not, or if i am missing something, but if i am on a server then cheat mode doesn't work, as in: i can't spawn any item. At first i thought the command used to summon said items was defined incorrectly, but the mod no longer has any options or config files like in previous versions, like 1.12.2. 

My guess is that the issue i'm experiencing is linked to the fact that JEI seems to have changed how it spawns items in 1.14.4. It used to be that if you click or right click an item in the list, it would add one/a stack of a specific kind of item to the player inventory, now instead it shows the amount of items next to your cursor when you click it from the item list, and you then have to click the item back into your inventory to place it there.

**Comment by mezz** [comment]
Thanks for the report!
JEI is still incomplete in 1.14 because it is missing its configs. 
Please see this issue for some more info: https://github.com/mezz/JustEnoughItems/issues/1526
