### ISSUE TITLE
[1.14.4] Crash while rendering overlay

### ISSUE THREAD

**Issue by Omni35** [mezz/JustEnoughItems#1708]
The crash always happens when I 'Save and Quit to Title' some premade maps like Skyblock 4.05, only happens with JEI installed. 

Crashlog with just Forge+JEI: 
[crash-2019-08-28_17.09.41-client](https://gist.github.com/Omni35/cdb272a10e0d7abd9a2f139e0073e254)

**Comment by mezz** [comment]
Thanks for the report!
I think this is no longer an issue in the latest versions, please let me know if it is.
