### ISSUE TITLE
1.14.4 Crashed when using optifine

### ISSUE THREAD

**Issue by CoffeeCatRailway** [mezz/JustEnoughItems#1710]
I launched a world and pressed E and the game crashed.
Crash log: https://pastebin.com/Td8T34Et

**Comment by Omni35** [comment]
Try OptiFine 1.14.4 HD U F4 pre3 instead, the issue is fixed there.

**Comment by CoffeeCatRailway** [comment]
That's the version I was using...

**Comment by Ommina** [comment]
"OptiFine_1.14.4_HD_U_F4_pre2_MOD.jar" (line 133 of your crash report) suggests otherwise.  Maybe check to ensure the .jar that is there is the file you think it is.

Regardless, this is not a JEI issue.

**Comment by CoffeeCatRailway** [comment]
I tried it again and it works now, idk why but it does
