### ISSUE TITLE
Installing the 1.12.2 latest JEI mods is impossible.

### ISSUE THREAD

**Issue by Anatoly03** [mezz/JustEnoughItems#1712]
I installed the latest 1.12.2 jei mod, but minecraft wants me to get 1.14.4 forge? Logic?
![Screenshot 2019-09-01 at 12 06 37](https://user-images.githubusercontent.com/44678124/64074194-f64c0b80-ccb0-11e9-944e-0de349e96bf6.png)
![Screenshot 2019-09-01 at 12 06 30](https://user-images.githubusercontent.com/44678124/64074196-fa782900-ccb0-11e9-83ed-82fbf40b8755.png)

**Comment by Ommina** [comment]
The 14.4 series of Forge is 28.0.* -- not 14.23.*

Update Forge to the 1.12.2 version specified.
