### ISSUE TITLE
Crashing client

### ISSUE THREAD

**Issue by Load-of-salt** [mezz/JustEnoughItems#1714]
The new version for 1.14.4 6.0.0.11 is crashing my client but not the server this is the 
crash report ( https://gist.github.com/Load-of-salt/6fdcf73dc586024729ca0c7293794430 )

**Comment by Ommina** [comment]
Update Forge as well. JEI .11 adds support for the new Forge fluids, which were only very recently added.

Some of the details of the new API seem to be a bit (ahem) fluid yet, so there may be some more wobble on the way as the dust settles.

**Comment by Load-of-salt** [comment]
Will do and thanks for the fast reply =)
