### ISSUE TITLE
JEI doesn't show up in 1.14.4 world, despite working in the same world before hand. (FastWorkbench and/or FastFurnace and any anvil mods are not installed)

### ISSUE THREAD

**Issue by ComicalTNM** [mezz/JustEnoughItems#1716]
Is there a certain mod that may cause this? 
List of current mods:
SecurityCraft
AppleSkin
BadMobs
BetterAdvancements
betteranimalsplus
BetterAnimationsCollection2
BetterThanMending
bettertridentreturn
Biomes O' Plenty
caelus
camera mod
Clumps
coltrya
CosmeticArmorReworked
Cucumber
Cyclic
Doggy Talents
elevatorid
Enchantmentdescriptioms
FastLeafDecay
FriendlyFire
Crayfish Furniture
Gravestone
ironchest
IronJetpacks
lumberjack
lycanitesmobs
modnametooltip
Neat+
Placebo
SilentGear and SilenLib
supertools
TrashSlot
u_team_core
UsefulBackpacks
Xaeros Minimap

**Comment by Morpheus1101** [comment]
I have same issue using Forge 28.0.91 .. Snippet form Latest.log mentioning JEI @ https://pastebin.com/cPnVqPQC

**Comment by Alex1331xela** [comment]
Same issue here, on Minecraft v1.14.4 and Forge v28.0.74

**Comment by Gbergz** [comment]
Same issue!
MC ver: 1.14.4
Forge ver: 28.0.93
JEI Version: 6.0.0.11

**Comment by Ommina** [comment]
Well.  Until we see some actual logs, we have no way of knowing if this is the same issue or not.

_Please_.  Create a new issue, include version numbers, and a link to logs.  There is a lot of wobble within Forge right now, between the Fluid API and the recent renames.  But it's difficult to even begin to work out a particular cause without the basics.

**Comment by Morpheus1101** [comment]
I provided logs an Gbergz proivided version info...

**Comment by Morpheus1101** [comment]
JEI on its own works as intended using 
Forge: 28.0.94
JEI: 6.0.0.11
