### ISSUE TITLE
1.14.4 Game crash. "fluids.FluidStack"

### ISSUE THREAD

**Issue by wertyleigh** [mezz/JustEnoughItems#1717]
Hi there,
After playing with my mods list and inserting and removing to try and figure out which mod was causing the problem - I have narrowed it down to JEI, which sucks. 
Chucked the crash log in, Just trying to fix it.
You know how it be.

Any ideas guys?

[https://gist.github.com/wertyleigh/e4ecdb2b78d1d0f5082178e12f4181cc](url)

**Comment by Ommina** [comment]
Update Forge as well. JEI .11 adds support for the new Forge fluids, which were only very recently added.  (28.0.73, IIRC)

@mezz -- Shouldn't users be getting the "JEI requires Forge Version foo (you have version (foo-bar))" screen instead of (or, at least, in addition to) a crash?

**Comment by wertyleigh** [comment]
I'm pretty sure I have the latest version of Forge. It tells me its a beta release?

**Comment by Ommina** [comment]
According to the logs: `Forge: net.minecraftforge:28.0.46`

The most recent version of Forge is `28.0.92`. I suppose it is fair to call it a Beta, sure.
