### ISSUE TITLE
JEI doesn't show up in 1.14.4 world (With log file link)

### ISSUE THREAD

**Issue by DRDeathKitty** [mezz/JustEnoughItems#1718]
Minecraft version: 1.14.4
Forge version: 28.0.93
JEI version: jei-1.14.4-6.0.0.11

Pastebin link for log output: https://pastebin.com/RXzhY6np

**Comment by DRDeathKitty** [comment]
Just an update, i tried jei version jei-1.14.4-6.0.0.10 and it works

**Comment by Ommina** [comment]
6.0.0.11 provides support for the new (well, week ago now) custom Fluid API.  If you don't yet need custom fluid support (and you probably don't), you can safely stay with 6.0.0.10 until the dust settles.  Downgrading Forge could also be an option, but sticking with 6.0.0.10 for the time being strikes me as the better choice.
