### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by TrainBoy65** [mezz/JustEnoughItems#1719]
The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.texture.TextureAtlasSprite.field_195670_c from class mezz.jei.color.ColorGetter

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
