### ISSUE TITLE
Smelting EXP text extends past the right edge of the recipe

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#172]
This doesn't really matter for JEI's recipe view, but causes issues for JustEnoughTooltips.

**Comment by Prospector** [comment]
Also just a stupid enhancement, exp text should be green :P

**Comment by mezz** [comment]
I just tried making it green and it looked truly horrible no matter what shade I used, sorry.

**Comment by Prospector** [comment]
What if it was green with black outline (see the numbers over the
experience bar in survival)

**Comment by mezz** [comment]
Tried that too, the grey background just doesn't like green text.

**Comment by Prospector** [comment]
Ah that's fine. It doesn't matter at all :P
