### ISSUE TITLE
When i open my inventory, the minecraft crash

### ISSUE THREAD

**Issue by Youma59** [mezz/JustEnoughItems#1720]
[crash-2019-09-10_19.49.53-client.txt](https://github.com/mezz/JustEnoughItems/files/3598086/crash-2019-09-10_19.49.53-client.txt)

**Comment by border999** [comment]
even without looking at the log, I can give a good guess why your crashing. you may have typed something into your JEI searchbar that pulled up an item that is having problems being rendered. If that's the case then you need to find a way to clear out whatever you were searching for without opening your inventory.
The other possibility is that you picked up an item that is also having problems being rendered, this one is simple, die and let your stuff drop somewhere safe. Then try to open your inventory when you respawn.

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: BuildCraft Silicon
	Ingredient Info: 1xitem.Facade@0 buildcraftsilicon:plug_facade nbt:{facade:{isHollow:0b,states:[{state:{Properties:{snowy:"false"},Name:"wildnature:brown_grass_block"}}]}}
```

This is an issue with a BuildCraft facade for `wildnature:brown_grass_block`
Please report this to BuildCraft here: https://github.com/BuildCraft/BuildCraft/issues
