### ISSUE TITLE
Railcraft crashing in JEI

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [mezz/JustEnoughItems#1721]
Can't browse Railcraft stuff: https://paste.dimdev.org/eroxerubep.rb

**Comment by border999** [comment]
don't know what to say man, know anyway to clear what is being searched in JEI without opening it up in-game?

**Comment by border999** [comment]
maybe also bring this up to the people over at Railcraft to see if they can fix the rendering problem on their end.

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
  Ingredient Mod: Railcraft
  Ingredient Info: 1xtile.railcraft.actuator@2 railcraft:actuator
```

This has been reported to Railcraft here: https://github.com/Railcraft/Railcraft/issues/1882
Please make sure to link related issues together so that mod authors can work together.

**Comment by border999** [comment]
@mezz on this note. Could you give some advice on how to remove only that item from JEI rendering it? Or some advice on how to  clear out the search bar without actually going into my inventory. Because, you know, that'd crash me

**Comment by Ommina** [comment]
There is also some indication that foamfix is directly or indirectly involved.  See https://github.com/Railcraft/Railcraft/issues/1806, for example.  So if you are affected by this, you may have some success disabling (if only temporarily) foamfix.

Which is not to say that it wouldn't _also_ be worthwhile blacklisting the item.
