### ISSUE TITLE
Forge 28.1.1 down to 28.0.95 consistently crashes

### ISSUE THREAD

**Issue by ComicalTNM** [mezz/JustEnoughItems#1722]
Here is the log:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 9/12/19 8:59 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at net.silentchaos512.lib.util.PlayerUtils.getPersistedDataSubcompound(PlayerUtils.java:73) ~[?:4.3.1+39] {}
	at net.silentchaos512.lib.event.InitialSpawnItems.onPlayerLoggedIn(InitialSpawnItems.java:89) ~[?:4.3.1+39] {}
	at net.silentchaos512.lib.event.InitialSpawnItems$$Lambda$3560/125499510.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$1949/1025587755.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:43) ~[?:?] {}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:205) ~[?:?] {}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?] {}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?] {}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224) ~[?:?] {}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3008768992 bytes (2869 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.95.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.95.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.95.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.95.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.95.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.95
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		[1.14.4]+SecurityCraft+v1.8.12.2.jar SecurityCraft {securitycraft@v1.8.12.2 DONE}
		Apotheosis-1.14.4-2.3.1.jar Apotheosis {apotheosis@2.3.1 DONE}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		BadMobs-1.14.4-3.0.1.jar BadMobs {badmobs@3.0.1 DONE}
		betteranimalsplus-1.14.4-7.1.0.jar Better Animals Plus {betteranimalsplus@7.1.0 DONE}
		BetterAnimationsCollection2-v1.1b4-1.14.4.jar Better Animations Collection 2 {betteranimationscollection2@1.1b4 DONE}
		BetterThanMending-1.3.1.jar BetterThanMending {betterthanmending@1.3.1 DONE}
		bettertridentreturn-1.14.4-1.0.0.jar Better Trident Return {bettertridentreturn@1.0.0 DONE}
		BiomesOPlenty-1.14.4-9.0.0.251-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.251 DONE}
		caelus-FORGE-1.14.4-0.11.jar Caelus API {caelus@FORGE-1.14.4-0.11 DONE}
		camera-1.4.5.jar Camera Mod {camera@1.4.5 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		colytra-FORGE-1.14.4-2.0-beta4.jar Colytra {colytra@FORGE-1.14.4-2.0-beta4 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		Cucumber-1.14.4-2.0.3.jar Cucumber Library {cucumber@2.0.3 DONE}
		Cyclic-1.14.4-0.0.9.jar Cyclic {cyclic@1.14.4-0.0.9 DONE}
		elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 DONE}
		EnchantmentDescriptions-1.14.4-1.3.3.jar EnchantmentDescriptions {enchdesc@1.3.3 DONE}
		extragolems-9.0.1.jar Extra Golems {golems@TODO-golems_version DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		FriendlyFire-1.14.4-3.0.1.jar FriendlyFire {friendlyfire@3.0.1 DONE}
		furniture-7.0.0-pre5-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 DONE}
		goodnightsleep-1.14.4-0.3.0.jar Good Night's Sleep {goodnightsleep@0.3.0 DONE}
		gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 DONE}
		guardillagers-1.14.4-1.0.1.jar GuardIllagers {guardillagers@1.0.1 DONE}
		ironchest-1.14.4-9.0.4.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		IronJetpacks-1.14.4-2.0.2.jar Iron Jetpacks {ironjetpacks@2.0.2 DONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 DONE}
		mcjtylib-1.14-3.5.6-alpha.jar McJtyLib {mcjtylib@NONE DONE}
		MobBattleMod-1.14.4-2.3.2.jar Mob Battle Mod {mobbattle@2.3.2 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		Neat+1.5-19.jar Neat {neat@1.5-19 DONE}
		Placebo-1.14.4-2.2.0.jar Placebo {placebo@2.2.0 DONE}
		rftoolsbase-1.14-0.0.3-alpha.jar RFToolsBase {rftoolsbase@NONE DONE}
		rftoolspower-1.14-1.2.3-alpha.jar RFToolsPower {rftoolspower@NONE DONE}
		SilentGear-1.14.4-1.3.9+58.jar Silent Gear {silentgear@1.3.9+58 DONE}
		SilentLib-1.14.4-4.3.1+39.jar Silent Lib {silentlib@4.3.1+39 DONE}
		supertools-1.14.4-2.3.jar Vanilla+ Tools {supertools@version DONE}
		TrashSlot_1.14.4-10.4.5.jar TrashSlot {trashslot@10.4.5 DONE}
		u_team_core-1.14.4-2.7.0.129.jar U Team Core {uteamcore@2.7.0.129 DONE}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 DONE}
		forge-1.14.4-28.0.95-universal.jar Forge {forge@28.0.95 DONE}
		forge-1.14.4-28.0.95-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['SirStralelvan'/215, l='Modded Survival (Minigames!)', x=82.65, y=77.00, z=-0.64]]
	Data Packs: vanilla, mod:uteamcore, mod:usefulbackpacks, mod:trashslot, mod:supertools, mod:silentlib, mod:silentgear, mod:securitycraft, mod:rftoolspower, mod:rftoolsbase, mod:placebo, mod:neat, mod:modnametooltip, mod:mobbattle, mod:mcjtylib, mod:jei, mod:ironjetpacks, mod:ironchest, mod:guardillagers, mod:gravestone, mod:goodnightsleep, mod:golems, mod:friendlyfire, mod:forge, mod:fastleafdecay, mod:enchdesc, mod:elevatorid, mod:cyclic, mod:cucumber, mod:cosmeticarmorreworked, mod:colytra, mod:clumps, mod:cfm, mod:camera, mod:caelus, mod:biomesoplenty, mod:bettertridentreturn, mod:betterthanmending, mod:betteranimationscollection2, mod:betteranimalsplus, mod:badmobs, mod:appleskin, mod:apotheosis
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

I deleted Doggytalents and xaeros minimap but it still crashed so I added them back.

**Comment by TehNut** [comment]
`net.silentchaos512.lib.util.PlayerUtils.getPersistedDataSubcompound(PlayerUtils.java:73)`

This is caused by SilentLib

**Comment by mezz** [comment]
Thanks for the report!
Please report this to SilentLib here: https://github.com/SilentChaos512/SilentLib/issues
