### ISSUE TITLE
Energy Converter FE Producer/Consumer Wont Show Up

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1726]
As title says it wont show up i always have to cheat the item to get it. https://i.imgur.com/NF1EbmE.png

**Comment by mezz** [comment]
Thanks for the report!
Can you please explain what will not show up? Do you mean the recipe, or something else?

**Comment by ghost** [comment]
Yes the recipe

**Comment by Ommina** [comment]
See also https://github.com/Xalcon/EnergyConverters/issues/48

**Comment by mezz** [comment]
Thanks. This is not likely to be a JEI issue, so I'll follow that issue and close this one for now. We can reopen it if we find out there is something wrong on JEI's side.
