### ISSUE TITLE
Game crashes upon creation of a new world OR joining a world

### ISSUE THREAD

**Issue by pastellarium** [mezz/JustEnoughItems#1727]
As the title says. I've tried with and without other mods, tried with forge version 28.1.0 and 28.0.93, all have the same issue

Log: https://gist.github.com/VisualFootprint/374831c16a24a8ce256ca828774ece82

**Comment by mezz** [comment]
Thanks for the report!
`hs_err_pid` errors come from crashes in the JVM itself. This is not caused by JEI, it is actually a bug in Java.
Please try updating your version of Java.
