### ISSUE TITLE
[1.14] Not all item group members are shown

### ISSUE THREAD

**Issue by rubensworks** [mezz/JustEnoughItems#1728]
_This issue was originally reported to the Everlasting Abilities issue tracker: https://github.com/CyclopsMC/EverlastingAbilities/issues/127_

The Everlasting Abilities abilities mod has a Totem item, which has several NBT-based sub-items.
Using the `fillItemGroup` method, the subitems are filled into the creative tab.
However, **when looking up the Totem with JEI, only one variant is shown**.
Is it possible that JEI is doing some kind of filtering to hide these other subitems?

I'm pretty sure that JEI is properly calling `fillItemGroup` on the item, since the single item that is shown contains valid NBT.

This is the relevant code for filling the item groups: https://github.com/CyclopsMC/EverlastingAbilities/blob/release-1.14/src/main/java/org/cyclops/everlastingabilities/item/ItemAbilityTotem.java#L48-L58
So if you see anything that is wrong on my end, be sure to let me know.

One remark: the totem variants are based on a custom Forge registry. So this is only populated after the item registry.

**Comment by TehNut** [comment]
You need to register a [subtype interpreter](https://github.com/mezz/JustEnoughItems/blob/1.14/src/api/java/mezz/jei/api/ingredients/subtypes/ISubtypeInterpreter.java)

**Comment by rubensworks** [comment]
So this is new behaviour in 1.14?
Items used to be distinguishable by NBT back in 1.12.

It's a bit unfortunate that mods (like Everlasting Abilities) that add NBT-based items now have to provide JEI integration. I'm wondering if no better scalable solution is possible.

**Comment by TehNut** [comment]
This was also required in 1.12 and earlier
