### ISSUE TITLE
Jei Bookmarks hijack scroll for containers on the left

### ISSUE THREAD

**Issue by Tfarcenim** [mezz/JustEnoughItems#1730]
![2019-09-18_21-54-44](https://user-images.githubusercontent.com/44327798/65208312-a320d980-da62-11e9-8efa-00a3a8ef675e.gif)

In addition, attempting to scroll the gui scrolls the bookmarks instead.

Disabling bookmarks stops the effect from happening

**Comment by mezz** [comment]
Thanks for the report!
You can tell JEI about this extra inventory area by implementing 
[`IGuiContainerHandler#getGuiExtraAreas`](https://github.com/mezz/JustEnoughItems/blob/1.14/src/api/java/mezz/jei/api/gui/handlers/IGuiContainerHandler.java).

**Comment by Tfarcenim** [comment]
That moved the items and the apparent deletion area (tooltip still shows) out of the way, but did not stop the scroll hijacking.
 
https://github.com/Tfarcenim/crafting-station/blob/rewrite/src/main/java/com/tfar/craftingstation/jei/JeiPlugin.java#L44

**Comment by mezz** [comment]
Hmm ok. This is likely a JEI 1.14 bug then.

**Comment by desht** [comment]
It looks like it also does the same for areas on the right (i.e. the main ingredient display area) - see https://youtu.be/6YYEDUS7Hho

I'm defining the GUI area as you can see (JEI moves items out of the way correctly when the side panel expands), but scrolling the mouse wheel while over that GUI area still gets intercepted by JEI, when it should be ignored and passed on to PneumaticCraft.
