### ISSUE TITLE
Minecraft failed to start

### ISSUE THREAD

**Issue by Benistcreative** [mezz/JustEnoughItems#1731]
Hello everyone,
I wanted to start the Dungeons, Dragons and Space Shuttles Modpack via the Twitch Curse launcher and just before finishing I got a message displayed, that JEI prevented Minecraft from starting. The message told me to contact the JEI support so I hope I'm right in posting the issue here. 
Here is the crash report that I got generated: https://paste.dimdev.org/disupizosu.mccrash
Hope that's all you need and would be glad for advice as to how I solve my Problem.
have a nice day
kind regards,
Benistcreative

**Comment by Ommina** [comment]
`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`

You'll need to provide the pack more RAM.  (How will vary with the launcher in use.)

It looks like you are presently giving it 4GB.  Try five or six.
