### ISSUE TITLE
JEI wont show the energy in cables/cells from other mods

### ISSUE THREAD

**Issue by Toplix** [mezz/JustEnoughItems#1732]
JEI wont show me, how many energy is in the cable/cell.
![cant see](https://user-images.githubusercontent.com/55629123/65375057-71418a00-dc91-11e9-9b74-dacd50c11d51.png)

**Comment by TehNut** [comment]
That's HWYLA, not JEI. Either the mod does not support showing energy in the tooltip or you haven't enabled HWYLA's builtin energy viewer.

**Comment by Toplix** [comment]
> That's HWYLA, not JEI. Either the mod does not support showing energy in the tooltip or you haven't enabled HWYLA's builtin energy viewer.

What is an Mod which can show me the energy? Or how can i activate this on HWYLA?

**Comment by TehNut** [comment]
You can enable it in the settings
