### ISSUE TITLE
JEI crashes the game on startup of certain worlds

### ISSUE THREAD

**Issue by Alex1331xela** [mezz/JustEnoughItems#1733]
Minecraft Version: 1.14.4
Forge Version: 28.1.10

When trying to start a world created and last played on Forge v28.0.45 - v28.0.58, JEI crashes the game on world startup. When trying to start an identical copy of the world last played on Forge v28.0.83+, however, it does not crash and loads into the world as expected.

A few crash logs:
[crash-2019-09-21_01.21.51-server.txt](https://github.com/mezz/JustEnoughItems/files/3638948/crash-2019-09-21_01.21.51-server.txt)
[crash-2019-09-21_01.25.52-server.txt](https://github.com/mezz/JustEnoughItems/files/3639074/crash-2019-09-21_01.25.52-server.txt)
[crash-2019-09-21_13.52.12-server.txt](https://github.com/mezz/JustEnoughItems/files/3638947/crash-2019-09-21_13.52.12-server.txt)

**Comment by TehNut** [comment]
These crashes are all caused by Mob Rebirth.

**Comment by Alex1331xela** [comment]
Oh shoot, my bad then. Sorry, seemed removing JEI fixed the crashing during my testing, but it must have been another factor then. Thanks for taking a look.
