### ISSUE TITLE
[1.14.4] Add support for stone cutter receips

### ISSUE THREAD

**Issue by MatthiasMann** [mezz/JustEnoughItems#1735]
Using jei-1.14.4-6.0.0.12 the recipes for the stone cutter are not shown.

**Comment by kreezxil** [comment]
I second this, we're on 1.15 now. is it possible to put a bounty on this?

**Comment by hanetzer** [comment]
@mezz could probably close this now :)

**Comment by kreezxil** [comment]
does JEI recognize stonecutter recipes now?

**Comment by mezz** [comment]
Yep! Support for stonecutter recipes was added here by hanetzer: https://github.com/mezz/JustEnoughItems/pull/1950
