### ISSUE TITLE
[1.12.2]Error thrown whilst accessing JEI internals

### ISSUE THREAD

**Issue by SamLam140330** [mezz/JustEnoughItems#1736]
Hello, I am using bungeecord in my server. When player join to my server, it will direct them to the lobby server with a compass to choose a game you want including mod survival. However, when player click it, it didn't work. In the server console, no any error. In the client log, it comes with some error related to jei.
https://pastebin.com/PSQdTq86
Does anyone know how to fix it?

**Comment by TehNut** [comment]
This is an NEI issue

**Comment by SamLam140330** [comment]
OK, thank you
