### ISSUE TITLE
Rendering issues?

### ISSUE THREAD

**Issue by Poke5555** [mezz/JustEnoughItems#1738]
when ever i use the search bar items will disappear or or just become a square.
https://i.imgur.com/SlBqdk0.png
here is my modlist
https://pastebin.com/jzMF3fw9
i have removed the jei addons and it still doesnt render correctly.
thanks for the help :)

mc version 1.12.2 jei version 	jei_1.12.2-4.15.0.268

**Comment by Poke5555** [comment]
if i make my screen small enough to get a second page then items on that page will render but not the first.

**Comment by Poke5555** [comment]
It is being caused by Clef https://www.curseforge.com/minecraft/mc-mods/clef
not sure why but i figured i would let you know :)

**Comment by mezz** [comment]
Thanks for reporting and following up for anyone else who might have the same issue!
