### ISSUE TITLE
Held ItemStacks are rendered behind the hover overlay

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#174]
Title will probably confuse you, images below should let you understand. It's really no big deal, but I noticed it and figured I would let you know.

![2016-02-16_19 51 29](https://cloud.githubusercontent.com/assets/6166773/13099433/f1cdacc8-d4e6-11e5-9b2a-01b576b6fa1d.png)
![2016-02-16_19 51 34](https://cloud.githubusercontent.com/assets/6166773/13099434/f1d15ac6-d4e6-11e5-848c-45e9883c1a80.png)

**Comment by mezz** [comment]
Thanks for the report!
Hm that's strange.
