### ISSUE TITLE
JEI calls the wrong burn time method on 1.14 causing JEI to not work at all.

### ISSUE THREAD

**Issue by jaredlll08** [mezz/JustEnoughItems#1743]
Log: https://gist.github.com/jaredlll08/d927e1c2e6b1a00c0388e763867008d1

So basically, I have a CrafttTweaker script which is removing an item (white wool) from the wool tag, doing so causes JEI to crash.

Looking at the code, I think it is basically, JEI looks at the map and caches fuel items, then CrafttTweaker comes in and removes items from tags. JEI then goes and tries to get the burn values of those items, calling this method: https://gist.github.com/jaredlll08/214f60eb4c020ea1590f686cc05710ba
here:
https://github.com/mezz/JustEnoughItems/blob/1.14/src/main/java/mezz/jei/plugins/vanilla/cooking/fuel/FuelRecipeMaker.java#L26

Which regenerates the map of fuels based on tags, because white wool is now no longer in that map, but is still in your fuel cache, it tries to get it's value, and ends up using the default of 0 as defined here:

https://github.com/mezz/JustEnoughItems/blob/1.14/src/main/java/mezz/jei/plugins/vanilla/cooking/fuel/FuelRecipeMaker.java#L41

Current thoughts on a fix would be:
Don't use the Deprecated vanilla method and instead use the Forge method, as I believe that is updated when tags are updated.

If you need the 1.14 version of CrafttTweaker to test this yourself, just reach out on discord :)

**Comment by mezz** [comment]
Thanks for the report!
I am pretty sure I wrote this before the Forge burn hook was implemented in 1.14. Thanks for the heads up, I'll update it now.
