### ISSUE TITLE
Crash on Loading

### ISSUE THREAD

**Issue by IamStig** [mezz/JustEnoughItems#1744]
Minecraft 1.14.4, forge-1.14.4-28.1.25, jei-1.14.4-6.0.0.10 (Also tried downgrading to .8 & .9)
I realise that it is not a definite issue with JEI but with 8, 9 or 10 installed it crashes and without JEI installed it runs, maybe there is an incompatible mod I have installed or just one updated.
New mods installed are Acceleratorcraft, better advancements, Click Machine, ComPatched Storage, Silent's Mechanisms, Placebo and Useful Railroads. Some mods have been updated since JEI was working but I can't recall which JEI version.
I'll keep trying to find the cause, I miss JEI if it isn't there
https://gist.github.com/IamStig/f908153b8bbaca957f61c2dca0ab1080

**Comment by Ommina** [comment]
For fluid support (which is where JEI is getting upset), you'll need 6.0.0.11 at least.  But might as well go for 6.0.0.12 while you're in there.

**Comment by TehNut** [comment]
Update JEI

**Comment by IamStig** [comment]
Oops, I actually downloaded JEI 6.0.0.13 when I was updating .....but somehow missed transferring it to the mods folder.
Can confirm that was the problem and it is working now. 
Thank you both
