### ISSUE TITLE
basically an Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items problem ;-;

### ISSUE THREAD

**Issue by Merkymurk** [mezz/JustEnoughItems#1747]
Sorry I'm new to dealing with twitch mods, so i tried to run a modpack on twitch but after loading the message on the title appeared, I tried googling this problem and i found this hithub page with a few of these problems. 
[crash-2019-10-01_17.16.25-client.txt](https://github.com/mezz/JustEnoughItems/files/3675546/crash-2019-10-01_17.16.25-client.txt)

**Comment by Ommina** [comment]
`java.lang.OutOfMemoryError: GC overhead limit exceeded`

Give it more memory.

**Comment by Merkymurk** [comment]
I got 16 gb ram, how do I give it more memory though?
