### ISSUE TITLE
Hotkey unintentionally drops additional items

### ISSUE THREAD

**Issue by lunofe** [mezz/JustEnoughItems#1753]
Minecraft: 1.14.4
Forge: 28.1.26 (_Already tried others, they're affected as well_)
JEI: 6.0.0.13

When pressing Control+Q while pointing to an empty slot in the inventory, the item selected in the hotbar will be dropped.
[Watch this short video to see it](https://youtu.be/5l_gX3neEec).

**Comment by mezz** [comment]
Thanks for the report!
Does this only happen when JEI is installed? JEI does not use that hotkey, so it is unclear to me how JEI might be involved here.

**Comment by lunofe** [comment]
Hi, I just tried it again. It occurred to me that it could (or must) be because of Forge, if JEI does not use the hotkey. Turns out, it's really Forge. I'm sorry I did not think about that before I reported the "bug".
