### ISSUE TITLE
[1.14.4] Soft-crash on server join

### ISSUE THREAD

**Issue by NielsPilgaard** [mezz/JustEnoughItems#1754]
Hello!

Whenever I log into my server, I instantly soft-crash. The latest.log only mentions JEI, so I'm reporting this to you guys, although I know JEI is most likely not the cause.

[Part of latest.log, right after joining the server](https://gist.github.com/NillerMedDild/13a78908078840bf11d20203f535e6b8)
[Complete latest.log raw](https://gist.githubusercontent.com/NillerMedDild/305c902915de65b7005d998e324e2264/raw/9caa1d2836679b5a38e16024d6b05cc18e6be23f/gistfile1.txt)
[Complete latest.log non-raw](https://gist.github.com/NillerMedDild/305c902915de65b7005d998e324e2264)

## Versions
- Forge 1.14.4-28.1.37
- jei-1.14.4-6.0.0.13

**Comment by mezz** [comment]
Thanks for the report!

```
[20:18:40] [Netty Client IO #1/ERROR]: Channels [cosmeticarmorreworked:main] rejected their server side version number during listping
[20:21:41] [Client thread/INFO]: Connecting to mc.dbgamehost.com, 25567
[20:21:44] [Netty Client IO #2/ERROR]: Channels [cosmeticarmorreworked:main] rejected their server side version number
[20:21:44] [Netty Client IO #2/ERROR]: Terminating connection with server, mismatched mod list
```

Based on this, it looks like the server is rejecting you because the `cosmeticarmorreworked` mod version you have does not match their version.

**Comment by NielsPilgaard** [comment]
Yes that was indeed an issue, but I fixed that, and then got this issue.

**Comment by NielsPilgaard** [comment]
The issue is still present, but it no longer soft-crashes me, so that's nice ^^

I deleted the world, reinstalled all mods and updated Forge. No idea if it was a coincidence, or one of those things (or several) allowed me to join the server.
