### ISSUE TITLE
Rendering Ingredient Crash

### ISSUE THREAD

**Issue by ichimo** [mezz/JustEnoughItems#1756]
https://paste.dimdev.org/virosupiti.mccrash

Crash when rendering a biome crystal from random things, used to be a different item, then downgraded random things version and just changed which item it says caused the crash.

**Comment by ichimo** [comment]
Able to get around crashing on opening the inventory I delete the worldsettings in jei config.  Searching or getting the item/items onto gui will crash the client still.

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
  Ingredient Mod: Random Things
  Ingredient Info: 1xtile.biomeStone@0 randomthings:biomestone
```
Please report this to Random Things here: https://github.com/lumien231/Random-Things/issues
