### ISSUE TITLE
JEI not loading on Forge 28.0.45 (Minecraft Version 1.14.4)

### ISSUE THREAD

**Issue by DeadShot2748** [mezz/JustEnoughItems#1757]
The changelog says that support for Forge 28.0.45 has been added, but when I try to load the mod, the game just says that Forge 28.1.0 is needed.

**Comment by Ommina** [comment]
Well, yes.  It was 28.0.45 at one point, but with the release of the Forge RB, the minimum requirements were changed to 28.1.0.  You'll need to update Forge or downgrade JEI.

**Comment by DeadShot2748** [comment]
Which version of JEI do you recommend I use for Forge 28.0.45?
