### ISSUE TITLE
JEI stuck on "Building ingredient filter..."

### ISSUE THREAD

**Issue by matyklug18** [mezz/JustEnoughItems#1758]
i have a big modpack(300 mods) but it loaded fine with over 500, but it doesnt now. the last thing i heard from the log is "building ingredients filter". happens every time, minecraft doesnt load.

**Comment by matyklug18** [comment]
update: does load without optifine, however optifine is needed in the pack

**Comment by Tahakk** [comment]
Optifine is not needed. But if you want it just post your crash log on the optifine github

**Comment by matyklug18** [comment]
well, if you think 10 fps is ok... but yeah, gonna post it to optifine then.

**Comment by Tahakk** [comment]
if you play with 10fps I doubt that optifine will give you that much for it to be playable. At the same time not all PC's are ableto run these huge packs

**Comment by matyklug18** [comment]
it was able to with 500 mods, i dunno why it wouldnt with 300...
