### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by NeoSpace29** [mezz/JustEnoughItems#1761]
hello im playing my game and for some reason tbh idk why but game keeps crashing and I have vanilla fix installed and JEI was one of the mods that was a potential causes of the crash
[all the mods 3 crash report.txt](https://github.com/mezz/JustEnoughItems/files/3721040/all.the.mods.3.crash.report.txt)

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
  Ingredient Mod: Forestry
  Ingredient Info: 1xitem.crated.forestry.fruits.6@0 forestry:crated.forestry.fruits.6
```
This looks like an issue with rendering an item from Forestry. 
Please report to them here: https://github.com/ForestryMC/ForestryMC/issues
