### ISSUE TITLE
Crash on shift load recipe into a crafting station

### ISSUE THREAD

**Issue by DeaSTL** [mezz/JustEnoughItems#1763]
This may just be a one off thing because it seemed kind of random.
I just thought that I should report it.

I tried to shift load a recipe into a crafting station from Tinkers Construct and it loaded 8 items and the 9th one crashed the game. Could be a caching issue with my game's current state(Not sure...).
 * https://gist.github.com/DeaSTL/fb9a90cc5fd380cf29f26790dffd52d1

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue with rendering an Ex2 item (weird!).
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Extra Utilities 2
	Ingredient Info: 1xtile.extrautils2:machine@0 extrautils2:machine nbt:{Type:"extrautils2:generator_survival"}
```
Please report this to them here: https://github.com/rwtema/Extra-Utilities-2-Source/issues
