### ISSUE TITLE
Mod does not seem to work, no recipes or any signs of it enabled show in-game.

### ISSUE THREAD

**Issue by WendigoTheDrunk** [mezz/JustEnoughItems#1765]
I am unsure how to go about this since I am new to this but I installed the mod into a modpack I am working and now no recipes show at all, Previously had NEI installed as default but I uninstalled them and have now encountered the recipe bug.

If there is anything I can do to help us find a fix let me know and I will update.

(JEI version in use is jei-1.14.4-6.0.0.18.jar)

Modpack includes mods like LOTR and many smaller mods that just add items or change graphics.

I have tried different versions of Minecraft to see if any of them would be a better match and none have worked so far.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by zackadiax24** [comment]
I have the same issue, in 1.14.4 using any version of your mod.
JEI isnt showing, as if i dont have it installed. The controls still show up in options and it still shows in settings page. I have tried the hide/show jei key  combo (even rebound it to a single key to see if that was the issue) I cant see recipes either.
Hope this helps.
https://gist.github.com/zackadiax24/3c861921f4ab99b4bd88b58a88456a37

**Comment by mezz** [comment]
@zackadiax24 It looks like your log has an incredible number of errors from various mods.
Please try removing some mods to see if one of them is conflicting with JEI.
Once you find out which mod is conflicting, I can work with them on a fix.
