### ISSUE TITLE
Inventory searching issue

### ISSUE THREAD

**Issue by xama45** [mezz/JustEnoughItems#1766]
When i load into my server i open my inventory just fine when i go to search for an item it crashes my game. https://gyazo.com/96d48e26b8ce87f0cfb76eb6c5b5cd9b

**Comment by TehNut** [comment]
If you open the crash report it will tell you what item was being rendered. Report it to that mod

**Comment by xama45** [comment]
https://gyazo.com/0329d497f1aea8ed631da1004e10c127 this crash report means nothing to me where do i start?

**Comment by TehNut** [comment]
Well if you link the report itself instead of sending screenshots of little bits of it, I could point you in the right direction.

**Comment by xama45** [comment]
i
[crash-2019-10-16_23.14.01-client.txt](https://github.com/mezz/JustEnoughItems/files/3741595/crash-2019-10-16_23.14.01-client.txt)

**Comment by TehNut** [comment]
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Forestry
	Ingredient Info: 1xitem.crated.natura.nether_glowshroom.2@0 forestry:crated.natura.nether_glowshroom.2
```

**Comment by xama45** [comment]
thats causing the crash?

**Comment by xama45** [comment]
Iam i in the right place to get this fixed?

**Comment by Tamaized** [comment]
I didn't know this was a Forestry issue tracker

**Comment by mezz** [comment]
Thanks for the report!
Please report to Forestry here: https://github.com/ForestryMC/ForestryMC/issues
