### ISSUE TITLE
[1.14.4] Fluids with colors aren't being rendered in JEI (present but 'invisible')

### ISSUE THREAD

**Issue by Wabbit0101** [mezz/JustEnoughItems#1769]
Forge version: **1.14.4-28.1.39**
JEI version: **jei-1.14.4:6.0.0.16**
Java: **Java 8**

If a custom Fluid has a color assigned to its attributes, JEI does not render the fluid texture properly (as in not at all but the item is present in JEI if you hover over it). I tried: a MaterialColor's colorValue, hardcoded rgb int as in '0xff0000', and a few other things, thinking perhaps the color value needed to be encoded somehow for FluidStackRenderer. No luck. When I removed the color completely, everything worked swimmingly and the fluid texture was drawn properly in JEI.

[code snip -- assume 'still' and 'flowing' are location of textures and MILK/FLOWING_MILK are static FlowingFluid references]
```
MILK = new ForgeFlowingFluid.Source(new ForgeFlowingFluid.Properties(()->MILK,()->FLOWING_MILK,
                                      FluidAttributes.builder(still,flowing)
                                                     .viscosity(1200).density(1200).color(MaterialColor.SNOW.colorValue))
                                     .block(()->MILK_BLOCK).bucket(()->Items.MILK_BUCKET).renderLayer(BlockRenderLayer.SOLID));
FLOWING_MILK = new ForgeFlowingFluid.Flowing(new ForgeFlowingFluid.Properties(()->MILK,()->FLOWING_MILK,
                                      FluidAttributes.builder(still,flowing)
                                                     .viscosity(1200).density(1200).color(MaterialColor.SNOW.colorValue))
                                     .block(()->MILK_BLOCK).bucket(()->Items.MILK_BUCKET).renderLayer(BlockRenderLayer.SOLID));

```

**Comment by mezz** [comment]
Thanks for the report!
Is there a mod I can try out with this problem, so I can easily see the issue and debug it?

**Comment by Wabbit0101** [comment]
Alas no. Just started tackling fluids for 1.14. I'll see if I can attach a little test mod later today.

**Comment by Wabbit0101** [comment]
Ok. So just got to placing fluids in world. Same issue so I knew it's ma code dats broken. Turns out to be a RTM moment: found in FluidAttributes (univ bucket reference is old but format still applies):
```
    /**
     * Color used by universal bucket and the ModelFluid baked model.
     * Note that this int includes the alpha so converting this to RGB with alpha would be
     *   float r = ((color >> 16) & 0xFF) / 255f; // red
     *   float g = ((color >> 8) & 0xFF) / 255f; // green
     *   float b = ((color >> 0) & 0xFF) / 255f; // blue
     *   float a = ((color >> 24) & 0xFF) / 255f; // alpha
     */
    private final int color;

```

**Comment by mezz** [comment]
Thanks for the followup, good to know it's working now!
