### ISSUE TITLE
I can't load my world (crash)

### ISSUE THREAD

**Issue by sepsol** [mezz/JustEnoughItems#1771]
[https://gist.github.com/SepSol/0ab8c219aed5a329d7dc9aa392cc57ff](https://gist.github.com/SepSol/0ab8c219aed5a329d7dc9aa392cc57ff)

**Comment by mezz** [comment]
Thanks for the report!
Please update your Forge and JEI to the latest versions available. I believe this has been fixed, let me know.

**Comment by sepsol** [comment]
I use forge 28.1.0
And JEI 6.0.0.13
And it works fine

If I install and use any of the recent versions (haven't tried them all, but the latest as of now is 6.0.0.18) my world stays at loading screen.

Also hiding items in JEI seems to not work?

**Comment by UnexoN** [comment]
I have the same problem, but on MC 1.12.2
