### ISSUE TITLE
When Disconnecting from vanilla server, crash with this report

### ISSUE THREAD

**Issue by Shadder-1-5** [mezz/JustEnoughItems#1772]
When i Disconnect from a vanilla server, Craftadia, i crash with this report https://pastebin.com/ntrSVdqi

**Comment by mezz** [comment]
Thanks for the report!
Does this happen if you have just JEI and Forge, with no other mods?
Please try to narrow down the mod list to see if there is a conflicting mod.

**Comment by Shadder-1-5** [comment]
i removed all other mods, and made a whole new mc directory to install it in, but still crashes, ill reinstall jei to see if that fixes it.

**Comment by Shadder-1-5** [comment]
yep, i reinstalled jei and it still crashed from the Craftadia server when disconnecting, But the server has a special resource pack, is that causing Problems?

**Comment by ThePlatinumGhost** [comment]
I get same error
When i disconnect from server (the server is vanilla it have only some plugin and a resource pack) i crash and i get this error https://pastebin.com/yYgxYC4W
I tried to remove all other mods but i get same error
i have Minecraft Forge

**Comment by Shadder-1-5** [comment]
Same man, its a little annoying but i can live with it, maybe i should post my crashlogs with jei only but ive been busy with my SAT and haven't had time to open MC up again

**Comment by Shadder-1-5** [comment]
Here is the Pastebin of the error with Jei only https://pastebin.com/xykBV4NA

**Comment by Shadder-1-5** [comment]
is there anyway to get anyone's attention with this?

**Comment by Shadder-1-5** [comment]
like can i use a bump or something, ive never used that before

**Comment by mezz** [comment]
Thanks for the updated report. This should be fixed in JEI 6.0.0.20
