### ISSUE TITLE
[1.14] Elytra Anvil Repair Recipe is Incorrect

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#1773]
In playing in modded survival 1.14 on my public Geolosys Testing server, I was curious to see if Elytra were given any crafting uses by the few mods we have. Then I noticed that the repair item was still Leather from the pre-1.13 era. Just thought I'd through it out there that that's still an issue. Here is some photographic proof if it helps:
______
## Photos

What is shown:

![javaw_muknr37CbB](https://user-images.githubusercontent.com/3887324/67251184-2fe0fd80-f43c-11e9-8dce-c5ab923aaafb.png)

My attempt at following this recipe:

![javaw_t93UqamIeb](https://user-images.githubusercontent.com/3887324/67251200-3ec7b000-f43c-11e9-980b-8d6ffcfeb1db.png)

The actual recipe:

![javaw_SoHPFB0IS0](https://user-images.githubusercontent.com/3887324/67251201-412a0a00-f43c-11e9-9f7d-6705c2b13274.png)

_____

## Possible Source of the Problem

https://github.com/mezz/JustEnoughItems/blob/f520f423d9e518eed0a5a1067999b430d519fd70/src/main/java/mezz/jei/plugins/vanilla/anvil/AnvilRecipeMaker.java#L134

I'd be glad to make a PR with the new Phantom Membran if it makes your life easier!!

**Comment by mezz** [comment]
Thanks for the report!
PRs are welcome. You diagnosed the problem completely, so it would be nice to give you credit for the fix.

**Comment by oitsjustjose** [comment]
PR made and tested, it should be good to go!
