### ISSUE TITLE
Stonecutter recipe support

### ISSUE THREAD

**Issue by IronPiston** [mezz/JustEnoughItems#1774]
The stonecutter has no recipe tab currently. 
It could maybe look like Future MC's implementation in 1.12:
![Screenshot from 2019-10-22 22-44-26](https://user-images.githubusercontent.com/11603684/67355775-be797b80-f51d-11e9-961a-66c8aa477fb0.png)

**Comment by mezz** [comment]
Thanks for the suggestion!
This has been implemented here: https://github.com/mezz/JustEnoughItems/pull/1950
