### ISSUE TITLE
Composter recipe support

### ISSUE THREAD

**Issue by IronPiston** [mezz/JustEnoughItems#1775]
The composter has no recipe tab.
Maybe it could look something like how Charm implements it in 1.12:
![Screenshot from 2019-10-22 22-45-31](https://user-images.githubusercontent.com/11603684/67355831-fda7cc80-f51d-11e9-92d1-626109482cc2.png)

**Comment by UncleSam139** [comment]
I know it's an old post. But is there a chance that we get support for the composter?

**Comment by mezz** [comment]
Thanks for the request!
I have added a simple Compostable recipe category in JEI 8.1.0 for Minecraft 1.17
