### ISSUE TITLE
Fails to load when connecting to a multiplayer server

### ISSUE THREAD

**Issue by cpw** [mezz/JustEnoughItems#1777]
JEI isn't loading into a multiplayer world until you have first opened a singleplayer world.

See: Forgecraft.

**Comment by mezz** [comment]
Thanks for the report!
Looking into this, there is no issue with just JEI so I think there is an issue coming from another mod. I'll try out FC in a bit and see what I get in the client log. If you have a log already please paste a gist here so I can check it out.

**Comment by mezz** [comment]
I just joined Forgecraft and JEI loaded when I went on to the server directly.
Maybe this was fixed in a round of other fixes. Can you confirm it's working for you now @cpw ?
