### ISSUE TITLE
Modded 1.8.9 crashes when clicking on the "wrench" button on JEI

### ISSUE THREAD

**Issue by vrork** [mezz/JustEnoughItems#178]
My game is crashing when i click on the wrench icon to change configs.

Here is the crash report:
http://pastebin.com/s1cCyNTF

**Comment by way2muchnoise** [comment]
`de.universallp.infotooltip.InfoTooltip`
Doesn't really seems to be somewhere in JEI
But what ever mod that adds those tooltips on items you ar elooking at on the floor

**Comment by vrork** [comment]
Fixed! thanks!
