### ISSUE TITLE
Textured Enchanted Books dont show their Texture

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1783]
FORGE: 28.1.74
JEI: 1.14.4-6.0.0.18

Hi,

I use a resource pack that changes the enchanted book textures.  In JEI the enchanted books all show their default book image, not the new texture pack ones.

When you click an item out of JEI (using cheat mode) the image shows correct texture

[An image here](https://1drv.ms/u/s!ArSGAcC04KWskm5dDjKtG8Lrklhr?e=2e6T5o)
[Link to Enchanted Books](https://www.curseforge.com/minecraft/texture-packs/faithful-enchanted-books)

**Comment by mezz** [comment]
Thanks for the report!
This looks like an incompatibility from Optifine, I think they are doing something to the render pipeline that is not being applied to JEI.
