### ISSUE TITLE
Crafting category extensions aren't used 

### ISSUE THREAD

**Issue by Hubry** [mezz/JustEnoughItems#1785]
JEI version: 6.0.0.18, Forge version: 28.1.74, tested with Quark's 1.14 dev enviroment.
Also tested on JEI 6.0.0.11, Forge 28.1.70 in Botania's 1.14 dev enviroment.

Reproduction: Register crafting category extensions like [this](https://github.com/Vazkii/Botania/blob/7cabf5f736617daf308c35fedff6c6b1fd40d679/src/main/java/vazkii/botania/client/integration/jei/JEIBotaniaPlugin.java#L107-L109), put a breakpoint in a constructor of any extension.

Expected result: Constructor is called, and recipe renders as expected.
What happens: The breakpoint is never triggered and the recipe never shows up.

**Comment by mezz** [comment]
Thanks for the report!
It looks like the one added by the vanilla plugin for `ICraftingRecipe` is being used, since your recipes extend that interface. I'll have to make sure there is better logic for this like with other recipe handling, so that the most specific handler gets used.

**Comment by mezz** [comment]
I looked deeper into this and the actual issue is that JEI drops all dynamic recipes.
I'll have to think of what the best solution is for this.

**Comment by mezz** [comment]
You can now override this method to allow your recipe category to handle dynamic recipes:
https://github.com/mezz/JustEnoughItems/blob/faa544d918b2c80a514d072d435e90e98663e770/src/api/java/mezz/jei/api/recipe/category/IRecipeCategory.java#L114-L124
