### ISSUE TITLE
Missing Brewing Recipes

### ISSUE THREAD

**Issue by pupnewfster** [mezz/JustEnoughItems#1787]
This is probably not all that high priority, but earlier today I was working on creating an EMC Mapper for Brewing Recipes and I came across an odd thing. JEI is missing two *valid* Vanilla brewing stand recipes.

Potion of luck + gunpowder -> splash potion of luck
Splash potion of luck + dragons breath -> lingering potion of luck

I believe the reason JEI does not find either of these recipes is that they are not declared in `PotionBrewing`, but I did test them and they do in fact work in the brewing stand.

The reason I believe this is probably rather low priority is that given the base potion of luck cannot even be crafted anyways, it doesn't really matter there are no recipes for its children.

JEI Version: 6.0.0.18
Forge Version: 28.1.80

https://github.com/pupnewfster/ProjectE/blob/nbt_nss/src/main/java/moze_intel/projecte/emc/mappers/BrewingMapper.java The mapper I made to find all the recipes.

**Comment by mezz** [comment]
Thanks for the report!
I build the potion list by starting with the base potion and applying reagents to it, so it makes sense that it would miss those potions. That was necessary because of the weird way potions worked before, maybe there is a smarter way now. I'll take a look at your implementation when I get a chance to see if I can adapt what I have a bit.

**Comment by pupnewfster** [comment]
Actually looking at how you do things it probably would be relatively simple to do given you have a list of all reagents. I think if you replace [this](https://github.com/mezz/JustEnoughItems/blob/1.14/src/main/java/mezz/jei/plugins/vanilla/brewing/BrewingRecipeMaker.java#L85-L94) with just using a slightly modified version of [this](https://github.com/pupnewfster/ProjectE/blob/nbt_nss/src/main/java/moze_intel/projecte/emc/mappers/BrewingMapper.java#L110-L120) for the list of knownPotions it will be able to find them. `ItemInfo` is basically just a helper class I have in general so that I can have the sets get rid of duplicate ItemStacks (given I don't care about stack size). But I believe in this case for the inputs it might even just work properly using ItemStacks (given there shouldn't be any duplication with how the list of inputs is built).

**Comment by mezz** [comment]
Thanks! I had to filter out some literally "uncraftable" vanilla potions but otherwise it worked well.

![2019-11-06_23 12 05](https://user-images.githubusercontent.com/916092/68364464-e1418d80-00e2-11ea-88c4-d76e80553c21.png)
