### ISSUE TITLE
Thaumcraft Enchanted Book: Repair II from creative tab doesn't show up in JEI

### ISSUE THREAD

**Issue by MalkContent** [mezz/JustEnoughItems#179]
First off, a big thank you for adding enchanted books to the item list :)
My guess is it doesn't show up, because the Repair II book is in the Miscellaneous tab, rather than the Tools or Combat tab and you only checked those two.
It probably would be prudent  to simply check all tabs to catch any mod books that have been put god knows where.
Also I simply might be wrong ^^

**Comment by mezz** [comment]
Thanks for the report!
Before I made JEI scan the creative tabs directly, I used to manually add all the types of books. I think I'll do that again and remove the duplicates.

**Comment by mezz** [comment]
Hmm actually I see Repair II shows up just fine. Can you make sure you have the latest version of JEI?
![2016-02-19_15 14 51](https://cloud.githubusercontent.com/assets/916092/13191857/a8073a50-d71b-11e5-8b7d-96b1a3c0f4ad.png)

**Comment by MalkContent** [comment]
jei_1.8.9-2.27.1.158, forge x1741
from earlier today
updated to jei x159, forge x1755, repair still not showing up
mods: jei, opencomputer, thaumcraft, inventorytweaks, all lates version

**Comment by MalkContent** [comment]
Tried the floppy thing from the other issue in case it was that, worked for the floppies, not the book
item blacklist is clear, too.

I'm in a singleplayer world, even though i doubt that makes a difference.

Edit: Oh. Ok repair shows up. Either I didn't see it before or it wasn't there before.
Edit2: ~~I can't search for it though~~ I am an idiot. I enabled the "# for tooltip search" thing. I thought that meant I /could/ search tooltips with that. Not that I /had/ to do so with that enabled. (the shame)

**Comment by mezz** [comment]
I loaded up the same mods minus inventory tweaks and it shows up fine.
Is there anything in your log that might indicate a problem?

**Comment by MalkContent** [comment]
see above :|
Maybe enchanted books should be treated differently, since the enchantment name tooltip is the essential thing about it, but maybe I'm just saying that to divert from my being a retard.

**Comment by mezz** [comment]
Ah ok :D

**Comment by mezz** [comment]
I think I will rename the config options. Maybe "Require # for Tooltips" ?

**Comment by MalkContent** [comment]
"Require # to include Tooltips" would be my pitch, might be a bit long though. Yours is fine.
Edit: mine would be wrong. It's Tooltips only with #
