### ISSUE TITLE
Jei and ultimate car mod incompat(1.14.4-forge-28.1.8) server side

### ISSUE THREAD

**Issue by SDUBZ** [mezz/JustEnoughItems#1791]
https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod/issues/89
all the info and logs are listed above

**Comment by mezz** [comment]
Thanks for the report!
I think this is caused by ultimate car mod, I didn't see anything in the log that seemed too strange from JEI. Unfortunately their mod doesn't seem to be open-source so I wasn't able to easily look into what they are doing.

**Comment by SDUBZ** [comment]
yeah thanks mezz and just waiting to see if they get around to fixing it

**Comment by SDUBZ** [comment]
any feedback on this issue
