### ISSUE TITLE
Crashing on Loading Screen 1.14.4

### ISSUE THREAD

**Issue by 07Babygirl28** [mezz/JustEnoughItems#1794]
My game keeps crashing on the loading screen saying "an unexpected issue has occurred". I am not using any other mods or datapacks, only forge. I've been trying to get JEI to work for 1.14.4 since this mod's version for 1.14.4 was released, but so far no luck. I even used different versions of forge.
I have never had this problem with JEI with 1.12.2, so I don't know what to do.

What do you suggest?

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
