### ISSUE TITLE
Enchantment render JEI

### ISSUE THREAD

**Issue by BardGitH** [mezz/JustEnoughItems#1797]
![image](https://user-images.githubusercontent.com/57300546/68857088-5a904000-06e2-11ea-952a-0b17058f7c08.png)

![image](https://user-images.githubusercontent.com/57300546/68857191-94f9dd00-06e2-11ea-8212-fd93f2f7c73f.png)

Jei only shows one color of enchantment glimmer
this is also the case when only JEI and Quark/Enchanted Book Redesign is installed

**Comment by mezz** [comment]
Thanks for the report!
Enchanted Book Redesign depends on rendering changes by Optifine. Optifine has changed vanilla rendering but it does not affect JEI's rendering here for some reason. I am not sure what exactly they are doing, but I think you should report to them so we can find out.

**Comment by mezz** [comment]
Actually I was mistaking this for a similar resource pack that depends on Optifine. 
Enchanted Book Redesign works standalone, and the issue has been reported to them here: https://github.com/Tfarcenim/Enchanted-Book-Redesign/issues/4
