### ISSUE TITLE
Jei doesnt show many Recipes of many Mods of FTB Ultimate Reloaded like IC2 Drill

### ISSUE THREAD

**Issue by Evonos** [mezz/JustEnoughItems#1798]
Many recipes arent shown in JEI if you add them via "A" in creative mode these dont show any recipes.

**Comment by mezz** [comment]
Thanks for the report!
Please report to the pack here: https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues
Maybe they have disabled the recipes, or maybe they have some more context for this issue.
