### ISSUE TITLE
Item list doesn't change to screen size while viewing recipes

### ISSUE THREAD

**Issue by pauljoda** [mezz/JustEnoughItems#180]
I resized my window while looking at some recipes and this was the result. Same things happens in reverse but renders off screen. Seems the list doesn't adapt to screen size changes while looking at recipes, even JEI added handlers 

http://i.imgur.com/DxDTyUd.png

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/171
Please update your JEI.

**Comment by pauljoda** [comment]
Ah didn't see that issue, good deal.
