### ISSUE TITLE
JEI takes looong to load

### ISSUE THREAD

**Issue by nift4** [mezz/JustEnoughItems#1800]
Log -> https://gist.github.com/nift4/6398b24cd99dc7e168a7f43437a09a76
JEI Debug mode is on. The plugins load forever and also the vanilla plugin takes a half hour.
What's going on? One time (sorry no log for that) it loaded over 2 hours and was also not finished.
Note: I use https://eclipse.org/openj9 from https://adoptopenjdk.net @ Linux and G1GC via java args (because RAM is not enough with Hotspot, the java standard), only to have it said.

**Comment by nift4** [comment]
But anyway thanks for the great mod @mezz

**Comment by mezz** [comment]
Thanks for the report!

`[jei]: Registered enchantment recipes in 25.46 min`

I think either you're hitting the memory limit and GCing constantly, or there are just an incredible number of possible enchantment recipes in your pack, or (most likely) both of these problems at once.

**Comment by mezz** [comment]
It also looks like the extra utilities plugin was taking 14 minutes before you gave up and killed it. It's probably the same issue as with the enchantment recipes.

```
[19:04:20] [Client thread/DEBUG] [jei]: Registering plugin: com.rwtema.extrautils2.crafting.jei.XUJEIPlugin ...
Process was killed by user at 19:18:23
```

**Comment by nift4** [comment]
Okay, I'll try to give 1GB more RAM. @mezz

**Comment by nift4** [comment]
I have currently no time to test :(

**Comment by mezz** [comment]
No rush, we can fix it when you have time.

**Comment by nift4** [comment]
More RAM + JVM Args fixed it, closing when game up 😀

**Comment by nift4** [comment]
Aww did not work 😣 JEI has eaten 1.5 GB RAM before Minecraft did not work anymore... No abnormal things in log. It was while Indexing ingrendients.

**Comment by nift4** [comment]
Enchantments taken less than 20 sec anyway

**Comment by nift4** [comment]
Now it has eaten 2 GB RAM and it is only at Registering plugins! What is going on? @mezz

**Comment by TehNut** [comment]
You appear to have a large number of mods. This means your memory requirements are quite high. Try increasing your allocated RAM to 4gb or so.

**Comment by nift4** [comment]
@mezz @TehNut I assigned 7,5 GB. I have 8 GB and use an reduced Linux that runs well on a computer that has only 512 MB. I also use the OpenJ9 VM and a high number of JVM arguments - I looked into almost every config of performance optimizing mods and don't have more ideas. I have FoamFix, VanillaFix, OptiFine, Surge, BetterFps and more smaller optimisation mods. My launcher is MultiMC.

**Comment by nift4** [comment]
@mezz @TehNut moved to #1822
