### ISSUE TITLE
[1.14.4] Crash in Intellij idea

### ISSUE THREAD

**Issue by DcZipPL** [mezz/JustEnoughItems#1801]
Crash when debugging own mod in Intellij Idea and JEI is installed in /run/mods.
[Crash gist](https://gist.github.com/DcZipPL/76a7e344130f3af6da2b349cdc2bfe46)

**Comment by TehNut** [comment]
I don't believe forge supports loading obfuscated mods from `run/mods` anymore.

**Comment by DcZipPL** [comment]
Earlier (1.12.2) everything worked fine.

**Comment by DcZipPL** [comment]
What is alternative.

**Comment by TehNut** [comment]
> Earlier (1.12.2) everything worked fine.

1.12 forge is extremely different to 1.14 forge.

> What is alternative.

Use gradle

**Comment by DcZipPL** [comment]
I added dependency in gradle and anything is working fine. Thank you!
