### ISSUE TITLE
The Jei it's making the world won't open

### ISSUE THREAD

**Issue by DaniGamer23** [mezz/JustEnoughItems#1802]
The mod makes the world don't open when it's in the Minecraft and the only thing that shows in the log it's timeout and if the Jei it's removed the world open without any problem

**Comment by DaniGamer23** [comment]
Version 1.12.2 

I tried the last release and I tried the last beta posted this month

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
