### ISSUE TITLE
NEI and JEI interface bug

### ISSUE THREAD

**Issue by Josh65-2201** [mezz/JustEnoughItems#1803]
Since people at NEI won't respond or update there mod i was wondering if the JEI team could fix this.

I get this in the console every time i open JEi/Nei and on launch:
[Nei error.txt](https://github.com/mezz/JustEnoughItems/files/3855873/Nei.error.txt)

Here's the full log if needed:
[latest.log](https://github.com/mezz/JustEnoughItems/files/3855875/latest.log)

**Comment by TehNut** [comment]
Any NEI errors must be fixed by NEI.

**Comment by mezz** [comment]
Thanks for the report!
Please report to NEI here: https://github.com/TheCBProject/NotEnoughItems/issues
