### ISSUE TITLE
Request to change recipe transfer icon

### ISSUE THREAD

**Issue by axieum** [mezz/JustEnoughItems#1804]
I'd suggest changing the [recipe transfer icon](/mezz/JustEnoughItems/tree/1.14/src/main/resources/assets/jei/textures/gui/icons/recipe_transfer.png) to something that means "export" or "transfer" - I personally find `+` ambiguous in that context.

**Suggestions** - of course these would need to be pixelated:
* https://www.flaticon.com/free-icon/transfer_876784
![](https://image.flaticon.com/icons/svg/876/876784.svg)
* https://www.flaticon.com/free-icon/transfer_159791
![](https://image.flaticon.com/icons/svg/159/159791.svg)
* https://www.flaticon.com/free-icon/share_1159761
![](https://image.flaticon.com/icons/svg/1159/1159761.svg)
* https://www.flaticon.com/free-icon/export_158749
![](https://image.flaticon.com/icons/svg/158/158749.svg)
* https://www.flaticon.com/free-icon/export_724938
![](https://image.flaticon.com/icons/svg/724/724938.svg)

**Comment by Ommina** [comment]
Huh.  Interesting.  I always called it an "add to grid", making the plus sign pretty much ideal.

Not that I'll lose any sleep if it changes, mind.

**Comment by axieum** [comment]
Ah, @Ommina that actually does make sense why it's an addition sign! 😆
