### ISSUE TITLE
JEI 1.8.9 not working

### ISSUE THREAD

**Issue by DeadMemesYT** [mezz/JustEnoughItems#1805]
I have it in my mods and it shows up in my list in game but it does nothing. Anyone know how to fix it?

**Comment by nift4** [comment]
CTRL+O

**Comment by DeadMemesYT** [comment]
I tried CTRL+O but it didn’t work.

**Comment by nift4** [comment]
Log?

**Comment by DeadMemesYT** [comment]
[latest.log](https://github.com/mezz/JustEnoughItems/files/3882850/latest.log)

**Comment by DeadMemesYT** [comment]
I just tested it again and it's working now. I don't know why it didn't work before.

**Comment by nift4** [comment]
There were some unlogic texture loading errors
