### ISSUE TITLE
[Request] An event that is fired after RecipesGui#setWorldAndResolution()

### ISSUE THREAD

**Issue by Daomephsta** [mezz/JustEnoughItems#181]
In an addon that I'm developing, I need to overlay some stuff on top of the recipe gui. I can get all the variables I need to do this with reflection(guiTop, guiLeft, ySize, recipeLayouts and logic), but when GuiInitEvent.Pre, GuiInitEvent.Pre or GuiOpenEvent are fired these variables are null.

**Comment by mezz** [comment]
Hm I should probably do most of that stuff in `initGui` so it works in a standard way. Then everything should be set when `InitGuiEvent.Post` is called. Would that work for your purposes?

**Comment by mezz** [comment]
What are you doing? I'm curious.

**Comment by Daomephsta** [comment]
> Hm I should probably do most of that stuff in initGui so it works in a standard way. Then everything should be set when InitGuiEvent.Post is called. Would that work for your purposes?

Yes

> What are you doing? I'm curious.

I'm creating an ingredient list. You select an item, select the recipes you want to use to craft it and it's ingredients(and their ingredients and so on) and it creates a list of all the materials with the needed amounts. JEI allows it to support any crafting method with JEI support, a way to display those recipes and an easily searchable list of items in the game.

Thanks for your help.

**Comment by mezz** [comment]
Ok should work, everything is set in `initGui()` now. 
Good luck, watch out for mod addons that may have bugs in their input->output relationships.

**Comment by Prospector** [comment]
Hmm @Leviathan143 that's a really cool idea. Mind posting to this /r/feedthebeast when it's done? I know I'll see it there, and it sound super useful.

**Comment by Daomephsta** [comment]
@ProfessorProspector 
I intend to do that, r/feedthebeast is a good place to get constructive criticism.
