### ISSUE TITLE
JEI Packet size issue with oredict recipes causes disconnect with error

### ISSUE THREAD

**Issue by Sakata-MC** [mezz/JustEnoughItems#1813]
When transferring items to crafting that have a large ore dictionary count, such as Enderio "Iron Alloy Ingot" or Actually Additions "Greenhouse Glass", or many other items that have wood/plants/glass in recipes, you will be disconnected with:

```
[13:53:25] [Netty Client IO #2/ERROR] [FML]: NetworkDispatcher exception java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes at
...
```

I'm not 100% sure how you can fix this, aside from perhaps client-side, picking *one* recipe in the ore dictionary, then sending that to the server, instead of iterating every single combination in one massive packet.

This would rely on recipes being identical on client and server, however I think that they already should be with any mods and packs, as issues would ensue if otherwise.

It looks like you may already have a fix that perhaps isn't implemented?  Either that or the dev found a fix by workaround... 
https://github.com/p455w0rd/JustEnoughEnergistics/issues/4#issuecomment-456227165

**Comment by YellerFeller** [comment]
Can this be re-opened? Currently a fairly major issue on 1.12 modpacks
