### ISSUE TITLE
Autofill on Servers(Vanilla/No JEI Plugin/Support)

### ISSUE THREAD

**Issue by Hi-ImKyle** [mezz/JustEnoughItems#1817]
I believe I've asked this before, but the answer was a long time ago I'm not sure what the reasoning was behind it.

But since Minecraft has implemented the autofill recipe feature, will JEI ever allow it on servers?

**Comment by TehNut** [comment]
#916

**Comment by Hi-ImKyle** [comment]
Is there any plans to make this a thing?
