### ISSUE TITLE
Detected classes with unsupported format crash (Java 6)

### ISSUE THREAD

**Issue by therealjimjack1** [mezz/JustEnoughItems#182]
I'm running Minecraft on mac with 1.8.9-forge1.8.9-11.15.1.1741 and jei_1.8.9-2.28.0.160 installed and when i try to run Minecraft it crashes.

**Comment by mezz** [comment]
Thanks for the report!
~~Please paste your crash log to https://gist.github.com/ and link it here.~~

**Comment by AEnterprise** [comment]
unsupported class format crashes are caused with your java version being to low, update to java 8 and it should work fine

**Comment by mezz** [comment]
Even Java 7 will work fine, if you can't get 8 on your mac.
If it is not possible to update Java at all because you have a very old mac, the solution is in this issue: https://github.com/mezz/JustEnoughItems/issues/147

**Comment by AEnterprise** [comment]
thought JEI required 8 as alot of the other 1.8.9 mods, derp on my part

**Comment by therealjimjack1** [comment]
When i verify java it says i have the recommended version, that is : 1.8.0_74 is this not java 8, or am i completely missing something?

**Comment by mezz** [comment]
Make sure your Minecraft launcher has selected Java 8, by default it will still choose 6.

**Comment by therealjimjack1** [comment]
lol, so, ever since Minecraft 1.6.4 and the launcher that goes with, i have been using a far outdated version of java XD. You have probably solved all of my mod pack building issues.

**Comment by therealjimjack1** [comment]
i wonder what changes i'll see jumping ahead that far. It didn't crash this time, thank you

**Comment by mezz** [comment]
Cool, hopefully you'll see a slight performance improvement. It's mainly about security and development though.
