### ISSUE TITLE
Crazy RAM managment

### ISSUE THREAD

**Issue by nift4** [mezz/JustEnoughItems#1822]
Debugged Problem from #1800

My modpack took ~1h to load until Finishing up -JEI and used 4,5 GB RAM.  Max RAM is 7,5 GB. Xms is 0,5 GB because then it does GC more often and wastes less RAM while loading - at JEI is starting 6GB were assigned. JEI loaded the vanilla plugin and eaten 5,6GB and then it GC'ed constantly (but there was no garbage to collect!) instead of eating more RAM. At the end it froze. That's not normal I think. :)

@mezz
@asiekierka - because you made the 1.12.2 mermory PR (hope it's okay) [and the great FoamFix I use]

**Comment by asiekierka** [comment]
I won't be able to do anything without a copy of the modpack.

**Comment by nift4** [comment]
No problem (MultiMC is okay hopefully) - tomorrow

**Comment by nift4** [comment]
Modpack: https://send.firefox.com/download/92f96f0dba810118/#k9yoYa2ifiPWRrdPjONu1w
Java: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9
@asiekierka

**Comment by asiekierka** [comment]
Note that I'm not likely to test with OpenJ9 at first, because my entire debugging workflow is based around the more common OpenJDK implementation. But we might get more of a clue that way.

**Comment by nift4** [comment]
Noted :)

**Comment by nift4** [comment]
Any news @asiekierka

**Comment by asiekierka** [comment]
I have a decently busy schedule, and modding in general is currently hard to schedule. I will not have more time before the 18th, that is for certain.

**Comment by nift4** [comment]
No Problem @asiekierka

**Comment by nift4** [comment]
I think this Problem is a modpack problem, not JEI
