### ISSUE TITLE
I can’t see the recipes

### ISSUE THREAD

**Issue by byzokky** [mezz/JustEnoughItems#1823]
When I want to see the recipe for an object, I can’t, and when I place all the options the craft table is not there.
version (1.12.2)

**Comment by JeffTheKillerJcar** [comment]
hola ya sabes como resolverlo ?

**Comment by byzokky** [comment]
Nope

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: JeffTheKillerJcar <notifications@github.com>
Enviado: Friday, December 13, 2019 3:15:15 PM
Para: mezz/JustEnoughItems <JustEnoughItems@noreply.github.com>
Cc: Steban Marin Ramon <byzokky@javerianacali.edu.co>; Author <author@noreply.github.com>
Asunto: Re: [mezz/JustEnoughItems] I can’t see the recipes (#1823)


hola ya sabes como resolverlo ?
