### ISSUE TITLE
1.12.2 Crash when an Agricraft / OpenComputers compat item is rendered in JEI

### ISSUE THREAD

**Issue by NFinET** [mezz/JustEnoughItems#1828]
[CRASHLOG HERE](https://paste.dimdev.org/giwaragayu.mccrash)

Minecraft version: 1.12.2
Forge Version: 14.23.5.2847

What I was doing when it happened: Searching for "conduit" in JEI, crash occurred when reaching the "n", log points to "Computer **con**trolled seed analyzer" from Agricraft, this item only exists if OpenComputers is also present.

Modpack used: Custom modpack I put together called the "Stuffed Crust Pizza Pack" that's available on CurseForge, crash occurs on version "Pepperoni R2.0.0". Modpack page located [HERE](https://www.curseforge.com/minecraft/modpacks/stuffed-crust-pizza-pack) 

Recently the modpack was updated and JEI was updated from 4.15.0.289 Beta to 4.15.0.291 Release. Additionally, OpenComputers was added in said update, but Agricraft was already present. Forge was also updated from 14.23.5.2846 to 14.23.5.2847 (necessary for updating another mod). Before those changes were made, searching for that term did not cause a crash, presumably because the aforementioned item that seems to be causing the crash when it's rendered in JEI (the computer controlled seed analyzer) only exists / is registered when OpenComputers is also present. I wasn't sure if this crash is related to Agricraft / InfinityLib or Just Enough Items so I'm submitting this here as InfinityLib and Agricraft have not been updated since 2018, so any support from issue-reporting to those is unlikely, as well as the crashlog seems to implicate it's the rendering of the item causing it though I don't know if that's something in JEI with rendering code or the actual model of the Agricraft item implicated by the crash. None of the three mods have anything related to this item nor this compatibility in their configs. If necessary and there's nothing to be done I'm prepared to alter the modpack to fix this problem if I really have to.

Thank you for your time.

**Comment by NFinET** [comment]
Regardless of what caused the issue reinstalling the pack fixed it, there's so sign it ever happened. Strange, but I'm closing this issue (it probably wasn't JEI anyway, but I wanted to cover my bases)

**Comment by NFinET** [comment]
Re-opening the issue, as it occurred again but this time with items that are unrelated to Agricraft's OpenComputers compat, however the items affected/causing it are still from Agricraft.

I have two more logs:
https://paste.dimdev.org/vawoxohuvi.mccrash <- Caused by an Agricraft Grate
https://paste.dimdev.org/usamifiroc.mccrash <- Caused by an Agricraft Water Tank

I'll be removing Agricraft from the pack because of how old it is and how long it's been since it last updated, the crash was not occurring before both adding OpenComputers and updating JEI as mentioned in the original post up above, but now that it's occurring with non-OC-compat items, I'm not sure what to think about what's going on. Installing a new copy of the pack seems to fix it, but then it will randomly occur with a different item, so that searching for things in JEI becomes a game of minesweeper where seemingly any random item from Agricraft can crash the game. I still don't know if this is caused more by JEI or Agricraft, but I'm re-opening the issue just in case.

I haven't had the time to try more in-depth testing like isolating the mods involved and messing with them, so sorry for not having done so already.

**Comment by TehNut** [comment]
https://github.com/AgriCraft/AgriCraft/issues/1170
