### ISSUE TITLE
Main maven is down

### ISSUE THREAD

**Issue by LemADEC** [mezz/JustEnoughItems#1829]
The progwml6.com server is down, its related maven https://dvs1.progwml6.com/files/maven/ is failing for a couple days at least, preventing compilation.
Fallback maven https://modmaven.k-4u.nl remains accessible but appears to be missing deobf version of the mod?

**Comment by KnightMiner** [comment]
Progwml6.com being down is known, owner has been busy and unable to fix it
You should not be using deobf builds anymore, instead use the deobf option in forge Gradle. This differs based on whether you are in 1.12 or 1.13+, so see the wiki for more info

**Comment by LemADEC** [comment]
Where is the related wiki for Forge Gradle? The github one doesn't refer to deobf and the readthedocs one stops before 1.12.

**Comment by TehNut** [comment]
He meant the JEI wiki, specifically [this page](https://github.com/mezz/JustEnoughItems/wiki/Getting-Started)

**Comment by KnightMiner** [comment]
It is back up now

**Comment by LemADEC** [comment]
Thanks!
The script was set to deobfCompile, I've changed it do compileOnly, the wiki recommend deobfProvided.
Also, while the main maven was down, the script was failing and wouldn't check the fallback maven, so I had to comment the former.
