### ISSUE TITLE
JEI Item Description Blank

### ISSUE THREAD

**Issue by Autissima** [mezz/JustEnoughItems#183]
If i go in JEI and look for a Non-Vanilla Recipe I have no descriptions on the items: No lore, damage or text in any way

**Comment by mezz** [comment]
Thanks for the report!
Can you give a specific example and a screenshot so I can understand what you mean?

**Comment by Autissima** [comment]
Ok, i just found out that even Vanilla Recipes are affected by this (Although not very much of them) Screenshot is attached and as an example i use a thaumium sword (TC 5)
![2016-02-21_16 21 09](https://cloud.githubusercontent.com/assets/17355089/13203405/bde2a54c-d8b7-11e5-96a4-763a10f04419.png)
![2016-02-21_16 21 05](https://cloud.githubusercontent.com/assets/17355089/13203406/bde39498-d8b7-11e5-9af0-4ea1a0506602.png)

**Comment by Autissima** [comment]
If you need more screenshots or other information please ask :3 Thanks for the fast answer

**Comment by GirafiStudios** [comment]
This happens because of Mapwriter. Not sure why it happens, but it seems to fix it if you remove Mapwriter or just turn the map itself off.

**Comment by Autissima** [comment]
ok thanks :D

**Comment by Autissima** [comment]
Ill Close this now because of fixed , ty for the fast reply
