### ISSUE TITLE
JEI hanging on “Building ingredient filter”

### ISSUE THREAD

**Issue by Dimentive** [mezz/JustEnoughItems#1836]
My friend’s game has been stuck on “Building ingredient filter” for nearly an hour now.

This has happened a few times before, but it didn’t happen yesterday, and we haven’t downloaded any additional mobs since yesterday.

The game is stuck on “Indexing ingredients - [Mod]” for, like, 15 minutes, and then the mod name changes. Then, it’s stuck for another ~15 minutes. Is my game ever going to load?

He allocated 6,969 MB of RAM.

[Full mod list.](https://pastebin.com/raw/ipVRD6ji)

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847
* **JEI:** 4.15.0.292

**Comment by Dimentive** [comment]
My game loaded for an hour. Then, I restarted my PC to try again. It’s been another hour, and it’s still stuck.

**Comment by Tahakk** [comment]
Upload log to [gist](https://gist.github.com/) and link it here as is written in template (:

**Comment by Dimentive** [comment]
Solved by changing the JVM argument `-XX:ParallelGCThreads=8` to `-XX:ParallelGCThreads=4`. My friend has an octo-core CPU, and I’m using the same JVM argument, so I don’t know why this was causing issues for him, but changing 8 to 4 solved this problem nonetheless.
