### ISSUE TITLE
[1.15.1] GUI not showing up in inventory.

### ISSUE THREAD

**Issue by cam443** [mezz/JustEnoughItems#1839]
The mod seems to have loaded, and even has keybinds showing, but doesn't appear to work. I've tried pressing CTRL + O and even changing that keybind to show JEI to no avail.

Here's my log if that helps: https://gist.github.com/SeenRender/992040e6df3c69ed718be93453b197f9

**Comment by Cr4fTJuNkiE** [comment]
Same issue for me as well.

**Comment by Dekamir** [comment]
If you are in creative mode, could you try pressing the key combination at "Survival Inventory" tab?
If you were in already survival mode, I don't know the reason.

**Comment by xKoku** [comment]
I Have this issue too
first i thought that it had like a new keybind to show the recipes or something

**Comment by xKoku** [comment]
I tried it in both survival and creative and it didn't work

**Comment by Cr4fTJuNkiE** [comment]
Same.

**Comment by Dekamir** [comment]
And I see mods running aside JEI. Could you try JEI in a session without other mods?
_At least the remainings of them._

**Comment by cam443** [comment]
> 
> 
> And I see mods running aside JEI. Could you try JEI in a session without other mods?
The mod works on a fresh install. I imagine that means the problem is another mod

**Comment by Dekamir** [comment]
`java.lang.IllegalArgumentException: Invalid ingredient found. Parameter Name: catalystIngredient Ingredient Info: 1 air minecraft:air`

The upper is a fatal error. I'm not an expert but it seems like a mod edits some variables about Air (Block zero). JEI normally shouldn't care about it, but it does (maybe because it's beta or Forge is).

**Comment by xKoku** [comment]
hello
i have a lot of mods but i can't really figure out which mod is causing the problem
i have 43 mods installed on forge
[latest.log](https://github.com/mezz/JustEnoughItems/files/4031796/latest.log)

and this is the log if it could help
can you guys help me figure it out?

**Comment by rgilbert1021** [comment]
Anvil Tweaks was causing that issue in mine.  Removing that one mod resolved the issue.

**Comment by xKoku** [comment]
You deserve a big kiss from
thank you so muchhh

**Comment by cam443** [comment]
Yeah Anvil tweaks was the problem for me as well.
