### ISSUE TITLE
Crash with both JEI and BetterInventory installed

### ISSUE THREAD

**Issue by rockdemon696** [mezz/JustEnoughItems#184]
I have isolated this issue to these two mods and it started with JEI version 1.8.9-2.25.12.152 released on Curse Forge on February 13, 2016 and is still happening on the latest public JEI version on the Curse Voice Launcher 1.8.9-2.28.1.162 released on February 20, 2016. BetterInventory has not updated since January 29, 2016. This may be a problem with either mod. I am reporting it here because I have no way to tell and I figured you would want to know if it is on your end, if not I am sorry please feel free to ignore me.

Crash Report: https://gist.github.com/rockdemon696/42fb30024dc6312e61fc

**Comment by mezz** [comment]
Thanks for the report!
Can you please post your whole client log to gist? (this crash report shows that something blew up earlier, and I need to find what it was)

**Comment by rockdemon696** [comment]
Here is a client log from a brand new instance with just the latest versions of the mods in question. Last time I may have accidentally grabbed a crash report from an older version of JEI that I was testing with to see what version the bug first appeared along side.

fml-client-latest.log: https://gist.github.com/rockdemon696/49b6ba715c9baa3ba1af

**Comment by mezz** [comment]
This has been fixed in JEI 2.28.2. 
BetterInventory has null items in its creative tabs, which caused JEI to crash. Now it will just log an error instead. 

Browsing the BetterInventory creative tabs ground my game to a halt, I don't recommend using that mod.
