### ISSUE TITLE
[1.15.1] No config

### ISSUE THREAD

**Issue by Nevrai** [mezz/JustEnoughItems#1843]
In 1.15.1, the “JEI Config” button doesn’t do anything, and the “jei” folder in the “configs” folder is empty.

I assume this is intended and that a config just hasn’t been implemented yet since this version of JEI is a very early version, but to be safe, I’m assuming it’s a bug or an oversight and posting this issue.

### Versions
* **Minecraft:** 1.15.1
* **Forge:** 30.0.36
* **Just Enough Items:** 6.0.0.1

**Comment by dureiken** [comment]
Same here :)

thanks for your work btw

**Comment by TehNut** [comment]
Duplicate of https://github.com/mezz/JustEnoughItems/issues/1526
