### ISSUE TITLE
"java.lang.NullPointerException: Ticking entity" crash when loading world

### ISSUE THREAD

**Issue by sn0wshoehare** [mezz/JustEnoughItems#185]
JEI 1.8.9-2.28.1.162 crashes with this error whenever I attempt to load a world.
https://gist.github.com/Toastywise/7b1d49c994b6b0ea628c#file-gistfile1-txt
No idea as to what might be causing this other than JEI itself, since the crash doesn't happen on older versions.

**Comment by sn0wshoehare** [comment]
Whoops, looks like this was already reported
https://github.com/mezz/JustEnoughItems/issues/184

**Comment by mezz** [comment]
Your crash might actually be different, the crash in the log was not the "real" crash. Try with JEI 2.28.2, it should give you a better crash log.

**Comment by sn0wshoehare** [comment]
Here's one on 2.28.4.170 (latest as of today): https://gist.github.com/Toastywise/e00cbca75ae38d834cab

**Comment by mezz** [comment]
Thanks. Can I have your full client log?

**Comment by sn0wshoehare** [comment]
https://gist.githubusercontent.com/Toastywise/62ef7638f5d5a0b47ed2/raw/7fee4764476eeb2b28da098ea9ffe4c5253deba2/fml-client-latest.log

**Comment by mezz** [comment]
Looks like an error cause by an old version of JEIAddons. It should be
fixed in the latest version, let me know if that works.

**Comment by sn0wshoehare** [comment]
Yep, updating JEIAddons fixed it. Thanks for the help.
