### ISSUE TITLE
Not running in newest 1.15.2

### ISSUE THREAD

**Issue by sugary-stardust** [mezz/JustEnoughItems#1852]
I'm using the latest download of JEI and the latest version of Forge for 1.15.2 and this is the message I get (copied from the error log):

_net.minecraftforge.fml.ModLoadingException: Mod File jei-1.15.2-6.0.0.2.jar needs language provider javafml:31 or above to load_

**Comment by Ommina** [comment]
~~And a stacktrace:~~

~~https://pastebin.com/CcbPWnNt~~

Edit: Resolved for me.

**Comment by Knito58** [comment]
JEI not running: YES but other source of issue.
Some mod has an invalid recipe and JEI seems to die silently.
versions:
MC 1.15.2
Forge 31.0.1
JEI 1.15.2-6.0.0.2

small chunk of lastest.log:`
`[24Jan2020 19:04:06.225] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Invalid ingredient found. Parameter Name: catalystIngredient Ingredient Info: 1 air minecraft:air
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2100/1814815047@3d233253
java.lang.IllegalArgumentException: Invalid ingredient found. Parameter Name: catalystIngredient Ingredient Info: 1 air minecraft:air
	at mezz.jei.util.ErrorUtil.checkIsValidIngredient(ErrorUtil.java:233)
	at mezz.jei.load.registration.RecipeCatalystRegistration.addRecipeCatalyst(RecipeCatalystRegistration.java:15)

...`

**Comment by Ommina** [comment]
@Knito58 That is a wholly different stack trace and deserves its own issue report.

**Comment by Knito58** [comment]
@Ommina Maybe but until now that is the first "real" issue in this thread. I made a new "latest.log" and put it on pastebin https://pastebin.com/rC5DVjgG and shortened my first comment a bit.
The interesting part starts at line 703 in my latest.log.

**Comment by Ommina** [comment]
It _still_ deserves its own report.  If @sugary-stardust resolves his FML issue and closes this, yours gets lost.  Which (I presume!) is not your goal.

**Comment by Knito58** [comment]
@Ommina Thats a point. Thank you. Made a new issue [there](https://github.com/mezz/JustEnoughItems/issues/1854).
