### ISSUE TITLE
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)  (RLCraft)

### ISSUE THREAD

**Issue by Lin-Jacob** [mezz/JustEnoughItems#1857]
Im trying to run RLCraft but this message keeps popping up! Can you help me?

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
[crash-2020-01-27_20.49.19-client.txt](https://github.com/mezz/JustEnoughItems/files/4120286/crash-2020-01-27_20.49.19-client.txt)

**Comment by Ommina** [comment]
Caused by: java.lang.OutOfMemoryError: Java heap space

You're out of memory.  Give it more.
