### ISSUE TITLE
When in creative mode with any tab other than survival inventory selected, JEI gives weird ghost items.

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#186]
Sorry for weird title, but it's hard to explain. To reproduce, go into creative mode, select any tab other than survival inventory, and give yourself blocks from JEI until your hotbar fills up. Continue giving items, and then click on the survival inventory tab. The items you gave yourself are not there, but they sorta are. If you give yourself more items, it treats it like those slots are full, and it skips them. As far as I know the items do not actually exist.

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately this is a vanilla bug. Here's how I found out:
1. get on top of  a block tower or fly up into the air
2. drop a wood stack on the ground below
3. fill hotbar slots with cobble
4. make sure your inventory is on a creative tab other than survival inventory
5. jump down to the stack on the ground and immediately open your inventory while still in the air. 

Your character will pick up the items and you will have the same problem, they are not in your inventory.

**Comment by mezz** [comment]
Seems related to this https://bugs.mojang.com/browse/MC-8409

**Comment by Prospector** [comment]
Hmm I always thought that was intended for creative mode. Though after testing it myself it does seem like a bug because it does that same weird ghost itemy thing. Thanks for clarification.

I wonder if this is something that could be fixed in forge, or if this goes too far into the realm of adding new content.

**Comment by mezz** [comment]
According to the bug I linked, it's marked "Working as intended" so I doubt Forge will want to mess with it. 

I think your bug is subtly different though. Report to Mojang and see what happens?

**Comment by Prospector** [comment]
Sure, I'll give it a shot.

**Comment by mezz** [comment]
Can you link me to the Minecraft issue so I can watch it?

**Comment by Prospector** [comment]
https://bugs.mojang.com/browse/MC-97819

**Comment by mezz** [comment]
Thanks

**Comment by Prospector** [comment]
Apparently my issue was a dupe. Here's the issue, for anyone else following it https://bugs.mojang.com/browse/MC-87019
