### ISSUE TITLE
[1.12.2] Problems in the server.

### ISSUE THREAD

**Issue by Diegomd1303** [mezz/JustEnoughItems#1861]
How to fix the error on a server "JEI has to be installed on the server", more or less, and I have JEI installed in the .minecraft mod folder and in the server mod folder and I don't know what to do, and it doesn't let me either Create recipes that are from other mods by hand... HELP!!

**Comment by Tahakk** [comment]
If you have it installed on both client and server check that you have same version and in case you do post logs here from both your client & server
