### ISSUE TITLE
Just Enough Items encountered an error during the complete event phase

### ISSUE THREAD

**Issue by Kulkoo** [mezz/JustEnoughItems#1866]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by vladimir0903** [comment]
I am also getting this error

[Crash Log](https://gist.github.com/vladimir0903/c2a19a2914825d4785fffdb596febd6d.js)

**Comment by abnerdrummer** [comment]
a mi tambien me aparece este error, se ha producido un error de just enough items (jei) durante la fase complete, ayuda :(
![evidencia](https://user-images.githubusercontent.com/60863917/74118269-94e96c00-4b6f-11ea-89f4-091418071fff.png)
