### ISSUE TITLE
[1.14] Issue with server based recipes

### ISSUE THREAD

**Issue by mcenderdragon** [mezz/JustEnoughItems#1869]
I have recipes which depend on the servers tags so I send them as soon as they are made to the client, but they are not added JEI. is it possible empty categories get deleted? I use `IRecipeManager.addRecipe(recipe, resourseLocation)` and as they are only server side I can not add them before that, also there is no delete option so I cant add dummy recipes I can correct later. Is there a workaround or a different way to achive this?

**Comment by mcenderdragon** [comment]
still valid.

**Comment by KittyKitCatCat** [comment]
i'm having a simmilar issue

**Comment by mcenderdragon** [comment]
By now I just always add them but now they show up to often. Alias each time you join a server a new set of recipes is added.

**Comment by mcenderdragon** [comment]
Go away stale.

**Comment by mcenderdragon** [comment]
At some point I need a anti stale bot...

**Comment by mezz** [comment]
Recipes will have to be synced to the client at some point.
JEI loads after the vanilla server->client recipe sync, so if you can add your recipes at that point it should work.
Manually adding them works, but you should make sure to remove them when disconnecting from the server to avoid adding duplicates.

**Comment by mcenderdragon** [comment]
But how can I remove them? There is no API method for that. if we had a remove function that would be awesome!

**Comment by mezz** [comment]
You can use "hide recipe" here:
https://github.com/mezz/JustEnoughItems/blob/1ea77203d8b731c99cea68166b02afeb3d9c6176/src/api/java/mezz/jei/api/recipe/IRecipeManager.java#L75-L84

**Comment by mcenderdragon** [comment]
That is cool, thanks. Is there also something for bulk operations? Like clear category and add a Collection of Recipes?
