### ISSUE TITLE
Whenever I press "E" to open inventory on single player, JEI crashes my Minecraft (Deleted META-INF)

### ISSUE THREAD

**Issue by Creplin** [mezz/JustEnoughItems#187]
The report file follows:

https://gist.github.com/mezz/e9f516d1983ad3bfdbfb

**Comment by mezz** [comment]
Thanks for the report!
Are you loading JEI from a .jar file in the /mods folder?
Can you please provide the full client log? https://gist.github.com is a good host for large files like that.

**Comment by Creplin** [comment]
No, I opened the .jar, deleted the META-INF file and put the new folder into the /mods folder

**Comment by way2muchnoise** [comment]
Well, you just need to add the .jar to the mods folder. The META-INF folder in the jar contains vital information about access transforming in minecraft code.

**Comment by Creplin** [comment]
Works perfectly now! In single player and on my server! Thank you!
