### ISSUE TITLE
[1.12.2] Launch up issue

### ISSUE THREAD

**Issue by Cursed-Toaster** [mezz/JustEnoughItems#1871]
I get the error (picture attached below) whenever I try to launch JEI. I'm using the latest version of JEI 1.12. I don't know if this is because of something I did or not, I'm sorry to waste your time if it is.
![Capture](https://user-images.githubusercontent.com/60907750/74207316-1c58dd00-4c4d-11ea-9466-48136ff3201f.PNG)

**Comment by Tahakk** [comment]
Its' literally **RIGHT THERE**

_Requires **Minecraft Forge 14.23.5.2816** or above (you have 14.23.5.2768)_

**Comment by Cursed-Toaster** [comment]
> 
> 
> Its' literally **RIGHT THERE**
> 
> _Requires **Minecraft Forge 14.23.5.2816** or above (you have 14.23.5.2768)_

I updated my forge to the lastest 1.12.2 I could...
