### ISSUE TITLE
Hide a block

### ISSUE THREAD

**Issue by Maratonec** [mezz/JustEnoughItems#1877]
Hi,
I am creating a mod using mcreator and I want to hide some blocks from jei. I cant touch to jei config because I am not creating modpack. How can I hide some block from jei only making changes in my mod code?

Thank you,
Maratonec

**Comment by Maratonec** [comment]
Please do you have answer for my question?

**Comment by TehNut** [comment]
You cannot do this with mcreator.

**Comment by Maratonec** [comment]
I will code it, but how?

**Comment by Jdewi12** [comment]
> You cannot do this with mcreator.

iirc mcreator has a java ide built in that lets you edit mods you create with it.
