### ISSUE TITLE
Clientside crash - java.lang.NoClassDefFoundError: mezz/jei/util/StackUtil

### ISSUE THREAD

**Issue by SkyMack** [mezz/JustEnoughItems#188]
Description:
When opening a recipe view in JEI, some of the recipes appear to immediately crash the client. I suspect it is when it tries to render a recipe using a specific machine or set of machines from one of the tech mods. Opening a recipe that defaults to that machine will crash the client, as will flipping through  a set of recipes until you reach that machine/view.

Experienced with:
jei_1.8.9-2.26.0.154 + JEIAddons_1.8.9-0.11.2.56 + JustEnoughResources-1.8.9-0.3.4
jei_1.8.9-2.28.2.166 + JEIAddons_1.8.9-0.12.0.57 + JustEnoughResources-1.8.9-0.3.4

If you need any additional information, just let me know!

Example full crash log: https://gist.github.com/SkyMack/2f9d6f2cdc75b9233bf6

**Comment by mezz** [comment]
Thanks for the report!
This appears to be the same as this issue here: https://github.com/EXTER7/OreDictionaryConverter/issues/9
It should be fixed by updating OreDictionaryConverter.
