### ISSUE TITLE
Unable to toggle cheat mode

### ISSUE THREAD

**Issue by EvinsonCH** [mezz/JustEnoughItems#1880]
Hello, i'm unable to toggle cheat mode using a mac computer.
I've tried everything, but nothing works.
How do I toggle cheat mode?

**Comment by SDUBZ** [comment]
use crtl click on settings button :D

**Comment by IskallDoe** [comment]
I have the same problem on a win10 pc. I cannot access the cheat mode even if use ctrl buttons in the controls settings.
It's pretty annoying. What the problem could be

**Comment by IskallDoe** [comment]
I forgot to mention that i'm on the latest version for minecraft 1.12.2
