### ISSUE TITLE
Jei keeps saying you don't have permission for cheat when i'm  just trying to look at recipes even when i click in inventory

### ISSUE THREAD

**Issue by stonemandave** [mezz/JustEnoughItems#1884]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by SDUBZ** [comment]
turn off cheating mode you might of accidentally ctrl cliked the settings button

**Comment by stonemandave** [comment]
I figured it that's why I closed I accidentally set the hotkey for left mouse click🤦‍♂️
