### ISSUE TITLE
JEI is not working in Minecraft 1.15

### ISSUE THREAD

**Issue by RaZorzPnW** [mezz/JustEnoughItems#1885]
Whenever I load up Minecraft with JEI installed, it won't let me continue to the home screen and says "Just Enough Items(jei) encountered an error during the complete event phase" and "net/minecraftforge/fml/client/event/ConfigChangedEvent$onConfigChangedEvent"

**Comment by KittyKitCatCat** [comment]
Try downloading an earlier forge version, this happens due to a recent change in a forge update.
EDIT: ok not that recent.
