### ISSUE TITLE
java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air

### ISSUE THREAD

**Issue by SDUBZ** [mezz/JustEnoughItems#1887]
forge: 31.1.16
jei: jei-1.15.2-6.0.0.2

just thought i would keep you informed if you haven't noticed this before
logs:
[latest.log](https://github.com/mezz/JustEnoughItems/files/4284221/latest.log)

Note: i have noticed some recipes not working server side 
not sure if jei fault or a mods compat

thanks in advance
if this is caused by another please let me know so i can report to them :D

**Comment by Gamestrust-TS** [comment]
I get the error, searching the internet I found this post, has it been solved somehow?thanks!!


java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air
