### ISSUE TITLE
Auto writing "enough item" on my computer

### ISSUE THREAD

**Issue by megapples** [mezz/JustEnoughItems#1888]
Heya guys, i need you help for a big problem : I dunno if it's due to the mod but recently the words "enough items" just wrote themselves whenever they can, in my search bar, in the mc chat, discord and the list goes on and on... Please help me I'm out of solutions.

**Comment by megapples** [comment]
HELP PLEASE it's like I have a virus on my computer!

**Comment by LiskoSlayer63** [comment]
This sounds like some kind of keylogger and autowriter, definetily NOT caused by this mod! You probably have some kind of malware or virus on your machine, do a scan as soon as possible.

Where did you download the mod?

Do you have any "autotalker" etc. installed?
