### ISSUE TITLE
Problem rendering JER handler with JET tooltip

### ISSUE THREAD

**Issue by thephoenixlodge** [mezz/JustEnoughItems#189]
See https://github.com/superckl/JustEnoughTooltips/issues/2
Apparently the issue is within JEI itself due to the handler expecting a GUI to be open or somesuch.

**Comment by mezz** [comment]
Hmm that's interesting.

**Comment by mezz** [comment]
![2016-02-23_22 08 57](https://cloud.githubusercontent.com/assets/916092/13277038/534fa4c2-da7a-11e5-9934-15ca593bb3b9.png)

Fixed, but a bit derpy looking. I'll leave any further refinements up to JER. 
JEI 2.28.3.168 will upload to curseforge soon with the change.
