### ISSUE TITLE
Game crashes upon loading a world

### ISSUE THREAD

**Issue by AgentKlunk2** [mezz/JustEnoughItems#1890]
Hello,
whenever I try to load a world with any of these mods, Industrial foregoing, Powah, or ProjectE, my game crashes and give me this lovely crash message: java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluid()Lnet/minecraftforge/fluids/Fluid; (see attached crash log)
I don't get the crash when I load the world with these mods, but without JEI. Any person trying to play modded minecraft with mods like these would know just how har it would be without the assistance of a mod like JEI. 
I am currently using minecraft version 1.14.4 and JEI version 6.0.0.10, Forge version 28.1.111 (i have also tried with the latest version of forge and had the same issue)
Here is the crash report
[crash-2020-03-10_04.04.25-client.txt](https://github.com/mezz/JustEnoughItems/files/4311043/crash-2020-03-10_04.04.25-client.txt)
And here is the latest log as well
[latest.log](https://github.com/mezz/JustEnoughItems/files/4311079/latest.log)
Some help would be greatly appreciated

**Comment by ghost** [comment]
Hi, Ive run exactly the same mods as you (list of mods from the crash.txt)
I didnt get any crash
The only difference was Im using JEI 6.0.0.27 and Forge 28.1.118

try with latest JEI 6.0.0.27 and Forge 28.2.1, tested for me and no crash
I found Forge 28.2.2/28.2.3 to cause game crashing

**Comment by AgentKlunk2** [comment]
Oh, I have been unable to find any other version for 1.14.4, due to it not being listed on the files page on curseforge.
P.S. I see it now under recent files on the side of the page
