### ISSUE TITLE
jei_1.12.2-4.15.0.293 don't work with forge 1.15.2-forge-31.1.19

### ISSUE THREAD

**Issue by guihsdev** [mezz/JustEnoughItems#1895]
Crash log to [gist](https://gist.github.com/GuiHS01/448f38f32cc54c558253dcd606178b24)

![image](https://user-images.githubusercontent.com/39705535/76565868-560a4700-648a-11ea-99a8-6466cbdac480.png)

**Comment by TehNut** [comment]
Probably because it's for Minecraft 1.12.2.

**Comment by UpcraftLP** [comment]
> Probably because it's for Minecraft 1.12.2.

nah, can't be that easy

**Comment by guihsdev** [comment]
Sorry, I was trolled!
![image](https://user-images.githubusercontent.com/39705535/76579597-a0e88680-64ab-11ea-8e5d-23087e5c1040.png)
