### ISSUE TITLE
Active Search Textbox, Press 'R' shows recipe

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1897]
JEI 1.14.4-6.0.0.27
Forge 28.2.1

When JEI's search bar is active (ie: im typing in it) if my mouse happens to be over an item and I press 'r' the recipe is shown for that item, meaning I can't type 'r' into the search bar unless I move the mouse off of any items/outside of JEI

a minor bug

Thanks for your time

**Comment by ghost** [comment]
this problem is not Stale as it still persists in 1.14 and 1.15 versions of the mod
jei-1.15.2-6.0.0.3 and jei-1.14.4-6.0.0.27

this problem is related to the 'r' _and_ 'a' keys when typing into the text search bar

**Comment by ghost** [comment]
not stale

**Comment by ghost** [comment]
yes, or no
I cant be the only one

**Comment by Ommina** [comment]
You're not the only one, and this certainly represents a shift of behaviour since the 1.12.2 version.
