### ISSUE TITLE
Creative tabs aren't being translated correctly for % search modifier, and search isn't properly being converted to lowercase

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#190]
Not sure how you would or could work around this, but right now you can only search for creative tab names that are one word long. For example, if you type `%building` You can see the building blocks tab, but once you start typing `%building blocks` It tries to search for items with the word 'blocks' in their name, that are inside the 'building' creative tab.

**Comment by mezz** [comment]
You can use `%building %blocks`, each word is considered independently.

**Comment by Prospector** [comment]
Hm. Didn't really think about that.

**Comment by Prospector** [comment]
Actually that doesn't work.

Searching `%building %blocks` gives no results

**Comment by ProfessorProspector** [comment]
Searching `%building %blocks` gives no results

**Comment by mezz** [comment]
`%blocks` gives no results either, weird. I'll look into it.

**Comment by Prospector** [comment]
Tested it with all the other modifiers, all of them work with multi-word searches except for the creative tabs one.

**Comment by mezz** [comment]
I'm not translating the tab name correctly at all, it's seeing `itemGroup.buildingBlocks`

**Comment by Prospector** [comment]
Hmm that would also explain why only some of the modded tabs are working.

**Comment by Prospector** [comment]
Wait, hold up. Are you sure? I tried searching `%itemGroup.buildingBlocks` and no results came up in JEI.

**Comment by mezz** [comment]
yeah I'm sure, fix incoming

**Comment by Prospector** [comment]
Also, wouldn't `%blocks` be a valid search if the tab name was itemGroup.buildingBlocks?

**Comment by mezz** [comment]
Normally I make everything lowercase for search comparison, I overlooked that too. Both things are fixed and `%building %blocks` works now.

**Comment by Prospector** [comment]
Sweet.

**Comment by Prospector** [comment]
You should pop one of the jenkins badges in the readme so people can see when a build is ready https://dvs1.progwml6.com/jenkins/job/Just_Enough_Items-MC1.8.9/badge/

**Comment by mezz** [comment]
ok
