### ISSUE TITLE
Request/idea: Pleasse add the magnet from Not Enough Items.

### ISSUE THREAD

**Issue by RepoDraghon** [mezz/JustEnoughItems#1910]
I'm currently using 1.12.2 but this could apply to all versions...
Chicken Boness has shut down, someone has picked up the mods but NEI is crashing my game... I would like to use your mod but it has no magnet like NEI...

**Comment by TehNut** [comment]
That is extremely out of scope for this project.

**Comment by RepoDraghon** [comment]
I would argue that it is within because NEI was 1st and this was to a lesser degree a complete copy (ripoff, counterfeit, stolen, etc.) of it, then when the creator of NEI started to lessen his interest in modding, it became a companion mod with JEI. Now someone else has picked up the mod but no one really knows that and that person seems to not really know what to do. Just say, "I don't want to implement it" and be done, cause what you said, to me, sounded misleading.

**Comment by RepoDraghon** [comment]
but thanks... for letting me know...

**Comment by TehNut** [comment]
It's not misleading, it's the truth. This mod is not NEI. It just provides a similar feature.
