### ISSUE TITLE
my minecraft issue

### ISSUE THREAD

**Issue by ming000416** [mezz/JustEnoughItems#1913]
i cant play minecraft mod
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
[crash-2020-03-29_13.48.26-client.txt](https://github.com/mezz/JustEnoughItems/files/4398359/crash-2020-03-29_13.48.26-client.txt)

**Comment by Ommina** [comment]
`Caused by: java.lang.OutOfMemoryError: Java heap space`

You've run out of memory.  Give it more.
