### ISSUE TITLE
Crash when CompactStrings is set

### ISSUE THREAD

**Issue by shadinx2** [mezz/JustEnoughItems#1914]
https://paste.dimdev.org/jiqapuxidu.mccrash
I have 14 gb of ram allocated to MC and justenoughIDs installed so I don't really see what's the problem. This started happening after installing a lot of tech mods all at once if that helps in any way.

**Comment by shadinx2** [comment]
https://github.com/mezz/JustEnoughItems/issues/1327
The error seems pretty similar to this one somehow, but I'm 100% sure I have enough ram. I bumped it from 10gb to 14gb with no success.
java.lang.ArrayIndexOutOfBoundsException -this seems like the kind of thing that happens when going over the id limit(but I have JEID for that).

**Comment by shadinx2** [comment]
After a long search I found the mod that conflicts with JEI. It's Tinkers Construct. I don't know if it's because of another mod or something. Removing either solves the crash. Downgrading either does not solve the crash though. Oof

**Comment by Rimevel** [comment]
https://pastebin.com/GuriHkA6 I dont have tinkers installed but get a crash cause some other reason. Seem to be something to do with fluids.

**Comment by shadinx2** [comment]
> https://pastebin.com/GuriHkA6 I dont have tinkers installed but get a crash cause some other reason. Seem to be something to do with fluids.

Different problem than mine. Ideally you could have opened another thread for it. This issue is the same as one you have as far as I can tell: https://github.com/mezz/JustEnoughItems/issues/1841

**Comment by Ommina** [comment]
I just don't know.  JEI and Tinker's work just fine together.  Although I'd be willing the entertain the possibility that it is a Tinker's addon responsible.

Line 12 of the crash report suggests that JEI is creating its index of items in the game.  My feeling there is that it is some other mod doing Something Weird, which is causing JEI to subsequently choke.  "which", "what", and "how" remain a mystery though.

As an aside, there's no indication at all that it is RAM related.  In fact, I'd argue that 10GB or more is too much.  For the 173 mods listed, five-ish GB seems more reasonable.

Edit: Does the splash screen display a mod name when it crashes?  That _should_ be the mod causing the sadness.

**Comment by shadinx2** [comment]
Found the third culprit for reproducing this bug. I removed all other mods and clean installed minecraft and forge. Then I slowly added jvm arguments until it started crashing. To reproduce the bug you need JEI, TConstruct and -XX:+CompactStrings. I'm using openj9 btw(much faster for me than hotspot) so I don't know if this bug will appear with hotspot(what minecraft normally runs on), but it's worth a shot. Even though I found an easy solution(remove -XX:+CompactStrings) this still probably is a bug so I won't close it for now. Also thanks for the reply Ommina, maybe you can deduce what happened from what I wrote above.

**Comment by LightDimf** [comment]
I occur the same problem when tried -XX:+CompactStrings to optimize the game and the Google bring me here. It's can be considered a bug, but I don't know if it possible to fix it.

**Comment by mezz** [comment]
Compact Strings are supposed to work exactly the same as regular strings (from the application's perspective, so JEI should not need to think about them).
I think this is may be a bug in CompactStrings. There aren't really any unsafe bit-hacking things I can do with strings in Java, so I'm not sure how I'd be causing this bug. It is pretty interesting though.
