### ISSUE TITLE
Pick block (middle-click) straight from JEI list automatically 

### ISSUE THREAD

**Issue by thewaliii** [mezz/JustEnoughItems#1916]
Is there a way to pick block (middle-click) straight from JEI list without search or manual pick?
For example, if I am looking at spruce wood plank block and I click ctr + middle-click then it picks automatically that block from JEI cheat list.

**Comment by TehNut** [comment]
Enable cheat mode and just click on it

**Comment by thewaliii** [comment]
I meant from the gameplay without opening the panel.

**Comment by TehNut** [comment]
I don't believe that is within the scope of this mod
