### ISSUE TITLE
[Feature Request] chunk and mob overlay

### ISSUE THREAD

**Issue by 0uti** [mezz/JustEnoughItems#192]
Plase add chunk grid and mob spawn overlay like NEI has.

**Comment by mezz** [comment]
This feature isn't really related to items and recipes, so JEI will not be adding it.
There are several mods which add these features in 1.8.9 now. Here are two that I've used:
- [Light Level Overlay Reloaded](http://minecraft.curseforge.com/projects/light-level-overlay-reloaded)
- [Just What I Needed](http://www.curse.com/mc-mods/minecraft/233186-just-what-i-needed-mod) (has chunk overlay among other things)
