### ISSUE TITLE
Modpack crash

### ISSUE THREAD

**Issue by Random-crypt** [mezz/JustEnoughItems#1922]
Minecraft crashed. It said JEI was a potential cause. Modpack: Dungeons, Dragons and Space Shuttles

LINK: https://gist.github.com/Random-crypt/08b81134b2c175d1ac9464771aa4dc7b

**Comment by Tahakk** [comment]
`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`

give it more RAM
