### ISSUE TITLE
ChickenBonesLib error

### ISSUE THREAD

**Issue by 2Gud4uM8** [mezz/JustEnoughItems#1923]
Apparently minecraft keeps crashing and traced it to chickenboneslib. Here's log:
https://gist.github.com/2Gud4uM8/7998e11e48e396518bd99158c3061490#file-gistfile1-txt

**Comment by Tahakk** [comment]
Seems that u have something wrong in your config file, just delete it and let it regenerate, i it persist it would be nice to report it to[ propper git](https://github.com/Chicken-Bones) with versions of forge and mod
