### ISSUE TITLE
Client crashing upon joining server - Broken recipes

### ISSUE THREAD

**Issue by Excaliburning** [mezz/JustEnoughItems#1924]
Hello, using latest alpha version of JEI 6.0.0.2 from CurseForge, I can connect to my server but get immediately kicked upon loading terrain following recipes errors as shown [here (crashlog)](https://gist.github.com/Excaliburning/bab437a8b3bb7d9cae4cdd16defbb679).

edit: forgot to mention, I'm using Forge 31.1.36 and MC 1.15.2

Are all the mods listed in the recipe errors at fault for these broken recipes or is JEI going crazy over something that could (maybe ?) be ignored ?
If it's not a JEI issue, I will submit this to the respective mods authors.

Best regards !

**Comment by mezz** [comment]
Thanks for the report!
JEI logs when it finds a broken recipe, but then ignores that recipes so that the game can run. It's a bit noisy in the log, but helps mod authors pinpoint the bugs in their recipes.
I think that JEI is not the cause of your issue here.

**Comment by Excaliburning** [comment]
You're welcome, it can stay closed.
I don't remember at when nor how, but it ended up working again so this issue is solved, not that I know how, but it's fine now.
