### ISSUE TITLE
Loot table documentation

### ISSUE THREAD

**Issue by muzikbike** [mezz/JustEnoughItems#1925]
The mod documents recipes pretty comprehensively, but JEI doesn't seem to touch on loot tables all that much, despite them being just as valid ways of obtaining blocks and items.

This would include block, entity, chest and fishing loot tables, as well as "other" loot tables such as cat gifts, villager gifts and (1.16) bartering. What a block drops would be handled similarly to a block's usage in different recipes.

**Comment by muzikbike** [comment]
shut up bot

**Comment by muzikbike** [comment]
die bot

**Comment by mezz** [comment]
I think this is covered by an addon mod: https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
I have helped with that mod too.
The idea is to keep JEI pretty lightweight, some features in the addon take extra processing or may be tough to port to new versions so it's good to have them separate.

**Comment by muzikbike** [comment]
Does it include block loot tables though?

**Comment by muzikbike** [comment]
Anyway, loot tables (for blocks, entities, loot chests, and the other off cases like villager gifts, cat gifts, bartering and fishing) definitely seem more like something worth implementing in base JEI given how frequently they come up (perhaps even more than recipes), and how closely related to recipes they are, being datapack driven, so having easier access to loot table information without having to download a separate mod that many people may not know about in the first place seems like the better idea to me. The fancy GUIs shown in jer for mob drops and the like probably wouldn't be neccessary either - just symbolise each mob as its spawn egg.

Stuff like ore veins are definitely a better fit for an addon mod since they're pretty different and not data driven.

**Comment by muzikbike** [comment]
bugger off bot
