### ISSUE TITLE
Also document blocks with no direct item form

### ISSUE THREAD

**Issue by muzikbike** [mezz/JustEnoughItems#1926]
There exist many blocks (in vanilla and modded) which do not have a direct item form (attached stems, potted plants, wall versions of blocks, etc.), and these are not displayed in the JEI menu. While not currently a problem, such blocks can have unique loot tables, and following on from #1925, if they are to be documented, having these appear in the JEI menu alongside other blocks may become neccessary.

Potential minor problems may arise from documenting these; for one, as they have no item form, how they would appear in the menu would not be defined, so JEI may have to provide sprites for the blocks in question for them to show up with a valid texture.

**Comment by muzikbike** [comment]
begone

**Comment by muzikbike** [comment]
begone robot

**Comment by muzikbike** [comment]
die bot

**Comment by muzikbike** [comment]
silence

**Comment by mezz** [comment]
I have given my opinion on this here: https://github.com/mezz/JustEnoughItems/issues/1925#issuecomment-647204358

Sorry, but I do not think this functionality should be included in the main mod.
