### ISSUE TITLE
Can't open JEI config menu.

### ISSUE THREAD

**Issue by qwerwastaken** [mezz/JustEnoughItems#1928]
When I click on the wrench in the bottom right, it does not open the config menu. I have cheats on, and it still does not work, I am only using 1.15.2 forge and JEI, nothing else.
I don't know what else to do.

**Comment by Volition42** [comment]
I'm also having this issue.

**Comment by Griefed** [comment]
Can confirm that the config menu doesn't open. CTRL+click to switch the cheat mode does work though. CTRL+o to show/hide JEI works, too.

**Comment by mezz** [comment]
You can track this issue here: https://github.com/mezz/JustEnoughItems/issues/1526
