### ISSUE TITLE
odd visual glitch

### ISSUE THREAD

**Issue by psychicash** [mezz/JustEnoughItems#193]
No crashes 
Using jei_1.8.9-2.27.1.158
with forge-1.8.9-11.15.1.1761-universal

When I'm looking through the items in my inventory, JEI, the recipe screen an odd bug happens.  Frequently the small window appears that would say like "cobblestone" and the rest of the info but it doesn't have the info in it. So it's just a black window appears and no text. Happens quite frequently.

**Comment by wlhlm** [comment]
Could be #183.

**Comment by mezz** [comment]
Thanks for the report!
If it's not happening all the time (like the mapwriter issue), it could be caused by a specific item. That happened before with the RFTools Screen: https://github.com/McJty/RFTools/issues/417

Try to narrow down which item on-screen is causing it.
