### ISSUE TITLE
[1.15.2] Don`t work JEI 

### ISSUE THREAD

**Issue by Rumaruka** [mezz/JustEnoughItems#1936]
I don`t know, but JEI don`t show recipe and don`t show list items
Forge version 31.1.43
JEI 6.0.0.3

![image](https://user-images.githubusercontent.com/8148679/79160516-56805f80-7df3-11ea-8901-c5c3a05b4a08.png)

**Comment by Neo2003** [comment]
Same problem here, jei not showing and no recipes on 1.15.2
Edit: I was using forge 31.1.45, downgraded to 31.1.44 and it's working now

**Comment by Rumaruka** [comment]
I found solution , reinstalled modpack in another profile

**Comment by IainColledge** [comment]
Apologies for butting in but how does one obtain JEI 6.0.0.3 please? I haven't seen it available anywhere.

**Comment by CraftedMods** [comment]
https://www.curseforge.com/minecraft/mc-mods/jei/files/all
CurseForge doesn't show alpha builds in the general filelist.

**Comment by IainColledge** [comment]
Thanks very much
