### ISSUE TITLE
 Minecraft Just Enough Items 1.12.2 not working?

### ISSUE THREAD

**Issue by 007lol** [mezz/JustEnoughItems#1939]
For issues:
There it says that I have to install a dependent mod, but I couldn't find any information about it

**Comment by Tahakk** [comment]
It's working just fine.
Any log, screenshot or any other?

**Comment by Gunnerolaf007** [comment]
I have forge 1.12.2-14.23.5.2768 and I'm trying super hard to play JEI but it keeps crashing. I then downloaded the latest version but it just still crashed please help.  I'm also on a mac
