### ISSUE TITLE
Bug: Two of the same item with different NBT data are registered as the same if you try to bookmark them

### ISSUE THREAD

**Issue by terra-MC** [mezz/JustEnoughItems#1940]
What I mean is that, for example, if I try to save two black shulker boxes with different items, only one of them is bookmarked, the other is treated as if it's a duplicate of the other black shulker box. Same thing applies to banners (only one of each base color can be bookmarked) or renamed items. It seems the bookmark system only registers certain differences between the same item like different maps or different enchanted books (but not different enchantments on armor pieces). Make it so that you're able to add it based on any change in NBT data.

**Comment by Katniss218** [comment]
Yeah, it makes me quite angry that the only feature in TMI that I cared about is not available in any newer versions.

I used TMI to save customized items from various maps back on 1.6/1.7, but I can't do it now because this feature is missing.

**Comment by mezz** [comment]
Thanks for the report! I have pushed a fix for this in the latest version.
