### ISSUE TITLE
1.12 Version

### ISSUE THREAD

**Issue by Shuzza** [mezz/JustEnoughItems#1944]
Is there a 1.12 version for JEI, I cannot find it anywhere. I am not looking for 1.12.2, only 1.12. Thank you!

**Comment by Tahakk** [comment]
[There](https://www.curseforge.com/minecraft/mc-mods/jei/files/all?filter-game-version=2020709689%3A6580) sure is :)
Twitch app installed jei_1.12.1-4.7.8.95 for me tho :) it's up to you to try

**Comment by Gunnerolaf007** [comment]
what would work for forge 1.12.2-14.23.5.278?
