### ISSUE TITLE
Ignore this

### ISSUE THREAD

**Issue by cloudiee1** [mezz/JustEnoughItems#1945]
![image](https://user-images.githubusercontent.com/64161451/80019096-e8145f00-84ce-11ea-9ba4-a2e40d8d369a.png)

**Comment by cloudiee1** [comment]
Never mind please Ignore this

**Comment by cloudiee1** [comment]
Im dumb

**Comment by Randomguy1011** [comment]
Sir, I am also dumb and have the same problem. Could you help me out?

**Comment by Randomguy1011** [comment]
Ironic I also got it after I asked

**Comment by Sharparam** [comment]
[![Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)](https://xkcd.com/979/)

**Comment by mezz** [comment]
The issue is that the version of Forge was too low.
The screenshot shows that the current version is less than the required version.
