### ISSUE TITLE
Jei/Gravestone Mods appear Client side but not Server side. Any help? 

### ISSUE THREAD

**Issue by RayZombie** [mezz/JustEnoughItems#1948]
[debug.log](https://github.com/mezz/JustEnoughItems/files/4533862/debug.log)

Hey, I spent all day yesterday researching and understanding multiplayer in Minecraft. I finally got it working but I noticed I wasn't getting gravestones in multiplayer. I also noticed I had a red text around the plus box that told me I can't move items unless I have JEI installed. Which I do, and client-side everything seems to be working as normal. 

Would you guys happen to have any input? Wondering if there are other mods not working server-side as well. I attached the Debug Log. Let me know if I need to send any more attachments to get help on this issue.

**Comment by mezz** [comment]
Most mods need to be installed on the client and the server.
JEI will mostly work if it is only installed on the client.
Some features require that it is installed on the server too, one of those features is the recipe transfer button.
