### ISSUE TITLE
Unhide individual items/blocks from a group

### ISSUE THREAD

**Issue by StaticPH** [mezz/JustEnoughItems#195]
I'd like to be able to unhide individual objects from a group that was hidden with, say, a wildcard. Take the old ExU drums for example. Using that example, if I hid ALL drums with the wildcard, but still wanted to see the empty drum, I'd like to be able to unhide just that. The current (tedious) alternative is to, one by one, hide each and every single item except for the one i want to see.

**Comment by mezz** [comment]
The use-case you gave sounds common enough to justify adding this feature for sure. 
I think I could accomplish this by turning a group-hide into individual ones.

**Comment by Xiaminou** [comment]
Any news on this? With more and more mods in 1.10.2 it's becoming important to be able to hide many types of items and leave one for the recipe.

**Comment by mezz** [comment]
No news, I haven't had much time to work on new features lately.

**Comment by Xiaminou** [comment]
Alright, thank you for the quick reply.

**Comment by mezz** [comment]
Added this feature in JEI 4.9.1.193
