### ISSUE TITLE
[1.15.2] JEI is trying to validate recipes too early

### ISSUE THREAD

**Issue by whatthedrunk** [mezz/JustEnoughItems#1953]
On ATM5 it seems that JEI is trying to validate recipes before all trees are loaded. When this happens JEI does not seem to load and users have to log into other worlds for it to load before they can see and use JEI. 

[I have no crash log but here is my lastest log showing JEI not starting until I jump into another world. ](https://paste.ubuntu.com/p/WKqTjtxXrH/)

**Comment by whatthedrunk** [comment]
Here is another person talking about the issue over a month ago but the stale bot closed it.
#1920

**Comment by whatthedrunk** [comment]
Looks like it may actually be Bonsai Trees if you can take a look. https://github.com/thraaawn/BonsaiTrees/issues/184 
This was also posted here again as #1955

**Comment by xy795** [comment]
Same issue here
JEI only shows up after I create a new singleplayer world

forge-1.15-31.2.8
jei-1.15.2-6.0.0.4
BonsaiTrees-2.1.2.6

**Comment by mezz** [comment]
I'm not exactly sure what the issue is here, I think it is from Bonsai Trees though because JEI loads pretty late.
