### ISSUE TITLE
1.12.2 now uses FG3 too

### ISSUE THREAD

**Issue by RythenGlyth** [mezz/JustEnoughItems#1959]
I'm using `1.12.2-14.23.5.2854`

According to the JEI wiki, for mc 1.12.2 this code works:
```
dependencies {
  // compile against the JEI API but do not include it at runtime
  deobfProvided "mezz.jei:jei_${mc_version}:${jei_version}:api"
  // at runtime, use the full JEI jar
  runtime "mezz.jei:jei_${mc_version}:${jei_version}"
}
```
This fails because FG3 uses the new commands, like this:
```
dependencies {
  /* minecraft dependency is here */

  // compile against the JEI API but do not include it at runtime
  compileOnly fg.deobf("mezz.jei:jei-${mc_version}:${jei_version}:api")
  // at runtime, use the full JEI jar
  runtimeOnly fg.deobf("mezz.jei:jei-${mc_version}:${jei_version}")
}
```
but jei releases are still named in the old pattern ("mezz.jei:jei_${mc_version}:${jei_version}") notice the underscores.

Please change in the wiki
Thanks

**Comment by leonbtww** [comment]
if I paste that into the build.gradle it does not work.

**Comment by RythenGlyth** [comment]
@leonbtww it is downloading but not working that's why i did [this](https://github.com/mezz/JustEnoughItems/pull/1963), but then the textures are not working, but i don't know why

**Comment by leonbtww** [comment]
bruh
