### ISSUE TITLE
Game Crash on Startup

### ISSUE THREAD

**Issue by RythenGlyth** [mezz/JustEnoughItems#1960]
When i start my game:
[Crash Report](https://gist.github.com/RythenGlyth/29f3164ed8a26eb96ccee6ae75f26379#file-gistfile1-txt)

I have Minecraft 1.12.2, forge-1.12.2-14.23.5.2854  and i tried jei versions 1.12.2-4.15.0.268 and 1.12.2-4.15.0.291 both keep crashing

I'm using the forge mdk. Even when I put the mod inside the run/mods folder it doesn't work, but with the normal version of forge but same version it does work

**Comment by mezz** [comment]
Thanks for the report!
I think the latest Forge is using ForgeGradle3, try using a slightly older version of Forge.
