### ISSUE TITLE
JEI Hidden, Won't Unhide

### ISSUE THREAD

**Issue by Siveheart** [mezz/JustEnoughItems#1961]
I am using version 1.3.0 version of the Omnia pack from Feed the Beast. I began having the issue while playing 1.2.0. The FTB staff were unable to help me and suggested that I post here instead. My JEI has hidden itself and the keys to unhide are not working. I've tried assigning different keys, reinstalling the modpack, updating JEI, deleting all configs, etc, but nothing I have tried has fixed the issue. If I create a new world, JEI is visible in that world, but not within the primary world that I play in.

**Comment by Siveheart** [comment]
https://github.com/FTBTeam/FTB-Omnia/issues/61

**Comment by GordonHollow** [comment]
I have the same issue on AllTheMods5 modpack.

JEI don't show, all the control buttons don't work.

Mod started correctly and show in list of loaded mods, no crash or something.

Situation the same as i play without JEI installed

**Comment by Tahakk** [comment]
You could try to delete/redownload JEI config file to see if it helps
