### ISSUE TITLE
Just Enough Items not loading (fabric)

### ISSUE THREAD

**Issue by DanielPBak** [mezz/JustEnoughItems#1968]
I am trying to use jei-1.15.2-6.0.0.4.jar, client-side only.

My other mods are loading fine. They are:

fabric-api-0.10.8+build.310-1.15
LightOverlay-4.6.1
modmenu-1.10.2+build.32

But JEI is not visible in the mod menu, and does not appear to be loading.

Does JEI not support Fabric? If it does, what is the issue here?

**Comment by antoinegag** [comment]
JEI does not support Fabric as far as I know.

**Comment by DanielPBak** [comment]
Thanks!

That information should be more clear.
