### ISSUE TITLE
Background size

### ISSUE THREAD

**Issue by Sleepwalkerx** [mezz/JustEnoughItems#1969]
I made a mod with a large workbench and I had a problem integrating my mod with JEI. As you can see in the screenshot, the craft item crawls out of the scope and I had a question. How to increase the background? (Avaritia code didn't help me)

P.s. I found something in the JEI code that is responsible for the background size, but it is set through the constructor and it cannot be changed in any way ... 

Can I do something?

JEI version - 6.0.0.4 
Minecrfat - 1.15.2
![pc](https://user-images.githubusercontent.com/62907629/82733559-42e2e580-9d1d-11ea-90ec-786c6f979513.PNG)

**Comment by mezz** [comment]
Thanks for the report!
This is a bit silly... but you can just put the output below so that it fits.
I had to put some limits somewhere unfortunately, and I think this is pretty generously wide already.
