### ISSUE TITLE
Pixylmon Battle menu, JEI, Don't mix.

### ISSUE THREAD

**Issue by Lithorn** [mezz/JustEnoughItems#197]
No crash to mention, just a slight incompatibility between JEI and Pixylmon.

Having the two enabled will cause issues with the Battle menu, in that you can't select certain actions at times. During battles you will often be stuck unable to exit your Bag, Or press escape, or click "Back" on the attack menu. The issue only occurs if JEI is installed along with Pix. Without JEI, Pix runs just fine. 

I have mentioned this also to Pixylmons Dev.

**Comment by mezz** [comment]
Thanks for the report!
I haven't heard of similar issues from any other mod. 
Can you link to your issue report to Pixylmon, to keep these together?
I'll wait for their response and go from there.

**Comment by Prospector** [comment]
I'm almost wondering if there's some other JEI addon that's causing it. Because I would think this would only cause any issues in the inventory screen.

**Comment by mezz** [comment]
I found the issue here and replied: http://www.pixelmonmod.com/tracker.php?p=2&t=7882

**Comment by mezz** [comment]
Talked with clienthax.
He's adding JEI integration to fix the buttons that overlap.
Guis like the starter selection screen were showing JEI on the side, and those are fixed by this: https://github.com/mezz/JustEnoughItems/commit/e4481f551b508ceb41e9d1c559ee377161409ae9
