### ISSUE TITLE
Jei Crashes Game when Try to use İt

### ISSUE THREAD

**Issue by DragonQwertik** [mezz/JustEnoughItems#1972]
So when I try to do anything in my inventory the game just shuts down: Pls Help
Here is the crash report:
https://gist.github.com/DragonQwertik/e6b73e6bb9f87f8f85795f77433976c5

**Comment by TurboPanda** [comment]
Hey Dragon,
I was having the same issue as you it seems. Try going into your config folder and deleting the "jei" and "jeresources" folder then relaunch the game. For whatever reason, this fixed the issue for me. Hope it works for you!

**Comment by mezz** [comment]
Thanks for the report!
This crash does not reference JEI at all, it seems to be from this item:
```
-- Item being rendered --
Details:
	Item Type: com.vicmatskiv.weaponlib.Weapon@734b508e
	Registry Name: mw:m16a4
	Item Aux: 0
	Item NBT: null
	Item Foil: false
```
