### ISSUE TITLE
6.0 Version - exists on curse but not on github

### ISSUE THREAD

**Issue by redrezo** [mezz/JustEnoughItems#1974]
I'm irritated. curse has a 6.0 download (for minecraft 1.15.2) (https://www.curseforge.com/minecraft/mc-mods/jei/files/2944279) but there is no github tag / release

I'm assuming you just build it from master and there is no tag - but my first thought was somebody else added it to curse for their own bot net - if so they would have already 474,619 downloads ;-)

**Comment by ChloeDawn** [comment]
Any files uploaded to the project on Curse would be done through Mezz's account, so you can rest assured it is an official build ^^ I think the lack of GitHub release tag is just an oversight. I don't think anyone can be blamed for overlooking things with all of the distractions in the world right now heh.

**Comment by way2muchnoise** [comment]
1.15.2 is clearly on the github, see https://github.com/mezz/JustEnoughItems/blob/1.15/gradle.properties and the [latest commits](https://github.com/mezz/JustEnoughItems/commits/1.15) match what is in the changelog on the file

**Comment by ChloeDawn** [comment]
Yes, the issue though is the lack of a [GitHub release tag](https://github.com/mezz/justenoughitems/releases) for 6.0.0, not the lack of source/commits for it.

**Comment by mezz** [comment]
Thanks for the report!
I had just forgotten to push the tag. There is no need for concern.
I have pushed the missing tag now.
