### ISSUE TITLE
Cant see control settings information on non English Languages

### ISSUE THREAD

**Issue by FifteenKarat** [mezz/JustEnoughItems#1976]
If I use a language other than English, the information text shifts and I can no longer see where to make a change.
Since **everything is good in the English version**, it would be great if this was also fixed in other languages.

It looks like this:

![Cant see Informations](https://user-images.githubusercontent.com/60288646/83941898-40898c80-a7ef-11ea-8a16-951a3aac7b00.png)

I tried it on German and Spanish

If you had to change that individually, I would like to know how so that I can fix it myself.

**Comment by Tahakk** [comment]
Are u sure this is JEI related? Also you didn't posted any versions of MC, Forge, JEI

**Comment by mcenderdragon** [comment]
yes this is caused by JEI, as the german translations are partialy wrong/misleadign and super fucking long. If you scroll down you see the string goes all over the place.

**Comment by mezz** [comment]
Thanks for the report!
Weird. I'm open to contributions to fix the German control translations overflowing here.
https://github.com/mezz/JustEnoughItems/blob/1.15/src/main/resources/assets/jei/lang/de_de.json
