### ISSUE TITLE
JEI and shaders Don't mix on 1.12.2

### ISSUE THREAD

**Issue by furbzy** [mezz/JustEnoughItems#1977]
Game crashes every time i hit E with shaders active says its a JEI error.

Minecraft: 1.12.2
Forge: 14.23.5.2847
JEI: 1.12.2-4.15.0.293
optifine: 1.12.2 HD U F5

[crash-2020-06-11_23.02.22-client.txt](https://github.com/mezz/JustEnoughItems/files/4768571/crash-2020-06-11_23.02.22-client.txt)

![7706fef74d760dc6d30255b97c02e995](https://user-images.githubusercontent.com/49768639/84460613-67552200-ac38-11ea-81a8-c5b3d0cc2dd5.png)

**Comment by Tahakk** [comment]
Optifine isn't usually supported by most of the mods since it's code is closed, you can try different versions tho

**Comment by furbzy** [comment]
> Optifine isn't usually supported by most of the mods since it's code is closed, you can try different versions tho

any suggestions ?

**Comment by Tahakk** [comment]
Do you mind me asking where did you get your JEI version? On Curse there is .291 as the latest one, and that one with OF F5 works just fine.

**Comment by furbzy** [comment]
> Do you mind me asking where did you get your JEI version? On Curse there is .291 as the latest one, and that one with OF F5 works just fine.

1.12.2-4.15.0.293

**Comment by Tahakk** [comment]
Now I see, it's hidden under the Beta tag. Try the .291 version, or re-download your pack, it should all work just fine
