### ISSUE TITLE
could you make a versio for 1.7.10

### ISSUE THREAD

**Issue by kartoon360** [mezz/JustEnoughItems#1987]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Tahakk** [comment]
1.7.10 is not supported by most of the mods in the first place

**Comment by muzikbike** [comment]
Who in their right mind would play 1.7.10 in 2020?

**Comment by BlueCreeper160** [comment]
I recommend use Too Many Items

**Comment by mezz** [comment]
Sorry there will not be a JEI for 1.7.10.
Each mod has written a plugin to be compatible with JEI. There would be no mod support in a 1.7.10 version of JEI because most development on 1.7.10 has stopped and nobody would write plugins.
