### ISSUE TITLE
It says 'just enough items encountered an error during the complete event phase' on minecraft 1.15.1 what do i do?

### ISSUE THREAD

**Issue by girlsrule1** [mezz/JustEnoughItems#1992]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Ommina** [comment]
"If you crashed, please paste the crash log to gist and link it here."

**Comment by girlsrule1** [comment]
I didnt crash 
It let me onto minecraft before it said the message

**Comment by girlsrule1** [comment]
> "If you crashed, please paste the crash log to gist and link it here."

I didn't crash
It let me on to Minecraft before saying the message

**Comment by Ommina** [comment]
If there is no crash, then we'll need a link to the full latest log.  With a single exception message, there is very little that can be done to narrow down the problem (if there even IS a problem).

There simply isn't enough to work with here.

**Comment by girlsrule1** [comment]
Okay i will post the latest log.


> If there is no crash, then we'll need a link to the full latest log. With a single exception message, there is very little that can be done to narrow down the problem (if there even IS a problem).
> 
> There simply isn't enough to work with here.

ok I will post the latest log.
can I just copy and paste it onto here or no?

**Comment by girlsrule1** [comment]
[latest.log](https://github.com/mezz/JustEnoughItems/files/4866311/latest.log)
Thats the latest log

**Comment by girlsrule1** [comment]
> If there is no crash, then we'll need a link to the full latest log. With a single exception message, there is very little that can be done to narrow down the problem (if there even IS a problem).
> 
> There simply isn't enough to work with here.

Can you please respond

**Comment by mezz** [comment]
Please try on Minecraft 1.15.2, I don't know if 1.15.1 is supported.

**Comment by girlsrule1** [comment]
Oh ok thank you
Could you please think about creating one for 1.15.1
