### ISSUE TITLE
I can't see a download for 1.12.2. I think I remember seeing it before. Was it removed?

### ISSUE THREAD

**Issue by AnD468** [mezz/JustEnoughItems#1996]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
You can find all the 1.12.2 releases of JEI here:
https://www.curseforge.com/minecraft/mc-mods/jei/files/all?filter-status=1&filter-game-version=2020709689%3A6756
