### ISSUE TITLE
[1.16.1] No Option to have search bar center

### ISSUE THREAD

**Issue by BedrockLegends** [mezz/JustEnoughItems#1997]
Thank you for reporting!

I cant seem to find away to make the search bar center like we did in 1.12

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
The config is not complete in versions 1.13 and higher, you can read more about it and track the issue here: https://github.com/mezz/JustEnoughItems/issues/1526
