### ISSUE TITLE
Issue with Cheatmode

### ISSUE THREAD

**Issue by AcesGamingUK** [mezz/JustEnoughItems#1999]
So i recently added the mod [More Commands](https://www.curseforge.com/minecraft/mc-mods/morecommands)
and now JEI cheatmode isn't working
I ctrl-LClick the "wrench" and I instantly get a stack of NetherStars and the `you do not have permission to use....`
Yes I have OP perms,
Yes I can use the standalone /give

no it still wont work

[Vid](https://drive.google.com/file/d/1JPwAh781ExyoTnygXqA1z9emh6R6-dWW/view?usp=sharing)
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I guess More Commands is changing the way permissions work somehow.

Here is the logic JEI uses to figure out if you have permission on the server to cheat:
https://github.com/mezz/JustEnoughItems/blob/a67739408843a2e96348edcfd776895bbdba4bf9/src/main/java/mezz/jei/util/CommandUtilServer.java#L71-L92

With that information, the developer of More Commands may have a better idea of what has gone wrong here.

**Comment by mezz** [comment]
I have added more clear messaging around this, and server configs for who is allowed to cheat. JEI will let you know what type of permission you are missing for the server you are connected to, so players shouldn't run into this problem any more.
