### ISSUE TITLE
[Suggestion] Easily hide items/blocks from JEI

### ISSUE THREAD

**Issue by Vexatos** [mezz/JustEnoughItems#2]
Maybe a new button on the GUI's top left next to the delete button, click on a block in NEI and it will > vanish from the list. Those items could then be re-enabled in the options menu.
EDIT:
> Also, so server-side override
> if the server hides an item
> it'll be hidden for all the players

**Comment by mezz** [comment]
There is now "Edit Mode" in the config.
When you hover over an item in the list in Edit Mode, it has a tooltip telling you what you can do.
Crtl-click to toggle blacklist,  Ctrl-right-click to toggle wildcard-blacklist.
Blacklisted items have a colored background that matches the tooltip so you know what's happening.
Everything you blacklist will end up in the `JEI.cfg` file if you want to transfer them for a modpack or whatever.

There is also an API for mods to blacklist things, which is separate from the config. Things blacklisted by the API are hidden from the item list even in Edit Mode.

Items that are hidden will still show up in recipes if they're in one.

**Comment by Akxe** [comment]
This feature is great, but I dont understand why there is such flaw in implementation. 

The wildcard is completely useless unless you are able to override any of it... I would like to hide, all applied energistic's facades but one... I want to be able to have one, for the recepie, and the rest be gone...

Or keep it hidden, but as soon as I type something into filter, it would show up at the end of list maybe even after a free row (for visual separation) and with half the opacity? Please, both solutions are great... and could be done even together... but the first is more important if any.
