### ISSUE TITLE
Items in the JEI menu are invisible

### ISSUE THREAD

**Issue by Arcticzomb** [mezz/JustEnoughItems#2000]
Basically, most to all items in the search bar next to my inventory are invisible. I've removed my shaders and resource packs to see if it would work but it hasn't.

Edit: I have also restarted Minecraft with and without texture packs/shaders.

Edit 2: After more testing I found out that the problem originates from the latest pre-release of optifine(or all of them) that's causing these  texture bugs. You can disregard this post as it is now irrelevant.

**Comment by mezz** [comment]
Thanks for the report!
Hopefully this is less of an issue over time.
