### ISSUE TITLE
[1.12.2]Crashed while I pressed 'E'

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2003]
When I try to open my backpack in minecraft, it crashed. It never happened before. I've also installed NEI and JEI Villagers, I don't know if there's any matter with this crash...
With crash log.
[crash-2020-07-08_15.07.15-client.txt](https://github.com/mezz/JustEnoughItems/files/4889150/crash-2020-07-08_15.07.15-client.txt)
[crash-2020-07-08_15.06.08-client.txt](https://github.com/mezz/JustEnoughItems/files/4889156/crash-2020-07-08_15.06.08-client.txt)
![Crash Page](https://user-images.githubusercontent.com/67999219/86891613-b4da8700-c131-11ea-8d66-01b821036fe4.png)
Sorry that they are all Chinese...

**Comment by mezz** [comment]
Thanks for the report!

```
-- Ingredient being rendered --
  Ingredient Mod: IndustrialCraft 2
  Ingredient Info: 1xic2.fluid_cell@0 ic2:fluid_cell nbt:{Fluid:{FluidName:"ic2weed_ex",Amount:1000}}
```

I think this bug is between Optifine and IC2, please try removing one to see.
You can report this bug to them as well.

**Comment by ghost** [comment]
Well,thanks bro!------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;James&amp;nbsp;Mitchell&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月2日(星期天) 上午8:18
收件人:&nbsp;&quot;mezz/JustEnoughItems&quot;<JustEnoughItems@noreply.github.com&gt;;
抄送:&nbsp;&quot;MSMint&quot;<2661734285@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mezz/JustEnoughItems] [1.12.2]Crashed while I pressed &#39;E&#39; (#2003)
