### ISSUE TITLE
[1.14/1.15/1.16] Please add the ability to search by item/block tags

### ISSUE THREAD

**Issue by theboo** [mezz/JustEnoughItems#2004]
Would be amazing if you guys could add the ability to search by block/item tags added in MC1.13 in JEI. # currently searches the tooltips but is rarely used, maybe it could be expanded to the block and item tags shown in f3+h (advanced tooltips) mode when the player has that enabled.  Or even $ could be the prefix since that was the old oredict prefix which has been replaced by the tags.

something like #/$forge:stone would bring up anything with the forge stone tag. Would be super useful for pack devs

**Comment by Drullkus** [comment]
There used to be a way to search by ore dictionary key before that got booted for Vanilla's tags. Oredict's prefix could be recycled instead to search by tag.

**Comment by mezz** [comment]
Thanks for the report!
`$` searches tags but it is disabled by the config, and the config is broken at the moment (please see https://github.com/mezz/JustEnoughItems/issues/1526)
Once the config is implemented properly, this feature will be available.

**Comment by mezz** [comment]
This is supported in the latest version for 1.16.3
![2020-10-11_18 43 02](https://user-images.githubusercontent.com/916092/95696863-ad73bf80-0bf1-11eb-8779-632972be4ac6.png)

**Comment by Spongman** [comment]
doesn't work in enigmatica 6. jei-1.16.4-7.6.1.65

**Comment by Spongman** [comment]
the weird thing is that the `$` prefix works fine in RefinedStorage, so a synchronized search results in this:
![image](https://user-images.githubusercontent.com/1088194/112731164-e6c78f80-8ef2-11eb-8eaf-cfe7af8a0e1f.png)
