### ISSUE TITLE
None of the versions working with the latest version of Forge

### ISSUE THREAD

**Issue by FatalPhenomenon** [mezz/JustEnoughItems#2006]
I have used this mod every single time I download Minecraft on the same computer. Now all the versions I have been trying to download, upon importing into the game will come up with the error message of I need to download a newer version of forge even though I have the newest.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
