### ISSUE TITLE
[1.14.4] Adding JEI to my Eclipse Dev Environment

### ISSUE THREAD

**Issue by TheCosmicNebula** [mezz/JustEnoughItems#2008]
Hi, I am beginning the process of updating my mods to 1.14.4 from 1.12.2. I am trying to add JEI into my Eclispse Project, but am getting this error when I follow the tutorial on the Developer Github:

`Could not resolve: mezz.jei:jei-1.14.4:6.0.0.29_mapped_snapshot_20190719-1.14.3`

Its adding the `_mapped_snapshot` etc but of course those files do not exist on the maven listing. I have never had this issue when adding JEI before.

**Comment by mezz** [comment]
Sorry I'm not sure what the issue is, ForgeGradle can fail for a lot of strange reasons.
Please try asking in the MinecraftForge Discord, there are more people with a better understanding: https://discord.gg/UvedJ9m
