### ISSUE TITLE
missing potions in item list

### ISSUE THREAD

**Issue by janf3** [mezz/JustEnoughItems#201]
JEI is missing some of the basic 2-step potions in the item list (Fire Resistance, Healing, Night Vision, Water Breathing, as far as I can tell). It only

https://imgur.com/a/iH3jB
The first and second screenshot are the potions listed in JEI.
The third one is the basic (2 step) recipe which you only get to by clicking the "ingredient" potion in the second picture.

Seems weird since it is properly showing all three possible potions e.g. for Regeneration or Strength.

Tested with release 2.28.6.173 as well as beta 2.28.7.174
Tested both in SMP and SSP.

**Comment by mezz** [comment]
Thanks for the report!
JEI grabs the potions from the creative item list, are they missing from there? The potion recipes shown in JEI are generated based in the available starting ingredients, so it may find more that way.

**Comment by janf3** [comment]
You are correct. They are indeed missing from the Creative Item list.

I just checked, in 1.7.10 they are missing from creative too but NEI does substitute the "4 steps" one with the missing 2 step potion. That's probably why I never noticed.

I guess it's an enhancement request then. But JEI seems to be in a good place right now so if that messes things up I can live without it.

**Comment by mezz** [comment]
This doesn't seem to be an issue anymore in 1.10, since Mojang rewrote the potion system.
