### ISSUE TITLE
Provide underlying recipe to IRecipeTransferHandler 

### ISSUE THREAD

**Issue by shartte** [mezz/JustEnoughItems#2010]
Same underlying issue as #312, but we'd like to just send the Recipe ID over to the server, since server and client now sync recipes, this should be safe. The recipe transfer handler will not provide us with the currently shown recipe (or it's ID) however.

Would it be possible to add this?

**Comment by mezz** [comment]
Sounds good! 
For the new interface, I am just sending you an `Object` recipe so you'll have to check that it's the instance type you expect, but it should work now.

**Comment by shartte** [comment]
Ah, thanks. That is fine, the recipe interface has a #getId method which should be sufficient for this!

Thanks. That'll allow us to finally get rid of the 300kb packets where we send the Ingredient's resolved ItemStack lists over the network to do recipe transfers 😇
