### ISSUE TITLE
Some problems with 1.8.9

### ISSUE THREAD

**Issue by NonSkilledMan** [mezz/JustEnoughItems#2011]
So I installed ic2 along with jei (all 1.8.9) and everything worked fine.
After that I decided to install Inventory Tweaks (1.8.9 as well) and created a server. After joining the server I noticed that some of the jei features don't work or just broken. Along with that I saw that  Inventory Tweaks installed NoCheatPlus plugin on my server (although I didn't have a plugin folder) which might be the case, but I don't know, even after deleting the mod the jei was still broken. 
Also some of the config setting are not tootip defined for some reason.
Here are the issues.
![ohno](https://user-images.githubusercontent.com/68250715/87353271-2157ea80-c565-11ea-8e28-819afafe52f8.png)

By the way I tried changing every single option I could and still didn't fix it.

**Comment by Tahakk** [comment]
1. 1.8.9 is ancient version, thus not supported
2. you might want to specify versions of the mods you have so that someone with similar issue might help you

**Comment by NonSkilledMan** [comment]
>     2. you might want to specify versions of the mods you have so that someone with similar issue might help you

All of my mods are 1.8.9

**Comment by Tahakk** [comment]
> All of my mods are 1.8.9

version of the mod, not version of the MC

**Comment by NonSkilledMan** [comment]
> version of the mod, not version of the MC

![image](https://user-images.githubusercontent.com/68250715/87413619-34090880-c5d3-11ea-95bb-102d2c521cfe.png)

Again, everything worked fine with this modpack.
