### ISSUE TITLE
Dupe items

### ISSUE THREAD

**Issue by Serega007RU** [mezz/JustEnoughItems#2017]
https://youtu.be/Qd9n7Lg0qiI?t=325
time code 5:25

**Comment by mezz** [comment]
Thanks for the report!
I think this is a bug with the auto-chisel inventory, please report to them too and link back here.

**Comment by Serega007RU** [comment]
no, the problem I think is on your side, see the screenshot, I indicated there how this problem can be solved
![image](https://user-images.githubusercontent.com/64780091/89166581-eef94600-d582-11ea-88d1-8e5ecffdf04b.png)

**Comment by mezz** [comment]
Thanks, you're right!

**Comment by mezz** [comment]
Fixed in version 4.16.1

**Comment by mezz** [comment]
Applied the fix for versions on 1.14.4, 1.15.2, and 1.16.2 as well.
