### ISSUE TITLE
Smithing table support for 1.16.1

### ISSUE THREAD

**Issue by Trnrr** [mezz/JustEnoughItems#2019]
Will smithing table support be added? It currently doesn't show recipes for it.

**Comment by Niketats** [comment]
Yes! I need this!

**Comment by nepphhh** [comment]
It is worth noting that https://github.com/thedarkcolour/Future-MC/wiki implements this for 1.15 already.

Looking forward to seeing Smithing table recipes; it's a bit confusing at the moment.

**Comment by mezz** [comment]
Added in JEI 7.3.1 for 1.16.2
