### ISSUE TITLE
Add support for custom smelting/smoking/campfire cooking/blasting time.

### ISSUE THREAD

**Issue by BetaCarotina** [mezz/JustEnoughItems#2023]
Using the .json recipe format, you can set a custom cooking time other than 100 ticks (blasting/smoking), 200 ticks (smelting) or 600 ticks (campfire). An example of a mod that uses custom cooking time is Aquaculture 2, for its jellyfish smelting and neptunium blasting recipes.

**Comment by mezz** [comment]
Thanks for the suggestion!
I have added a string displaying the processing time in seconds to these recipes, and animate the arrow based on the time.
