### ISSUE TITLE
I cant see the tab of crafting table

### ISSUE THREAD

**Issue by Chris8585** [mezz/JustEnoughItems#2025]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Chris8585** [comment]
![image](https://user-images.githubusercontent.com/69218406/89341611-c9416f00-d65e-11ea-9d94-dca664b80e03.png)
![image](https://user-images.githubusercontent.com/69218406/89341646-d65e5e00-d65e-11ea-9ec4-be7dbc57dd6c.png)

**Comment by mezz** [comment]
Thanks for the report!
I think these items may not be in crafting table recipes.
Try looking at a different item like planks, and the crafting table tab should show.
