### ISSUE TITLE
[1.16] move items button not working

### ISSUE THREAD

**Issue by fruitytoast** [mezz/JustEnoughItems#2027]
Hi there, I'm having some issue on my server getting the [+] move items button to function. I've seen before people saying that the latest version of JEI needs to be installed on the server for this feature to function, but still it does not work; just closes the recipe window and goes back to the crafting grid. Works fine in single player.

I am on JEI 1.16.1-7.1.9 & forge 32.0.106

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
