### ISSUE TITLE
[1.16.1] JEI doesn't show up in my mods folder ingame. Minecraft doesn't seem to recognize it.

### ISSUE THREAD

**Issue by Tae47** [mezz/JustEnoughItems#2028]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by stargateguy1** [comment]
I too seem to be having an issue where the JEI panel on the right side of the inventory GUI is not showing. In addition, the key controls for JEI also do not seem to be working. I did not see any issues in the debug file, so I am not sure exactly what is causing the issue. I believe it is the latest version of Forge as I revered back to the version I was using prior to updating and got the same result. Issue is happening on Forge version "forge-1.16.1-32.0.106". If you'd like to see the debug file, just let me know.

**Comment by Blugori** [comment]
Hi, I got this proble mwith forge 0.108 too, that's too sad :( , are you planning to release new versions for 1.16.1 or are you focusing on 1.16.2 ?

**Comment by mezz** [comment]
Thanks for the report!
I am only focused on the latest versions for each release: 1.12.2, 1.14.4, 1.15.2, and 1.16.2.
There is a lot to support, and the community always moves on to versions this way, so it is best to keep moving forward.

**Comment by Blugori** [comment]
Yes that's true, I'll just wait for mods to be updated in 1.16.2 and I'll enjoy more jei at that time :) thanks for your hard work !
