### ISSUE TITLE
JEI is not working!

### ISSUE THREAD

**Issue by ItIsJustX** [mezz/JustEnoughItems#2029]
JEI is not showing the JEI menu in-game. I have over 80 mods downloaded and I also have tried using the button to make the menu reappear and nothing happens

**Comment by stargateguy1** [comment]
i was having this problem too. reported it also in the previous issue thread. seems to be the latest version of forge. JEI is initialized and loaded and can be seen as active in the game, but none of the keybinds or functions seem to work. hopefully it gets fixed soon!

**Comment by Ommina** [comment]
It would be really really really handy if somebody affected by this could include the basics:

Forge Version
JEI Version
pastebin link to debug.log

**Comment by stargateguy1** [comment]
Forge Version is 32.0.107
JEI Version is 7.0.1.9
 And pastebin will not let me do the paste since it is larger than 512 kilobytes. Can give a share link to the latest debug on my google drive if that works for you.

**Comment by stargateguy1** [comment]
First noticed it on Forge 32.0.106. I realized I should've put that first since .107 just came out earlier today.

**Comment by TomaszewskiPatryk** [comment]
I had a similar issue, and after a lot of digging and messing around with the mods, it turned out to be caused by a recipe with an invalid ingredient (in my case it was an item tag <tag:forge:wool>, which no longer exists in forge).

**Comment by stargateguy1** [comment]
Alright. How did you end up fixing it?

**Comment by TomaszewskiPatryk** [comment]
> Alright. How did you end up fixing it?

Well, it was caused by my custom script in CraftTweaker, so I just changed that.
If you are unsure if you have any custom scripts, I suggest just removing CraftTweaker and OpenLoader to see if it helps. Otherwise, try updating all the mods, maybe one of them is using an old tag.

**Comment by MaikiNG12** [comment]
I have the same problem :(

**Comment by MaikiNG12** [comment]
> > Alright. How did you end up fixing it?
> 
> Well, it was caused by my custom script in CraftTweaker, so I just changed that.
> If you are unsure if you have any custom scripts, I suggest just removing CraftTweaker and OpenLoader to see if it helps. Otherwise, try updating all the mods, maybe one of them is using an old tag.

I have the same problem, but I can´t update all the mods because... I have more than 200 ._.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
