### ISSUE TITLE
Forge Version

### ISSUE THREAD

**Issue by datznoah** [mezz/JustEnoughItems#2031]
I can't find an answer to this anywhere, but does the version of forge have to be the version in the name of the JAR file? If so, is there one for 1.12.2 - 14.23.5.2854, or do I have to downgrade to use JEI?

Thanks in advance. :)

**Comment by Ommina** [comment]
The Forge version numbers do not need to match.  Typically, you can usually use later versions of forge, and often, earlier as well.

Later versions, though, are a better bet, as Forge, too, will be fixing bugs and adding new abilities with later versions.
