### ISSUE TITLE
Display Recipe ID for Smelting-type recipes

### ISSUE THREAD

**Issue by Drullkus** [mezz/JustEnoughItems#2036]
Crafting recipes display their recipe ID when `F3`+`H` "Advanced Tooltips" are enabled, it'd be nice if there was a way to see the recipe resource location for Smelting/Smoking/Blasting/Campfire recipes, or even universally on all types of recipes.

**Comment by mezz** [comment]
Good idea, I added this for all `IRecipe` categories
