### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by epicwappy20** [mezz/JustEnoughItems#2038]
my game crashes every time i open my inventory. i get this error, The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.field_147003_i from class mezz.jei.gui.GuiProperties. i am not using optifine. please help!

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
