### ISSUE TITLE
[1.16.1] All item tooltips in JEI turn gray

### ISSUE THREAD

**Issue by Shadows-of-Fire** [mezz/JustEnoughItems#2039]
As of MC 1.16, it would appear that all item tooltips shown in JEI turn gray.  This does not seem to affect tooltips added via the ItemTooltipEvent (at least, I think), and only the ones added via the item's own `addInformation` call.

It affects both vanilla and modded items.
JEI: 
![](https://i.imgur.com/izg64j0.png)
![](https://i.imgur.com/BMEFV2N.png)
Player Inventory: 
![](https://i.imgur.com/KFen39B.png)
![](https://i.imgur.com/mqMe1zb.png)

Note how the modid added by HWYLA is not affected, yet all other tooltip information is.

**Comment by mezz** [comment]
Thanks for the report!
This is probably because the text formatting method names were not in MCP yet. Working with them has been confusing heh.

**Comment by mezz** [comment]
Looks like I was doing some formatting that's no longer necessary in 1.16 since tooltips are made up of proper `ITextComponent`s now.
