### ISSUE TITLE
Add the machine's processables to the machine's usage

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#204]
It would be real nice to be able to search up the uses for a crafting table to bring up the recipes that are crafted in it. This could be added in a couple ways (and both of them should be added IMO):
- Machine's processes in usage (example: when I view uses for crafting table, all crafting table recipes show up
- When viewing the machine's JEI handler, show the machine in the corner so you can view the crafting recipe of the machine itself. (example: when I view alloy smelter recipes, I can click on an alloy smelter icon in the corner to view the recipe of the alloy smelter itself)

**Comment by mezz** [comment]
Currently working on this. It's a big feature, making a real mess of things. I think it will be really good to have though.

**Comment by mezz** [comment]
![2016-04-29_14 03 26](https://cloud.githubusercontent.com/assets/916092/14929664/79620f0c-0e13-11e6-8eac-64a54c17bcfe.png)

**Comment by KnightMiner** [comment]
does this support multiple stacks for a single handler? Like could a mod add their crafting table to a list for vanilla crafting then animate through that, or otherwise a mod list multiple machines for their own recipe?

**Comment by mezz** [comment]
It should yes, I haven't tested it yet since 1.9 is lacking mods heh.

Registration looks like this:

``` java
registry.addRecipeCategoryCraftingItem(new ItemStack(Blocks.CRAFTING_TABLE), VanillaRecipeCategoryUid.CRAFTING);
registry.addRecipeCategoryCraftingItem(new ItemStack(Blocks.FURNACE), VanillaRecipeCategoryUid.SMELTING, VanillaRecipeCategoryUid.FUEL);
registry.addRecipeCategoryCraftingItem(new ItemStack(Items.BREWING_STAND), VanillaRecipeCategoryUid.BREWING);
```

I'll do some tests to make sure it's working properly.

**Comment by mezz** [comment]
There were some glitches, they're fixed now.

**Comment by Prospector** [comment]
Awesome!
