### ISSUE TITLE
Game Save and Crash Botania mod with Just Enough Items (JEI)

### ISSUE THREAD

**Issue by Trodor** [mezz/JustEnoughItems#2042]
Game Save and Crash Botania mod with Just Enough Items (JEI) Mod

**Comment by Tr4nz1uc3nt** [comment]
Getting this in 1.16.1 as well. Crashes any time I start to look up "na..." in JEI, with the crash report showing some error regarding Natura Pylon in Botania. Haven't yet found a fix for it, but unfortunately I also can't remove Botania, as it's one of the main mods on my server.

**Comment by AidilRiski** [comment]
I also have this problem. Here is the log if it may help.

https://pastebin.com/mzPf0sBD

**Comment by mezz** [comment]
Thanks for the report!
This has been solved by Botania: https://github.com/Vazkii/Botania/issues/3412
