### ISSUE TITLE
crashed game when i searched "f" and i cant go back onto the world while using jei anymore 

### ISSUE THREAD

**Issue by pipps17** [mezz/JustEnoughItems#2045]
https://gist.github.com/pipps17/4efb8d45c18976ba3babb37dd182c4f4

i have 35 mods loaded but in the error log it says all the mods are working fine.
the error when minecraft crashed was
the game crashed while rendering ingrediants
ERROR: java.lang.ArrayIndexOutOfBoundsException: -1

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with Optifine and OpenBlocks: https://github.com/sp614x/optifine/issues/2267
