### ISSUE TITLE
i dont what to do 

### ISSUE THREAD

**Issue by Lake20004** [mezz/JustEnoughItems#2048]
Thank you for reporting!

For issues:Keeps telling me Jer needs an language prpvider jajafml33 i dont understand it was working when i was playing an little bit ago 
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by ravenbuilder934** [comment]
That means your JEI version is ahead of your Minecraft/Forge version (FML=Forge Mod Loader)
