### ISSUE TITLE
1.16.1 rending issue

### ISSUE THREAD

**Issue by MrStatman80** [mezz/JustEnoughItems#2049]
My game as just crashed as it's a rending issue with JEI and Botania which i'll send Vakii an issue as well

https://pastebin.com/JeqVzNJs

That's the crash report if it helps as i'm playing on 1.16.1 and forge 32.0.18 version

**Comment by mezz** [comment]
Thanks for the report!
This is probably an issue with Optifine and Botania, JEI is just showing the item here.

**Comment by MrStatman80** [comment]
No if it was just Optifine then it would't say mezz.JEI would it???

And i sent Vakii the same message

**Comment by MrStatman80** [comment]
Plus i haven't started Botania yet and so why does it crash then?? As i wasn't looking up Botania

**Comment by MrStatman80** [comment]
And don't say Optifine as that's and easy go to

**Comment by MrStatman80** [comment]
The fact is JEI crashed on 1.16.1 and you don't want to amend it

**Comment by MrStatman80** [comment]
And i told Vakii you blame them for the crash

**Comment by Ommina** [comment]
Goodness, for a moment there I thought Twitter had changed layouts again.

I wouldn't dream of suggesting Optifine.  However, a crash report without Optifine in the stack trace would be useful to both the JEI and Botania devs.

Edit:

Except: https://github.com/Vazkii/Botania/issues/3412

**Comment by mezz** [comment]
I have responded to and routed hundreds of these issues over the years, so at this point I’m pretty confident when I recommend the best place to start investigating. 
Please understand that we have a good relationship between modders in this community and I am not blaming anyone. The bug is simply not caused by JEI, and has been resolved very quickly by the other developers.

**Comment by MrStatman80** [comment]
So why does it said JEI and Botania then???
And you both put it down to optfine which I tested it and not to blame

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mezz** [comment]
JEI displays a list of items, similar to how items are displayed in your inventory.
I have received many reports like this so I have added diagnostic information to the crash logs, here's what I see for yours:
```
-- JEI render details --
Details:
	Unique Id (for Blacklist): botania:mana_pylon
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1 mana_pylon botania:mana_pylon
	Filter Text: na
	Edit Mode Enabled: false
	Debug Mode Enabled: false
```

In this case you have typed "na" into the filter, and the Botania Mana Pylon is being rendered in the JEI item list.

Based on the stack trace, Optifine has altered some parts of the rendering pipeline. This is a frequent cause of incompatibility with mods and something we work to fix very often.

Here is the relevant portion of the stack trace that shows Optifine has altered the regular rendering pipeline, making me believe it is very likely to be involved here:
```
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:252) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:407) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:447) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:436) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
```

> And you both put it down to optfine which I tested it and not to blame

If you can send the crash report without Optifine here then I'd be interested to see.

**Comment by MrStatman80** [comment]
But I just sent the report cos Vazaii said it’s on your end if not Optifine...

And I checks it only happened when I type in JEI MAN then I crash

And I was looking for Manager for Refine Storage I typed Man and I crashed all the time

So I sent you the bug report as it said JEI and I Sent Vakaii one as well and they said it’s on you

**Comment by williewillus** [comment]
@MrStatman80 I am the maintainer of Botania.

First and foremost, this is an Optifine issue. Let me repeat that again: **it's Optifine**. We know because we have observed this pattern through several reports. If you removed it, this problem would go away entirely.

Second, Botania has added extra safety checks to try to mitigate Optifine's hackery. Update to 1.16.1-403.


Finally, this has nothing to do with JEI and would happen any time a pylon shows up in an inventory.

**Comment by MrStatman80** [comment]
So why does it Crash when I type man then crash and crash report comes up as Botania and JEI??

The Fact is a crash using both mods and yes Optifine in installed but only for fps as I lag if not installed

I installed Optfine as with mods I lag and only without it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MrStatman80** [comment]
And second of all I keep my pack updated  using all of them and updating when new updates comes out

So due to my bug report it make Vakii update?? Since you said it was his fault

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by KingLemming** [comment]
I'm reading this and am just stunned how you are clearly able to read a crash report and yet not able to read down to the 10th line of it to see that Optifine is, in fact, the cause.

**Comment by Vazkii** [comment]
my dude this is optifine breaking the mod just accept it
