### ISSUE TITLE
Categories are being merged together strangely

### ISSUE THREAD

**Issue by williewillus** [mezz/JustEnoughItems#205]
See: https://github.com/williewillus/Botania/issues/172#issuecomment-194581398

I build on JEI 2.25.7.145. User has 2.28.x and sees two of my categories merged together under one.

My code https://github.com/williewillus/Botania/tree/MC18/src/main/java/vazkii/botania/client/integration/jei

**Comment by mconwa01** [comment]
The earliest version where the problem occurs is 2.28.0.160. Works fine in 2.27.2.159.

**Comment by mconwa01** [comment]
Could it have something to do with the fact that Botania's RecipeRuneAltar extends its RecipePetals?
https://github.com/williewillus/Botania/blob/f5b71f9db1fd299884863da5e4c05fec24dbf464/src/main/java/vazkii/botania/api/recipe/RecipeRuneAltar.java

Wild guess that it's related to this change between v2.27.2 and v2.28.0:

```
diff --git a/src/main/java/mezz/jei/RecipeRegistry.java b/src/main/java/mezz/jei/RecipeRegistry.java
index dc9d49f..ef0a64e 100644
--- a/src/main/java/mezz/jei/RecipeRegistry.java
+++ b/src/main/java/mezz/jei/RecipeRegistry.java
@@ -265,12 +265,13 @@ public IRecipeHandler getRecipeHandler(@Nullable Class recipeClass) {
            return null;
        }

-       IRecipeHandler recipeHandler;
-       while ((recipeHandler = recipeHandlers.get(recipeClass)) == null && (recipeClass != Object.class)) {
-           recipeClass = recipeClass.getSuperclass();
+       for (Class<?> handledClass : recipeHandlers.keySet()) {
+           if (handledClass.isAssignableFrom(recipeClass)) {
+               return recipeHandlers.get(handledClass);
+           }
        }

-       return recipeHandler;
+       return null;
    }

    @Nullable
```

**Comment by williewillus** [comment]
oh what the hell, it does?
if that really is the cause (need confirmation) I'll fix it on my end

**Comment by mezz** [comment]
Yeah that's probably the cause. If you have a `RecipePetals` handler registered first, it will handle `RecipeRuneAltar` too. You can probably fix it by registering the more specific handler first, or just make it not extend.
