### ISSUE TITLE
[1.16.1]On Forge Server Jei not showing up recipes from other mods.

### ISSUE THREAD

**Issue by Jartko** [mezz/JustEnoughItems#2050]
**###  Hi,**
I add a few mods and jei on minecraft forge server.
JEI only shows recipes from vanilla minecraft and enchant in the anvil of all tools
In singeplayer issue does not occur.
*i tried to change the forge and JEI versions*

**Comment by konsaril** [comment]
Same.
On LAN Mode the Hoster sees the recipies but other players dont.
On Forge Server no one can see the recipies
