### ISSUE TITLE
Enchantment Book Info

### ISSUE THREAD

**Issue by Darkhax** [mezz/JustEnoughItems#206]
I was going to write this as a separate side mod, however I feel it might be much more beneficial as part of the main mod itself. The main concept behind this mod is to add something like the description recipe, but targeted towards enchantment books. The idea is that a description key would be generated based on the enchantment on the book, and then add that recipe into the description list. 

I have a similar feature in WAWLA and Enchanting Plus which show the description for the enchantments, and have descriptions written up for all of the vanilla enchantments which could also be used in JEI.

**Comment by mezz** [comment]
This sounds good! Feel free to make PR. It would be a new folder under `jei/plugins/jei` along with `description` as part of the `JEIInternalPlugin`.

**Comment by Darkhax** [comment]
Sure, I can make the PR. Would you like this to be a new plugin, or a built in part of the description plugin? I was thinking about directly adding it into the description plugin, however that might be a bit odd, and require #207 to be dealt with first.

**Comment by Prospector** [comment]
IMO it should be it's own plugin.

**Comment by AEnterprise** [comment]
maybe it's own plugin with an api hook so other mods who add enchants can add descriptions for those?

**Comment by Darkhax** [comment]
Well the way I currently do it in Wawla and Enchantment plus is to generate a translation key using the enchantment name, and then try to get a body of text for that message. If there is no translation, then there is no description provided. This would allow the mod author to just put the localization in their lang files, and have it work automatically. If we were to go for an API/Registry for adding description, that would be somewhat counter productive, as we can already add descriptions to enchantment books using the current system.

**Comment by Prospector** [comment]
Also could it have useful info about the enchant, like the mod that added it, enchantment id, etc?

**Comment by Darkhax** [comment]
I am not sure if it is possible to show the mod that added the enchantment yet. 1.8.9 still uses a raw numeric ID system, and it doesn't actually log that info. If anyone knows how to get it, I can factor that in as well. Right now it would be limited to min/max enchantment levels, the enchantability and numeric ID. Once Mezz moves things over to 1.9 though, I should be able to show mod name, and a lot of other stuff, like where the item effect is valid (chestplate, boots, held item, stuff like that).

**Comment by way2muchnoise** [comment]
@darkhax as there is an [official forge build](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.9.html) and he did some work with a custom build already in the [1.9 branch](https://github.com/mezz/JustEnoughItems/tree/1.9). I don't think it will take long before an official JEI for 1.9

**Comment by Darkhax** [comment]
Okay, I guess I will be targeting 1.9 with this then :p Although now that 1.9 builds of forge are public, I have to focus some time into updating my own mods. Shouldn't take too long though.

**Comment by mezz** [comment]
Any update @darkhax ?

**Comment by Darkhax** [comment]
After further discussion with you on IRC we determined that an NBT sensitive version of the recipe handler would be needed to get the correct enchantment info. Have there been any changes on that front?

**Comment by mezz** [comment]
It is possible now, enchanted books are correctly differentiated from each other.

**Comment by Darkhax** [comment]
Oh right, forgot this issue existed. This feature was added in the [Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions) mod and is no longer an issue.
