### ISSUE TITLE
It may be a compatibility issue

### ISSUE THREAD

**Issue by 404nill** [mezz/JustEnoughItems#2060]
<img width="960" alt="註解 2020-08-23 122112" src="https://user-images.githubusercontent.com/59758693/90970856-875c6800-e53c-11ea-9dff-1c0fbfe4e990.png">
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Valafi** [comment]
Just ran into this too. Looks like a small mistake with the latest build.
Affected version: jei_1.12.2-4.16.1.300

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next release.
