### ISSUE TITLE
[Request] IngredientInfoRecipeCategory setRecipe change

### ISSUE THREAD

**Issue by ThatGravyBoat** [mezz/JustEnoughItems#2061]
Hello there,
I would like to request a change to the Ingredients Info category, currently the info category wont render ingredients if they are not an ingredient thats a ItemStack or FluidStack due to the categories `setRecipe` method only checking those 2 it would be nice if it can use the ingredient type that's provided from the recipe to set the recipe ingredient using the IRecipeLayout `getIngredientsGroup` method.

Im not 100% sure this method will work but if it does it would be nice if it can be changed to it.
Thanks for reading and i'm sorry if I wasted your time with this request if it does not work.

-ThatGravyBoat

**Comment by mezz** [comment]
Good suggestion, that is how it should have worked anyway. 
Added in the next version.
