### ISSUE TITLE
 hello the JEI mod does not work well (@ version @) and when will they release the update to repair it?

### ISSUE THREAD

**Issue by Rodrix8050** [mezz/JustEnoughItems#2068]
Hi I've been making a mod pack but it didn't give me the mod, please it's one of my favorite mods :c

**Comment by Tahakk** [comment]
Duplicate of #2060

**Comment by Valafi** [comment]
@Rodrix8050 are you sure you're using the latest release? You forgot to mention which version you're using.

**Comment by mezz** [comment]
Thanks for the report!
Please update to the latest version, that one has an issue.
