### ISSUE TITLE
[1.12.2] Crash with Forge Gradle 3 (ATs)

### ISSUE THREAD

**Issue by Enginecrafter77** [mezz/JustEnoughItems#2069]
### The problem
The issue has been previously mentioned in #2009. However, @mezz closed the issue as solved, but the issue still persists (it was probably reintroduced with 4.16.1).

In short, the issue lies in Access Transformer handling in Forge Gradle 3. It seems that Forge Gradle 3 does not use the Access Transformers provided by JEI. As such, it fails to start because of `IllegalAccessException`.

A temporary workaround is to copy-paste the JEI AT into your own Access Transformer config, but that seems rather impractical in the long run. Especially when you want to just use JEI as a nice tool to help debugging your own mod.

### The solution I am proposing:
If viable, upload a  FG3-compatible 1.12.2 JEI version (4.16.0 most probably) to the maven repository.

**Comment by mezz** [comment]
I have reverted the FG3 changes, it doesn't seem to be viable for 1.12.2. Support for ATs, resources, and dependencies is buggy and uncharted territory. Since I ran into so many issues I decided to move back to FG2 on 1.12.2, unfortunately.

**Comment by Enginecrafter77** [comment]
Oh okay then. So there probably isn't a way to get FG3 working with this. I suppose the main problem is the terrible lack of documentation for FG3 on 1.12.2 (there are literally NO documents about FG3 with 1.12.2 besides the comments supplied in build.grade in the MDK), together with the fact that the whole forge team turned their backs to one of the most popular modded minecraft version. Anyways, thanks for your attention.

**Comment by MichaelHillcox** [comment]
This is actually intended functionality. I have no idea why but FG3 for 1.12 just does not bring over AT. I don't know if this is the same thing above 1.12 for FG3 but this definitely isn't a JEI issue... I'd recommend avoiding FG3 with 1.12 as it was an after thought and poorly planned migration.

**Comment by Enginecrafter77** [comment]
Okay so apparently the only solution to this problem is downgrading to ForgeGradle 2.3, since FG3 doesn't have good support for ATs. I am closing this issue to mark it as solved (and to avoid cluttering the feed).
