### ISSUE TITLE
Recipes on meta and nbt sensitive items. 

### ISSUE THREAD

**Issue by Darkhax** [mezz/JustEnoughItems#207]
I am not entirely sure how to explain this issue, as it is a bit tricky to narrow down. The primary issue is that recipes are being grouped together based on meta and nbt, when they probably shouldn't be. Here are a few examples of what I mean. 

If you have 1 item with 5 meta states, and give each a unique description recipe, they would only show their own description, however if you were to then add a generic description to that item without specifying a meta value, it would group all 5 description recipes, plus the one generic recipe together. 

In Botania, if you look up the recipe for any flower, it starts you off with the pure daisy recipe, regardless of where you started in the list. 

If you were to add a description to a ItemStack with an nbt value such as an enchanted book, the description will show the correct enchanted ItemStack, however when you add more, it won't display the correct discreption based on the item you clicked on, and it will start you off with the first one registered.

**Comment by Darkhax** [comment]
This issue was caused by several misunderstandings. If anyone has similar issues they should make sure that they set hasSubTypes to true if applicable. And if you want to reference a generic ItemStack that is not meta specific, OreDictionary.WILDCARD_VALUE should be used.

**Comment by mezz** [comment]
Thanks for the followup!
