### ISSUE TITLE
[Suggestion] Highlight Items when double-clicking search bar?

### ISSUE THREAD

**Issue by marios-andr** [mezz/JustEnoughItems#2071]
This used to be a NEI feature I believe but I did not see it on the spreadsheet so here goes:
The you double click the JEI search bar it will highlight items that have the name of the item you were searching. For example, if you search "gold" and double click the search bar JEI will highlight all items that have "gold" in there names in your current gui.

**Comment by way2muchnoise** [comment]
That feature is added in [More Overlays](https://www.curseforge.com/minecraft/mc-mods/more-overlays).

[See this spreadsheet](https://goo.gl/MQ0f3R) for old NEI features and what mods currently add them.
