### ISSUE TITLE
[1.16.2] Move Items "+" not placing items in crafting slots

### ISSUE THREAD

**Issue by n810K** [mezz/JustEnoughItems#2074]
Steps to Reproduce:

1) Open inventory, default is "e"
2) Select item from the list of items on the right that I want to craft. For example, "Crafting Table".
3) Click the icon
4) The recipe now shows up and a "+" symbol appears that when hovered, shows "Move Items".
5) Pressing this "Move Items" button does not do anything

Expected Function: 

Move items into the 2x2 or 3x3 crafting slots depending on whether the user is in the default inventory or in a crafting table.

With the steps above, my wooden planks should have been moved into the 2x2 crafting slots within the inventory. I do in-fact have the required items.

Other Mods:

BetterPVP
Optifine
Xaero's World Map

Additional Notes:

I have tried closing the built in crafting assistance, but the results are still the same.
This issue has occurred on versions previous to 1.16.2. I remember this issue existing in 1.15

**Comment by mezz** [comment]
Thanks for the report!
Please try removing other mods to see if one is causing a bad interaction with JEI.

**Comment by n810K** [comment]
> 
> 
> Thanks for the report!
> Please try removing other mods to see if one is causing a bad interaction with JEI.

Hey! Thanks for the speedy reply, I've all other mods but the issue still persists. 

I am on Forge 1.16.2 - 33.0.22, in case this might be the difference.

**Comment by mezz** [comment]
I need some more information to solve this issue, can you please paste your full `latest.log` to https://gist.github.com and link it here?

**Comment by n810K** [comment]
https://gist.github.com/enn810/0a1e6b939b6645e1294e9a79eca30019

Here is the log. I made sure to try to move the items into the crafting spaces before gathering the log data. 

I took a quick glance at the log as well, but I tried using JEI without any other mods, so I'm pretty sure that the Shaders entries are not the problem. I tried to use JEI without any mods as suggested before, which included the disabling of Shaders.

**Comment by mezz** [comment]
Thanks! Unfortunately it looks like the other mods are still installed, and the log isn't showing much from JEI.
Do you have the server log as well, or are you in singleplayer?

**Comment by n810K** [comment]
No problem! And I re-enabled the mods since I found that even when all the mods were disabled, JEI wasn't working. So I thought it would be okay to re-enable all the other mods for now.

And I'm on a server. Looking at the server, nothing gets added to the log/server status when I attempt to move the items into my inventory.

**Comment by YeehawChucklefucks** [comment]
> No problem! And I re-enabled the mods since I found that even when all the mods were disabled, JEI wasn't working. So I thought it would be okay to re-enable all the other mods for now.
> 
> And I'm on a server. Looking at the server, nothing gets added to the log/server status when I attempt to move the items into my inventory.

I had this same issue as well on my server. My issue was that Just Enough Items was not installed to the server, so I just dragged it into the mods folder for the server and that fixed it.

**Comment by n810K** [comment]
> 
> 
> > No problem! And I re-enabled the mods since I found that even when all the mods were disabled, JEI wasn't working. So I thought it would be okay to re-enable all the other mods for now.
> > And I'm on a server. Looking at the server, nothing gets added to the log/server status when I attempt to move the items into my inventory.
> 
> I had this same issue as well on my server. My issue was that Just Enough Items was not installed to the server, so I just dragged it into the mods folder for the server and that fixed it.

Does this still apply to a Vanilla Server? And I'm not sure if I'm allowed to reference other mods, but there is a similar version of this mod but using Fabric, and I never had the problem while using the Fabric version.

**Comment by mezz** [comment]
Just Enough Items must be installed on the server to support the `+` button. 
The server does the work of moving the items around quickly.
