### ISSUE TITLE
[1.16.1] JEI lagg

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [mezz/JustEnoughItems#2075]
Playing modpack: All the mods 6

When opening my inventory the framerate becomes abysmal on a 1440p screen resolution. 
It drops down from 580 fps to like 25 - 50, the second jei is closed its fixed again.
(My mouse becomes sluggish and crafting doesnt go as fast due to this)

Typing gibberish in the search bar so I find little to no items resolves the issue. 

It seems that theres a problem with rendering too many items on the screen?

I can reproduct the issue on 2 different machines. 
One machine has the following hardware:  (I9 9900k and a RTX 2080 + 32Gb ram with 8Gb allocated to the pack)

**Comment by Ommina** [comment]
See also #2030
