### ISSUE TITLE
just enough items javafml:33 error (NVM Fixed)

### ISSUE THREAD

**Issue by tokkonii** [mezz/JustEnoughItems#2078]
![Screenshot (28)](https://user-images.githubusercontent.com/68045405/91876141-5ec62380-ec4a-11ea-825b-3b140a9851b5.png)

Get this error every time I open up Minecraft, couldn't find any help on the internet. Using Forge-1.16.1 - 32.0.108

**Comment by Tahakk** [comment]
Looks like you are using 1.16.2 JEI with 1.16.1 MC. Anyways upgrade Forge to 33.x and MC version or downgrade the JEI to the proper 1.16.1 version

//edit
answered for other ppl searching this issue - if you figure it out you should post it
