### ISSUE TITLE
Latest 1.16.1 ver not working with modded server

### ISSUE THREAD

**Issue by Ske3lly** [mezz/JustEnoughItems#2079]
I have a modpack, can link it if needed and I've set up a server with it to play with some friends but JEI doesn't seem to load whatsoever on the server. I'm struggling to play without it, forge version is 32.0.108 and here's a log I got from pressing the search bar on a refined storage network with JEI synchronised: https://gist.github.com/Ske3lly/4dc45485b155f0c1237026844e454c18

**Comment by Ske3lly** [comment]
Also I think it's a compat issue, but I don't know which mods are causing this

**Comment by optionboom** [comment]
You should link the modpack. I'm getting the same issue (JEI not loading in at all) with Refined Storage and ElementalCraft together, but not individually.

**Comment by Prophious** [comment]
i'm having the same issue, different mod set(custom of like 140+) but i does seem to fix its self after relogging like 3-7 times

what i can assume is that it is client side that the mod errors(if that's what it is) when you have booted up a fresh minecraft game and join in to a server, but like i said it kinda corrects its self after like 3-7 relogs, and will continue to work until you close out minecraft all the way, then you would have to do the same thing again

i do not have Refined Storage or ElementalCraft in my pack

**Comment by mezz** [comment]
Thanks for the report!

`	at com.refinedmods.refinedstorage.screen.widget.SearchWidget.updateJei(SearchWidget.java:33) ~[?:1.9.2] {re:classloading}
`

This issue is with Refined Storage, if you still encounter this error please report it to them here: https://github.com/refinedmods/refinedstorage/issues
