### ISSUE TITLE
Is there any way to make a wildcard recipe handler?

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#208]
Is there a decent way to make a handler that says any item can be used in it?

**Comment by way2muchnoise** [comment]
Use `ItemStack` as class to be handled I guess

**Comment by mezz** [comment]
You can generate the recipe wrappers ahead of time and pass them to JEI.
Can you give an example? Claiming to handle every item is probably bad practice.

**Comment by Prospector** [comment]
Recycler from TechReborn can turn any itemstacks into scrap.

**Comment by mezz** [comment]
Well... from `IRecipeWrapper.getInputs()` just return `Collections.singletonList(IItemRegistry.getItemList())` ?

**Comment by mezz** [comment]
@ProfessorProspector did this work for you?

**Comment by Prospector** [comment]
Sorry haven't tried it yet.

**Comment by Prospector** [comment]
Cannot make a static reference to the non-static method getItemList() from the type IItemRegistry

**Comment by TehNut** [comment]
Use your instance of IItemRegistry

**Comment by Prospector** [comment]
derp I am a derp
