### ISSUE TITLE
Vanilla Search Bar Error

### ISSUE THREAD

**Issue by xzefir** [mezz/JustEnoughItems#2080]
Hello, I have one error when I use your mod (JEI) with FaomFix, when I search one item in Vanilla bar nothing appears 
(see the screen) 
![Capture](https://user-images.githubusercontent.com/42659411/92038672-0db24e80-ed74-11ea-8c8e-baec3f32a044.PNG)

In the console there is two errors :

` [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: java.lang.NullPointerException
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at net.minecraft.client.util.SearchTreeManager.func_110549_a(SourceFile:51)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:530)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at java.lang.reflect.Method.invoke(Unknown Source)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
 [STDERR]: [net.minecraft.client.util.SearchTreeManager:func_110549_a:53]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

And

`[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: java.lang.NullPointerException
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at pl.asie.foamfix.client.jei.SearchTreeJEIItems.func_194038_a(SearchTreeJEIItems.java:59)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:395)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:343)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[STDERR]: [pl.asie.foamfix.client.jei.SearchTreeJEIItems:func_194038_a:66]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

Thank you !

**Comment by mezz** [comment]
Thanks for the report!
Please report this to foamfix here: https://github.com/asiekierka/FoamFix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
