### ISSUE TITLE
Unable to toggle cheat mode on macOS

### ISSUE THREAD

**Issue by thislooksfun** [mezz/JustEnoughItems#2083]
Ctrl+click on the settings button in JEI 7.3.2.25 does not toggle cheat mode on macOS since ctrl+left click on the trackpad is bound to right click at the system level. I think [this](https://github.com/mezz/JustEnoughItems/blob/e01c9aad01f3a9f89eee41606201bf215d95cb82/src/main/java/mezz/jei/gui/overlay/ConfigButton.java#L73) needs to be changed to check `GLFW.GLFW_KEY_LEFT_SUPER` and `GLFW.GLFW_KEY_RIGHT_SUPER ` if `Minecraft.IS_RUNNING_ON_MAC` is true.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version.
