### ISSUE TITLE
Recipe Ordering

### ISSUE THREAD

**Issue by Ceifeire** [mezz/JustEnoughItems#2085]
Hi,

This is not much of an issue as it is a question. I am using a mod called Artisan Worktables to make custom recipes for certain items, mostly equipment. My question, is there a way to re-order the recipe tabs when you select the item to see how to make it? At the moment my new recipe using the custom table is the last option and the first option that appears is the enchantments on the anvil.

I am asking the mod creator as well if he has had this issue but I wasn't sure which of you would have more control over this.

![JEI, artisan recipe issue](https://user-images.githubusercontent.com/38624271/92429033-c7d3fc80-f15e-11ea-83d2-e1a69621025a.png)

**Comment by mezz** [comment]
Thanks for the request!
In newer versions of JEI there is now a config to order recipe columns, see the config file in `config/jei/recipe-category-sort-order.ini`
