### ISSUE TITLE
API Request: remove limitation of one RecipeHandler per Recipe Class

### ISSUE THREAD

**Issue by Aroma1997** [mezz/JustEnoughItems#209]
I have one recipe class, that I want to show under different categories in JEI. The problem I have:
I register one IRecipeHandler for that recipe class, make it only accept the recipes I want for this category.
When I now register the second IRecipeHandler for that recipe class accepting other recipes, the game crashes, when I load the world, it crashes here: http://pastebin.com/7UmLh0ZT ( https://github.com/mezz/JustEnoughItems/blob/6aacda5782de9a4e4f2a150fcac11d744377b44d/src/main/java/mezz/jei/RecipeRegistry.java#L80 ), because both of these handlers use the same Recipe Class.
I suggest removing this limitation. This allows for splitting recipes into different categories by registering multiple handlers.

**Comment by mezz** [comment]
Interesting. Can you give me a real example of the recipes you want to support so I can make sure I implement this correctly?

**Comment by Aroma1997** [comment]
Let's say machine recipes:
For example you have a machineRecipe OneInputOneOutput.
And each machine has its own "registry"/list, where you put your recipes via new OneInputOneOutput().
To make them in show up in JEI, you need to make a wrapper recipe for every instance of OneInputOneOutput, containing a reference to the original list/whatever to sort them into different categories.
Currently, I would need to create a new recipeWrapper class for every machine (or just make one recipeWrapper class and make empty child classes that are just there for the sake of being a different class), to sort them into different RecipeCategories.
Alternatively making a recipe-aware version of IRecipehandler.getRecipeCategoryUid() would also work.

**Comment by Aroma1997** [comment]
An other solution to this would be to make getRecipeCategoryUid() in IRecipeHandler recipe-aware.

**Comment by mezz** [comment]
`getRecipeCategoryUid()` in `IRecipeHandler` is now recipe-aware in JEI 3.5.0
