### ISSUE TITLE
JEI crashing as i open inventory.

### ISSUE THREAD

**Issue by Afonsoprogo** [mezz/JustEnoughItems#2090]
Hello.

So i have a modpack and JEI is causing some problem.
When i open my inventory in game it sudently just crashes if u have something to do to get my problem then thank you.
Crash report:

[crash-2020-09-16_00.46.48-client.txt](https://github.com/mezz/JustEnoughItems/files/5228779/crash-2020-09-16_00.46.48-client.txt)

**Comment by Cattycat1029** [comment]
I'm having the same issue but it only happens when the jei menu is open. If I open the recipe book instead my game runs fine.
Here's my crash report: https://docs.google.com/document/d/1UiC5Ivf821gyhG_JMr5d8P3zQYQnDk2XdMgHirQ55Y8/edit?usp=sharing

**Comment by PLAYLEX** [comment]
Same Problem here: https://github.com/xJon/The-1.12.2-Pack/issues/535

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with OpenBlocks, caused by Optifine. You can subscribe to the Optifine issue here: https://github.com/sp614x/optifine/issues/2267
