### ISSUE TITLE
JEI lags when searching mods with @ prefix

### ISSUE THREAD

**Issue by Kangy1103** [mezz/JustEnoughItems#2092]
Hi, when using the @ prefix to search mods it's causes lag until you clear the search or close you're inventory

Modpack: All The Mods 5
JEI Version: 6.0.3.15
Minecraft Versions 1.15.2

If you need any more information please let me know

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately i'm not able to reproduce this issue, could you show some screenshots with your FPS visible (F3) with a blank search and with the `@` search'?

**Comment by Kangy1103** [comment]
@mezz sorry for the delay in response. 

I'm not not sure it's an issue with JEI as after a bit more testing it only seems to happen when I type @ silent. (without the space of course but I added the space as it tagged another user)

I think something in Silents mods is causing the lag when shown in JEI.

it also happens when scrolling through JEI and I get to Silents sections

**Comment by mezz** [comment]
Ah okay that makes sense!
JEI displays a ton of items, and in this case it's showing a lot of slow items at once, which adds up.
You should report this to Silent's mods and link back here for discussion.
