### ISSUE TITLE
Forced to add ftb gui lib to the workspace of mods that depend on jei

### ISSUE THREAD

**Issue by vincentmetevelis** [mezz/JustEnoughItems#2095]
Since the #2077 commit, you as a mod developer are required to add the FTB GUI lib as a dependency, instead of it being optional. Big chance this is because of the 'compile' in the 'build.gradle' instead of 'compileOnly'. Anyway, this shouldn't happen, because the FTB GUI lib is an optional mod for JEI, and JEI doesn't depend on it. (similar to how JEI plugins work towards the JEI API)

**Comment by LatvianModder** [comment]
Hm I didn't know this was even done lol. I would have recommended for it to be its own mod like JEI Config instead of being part of it, but it's fine by me either way. Is it just Gradle being dumb?

**Comment by mezz** [comment]
Thanks for the report!
Yeah this is just some gradle misconfiguration on JEI's side. I'll fix this up when I get a chance to.

**Comment by vincentmetevelis** [comment]
Thanks :D

**Comment by mezz** [comment]
This has been fixed in the latest version.
