### ISSUE TITLE
stop telling us to vote, dammit

### ISSUE THREAD

**Issue by steeleater** [mezz/JustEnoughItems#2096]
2/3rds of your userbase isn't even old enough to vote anyway and it's really fucking annoying to open up the menu and get told to vote every single time.
i wonder how much biden paid you to put his name on a fucking minecraft mod

**Comment by mezz** [comment]
Thanks for the report!
The screen will only show once. I am not sponsored by Joe Biden.

This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2093, let's keep discussion there.
