### ISSUE TITLE
[Bug] Can't display wildcard meta

### ISSUE THREAD

**Issue by SettingDust** [mezz/JustEnoughItems#2098]
jei_1.12.2-4.16.1.302
CraftTweaker2-1.12-4.1.20.589

CraftTweaker
```
val runeStone = <ebwizardry:runestone:*>;
val runeStonePedestal = <ebwizardry:runestone_pedestal:*>;

recipes.addShaped("Waystone", <waystones:waystone>, 
[
    [null,              runeStone,              null],
    [runeStone,         <waystones:warp_stone>, runeStone],
    [runeStonePedestal, runeStonePedestal,      runeStonePedestal],
]);
```

JEI
![图片](https://user-images.githubusercontent.com/19922286/93997766-5636b800-fdc6-11ea-8daf-200a875e8510.png)

Minecraft
![图片](https://user-images.githubusercontent.com/19922286/93997815-6189e380-fdc6-11ea-8565-35aeba9498ab.png)
![图片](https://user-images.githubusercontent.com/19922286/93997831-664e9780-fdc6-11ea-92c3-cf119a1079b0.png)

**Comment by mezz** [comment]
Thanks for the report!
I think this may be an issue on CraftTweaker's side, can you report to them and link back here?

**Comment by SettingDust** [comment]
> 
> 
> Thanks for the report!
> I think this may be an issue on CraftTweaker's side, can you report to them and link back here?

Of course. ~~I'm submitting~~. Done
