### ISSUE TITLE
Cannot connect server

### ISSUE THREAD

**Issue by valveo** [mezz/JustEnoughItems#210]
Thank you for reporting!

If there is an issue:
- It may already be fixed, please try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files).
- If JEI crashed, please paste the crash log to [gist](https://gist.github.com/) and link it in this issue.

Somehow I cant connect server. Tried disable multiple mods, but always same error.
https://gist.github.com/valveo/cb43ead2c11e9ac3be88
Im not sure if this is because jei

**Comment by mezz** [comment]
Thanks for the report!
JEI is logging some errors about broken ItemStacks it found, but it's nothing terrible and I don't think it's related to your issue. 
Please post a link to your server log, it should have the information required to figure out what's happening.

**Comment by valveo** [comment]
Here is server log:
https://gist.github.com/valveo/fedb900228d62b4f6375

Netty timeout, but problem isnt network, because I have second mc server in same location and it works just fine.

**Comment by valveo** [comment]
I just tested to remove jei and client connected to server just fine.
Something is blocking connection if it is installed.

**Comment by valveo** [comment]
Lots of debugging and found problem. I was buildcraft-compat that caused issue.

**Comment by mezz** [comment]
Thanks for following up. Is there anything to report to buildcraft-compat, or did you just need to update?
