### ISSUE TITLE
Item grouping and order

### ISSUE THREAD

**Issue by Rithenar** [mezz/JustEnoughItems#2100]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

In previous versions of JEI when I do a search items would show up grouped and sorted by tier. For example, if I search for @Powah I would get the items grouped by similar and then sorted by tier. This is not the case any longer. JEI shows all items from a mod as you can see in the pic
![image](https://user-images.githubusercontent.com/9939332/94089334-88511580-fdd8-11ea-8d1c-2f7d58e83aea.png)

This is not exclusive to Powah. All mods are showing the same way. See Bee Resourceful for example.
![image](https://user-images.githubusercontent.com/9939332/94089406-bc2c3b00-fdd8-11ea-8525-ad7da66ce6a8.png)

I noticed this on latest 1.16 version. I am using 1.16.3-7.3.2.33

Can this be changed in the config or is it a code issue?

**Comment by mezz** [comment]
Thanks for the report!
I think JEI is supposed to be ordered sort of like the creative menu, can you see if the issue is in the creative menu too?

**Comment by Rithenar** [comment]
Actually I was told to remove the Registries entry under fml in the level.dat and that solved the problem. Not sure what or how that happened but it worked :)

**Comment by IMarvinTPA** [comment]
I'm working on a massive Inventory Tweaks Tree for 1.16 and have a Pull Request https://github.com/mezz/JustEnoughItems/pull/2380 to read such a file.  Would that be cool?
