### ISSUE TITLE
Cannot access JEI on server 1.16.3

### ISSUE THREAD

**Issue by ClaudiusMinimus** [mezz/JustEnoughItems#2101]
I'm working on a 1.16.3 pack and when I first launch Minecraft and log onto our test server JEI does not appear when I open my inventory GUI. If I exit and then open a SP ("single player") world, then JEI appears as normal. After I exit the SP world and log onto the server JEI now appears. This happens for each session I launch Minecraft. I have been able to repeat this process multiple times and our other testers have also experienced this issue and workaround.

I have included the unpublished pack at the bottom of this post.

Minecraft: 1.16.3
Forge: 34.0.9
jei-1.16.3-7.3.2.34.jar

[latest.log](https://paste.ee/p/Qewmx)

[Paradise in Chaos-0.4.0.zip](https://github.com/mezz/JustEnoughItems/files/5275917/Paradise.in.Chaos-0.4.0.zip)

**Comment by Letoric** [comment]
I also experience this issue, same version of JEI and Minecraft, but forge 34.1.0
I'm using a hybrid version of ATM 1.16.3 that is not on Twitch, and they do NOT experience the issue with JEI 7.3.2.33

**Comment by playpolticalgameswinpolticalprizes** [comment]
Could be cause mezz added IP tracking he added to push poltitical canadates on people.
It now sends your IP address to a third party server and tracks where you live if it isn't getting it likely isn't 

That is only thing that has changed with JEI since aug.

**Comment by ClaudiusMinimus** [comment]
I'm in the US, but the server I use is in Germany, so even  JEI 7.3.2.25 or 7.3.2.23 did not work. The only workaround I can find is to do as I explained above by opening a SP world > close > open MP world.

**Comment by ClaudiusMinimus** [comment]
I just installed the latest version 7.3.2.35 on client and server, and JEI still does not appear unless I log into SP first, then MP.

[Client latest.log](https://paste.ee/p/btAaf)
[Server latest.log](https://github.com/mezz/JustEnoughItems/files/5287521/latest.log)

**Comment by mezz** [comment]
Thanks for the report!
I'm looking into this now.
JEI depends on a specific Forge event to start, I'm guessing it is not being fired when you connect to the server.

**Comment by mezz** [comment]
I have tested this with just JEI (no other mods) and it is working fine when I connect to a server. 
Can you try removing mods to narrow down which mod is conflicting with JEI? I can help work out the bug with them once you've found it.

**Comment by ClaudiusMinimus** [comment]
Will do

**Comment by ClaudiusMinimus** [comment]
I should let you know I have chronic health issues and cannot guarantee how soon I can narrow down which mod is conflicting with JEI. However, feel free to do it if you are unable to wait for me. Here is the install for the pack I'm working on: [Paradise in Chaos-0.4.0.zip](https://github.com/mezz/JustEnoughItems/files/5275917/Paradise.in.Chaos-0.4.0.zip) I don't have a script for installing a server, but you should be able to figure out which client mods need removing for a server. Again, the server I use is in Germany, but I'm in the US - not sure if that makes a difference.

**Comment by mezz** [comment]
No rush, it can take a while to look into issues like this. If others have this issue they may be able to help out too.
This is most likely unrelated to your country or the country your server is in, I am pretty sure it’s a mod conflict.

**Comment by Prophious** [comment]
i'm gonna try to see what mods may be causing this, tho i'm gonna do 1.16.1... it is possible that it may be the same mod in later versions as well


[trio (1)-1.0.0.zip](https://github.com/mezz/JustEnoughItems/files/5322873/trio.1.-1.0.0.zip)

the pack i play with, with over 140 mods 
just for reference


update: after several hours of removing one mod at a time i have found the minimum mods where jei does not work except when relogging once for 1.16.3
[test test-1.0.0.zip](https://github.com/mezz/JustEnoughItems/files/5323134/test.test-1.0.0.zip)

Apotheosis and Forbidden & Arcanus mods(with library) seem to have conflict showing jei

hope this helps

however in 1.16.1 i did not have the non-jei mods in that pack there, and jei would not load until 2-3 relogs
[dffdg-1.0.0.zip](https://github.com/mezz/JustEnoughItems/files/5323137/dffdg-1.0.0.zip)
this pack might not be able to get every mod(thats what twitch client export was telling me)

**Comment by Darkfiend009** [comment]
Just to add to this, i am also playing on 1.16.3 and didn't experience this issue at all yesterday.

Today, however, i added the following mods:

Embellishcraft
Statues
Pandoras Creatures
Macaw's Doors
Silent's Gems/Gear
Mining Gadgets

I now run into the issue of not having JEI on the server unless i connect to a single player world first.

**Comment by JJayzX** [comment]
Mine just started doing this and I had just added Silent's Gear with Silent's Lib, so I removed it and JEI is back.

**Comment by Prophious** [comment]
can confirm that with silent gear/lib along with just jei (jei-1.16.3-7.5.0.42) does not load jei first time, same thing i can relog in to server with just the 3 mods and it will work on second log in

also can confirm that even with the newer jei while having both Apotheosis and Forbidden & Arcanus mods JEi does not load on first log in, and separately Jei loads fine, will post in both githubs about it

**Comment by dkbhn** [comment]
Hi

I'm helping ClaudiusMinimus on his modpack.

I've been spending the last many hours trying to find out what's causing the problem. And here's what I've found out:

![mods](https://user-images.githubusercontent.com/48546523/97341256-195a5700-1885-11eb-986b-3a852bfb4f74.png)

With only the above mods installed, the JEI doesn't show when entering a server.
If either forbidden-arcanus OR apothesis is removed, there JEI works fine.

Hope it helps

**Comment by ClaudiusMinimus** [comment]
In addition to what dkbhn posted above, he also found with the addition of [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench/files/3069047) the issue goes away.

**Comment by KKotik** [comment]
I found that issue with Random Patches, using latest versions of mod itself, forge and jei as well.

**Comment by danielmartin0** [comment]
> In addition to what dkbhn posted above, he also found with the addition of [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench/files/3069047) the issue goes away.

Adding this mod didn't solve the issue for me on 1.15.2.

**Comment by zachsai** [comment]
I have the same issue
Silent lib with apotheosis causes the issue that removed the jei from showing.
I am attempting the fastworkbench method that ClaudiusMinimus recommended
My log: https://gist.github.com/celsiusqc/8185d87c71edbe142e98fb9439e71586

Edit1- fastworkbench fixed the problem
