### ISSUE TITLE
Make recipe auto fill ingredients use recipe context instead of ingredient context

### ISSUE THREAD

**Issue by pupnewfster** [mezz/JustEnoughItems#2102]
This is a slight follow up of #2073 in that even with the new context system it is not quite enough to implement that type of thing when it comes to energy. For energy cubes in Mekanism for the filling crafting grid I don't care about energy, which sort of works when I only do it with UidContext.Ingredient, except that because the components of the recipe are also in the ingredient context, instead of in the recipe context like the output is, the components for shift clicking in care about how much energy is in them. As [discussed on discord](https://discordapp.com/channels/358816755646332941/358816844477497346/756197380369547396) it would make sense that they are either in the Recipe context in this case as well.

JEI Version: 7.3.2.36

**Comment by mezz** [comment]
Thanks for the suggestion!
This has been implemented in JEI 7.4.0
