### ISSUE TITLE
Add flag to disable colour names for items

### ISSUE THREAD

**Issue by axieum** [mezz/JustEnoughItems#2103]
Extracting the colours for ingredients appears to use a significant amount of memory and processing time. I would like to suggest allowing players with low-end computers to turn this feature off.

I had a look under configuration, but couldn't find much. I'm happy to close this issue if it's already configurable.

https://github.com/mezz/JustEnoughItems/blob/d0af18c4d59de6e38037899c375270d9c219cf3a/src/main/java/mezz/jei/ingredients/IngredientInformation.java#L55-L59

![image](https://user-images.githubusercontent.com/7577851/94566508-c2755800-02ad-11eb-8ed6-2d271bc0c190.png)

In the scheme of things, `660MiB - 2.07GiB` doesn't seem much when compared to the `15.83GiB`, but I think it's not worth ignoring if some players could free up some of that memory and computation time.

**Comment by mezz** [comment]
Thanks for the report!
This can be disabled if you disable color search entirely in the JEI config file.
```
	#Search mode for Colors (prefix: ^)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ColorSearchMode = "DISABLED"
```

I have gone ahead and disabled this by default in the config, so that it is opt-in like it was in 1.12.

**Comment by axieum** [comment]
Love your work 👌
