### ISSUE TITLE
Change Biden support button to NAMBLA ones the election is over

### ISSUE THREAD

**Issue by mc-asukafag** [mezz/JustEnoughItems#2107]
I, a fellow moduser, am very pleased about your political activism against racism and in favour of tolerance and inclusion.
Voicing your support for Biden and asking players of a game that is PEGI 7 to donate to his campaign is a very important step towards more LGBTQP acceptance.
Biden, who loves children sexually, would be the first LGBTQP president of the United States and would be a huge step forward. But what happens after the election? We can't just sleep, we have to keep the pressure alive.
Therefore i suggest to keep the button, but to change it to a support link for NAMBLA the North American Man Boy Love Association.
Maybe, in the near future, we will finally decriminalize p3d0philia and ageism will be a thing of the past.
Age is just a number, it is just a social construct like gender is. I am glad that you agree with me here and correctly realize that a 7yo boy who plays minecraft is intelligent enough to be exposed to political propaganda and identity politics in his game.

**Comment by ricksouth** [comment]
Yes America, re-elect a president which has told over 20000 public lies to date. Europe supports your decision.
And yes, the modding scene is only played by 7 year old boys, such as yourself I suppose.

**Comment by mc-asukafag** [comment]
Why re-elect? Biden wasn't president yet, just vice president under the Obama Administration, the Administration with the first trans First Lady Michael LaVaughn Robinson, but also the Administration under which BLM got founded and first rioted.
And Biden isn't lying, he just forgets things. Like when he was confronted with his corruption in the Ukraine and said that he doesn't even know the Ukraine Gas Exec, but then a picture emerged of them playing golf together — he legitimately just forgot it. That's not a lie, just dementia.
But we shouldn't judge a  president based on mental health or skill, we should judge them based on identity, Biden, as LGBTQP member and known pedosexual, would be good for the LGBTQP community, and that is what really matters.

And of course we have to care a lot about what other countries, who know totally nothing about US issues and just hear about it filtered through news, want us to vote. Especially Europe, with the EU that is currently busy suing each other over who should take refugees. We should ask China and Russia about what we should vote too. China is just as democratic as the EU is, i am sure their opinion matters.

Anyway, that is OffTopic right now.
This issue is about how to continue after the election, and i am strongly in favour to keep the button there and to keep using it to fight against Ageism.
Age is a social constuct.

**Comment by ricksouth** [comment]
Oh the damage conservative media can do to young minds..

**Comment by mc-asukafag** [comment]
I agree, conservative media like CNN, MSNBC and NewYorkTimes, who all reported about the Ukraine corruption of Biden, painted it as if Biden is lying instead of realizing that it's dementia.
The well known conservative media bias is a big issue... the more important it is that we use the platform we have, a PEGI 7 game that children play, to spread our message against racism and ageism.

**Comment by ricksouth** [comment]
For anyone else reading this mess, get your information from multiple sources. Don't be a gear in the system by making your voice a shallow echo. The world is already small, don't make your world even smaller.

**Comment by mc-asukafag** [comment]
Why would you need multiple sources, if you could just vote what some mod of a PEGI 7 game tells you to vote?

Here are your multiple sources
https://www.youtube.com/watch?v=6MmB7_e7ftY
also remember not to read leaked sources like Wikileaks
https://www.youtube.com/watch?v=eQllunHssEk

**Comment by Orbulon** [comment]
@ricksouth, I'm going to have to disagree with you there. Conservative propaganda outlets like FoxNews, CNN, MSNBC etc are poisoning our youth. All I can recommend are more trustworthy outlets such as http://mediamatters.org

**Comment by ricksouth** [comment]
My vote is for one united Earth. Another government on Mars and finally realise we're all humans on the same planet here. The way the Trump kid's house is governing with total disregard of nature and our fragile ecosystem, is frankly embarrassing. Don't we all want clean water to drink and safe air to breath? Stop mining coal, use renewable energy sources and recycle the heaps of trash we already have. If any government is against these basic principles, I salute them adieu.

**Comment by mc-asukafag** [comment]
@ricksouth a few years ago the EU decided to make a certain percentage of biofuel mixed into diesel mandatory.
This lead to crop prices exploding and it was expected to cause more deforestation all over the planet to produce biofuel and more palm oil. The EU did later weaken the regulation, but still kept it, with all it's negative consequences.
People who actually cared about the environment demanded that they at least implement a ban on palm oil usage in biofuel. It took them a decade to formulate such a ban, and in fact, it's still not in place.
With that one regulation, that the EU claimed is in favour of the environment, they became the largest cause for world wide deforestation. Palm oil usage exploded.

They didn't care about the environment. The politicians could virtue signal about how they care about nature, because bio sounds good, the car manufactures and the industry welcomed it, because it gave consumers a reason to buy newer cars, the agricultural industry welcomed it, because their products are now more worthy. A win-win situation, the only losers were the consumers and the nature.
Meanwhile Germany allowed VW to cheat environmental controls and to throw more NOX poison into the world. They didn't punish them, the opposite, they did financially help them when the USA punished them.
Of course lets not forget how Germany covers their needs for electricity with coal.

I don't know a single compareable crime against nature from the USA during the Trump administration.
You are in the Netherlands, part of the EU, what are YOU doing to stop your rulers from governing with total disregard of nature and our fragile ecosystem?

**Comment by mezz** [comment]
wtf no
