### ISSUE TITLE
Keep your political bullshit out of Minecraft asshole.

### ISSUE THREAD

**Issue by Wodong77** [mezz/JustEnoughItems#2111]
I play Minecraft to get away form the real world bullshit.  You're a real champ forcing that shit on everyone.

**Comment by Sunconure11** [comment]
![derpfish](https://user-images.githubusercontent.com/5614902/95477504-6a49f000-0956-11eb-992e-a58e30c444af.png)

**Comment by CammiePone** [comment]
Some of us can't have that luxury. Get off your privileged high horse and deal with a bit of text.

**Comment by quat1024** [comment]
do you fart
