### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pixelmon (pixelmon) Exit Code: -1

### ISSUE THREAD

**Issue by KiraClean** [mezz/JustEnoughItems#2112]
i have loaded up many mods but it seems if i go past 62 or have certain mods it fails

**Comment by KiraClean** [comment]
also certain mods wont work,like pixelmon

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
