### ISSUE TITLE
[1.16.3] Throwing items out of inventory causes crash

### ISSUE THREAD

**Issue by froyo4u** [mezz/JustEnoughItems#2114]
Hello, if I try to throw something out of my inventory using CTRL+Q or just dragging it out my game crashes with the Container Click error.

Steps to reproduce:

1. Have an item in your inventory. 

2. Go into survival(if you aren't already).

3. Drag the item out of your inventory or CTRL+Q it out of your inventory.

4. See a crash.

Crash Log:

https://gist.github.com/MeowMC/3ebdd49c9a21acbd03f6c34a3f2f49e1

**Comment by froyo4u** [comment]
Even with the newer version, in that log I was using the older one just to see if it was caused by an update, but it happens on both.

**Comment by Ommina** [comment]
This appears, to me, to be related to "Enderite Mod", not JEI.

**Comment by froyo4u** [comment]
Interesting. I will let the modpack owner know.
