### ISSUE TITLE
No 1.16.1 version - Please add/or create 1

### ISSUE THREAD

**Issue by CosmicjLightning** [mezz/JustEnoughItems#2117]
can't use it with quark as they haven't updated to 1.16.3 as they say it's too hard to right now so I would really like an 1.16.1 version of JEI. I even tried launching with the 1.16.3 version and it weirdly stated jei was using an older version of Minecraft when it's actually the newest one

**Comment by Ommina** [comment]
https://www.curseforge.com/minecraft/mc-mods/jei/files/3028697

**Comment by CosmicjLightning** [comment]
thank you. Guess I'm blind or something. I kept looking for it earlier & just couldn't find it.
