### ISSUE TITLE
JEI 1.16.1 Crashes

### ISSUE THREAD

**Issue by Saltixir** [mezz/JustEnoughItems#2118]
I really wish for you to update the 1.16.1 alpha version of the mod,because theres a crash caused if you press h,l,u and maybe some others which is very frustrating to play with and also jei doesnt load the first time i join on a server but thats minor compared to the crash bug.If i press L,h,u the game closes and says Saving World,error code -1 .

**Comment by Ommina** [comment]
Please provide the crash log.

My suspicion is that a particular item is not rendering (which would -- probably -- fall to the mod that adds the item), but with no logs, it's all just guesswork.

**Comment by Saltixir** [comment]
Seems there is no need, i deleted the jei config file and somehow that fixed it but still thanks for the help.
