### ISSUE TITLE
[1.16.3] Bookmark Button Zoomed Out

### ISSUE THREAD

**Issue by KhanhPham05** [mezz/JustEnoughItems#2119]
### _**Issue Description**_
The **<** and the **>** button in the bookmark side of the JEI become over-zoom(too big)

This cause from Valkyreiofnight VIP-server
_[Server Side]_

### _**Image:**_
![2020-10-15_18 23 17](https://user-images.githubusercontent.com/68932626/96124378-a9abaa00-0f1d-11eb-9edc-035e64899dbc.png)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.
