### ISSUE TITLE
Please add mass light level checking, I know this is in some other mods and is an NEI feature but none of the other mods that have this are in 1.16 and it is just convenient for everyone who uses this mod

### ISSUE THREAD

**Issue by Herocrossfire** [mezz/JustEnoughItems#2121]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Ommina** [comment]
https://www.curseforge.com/minecraft/mc-mods/light-overlay

**Comment by mezz** [comment]
From the issue template,

Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

Light Overlay and others work great.

**Comment by Herocrossfire** [comment]
not in 1.16...

**Comment by mezz** [comment]
I’m sure something will be updated, but in any case this feature doesn’t really belong in JEI.

**Comment by Ommina** [comment]
The Light-Level overlay I linked above IS for 1.16, with versions for 1.16.1, 1.16.2, and 1.16.3.  And Fabric (with snapshots!) too, if that floats your particular boat.

**Comment by Herocrossfire** [comment]
Oh Thank You, I'm sorry for the trouble.
