### ISSUE TITLE
Deleting things with JEI

### ISSUE THREAD

**Issue by ryangood1** [mezz/JustEnoughItems#2123]
When you delete an item by dropping it onto the JEI menu, you cannot immediately delete another. When you click the next item, nothing happens so you have to click it again to select and then delete it. Oh, and the version number shown in the in-game mods menu says 7.6.0.43, even though I have 0.49 installed.

tl;dr - the next item you click after deleting an item needs to be double-clicked to be selected.

Version: 1.16.3-7.6.0.49, but I don't think the version really matters as it has been happening for a while.
Thanks.

**Comment by mezz** [comment]
Thanks for the report!
Closing this as a duplicate of https://github.com/mezz/JustEnoughItems/issues/2108
