### ISSUE TITLE
1.15.2 Ctrl+click "Enable cheat mode" doesn't write preference to config?

### ISSUE THREAD

**Issue by GormAuslander** [mezz/JustEnoughItems#2124]
I can't tell if this is an issue with my launcher or the mod not writing to a config, because obviously if I remove the mod the option goes away, but the mod no longer remembers my preference for whether to have it enabled and has to be reactivated every game launch. It's obviously just one click, but it's a little quality option we used to have in 1.12 that I sorely miss

**Comment by darthvader45** [comment]
I've had a very similar issue in 1.16, as for some reason it turns off as soon as I exit the game and I have to turn it back on when I relaunch.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in later versions of JEI.

**Comment by GormAuslander** [comment]
So no fix planned for 1.15?

**Comment by mezz** [comment]
Sorry no, 1.15 is not a well-supported version. 
1.12, 1.16, and 1.18 have more support.
