### ISSUE TITLE
Can't use Hide mode to Hide items from list

### ISSUE THREAD

**Issue by Reidlos65** [mezz/JustEnoughItems#2125]
MC version 1.15.2
JEI version: jei-1.15.2-6.0.3.15

I cant get any items to hide in the JEI menu.  I toggle the Hide mode with the shortcut , I click the items, they turn red.  I then close the inventory after turn off the hide mode and they are still there.  I read in the config there was a mode that might allow things to be hidden (forgot what its called) but there is no config for 1.15.2

There is a set of items for a mod that lag massively when shown and they are not needed as they are all just variants of the same thing.  Not sure what Hide mode does, maybe it doesnt do what I think?

**Comment by Entoarox** [comment]
From my own experience, you need to exit & re-enter the world for the changes to take effect, using the `/reload` command may also work, but I have not tried that yet. (Thought of it just as I was writing this reply, will test it and edit to say if it works)

Edit: The /reload command does indeed work!

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the latest versions of JEI for 1.16, 1.17 and 1.18.
You can bind a hotkey to toggle the "hide items" mode on and off in the Minecraft controls, and the hidden items will stay hidden properly.
