### ISSUE TITLE
[1.16.3] Scaling Buttons issue

### ISSUE THREAD

**Issue by YOYOK9** [mezz/JustEnoughItems#2129]
I've noticed that the arrow buttons don't scale properly from different interfaces, ie: Inventory, storage blocks, machines from mods. I've only noticed this in the 1.16.3 X additions, Don't recall seeing them this big in 1.16.1 of my pack.

MC: 1.16.3
Forge: 34.1.23
JEI: jei-1.16.3-7.6.0.49
Other JEI addons installed:
jeiintegration_1.16.3-6.0.0.8

I have taken a few screen shots showing the changes:
GUI scale in Auto:
Inventory: https://puu.sh/GFjq9/e0b0ebd1b1.png
AE2: https://puu.sh/GFjqt/96183e400d.png
Mekanism Smelter: https://puu.sh/GFjqX/896c0fbfb4.png
Digi Miner: https://puu.sh/GFjrG/74e264749c.png

I play in GUI 3 most of the time and noticed it almost looks bigger as well, Digi miner: 
https://puu.sh/GFjtR/842378563d.png

Edit:
I do not have optifine installed.

**Comment by scottctd** [comment]
I have exactly the same issue.
![image](https://user-images.githubusercontent.com/35100768/97007395-eb6acf00-1573-11eb-8d39-b347c0bef2da.png)
For version jei-1.16.3-7.6.0.49.jar

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.
