### ISSUE TITLE
crash 1.9

### ISSUE THREAD

**Issue by loordgek** [mezz/JustEnoughItems#213]
https://paste.ee/p/ynM8e
when i go to the 2nd page

**Comment by loordgek** [comment]
more info it is crashing w/ psi http://psi.vazkii.us/changelog.php#beta-27

**Comment by Vazkii** [comment]
It takes an incredibly thick skull to find a crash with a mod, go to the point of recognising that's the mod it's crashing with, having an old version of that mod and linking the changelog for the latest version and not connecting the dots.

**Comment by loordgek** [comment]
vaskii was running 24 now 26 and fixed OOPS

**Comment by mezz** [comment]
Thanks for the followup! Glad it works.
