### ISSUE TITLE
Crash clicking Singleplayer at Main Menu - jei_1.12.2-4.14.3.242

### ISSUE THREAD

**Issue by AefRal** [mezz/JustEnoughItems#2137]
Was playing Forever Stranded: Lost Souls (Version: 1.0.3.15-B3-RC1) by GWSheridan.
Noticed it didn't have the JEI bookmarks.
The pack was running jei_1.12.2-4.10.0.199. (Perfectly fine and playable.)
The newest JEI versions would require that I change the Forge version, which would likely cause errors in a bunch of other mods.
Took a bit, but after using search function in the changelog, I realized that bookmarks seemed to be introduced in 
version 4.14.0 of JEI.
So I switched it out for that one. It seems to load perfectly fine. I get to the main menu, click single player, then it crashes.
Have also tried a few other 4.14.* with same result.

[crash-2020-10-25_21.45.11-client.txt](https://github.com/mezz/JustEnoughItems/files/5436699/crash-2020-10-25_21.45.11-client.txt)

I just want bookmarks, they're so useful, but I don't want to go and change the entire pack full of mods to get them (203 mods).

**Comment by Ommina** [comment]
This appears to be JEI Integration looking for something that isn't there.

Try updating that.  No promises that this will or will not cause a cascade of errors requiring updates to other mods afterward.  That's the joy of updating dependencies.

**Comment by AefRal** [comment]
Thanks I'll try that.
