### ISSUE TITLE
Help I cant find the Jei on 1.15.2

### ISSUE THREAD

**Issue by WaitWhyAmIHere** [mezz/JustEnoughItems#2139]
Well last time I saw it then a couple days later its gone, it was after i installed some mods but last time when i did that it was doing fine.

**Comment by Eric-01** [comment]
What about pressing Ctrl + O if you already have JEI installed, or using the following link to download it: https://www.curseforge.com/minecraft/mc-mods/jei/files/all?filter-game-version=1738749986%3A68722 ?
