### ISSUE TITLE
Simply not working properly

### ISSUE THREAD

**Issue by ds3p** [mezz/JustEnoughItems#2140]
Well, i have been using the mod normally for 2 days ( also used to use it with 1.7.10 version, now on 1.12.2) and the mod suddendly stopped working properly.when i press R It is just showing Alchemy stand, anvil and enchantment table uses and i cant see the important stuff like furnace or workbench. i am starting to get really mad and i just want a solution plz help!!!!

**Comment by ds3p** [comment]
👎

**Comment by ds3p** [comment]
ok so is no one goin to help me :/

**Comment by tanyan-tanyan** [comment]
There is very little information to go off, what version of the mod are you using? Can you show some screenshots?
