### ISSUE TITLE
Various minor accessibility improvements [Feature request]

### ISSUE THREAD

**Issue by Profilename1** [mezz/JustEnoughItems#2142]
I'm a modpack maker and I was talking with someone on my Discord that mentioned that they had trouble using Minecraft's crafting system due to a disability of theirs. After a short discussion we had a few ideas that could be implemented in JEI's framework that would improve accessibility. The biggest one would be the ability to set JEI's gui scaling independently of Minecraft's so that the items could be made much larger than normal and easier to see. Another was to add the ability to map the function the plus sign currently has (popping items into the grid) to a hotkey in addition to another hotkey for taking the finished item from the crafting grid and into the player inventory.

**Comment by mezz** [comment]
Thanks for the suggestions.
I am cleaning up the backlog, and I think this request can be covered by these two other suggestions so I will close this one:
* https://github.com/mezz/JustEnoughItems/issues/2319
* https://github.com/mezz/JustEnoughItems/issues/3349
