### ISSUE TITLE
JEI disappearing

### ISSUE THREAD

**Issue by wojhd007** [mezz/JustEnoughItems#2145]
I have a bug in which JEI after installing to the online server does not appear the first time I enter the game. Only after the 2nd or 3rd entry does it appear. When I load the single world everything is fine.
"Error Executing Task on Client" appears in the console.

Game version: 1.16.1
Forge version: 32.0.108
JEI version: jei-1.16.1-7.0.1.10

**Comment by ro371** [comment]
It´s the same for me, i have to first enter singleplayer and then the server for it to work

**Comment by Ommina** [comment]
See, also, #2101
