### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by Yikage** [mezz/JustEnoughItems#2147]
So, the newest 1.16.4 version is for 1.16.3, said that the version need to be 34.0.3 or above and below 35.0.0, but there is no version of 1.16.4 are under 35.0.0

**Comment by Fatheed7** [comment]
In lieu of a proper fix, I've managed to fix this by doing the following:

- Open the .jar file in Winrar
- Open META-INF folder
- Open mods.toml with a text editor
- Near the bottom (line 54) - Update versionRange="[34.0.3,35.0.0)" #mandatory to versionRange="[35.0.3,36.0.0)" #mandatory

**Comment by Raycoms** [comment]
Yes, I just looked into this, and the build used the cached old values for the mods.toml instead of using the new values.

**Comment by Yikage** [comment]
Thanks
