### ISSUE TITLE
1.16.1

### ISSUE THREAD

**Issue by TOWIIIZ** [mezz/JustEnoughItems#2150]
Hi, I would just really appreciate using this on 1.16.1
I had to use 1.16.1 as it was the easiest way to get as many mods for 1.16. But sadly this one does not have a .1 version :(

**Comment by Ommina** [comment]
https://www.curseforge.com/minecraft/mc-mods/jei/files/3028697

**Comment by TOWIIIZ** [comment]
Thank you!!
