### ISSUE TITLE
[1.16.3, 1.16.4] Add option for resorting items for cases when sorting order is broken]

### ISSUE THREAD

**Issue by llssc** [mezz/JustEnoughItems#2156]
![image](https://user-images.githubusercontent.com/69404048/98764547-e473f700-2390-11eb-9842-498c04c31645.png)
![image](https://user-images.githubusercontent.com/69404048/98764586-f9508a80-2390-11eb-8ab9-068b18ce8208.png)
(obviously, these two mods are not the only mods I have installed) 

Item sorting order gets broken completely randomly and unpredictably. On one world, the items are sorted fine, but gets completely shuffled (differently per world) other times.

Regardless, it completely throws me off as I have no idea where the item might be.
The items are sorted according to mods (so that code is working fine), but other codes may need inspection.

Add an option to attempt resorting of those items, or please fix this issue.

One thing to note is that the items are also not sorted on creative menu, and seems to be following that chaos when it decides to get unsorted. 
However, as stated, the items are sorted properly on some worlds even though the creative menu is in complete chaos.

**Comment by IMarvinTPA** [comment]
I found that /reload does the trick too.
