### ISSUE TITLE
1.16.3 and 1.16.4 JEI not showing

### ISSUE THREAD

**Issue by redo6565** [mezz/JustEnoughItems#2159]
jei is installed but is not showing up is single player world. even checked to see if it was hidden and still not showing

**Comment by ticticboooom** [comment]
i can second this. it has loaded into forge however there is no jei gui shown, nor can i summon the recipe screen on `r` or `u` keys pressed.

**Comment by djwild** [comment]
same here, usually it only append on the first time i join a server, logging off and log back in fix it.

Forge 35.0.17
JEI 7.6.0.58

**Comment by MadPandaLord** [comment]
Similar issue JEI doesn't appear when joining a server when the pack is first loaded up i've found that joining a singleplayer world and then joining the server fixes it 
**Edit** 
leaving and rejoining the server seems to also fix this issue but JEI appears to work first try when joining a singleplayer world
Versions
Minecraft 1.16.3
Forge 34.1.42
JEI 1.16.3-7.6.0.51 (BETA) 

not sure if it matters but these were the most recent versions available on the Twitch Launcher at the time of writing this comment 15/11/2020

let me know if you'd prefer this to be commited as it's own issue

**Comment by IchigoGames** [comment]
same thing happening on my modpack

**Comment by Ja-spec** [comment]
Same as all of these, the leaving and rejoining without a relog does work though

**Comment by CelestialPhoenix** [comment]
Just randomly encountered this issue; it was working fine, and I restart the pack and its not showing. The show/hide button does not show JEI either, and the keybinding menu does not show a button clash.
Issue persists when creating a new world, and when re-entering my current world.
Not sure if its related but this happened immediately following a password reset from Mojang.
JEI 7.6.0.62
Forge 35.1.4 (_recommended version on MultiMC_)

_[also present; 
ContentTweaker 1.0.0.develop.9
CraftTweaker 7.0.0.27
Create 0.3
FTB GUI Library 1604.1.1.26
ImmersiveEngineering 4.1.2-129
OpenLoader 8.0.1]_

----edit-----
Found the problem, and its sitting in the chair.
I've added a CT recipe using <tag:forge:nuggets/platinum> when no mod present adds platinum nuggets.
(_the lack of platinum did not throw any immediately apparent error on /reload, JEI not showing was the first apparent symptom._)

**Comment by Rmdhn1** [comment]
It works on creative but not survival

**Comment by radj307** [comment]
Same thing happens to myself and everyone else who uses my server. (Debian 10 on a VM)

MC Version: 1.16.5
Modpack: Brass v0.4.0a (modlist: https://www.modpackindex.com/modpack/22520/brass)

Simply relogging into the server fixes it for everyone.

**Comment by heav-4** [comment]
i too am having this issue on a singleplayer world. i can't relog because an unrelated mod crashes the game.

**Comment by radj307** [comment]
AFAIK hasn't been fixed so shouldn't be stale

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
