### ISSUE TITLE
Remove Pagination for bookmarks if only a single page is present

### ISSUE THREAD

**Issue by Darkere** [mezz/JustEnoughItems#2161]
I would argue that 99% of people will never have more than a single page of bookmarks. 

Combined with the fact that the left side of the GUI tends to be where most mods have moved their GUI elements (most likely due to JEI in the first place), it makes me feel like the buttons are more in the way than anything else.

**Comment by mezz** [comment]
Thanks for the suggestion!
This has been implemented as a configurable option, pagination can be removed from bookmarks or the ingredient list.
