### ISSUE TITLE
GUI text doesn't wrap

### ISSUE THREAD

**Issue by Regnander** [mezz/JustEnoughItems#2162]
The text for `gui.jei.category.fuel.smeltCount`/`gui.jei.category.fuel.smeltCount.single` doesn't wrap and goes outside the GUI in some languages.

I've tried adding newlines (`\n`) to the language file to no avail.

|![English](https://user-images.githubusercontent.com/17113053/99153591-a553e780-26a9-11eb-8a73-ca7b43a39fbd.png) ![German](https://user-images.githubusercontent.com/17113053/99153586-a38a2400-26a9-11eb-963d-a85788db02d7.png)<br> ![Swedish](https://user-images.githubusercontent.com/17113053/99153589-a4bb5100-26a9-11eb-8df1-a35ecfdef42c.png) ![Polish](https://user-images.githubusercontent.com/17113053/99153588-a422ba80-26a9-11eb-9976-ad97ea620407.png)
|-|
|_Pictured: English, German, Swedish and Polish_

**Comment by Greg-21** [comment]
Oh, thanks for the reminder. As a workaround, I planned to shorten the Polish "Przetapia przedmiotów: %s" and leave only "Przetapia: %s" (Eng. "Smelts: %s"). It will reduce clarity, but it's still better than having text longer than the recipe frames and even the entire GUI.

**Comment by mezz** [comment]
Thanks for the report!
I have made the recipe size depend on the language, so it'll measure the length of the string and make the recipe wider.
![2020-12-11_21 45 39](https://user-images.githubusercontent.com/916092/101978641-47181700-3c0b-11eb-80ae-39718872f115.png)

You'll still have to stay within the GUI width but that should buy you a lot of space.
