### ISSUE TITLE
JEI is not searching on Tags on a server 

### ISSUE THREAD

**Issue by MuteTiefling** [mezz/JustEnoughItems#2165]
Thank you for reporting!

Version: jei-1.16.4-7.6.0.58.jar

$ doesn't seem to return any results when searching for tags on a server. Working fine in Single Player

https://github.com/NillerMedDild/Enigmatica6/issues/380

**Comment by NielsPilgaard** [comment]
This is has been fixed by... something? No longer an issue in in-dev Enigmatica 6

**Comment by MuteTiefling** [comment]
It seems random. Maybe related to something else, but it's started happening again on the public E6 server.

**Comment by EndergamerHUN** [comment]
It also messes with color searching. Works in Single Player, not on servers.

**Comment by Alwinfy** [comment]
Seems to be same underlying issue as this: https://github.com/mezz/JustEnoughItems/issues/2217#issuecomment-763172521

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version of JEI by #2227

**Comment by MuteTiefling** [comment]
Awesome, thanks for looking into this! :D

**Comment by Xiarno** [comment]
Doesn't work for me and I'm using the latest server & client version possible. Tag are enabled in the settings.
