### ISSUE TITLE
Bookmarks gui buttons are massive.

### ISSUE THREAD

**Issue by tobi-polar** [mezz/JustEnoughItems#2167]
When using a refined storage grid:
![2020-11-17_12 24 39](https://user-images.githubusercontent.com/36657224/99338721-7f5c5c00-28d0-11eb-90e6-ae62f927527f.png)
when just viewing player inventory:
![2020-11-17_12 30 02](https://user-images.githubusercontent.com/36657224/99338821-b03c9100-28d0-11eb-9b94-9a6c0ac01f99.png)

Minecraft:1.16.3
JEI Version: jei-1.16.3-7.6.0.51
Forge:34.1.42

I don't know why it's happening but please god make it stop. Probably a clash with ftb chunks/quests gui buttons?

**Comment by Based199** [comment]
can confirm. pack im using is ftb unstable 1.16. Happens on all gui scales, each with increasing size. 
happens for me with a status effect, but it'll even happen in a furnace gui or any other gui.

![image](https://user-images.githubusercontent.com/32063145/99416030-42cb3900-28ad-11eb-8b46-bbc3b7552bd8.png)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.
