### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Grim25** [mezz/JustEnoughItems#2168]
> url
[crash-2020-11-17_08.27.48-client.txt](https://github.com/mezz/JustEnoughItems/files/5553767/crash-2020-11-17_08.27.48-client.txt)

![Screenshot 2020-11-17 083345](https://user-images.githubusercontent.com/74605287/99396380-ac4c4700-28af-11eb-89d2-f26111917e58.png)

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Ommina** [comment]
Caused by: java.lang.OutOfMemoryError: Java heap space

Give it more RAM.  (This is not an error with JEI specifically, it's just getting the blame.)
