### ISSUE TITLE
Unable to get items

### ISSUE THREAD

**Issue by artalartistic** [mezz/JustEnoughItems#2169]
Hello! I'm not sure if this is just because of me or if the server I'm on somehow has an anti-cheat, but I seem to be unable to drag items from the JEI list into my inventory. Any fixes?

**Comment by Ommina** [comment]
Er.  If the server says no, then no.

Or maybe I'm just not understanding your phrasing.  JEI's goal certainly isn't to enable some sort of cheat mode for anybody who installs it.
