### ISSUE TITLE
Crash on Connect

### ISSUE THREAD

**Issue by magerooster** [mezz/JustEnoughItems#217]
https://gist.github.com/magerooster/5dee6d7d81c970c3b64c (Original crash)
https://gist.github.com/magerooster/321b1e8f0fadaeb2b027 (On connect) 

Initially randomly disconnected from the server while moving items around between chests.
Continues to happen each time I reconnect to the server.

Edit: Realized the initial crash has something different and added the gist for that.

I started this server up yesterday and it had no problems until now.

**Comment by mezz** [comment]
Thanks for the report!
Please try with this new version http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2288763
