### ISSUE TITLE
Unable to download JEI

### ISSUE THREAD

**Issue by Vernolity** [mezz/JustEnoughItems#2170]
When I start up a modpack with JEI for the first time, it will stop responding when it starts unpacking/downloading JEI files.

My RAM seems to be fine, but my processor just goes rambo and uses every bit of power to keep it from crashing.
It takes ages before it crashes itself and just gives me an exit code: 0.

**Comment by Ommina** [comment]
I don't recall JEI doing any downloading of files, save for in a development environment.

So -- let there be logs.

**Comment by Vernolity** [comment]
Yeah, won't do. Maybe it's just unpacking, but the start-up of the modpack just doesn't work. It stops unpacking at JEI and uses everything of my CPU. It just stops responding and I have to force close it.

**Comment by Ommina** [comment]
Provide the logs then and I'll take a look.  debug.log from the logs folder to pastebin or gist preferred.

**Comment by Vernolity** [comment]
The issue was likely related to the client I was playing the mod from. I don't encounter the problem anymore. The problems encountered on the Twitch app. Because it was recommended to try other launchers first, I did that first and it works. Thanks for trying to help anyway.
