### ISSUE TITLE
[1.16.4] Large Bookmark Buttons

### ISSUE THREAD

**Issue by TwilightPSN** [mezz/JustEnoughItems#2171]
Have been having an issue where the bookmark buttons are massive even after many of the updates.
![2020-11-20_20 05 38](https://user-images.githubusercontent.com/37508557/99863413-0da03e80-2b6c-11eb-8880-9bbd2e82a4de.png)

**Comment by Ommina** [comment]
See #2167, #2129, and #2119

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.
