### ISSUE TITLE
Undeclared Dependency on FTB GUI Library

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2173]
Not an issue with the mod itself per se, but with how it's listed on CurseForge. The JEI Config UI requires [FTB GUI Library](https://www.curseforge.com/minecraft/mc-mods/ftb-gui-library), but this is not listed as [a relation](https://www.curseforge.com/minecraft/mc-mods/jei/relations/dependencies) on CurseForge. This makes it easy to miss the dependency when assembling a modpack, negatively impacting accessibility/configurability.

**Comment by AngleWyrm10** [comment]
Seconded; The display of optional dependency would be an improvement.

**Comment by Aevaris** [comment]
Thirded, but while installing it, the 4 quick toggle buttons in the top left don't work as they attempt to call /ftbguilibrary commands which do not exist.

**Comment by SaphireLattice** [comment]
At very least have this be mentioned in the mod description. Was about to create an issue for this but found there is one already.

There's not a single mention of the dependency on FTB library for even the *settings* of the mod until you try to open it and fail.

I understand that most people use modpacks, but it is rather inconvenient to build your own when there's all the various potentially missing "optional" things.

**Comment by mezz** [comment]
Thanks for the report!
I have removed support for FTB Library and now recommend installing the Configured mod to configure mods in-game. Sorry, I wish this was built into Forge like in previous versions.
This is entirely optional, you can use JEI without an in-game config, so I do not put a hard dependency on these mods that add support for in-game configs.
