### ISSUE TITLE
Endless JEI server issues

### ISSUE THREAD

**Issue by HBARRY19** [mezz/JustEnoughItems#2179]
After countless hours of reinstalling mods and trying pre-made packs every time I try to play on my local server, it says "The Server must have JEI installed" when it has the mod already in the mods folder.

Please help

**Comment by mezz** [comment]
Thanks for the report!
I suspect something in JEI is crashing, or some other mod is having a bad interaction with JEI.
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
