### ISSUE TITLE
Erratic replacement of slot 2 with a stack of a random item from MC

### ISSUE THREAD

**Issue by Letoric** [mezz/JustEnoughItems#2180]
This issue occurs when enabling cheats via ctrl + click, it is not 100% consistent, but with doing it enough times, you're bound to see it. Sorry it's not a more detailed report, but that's what I've narrowed it down to. If you believe this is other mods, let me know and I'll try to dig deeper.

forge-35.1.11
jei-1.16.4-7.6.0.58

absentbydesign-1.16.3-1.1.1.jar
AdditionalEnchantedMiner-1.16.4-16.1.3.jar
ae2extras-1.0a-1.16.4.jar
aiotbotania-1.16.3-1.4.3.jar
angelring-1.16.3-1.3.3.jar
Apotheosis-1.16.3-4.4.1.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
appliedenergistics2-8.2.0-alpha.2.jar
archers_paradox-1.16.3-1.0.0.jar
architectury-1.1.55-forge.jar
ars_nouveau-1.16.3-1.8.1.jar
AttributeFix-1.16.4-9.0.2.jar
AutoRegLib-1.6-47.jar
BadMobs-1.16.4-8.0.2.jar
bagofyurting-1.16.4-1.1.0.2.jar
balancedenchanting-1.0.jar
BetterAdvancements-1.16.4-0.1.0.103.jar
biggerreactors-1.16.3-0.2.6-beta.jar
BloodMagic-1.16.3-3.0.2-7.jar
Bookshelf-1.16.4-9.3.18.jar
Botania-1.16.4-410.jar
BotanyPots-1.16.4-6.0.7.jar
buildinggadgets-3.7.2.jar
bwncr-1.16.4-3.9.16.jar
cagedmobs-1.16.4-1.2.6.jar
camera-1.16.4-1.0.7.jar
cc-tweaked-1.16.4-1.94.0.jar
chonk-1.16.3-0.1.4.jar
citadel-1.5.3.jar
cleancut-mc1.16-2.2-forge.jar
ClientTweaks_1.16.3-5.2.0.jar
cloth-config-forge-4.1.1.jar
Clumps-6.0.0.12.jar
cofh_core-1.16.3-1.0.4.jar
collective-1.16.4-1.53.jar
comforts-forge-1.16.4-4.0.0.2.jar
Compressium-1.16.4-1.1.36.jar
confdespawntimer_1.16.4-1.3.jar
constructionwand-1.16.2-1.6.jar
Controlling-7.0.0.11.jar
CookingForBlockheads_1.16.3-9.2.2.jar
CosmeticArmorReworked-1.16.4-v1.jar
CraftingTweaks_1.16.3-12.2.0.jar
crashutilities-3.6.jar
Cucumber-1.16.4-4.1.5.jar
culinaryconstruct-forge-1.16.3-4.0.0.1.jar
curios-forge-1.16.4-4.0.3.0.jar
Cyclic-1.16.4-0.10.0.jar
dankstorage-3.12.jar
DarkUtilities-1.16.4-7.0.3.jar
deathbackup_1.16.4-1.1.jar
DefaultOptions_1.16.3-12.2.0.jar
demagnetize-forge-1.16.2-1.2.2.jar
DimStorage-1.16.4-4.3.0.jar
Ding-1.16.3-1.2.0.jar
DungeonCrawl-1.16.3-2.2.1.jar
Dynmap-3.1-beta5-forge-1.16.3.jar
elevatorid-1.16.4-1.7.8.jar
emojiful-1.16.3-2.1.1.jar
enchantingcmds_1.16.4-1.3.jar
EnchantmentDescriptions-1.16.4-6.0.2.jar
engineersdecor-1.16.4-1.1.4.jar
engineerstools-1.16.4-1.1.2.jar
ensorcellation-1.16.3-1.0.3.jar
entangled-1.2.9-mc1.16.4.jar
extradisks-1.16.4-1.3.4.jar
ExtraStorage-1.16.4-1.2.1.jar
extremeSoundMuffler-3.1_Forge-1.16.4.jar
FarmingForBlockheads_1.16.3-7.2.1.jar
FastFurnace-1.16.3-4.3.0.jar
FastLeafDecay-v25.jar
FastWorkbench-1.16.3-4.4.1.jar
flatbedrock-1.16.4-1.1.6.jar
FluxNetworks-1.16.4-6.1.5.10.jar
forbidden_arcanus-1.16.4-1.0.0.jar
forge-1.16.4-geckolib-3.0.0-beta.10.jar
ftb-backups-2.1.1.6.jar
ftb-chunks-1604.2.1.50.jar
ftb-gui-library-1604.1.1.26.jar
ftb-ranks-1604.1.1.9.jar
ftb-teams-1604.1.0.13.jar
ftb-ultimine-1603.1.1.13.jar
ftbessentials-1603.1.0.11.jar
globalxp-1.16.3-v1.4.15.jar
ImmersiveEngineering-1.16.4-4.1.1-128.jar
ImmersivePetroleum-1.16.3-3.0.0.jar
industrial-foregoing-1.16.4-3.2.5-74675d6.jar
invtweaks-1.16.2-1.0.0.jar
ironchest-1.16.4-11.2.10.jar
ironfurnaces-1.16.4-2.5.4.jar
IronJetpacks-1.16.4-4.1.3.jar
item-filters-2.2.2.18.jar
JAOPCA-1.16.4-3.4.0.1.jar
jei-1.16.4-7.6.0.58.jar
jeiintegration_1.16.4-6.1.1.11.jar
jumbofurnace-1.16.4-2.2.0.1.jar
JustEnoughResources-1.16.4-0.12.0.103.jar
KleeSlabs_1.16.3-9.2.0.jar
kubejs-1604.3.1.111-forge.jar
kubejs-immersive-engineering-1604.1.0.8.jar
kubejs-mekanism-1604.1.0.4.jar
kubejs-thermal-1604.1.0.5.jar
kubejs-ui-1604.1.0.7.jar
LibX-1.16.3-1.0.5.jar
light-overlay-5.5.4.jar
LightingWand-1.16.4-1.7.2.jar
Lollipop-1.16.4-3.2.3.jar
mahoutsukai-1.16.4-v1.26.5.jar
managear-1.16.3-2.2.1.jar
Mantle-1.16.4-1.6.43.jar
mcjtylib-1.16-5.0.15.jar
mcw-bridges-1.0.4-mc1.16.4.jar
mcw-doors-1.0.1fix-mc1.16.4.jar
mcw-trapdors-1.0.0-mc1.16.4.jar
mcw-windows-1.0.2-mc1.16.4.jar
mcws-roofs-2.0.0-mc1.16.4.jar
Mekanism-1.16.4-10.0.18.445.jar
MekanismAdditions-1.16.4-10.0.18.445.jar
MekanismGenerators-1.16.4-10.0.18.445.jar
MekanismTools-1.16.4-10.0.18.445.jar
metalbarrels-3.3a.jar
mininggadgets-1.7.1.jar
mining_dimension-1.16.4-1.0.2.jar
modnametooltip_1.16.2-1.15.0.jar
mods.txt
modular-routers-1.16.3-7.2.0-39.jar
morered-1.16.4-2.0.1.2.jar
MouseTweaks-2.13-mc1.16.2.jar
MysticalAgradditions-1.16.4-4.1.2.jar
MysticalAgriculture-1.16.4-4.1.3.jar
MysticalCustomization-1.16.4-2.1.1.jar
MythicBotany-1.16.3-1.2.0.jar
NaturesAura-33.1.jar
NaturesCompass-1.16.4-1.8.6.jar
NetherPortalFix_1.16.3-7.2.1.jar
nomowanderer_MC1.16.4_1.0.jar
observerlib-1.16.4-1.4.3.jar
omgourd-1.16.3-1.0.0.jar
pamhc2foodcore-1.16.3-1.0.0.jar
Patchouli-1.16.4-48.jar
pedestals-0.8k.jar
phosphophyllite-1.16.3-0.2.1-beta.jar
PickleTweaks-1.16.4-5.1.4.jar
Placebo-1.16.3-4.3.3.jar
platforms-1.16-1.7.8.jar
pneumaticcraft-repressurized-1.16.4-2.7.2-86.jar
polymorph-forge-1.16.3-0.16.jar
portality-1.16.4-3.2.0.jar
potionsmaster-0.1.28-1.16.4-35.1.7.jar
Powah-1.16.4-2.3.6.jar
Psi 1.16-88.jar
Quark-r2.4-279.jar
randompatches-1.16.4-1.22.1.10.jar
rangedpumps-0.8.2.jar
ReAuth-1.16-Forge-3.9.3.jar
refinedstorage-1.9.9.jar
refinedstorageaddons-0.7.2.jar
reliquary-1.16.3-1.3.4.1061.jar
repurposed_structures-1.16.4-2.3.3.jar
resourcefulbees-1.16.3-0.5.5b.jar
restrictions-1.16-3.0.3.jar
rftoolsbase-1.16-2.0.8.jar
rftoolsbuilder-1.16-3.0.12.jar
rftoolscontrol-1.16-4.0.6.jar
rftoolspower-1.16-3.0.8.jar
rftoolsstorage-1.16-2.0.7.jar
rftoolsutility-1.16-3.0.19.jar
rhino-1.7.13.9.jar
rsgauges-1.16.4-1.2.6-b1.jar
Runelic-1.16.4-6.0.2.jar
ScalableCatsForce-2.13.3-build-6-with-library.jar
scuba-gear-1.16.4-1.0.1.jar
shetiphiancore-1.16-3.8.4.jar
shutupexperimentalsettings-1.0.1.jar
SilentGear-1.16.3-2.4.3+186.jar
SilentLib-1.16.3-4.9.0+63.jar
simplemagnets-1.0.8-mc1.16.4.jar
simplylight-1.16.4-1.1.1.jar
SolarFluxReborn-1.16.3-16.2.3.jar
solcarrot-1.16.3-1.9.8.jar
spatialharvesters_forge_1.16.4-0.9.10.jar
StorageDrawers-1.16.3-8.2.1.jar
tanknull-2.2-1.16.4.jar
tgcropesmod-1.16.2-1.1.0.jar
theoneprobe-1.16-3.0.6.jar
thermal-1.16.3-1.0.5.jar
thermal_cultivation-1.16.3-1.0.5.jar
thermal_expansion-1.16.3-1.0.5.jar
thermal_innovation-1.16.3-1.0.3.jar
titanium-1.16.4-3.2.2.jar
TMechworks-1.16.3+-2.2.2.jar
Toast-Control-1.16.3-4.3.0.jar
tombstone-1.16-6.0.3.jar
ToolBelt-1.16.3-1.15.2.jar
torchmaster-2.3.5-alpha.jar
TrampleStopper-2.4.8+mc-1.16.4.jar
trashcans-1.0.3-mc1.16.4.jar
TrashSlot_1.16.3-12.2.1.jar
TravelAnchors-2.1.jar
useful_backpacks-1.16.4-1.11.6.86.jar
useful_railroads-1.16.4-1.4.6.34.jar
u_team_core-1.16.4-3.1.15.189.jar
WaterStrainer-1.16.3-10.0.0.jar
Waystones_1.16.3-7.3.1.jar
Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar
woot-1.16.4-1.0.2.1.jar
WorldEdit-CUI-FE3-1.16.4-3.0.8.jar
worldedit-forge-mc1.16.3-7.2.1-dist.jar
XaerosWorldMap_1.11.4_Forge_1.16.4.jar
Xaeros_Minimap_20.28.2_Forge_1.16.4.jar
xnet-1.16-3.0.10.jar
XNetGases-1.16.4-2.1.1.jar
xptome-1.16.2-v1.1.6.jar

**Comment by mezz** [comment]
Thanks for the report!
I think this may be an interaction with another mod, please try to confirm that JEI alone works, and then try to find which combination causes the issue.

**Comment by LyraelRayne** [comment]
Hi there, I have reproduced this on a fresh (CurseForge) profile with only jei-1.16.5-7.7.0.106.jar and default settings.

The issue isn't that it's randomly replacing slot 2, it's that when you "pick" an item stack into a slot by pressing the number key (for example, 2) it will replace the item in that slot, deleting the item. Not so bad if the slot is empty, not great if it contains your fully enchanted Netherite sword, or your carefully crafted Create contraption.

Technically, this is probably not a bug. _But!_ It'd be nice to have the option to disable the number button slot filling, or at the very least not overwrite existing items when it triggers (either by doing nothing, or by moving the original item to an empty slot if one is available and doing nothing otherwise). 

I think the reason this user has it happen in slot 2 "randomly" is that sometimes when you're trying to search for an item in the search bar, and you're searching by mod (using the "@" symbol, which just happens to be on the "2" key) sometimes you're not actually in the search box, and you don't quite hit the shift key properly. Result: Nice new stack of Wool (or whatever was under the mouse at the time) where your sword used to be :( I've also had it happen with slot 3 a number of times because I use the # prefix for finding enchanted books. It seems to be random because you don't always notice it when it happens. One day, you switch to your sword and it's turned to Wool!

**Comment by mezz** [comment]
I have added a config to enable this feature, and it is now disabled by default: #2612
