### ISSUE TITLE
JEI "all recipes" tab opens when closing the vanilla recipe dictionary

### ISSUE THREAD

**Issue by Barerock** [mezz/JustEnoughItems#2183]
Using the 7.6.0.62 version for 1.16.4 and Forge 35.1.10.

When closing the recipe dictionary (used for quick mass crafting) JEI opens the recipes menu/tab/feature that is typically accessed by clicking on the crafting arrow. It doesn't do this when opening the menu, only when clicking on the book again to close it; it adds another thing to close when exiting my inventory or when I'm done with crafting, mostly it breaks immersion and is frustrating to deal with.

Thanks, I hope this isn't a duplicate from ages ago!

**Comment by mezz** [comment]
Thanks for the report!
I think this should be fixed in the latest version of JEI, please try it out and report back when you get a chance.
