### ISSUE TITLE
[1.16.4 forge-35.1.13] Very minor: Can not use CTRL+A in search field

### ISSUE THREAD

**Issue by Griefed** [mezz/JustEnoughItems#2186]
Hello everybody,

I feel stupid for opening an issue for this. I didn't find an answer browsing reddit, wikis and a couple of forums.

Forge Version: forge-35.1.13
Minecraft Version: 1.16.4
JEI Version: jei-1.16.4-7.6.0.62

In the JEI search field, I can not mark all text via CTRL+A so I can then delete it...that's it. 
That's my issue...eh yeah, sorry.

Thing is, it works in a modpack called Valhelsia 3. 
I've compared my configs and modversion to theirs and they're identical, furthering my confusion why it works for them, but not for me. It's a non-issue in the grand scheme of things, but it's slowly driving me insane. 😄 I've also tried using the oldest available version for 1.16.4, jei-1.16.4-7.6.0.5, but no dice.

Any help would be appreciated.

Stay safe and stay healthy.
Cheers,
Griefed

P.S.: Thank you for keeping JEI updated through all these years. Been playing Minecraft since early beta and JEI has become a must have for me. Keep up the good work.

**Comment by CaptainSisko** [comment]
I am using the Direwolf20 1.16 pack which uses the same Forge and JEI versions, I am also experiencing this issue.

CTRL + F also doesnt work to focus the Search Box however if I unbind "F" from "Swap Item With Offhand" it starts working.

I tested unbinding "A" from "Strafe Left" but that doesn't make CTRL + A work.

If you look at the recipe for an item both CTRL + A and CTRL + F work fine, the issue only occurs when you are looking at your inventory and trying to use the keyboard shortcuts.

I created a new instance of Minecraft with:
MC 1.16.4
Forge-35.1.13
JEI-1.16.4-7.6.0.62

The issue does not occur with **only** JEI installed so it is likely a mod conflict causing the issue. If I get some time later today i will attempt to find the mod causing the issue.

**Comment by tanyan-tanyan** [comment]
I'm not so sure if it's a mod conflict because the same thing happens with the backspace key. You have to frantically spam the key to clear out the search box instead of just being able to hold it down. There are times when it works but I haven't been able to pinpoint what it depends on.

**Comment by AyalCiobotaru** [comment]
Was this fixed? I'm having this issue with Skyopolis 4.

**Comment by Griefed** [comment]
@AyalCiobotaru 
I am no longer having this problem using Forge 36.2.4, Minecraft 1.16.5, JEI-1.16.5-7.7.1.121, so either it was fixed in an update of JEI or any of the other mods in my modpack which cause this issue to begin with have fixed it from their side. Unfortunately, I can not pinpoint which of these two actually resolved this.
