### ISSUE TITLE
No GUI for Modded Multiplayer Server

### ISSUE THREAD

**Issue by Coraline77447** [mezz/JustEnoughItems#2188]
Hi, I've just started my modded 1.16.4 server and I cant see JEI GUI when I'm in my inventory and I can't show JEI with a key bind in my inventory. On any of my modded singleplayer worlds I should be able to see JEI's GUI and being able to see all of the crafting recipes but for my modded multiplayer server I cant see JEI at all.

EDIT: JEI as of it's GUI (in inventory btw) is working for modded singleplayer, but it's not working on my modded multiplayer server tho...

EDIT 2: This problem has existed before and I'm experiencing it like how many others have in the past and since I'm looking it up on how to fix this problem and that you've replied to Renadarian sayin that they accidentally hit control+O and to try the hotkey to bring it back (which didn't work for me) then the last resort is to delete JEI's config folder...

SUGGESTION: Could you make a tutorial for people who's making a modded multiplayer server (through a server hosting service or made one without server hosting) to make JEI work on the server side? Why I suggest you to make a tutorial for that is cause if I were to find out which world belongs to my modded multiplayer server then what? What needs to be specifically changed in order for JEI to work for the server side?

**Comment by Havoc1001** [comment]
I am experiencing this same problem. I even deleted the server and client config and everything related to jei, and still have the problem. What the funny part about the whole situation is on my modded Minecraft server everyone but me can see and use the jei interface.

**Comment by Coraline77447** [comment]
So even if I were to delete everything related to JEI and its config files I still wouldn't be able to see JEI's GUI on my modded multiplayer server? Then that's really strange and makes some of those solutions that Mezz said to Renadarian a few years back irrelevant now since deleting JEI's config files doesn't fix the problem. Havoc, have ya tried to change your JEI world settings for the world your server is using? Cause I cant find my servers world in JEI world settings in its config file and even if I were to find it what needs to be changed in order for me or us to see JEI's GUI on a modded multiplayer server?

**Comment by Havoc1001** [comment]
I ended up finding out that my server was causing an error with some random mod, I took it out but was still unable to see jei. But as soon as I left the server and came back jei popped up. But sometimes it just randomly disappears from my Inventory screen.

**Comment by Maruhl** [comment]
I have the same issue, so i tested a while why that happen.
I downloaded: [FTB Gui Library](https://www.curseforge.com/minecraft/mc-mods/ftb-gui-library) just for fun, to enter the configuration menu.
Everything happened in singleplayer creative mode. After i entered my modded server, the menu was available.
Maybe this will help you.

**Comment by Coraline77447** [comment]
But I dont have FTB Gui Library since my server is being hosted by me on my pc not on any server hosting or on curseforge or FTB launcher.

My launcher is Tlauncher so idk if FTB Gui Library would even work for me since I'm using a third party launcher to launch modded Minecraft.

Even tho I have the official launcher now thanks to someone on Project MMO's discord for buying me the game for my main Microsoft account but I only use my official launcher for vanilla servers and maybe vanilla but for modded I use Tlauncher all the way even tho I'm only able to accumulate 2977 (2965 actually.)

Tlauncher used to let me accumulate well over 3gb (3795 or something like that) since I only have 4gb of RAM to work with...

Also Project MMO's gui doesn't show up when I used the official launcher and I was tryin to turn all of PMMO's gui stuff on/off and wasn't workin but for Tlauncher I can see PMMO's gui like everyone else can so that why I'm sticking with Tlauncher for modded, especially since my server is in offline mode anyways.

**Comment by kreezxil** [comment]
ftb gui  library is just a mod. i had jei and rei both functional in 1.16.4 and then poof it vanished. we all here have different pack builds clearly. I'm willing to bet it's a forge change. Forge changed a class without bothering to update the class version changer. ie the middle number. Based on what is going on here, I'm going to start rolling backwards on forge until I find a version of forge that works.

**Comment by Havoc1001** [comment]
Nah its mods that are conflicting, it has nothing to do with forge. I
switched mod packs that has the same version of forge, and I have no
problems now. Its 100% a mod conflict.

**Comment by kreezxil** [comment]
for you maybe, and please tell us if you know which mods are conflicting so that everyone may benefit. I think some of us might have a forge issue. I'm still chasing that rabbit. ok so I took my pack that was acting up and rolled it down to 1.16.4-35.1.13 and the jei came back, but on 35.1.29 the jei doesn't show up.

**Comment by Coraline77447** [comment]
Maybe forge changed something between 35.1.13 and 35.1.32 or whatever latest version forge is at now that they need to fix. 

They've made a change to something related to the GUI for certain mods while breaking others like possibly JEI's GUI for modded multiplayer servers both dedicated servers and not dedicated servers since JEI's GUI still works for modded singleplayer. 

Btw my report is now irrelevant since I'm considering about getting rid of my server that I'm literally hosting on my pc since there's hardly anyone who would like to join me since the only way to join my modded multiplayer server is with a VPN as of Radmin VPN. 

But I'm gonna keep this report open since this issue is still relevant to others who either is hosting a server on a way better pc than mine or is hosting a server on a server hosting service so that people can connect without having to install a VPN to connect unlike my server......
