### ISSUE TITLE
Creative Gui Screen Crash

### ISSUE THREAD

**Issue by BedrockLegends** [mezz/JustEnoughItems#2189]
[crash-2020-12-27_14.56.07-client.txt](https://github.com/mezz/JustEnoughItems/files/5745192/crash-2020-12-27_14.56.07-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
It looks like there are several mods that edit the vanilla method that JEI is calling:
`	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:852) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
`
(formatted nicer:)
```
{
	re:mixin,
	pl:accesstransformer:B,
	pl:runtimedistcleaner:A,
	re:classloading,
	pl:accesstransformer:B,
	pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,
	pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,
	pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,
	pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,
	pl:mixin:A,
	pl:runtimedistcleaner:A
}

```

randompatches, mining_helmet, immersiveengineering, and botania are all involved. Please try removing these mods and see if the crash still occurs.
