### ISSUE TITLE
[1.16.4] AdditionalLights + JEI Recipes not working?

### ISSUE THREAD

**Issue by Yourname942** [mezz/JustEnoughItems#2199]
Does anyone else have JEI issues where JEI recipes show up in singleplayer, but not on a multiplayer server? I only have 2 mods:

Minecraft 1.16.4
Forge 35.1.29 (latest)
JEI 1.16.4-7.6.1.63
Additional Lights 1.16.4-2.1.3

I even tried doing this with Forge 35.1.4 (reccomended) but it doesn't work here either. More specifically I can see vanilla recipes just fine in both singleplayer and multiplayer, but for Additional lights recipes I only can see them in JEI in singleplayer. 

This also occured with Advanced Hook Launchers JEI recipes. I removed that mod to focus on just 2 mods installed to narrow down the error.

Another issue is I cannot give myself items with cheat mode enabled, even though I gave myself op permission in the server

Latest log (multiplayer): https://gist.github.com/Yourname942/c90330bbab68d66f440237bccbe65693

Latest log (singleplayer):
https://gist.github.com/Yourname942/ecc69e1cf910aff2b10ba250bfa9b1a6

**Comment by Draskh** [comment]
[17:21:37] [Netty Client IO #1/INFO]: Connected to a vanilla server. Catching up missing behaviour. 

You joined a vanilla server. You can only use a mod if it is installed on the server.

**Comment by Yourname942** [comment]
> mod if it is installed on


I posted 2 different logs: 
1) The first one is when I tested the mods on my multiplayer server
2) The second one is when I tested the mods in a singleplayer world (to see if there are weird behavior differences to potentially help narrow down the cause of the issues.
