### ISSUE TITLE
Red text at the top of JEI saying if you're in cheat mode

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#220]
This has happened to me at least 15 times this week:

So I'm looking up recipes in JEI, then I find a bug so I switch to cheat mode to get some uncraftable items from our mod. Then I try to view some recipes later on and then boom, items are now in my inventory because I forgot to switch back.

Something like this would be really helpful. Obviously there doesn't need to be a [Normal Mode] text, just the cheat one.
![image](https://cloud.githubusercontent.com/assets/6166773/13970773/23b44324-f048-11e5-857b-38b55141d7cd.png)

**Comment by Jerzerak** [comment]
It might look better if there was maybe a red icon overlayed on the settings icon in the bottom right or the page numbers at the top change color based on mode

**Comment by Prospector** [comment]
Well it needs to be noticeable, or else it would be completely useless.

**Comment by mezz** [comment]
It needs to be subtle, or else it would be completely hideous :D

**Comment by Prospector** [comment]
IMO the way I edited the text into the image above makes it noticable and still keeps it clean. Or even something as simple as making the page numbers red and bold would work.

**Comment by Jerzerak** [comment]
I'm with mezz on this one, if the change is small but not entirely unnoticeable it should get the job done without distracting from the item list, UX should be the primary concern here

**Comment by Prospector** [comment]
Personally I find the primary concern function. Looks are a bonus.

**Comment by mezz** [comment]
This project tries to keep a minimalist design to some extent, there are no words anywhere on the item list.

**Comment by Prospector** [comment]
Like I said, simply making the page numbers red and bold could keep the minimalistic design by not adding any new objects to it, and it could get the point across.

**Comment by mezz** [comment]
That would be better, but it would be confusing if you didn't know what it meant already. I haven't thought of a good solution but I will leave this open.

**Comment by mezz** [comment]
Maybe a retexture of the wrench would indicate that your mode is different.

**Comment by Jerzerak** [comment]
From a user standpoint I do think that adding a light grey text to the search box stating the mode that you are in might do the trick

**Comment by TehNut** [comment]
Either changing the wrench or the outline color of the search bar.

**Comment by mezz** [comment]
Can we agree that this red wrench does the job?

![2016-03-22_17 24 01](https://cloud.githubusercontent.com/assets/916092/13972089/eb38a930-f052-11e5-8286-789c6301c24b.png)

**Comment by TehNut** [comment]
Yup looks good!

**Comment by Prospector** [comment]
Yeah, it looks nice but still not terribly obvious and it probably won't stop me from accidentally cheating items when looking up recipes. Maybe a bit more saturated red?

**Comment by Jerzerak** [comment]
Any more obvious and it'll just become an eyesore IMHO

**Comment by mezz** [comment]
The more red I make it the darker it gets, maybe I need to make a new asset instead of messing with OpenGL colors.

**Comment by Prospector** [comment]
This might be good 
![image](https://cloud.githubusercontent.com/assets/6166773/13972188/c0a7de56-f053-11e5-99c1-b966aabed246.png)

**Comment by Jerzerak** [comment]
Is it possible to make a red mouseover highlight as well? That'd certainly be very clear in function

**Comment by mezz** [comment]
Compromise?

![2016-03-22_17 24 01-2](https://cloud.githubusercontent.com/assets/916092/13972228/ff919cba-f053-11e5-885e-c318618144ec.png)

**Comment by mezz** [comment]
The latest 1.9 build has it (I assume that's what you're using).

**Comment by Prospector** [comment]
Yep. Thanks ;)
