### ISSUE TITLE
Crash on loading JEI

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [mezz/JustEnoughItems#2200]
I use Java Edition and allocated the max amount of RAM that it let me (Which was over 10GB) and it still crashed every time I loaded the modpack. It always crashed on JEI loading in the finishing up section (6/7).
https://gist.github.com/23KiaraMinecraft/7e0c4d5f72801cf9d4a17d6c58dba9ba

**Comment by mezz** [comment]
Thanks for the report!
Try setting this to `true` in JEI's `jei-client.toml` config file:
```
    #Set low-memory mode (makes search very slow, but uses less RAM)
	LowMemorySlowSearchEnabled = false
```

**Comment by 23KiaraMinecraft** [comment]
Thanks for the feedback. I've actually fixed the problem. I got a better computer and it runs smoothly now.

**Comment by mezz** [comment]
Ok, glad to hear it worked out
