### ISSUE TITLE
Can't select-all text in JEI search box

### ISSUE THREAD

**Issue by TemperedFool** [mezz/JustEnoughItems#2203]
Running the modpack Enigmatica 6, versions 0.3.2 and 0.3.4. These have JEI versions 1.16.4-7.6.0.62 and 1.16.4-7.6.1.63 respectively.

Running Max OS X  10.15 and then 11 (with latest point releases).
Oracle Java 8 Update 271 build 09.

Hitting cmd-A doesn't select text in the JEI search box. I've also tried control-A to no avail. I checked in with users in the E6 Discord channel, and it sounds like a few people are having the same issue, on Windows as well.

Not sure if there are logs or similar things that would help diagnose the issue, if so please let me know!

**Comment by mezz** [comment]
Thanks for the report!
Please try version 7.6.1.65. I have just recently fixed this issue: https://github.com/mezz/JustEnoughItems/commit/9f9b7778079cf48cc7730a0cc941837852d063f7

**Comment by TemperedFool** [comment]
Dropping that version in does seem to fix it! Thank you so much!

**Comment by IllegalCharacter** [comment]
Experiencing this issue while playing TNP Limitless 5 on Minecraft 1.18.2, JEI version 9.7.0.180

Not sure if something caused a reversion, or if it's conflict with something else.

**Comment by mezz** [comment]
@IllegalCharacter please open a new issue, this one is quite old. 
I can help look into the specifics of what's happening in the new issue.
