### ISSUE TITLE
waila is not working

### ISSUE THREAD

**Issue by Skorlex1** [mezz/JustEnoughItems#2204]
waila is not working with my JEI, if waila is no supported with this mod, can someone recommend a mod similar as waila?

**Comment by Eric-01** [comment]
To me, the best WAILA alternative for modern versions of Minecraft and Forge is The One Probe (TOP). You can check it out.

**Comment by Eric-01** [comment]
To me, the best WAILA replacement for modern versions of Minecraft and Forge is The One Probe (TOP). You should check it out.

**Comment by Eric-01** [comment]
To me, the best WAILA replacement for modern versions of Minecraft is The One Probe (TOP). You should check it out.

**Comment by Eric-01** [comment]
To me, the best WAILA replacement for modern Minecraft versions is The One Probe (TOP). You should check it out.
