### ISSUE TITLE
A respectful ask for the ability to manually sort items within JEI, and few other things.

### ISSUE THREAD

**Issue by corneliusdeforrest** [mezz/JustEnoughItems#2208]
### Summary
The core idea is the ability to manually sort items within JEI using item's string names. This would be an option within the config, for it would by default it would make the JEI blank. This would be done by parsing a text file of ID's.

**Example:**
`<minecraft:stone>, <minecraft:stone:1>, <minecraft:stone:2>`
Which would sort into the JEI in the order:
Granite, Polished Granite, Stone

### A few extra feature ideas relative:
 - The ability to have items blink between one another in a single grid cell liken to in recipes.
**Example:**
In the text file, when using <minecraft:stone:*>, all of the items under the ID list will condense within one cell and flicker between one another as a single cell in the JEI.

 - The ability to create array elements, in order to list particular items within one cell in the JEI, that don't have the same ID. Array lists would be sorted by default alphabetically within the JEI, or by placement within the text file.
**Example:**
`ToolsArray = {
<minecraft:wood_pickaxe>,
<minecraft:stone_pickaxe>,
<minecraft:iron_pickaxe>,
<minecraft:gold_pickaxe>,
<minecraft:diamond_pickaxe>
}`

- The ability to sort recipes and uses by recipe name, alphabetically.
- The ability to create custom strings to search within JEI. Custom strings can be created inside a .txt file. Within the search bar you will type >StringName to search for it

**Comment by IMarvinTPA** [comment]
How would you feel about Inventory Tweak's old tree file format for setting the order?

**Comment by IMarvinTPA** [comment]
Tree File merge request https://github.com/mezz/JustEnoughItems/pull/2380
