### ISSUE TITLE
Crash trying to launch (1.9) [Java 6]

### ISSUE THREAD

**Issue by norveblue** [mezz/JustEnoughItems#221]
I'm not really sure what this is about, but it's the only mod crashing for me.  I removed Optifine to see if that would help (you never know) but nothing.  Here's what happens when I try to launch:

http://pastebin.com/PPzEX9mf

I have the most updated version of JEI for 1.9 and I get the same error even with the previous version.  As far as I'm aware I'm using the latest version of both JEI and Forge.  This is the first time I've tried to use JEI, so I apologize for any stupid questions.  Is there something I am missing?  Is this a simple fix?

Thank you for any help on this issue and please pardon my dumber questions.

**Comment by TehNut** [comment]
JEI requires Java 7. You are running Minecraft with Java 6. And an extremely old version of Java 6 at that.

**Comment by norveblue** [comment]
Haha I actually thought I had 7 already tied to MC but apparently not, so I didn't even think to consider it.  Thanks!
