### ISSUE TITLE
JEI not showing on the right when booting and joining server, have to do /reload everytime when booting game

### ISSUE THREAD

**Issue by zachsai** [mezz/JustEnoughItems#2213]
Title explains it, this started happening a little over after hiding items in jei, now it hides the whole jei when booting the game and joining server.
My Show/hide JEI does not make it appear

**Comment by artheus** [comment]
You will need to specify more detail, to give the mod developer a possibility to debug it.

- What version of minecraft-forge are you using?
- What version of JEI are you using?
- Are you using this in any downloadable mod-pack?
  - If not, are you building your own mod-pack? (if yes, other mods might interfere with JEI, resulting in what you see)
- Are you running this on a server, or client-only?
- Which launcher are you using for your client?
- If on server, what command are you using to start the server?
- Which java build and version are you using?
- What memory limit have you set for launching minecraft (server / client)

If you answer the questions above, and provide all the information you can think of (about your minecraft setup), there is a much bigger chance for you to actually get help with this issue.

**Comment by ghost** [comment]
Hello, I have a similar issue I am experiencing when connecting to my survival server world as well

I'm on 35.1.37 Forge

jei-1.16.4-7.6.1.65.jar

Building own modpack

Connecting to a server (hosted on my local PC) from client

Vanilla launcher

Using `java -Xms24G -Xmx24G -jar forge-1.16.4-35.1.37.jar nogui`

JRE8u27 I think

16GB mem limit for minecraft and 24GB mem limit for server

**Comment by NielsPilgaard** [comment]
@TechniumUnlimited Are you using the mod Supplementaries?
Edit: A forced crash-log (Hold F3+C for 10 seconds) would be helpful

**Comment by ghost** [comment]
It seems the GUI appears when I create a single player world in creative, just not when I join the server.

**Comment by ghost** [comment]
> @TechniumUnlimited Are you using the mod Supplementaries?

Yes, I am - I just went to their discord to see if they know anything abt whats going on in case it is that mod

**Comment by NielsPilgaard** [comment]
I found the issue to be with the version ending with 19, if you can update you should :)

**Comment by MehVahdJukaar** [comment]
hmmm

**Comment by ghost** [comment]
Here is my debug log if that could help https://drive.google.com/file/d/1tqwwTi6nlbytrSIdQyg6sL1rBJQIrY8d/view?usp=sharing

It's very large.. my apologies...

**Comment by MehVahdJukaar** [comment]
I'm not doing anything with jei :/
I don't know what could cause this

**Comment by NielsPilgaard** [comment]
@MehVahdJukaar Me neither, but your recent builds do not have any issues with JEI :)

**Comment by ghost** [comment]
> @MehVahdJukaar Me neither, but your recent builds do not have any issues with JEI :)

If the recent builds have fixed it, I think I am on the latest :(

Edit: I am 1 version behind (b instead of c)

**Comment by MehVahdJukaar** [comment]
Well that's a relief then. I'm still curious on what could have caused it

**Comment by Shorepion** [comment]
I have the same issue. If you have Apotheosis in your modlist, thats causing the issue. I did a testrun without Apotheosis and JEI was visible on server (even without starting a single player world before).

**Comment by ghost** [comment]
will test both and lyk

**Comment by ghost** [comment]
updating supplementaries did not resolve,
removing apotheosis did not resolve either

**Comment by ghost** [comment]
Another related issue https://github.com/mezz/JustEnoughItems/issues/2190

**Comment by ghost** [comment]
> I have the same issue. If you have Apotheosis in your modlist, thats causing the issue. I did a testrun without Apotheosis and JEI was visible on server (even without starting a single player world before).

It's possible that Apotheosis also causes this issue, but that another mod I have that you didn't also causes it, I am not sure, but removing it didn't resolve :(

**Comment by Shorepion** [comment]
Can you post the whole modlist?

**Comment by ghost** [comment]
I can make a gist of it as its 330+ mods xD

I also made a list of the mods I have in common with issue #2210 , they are:
apotheosis 
appleskin
ars nouveau
autoreglib 
betteradvancements 
bop 
bloodmagic 
bookshelf 
botania+addt
bountifulbaubles 
caelus api
chiselandbits 
clumps
controlling 
cosmeticarmor
craftingtweaks 
crafttweaker 
creativecore
curios/armorstands/elytra
cyclic 
darkutils 
decblocks
eidolon 
enchantmentdescriptions 
enderchests
endertanks
enigmaticlegacy
ensorcellation
forbiddenandarcanus
geckolib 
greater eye 
hwyla 
iaf
libx 
ma enchants 
macaws x
mahou tsukai
managear
mana and artifice 
morpheus?
moustweaks
polymorph
placebo
patchouli
psi 
quark 
shetiphiancore
storage drawers
valhesia structures 
waila harvestability
wawla

**Comment by ghost** [comment]
This seems to be the same issue too: https://github.com/mezz/JustEnoughItems/issues/2188

**Comment by Shorepion** [comment]
Thats not enough helpful, the full list is needed.
If its too long to post use google docs.
One way to filter the concerned mod is to split the modlist in half and run the first half then the other half, then split again, run the new half and so on..

**Comment by ghost** [comment]
Here is the full list: https://pastebin.com/icnn81Ju

**Comment by ghost** [comment]
In single player, where the JEI GUI loads, it tells me to install FTB GUI Lib to use in game config, gunna do that and see if I can find anything worthwhile there...

if nothing else.. I'll do the 50/50 splitter til I find the problem mods...

**Comment by ghost** [comment]
After further testing based on some comments elsewhere, joining a single player world, and then joining the server, does seem to resolve it - temporarily - not an acceptable fix for the problem though as I cant ask my friends to do this every time they play w/ me, at least found some more info out tho..

edit added info: Once you do load a single player world once, you can connect & disconnect as many times as you like and JEI interface will continue to load appropriately.

**Comment by f0kx** [comment]
so i also test it and your mod my mods have one in common what causes the fail maybe! EnchantmentDescriptions-1.16.4-6.0.3 to EnchantmentDescriptions-1.16.4-6.0.2 can you test it and see if it helps?

**Comment by f0kx** [comment]
https://github.com/vectorwing/FarmersDelight/issues/106

**Comment by ghost** [comment]
I will test it right now @SugarDaddii :)

**Comment by f0kx** [comment]
it was / is a problem on my side with farmers delight and apotheosis maybe EnchantmentDescriptions but you dont have farmers delight so i dont was correct in my case deleting famers delight was fixing it i think!

**Comment by ghost** [comment]
hmm, well I have already removed apotheosis, so the issue described in the one you linked is unlikely since it was, I think, apotheosis trying to access something from farmers delight? 

Did you delete Enchantment descriptions mod too?

Also how did you find the tags that were causing issues, maybe I can find it in my logs and find the same issue with a different mod

**Comment by f0kx** [comment]
i downgraded it and delete farmers delight and it was working will test it with an older version of farmers delight and apotheosis

**Comment by ghost** [comment]
Well removing enchantment descriptions mod seems to improve load time pretty dramatically already - so removing it may be a good thing even if it doesn't fix the problem xD

And to report on whether it fixed it by removing it, no, unfortunately it did not :(

Thanks for trying to help though! Appreciate it :)

**Comment by ghost** [comment]
I believe it is now time to start halving mods... will let you all know what I discover... lol

**Comment by ghost** [comment]
I have now narrowed it down to 5 mods, 
Tesseract Mod
SilentMechanisms
SimplyJetpacks
Sophisticated Backpacks
and Super Multi Drills

**Comment by ghost** [comment]
It is
SuperMultiDrills mod

**Comment by ghost** [comment]
Would it be possible for JEI to implement something that can skip over a mod that has broken tags, or whatever this issue is caused by? 

`"Tag supermultidrills:drill_batteries used before it was bound"`

Maybe can't fix the mods that error, but maybe can keep JEI alive despite it

**Comment by ghost** [comment]
Well, back to square one, in the last reimplementation of mods I had removed, another mod does also break JEI lol - I suspect apotheosis is doing so.

**Comment by ghost** [comment]
Update: Apotheosis also caused the same issue, removing it + supermultidrill == resolution, for now.

I will leave the issue open in case JEI devs think they can prevent JEI's problems caused by the other mods' errors.
