### ISSUE TITLE
Minecraft crash when i try to load a world with JEI

### ISSUE THREAD

**Issue by emanuelepro25** [mezz/JustEnoughItems#2218]
when i try to load an old or a new world the loading process goes until 100% then minecraft crash without giving me crash log or report

**Comment by Tahakk** [comment]
How about providing versions of JEI, Minecraft, Forge and Java. At the same time you could upload `latest.log`

**Comment by HankWRLD999** [comment]
everytime i try to launch a world with JEI when it gets to "saving world" the app crashes/closes but everytime i remove the mod from the mod folder it works fine but when i put back in it doesn't work. idk if it's because i ran out of storage or i have too much mods

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
