### ISSUE TITLE
JEI does not appear on multiplayer with Apotheosis + Autumnity installed

### ISSUE THREAD

**Issue by zachsai** [mezz/JustEnoughItems#2219]
Autumnity 2.0.1
Apotheosis 4.4.1
JEI 7.6.1.65
Forge: 36.0.1
Jei does not appear when joining a multiplayer after booting up the game. I have to do /reload in game for it to appear, which would not be possible for players without cheats/op on the server.
Thanks

**Comment by Shorepion** [comment]
Try to add FastWorkbench to your modpack. This fixed it for me.
