### ISSUE TITLE
JEI Crash 1.9 Release-169 

### ISSUE THREAD

**Issue by Nbenito** [mezz/JustEnoughItems#222]
I downloaded 1.9 Forge: 12.16.0.1807 and when I try to launch the game it gives the title screen and a few seconds later is crashes. it is the latest release version from the launcher as of this report.

link: https://gist.github.com/Nbenito/f93f704f2c2e4d2f7858

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the latest beta version of JEI on Cursefoge. Forge 1.9 made some breaking changes.
