### ISSUE TITLE
(JEI MC 1.16.5 Request)

### ISSUE THREAD

**Issue by LANCECRAFT1104** [mezz/JustEnoughItems#2221]
Add MC 1.16.5 I need it...

**Comment by Eric-01** [comment]
99% of Forge mods for 1.16.4 are compatible with 1.16.5 as well. Just download them, and check it out :)

However, I agree that for now Mezz could mark at least the latest version of JEI as compatible with 1.16.5 to reduce confusion, but that's totally up to him.

**Comment by Eric-01** [comment]
99% of Forge mods for 1.16.4 are compatible with 1.16.5 as well. Just download them, and check it out :)

However, I agree that for now Mezz could mark at least the latest version of JEI as 1.16.5 compatible to reduce confusion, but that's totally up to him.
