### ISSUE TITLE
Using 1.16.4 Love this mod but I am am receiving this msg when I click the wrench icon. Install FTB GUI Library to access ingame config.   Thank you

### ISSUE THREAD

**Issue by PoppetMcStuffins** [mezz/JustEnoughItems#2222]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Eric-01** [comment]
So why don't you do what it tells you and install the FTB GUI library or (better) use MrCrayfish's Configured mod instead?

**Comment by elzocko64** [comment]
👎

**Comment by mezz** [comment]
Thanks for the report!
I have removed support for FTB Library and now recommend installing the Configured mod to configure mods in-game. Sorry, I wish this was built into Forge like in previous versions.
