### ISSUE TITLE
Enchantment book not found using its name

### ISSUE THREAD

**Issue by Crimix** [mezz/JustEnoughItems#2223]
I am developing a new mod with only a single enchantment.

I am experiencing a odd issue, when I search for my enchantment books named Knowledge Drop using both the start of both words it is not found.
But in my dev environment if the enchantment does not have a localized name it is found using both.
The mod id is the same name as the enchantment, so it is found if I type `@know` but not if I only type `know`.
I have published the mod here [Knowledge Drop](https://www.curseforge.com/minecraft/mc-mods/knowledge-drop) if it helps in testing.
The same also happens outside dev environment.

Mod id: knowledgedrop
Enchantment register name: knowledgedrop:knowledge_drop
Enchantment translated name: Knowledge Drop

Minecraft Version (Dev): 1.16.3
Minecraft Version (Non-dev): 1.16.4
Forge Version (Dev): 34.1.32
Forge Version (Non-dev):35.1.0
JEI Version (Dev): 1.16.3:7.6.0.49
JEI Version (Non-dev): 1.16.4.7.6.1.65

**Comment by mezz** [comment]
Sorry for the late deploy. If you still have this issue, please join the discord to get quick help with development issues: https://discord.gg/sCQcWU2
