### ISSUE TITLE
Stick drops not reported from leaves

### ISSUE THREAD

**Issue by DoomRater** [mezz/JustEnoughItems#2225]
Leaves occasionally drop sticks, but looking up recipes for sticks doesn't display this information anywhere. This change occurred in Minecraft 1.14.

**Comment by Eric-01** [comment]
JEI's purpose is to show recipes (crafting, smelting, brewing, stonecutting, etc.), not item/block/mob drops. Unless I'm wrong ;)

**Comment by Eric-01** [comment]
JEI's purpose is to show recipes (crafting, smelting, stonecutting, etc.), not item/block/mob drops. Unless I'm wrong ;)

**Comment by DoomRater** [comment]
A recipe is where items come from and where items go to.  Evidence?  Hit R on a Concrete Block.  It is impossible to make one unless you put concrete powder next to water, yet this is documented.  That's not a crafting recipe, a smelting recipe, or anything to do with stonecutting, banner making, or composting.

**Comment by Ocelot5836** [comment]
Base JEI does not document creating concrete from concrete powder. That might be from an add-on mod of some sort.

**Comment by MelanX** [comment]
I would say it’s Just Enough Resources
