### ISSUE TITLE
JEI adding invalid space between item id and nbt in /give

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#2228]
**JEI version:** [1.16.4-7.6.1.65](https://www.curseforge.com/minecraft/mc-mods/jei/files/3157864)

When using give mode in JEI, it is adding an invalid space between item id and nbt, resulting in the following command
```
/give HeckinChloe minecraft:lingering_potion {Potion:"minecraft:long_water_breathing"} 1
```
producing the following message:
```
Expected integer
...ng_potion {Potion:"minecraft:long_water_breathing"} 1<--[HERE]
```

Typing the following actually gives the item:
```diff
- /give HeckinChloe minecraft:lingering_potion {Potion:"minecraft:long_water_breathing"} 1
+ /give HeckinChloe minecraft:lingering_potion{Potion:"minecraft:long_water_breathing"} 1
```

The problematic implementation can be found here:
https://github.com/mezz/JustEnoughItems/blob/fb0edcbd6ca13cb361d684e6d9bdb335d0c51dd9/src/main/java/mezz/jei/util/CommandUtil.java#L96
A solution could be to join id and nbt before passing it to this method

**Comment by mezz** [comment]
Thanks for the report!
Do you know which version this syntax started in? I may need to backport a fix to some older versions.

**Comment by ChloeDawn** [comment]
I believe it was introduced in the switch to Brigadier? https://minecraft.gamepedia.com/Argument_types#item_stack
