### ISSUE TITLE
Works in creative, not survival

### ISSUE THREAD

**Issue by k4tie3** [mezz/JustEnoughItems#2229]
I had only this mod downloaded and it worked fine in creative mode.  When I go into survival it doesn't work, so I think I uninstalled it and tried again.  When I looked for a "configure JEI" thing after installed again, it said in Minecraft I should/ need to download "FTB GUI Library Mod".  
I downloaded that but then in the game when you load up a mod before playing, Minecraft said I needed "Architectury."  I did some searching and I downloaded "Minecraft architectury API mod."  
So I then had all three of those mods and my final problem is that in survival mode still, at the bottom right when I click inventory I hover over a wrench/settings looking icon at the bottom right and it says, "There is not enough space to display JEI here." 

Can anyone help with this?

**Comment by k4tie3** [comment]
hey if anyone had this same problem, what I did was make my gui scale smaller (mine is at 3 now) and it works fine.  :)

**Comment by oddsoul** [comment]
Also can confirm this is the case. not sure why auto isn't picking up the JEI
