### ISSUE TITLE
Menu not showing 1.16.3

### ISSUE THREAD

**Issue by ChaoticDusk** [mezz/JustEnoughItems#2230]
I'm playing in 1.16.3 and for some reason the menu will no longer show up when it has in the past. I don't quite know if it's because of the other mods I have since I haven't had issues in the past but whenever I go into my inventory the menu never shows up. I've tried to see it any of the controls might fix it and nothing I tried did so I don't really know what to do. IS anyone else having or had this problem? Anyone know how to fix it? any help would be appreciated.

**Comment by cech12** [comment]
Which versions do you use exactly (Forge, JEI)? Can you send an error log? Did you test it without any other mod?

**Comment by ChaoticDusk** [comment]
I messed around with the versions a bit and eventually got it working.
