### ISSUE TITLE
[1.16.5] JEI menu does not display

### ISSUE THREAD

**Issue by WenXin20** [mezz/JustEnoughItems#2231]
`Minecraft v1.16.5`
`Forge v36.0.7`
`JEI v7.6.1.66`

After updating JEI, the menu did not display on my screen when connected to my server. The issue seems to be related to tags. The error in the log is on line 5363.
[Error Log](https://gist.github.com/WenXin20/46d369a9f332f329e748d984135c2959#file-latest-log-L5363)

**Comment by mezz** [comment]
Thanks for the report!
If another mod is crashing the tag loading process at startup with a bad tag, the event that fires at the end of the loading will not be fired. JEI listens for that event to know when to start, so it will not get the event and will not start in this case.

**Comment by WenXin20** [comment]
Ah, well, at this point my modpack has changed and I am no longer seeing this error. Also kinda forgot about this.
