### ISSUE TITLE
Update Curse page to 1.16

### ISSUE THREAD

**Issue by Guanran928** [mezz/JustEnoughItems#2235]
Hey!
I just saw JEI in curseforge shows it for the 1.12.2 version on the description.
Please update it to 1.16.4 :D

*I am not sure is a dupe because I don't know how to search on the issue page but at least I reported it :>

**Comment by cech12** [comment]
This value is related to the latest release upload. All uploads for later Minecraft versions are marked as alpha or beta. ^^
