### ISSUE TITLE
[1.16.4] Move Items button closes inventory. 

### ISSUE THREAD

**Issue by CrossVas** [mezz/JustEnoughItems#2236]
Minecraft version: 1.16.4;
Forge version: 35.1.37;
JEI version: 1.16.4-7.6.1.70

![rec_1](https://user-images.githubusercontent.com/25727222/106944269-0c27f080-672f-11eb-9e3c-90e9d1ed2f5c.gif)

**Comment by mezz** [comment]
Thanks for the report!

@Ocelot5836 I think this is related to your changes here: https://github.com/mezz/JustEnoughItems/pull/2216
Can you try to reproduce this issue?

**Comment by mezz** [comment]
Fixed in version .71
