### ISSUE TITLE
Dragging items in a crafting table still can click the arrow "display recipes"

### ISSUE THREAD

**Issue by realcatgirly** [mezz/JustEnoughItems#2239]
When I drag items with any mouse button and I land on the arrow in the crafting table "show recipes" that display all recipes, it still opens that page, making my crafting disappear and I have to exit the crafting table to drop the items. When crafting quickly it happens quickly and can be really annoying. Also there's a bug when I disable the official recipe bug, it still clicks the arrow. A video will be attached.

https://user-images.githubusercontent.com/12198004/107216522-2c94cb00-6a0d-11eb-81ef-bfdefe2404cb.mp4

**Comment by Fireztonez** [comment]
Yeah, this appen to me a lot with JEI for Minecraft 1.16.x. I don't remember to have that issue before, on Minecraft 1.12.2.

If you can't find a way to avoid the recipe page to open when draging objects little off from the crafting table slot, I think adding an option to simply disable that arrow for the crafting table vanilla will be great.

By the way sincerely, I never clicked on the arrow of the craft vanilla table on purpose. I think it's just completely unnecessary to have a similar link allowing you to see all the thousands of existing recipes in a modpacks one by one, when you can see exactly the recipe you need with JEI pretty fast.

**Comment by mezz** [comment]
This is a legacy from NEI and not a great user experience.
There is probably a better way to do this, more built into the JEI part of the screen.

**Comment by lukiono** [comment]
How about a config option to disable this arrow behaviour?

**Comment by mezz** [comment]
Can you please try with the latest version of JEI?
I have changed click handling so that to click anything in JEI, you must click down and release on the same area to have it count. That may help prevent misclicks on areas like this, since it takes a more deliberate click-and-release to activate it.

**Comment by mezz** [comment]
I think this has been resolved.
