### ISSUE TITLE
Crash starting on Forge 1809

### ISSUE THREAD

**Issue by kwpugh** [mezz/JustEnoughItems#224]
Thank you for reporting!

If there is an issue:
- It may already be fixed, please try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files).
- If JEI crashed, please paste the crash log to [gist](https://gist.github.com/) and link it in this issue.

Crash report:  http://pastebin.com/raw/FA5hkCUJ

**Comment by GirafiStudios** [comment]
You're not on the latest version..
And please read the template before you report a crash (Which you haven't event borthered to remove?)

**Comment by raoulvdberge** [comment]
I'm also having this crash, on Forge >= 1805.

**Comment by way2muchnoise** [comment]
http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2289386

If you want to use forge 1805+ use JEI 3.1.0+

**Comment by raoulvdberge** [comment]
I _am_ using JEI 3.1.0+

```
dependencies {
    deobfCompile "mezz.jei:jei_1.9:3.1.+"
}
```

**Comment by way2muchnoise** [comment]
Crash log?

**Comment by kwpugh** [comment]
I'm using jei_1.9-3.1.0.170.jar on forge 1811 and it seems to work fine there.

**Comment by raoulvdberge** [comment]
Nevermind, this was a Gradle caching issue...

**Comment by GirafiStudios** [comment]
@kwpugh in that case, please close the issue.

**Comment by kwpugh** [comment]
Nothing to moving along....

**Comment by mezz** [comment]
duplicates https://github.com/mezz/JustEnoughItems/issues/222
