### ISSUE TITLE
Cant find config mod (JEI) mc. 1.16.5 forge- 36.0.13

### ISSUE THREAD

**Issue by oli0076** [mezz/JustEnoughItems#2242]
Thank you for reporting!
I am unable to find the correct config mod for JEI

**Comment by CreatorCobalt** [comment]
I 

> Thank you for reporting!
> I am unable to find the correct config mod for JEI

I am also not able to find the right config mod. I can't find a way to activate cheat mode to grab items.

**Comment by DMG1727** [comment]
you need the FTB GUI Library
https://www.curseforge.com/minecraft/mc-mods/ftb-gui-library
