### ISSUE TITLE
Los crafteos y su uso no se muestran en las versiones 1.12.2

### ISSUE THREAD

**Issue by wilbertwolf** [mezz/JustEnoughItems#2244]
buenos dias OwO

solo vengo ha informales que en las versiones de jei 1.12.2 no me enseña los crafteos de los objetos, ejemplo:

si quiero ver como se craftea una mesa de craftear y para que se usa los normal es que le de a la R para ver el crafteo y a la U para ver su uso pero eso no pasa y no aparece ni el crafteo ni para que se usa TwT.

eh intentado ver si es una falla en la configuracion de la llave pero no funciona hasta me intente descargar una version mas antigua y no funciona.

espero que me respondan y me puedan ayudar QwQ.

**Comment by Dhantrex** [comment]
Lo mismo me pasa a mi no me aparecen los crafteos de los objetos estoy con mods y nada se me muestra ni del minecraft vanilla
