### ISSUE TITLE
does it work on 1.16.5?

### ISSUE THREAD

**Issue by BakwanHybrid** [mezz/JustEnoughItems#2245]
the mod is for 1.16.4 but my minecraft version is 1.16.5

**Comment by shoodidagen** [comment]
It works for me on 1.16.5 however as soon as i try to use it with a server (Linux) it dissapears (investigating now).
Single Player 1.16.5 looks good to me (I cant comment on Windows based servers)

**Comment by mezz** [comment]
Closing this issue because there are 1.16.5 versions now
