### ISSUE TITLE
Performance/FPS Dips while in menus ,chest, crafting tables, etc..

### ISSUE THREAD

**Issue by DMG1727** [mezz/JustEnoughItems#2246]
So I'm not sure what's causing this issue but whenever I open my inventory with JEI I get a massive FPS dip (go from 120+ with shaders to 30 or less, ill attach screenshots without and with shaders showing fps). Something I forgot to include is that I'm playing on 1.16.5

Things I've tried 
1. Trying different versions of forge
2. Trying different versions of JEI
3. Having only JEI and the GUI installed 
4. Increasing ram amount

None of these things seemed to fix the issue. the weird thing is that I've played on 1.12 with JEI and it was fine.

PC Specs
Ryzen 3700x
32gb 3200 ram
2080 super

![2021-02-22_13 08 50](https://user-images.githubusercontent.com/32829585/108771067-f593de80-750f-11eb-8609-e44b1ea0fd49.png)
![2021-02-22_13 08 57](https://user-images.githubusercontent.com/32829585/108771084-fb89bf80-750f-11eb-89f8-f8ce22661e58.png)
![2021-02-22_13 17 19](https://user-images.githubusercontent.com/32829585/108771339-60451a00-7510-11eb-89e3-043497e20b3b.png)
![2021-02-22_13 17 28](https://user-images.githubusercontent.com/32829585/108771354-6509ce00-7510-11eb-80b7-b8ea01c29139.png)

If this has been covered before I am sorry for posting repeating stuff I just cant find a solution. also if the format of this is garbage I'm sorry I don't make posts I just try and look for the solution before I post. Thanks for the help with this problem!

**Comment by Ommina** [comment]
See #2030

**Comment by DMG1727** [comment]
Thanks
