### ISSUE TITLE
Crash while loading singleplayer world

### ISSUE THREAD

**Issue by Gbear17** [mezz/JustEnoughItems#225]
I have just updated to Forge 1811 with JourneyMap, ChunkIndicator, and JEI.
https://bitbucket.org/TeamJM/journeymap/issues/40/illegalaccesserror-in
[crash-2016-03-26_07.27.42-server.txt](https://github.com/mezz/JustEnoughItems/files/190559/crash-2016-03-26_07.27.42-server.txt)

**Comment by way2muchnoise** [comment]
Did you try the latest version of all of those mods? Cause there are some major changes in forge since 1805.

**Comment by Gbear17** [comment]
~~Did you read my comment?~~ I am using Forge 1811, with all the updated versions of those mods as of 42 minutes ago.

**Comment by AEnterprise** [comment]
@Gbear17 you didn't say they where all up to date, also a without a crashlog this is hard to trace and fix so can you provide one?

**Comment by way2muchnoise** [comment]
Provide a log and  try each mod on their own. Who says the issues is with JEI?

**Comment by Gbear17** [comment]
You're right @AEnterprise I did not provide a crash log... My bad;
[crash-2016-03-26_07.27.42-server.txt](https://github.com/mezz/JustEnoughItems/files/190559/crash-2016-03-26_07.27.42-server.txt)

Everything, Forge 1811, ChunkIndicator, and JourneyMap, worked just fine w/out JEI. Before I installed JEI I already had everything else and was using them and had no problems.

**Comment by way2muchnoise** [comment]
`java.lang.IllegalAccessError: tried to access field net.minecraftforge.event.entity.EntityEvent.entity from class journeymap.client.network.WorldInfoHandler`

It seems like it is JEI for sure....  Do people even read before posting.

**Comment by Gbear17** [comment]
@way2muchnoise How do you know it is JEI? Or are you being sarcastic, its hard to tell from text -_-

**Comment by way2muchnoise** [comment]
**journeymap**`.client.network.WorldInfoHandler`

You don't need to know anything about coding to open the log and read the first like ten lines. It says the words `from class journeymap.`....

It could be some weird mod interaction issue but since it is journeymap crashing you might want to post it there first.

**Comment by Gbear17** [comment]
I have posted there, and here, because obviously JEI is part of the problem, if JEI wasn't part of the problem it would have worked fine.

**Comment by way2muchnoise** [comment]
Ok, I'm sorry for lashing out then. You should have included that information from the start next time. Also you might want to link the other issue so we can read up on changes there.

**Comment by Gbear17** [comment]
First comment.

**Comment by Prospector** [comment]
> I have just updated to Forge 1811 with JourneyMap, ChunkIndicator, and JEI.

Perhaps you worded it poorly, but to me it sounds like you updated JourneyMap which is what is causing this issue.

**Comment by mezz** [comment]
Thanks for the report!
Be nice everyone -_-.

Forge 1805 broke everything, mods that are not updated past that version will not work at all. In this case, the crash log indicates that JourneyMap needs to update.
