### ISSUE TITLE
I can't add recipe on crafting table

### ISSUE THREAD

**Issue by Patronelli** [mezz/JustEnoughItems#2251]
Minecraft: 1.16.5
Forge: 1.16.5-36.0.15
JEI: 1.16.4-7.6.1.70

When i click "plus" on a recipe to add items on crafting table nothing is happening.

**Comment by kaancl3344** [comment]
I have the same issiue. Did u fix it yours ?

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
