### ISSUE TITLE
[1.16.4] Recipes for items with a potion attached (e.g. tipped arrow) display even when removed through a datapack

### ISSUE THREAD

**Issue by IchHabeHunger54** [mezz/JustEnoughItems#2253]
Minecraft 1.16.4, Forge 35.1.37, JEI 7.6.1.171, Singleplayer

I removed the recipe for tipped arrows through a datapack:
![2021-02-27_00 39 31](https://user-images.githubusercontent.com/52419336/109366936-05574e00-7895-11eb-9a1d-1fee55c56f43.png)
(It can also be noted that the night vision arrow has also been hidden from the item list.)

Yet, in both the Uses of the Lingering Potion and the "Show All Recipes" view, this recipe still appears:
![2021-02-27_00 46 06](https://user-images.githubusercontent.com/52419336/109367074-65e68b00-7895-11eb-8c33-df27da1169ad.png)
![2021-02-27_00 48 00](https://user-images.githubusercontent.com/52419336/109367090-73037a00-7895-11eb-902a-8ef068bb6bda.png)
This applies to all other tipped arrows as well. The recipe for the Uncraftable Arrow (potion minecraft:empty) appears on any lingering potion usage and once in the Show All Recipes view.

This behavior also applies to modded items that are distinguished by their potion NBT. In my pack, I have Reliquary (https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3) installed. Just like with the tipped arrow, I removed the crafting recipe (special crafting serializer, obviously based on the vanilla tipped arrow) through a datapack and I am getting the same issue, with the only difference being that the Uncraftable Potion doesn't show up this time. (I didn't screenshot it, but both of the below also appear in the All Recipes view, alongside all the other potion types.)
![2021-02-27_01 02 00](https://user-images.githubusercontent.com/52419336/109367864-96c7bf80-7897-11eb-803e-a550cded06e3.png)
![2021-02-27_00 57 31](https://user-images.githubusercontent.com/52419336/109367605-cde9a100-7896-11eb-9747-59c8a4d2ae60.png)
![2021-02-27_00 57 34](https://user-images.githubusercontent.com/52419336/109367657-fa052200-7896-11eb-8c48-5750f4a2529c.png)
![2021-02-27_01 02 08](https://user-images.githubusercontent.com/52419336/109367878-9c250a00-7897-11eb-93db-0769bf12c803.png)
![2021-02-27_00 57 35](https://user-images.githubusercontent.com/52419336/109367660-fd001280-7896-11eb-9339-609597101aab.png)
![2021-02-27_00 57 37](https://user-images.githubusercontent.com/52419336/109367664-fffb0300-7896-11eb-80aa-67a4dbcbd3fa.png)
If you have any questions left, feel free to ask. Looking forward to a soon fix!

**Comment by IchHabeHunger54** [comment]
Occurs in any 1.16.5 version aswell.

**Comment by copygirl** [comment]
Just want to note this also occurs to me with a modpack I'm working on where I remove all recipes with KubeJS. When looking at all crafting recipes, the tipped arrow and shulker box dyeing recipes take up most of the pages.

**Comment by mezz** [comment]
Thanks for the report! 
This should be fixed in the latest version of JEI for 1.16 and 1.17, please let me know if you have any more issues.
