### ISSUE TITLE
When i open a jei recipe it crashed my gane

### ISSUE THREAD

**Issue by Tornadozzz12** [mezz/JustEnoughItems#2254]
So i am clueless when it comes to coding and stuff and i was hoping someone could tell me why everytime i try to look at and items recipe it crashes my game, i play on a modpack called BOMBS, GUNS AND WAR.
 im not entierly sure what is needed so i will copy and paste it all

---- Minecraft Crash Report ----
// Don't do that.

Time: 2/26/21 9:36 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.hbm.inventory.RecipesCommon$ComparableStack.hashCode(RecipesCommon.java:107)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.putMapEntries(HashMap.java:514)
	at java.util.HashMap.<init>(HashMap.java:489)
	at com.hbm.inventory.ShredderRecipes.getShredderRecipes(ShredderRecipes.java:209)
	at com.hbm.handler.nei.ShredderRecipeHandler.loadCraftingRecipes(ShredderRecipeHandler.java:97)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
	at com.hbm.handler.nei.ShredderRecipeHandler.loadCraftingRecipes(ShredderRecipeHandler.java:91)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.inventory.RecipesCommon$ComparableStack.hashCode(RecipesCommon.java:107)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.putMapEntries(HashMap.java:514)
	at java.util.HashMap.<init>(HashMap.java:489)
	at com.hbm.inventory.ShredderRecipes.getShredderRecipes(ShredderRecipes.java:209)
	at com.hbm.handler.nei.ShredderRecipeHandler.loadCraftingRecipes(ShredderRecipeHandler.java:97)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
	at com.hbm.handler.nei.ShredderRecipeHandler.loadCraftingRecipes(ShredderRecipeHandler.java:91)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)

-- Affected screen --
Details:
	Screen name: com.rikmuld.camping.client.gui.GuiCampinginv

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['tornadozzz'/2808, l='MpServer', x=1362.16, y=65.62, z=-127.50], MCH_ViewEntityDummy['McHeliDummyEntity'/255, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Chunk stats: MultiplayerChunkCache: 433, 433
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (248,64,256), Chunk: (at 8,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 297337 game time, 63436 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 109 total; [EntityPig['Pig'/2816, l='MpServer', x=1369.16, y=69.00, z=-140.50], EntityCreeper['Creeper'/12544, l='MpServer', x=1330.50, y=63.00, z=-121.50], EntityPig['Pig'/2817, l='MpServer', x=1378.03, y=65.00, z=-117.13], EntityCreeper['Creeper'/12545, l='MpServer', x=1331.50, y=63.00, z=-120.50], EntitySheep['Sheep'/2819, l='MpServer', x=1357.50, y=64.00, z=-111.13], EntitySheep['Sheep'/2820, l='MpServer', x=1338.63, y=63.00, z=-149.47], EntitySheep['Sheep'/2821, l='MpServer', x=1397.03, y=68.00, z=-150.97], EntityBat['Bat'/11525, l='MpServer', x=1317.63, y=40.10, z=-126.59], EntityPig['Pig'/2822, l='MpServer', x=1375.50, y=78.00, z=-157.50], EntityBat['Bat'/11526, l='MpServer', x=1314.13, y=38.10, z=-116.50], EntitySheep['Sheep'/2823, l='MpServer', x=1403.34, y=71.00, z=-121.88], EntitySheep['Sheep'/2824, l='MpServer', x=1407.22, y=73.00, z=-125.59], EntitySheep['Sheep'/2825, l='MpServer', x=1405.25, y=73.00, z=-123.13], EntitySheep['Sheep'/2826, l='MpServer', x=1400.03, y=76.00, z=-112.91], EntityMinecartChest['entity.MinecartChest.name'/2831, l='MpServer', x=1345.50, y=33.50, z=-148.50], EntityMinecartChest['entity.MinecartChest.name'/2832, l='MpServer', x=1348.50, y=33.50, z=-146.50], EntityPig['Pig'/2834, l='MpServer', x=1375.84, y=68.00, z=-159.53], EntityPig['Pig'/2835, l='MpServer', x=1377.53, y=83.00, z=-156.47], EntitySkeleton['Skeleton'/12563, l='MpServer', x=1382.50, y=69.00, z=-185.94], EntityPig['Pig'/2836, l='MpServer', x=1366.47, y=67.00, z=-140.91], EntitySheep['Sheep'/2837, l='MpServer', x=1398.84, y=69.00, z=-137.88], EntitySheep['Sheep'/2838, l='MpServer', x=1397.03, y=64.00, z=-128.06], EntitySheep['Sheep'/2839, l='MpServer', x=1407.13, y=68.00, z=-140.94], EntitySheep['Sheep'/2840, l='MpServer', x=1407.09, y=70.00, z=-133.47], EntitySheep['Sheep'/2841, l='MpServer', x=1399.66, y=71.00, z=-117.50], EntitySheep['Sheep'/2843, l='MpServer', x=1329.81, y=63.00, z=-136.91], EntityPig['Pig'/2844, l='MpServer', x=1395.78, y=73.00, z=-155.66], EntityCreeper['Creeper'/11036, l='MpServer', x=1304.50, y=64.00, z=-166.50], EntityPig['Pig'/2845, l='MpServer', x=1395.47, y=70.00, z=-159.53], EntityPig['Pig'/2846, l='MpServer', x=1398.50, y=67.00, z=-150.69], EntityCow['Cow'/2847, l='MpServer', x=1406.91, y=76.00, z=-81.97], EntityClientPlayerMP['tornadozzz'/2808, l='MpServer', x=1362.16, y=65.62, z=-127.50], EntitySheep['Sheep'/2850, l='MpServer', x=1364.50, y=71.00, z=-175.50], EntitySpider['Spider'/12066, l='MpServer', x=1431.50, y=64.00, z=-155.50], EntitySheep['Sheep'/2851, l='MpServer', x=1367.88, y=82.00, z=-166.94], EntitySheep['Sheep'/2852, l='MpServer', x=1367.84, y=77.00, z=-172.81], EntitySpider['Spider'/10533, l='MpServer', x=1289.50, y=38.00, z=-137.50], EntitySkeleton['Skeleton'/12585, l='MpServer', x=1359.50, y=15.00, z=-69.50], EntityEnderman['Enderman'/12074, l='MpServer', x=1364.50, y=20.00, z=-189.44], EntitySkeleton['Skeleton'/12586, l='MpServer', x=1354.50, y=15.00, z=-66.50], EntityBat['Bat'/12333, l='MpServer', x=1405.93, y=33.00, z=-122.02], EntitySpider['Spider'/12590, l='MpServer', x=1302.50, y=72.00, z=-131.50], EntitySkeleton['Skeleton'/12082, l='MpServer', x=1405.50, y=76.00, z=-82.50], EntitySheep['Sheep'/2867, l='MpServer', x=1414.47, y=77.00, z=-133.34], EntityPig['Pig'/2868, l='MpServer', x=1406.84, y=64.00, z=-165.84], EntitySkeleton['Skeleton'/12084, l='MpServer', x=1406.50, y=76.00, z=-86.50], EntityCow['Cow'/2869, l='MpServer', x=1415.78, y=76.00, z=-87.22], EntityCow['Cow'/2870, l='MpServer', x=1418.72, y=75.00, z=-76.25], EntitySheep['Sheep'/2872, l='MpServer', x=1297.59, y=66.00, z=-112.03], EntitySheep['Sheep'/2873, l='MpServer', x=1363.50, y=67.00, z=-176.50], EntityZombie['Zombie'/10810, l='MpServer', x=1376.50, y=17.00, z=-179.50], EntitySheep['Sheep'/2877, l='MpServer', x=1306.84, y=63.00, z=-104.78], EntitySpider['Spider'/10813, l='MpServer', x=1373.41, y=17.00, z=-180.75], EntitySheep['Sheep'/2878, l='MpServer', x=1300.19, y=64.00, z=-109.53], EntityCreeper['Creeper'/11840, l='MpServer', x=1403.50, y=65.00, z=-163.50], EntityTrail['unknown'/322, l='MpServer', x=1362.16, y=65.62, z=-127.50], EntityCreeper['Creeper'/12101, l='MpServer', x=1417.50, y=49.00, z=-188.50], EntityCow['Cow'/2886, l='MpServer', x=1416.06, y=76.00, z=-80.84], EntityPig['Pig'/2887, l='MpServer', x=1398.28, y=71.00, z=-182.50], EntityPig['Pig'/2888, l='MpServer', x=1402.50, y=71.00, z=-185.78], EntitySheep['Sheep'/2889, l='MpServer', x=1287.03, y=68.00, z=-124.97], EntitySpider['Spider'/10827, l='MpServer', x=1322.50, y=70.00, z=-198.50], EntityZombie['Zombie'/9551, l='MpServer', x=1289.34, y=38.00, z=-169.66], EntityZombie['Zombie'/12112, l='MpServer', x=1384.50, y=74.00, z=-104.50], EntityPig['Pig'/2903, l='MpServer', x=1406.72, y=67.00, z=-197.63], EntityPig['Pig'/2904, l='MpServer', x=1399.50, y=68.00, z=-196.97], EntityZombie['Zombie'/12378, l='MpServer', x=1349.44, y=78.00, z=-169.91], EntityZombie['Zombie'/12379, l='MpServer', x=1339.50, y=78.00, z=-165.50], EntityCreeper['Creeper'/12128, l='MpServer', x=1363.50, y=69.00, z=-77.50], EntitySpider['Spider'/12129, l='MpServer', x=1316.44, y=71.00, z=-160.75], EntitySkeleton['Skeleton'/12647, l='MpServer', x=1396.50, y=29.00, z=-151.50], EntitySkeleton['Skeleton'/12648, l='MpServer', x=1396.50, y=29.00, z=-152.50], EntityMinecartChest['entity.MinecartChest.name'/2927, l='MpServer', x=1339.50, y=36.50, z=-209.50], EntitySkeleton['Skeleton'/12660, l='MpServer', x=1423.54, y=45.00, z=-156.50], EntitySkeleton['Skeleton'/12661, l='MpServer', x=1424.96, y=45.00, z=-158.08], EntitySpider['Spider'/12663, l='MpServer', x=1426.21, y=45.00, z=-157.78], EntityZombie['Zombie'/10109, l='MpServer', x=1399.50, y=29.00, z=-116.50], EntityZombie['Zombie'/12669, l='MpServer', x=1293.50, y=13.00, z=-90.50], EntityZombie['Zombie'/12670, l='MpServer', x=1294.50, y=13.00, z=-92.50], EntitySkeleton['Skeleton'/11143, l='MpServer', x=1327.50, y=36.00, z=-172.50], EntitySkeleton['Skeleton'/11144, l='MpServer', x=1329.50, y=36.00, z=-172.50], EntityMinecartChest['entity.MinecartChest.name'/2955, l='MpServer', x=1311.50, y=38.50, z=-208.50], EntityZombie['Zombie'/11147, l='MpServer', x=1323.66, y=36.00, z=-173.16], EntityMinecartChest['entity.MinecartChest.name'/2956, l='MpServer', x=1306.50, y=38.50, z=-208.50], EntityZombie['Zombie'/11148, l='MpServer', x=1328.50, y=36.00, z=-172.50], EntityBat['Bat'/12442, l='MpServer', x=1288.25, y=58.10, z=-105.25], EntityZombie['Zombie'/12203, l='MpServer', x=1423.50, y=83.00, z=-133.50], EntityCreeper['Creeper'/12207, l='MpServer', x=1362.50, y=17.00, z=-54.50], EntityZombie['Zombie'/11971, l='MpServer', x=1373.50, y=67.00, z=-97.50], EntitySkeleton['Skeleton'/11973, l='MpServer', x=1316.50, y=25.00, z=-49.25], EntityBat['Bat'/11723, l='MpServer', x=1395.68, y=31.75, z=-119.96], EntityBat['Bat'/11724, l='MpServer', x=1386.84, y=24.82, z=-124.36], EntitySkeleton['Skeleton'/12236, l='MpServer', x=1292.94, y=18.00, z=-49.47], EntitySkeleton['Skeleton'/10703, l='MpServer', x=1322.50, y=35.00, z=-150.88], EntitySkeleton['Skeleton'/10704, l='MpServer', x=1323.50, y=39.00, z=-143.50], EntityCreeper['Creeper'/11984, l='MpServer', x=1405.50, y=19.00, z=-52.50], EntityEnderman['Enderman'/9169, l='MpServer', x=1357.31, y=22.00, z=-179.44], EntityCreeper['Creeper'/11985, l='MpServer', x=1407.50, y=19.00, z=-53.50], EntityCreeper['Creeper'/11986, l='MpServer', x=1408.50, y=19.00, z=-53.50], EntityCreeper['Creeper'/11475, l='MpServer', x=1392.50, y=69.00, z=-152.50], EntityCreeper['Creeper'/10481, l='MpServer', x=1422.50, y=76.00, z=-106.50], EntityCaveSpider['Cave Spider'/2041, l='MpServer', x=-32.45, y=-29.62, z=-31.69], EntitySheep['Sheep'/2812, l='MpServer', x=1352.38, y=64.00, z=-141.53], EntitySkeleton['Skeleton'/12540, l='MpServer', x=1320.50, y=63.00, z=-107.50], EntityPig['Pig'/2813, l='MpServer', x=1369.47, y=64.99, z=-136.50], EntitySkeleton['Skeleton'/12541, l='MpServer', x=1318.50, y=63.00, z=-108.50], EntitySheep['Sheep'/2814, l='MpServer', x=1352.19, y=64.00, z=-133.88], EntitySkeleton['Skeleton'/12542, l='MpServer', x=1322.50, y=63.00, z=-105.50], MCH_ViewEntityDummy['McHeliDummyEntity'/255, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1212880608 bytes (1156 MB) / 3084386304 bytes (2941 MB) up to 6710886400 bytes (6400 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7200m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCHIJA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJA	aiimprovements{0.0.1.19} [AI Improvements] (AIImprovements-1.7.10-0.0.1b19-dev.jar) 
	UCHIJA	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCHIJA	BBG{1.0.0} [BetterBedrockGen] (BBG-1.0.0.jar) 
	UCHIJA	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJA	BetterFoliage{2.0.17} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.17.jar) 
	UCHIJA	controlling{1.0.0} [Controlling] (Controlling-1.7.10-1.0.0.jar) 
	UCHIJA	craftingtweaks{1.0.88} [Crafting Tweaks] (craftingtweaks-mc1.7.10-1.0.88.jar) 
	UCHIJA	creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJA	fbp{2.4.1} [Fancy Block Particles] (FancyBlockParticles-1.7.x-2.4.1.jar) 
	UCHIJA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJA	hbm{1.0.27 BETA (3565)} [Hbm's Nuclear Tech] (hbm_1.0.27_X3565.jar) 
	UCHIJA	voltzengine{1.9.14.302} [Voltz Engine] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJA	icbm{2.15.4.497} [ICBM] (ICBM-1.7.10-2.15.4b497.jar) 
	UCHIJA	icbmclassic{2.16.2.205} [ICBM-Classic] (ICBM-classic-1.7.10-2.16.2b205.jar) 
	UCHIJA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJA	kleeslabs{1.0} [KleeSlabs] (kleeslabs-mc1.7.10-1.2.9.jar) 
	UCHIJA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJA	mcheli{1.0.4} [MC Helicopter] (mcheli) 
	UCHIJA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJA	mw{1.11.7.7} [Modern Warfare] (mw-1.11.7.7_mc1.7.10.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.0.jar) 
	UCHIJA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJA	notenoughIDs{1.4.3.4} [NotEnoughIDs] (NotEnoughIDs-1.4.3.4.jar) 
	UCHIJA	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UCHIJA	clearingblock{0.3} [ClearingBlock Mod] (Nuclear Bomb Mod 1.0v.jar) 
	UCHIJA	NuclearCraft{1.9g} [NuclearCraft] (NuclearCraft-1.9g--1.7.10.jar) 
	UCHIJA	parachutemod{1.7.10} [Parachute Mod] (parachutemod-1.7.10-2.5.6-01.jar) 
	UCHIJA	gunpowder{1.1} [Placeable Gunpowder] (PlaceableGunpowder-1.1.jar) 
	UCHIJA	portalblocks{0.0.0} [portalblocks] (Portal Blocks v1.0_1.7.10.jar) 
	UCHIJA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UCHIJA	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCHIJA	reccomplex{0.9.7.1.1} [Recurrent Complex] (RecurrentComplex-0.9.7.1.1.jar) 
	UCHIJA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJA	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c (1).jar) 
	UCHIJA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJA	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar) 
	UCHIJA	voltzenginemodcompat{1.9.14.302} [Voltz Engine Mod Compatibility Loader] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJA	voltzenginemodflag{1.9.14.302} [VoltzEngine mod protection, flag, and region system] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJA	warstuff{1.3} [WarStuff] (warstuff_mod_1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.40' Renderer: 'GeForce RTX 2060 SUPER/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by actuallyasmartname** [comment]
Try removing Not Enough Items.

**Comment by actuallyasmartname** [comment]
This is an error with NEI, not JEI. https://github.com/Chicken-Bones/NotEnoughItems
