### ISSUE TITLE
[Bug] CraftTweaker Create Automated Crafting recipes not visible in JEI

### ISSUE THREAD

**Issue by Kisutora** [mezz/JustEnoughItems#2257]
**Forge:** release 1.16.5-forge-36.0.43
**JEI:** [7.6.1.71](https://www.curseforge.com/minecraft/mc-mods/jei/files/3192904)
**CraftTweaker:** [7.1.0.135](https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3221310)
**Create:** [v0.3e](https://www.curseforge.com/minecraft/mc-mods/create/files/3167531)

When a Crafting Table recipe is added Create automatically generates an Automatic Shaped/Shapeless Crafting recipe for it.
However recipes added using CraftTweaker **do not** show their Automated Crafting recipes in JEI, but **do** work in-game.

**Here's an example recipe added using CraftTweaker:**
https://pastebin.com/EgCt5y3g
![javaw_5yjkN6DCuj](https://user-images.githubusercontent.com/22685232/109565980-e3a3d400-7aeb-11eb-802e-a711c48a028f.png)
Notice no Automated Shaped Crafting recipe visible, however the recipe works fine in-game.

**Here's an example of what it should look like:**
![image](https://user-images.githubusercontent.com/22685232/109565894-c66f0580-7aeb-11eb-9191-1cac042d1db5.png)

**Comment by mezz** [comment]
Thanks for the report!
Please report this to CraftTweaker: https://github.com/CraftTweaker/CraftTweaker/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
Jared probably has a better idea of how this works than I do.
