### ISSUE TITLE
jei_1.9-3.0.6.169 crashes client on startup using forge 1.9 build 1811

### ISSUE THREAD

**Issue by kreezxil** [mezz/JustEnoughItems#226]
fml latest: http://paste.ee/p/H6Mb2

crash report: http://paste.ee/p/dK88l

**Comment by way2muchnoise** [comment]
Use the [latest release](http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2289386) it fixes the issues with 1805+

**Comment by mezz** [comment]
Forge 1805+ has broken every mod, please update to the latest version.

Duplicates https://github.com/mezz/JustEnoughItems/issues/222
