### ISSUE TITLE
Are Legacy Versions being Removed?

### ISSUE THREAD

**Issue by KPTEXH** [mezz/JustEnoughItems#2261]
I was working on my modpack in Curse Forge today and was shocked to find that JEI 1.7.10 was no longer available. I thought it was a conflict, but I check my mods folder, and then curse, and then the JEI page on curse forge, and version 1.7.10 is simply not anywhere I can find as of today (I was working on this yesterday as well). Is this intentional?

**Comment by Ommina** [comment]
JEI was never available for 1.7.10 -- its first iteration (to my knowledge) was for 1.8 and is still available on CurseForge.

For 1.7.10 you almost certainly want NEI instead.
