### ISSUE TITLE
Same item from multiple mods not showing

### ISSUE THREAD

**Issue by xtcp** [mezz/JustEnoughItems#2268]
Hello,

I used to play ATM5 and the same item showed on the list once for each mod, for example "Diamond Dust" there was 3 or 4 versions from different mods and each showed their own way of crafting. On ATM6 when I go to JEI and search for "Diamond Dust", only the Thermal Series version appears, and only 3 ways of crafting that one. Versions like the Mekanism one don't show and even though I can craft it it does not appear in JEI.
Does anyone know if this is a bug or is there a setting in JEI for all the versions of the same item (from different mods) to appear?

JEI version: jei-1.16.4-7.6.1.71.jar
ATM6 version: 1.5.3b

Thank you in advance,
Best Regards

**Comment by Ommina** [comment]
Are you certain that the ATM developers have not intentionally hidden duplicate items?
