### ISSUE TITLE
"+" button missing in new version.

### ISSUE THREAD

**Issue by blockbreaker1361** [mezz/JustEnoughItems#227]
The + button is missing in the crafting station from tinkers with the newest version of JEI for 1.8.9. Here's a photo. http://imgur.com/zz8m23b
It's also missing from the vanilla crafting table.

**Comment by ramalott** [comment]
I also noticed that the "+" button was missing in all crafting interfaces. Currently using:
jei_1.8.9-2.28.11.179.jar
forge 1.8.9-11.15.1.1808

**Comment by VT-14** [comment]
Mine is present, but in the wrong spot.  It's to the top left of the crafting grid (next to the bottom, left arrow).  The red boxes for missing items are equally displaced more to the left.  Same version of JEI and Forge as ramalott.  Checked with Vanilla and Tinker's Construct Crafting Table/Station.

**Comment by mezz** [comment]
Thanks for the report! 
My mistake, just use the previous version for now.

**Comment by mezz** [comment]
jei_1.8.9-2.28.12.180 should work correctly, it'll be on Curse soon.

**Comment by blockbreaker1361** [comment]
Thanks for fixing it. Works great now. :)

**Comment by Hund** [comment]
It doesn't work for me. :( I tried version 2.28.12.180 and every version after that from Curseforge. I dont know when  it stopped working.

**Comment by mezz** [comment]
The [+] will be missing if you aren't in a gui that can handle it (like a crafting table) or if JEI is not on the server.

**Comment by Hund** [comment]
Oh, so it needs to be on the server as well? I removed it from the server after I saw something on the server console about JEI disbled itself due to running on a server.

**Comment by mezz** [comment]
It was probably a message from an addon, JEI on the server helps with recipe transfer, item cheating, and a couple other minor things.

**Comment by Hund** [comment]
Oh! I see. :) Thank you!
