### ISSUE TITLE
[1.12.2][Bug] Can display recipes of a worktable been hided

### ISSUE THREAD

**Issue by SettingDust** [mezz/JustEnoughItems#2272]
Hide with JEI won't display any recipes on tables been hided.
![image](https://user-images.githubusercontent.com/19922286/110758737-d1622c80-8287-11eb-9c5f-e5d91a3bafb5.png)

Hide with CraftTweaker will display the name of tables.
![image](https://user-images.githubusercontent.com/19922286/110758196-310c0800-8287-11eb-84f2-25a0bbd766c3.png)

**Comment by mezz** [comment]
I believe this has been fixed so that they work the same and hide the recipe category.
