### ISSUE TITLE
I cant use ingame configs

### ISSUE THREAD

**Issue by SirSuomiPoika** [mezz/JustEnoughItems#2273]
Minecraft version = 1.16.5
So i am trying to make a modpack and i am including this in it. But when im trying to access JEI ingame configs it wont let me and just tells that i need to download FTB GUI Library. And when i do that it crashes the game
![2021-03-12_11 18 04](https://user-images.githubusercontent.com/80515223/110922643-995ef600-8328-11eb-8beb-1abd3bb29eae.png)

Can anyone help me?

**Comment by actuallyasmartname** [comment]
Install this: https://www.curseforge.com/minecraft/mc-mods/ftb-gui-library
