### ISSUE TITLE
Potion effects pushing bookmarks too far down (7.6.1.71)

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2276]
I have one potion effect and it's pushing the bookmarks list all the way down. See pic.
<img width="726" alt="Screen Shot 2021-03-12 at 9 48 49 AM" src="https://user-images.githubusercontent.com/15851438/110979000-fa53f180-835b-11eb-8e2c-5d73fc756c60.png">

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version.
