### ISSUE TITLE
Pixelmon integration

### ISSUE THREAD

**Issue by Yriokiri** [mezz/JustEnoughItems#2278]
Suggestion.

is possible to make an integration for the Pixelmon Reforged mod? the recipes of that mod don't show up. an exemple is the potion craft. it get crafted in the brewing stand using a berry and 3 water bottles

**Comment by Ommina** [comment]
Possible?  Sure.

However, JEI plugins are typically written by the mod author or authors, not by mezz or JEI contributors.

The latter would be an impossibly work-intensive task.
