### ISSUE TITLE
When pressing R recipes will not be displayed.

### ISSUE THREAD

**Issue by ItsIvanio** [mezz/JustEnoughItems#2279]
I've been playing on a server I made with a modpack I made and I cant seem to use most of JEI's features. Whenever I press R while hovering it will display the anvil tab. I tried messing with the controls and that didn't change anything I tried reinstalling the mod and it still wouldn't work. I uninstalled on my forge and tried running it on the server side that didn't work, and then I tried running it client side only and I still can't see recipes. The thing is that on my solo world it works just fine and that made me think its a problem with the server, but I don't know what the issue could be. Please help I really want this mod to work.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by krimsung** [comment]
I am having the same issue I think. I am using Forge forge-1.16.5-36.1.32 and JEI 7.7.0.107.
https://gist.github.com/krimsungh/042c9b73d334b63c818387c3e4094a99
