### ISSUE TITLE
Transitive Crafting

### ISSUE THREAD

**Issue by AljoschaMeyer** [mezz/JustEnoughItems#228]
Hey there,
what do you think about adding a transitive crafting function? E.g. transitively crafting a crafting table from a wood log. Implementation would be tricky, but possible (disclaimer: I did not look at the JEI code at all yet).

Some stuff to consider off the top of my head:
- Handle unused itermediate products (e.g. transitively crafting a torch with a coal and log would result in 4 torches, 3 sticks and  2 planks).
- Whether to do partial crafting if not everything is in the inventory (e.g. trying to craft a torch from only a log, should this still create 4 sticks and 2 planks, or just leave the log unchanged?)
- Handle multiple possibilities to craft (e.g. crafting a torch from coal, an oak log and a birch log)
- How to handle crafting that comes at a cost (resources or time), or which does not completely happen in a GUI - make transitive crafting opt-in via the plugin api?

And finally, does this even belong in a utility mod (gameplay-wise), or should this functionality be tied to setup or costs (as in e.g. Applied Energistics or Logistics Pipes)?

**Comment by mezz** [comment]
Thanks for the suggestion!
I think this would be better implemented by another mod, JEI is trying to stay simple. They could hook into JEI's API to get the information required for the crafting recipes.

**Comment by AljoschaMeyer** [comment]
That sounds reasonable. The clean design of JEI is great, so keeping things simple can't be wrong.

I feel like the JEI GUI would be a good place for the user interface for a utility (client-side only) mod providing transitive crafting. So in the unlikely case I'd ever get around to writing something like that, I'll just bug you again =)
