### ISSUE TITLE
Please set an updateJSONURL

### ISSUE THREAD

**Issue by miiichael** [mezz/JustEnoughItems#2281]
In-game version checks currently do not work (resulting in me not realising my JEI was out of date). For some reason I had assumed "no green dot" meant "running latest version". :sweat_smile: 

![image](https://user-images.githubusercontent.com/4179353/111089908-bb46bb80-8568-11eb-91a8-5f042d3b27d9.png)

**Comment by Popaulol** [comment]
The Problem is for an update check, they'd have to set up a website or at least an API Server, which will be pinged allot, so it'll need to have a big bandwith and Power and that is pretty expensive and hard to do for a mod as big as JEI...

**Comment by miiichael** [comment]
Does the existence of https://github.com/Ephys/mc-curseforge-updateJSONURL help at all? 🤔

**Comment by Popaulol** [comment]
> 
> 
> Does the existence of https://github.com/Ephys/mc-curseforge-updateJSONURL help at all? 🤔

It would help them to not have to implement it themselfes, but they'd still have to Host it somewhere and with probebly thousands of people Playing with JEI at the time, they'd have to worry about the Mod exidentally ddosing the Versioning server...
It is possible but expensive.

**Comment by miiichael** [comment]
Somewhere like https://pages.github.com/ ? :sweat_smile:

**Comment by miiichael** [comment]
Comment.

**Comment by miiichael** [comment]
Comment.

**Comment by Popaulol** [comment]
> Somewhere like https://pages.github.com/ ? sweat_smile

As far as i remember gh pages can only be used to serve static web content.
So yes it would be possible to host this on gh pages since you'd only need to serve a single json file if i recall correctly.

**Comment by miiichael** [comment]
Comment?
