### ISSUE TITLE
[Suggestion] Hotkeys to switch between recipe categories

### ISSUE THREAD

**Issue by schliip** [mezz/JustEnoughItems#2282]
I think that rebindable hotkeys to switch between machines/categories of recipes, similar to the existing hotkeys to change recipe pages, would help navigate recipes much more quickly.

![image](https://user-images.githubusercontent.com/34576051/111861421-8057d580-8924-11eb-867d-5754ebf3d124.png)

**Comment by mezz** [comment]
Good idea thanks, I have added a re-bindable hotkey for this.
