### ISSUE TITLE
JEI not showing

### ISSUE THREAD

**Issue by Skarsnix** [mezz/JustEnoughItems#2284]
I have just downloaded and installed JEI mod along with some other mods, when I load into a single player or into my server the JEI menu does not show up on the side when I open up inventory or at the crafting table. I have removed the other mods so that I could do a process of elimination to see if it was having an issue with another mod, with just JEI being the only mod I had in my mod folder, when I went into a game, single or multi the menu on the side still does not show up when opening the inventory or the crafting table. If someone could please help me figure this out it would be great

Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by actuallyasmartname** [comment]
Can you give us a log? It would be nice, thank you
