### ISSUE TITLE
Memory leak on reloading world / server still present

### ISSUE THREAD

**Issue by MrKashew** [mezz/JustEnoughItems#2289]
Using jei-1.16.5-7.6.1.75.jar
I see this issue referred to as fixed in the changelog
(https://github.com/mezz/JustEnoughItems/pull/2153)
Still having this issue arise where I am using 1gb+ more ram upon reloading a world

**Comment by mezz** [comment]
Thanks for the report!
There have been more fixes recently, do you still see this issue on the latest version today?
