### ISSUE TITLE
JEI + Forge 1.12.2.14.23.5.2854

### ISSUE THREAD

**Issue by calgia** [mezz/JustEnoughItems#2297]
Hello

I've wanna use Just Enugh items on a Forge 1.12.2.14.23.2854 (the newst Forge-Version) but that actually bring me a error at starting.
First hestart normaly later he gave m e an error.

I have other mods what are unluckly only available for 1.12.2.
On the Server and Local are stored:

- SecurityCraft
- Grim Pack
- InventoryPets
- JEI
- Malissis Doors & Malissis Core
- Three Chopper
- Worldedit Forge
- Xaeros Minimap

``---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.5.0_Forge_1.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/2/21 1:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.RuntimeException: Guice Injector not initialized yet!
	at net.mysterymod.mod.MysteryMod.getInjector(MysteryMod.java:63)
	at net.minecraft.client.gui.GuiButton.handler$injectConstruct$zbi000(GuiButton.java:560)
	at net.minecraft.client.gui.GuiButton.<init>(GuiButton.java:44)
	at mezz.jei.gui.elements.GuiIconButton.<init>(GuiIconButton.java:33)
	at mezz.jei.gui.elements.GuiIconButton.<init>(GuiIconButton.java:28)
	at mezz.jei.gui.PageNavigation.<init>(PageNavigation.java:26)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.<init>(IngredientGridWithNavigation.java:51)
	at mezz.jei.gui.overlay.IngredientListOverlay.<init>(IngredientListOverlay.java:61)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:105)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 390899904 bytes (372 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version               | Source                                   | Signature                                |
	|:------ |:----------------- |:--------------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                | minecraft.jar                            | None                                     |
	| LCHIJA | mcp               | 9.42                  | minecraft.jar                            | None                                     |
	| LCHIJA | FML               | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core | 1.12.2-1.0            | minecraft.jar                            | None                                     |
	| LCHIJA | securitycraft     | v1.8.21               | [1.12.2]+SecurityCraft+v1.8.21.jar       | None                                     |
	| LCHIJA | grimpack          | 6.0.0.6               | Grim+Pack-1.12.2-6.0.0.6.jar             | None                                     |
	| LCHIJA | inventorypets     | 2.0.12                | inventorypets-1.12-2.0.12.jar            | None                                     |
	| LCHIJE | jei               | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                | None                                     |
	| LCHIJ  | malisiscore       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar             | None                                     |
	| LCHIJ  | malisisdoors      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar            | None                                     |
	| LCHIJ  | treechopper       | 1.2.4                 | TreeChopper-1.12.2-1.2.4.jar             | None                                     |
	| LCHIJ  | worldedit         | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar | None                                     |
	| LCHIJ  | xaerominimap      | 21.5.0                | Xaeros_Minimap_21.5.0_Forge_1.12.jar     | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.5.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.20' Renderer: 'GeForce RTX 2080 Super with Max-Q Design/PCIe/SSE2'
	Grim Pack loaded parts: 
	= Grim Core { Loaded }
		~ Enable aluminum subpart { Enabled }
		~ Enable coal subpart { Enabled }
		~ Enable graphite subpart { Enabled }
		~ Enable iron subpart { Enabled }
		~ Enable rubber subpart { Enabled }
		~ Enable steel subpart { Enabled }
	= Grim Cuisine { Loaded }
		~ Enable SubPart chocolate { Enabled }
		~ Enable SubPart dairy { Enabled }
		~ Enable SubPart dragon fruit { Enabled }
		~ Enable SubPart health { Enabled }
		~ Enable SubPart pie { Enabled }
		~ Enable SubPart soda { Enabled }
	= Grim Decor { Loaded }
		~ Enable SubPart alarm { Enabled }
		~ Enable SubPart cages { Enabled }
		~ Enable SubPart calendar { Enabled }
		~ Enable SubPart colorizer { Enabled }
		~ Enable SubPart decorations { Enabled }
		~ Enable SubPart fireplaces { Enabled }
		~ Enable SubPart flat item frame { Enabled }
		~ Enable SubPart fluro { Enabled }
		~ Enable SubPart frames { Enabled }
		~ Enable SubPart furniture { Enabled }
		~ Enable SubPart lamp posts { Enabled }
		~ Enable SubPart lanterns { Enabled }
		~ Enable SubPart lightbulbs { Enabled }
		~ Enable SubPart neon sign { Enabled }
		~ Enable SubPart slopes { Enabled }
		~ Enable SubPart wall clock { Enabled }
		~ Enable SubPart wallpaper { Enabled }
	= Grim Industry { Loaded }
		~ Enable SubPart bridges { Enabled }
		~ Enable SubPart chunk loader { Enabled }
		~ Enable SubPart conveyor { Enabled }
		~ Enable SubPart decoration { Enabled }
		~ Enable SubPart doors { Enabled }
		~ Enable SubPart elemental blocks { Enabled }
		~ Enable SubPart extruder { Enabled }
		~ Enable SubPart fans { Enabled }
		~ Enable SubPart gates { Enabled }
		~ Enable SubPart gravity { Enabled }
		~ Enable SubPart hlights { Enabled }
		~ Enable SubPart ice maker { Enabled }
		~ Enable SubPart machines { Enabled }
		~ Enable SubPart metal works { Enabled }
		~ Enable SubPart nuclear { Enabled }
		~ Enable SubPart rways { Enabled }
		~ Enable SubPart sensors { Enabled }
		~ Enable SubPart shaped charges { Disabled }
		~ Enable SubPart spikes { Enabled }
		~ Enable SubPart steel { Enabled }
		~ Enable SubPart storage { Enabled }
		~ Enable SubPart torches { Enabled }
		~ Enable SubPart workbench upgrades { Enabled }
	= Grim Tools { Loaded }
		~ Enable SubPart backpacks { Enabled }
		~ Enable SubPart black diamond { Enabled }
		~ Enable SubPart boomerangs { Enabled }
		~ Enable SubPart buckets { Enabled }
		~ Enable SubPart chicken suit { Enabled }
		~ Enable SubPart chisel { Enabled }
		~ Enable SubPart detonators { Enabled }
		~ Enable SubPart extinguisher { Enabled }
		~ Enable SubPart grenade launcher { Enabled }
		~ Enable SubPart hammers { Enabled }
		~ Enable SubPart knives { Enabled }
		~ Enable SubPart machetes { Enabled }
		~ Enable SubPart magic { Enabled }
		~ Enable SubPart masks { Enabled }
		~ Enable SubPart multitools { Enabled }
		~ Enable SubPart pokeball { Enabled }
		~ Enable SubPart portable workbench { Enabled }
		~ Enable SubPart powerstaff { Enabled }
		~ Enable SubPart ray guns { Enabled }
		~ Enable SubPart slingshots { Enabled }
		~ Enable SubPart spears { Enabled }
		~ Enable SubPart staffs { Enabled }
		~ Enable SubPart ultimate fist { Enabled }
		~ Enable SubPart wands { Enabled }
	= Grim Util { Loaded }
		~ Enable SubPart auto item replacer { Disabled }
		~ Enable SubPart auto torch { Enabled }
		~ Enable SubPart chicken feathers { Enabled }
		~ Enable SubPart debug { Disabled }
		~ Enable SubPart double doors { Enabled }
		~ Enable SubPart frozen { Enabled }
		~ Enable SubPart fusrodah { Enabled }
		~ Enable SubPart graves { Enabled }
		~ Enable SubPart infinite lava { Disabled }
		~ Enable SubPart time { Enabled }
	= Grim World { Loaded }
		~ Enable SubPart 8-bit mobs { Enabled }
		~ Enable SubPart corruption { Disabled }
		~ Enable SubPart desert wells { Enabled }
		~ Enable SubPart flat bedrock { Enabled }
		~ Enable SubPart floating island world type { Disabled }
		~ Enable SubPart floating islands { Enabled }
		~ Enable SubPart fungus { Enabled }
		~ Enable SubPart glowstone seeds { Enabled }
		~ Enable SubPart gunpowder reeds { Enabled }
		~ Enable SubPart ice pixie { Enabled }
		~ Enable SubPart more people { Disabled }
		~ Enable SubPart randomite { Enabled }
		~ Enable SubPart ruins { Enabled }
		~ Enable SubPart treasure mobs { Enabled }
		~ Enable SubPart world gen expanded { Enabled }

	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.20
	OpenGlRenderer: GeForce RTX 2080 Super with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16``

Greatings, calgia

**Comment by mezz** [comment]
Thanks for the report!
This appears to be a crash from `MysteryMod`, please try removing it to see if you still have an issue.

**Comment by calgia** [comment]
Hello

Mysterymod say that the bug is from you.
I have as well problems with normal forge

MysteryMod is a all in one Client mod what you can Download at nysterymod.net

Freundliche Grüsse

Gian Duri Calonder


Am 17.05.2021 um 03:51 schrieb mezz ***@***.***>:

﻿

Thanks for the report!
This appears to be a crash from MysteryMod, please try removing it to see if you still have an issue.

**Comment by mezz** [comment]
Please link me to the discussion or have the developer join here so we can have a conversation in one place.

**Comment by calgia** [comment]
They have there own forms at forum.mysterymod.net

Freundliche Grüsse

Gian Duri Calonder

Am 17.05.2021 um 11:32 schrieb mezz ***@***.***>:

﻿

Please link me to the discussion or have the developer join here so we can have a conversation in one place.

**Comment by Ommina** [comment]
The thread _seems_ to be at: https://forum.mysterymod.net/forum/thread/636-just-enough-items-forge-desaster/?postID=3662 (identical mod list and exception at any rate).

In it, it is the (forum) OP that concludes JEI is at fault, because Forge crashes even without MysteryMod (presumably).

I note, as well, calgia reports above "I have as well problems with normal forge".  If that is the case, then a link to a fresh crash report would, I'm sure, be useful.

**Comment by mezz** [comment]
Thanks Ommina!

@calgia it seems like you have misrepresented the issue here. The author of MysteryMod did not say it is a bug caused by JEI, that is a conclusion you came to on your own.

**Comment by calgia** [comment]
Yea that’s true.

This is my old report. Because the Mod did not work there with Forge as well i‘ve vrote here.

https://forum.mysterymod.net/forum/thread/636-just-enough-items-forge-desaster/?postID=3662

I can check today evening if the issue still there.

Freundliche Grüsse

Gian Duri Calonder

Am 17.05.2021 um 22:41 schrieb mezz ***@***.***>:

﻿

Thanks Ommina!

@calgia<https://github.com/calgia> it seems like you have misrepresented the issue here. The author of MysteryMod did not say it is a bug caused by JEI, that is a conclusion you came to on your own.

**Comment by calgia** [comment]
Hello

I’ve now made a video from my desktop. You’ll find it here: https://youtu.be/Rj--ZpJ63xM

I’ve used the standard forge version, with 2855 the newst it also crashed.

I use jei 1.12.2

Greetings, Gian Duri Calonder

**Comment by Ommina** [comment]
It still says "net.MysteryMod" in the crash report.  (And I, for one, will not look at a video of a crash report again.)

It also even has "MysteryMod 0.1.21 OPEN BETA" [on the loading screen](https://youtu.be/Rj--ZpJ63xM?t=33).

I can't help but feel MysteryMod is still installed.
