### ISSUE TITLE
jei

### ISSUE THREAD

**Issue by epsonlilg** [mezz/JustEnoughItems#2299]
Jei keeps crashing my minecraft whenever it crashes it says this Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file jei-client.toml of type CLIENT for modid jei
Exit Code: -1

**Comment by mezz** [comment]
Thanks for the report!
Have you tried deleting the `jei-client.toml` and then starting the game?
