### ISSUE TITLE
REI "Failed to parse mod menu version"

### ISSUE THREAD

**Issue by officialeleri** [mezz/JustEnoughItems#2301]
My game is able to launch normally, however just before the main screen loads I get the following message:

"Errors during Roughly Enough Items' Initialization"
"Errors: Failed to parse Mod Menu Version: Could not parse version number component 'v1'!"

I've attached a picture of all the mods and clients I use below. 
I have 0 experience with coding and developing, so I'm hoping someone will be able to explain as simple as possible what I can do to fix this problem :)
I also apologize if there's a very obvious answer, again I don't have any experience with mod compatibility and coding

I'm using 1.16.5 with fabric loader and optifine using OptiFabric 

![Error JEI](https://user-images.githubusercontent.com/82015805/113663667-6e8e6600-9678-11eb-9219-ae5de4130be6.png)

![Mods Installed](https://user-images.githubusercontent.com/82015805/113663803-abf2f380-9678-11eb-8aeb-71bca944f301.png)

**Comment by Ommina** [comment]
JEI (Forge) <> REI (Fabric)

I see you've already posted an identical issue on the REI issue tracker, and have got a couple replies, so you can close this one here.

**Comment by officialeleri** [comment]
So sorry for leaving the issue open, I originally thought I posted this to REI, and forgot to close this issue :)
