### ISSUE TITLE
JEI CHEAT MODE

### ISSUE THREAD

**Issue by micaelgomestavares** [mezz/JustEnoughItems#2303]
**Server-side problem

I have a minecraft server, in 1.16.4  mohist  version (with mods obviously). But, the players of my server can get items from JEI cheat mode, can i disable that? Because this break the server, and the JEI not have a config archive.

*players not have a give permission, i'm using LuckPerms*

**Comment by BanHerobrine** [comment]
disable it here:
![image](https://user-images.githubusercontent.com/73577302/114713213-339fc880-9d31-11eb-8925-ee5459cd1fe6.png)
and also click the checkmark on the bottom right so its global

**Comment by jshalbrook** [comment]
Have the same problem and we are using:
   ftb-gui-library-1605.2.1.41-forge.jar
We had a player yesterday start grabbing stuff from the JEI. Did this by setting up their key bind to enable cheat mode while in the JEI.  CTRL+LeftClick also enabled it. How do we disable this with a menu like the one below?

![image](https://user-images.githubusercontent.com/35284823/116248382-10a9e700-a729-11eb-9f09-6e3344092d8d.png)

**Comment by Ommina** [comment]
~~As I recall, all JEI does is issue the _/give_ command on the server; it does not actually create any items itself.~~  Ensure that your server permissions (and any other permission stuff you might be running) are correct.

Edit: Looks like "is in creative mode" or "is an op" or "can use /give".

**Comment by jshalbrook** [comment]
> Have the same problem and we are using:
> ftb-gui-library-1605.2.1.41-forge.jar
> We had a player yesterday start grabbing stuff from the JEI. Did this by setting up their key bind to enable cheat mode while in the JEI. CTRL+LeftClick also enabled it. How do we disable this with a menu like the one below?
> 
> ![image](https://user-images.githubusercontent.com/35284823/116248382-10a9e700-a729-11eb-9f09-6e3344092d8d.png)

This has been resolved for us at least with the newest JEI version: 1.16.5-7.7.0.103

**Comment by mezz** [comment]
Thanks for the report!
I have added some new server-side configs to enable or disable cheat mode in JEI, that will allow server owners to control this behavior. https://github.com/mezz/JustEnoughItems/commit/574bb250458f17dc0ae6045bfdff1d424b47e8b3
