### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by hammy275** [mezz/JustEnoughItems#2304]
The Wiki on this GitHub is quite out of date (seems to be mainly for 1.12 JEI). I had to go through a bit of trouble to get my mod working with 1.16 JEI, but now that I have that working, I'd be more than happy to update the Wiki for it! Since 1.12 is still quite popular though, I want to ask how it would be best to go about things. Would it be best to:

* Make separate 1.16 versions of all the pages
* Update the pages to replace 1.12 things with 1.16 things
* Have 1.16 and 1.12 support on all pages

Thank you so much for any replies, and I look forward to hopefully being able to update the wiki!

**Comment by mezz** [comment]
Thanks! I think it would be best to split 1.12 and 1.13+ into separate pages at this point. I tried putting both on some pages, like for Getting Started, but it can be a bit complicated to read.

**Comment by hammy275** [comment]
I've finished a 1.13+ version of the Wiki that has nearly everything the 1.12 one does. I'm not familiar with using custom ingredient types, so I haven't written a page on that, but besides that and a lack of talk on custom transfer handlers, it should be pretty much done! I'll definitely be making passes through it over the next couple days to try to refine things, and will probably end up splitting the [1.13 recipe categories page](https://github.com/mezz/JustEnoughItems/wiki/Recipe-Categories-%5B1.13-and-Up%5D) into multiple pieces.

If there's anything that you'd want me to rearrange, change, etc. feel free to let me know!

**Comment by mezz** [comment]
Nice, thanks! This looks like a good improvement over what was there before. I like the way it's split up.

**Comment by hammy275** [comment]
Thanks! :D 

Going to close this issue for now, as I feel the edits I made are in a generally good place. I do plan to make small edits here and there if/when I catch any problems or learn something more about JEI that needs to be documented. Feel free to re-open this if you need me to add anything else or run into something.
