### ISSUE TITLE
[1.12] Unable to be used with Controllable (Joystick)

### ISSUE THREAD

**Issue by PibePlayer** [mezz/JustEnoughItems#2308]
I'm not able to fullly use it on conjunction with Controllable since I'm not able to "click" the icons to see the recipes.
Thanks for your time!

**Comment by mezz** [comment]
Thanks for the suggestion!
It looks like Controllable has its own built-in JEI integration these days: https://github.com/MrCrayfish/Controllable/blob/b4b1974e0f9bcaefae5dd5ad02d31021b29c87ab/src/main/java/com/mrcrayfish/controllable/integration/JustEnoughItems.java
