### ISSUE TITLE
left side of JEI not showing up

### ISSUE THREAD

**Issue by BanHerobrine** [mezz/JustEnoughItems#2309]
Thank you for reporting!

For issues:
the forge loader is : 14.23.5.2769
the JEI version is:4.13.1.220
![image](https://user-images.githubusercontent.com/73577302/114712849-d73ca900-9d30-11eb-934c-cbbb11f284eb.png)
i tried also pressing a on an item on JEI but it still wont go into the bookmark list. besides, it should appear on the left side anyway even if there are no items i bookedmarked. can someone please help me? thanks.

**Comment by mezz** [comment]
Thanks for the report!
You have a very old version of JEI from before bookmarks existed. They were first added in version 4.14.0

**Comment by BanHerobrine** [comment]
ok thank you
