### ISSUE TITLE
Where is the file that stores recent searches?

### ISSUE THREAD

**Issue by PeterLemur** [mezz/JustEnoughItems#2310]
Game crashes whenever I open my inventory. My inventory is empty, so I am pretty sure I searched up a broken item and since it is my most recent search it re-searches it whenever I re-open my inventory. Hopefully if I can clear the recent searches that will fix it.

**Comment by mezz** [comment]
The recent searches are stored in the config/jei folder inside your minecraft directory.
You should also be able to see a JEI ID for the broken item from the crash report, and then blacklist that item by adding it to the JEI blacklist config file.
