### ISSUE TITLE
cant use the cheat mode

### ISSUE THREAD

**Issue by devoak06** [mezz/JustEnoughItems#2311]
so when i go to config the mod ingame to turn on cheat mode it says that i need to install FTB GUI library so can someone point me in the right direction to get this fixed. edit: so i found the download link so i installed it and now a error pops up when loading the mods that architectury 1.1.53 or above is not installed so i would like some help with this now
![FML early loading progress 4_14_2021 11_35_30 PM](https://user-images.githubusercontent.com/82490008/114819245-68843d80-9d7a-11eb-8fcf-40415967ef1d.png)

**Comment by Ommina** [comment]
Well, if it says it is required, and it isn't installed, then... install it.

https://www.curseforge.com/minecraft/mc-mods/architectury-forge

(Maybe, someday, somebody will update the GUI to remove the FTB GUI Library dependency.  Maybe.)

**Comment by Eric-01** [comment]
> (Maybe, someday, somebody will update the GUI to remove the FTB GUI Library dependency. Maybe.)

Fortunately, someone has already done this. Kind of. Check out MrCrayfish's Configured mod.

IMO there's nothing wrong in depending on the FTB GUI Library as long as it doesn't depend on yet another dependency — Fabric guy's Architectury mod ;p
