### ISSUE TITLE
[1.16.5] JEI does not appear, nor does it function, but it detects it's installed.

### ISSUE THREAD

**Issue by Darkmega18** [mezz/JustEnoughItems#2312]
I have attached a latest log incase it sheds any light. Don't worry about the crash at the end, I don't think it was related. But when I load into my game when I open my inventory I expect to see JEI and be able to search items and recipes etc on items.

But on getting in there there is no JEI. I thought at first I just had it turned off by accident. So I use the control settings to try to turn it on but nothing happens. I double check to make sure it's installed and such but it's definitely there and the controls are exchangeable in control options and such, just that there is no functionality in the game currently for some odd reason or another. My advanced tooltips are active.
[latest.log](https://github.com/mezz/JustEnoughItems/files/6323116/latest.log)

I believe another had a similar issue here:
https://github.com/mezz/JustEnoughItems/issues/2284
but never provided any logs etc. however my mods are all still installed cause of the sheer number of them and I don't know where to start on what COULD be something thats interrupting it's functionality... :V

Version of JEI is: jei-1.16.5-7.6.4.86.jar
Version of Forge is: 36.1.4

**Comment by hyperQ7** [comment]
I have the same issue. I removed what looked like the problem mods and it did not fix the issue. Even though it did not show any errors. The error says "Couldn't parse loot table" followed by the mod.
[latest.log](https://github.com/mezz/JustEnoughItems/files/6339416/latest.log)

**Comment by mezz** [comment]
Thanks for the report!
Based on the log and code, it looks like some mod might have accidentally (or intentionally?) deleted the vanilla anvil from the game.

From other lines in the log, I think this may be because of the `apotheosis` mod. Please try removing it and see if that works.

```
[20:14:14] [Render thread/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `anvil`, expected `apotheosis`. This could be a intended override, but in most cases indicates a broken mod.
[20:14:14] [Render thread/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `chipped_anvil`, expected `apotheosis`. This could be a intended override, but in most cases indicates a broken mod.
[20:14:14] [Render thread/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `damaged_anvil`, expected `apotheosis`. This could be a intended override, but in most cases indicates a broken mod.
```

**Comment by Darkmega18** [comment]
I since rebuilt the pack with some other stuff and JEI has been existing fine now. I've used JEI and apotheosis a lot in 1.12.2 and am still using it in the latest 1.16.5 stack of mods I'm testing and it's working. so I'm not sure what had happened that time to trigger this.

**Comment by mezz** [comment]
Ok thanks. If it comes up again please feel free to open a new issue. For now I will close this one since it seems to be resolved.
