### ISSUE TITLE
Game instantly crashes whenever opening inventory

### ISSUE THREAD

**Issue by pixoe** [mezz/JustEnoughItems#2316]
Whenever I open my inventory, it shows me already have typed in fluid and things from industrialcraft 2 show up, even though I don't have that mod installed currently. whenever I try to delete the text my game instantly crashes.

**Comment by pixoe** [comment]
The game crashed whilst rendering ingredient
Error: java.lang.IllegalStateException: Not building!
Exit Code: -1

is what the error code says

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
