### ISSUE TITLE
JEI disapering when i search some recipes

### ISSUE THREAD

**Issue by Zjories** [mezz/JustEnoughItems#2317]
I play with a mod pack and I'm working on 4x ores with mekanism but when I typed hy in the search bar because I needed Hydrogen, JEI disapeert, and also things in my Inventory. I tried older versions of JEI but that didn't fix it. and it's not only with hy also with other things. This is very annoying because I need JEI for recipes. Did I do something wrong or is it a bug I have no idea. It started about 2 weeks ago and I don't know how to fix it. this is on 1.16.4 JEI version jei-1.16.4-7.6.1.7 and forge 35.1.37

https://user-images.githubusercontent.com/62447055/115149068-adea8880-a062-11eb-95fa-ef22f052911a.mp4

Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I think that some mod has an item rendering bug, so when that item shows up it messed up some of the other rendering. Please try to narrow down which searches cause the issue, the issue is probably from one mod.

**Comment by Zjories** [comment]
JEI disappears when i scroll to the menu and I get to silents_mechanisms and it crashes my game if I look at what I can do with silents_mechanisms items.  The disappearance of JEI is with a few specific searces like gold hydrogen and another few. if JEI disapreas I can still add the items to my bookmark and view the recipe.
