### ISSUE TITLE
Bug with spawning in items with NBTDouble/Float.

### ISSUE THREAD

**Issue by Aroma1997** [mezz/JustEnoughItems#232]
Ok, so there is a bug when you spawn in an Item, that has a NBT on it.
For example when you have an item in JEI, that (for whatever reason has a nbt tag "someNumber" = 10,000,000D on it (A NBTTagDouble with 10 Million), and you spawn that item in in JEI, it does not have that NBTTag on it anymore. Instead, the NBTTagCompound of the ItemStack has a NBTTagString with 1.0E7d on it. This is due to the NBTTagCompound.toString() converting the Double into something, the Minecraft Give Command does not parse as a Double.
The issue lies here: https://github.com/mezz/JustEnoughItems/blob/8b318360cacf21db602855fb2933c07aa030eff2/src/main/java/mezz/jei/util/Commands.java#L46
I suggest using another way to convert the NBTTagCompount of an ItemStack to a String.

**Comment by mezz** [comment]
Thanks for the report!
I believe this is the same issue: https://github.com/mezz/JustEnoughItems/issues/177
