### ISSUE TITLE
[1.16.5] Can't access config/cheat mode after updating

### ISSUE THREAD

**Issue by Peca21** [mezz/JustEnoughItems#2320]
I updated JEI today to jei-1.16.5-7.6.4.88 and I can't access config anymore. It was working yesterday no problem. I also can't enable cheat mode with ctrl+config.

EDIT: I also can't unfocus search box by clicking anywhere empty.

forge-36.1.4
Java x64 1.8.0-281

**Comment by ozokuz** [comment]
Same

**Comment by aaronhowser1** [comment]
Same here

**Comment by enricotagliavini** [comment]
Same here, a message appears in chat to install the FTB library mod, but it's installed and active, version ftb-gui-library-1605.2.1.41

**Comment by Peca21** [comment]
I didn't get a warning I don't have FTBLib, this is other bug where you couldn't do a lot of stuff with the mouse in JEI. This issue has been fixed but not closed for some reason so I am closing it now.

**Comment by enricotagliavini** [comment]
Maybe a different issue then, but the config GUI is currently not working, I had to downgrade to jei-1.16.5-7.6.4.87 to have it working.

**Comment by aaronhowser1** [comment]
> 
> 
> Same here, a message appears in chat to install the FTB library mod, but it's installed and active, version ftb-gui-library-1605.2.1.41

FTB Gui Library is not FTB Library

**Comment by Peca21** [comment]
I got the same error now. No lib installed
