### ISSUE TITLE
pls make a 1.7.10 version

### ISSUE THREAD

**Issue by Maxwill333** [mezz/JustEnoughItems#2323]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Eric-01** [comment]
1.7 in 2021? Just let it die...

**Comment by mezz** [comment]
1.7.10 has NEI, which works well there. 
If I made a 1.7.10 version of JEI then all the mods would also have to add support, but nobody is developing on that version and so there would be no mod support.

**Comment by RogerRoger101** [comment]
> 1.7.10 has NEI, which works well there.
> If I made a 1.7.10 version of JEI then all the mods would also have to add support, but nobody is developing on that version and so there would be no mod support.

The three biggest MC versions (mod-wise) are:  1.7.10, 1.12, and 1.16, and people are still dev'ing even on 1.7.10.   The best mods are still on 1.7.10.  1.12 is slowly catching up.  

People are dev'ing for 1.7.10.  I have a discord list full of them.  I think those that want JEI integrated would do so.  I just think you don't want to make it which is your prerogative.

**Comment by mezz** [comment]
People are dev'ing for Minecraft beta as well, but no I don't want to support these old versions.

**Comment by RogerRoger101** [comment]
> People are dev'ing for Minecraft beta as well, but no I don't want to support these old versions.

fair enough but please don't tell people that no one is dev'ing for older versions of MC.  There are a lot of us that still love and enjoy those versions mentioned above :) and dev for it  :)

**Comment by gatoborrachon** [comment]
In case someone is looking for an answer to this, give a try to [NEI-GTNH](https://www.curseforge.com/minecraft/mc-mods/notenoughitems-gtnh)
