### ISSUE TITLE
[1.16.5] Incompatible with Create's potions

### ISSUE THREAD

**Issue by MarioSMB** [mezz/JustEnoughItems#2325]
Create introduces fluid types for all potions, JEI is not correctly detecting the potion types and defaulting to a generic "potion" fluid shared across all recipes.  
Referenced from here: https://github.com/Creators-of-Create/Create/issues/1499

**Comment by mezz** [comment]
Thanks for the report!
Based on the conversation in the other issue, this may be something to fix on their end.
I will subscribe to the other issue to get updates, and close this one.
