### ISSUE TITLE
FTB GUI Library

### ISSUE THREAD

**Issue by Hungry15230** [mezz/JustEnoughItems#2326]
On the JEI mod when i try and go into the wrech settings it says Install FTB GUI Library to access ingame config.

**Comment by Eric-01** [comment]
So why don't you do what it tells you and install the FTB GUI library or (better) use MrCrayfish's Configured mod instead?

**Comment by Hungry15230** [comment]
Ok, i didn't know what it meant or how to find it.

**Comment by Eric-01** [comment]
If your problem has been resolved, please close this issue.
