### ISSUE TITLE
Change event when clicking on items

### ISSUE THREAD

**Issue by RGFTheCoder** [mezz/JustEnoughItems#2327]
When an item is clicked in a recipe (to get its recipe), the new recipe should only be shown after the mouse is released (as it is now), but only if the mouse was originally pressed on the same item. This would stop the strange bugs that occur with FTB Quests in 1.16.5, as the click start would be on the questbook, so it wouldn't go into a random sub-recipe.

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed with the latest version, can you try it out?
