### ISSUE TITLE
JEI and Block Armor

### ISSUE THREAD

**Issue by CanBoy67** [mezz/JustEnoughItems#2331]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.
I have already reported this issue to the dev for 1.16.5 version of block armor but since I don't know if it's a problem with this mod or block armor I decided to report it here aswell. With the 1.16.5 version of jei installed and block armor jei is inaccessible so I'm unable to see any recipes

**Comment by mezz** [comment]
Thanks for the report!
Mods add their own integration to JEI, so it is likely an issue with Block Armor.
