### ISSUE TITLE
JEI Search Ignores Language

### ISSUE THREAD

**Issue by Peekofwar** [mezz/JustEnoughItems#2332]
When the game language is changed to EN-UK for instance, searching `biscuit` doesn't show the `biscuit`. You still have to search `cookie`.

![image](https://user-images.githubusercontent.com/10189526/116825922-4c3c1b00-ab46-11eb-82bc-8d633bdd6b52.png)

**Comment by mezz** [comment]
Thanks for the report!
I have tested this in the latest version of JEI and it is no longer an issue:
<img width="227" alt="Screen Shot 2022-01-08 at 3 43 40 PM" src="https://user-images.githubusercontent.com/916092/148665981-17146ce8-9311-444a-b12b-c0ce6ea140bc.png">
