### ISSUE TITLE
[1.16.5] Missing textures (black/purple) for some items from tinkers construct

### ISSUE THREAD

**Issue by Khana-an** [mezz/JustEnoughItems#2336]
As said in title. TC worked flawlessly before. just installed JEI on both server and client. then those Black/pruple sqares appeared for some smeltery blocks and every tool/toolpart.
![2021-05-06_17 00 15](https://user-images.githubusercontent.com/33006952/117320675-c04f2980-ae8c-11eb-87b4-edf17f812656.png)
![2021-05-06_17 00 29](https://user-images.githubusercontent.com/33006952/117320681-c0e7c000-ae8c-11eb-9b0e-5264bb09f688.png)
![2021-05-06_17 00 07](https://user-images.githubusercontent.com/33006952/117320684-c1805680-ae8c-11eb-9157-0804c0a5fc95.png)

Any suggestions?

**Comment by sbernardoDavi** [comment]
you can fix this?

**Comment by mezz** [comment]
Thanks for the report!
If this is still an issue, I need some more information to solve it. 
Please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
