### ISSUE TITLE
[1.16.5] If you right click the search box when there's no text, it doesn't get selected

### ISSUE THREAD

**Issue by aaronhowser1** [mezz/JustEnoughItems#2337]
Using `jei-1.16.5-7.6.4.90`.

I usually right-click to focus the search box, because it clears whatever's there. Before, right click would select it even when empty, but it doesn't in the latest version.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version.

**Comment by joklbash** [comment]
This appears to have resurfaced in the 136 version. If I only right click to clear the text, it does not get focus. Forge 36.2.8. No errors.

**Comment by mezz** [comment]
Thanks, I have fixed it (again) in the latest version which should be published shortly.

**Comment by joklbash** [comment]
Thanks so much - that fixed it!

**Comment by mezz** [comment]
Great, thanks for confirming.
