### ISSUE TITLE
i searched for 1.16.2 only mods and it showed this. and this dose not work on minecraft 1.16.2

### ISSUE THREAD

**Issue by The-lights** [mezz/JustEnoughItems#2338]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Eric-01** [comment]
Are you sure you downloaded JEI from here: https://www.curseforge.com/minecraft/mc-mods/jei/files/all?filter-game-version=2020709689%3A8010 ?

And by the way, why are you still on 1.16.2? The latest 1.16.5 has much better mod support. I strongly encourage you to update :)

**Comment by The-lights** [comment]
Becose i had a laptop that has that error with not accepting 1.16.5 forge
instaler now i have jarfix now it works
