### ISSUE TITLE
JEI only opens when another screen is open

### ISSUE THREAD

**Issue by JadeFairall** [mezz/JustEnoughItems#2339]
I am playing pixelmon on 1.12.2 with the correct JEI version installed (1.12.2). The mod works however it will only open when I have another screen open in front, for example the cosmetic screen. Why won't JEI open by itself?

First image is where it does not open by itself, second image is where it will only open with something underneath it.

![image](https://user-images.githubusercontent.com/83689903/117532549-05d03b80-afe0-11eb-9ef5-49a6858ce18e.png)

![image](https://user-images.githubusercontent.com/83689903/117532557-11bbfd80-afe0-11eb-9d12-a7beb18d7f69.png)

**Comment by mezz** [comment]
JEI only opens alongside GUIs that have slots for items. It is intended as a crafting helper, so it's not meant to display on its own.
pixelmon does some weird things with GUIs so JEI doesn't seem to be displaying well there.
