### ISSUE TITLE
JEI not working server side.

### ISSUE THREAD

**Issue by CloWnicide** [mezz/JustEnoughItems#2340]
Currently running Forge: 36.1.16, JEI: 1.16.5-7.6.4.90, and JEI will not show up client side for my server at all. Tried reverting back to an older version, and that does not work either, any recommended troubleshooting steps to try?

**Comment by brumoen** [comment]
I'm seeing the same issue when I connect to our server, we have however figured out that if we load up a local world first then connect to the server it works. So not quite sure what's going on as we can't seem to find any information in the logs that sheds any light on the situation. 
Forge: 36.1.9
JEI: 1.16.5-7.6.4.90

It seems like others are having the same issue here: 
#2312 
#2284 (Kind of the same, but doesn't work in local worlds either so might not be related)

**Comment by Ommina** [comment]
See also #2210 #2213 and probably others.
