### ISSUE TITLE
Just Enough Buttons alternativ 

### ISSUE THREAD

**Issue by KineticPie** [mezz/JustEnoughItems#2341]
Hello,

I am a real fan of NEI and now also of JEI.
My problem is but I liked to use the function where I am shown which areas are no longer illuminated. 
Also I am missing some buttons from Just Enough Buttons, is there any way to install those under Minecraft version 1.16.5?

Is there also a mod like NEI back then that you can enchant tool?

**Comment by Eric-01** [comment]
To have some of the NEI overlays back, you can try More Overlays Updated.
