### ISSUE TITLE
Minecraft crashing as soon as it finishes loading. 

### ISSUE THREAD

**Issue by Lionley** [mezz/JustEnoughItems#2342]
I've been trying to load up MC Eternal for a while now and every time I do it keeps saying that this mod is the reason for Minecraft crashing (after the long part of loading all the mods) 

https://paste.dimdev.org/ecefocuhiq.mccrash

**Comment by Ommina** [comment]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

It (Minecraft as a whole) is running out of RAM.  You're giving it 6000MB, which feels like it should be enough, but I guess MC Eternal is extra needy.

**Comment by Lionley** [comment]
> Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
> 
> It (Minecraft as a whole) is running out of RAM. You're giving it 6000MB, which feels like it should be enough, but I guess MC Eternal is extra needy.

Ok i could try to give it more ram ig, bit odd but hopefully thatll work

**Comment by Ommina** [comment]
Not that odd.  Even the Curseforge page for MC Eternal suggests 8GB.
