### ISSUE TITLE
Jei refuses to load, whenever minecraft would finish loading, it crashes instead even when it is the only mod on. I have been having this issue since 1.16.4. I can't figure out why it won't load or how to fix it. https://gist.github.com/KritantaMabuz/213ef4eb92efdfe45d91fe39e977ebdd

### ISSUE THREAD

**Issue by KritantaMabuz** [mezz/JustEnoughItems#2346]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Please include a log where JEI is the only mod active. This crash log is filled with errors from other mods, so it is not possible to interpret.

**Comment by KritantaMabuz** [comment]
I think that is part of the problem, it crashed with the other mods on so I took all but JEI off then reloaded it again, when it crashed I copied the logs and after posting them here, I looked it over and saw all the other mods. I'll do it again and post the logs and see if anything has changed.

**Comment by KritantaMabuz** [comment]
https://gist.github.com/KritantaMabuz/c81610a5d3d42981fd34bb4b6f17b3b2
![mods 5_17_2021 7_51_20 PM](https://user-images.githubusercontent.com/84000102/118574618-6bdc6180-b74a-11eb-959d-11598e2a6257.png)

**Comment by KritantaMabuz** [comment]
Once again the logs came up with serene seasons, better default biomes, and others. I don't know why they keep showing up when I watch the loading screen, and they don't appear in the loading mods section but they are showing in the crash logs. I don't know why they do that.

**Comment by KritantaMabuz** [comment]
I restarted and fully updated my computer, the game still crashed, I didn't see anything pointing to any other mod in the crash log. Hopefully this helps. https://gist.github.com/KritantaMabuz/8d61161eca216fb117d794cd4f1995d3

**Comment by mezz** [comment]
It seems like something is breaking when it loads the config file. Try deleting the JEI config files and see if it still crashes.

**Comment by KritantaMabuz** [comment]
It loaded properly thank you. I did two test runs by itself and with other mods, it worked.
