### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Aarrn33** [mezz/JustEnoughItems#2347]
There is a missing translation in french in the latest 1.16 build (version 7.6.4.90) for the "jei.message.ftbguilib", where there is no translation. The translation is supposed to be "Installez la librarie FTB GUI pour accéder aux configurations en jeu".
Thanks

**Comment by Eric-01** [comment]
All JEI translations, except U.S. English, are contributed by the community. So if you know French well enough, you can contribute as well and improve the current French translation. After you are done, create a pull request and wait for Mezz's review :)

**Comment by Eric-01** [comment]
All JEI translations, except U.S. English, are contributed by the community. So if you know French well enough, you can contribute as well and improve the current French translation (not only by translating untranslated phrases and sentences but also by fixing any issues in the already translated ones). After you are done, create a pull request and wait for Mezz's review :)

**Comment by Aarrn33** [comment]
Ok, thank you very much!
