### ISSUE TITLE
1.9 JEI possibly getting overloaded causing GC sweep lag spikes.

### ISSUE THREAD

**Issue by NolanSyKinsley** [mezz/JustEnoughItems#235]
I am not quite sure where to go with this as there possibly could be many mods involved. I am making my own personal 1.9 modpack and I came across an issue after I installed Botania. After installing it I am getting ~1-2 second lag spikes with every GC round that was happening every 3-4 seconds. I have 1.5G allocated to MC, but the GC sweeps are happening at 1.3G and taking it down to 1G repeatedly, not even allocating the full 1.5G. 

Removing JEI resolves this issue, or removing either botania, or a few other mods, will also stop the issue from happening. The determining factor seems to be just the pure number of recipes, as I can't find any combination of mods that cause the issue individually, or as a group of 5-10, just as a whole group of mods approaching 50.

I enabled verbose GC and this is the log that resulted: https://gist.github.com/NolanSyKinsley/a868fe08be23bfcf0c4c03f4766252ab

(yes, I have also tested without optifine, same issue, I have also tried adding mods one by one looking for the culprit and never been able to find the smoking gun)

If there is anything I can do to get to the root cause of the issue please let me know.

**Comment by NolanSyKinsley** [comment]
Ok, my memory came in today so I was able to up the allocation to 2G and that helped a lot and seems to resolve the issue, but it is still really odd that the game was not even using the full 1.5 gigs allocated and having such difficulty.

**Comment by mezz** [comment]
Thanks for the report!
My best guess is that JEI is bumping up the memory usage just enough that your GC is struggling with the remaining memory space available. 2G is definitely on the low-end for modded minecraft, probably the minimum.

**Comment by NolanSyKinsley** [comment]
I have ran modpacks with upwards of 200 mods on 1.5 gigs, I have even gotten away with 1 gig on modpacks up to ~150 mods, it really really should not be struggling with 50 mods @1.5 gigs, most of which are not very large at all, I only have a few heavy hitters. I also reiterate that the game was not allocating all the memory I had given it.

**Comment by mezz** [comment]
Minecraft 1.8+ is a lot heavier on ram than 1.7.10 was. The performance is better otherwise though.

**Comment by NolanSyKinsley** [comment]
No... it really isn't. Vanilla performance is literally spot on exactly what it was before, and even if it is heavier it doesn't account for that severity.

There definitely is something funky going on, the memory usage wasn't hitting what the game had allocated and the game hadn't allocated what I had allocated to the java process. GC was happening at 1.28G, I have never, ever, had GC lag spikes before unless it hits the memory limit. And if the memory limit truly were the issue then it should have gone to an OOM error, not getting GC lag spikes, GC is for garbage collection, getting rid of what is not needed but something kept trying to load a bunch into memory that simply is not needed by the game.

Just because it gets better by throwing more memory at it doesn't mean that is the correct solution, that is just covering up an issue with a mod happening somewhere.

**Comment by mezz** [comment]
I don't know what to say. I'm not arguing that there is no problem.

JEI doesn't constantly generate a ton of objects for the garbage collector to deal with. It does take up a stable chunk of memory up-front to store what it needs though.

Minecraft 1.8 introduced the BlockPos object which are created and discarded extremely frequently, causing a huge amount of Young Generation garbage collection. If your baseline, stable memory use is very close to your memory limit, the garbage collector has much worse performance and has to run more often. If your baseline stable memory use hits the memory limit, you get a OOM error.

All of this is difficult to replicate without the exact mods and memory limitations you have. If you can pin the rapid garbage generation to one mod that would be helpful. I have profiled JEI and didn't uncover a memory issue that would cause your problem.

**Comment by VT-14** [comment]
You really should have more RAM for this kind of stuff.  I personally use 4 GB.  "More RAM" might not be the 'correct' solution but it certainly is an effective one.

Also keep in mind that 1.9 mods are super early in development.

I'm curious what "200 mods" you had running with 1.5 GB of RAM and whether it was while playing on a server or single player.  I know a few people who have similarly small amounts of RAM available, and a list of friendly mods or even a modpack would be convenient.
