### ISSUE TITLE
FTB Gui Library installed, but configs still won't show

### ISSUE THREAD

**Issue by garrowson** [mezz/JustEnoughItems#2351]
I can't access the ingame config. It shows the text "Install FTB Library to access ingame config" in chat be it MP & SP.

I already installed:
jei-1.16.5-7.7.0.91
ftb-gui-library-1605.2.1.41-forge
architectury-1.13.153-forge

Am I missing something?

**Comment by Eric-01** [comment]
Hasn't the FTB GUI Library been superseded by FTB Library?

And by the way, you can use MrCrayfish's Configured mod instead. It makes mod configs accessible in game for (almost) **all** Forge mods, not just the JEI's one. You should give it a try ;)

**Comment by garrowson** [comment]
https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge
Is this not the right one?
In the source you find dev.ftb.mods.ftblibrary which should be the updated path for issue/commit "Update FTB Library integration (#2334)"

I already tried MrCrayfish's Configured, but while it is indeed a good mod it just isn't what I want/seek. Besides I eventually will install a few other things from the FTB mods. Meanwhile it will do as a workaround.

**Comment by Eric-01** [comment]
I thought you were trying to use the old FTB GUI Library. My bad. Nevermind then.

Speaking of Configured, JEI could simply detect whether it is installed or not, and when it is, link the wrench button to the JEI config GUI dynamically generated by Configured. IMO there's nothing wrong in depending on the FTB library as long as it doesn't depend on yet another dependency — Fabric guy's Architectury mod ;p

**Comment by garrowson** [comment]
It detects Configured? The wrench button always sends me the require FTB Libary message. Regardless if I have FTB libary or Configured installed.

**Comment by SpokenSoftly** [comment]
Attempting to click the config button while loaded into a save puts up a message about requiring FTB Library, even with the latest FTB Library and Configured installed. Configured allows access from the main menu, but changes don't appear to carry over to existing saves.

I'm fairly sure that Curse's FTB Library is deprecated altogether, the page is "FTB Library" but the name shows as "FTB GUI Library" within the mods menu accessed from the main menu, and the description is "FTB GUI Library adds nothing."

**Comment by garrowson** [comment]
The internal name for FTB Library has been updated. They may have forgotten to change the mod description.

And a libary indeed does add nothing by itself. It only provides optimal code to be used by other mods like jei.

**Comment by SpokenSoftly** [comment]
My poor reading comprehension aside, this is indeed an issue with the latest update. Reverting to version 7.6.4.90 fixes the issue.

**Comment by garrowson** [comment]
> ... Reverting to version 7.6.4.90 fixes the issue.

That fixed it thanks!

Funny, however that the "Update FTB Library integration" of the latest version actually broke it...

**Comment by MaxNeedsSnacks** [comment]
That PR was merged a bit prematurely as the refactored version of FTB Library isn’t out on Curseforge yet (we’re still making changes to some dependants of it and want to test those first because there’s gonna be quite a few breaking changes)

For now rolling back to the version mentioned above should be fine! ^^
