### ISSUE TITLE
Regression! When ghost item handler is enabled you can no longer click to see recipes

### ISSUE THREAD

**Issue by Darkere** [mezz/JustEnoughItems#2352]
Tested with RS 1.9.12 and jei-1.16.5-7.7.0.91

Original feature request: #1307

**Comment by Spongman** [comment]
how do you disable this "ghost item handler"? this completely breaks Refined Storage's pattern grid - all it does is flash the pattern grid green when you click. useless.

**Comment by Darkere** [comment]
@Spongman you are still able to use the JEI recipe keybind  to look up the recipe. 
I've taken a look at how you could potentially fix this, however the new mouse handling doesn't really support this. This will require a bit of a hacky solution.

**Comment by Spongman** [comment]
the problem with using the keybind is that often the focus is in a textbox so it just types that character in the textbox. what is even the benifit of this new mouse handling, anyway?

**Comment by Spongman** [comment]
can we just back out 364d6975a5ad37de2f4413656d94d4efa2f25ad9 ?

**Comment by LoneStarrr** [comment]
This has been driving me nuts for a good half year. My solution was to right click the configure button to get the focus off the text screen, but it makes it so much more frustrating to work with e.g. RS pattern grid. I'd gladly sacrifice the ghost dragging behavior in favor of a working solution. @Spongman have you tried building JEI with that patch reversed to see if that fixes the behavior?

**Comment by Spongman** [comment]
no, unfortunately i'm not set up to build this to try.

the frustrating thing is that this could easily be unambiguously handled by changing the action to mouse-up:
- mouse-down + mouse-move => ghost drag
- mouse-down + mouse-up => click

**Comment by LoneStarrr** [comment]
A quick hack later and I have the original behavior working @Spongman . It's not worthy of a PR as it's an extremely crude fix, but I would be extremely happy if this could at the very least be a configurable option so we have something for now @Darkere .

I'm not going to provide a build for this, but if you want to build yourself, here's the hack: https://github.com/LoneStarrr/JustEnoughItems/commit/a021d923cb2e07762de852047a8fe157e7d25bad

**Comment by Darkere** [comment]
> the frustrating thing is that this could easily be unambiguously handled by changing the action to mouse-up:
> mouse-down + mouse-move => ghost drag
> mouse-down + mouse-up => click

Yes. Unfortunately the system that was build, cannot really make this work. I'm sure there is some kind of hack you could write to make it work, but such a thing is fairly unlikely to be merged. 

The change above disables the ghostingredienthandler completely which is not a solution.

**Comment by mezz** [comment]
Thanks for the report!
I just pushed a big fix for a bunch of edge-case bugs in click and drag handling. This should be released for 1.16 shortly, and I'll get it working on 1.17 next.

Thanks for your patience on this, complex mouse handling in Minecraft is hard to get right and takes a lot of time to write and test! Please let me know if you run into any additional issues.
