### ISSUE TITLE
Using `IGuiContainerHandler.getGuiExtraAreas()` with an area at the top moves everything down

### ISSUE THREAD

**Issue by yueh** [mezz/JustEnoughItems#2353]
When telling JEI about extra gui areas while these are located at the top of the screen and overlap the previous/next page buttons, it will cause everything to be moved down until it has an area big enough to fit JEI in terms of width.

![2021-05-15_20 17 15](https://user-images.githubusercontent.com/151949/118374121-aca57080-b5ba-11eb-885a-f48bfc27eb94.png)
This will also apply to the bookmark list, which is not shown here.

If there is enough space for the buttons it will behave normally and just wrap the list around the areas like here
![2021-05-15_20 26 56](https://user-images.githubusercontent.com/151949/118374360-fe022f80-b5bb-11eb-978f-4c41434c300b.png)

A better solution here might be to reduce the width to still allow JEI to expand to the full height, similar to how it dynamically adjusts to a different screen ratio.

In case you want to reproduce it, it happens with the just released 8.4.0-alpha.1 of AE2.
You can use the last button on the left side to toggle between both modes.

**Comment by mezz** [comment]
Thanks for the report yueh!
I have updated the logic to try to maximize the rectangular area for items when a modded GUI intersects with the navigation controls.
I also update the default config to show 9 columns of items (still configurable to whatever you want) which should help keep most cases like this looking consistent even without the new logic.

**Comment by yueh** [comment]
Many thanks for the quick fix and also new build.
