### ISSUE TITLE
Provide a warning level for `IRecipeTransferError` or similar

### ISSUE THREAD

**Issue by yueh** [mezz/JustEnoughItems#2354]
Currently we are facing the issue that the type of `IRecipeTransferError` is either a hard error or no immediate feedback except for the most observant players paying attention to the tooltip before clicking a button.

Neither is really adequate in some cases to provide useful feedback to a player. Either by not getting their attention quickly or by having them hit a hard wall, which in instead would be easy to solve by a human. For example it is not always easy to match existing itemstacks with NBT against valid ingredients. It can easily be too restrictive and miss valid ones or too permissive and then not work as expected.

In these cases it would be really helpful to provide additional feedback in an immediate way. E.g. by allowing the button to be tinted or just marked as warning and then use red instead of gray. Or replace the `+` with `!`. Or some other symbol. However this might be tricky for texture packs.
This would allow us to inform players about potential issues in a quick and easy way. But not forcing them into a hard wall, because they just put a ingredient into their backpack and the only option is to either cancel everything, grab the missing item and then start all over. Worst case having to traverse a couple levels through a crafting chain again, because they just forgot what intermediate material it was.
Or are left confused because one item not being moved, while it's clearly in their inventory.

Another option might be to allow for a modifer to be pressed similar to `shift`. Say use `ctrl` to allow them to bypass it and allow the the transfer handler to use a best guess approach and provide as many ingredients as possible and maybe leave just 1 or 2 for the player to resolve instead of forcing them to remember all 9 ingredients.

This might probably overlap with  #1040 to some degree.

**Comment by mezz** [comment]
We added support for `COSMETIC` errors here: https://github.com/mezz/JustEnoughItems/pull/1971
I think setting the button to yellow/orange when it's a `COSMETIC` error might solve this issue.

**Comment by yueh** [comment]
Yes, I was aware of the `COSMETIC` type. It was just mostly missing a clear indication besides a custom tooltip.

Simple color change like now is fine for us. I was just worried about custom texture pack as this might clash with their color theme.
Also in case someone uses it for a custom tooltip now, but does not want a different button color.

**Comment by mezz** [comment]
I think this can be improved on still, but for now I think the extra color is better than not having it.

**Comment by mezz** [comment]
This has been improved by https://github.com/mezz/JustEnoughItems/pull/2971, which lets you set the button to a custom color.
