### ISSUE TITLE
FTB Library installed but stating its not

### ISSUE THREAD

**Issue by Joshernoob** [mezz/JustEnoughItems#2355]
Issue: to put it simple when i try to the config button to change some thing like center search bar and so on it states that the needed lib ( FTB Library) is not installed even though the mod is in the pack.

Minecraft Version: 1.16.5
Pack: Dev- Magic Sky
Mod Version: jei-1.16.5-7.7.0.91
Lib Version: ftb-gui-library-1605.2.1.41-forge
![ttt1](https://user-images.githubusercontent.com/64944433/118407841-921dd680-b650-11eb-9ff7-364c170c2578.png)
![ttt2](https://user-images.githubusercontent.com/64944433/118407842-92b66d00-b650-11eb-95f2-09ebd77ed68a.PNG)
![ttt3](https://user-images.githubusercontent.com/64944433/118407844-934f0380-b650-11eb-8f5b-8087789f9f6e.PNG)

This seem like a small bug but like one none the less so I'm hoping this can get fixed soon

**Comment by Wapplee** [comment]
> Issue: to put it simple when i try to the config button to change some thing like center search bar and so on it states that the needed lib ( FTB Library) is not installed even though the mod is in the pack.
> 
> Minecraft Version: 1.16.5
> Pack: Dev- Magic Sky
> Mod Version: jei-1.16.5-7.7.0.91
> Lib Version: ftb-gui-library-1605.2.1.41-forge
> ![ttt1](https://user-images.githubusercontent.com/64944433/118407841-921dd680-b650-11eb-9ff7-364c170c2578.png)
> ![ttt2](https://user-images.githubusercontent.com/64944433/118407842-92b66d00-b650-11eb-95f2-09ebd77ed68a.PNG)
> ![ttt3](https://user-images.githubusercontent.com/64944433/118407844-934f0380-b650-11eb-8f5b-8087789f9f6e.PNG)
> 
> This seem like a small bug but like one none the less so I'm hoping this can get fixed soon

happening to me too.

**Comment by ModernGamingWorld** [comment]
This is also happening to me as well, I know the FTB Developer has been super busy redoing alot of things and he changed the mod Name from FTB Gui Library  to FTB Library (Forge)

**Comment by GamerRaven81** [comment]
Ok, glad to know I'm not alone. I thought maybe I was installing mods wrong somehow. Hope this gets figured out soon. I can't stand My search bar off to the right. LoL

**Comment by mezz** [comment]
Thanks for the report!
Paging @LatvianModder for clarification on this issue

**Comment by MaxNeedsSnacks** [comment]
See https://github.com/mezz/JustEnoughItems/issues/2351#issuecomment-841796827 for reference:

> That PR [to support the new FTB Library] was merged a bit prematurely as the refactored version of FTB Library isn’t out on Curseforge yet (we’re still making changes to some dependants of it and want to test those first because there’s gonna be quite a few breaking changes)

~~Basically, for now, I recommend you guys just downgrade (or that mezz reverts the changes made by that PR until we actually make a CurseForge release) for the next couple of days until we can actually push releases to CurseForge (unfortunately I can't give a *concrete* ETA here but it should be **very** soon hopefully)~~

Nevermind, I convinced Lat to [release them to CurseForge as alphas](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/3334387) lol
Please keep in mind that they're still most likely a *bit* buggy, but if you're just using FTB Lib you **should** absolutely be fine!

**Comment by benbenlaw** [comment]
can confirm still happens on the latest version of JEI "jei-1.16.5-7.7.0.103.jar"

**Comment by hron84** [comment]
@mezz it would solve a problem if you mark all affected JEI versions as alpha on CF, to prevent auto-upgrading 'til the FTB Library change would be merged. I would not break anyone who already installed this verison of JEI but would make sure stop creating issues like this.

**Comment by Fireztonez** [comment]
I confirm this issue still happens with the latest current version.

**JEI version:** 1.16.5 - 7.7.0.106
**FTB Library:** 1605.2.1.41
**Minecraft:** 1.16.5
**Forge:** 36.1.31

**Comment by mezz** [comment]
You will need to install the FTB Library alpha (1605.3.1 or higher) available here:
https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/all?filter-game-version=2020709689%3A8203

**Comment by mezz** [comment]
I have removed support for FTB Library and now recommend installing the Configured mod to configure mods in-game. Sorry, I wish this was built into Forge like in previous versions.

**Comment by hron84** [comment]
@mezz is there any chance it makes its way to Forge sometime later?
