### ISSUE TITLE
Client crash in latest 

### ISSUE THREAD

**Issue by CritFlaw** [mezz/JustEnoughItems#2356]
Thank you for reporting!

For issues:
https://pastebin.com/CdKiMi7z

Forge - 36.1.12
Minecraft - 1.16.5
JEI - jei-1.16.5-7.7.0.94

Recreating:
When trying to see the uses/recipes from an item in inventory, the log above is produced

**Comment by mezz** [comment]
Thanks for the report! This has been fixed here: https://github.com/mezz/JustEnoughItems/commit/7371edbda142621c9fe2bff60fe1bf9b53e0abc0
Please try the latest version and let me know if you run into any other issues.

**Comment by CritFlaw** [comment]
Yep, seems to be fixed, thank you
