### ISSUE TITLE
Item List not changing width with GUI scale

### ISSUE THREAD

**Issue by CisluneMusic** [mezz/JustEnoughItems#2360]
Thank you for reporting!
 
Minecraft: 1.16.5
Forge: 36.1.23
JEI: 7.7.0.98

No matter what GUI scale I use, the width of the item list doesn't change accordingly (other than GUI scale 4, where it narrows down one column). I've tried multiple versions spanning across MC 1.16, but each one has the same issue.

**Comment by BlackInkBlood** [comment]
I am having this issue as well. I was trying to look into it more, but this was the only thing I could find on the matter.

**Comment by CisluneMusic** [comment]
It doesn't seem to have been caused by a mod either, as it still happens on its own. Quite annoying considering that I play on a fairly low GUI scale.

**Comment by mezz** [comment]
Thanks for the report!
You can set the max width of the item list in the config, by default it's 9 columns right now. 
If you want to have it take up as much room as possible, you can set it to like 100.

**Comment by CisluneMusic** [comment]
Oh, thanks!

**Comment by Cinderheart** [comment]
Same issue here, before it changed with the GUI. Nice to know its just a config, I was just wondering why it changed?

Also, it used to be that if you installed FTB GUI Library it would let you edit the GUI in game. Now it still prompts you to do that even if the other mod is installed.

**Comment by mezz** [comment]
This was changed because people with large screens were getting big slowdowns when displaying too many items. I limited the default to 9 columns to help with performance for most people.  You can configure it to display more if you have a powerful computer.
