### ISSUE TITLE
JEI shading items

### ISSUE THREAD

**Issue by rvincent22** [mezz/JustEnoughItems#2361]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

So, when I'm playing a modded world (multiple mods including JEI), when I press E I see all my items BUT they all look different. What I mean by that is the block shading is incorrect, this Is a new problem, I didn't have this problem before. I searched up on YT and all of their JEI screens look brighter instead of how mine looks, and the items like diamond etc. are completely darkened and you can barely see it. I'm not a professional in JEI, is there a way to fix this or did I accidentally press a command that did this? Thank you.

![image](https://user-images.githubusercontent.com/84468349/118855933-58dda480-b8a4-11eb-9f65-93326c54ebb9.png)

^ Image for how my JEI screen looks.

![image](https://user-images.githubusercontent.com/84468349/118856619-26807700-b8a5-11eb-9db0-a1e56f9b1ce8.png)

^ Items instead of blocks, they are even more darkened.

**Comment by CREEATION** [comment]
does this also happen in an instance where you're only using JEI and no other mods?

if not, try disabling your mods one-by-one and see which one might be causing this issue.
(**example**: rename _`Clumps-6.0.0.22.jar`_ to _`Clumps-6.0.0.22.jar.disabled`_)

**Comment by rvincent22** [comment]
Okay, I'll try that. 

Edit: IT WORKED, THANK YOU SO MUCH. I just put all the mods out and it worked well, I'm now gonna use your method and see which mod is causing the problem.

![image](https://user-images.githubusercontent.com/84468349/119172792-5ad66d80-ba34-11eb-871d-60bc4cca87ca.png)

**Comment by CREEATION** [comment]
great! make sure to report the JEI-breaking mod back here 🐢

**Comment by rvincent22** [comment]
Will do.
Edit: really busy kinda, I'll post it by today or tomorrow especially since the process to figure the mod is so tedious. But don't worry, it'll happen soon.

**Comment by mezz** [comment]
One way to check a little faster is to disable half at a time.
If it's broken, you know the broken mod is somewhere in that half, otherwise it's in the other half. Then you can keep repeating that process on whatever's left until you find it.

It's a bit tricky since some mods depend on libraries (just leave library mods enabled if you can). With 100 mods you'll finish in fewer steps by halving each time: 50, 25, 13, 7, 4, 2, 1

**Comment by rvincent22** [comment]
Ok, thanks.

**Comment by DamienTC** [comment]
any update on the mod?

**Comment by rvincent22** [comment]
> any update on the mod?

Well, I had an optifine mod and when I removed it, the issue stopped. So I guess it's this optifine. Actually, after some research. I saw that optifine 1.16.5 only goes up to forge 36.1.0 and I'm on forge 36.1.13 so it's just that the version was wrong. yes, super lame response but it happens.

**Comment by AbedMir31** [comment]
It's because of shaders, but I am not sure how to fix it still

**Comment by AbedMir31** [comment]
Issue may be related to the latest optifine. Downgraded to G7 and it fixed.
