### ISSUE TITLE
[1.12.2] JEI causing issues when opening 

### ISSUE THREAD

**Issue by ajpms** [mezz/JustEnoughItems#2362]
i've been working on a pack and JEI is causing issues whenever I try use it, I don't know if it's a compatibility issue or what.
here's the crash report

https://paste.dimdev.org/daheburahu.mccrash

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2021-05-24 02:04:00 BST
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
    at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
    at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:596)
    at net.minecraftforge.registries.GameData.freezeData(GameData.java:249)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 674496488 bytes (643 MB) / 3688366080 bytes (3517 MB) up to 7635730432 bytes (7282 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 42 mods loaded, 42 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                  | Version           | Source                                     | Signature                                |
       |:------ |:------------------- |:----------------- |:------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft           | 1.12.2            | minecraft.jar                              | None                                     |
       | LCHIJA | mcp                 | 9.42              | minecraft.jar                              | None                                     |
       | LCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge               | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | antiqueatlas        | 4.6.3             | antiqueatlas-1.12.2-4.6.3.jar              | None                                     |
       | LCHIJA | antiqueatlasoverlay | 1.2               | antiqueatlas-1.12.2-4.6.3.jar              | None                                     |
       | LCHIJA | astikorcarts        | 1.12.2-0.1.2.7    | astikorcarts-1.12.2-0.1.2.7.jar            | None                                     |
       | LCHIJA | atlasextras         | 1.8               | AtlasExtras-1.12.2-1.8.jar                 | None                                     |
       | LCHIJA | bibliocraft         | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar          | None                                     |
       | LCHIJA | crafttweaker        | 4.1.20            | CraftTweaker2-1.12-4.1.20.646.jar          | None                                     |
       | LCHIJA | waila               | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                | None                                     |
       | LCHIJA | jei                 | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                  | None                                     |
       | LCHIJA | tfc                 | 1.7.18.176        | TerraFirmaCraft-MC1.12.2-1.7.18.176.jar    | None                                     |
       | LCHIJA | ca                  | 1.0               | Caffeine [TFC Addon]-1.2.1.jar             | None                                     |
       | LCHIJA | cellars             | 1.22.6            | CellarAddon-1.22.6.jar                     | None                                     |
       | LCHIJA | ctgui               | 1.0.0             | CraftTweaker2-1.12-4.1.20.646.jar          | None                                     |
       | LCHIJA | crafttweakerjei     | 2.0.3             | CraftTweaker2-1.12-4.1.20.646.jar          | None                                     |
       | LCHIJA | crafttweakerutils   | 0.7               | crafttweakerutils-0.7.jar                  | None                                     |
       | LCHIJA | ctm                 | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                  | None                                     |
       | LCHIJA | customnpcs          | 1.12              | CustomNPCs_1.12.2-(05Jul20).jar            | None                                     |
       | LCHIJA | debark              | 0.1.2             | Debark-0.1.2.jar                           | None                                     |
       | LCHIJA | firmalife           | 0.3.9             | firmalife-0.3.9.jar                        | None                                     |
       | LCHIJA | gravestone          | 1.10.3            | gravestone-1.10.3.jar                      | None                                     |
       | LCHIJA | matchlockweapons    | 0.8               | Matchlock Guns Mod-1.12.2-7a.jar           | None                                     |
       | LCHIJA | mtrm                | 1.2.2.30          | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar | None                                     |
       | LCHIJA | ordinarycoins       | 1.5               | ordinarycoins-1.12.2-1.5.jar               | None                                     |
       | LCHIJA | parry               | 1.0               | parry-1.0-hotfix.jar                       | None                                     |
       | LCHIJA | patchouli           | 1.0-23.6          | Patchouli-1.0-23.6.jar                     | None                                     |
       | LCHIJA | rocksalt            | 1.0.3             | rocksalt-1.0.3.jar                         | None                                     |
       | LCHIJA | rustic              | 1.1.7             | rustic-1.1.7.jar                           | None                                     |
       | LCHIJA | tfcthings           | 1.3.3             | terrafirmathings-1.3.4.jar                 | None                                     |
       | LCHIJA | tfcmetallum         | 1.4.0             | TFC-Metallum-MC1.12.2-1.4.0.jar            | None                                     |
       | LCHIJA | tfc_decoration      | 1.0.7             | tfc_decoration-1.0.7.jar                   | None                                     |
       | LCHIJA | aged_drinks         | 1.0.1             | TFCAgedDrinks-1.0.7.jar                    | None                                     |
       | LCHIJA | tfctech             | 1.2.16            | TFCTech-Unofficial-MC1.12.2-1.2.16.jar     | None                                     |
       | LCHIJA | tfcompat            | 1.2.1             | tfccompat-1.2.1.jar                        | None                                     |
       | LCHIJA | tfcstorage          | 1.0               | TFCStorage-1.0.7.jar                       | None                                     |
       | LCHIJA | tfctweaker          | 1.0.7             | tfctweaker-1.0.7.jar                       | None                                     |
       | LCHIJA | vanillafix          | 1.0.10-150        | VanillaFix-1.0.10-150.jar                  | None                                     |
       | LCHIJA | gvc                 | 1.2.5             | Voice Chat Reloaded-1.2.5.jar              | None                                     |
       | LCHIJA | walljump            | 1.3.2             | walljump-1.12.2-1.3.2.jar                  | None                                     |
       | LCHIJA | waterflasks         | 1.9               | waterflasks-1.9.jar                        | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9171' Renderer: 'Intel(R) HD Graphics 610'
  Patchouli open book context: n/a
  Suspected Mods: Unknown
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 610 GL version 4.6.0 - Build 27.20.100.9171, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Pentium(R) CPU 4417U @ 2.30GHz

**Comment by ajpms** [comment]
this error only happens when using JEI

**Comment by Ommina** [comment]
Well -- it says to check log for details.  Did you?

debug.log, presumably!
