### ISSUE TITLE
JEI gui only half screen size

### ISSUE THREAD

**Issue by ThaAwesomePanda** [mezz/JustEnoughItems#2364]
![2021-05-25_00 23 41](https://user-images.githubusercontent.com/84762383/119443663-9355a000-bcef-11eb-9332-2716dd734426.png)

Anyone else having this issue?  Yes it increases when I scale up the normal gui, but I play on medium gui, and it should fill the all the way up to the crafting menu.

**Comment by Ommina** [comment]
See #2360
