### ISSUE TITLE
[1.16.5] Can't access Wrench Menu

### ISSUE THREAD

**Issue by TrickyEagle** [mezz/JustEnoughItems#2367]
So my friends and I are attempting to make a "custom" modpack for us to play on a server together.  However, one of the issues we are running into while testing it out is that when we go to click on the JEI wrench to open that menu, it says to install FTB Library (even though we already have that in the client and server stuff).
Below I've included the client and server zips. Any help would be appreciated! Ty

[Skydragon_SERVER_1.16.5-0.4.zip](https://github.com/mezz/JustEnoughItems/files/6542203/Skydragon_SERVER_1.16.5-0.4.zip)
[Skydragon_CLIENT_1.16.5-0.4.zip](https://github.com/mezz/JustEnoughItems/files/6542204/Skydragon_CLIENT_1.16.5-0.4.zip)

**Comment by AlisterGontineac** [comment]
Same

**Comment by Eric-01** [comment]
As a good workaround you can use MrCrayfish's Configured mod instead. It makes mod configs accessible in game for almost all Forge mods, not just the JEI's one.

**Comment by twothe** [comment]
I have the same issue. Just installed the latest JEI version in a new mod pack I am trying and it gives me that error.

**Comment by IMarvinTPA** [comment]
The mods you need are [Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-forge) (I have 1.17.17) and [FTB Library Legacy (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-legacy-forge) version 1605.3.1-build.10.  Newer ones changed the name of the mod and don't register as being installed.

**Comment by NovaLynxie** [comment]
Erm... @IMarvinTPA the linked FTB Library is for Minecraft 1.12.2, not 1.16.5. I don't see the mentioned version either.
Unless you mean the [FTB Library (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge) one since this is where they are stored.

**Comment by IMarvinTPA** [comment]
Curse wasn't working at the time I wrote the response: https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/3325106 although newer options in the alpha branch might work too.

**Comment by mezz** [comment]
Thanks for the report!
It seems like FTB Library hasn't been very dependable, I have removed support for it and now recommend installing the Configured mod to configure mods in-game. Sorry, I wish this was built into Forge like in previous versions.
