### ISSUE TITLE
Hidden items won't stay hidden

### ISSUE THREAD

**Issue by chris819t** [mezz/JustEnoughItems#2372]
Title simply states what the issue is. I'm using the keybinding "Toggle Hide/Edit Mode" and i set it to CTRL + H and it will go into the mode but when i hide something in JEI then exit the mode it just unhides all the items i wanted to hide.
Please help, this feature is a major thing for me. I am using the 1.16.5 forge version btw.

I just noticed when I hid some things and reloaded the game those items are hidden forever... how do unhide them? When i go into the mode i don't see them anymore

**Comment by Darkmega18** [comment]
I have this also. I've just gone through and wildcart hidden all the potion arrows and the over extra stuff to take down a few pages of JEI, but when I toggle off hide mode, the hidden things don't go poof until I turn back on hide mode again.

Although:
> I just noticed when I hid some things and reloaded the game those items are hidden forever... how do unhide them? When i go into the mode i don't see them anymore

oh, I guess thats gonna happen to me once my game is closed and brought back up then. :V

**Comment by chris819t** [comment]
...I guess this GitHub is abandoned now

**Comment by Darkmega18** [comment]
![welp](https://media1.tenor.com/images/40ccff0392ce74219aab17db3e3f8adf/tenor.gif?itemid=5089055)

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the latest versions of JEI for 1.16, 1.17 and 1.18.
You can bind a hotkey to toggle the "hide items" mode on and off in the Minecraft controls, and the hidden items will stay hidden properly.
