### ISSUE TITLE
[Suggestion] 1.17 update?

### ISSUE THREAD

**Issue by orrinpants** [mezz/JustEnoughItems#2376]
Thank you for suggesting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

I want 1.17 support so I can see the new items from it.

**Comment by mezz** [comment]
Thanks for the request!
Sorry, JEI depends on Minecraft Forge, which is not available for 1.17 yet.

**Comment by orrinpants** [comment]
I thought there was 1.17 forge

**Comment by orrinpants** [comment]
Back to this post, it's actually only fabric that has 1.17.

**Comment by mezz** [comment]
JEI is out for 1.17 on Forge now.
