### ISSUE TITLE
Crash Upon Opening Player Inventory

### ISSUE THREAD

**Issue by anatevka-xD** [mezz/JustEnoughItems#2377]
Game crashes when I try to open the player inventory. I looked through the crash report but can't figure it out.
There are a lot of mods in the pack.

https://gist.github.com/anatevka-xD/43ad6eddb81d3622b8a32a074e4fb2fe

**Comment by hydroartdragon2003** [comment]
Hi I'm the author of the mod you have installed named "Generic Ecosphere"; as of right now, the mod isn't compatible with JEI, though, I am trying to figure out how to fix this as this crash is likely on my end.

**Comment by anatevka-xD** [comment]
Gotcha! I want JEI more than Generic Ecosphere so I'll remove that for now. Thanks!
