### ISSUE TITLE
Tooltips get put below the next recipe's IDrawables

### ISSUE THREAD

**Issue by yrsegal** [mezz/JustEnoughItems#238]
using `IRecipeWrapper#getTooltipStrings`

Item tooltips don't do this.

<img width="504" alt="screen shot 2016-04-04 at 3 46 10 pm" src="https://cloud.githubusercontent.com/assets/6596492/14261040/c3500a92-fa7c-11e5-88ba-1258ea883fa1.png">

Using 1.9:3.2.5.179

**Comment by mezz** [comment]
Thanks for the report! Fixed in the latest version.
