### ISSUE TITLE
JEI not working properly on minecraft 1.12.2

### ISSUE THREAD

**Issue by kaka2hiii** [mezz/JustEnoughItems#2381]
I have been playing for 1 week on pixelmon with jei and it doesn't show me the crafting recipie when i push my keybind it shows the first screen shot and if i push my use keybind it shows the 2nd screenshot
Could anyone help me i have already redowladed it and minecraft too.
Thx.
![2021-06-06_18 09 24](https://user-images.githubusercontent.com/85450836/120931652-dc93ef80-c6f2-11eb-9d1c-32cc7ff72252.png)
![2021-06-06_18 09 43](https://user-images.githubusercontent.com/85450836/120931659-def64980-c6f2-11eb-9b36-f609c2d8350d.png)
![2021-06-06_18 09 51](https://user-images.githubusercontent.com/85450836/120931660-e0277680-c6f2-11eb-9fb8-234cabf7b639.png)
![2021-06-06_18 10 01](https://user-images.githubusercontent.com/85450836/120931662-e1f13a00-c6f2-11eb-894b-4b4c499254bd.png)

**Comment by kaka2hiii** [comment]
up

**Comment by asolisq** [comment]
I have the same issue, any solution?
