### ISSUE TITLE
jei crash on item source  

### ISSUE THREAD

**Issue by DjBigNic977878** [mezz/JustEnoughItems#2383]
[crash-2021-06-07_14.21.17-client.txt](https://github.com/mezz/JustEnoughItems/files/6612263/crash-2021-06-07_14.21.17-client.txt)
[crash-2021-06-07_15.05.41-client.txt](https://github.com/mezz/JustEnoughItems/files/6612264/crash-2021-06-07_15.05.41-client.txt)

please Help!!!

**Comment by Ommina** [comment]
@IMarvinTPA Does this relate to the recent tool sorting addition?  It seems to mention it, but I can't tell if it from JEI or, as is so often the case, some other mod misbehaving and JEI getting the blame.

**Comment by IMarvinTPA** [comment]
@Ommina  Yep.  I'll fix it tonight when I get back from work.
