### ISSUE TITLE
[1.16.5] JEI Not Working on Server if you Join Right After Startup

### ISSUE THREAD

**Issue by Crazydude323** [mezz/JustEnoughItems#2384]
I run a small modded server for some friends and I, and after a series of mod updates we recently did, JEI has been experiencing serious issues.

If one of us loads up Minecraft and goes right to joining the server, JEI doesn't show up at all. We've confirmed that it's not just an issue of being disabled to start with; using the keybind to toggle JEI does nothing.

However, if we load up a single player world first, JEI works fine there. If you view a recipe in single player before exiting back to the main menu, and then join the server, it works on the server just fine.

We're currently on JEI version 7.7.0.101, since the newest version had a different issue where it would load but wouldn't show recipes. I plan on testing version 7.7.0.103 next to see if that works better.

**Comment by Crazydude323** [comment]
103 has the same issue that 104 (the latest version) has, where it shows up on the side but won't provide recipes for any items.

**Comment by Ommina** [comment]
See also #2213 

If I recall correctly, this seems to come about when a mod does something silly, causes an exception, and prevents JEI from getting the 'recipes are loaded' event.  Loading in single player triggers said event, and allows JEI to complete.

I'm not sure if there is anything in debug.log to indicate what is going wrong where, but it is probably worth a look.

**Comment by Crazydude323** [comment]
I didn't see anything in the server's debug.log to indicate a problem when I used ctrl + f to find "jei", but I did notice in the issue you mentioned that Supplementaries is a potential cause for the issue, and that is one of the mods that I updated on the last server update.
Given this information, I'll try and downdate Supplementaries to the previous version, and see if that fixes things. Thanks for pointing me in a direction; hopefully it's the right one!

**Comment by Ommina** [comment]
The debug.log wouldn't say anything about JEI, since it is not JEI code that is crashing.  I'm not honestly certain any exception will be logged at all, but since you mentioned Supplementaries, maybe take a peek in the (client!) debug.log for an exception from them.

Please let us know what you learn.  It looks like Supplementaries has a significant number of json parsing errors in its recent release, but I'm not familiar enough with the code to point any fingers.  I may need to defer to mezz here.

**Comment by Crazydude323** [comment]
I tried reverting to the older version of Supplementaries, but that did not fix the issue. A lot of mods were updated the last time I updated the server so it's probably going to be hard to narrow it down. The next thing I plan on trying is Enchantment Descriptions, since that's another mod that was mentioned in the other issue.

**Comment by Crazydude323** [comment]
Also wasn't it. Which means I'm going to have to bite the bullet and do things the really slow way, testing in halves.

**Comment by Crazydude323** [comment]
I have found the issue! It's from a newer mod called [Malum](https://www.curseforge.com/minecraft/mc-mods/malum).

Given how new the mod is, it's almost certainly an issue on their end rather than on JEI's end. So I'll be closing this issue myself, and reporting this to them instead. Hopefully they're able to fix it, because it looks rather promising.

**Comment by Ommina** [comment]
I'm glad you were able to determine the cause; it's always difficult when you have to start the "remove half and try again" game.

The author looks fairly responsive, hopefully they won't have any troubles tracking it down.

**Comment by Crazydude323** [comment]
Nevermind, that was apparently NOT the issue. Even though it did fix it for a second, it's now broken again. Son of a gun.

I'm honestly at my wits end here.

**Comment by Crazydude323** [comment]
The actual issue, it seems, is with _either_ Essentials, or Crossroads MC. Crossroads depends on Essentials, so it could really be either one.

I'll run a couple more tests before closing this issue though; I've learned that lesson after prematurely thinking it was Malum.

**Comment by Crazydude323** [comment]
Disabling both Essentials and Crossroads fixed the issue. This I know to be true. I then re-enabled Essentials, and JEI still functions fine, so you'd think that Crossroads must be the issue, right?

Except I then enable Crossroads, and JEI is still working fine, despite the fact that _disabling Crossroads_ is what fixed the problem.

So this problem is either completely random, and there's no one cause for it occurring, OR the problem is now permanently fixed, even though all I did was disable a mod, restart the server, and then turn the mod back on and restart the server again. I expect the only way I'll be able to figure out which of those is the case is with time.

**Comment by Crazydude323** [comment]
I am now confident that I've found the issue! It is not at all what I thought.

I have a few Data Packs on the server to change recipes that CraftTweaker can't interact with; usually recipes which involve modded crafting mechanisms. Disabling and re-enabling a whole bunch of mods shifted around the order things were loading in, meaning that some of the datapacks that affected nothing but recipes weren't loading at all.

I had a datapack that was meant to change a few recipes from Crossroads's Beam Transmutation system. When that datapack loads ahead of Crossroads (which it has to in order to do anything), it breaks JEI. I have no idea why this is, nor if it's something that has to be fixed on JEI's end or on Crossroads's end. But at the very least, I'm 100% certain that this is what's causing the issue, even if I don't know _why_ it's causing an issue.

Not sure if I should change the title of this issue to reflect my new information, or if I should close this issue and make a new one (since this issue has gotten quite long). For now, I'll do nothing here, and report this on Crossroads's tracker. Ommina seems knowledgeable regarding this repository, so I'll wait for their opinion on whether to rename this issue, or close it and make a new one.

**Comment by Crazydude323** [comment]
Not sure if I should change the title of this issue to reflect my new information, or if I should close this issue and make a new one (since this issue has gotten quite long). For now, I'll do nothing here, and report this on Crossroads's tracker. Ommina seems knowledgeable regarding this repository, so I'll wait for their opinion on whether to rename this issue, or close it and make a new one.
