### ISSUE TITLE
Default sort order not working properly

### ISSUE THREAD

**Issue by Feramance** [mezz/JustEnoughItems#2387]
I am playing All The Mods 6 and I tried deleting configs and allowing Minecraft to regenerate the configs however I cannot seem to get the original sort order. Would you be able to let me know how to obtain the default sort order that has been the norm for years?

Thanks,
Feramance

**Comment by mezz** [comment]
Thanks for the report!

@IMarvinTPA it seems like people are having issues with the new default sort order. Can you revert the config defaults so that it is like before, at least until the in-game config is ready?

**Comment by IMarvinTPA** [comment]
@Feramance Before starting the game, edit the jei-client.toml.
IngredientSortStages = ["MOD_NAME", "INGREDIENT_TYPE", "CREATIVE_MENU"]
@mezz Yeah.

**Comment by Feramance** [comment]
@IMarvinTPA Thanks, I tried to mess with those myself but didn't get the correct order. Thanks for the solution. Also I agree with @mezz, better to leave the default as it was until the in-game config is ready.

Thanks
