### ISSUE TITLE
Shift-clicking a recipe adds extra random block to the crafting grid

### ISSUE THREAD

**Issue by Hund** [mezz/JustEnoughItems#239]
Shift-clicking a recipe adds extra random block to the crafting grid. At least it seems to be a random item.

![](http://i.imgur.com/weHpqjk.png)
- Minecraft 1.8.9
- Forge 11.15.1.1808
- JEI 2.28.12.180
- [List of my mods](http://hastebin.com/wareteroke.txt)

**Comment by Prospector** [comment]
FYI you don't need to shift-click. Just a normal click will do.

**Comment by Hund** [comment]
Oh. Old habit I guess. :)

**Comment by mezz** [comment]
Thanks for the report!
Does this always happen, or is it certain recipes?

Shift-Click will move as many items as it can into the crafting area, regular click will more one set.

**Comment by Hund** [comment]
Ah, didn't know that. JEI just keeps getting better and better. :) If I recall correctly it does always happen for me, if it's not a recipe with 9 items.

**Comment by Prospector** [comment]
Oh, I had no idea, thought just a normal click would do. Nevermind then, that's really useful.

**Comment by mezz** [comment]
Is this still a problem in the latest version? I haven't seen it happen in a long time, I think it may have been fixed.

**Comment by Hund** [comment]
I totaly forgot about this issue. It seems to be solved some time ago. :)
