### ISSUE TITLE
for some reason on curseforge (on the overwolf launcher) JEI does not show up for an option to download on 1.12.2 or below. Its really weird. Thats not the only mod either. Mods like JourneyMap, Iron Chest, and even LootBags and ProjectE. Please someone help me, I want to use these mods!

### ISSUE THREAD

**Issue by gamerpogmandude** [mezz/JustEnoughItems#2390]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by gamerpogmandude** [comment]
actually it turns out that it isn't on 1.13.2 either.

**Comment by mezz** [comment]
Please ask for help from Overwolf on their Discord server, this is not the right place.
