### ISSUE TITLE
Joining worlds takes a long time

### ISSUE THREAD

**Issue by NielsPilgaard** [mezz/JustEnoughItems#2391]
Joining both singleplayer and servers takes quite a while in Enigmatica 6, and I've noticed in the log that a large portion of that time comes from JEI loading: I've seen values ranging from 20 to 50 seconds. 

I was hoping there would be something I could do to make the process more performant? ^^'

### Versions
- Forge-1.16.5.36.1.16
- jei-1.16.5-7.7.0.104
- Modpack: Enigmatica 6 0.5.0-indev

### Latest.log
https://pastebin.com/dH2F0UuH

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/2383

**Comment by grundyboy34** [comment]
If your pack has Just Enough Resources (JER), try removing it. My JEI load time went from 34s to 7s with JER removed.

**Comment by NielsPilgaard** [comment]
Small note: I have Just Enough Resources included, removing it makes no difference as far as I can tell. 48 second startup.
