### ISSUE TITLE
Crashing when opening Player Inventory

### ISSUE THREAD

**Issue by TrickDevelopment** [mezz/JustEnoughItems#2392]
This is on a Forge instance with about 130 mods:

My world loads up fine, but when I try to open my inventory it crashes.

[crash-2021-06-09_15.02.46-client.txt](https://github.com/mezz/JustEnoughItems/files/6626286/crash-2021-06-09_15.02.46-client.txt)

**Comment by Ommina** [comment]
Hi!  See also #2383
