### ISSUE TITLE
[1.16.5]Mouse buttons in controlling 

### ISSUE THREAD

**Issue by NiTiSon** [mezz/JustEnoughItems#2395]
Don't works button 4 and 5 on mouse when i use this for view recipe and uses
_Maybe other mouse buttons, also doesn't works_

Other mods don't have this problem

Mod vers: 
jei-1.16.5-7.7.0.106.jar

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in JEI for 1.18+
