### ISSUE TITLE
Recipes in Furnaces display twice

### ISSUE THREAD

**Issue by LavaMunkee** [mezz/JustEnoughItems#2399]
All recipes in the furnace in 1.16.5, regardless of mod appear to display twice in the furnace basically doubling the number of recipes it has. This does not appear to affect any other form of crafting or any block with a GUI and recipes.

Attached is a screenshot of what the charcoal recipe look like, however it affects any recipe, I will note that when using F3+H to see the ID of a recipe both recipes shown have the exact same recipe ID.
![recipe_duplicate](https://user-images.githubusercontent.com/69769856/122431075-1e7a2c80-cf62-11eb-8fc2-76275245af01.png)

**Comment by willatendo** [comment]
This is something they can't fix; the people who have created the recipe must change to use a tag instead of an item. In other words, they can't fix this

**Comment by LavaMunkee** [comment]
This is a tag recipe, it accepts any minecraft:logs and even applies to recipes I have personally added using CraftTweaker, which I have specifically only added once.

**Comment by rlnt** [comment]
Did you remove the original furnace charcoal recipe which is added by default?

**Comment by LavaMunkee** [comment]
There is only one furnace recipe, the one shown there, both recipes shown have the exact same recipe meaning they are the same, as I mentioned this issue also applies to recipes that I have personally added which I have only added once

**Comment by rlnt** [comment]
Was not my question.

**Comment by LavaMunkee** [comment]
No I did not remove the furnace charcoal recipe which I added by default, nor did I add one
