### ISSUE TITLE
JEI / OptiFine Shaders incompatibility (Forge 1.16.5)

### ISSUE THREAD

**Issue by salisiumide** [mezz/JustEnoughItems#2400]
Is there a fix to this visual bug that occurs when one uses shaders and JEI at the same time? Blocks have weird shading and 2D items appear darkened (Minecraft version: 1.16.5).
![image](https://user-images.githubusercontent.com/64909490/122660097-10f1bc00-d187-11eb-8a83-512029b651f7.png)

**Comment by NathanLithia** [comment]
This is an issue when JEI is combined with Optifine 1.16.5 G8, Optifine 1.16.5 G7 does not introduce this issue,
https://github.com/sp614x/optifine/issues/5687
