### ISSUE TITLE
Server Disconnect on Join (Server Disconnect - Payload may not be larger than 1048576 bytes)

### ISSUE THREAD

**Issue by AlmightyChan** [mezz/JustEnoughItems#2401]
Any time I try and join our server I get this error I think it may be an error with JEI here are the logs it won't allow me to upload debug file though. 

If this is not a JEI error would you mind telling me who you think I should bring this error to.

[latest (2).log](https://github.com/mezz/JustEnoughItems/files/6690374/latest.2.log)

**Comment by Spudstak** [comment]
This is actually probably minecolonies, not JEI. This is a confirmed issue with minecolonies and I have experienced it with my own pack. 

https://github.com/ldtteam/minecolonies/issues/7331
