### ISSUE TITLE
Cycle behaviour on scrolling improvement

### ISSUE THREAD

**Issue by rlnt** [mezz/JustEnoughItems#2402]
It would be really nice if the cycling behaviour when scrolling with the mouse wheel could be improved a little.
I am a fan of the feature but what I am suggesting is a hybrid of the current functionality.

Current behaviour:
If you have multiple pages of recipes, you can scroll to cycle through the different pages.
But if you only have one page with a recipe that uses an item tag, the scrolling will cycle through the possible input items.
The issue here is that if you have multiple recipe pages which multiple recipes that have input tags, the cycling through the different input items does not work anymore because it will scroll to the next recipe page instead.
![](https://i.imgur.com/CjAOX2l.gif)

Suggested behaviour:
I think it would be nice to have an option to cycle through both of them.
This could be achieved by a hotkey you have to press.
Let's say if you just scroll without any hotkey, it will cycle through the recipe pages and if you press shift (as an example) while scrolling, it will cycle through the possible ingredients for the recipe on the current page.
This could be further improved by only cycling through the ingredients of the recipe the mouse is currently hovering over. Otherwise it would have to cycle through the ingredients of all the recipes on the current page in case there are more than just one.

As an alternative, you could completely work around the hotkey mechanism.
This would mean that pages are cycling while you are scrolling anywhere and recipe ingredients would cycle while hovering over the slot or the whole recipe.

**Comment by rlnt** [comment]
Would still be nice QoL.

**Comment by mezz** [comment]
Thanks for the suggestion! I agree this should be improved.
I think this is the same as https://github.com/mezz/JustEnoughItems/issues/1585 so I will close this one.

**Comment by jursamaj** [comment]
I assume all these sorts of items are oredicts.

Perhaps the simplest solution: have a modified click on the oredicted item copy the relevant search string over to the JEI search bar.  It's easy enough for the user to go back to any prior search with cursor-up.
