### ISSUE TITLE
Unable to get *all* recipe categories

### ISSUE THREAD

**Issue by jaredlll08** [mezz/JustEnoughItems#2403]
So basically `RecipeManager#getRecipeCategories` only returns categories that are visible, the java doc does say `returns an unmodifiable list of all Recipe Categories`, so I'm not sure if this is intended.

The check that causes this is here:
https://github.com/mezz/JustEnoughItems/blob/1.16/src/main/java/mezz/jei/recipes/RecipeManager.java#L161

Is this method meant to only return visible categories?
If yes, how would I go about / could a method be added to retrieve *all* categories regardless of visibility?

**Comment by mezz** [comment]
Thanks for the report!
I have added some new API methods in this commit to expose the data you need. 
Please let me know how they work out for you:
https://github.com/mezz/JustEnoughItems/commit/7413f0c6d1a3eee2582a60ad757c50af20e5e8ed

**Comment by jaredlll08** [comment]
Sorry it took me a bit to get back to this.

Seems to be working!

Thanks!
