### ISSUE TITLE
1.16.5 players can get items from jei on server

### ISSUE THREAD

**Issue by RQ0392** [mezz/JustEnoughItems#2405]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by RQ0392** [comment]
I am not op but I can still get things from cheat in jei

**Comment by kongbai-s** [comment]
Me too, but I'm a plugins and module Server。

**Comment by mezz** [comment]
Thanks for the report!
I have added some new server-side configs to enable or disable cheat mode in JEI, that will allow server owners to control this behavior. https://github.com/mezz/JustEnoughItems/commit/574bb250458f17dc0ae6045bfdff1d424b47e8b3
