### ISSUE TITLE
Players can use cheat mode in a server

### ISSUE THREAD

**Issue by Shiori514** [mezz/JustEnoughItems#2406]
mod installed
- Client side : JEI, FTB Library, Architectury
- Server side : JEI

In this case, the players can enable cheat mode in the server (even without any permission) and use give mode to get any items they want.

**Comment by alexander-denev** [comment]
That's probably because they have operator permissions (/op)

**Comment by mezz** [comment]
Thanks for the report!
I have added some new server-side configs to enable or disable cheat mode in JEI, that will allow server owners to control this behavior. https://github.com/mezz/JustEnoughItems/commit/574bb250458f17dc0ae6045bfdff1d424b47e8b3
