### ISSUE TITLE
Odd Incompatibility

### ISSUE THREAD

**Issue by CanadianHarp85** [mezz/JustEnoughItems#2410]
When having only Apotheosis, JEI and Tropicraft (and any respective coremods) JEI simply does not operate. 
Ctrl+o does not open anything, R and U do not work; and although you can edit the control/keybinds for the Overlay, there isn't any other evidence that JEI is even installed.

I wish I knew more to tell you which mods fault it is; but I spent all of Friday narrowing it down until I learned that it was only when all three of these were together, that there was an issue.

As a note; I have reported this issue to all three mod developers, if I've totally screwed it up somewhere- I'm sorry.

## Steps to Reproduce
1) Install JEI
2) Install Apotheosis
3) Install Tropicraft

Apotheosis API Version: 4.6.1   
JEI Version: 1.16.5-7.7.0.107   
Tropicraft Version:   9.0.0-beta+54   
Forge Version:   36.1.32   

No applicable crash logs.

I ran /start debug and /stop debug while opening inventory and attempting normal JEI commands.
[profile-results-2021-07-03_04.21.31.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6758076/profile-results-2021-07-03_04.21.31.txt)
I did not see a debug.log. Here's the latest.log:
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/6758078/latest.log)

**Comment by CanadianHarp85** [comment]
Appears that perhaps Tropicraft was the root cause? They indicated on my post there that they are making a fix.
https://github.com/Tropicraft/Tropicraft/issues/395

Thank you for your time. I had finally resolved to remove Tropicraft because JEI is so essential in large packs (and Apotheosis was far too good to remove), and I wish you a most excellent rest of 2021.

**Comment by Ommina** [comment]
If this has been resolved, perhaps close the outstanding open issues here and on Apotheosis?

**Comment by CanadianHarp85** [comment]
My apologies, haven't been on Github in several years; thanks for the reminder! :)
