### ISSUE TITLE
Ram spiking

### ISSUE THREAD

**Issue by Icedragonzz821** [mezz/JustEnoughItems#2412]
Hey My ram is spiking on my client when I add JEI, I dont know how to fix it or how to seee whats causing it. Without JEI its loading like 5gb of ram to load but with JEI its taking over 13gb

**Comment by mezz** [comment]
Thanks for the report!
Try setting `LowMemorySlowSearchEnabled` to `true` in JEI's client config. It should make the search use less memory, but run slower.
