### ISSUE TITLE
Suggestion: Config Addition

### ISSUE THREAD

**Issue by Tyrius1** [mezz/JustEnoughItems#2413]
Hey there! Could you add a config to disable the plus button auto filling a recipe in JEI 1.16.5? 
Maybe when its disabled it could fill the crafting grid with fake versions of it rather than pulling from the inventory. Similar to how the recipe book does it when you don't have the necessary materials.
I'm using a mod called Project MMO and it restricts crafting recipes until reaching a certain level but using the plus button overrides this and allows the player to craft the item regardless if they've met the level or not.

Thank you for your time!

**Comment by mezz** [comment]
Thanks for the report!
I think it should be possible to restrict the recipe no matter how the items are placed, mods like GameStages do this. You should report this to Project MMO to see if they can improve their recipe gating implementation.

**Comment by AsheX1** [comment]
uuu gone add on here about PMMO its has problems over all with JEI like spamming the consol  and bloating the log file to over 500+ MB and looking at there discord and having report the problem there also seems they just dont care 

as it has bin report over 10+ times that PMMO breaks stuff wen JIE is used 
and the thing that breaks the what tyius1 is saying there is a second problem disabling the lvl restrictions for stuff wil still make PMMO spam the log about JEI 

they dont really care as far as i know maybe it can be fixed here on JEI it self but idk as to me it looks more like a PMMO problem
