### ISSUE TITLE
Forge Version 14.23.5.2768 Error - pls help 

### ISSUE THREAD

**Issue by Endercake6080** [mezz/JustEnoughItems#2417]
I wanted to start a project with some friends, with a small mod list. It includes mods that need a specific version of 1.12.2 Forge because of render changes. Also, our server hosting site only accepts One of the few Forge versions the mods need to work - and if I Start this version (forge 14.23.5.2768) The game shows me that it needs a newer version of Forge. I tried every on curse forge exciting jei version, and it still doesn't work. 
Here a screenshot of the error message - hope it helps
![Screenshot 2021-07-12 100308](https://user-images.githubusercontent.com/87301586/125252252-6e95a600-e2f8-11eb-88e0-ebb7b800906c.png)

Could you please help me with that? I really need the mod in the project.

**Comment by Ommina** [comment]
If I'm reading things correctly, the first build for Forge 14.23.5 supported by JEI is 2775.  I suppose you could try going back into 14.23.4, but now you're in breaking-changes territory, and the odds of some other mod not working goes up sharply.
