### ISSUE TITLE
JEI 7.7.1.110 prevents crafting Kemonocraft items

### ISSUE THREAD

**Issue by red3dred** [mezz/JustEnoughItems#2418]
So, title says everything there is to say sadly. JEI 110 seems to prevent crafting of key items to use that mod, and reverting to 107 seems to revert this issue. Oddly, JEI presents the same recipes that it seems to prevent the crafting of, without issue. Mod in question is called "Kemonocraft" by "SonicFan". A friend has already informed them of the issue on their end, so i'm just putting this here aswell.

I've checked the logs generated by Forge but haven't seen anything mentioning the mod, or any error at all in fact, only "Recipe registry plugin is slow".

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
