### ISSUE TITLE
My Minecraft crash when i open jei and search items

### ISSUE THREAD

**Issue by GalaxyBuilder-oss** [mezz/JustEnoughItems#2419]
minecraft always crash when search and viewing recipe list in jei, can you help me? this is crash report i got
[crash-2021-07-14_06.11.14-client.txt](https://github.com/mezz/JustEnoughItems/files/6812534/crash-2021-07-14_06.11.14-client.txt)

**Comment by th3akmin3412** [comment]
i have the same problem, when searching  " se  "  the game crash .

my version is forge 1.16.5
[latest.log](https://github.com/mezz/JustEnoughItems/files/7157690/latest.log)

**Comment by mezz** [comment]
Thanks for the report!
This looks to be an issue with another mod here: https://github.com/SilentChaos512/Silent-Gear/issues/395
