### ISSUE TITLE
Unable to open JEI confing from main menu

### ISSUE THREAD

**Issue by Rorombik** [mezz/JustEnoughItems#242]
Here [https://gist.github.com/Rorombik/6410a55f361dde6fefa31ccf1996882f](url)
If you try to open JEI config menu from forge mods menu it not responds and write an error to log `[Client thread/ERROR] [JEI/]: Failed to register mod plugin: class jeresources.jei.JEIConfig
net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: DEFAULT_TRADE_LIST_MAP` (line 1849)
From the inventory it opens but with another error 
`[Client thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.fml.client.event.ConfigChangedEvent$OnConfigChangedEvent@a7c3e37:
java.lang.IllegalAccessError: tried to access field net.minecraftforge.fml.client.event.ConfigChangedEvent.modID from class com.nottoomanyitems.stepup.ConfigHandler`
(line 1894)

**Comment by TehNut** [comment]
The first one is caused by JER failing to find a field (JER's problem). The second one appears to be caused by `com.nottoomanyitems.stepup.ConfigHandler` (StepUp) not having updated to your Forge version yet. (StepUp's problem)

**Comment by mezz** [comment]
Thanks for the report!
I saw an issue opening the JEI config menu without those mods and fixed it.
