### ISSUE TITLE
Unreasonably high memory allocation by RecipeManager

### ISSUE THREAD

**Issue by starmun-0010** [mezz/JustEnoughItems#2422]
**Description**
In extra large modpacks, RecipeManager is allocating massive amounts of memory.
Please see the screenshots below of the heap dump for reference, RecipeManager is taking ~ 882 MB of memory.

**Question**
I saw in the source code that there have been relatively recent changes of separating RecipeManager from RecipeManagerInternal, so are there any plans of taking the RecipeManagerInternal's caching away from memory and persisting it to disk? Such that it reduces the memory consumption significantly? 
If not, I would like to request the permission for one of the following

- Create a PR for user configurable alternative RecipeManager which caches to disk, invalidates caches on game startup  and only loads selective recipe maps into memory when needed. Its response time will be obviously slightly slower but it will be significantly more memory efficient.
**OR**
- An Addon for JEI to do the same if you think such a feature will not fit within JEI

Thank you

**Screenshots of Heap Dump**

![image](https://user-images.githubusercontent.com/5557278/125717335-ebbd35a2-aef4-4d6a-a866-fea22e9de90f.png)

![image](https://user-images.githubusercontent.com/5557278/125717062-549dc0f7-193c-4936-bd09-af15c0095225.png)

**Related Issue**

One of the major culprits is blue skies so I have created an issue in their repo:

https://gitlab.com/modding-legacy/blue-skies/-/issues/41

**Comment by mezz** [comment]
Thanks for the report!
It looks like 2/3 of these recipes were from a single mod, is this still a problem now that they've fixed it?

**Comment by mezz** [comment]
@starmun-0010 has this been resolved?

**Comment by starmun-0010** [comment]
sorry, too busy to do further benchmarks right now. I'll try to test again and report back as soon as possible.
