### ISSUE TITLE
Builds from the 1.17 branch are being added to CurseForge under 1.16

### ISSUE THREAD

**Issue by jaredlll08** [mezz/JustEnoughItems#2427]
I believe this file is from 1.17.
https://www.curseforge.com/minecraft/mc-mods/jei/files/3399851

It is also pushed to jenkins and maven under this version.

Was mighty confused when I saw this
![image](https://user-images.githubusercontent.com/5553605/126883606-be47c824-2dec-4d73-bcf6-e716aa0a9aeb.png)

It also led to a user updating to this and then a version check didn't work anymore (JEITweaker requires `7.7.1.110 ` or above), so you may want to archive that file.

**Comment by dbkynd** [comment]
I noticed the same JEITweaker conflict. Just switched back to 7.7.1.115

**Comment by mezz** [comment]
Thanks for the report!
Ah this was a mistake with the new build system for 1.17.
I have archived the broken build and disabled the 1.17 build pipeline until it's ready.
