### ISSUE TITLE
JEI inventory not showing 1.12.2

### ISSUE THREAD

**Issue by Gqlaxy99** [mezz/JustEnoughItems#2430]
I have added JEI, when i go into minecraft and open the inventory, there is no GUI, i looked in my mod options and JEI is not showing, Even though it is in the mods folder. I don't know if this is some sort of code issue or something: I checked my logs and there are no errors

Im using 1.12.2
Here is the log
https://github.com/Gqlaxy99/Just-a-log

**Comment by Mr-Syntax** [comment]
i have the same issue on 1.16.5 forge 36.1.31

**Comment by Ommina** [comment]
There's no log there.
