### ISSUE TITLE
[Issue] JEI Cheat Mod number keyboard shortcuts do not account for modifier key(s) being held

### ISSUE THREAD

**Issue by sdarkwell** [mezz/JustEnoughItems#2431]
**Issue:**

While in Cheat Mode, JEI treats pressing 1 - 9 the same regardless of whether or not any modifier keys (eg: shift, ctrl, alt) are being held. Pressing keys 1 - 9, modifier key held or not, you will be given a stack of any item hovered in JEI in the associated slot in your hotbar. 

As searching JEI by ModName, Tooltip, Tag, CreativeTab, Color, or Resource ID require entering a special character utilizing the "shift" key modifier followed by the same keys used as shortcuts to obtain a stack into a hotbar slot, it is easy to unintentionally "overwrite" items in your hotbar slot when attempting to search with the search bar unintentionally not selected.

**Request:**

Only allow JEI "Cheat Mode" to place a stack of items into your hotbar if a number key is pressed _without_ any modifier keys held.

**Thank you for your consideration. Be well!**
\- S.

**Comment by mezz** [comment]
Thanks for the report!
I believe these issues have been fixed in the latest versions.
