### ISSUE TITLE
When the forge & bukkit server installs the EssentialX plugin, everyone can use cheat mode in the server.

### ISSUE THREAD

**Issue by oldmmry** [mezz/JustEnoughItems#2433]
In the Minecraft 1.16.5 .When the forge & bukkit server installs the EssentialX plugin, everyone can use cheat mode in the server.Even without the rights of the operator.

**Comment by mezz** [comment]
Thanks for the report!
I have added some new server-side configs to enable or disable cheat mode in JEI, that will allow server owners to control this behavior. https://github.com/mezz/JustEnoughItems/commit/574bb250458f17dc0ae6045bfdff1d424b47e8b3
