### ISSUE TITLE
Suggestion: Search by color

### ISSUE THREAD

**Issue by Lovatic123** [mezz/JustEnoughItems#2435]
Hello there!

I love building in the game, and I thought it would be much easier to find similair colored blocks if one could search by color in JEI. Sometimes when building you just need the right color and texture, which is why I thought being able to search by color would be a great addition to the mod.

**Comment by Eric-01** [comment]
JEI already offers such feature. For a looong time now.

**Comment by Lovatic123** [comment]
Really? I cant seem to find this feature mentioned on the curseforge page, so I dont know how it works? O.O

**Comment by Eric-01** [comment]
It is disabled by default (most likely due to performance overhead), but you can enable it in the config by setting the following option to "ENABLED" (or "REQUIRE_PREFIX"):
![Color_search_config](https://user-images.githubusercontent.com/46398175/131091712-fae69ffa-ee92-4a3c-ac3e-8397c32e2706.png)
