### ISSUE TITLE
How do I add custom fuels for a custom furnace to JEI?

### ISSUE THREAD

**Issue by Sinhika** [mezz/JustEnoughItems#2438]
I have a mod that introduces special custom furnaces that execute standard furnace recipes (SMELTING, BLASTING, SMOKING), but use special, non-standard fuel items. I cannot figure out how to tell JEI that these items are burnable in the custom furnaces and only the custom furnace. I can't figure out how to add fuel items that are not normally fuel to JEI, period. Can you show me where to start?

**Comment by mezz** [comment]
Thanks for the question!
You should join the Discord and ask there to get quicker help on questions: https://discord.gg/sCQcWU2
I think in this case you want to support the standard categories with your custom furnace (add your furnace as a crafting catalyst), and then create your own separate recipe category for the fuel items that are only working with your custom furnace.
