### ISSUE TITLE
I cant see the item list

### ISSUE THREAD

**Issue by HornyRider** [mezz/JustEnoughItems#2439]
I bought a server at "g-portal.com" with 9gb of ram to play the mod "All the mods 6", when I started it and played multiplayer it didn't start the mod "Just Enough Items (JEI)", it only used 291 instead of 310 mods, it was version 1.6.5. Newer version won’t work because "All the mods 6" does not support them. Can u guys help me?

**Comment by mezz** [comment]
Thanks for the report!
Please ask ATM 6 here: https://github.com/AllTheMods/ATM-6/issues
