### ISSUE TITLE
Plugins server installation Jei,  No OP permission or give permission,You can open cheating mode

### ISSUE THREAD

**Issue by kongbai-s** [mezz/JustEnoughItems#2454]
Plugins server installation Jei,  No OP permission or give permission,You can open cheating mode

**Comment by mezz** [comment]
Thanks for the report!
I have added some new server-side configs to enable or disable cheat mode in JEI, that will allow server owners to control this behavior. https://github.com/mezz/JustEnoughItems/commit/574bb250458f17dc0ae6045bfdff1d424b47e8b3
