### ISSUE TITLE
[Visual Glitch] recipe ingredients are far outside of slots 

### ISSUE THREAD

**Issue by Commandore32** [mezz/JustEnoughItems#2455]
![Jei bug](https://user-images.githubusercontent.com/57783112/129264401-91c611ee-7372-4103-945d-3be7d0ee1413.png)

**Comment by Ommina** [comment]
That is, as I recall, intentional on the part of Astral Sorcery.

**Comment by mezz** [comment]
Yes, this is intentional on their side. Please open an issue with them if you want to, I think it would probably make sense for them to pad their background image so that the ingredients are at least shown inside the box.
