### ISSUE TITLE
When clicking an item in JEI, the search bar is still selected (when not in cheat mode)

### ISSUE THREAD

**Issue by Goldenlion5648** [mezz/JustEnoughItems#2459]
When I type in the JEI search bar and click an item to see its recipe, the search bar is still selected. This ends up making it so that I can't press 'e' to go back to my normal inventory. I have to click somewhere that is not on an item, then press 'e', or press escape twice.

**Comment by mezz** [comment]
Thanks for the report!
Which version of JEI are you using? Is this still an issue in the latest version?

**Comment by Goldenlion5648** [comment]
I am using 7.7.1.122 on 1.16.5 (currently the latest version of the mod) and this is still an issue

**Comment by mezz** [comment]
Thanks, I found the source of the bug and fixed it in the next version.
