### ISSUE TITLE
show recipe overwrites the display. how can I deactivate "show recipe".

### ISSUE THREAD

**Issue by Steintigermaus** [mezz/JustEnoughItems#2461]
![Unbenannt](https://user-images.githubusercontent.com/89216894/130118638-39f78500-36a3-4428-962c-6d5770152ef7.png)

**Comment by mezz** [comment]
Thanks for the report!
If this is your mod, you should move the recipe click area so that it is not the same as the tooltip area.
If this is not your mod, please report this issue to the mod author.
