### ISSUE TITLE
Opening any inventory client will crash

### ISSUE THREAD

**Issue by Muzi2333** [mezz/JustEnoughItems#2462]
[minecraft-exported-logs-2021-08-20T20-04-59.log](https://github.com/mezz/JustEnoughItems/files/7021341/minecraft-exported-logs-2021-08-20T20-04-59.log)

**Comment by Muzi2333** [comment]
Find out why "CodeChickenLib-1.16.5-4.0.2.429-universal" caused it.
No problem with "CodeChickenLib-1.16.4-3.5.1.408-universal"

**Comment by Ommina** [comment]
What about without Optifine?
