### ISSUE TITLE
Jei mod loaded, but no ingame visuals

### ISSUE THREAD

**Issue by wicked9090** [mezz/JustEnoughItems#2463]
I am having an issue when using a large pack of mods where JEI is loading as a mod W/ all Configs and control options, but unable to use the mod. I have been unsuccessful in finding the cause after hours of testing. Please see my latest log which I am unsure if it will help. It all worked fine a week ago, then I load up since and JEI doesn't show anymore, even after using the show/hide JEI keybind

https://gist.github.com/wicked9090/b49af7fe3b870c6e6ec4f4b60625b628

Let me know if there is anything extra I con provide that may assist.

**Comment by wicked9090** [comment]
@Ommina

**Comment by Ommina** [comment]
Thank you for creating the new issue.

Let's start with updating BluePower to bluepower-1.16.5-0.5.250-alpha and if that fails to work, remove it (BluePower) entirely as a test.

**Comment by wicked9090** [comment]
Sorry for the delay, been away from PC for a few days. Updated BluePower and launched, got the unable to load resource packs error, removed blue power and tried to load world and crashed to desktop... Trying again with all 3 options to make sure nothing else changed - relaunched without BluePower and it's now getting stuck loading the world :/
