### ISSUE TITLE
[1.17] JEI does not show items with layers in main menu

### ISSUE THREAD

**Issue by Pdiddy973** [mezz/JustEnoughItems#2466]
items with layers do not show up in the normal JEI interface:
![image](https://user-images.githubusercontent.com/68764896/130520617-8e7b9040-6446-4d45-a3a1-57dafa2ba46e.png)

however when clicking on the items, the recipe page shows them correctly
![image](https://user-images.githubusercontent.com/68764896/130520691-2d9002ac-48f1-4240-a648-8d4bfd2beb58.png)

JEI - 8.0.0.12

**Comment by mezz** [comment]
Thanks for the report!
Does your item's baked model return `true` from `isCustomRenderer`? 
How does it render differently from other items? Thanks!

**Comment by mezz** [comment]
hm ok looks like this is forge's `MultiLayerBakedModel` which doesn't use `isCustomRenderer`.

**Comment by mezz** [comment]
I will exclude layered models from the fast-rendering pipeline for now, that should fix this issue.

**Comment by narwall101** [comment]
I also have this same issue
