### ISSUE TITLE
[1.17] error code 0

### ISSUE THREAD

**Issue by kezidian** [mezz/JustEnoughItems#2467]
for minecraft 1.17.1 JEI getting an exit code 0 when trying to launch minecraft. when removing jei from mod folder the game launches and runs fine

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by kezidian** [comment]
where do i find the location of the file?

**Comment by ryaccodes** [comment]
made an account just to post this. im having the same issue.  i stripped out my uuid b/c its pii. there doesnt look like there anything really telling in here though?

https://gist.github.com/ryaccodes/58cd08ef1aee68dea94790c89eddea11

**Comment by andrilyas** [comment]
I am also having this exact problem.

**Comment by mezz** [comment]
Sorry I don't think this is the right log file, the right one should have hundreds or thousands of lines of logs. Unfortunately I am not able to see the crash in the log posted here.
