### ISSUE TITLE
[1.16.5] Squeezer's recipes of integrated dyanmics crash 

### ISSUE THREAD

**Issue by Inverseder** [mezz/JustEnoughItems#2468]
Hey, I updated JEI from 1.16.5.7.7.1.118 to 1.16.5.7.7.1.120 and I found a bug with integrated dynamics squeezer. When I open a squeezer's recipe my game crash. When i downgrade JEI to 1.16.5.7.7.1.118, i can open the recipe easely.
Here the crash report: https://gist.github.com/Inverseder/4ae58e12eba87789eca81353d98220c5
Thanks for help

**Comment by Neb2566** [comment]
Sounds like the same issue that I got with Dissolution chamber from Industrial Foregoing recipes. Downgraded to .118 fixed the issue for me aswell.

**Comment by Aspifion** [comment]
https://gist.github.com/Aspifion/c005007f54b10c26f5f52edb3f902167

**Comment by mezz** [comment]
Thanks for the report! This should be fixed in the next release, `1.16.5-7.7.1.121`

**Comment by tytan652** [comment]
I confirm it don't make crash the game but it doesn't show any recipes from some machine from integrated dynamics and industrial foregoing.

#2471

**Comment by mezz** [comment]
Thanks for the report!
Please report this to integrated dynamics and industrial foregoing, I think there is something else going wrong here and they may be able to resolve it on their side.
