### ISSUE TITLE
FPS degradation with certain mods

### ISSUE THREAD

**Issue by Cherry** [mezz/JustEnoughItems#247]
FPS degradation with certain mods

I recently reported https://github.com/TeamBR-Modding/NeoTech/issues/280, however have since found that it affects other mods such as Tinker's Construct & Chisel too. Storage Drawers & Deep Resonance don't seem to suffer from this issue.

X-posting here, to see if it's potentially a JEI issue. If there's any further information I can provide, please let me know.

**Comment by mezz** [comment]
I think the FPS drop from 150 to 70 while viewing half the game's items at once sounds about right, item rendering is pretty slow.
I'll reply in the other issue to see what's going on with NeoTech.

**Comment by Cherry** [comment]
For your reference, this also affects Tinkers'; https://github.com/SlimeKnights/TinkersConstruct/issues/2007

**Comment by jjc54** [comment]
The same issue happens with some of the Chisel blocks while scrolling through JEI.
