### ISSUE TITLE
Last update JEI - recettes Industrial/Dissolution chamber.

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2471]
Hello, it seems that the latest update of JEI is breaking the display for some recipes Industrial foregoing -> dissolution chamber.

Logs : https://gist.github.com/PlatiniumOfficial/e0f33e661171d2c056ee4429297f2b58
Screen : https://imgur.com/a/0Y4wXRW

**Comment by Grishord** [comment]
I have this issue as well
