### ISSUE TITLE
Client option to remove mod name from item

### ISSUE THREAD

**Issue by Shadowdragon019** [mezz/JustEnoughItems#2472]
In JEI when you hover over an item with your mouse it shows details of the item along with what mod it was from.
![image](https://user-images.githubusercontent.com/67480398/131016110-694525d6-fc0c-48b6-b621-28040b245e28.png)

It would look like
![image](https://user-images.githubusercontent.com/67480398/131016174-319f796b-7657-413a-9805-f93251adc7b8.png)

**Comment by Eric-01** [comment]
JEI already offers such feature. For a looong time now.

If you would like to modify the appearance of this text, go to the config and modify the following option:
![Mod_name_config](https://user-images.githubusercontent.com/46398175/131092048-9685c3de-8785-47f0-a329-c2f2ea151521.png)

After setting it to an empty string, the mod name text won't be displayed at all, as it seems you want.
