### ISSUE TITLE
Crash with MineCraft 1-16-5 Forge 36.2.2 and JEI 7.7.1.120

### ISSUE THREAD

**Issue by trogarus** [mezz/JustEnoughItems#2473]
Crash while looking at Industrial Foregoing recipes

Minecraft 1-16-5
Forge 36.2.2
JEI 7.7.1.120

https://gist.github.com/trogarus/70879e2c650292739d7fdeb07d8a83e2

**Comment by LordBoos** [comment]
I have this same problem. Happens when opening recipe for Awful Crystal form Stalwart Dungeons mod.
[crash-2021-08-28_19.20.40-client.txt](https://github.com/mezz/JustEnoughItems/files/7071188/crash-2021-08-28_19.20.40-client.txt)

**Comment by trogarus** [comment]
Updated to jei-1.16.5-7.7.1.121

Seems to have fixed the crash issue, but now there are no recipes showing for the dissolution chamber at all.

**Comment by trogarus** [comment]
Recipes now seem to be showing in dissolution chamber after most recent Industrial Foregoing updates
