### ISSUE TITLE
[1.8.9] JEI wont load for the 1.8.9 version of minecraft

### ISSUE THREAD

**Issue by C-apy** [mezz/JustEnoughItems#2475]
![image](https://user-images.githubusercontent.com/57754485/131244238-6b59bd88-b64d-487a-b0a6-3dafcf56e749.png)

When I tried to Load up minecraft it shows up this. after i remove it from the mod folder it works again

Heres the file for the logs: 
[fml-client-latest.log](https://github.com/mezz/JustEnoughItems/files/7072157/fml-client-latest.log)

**Comment by PlazmaKG** [comment]
This error has nothing to due with JEI, you simply need to update Forge to a later version.
