### ISSUE TITLE
[1.17.x] Client crash with ghost ingredient rendering

### ISSUE THREAD

**Issue by desht** [mezz/JustEnoughItems#2479]
JEI version: 8.0.0.10

JEI will lock up the client if a ghost ingredient handler is used (i.e. an `IGhostIngredientHandler` has been registered). Exception here: https://gist.github.com/desht/3c3a2d56ec3ac43288bdbec0c55cbd9a

Presumably due to using raw GL11 calls in `GhostIngredientDrag`, which definitely isn't going to work in 1.17...

**Comment by mezz** [comment]
Thanks for the report!
I believe this was fixed here, and merged a few days after your report: https://github.com/mezz/JustEnoughItems/pull/2469
