### ISSUE TITLE
Correlated Potentialistics and +

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#248]
Request for integration, Please allow the + crafting shortcut to be usable in the Correlated Potentialistics Crafting table from player inventory first, followed by drive inventory

http://minecraft.curseforge.com/projects/correlated-potentialistics

**Comment by shadowfacts** [comment]
This would either belong in Correlated Potentialistics or JEI Addons, not JEI core.

cc @unascribed

**Comment by mezz** [comment]
Mods add their own integration, you can request the feature [here on the Correlated Potentialistics github](https://github.com/unascribed/CorrelatedPotentialistics/issues?q=is%3Aopen+is%3Aissue).
