### ISSUE TITLE
bug when not seeing the recipes

### ISSUE THREAD

**Issue by Huachin12** [mezz/JustEnoughItems#2480]
I want to report a bug, I cannot see the recipes of the crafting with the jei and I have other mods apart from that one.
![Captura de pantalla (363)](https://user-images.githubusercontent.com/89950371/131762023-ed678c0d-318e-45ba-a47b-127682af877e.png)

**Comment by tattttoal** [comment]
me pasa exactamente lo mismo, ya he probado varias versiones de JEI y hasta ahora nada

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
