### ISSUE TITLE
How to make JEI only show the items which unlocked like the vanilla recipes?

### ISSUE THREAD

**Issue by GF-Huang** [mezz/JustEnoughItems#2481]
In default, the JEI shows all the things, this made me lose the joyful experience of unlocking/discovering a new recipe. How to make like only show recipes which already unlock/discover?

**Comment by mezz** [comment]
Sorry, there is no support for this in JEI. With modded minecraft, things are usually too complicated to easily progress this way, so most mods are built around the idea that you can see all the items and recipes in JEI.

It would be possible to do this using an addon for JEI, the API allows mods to control what is shown. Something like this is done in some modpacks that offer progression, like in the SevTech Ages modpack.

**Comment by GF-Huang** [comment]
Got it, thanks reply.
