### ISSUE TITLE
ModDupe? 

### ISSUE THREAD

**Issue by StonerKing420** [mezz/JustEnoughItems#2483]
ok so i went into curseforge made a 1.16.5 minecraft world so then i got into adding modpacks 105 total now JEI happens to be one of em now when i press play for my world alls good it auto switches to the java launcher and i press play it pops up loads the mods but at the very end when its supposed to pop the main menu up i get this instead Fml.modloading.dupedmod and this was the crashreport 
[mc crash.txt](https://github.com/mezz/JustEnoughItems/files/7109009/mc.crash.txt)

**Comment by StonerKing420** [comment]
i just rlly dont know why i mean i mess with mods all the time everyday and dont get that Dupedmod crash thing and even im stumped g

**Comment by mezz** [comment]
Thanks for the report!
I think this just means you have multiple jei `.jar` files in your `mods` folder. Take a look and see if there's an extra one in there for some reason.
