### ISSUE TITLE
JEI- 1.15.5-7.7.1.121 ON SERVER : Not Showing Any Recipes Besides Default Minecraft Ones

### ISSUE THREAD

**Issue by SlickEcho** [mezz/JustEnoughItems#2486]
Minecraft Version: {1.16.5}

Forge Version: {Forge-1.16.5-36.2.2)

Logs: No errors in Logs to report

Steps to Reproduce:
Setup Minecraft server and install same versions of Forge, JEI, and jeiintegration- 1.16.5-7.0.1.15. Add tinker construct to see one example of my issue.

*Description of issue:
Small server with only 25 mods or so. Most issues have been with Minecraft version and just bad luck of mods not working proper; however, jei I've installed like 4 different versions and all the same issue. I've also changed my optifine version to G7 and that fixed a shading issue but I've researched for like two days now and can't find a solution.

Notes:
I have tried basically the top 10 on google search for solutions and none of them worked.
I have the same mods and versions of mods in my local and server mod folder.
Hosting site is Hostinger (which could be the problem in of its self) with my luck).
Only Minecraft has working recipes but every single one of my mods recipes do not work at all, I have a few that will show information about the spawning or other information related to it.

(also first post ever here so I do apologize if this is in the wrong spot or doesn't retain the correct information for finding solutions)

**Comment by LLjo** [comment]
Had the same problem. I removed the newest Occultism update and it worked fine afterwards

**Comment by tattttoal** [comment]
tengo el mismo problema, JEI no me muestra los crafteos, aveces muestra crafteos y otras no

en un servidor de 60 mods el JEI mod no me funciona a mi ni a mis compañeros, no muestra crafteos de los mods, tampoco de los objetos vanilla, ya he descargado varias versiones de JEI, también se las cambié al servidor y hasta ahora nada

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
