### ISSUE TITLE
[Question] A way to list recipe variants?

### ISSUE THREAD

**Issue by violetazx** [mezz/JustEnoughItems#2487]
Is there a way to list/show recipe variants separately? The current display, with how the variants cycle, is much too fast for me to hover + see what items are needed for a recipe. i.e. Nature's Compass has many variants on how to make it, but I can't immediately recognize every item and there's so many variants, I have to wait for it to cycle back if I want to see the one I was trying to make.

**Comment by mezz** [comment]
Thanks for the Question!
I have attempted a few ways to display this type of information better, but unfortunately it's pretty hard to do it in a way that works generally for all modded recipes.

**Comment by violetazx** [comment]
Understandable. Maybe an option to slow down/pause the cycle, then? Not sure how viable that would be.

**Comment by mezz** [comment]
IIRC you should be able to pause the cycle by holding `shift`.

**Comment by violetazx** [comment]
It doesn't work. I don't think it's a mod conflict, afaik nothing except sprint is bound to shift and advanced tooltips are off. I don't see an option for it in the config file, either.

**Comment by mezz** [comment]
Hmm, it's working for me, the rotation cycle pauses as long as I hold down the shift key.
I checked the code and it's hard-coded as shift in there, it's not configurable.
I think this hidden feature is a hold-over from NEI, I just included it since people were used to it at the time.
