### ISSUE TITLE
jei not showing up on a server

### ISSUE THREAD

**Issue by MasterQuentus** [mezz/JustEnoughItems#2488]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
![2021-09-09_01 06 48](https://user-images.githubusercontent.com/32037705/132632342-d0ddd865-bf7a-4447-b9e4-03e80bdce43e.png)
on single player it shows up just fine but if i load onto the server no jei on the side it will show up if i leave the server join single player then join the server again but it causes major lag when i do that 
For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
