### ISSUE TITLE
1.17.1 JEI not working

### ISSUE THREAD

**Issue by HTMLDevelopment** [mezz/JustEnoughItems#2489]
I've downloaded JEI for 1.17.1 to use it on a friend's server, but the mod doesn't load nor show the items list! Could you help me fix it? I do not have any other recipe mod exept for JER and enchantment descriptions.

**Comment by mezz** [comment]
Thanks for the report!
Sorry I think this is more of a general modding issue, please try asking on a forum or discord for live help from people who are knowledgeable about making mod packs.

**Comment by HTMLDevelopment** [comment]
Actually, the mod is on the mod folder but fabric apparently doesn't detects the mod

[23:45:11] [main/INFO]: Loading for game Minecraft 1.17.1
[23:45:13] [main/INFO]: Loading 50 mods:
	- fabric 0.40.8+1.17
	- fabric-api-base 0.3.0+a02b446318
	- fabric-api-lookup-api-v1 1.3.0+cbda931818
	- fabric-biome-api-v1 3.2.0+cbda931818
	- fabric-blockrenderlayer-v1 1.1.5+a02b446318
	- fabric-command-api-v1 1.1.3+5ab9934c18
	- fabric-commands-v0 0.2.2+92519afa18
	- fabric-containers-v0 0.1.12+cbda931818
	- fabric-content-registries-v0 0.3.0+cbda931818
	- fabric-crash-report-info-v1 0.1.5+be9da31018
	- fabric-dimensions-v1 2.0.11+6cefd57718
	- fabric-entity-events-v1 1.2.3+87cc6e4c18
	- fabric-events-interaction-v0 0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0 0.2.1+92519afa18
	- fabric-game-rule-api-v1 1.0.7+cbda931818
	- fabric-item-api-v1 1.2.4+cbda931818
	- fabric-item-groups-v0 0.2.10+b7ab612118
	- fabric-key-binding-api-v1 1.0.4+cbda931818
	- fabric-keybindings-v0 0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1 1.4.4+a02b446318
	- fabric-loot-tables-v1 1.0.4+a02b446318
	- fabric-mining-levels-v0 0.1.3+92519afa18
	- fabric-models-v0 0.3.0+a02b446318
	- fabric-networking-api-v1 1.0.13+cbda931818
	- fabric-networking-blockentity-v0 0.2.11+a02b446318
	- fabric-networking-v0 0.3.2+92519afa18
	- fabric-object-builder-api-v1 1.10.9+cbda931818
	- fabric-object-builders-v0 0.7.3+a02b446318
	- fabric-particles-v1 0.2.4+a02b446318
	- fabric-registry-sync-v0 0.7.11+7931163218
	- fabric-renderer-api-v1 0.4.4+cbda931818
	- fabric-renderer-indigo 0.4.8+cbda931818
	- fabric-renderer-registries-v1 3.2.4+7931163218
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446318
	- fabric-rendering-fluids-v1 0.1.14+4658223018
	- fabric-rendering-v0 1.1.5+7931163218
	- fabric-rendering-v1 1.9.0+7931163218
	- fabric-resource-loader-v0 0.4.8+a00e834b18
	- fabric-screen-api-v1 1.0.4+cbda931818
	- fabric-screen-handler-api-v1 1.1.8+cbda931818
	- fabric-structure-api-v1 1.1.13+5ab9934c18
	- fabric-tag-extensions-v0 1.2.1+b06cb95b18
	- fabric-textures-v0 1.0.6+a02b446318
	- fabric-tool-attribute-api-v1 1.2.12+b7ab612118
	- fabric-transfer-api-v1 1.4.0+7931163218
	- fabricloader 0.12.2
	- java 16
	- minecraft 1.17.1
	- xaerominimap 21.18.0
	- xaeroworldmap 1.17.3
And yeah i'm using MultiMC to load minecraft, and i've seen that multimc doesn't really affects anything because i loaded fabric 1.17.1 on the original minecraft launcher and it also didn't work. I hope you know how to fix it. Thanks.

**Comment by mezz** [comment]
JEI is a Forge mod, it doesn’t work with Fabric. I think there are alternative mods written for Fabric

**Comment by HTMLDevelopment** [comment]
Oh wait what? Did I download the wrong version?

**Comment by HTMLDevelopment** [comment]
Yeah I did, i'll make a 1.17 Forge so i can play it. Sorry.
