### ISSUE TITLE
[Request] Custom spawn command

### ISSUE THREAD

**Issue by SarahGreyWolf** [mezz/JustEnoughItems#249]
Would it be possible to add a way to change the command used to spawn in items from JEI like NEI used to so it is compatible with servers using custom plugins like Sponge plugins or Spigot Essentials?

**Comment by mezz** [comment]
JEI uses the vanilla `/give` command, is that not compatible?

**Comment by SarahGreyWolf** [comment]
I've been using the Core plugin for SpongeForge
It's /give command does not support the item data part of the command.
I can remedy it by disabling the plugins commands but other plugins might not have an option to disable it or have completely different commands like /I <player> <item>

**Comment by KnightMiner** [comment]
If another mod changes the give command so it cannot do item giving as done by vanilla, I think that would be it's fault rather than JEI for not adapting to what it broke

**Comment by mezz** [comment]
I'm sorry but I have to agree with @KnightMiner here. This seems like an issue for the Core plugin for SpongeForge. Item data is often very important in 1.8+.

**Comment by temdur** [comment]
Same problem here. In previous MC versions (same server/plugins) the NEI command need always adjustment.

JEI use "/give player minecraft:bed 1 0"
translated this is "/give <target> mod:item [amount] [data]"

The bukkit server responds with:

> Too many arguments.
> /give [-do] [-d] <target> <item[:data]> [amount]

I assume the commandbook plugin is responsible for handling /give. 

Don't know if the serverside <item[:data]> can handle modname:blockname:damageID

I support the request.

**Comment by mezz** [comment]
I talked to @zml2008 in the #spongedev irc channel and they helped me track down the source of the problem. [I reported the issue to the Nexus plugin for Sponge here.](https://forums.spongepowered.org/t/atom-nexus-v1-7-6a-providing-100-essential-commands-and-features/12227/22?u=mezz)

I can add custom spawn commands if people really want to do something more advanced, but my first priority is to have JEI "just work" without messing with the configuration.

**Comment by TehNut** [comment]
I am of the opinion that if plugins are going to overwrite the vanilla command, they should retain compatibility. This is an error on their side.

**Comment by mezz** [comment]
They already replied and said they will fix it, cool.

> I see.. good suggestion! I'll add that to be ready in the next version :relaxed:
