### ISSUE TITLE
jei crash when searching items_forge 1.16.5

### ISSUE THREAD

**Issue by th3akmin3412** [mezz/JustEnoughItems#2491]
when searching items in jei this causes game crash, the last time i tried to search "mo" and the game close after seconds.
other times when writing "se" also crashes but with other words it works well so i dont understrand what is the problem

my version is forge 1.16.5

https://gist.github.com/th3akmin3412/2020d3b79ce2bc315d1865f1e91df1be

**Comment by mezz** [comment]
Thanks for the report! Unfortunately this log doesn't show the crash. Do you have a crash log?
