### ISSUE TITLE
in 1.17 i have a IRecipeTransferHandler Specifically Only for the CraftingRecipe, but JEI ransferHandler.transferRecipe crashes with BlastingRecipe 

### ISSUE THREAD

**Issue by Lothrazar** [mezz/JustEnoughItems#2493]
I think my plugin is correct, i left C for container and then added the recipe like this 

`public class RequestRecipeTransferHandler<C extends AbstractContainerMenu> implements IRecipeTransferHandler<C, CraftingRecipe> {`

Crash log is here 
https://pastebin.com/mW3iQrpN

Related code https://github.com/mezz/JustEnoughItems/blob/91995dd6d27056a0117159d5827c4923405dd4a6/src/main/java/mezz/jei/transfer/RecipeTransferUtil.java#L70

My plugin for CraftingRecipe 
https://github.com/Lothrazar/Storage-Network/blob/trunk/1.17/src/main/java/com/lothrazar/storagenetwork/jei/RequestRecipeTransferHandler.java#L35

Related issue https://github.com/Lothrazar/Storage-Network/issues/388

**Comment by mezz** [comment]
Thanks for the report!

https://github.com/Lothrazar/Storage-Network/blob/7c8f524c04bfa6e90d68d2a01a06f9fed5de9331/src/main/java/com/lothrazar/storagenetwork/jei/JeiPlugin.java#L42-L46

It looks like you have registered as a `universal` recipe transfer handler, which should accept all recipe types. I can look into restricting it based on `getRecipeClass()`, that would make sense.

**Comment by mezz** [comment]
This should be fixed in the next automatic release
