### ISSUE TITLE
The game crashed whilst rendering ingredient Error: java.lang.ArrayIndexOutOfBoundsException: -1 Exit Code: -1

### ISSUE THREAD

**Issue by NuggetBoio** [mezz/JustEnoughItems#2494]
Basically, whenever I type in the JEI search bar it crashes my game. here is the crash log

https://pastebin.com/uU0etCKr

**Comment by NuggetBoio** [comment]
oh btw I'm playing sky factory three Minecraft version 1.10.2

**Comment by NuggetBoio** [comment]
update: I had tried searching something earlier today and it crashed me once again, then I tried to rejoin and I can no longer open my inventory. It gives the same crash message as before too

**Comment by mezz** [comment]
Thanks for the report!
JEI doesn't always work well with Optifine, can you try without it and see if that helps?

**Comment by NuggetBoio** [comment]
Yeah, I think removing optifine did fix it, I also found something else out. Say I search "red" and scroll to the next page it'll crash. maybe when it renders certain items from mods it crashes? It sucks because optifine improves fps by a lot especially with these huge modpacks with 100+ mods

**Comment by mezz** [comment]
Yeah sorry, it's unfortunate. You can report the issue to Optifine, and they often fix these issues.
Unfortunately Optifine is closed-source and hacks the code in a way so that I can't fix it, unlike most mods.
