### ISSUE TITLE
Hiding interface in all worlds by default (1.8.9 & 1.12.2)

### ISSUE THREAD

**Issue by PlazmaKG** [mezz/JustEnoughItems#2495]
Is there a way to hide the interface in all worlds/servers by default? I have it in my mods folder for certain cases where I may not remember a recipe, but I don't want it to be visible unless I actually toggle the interface.

**Comment by mezz** [comment]
You can toggle the JEI overlay by pressing `Ctrl-O` (this can be set in the controls menu).
It will hide the interface until you press `Ctrl-O` again.

**Comment by PlazmaKG** [comment]
I know you closed the subject but...

I know Ctrl-O toggles the interface, but it only does it on a per world basis. It shows up by default on all worlds until you implicitly hide the interface. What I'm asking here is if there is a way to make it so it's off in **all** worlds until I implicitly un-hide the interface.
