### ISSUE TITLE
JEI Crash with CB Multipart

### ISSUE THREAD

**Issue by GlacierPark19** [mezz/JustEnoughItems#2496]
Hello Folks!

Found this "gem" while playing on my friend's Modded mc server. This crash occurs whenever JEI renders ANY multipart block.
Reported this to CBMultipart as well

https://gist.github.com/GlacierPark19/529e5f96902ad542f497b0ef7698bc42

**Comment by mezz** [comment]
I think this may be an issue with CBMultipart, I'll watch the issue here: https://github.com/TheCBProject/CBMultipart/issues/104
