### ISSUE TITLE
JEI Crash with Optifine Removed, Do not know much about Java so would be thankful for any support. Crash Log is attached.

### ISSUE THREAD

**Issue by Smash131** [mezz/JustEnoughItems#2498]
[crash-2021-09-23_20.59.49-client.txt](https://github.com/mezz/JustEnoughItems/files/7219150/crash-2021-09-23_20.59.49-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This turns out to be the same bug as in https://github.com/mezz/JustEnoughItems/issues/2493
I have fixed the bug and it should work with the latest version of JEI for 1.17
