### ISSUE TITLE
[1.16.5] Plus sign for auto complete recipe not showing up

### ISSUE THREAD

**Issue by ToxinZangoose** [mezz/JustEnoughItems#2499]
Hello! I have used JEI for quite a while and hardly ever had issues, so this is a first.

Just recently, I have been playing with my own modpack and encountered this.
I can't click the button, in fact, it isn't rendered in the crafting GUI.

If there's anything I can do to refresh JEI or if FTB-Lib is causing this, please let me know.

I am using Optifine, but only for performance improvements.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by ToxinZangoose** [comment]
[latest.log](https://github.com/mezz/JustEnoughItems/files/7230741/latest.log)
Apologies for the inexperience with sending bug reports.

**Comment by mezz** [comment]
Hmm unfortunately I don't see anything in the log that might indicate what's wrong.
I think this is most likely from a bad interaction with another mod. You can try tracking down which mod is causing the problem by copying your mod pack and removing batches of mods until things work again, and then try narrowing down which mod in the batch was causing the problem.
If you find the mod that is causing the issue, you can create a new issue on their Github and the link back here in case they have questions for me.
