### ISSUE TITLE
[Request] Light level indiction grid

### ISSUE THREAD

**Issue by gendalv** [mezz/JustEnoughItems#250]
kinda like f7 in NEI.

**Comment by mezz** [comment]
Sorry no, this feature is already a part of several mods that can work alongside JEI: Light Level Overlay Reloaded, FTBLib, and Just What I Needed.
JEI is just about items and recipes, not random extra things.

**Comment by gendalv** [comment]
thanks for mentioning Light Level Overlay Reloaded tho

**Comment by Prospector** [comment]
I really wish this wasn't called Just Enough Items, because people expect it to be a NEI replacement. It's not, it's a recipe viewer. I feel like it's often branded as "the new NEI" when it's a completely different mod.

**Comment by mezz** [comment]
It replaces the main part of NEI, makes sense to me.
