### ISSUE TITLE
Problems displaying Vanilla

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2500]
Since the last update a lot of mods have broken recipes in JEI some have corrected this on their side but JEI has broken some vanilla recipes.

JEI : 1.16.5-7.7.1.121
Forge : 36.2.0

Furnace : fuel is not displayed anymore.
Smelting : Same

I haven't seen any other issue about it, sorry if it has already been reported :s.

**Comment by mezz** [comment]
Thanks for the report!
This seems to work fine with just JEI and Forge, is some other mod causing an issue?
Please try removing some mods and see if you can narrow down what is causing the problem.
