### ISSUE TITLE
JEI interface doesn't exist in .16 release and everytime I boot up the game, my settings are reset

### ISSUE THREAD

**Issue by DeltaDeon** [mezz/JustEnoughItems#2505]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to 
![Issue](https://user-images.githubusercontent.com/91763804/135694803-dc9f02a9-ca07-461e-a749-0f9169455ffe.png)
see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by ProsperCraft** [comment]
I have the same issue with the interface not showing on jei-1.17.1-8.1.0.19 on my client when on our dedicated server, rolling the client back to .18 fixed it.
Debug log-
https://gist.github.com/ProsperCraft/3162041cb92ba15046a90b87b314dbe3
Latest log-
https://gist.github.com/ProsperCraft/5664e6cc96f3d25d3f71f7a972b1b20d

**Comment by mezz** [comment]
Thanks for the logs!
This has been fixed in the next version.
