### ISSUE TITLE
Why does JEI crash this modpack?

### ISSUE THREAD

**Issue by Minecraftslayer92** [mezz/JustEnoughItems#2507]
So, I have tried to download and play a new modpack called Insanecraft, on curseforge it crashed to patchouli, but on multimc it crashes to JEI. I removed every JEI mod and it worked perfectly fine, but how can you navigate 250 mods without JEI? I really need help with this since how can you play a modpack that big with no way to actually navigate the recipes?

 Here is the [gist](https://gist.github.com/Minecraftslayer92/d06311075d9f075ced0d9a4f62230203).

**Comment by mezz** [comment]
Thanks for the report!
Sorry but I don't see anything in the log that indicates JEI is crashing. Do you have a separate crash log that shows an issue with JEI that I can look at?

**Comment by Minecraftslayer92** [comment]
Hm, well I don't understand coding so I cant help much, also its not just me, on the actual curseforge website for this modpack, dozens of others crash to it as well, ill edit in a new gist and a screenshot into the original post, it has to be later though since its not even getting through AOA right now, plus I'm going to be gone for a while.

**Comment by Minecraftslayer92** [comment]
Hm, well that's... Unexpected. I just tried playing the modpack again, and it worked? I don't know why or how, but I guess this is done? They might have updated the pack or something just fixed itself when I redownloaded it because it erased itself I guess, uh, yea I have no idea what just happened.
