### ISSUE TITLE
JEI is not showing up even though the mod is loaded

### ISSUE THREAD

**Issue by katiekatkate** [mezz/JustEnoughItems#2509]
Hi! I downloaded JEI and it installed just fine and the only issue is that it won't show up no matter how much I press the control buttons.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by ReeCodes** [comment]
Since I have the same issue, have my log instead
https://mclo.gs/pgvKv6W

**Comment by laneyfamily** [comment]
I'm getting the same issue as well, it shows in controls, but when going into inventory the item list on the right is missing and favorites is missing on the left, additionally usage and recipe key bindings do not work.  Seems its registered as running, but no affect can be seen in game, when I'm back at the machine I can pull the logs

**Comment by Klouver-github** [comment]
im using the latest forge as well, I believe many are having same problem

**Comment by mezz** [comment]
Thanks for the report!
Based on the log, I think this is related to https://github.com/mezz/JustEnoughItems/issues/2514, but in your pack it is breaking JEI even more severely than in the other bug. Same JEI bug but some mods are super unhappy heh
This should be fixed with the next release of JEI.

**Comment by mezz** [comment]
Actually this looks like it may be an issue from a mod called JustEnoughAdvancements, I'll open an issue with them.

**Comment by mezz** [comment]
Reported here: https://github.com/MelanX/JustEnoughAdvancements/issues/3

**Comment by superdude808** [comment]
have been having the same problem and i DON'T have just enough advancements

**Comment by mezz** [comment]
If you have a similar problem but it is not from JustEnoughAdvancements, please open a new issue and we can investigate there.
