### ISSUE TITLE
1.16.5 - Forge crashes when loading JEI with Tinker's Construct

### ISSUE THREAD

**Issue by ImpMind** [mezz/JustEnoughItems#2510]
Minecraft Version
1.16.5

Forge Version
36.2.6

JEI Version
7.7.1.122

Mantle Version
1.6.123

Tinkers' Construct Version
3.1.2.265

Describe your issue:
Whenever I load a world, it saves and crashes. It seems to be something to do with JEI because when I take it out it no longer crashes on loading a world.

Crash Report
https://gist.github.com/ImpMind/4723bc92e46de582bb6367c514d9af1b

The crash can be reproduced with these mods:
JEI Version
7.7.1.122
Mantle Version
1.6.123
Tinkers' Construct Version
3.1.2.265

**Comment by FearAK** [comment]
Me too after the last update

**Comment by ImpMind** [comment]
Apparently, it's a tinkers' bug. Sorry!
