### ISSUE TITLE
Create recipes do not appear on most recent version (7.7.1.122)

### ISSUE THREAD

**Issue by dongbeater3000** [mezz/JustEnoughItems#2511]
Create specific recipes (crushing, milling, mixing, sequenced assembly, deploying, filling, etc) do not appear in the most recent (7.7.1.122) version of JEI.

Auto generated recipes, such as blasting or mechanical crafting, do seem to work most of the time. 

This bug does not occur in 7.7.1.121, and has also been reported to the Create team.

**Comment by OmegaAlpha83** [comment]
same is happening to me with create and mechanism and other mods i think ill roll back a version

**Comment by mezz** [comment]
Thanks for the report!
This seems to be the same issue as the one here: https://github.com/mezz/JustEnoughItems/issues/2514
This should be fixed in the next version.

**Comment by magcicada** [comment]
Mechanical Crafter still have no recipe. @mezz
