### ISSUE TITLE
JEI is preventing me from downloading insanecraft

### ISSUE THREAD

**Issue by CryptoWolfGaming** [mezz/JustEnoughItems#2513]
![JEI issue](https://user-images.githubusercontent.com/91980359/136100809-9e3b750a-a543-4420-a7c9-d878fd6db09d.png)
I get this every time I try to install the insane craft mod pack the contains JEI

**Comment by Ommina** [comment]
Post a link to the crash report here.

Instructions are, quite literally, in the screen-shot you provided.

**Comment by CryptoWolfGaming** [comment]
the problem is is that the link fails every time i try to get it, and also it is telling me to report the issue to the Author which is what i am doing.
