### ISSUE TITLE
Game crash report

### ISSUE THREAD

**Issue by XSqjm** [mezz/JustEnoughItems#2518]
My game crashes when entering certain characters for an unknown reason
This is my crash-report:
https://gist.github.com/XSqjm/6a40afeef4eaa6b738389ed921aa8614
Thanks:D

**Comment by XSqjm** [comment]
when i enter number like 4 and 7 first,the game will be crash(

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
  Mod Name: OpenBlocks
  Registry Name: openblocks:glyph
  Display Name: "4" 雕文
  String Name: 1xitem.openblocks.glyph@52

-- JEI render details --
  Unique Id (for Blacklist): openblocks:glyph:52
  Ingredient Type: class net.minecraft.item.ItemStack
  Error Info: 1xitem.openblocks.glyph@52 openblocks:glyph
  Filter Text: 4
  Edit Mode Enabled: false
  Debug Mode Enabled: false
```
This appears to be this crash: https://github.com/OpenMods/OpenBlocks/issues/948
You can fix it by disable anisotropic filtering or anti-aliasing in Optifine.
