### ISSUE TITLE
Shapeless recipes indicator

### ISSUE THREAD

**Issue by xbony2** [mezz/JustEnoughItems#252]
It would be nice if there was a configuration that allowed the user to separate shaped and shapeless recipes, like how NEI does it. At the FTB Wiki, we consider the distinction important for documentation.

**Comment by Prospector** [comment]
It wouldn't even need to be a seperate category...what if there was just a
S or an S with a line through it to show shaped vs not shaped

**Comment by Prospector** [comment]
Next to the recipe of course

**Comment by mezz** [comment]
Would an indication that it's shapeless on the recipe work for you?
The distinct categories are not helpful for people just looking for recipes.

**Comment by TehNut** [comment]
+1 for an indicator of shaped vs shapeless instead of separate categories.

**Comment by KnightMiner** [comment]
On the Minecraft Wiki we use a little swirly arrow icon with a tooltip to mark shapeless recipes. Otherwise another option is like the FTB wiki does and remove the lines between the crafting table cells

**Comment by xbony2** [comment]
As long as you can tell they're different, it's good enough for me ^_^

**Comment by mezz** [comment]
![2016-04-17_15 35 12](https://cloud.githubusercontent.com/assets/916092/14590555/76e8bd3a-04b2-11e6-9936-e988162caecd.png)

**Comment by Prospector** [comment]
could it maybe be above the arrow instead? lol it's not centred or anything :P

(sorry it bothers me)

**Comment by Prospector** [comment]
er--also is that for the top or bottom recipe? aren't those both shapeless recipes?

**Comment by mezz** [comment]
It's aligned the same way as the wiki, top right. http://minecraft.gamepedia.com/Crafting#Complete_recipe_list

![](http://memesvault.com/wp-content/uploads/Deal-With-It-Dog-Gif-01.jpg)

**Comment by mezz** [comment]
The top recipe is also shapeless, but there's only 1 item so informing the user of its shapelessness would just be noise.

**Comment by Prospector** [comment]
well it would be good to know because I know a lot of mods that have shaped recipes with one or two items, so knowing if it's actually shapeless or a mod dev derp is good.

no particular examples at hand but I know I've seen them and it's annoying :P

**Comment by mezz** [comment]
A shaped recipe with one item can still be placed anywhere in the grid, so it's effectively the same as shapeless.

**Comment by Prospector** [comment]
not if it's defined to be blank in every other spot. when I was starting modding I made that mistake a lot

`"   ", " x ", "   "`would only work in the centre spot.

edit: damn it github stop removing my spaces

**Comment by mezz** [comment]
If it's defined to be blank in every other spot, JEI will show the shapeless icon.

**Comment by mezz** [comment]
Wait what? Sorry but you have bigger issues if you do that :p

**Comment by Prospector** [comment]
Not saying I do, but some people do. If JEI just always showed the shapeless icon if it's shapeless then it would be way easier to make sure a recipe is shapeless and not a DerpRecipe(tm)

**Comment by mezz** [comment]
I'm siding with "nice to use" over "ultimate recipe debugger".

**Comment by Prospector** [comment]
configggggggggggggggggggggggggggggggggggggg lol

**Comment by Prospector** [comment]
Actually I have a practical usage for my argument. UU matter (in TechReborn and old IC2) placed in different spots in the crafting grid causes different items to be crafted. All shapeless recipes should have the icon, for consistency and these (albeit rare) cases. I also I've experienced other cases of this, can't think of any off the top of my head.
