### ISSUE TITLE
Install FTB Library to access ingame config

### ISSUE THREAD

**Issue by ZAKsPop** [mezz/JustEnoughItems#2521]
jei-1.16.5-7.7.1.126 causing the aforementioned issue.

I have ftb-library-forge-1605.3.3-build.74.jar installed.

**Comment by BedrockLegends** [comment]
Same the new issue seems to have broken this again, @mezz has had to fix this before

**Comment by Darkmega18** [comment]
ditto. gonna backdate for a bit. cause with my client configs constantly resetting themselves for an unknown reason IN THE MIDDLE of playing the game changing itself back to the default from my favored inventory mode is annoying as hell when I can't fix it.

**Comment by Eric-01** [comment]
As a good workaround (or even a permanent solution), you can use MrCrayfish's Configured mod instead, which makes mod configs accessible in game for almost all Forge mods, including the JEI's one.

**Comment by MechanosG** [comment]
I'm having the same issue.  Guess I'll go back a version and see if that fixes it.

@Eric-01 - Thanks for pointing me at that Configured mod.  Definitely helpful.  ~~Although I don't think it's displaying all of JEI's options, such as toggling into cheat mode when singleplayer debugging.  Or at least I wasn't able to find it after testing Configured.~~

Edit:  Going back one version to 125 fixes the JEI Config button.  However, seems I was wrong about "Configured" not showing some options.  I could have sworn there was a toggle to enable easy grabbing of items if cheats are enabled, but I must have been thinking about REI or an older version of JEI.

**Comment by mezz** [comment]
Thanks for the report!
It seems like FTB Library hasn't been very dependable, I have removed support for it and now recommend installing the Configured mod to configure mods in-game. Sorry, I wish this was built into Forge like in previous versions.

**Comment by Darkmega18** [comment]
looks like I'm keeping it out of date then, until I can figure out why my client side configs keep resetting themselves. :V
