### ISSUE TITLE
[1.16.5] Config file no longer working

### ISSUE THREAD

**Issue by Discomanco** [mezz/JustEnoughItems#2525]
The config file for jei-client appears to no longer be working.  
Things like MaxColumns, GiveMode, CenterSearch doesn't do anything.
These are fresh configs, deleted before client was booted, in a fresh world

Mods:  
JEI 7.7.1.126
FTB Library 1605.3.3 build 74
Architectury 1.23.33
![image](https://user-images.githubusercontent.com/4707702/137513686-8974dc71-9482-4dbf-9feb-1890dc252546.png)
and ofc the whole "FTB Library no longer works" thing, but thats already reported.
(also tested without FTB Library and Architectury, no change)

**Comment by Ocraftyone** [comment]
this is also happening on jei 1.17.1-8.1.0.26 in ATM 7

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the latest JEI versions for 1.16 (`7.7.1.128`) and 1.17 (`8.1.0.31`).
