### ISSUE TITLE
JEI Mod does not appear 1.16.5

### ISSUE THREAD

**Issue by themancum** [mezz/JustEnoughItems#2526]
The Forge detects it as a loaded mod but at the moment of playing not a trace appears, not even pressing CTRL + O.

**Comment by themancum** [comment]
I've been doing some mods and it seems to me that the Armventure is incompatible with the JEI in my personal mod pack.

I will continue to report!

**Comment by mezz** [comment]
Thanks for the report.
Have you found any more information?
I could use some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
