### ISSUE TITLE
Some Requests!

### ISSUE THREAD

**Issue by RoyalKingsCrown** [mezz/JustEnoughItems#253]
I love this mod already! Quite the impressive, but I would like it if you could add these features:
-Ability to change the time of day without commands
-Ability to create fireworks without having to craft them manually
-Ability to place flower pots with flowers already in them
-Regenerate all health
-Add saves!
-Trash can button

**Comment by TehNut** [comment]
All of those belong in separate mods. Some of them already are, actually.

Trash Can - [TrashSlot](http://minecraft.curseforge.com/projects/trashslot)
Change time - [FTBLib](http://minecraft.curseforge.com/projects/ftblib)

**Comment by Prospector** [comment]
None of those features have anything to do with a recipe viewer. Out of the scope of the project.

**Comment by mezz** [comment]
Thanks for the suggestions, however JEI is just for items and recipes.

In addition to the other mods that have filled in the gaps a bit, @covers1624 is working on NotEnoughWidgets which will work alongside JEI to bring those features to 1.8+.
[You can subscribe to the thread here to get updates.](https://github.com/TheCBProject/NotEnoughItems/issues/6)

At some point there should be a Fireworks recipe handler but I haven't started on it, see https://github.com/mezz/JustEnoughItems/issues/91

> Ability to place flower pots with flowers already in them

This sounds cool but could be done better by another small mod that adds them in as items.
