### ISSUE TITLE
In-game config not accessible [1.16.5]

### ISSUE THREAD

**Issue by nanonestor** [mezz/JustEnoughItems#2533]
The in-game config is inaccessible - the automatic in-game message is that FTB GUI Library needs to be installed (It is... both mods are updated to their respective latest release versions.):

(Using Forge 36.2.8)
ftb-library-forge-1605.3.3-build.74
jei-1.16.5-7.7.1.126.jar

From previous threads it sounds like FTB GUI Library has changed it's name and that reference needs to be remedied within the JEI code which is looking for it.
![ftblib](https://user-images.githubusercontent.com/68798571/138541219-71a94ef1-c074-44da-bc51-5d0085d1b28d.JPG)

**Comment by DesolateElf-dev** [comment]
I'm having the same issue

**Comment by DesolateElf-dev** [comment]
I found the solution in another issue https://github.com/mezz/JustEnoughItems/issues/2521

But even if I change the gui to show more then just 9 columns, it keep at 9, the default is 7, but if i put 2 or 20, it keep showing 9

**Comment by nanonestor** [comment]
The linked isn't a solution - it's a workaround by adding a separate mod.  The current release jei-1.16.5-7.7.1.126 is not working as intended.

**Comment by mezz** [comment]
Thanks for the report!
It seems like FTB Library hasn't been very dependable, I have removed support for it and now recommend installing the Configured mod to configure mods in-game. Sorry, I wish this was built into Forge like in previous versions.
