### ISSUE TITLE
Uncompatibility

### ISSUE THREAD

**Issue by Neikless** [mezz/JustEnoughItems#2535]
My JEI do not show in game, but its loaded, and keybinds do not help with this issue, i think that problem is with Mode MrCrayfish´s Furniture Mode, but i dont want to delete this mode from my folder, so know anyone how to fix this?

Thank you! 

EDIT: My brother I plaing with this modes, can see JEI, but i cant see this in game.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
