### ISSUE TITLE
Various problems with latest version

### ISSUE THREAD

**Issue by aaronhowser1** [mezz/JustEnoughItems#2536]
This is using `jei-1.16.5-7.7.1.126`

![image](https://user-images.githubusercontent.com/15698722/138566946-6d32b130-fe19-46d9-b727-8294055f58aa.png)
Bookmarks are shifted to the right, instead of being under FTB Library stuff.

Searching is on the right instead of the middle, even though center search is enabled.
![image](https://user-images.githubusercontent.com/15698722/138566983-c50bde84-d640-4b84-b746-3783ca8552db.png)

![image](https://user-images.githubusercontent.com/15698722/138567009-5a51cc4d-ba40-4e42-8362-479600963c91.png)
When there are no bookmarks, the button is still there.

![image](https://user-images.githubusercontent.com/15698722/138567017-dacc029f-b4ae-4cb7-8e57-0e5b8ff85d54.png)
Clicking doesn't hide the button, and it has a missing lang key

![image](https://user-images.githubusercontent.com/15698722/138566959-f4b2dc23-1b25-474b-aa41-6e35ace43cdf.png)
FTB Library is installed.
![image](https://user-images.githubusercontent.com/15698722/138566967-23416f1a-3fdf-44fd-9875-751827824619.png)

Give Mode: Inventory doesn't work, clicking an item puts it into my mouse instead of the first open slot in my inventory

**Comment by mezz** [comment]
Thanks for the report!
Most of these issues have been fixed in `jei-1.16.5-7.7.1.128`


> Bookmarks are shifted to the right

This is normal if there is enough room to display all the bookmarks, or enough room to display more bookmarks to the right than there is room to display them under.

> When there are no bookmarks, the button is still there.

This is normal, to show people how to add bookmarks

> it has a missing lang key

I thought this was a Forge issue but I may still need to fix this actually, I'll take a closer look now.

**Comment by mezz** [comment]
> it has a missing lang key

This is now fixed in JEI `7.7.1.129`, thanks for reporting!

**Comment by aaronhowser1** [comment]
> This is normal if there is enough room to display all the bookmarks, or enough room to display more bookmarks to the right than there is room to display them under.

In previous versions, the bookmarks were underneath the FTB mod buttons, with the bookmark button being in the very bottom left.
