### ISSUE TITLE
JEI and Configured mod

### ISSUE THREAD

**Issue by ItsColdFire18** [mezz/JustEnoughItems#2538]
Using jei version jei-1.16.5-7.7.1.129 its saying use configured mod to access ingame config. i have configured version configured-1.2.0-1.16.3 it still gives me this error. i dont know what to do.
![Screenshot 2021-10-25 112411](https://user-images.githubusercontent.com/93148932/138733711-c8b35b3a-bd40-40b1-8db1-5d2a12da1e97.png)

**Comment by JeNaiKe** [comment]
Can confirm it, same versions. Not game breaking since config from the file still applies.

**Comment by ItsColdFire18** [comment]
yes i can change it in the config in the file just not in game

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest versions for JEI for 1.16 and 1.17
