### ISSUE TITLE
when im trying to load save my game crash but when im starting new game it work. ( anisotropic filtering or anti-aliasing off dont fix my problem) sorry for my bad english

### ISSUE THREAD

**Issue by dominika1947** [mezz/JustEnoughItems#2539]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
