### ISSUE TITLE
[Request]: Please for the love of all that's holy, Readd the NEI Dump tools!

### ISSUE THREAD

**Issue by Lanse505** [mezz/JustEnoughItems#254]
As a pack author the single greatest tool in my opinion in NEI was the Dump tool.
To my knowledge in 1.9 the only thing that comes close to this is the TellMe mod.

The dump tool in question would simply generate a list of whatever selected registry you decide to "dump". IE. Block, Item, Entity, Container, and Dungeon Loot (there are probably some good ones i'm forgetting). 

If this is already an implemented feature or on the ToDo list and I've missed it thus far I apologize ahead of time!

Pictures for Reference:
Will add soon!

**Comment by shadowfacts** [comment]
This belongs in a different mod. JEI is a recipie viewing mod, not a clone of NEI.

**Comment by Prospector** [comment]
@mezz Could you put a note like "JEI is not a replacement for NEI, it is purely a recipe viewer. Do not suggest features that do not belong in a recipe viewer!" in the issue preset and readme?

**Comment by mezz** [comment]
NotEnoughWidgets is coming soon with the missing NEI features! This does not really belong in JEI.
