### ISSUE TITLE
JEI is limited to 9 colums

### ISSUE THREAD

**Issue by zaze06** [mezz/JustEnoughItems#2540]
Hi, whoever reads this. I have a problem whit the JEI items display being limited to 9 columns. I have selected in the config file 40 columns for JEI but after restarting it is still limited to 9 columns.
![image](https://user-images.githubusercontent.com/54169874/138741457-74dae522-2894-44e2-8bc4-b2c52dc65890.png)
So is this a local problem?
FTB Library is present but JEI dos not find it and tells me to install it.
JEI version: 7.7.1.126
FTB library version: 1605.3.3-build.74
Minecraft version: 1.16.5
Forge Version: 36.2.8

**Comment by NielsPilgaard** [comment]
This has been fixed in the latest update :)

**Comment by zaze06** [comment]
Ok. I Will update and test then.

**Comment by zaze06** [comment]
Yup, it works now thanks.
