### ISSUE TITLE
[1.16.5] Shader Rendering issue with items when using Optifine G8 with BSL and/or Complimentry Shaders

### ISSUE THREAD

**Issue by Shibva** [mezz/JustEnoughItems#2542]
In Optifine 1.16.5 G7 this issue did not exist and it was today (the date this was created) that I upgraded to G8 and I noticed an issue with the item render with the JEI items, their lighting was messed up for some reason

I went to my shaderpacks discord (Using Complimentry; a fork of BSL) and had a chat, I asked around and found that this issue can be potentaly be fixed by Optifine, and/or You guys. How IDK but I bet the kind folks on the Complimentery Discord will be able explain what might be happening and how to fix it

the shaders are great and it would be a shame that I had to disable them over a small issue as this.

A fix would be nice because I cant imagine not having this mod in the mix of things

as a final side note, I want to thank the mad lads that made this mod possible and being such a useful asset to the community

Screenshot of the issue
![image](https://user-images.githubusercontent.com/38770780/138812647-e4006c8b-17d5-42d2-ada9-03750de399e2.png)

Relatively same snapshot but it running Optifine HD 1.16.5 G7 instead of G8 like in the one above
![image](https://user-images.githubusercontent.com/38770780/138814370-772dd159-6ead-4084-8fcb-d265ffbf64d2.png)

**Comment by Shibva** [comment]
this issue has been confimed as well for others as it can be found via this report link

https://github.com/sp614x/optifine/issues/5687

**Comment by Shibva** [comment]
Additional Notes:

Forge version: 36.2.8 (lattest as of this time)

Mods present: will provide if needed; Optifine and this mod are present naturally since this report is based on the 2

REMEMBER: this issue is only present in G8, you will not be able to reproduce this issue if your using G7 Optifine

**Comment by mezz** [comment]
Thanks for the report!
JEI is just rendering items, unfortunately rendering issues like this happen occasionally and it is up to Optifine to fix.
