### ISSUE TITLE
Minecraft Crash when i join my own server

### ISSUE THREAD

**Issue by Matpods** [mezz/JustEnoughItems#2544]
I have installed JEI version 1.16.5-7.7.1.129. I join my server and Minecraft Crash

**Comment by Matpods** [comment]
It is the crash report file

https://gist.github.com/Matpods/e8038e3a754fc2549ea992d1b8145a2d

**Comment by Ommina** [comment]
Looks like https://github.com/SlimeKnights/TinkersConstruct/issues/4631

**Comment by Matpods** [comment]
I didn't understand, what should I do to play Minecraft with Tinker Construct and JEI installed

**Comment by Ommina** [comment]
"Fixed in 3.1.3.271"

Update Tinker's Construct to 3.1.3.271 or (presumably) later.
