### ISSUE TITLE
suggestion: astral sorcery info tab

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [mezz/JustEnoughItems#2545]
astral sorcery info tab::
an entry from the luminous crafting table of the astral tome:

 "place a crafting table in a larger shrine found on surface in overworld (zone 0) then make sure the tutorial shrine has enough starlight reaching it to activate it (you may need to excavate a large amount of the storm roof to allow productive STAR luminance."
 
in order for the Luminous Crafting Table to work it must be placed somewhere open to the sky, preferably at night for the correct intensity of star energy. This table has a “Star Light” meter at the bottom when you open it. This will fill up depending on where the table is placed and the time. In the middle of the night, your table will have higher levels of Star Light than during the day. Tables placed at a higher elevation (max Y-level 120) will also get more Star Light. Higher levels can be achieved if you are near a Collector Crystal or in an area of high Starlight concentration (more on this later). This Star Light level is also affected by where the moon is and where you are in world, as it depends on what Constellations the table can see. During the day you will get next to no Star Light.

**Comment by Ommina** [comment]
This is something that Astral Sorcery would have to add, should they want it.  Looking at your linked issue, it appears they have explicitly selected the Tome as their guide.
