### ISSUE TITLE
Open Recipe from ItemStack

### ISSUE THREAD

**Issue by joshiejack** [mezz/JustEnoughItems#255]
I had a look around the code, and I'm probably blind... 

Is there a method at all for simply opening the recipes of an item, by passing in an itemstack. All I could find was how the recipes are opening from a focus, but I couldn't find a way to open the recipe myself. (Without going down a long reflection path). My use case is simply being able to open a JEI recipe by clicking on an item in my own gui.

**Comment by mezz** [comment]
There's no way to open a recipe in JEI using the API.
Generally users will press R or U over an itemStack, and JEI will look at the current `guiContainer.getSlotUnderMouse()`. Doing it this way keeps things consistent.

If you really want to see how JEI calls it, [you can start here](https://github.com/mezz/JustEnoughItems/blob/1.9/src/main/java/mezz/jei/input/InputHandler.java#L215-L227) (it uses `Focus`). It will break if I change internal stuff though.

If you have a compelling case I can add a method to the API to open the recipe, but at the moment I'm happy with R and U.

**Comment by joshiejack** [comment]
Yeah I followed the line and worked out how to get it working, just wasn't sure if there was an easier way. So thought I'd ask just in case. There's no container/slots where I'd be opening it. Why I needed to do it that way.

**Comment by mezz** [comment]
Is it a guide book without recipes or something like that? Hmm maybe something like the HQM book would need this.

**Comment by joshiejack** [comment]
Yeah my use is pretty much like hqm. Clicking on a crafting task to be able to display the recipe for it, for users sake/convenience.

**Comment by mezz** [comment]
You can now select recipes using the [`IRecipesGui`](https://github.com/mezz/JustEnoughItems/blob/1.9/src/main/java/mezz/jei/api/IRecipesGui.java). 

You can get the instance from `IJeiRuntime.getRecipesGui()`. 
The `IJeiRuntime` is passed to your `IModPlugin` when it is available (`onRuntimeAvailable` when the game is running).

**Comment by joshiejack** [comment]
Thanks =)
