### ISSUE TITLE
Jei crashes after searching 'ax'

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2551]
https://pastebin.com/WDWbMFCy

**Comment by WFPhantom** [comment]
This is a known issue with VMW. You can either downgrade forge, install optifine or what VMW recommends, go to the forge config file and disable "allowEmissiveItems"

**Comment by mezz** [comment]
Thanks for the report!

The message from the VMW mod can be viewed here: https://www.curseforge.com/minecraft/mc-mods/vics-modern-warfare-mod

> This mod crashes on Forge versions higher than 14.23.4.2759 because Forge made a change on their side that we haven't found a workaround for. Here are 3 easy solutions of fixing this:

> Recommended solution: If you visit .minecraft/config and locate "forge.cfg" - open it and look for "allowEmissiveItems" and turn it to false.
The other two solutions are: Install Optifine or downgrade your forge version.
