### ISSUE TITLE
[1.16.5] Cannot open the JEI menu, and I don't know why

### ISSUE THREAD

**Issue by the-lpsilva** [mezz/JustEnoughItems#2552]
In 1.16.5, when I open the inventory in survival mode, the JEI menu doesn't appear. 
I've tried to use all possible commands, but it doesn't work. 
What must be the problem?

**Comment by Boolyman** [comment]
I think this is some ploy to get people to download the Configured mod.  There is an in-game JEI button that doesn't work... it just tells you to download the Configured mod.  When you download the Configured mod, the button still says to download the configured mod.  You have to go back to the main menu, search for JEI in the mods button, edit the config manually, and then reload your world.  So what is the point of the in-game JEI config button?  It's a conspiracy I tell ya.

I'm only half joking.

**Comment by DeLoreanPro** [comment]
I have to add on to this: Not only does the JEI ui not seem to exist, but all crafting recipes period. The recipe book only has the "All" tab and no recipes.
![Screenshot (674)](https://user-images.githubusercontent.com/63178577/140425039-7ceb2790-efd9-4215-8a65-8d378429363f.png)

**Comment by Raidobw2** [comment]
I've noticed the JEI menu working again in `jei-1.16.5-7.7.1.130.jar`. I'd recommend testing with that version and the Configured mod @the-lpsilva and closing this issue if it's resolved, to help the mod author focus on new issues.

**Comment by DeLoreanPro** [comment]
Found the issue for my case: Advent of Ascension.

**Comment by Sixdd6** [comment]
Having the same issue here and I don't have Advent of Ascension.
[debug.log](https://github.com/mezz/JustEnoughItems/files/7489812/debug.log)

**Comment by mezz** [comment]
> Having the same issue here and I don't have Advent of Ascension. [debug.log](https://github.com/mezz/JustEnoughItems/files/7489812/debug.log)

Unfortunately this debug log seems to be truncated, can you upload your latest.log instead?
