### ISSUE TITLE
JEI Missing 95% of CBMicroblock items except for Stone

### ISSUE THREAD

**Issue by djoveryde** [mezz/JustEnoughItems#2553]
All CBMicroblock items are missing from JEI except stone items. I have been unable to figure out why it fails to show all other items. These are however available in creative which is no good for players in game.
All mods are latest versions available for 1.16.5.

1. Install latest 1.16.5 version of CBMultipart
2. Search @CBMicroblock in JEI
3. Only stone microblocks will show

- Minecraft: 1.16.5
- Forge: 36.2.8
- Refined Storage:

**Comment by mezz** [comment]
Thanks for the report!
Please report this to CBMicroblock. To display this correctly, they will need to register a subtype interpreter with their JEI plugin. You can link them here for more info: https://github.com/mezz/JustEnoughItems/wiki/Item-Subtypes-%5B1.13-and-Up%5D

**Comment by ALainxD** [comment]
BTW i think this is intended since you would have multiple sites of spam in JEI otherwise
