### ISSUE TITLE
Game crashes randomly when searching

### ISSUE THREAD

**Issue by Mc-man165** [mezz/JustEnoughItems#2554]
Playing ftb oceanblock on a server with JEI on 1.16.5-7.7.1.129.

No idea why it does this just crashes when searching various things for me and my friend playing on my server. Its happened at least 10 times between us over a week now in different circumstances. 

Hopefully these logs help

[2021-11-04-1.log](https://github.com/mezz/JustEnoughItems/files/7479845/2021-11-04-1.log)
[debug-1.log](https://github.com/mezz/JustEnoughItems/files/7479847/debug-1.log)

**Comment by General-Knutin** [comment]
Hi there. 
I had the same issue (JEI on 1.16.5-7.7.1.130), however I think it's more like an forced closing rather than a game crash because Minecraft behaves the same and shows the same massage when I force closed it with the Task Manager. 

I've tested a bit and found a replicatable setting:
These are the Mods
![mods](https://user-images.githubusercontent.com/93824728/140612186-fb599875-3b22-452b-8688-5204d2f6dddc.jpg)

Forge version: 36.2.9

In my case it also worked in singleplayer.
When I now typed "i" and then "r" the game closed itself. The "r" itself doesn't seems to be the problem because when I typed "rr" nothing happend. I also changed and removed various keybindings and it still occured, though after removing the mods and starting the game with JEI only and then returning to the original setup it fixes the issue, but I don't know how why. Can be reversed by starting it without JEI and then returning to the setup.

Hope this helps

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately the debug log doesn't seem to contain the crash report I'm looking for.
@General-Knutin do you have a latest.log or crash log you can share here?

**Comment by General-Knutin** [comment]
@mezz
Sure.
These are the game logs:
[latest.log](https://github.com/mezz/JustEnoughItems/files/7497364/latest.log)
[debug.log](https://github.com/mezz/JustEnoughItems/files/7497365/debug.log) 
But no crash log was created.

**Comment by mezz** [comment]
Hmm there's really nothing in the log here that indicates a crash.
I wonder, did Java itself crash?

Do you have any files that start with `hs_err_pid` in your minecraft directory? If you do, that's a java error log, which is pretty rare! If that is the issue, you may be able to fix it by updating Java. 
I helped debug a Java crash like that a while ago here: https://github.com/mezz/JustEnoughItems/issues/1365

**Comment by Mc-man165** [comment]
Yes I have 11 of those files.... soooo that must be it. Here is the most recent if you are curious but ill try updating java.
[hs_err_pid42172.log](https://github.com/mezz/JustEnoughItems/files/7509409/hs_err_pid42172.log)

**Comment by mezz** [comment]
Ok cool!
Here's the stack trace from your log:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.opengl.GL20C.nglShaderSource(IIJJ)V+0
j  org.lwjgl.opengl.GL20C.glShaderSource(ILjava/lang/CharSequence;)V+38
j  org.lwjgl.opengl.GL20.glShaderSource(ILjava/lang/CharSequence;)V+2
j  codechicken.lib.render.shader.AbstractShaderObject.alloc()V+64
j  codechicken.lib.render.shader.ShaderProgram$$Lambda$25151.accept(Ljava/lang/Object;)V+4
J 13734 C2 java.util.ArrayList.forEach(Ljava/util/function/Consumer;)V (75 bytes) @ 0x0000000004d7db1c [0x0000000004d7da60+0xbc]
j  codechicken.lib.render.shader.ShaderProgram.compile()V+39
j  codechicken.lib.render.shader.ShaderProgram.pushCache()Lcodechicken/lib/render/shader/UniformCache;+1
j  com.brandon3055.draconicevolution.client.render.item.ToolRenderBase.getShaderType(Lnet/minecraft/client/renderer/RenderType;Lcom/brandon3055/brandonscore/api/TechLevel;Lcodechicken/lib/render/shader/ShaderProgram;F)Lcodechicken/lib/render/shader/ShaderRenderType;+1
j  com.brandon3055.draconicevolution.client.render.item.ToolRenderBase.getShaderType(Lnet/minecraft/client/renderer/RenderType;Lcom/brandon3055/brandonscore/api/TechLevel;Lcodechicken/lib/render/shader/ShaderProgram;)Lcodechicken/lib/render/shader/ShaderRenderType;+4
j  com.brandon3055.draconicevolution.client.render.item.RenderModularPickaxe.renderTool(Lcodechicken/lib/render/CCRenderState;Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;Lcodechicken/lib/vec/Matrix4;Lcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;ZI)V+248
j  com.brandon3055.draconicevolution.client.render.item.ToolRenderBase.renderItem(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;Lcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;II)V+59
J 47135 C2 net.minecraft.client.renderer.ItemRenderer.handler$zch000$onRenderItem(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;ZLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;IILnet/minecraft/client/renderer/model/IBakedModel;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V (69 bytes) @ 0x000000000975f108 [0x000000000975eac0+0x648]
J 52388 C2 net.minecraft.client.renderer.ItemRenderer.func_229111_a_(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;ZLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;IILnet/minecraft/client/renderer/model/IBakedModel;)V (455 bytes) @ 0x000000000a63b8e4 [0x000000000a63b7e0+0x104]
J 43257 C2 net.minecraft.client.renderer.ItemRenderer.func_239387_b_(Lnet/minecraft/entity/LivingEntity;Lnet/minecraft/item/ItemStack;II)V (160 bytes) @ 0x000000000901bcbc [0x0000000009019fe0+0x1cdc]
J 46601 C2 mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(Lcom/mojang/blaze3d/matrix/MatrixStack;IILjava/lang/Object;)V (13 bytes) @ 0x00000000084e2558 [0x00000000084e1ee0+0x678]
J 52763 C2 mezz.jei.render.IngredientListElementRenderer.renderSlow(Lcom/mojang/blaze3d/matrix/MatrixStack;Lmezz/jei/config/IEditModeConfig;Lmezz/jei/config/IWorldConfig;)V (91 bytes) @ 0x000000000965a06c [0x0000000009659fc0+0xac]
J 40639 C2 mezz.jei.render.IngredientListBatchRenderer.render(Lnet/minecraft/client/Minecraft;Lcom/mojang/blaze3d/matrix/MatrixStack;)V (398 bytes) @ 0x00000000096104c8 [0x000000000960da60+0x2a68]
J 49940 C2 mezz.jei.gui.GuiEventHandler$$Lambda$23379.accept(Ljava/lang/Object;Ljava/lang/Object;)V (12 bytes) @ 0x000000000abeb3ec [0x000000000abe9c80+0x176c]
J 45837 C2 mezz.jei.events.EventBusHelper$$Lambda$23213.accept(Ljava/lang/Object;)V (16 bytes) @ 0x00000000045540b4 [0x0000000004554020+0x94]
J 24488 C2 net.minecraftforge.eventbus.EventBus$$Lambda$2842.invoke(Lnet/minecraftforge/eventbus/api/Event;)V (21 bytes) @ 0x0000000006732ea0 [0x0000000006732de0+0xc0]
J 49565 C2 net.minecraft.client.gui.screen.Screen.func_238651_a_(Lcom/mojang/blaze3d/matrix/MatrixStack;I)V (58 bytes) @ 0x000000000aae5740 [0x000000000aae5560+0x1e0]
J 43943 C1 com.refinedmods.refinedstorage.screen.grid.GridScreen.func_230430_a_(Lcom/mojang/blaze3d/matrix/MatrixStack;IIF)V (45 bytes) @ 0x0000000008094a9c [0x0000000008094860+0x23c]
J 48187 C2 net.minecraft.client.renderer.GameRenderer.func_195458_a(FJZ)V (861 bytes) @ 0x0000000008c7d558 [0x0000000008c7b460+0x20f8]
J 45179 C2 net.minecraft.client.Minecraft.func_195542_b(Z)V (994 bytes) @ 0x0000000009ace5e0 [0x0000000009acd6c0+0xf20]
J 52767% C1 net.minecraft.client.Minecraft.func_99999_d()V (208 bytes) @ 0x0000000009f9bf34 [0x0000000009f9bc20+0x314]
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1379
```

It looks to me like JEI is trying to render an item from Draconic Evolution, and that item uses CodeChicken Lib to render it with some kind of shader, which is absolutely not working with your graphics driver, causing the crash.
You should try updating your graphics drivers, and if nothing works then try reporting to Draconic Evolution.

**Comment by Mc-man165** [comment]
Any idea why that only happens like 10% of the time?

**Comment by mezz** [comment]
It might be a bug in the shader code that unintentionally tries to access some graphics memory it shouldn't. Bugs like that might only crash sometimes, where most of the time it does a bad access but it's ok, but other times it tries to access a restricted area and that causes a crash.

**Comment by Mc-man165** [comment]
Okay interesting, so far updating Java seems to actually have fixed it so ill close the issue. All 11 of the logs mention the same thing with draconic rendering something so ill post over there if it keeps happening. Thanks for the help!

**Comment by mezz** [comment]
Cool, glad that fixed the issue!
