### ISSUE TITLE
Need Some Help with an unknown Issue

### ISSUE THREAD

**Issue by birdbirdbirdbi** [mezz/JustEnoughItems#2557]
When I join my server with JEI, the menu does not appear on the side, but this doesn't happen in single player. This has occurred on many different versions. I've seen the solution to be something with the server config settings in other similar issue threads, but Jei does not have anything in either of the config folders for me, and downloading and running different versions has not fixed this. I'm at a complete loss.

**Comment by mezz** [comment]
Thanks for the report!
I got a similar report here, can you check if it has the same solution (try removing Growthcraft)? https://github.com/mezz/JustEnoughItems/issues/2565
