### ISSUE TITLE
JEI "configured mod" is nowhere to be found.

### ISSUE THREAD

**Issue by TreyAyy** [mezz/JustEnoughItems#2558]
When I click the wrench in game it tells me I need this "configured" mod to access the JEI config but I can't find this mod anywhere. It's not under JEI dependencies in Curseforge and the only thing that comes up on google is Mr.Crayfish's configured mod, so I don't really know what to do to access the JEI settings. I'm running on 1.16.5.

**Comment by Ommina** [comment]
Mr. Crayfish "Configured" is correct: https://www.curseforge.com/minecraft/mc-mods/configured

**Comment by celeste-42bit** [comment]
For all the people running Fabric, the port of the configured mod does not work. Can we please go back to how it was before we needed this addon?
