### ISSUE TITLE
fake website for jei

### ISSUE THREAD

**Issue by yhkhoo** [mezz/JustEnoughItems#2559]
I am writing this issue to bring your attention to a fake website for jei i have noticed. The website is located at https://justenoughitems.com/. I feel this website is fake as it is written in even worse English than what I am writing this issue with, and that it mentions that jei is a "9minecraft mod"
This is an issue because it is redirecting users away from the actual jei curseforge and github, misleading them. The website appears quite high on the search results for "just enough items" or "jei"

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately sites like this are difficult to take down, they are often hosted in countries that do not respect copyright.
I have taken down the 9minecraft page for JEI multiple times but they will simply put it back up a little while later.
Please help spread awareness in the community that these mod rehosting sites are sketchy and illegal.
