### ISSUE TITLE
JEI taking forever to load "Indexing Ingredients"

### ISSUE THREAD

**Issue by ThunderwolfPony** [mezz/JustEnoughItems#2560]
First of all, yes I know this is a ridicules use case, but I'm not looking to remove unnecessary mods as the mod count is the goal.
I'm making the biggest modpack I can, currently at 600+ mods and so far I have it running smoothly.
I'm still ironing out the problems here and there and most are pretty explanatory. But the biggest problem, as you can assume, is the load time at start up. Yes loading the massive amount of mods takes a long time but its stuck on JEI in particular.
Specifically "Indexing Ingredients"
![image](https://user-images.githubusercontent.com/56629665/141598539-1371c4b6-06d6-49ca-8c7c-84126151e18f.png)
I tried adding more ram (All the way to 128GB) and I tried setting less ram (down to 16GB) but either way it gets stuck on JEI. I did try leaving it to load over a couple days and it did eventually reach completion and was playable with no further problems, but its not ideal to wait that long for each time I start the pack, especially when adding more mods.
The reason why I'm making this post is not to remove other mods as thats not the point. (If its one or two mods or a group theb I can compromise)
I am looking for a solution to either bypass this phase or fix it.
[If you need any more information, ie modlist, computer specs, forge, java, or jei versions you may ask]

**Comment by mezz** [comment]
Thanks for the report!

I think if you are serious about this endeavor, you will need to become familiar with debugging performance problems in Minecraft.

In my experience, the best tool for figuring out why something is taking too long is a Java profiler.
A popular free Java profiler is VisualVM: https://visualvm.github.io/

You'll want to profile a few seconds while things are "stuck" and then you can see where in the code things are stuck.
You screenshot the results, and also export the data for other people to take a look here.

I expect you will run into a bunch of weird interactions in your pack, so this should be a useful technique for finding the source of bugs and reporting to the mod authors involved.
