### ISSUE TITLE
JEI does not show crafting  recipes 1.12.2

### ISSUE THREAD

**Issue by JEIisbroken** [mezz/JustEnoughItems#2561]
Jei does not show crafting table reciepes, but shows furnace, anvil etc
NO other mods installed
Things i have tried
- uninstalling minecraft
- uninstalling the mod
- uninstalling java
- setting all settings to default
- reinstalling windows

PLEASE HELP!!!!!!!!!!

**Comment by JEIisbroken** [comment]
EDIT: Reinstalling forge worked, will try adding mods now

**Comment by TR80R** [comment]
the issue is forge and the FTB mods not ruining well with JEI removing the FTB lib a dependency
