### ISSUE TITLE
[1.16.5][JEI 7.7.1.135] Can't use mouse button to see Usage/Recipe

### ISSUE THREAD

**Issue by drakray** [mezz/JustEnoughItems#2563]
Don't know if it's supposed to do that now?
Forge 36.2.9
Losta mods

**Comment by etherealgears** [comment]
I'm having the same or a similar issue. I can't click on an item inside the crafting grid of JEI to see its recipe. I can right-click and left-click to see usage/recipe fine in the actual JEI menu, but I can't access the usage/recipe of items in the grid. Here's a picture to explain which part works and which part doesn't:

![worksnotworks](https://user-images.githubusercontent.com/93540791/141761111-8a200240-0779-433c-8ec1-1d70d2dba595.jpg)

**Comment by MickeyMouseYT** [comment]
Yeah me too

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next version, released shortly.

**Comment by DEX47** [comment]
Not seeing an recipes in 7.7.1.136 for multiplayer. The exception is the Doggy Talents has some recipes showing up.

Forge 36.2.8

**Comment by mezz** [comment]
@DEX47 please open a new issue, that doesn't sound related to this issue.
