### ISSUE TITLE
Keyword Search

### ISSUE THREAD

**Issue by Xaikii** [mezz/JustEnoughItems#2564]
For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

Being able to define Keywords and include Item to those Keys is could be very useful.
It can help to improve to show dependencies for certain machines or Items that are generally similar.
e.g.
Keystone "Redstone", you could add Observers, Pistons, Slimeblocks etc.
or
Keystone "Sieve", you could add Meshes and the respective Input

**Comment by mezz** [comment]
Thanks for the suggestion!
I think you can achieve something like this by using Minecraft's tag system. JEI can search tags, so it will should work fairly easily.

**Comment by Xaikii** [comment]
theoretically possible yes, but it has it's drawbacks

1. Mods that iterate through all available Tags of Item or iterating through all items in a tag (I can already think of a few Mods doing this)
2. Many(if not even, the majority) of players play with Advanced Tooltips on. Item & Block Tags are shown on the Item. Yet again there are many Mods using (especially BlockTags) for their logic, partially adding a lot of Tags already to Items. Adding more on those would make it unreadable for any Player, if he would ever need to.
3. Exact Search Problems. Using ItemTags for this would be difficult for some areas. Again an example would be Redstone, in which you'd have to add related to the Redstone Tag which is used for Recipes by some Mods to ensure Compat. with other Mods.
