### ISSUE TITLE
1.16.5 [JEI 7.7.1.136] Multiplayer recipes not showing in game. 

### ISSUE THREAD

**Issue by DEX47** [mezz/JustEnoughItems#2565]
Thank you for reporting!

Minecraft Version 1.16.5
Forge Version 36.2.8
JEI 7.7.1.136

JEI behavior is normal in single player. However in multiplayer I am unable to access recipes. Tabs for JER 12.1.128 are displaying correctly. I also noticed some recipes form Doggy Talents 2.1.14 are display correctly.

**Comment by DEX47** [comment]
I will provide a mod list in a sec. I was about to update it with removing some.

**Comment by DEX47** [comment]
Mods list up to date as of 11-15-2012.

A Sylvan Origin [FORGE/FABRIC]
candycanecazoo
sylvano-0.1.0.jar

Abnormals Delight
TeamAbnormals
abnormals_delight-1.16.5-1.2.0.jar

Abyssal Depths
Chumbanotz
AbyssalDepths-1.16.5-1.0.1.jar

Advanced Chimneys
EnderLanky
AdChimneys-1.16.5-6.0.12.2-build.0191.jar

Advanced Mining Dimension
henkelmax
mining_dimension-1.16.5-1.0.6.jar

Alex's Mobs
alex_khaan
alexsmobs-1.12.1.jar

Aquaculture 2
Shadowclaimer
Aquaculture-1.16.5-2.1.21.jar

Aquafina
hugomage999
Aquafina no pollution.jar

Architectury API (Forge)
shedaniel
architectury-1.24.35-forge.jar

AstikorCarts [Horse Carts]
MennoMax
astikorcarts-1.16.5-1.1.1.jar

Astral Sorcery
HellFirePvP
astralsorcery-1.16-1.16.5-1.13.12.jar

Atmospheric
TeamAbnormals
atmospheric-1.16.5-3.1.0.jar

AutoRegLib
Vazkii
AutoRegLib-1.6-49.jar

Autumnity
TeamAbnormals
autumnity-1.16.5-2.1.1.jar

Berry Good
TeamAbnormals
berry_good-1.16.5-4.1.1.jar

BetterEnd Reforked
someoneelsewastaken
betterendforge-1.16.5-2.5.jar

BetterNether Reforged
someoneelsewastaken
betternether_reforged-1.2.jar

Blood Magic
WayofTime
BloodMagic-1.16.4-3.1.5-25.jar

Blueprint
TeamAbnormals
abnormals_core-1.16.5-3.3.0.jar

Bountiful (Forge)
ejektaflex
Bountiful-1.16.4-3.3.1.jar

Caelus API (Forge)
TheIllusiveC4
caelus-forge-1.16.5-2.1.3.2.jar

Citadel
alex_khaan
citadel-1.8.1-1.16.5.jar

Cloth Config API (Forge)
shedaniel
cloth-config-4.12.41-forge.jar

Collective (Forge)
Serilum
collective-1.16.5-2.65.jar

Cosmetic Armor Reworked
LainMI
CosmeticArmorReworked-1.16.5-v4.jar

Create
simibubi
create-mc1.16.5_v0.3.2f.jar

Create Addon
celsiusqc
create-addon-v5.jar

Create Automated
kotakotik22
createautomated-1.16.5-1.4.1.jar

Create: Steam Powered
yuesha_yc
steampowered-1.16.5-1.1.7c.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.5-4.0.5.3.jar

Curios Quark Oddities Backpack
6LeoMC
CuriosQuarkOBP-1.16.5-1.0.2.jar

Demon Origin (Forge/Fabric)
TheImperiumCentral
demonorigin-2.0.jar

Doggy Talents
percivalalb
DoggyTalents-1.16.5-2.1.14.jar

Druidcraft
VulpTheHorseDog
Druidcraft-1.16.5-0.4.54.jar

Dungeon Crawl
xiroc_
DungeonCrawl-1.16.5-2.3.3.jar

Environmental
TeamAbnormals
environmental-1.16.5-1.1.0.jar

Extended Lights
Polyvalord
extlights-3.3.jar

Farmer's Delight
vectorwing
FarmersDelight-1.16.5-0.5.1.jar

Farmer's Delight Compats
burritoeatinghamster
farmersdelightintegrations-1.16.5-1.2.jar

Filtered Chests
NaturaSpell
filteredchests-1.0.2.jar

Flower Seeds
Trhod177
flowerseeds-1.16.5-1.3.2.jar

Flywheel
jozufozu
flywheel-1.16-0.2.4.jar

ForgeEndertech
EnderLanky
ForgeEndertech-1.16.5-7.2.1.1-build.0192.jar

FTB Backups (Forge)
FTB
ftb-backups-2.1.2.2.jar

FTB Chunks (Forge)
FTB
ftb-chunks-forge-1605.3.2-build.81.jar

FTB Library (Forge)
FTB
ftb-library-forge-1605.3.4-build.83.jar

FTB Quests (Forge)
FTB
ftb-quests-forge-1605.3.5-build.72.jar

FTB Teams (Forge)
FTB
ftb-teams-forge-1605.2.3-build.38.jar

Gauges and Switches
wilechaote
rsgauges-1.16.5-1.2.12.jar

GeckoLib
ThanosGecko
geckolib-forge-1.16.5-3.0.54.jar

Goblin Traders
MrCrayfish
goblintraders-1.6.0-1.16.3.jar

Golden Hopper
MrCrayfish
goldenhopper-1.2.1-1.16.3.jar

GottschCore
gottsch
GottschCore-mc1.16.5-f36.1.0-v1.4.0.jar

Growthcraft Community Edition
Alatyami
growthcraft-1.16.5-6.0.6.jar

Guard Villagers
almightytallestred
guardvillagers-1.16.5.1.2.6.jar

Hardcore Revival
BlayTheNinth
HardcoreRevival_1.16.5-5.2.1.jar

HT's TreeChop
hammertater
TreeChop-1.16.4-0.14.6-fixed.jar

Hwyla
TehNut
Hwyla-forge-1.10.11-B78_1.16.2.jar

Inspirations
KnightMiner
Inspirations-1.16.5-1.2.3.38.jar

Iron Age Furniture
SkyBlade1978
ironagefurniture 1.16.4-1.16.5 0.2.0.5.jar

Item Filters (Forge)
LatvianModder
item-filters-forge-1605.2.5-build.9.jar

Just Enough Items (JEI)
mezz
jei-1.16.5-7.7.1.136.jar

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.16.5-0.12.1.128.jar

Kitsune Origin (Forge/Fabric)
TheImperiumCentral
kitsuneorigin-1.0.jar

Kotlin for Forge
thedarkcolour
kotlinforforge-1.15.1-obf.jar

Locks
Melonslise
locks-1.16.5-3.0.3.jar

Macaw's Doors
sketch_macaw
mcw-doors-1.0.3-mc1.16.5.jar

Macaw's Fences and Walls
sketch_macaw
mcw-fences-1.0.1-mc1.16.5.jar

Macaw's Lights and Lamps
sketch_macaw
mcw-lights-1.0.0-mc1.16.5.jar

Macaw's Roofs
sketch_macaw
mcw-roofs-2.0.1-mc1.16.5-4.jar

Macaw's Trapdoors
sketch_macaw
mcw-trapdoors-1.0.3-mc1.16.5.jar

Macaw's Windows
sketch_macaw
mcw-windows-2.0.0-mc1.16.5.jar

Mana and Artifice
AWildCanadianEh
mana-and-artifice-1.5.0.10.jar

Mantle
mDiyo
Mantle-1.16.5-1.6.127.jar

MarbleGate's Exotic Enchantment: Flowing Agony
marblegatekeeper
flowingagony-1.16.5-1.0.4.jar

More Create Stuffs
JerryLu086
morecreatestuffs-mc1.16-1.4.1b.jar

Mowzie's Mobs
bobmowzie
mowziesmobs-1.5.19.jar

Mystical World
Noobanidus
mysticalworld-1.16.5-0.3.5.24.jar

Nature's Aura
Ellpeck
NaturesAura-34.3.jar

Nether Portal Spread (Forge)
Serilum
netherportalspread_1.16.5-5.4.jar

Nether's Delight
lumpazl
nethers_delight-2.1.jar

Nether's Exoticism
Furti_Two
nether-s-exoticism-1.16.5-1.1.2.jar

NetherPortalFix
BlayTheNinth
NetherPortalFix_1.16.3-7.2.1.jar

NoCube's Sea Dwellers
nocubeyt
NoCube's_Sea_Dwellers_1.0.2.jar

ObserverLib
HellFirePvP
observerlib-1.16.5-1.5.3.jar

Occultism
kli_kli
occultism-1.16.5-1.19.3.jar

Odd Water Mobs
Tegus_Talpan
OddWaterMobs[1.16.5]_1.4.1.jar

Origins (Forge)
EdwinMindcraft
Origins-1.16.5-0.7.3.9-forge.jar

Pandoras Creatures
andrew0030
pandoras_creatures-1.16.3-2.0.1.jar

Patchouli
Vazkii
Patchouli-1.16.4-53.2.jar

Quark
Vazkii
Quark-r2.4-319.jar

Quark Oddities
Vazkii
QuarkOddities-1.16.3.jar

RandomPatches (Forge)
TheRandomLabs
randompatches-2.4.4-forge.jar

Savage & Ravage
TeamAbnormals
savageandravage-1.16.5-3.1.0.jar

Selene Lib
MehVahdJukaar
selene-1.16.5-1.9.0.jar

Serene Seasons
TheAdubbz
SereneSeasons-1.16.5-4.0.1.122-universal.jar

Shadekin Origin (Forge/Fabric)
TheImperiumCentral
shadeorigin-1.0.jar

Simple Wooden Pipes
Dogboy21
simplewoodenpipes-1.16.5-2.0.jar

Small Ships
talhanation
smallships-1.16.5-1.10.1.jar

Smarter Farmers (farmers replant)
MehVahdJukaar
smarterfarmers-1.16.5-1.2.1.jar

Snail Mail
Cicoda
snailmail-1.16.4-1.0.1.jar

Sophisticated Backpacks
P3pp3rF1y
sophisticatedbackpacks-1.16.5-3.11.1.390.jar

Spice of Life: Carrot Edition
lordcazsius
SoL-Carrot-1.16.5-1.10.1.jar

Storage Drawers
Texelsaur
StorageDrawers-1.16.3-8.3.0.jar

Stumble Upon: Campsites
PwrDownYT
StumbleUponCampsites.jar

Supplementaries
MehVahdJukaar
supplementaries-1.16.5-0.17.10.jar

The Endergetic Expansion
TeamAbnormals
endergetic-1.16.4-3.0.0.jar

The Twilight Forest
Benimatic
twilightforest-1.16.5-4.0.546-universal.jar

THE UNDEAD
punpanprolol
UNDEADv.1.3.release+Biome.jar

The Undergarden
Quek04
The_Undergarden-1.16.5-0.5.5.jar

Tinkers Construct
mDiyo
TConstruct-1.16.5-3.2.1.296.jar

Tiny Gates
Danny_and_Son
tinygates-0.1.2a.jar

Tiny Redstone
Danny_and_Son
tinyredstone-1.16.5-1.10.6.jar

Treasure2: Twilight Forest Loot Pack
gottsch
Treasure2TwilightForestLP-mc1.16.5-f36.2.0-v1.0.0.jar

Treasure2!
gottsch
Treasure2-mc1.16.5-f36.2.0-v1.7.2.jar

Tubes Reloaded
Commoble
tubesreloaded-1.16.5-1.5.0.3.jar

Upgrade Aquatic
TeamAbnormals
upgrade_aquatic-1.16.5-3.1.1.jar

Upstream
Corgi_Taco
upstream-1.0.jar

Village Spawn Point (Forge)
Serilum
villagespawnpoint_1.16.5-1.8.jar

Villagers Respawn
MacTso
VillagersRespawn-1.16.5-1.36.0.4.jar

Waystones
BlayTheNinth
Waystones_1.16.5-7.6.4.jar

Wildfire's Female Gender Mod (Forge)
WildfireRomeo
[Forge] Wildfire Female Gender Mod-2.8.jar

Witchery: Rewitched
hero3112
witchery_rewitched-0.3.0.jar

Wyrmroost
Wyrmroost
Wyrmroost-1.16.3-1.2.11.jar

**Comment by saintfather13** [comment]
Hey, i had the same issue as you, our mods are pretty similar, so i found out, that mod we both use is Growthcraft Community Edition, which is causing the issue

**Comment by saintfather13** [comment]
Just delete it from your modpack, and everything should be fine

**Comment by DEX47** [comment]
I was able to confirm removing Growthcraft Community Edition was the cure. Did anyone open a ticket with them?

**Comment by Alatyami** [comment]
This has been fixed and will be in the next alpha release of Growthcraft. This was not an issue with JEI.
