### ISSUE TITLE
How do I prevent JEI from doing this please?

### ISSUE THREAD

**Issue by SirTwsted** [mezz/JustEnoughItems#2566]
Hi,  I am trying to find a solution to this problem I am having with JEI in minecraft v1.16.5  and JEI v7.7.1.136
Using Forge Edition v36.2.9 of modded minecraft game build.

![2021-11-16_03 35 59](https://user-images.githubusercontent.com/15247713/141953156-562b418a-4255-4209-94c3-57bfcbe5db1c.png)

thanks

**Comment by Ommina** [comment]
Prevent JEI from doing... what, exactly?

Perhaps there is some salient feature of the screenshot that evades me, but I'm really at a loss over what it is to which you are trying to draw our attention.

**Comment by SirTwsted** [comment]
JEI is too slim and pushed over to the right side.....  Last time I remember it was never like that.
Was this done purposefully ?  🤷‍♂️

**Comment by Ommina** [comment]
Ah!  There is a config option for the number of columns to display, defaulting to nine.  Check maxColumns, under [advanced] in jei-client.toml

I believe it was done to reduce the number of items being rendered at any given time, as having a significant number of items being displayed would start eating into the frame rate.  You can increase it to suit your own needs and hardware.

**Comment by SirTwsted** [comment]
Works.!!  Thanks  😎👍

![2021-11-16_05 37 51](https://user-images.githubusercontent.com/15247713/141970664-d614f41f-34f1-432f-aa26-ba41a26a7338.png)
