### ISSUE TITLE
1.12.2 JEI crash on load.

### ISSUE THREAD

**Issue by Pantheris2019** [mezz/JustEnoughItems#2567]
Friend getting JEI exception net.minecraftforge.fml.common.LoaderExceptionModCrash from trying to load JEI as a part of an FTB revelations modpack.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
