### ISSUE TITLE
My jei just wont load up in minecraft

### ISSUE THREAD

**Issue by Kokadoe** [mezz/JustEnoughItems#2568]
So when I have Jei in my mods folder, and then load up minecraft, it starts loading then just sits there like frozen like but its not and then eventually closes calling it a crash, not sure what could be the problem, I have the latest forge for 1.16.5 and I have the latest mod for 1.16.5 for Jei

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by Kokadoe** [comment]
tbh, I don't have the slightest clue on how to do what your asking

**Comment by mezz** [comment]
Next to your mods folder should be a logs folder, and in there is a file called `latest.log`
Copy the contents of that file, and paste them into the large box here: https://gist.github.com/
Then click the green button for "create public gist",
then copy the url and paste it here.

**Comment by Kokadoe** [comment]
https://gist.github.com/Kokadoe/e4b0f461ee284d66e37b54b8b5ae7ca7
Im assuming this is the url/log your looking for

**Comment by mezz** [comment]
Thanks.
From the log:
`Failed loading config file jei-client.toml of type CLIENT for modid jei`

It looks like there's something wrong with the config file. 
Please try deleting the JEI config files (including `jei-client.toml`) and then try launching the game again.

**Comment by Kokadoe** [comment]
Thanks so much for helping me, but one last question isnt the menu type thing suppose to be bigger? 
![image](https://user-images.githubusercontent.com/94571135/142518716-d3f3ebe7-de72-49e9-ab63-5a4f95e6e492.png)

**Comment by mezz** [comment]
You're welcome!
You can change the number of columns to a larger number in the config, by default it's 9 columns because rendering too many items can lower your performance.
