### ISSUE TITLE
[1.16.5] Color ModName?

### ISSUE THREAD

**Issue by Faiz8ship** [mezz/JustEnoughItems#2570]
Thank you for reporting!

For issues:
Mod jei-1.16.5-7.7.1.137
Mod ftb-library-forge-1605.3.4-build.87
Mod configured-1.3.2-1.16.5 Fix (color modname)

![Screenshot_16](https://user-images.githubusercontent.com/76649163/142845806-a7145f5f-9cfb-4340-be8a-fd4bf0711015.png)

**Comment by mezz** [comment]
Thanks for the report!
I think multiple mods are trying to add the mod name to the tooltip. 
When JEI detects that another mod is already adding the mod name, it does not add it again or it will try to copy the formatting of the other mod.
In this case you will need to find which other mod adds the tooltip (maybe ModNameTooltip) and edit the config there.

**Comment by Faiz8ship** [comment]
Sorry add mod ModNameTooltip

add dark_pink + pink?

Thanks you! ❤
