### ISSUE TITLE
Can't find ,,hide items" option 1.16.5

### ISSUE THREAD

**Issue by I3estOFF** [mezz/JustEnoughItems#2572]
Can't find ,,hide items" option 1.16.5 is it available?
how can i delete item?

**Comment by mezz** [comment]
Thanks for the report!
This is currently missing because there was no in-game config when I was porting to 1.16.
Now that the in-game config works, we should add this feature to the config again.

**Comment by mezz** [comment]
This is fixed in the latest version, you can bind a hotkey to toggle the "hide items" mode on and off in the Minecraft controls.
