### ISSUE TITLE
can we get justenoughitem 1.7.10?

### ISSUE THREAD

**Issue by alert170** [mezz/JustEnoughItems#2573]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Ommina** [comment]
It strikes me that the needs of 1.7.10 are already well met by NEI: you can [find it here](https://www.curseforge.com/minecraft/mc-mods/notenoughitems/files).
