### ISSUE TITLE
Issue with JEI 7.7.1.137.

### ISSUE THREAD

**Issue by axusar** [mezz/JustEnoughItems#2576]
So I was making a modded server with the "Create: Above and Beyond" modpack, and turns out somehow JEI isn't working as expected.
Like when I try to search for items in one mod only a few items show up and like 90% of the items are just gone, but I can get the items from the creative inventory, but I can't see their recipe from there either, making it impossible to use some mods.
And the /give command does have the option to give those items but doesn't work. 
I have no idea what to do and I'm definitely not much of an expert at stuff like this.

![Create_ Above and Beyond 26_11_2021 13 59 33](https://user-images.githubusercontent.com/95082624/143577890-9ba44d5d-95bd-49ff-930c-eab99168a004.png)

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by axusar** [comment]
> Thanks for the report! I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

Sorry, how do I find that?

**Comment by mezz** [comment]
Here's a guide for finding your logs on various Minecraft launchers:
https://help.ggservers.com/en-us/article/where-to-find-client-side-logs-7upje9/
