### ISSUE TITLE
jei-1.16.5-7.7.1.137 loading crash

### ISSUE THREAD

**Issue by subochev-k-n** [mezz/JustEnoughItems#2577]
Hi, I have a problem with JEI loading
[crash-2021-11-27_13.15.17-fml.txt](https://github.com/mezz/JustEnoughItems/files/7611570/crash-2021-11-27_13.15.17-fml.txt)
[latest.log](https://github.com/mezz/JustEnoughItems/files/7611571/latest.log)

**Comment by Ommina** [comment]
> 	Mod File: jei-1.16.5-7.7.1.137.jar
>	Failure message: fml.modloading.dupedmod

Are you sure you have only one instance of JEI in the mod folder?

This error message suggests that it (Forge) is trying to load JEI multiple times.

**Comment by subochev-k-n** [comment]
Thanks, you're right.

It was conflicted with roughlyenoughitems
