### ISSUE TITLE
[1.16.5][Suggestion] JobSite as input for Villager trader

### ISSUE THREAD

**Issue by drakray** [mezz/JustEnoughItems#2578]
As the title says: being able to see the PointOfInterestType block with the villager in the Villager Trades tab(as a "Use") would be very nice, I think.
It would be mainly useful for modded villagers, where documentation is lacking(why list stuff, when there's JEI lol XD )

**Comment by mezz** [comment]
Thanks for the suggestion!
This type of information is normally provided by JER (JustEnoughResources) which is an addon for JEI.
Please request features for JER here: https://github.com/way2muchnoise/JustEnoughResources
