### ISSUE TITLE
How to change default keybindings `R, U` ?

### ISSUE THREAD

**Issue by XyLyXyRR** [mezz/JustEnoughItems#2580]
```
Show Recipes: Hover over item + R
Show Uses: Hover over item + U
```

How I change these keybindings? I looked up config and issues, and find nothing.

**Comment by mezz** [comment]
Thanks for the question!
You can configure these in the Minecraft Controls menu, where you can set keybindings for all kinds of things.

**Comment by XyLyXyRR** [comment]
Oh my god. How I didn't find it? Sorry for bothering you for this small things.
