### ISSUE TITLE
Suggestion: Client side filtering

### ISSUE THREAD

**Issue by reburke** [mezz/JustEnoughItems#2583]
One thing that would make gaming easier is being able to filter what is shown by JEI client side so a player don't have to edit the modpack or lean kubejs, crafttweeker, etc

Examples:
remove items from showing in the list that spam the listing of items  (hide facades and chisel bits)

when looking and uses and recipes being able to filter out results by mod of hide tabs  (not showing mine colonies crafting when I have not start a colony yet)

Maybe even advances option (hiding create crafting that can be done in a normal crafting table)

**Comment by mezz** [comment]
Thanks for the suggestion!
JEI actually has a feature for this type of advanced hiding, but it hasn't been properly exposed in the config file in the latest versions.
Please follow this issue for any updates: https://github.com/mezz/JustEnoughItems/issues/2572
