### ISSUE TITLE
every time i add this to my server it makes the ping packet not work so no one can join

### ISSUE THREAD

**Issue by Mrh251291** [mezz/JustEnoughItems#2584]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Can you provide the server log that shows how the ping packet is being broken?
