### ISSUE TITLE
My jei just wont load up in minecraft 

### ISSUE THREAD

**Issue by PakoPakete** [mezz/JustEnoughItems#2586]
I try to connect to my minecraft server, but when i open the minecraft, appears an error, that saids:
![image](https://user-images.githubusercontent.com/95642732/144884384-fe7315fd-83d5-4b99-811b-df8105c9a30a.png)
Any help will be helpfull, thanx.

**Comment by Ommina** [comment]
Please provide a pastebin link to the crash report mentioned in the screenshot and we can take a look.
