### ISSUE TITLE
JEI Interface overlaps with potion status effects

### ISSUE THREAD

**Issue by PlazmaKG** [mezz/JustEnoughItems#2588]
In Minecraft 1.18, Mojang moved the potion status effects to the right side of the inventory, instead of leaving them on the left side like they are in 1.17.1 and below.

My suggestion here is to possibly move the potion status effect information back to the left side of the inventory, like they were before, so they're not being overlapped by JEI.
![image](https://user-images.githubusercontent.com/38696130/145141653-e142d89e-1ea8-4c22-b56e-75037ec75fe9.png)
![image](https://user-images.githubusercontent.com/38696130/145141732-42f92882-1d14-4222-b72b-8245da1c4455.png)

**Comment by mezz** [comment]
Thanks for the report!
For now I'll just move JEI items out of the way of the potion status effects. 
Forge might add an event later to change the way the potion status effects are displayed, but I will not mess with that now.
