### ISSUE TITLE
No Configuration

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2589]
Hello, so version 1.16.5 I can't use the configuration button. It keeps saying 'Install the Configured'  (what I can't find) mod to access the in-game config. jei-1.16.5-7.7.1.137.jar is installed

**Comment by Ommina** [comment]
[Configured](https://www.curseforge.com/minecraft/mc-mods/configured).

Very first hit for "configured mod" on DuckDuckGo, Bing, and Google.

**Comment by mezz** [comment]
Thanks for the report!
You can also go to Configured by clicking the text in chat. 
Sorry it's confusing, I wish Forge's built-in version of this was working.
