### ISSUE TITLE
[1.18] Mouse Buttons Do Not Work for Usage/Recipe in Central GUI

### ISSUE THREAD

**Issue by Boomflex** [mezz/JustEnoughItems#2590]
Hi Mezz, hope you're good mate?

Forge: 38.0.16
JEI: jei-1.18-9.0.0.40.jar

Same issue as an older 1.16.5 issue: https://github.com/mezz/JustEnoughItems/issues/2563

Looks like it reared it's ugly head again!

**Comment by moon-st0ne** [comment]
to add to this, there seems to be a bug where right-click will always show recipe if bound, and will not give one item even if enabled. left click behaves normally.

**Comment by mezz** [comment]
Thanks for the report!
Both of these issues are fixed in the next version for 1.18.1, which should be released shortly.

**Comment by Fynxes** [comment]
is it possible to fix the same issue in Version 1.17.1?

**Comment by mezz** [comment]
Sorry I thought I had fixed this in 1.17 as well. The next version of JEI for 1.17 has this fix now.
