### ISSUE TITLE
JEI isnt showing the images of items

### ISSUE THREAD

**Issue by HazukiSuran** [mezz/JustEnoughItems#2591]
![image](https://user-images.githubusercontent.com/95886313/145478969-eee9ca04-fdba-4005-ae6d-ce2d1189cb2e.png)

for some reason the images of items arent showing up but the items are still there. I'm able to see them when I search for them but when its just normal, some items just dont want to show up

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by HazukiSuran** [comment]
I actually ended up finding out the problem last night before bed. It was Optifine causing the problem. JEI works perfectly now that I removed it from my game.

**Comment by mezz** [comment]
Ah ok thanks. Can you report it to optifine and link back to here? I’m sure they’ll fix it if they know about it

**Comment by HazukiSuran** [comment]
Sure I can do that
