### ISSUE TITLE
JEI crashes on <enter> in waypoint screen.

### ISSUE THREAD

**Issue by pi314ever** [mezz/JustEnoughItems#2592]
Crashes when in waypoint screen if I press <enter>. Bug report originally from Xaero's minimap mod, redirected here. 
Link: https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/577

[crash-2021-12-08_00.36.27-client.txt](https://github.com/mezz/JustEnoughItems/files/7689492/crash-2021-12-08_00.36.27-client.txt)

**Comment by Ommina** [comment]
See also #2597

**Comment by mezz** [comment]
Thanks for the report!
I will close this one so there is only one report for this open, please follow the other issue here: #2597
