### ISSUE TITLE
Potion cards shift and overlap with the inventory when viewing a recipe with JEI

### ISSUE THREAD

**Issue by TheDyreBanana** [mezz/JustEnoughItems#2593]
It goes away after reopening the inventory screen. 

mods : mouse tweaks forge 2.16, JEI 9.0.0.40, forge 38.0.17
![image](https://user-images.githubusercontent.com/59154209/145603238-aa3807ac-a26d-40ed-ba65-502386c3f3ca.png)

**Comment by mezz** [comment]
Thanks for the report!
This is actually a bug from Forge, you can follow it here: https://github.com/MinecraftForge/MinecraftForge/issues/8252
