### ISSUE TITLE
JEI 7.7.1.137 not showing in multiplayer

### ISSUE THREAD

**Issue by demar6194** [mezz/JustEnoughItems#2595]
Hello,
I'm looking for help with my 1.16.5 minecraft server. My single player works without trouble. and server only has jei as i have already removed jer, and jei intergration. Ahead of time sorry for so many pastebin links.

Log:
https://pastebin.com/BtCdzHjS
https://pastebin.com/qzAkiNpE
https://pastebin.com/auJEdq4B

**Comment by mezz** [comment]
Thanks for the report!
I am guessing that some mod is causing an error during one of the syncing events when you connect to a Server.
JEI uses these events to know when to start, and I do not see any logs from JEI starting.
Please try narrowing down your mod list to see if there is another mod causing this issue.
