### ISSUE TITLE
JEI does not work with the new forge 1.12.2

### ISSUE THREAD

**Issue by philip5203** [mezz/JustEnoughItems#2596]
Are there plans to release an updated version for 1.12 after the security vulnerability was found and forge had to update?

**Comment by Ommina** [comment]
I would expect JEI to work with the updated Forge release as is.  There were no Forge changes beyond shipping the new log4j library, and JEI has never, to my knowledge, had a maximum forge version.

Can you expand on "does not work"?  Does it crash?  (Post the crash report)  Freeze?  Other?  (Post the debug.log).
