### ISSUE TITLE
Some Modded Items Textures are missing in The recipe window (1.18.1)

### ISSUE THREAD

**Issue by Shadow212121** [mezz/JustEnoughItems#2600]
![2021-12-12_17 46 39](https://user-images.githubusercontent.com/79116680/145734591-261492d7-4bc7-4f9d-9933-0022086858ca.png)
![2021-12-12_17 45 45](https://user-images.githubusercontent.com/79116680/145734601-eb193933-9981-4c5b-8752-9f5d1923eb8e.png)
Only mods I had issues with were Gobber and Supplimentaries

**Comment by mezz** [comment]
Thanks for the report!
Please report this to the individual mods involved and link back here. I am not sure why they do not display here.
