### ISSUE TITLE
error loading  jei-1.18.1-9.1.0.41.jar (1.18) 

### ISSUE THREAD

**Issue by dabult1223** [mezz/JustEnoughItems#2601]
There is an error when I try to open Minecraft 1.18, which gives me this error message "jar needs language provider javafml:39 or above to load" What does this mean?

**Comment by mezz** [comment]
Thanks for the report!
Most likely you need the latest version of Forge for 1.18.1, maybe you have Forge for 1.18?
If that's not it, I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
