### ISSUE TITLE
[1.18.1] Items not rendering in jei menu

### ISSUE THREAD

**Issue by Epicjii** [mezz/JustEnoughItems#2602]
Whenever I open my inventory the most items do not appear
![2021-12-13_01 56 02](https://user-images.githubusercontent.com/66448504/145740890-854ff2e8-9567-4bf7-83ed-3179ae7997b5.png)
.

Only JEI and Optifine installed.

**Comment by mezz** [comment]
Thanks for the report!
What does it look like without Optifine?

**Comment by Epicjii** [comment]
![image_2021-12-12_222124](https://user-images.githubusercontent.com/66448504/145747337-9be5382b-264e-4916-801d-10dbe62c3b9f.png)
It looks normal. Is there settings in the optifine menu I need to change?

**Comment by mezz** [comment]
Optifine does a lot of weird stuff with rendering, so every time there is an incompatibility with JEI they usually did something unusual and release a fix for it.
Please report this issue to them and link back here to make sure they're aware of the issue.

**Comment by Epicjii** [comment]
Alright. Will do.
