### ISSUE TITLE
Buffs Appear on wrong side (1.18.1)

### ISSUE THREAD

**Issue by Shadow212121** [mezz/JustEnoughItems#2608]
![2021-12-13_18 16 08](https://user-images.githubusercontent.com/79116680/145910561-186af48c-a0e2-4df3-bc56-368d698f8254.png)
Buff is from Alex's Mobs

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2588
