### ISSUE TITLE
1.18 - Recipe not showing when an item is clicked in a displayed recipe

### ISSUE THREAD

**Issue by Snaitf** [mezz/JustEnoughItems#2609]
What I mean is, if you click an item in the JEI sidebar, the recipe will appear like normal.  But, if you then click an item in that recipe, the recipe to make that item won't show, like it did in 1.16.

Pressing 'R' does work however, so it's a very minor thing, just thought i would bring it to your attention.

**Comment by mezz** [comment]
Thanks for the report!
I think this was reported before and should be fixed in the latest versions of JEI.
If you are on the latest version, I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
