### ISSUE TITLE
[1.18] Curious update makes JEI Overlay go missing

### ISSUE THREAD

**Issue by ffuentesm** [mezz/JustEnoughItems#2613]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

The new curious update curios-forge-1.18.1-5.0.3.0.jar, and curious Elitra curiouselytra-forge-1.18.1-5.0.0.0.jar, made the entire JEI menu go missing. 

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Klouver-github** [comment]
I am having the same Issue

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Curios and link them back here so we can find out what's happening here.

**Comment by StrangeThistle** [comment]
Thank you! I can live without curious elytra. Having to figure out how I broke JEI was going to take days and drive me crazy in the process.
