### ISSUE TITLE
JEI Overlay not appearing in creative

### ISSUE THREAD

**Issue by lamoyrl90** [mezz/JustEnoughItems#2614]
MC 1.18.1
Forge 39.0.0
JEI 9.1.0.46

The overlay in the inventory screen shows up in survival mode, but disappears in creative. I'll fiddle around with the handful of mods I have to see if I can resolve it, and if so I'll update you on where the conflict is.

**Comment by Shadow212121** [comment]
Did you try pressing O? Happened to me too

**Comment by lamoyrl90** [comment]
Yep that was the issue. User error as always >.>
