### ISSUE TITLE
Crash on 1.17.1-8.3.0.45

### ISSUE THREAD

**Issue by PellucidDice** [mezz/JustEnoughItems#2615]
https://gist.github.com/PellucidDice/98f2bfc710324d21cc6fced5355a4087

Game crashes when clicking with both left and right mouse buttons fast on the item list UI located on the right.

**Comment by mezz** [comment]
Thanks for the report!

I fixed this in JEI for 1.18 in #2606, I'll apply this fix to 1.17 now as well.
