### ISSUE TITLE
1.16.5 :After hiding an item, i can't unhide them again because they don't show up

### ISSUE THREAD

**Issue by chrisgates301** [mezz/JustEnoughItems#2616]
I already hid a bunch of items using the hide mode (its not in the config, but in the controls you can toogle it on and off with a keybind), but now i have no way of unhiding them, they dont show up even when i toggle the hide/edit mode.

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next version of JEI, which will be released shortly.
