### ISSUE TITLE
Invisible JEI items 1.18.1

### ISSUE THREAD

**Issue by zachsai** [mezz/JustEnoughItems#2617]
Thank you for reporting!

For issues:
![image](https://user-images.githubusercontent.com/63996164/147028886-cc162a13-054f-4218-ae62-f67661cd2435.png)
Items are not showing properly with optifine for some weird reason. This problem is not happening with Roughly Enough Items, so I do not think it is a Optfine issue? Please help :D

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by unspunreality** [comment]
It is optifine, but its weird cause yesterday I had no issue with JEI. Today nothing new except I added ForgeEndertech/AdFinders/AdHooks/AdLods and now even if I remove them I get this same issue, only resolved if I remove optifine. Top row appears if searching for itemsnd hidden items appear if directly searched for. Still odd.

**Comment by zachsai** [comment]
Yeah, I assumed it was jei since rei does not have this problem.
I'll look into writing to optifine to find a solution since id rather have jei in my modpack for curse over rei.
Also, while I have this exchange going, I assume you are a dev for jer, I cannot seem to find info on how to add json for custom ores, since the command isnt yet implemented. How could I get help for that?

**Comment by zachsai** [comment]
So apparently, my resourcepack with emissive textures is the cause of this, I dont know why though

**Comment by unspunreality** [comment]
> So apparently, my resourcepack with emissive textures is the cause of this, I dont know why though

First. Not a mod. Just commenting to not open my own thread. Second... resource pack issue? Hmm... I did change a resource pack. Which could be odd as hell but interesting if it did cause the issue.

**Comment by iiKraze** [comment]
im having the same issue, but after removing the emissive ores pack it seems to have fixed this issue, so for the time being im using REI as i need my emissive ores :)

**Comment by iiKraze** [comment]
ok so after a few hours of testing it turns out that it is impossible to use JEI and Emissive textures together, Mezz needs to add Emissive support for this to work flawlessly.

**Comment by Ommina** [comment]
I was recently reminded (and rightly so!) in #2624 that emissive texture support is something that is added by Optifine, and is not part of vanilla MC or even Forge.  Has the issue been reported there?

**Comment by mezz** [comment]
Thanks for the report!
I added a config option to disable JEI's optimized item rendering, and JEI should detect Optifine and disable any rendering optimizations if Optifine is found.
Please try out the latest version of JEI for 1.18 and see if it fixes the issue. You should find this in the logs: 
> Optifine is detected. JEI's fast item rendering is being disabled to prevent rendering issues.
