### ISSUE TITLE
Show fluid recipe when querying filled containers

### ISSUE THREAD

**Issue by BluSunrize** [mezz/JustEnoughItems#2618]
Weird to be filing a suggestion/request as a dev...

Anyhow, I've noticed that when I have a bucket of fluid and I check the recipe, it only shows me a recipe that crafts that very bucket.
It'd be infinitely more helpful, if it also showed me recipes relating to the fluid inside it.

Specific userstory:
I want to make the "Advanced Lubricration System" from Immersive Engineering. It requires some iron and two buckets of plantoil. Now I wanna check how to make those, but no recipe comes up, because there is no recipe to craft that specific bucket. Instead I now have to search for "plantoil" in JEI and specifically check the recipe for the fluid(-block).
It'd be super helpful if it would just navigate me to the fluid recipe when I query the bucket!

**Comment by mezz** [comment]
Thanks for the report Blu!

Currently all fluids are shown in JEI as their own ingredients, in addition to the buckets. There is no way to look up multiple recipes at once, so I would have to translate all bucket lookups to fluid lookups, and then unfortunately people couldn't look up how to craft the fluid buckets when there is a recipe for them.

Usually there's some recipe for `fluid + bucket -> fluid bucket`, like from Forestry's bottler. Could you add recipes for Immersive Engineering's Bottling Machine? It adds an extra lookup step but avoids any ambiguity.

As you probably know from implementing IE's assembler, wildcard fluid crafting ingredients don't have great support in the game, and so it's not great in JEI either.

**Comment by BluSunrize** [comment]
> As you probably know from implementing IE's assembler, wildcard fluid crafting ingredients don't have great support in the game, and so it's not great in JEI either.

Yeah no, I know *exactly* what that is like, hahah.

Our bottling machine does support "recipes", but the feature of filling buckets (or other fluid containers) is done natively rather than with recipes. That said, I could probably add some "fake" recipe for JEI...?

**Comment by mezz** [comment]
Yeah check out Forestry’s JEI handling for the bottler (even though it’s on an older version), I just generate a bunch of fake recipes for JEI to understand.
