### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by PLWRush** [mezz/JustEnoughItems#262]
Hi, I've been putting together a mod pack for me and a couple friends to play, and I am getting a crash on world load from JEI, I have tried multiple versions(The 4 most recent including betas I believe and none seem to work). The pack will launch and load into world fine without JEI installed.

https://gist.github.com/PLWRush/15c277f19ffcd0d90fa5acfa5868df84

**Comment by mezz** [comment]
Thanks for the report!
This crash is coming from mribby's OldPvp. Can you remove that mod and see if it works?

**Comment by PLWRush** [comment]
That fixed it! Thank you. I guess I don't quite know how to read crash logs so I thought it was JEI, Sorry about that. Thanks for the help though!

**Comment by mezz** [comment]
No problem! Make sure to report the issue to them. Forge changed some event methods, so they will need to update in order to support the latest Forge.
