### ISSUE TITLE
Text wrapping in TooltipRenderer resets style.

### ISSUE THREAD

**Issue by The7seVen** [mezz/JustEnoughItems#2622]
In TooltipRenderer#drawHoveringText, when wrapping text lines, style of the component is set to Style.EMPTY, which is not nice.

**Comment by mezz** [comment]
Thanks for the report!
This code is based on the vanilla text wrapping code and seems to be working fine in JEI for 1.18, can you provide some screenshots?
![2021-12-25_11 33 39](https://user-images.githubusercontent.com/916092/147383166-585a3d5d-5716-4695-8654-766d01ab3cec.png)

**Comment by The7seVen** [comment]
I have no clue what's happening, my nbt-based names are generated in getName()
Note: Jei - 1.17.1-8.3.0.45 , rune labels are images added via gatherComponentsEvent
![rune_names_bug](https://user-images.githubusercontent.com/42298229/147386010-59c529af-0802-4548-83f9-11541412e68c.png)

**Comment by The7seVen** [comment]
Also I just noticed this, and that's after disabling my code:
![vanilla_name_bug](https://user-images.githubusercontent.com/42298229/147386437-e7268be8-682d-4a16-90c5-a8ed96e8bc3e.png)

**Comment by The7seVen** [comment]
OK. This is happening only in dev environment, so I guess it's all fine? Weird behavior.

**Comment by mezz** [comment]
Hmm weird. Maybe this was something broken in older versions of JEI and I somehow fixed it recently?
