### ISSUE TITLE
JEI Launch error at common_setup

### ISSUE THREAD

**Issue by affogatto** [mezz/JustEnoughItems#2623]
Hi, could someone please help me figure this issue out?
Every time I try to start Minecraft with JEI I get the error:
```
Just Enough Resources (jeresources) encountered an error during the common_setup event phase
java.lang.NoSuchFieldError: TALL_GRASS
```
Here is both the crash log and the latest.log
[crash-2021-12-25_11.53.48-fml.txt](https://github.com/mezz/JustEnoughItems/files/7776137/crash-2021-12-25_11.53.48-fml.txt)
[latest.log](https://github.com/mezz/JustEnoughItems/files/7776138/latest.log)

Thank you in advance.

**Comment by Ommina** [comment]
The error message is from Just Enough _Resources_, not Just Enough _Items_.

You can find the JER issue page here: https://github.com/way2muchnoise/JustEnoughResources/issues

I also see Optifine lurking in the stack trace, but I'm not certain how mixins affect such crashes (if they do at all), so I have to defer to the more knowledgeable way2muchnoise on that subject.
