### ISSUE TITLE
Emissive Textures with resourcepack causes jei items to be invisible (1.18.1)

### ISSUE THREAD

**Issue by zachsai** [mezz/JustEnoughItems#2624]
Here is a video
https://streamable.com/tno0tx

This issue does not happen with roughly enough items, I will post about it to optifine also, but I think this is a jei issue since it doesnt happen with rei. 
Hopefully a solution can be found
This is the resourcepack making the emissive textures
[bordered-ores-v2.zip](https://github.com/mezz/JustEnoughItems/files/7776267/bordered-ores-v2.zip)
:

**Comment by zachsai** [comment]
Tested with a new instance, jei only and optifine only + the resourcepack. The problem still occurs.

**Comment by Ommina** [comment]
And without Optifine?

**Comment by zachsai** [comment]
It has to do with emissive textures. Something with how jei renders things is messed up when having emissive textures in 1.18.1

**Comment by Ommina** [comment]
And without Optifine?

**Comment by zachsai** [comment]
Emissive textures is only available with optifine, so without optifine the issue is not present, that goes without saying
