### ISSUE TITLE
Client crash to menu when using [+] to transfer recipe to crafting station while connected to a colossal chest

### ISSUE THREAD

**Issue by ndrew420** [mezz/JustEnoughItems#2625]
The error I get:
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes
[log.log](https://github.com/mezz/JustEnoughItems/files/7776852/log.log)

I am playing on stacia expert.
Connected a 6x6x6 colossal obsidian chest to a crafting station. When opening the crafting station it loads the colossal chest inventory on the left as it's supposed to do.
I search for a recipe on JEI, click the [+] and it crashes.

Worth noting that with a 7x7x7 the crafting station does not load the chest inventory, instead it crashes with a different error.

Tried looking into lowering maxSlotsPerPacket value as described [here](https://github.com/CyclopsMC/ColossalChests/issues/40) to 1000 or increasing it to 100000. Same result with different numbers.

Tried in single player and it works fine.

It seems this could be like this issue [here](https://github.com/CyclopsMC/ColossalChests/issues/65).

Thanks

**Comment by mezz** [comment]
Thanks for the report!
The log you posted doesn't include a `DecoderException` at all, maybe you uploaded the wrong one?
I can take a look at how to support this (if possible) once I have the full stack trace.
