### ISSUE TITLE
Stall on Joining World - Building ingredient filter...

### ISSUE THREAD

**Issue by itsdinkd** [mezz/JustEnoughItems#2626]
Using JEI on my modpack for 1.18.1, with forge loader 39.0.8, All players joining a dedicated server get stuck on "Joining World"... for about 5-10 minutes. If they click or do anything during that time, the game will go unresponsive. In the logs, the last thing that its doing is

```
Building ingredient filter...
```

I have tried the second most recent version of JEI, with no dece, same issue. So then I tried using Roughly Enough Items instead of JEI, and the players were able to join at normal times/speeds. 

Latest Log- https://pastebin.com/DkhV33db

**Comment by itsdinkd** [comment]
@mezz was this addressed by chance in latest update? would love to switch my modpack back to JEI

**Comment by mezz** [comment]
This may be related to another bug that was fixed (https://github.com/mezz/JustEnoughItems/issues/2582), please try with the latest version and see how it goes.

**Comment by itsdinkd** [comment]
okay will do

**Comment by itsdinkd** [comment]
So I finally had the time to test JEI with it's latest version. its not as long but its still taking quite some time, 1 minute and 30 seconds to be exact. but REI for some reason only takes 30-40 seconds. 




 in this log, it shows from start of connecting to server up to connected. https://gist.github.com/itsdinkd/625895d6c4edbed01f507101d65d9ee5

**Comment by itsdinkd** [comment]
Actually after comparing both true times via logs from connecting to server, to connected, REI took 1 minute and 13 seconds, JEI took 1 minute and 33 seconds.

**Comment by mezz** [comment]
JEI tracks the time of various loading stages, you can see the total time at the end of the log: `Starting JEI took 25.36 s`.
That includes all the plugins, checks, building steps, etc.

Digging in more detail is possible, but the Forge logs are configured poorly right now so you can't easily find all the logs coming from JEI.

As long as the stall is fixed I think this issue can be closed. Please open a new issue if you're concerned about the startup performance.

**Comment by Ommina** [comment]
I'm not at all certain, but it appears to me that https://github.com/MinecraftForge/MinecraftForge/issues/8359 relates to this as well.

**Comment by mezz** [comment]
Definitely possible! Looks like it's a good idea to update to the latest version of Forge to avoid that issue.

**Comment by itsdinkd** [comment]
Getting tons of reports that its happening ( I officially switched the pack back over to JEI ) and whats odd is its only happening to players who join a server for the first time. 
![image](https://user-images.githubusercontent.com/35115304/149673306-1235dbcc-b47f-4eba-9850-4ac6a9076da3.png)
![image](https://user-images.githubusercontent.com/35115304/149673311-ef323dc6-72fc-465b-af11-3d2ed6dd4493.png)
![image](https://user-images.githubusercontent.com/35115304/149673312-4ed328b0-ba51-47de-b72d-a969632d2c7a.png)
![image](https://user-images.githubusercontent.com/35115304/149673318-ba2d3c28-83db-4cdf-ab61-61ff34a7c38b.png)


My modpack is https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-3 (if you'd like to test) 

but it only happens when people join servers for the first time. when you are joining after you've been on it before (you get my experience of the whole 1:30 second load)

**Comment by itsdinkd** [comment]
I also am using modloader 0.22 on the modpack, and in the server pack downloader for everyone to use so the .20 update did not do anything to fix this issue with JEI and first time join

**Comment by mezz** [comment]
Thanks for the pack link, I'll try this out with a java profiler and try to see what's going on.

**Comment by mezz** [comment]
I was able to join the Zion server without any issues on my first try, is this still a problem for people?

**Comment by itsdinkd** [comment]
I switched back to REI after the .20 modloader update not fixing the issue
so I'm not sure. You used JEI and it took a normal amount of time??

**Comment by itsdinkd** [comment]
Ah you probably joined with the regular download from the pack. You'll have
to install JEI and since the server is using REI I don't think you'd be
able to connect. A easy way to test is by downloading the server pack and
running a local instance with jei in it instead of rei. I make it easy to
launch local servers as my server packs include server start.

**Comment by mezz** [comment]
Ah ok thanks, I thought I must be missing something obvious :D

**Comment by mezz** [comment]
I tried running this locally, with a brand-new server using the link on curseforge curseforge.com/minecraft/modpacks/another-quality-modpack-3 

Created a new modpack instance on curseforge to have a fresh start.
I added the latest JEI, then disabled REI and RoughlyEnoughItems-jei-internals-workaround on both the client and server.

On first join, it took quite a long time to join but it did complete. I ran this with a java profiler attached in order to see what JEI was doing, and didn't find much out of the ordinary.

75 seconds was spent on loading JEI
`ClientLifecycleHandler.java:107 mezz.jei.startup.ClientLifecycleHandler.setupJEI() 75197`
 * 39 seconds of that was from JER loading `CommonProxy.java:14 jeresources.compatibility.Compatibility.init() 39068`, maybe that could be improved.
 * 22 seconds was from JEI getting tooltip strings, which is about what's expected for a pack this large
 * the remaining 14 seconds was spent by other plugins and by JEI doing all kinds of other stuff like finding all the vanilla items.

**Comment by itsdinkd** [comment]
Hmm do you think it's possible it didn't take as long as reports because
the server was ran locally? Only thing I can think of maybe why it didn't
take as long.

If you don't mind running one more test, I can start up my staging server
with jei in it and share the ip?

**Comment by mezz** [comment]
Sure I'll give it a shot. You can DM me the IP on Discord: `mezz#9999`

**Comment by itsdinkd** [comment]
Just messaged you, sorry for delay. Adding JEI into my latest update, and on dedicated server for modpack. 

Also with the latest version and new logging, I think these are the cause for the delay, idk. not too sure.
Log; https://gist.github.com/itsdinkd/f27076a14949db12d03428e93b508e77

Using the latest JEI that came out yesterday for 1.18.1

**Comment by mezz** [comment]
Thanks for the log! I've been working on making stuff like this easier to diagnose, and the new log should help a lot.

`Starting JEI took 22.19 s`
that's not very fast, but it's not a "Stall on Joining World for 5-10 minutes" like reported in the issue.
Have things really improved?

If someone is still stalling for a long time, I think their log with the latest JEI will really help us figure out what's going on here.

**Comment by mezz** [comment]
I have implemented some memory performance improvements here: <https://github.com/mezz/JustEnoughItems/pull/2734>
This is available in JEI `9.4.1.109`, can you try it out?
