### ISSUE TITLE
Crafting table lookup should show recipes using the crafting table first

### ISSUE THREAD

**Issue by doritobob269** [mezz/JustEnoughItems#263]
With the new JEI update, there is an issue when i look up the uses for a crafting table. This means i look up a use for the crafting table when it is used as a crafting item. JEI shows not only recipes involving the crafting table, but all the crafting recipes registered as the crafting table lookup shows the crafting manager recipes. A possible suggestion i have is holding control and clicking the item in JEI will show the crafting manager recipes of that block.

**Comment by Prospector** [comment]
This is intentional. Recipes crafted in a crafting table are uses for the crafting table, no?

**Comment by doritobob269** [comment]
Yes, but when I want to look up specific recipes involving a crafting table only, I get every crafting recipe. For instance if I wanted to look up the tinkers recipe for the crafting station, I would click "U" on the vanilla crafting table in JEI, but instead of getting just the crafting station recipe, I would also get all recipes registered as this is a normal JEI functionality

**Comment by KnightMiner** [comment]
Maybe put the recipes containing a crafting table first when viewing via the crafting table?

**Comment by Prospector** [comment]
Oh, I see. That is a bit of an issue

**Comment by mezz** [comment]
I think it makes sense to keep showing all the recipes, but show the most relevant recipes first.

**Comment by Prospector** [comment]
Does it do that now, or are you gonna do that?

**Comment by mezz** [comment]
Should work properly now, let me know if you find anything strange!

![2016-04-30_17 43 22](https://cloud.githubusercontent.com/assets/916092/14939456/9b636d0a-0efc-11e6-984e-f6a4906772c9.png)

**Comment by VT-14** [comment]
Strange... According to your picture, you can craft a crafting table into a baked potato.

Mostly related: would it be possible to make the order of recipes changeable by the player?  I remember when Blood Magic, Botania, and Forbidden Magic were all installed, the Bloodthorn flower was added (infusing a Red Mystical Flower in a Blood Altar).  Annoyingly, every craftable Botania flower showed this recipe first.  A simple fix would be to show the Blood Altar recipes after all of the Botania crafting.

It would also be nice in general.  Say you have IndustrialCraft2, Thermal Expansion, and EnderIO all installed, but only have EnderIO machines?  Being able to put EnderIO first would be nice.

**Comment by Prospector** [comment]
It was a test recipe.
