### ISSUE TITLE
JEI 1.18 Will not open 

### ISSUE THREAD

**Issue by RNGMSTR** [mezz/JustEnoughItems#2632]
JEI will not open show in my mods tab after launching MC, removed all my mods and only kept in JEI and still doesnt work. I dont know how to post the snapshot of the log thats asked for in the other posts either. I have 1.18.1 curse forge and all of my other mods work just not JEI but im not getting any error codes or anything else its just not in the mods tab even though its in my mods folder.

**Comment by noskincz** [comment]
same issue but on 1.18.2

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
