### ISSUE TITLE
JEI doesn't show "move items" button when using jei through the Simple Storage Network(SSN) mod.

### ISSUE THREAD

**Issue by Adesh-poz** [mezz/JustEnoughItems#2633]
When I browse JEI interface through a normal crafting table, I can click on an item to check its recipe and it shows that I can "move items" as in I can craft them directly (given of course I have the necessary ingredients in my inventory).

But when I try to do the same with Simple Storage Network(SSN) interface, **it doesn't show that "move items"** (AKA that plus button on the lower right of the ingredient recipe). I can still see the recipes but the plus sign doesn't show.

Why?

I have checked the config file of jei and can't seem to find any related setting for that.

I have seen in a modded minecraft video that it should have that functionality. He used the same Simple Storage Network(SSN) mod as me. (It was probably for 1.16.5 tho, so this may actually be a version issue.)

Please help.

Game version: 1.18 
Simple Storage Network(SSN) version: 1.18-1.5.0 
JEI version: 1.18-9.0.0.40

I also have JEED 1.18-1.16 in the mod list. In case this helps. Idk if it can actually cause any issue though.

**Comment by Ommina** [comment]
Such goodies are added by the mod itself, not JEI.  You can find them at https://github.com/Lothrazar/Storage-Network/issues

At quick glance, it looks like they have recipe transfers for 1.18.1 -- there may be something else going on preventing the button's display.

**Comment by mezz** [comment]
Thanks for the report!
Ommina is right, please report this issue to [Lothrazar/Storage-Network/issues](https://github.com/Lothrazar/Storage-Network/issues)
