### ISSUE TITLE
Crash when crafting wood planks

### ISSUE THREAD

**Issue by yay855** [mezz/JustEnoughItems#2637]
I recently created a new modpack using Curseforge, and every time I try to craft wood planks, the game crashes. Crash report is here:

https://gist.github.com/yay855/d39ed7405d479730725f4026c27ea148

**Comment by Ommina** [comment]
See #2636  (Despite the title, it affects more than the Create sandpaper.)

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which will be released shortly.
dcd7d2b
