### ISSUE TITLE
Unknown ingredient class: class net.minecraft.client.gui.Font

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#2638]
When opening any UI with JEI for more than a few seconds, the client (not dedicated server) crashes.

## Versions

* **JEI**: `jei-1.18.1-9.1.2.50`
* **Forge**: 39.0.9

[**Full Mod List**](https://gist.github.com/oitsjustjose/1ade7d1ceaffd08eb3a2268c76383182)

[**Crash Report**](https://gist.github.com/oitsjustjose/3b6a23ff218291324ff7694608b53546)

Let me know if you need any additional info!

**Comment by Ommina** [comment]
See #2636 (Despite the title, it affects more than the Create sandpaper.)

**Comment by oitsjustjose** [comment]
Looks right, ok I'll go ahead and close this bug, marking as duplicate to #2636
