### ISSUE TITLE
Can't start developer Minecraft with JEI as a dependency 

### ISSUE THREAD

**Issue by Flamebom** [mezz/JustEnoughItems#2639]
For some reason JEI is stopping my Minecraft from loading properly when I try to start in the forge dev environment.
I asked on the forge discord and they said it was probably a JEI bug.
Crash Report:
https://gist.github.com/Flamebom/c0cf514e3c213811e72f5f531ff168af

**Comment by Ommina** [comment]
Something looks weird there.  Can we see your build.gradle?

`at mezz.jei.startup.NetworkHandler.<init>(NetworkHandler.java:17) ~[jei-1.17.1-8.0.0.16_mapped_parchment_2021.12.19-1.18.1.jar%2384!:8.0.0.16] {re:classloading}`

looks like you have a 1.17.1 copy of JEI in there somewhere.

**Comment by Flamebom** [comment]
https://github.com/Flamebom/HellFall/blob/main/HellFall/build.gradle
https://github.com/Flamebom/HellFall/blob/main/HellFall/gradle.properties

**Comment by mezz** [comment]
Thanks for the report!
I think Ommina correctly identified the issue, there is something wrong with the state of the gradle project and you have an older version of JEI in there.
Try refreshing your gradle project or deleting the gradle cache and try again.

**Comment by Flamebom** [comment]
still doesn't work, going try deleting the cache again though it didn't work the first time

**Comment by Flamebom** [comment]
seems like it worked on a different computer without gradle already installed
