### ISSUE TITLE
[1.18.1] Crash On hover over arrow

### ISSUE THREAD

**Issue by PestoPosta** [mezz/JustEnoughItems#2640]
Well having poked around in the crash, JEI seems to be the cause, but if it i not
any help would be appreciated. I've been arguing with the mod pack for the last week or so
and I finally have a playable version except for this crash.

I hover over the arrow game crashes.
![image](https://user-images.githubusercontent.com/15177759/147874716-6e154c5d-8e2a-4ba8-b3f0-3a5f27eb9104.png)

Crash Log
[crash-2022-01-02_06.37.56-client.txt](https://github.com/mezz/JustEnoughItems/files/7798986/crash-2022-01-02_06.37.56-client.txt)

Any assistants would be greatly appreciated.
Thanks in advance for any help provided. :)

**Comment by Ommina** [comment]
See #2636

You can revert to 9.1.1.48 for the time-being, or just hang out and wait for an update.

**Comment by PestoPosta** [comment]
> See #2636
> 
> You can revert to 9.1.1.48 for the time-being, or just hang out and wait for an update.

Your a god send

I should have thought of that, but I am sure you know how it is when you've
 looked at a problem for hours and can't figure out what the cause is.
 
 Thanks

**Comment by PestoPosta** [comment]
This bug can be closed

Down Grade to the previous version of JEI fixed it.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which will be released shortly.
dcd7d2b
