### ISSUE TITLE
Error -1

### ISSUE THREAD

**Issue by gott150** [mezz/JustEnoughItems#2641]
Hi,
every time i play it crashes. Someone from the forge forum said its Just Ehough Items. 
The crash report:    https://gist.github.com/gott150/f6e23625d55f17c0e90e17d735371559
The debug.log:    https://gist.github.com/gott150/7a81dd466f23ff06d7a62b93a03ab2d8

**Comment by Wailwolf** [comment]
Same ! Each time I tried to craft something it crashed with this error. I removed the mod waiting for a fix.

**Comment by Ommina** [comment]
See #2636 

You can revert to 9.1.1.48 for the time-being, or hang out and await an update.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which will be released shortly.
dcd7d2b
