### ISSUE TITLE
[Crash] Rendering Screen on 1.18.1 using JEI-1.18.1-9.1.2.50.jar

### ISSUE THREAD

**Issue by Entralia** [mezz/JustEnoughItems#2644]
(https://github.com/mezz/JustEnoughItems/files/7800306/crash-2022-01-02_23.31.03-client.txt)

Greetings, JEI Team!
Blessed New Years!

It appears like JEI was causing a crash whenever I tried to hover over the 2x2 crafting grid to craft anything (namely, trying to craft logs to planks to start the game 😅)
The crash produced a "Rendering Screen" error

Any idea how to fix this?
As far as I'm aware, it's a client-sided crash since it happens both on singleplayer worlds, and only to the player on our multiplayer server with the same modlist (minus JEI, since it's client-sided)

The full modlist is included at the bottom of the crash report, if it's any help

Is it possible I downloaded a broken version of JEI from curseforge, or was it a mod conflict?

**Comment by Klouver-github** [comment]
this is happening to me as well

**Comment by Entralia** [comment]
> this is happening to me as well

Glad I'm not the only one experiencing it
Thanks for the quick reply!
Hope it gets resolved for both of us 😃

**Comment by Entralia** [comment]
Seems like a quick-fix for me was downgrading the JEI version to jei-1.18.1-9.1.1.48.jar

Hope this helps in the meantime, Klouver-github!

**Comment by Ommina** [comment]
See #2636  (and about eight others now I think).  Reverting to an earlier version is you best bet for the moment.

**Comment by Entralia** [comment]
Cheers, Ommina!

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which will be released shortly.
dcd7d2b
