### ISSUE TITLE
Game crash when hovering mouse on spruce plank

### ISSUE THREAD

**Issue by AlepandoCR** [mezz/JustEnoughItems#2646]
just crafting a spruce plank will give error: 
```
The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.client.gui.Font
Código de error: -1
```
mods used:
![image](https://user-images.githubusercontent.com/70236880/147903097-827c5673-5a88-4243-8583-f09037d377d3.png)

Note: Removing JEI fixes the problem

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which will be released shortly.
https://github.com/mezz/JustEnoughItems/commit/dcd7d2bb9a65ea4204a0a790a05f26fc63106ef1

**Comment by RebelliousUno** [comment]
Thanks for this, I've just seen this come through on CurseForge.  Updated my pack and this seems to be working now <3
