### ISSUE TITLE
Game crashes when hovering any type of wood

### ISSUE THREAD

**Issue by Anmos31** [mezz/JustEnoughItems#2647]
Not only vanilla wood. It's been happening with BoP too.

Description: Rendering screen

java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.client.gui.Font

**Comment by Ommina** [comment]
Hi!  This is been fixed in the most recent (as of this writing) release of JEI: the Beta releases for both 1.17 and 1.18 on CurseForge.  Update your JEI and you should be fine.

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of #2638
