### ISSUE TITLE
Translation strings for keybinds too long

### ISSUE THREAD

**Issue by sekwah41** [mezz/JustEnoughItems#2648]
![image](https://user-images.githubusercontent.com/3209834/147965347-1af3061a-15cc-4839-9ff8-dbd02b4cbb99.png)

The translation strings for some of the keybinds are far too long and make other mods' keybinds unreadable. (At least in auto or on certain resolutions)

I'll look to make a pr to fix this on forge's end to stop them from being unreadable though the value is far too long.

**Comment by mezz** [comment]
Thanks for the report!
I think this should be handled in Forge, I'm sure these will end up even longer in more verbose languages like German.
I'll try to think of a shorter string for this in the meantime.
