### ISSUE TITLE
Neotech's Basic RF Batteries are crafted with 0 durability, breaking JEI's "Move items into crafting area"

### ISSUE THREAD

**Issue by mickdekkers** [mezz/JustEnoughItems#265]
BBoldt/ThePioneers/issues/62
@mezz as requested, I'm opening an issue about this here.

I can use the batteries as components in regular crafting, notice the 0 durability: ![](http://puu.sh/ovBk1/f7d04a2182.png)
Also notice the extra Basic RF Batteries in my inventory.

However, I'm unable to click the `+` icon because JEI says the Basic RF Batteries are missing: ![](http://puu.sh/ovBGu/2e916f254c.png)

JEI seems to think the recipe requires _undamaged_ Basic RF Batteries, which isn't true (see first pic): ![](http://puu.sh/ovBwO/29a726bc8b.png)

Some additional information:
- Crafting the _Basic RF Storage_ item using the batteries shown in the pictures crafts that item with 0 durability as well, as though it 'inherited' it from the batteries. According to JEI, this item can then also not be used as a component in further crafting recipes (e.g. to craft _Advanced RF Storage_).
- Using a Buildcraft Auto Workbench to craft these items (_Basic RF Battery_, _Basic RF Storage_) results in their undamaged versions.

Version info:
- [The Pioneers modpack](http://mods.curse.com/modpacks/minecraft/241377-the-pioneers) R7
- Minecraft 1.8.9
- Forge 11.15.1.1855
- [NeoTech](https://github.com/TeamBR-Modding/NeoTech) 1.8.9-2.4.4
- JEI 1.8.9-2.28.17.185

**Comment by Prospector** [comment]
I'm pretty sure NeoTech needs to add this on their side via the JEI api.

**Comment by mezz** [comment]
I have reported this to NeoTech now that there is a proper way for them to register the extra information with JEI.
