### ISSUE TITLE
Can't hide items in 1.18.1

### ISSUE THREAD

**Issue by Nick-McKay** [mezz/JustEnoughItems#2650]
None of the key-combinations seem to be able to hide items and none of those keys are listed under keybinds in the Minecraft keybind menu either

**Comment by Tahakk** [comment]
it's completely borked... if you turn the mode on, every key press when hovering (toggling on/of function, left/right click, shift, ctrl) hides/unhide only that one hovered item

it would also be nice to have interaction with the cogwheel (like cheat mode - but SHIFT key for example), also there is no indication that the mode is ON (blue cogwheel background?)

**Comment by mezz** [comment]
Thanks for the report!
It should be working correctly in the latest version, I just fixed it very recently. Please try updating and if you still have issues, please paste your client log here.

**Comment by Tahakk** [comment]
Can confirm. Using 9.1.2.58 fixed the issue :) Thanks
