### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by thelegitdolt** [mezz/JustEnoughItems#2652]
For issues:
https://gist.github.com/thelegitdolt/96c5688265de5e0b8fa9ef185643863a crash report

https://gist.github.com/thelegitdolt/4ea532ff1d72935f111176c88d5d3905 latest.log

**Comment by Ommina** [comment]
Hi! This is been fixed in the most recent (as of this writing) release of JEI: the Beta releases for both 1.17 and 1.18 on CurseForge. Update your JEI and you should be fine.

**Comment by DoubleThoughtTheProgrammer** [comment]
Hi, I just encountered the same crash, and I'm running the latest version of JEI (Beta, jei-1.18.1-9.1.2.54.jar). CurseForge says it is up to date, and it's the version uploaded yesterday (03 Jan 2022).

**Comment by dave-development** [comment]
I have the same problem.

**Comment by Ommina** [comment]
@DoubleThoughtTheProgrammer  In that case, I think it would be best if you provided a fresh crash report.  The crash given in the OP is for 9.1.2.50 -- if you're using the updated version, an equally updated crash report would be valuable.

@David-Vornholt  Same comment applies, if you're using 9.1.2.54.

**Comment by DoubleThoughtTheProgrammer** [comment]
[crash-2022-01-05_11.51.26-client.txt](https://github.com/mezz/JustEnoughItems/files/7811898/crash-2022-01-05_11.51.26-client.txt)
[latest.log](https://github.com/mezz/JustEnoughItems/files/7811899/latest.log)

Here you go

I'm only using 9.1.2.50, but that's the one that is up to date from CurseForge... not sure why there's the mismatch between the version which Forge claims and the version the file claims. I'm going to delete JEI and reinstall.

Edit: I installed the latest version from the curseforge website, but it added an "update" button to the curseforge app. Clicking the button downgrades from 9.1.2.54 to 9.1.2.50, but the CurseForge GUI claims that I updated today, and the version is 9.1.2.54.
<img width="1473" alt="Screenshot 2022-01-05 at 12 03 29 PM" src="https://user-images.githubusercontent.com/74284809/148158947-7ed37d8d-3d70-49ab-9488-657e3545a538.png">
(This is the GUI from CurseForge showing the version after I click update; note that the actual file installed is 9.1.2.50)

**Comment by DoubleThoughtTheProgrammer** [comment]
Alright, so there was a bit of GUI confusion, and for some reason CurseForge wants to update from 9.1.2.54 to 9.1.2.50. Now that I've downloaded the mod manually from the website and dragged it into the mods folder, it seems like it's working.

**Comment by Ommina** [comment]
Thank you for taking the time to test it out!  I, for one, don't pretend to understand what sorcery CurseForge uses to decide which version to promote, but I'm glad you got it working in the end.

We've not heard back from David, but I wonder if it is a similar situation.
