### ISSUE TITLE
[ISSUE] Mouse Cursor Display of Given Item Not Shown in Minecraft (v1.17.1, v1.18.0, or 1.18.1)

### ISSUE THREAD

**Issue by sdarkwell** [mezz/JustEnoughItems#2654]
**Hello,**

It appears there may be a regression between version for Minecraft v1.16.5 and later versions.

**With Cheat Mode enabled (and in Give Mode "MOUSE_PICKUP" per default), after left-clicking an item:**
- v1.16.5: Displays a hovering representation of the given item (or item stack) that follows the mouse. Hovering representation is removed once an item slot or area outside of the inventory is clicked (thus instantiating the item into the world)
- v1.17.1: No item is displayed. Item will still be instantiated into the world after clicking in an item slot or outside of the inventory

I've tested this in Single player Survival in clean versions of Minecraft v1.16.5, 1.17.1 and 1.18.1 with no other mods installed and using the newest version of Forge associated with each Minecraft version.

Attached is a copy of a [latest.log](https://github.com/mezz/JustEnoughItems/files/7810637/latest.log) where I start a new Minecraft instance, create a Single Player world, enter Cheat Mode, give myself a single item, then exit the game.

- Log: [latest.log](https://github.com/mezz/JustEnoughItems/files/7810637/latest.log)

Please let me know if there is anything else I can provide to assist with troubleshooting.

**Thank you and be well!**
\- S.

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix for this for 1.17 and 1.18. 
Please let me know if you find any more issues.
