### ISSUE TITLE
Crash when using shortcuts for inventory crafting

### ISSUE THREAD

**Issue by hypernova132** [mezz/JustEnoughItems#2656]
[crash-2022-01-05_14.11.12-client.txt](https://github.com/mezz/JustEnoughItems/files/7817551/crash-2022-01-05_14.11.12-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/2638
Please try the latest version of JEI, it should be fixed already.
