### ISSUE TITLE
[1.18.1] Wood Logs not being moved when clicking on Move Item. 

### ISSUE THREAD

**Issue by ffuentesm** [mezz/JustEnoughItems#2657]
Basically, for some reason, the Move Item for fast crafting does not recognize logs, any type of log, not from Vanilla, or mods.

![image](https://user-images.githubusercontent.com/44974827/148299539-181cba11-8c68-4da2-816e-c4f75af6924d.png)
![image](https://user-images.githubusercontent.com/44974827/148299557-65fe444b-69ab-49d0-b968-7c27153db8eb.png)

**Comment by mezz** [comment]
Thanks for the report!
That's very strange, but I wasn't able to reproduce this issue with just JEI and vanilla. 
Can you try to remove some mods and see if one is causing the issue?

**Comment by ffuentesm** [comment]
This was fixed in the latest update, where logs and planks are now picked, regardless of the type. 

This issue is now showing on the glass block. Where if I have a recipe that uses any glass block, but the current repipe is showing a glass block form a mod, no glass block that matches that specific type will be used.
