### ISSUE TITLE
I can't start my minecraft modpack.

### ISSUE THREAD

**Issue by Rarabus1** [mezz/JustEnoughItems#2658]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by Rarabus1** [comment]
I can give you a screenshot of how it looks when im starting it if that is good enough.

**Comment by mezz** [comment]
No sorry, that would not help me.

**Comment by Rarabus1** [comment]
Ok where do i see the information you need??

**Comment by Rarabus1** [comment]
![Skärmbild 2022-01-06 175521](https://user-images.githubusercontent.com/97201176/148420090-99188b3c-4b1b-40d4-86ac-8e6d923d2420.png)

That is what is coming up for me when im starting i don't know where the information you need is that is all i got.

**Comment by mezz** [comment]
Please click the green link to the crash report, copy and paste its contents to https://gist.github.com, and link the gist url here so I can see.

**Comment by Rarabus1** [comment]
If i click it nothing happens

**Comment by mezz** [comment]
What happens when you click the "Get link" button?

**Comment by Rarabus1** [comment]
It says [Failed]

**Comment by mezz** [comment]
It looks like this screen is from the `VanillaFix` mod, but something went very wrong with it.
Can you please report the bug to them here, and link back to this issue? https://github.com/DimensionalDevelopment/VanillaFix/issues/new
