### ISSUE TITLE
JEI 1.10.2

### ISSUE THREAD

**Issue by Scyye** [mezz/JustEnoughItems#2660]
When playing a modpack, when searching:
blaze
diamond
iron
and a few more
my game crashes.

**Comment by Scyye** [comment]
MODPACK: https://www.curseforge.com/minecraft/modpacks/project-infinity-unlimited-extended

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full crash log to https://gist.github.com and link it here.
