### ISSUE TITLE
1.18.1 crash when crafting

### ISSUE THREAD

**Issue by Zygarde365** [mezz/JustEnoughItems#2662]
on the most recent version of JEI and forge

crash report:

[crash-2022-01-06_17.12.36-client.txt](https://github.com/mezz/JustEnoughItems/files/7825080/crash-2022-01-06_17.12.36-client.txt)

**Comment by oznecniV97** [comment]
The bug is still present on version 9.2.1.69 using last forge version (39.0.19)
[crash-2022-01-12_23.51.13-client.txt](https://github.com/mezz/JustEnoughItems/files/7858472/crash-2022-01-12_23.51.13-client.txt)

**Comment by mezz** [comment]
> The bug is still present on version 9.2.1.69 using last forge version (39.0.19) [crash-2022-01-12_23.51.13-client.txt](https://github.com/mezz/JustEnoughItems/files/7858472/crash-2022-01-12_23.51.13-client.txt)

@oznecniV97 sorry, your crash log has something weird going on.
The version of JEI that you have running (visible in the stack trace) is actually an older one: `jei-1.18.1-9.1.2.50`.
I don't know why, please check your modpack or dev environment.

**Comment by oznecniV97** [comment]
> > The bug is still present on version 9.2.1.69 using last forge version (39.0.19) [crash-2022-01-12_23.51.13-client.txt](https://github.com/mezz/JustEnoughItems/files/7858472/crash-2022-01-12_23.51.13-client.txt)
> 
> @oznecniV97 sorry, your crash log has something weird going on. The version of JEI that you have running (visible in the stack trace) is actually an older one: `jei-1.18.1-9.1.2.50`. I don't know why, please check your modpack or dev environment.

Short sad story, CurseForge install me 2 versions of the mod togheter and forge load the oldest one instead of the new one...
Thanks for the solution.
