### ISSUE TITLE
JEI overlap

### ISSUE THREAD

**Issue by zachsai** [mezz/JustEnoughItems#2663]
Effect wrapping / jei wrapping. You can see in this video what happens when you have an effect and the jei. I have a lot of columns because I am on an ultrawide monitor. That might be why you have never had this issue. NER has item wrapping in their item guis on the right, so it must be possible.
1.18.1
https://user-images.githubusercontent.com/63996164/148464662-1059f147-add3-4a41-81d5-45e737bacbd0.mp4

**Comment by mezz** [comment]
Thanks for the report!
Please try with the latest version of JEI, I believe this has already been fixed.
