### ISSUE TITLE
[1.18.1 Feature] Allowing MODID:ITEMNAME in search

### ISSUE THREAD

**Issue by itsdinkd** [mezz/JustEnoughItems#2668]
Being a modpack maker and editing recipes on the go in json files sometimes human errors can occur like thinking a item name is written like something else. 

A quick way to verify this would be copying and pasting the entire id like `givemehats:strider_hat` into JEI search bar, and allowing it to show a item if it exists and matches the format. A feature currently in REI, I was hoping this would be possible to add into JEI.

**Comment by mezz** [comment]
Thanks for the suggestion!

I have changed JEI's `resourceId` search mode to `resourceLocation`, so now you can enable this in JEI's client config:
`ResourceLocationSearchMode = "ENABLED"`
and search the way you'd like:
![2022-01-12_14 24 53](https://user-images.githubusercontent.com/916092/149244162-c34b08a2-2edb-4b4f-b325-9f12aaae1281.png)

**Comment by itsdinkd** [comment]
Oh hell yeah! Thanks!

**Comment by itsdinkd** [comment]
> Thanks for the suggestion!
> 
> I have changed JEI's `resourceId` search mode to `resourceLocation`, so now you can enable this in JEI's client config: `ResourceLocationSearchMode = "ENABLED"` and search the way you'd like: ![2022-01-12_14 24 53](https://user-images.githubusercontent.com/916092/149244162-c34b08a2-2edb-4b4f-b325-9f12aaae1281.png)

Which config file do I enter this in?

**Comment by itsdinkd** [comment]
Found it. when i put in ResourceLocationSearchMode = "ENABLED" it automatically gets deleted after saving lol

**Comment by mezz** [comment]
There was an issue with my build system recently, so the fixed version might not have been published when you tried this out.
Please try again with the latest version on CurseForge from today, and let me know how it goes!
