### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by noobyaran9** [mezz/JustEnoughItems#267]
Minecraft crashed when trying to load the world.

[crash-2016-05-07_21.12.18-client.txt](https://github.com/mezz/JustEnoughItems/files/253431/crash-2016-05-07_21.12.18-client.txt)

**Comment by GirafiStudios** [comment]
This is a MineTweaker crash.

**Comment by mezz** [comment]
Thanks for the report!
Please copy your report to the MineTweaker/CraftTweaker issue tracker here: https://github.com/jaredlll08/CraftTweaker/issues
