### ISSUE TITLE
Going back a screen in JEI

### ISSUE THREAD

**Issue by Groot6969** [mezz/JustEnoughItems#2670]
Hello, I was wondering if there is a way to go "back a screen" in jei. Say like you click 1 thing and it leads to another but you need to make something else. How can you go back to the OG thing you were trying to make?

**Comment by Ommina** [comment]
I *think* they key you are looking for is Backspace, which returns you to the previous recipe.

**Comment by Groot6969** [comment]
I tried that and nothing happens. Do I need to change anything in controls?

**Comment by mezz** [comment]
There's a keybind for it in the controls, "Show Previously Viewed Recipe".
By default, it's set to `Backspace` but you can bind it to whatever you want.
