### ISSUE TITLE
1.18.1 - 9.2.1.69 - Crash when mouse pass on arrow in crafting table

### ISSUE THREAD

**Issue by oznecniV97** [mezz/JustEnoughItems#2674]
When the mouse pass on the recipe arrow in crafting table the game crashes.
It will happen even in inventory and furnace.

*Minecraft version*: 1.18.1
*Forge version*: 39.0.19
*JEI version*: 9.2.1.69

## Log
[crash-2022-01-12_23.51.13-client.txt](https://github.com/mezz/JustEnoughItems/files/7858472/crash-2022-01-12_23.51.13-client.txt)

_Originally posted by @oznecniV97 in https://github.com/mezz/JustEnoughItems/issues/2662#issuecomment-1011522569_

**Comment by mezz** [comment]
Thanks for the report!
Sorry, your crash log has something weird going on.
The version of JEI that you have running (visible in the stack trace) is actually an older one: `jei-1.18.1-9.1.2.50`.
I don't know why, please check your modpack or dev environment.

**Comment by oznecniV97** [comment]
Short sad story, CurseForge install me 2 versions of the mod togheter and forge load the oldest one instead of the new one...
Thanks for the solution, the issue can be closed.
