### ISSUE TITLE
Latest 1.18 release swaps `Show recipe` and `Show uses`

### ISSUE THREAD

**Issue by josiah-roberts** [mezz/JustEnoughItems#2676]
Title pretty much says it all.

**Comment by Ommina** [comment]
So I was about to write a "something else must be going on here" reply, but figured I'd better check before spouting off too much.

Tested 9.2.1.71 (IntelliJ dev environment, one other mod, forges 39.0,9 and 39.0.19 both), and... normal behaviours of LMB and RMB are indeed reversed.  It's surprisingly disconcerting.

Edit: *R* and *U* are also reversed.  JEI "show recipes" and "show uses" key binds are correct.

**Comment by josiah-roberts** [comment]
> Edit: _R_ and _U_ are also reversed. JEI "show recipes" and "show uses" key binds are correct.

Yup. Checked all that as well.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the next release, which should be available shortly.
