### ISSUE TITLE
Forge version 14.23.2759

### ISSUE THREAD

**Issue by C3BOOST** [mezz/JustEnoughItems#2679]
Is there a JEI version that works on forge version 14.23.2759? i try to make a custom profile on curseforge and the first mod i want to use doesn't work on higher forge versions then previously mentioned.

thanks for the answser already.

**Comment by Ommina** [comment]
I'm making some guesses here, but assuming you mean 14.23.4.2759, you could give JEI version 4.13.1.220 a try.

In theory, later versions should work as well (4.13.1.225 was pretty popular), but I honestly don't remember if there were breaking changes in Forge around that time.

**Comment by C3BOOST** [comment]
> I'm making some guesses here, but assuming you mean 14.23.4.2759, you could give JEI version 4.13.1.220 a try.
> 
> In theory, later versions should work as well (4.13.1.225 was pretty popular), but I honestly don't remember if there were breaking changes in Forge around that time.

Didn't saw my own typo lol but you where guessing right :D i tried the version you recommmend and it's working!! So much thanks this makes me really happy :)))
