### ISSUE TITLE
1.16.5 Bookmark dupe

### ISSUE THREAD

**Issue by MaryKirschner** [mezz/JustEnoughItems#2681]
so basically whenever i bookmark an item then bookmark another and try bookmark the previous item it shows 
![image](https://user-images.githubusercontent.com/45043402/149622122-eb3d8899-5892-4428-bd30-599f34522747.png)
as shown here

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next version of JEI for 1.16
