### ISSUE TITLE
New 1.16.5 not showing crafting recipes (with Thermal mods)

### ISSUE THREAD

**Issue by BrettThekidRE** [mezz/JustEnoughItems#2682]
The newest update seems to have a bug for me where it doesn't show crafting or any other mod supported recipes for items 

So currently I have had to downgrade to a version that did work hope you can help me out thank you (My bad its another mods problem)

**Comment by KasenC** [comment]
I'm having the same problem, could I ask what other mod the issue is with?

**Comment by BrettThekidRE** [comment]
I've no clue I just happened when I updated to the newest version of JEI it basically doesn't let me look up crafting recipes or smelting recipes just if it has a trade it shows

**Comment by KasenC** [comment]
In my case, it was Thermal Foundation/Thermal Expansion. I downgraded these (to the 1.4.1.x releases) and it seems to have fixed the issue,

**Comment by BrettThekidRE** [comment]
Ok I will give that a try

**Comment by KasenC** [comment]
Upon further investigation, my issue was not in fact being directly caused by Thermal, but rather a broken Thermal compatibility recipe in the mod Atmospheric. Downgrading Thermal has, however, been a viable workaround for me, and has resolved the glitched behavior.

**Comment by Snefee** [comment]
Could you tell me what version is working for you? When I play on multiplayer the mod shows only reciepes for anvil (even on vanilla items) but when I play on singleplayer everything works fine. The mod (same version) is on the server and client.

**Comment by KasenC** [comment]
I'm using thermal_foundation-1.16.5-1.4.1.7, thermal_expansion-1.16.5-1.4.1.3, and jei-1.16.5-7.7.1.144

**Comment by Snefee** [comment]
Thank you! It worked!

**Comment by KasenC** [comment]
No problem!

**Comment by laforcem** [comment]
Worked for me as well. The fix also works for the current version of JEI at the time of writing (jei-1.16.5-7.7.1.14).

**Comment by mezz** [comment]
Has this bug been reported to the thermal mods? If so please link it here for people to find.

**Comment by BrettThekidRE** [comment]
I am not sure to be fair

**Comment by norbzy** [comment]
has anyone seen if the new thermal mods updates fix it?

**Comment by eliseuwuu** [comment]
> has anyone seen if the new thermal mods updates fix it?

Yes it does

**Comment by mezz** [comment]
Thanks for the update, I'll close this issue now that it's resolved by updating the Thermal mods.
