### ISSUE TITLE
Just Enough Items not showing up with to many mods

### ISSUE THREAD

**Issue by tomiscool850** [mezz/JustEnoughItems#2685]
so every time i run Minecraft on 1.16.5 the JEI doesn't show up

some other information

-it doesn't crash the game just doesn't show up
-I've seen that this happens when you have about 300 mods so idk

![Screenshot 2022-01-17 124458](https://user-images.githubusercontent.com/78148468/149835234-f18885fb-270d-4e7b-ae04-41bded8a1acc.png)

**Comment by mezz** [comment]
Thanks for the report!
This is probably caused by one of the 300 mods, please try removing batches of mods to figure out which one is causing an issue, and then we can find out what the problem is and report it to the author of that mod or fix the issue in JEI.
