### ISSUE TITLE
[1.16.5 Modded] JEI not showing crafting reciepes on Server

### ISSUE THREAD

**Issue by Snefee** [mezz/JustEnoughItems#2686]
Hi,
Im playing modded minecraft with my friends on a server and we have a problem. JEI doesn't show any crafting recipe when we try to use it on our server. When we are on singleplayer everything is working fine. Our modpack has 287 mods.
JEI (same version) is in the mods folder on server too so there is no chance that it isn't loaded or something. We tried 3 versions from curseforge and they didnt work. We tried - 1.16.5-7.7.1.145, 1.16.5-7.7.1.144, 1.16.5-7.7.1.139.

**Comment by Snefee** [comment]
Server logs: [latest.log](https://github.com/mezz/JustEnoughItems/files/7884898/latest.log)

**Comment by Snefee** [comment]
Everything worked after downgrading thermal expansion to 1.16.5-1.4.1.3 and thermal foundation to 1.16.5-1.4.1.7 with JEI 1.16.5-7.7.1.144

**Comment by VelkyFauls** [comment]
How did you do this exactly? My friends and I are having this issue but we do not know how to downgrade mods. We are running the "A bit of everything" modpack.

**Comment by Snefee** [comment]
> How did you do this exactly? My friends and I are having this issue but we do not know how to downgrade mods. We are running the "A bit of everything" modpack. 

Go into the mods folder in your minecraft folder -> search for the mods that you want to downgrade -> delete them -> download older mods from curseforge [when you go into selected mod category you go into files and find older version for your minecraft version] -> put them into your mods folder

For server just repeat the steps but go into the mods folder in your server folder

**Comment by eliseuwuu** [comment]
Therezbeen a patch for thermal that fixes this bug
