### ISSUE TITLE
Is there JEI version 7.7.1.117 of the API?

### ISSUE THREAD

**Issue by korAPUcard** [mezz/JustEnoughItems#2690]
I need that versions for my mod project. MC version is 1.16.5.
My mod project is using mekanism API, but this API requires JEI version 7.7.1.117.

**Comment by Ommina** [comment]
I'm not completely understanding the question, but if you absolutely have to have that particular version of JEI, [here you go](https://www.curseforge.com/minecraft/mc-mods/jei/files/3411420).

**Comment by mezz** [comment]
You can also find all the API artifacts here: https://dvs1.progwml6.com/files/maven/mezz/jei/
The specific one you're looking for is in https://dvs1.progwml6.com/files/maven/mezz/jei/jei-1.16.5/7.7.1.117/
