### ISSUE TITLE
JEI crashes when I click the next page button or search in the JEI interface

### ISSUE THREAD

**Issue by rlcraftisharder** [mezz/JustEnoughItems#2695]
Description: Rendering Screen
java.lang.NullPointerException: null
Using MC 1.18.1, JEI 9.2.3.83, Forge 39.0.59
Crash report: https://gist.github.com/rlcraftisharder/94e4393213ea30b73014caf46ae68d2e#file-gistfile1-txt

**Comment by mezz** [comment]
Thanks for the report!
Sorry, I pushed 9.2.3.83 before it was ready, please downgrade to the previous version for now. 
I will archive it on CurseForge so it's hidden.
