### ISSUE TITLE
Move log spam about recipes with empty input list to debug level

### ISSUE THREAD

**Issue by Vexatos** [mezz/JustEnoughItems#270]
Maybe remove them completely. Sometimes they are intentional.

**Comment by KnightMiner** [comment]
I cannot see why you would intentionally add a null item recipe, just check that the input stack is not null before adding it. Empty oredict recipes also seem to return null

**Comment by Vexatos** [comment]
Empty oredict tags return an empty list. I would have to go through every single oredict tag in every recipe in a mod and check whether it's empty or not.

**Comment by TehNut** [comment]
The empty list is only there because people query `OreDictionary.getOres(...)` (Creates an entry if it's not there) before querying `OreDictionary.doesOreNameExist(...)` (Does not create an entry). If modders did the checks correctly, that wouldn't be an issue.

**Comment by mezz** [comment]
Even Forge's `ShapedOreRecipe` and `ShapelessOreRecipe` are guilty of that error though, TehNut.
