### ISSUE TITLE
Item List Edit Mode missing?

### ISSUE THREAD

**Issue by Elkinsrg** [mezz/JustEnoughItems#2703]
Potentially not actually a bug but I can't find the setting for enabling the Item List Edit Mode of previous iterations. Where should it be? Version jei-1.18.1-9.2.3.84.jar

Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the question!
Look for "Toggle Hide Ingredients Mode" in the Minecraft controls/keybind menu. 
You can see the hotkey to toggle it on and off, or set your own hotkey if it's not set.
