### ISSUE TITLE
POWDER SNOW BUCKET MISSING FROM JEI

### ISSUE THREAD

**Issue by Camawama** [mezz/JustEnoughItems#2704]
It would seem as though powder snow buckets are not listed in the JEI menu! 

MC VERSION: 1.18.1
FORGE VERSION: 39.0.64
JEI VERSION: LATEST

**Comment by mezz** [comment]
Thanks for the report!

Hmm It looks like it's there to me
![2022-02-09_16 03 22](https://user-images.githubusercontent.com/916092/153311325-805ce54f-1447-4a4e-83ba-266e935f4bcf.png)
Do you have other mods installed?

**Comment by Camawama** [comment]
So the Forbidden and Arcanus mod seems to overwrite the Bucket of Powdered Snow. When I middle-click powdered snow, it gives me a Powdered Snow Eldelwood Bucket instead of the normal Powered Snow Bucket. This might have something to do with it, however, I don't see why it would remove itself from JEI.

**Comment by mezz** [comment]
Hm ok. Please report this problem to them and link back to this issue.
