### ISSUE TITLE
JEI Item list not showing in singleplayer 1.16.5

### ISSUE THREAD

**Issue by veillax1354** [mezz/JustEnoughItems#2706]
JEI does not work in 1.16.5 singleplayer, have not tried in multiplayer yet, mod list is linked below:
[https://docs.google.com/document/d/1ax5B7Pyi4pNcM06XJh0kYCtPwqhBxVFEnSdqkQ2_nkk](url)

**Comment by Veillax135** [comment]
Wrong ideas here, I forgot to install JEI

**Comment by veillax1354** [comment]
Wrong ideas here, I forgot to install JEI
