### ISSUE TITLE
JEI not working

### ISSUE THREAD

**Issue by armored999** [mezz/JustEnoughItems#2707]
How can I activate it? I don't understand how. please help

![Captura de pantalla (40)](https://user-images.githubusercontent.com/98996706/152462609-d0a05417-706a-4773-8f36-190a9e0060ad.png)

**Comment by armored999** [comment]
translation: jei overlay is off
press key.keyboard.o to activate

**Comment by mezz** [comment]
Thanks for the report!
`key.keyboard.o` should just say `o`. It means please press the `o` key on your keyboard to show JEI.

**Comment by armored999** [comment]
Now if it works, it's because I'm a newbie, thanks mezz
