### ISSUE TITLE
我进去，jei合成表显示不出来

### ISSUE THREAD

**Issue by 123fengmjmgxm** [mezz/JustEnoughItems#2708]
我做了个整合包，然后jei加进去显示不出来，有按键，但不显示

**Comment by luckyu19** [comment]
得麻煩您提供更多訊息了，截圖、Minecraft版本、JEI版本、Forge版本還有載入的log文檔
可以的話確認都更新到當前最新的版本
另外嘗試獨立測試只有JEI的話是否能正常顯示
能的話就得測試是哪個模組與JEI衝突
大多以英文溝通，中文的話我盡量幫您轉述而已

They were saying JEI crafting recipes are not showing when they are in the world, but it is a self made pack so I requested them to provide more information and test if replicable with only JEI (or attempt to find the conflict if they found the conflicting mods).

**Comment by isaaclepes** [comment]
It could be that overlays are hidden.

![image](https://user-images.githubusercontent.com/54421422/153126749-4ad8cc9d-dab3-474f-9336-05faca21c170.png)
