### ISSUE TITLE
Crash with CraftTweaker

### ISSUE THREAD

**Issue by MCEventHorizon** [mezz/JustEnoughItems#271]
If I add a recipe with CraftTweak and I look it up with JEI, I crash.
Log: http://pastebin.com/CiThmhmF

**Comment by mezz** [comment]
Thanks for the report!
Hmm interesting. What is the recipe?

**Comment by MCEventHorizon** [comment]
This is all I have, just a chisel recipe(I'm new to writing scripts so this could be my mistake but I didn't get any errors from Minetwekaer(Crafttweker) when I loaded the scrpits: //crafting items
val stone = minecraft:stone;
val iron = minecraft:iron_ingot;
val glowstone = minecraft:glowstone;
val antiblock = chisel:antiblock:*;
val dyewhite = ore:dyeWhite;
//recipies
recipes.addShaped(chisel:antiblock:15, [[stone, stone, stone, stone, glowstone, stone, stone, stone, stone]]);
recipes.addShaped(chisel:antiblock:15, [[antiblock, antiblock, antiblock, antiblock, glowstone, antiblock, antiblock, antiblock, antiblock]]);

**Comment by KnightMiner** [comment]
Well, shaped recipes are supposed to contain three sub arrays, not all in one double bracket array. E.g:

```
recipes.addShaped(furnace, [
  [cobblestone, cobblestone, cobblestone],
  [cobblestone, null,                 cobblestone],
  [cobblestone, cobblestone, cobblestone
]);
```

Items names (not variables) should contain <> around them, like so `val cobblestone = <minecraft:cobblestone>`

**Comment by MCEventHorizon** [comment]
Thanks, I'm dumb. Sorry for posting false bug report.
