### ISSUE TITLE
Item tooltip components returned from `getTooltipImage` are not rendered

### ISSUE THREAD

**Issue by Hubry** [mezz/JustEnoughItems#2710]
Using MC 1.18.1, Forge 39.0.58, and JEI 9.2.1.69

Rendering items like bundles in JEI does not show the components declared by the item.

Expected:
![img](https://user-images.githubusercontent.com/26120076/152692952-57a665c9-7c47-4d15-b88e-7044530fdd89.png)

Instead, this occurs: (note: needs bookmarking a `/give`n bundle, because they are hidden in creative/JEI)
![img](https://user-images.githubusercontent.com/26120076/152692984-4ad2a7e1-95f3-4d6e-96cb-7431f8aa4250.png)

Note that the vanilla recipe book does not show these either.

**Comment by mezz** [comment]
Thanks for the report!
This has been added in the latest version of JEI.
