### ISSUE TITLE
In 1.18.1 pressing 'f' in the search box has no effect.

### ISSUE THREAD

**Issue by sixcoino** [mezz/JustEnoughItems#2712]
JEI版本： jei-1.18.1-9.2.3.84
Forge版本：39.0.66
Minecraft版本：1.18.1
仅有JEI一个mod。
当我在搜索框内按下f键，将会与副手交换物品，需要再按一次才能输入。

JEI version: jei-1.18.1-9.2.3.84
Forge version: 39.0.66
Minecraft version:1.18.1
Only one mod of JEI is available.
When I press 'f' in the JEI search box, it will exchange items with the deputy, I need to press again to enter.

I'm sorry my English is terrible.

**Comment by mezz** [comment]
Thanks for the report!
There is a keybind to select the search box. By default it is `CTRL-F`. 
It sounds like you are hitting this keybind.
Please check your Minecraft Controls and see that you do not have the keybind set to `F`.

**Comment by niraqw** [comment]
I've encountered this issue with the f key and a similar issue with the o key (hiding the jei overlay). It seems that the default key bindings for both of these actions was at some point just the letter key without CTRL. 

A few instances I've been using for a while had the letter-only keybinds, and I never changed them, but fresh instances have the correct key bindings.

**Comment by mezz** [comment]
Strangely, JEI has pretty much always used CTRL for these keys, there may be a bug in the way that the keys are saved by Minecraft or Forge or some other issue.

**Comment by Toma400** [comment]
This is so annoying. I experienced this bug too, but it simply does swap my selected item in inventory instead of typing in JEI, and reversely - when I try to swap item, it types in JEI.
Therefore now I try to type out everything by omitting "f", like "lywheel" instead of "flywheel" .-.

**Comment by mezz** [comment]
You can just change the hotkey, it's configurable in the Minecraft controls. 
Something (maybe the modpack or a Forge bug?) changed it to a bad value but you can change it back easily without needing to work around the issue.
