### ISSUE TITLE
"Move to grid" in a odd location [BUG]

### ISSUE THREAD

**Issue by pieman0110** [mezz/JustEnoughItems#2714]
As you can see, in the newest beta, the [+] "Move to grid icon" is now located in the top left of the crafting grid, rather than outside, to the bottom right.

Tried re-installing, no use. And received multiple complaints from others on the same modpack as me.

Then attempted to install onto vanilla Minecraft, same issue, this is the version from which I took the screenshot.

Version - 1.18.1
JEI - 1.18.1-5.8.0 beta11
Forge - 39.0.63 and 39.0.75

![image](https://user-images.githubusercontent.com/99226179/153392839-9bed7c0c-c64a-4ee8-b80c-35b208a54188.png)

**Comment by Faranwall** [comment]
Version - 1.18.1
JEI - jei-1.18.1-9.3.1.88
Forge - 39.0.75

I has the same problem.

**Comment by MommyLexie** [comment]
same problem

**Comment by A5TC** [comment]
I'm having the same problem here as well.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which should be available shortly.
