### ISSUE TITLE
 "Move to Grid" not working in crafting systems. Checked to see if vanilla crafting table worked and it did.  Version jei-1.18.1-9.3.2.89.jar

### ISSUE THREAD

**Issue by Remn1c** [mezz/JustEnoughItems#2715]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Which crafting systems are having issues specifically?

**Comment by markiem32** [comment]
I can report that Refined Storage is not interacting with the "move to grid" feature, at least.

**Comment by Remn1c** [comment]
The "move to grid" is not actually moving to the grid. I have the correct items in my storage system, but when I hit the button, nothing happens. It doesn't claim that I have the materials for the craft. If I had automatic crafters. it would be broken. For example, i tried to craft a piston, had the materials to create multiple of them in my system, hit the button and nothing happened. Hope that helps.

**Comment by Remn1c** [comment]
> The "move to grid" is not actually moving to the grid. I have the correct items in my storage system, but when I hit the button, nothing happens. It doesn't claim that I have the materials for the craft. If I had automatic crafters. it would be broken. For example, i tried to craft a piston, had the materials to create multiple of them in my system, hit the button and nothing happened. Hope that helps.

**Comment by derrickmehaffy** [comment]
Old issue is: https://github.com/mezz/JustEnoughItems/issues/2715

I can confirm that only Refined Storage thus far is having the problem. I tested on Applied Energistics with latest ATM7 version (0.2.40b) and it works fine there.

**Comment by mezz** [comment]
I believe I broke this in the recent refactor for JEI 9.3.0.
I will take a look at what's going wrong and make sure I restore backward compatibility with Refined Storage's transfer system.

**Comment by Thomas-Tomahawk** [comment]
As mentioned in the closed thread:
I can confirm that "Sophisticated Backpacks" has the same problem with the Crafting Upgrade!

**Comment by mezz** [comment]
Thanks, I’ve identified the issue on my end and will work on a fix.

**Comment by mezz** [comment]
This issue has been fixed in JEI version 9.3.2.92
