### ISSUE TITLE
The "move to items" issue (Accidentally closed my thread), but my follow-up

### ISSUE THREAD

**Issue by Remn1c** [mezz/JustEnoughItems#2717]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Remn1c** [comment]
The "move to grid" is not actually moving to the grid. I have the correct items in my storage system, but when I hit the button, nothing happens. It doesn't claim that I have the materials for the craft. If I had automatic crafters. it would be broken. For example, i tried to craft a piston, had the materials to create multiple of them in my system, hit the button and nothing happened. Hope that helps.

**Comment by Remn1c** [comment]
"C:\Users\13205\Videos\2022-02-10 20-47-42.zip" -VIdeo

**Comment by Remn1c** [comment]
Video Help: [2022-02-10 20-47-42.zip](https://github.com/mezz/JustEnoughItems/files/8045694/2022-02-10.20-47-42.zip)

**Comment by derrickmehaffy** [comment]
Old issue is: https://github.com/mezz/JustEnoughItems/issues/2715

I can confirm that only Refined Storage thus far is having the problem. I tested on Applied Energistics with latest ATM7 version (0.2.40b) and it works fine there.

**Comment by derrickmehaffy** [comment]
@Remn1c why do you keep closing these issues?

**Comment by Thomas-Tomahawk** [comment]
I can confirm that "Sophisticated Backpacks" has the same problem with the Crafting Upgrade!

**Comment by MommyLexie** [comment]
Create's Mechanical Crafter is showing issues with jei when viewing recipes the background for the icon is completly on the wrong side

**Comment by mezz** [comment]
Let's keep discussion to this original issue please, I'll reopen it: https://github.com/mezz/JustEnoughItems/issues/2715

**Comment by mezz** [comment]
This issue has been fixed in JEI version 9.3.2.92
