### ISSUE TITLE
Create's Mechanical Crafter layout in recipes is completely broken

### ISSUE THREAD

**Issue by MommyLexie** [mezz/JustEnoughItems#2718]
Thank you for reporting!

Create's Mechanical Crafter is showing issues with jei when viewing recipes the background for the icon is completely on the wrong side

![image](https://user-images.githubusercontent.com/81419755/153655509-71ae3a9d-5dd2-4b30-bba1-73c875a2e41d.png)
![image](https://user-images.githubusercontent.com/81419755/153655531-d21485b1-25ac-43e8-9f50-4b4355874008.png)

**Comment by MommyLexie** [comment]
The Position of the icon and  bar on the right changes when viewing different recipes

**Comment by MommyLexie** [comment]
oh and sequenced assemblies
![image](https://user-images.githubusercontent.com/81419755/153656596-8aba335a-5c51-4b34-b163-408dc7236834.png)

**Comment by mezz** [comment]
Thanks for the report!
Does this issue only happen with Create?
Please report this bug to them as well and link back here.

**Comment by MommyLexie** [comment]
> Thanks for the report! Does this issue only happen with Create? Please report this bug to them as well and link back here.

will do

**Comment by mezz** [comment]
Thanks! Create has fixed this on their side, and I have added some extra safety on JEI's side that will prevent the issue from happening again if another mod accidentally makes the same mistake.
