### ISSUE TITLE
[1.18.1-9.3.2.92] Recipe ingredients and outputs messed up

### ISSUE THREAD

**Issue by JaisDK** [mezz/JustEnoughItems#2720]
There is an issue displaying some recipes in .92, examples are bee breeding recipes from Productive Bees and any Mixing recipe from Create involving fluids.

There should be two bees where the flowers are shown and the flowers should be on the slots below.
![image](https://user-images.githubusercontent.com/15868585/153730072-90a3750e-8402-401a-a2a6-80cf7b680e9a.png)

Create brewing recipes (input not shown and an output fluids shown in its place)
![image](https://user-images.githubusercontent.com/15868585/153730091-f15d0e04-43e6-4f24-8940-535b55039c7b.png)

and mixing recipes (not showing output fluid)
![image](https://user-images.githubusercontent.com/15868585/153730104-9e16e22b-f35e-4fdb-9b8d-f019203ce9fb.png)

**Comment by ffuentesm** [comment]
Same this is happening in Tinker's: TConstruct-1.18.1-3.4.0.34.jar
The JEI version .92 breaks the recipe system. 
Older version does not have this problem.
![image](https://user-images.githubusercontent.com/44974827/153731850-2bf9b5da-eab8-411d-9920-26939019315e.png)
![image](https://user-images.githubusercontent.com/44974827/153731853-b1c58096-50d4-4090-969a-0969c5927a76.png)
![image](https://user-images.githubusercontent.com/44974827/153731856-1052600b-afad-4922-8ab6-15194e5c8b61.png)
![image](https://user-images.githubusercontent.com/44974827/153731864-71b58aa9-3563-412d-91bd-ae4aa69261c7.png)

**Comment by KnightMiner** [comment]
Issue seems to happen whenever a mod had multiple types of ingredients for a single recipe, particularly mixed inputs or mixed outputs. Can of course update to the new API to fix, but with how many mods this breaks it might be worth reassessing the legacy support.

**Comment by mezz** [comment]
Thanks for the report!
Hmm yeah this just seems like a JEI rendering issue, legacy support is supposed to work without issues.

**Comment by mezz** [comment]
I have a fix pending, I'll try it out on a big mod pack and ensure it's fixing all the issues listed here.

**Comment by mezz** [comment]
Looks good now, JEI version 9.3.2.94
<img width="453" alt="Screen Shot 2022-02-13 at 3 47 37 PM" src="https://user-images.githubusercontent.com/916092/153786703-fa6dc19c-b09d-4498-8fbf-d3e549c0f826.png">
<img width="394" alt="Screen Shot 2022-02-13 at 3 47 17 PM" src="https://user-images.githubusercontent.com/916092/153786707-28bdbf90-7fdb-4eaf-a198-d521ebc17355.png">
