### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 35

### ISSUE THREAD

**Issue by xkeksi** [mezz/JustEnoughItems#2724]
forge: newest 1.16.5

crashlog: https://gist.github.com/xkeksi/f30c8dead3fb9b4bce4e1e19d061cd63

how it happend: just clicked next page and it crashed (after page 5)

**Comment by xkeksi** [comment]
fixed, removed AE2 and replaced it with another item storage system. but you should still look into that issue.

**Comment by xkeksi** [comment]
@mezz 
nvm i got the crash again bruh (the crashlog is the same with the above attached file, just with another mod)

	Mod Name: Silent Gear
	Registry Name: silentgear:fishing_rod
	Display Name: Dimerald Fishing Rod
	String Name: 1 fishing_rod

**Comment by Ommina** [comment]
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/157  I believe.

**Comment by mezz** [comment]
Thanks for the report!
These are rendering crashes from other mods, basically JEI is just rendering the item and the item crashes.
The original crash does match the one Ommina linked.
I think the second crash is unrelated, caused by SilentGear.

**Comment by xkeksi** [comment]
I basically only got those crashes if i use JEI, if i dont use i didnt got a crash, also this only happens with 1.16.5 on 1.12.2 there are N O crashes with almost the exact same mods, just for other versions

**Comment by mezz** [comment]
Thanks for the info.
Are you able to view these items in the creative menu without them crashing?

**Comment by xkeksi** [comment]
Yeah i can, but as soon ill search it with jei, the game crashes

**Comment by mezz** [comment]
I'm creating a new build of JEI that has a new config option in `config/jei-client.toml`: 
`FastItemRenderingEnabled`

Please try this `7.7.1.149` version of JEI and set `FastItemRenderingEnabled = false` and see if that resolves the issue.
https://www.curseforge.com/minecraft/mc-mods/jei/files/3652086

**Comment by xkeksi** [comment]
alright im going to test, give me 5mins

**Comment by xkeksi** [comment]
Nope still crashes for the same reason

**Comment by mezz** [comment]
Thanks, could you link the new crash report here?

**Comment by xkeksi** [comment]
> Thanks, could you link the new crash report here?

https://gist.github.com/xkeksi/825a160168c230ee85b480f895768a7a

**Comment by mezz** [comment]
Hmm ok. So with this new flag, I am really just calling the vanilla minecraft rendering code to draw the item. For some reason the broken item is added to JEI's list but it is fine in the creative menu, or maybe they render differently somehow...

Can you confirm if this issue happens with just JEI and Silent's mods?
If you can find exactly which mods are involved, I can dig into those and find out what's going on.

**Comment by xkeksi** [comment]
So, i sorted every mod out expect jei and silent's mods and it didnt crash, ill keep adding my mods back till i find the crash issue

updates regarding this follows soon

**Comment by xkeksi** [comment]
update: so it turns out that magnesium 1.5 is causing those jei crashes

(https://www.curseforge.com/minecraft/mc-mods/sodium-reforged)

**Comment by mezz** [comment]
Nice find, please report to them https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues and link back to this issue in your new report.

**Comment by Ommina** [comment]
Apologies, I should have said "try without magnesium" when I posted the link last night.  I was tired!
