### ISSUE TITLE
serveur crash 1.18.1

### ISSUE THREAD

**Issue by laboriens** [mezz/JustEnoughItems#2727]
forge 1.18.1 39.0.79
jei: 9.4.1.104

logs: https://textup.fr/614569sN

crash server start

**Comment by geferon** [comment]
Got the same issue

**Comment by Atlantispy** [comment]
[crash-2022-02-23_12.05.15-fml.txt](https://github.com/mezz/JustEnoughItems/files/8124176/crash-2022-02-23_12.05.15-fml.txt)

Same here

**Comment by CDAGaming** [comment]
Same issue as well...

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next version, available shortly.
