### ISSUE TITLE
Key binds window distorted

### ISSUE THREAD

**Issue by Bartmannnnn** [mezz/JustEnoughItems#2728]
Forge version - 39.0.85
JEI version - 9.4.1.104

Key binds window is distorted, as seen in the picture it is shifted to the left.

![image](https://user-images.githubusercontent.com/6097325/155308327-61d4db8d-9dae-4e60-8a17-f89921129861.png)

There are no other mods installed and window renders correctly without JEI

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the latest version, available shortly.
