### ISSUE TITLE
Menu slides to the right (1.18.1)

### ISSUE THREAD

**Issue by PhoenixBodrov** [mezz/JustEnoughItems#2729]
![изображение](https://user-images.githubusercontent.com/100290554/155328094-c6ec0140-8c9e-433d-b616-098878ff4ce6.png)

Very hard to play with that. Affects all other mods menus, such as Goki Stats and other.
1 by 1 mod test has verified that if i only had JEI, issue occurs, without it - perfect

I have optifine, Tlauncher, Forge 39.0.79

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the latest version, available shortly.
