### ISSUE TITLE
[1.9] Client side shutdown

### ISSUE THREAD

**Issue by kwpugh** [mezz/JustEnoughItems#273]
No crash report.  Launcher log: http://paste.ee/p/cTl9K

Forge: 1906
Mod: jei_1.9-3.3.3.200.jar

**Comment by kwpugh** [comment]
Happens on 197 as well.

Just tried and crashed.

**Comment by mezz** [comment]
Thanks for the report!
`A fatal error has been detected by the Java Runtime Environment`
Wow you have run into a bug with Java! Those are pretty rare.
Try updating your version of Java, it should fix the crash.
