### ISSUE TITLE
Game crashing when trying to search 1.16.5

### ISSUE THREAD

**Issue by Oakstz** [mezz/JustEnoughItems#2730]
https://gist.github.com/Oakstz/997cda0ac6902ceb9b9f3194d684d189 
Game crashes when trying to search in JEI link is above.

**Comment by Oakstz** [comment]
I guess never mind

**Comment by Pigbull320** [comment]
https://gist.github.com/Pigbull320/ff8e07bea2882601820090477690694c

Same, not every time but very often once an hour my game crashes to launcher when i type into the JEI. I think only when AE2 ME is open it happens? happens more often when i left or right click on the search bar. I cant find a good way to reproduce. but this is probably my 20th crash
