### ISSUE TITLE
1.18.1 Forge freeze on the loading screen when joining to a server

### ISSUE THREAD

**Issue by VirtualGaming1** [mezz/JustEnoughItems#2731]
Forge 39.0.85
MC 1.18.1
JEI jei-1.18.1-9.4.1.106

As it say freeze on loading screen when joining onto the server.

keep on freezing at "Building ingredient filter... "

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by VirtualGaming1** [comment]
that is very late replay let say about 7 months late. the thing is now is that I am not using 1.18.1 any more and have switched to different mod that is like this. and the log is _**LONG GONE**_ 

Rating for support -4 for very late reply
