### ISSUE TITLE
[Suggestion] Compatibility with Mod "Unidentified Enchantments"

### ISSUE THREAD

**Issue by LunarFactory** [mezz/JustEnoughItems#2732]
![image](https://user-images.githubusercontent.com/69113888/155830787-c0f6c84f-8077-4915-af17-09afe244d16d.png)
Unidentified Enchantments does not work well with JEI. JEI shows information of unidentified enchantments.

**Comment by mezz** [comment]
Thanks for the report!
The mod will need to create a JEI plugin to handle this. 
I will close this JEI issue, we can keep the discussion here: https://github.com/ferriarnus/Unidentified-Enchantments/issues/6
