### ISSUE TITLE
JEI doesnt update after /reload

### ISSUE THREAD

**Issue by freopt** [mezz/JustEnoughItems#2733]
I made changes to recipes in kubejs, then did /reload
updated recipes don't show in jei but still work

In JEI:

![image](https://user-images.githubusercontent.com/45438411/155863880-ae1ddcf9-ff49-4cf6-b586-09ecc8012a9a.png)

Crafting table:

![image](https://user-images.githubusercontent.com/45438411/155863889-6a19ab2f-f8b5-4d93-b8a7-646fbeda0720.png)

**Comment by freopt** [comment]
1.18.1 
jei 9.4.1.106

**Comment by mezz** [comment]
Thanks for the report!
`/reload` is not added by JEI, some other mod adds it and tries to reload JEI. 
Please open a new issue with whichever mod creates the `/reload` command.

**Comment by freopt** [comment]
/reload is vanilla
https://minecraft.fandom.com/wiki/Commands/reload

**Comment by mezz** [comment]
Oh sorry, somehow I've never used that command.
I need some more information to solve this issue, please paste your full `latest.log` to https://gist.github.com and link it here.

**Comment by freopt** [comment]
https://gist.github.com/freopt/cb9a128574bbf8360106b10f32f3b634
pretty sure this wasn't a problem until somewhat recently, like within the last month or so

**Comment by mezz** [comment]
Thanks, based on your log it looks like I changed some logic and it's working incorrectly on`/reload` now:
`Failed to start JEI, it is already running.`
I'll work on a fix for this shortly.

**Comment by mezz** [comment]
I have tested this out and I think I have found a good solution. 
It should work correctly on JEI `jei-1.18.2-9.4.1.116`, available shortly.
Please let me know if you run into any other issues!
