### ISSUE TITLE
Just Enough Resrouces unable to load

### ISSUE THREAD

**Issue by dorkup** [mezz/JustEnoughItems#2735]
as I'm loading a modpack from curseforge, it says that I don't have a high enough version of JEI, despite the fact that I cannot *get* a higher version, making it completely unplayable.

**Comment by kuehnfelix** [comment]
Same here!
![grafik](https://user-images.githubusercontent.com/57009073/156054710-c18319a4-2570-4fc4-8e39-2f9af5189c9c.png)

**Comment by Ommina** [comment]
The _version required_ is set by the mod that does the requiring.  In this case (or, at least, in the case of the second post, as the original post provides no details) it is JER saying that it requires 9.4.0.

You can find version 9.4.1.110 (the newest as of this writing) at https://www.curseforge.com/minecraft/mc-mods/jei/files/3667756
