### ISSUE TITLE
Certain items crafting recipe are not available to view

### ISSUE THREAD

**Issue by gdawson521** [mezz/JustEnoughItems#2736]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Please provide more information so that I can understand exactly what the problem is.

**Comment by gdawson521** [comment]
hi, so some crafting recipes are not showing on JEI but they still work for example the lead dust recipe for calculator isn't showing but when i put in the recipe it still works, this is happening with other mods like thermal expansion the machine frame, and the solar flux solar panel mark 2 the other solar panel recipes are showing. im sure other recipes arnt showing as well those are just the ones I've found so far

**Comment by mezz** [comment]
Ok thanks for the info.
I need some more information to solve this issue, please paste your full `latest.log` to https://gist.github.com and link it here.

**Comment by gdawson521** [comment]
ok where do i get my latest.log from

**Comment by gdawson521** [comment]
ok found it.

https://gist.github.com/gdawson521/84d82354f8860f6fa4268c5acf2a8ef7

**Comment by gdawson521** [comment]
i fixed it by deleting JEI and reinstalling it

**Comment by alastgir** [comment]
I've had issues with a lot of the create crafting recipes not showing, and even some vanilla items like rockets
