### ISSUE TITLE
Crash on recipe hover

### ISSUE THREAD

**Issue by Ondras4620** [mezz/JustEnoughItems#2738]
Hello, i made modpack, configured a bit and then uploaded to curseforge, later when my friend joined to my server evertything was fine until he swiped his cursor over any recipe in JEI, for me it was fine, his game crashes no crash-log just log files:

[2022-03-01-1.log.gz](https://github.com/mezz/JustEnoughItems/files/8169955/2022-03-01-1.log.gz)
[2022-03-01-2.log.gz](https://github.com/mezz/JustEnoughItems/files/8169958/2022-03-01-2.log.gz)

he tried it more nothing worked ill send my mod list and as soon as he comes back home ill send minecraft launcher log file if you need it, thanks and let me know if you find the issue

**Comment by Ondras4620** [comment]
found my problem

**Comment by mezz** [comment]
Thanks for the report!
For anyone else who comes here with the same issue, what was the problem and solution?
