### ISSUE TITLE
[1.9] Crash / Extreme lag when switching into cheat mode and back.

### ISSUE THREAD

**Issue by Insufficient-Charge** [mezz/JustEnoughItems#274]
I am on the latest version of JEI (On CurseForge) and I seem to be crashing whenever I click the "Done" in the options menu after changing my mode from "cheating: false" to "cheating: true" ...
This also happens to me in 1.8, but it seems like other people (I watch other people do it on Youtube in 1.9 and it doesn't happen to me) don't have the same issue. I don't know if it's because of some mods I have in my modpack or not. There is no crash log.

**Comment by mezz** [comment]
Thanks for the report!
JEI reloads when you change its config settings. If an addon is especially slow it might pause a while.
To solve this, I should add better handling for config settings that don't need a reload, like cheat mode.
