### ISSUE TITLE
[Other]: Cheat mode not working? (1.16.5)

### ISSUE THREAD

**Issue by jonesy678** [mezz/JustEnoughItems#2741]
### Other

I have the configurations mod on, for some reason when I turn it on, it doesn't work when I try to grab something. Help!

**Comment by mezz** [comment]
Thanks for the report!
Please report this as a Bug and include the required information so that I can look into it:
https://github.com/mezz/JustEnoughItems/issues/new?assignees=&labels=&template=bug.yml&title=%5BBug%5D%3A+
