### ISSUE TITLE
[Bug]: JEI not working in LAN

### ISSUE THREAD

**Issue by kpaakeh** [mezz/JustEnoughItems#2742]
### Steps to Reproduce the Bug

Go to lan world (not host) 

### Expected Behavior

JEI should show recipes 

### Actual Behavior

Only show 204 recipes lists
![bug](https://user-images.githubusercontent.com/100779868/156890247-58173430-36e4-44cd-a518-5ceb5d20ee5d.png)

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/ultimate-progression

### Mod Pack Version (Optional)

0.5.3

**Comment by mezz** [comment]
Thanks for the report!
I tried this out with just JEI and it seems to be working. There may be some mods that have issues, or there may be some problem in JEI on LAN with certain mods.

Can you include the `latest.log` here from the client that is joining the server and doens't see all the recipes?

**Comment by kpaakeh** [comment]
[latest.log](https://github.com/mezz/JustEnoughItems/files/8203502/latest.log)

**Comment by mezz** [comment]
Based on the log, it looks like there may be an issue with Optifine or JustEnoughResources.
Can you try again with those mods removed?
