### ISSUE TITLE
Does not show in inventory[Bug]: 

### ISSUE THREAD

**Issue by TKVZeus** [mezz/JustEnoughItems#2743]
### Steps to Reproduce the Bug

Not sure

### Expected Behavior

To see the actual mod in inventory

### Actual Behavior

Controls show up in keybinds but nothing is visible in inventory

**Comment by mezz** [comment]
Thanks for the report!
This is the same as https://github.com/mezz/JustEnoughItems/issues/2744
I will close this issue because the other issue has more information.
