### ISSUE TITLE
[Bug]: Conflict with Optifine HD U H6 pre1

### ISSUE THREAD

**Issue by NekoCompiler** [mezz/JustEnoughItems#2745]
### Steps to Reproduce the Bug

1. Press E

### Expected Behavior

jei is visible

### Actual Behavior

jei is not visible

### Extra Notes (Optional)

game version: 1.18.2 java edition
java version: oracle jdk 17.0.2
jei version: jei-1.18.2-9.5.0.125.jar
optifine version: OptiFine HD U H6 pre1

**Comment by mezz** [comment]
Thanks for the report!
This has been reported to Optifine here: https://github.com/sp614x/optifine/issues/6662

**Comment by mezz** [comment]
Duplicate of https://github.com/mezz/JustEnoughItems/issues/2744
