### ISSUE TITLE
[Bug]: Conflict between JEI and Optifine causing chat history to not function

### ISSUE THREAD

**Issue by HoodedDeath** [mezz/JustEnoughItems#2750]
### Steps to Reproduce the Bug

Easily reproducable by loading both JEI and Optifine through Forge. Confirmed behavior on Minecraft version 1.18.1, with latest available versions JEI (9.4.1.112), Optifine (HD U H5), and Forge (39.1.2)

### Expected Behavior

Expected chat history to function as normal

### Actual Behavior

Chat history does not exist. After typing in chat, pressing the up arrow to use previous messages/commands does nothing.

### Extra Notes (Optional)

I have tested this enough to know it only happens when both JEI and Optifine are loaded. I initially found this behavior when older versions of the three mods involved, then tested latest versions of all to confirm issue. I have not tested this on any game version except for 1.18.1.

### latest.log

https://gist.github.com/HoodedDeath/d71a99ed89cc4ab53ba0ad2cc1119e7b

**Comment by HoodedDeath** [comment]
For the sake of communication, I have also reported this to [Optifine's issues page here](https://github.com/sp614x/optifine/issues/6670)

**Comment by HoodedDeath** [comment]
Don't know if this still counts as a bug or conflict. I have just found out this is happening because I have the "Toggle Cheat Mode" keybind for JEI set to up arrow. That resulted in the up arrow being always caught by JEI when loaded alongside Optifine apparently (note this behavior did not happen if Optifine was not loaded)

**Comment by mezz** [comment]
Thanks for the report!
Sorry, I'm not sure what Optifine is doing in this case. 
JEI works alongside vanilla and every other mod in this case, so unfortunately I think for now I have to assume Optifine is doing something unusual.

**Comment by HoodedDeath** [comment]
I pretty much assume the same thing at this point. It seems that something Optifine is doing is causing JEI keybinds to become global, which made me unsure if it was a conflict between the two or just a bug with Optifine that I haven't noticed effecting any other mods
