### ISSUE TITLE
Crash when MC window becomes too narrow

### ISSUE THREAD

**Issue by malte0811** [mezz/JustEnoughItems#2751]
### Steps to Reproduce the Crash

1. Open an inventory (with JEIs item grid visible)
2. Make the Minecraft window narrower
3. Observe a crash

By default the window has to become very narrow for the crash to happen, but if the vanilla recipe book is also visible it happens at something like 75% of the default window width (this has actually happened in practice).

### Extra Notes (Optional)

Tested on commit 1a1db97ecc33d282477e14536ffdf49baae23b13 (latest at the time of opening this issue)

CC @DeadlySwede, this was originally reported by them on the IE testing server.

### Crash Report

https://gist.github.com/malte0811/23048141d51ce6436c0f82c42889aeeb

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the next version, which should be available shortly.
