### ISSUE TITLE
[Crash]: Crash when opening inventory with ftb teams & architectury installed (1.18.2)

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2753]
### Steps to Reproduce the Crash

1. Add jei, ftb teams, and architectury (ftb teams dependency) to your mods folder in 1.18.2
2. Launch mc
3. Create a new world 
4. Open your inventory

### Extra Notes (Optional)

I have only tested this on 1.18.2, it may occur on other 1.18 versions as well.

### Crash Report

https://gist.github.com/dragonsflame246/e0838b0a49ab7c45082d880e0ef34704

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed today in the latest version, can you try it out and let me know?

**Comment by ghost** [comment]
Sorry for the delay, I tested it and confirmed, the crash is fixed. Thank you for fixing it, especially so fast.
