### ISSUE TITLE
[Bug]: Bookmarking Botania book "Lexica Botania". When trying to remove the book it does not remove and instead duplicates it

### ISSUE THREAD

**Issue by Comphoto** [mezz/JustEnoughItems#2755]
### Steps to Reproduce the Bug

Click the hotkey "A" on the book to bookmark it then click "A" again to remove and it does not remove it while adding it again at the top

### Expected Behavior

The book should be unbookmarked

### Actual Behavior

Does not remove the book and readds it to the top so I have a second botania book and so on

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-6

### Mod Pack Version (Optional)

1.8.20

### latest.log

https://gist.github.com/Comphoto/1f7f7b0c8f6903070af2b02c3a22d2a9

**Comment by Lordmau5** [comment]
Can confirm the same on 1.16.5 with JEI 7.7.1.152
