### ISSUE TITLE
[Bug]: JEI & Create (Creative Blaze Cake item)

### ISSUE THREAD

**Issue by Aleruslio** [mezz/JustEnoughItems#2756]
### Steps to Reproduce the Bug

1. Use "Show Uses" button (JEI) on Creative Blaze Cake (item from Create mod)
2. That's it

### Expected Behavior

1. Make it so that the inscription "Smelts 10,737,418 items" fits in the frame
2. Fix the bug with blinking GUI elements (from above the Creative Blaze Cake icon)

### Actual Behavior

Howdy! Sorry for mistakes, I used Google Translator. When I use "Show Uses" button on Creative Blaze Cake, the information is not displayed correctly, loot at the screenshot: https://ibb.co/x182mnb

### Extra Notes (Optional)

Minecraft 1.16.5
JEI 7.7.1.152
Create 0.3.2g
As far as I know 1.18 version has the same problem

**Comment by mezz** [comment]
Thanks for the report!
This will be fixed in the next JEI version for 1.18, available shortly.
