### ISSUE TITLE
[Other]: Cant see crafts

### ISSUE THREAD

**Issue by TinderPlus** [mezz/JustEnoughItems#2759]
### Other

i have the mod installed using fabric, it was working on my forge server but doesn't work on the fabric server, was wondering if there is something else i have to do. 
link to screen shot below. 

https://gyazo.com/dc80e12dd4f4adae83a2d9fdfb39b126
https://gyazo.com/1e5d4abd59749a8c5d81293787ace35d
https://gyazo.com/b03fe98050af733c0577676efa1905d6

Any suggestions would be great, Thank you!

**Comment by TinderPlus** [comment]
UPDATE: i removed all mods and still nothing. idk if i have a bad link or what.

**Comment by mezz** [comment]
Thanks for the report!
JEI is written for Forge, not Fabric. I think that is the issue here.

**Comment by TinderPlus** [comment]
> Thanks for the report! JEI is written for Forge, not Fabric. I think that is the issue here.

oh appreciate the response, do you know anything thats the same but for fabric?

**Comment by mezz** [comment]
There is a mod called REI written for Fabric, you can try it out.

**Comment by TinderPlus** [comment]
it just crashes my game every time

**Comment by mezz** [comment]
Sorry but I am not really able to help debug issues with other mods here, it looks like this is not a problem with JEI.
