### ISSUE TITLE
[1.8.9 / 1.9] E-flux crashing.

### ISSUE THREAD

**Issue by Insufficient-Charge** [mezz/JustEnoughItems#276]
E-flux is crashing whenever I look up a recipe for it. Don't know if this is on E-flux's side or JEI's.
Crash log: https://gist.github.com/Insufficient-Charge/904cf12dda9b84a18633940750ae11d4
This is happening to me with both 1.8.9 and 1.9 versions of E-flux and JEI.

**Comment by mezz** [comment]
Thanks for the report!
This looks like a crash from the Compression mod's use of the Elec-Core.
Please report the same issue to them, I think they will know how to fix it:
https://github.com/TheTemportalist/Compression/issues?q=is%3Aopen+is%3Aissue
