### ISSUE TITLE
[Bug]: mod name tooltip is wrong with some mods

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2762]
### Steps to Reproduce the Bug

JEI: 1.16.5 - 7.7.1.152
Forge: 36.2.31

install jei 
install industrial foregoing, hover mouse over industrial foregoing items in JEI

### Expected Behavior

show correct mod name in tooltip

### Actual Behavior

Incorrect mod name is shown in JEI tooltip
Some mods like Industrial Foregoing register their items under different mod names

see this lovely picture  https://imgur.com/a/8ecftg8

**Comment by ghost** [comment]
noticed that liquids don't show the mod name at all, buckets do but the actual liquid tiles do not

and we cant turn off the modname by setting `ModNameFormat = ""` as suggested in issue #2472

**Comment by mezz** [comment]
Thanks for the report!
There may be another mod that adds the mod name incorrectly. By default, JEI will not add this info to tooltips if it detects that another mod is doing it already.
Try settings JEI's mod name color to something different (red) to see if it's the one creating these tooltips.

**Comment by ghost** [comment]
After some testing, which I should have done before reporting - sorry about that - JEI is indeed working correctly

I tried just JEI and Industrial Foregoing, and all was good

So indeed it must be another mod

Thanks

**Comment by ghost** [comment]
quick update: This seems to be caused by Jade mod.  Disableing Jade causes the tooltip to turn red, which what I set JEI too

**Comment by mezz** [comment]
Thanks. 

Let's direct anyone who finds this by searching, here's the Jade issue here: https://github.com/Snownee/Jade/issues/102
