### ISSUE TITLE
[Crash]: 1.18.2

### ISSUE THREAD

**Issue by JaisDK** [mezz/JustEnoughItems#2763]
### Steps to Reproduce the Crash

Right click a custom recipe catalyst in JEI while catalyst container screen is open

### Extra Notes (Optional)

Dev environment with version 9.5.2.135 because the newer ones are not available on your maven

### Crash Report

https://gist.github.com/JaisDK/31607798bd60ddb8ecfcbb75edf5f758

**Comment by mezz** [comment]
Thanks for the report!
The maven has been fixed, you can try out the latest versions there.
Can you link me to your JEI plugin? It looks like a recipe transfer issue, where some bad data has been registered for an inventory and it crashes.

**Comment by JaisDK** [comment]
https://github.com/JDKDigital/geomancy/blob/main/src/main/java/net/codersdownunder/gemmod/compat/jei/GemModJEIPlugin.java

**Comment by JaisDK** [comment]
same result with 1.18.2-9.5.3.143, can't get .148 yet but will check later when maven let's me

**Comment by mezz** [comment]
try removing your `registerRecipeTransferHandlers` and see if they are causing the crash

**Comment by JaisDK** [comment]
yea that does it. I take it they are made incorrectly then

**Comment by mezz** [comment]
Yeah you are getting an "index out of bounds" exception, so I think you have defined some index there incorrectly.

**Comment by JaisDK** [comment]
there was also two of them, removed the faulty one and it's working fine now. Thanks for the assist!

**Comment by mezz** [comment]
Glad to help!
