### ISSUE TITLE
[Bug]: Cheat Mode not working in 1.18.1

### ISSUE THREAD

**Issue by GhostWolf1512** [mezz/JustEnoughItems#2765]
### Other

I am creating a custom mod pack for myself in Minecraft 1.18.1.
When I try to cheat an item into my inventory in creative and survival modes nothing happens.
My world has cheats enabled.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by GhostWolf1512** [comment]
Here is the log.
https://gist.github.com/johanghostwolf/ad33058ed9e79dc75e3a608d82c35383

**Comment by mezz** [comment]
Thanks, unfortunately I don't see anything here. Can you please open a new issue using the "Bug" template instead of "Other" and follow the steps so that I can have enough information to help solve this bug?

**Comment by mezz** [comment]
Thanks, unfortunately I don't see anything here. Can you please open a new issue using the "Bug" template instead of "Other" and follow the steps so that I can have enough information to help solve this bug?
