### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Luckyman112** [mezz/JustEnoughItems#2766]
### Steps to Reproduce the Bug

![image](https://user-images.githubusercontent.com/102043251/159281168-990bcf0a-0a4c-420e-9f9a-552723df2201.png)

### Expected Behavior

как сделать чтобы предметы показывались слева?

### Actual Behavior

не знаю как исправить

**Comment by mezz** [comment]
Sorry JEI does not exist in 1.7.10.
If you have an issue with NEI, you can report here: https://github.com/Chicken-Bones/NotEnoughItems/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
