### ISSUE TITLE
[Bug]: Wrong version in mods.toml

### ISSUE THREAD

**Issue by MelanX** [mezz/JustEnoughItems#2767]
### Steps to Reproduce the Bug

Download JEI (e.g.) 9.5.3.143
Open with zip manager
Open mods.toml
See version 9.5.2.136
![image](https://user-images.githubusercontent.com/26039509/159338878-c75ff447-1284-4cae-825f-46b514b2c9e3.png)

### Expected Behavior

It should contain the correct version. Otherwise, I can't set the required version in my mods.toml correctly.

### Actual Behavior

A wrong version is stored in mods.toml.

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in JEI `9.5.3.148` and going forward. (Fixed by this commit: https://github.com/mezz/JustEnoughItems/commit/2bfe7a815be61756a3ecf6f275f2afbb777ad1ba)
Please let me know if you run into any more issues.
