### ISSUE TITLE
[Suggestion]: Add log entry for when player uses cheat mode to gain an item. Similar to /Give command does.

### ISSUE THREAD

**Issue by rmccarthy1504** [mezz/JustEnoughItems#2769]
### Suggestion

Same as this really:

https://github.com/mezz/JustEnoughItems/issues/728

Seems it used to be a feature, but it's no longer present in 1.16.5 (haven't tested other releases.

But would be super helpful to us server admins making sure everyone is playing fair.

Cheers,

ryan

**Comment by mezz** [comment]
Thanks for the report!
Please open a new issue using the "Bug" template and fill out the information there so that I can investigate this issue.
