### ISSUE TITLE
If you enable option to hide chat, you can't get items in cheat mode.

### ISSUE THREAD

**Issue by auboli77** [mezz/JustEnoughItems#277]
Using: 
Forge 12.16.1.1906
JEI 1.9-3.3.3.200

**Comment by Prospector** [comment]
Hmm, there's no real good way around this, basically JEI just does a /give command for you, but without chat you can't do commands. I mean JEI could enable chat for a quick second, but that sounds kinda dumb. Probably a wontfix

**Comment by mezz** [comment]
Thanks for the report!
That's very strange, I wonder why hiding the chat also disables all its functionality.
I'll have to look into it more, maybe Forge can do something.
I probably will not be able to fix this soon though.
