### ISSUE TITLE
[Other]: melons drops itself instead of slices

### ISSUE THREAD

**Issue by krjencik** [mezz/JustEnoughItems#2770]
### Other

I dont know where or who to tell the bug i have: when breaking a melon, i get melon instead of melon slices
I dont even know what mod is causing this...

**Comment by krjencik** [comment]
Also, i accidentally forked this whole repository - how can i delete it?

**Comment by mezz** [comment]
Sorry this is not caused by JEI, it doesn't change any blocks at all.
