### ISSUE TITLE
[Suggestion]: IRecipeTransferInfo can be create custom IRecipeTransferError

### ISSUE THREAD

**Issue by gisellevonbingen** [mezz/JustEnoughItems#2771]
### Suggestion

I hope transfer recipe can only when some conditions are met. (a.k.a. "Move Items")
And show "why can't transfer" as Tooltip

> In example, a machine can change operation mode,
> And each modes use different RecipeType.
> So, i trying BLOCK transfer recipe (a.k.a. "Move Items") when showing RecipeType and selected operation mode mismatched

IRecipeTransferInfo already can return 'whether can handle' though canHandle
But, It's return type is bool, just true or false
Can't show exactly cause

I know IRecipeTransferHandler can implement enough
But in same time, it mean implement 'transferRecipe' method myself

If possible, I would like to use the BasicRecipeTransferHandler provided by JEI as it is, and create only custom IRecipeTransferError.

**Comment by mezz** [comment]
Thanks for the suggestion! I have implemented this in JEI 9.5.4
