### ISSUE TITLE
[Bug]: 1.18.1 Client locks up when loading game with JEI

### ISSUE THREAD

**Issue by ozma6464** [mezz/JustEnoughItems#2774]
### Steps to Reproduce the Bug

Install latest JEI fpr 1.18.1
Same issue occurs whether both Server and Client has the mod installed, Client only has the Mod Installed, or server only has the mod installed.
No Crash Report is being generated

### Expected Behavior

Successful log in. World loads and can play the game.

### Actual Behavior

Screen freezes after the words "Joining World" displays. World never loads on the Client but the Server registers the Player Log in and even registers if a Mob kills the player, though none of it is seen on the Client due to the screen freeze.

Game Falls into a "Not Responding" state.

### Extra Notes (Optional)

MOD LIST:
blue_skies-1.18.1-1.3.4.jar                       |Blue Skies                    |blue_skies                    |1.3.4    
endportalrecipe_1.18.1-2.6.jar                    |End Portal Recipe             |endportalrecipe               |2.6     
AwesomeDungeonEnd-Forge-1.18.1-1.0.0.jar          |Awesome Dungeon End           |awesomedungeonend             |1.0.0    
Snad-1.18.1-1.21.12.11a.jar                       |Snad                          |snad                          |1.18.1-1.21.12.11a  
treeharvester_1.18.1-4.2.jar                      |Tree Harvester                |treeharvester                 |4.2                 
LibraryFerret-Forge-1.18.1-1.0.3.jar              |Library ferret                |libraryferret                 |1.0.3               
caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      
colytra-forge-1.18.1-5.2.0.0.jar                  |Colytra                       |colytra                       |1.18.1-5.2.0.0      
createchunkloading-0.4.0.jar                      |Create Chunkloading           |createchunkloading            |0.3.0               
waystones-forge-1.18.1-9.0.4.jar                  |Waystones                     |waystones                     |9.0.4             
awesomedungeon-2.0.5.jar                          |Awesome Dungeon               |awesomedungeon                |2.0.5             
TravelersBackpack-1.18.1-7.0.3.jar                |Traveler's Backpack           |travelersbackpack             |7.0.2            
upgradednetherite_items-1.18.1-3.1.0.2-release.jar|Upgraded Netherite : Items    |upgradednetherite_items       
sworddisplay-1.18.1-1.1.0.jar                     |Sword Displays                |sworddisplay                  |1.18.1-1.1.0    
PickUpNotifier-v3.1.0-1.18.1-Forge.jar            |Pick Up Notifier              |pickupnotifier                |3.1.0           
keepmysoiltilled_1.18.1-1.1.jar                   |Keep My Soil Tilled           |keepmysoiltilled              |1.1          
Corail-Spawners-1.18.1-020.jar                    |Corail Spawners               |corail_spawners               |1.18-020       
balm-2.4.3+0.jar                                  |Balm                          |balm                          |2.4.3+0    
thutessentials-1.18.1-4.4.1.jar                   |Thut Essentials               |thutessentials                |4.4.1    
cloth-config-6.2.57-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.57   
forge-1.18.1-39.0.66-universal.jar                |Forge                         |forge                         |39.0.66   
shetiphiancore-1.18-3.10.4.jar                    |ShetiPhian-Core               |shetiphiancore                |3.10.4    
createfa-1.18.1_v1.0.8.jar                        |CreateFoodAdditions           |createfa                      |1.0.8     
toofast-1.18-0.0.1.2.jar                          |Too Fast                      |toofast                       |0.0.1.2   
upgradednetherite-1.18.1-4.1.0.0-release.jar      |Upgraded Netherite            |upgradednetherite             
structure_gel-1.18.1-2.1.3.jar                    |Structure Gel API             |structure_gel                 |2.1.3     
DungeonsArise-1.18.1-2.1.49d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49d-1.18.1 
AwesomeDungeonOcean-Forge-1.18-2.0.4.jar          |Awesome Dungeon Ocean         |awesomedungeonocean           |2.0.4          
client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1         
Dynmap-3.4-beta-1.1-forge-1.18.jar                |Dynmap                        |dynmap                        |3.4-beta-1.1-755 
morevillagers-FORGE-1.18.1-3.1.2.jar              |More Villagers                |morevillagers                 |3.1.2           
endertanks-1.18-1.11.3.jar                        |EnderTanks                    |endertanks                    |1.11.3         
AwesomeDungeonNether-Forge-1.18.1-1.0.0.jar       |Awesome Dungeon Nether        |awesomedungeonnether          |1.0.0         
Chunky-1.2.154.jar                                |Chunky                        |chunky                        |1.2.154         
dimdungeons-1.13.4-forge-1.18.1.jar               |Dimensional Dungeons          |dimdungeons                   |1.13.4         
flywheel-forge-1.18-0.6.1.jar                     |Flywheel                      |flywheel                      |1.18-0.6.1.63    
alloyed-1.18.1-v1.2a.jar                          |Create: Alloyed               |alloyed                       |1.18.1        
create-mc1.18.1_v0.4e.jar                         |Create                        |create                        |0.4e          
createdeco-1.2.5-1.18.jar                         |Create Deco                   |createdeco                    |1.2.5-1.18     
curios-forge-1.18.1-5.0.6.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.2   
Patchouli-1.18.1-65.jar                           |Patchouli                     |patchouli                     |1.18.1-65        
collective-1.18.1-4.7.jar                         |Collective                    |collective                    |4.7             
enderchests-1.18-1.9.2.jar                        |EnderChests                   |enderchests                   |1.9.2          
InventoryHud_[1.18].forge-3.4.4.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.4          
worldedit-mod-7.2.9.jar                           |WorldEdit                     |worldedit                     |7.2.9+e20e013   
upgradedcore-1.18.1-3.1.0.0-release.jar           |Upgraded Core                 |upgradedcore                  
Project_MMO-1.18.1-3.69.9.jar                     |Project MMO                   |pmmo                          |1.18.1-3.69.9    
architectury-3.7.31.jar                           |Architectury                  |architectury                  |3.7.31           
ferritecore-4.1.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.1.2            
cc-tweaked-1.18.1-1.100.2.jar                     |CC: Tweaked                   |computercraft                 |1.100.2          
PuzzlesLib-v3.2.1-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.2.1             
The_Undergarden-1.18.1-0.6.3.jar                  |The Undergarden               |undergarden                   |0.6.3            
DynmapBlockScan-3.4-SNAPSHOT-forge-1.18(1).jar    |DynmapBlockScan               |dynmapblockscan               |3.4-SNAPSHOT-228  
geckolib-1.18-forge-3.0.11.jar                    |GeckoLib                      |geckolib3                     |3.0.11           
ars_nouveau-1.18.1-2.3.0.jar                      |Ars Nouveau                   |ars_nouveau                   |2.3.0            
ars_elemental-1.18.1-0.3.0.0.jar                  |Ars Elemental                 |ars_elemental                 |1.18.1-0.3.0.0    
ars_creo-1.18.1-1.0.0-BETA1.jar                   |Example Mod                   |ars_creo                      |1.0.0            
TradingPost-v3.1.2-1.18.1-Forge.jar               |Trading Post                  |tradingpost                   |3.1.2            
createaddition-1.18.1-20220125a.jar               |Create Crafts & Additions     |createaddition                |1.18.1-20220125a   	
jei-1.18.1-9.4.1.112.jar
OptiFine_1.18.1_HD_U_H5

### latest.log

https://gist.github.com/ozma6464/5a8f11512b7ed20e20470fc82f87afe0

**Comment by mezz** [comment]
Thanks for the report!

I think this is caused by a conflict with another mod. 
Please try removing mods to figure out which one is conflicting so that I can investigate and fix the issue.
OptiFine often causes problems with other mods, so try starting there.

**Comment by ozma6464** [comment]
I will do so. i have already thought about Optifine and already ruled it out. I will run tests and let you know

**Comment by ozma6464** [comment]
I am still running tests... im having to duplicate my server to perform the tests as i do not want to corrupt my running server..

**Comment by ozma6464** [comment]
Just to advise... this is the error code that populates:
Exit Code: 805306369
This exit code is caused when the client runs out of memory. This can be caused by the JVM not being allocated enough memory, a bug in the game, using client modifications or a dependency of the game that has unexpectedly terminated.

**Comment by ozma6464** [comment]
@mezz 
I have identified the Mod Conflict. 
JEI is not working with Project_MMO-1.18.1-3.69.9
https://www.curseforge.com/minecraft/mc-mods/project-mmo/files

**Comment by mezz** [comment]
Thanks!
I think this is happening because you are running out of memory, you need to allocate more memory to your Minecraft java instance.
Sometimes things will just slow down severely before Minecraft runs out of memory, so it would explain both of the issues you've seen here.

**Comment by ozma6464** [comment]
Well I'm already allocating 1M running and 8M max on the server.. and while running, it usually only runs at about 2M even when I'm logged in.
I'm not too sure if that is the full issue?
Could there be anything else?

**Comment by ozma6464** [comment]
Maybe some interaction between JEI and PMMO is causing a memory leak? though i dont see any spikes

**Comment by mezz** [comment]
JEI only runs on the client, what are the memory settings there?
Try increasing the amount and see if it improves or not, that will help diagnose the issue.

**Comment by ozma6464** [comment]
It doesnt need to be on the server? The descriptions say that there are features disabled when it is only client side

**Comment by mezz** [comment]
JEI is on the server but it does very little there, and doesn't load anything. 
In your case the client is freezing and probably running out of memory, and I think you can disregard the server here.

**Comment by ozma6464** [comment]
I increased my Client from 4M to 8M (-Xmx8192m -Xms1024m) and I got the same result. Once it gets past "Joining World" the client locked up again and then dropped into Not Responding.

![image](https://user-images.githubusercontent.com/100719833/160470825-347a3a40-877f-4178-bf87-7dc8576a53d3.png)
![image](https://user-images.githubusercontent.com/100719833/160470285-95ae9355-f862-468b-80a5-180b9d731ef4.png)
![image](https://user-images.githubusercontent.com/100719833/160470381-634a33e5-1445-46d3-ab17-d003d39bf85e.png)

**Comment by mezz** [comment]
What do you see in the log?

**Comment by ozma6464** [comment]
[latest.log](https://github.com/mezz/JustEnoughItems/files/8365645/latest.log)

Here is my log file

**Comment by ozma6464** [comment]
stops at loading ingredients

**Comment by mezz** [comment]
I created a new mod pack with just Project MMO `1.18.1-3.69.9` and JEI `1.18.1-9.4.1.168` and didn't run into any issues when starting a singleplayer world.
Can you try that out? Is there a specific situation where this happens that I can reproduce?

**Comment by ozma6464** [comment]
no specific situations, just simply installing the mod and trying to log in. Unless this is a conflict between multiple mods... which i dont have time to test for tonight. would will have to wait until later.

**Comment by ozma6464** [comment]
Just tested with your recent update. Still getting the same issue. Checked memory usage and im only using about 4M out of the 8M allocation.
Its going to take some time to identify the Mod combination causing this, if you have any advise or ideas when looking at my Mod list it would be appreciated

**Comment by mezz** [comment]
Narrowing down which mod is involved is definitely a chore, but you can make it go faster by trying to add or remove batches of mods at a time. If you go one at a time it can be very slow. 
Also keep in mind that testing a few mods at a time will always load much faster than starting with a full pack and removing some.
Unfortunately I don’t have any specific idea of where the issue is coming from, mods have deep interconnected interactions so the bug could be in almost any of them.

**Comment by ozma6464** [comment]
Well.. looks like my issue is not what I thought it was, I started the game and it fell into "not responding" again and then left it there. After about 5 minutes the game finally loaded. Looks like the issue isnt a Freeze but just an abnormally long time to load. 
IE:
10 seconds without PMMO
vs
5 minutes with PMMO

Any thoughts on what could cause this?

**Comment by mezz** [comment]
The most likely cause of slowness here is a mod that adds information to tooltips, but has a performance bug that makes it go slow. During this stage, JEI gathers metadata about all the items, including tooltips, and from past experiences I have found that it often exposes performance issues in mods. Usually the game just shows 1 tooltip at a time and you might get a slight FPS drop if the code is slow, but JEI grabbing 4000 of them in a row makes it much more noticeable.

If you can narrow down which mods are involved then I can help look into it further.

**Comment by ozma6464** [comment]
The only Mod that is causing the increased Load time is PMMO, My Game loads within seconds without it.

**Comment by ozma6464** [comment]
Ill see if i can find the Mod combination

**Comment by Elrol** [comment]
I am having the same issue. However when I go to a single player world it loads quickly. The only issue is when I am joining the server that has the mods. 

You mention that the issue is that a mod adds tooltips could be the cause. PMMO adds tooltips to any/all items that have a level requirement. Some have multiple requirements and can have different types of requirements. I am fairly certain that is the cause but I am wondering if there is a way around this issue.

**Comment by mezz** [comment]
As a workaround, you can disable searching tooltips in JEI's config. Then it will not index the tooltips at all, and it should load quickly.
