### ISSUE TITLE
[Crash]: Client login crash when joining Realm

### ISSUE THREAD

**Issue by taercy** [mezz/JustEnoughItems#2775]
### Steps to Reproduce the Crash

1. Open game, works normally
2. Open realms, join realm
3. Crash

### Mod Pack URL (Optional)

https://drive.google.com/file/d/1lqB413kXbAuqVkrIwJlLEvXiceryS-WB/view?usp=sharing

### Mod Pack Version (Optional)

0.0.1

### Extra Notes (Optional)

I threw this "modpack" together a few minutes ago, it's client-side forge-friendly mods only so it shouldn't be a Realms issue, and even if it was a "no mods" thing, it would just tell you and not crash the game. I think it is JEI because it seems to be crashing during JEI launch. Let me know if you need more details. 

### Crash Report

https://gist.github.com/taercy/fb8a49081aa49a3224ce8353f19e0ab1

**Comment by taercy** [comment]
Confirmed, disabled JEI and I can play normally, all other mods are active and working correctly

**Comment by mezz** [comment]
Thanks for the report!
I suspect another mod may be causing an issue for you but it's hard to tell.
Can you please get a crash log with just JEI and no other mods?

**Comment by taercy** [comment]
I gotchu homie.

Here's one with JER and JEI running, I thought you wrote JER because.. ykno.. you wrote this one? I guess? I can't read? I don't know. 

https://gist.github.com/taercy/81d28880924f0a7b45c1ecf7b25dad79

So I thought to myself, maybe I'll check the mod author to make sure. Funny enough, you didn't write that one. OK so maybe that's the culprit. No, still crashed. 

New only JEI run crash: 

https://gist.github.com/taercy/604c7f718430fede3b6a45c26755bf7b

One other note, I'm using MultiMC as a launcher, and it says "experimental forge version" (using 40.0.31) at the top of my screen, but it's the latest version from the site and I tried to find the distinction between the experimental and release versions to no avail. 

Like I said, the game launches to the main menu screen fine, the issue is on connection to server / realm. It crashes as soon as I start loading into the world.

**Comment by mezz** [comment]
Ah ok I see the issue now, thanks for the logs!.
You are using JEI for 1.18.1 but you have Forge for 1.18.2.
Try updating JEI to one of the latest versions, that support 1.18.2.

**Comment by mezz** [comment]
I am going to push a new release of JEI for 1.18.1 that will ensure it doesn't run on the "wrong" Forge version. It'll give a more descriptive error and should prevent this confusing problem from happening.
