### ISSUE TITLE
Allow hiding of recipe categories

### ISSUE THREAD

**Issue by artemisSystem** [mezz/JustEnoughItems#2776]
### Suggestion

It would be nice if it was possible to instead of just sorting recipe categories, you could remove/hide them entirely. For example, Create adds several recipe categories that just show vanilla recipes in a different form (shapeless mixing, compacting, automated shaped crafting, etc), that i would like to hide. One might also want to hide categories like the anvil, or maybe some added by JER or a similar mod.

**Comment by mezz** [comment]
Thanks for the suggestion!
This should be possible with CraftTweaker's JEI plugin. Have you tried it out?
https://docs.blamejared.com/1.12/en/Mods/JEI/JEI#hide-categories

**Comment by artemisSystem** [comment]
Ah, i see. I'm using KubeJS because i'm familiar with javascript and its syntax, but i didn't find an example for hiding a whole category on their wiki. Should i make a suggestion there instead, then? Switching to CT isn't really an option for me.

**Comment by mezz** [comment]
Ah, yes. I think that would be a good addition for KubeJS.
