### ISSUE TITLE
Jei closes in inventory after a few seconds

### ISSUE THREAD

**Issue by Theloserlad** [mezz/JustEnoughItems#278]
After just a few seconds of opening the inventory JEI closes suddenly and posts this to the console.

https://gist.github.com/mezz/47a8cb3629a6048a2b60388f8f1bdbe5

FULL client log : https://gist.githubusercontent.com/Theloserlad/2cfefb60c57fe39820c23c36a0ff8c0f/raw/64630914d80a4255510131ee437bb526f0ebdd96/Log.txt

**Comment by mezz** [comment]
Thanks for the report!
Those errors should not cause JEI to close. Can you paste the full client log to https://gist.github.com and link it here?

**Comment by Theloserlad** [comment]
Comment updated.

**Comment by mezz** [comment]
Hmm I don't see anything that might cause a problem in the log.
I don't have enough time to look deeply into it today, but I have two things you can try:
- Add JEI to the server too. It's needed for some functions, and there might be a bug when it's missing.
- Remove mods until it works, so we can find which other mod causes the problem. Maybe try with just JEI and add mods until it breaks?

**Comment by Theloserlad** [comment]
We figured it out!!! We have a mod on the client called BetterHUD and its a completely configurable hud mod, now theres a setting that shows connection info in ping. After rigorous testing and removing mods from the client we narrowed it down to better hud and now JEI doesent close anymore AFTER disableing the connection info from better hud.

**Comment by mezz** [comment]
Interesting, thanks for reporting back!

I have no idea why that would cause JEI to close, I haven't seen that happen before. 
Maybe they will have an idea? Try reporting to BetterHUD and linking back here.
