### ISSUE TITLE
[Bug]: 1.18.2 The mod's scroll list and things are not there. 

### ISSUE THREAD

**Issue by TheReallyP** [mezz/JustEnoughItems#2780]
### Steps to Reproduce the Bug

I downloaded the latest 1.18.2 file from forge. I drop it in the mods folder, and I save the changes. I open the launcher. I get on Minecraft, enter a world, and I open my inventory.

### Expected Behavior

I wanted to see my favorite item table on the right side of my inventory screen. It wasn't there, so I reloaded it, tried the toggle hotkeys in the controls, and checked all the other things which may make some feature of this mod work.

### Actual Behavior

Nothing works, mod doesn't load or enter existence. All features are missing when it is active.

### Extra Notes (Optional)

This is with the "jei- 1.18.2-9.5.4.171.jar" file on the page.

### latest.log

https://gist.github.com/TheReallyP/7301956c2552c398ebac809ed530c3bb

**Comment by TheReallyP** [comment]
Here is a picture of the problem.

![Minecraft_ 1 18 2 3_29_2022 6_23_49 AM](https://user-images.githubusercontent.com/99220890/160591836-6e6b870f-3e05-4ccb-933d-48083da60771.png)

**Comment by TheReallyP** [comment]
After the new update 9 minutes ago, I still got the missing jei issue. Here is the link to the new latest.log .
https://gist.github.com/TheReallyP/31a46fdfe8bb6a2f6f4e5466ecddd633

**Comment by mezz** [comment]
Thanks for the report!
Based on your log, it looks like some MCreator mod is crashing when JEI tries to ask if its item can be enchanted.
I'll make a new release that should help fix the issue and identify the item that is causing the problem.

**Comment by mezz** [comment]
Please try with JEI version `9.5.5.174`. It should work for you, but please paste the new log here so I can figure out which mod caused the problem so we can report it to them too.

**Comment by TheReallyP** [comment]
Thanks, the issue is fixed. Here is the new latest.log for 9.5.5.174 .
https://gist.github.com/TheReallyP/834b7f0a6dd95b87422a2e53892cdae5

**Comment by mezz** [comment]
Glad it works now. Thanks for reporting back. 
It looks like the original problem is caused by this issue: https://www.curseforge.com/minecraft/mc-mods/wastelands-of-baedoor/issues/17
