### ISSUE TITLE
[Suggestion]: mobile app

### ISSUE THREAD

**Issue by r3365** [mezz/JustEnoughItems#2781]
### Suggestion

I love jei, you guys are amazing! This is probably way out of scope, I thought it would be a great idea if you had a mobile app with the same functionality as per each mod pack.

Just by selecting the mod pack in a drop down you could change the pack and see the recipes.

I find myself thinking about certain machines when I'm meant to be working, but I can't get it out of my head.

I would pay $10-20 for this app. Especially if the app had bookmarks for when I'm back in front of my pc.

**Comment by mezz** [comment]
Thanks for the suggestion!
I agree this is a good idea, but unfortunately it is way out of scope.
I already work full-time so I do not really have the ability to take on a new side project of that size.
