### ISSUE TITLE
[Bug]: The items menu isn't showing

### ISSUE THREAD

**Issue by RomanMons** [mezz/JustEnoughItems#2784]
### Steps to Reproduce the Bug

Simply add the JEI mod in the minecraft mods folder, already containing other mods

### Expected Behavior

JEI should function normally even though there are other mods

### Actual Behavior

The recipes on the right on the screen simply aren't showing

### Mod Pack Version (Optional)

1.18.1

### Extra Notes (Optional)

With "jei-1.18.2-9.5.5.174.jar" and I even tried with "jei-1.18.1-9.4.1.172.jar" but it doesn't work

### latest.log

https://gist.github.com/DragonFire93/e1b6c5df10c858e5ae34d2155fb62d18#file-gistfile1-txt

**Comment by Ommina** [comment]
JEI is a Forge mod, and will not function in a Fabric environment.

**Comment by gonsior74** [comment]
> JEI is a Forge mod, and will not function in a Fabric environment.

It should be mentioned somewhere.

**Comment by mezz** [comment]
Thanks for the report!
JEI has a Fabric version now, it should be less confusing.
