### ISSUE TITLE
[Other]: Vivecraft simply doesn't work with JEI

### ISSUE THREAD

**Issue by akip1** [mezz/JustEnoughItems#2786]
### Other

I know this is probably pretty low priority but the menus just simply don't work with VR. JEI itself shows up, but you can't click on any items to show recipes/uses.

**Comment by mezz** [comment]
Thanks for the report!
I'm not sure how Vivecraft changes input handling. I think it would be worth asking them to weigh in. 
Please open an issue with them and link back to this one here.
