### ISSUE TITLE
it crash every time

### ISSUE THREAD

**Issue by AnasgamingCRAFT** [mezz/JustEnoughItems#2789]
### Steps to Reproduce the Crash

ir keep crashing

### Mod Pack Version (Optional)

1.18.2

### Crash Report

crash

**Comment by AnasgamingCRAFT** [comment]
crash

**Comment by ghost** [comment]
for me if i type into the search bar it just crashes

**Comment by mezz** [comment]
Please open a new crash report with a crash log, this does not have the information I need in order to solve the crash.
