### ISSUE TITLE
Crash when looking up a crusher recipe

### ISSUE THREAD

**Issue by MrTubzy456** [mezz/JustEnoughItems#279]
http://pastebin.com/Ka2vkzFU

**Comment by MrTubzy456** [comment]
version jei_1.9-3.3.3.200

**Comment by TehNut** [comment]
Bookshelf/Neotech error

**Comment by mezz** [comment]
Thanks for the report!
Please report to Neotech here, they should know what to do:
https://github.com/TeamBR-Modding/NeoTech/issues?q=is%3Aissue

**Comment by MrTubzy456** [comment]
Thanks for the link and getting to my issue so fast.

**Comment by mezz** [comment]
No problem. 
Linking here so the two issues are connected: https://github.com/TeamBR-Modding/NeoTech/issues/329

**Comment by pauljoda** [comment]
Sorry for the delay, fixed in next Bookshelf release
