### ISSUE TITLE
Recipes get listed twice when checking the uses of an ingredient that is also in the list of items to the left

### ISSUE THREAD

**Issue by jamesjimmy88** [mezz/JustEnoughItems#2790]
### Steps to Reproduce the Bug

1 Create a custom recipe that uses one of the items listed to the left of a category (for example, a smelting recipe that smelts a Furnace, a blasting recipe that smelts a Blast Furnace
2 Check the uses of the item (for the examples above, check the uses for a Furnace or a Blast Furnace)

### Expected Behavior

For the recipe to show up only once

### Actual Behavior

The recipe shows up twice.

I made a custom recipe to smelt a Blast Furnace inside another one to get a Nether Star, and this is what is shown after checking the uses of a Blast Furnace:
![blasting](https://user-images.githubusercontent.com/58559532/162627450-7effd5b3-7629-44cc-8cb8-fd3e6054cfe2.png)
As you can see, the recipe shows up twice. It's actually the same recipe, as shown by looking at the recipe names.

### Extra Notes (Optional)

This issue applies to every possible JEI category - I tried with vanilla recipes, modded recipes and CraftTweaker's custom JEI categories, and the issue will consistently show up in all of them if the requirements are met.

The issue does not appear when checking the recipes for outputs (in the examples above, checking the recipes for obtaining nether stars will have them show only once per involved category)

Tested with JEI version 10.0.0.188 on Forge 40.0.42 (1.18.2)

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next version, available shortly.
