### ISSUE TITLE
[Bug]: anything with fluids broken

### ISSUE THREAD

**Issue by freopt** [mezz/JustEnoughItems#2791]
### Steps to Reproduce the Bug

Start game, look for recipes with fluids

### Expected Behavior

The recipes show

### Actual Behavior

They don't show

### latest.log

https://gist.githubusercontent.com/freopt/7f1ae5b775f4f033d0022171aa0a5841/raw/6924958e1f04a17e1f4c7bbc6af1787805beb236/gistfile1.txt

**Comment by mezz** [comment]
Thanks for the report!
It looks like you are using JEI 10 which is an Alpha version.
Try using JEI 9 until mods update to the latest JEI version.

**Comment by JLCGaming** [comment]
I have a similar issue, but I'm using JEI 9

Tried 9.7.0.195 and 194

I've got tons of these in my log:
https://pastebin.com/qFqKGSD2

It only effects recipes that use a fluid, and it only happens when I join my server. Single player shows everything just fine.
