### ISSUE TITLE
[Bug]: JEI Alpha 10 searchbar locks keyboard

### ISSUE THREAD

**Issue by freopt** [mezz/JustEnoughItems#2792]
### Steps to Reproduce the Bug

Open JEI searchbar, try to exit

### Expected Behavior

You can unselect the searchbar by clicking out of it, or you can exit inventory screen by hitting ESC

### Actual Behavior

You can't do any of the above

**Comment by Peach774** [comment]
Im also having this problem - what other mods are you using?

**Comment by KhanhPham05** [comment]
Same for me, the only thing to solve is to toggle full screen off and then on again, using F11

**Comment by Peach774** [comment]
> 

What mods are you using - maybe we can figure out what mods we have in common and narrow down the conflict?

**Comment by freopt** [comment]
I don't why you're convinced it's a conflict and not just a bug in JEI

**Comment by KhanhPham05** [comment]
> > 
> 
> What mods are you using - maybe we can figure out what mods we have in common and narrow down the conflict?

Just JEI itself, and Configured

**Comment by KhanhPham05** [comment]
btw, the JEI version has not mentioned in the issue, it is the Alpha 10.0.191
@mezz

**Comment by mezz** [comment]
Thanks for the report!
JEI 10 Alpha is still a work-in-progress. Please use a Beta or Release version for now, I will try to fix this soon.

**Comment by mezz** [comment]
JEI 10 Alpha should be working much better now, can you confirm if this bug has been fixed for you?

**Comment by Peach774** [comment]
I'm no longer having this issue.

**Comment by mezz** [comment]
Great, thank you for confirming
