### ISSUE TITLE
[Crash]: Cant Launch server  with any if the 1.18.2 10.0.0 versions 

### ISSUE THREAD

**Issue by Daihok41** [mezz/JustEnoughItems#2793]
### Steps to Reproduce the Crash

For me its just start server it wont load

### Extra Notes (Optional)

Havent been able to launch any of the versions 1.18.2 10.0.0.184-191. I keep having to use  1.18.2-9.7.0.180 to launch on servers.

There is no crash reports for server but it wont launch. Soon as i put the .180 version back in it launchs fine.

I am playing with mods just not sure how to link you all the mods.

### Crash Report

there is no crash report

**Comment by mezz** [comment]
Thanks for the report!
Can you try with the latest 10.0 versions? It should work correctly now.
