### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Skyros199** [mezz/JustEnoughItems#2796]
### Steps to Reproduce the Crash

Launching

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/project-equivalence-2-covalence-unified

### Crash Report

https://gist.github.com/Skyros199/1467ea79f4430c71eb1a0945dcbbbf7b

**Comment by mezz** [comment]
Thanks for the report!
`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`
It looks like Java needs more memory, try giving it more in your settings.
