### ISSUE TITLE
[Crash]: World crashes on load when JEI is loaded at the same time as Inventory Profiles Nextr

### ISSUE THREAD

**Issue by BrandonKhoo** [mezz/JustEnoughItems#2798]
### Steps to Reproduce the Crash

1. Open Minecraft 1.18.2 with forge 1.18.2 with JEI 1.18.2 and IPN 1.18.2
2. load world
3. Crash happens
[crash-2022-04-16_16.16.41-client.txt](https://github.com/mezz/JustEnoughItems/files/8500738/crash-2022-04-16_16.16.41-client.txt)

### Extra Notes (Optional)

I have already talked to IPN support and have assured me it is handled in their code.
their assumption is that it is 1.18.2 specific

### Crash Report

https://gist.github.com/BrandonKhoo/b7edb1bbe004aeecb624fd43696191b8

**Comment by mezz** [comment]
Thanks for the report!
I see it was reported here, as you said: https://github.com/blackd/Inventory-Profiles/issues/130

It looks like you are using JEI for 1.18.1, please try updating JEI to a version for 1.18.2.
