### ISSUE TITLE
Gradle-wrapper.jar not included

### ISSUE THREAD

**Issue by BionicFelps** [mezz/JustEnoughItems#28]
And the build fails if I just go get one >.>

Seems to be missing dependencies from forestry I guess...

(was just being nosy as to how this is going, since NEI is failing pretty hard in a pack I'm making for fun... Obviously stability is optional)

**Comment by mezz** [comment]
You're probably just missing Forestry. Drop a dev version of Forestry in the libs folder and it should work. http://jenkins.ic2.player.to/job/Forestry_Dev/
JEI is pretty stable last time I checked, just light on features at the moment :).

Sorry if that doesn't fix your problem, I haven't touched this in a while. I'll leave the bug open.

**Comment by BionicFelps** [comment]
Can't get it to build (this is probably more to do with my lack of experience with gradle and not knowing exactly where to put it (the libs folder doesn't already exist in my download))

I basically know just enough to get it to build, although I know java and C and a bunch of others, just never really used gradle (or made minecraft mods in general)

**Comment by BionicFelps** [comment]
Oh... I should leave this up so you know to fix the files >.>

**Comment by mezz** [comment]
Thanks!

**Comment by mezz** [comment]
Fixed with the update to 1.8. Forestry support is temporarily removed

**Comment by mezz** [comment]
Oh and added Gradle-wrapper.jar recently, I missed that.
