### ISSUE TITLE
Command Block GUI Issue

### ISSUE THREAD

**Issue by crzyc** [mezz/JustEnoughItems#280]
This is a fairly minor bug in Minecraft 1.9 and using 3.3.3.200 of JEI. When opening the command block GUI, when I highlight everything (Ctrl+a) and use the mouse cursor to click out of the highlight multiple times, I find that I cannot hold the arrow keys and move the cursor (I have to spam the left or right arrow key). Again, this is a minor bug but I hope it gets fixed!

**Comment by mezz** [comment]
Thanks for the report!
As a workaround for now, you can open/close JEI by pressing Control-O. Having JEI closed should stop it from messing with the keys there.

**Comment by crzyc** [comment]
Unfortunately, even with doing Control-O, the bug is still there.

**Comment by Prospector** [comment]
Actually do you think this has to do with the ctrl keybind modifiers in 1.9 forge?

**Comment by crzyc** [comment]
This bug happens less frequently in versions before 3.2.9.184.

**Comment by mezz** [comment]
Fixed in version 3.4.1.
JEI was disabling the keyboard repeat when it detected that its search bar was deselected, which would happen when you clicked the Command Block gui. Now, it correctly understands that it's hidden and doesn't mess with the keyboard repeat function.
