### ISSUE TITLE
[Bug]: No item displayed in left panel 

### ISSUE THREAD

**Issue by SummerXXXX** [mezz/JustEnoughItems#2802]
### Steps to Reproduce the Bug

JEI works fine at the beginning, but now there is no item displayed in left panel. 

I am not sure if this is a bug or I click some button wrong.

minecraft 1.18.2
jei-1.18.2-9.7.0.193

No item displayed in left panel:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/10771754/164230717-3e342d9d-1935-497b-b0f1-67990b2a86ac.png">

### Expected Behavior

Show items that can be crafted

### Actual Behavior

Not sure

### latest.log

https://gist.github.com/SummerXXXX/7ee2671aee33bdff5552118387411ea8

**Comment by SummerXXXX** [comment]
problem fixed after update forge

**Comment by SummerXXXX** [comment]
problem happens again...

**Comment by mezz** [comment]
Thanks for the report!
Can you include a log with the new Forge, where you try to open a GUI and JEI doesn't display?

**Comment by SummerXXXX** [comment]
https://gist.github.com/SummerXXXX/95ae9a3e572107b85813442797914385

log is attached.

Also found that one or more restart of minecraft can fix the problem
