### ISSUE TITLE
I can’t use it

### ISSUE THREAD

**Issue by Le1sure** [mezz/JustEnoughItems#2803]
### Other

I can’t see my jei I try to use Ctrl+O, R, U but it’s doesn’t work
Maybe it has bug with another mod?

**Comment by mezz** [comment]
Please submit a bug report, filling out the template with more information so that I can help you find out what's wrong.
https://github.com/mezz/JustEnoughItems/issues/new?assignees=&labels=&template=bug.yml&title=%5BBug%5D%3A+

**Comment by Le1sure** [comment]
I know the problem it’s has bug with mod MrPineapple gun

mezz ***@***.***>于2022年4月25日 周一21:32写道：
