### ISSUE TITLE
[Crash]: World crashes somehow with JEI

### ISSUE THREAD

**Issue by Jukabofy** [mezz/JustEnoughItems#2804]
### Steps to Reproduce the Crash

1. Create a world
2. Walk randomly around the world
3. Somehow the tps stop and then you can't do anything
4. For some reason it doesn't leave a crash report just a special message of this mod at the end of the log

### Mod Pack URL (Optional)

I'm using a custom modpack

### Extra Notes (Optional)

one of the first problems seemed to have to do with empty jigasw systems
I opened other worlds to see if the same thing happened, and the same thing happened again
then try to remove the config
but the problem still persisted
I tried removing JEI and there was no problem
so I deduced that JEI is probocando something
in the log, it is seen in the last messages...
[21:42:09] [Render thread/INFO]: Stopping!
[21:42:09] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
[21:42:09] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[21:42:09] [Render thread/INFO]: Stopping JEI
Stopping JEI?, every TPS stop event was ending in the same way
*I'M UING THE LAST AND STABLE VERSION OF FORGE 1.18.2*

### Crash Report

https://gist.github.com/Jukabofy/892181ed442675791caa09878d5dd791

**Comment by Jukabofy** [comment]
It's a incompatibility maybe

**Comment by mezz** [comment]
Thanks for the report!
It looks like JEI is stopping because you are being logged out of the world, because it has stopped for some reason.
Unfortunately JEI is not the cause here, and the log doesn't seem to clearly show what is happening.
You will need to try removing some mods to see which one is causing the issue.

**Comment by Jukabofy** [comment]
Well...
I updated all my mods, and I have seen that Selene lib was having a lo of updates this days, so, I readded JEI, and now it seems to work again
Thanks for the answer ✔
