### ISSUE TITLE
[Crash]: Crash upon launching game, "Unsupported installed optional dependencies: jei"

### ISSUE THREAD

**Issue by Dankleberg** [mezz/JustEnoughItems#2805]
### Steps to Reproduce the Crash

1. Install mods from modlist (Custom modpack, see in Extra Notes)

2. Hit play in the Minecraft launcher

### Extra Notes (Optional)

[modlist.txt](https://github.com/mezz/JustEnoughItems/files/8536594/modlist.txt)

Game crashes before the loading window even appears, so I just have the latest.log as the crash report.  I think the line of note in there is line 145 "[main/ERROR]: Unsupported installed optional dependencies: jei".  This crash happens regardless of if I have Just Enough Resources or other similar extension mods added to get that out of the way as well.

### Crash Report

https://gist.github.com/Dankleberg/d0602d4fb40229465006b4bc6de871ae

**Comment by mezz** [comment]
Thanks for the report!
This error message is from Forge, and I think this is supposed to show an error screen.
Some mod you have installed depends on a specific version of JEI, but the one you have installed does not meet its requirements.
Unfortunately from this log file I am not able to determine which mod is involved, or what version of JEI it requires. Try updating JEI to the latest 9.x version, or try using an older version.

**Comment by Dankleberg** [comment]
I found out that the problem was the Domestication Innovation mod for some reason.  The mod doesn't have a dependency for this listed on CurseForge, and it's one required dependency (Citadel) works just fine with JEI, so it seems like it was just a screw-up in that mod.
