### ISSUE TITLE
[Crash]: NullPointerException: Cannot invoke "Object.getClass()" because "plugin" is null

### ISSUE THREAD

**Issue by steventopper** [mezz/JustEnoughItems#2806]
### Steps to Reproduce the Crash

1. In All the Mods 7, use JEI to view the uses of Raw Lead Ore.
2. Click on the tab to display uses of Raw Lead Ore in Mekanism's Combiner machine.
3. Crash.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-7

### Mod Pack Version (Optional)

v0.3.7

### Extra Notes (Optional)

This crash was very difficult to reproduce, but fortunately, the crash report is fairly self-explanatory:

If, in the [safeCallPlugin](https://github.com/mezz/JustEnoughItems/blob/efd8ef5bbf45e0c73c5d6285163fe5dc6f827323/Forge/src/main/java/mezz/jei/recipes/PluginManager.java#L105) method in PluginManager.java, the variable "plugin" is passed as null for any reason, the game will crash due to a NullPointerException on [line 115](https://github.com/mezz/JustEnoughItems/blob/efd8ef5bbf45e0c73c5d6285163fe5dc6f827323/Forge/src/main/java/mezz/jei/recipes/PluginManager.java#L115).

A simple solution to this would be a null check on "plugin" before methods are called on it, though if you're able to deduce the reason for "plugin" being passed as null, that may result in a more robust solution.

### Crash Report

https://gist.github.com/steventopper/bccf30021875619b3404f071282f1d56

**Comment by mezz** [comment]
Thanks for the report!
Strange, `plugin` should never be null here, it should not be possible because it's coming from a list that validates that all inputs are non-null.
Can you paste your client's latest.log here?

**Comment by steventopper** [comment]
Unfortunately, CurseForge seems to have deleted my latest.log files during a pack update, and I foolishly didn't think to save a separate copy. I'll continue playing the pack and try to reproduce the situation and send both files here. Will reopen once I'm successful.

**Comment by mezz** [comment]
Sounds good, thank you!
