### ISSUE TITLE
[Bug]: Can't select all text with CTRL + A

### ISSUE THREAD

**Issue by IllegalCharacter** [mezz/JustEnoughItems#2807]
### Steps to Reproduce the Bug

Experiencing this issue while playing TNP Limitless 5 on Minecraft 1.18.2, JEI version 9.7.0.180

Pressing CTRL + A in the textbox has no effect.

### Expected Behavior

The text should be selected

### Actual Behavior

The text isn't selected.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5

### Mod Pack Version (Optional)

2.2.0

### Extra Notes (Optional)

Tried the updated JEI 
jei-1.18.2-9.7.0.193.jar

Same issue persists

**Comment by atlgeek007** [comment]
I am also having this issue on forge 40.1.0 with the latest version from curseforge in a DIY modpack.

**Comment by mezz** [comment]
Thanks for the report!
This seems to be a mod conflict, when I test with JEI alone there is no issue.
Can you please narrow down your mod list to find out which mod is conflicting here?

**Comment by Xetaxheb** [comment]
Having issue on .194, can't ctrl+a or shift select, and perhaps unsurprisingly FTBLibrary (ftb-library-forge-1802.3.6-build.115.jar) is the culprit. Architectury (architectury-4.4.54) (ftblibrary requirement) alone doesn't cause the problem. 

Already mentioned here I guess: https://github.com/FTBTeam/FTB-Mods-Issues/issues/262

**Comment by Xetaxheb** [comment]
not stale, but probably ftb's fault so

**Comment by mezz** [comment]
This will be resolved by the upcoming FTB update, and also by an upcoming JEI update.
More detailed info about the bug can by found here: https://github.com/mezz/JustEnoughItems/issues/3009
