### ISSUE TITLE
[Bug]: JEI kinda just freezes and doesnt work when loaded together with inventorysorter

### ISSUE THREAD

**Issue by ihaveaskimask** [mezz/JustEnoughItems#2809]
### Steps to Reproduce the Bug

1. Move both JEI and [InventorySorter](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter) into mods folder 

2. Launch game

 

### Expected Behavior

JEI works just fine and so does InventorySorter

### Actual Behavior

InventorySorter works as intended but JEI freezes up and the gui doesnt do anything anymore

**Comment by ihaveaskimask** [comment]
i realize this is more of a compatibility issue than a bug but i wasnt too sure as to where exactly it should go so i put it here, sorry.

**Comment by mezz** [comment]
Thanks for the report!
Could you include your client's latest.log here so I can take a look?
