### ISSUE TITLE
[Other]: JEI not load at modmenu

### ISSUE THREAD

**Issue by UdinDesu** [mezz/JustEnoughItems#2811]
### Other

I use JEI 1.17.1 and the mod not loaded when my minecraft start
<img width="517" alt="1" src="https://user-images.githubusercontent.com/89616171/165865772-879e1b42-ea01-46f7-8885-8773f15cf31e.png">
<img width="635" alt="2" src="https://user-images.githubusercontent.com/89616171/165865795-27302632-15d5-484f-bbba-b06bab73c759.png">

**Comment by Ommina** [comment]
JEI is (at present) a Forge mod, and will not work in a Fabric environment.
