### ISSUE TITLE
[Suggestion]: Add a keybind for the key to exit a recipe screen to the inventory

### ISSUE THREAD

**Issue by Vazkii** [mezz/JustEnoughItems#2812]
### Suggestion

Currently to exit from a recipe viewer to the inventory, the only option is ESC, adding a separate keybind to duplicate the behaviour would allow it to be bound to a controller button with the Controllable mod

**Comment by mezz** [comment]
Thanks for the suggestion!
Added in `jei-1.18.2-9.7.0.194`
