### ISSUE TITLE
[Crash]: out of bounds when map a list

### ISSUE THREAD

**Issue by sukimiya** [mezz/JustEnoughItems#2813]
### Steps to Reproduce the Crash

1. open crafting table
2. move to copper ingot
3. press 'U'
4. flip 3 pages
[crash-2022-05-02_03.50.43-client.txt](https://github.com/mezz/JustEnoughItems/files/8599698/crash-2022-05-02_03.50.43-client.txt)

version: jei-1.18.2-9.7.0.194.jar

### Crash Report

sukimiya

**Comment by mezz** [comment]
Thanks for the report!
This bug should be fixed in the latest versions of JEI (by the change here: https://github.com/mezz/JustEnoughItems/commit/4f991ab7b552256c01009993454f4f9c76a46865)
