### ISSUE TITLE
[Bug]: Searching JEI by tags doesn't include block tags

### ISSUE THREAD

**Issue by Darinth** [mezz/JustEnoughItems#2814]
### Steps to Reproduce the Bug

Search for a block by tag use a block tag i.e. `$beacon` to try to find minecraft:beacon_base_blocks

### Expected Behavior

It pulls up a list of all blocks matching the tag

### Actual Behavior

It will pull up items that have tags matching the search (such as beacon_payment_items when you use `$beacon`) but does not find the blocks that match.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/magica-prime

### Mod Pack Version (Optional)

1.1.4

### Extra Notes (Optional)

I don't think that there's a mod interaction, but I acknowledge that it's a large modpack that I put together. If this is working on other 1.16.5 setups, I'll be happy to do some further testing. I am not on the most absolute recent version of the mod, but only 2 versions behind. Needless to say, I am the modpack author, happy to help where I can.

### latest.log

https://gist.github.com/Darinth/1b020acdd21b5c161da96b62237f32eb

**Comment by mezz** [comment]
Thanks for the suggestion!
This was completed in https://github.com/mezz/JustEnoughItems/issues/3320

**Comment by Darinth** [comment]
Awesome! Thank you! 👍
