### ISSUE TITLE
[Bug]: Jei isnt showing. jei 1.18.2-9.7.0.194.jar

### ISSUE THREAD

**Issue by drakosoldier298** [mezz/JustEnoughItems#2815]
### Steps to Reproduce the Bug

Install it and see there is no list of items on screen.

### Expected Behavior

When opening your inventory items would show on the right and you'd be able to click on them to see how they are made,

### Actual Behavior

When opening your inventory for some reason the only thing that shows is the search and gear, which isn't what would happen if I had hidden it, only the gear would show, 
![image](https://user-images.githubusercontent.com/30358222/166615657-cb9be9fb-c2db-484c-8e21-403c6e1156e3.png)

oddly seeing recipes through keybind still works.

### latest.log

https://gist.github.com/drakosoldier298/3ab23d8de434481d9bd8425b9d294645

**Comment by Xplodin** [comment]
you have rubidium extras.
its a feature of it

**Comment by mezz** [comment]
Thanks for the report!
Xplodin is right, there is a config option in that mod that leaves JEI blank when there is nothing written in the search box.

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
