### ISSUE TITLE
[Suggestion]: Recipe transfer helper extensions

### ISSUE THREAD

**Issue by yrsegal** [mezz/JustEnoughItems#2817]
### Suggestion

Currently, it's hard to write a custom recipe transfer helper because JEI uses a lot of internal information to do so.
The things that I would like exposed to the API to help with this (in `IRecipeTransferHandlerHelper`, most likely):

a way to create a `BasicRecipeTransferHandler` without registering it
a way to create a `BasicRecipeTransferInfo` without registering it
an exposing of `ServerInfo.isJeiOnServer()` to the API

This would allow me to make a PlayerRecipeTransferHandler for Quark's backpacks without needing to copy large swathes of JEI code and/or harddep on it.

**Comment by mezz** [comment]
Thanks for the suggestion!
This has been implemented in JEI 11.3.0
