### ISSUE TITLE
[Bug]: JEI item list doesn't fill whole height of the screen

### ISSUE THREAD

**Issue by Sunekaer** [mezz/JustEnoughItems#2818]
### Steps to Reproduce the Bug

The item list only covers about 2/3 of the screens height. This seems to be affected by GUI scale, using scales below 3 will reproduce this problem.

    Set GUI scale to a value below 3.
    Open inventory and see the item list is limited.
    Expected behaviour
    Should cover the full screen height on any GUI scale
    Screenshots
    https://i.imgur.com/ny0IMbq.png
    Additional info

### Expected Behavior

To file the screen height

### Actual Behavior

Video of issue: https://cdn.floatingmonkey.dev/screenshots/2022/05/07/1651926045_NVIDIA_Share.mp4

**Comment by JLCGaming** [comment]
As a temporary fix, if you have the configured mod, you can edit the config and change the # of rows to a higher number.

**Comment by mezz** [comment]
Thanks for the report!
This is configurable, it has been set to a lower value because many people ran into performance issues because they were rendering too many items at once. Lowering the number of rows and columns helps. You can set it to a high value like 1000 if you like.
