### ISSUE TITLE
[Bug]: JEI Only Showing Items Through Searches

### ISSUE THREAD

**Issue by SoCoolMuchGitHub** [mezz/JustEnoughItems#2819]
### Steps to Reproduce the Bug

I'm not quite sure actually. I just installed it and this was happening.

### Expected Behavior

Items should appear like normal when I open my inventory.

### Actual Behavior

When I open my inventory, it looks like this
![Screenshot 2022-05-07 174654](https://user-images.githubusercontent.com/59752651/167272690-8ca29c9e-5fc3-4b1a-995e-9c8c43547e42.png)
.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/trewgamerz-never-die-hardcore-modpack

### Mod Pack Version (Optional)

v2.4

### Extra Notes (Optional)

A workaround is if you just put an @ symbol in the search bar.

### latest.log

https://gist.github.com/SoCoolMuchGitHub/8a455766d9cbd10b9aa3ce25dd72e494

**Comment by govr017** [comment]
same issue

**Comment by Gbergz** [comment]
Hey, this is a feature added by the mod Rubidium/Magnesium Extras, which is in that modpack you mentioned. 
You can toggle it in the config.

**Comment by KaiserThompson** [comment]
> Hey, this is a feature added by the mod Rubidium/Magnesium Extras, which is in that modpack you mentioned. You can toggle it in the config.

Thank you for telling me, I found it in the config file but not the visual settings option on the menu. I couldn't find it anywhere on either the settings page or on their curseforge page saying they had that feature.

**Comment by SoCoolMuchGitHub** [comment]
> Hey, this is a feature added by the mod Rubidium/Magnesium Extras, which is in that modpack you mentioned. You can toggle it in the config.

Cool, thank you for letting me know. I knew linking the modpack would do me good.

**Comment by itsdinkd** [comment]
> Hey, this is a feature added by the mod Rubidium/Magnesium Extras, which is in that modpack you mentioned. You can toggle it in the config.

Wow.... and they really set it to default too.. that's annoying.

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
