### ISSUE TITLE
Allow for non-item/fluid ingredients to be queried in recipe and usage lookups

### ISSUE THREAD

**Issue by aidancbrady** [mezz/JustEnoughItems#282]
As discussed over IRC.  Something to allow resources other than FluidStacks and ItemStacks to be queried in recipe and usage searches.

**Comment by KnightMiner** [comment]
As someone who missed the IRC conversation, what are some example resources that are neither liquids or items? The only thing I can think of is power, but that is basically used in all machines from a mod.

**Comment by mezz** [comment]
Mekanism has Gasses that are not Fluids. 
Another example might be Thaumcraft Aspects.

**Comment by Prospector** [comment]
Also potentially energy. Having categories for energy generation and usage would be interesting.

**Comment by mezz** [comment]
Alright @aidancbrady this is in!
Check out `VanillaPlugin` and `JEIInternalPlugin` for examples of adding your own ingredients. It all starts with `IModIngredientRegistration`. Let me know if you have questions.

**Comment by Prospector** [comment]
Do you think energy should be using this? For example, RF, Tesla, or whatever? Or should it just stay off of JEI?

**Comment by mezz** [comment]
Go for it, I think the only way to find out if it makes sense is to give it a try. It may be difficult to convince everyone to add "energy" recipes for their engines and machines though.

**Comment by aidancbrady** [comment]
Thanks @mezz!

-Aidan
