### ISSUE TITLE
[Bug]: Cheat Item Grab doesn't work.

### ISSUE THREAD

**Issue by JacksonWoodsknight** [mezz/JustEnoughItems#2820]
### Steps to Reproduce the Bug

Just simply try to grab an item from JEI with cheat mode active.

### Expected Behavior

Should be able to grab the item in your cursor.

### Actual Behavior

Nothing happens at all. Even when the configs are set to work.

### Extra Notes (Optional)

Only way around this is to Shift+<1-9> but it always gives you the stack and it is too much of a hassle when you only want 1 of an item.

**Comment by lysz210** [comment]
@JacksonWoodsknight what minecraft version?
I have a similar issue in 1.18.2, for me it works after go back to play mode and re-enter in inventory.

**Comment by VallenFrostweaver** [comment]
Can veryify lysz210 is accurate with a temporary and awkward solution.

To further the issue, this is happening on 1.18.2 up to and including 1.19.2 but I am only experiencing it when trying to grab a stack in cheat mode and not a single item.

To add more to the issue, if you try to grab a stack after getting the above sequence to work, it will not allow you to drag that stack if you are still holding the shift key which in turn is also the case if you just hold shift longer than a split second when stack grabbing.
