### ISSUE TITLE
[Bug]: JEI search not working in parallel with another search bar

### ISSUE THREAD

**Issue by ocram9** [mezz/JustEnoughItems#2821]
### Steps to Reproduce the Bug

1. Open the creative inventory and go to search items (or any other mod that ads a search bar like Refined Storage)
2. Try and type something in the JEI search bar
3. Your search only shows up in the creative menu, not in JEI even though the typing indicator in JEI is blinking

### Expected Behavior

Being able to search in JEI while having another inventory with a search option open. This is especially noticeable when using Refined Storage and trying to type anything into JEI.

### Actual Behavior

The search meant for JEI shows up in another search bar even though the JEI search is selected.

### latest.log

https://gist.github.com/ocram9/80da422c65b204cb4267c701119bb605

**Comment by InsaneJ** [comment]
I'm having the same issue using jei-1.18.2-9.7.0.195 in FTB's Direwolf20 for MC 1.18.2 v1.0.0.
