### ISSUE TITLE
[Other]:  Hello ! My JEI gui appears somewhat.

### ISSUE THREAD

**Issue by andalusiandonkey** [mezz/JustEnoughItems#2823]
### Other

Hello! i have succesfully created a custom modpack for me and a few friends , JEI works properly and shows the search bar , however no interactible GUI. i can click items but they seem to be invisible unless i type something in the searchbar , its very weird.

Im using the latest version of JEI , alongside launcher 1.18.1 and curseforge also is in its latest version.

I suspect it might have to do with the origins mod ? since JEI is very sensitive when other mod starts at the start of the game , just wondering.

Thank you in advance !

**Comment by Ommina** [comment]
I'm _guessing_ this is also #2819, but without logs I can't really be sure.

**Comment by andalusiandonkey** [comment]
it was exactly that ! thank you so much!

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
