### ISSUE TITLE
[Other]: JEI not showing any items in modpack

### ISSUE THREAD

**Issue by axtrough** [mezz/JustEnoughItems#2824]
### Other

Yeah so just enough items are not showing any items. So here we have the modpack so you can try it out. But yeah i found out about the problem when i opened my inventory.
[hooyowa.zip](https://github.com/mezz/JustEnoughItems/files/8691009/hooyowa.zip)

**Comment by Ommina** [comment]
#2819

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
