### ISSUE TITLE
[Bug]: Slow performance persists even on 1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [mezz/JustEnoughItems#2826]
### Steps to Reproduce the Bug

1. Join a world

### Expected Behavior

Not to take too long

### Actual Behavior

Taking way longer than REI, about triple the time

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-3

### latest.log

https://gist.github.com/itsdinkd/7f617bbe0cf0f3def84573cbc725912d

**Comment by mezz** [comment]
Thanks for the report!
I see `Starting JEI took 24.06 s` in the log.
Is this matching what you are measuring?
