### ISSUE TITLE
[Bug]: Recipes not showing in multiplayer in 1.16.5

### ISSUE THREAD

**Issue by LaytoMax35** [mezz/JustEnoughItems#2828]
### Steps to Reproduce the Bug

Playing in a modded pack I made myself for 1.16.5, recipes are showing without any problem in singleplayer but are not showing at all in multiplayer, I have searched for problems like this one, but only answers were to delete Thermal Foundation and Mystical agriculture, which I did to no avail

### Expected Behavior

Jei should show the recipes in multiplayer

### Actual Behavior

Jei doesn't show the recipes in multiplayer

### Extra Notes (Optional)

Also tried to log in singleplayer first and then go to the server but that didn't work either

### latest.log

https://gist.github.com/LaytoMax35/a5370a3e58e418b491f57af4a1a3b85d

**Comment by mezz** [comment]
Thanks for the report!
This is probably caused by another mod that is breaking the recipe sync. If the recipe sync does not complete successfully, JEI will not know to start.
Please try narrowing down your mod list to see which mod is causing the issue.
