### ISSUE TITLE
[Suggestion]: could you maybe make a vertion for fabric please

### ISSUE THREAD

**Issue by ofri30** [mezz/JustEnoughItems#2829]
### Suggestion

most mods for newer versions of minecraft use fabric but jei doesnt could you make a fabric version of the mod please

**Comment by Sunconure11** [comment]
Before this gets trolled or something, I can direct you to a mod like this that is on Fabric.

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items

**Comment by hakanai** [comment]
Duplicate of #2747?

**Comment by mezz** [comment]
Making a Fabric version is a work-in-progress, https://github.com/mezz/JustEnoughItems/pull/2787

**Comment by mezz** [comment]
There is a fabric version now 🎉
