### ISSUE TITLE
[Bug]: In Japanese, tooltips hidden recipes

### ISSUE THREAD

**Issue by BoootMC** [mezz/JustEnoughItems#2830]
### Steps to Reproduce the Bug

On FEB Academy 1.16
Jei Version: jei-1.16.5-7.7.1.138

Mouse Hover [+] "Missing items in inventory." tooltips hidden recipe.
So I can't see what item is missing.

 
<img width="451" alt="image" src="https://user-images.githubusercontent.com/6838684/169825533-25f74810-bf38-441e-b68d-0e85abc8bd74.png">
<img width="394" alt="image" src="https://user-images.githubusercontent.com/6838684/169826692-ed9254cc-e9d8-4fdb-adb2-412d25122edc.png">

### Expected Behavior

I can see recipe!!

this is example, changing lang file from resource pack.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/6838684/169827388-69ff2f3c-f854-431d-bf96-7a18aa572b24.png">

### Actual Behavior

I can't see recipe for what is missing items.

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I can not control this behavior directly. If the tooltip is too large to fit, it will go to the left automatically.
Can you try using a smaller GUI size or increase the size of your screen?
