### ISSUE TITLE
[Bug]: JEI does nothing when installed

### ISSUE THREAD

**Issue by Xplodin** [mezz/JustEnoughItems#2831]
### Steps to Reproduce the Bug

load world

### Expected Behavior

jei to work when in singleplayer world

### Actual Behavior

R, and U keys do nothing and there is no search bar/item list

### Mod Pack URL (Optional)

custom

### Mod Pack Version (Optional)

custom

### Extra Notes (Optional)

I believe there is an error relating to recipe book
[latest.log](https://github.com/mezz/JustEnoughItems/files/8772671/latest.log)
gist.github is borked rn and uploading results in error pages

**Comment by mezz** [comment]
Thanks for the report!
I think another mod may be breaking the recipe sync packet. If the event from the packet doesn't fire, JEI will not know to start and it'll end up looking like this.
Please try narrowing down your mod list to see which mod is causing a problem.
