### ISSUE TITLE
[Bug]: game crash due to 'net.minecraft.util.ReportedException: Registering texture'

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2833]
### Steps to Reproduce the Bug

So this only happens ONLY when I use a test client in a mod creator called MCreator. It is very hard to explain how to get it to replicate exactly becuase i needed to do multiple different modifications to mcreator to be able to run 1.12.2. 

I have however attached a clip showing the exact issue 

https://user-images.githubusercontent.com/99213873/170531934-7309d6c6-786a-4109-82bb-06897d009ade.mp4

 

### Expected Behavior

It should normally boot minecraft up 

### Actual Behavior

It crashes my minecraft 

### latest.log

https://gist.github.com/SyntalDev/f8ac76698131cfc4907cffc8b9bddf97

**Comment by mezz** [comment]
Thanks for the report!
I think your development environment is not respecting the Access Transformers used by JEI.
Normally Forge will apply JEI's Access Transformers, which allow JEI to call some methods that are usually private.
It looks like for whatever reason, here the Access Transformers are not applied and it crashes.
Sorry I do not know more about why this is happening, I am not familiar with MCreator.

**Comment by ghost** [comment]
> 

Is there anyway to fix this issue?
