### ISSUE TITLE
[Crash]: On load the world 1.16.5

### ISSUE THREAD

**Issue by Luppyn** [mezz/JustEnoughItems#2837]
### Steps to Reproduce the Crash

Using my modpack on 1.16.5, any world you create, will crash.

### Mod Pack URL (Optional)

https://www.mediafire.com/file/27ih9ncp1z4s4a9/mods.7z/file

### Crash Report

https://gist.github.com/Luppyn/17e13fe0453c01363549349664ec47f2

**Comment by blessofsoraka** [comment]
Creating a new world works perfectly for me - using forge 36.2.35
![image](https://user-images.githubusercontent.com/107306869/173187802-ad1961f2-ade0-40eb-9c55-2f4ab67646ce.png)
-
![image](https://user-images.githubusercontent.com/107306869/173187866-cbfdd3bc-2340-481d-a727-19dd68bb83c3.png)

**Comment by mezz** [comment]
Thanks for the report!
This looks like an issue with Tinker's Construct, please try updating it and if you still have the same crash log, please report it to the mod author.
