### ISSUE TITLE
[Bug - 1.12.2]: Tooltip Search Doesn't Search Entire Tooltip

### ISSUE THREAD

**Issue by AlgebraManiacABC** [mezz/JustEnoughItems#2838]
### Steps to Reproduce the Bug

First, ensure "Tooltip search" is enabled or set to require prefix (#).
As shown below, simply search keywords from Tinkers' Construct tool pieces; I cannot search tool parts by their abilities.
![2022-05-31_21 45 57](https://user-images.githubusercontent.com/39248961/171317640-5af063e4-a885-4269-8f4d-0fde1fd505f4.png)
![2022-05-31_21 46 36](https://user-images.githubusercontent.com/39248961/171317651-4b05b011-8e8a-4ba9-8d48-fe83a761fd7d.png)
![2022-05-31_21 48 46](https://user-images.githubusercontent.com/39248961/171317810-79cce9b6-94de-4cb8-a237-28a6760b9ddc.png)
![2022-05-31_21 48 57](https://user-images.githubusercontent.com/39248961/171317811-b55a408b-270b-4d1f-95de-8574da05b72e.png)

Please note that this issue is not just occurring with TC:
![2022-05-31_21 50 38](https://user-images.githubusercontent.com/39248961/171318297-de271d9b-86a2-44d5-9484-790af52819f6.png)
![2022-05-31_21 50 50](https://user-images.githubusercontent.com/39248961/171318301-2e31229c-c74a-43a2-8fff-3dfaa72a1c9d.png)
![2022-05-31_21 51 02](https://user-images.githubusercontent.com/39248961/171318309-90533203-7c84-451d-9d6b-2a0b7edb0038.png)

As shown above, I cannot search the Range Addons by their Range (Industrial Foregoing).

### Expected Behavior

I expected that the tooltip search would search and find all "Lightweight" tool parts, and that I could find the range addon I want without hovering over each one (they are not in order).

### Actual Behavior

Shown in screenshots; doesn't appear.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/mc-eternal-lite

### Mod Pack Version (Optional)

1.3.8.1

**Comment by mezz** [comment]
Thanks for the report!
There is a JEI client config option to search advanced tooltips. It is off by default, because it uses more memory to store all that information in the search.
Can you try with that option enabled?
