### ISSUE TITLE
Moving items into crafting grid not showing up. (1.9.4)

### ISSUE THREAD

**Issue by hugeblank** [mezz/JustEnoughItems#284]
In the latest version of JEI, for 1.9.4, the little plus button isn't showing up for me :( Have a look:
![2016-05-21_14 53 04](https://cloud.githubusercontent.com/assets/16393543/15451012/4dad17d2-1f64-11e6-8f07-da1bc188b3f0.png)

Am I doing something horribly wrong, or is this a bug?

**Comment by mezz** [comment]
Thanks for the report!

It will only show up if:
- You have JEI on the server.
- You have a crafting inventory open that  can support it (like a crafting table)

Perhaps I should always have it there greyed out, with a message stating why? I thought doing that might be ugly but I'm having second thoughts because I really don't want to confuse people.

**Comment by Prospector** [comment]
What about a message at the top that only shows up the first time you open JEI on that world/server. Right under the 1/1 display "For full functionality, install JEI on the server"

Displaying a grayed out plus icon next to every recipe would look ugly imo

**Comment by TehNut** [comment]
IMO, add the grayed out button. There was a large discussion about consistency on this tracker (somewhere, can't find it currently). To users, the button not being there sometimes, but being there others can be very confusing. Adding the grayed out button keeps the button there are provides information when they want to know why they can't use it.

**Comment by Prospector** [comment]
That is true. Always having the button is nice, even if you're not in a bench that it can transfer to.

**Comment by mezz** [comment]
Makes sense to me. I'll keep the button there and look into ways to make it more informative and perhaps less ugly.

**Comment by Prospector** [comment]
what if the grayed out icon was lighter and with a softer border making it blend more, but still noticeable? Like the plus would be noticeable, but the background would blend in better

**Comment by hugeblank** [comment]
Ok, Thanks for the info, I don't have it on the server. Would it be at all possible to change that, and make it client side? That would fix wether or not to have the greyed out button or not! :P

**Comment by mezz** [comment]
Unfortunately, moving the items on client-side is extremely error-prone. You have to simulate the player clicking, and it can mess up easily with any lag.

**Comment by Prospector** [comment]
What if it could do a clientside thing like NEI had, with item overlays to show where the items were placed at in a crafting table

**Comment by mezz** [comment]
I really disliked that feature, it was hard to see what the items were. Consider it replaced with the "missing items" feature in JEI.
Just install JEI on the server if you want the feature. If your server doesn't have Forge then you're only dealing with vanilla recipes anyway, not like GregTech where you'd die without more advanced recipe handling.
Generally I don't want JEI to be a "cheat" thing anyway. If the server is vanilla and PVP or something I don't want to make crafting instantly all that easy.

**Comment by Prospector** [comment]
To be fair gregtech had its own in-game recipe viewer

**Comment by mezz** [comment]
This should now show an informative tooltip in JEI 3.8.0.
