### ISSUE TITLE
[Bug]: 1.16.5, Multiplayer, Vast Majority Of Recipes Not Showing Up On JEI (have tried other solutions available)

### ISSUE THREAD

**Issue by halfashilling** [mezz/JustEnoughItems#2840]
### Steps to Reproduce the Bug

Load up a custom modpack being used in this instance, vast majority of recipes, including crafting recipes, shaped and shapeless, other recipes from certain machines do not appear on the JEI registry, 
[latest.log](https://github.com/mezz/JustEnoughItems/files/8848596/latest.log) - This is the log from the server. 

[latest.log](https://github.com/mezz/JustEnoughItems/files/8848607/latest.log) This is the log from the single player instance. 

### Expected Behavior

All recipes should appear, but the vast majority do not.

### Actual Behavior

Vast majority of recipes do not, including crafting, shapeless, many create recipes, and assorted recipes from machines. Makes most items unknown and the pack unplayable.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/the-corner-pack

### Mod Pack Version (Optional)

Only one for the time being. 

### Extra Notes (Optional)

I have done all other options availible when simply google searching the issue, including removing the thermal suite and all dependencies, knocking these mods down a version, removing materialis, none of these measures have worked and im a little lost. 
Thank you very much in advance for the help. 

### latest.log

https://gist.github.com/halfashilling/4485dd3fcec724209731a9d5369127c7

**Comment by SharkWipf** [comment]
Seems like this happens with the latest version (1.5.0) of the Direwolf20 1.18 modpack as well.  
Single-player all recipes load fine, but multiplayer, the vast majority of recipes is missing.
Possibly unrelated, but it also takes a long time to open the inventory the first time.

Specifically, it seems like all standard shapeless and shaped recipes are missing, but special procedures still work.
Interestingly a handful of regular crafting recipes do still work, like Advanced Peripherals.

EDIT: This seems to be a dupe of #2832

**Comment by mezz** [comment]
Thanks for the report!
What you see here is JEI is desperately trying to continue working even though the recipe sync from the server was broken.
Unfortunately without the recipe sync it doesn't have much to work with so it looks pretty broken.

The right strategy here is to try to find what other mod might be involved, it looks like an older version of Oreberries broke the recipe sync packet and caused #2832. It may be the came mod causing the issue here, or another mod might have a similar issue.

**Comment by SharkWipf** [comment]
Yep, I confirmed it was Oreberries Replanted 1.6 for this specific issue, updating to Oreberries Replanted 1.7 fixed it.  
If possible, it may be a good idea to visually display an error to the client that indicates it's another mod's problem, to prevent reports like this from showing up unneccesarily.
