### ISSUE TITLE
[Bug]: Bookmarking duplicates main JEI menu

### ISSUE THREAD

**Issue by twitch0001** [mezz/JustEnoughItems#2841]
### Steps to Reproduce the Bug

1. Use Bookmark button to bookmark an item
2. See that menu on the left is a duplicate of the right/main JEI menu
(Video: https://i.imgur.com/gdB3CqX.gif)

### Expected Behavior

Bookmarking an item should add it to a list appearing by default on the left, not duplicate the main JEI menu

### Actual Behavior

Main JEI menu is duplicated
Video: https://i.imgur.com/gdB3CqX.gif

### Extra Notes (Optional)

Version: jei-1.18.2-forge-10.0.0.191.jar

### latest.log

https://gist.github.com/twitch0001/bad53ff0dfa97d9b84cad2435820081b

**Comment by mezz** [comment]
Thanks for the report!
I think this has been fixed, can you try out the latest version?

**Comment by twitch0001** [comment]
Apologies for the late reply! Just tested the latest version and all works now
Thank you very much :)
