### ISSUE TITLE
[Suggestion]: Port to 1.19

### ISSUE THREAD

**Issue by gohkenytp** [mezz/JustEnoughItems#2843]
### Suggestion

Please port this mod to 1.19? It just released already and is growing strong.

**Comment by gohkenytp** [comment]
I'm just letting you know that 1.19 is released, so anyone can port it with great pleasure.

**Comment by MichaelHillcox** [comment]
Don't do this, we know new versions of MC has released, this is easly the most annoying thing players do

**Comment by chibbi** [comment]
is a port in progess/planned?
and is it even a "port" ?
