### ISSUE TITLE
[Crash]: Rendering ingredient

### ISSUE THREAD

**Issue by Ondras4620** [mezz/JustEnoughItems#2845]
### Steps to Reproduce the Crash

1.start game
2.open jei(inv.)
3.have mouse in middle
4.scroll
5.at some page crash occurs

### Extra Notes (Optional)

i cant use jei i think with this but i had the crash just sometimes i think most issues is with silent-gear and Magnesium jei just shows them and i think creative tab would crash too.. let me know what to do or if you can fix it or where should i report thanks.

### Crash Report

https://gist.github.com/Ondras4620/70cefe4fb109f4ae21c4243609ac655d

**Comment by mezz** [comment]
Thanks for the report!
Please report these render crashes to the mod author of the item. I think they will still crash in the creative inventory, try scrolling there and then hopefully you can give the author a crash log where JEI is not involved so they can easily see the problem.
