### ISSUE TITLE
[1.18.2 Bug]: Items not rendering in JEI

### ISSUE THREAD

**Issue by vizthex123** [mezz/JustEnoughItems#2846]
### Steps to Reproduce the Bug

1) Installed the latest beta (9.7.0.196)
2) Load the game
3) Items do not render (pic attached)
![image](https://user-images.githubusercontent.com/31721920/173212588-cfee740f-1db3-4486-b231-0ee774899885.png)

### Expected Behavior

Items would render in JEI

### Actual Behavior

They don't render.

### Extra Notes (Optional)

This is for a custom modpack, and I had to use the beta since Solar Cooker wants me to use it.

Downgrading to the latest release version does not fix the issue.

### latest.log

https://gist.github.com/vizthex123/d084f9d69cdda07ee38d7d1b0781df27

**Comment by vizthex123** [comment]
Update: I found that this was an issue with Rubidium Extras, gonna close the report. Sorry for the false issue.

**Comment by TheFurryDevil** [comment]
It's a feature, Rubidium Extras has a config option, which is by default enabled, which hides JEI unless you search for something.

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26

**Comment by vizthex123** [comment]
noice, thanks
