### ISSUE TITLE
[Bug]: Custom furnace recipes couse JEI to fail to load

### ISSUE THREAD

**Issue by EnderiumSmith** [mezz/JustEnoughItems#2847]
### Steps to Reproduce the Bug

Install a mod that adds custom furnace recipes, for example to make it account for nbt data

### Expected Behavior

JEI should load

### Actual Behavior

java.lang.IllegalArgumentException: minecraft:furnace recipes must be an instance of class net.minecraft.world.item.crafting.SmeltingRecipe. Instead got: class charcoalPit.recipe.AlloySmeltRecipe

The recipe extends AbstractCookingRecipe so JEI crashes when it tries to cast it. Since the furnace works just fine with it and that class seems the sensible thing to extend JEI should work with it too.

### Extra Notes (Optional)

the custom recipe: https://github.com/EnderiumSmith/CharcoalPit3/blob/master/src/main/java/charcoalPit/recipe/AlloySmeltRecipe.java

**Comment by mezz** [comment]
Thanks for the report!
Can you please include the crash log?

**Comment by EnderiumSmith** [comment]
the game doesnt crash. just JEI doesnt start. the invalid casting type seems pretty self explanatory.

**Comment by mezz** [comment]
Can you include the full stack trace for the exception that is raised?
