### ISSUE TITLE
[Suggestion]: Allow registration of IRecipeTransferHandler using MenuType in addition to the class of the menu

### ISSUE THREAD

**Issue by McJty** [mezz/JustEnoughItems#2850]
### Suggestion

It would be great if it was possible to also register recipe transfer handlers though the unique MenuType thas has to be registered for every menu. This would allow mods to be able to share the same menu class for different menus while still having different recipe transfer handlers

**Comment by mezz** [comment]
Thanks for the suggestion!
This has been implemented in JEI for 1.19
