### ISSUE TITLE
[Crash]: 10.1.0.200 Throwing exceptions

### ISSUE THREAD

**Issue by Moobien** [mezz/JustEnoughItems#2851]
### Steps to Reproduce the Crash

Loaded up my world and had an instant crash.  Logs indicate JEI crash relating to fluids.

### Crash Report

https://gist.github.com/Moobien/63c99b1099b79629aca32e48e040f0dc

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next release, available shortly.

**Comment by Moobien** [comment]
No worries Mezz, glad I could help
