### ISSUE TITLE
[Bug]: 1.19 VanillaTypes.FLUID missing

### ISSUE THREAD

**Issue by JaisDK** [mezz/JustEnoughItems#2853]
### Steps to Reproduce the Bug

In version 11.0.0.203 VanillaTypes.FLUID is no longer present, what are we supposed to replace it with?

### Expected Behavior

VanillaTypes.FLUID to exist

### Actual Behavior

VanillaTypes.FLUID does not exist in version 11+

**Comment by Peca21** [comment]
I just wanted to report some other bug and I opened latest log to paste it and realized it had 47MB of 
java.lang.NoSuchFieldError: FLUID
This creates massive log spams

**Comment by Peca21** [comment]
Code says use {@link ForgeTypes#FLUID_STACK}

**Comment by JaisDK** [comment]
thanks
