### ISSUE TITLE
[Bug]: meez why yoe disable cheat mode from jei I need this.

### ISSUE THREAD

**Issue by MrAmHamoham** [mezz/JustEnoughItems#2856]
### Steps to Reproduce the Bug

1 i can't get cheat mode

### Expected Behavior

I can't use cheat mode

### Actual Behavior

Just i can't enable cheat mode

**Comment by mezz** [comment]
Hey, cheat mode should work.
What am I supposed to do with this information?

**Comment by mezz** [comment]
Please write a better bug report so I can help, I wrote the template to make it easier for you to give me the information I need in order to solve bugs.
