### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Disconnected7K** [mezz/JustEnoughItems#2857]
### Steps to Reproduce the Crash

Game crash over "getfluidtype"

### Extra Notes (Optional)

Hello, I seen an answer for this already so this is kinda a dumb question but I get this error message when I start my game and instantly crash after load to main screen

"The game crashed whilst rendering overlay
Error: java.lang.RuntimeException: Mod fluids must override getFluidType.
Slutkod: -1" 

(nevermind the "slutkod" that's just my language set on my own. slutkod=endcode)

I did see the fix here --> https://github.com/mezz/JustEnoughItems/issues/2853

But I'm actually do dumb to know where to put the {@link ForgeTypes#FLUID_STACK} if that is the fix.

I tried finding where to put it or if I'm completly lost on what to do with that then I could use a lil guide so I can be on my way

### Crash Report

https://gist.github.com/Disconnected7K/0e671c9331d8faf9a895cb73d3b3760b

**Comment by mezz** [comment]
Thanks for the report!
It looks like this crash is from another mod interacting badly with the latest Forge version. 
JEI is not in this stack trace, so I think it is not actually involved in this particular crash.
Please try removing mods to see which one may be causing the problem.
