### ISSUE TITLE
JEI Not loading

### ISSUE THREAD

**Issue by ThePickle04** [mezz/JustEnoughItems#2863]
### Steps to Reproduce the Bug

When loading up, I get the followung error message;

Mod jei requires forge 41.0.28 or above
		Currently, forge is 41.0.5

I have Forge 41.0.5 installed

Anyone know of a fix?

### Expected Behavior

JEI should load up and allow me to connect to my server

### Actual Behavior

Minecraft doesnt load into the main menu, meaning I am unable to play with JEI enabled

**Comment by mezz** [comment]
Thanks for the report!
`41.0.5` is a lower version than `41.0.28`
The message is saying that you need to install Forge `41.0.28` or a higher version.
