### ISSUE TITLE
[Bug]: Slow mouse movement in any gui with Jei installed

### ISSUE THREAD

**Issue by scarletwolf134** [mezz/JustEnoughItems#2865]
### Steps to Reproduce the Bug

??? I recently updated to 1.18.2 from 1.12.2, I actually have less mods now which makes the slowness even more confusing and frustrating! 

### Expected Behavior

No weird mouse/button interaction slowness

### Actual Behavior

It's odd as it's not lagging. My fps stays at 55 even as my mouse creeps across my guis like it's at 2... picking up items also is affected by the slowness and strangely enough even when I'm not in a world my menu guis are lagging!? (psa before anyone says it's because I have too many mods the issue is persisting when jei is the only mod I have loaded and my mc having 13g of my memory)

### Extra Notes (Optional)

The issue dropped once randomly then came back to stay with no way to be rid of it other then getting rid of jei which isn't an option as it'd become hell trying to play with some of my mods

### latest.log

https://gist.github.com/scarletwolf134/2b2632f571e900782431a8953286b2b6

**Comment by scarletwolf134** [comment]
Hey I've fixed it it was a resolution issue with jei! Setting your fullscreen mode to Current causes the issue but if you correct it to your screens resolution the mouse jumping goes away.

**Comment by scarletwolf134** [comment]
Never mind it still happens everytime I tab out and back in

**Comment by mezz** [comment]
Thanks for the report!
Hmm that's super weird.
It looks like you gave me a server log, can you send the client log instead?

**Comment by scarletwolf134** [comment]
wait no

**Comment by scarletwolf134** [comment]
I didn't mean to close the issue it was an accident it's still very much happening and hasn't stopped. How do I get my client logs? I don't know where they are in the files.
