### ISSUE TITLE
[Bug]: 1.18.2 half-size

### ISSUE THREAD

**Issue by arzadu** [mezz/JustEnoughItems#2866]
### Steps to Reproduce the Bug

Appears to be a GUI sizing issue? JEI's items only take up the top half of the usual space, making the overall pages of items double.

### Expected Behavior

JEI item display will use all of the space from the top of the screen to the searchbar (when open adjacent to an inventory).

### Actual Behavior

Items only display in the top half of the area, creating far more pages than necessary (vanilla items taking up 11 pages, for example). 

### Extra Notes (Optional)

It's not a huge issue (the mod works as intended), but I can't figure out what's causing it and it's mildly annoying
![2022-06-24_11 01 58](https://user-images.githubusercontent.com/97483584/175563049-f6567a04-10b0-4f26-8400-a639942c4717.png)
.

**Comment by mezz** [comment]
Thanks for the report!
This size is configurable, you can change it in JEI's config file.
I made the default size 9 columns wide because many people were having performance issues from rendering so many items. You can set it to a huge number if you want JEI to just take up as much space as possible.

**Comment by Ethyl238** [comment]
> Thanks for the report! This size is configurable, you can change it in JEI's config file. I made the default size 9 columns wide because many people were having performance issues from rendering so many items. You can set it to a huge number if you want JEI to just take up as much space as possible.


I can't find how to open config file.

**Comment by mezz** [comment]
Sorry for the late reply.
All config files are in your modded minecraft folder, the one you're looking for should be `config/jei/jei-client.ini`
