### ISSUE TITLE
[Bug]: 1.16.5 JEI Recipes do not work in multiplayer

### ISSUE THREAD

**Issue by Juicysteak117** [mezz/JustEnoughItems#2868]
### Steps to Reproduce the Bug

With a freshly installed FTB University modpack on a multiplayer server without any modifications, attempt the following:

1. Attempt to craft wooden planks from logs
2. Attempt to open up the recipe for anything involving the crafting table.

The issue does not persist in singleplayer.

### Expected Behavior

1. The planks will be shown in the output square.
2. The recipe will be shown.

### Actual Behavior

1. The output square is empty (but can still be crafted).
2. The recipe is not shown.

### Mod Pack URL (Optional)

FTB University

### Mod Pack Version (Optional)

1.6.1

### Extra Notes (Optional)

Like I mentioned, it's a fresh install. Just made the server today along with downloading the modpack. My friend and I have spent a while scouring other issues, the logs, and the internet to no avail. Seems like potentially a mod conflict since I understand an issue with the sync ruins the whole thing, but I can't figure out which.

The client latest.log is linked below, the server latest.log can be found here as well: https://gist.github.com/Juicysteak117/d2459d73925dac5872d6228185823669

### latest.log

https://gist.github.com/Juicysteak117/8d95f3584ebfa11125b7a4ee2c80241c

**Comment by Juicysteak117** [comment]
Update: Downgrading the modpack version to 1.5 appears to fix the issue, but with all the mods that got changed I truly have no idea where the conflict is.

**Comment by mezz** [comment]
Thanks for the report!

I took a look at the client log and found this:
```
[24Jun2022 16:06:47.333] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft: 
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_192575_l(PacketBuffer.java:366) ~[?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_218772_c(SourceFile:52) ~[?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148837_a(SourceFile:35) ~[?:?]
	at net.minecraftforge.network.VanillaPacketSplitter.onClientPacket(VanillaPacketSplitter.java:178) ~[forge:?]
...
```

It looks like some mod is breaking the recipe sync packet. I am not sure which mod is causing this issue, but it will prevent JEI from working correctly in multiplayer. You can try removing mods to find which one is causing the problem.

**Comment by Juicysteak117** [comment]
Right! Forgot I posted this. I spoke with the modpack creator and they were able to determine the issue was caused by Blood Magic, so updating that mod solved it. I don't know if it's possible to throw out a notice to users that one of their mods is breaking the recipes (determining the exact mod itself seems difficult though), but it might save other people from as much of a headache.

**Comment by mezz** [comment]
Glad you were able to resolve the issue!
I have added a warning for when the recipe packet is broken in 1.18+, but unfortunately there isn't a good way to identify which mod is causing the problem.
