### ISSUE TITLE
[Crash]: Installing on my Forge server crashes on startup

### ISSUE THREAD

**Issue by wbatzle** [mezz/JustEnoughItems#2869]
### Steps to Reproduce the Crash

I just installed this on my forge server which is fully up to date. I downloaded the file that was released about 10hrs ago from the time of this issue post. I will attach logs if I can find one listing the crash. I checked current logs I have but I don't see anything with any great detail. If I remove JEI it starts

### Crash Report

https://gist.github.com/wbatzle/a8d79a7a2626241e97c1ffcd1759161c

**Comment by mezz** [comment]
Thanks for the report!

```
[25Jun2022 10:10:58.118] [main/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod �ejei�r requires �6forge�r �o41.0.28 or above�r
�7Currently, �6forge�r�7 is �o41.0.5
```

It looks like this version of JEI requires Forge 41.0.28 or higher, and you are using an older version of Forge (41.0.5)
