### ISSUE TITLE
[Bug]: [1.18.2]Don't show item in inventory's interface.

### ISSUE THREAD

**Issue by Greygreygod** [mezz/JustEnoughItems#2870]
### Steps to Reproduce the Bug

If i install rubidium(version 0.5.2a) with JEI(version 9.7.0.xxx),item will disappear in inventory's interface if i don't use serch.

### Expected Behavior

If i install the JEI and the version 10.1.0.208,item shows  normally,but it cause another problem that tinkerconstruct3's smelting recipe will disappear.

### Actual Behavior

Don't show item in inventory's interface.

**Comment by ghost** [comment]
Not a JEI bug.

This is due to rubidium extra's choice to intentionally hide items unless you search.

Change it in the config and close this.

**Comment by mezz** [comment]
Thanks for the report!
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
