### ISSUE TITLE
[Bug]: IIngredientFilter#setFilterText doesn't update text field

### ISSUE THREAD

**Issue by raoulvdberge** [mezz/JustEnoughItems#2871]
### Steps to Reproduce the Bug

1. Open Refined Storage Grid
2. Enable JEI synchronization mode (one way)
3. Notice that the filter is being updated, but the text field isn't.

### Expected Behavior

The text field should be updated with the new search query as well.

### Actual Behavior

The text field isn't updated, but the underlying filter is updated.

### Extra Notes (Optional)

JEI 11.0.0.206

You can try this with RS 2.

- https://github.com/refinedmods/refinedstorage2/blob/develop/refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/screen/grid/GridScreen.java#L129
- https://github.com/refinedmods/refinedstorage2/blob/develop/refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/screen/grid/GridScreen.java#L134
- https://github.com/refinedmods/refinedstorage2/blob/develop/refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/integration/jei/JeiGridSynchronizer.java#L28
- https://github.com/refinedmods/refinedstorage2/blob/develop/refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/integration/jei/JeiProxy.java#L9

Get an artifact for 1.19 here:
https://github.com/refinedmods/refinedstorage2/actions/runs/2550893231

1.18.2: https://github.com/refinedmods/refinedstorage2/releases/tag/v2.0.0-milestone.1.4

The bug can apperantly also be reproduced with RS1: https://github.com/refinedmods/refinedstorage/issues/3293

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version for 1.19. I will work on backporting it to 1.18 as well.
