### ISSUE TITLE
[Bug]: Ghost ingredient handler doesn't reset when opening another recipe

### ISSUE THREAD

**Issue by raoulvdberge** [mezz/JustEnoughItems#2872]
### Steps to Reproduce the Bug

1. Open a GUI that has a ghost recipe transfer handler with targets.
2. Start dragging an ingredient
3. Click on another ingredient in the ingredient list while the drag is active, ensure that the ingredient list doesn't shuffle.
4. Targets are still rendered and drag is still active.

Result:
![image](https://user-images.githubusercontent.com/10358424/175823293-aebc56a9-5da5-40ca-b611-f937e79655ba.png)

### Expected Behavior

Drag should no longer be active after opening a recipe.

### Actual Behavior

Drag stays active.

### Extra Notes (Optional)

Tested with RS 2 

**Only reproduceable on Fabric with JEI 11.0.0.206**

**Comment by raoulvdberge** [comment]
As an addendum, I'm also noticing that if there is a recipe for a given ingredient, it opens the recipe viewer immediately when I just wanted to drag, leading to the same result (screenshot). Also only on Fabric.

**Comment by mezz** [comment]
Thanks for reporting!
Along with https://github.com/mezz/JustEnoughItems/issues/2873, this issue has also been fixed by https://github.com/mezz/JustEnoughItems/commit/b6813e7b3a70606841b8fdb6a80252a92e5c8fac
