### ISSUE TITLE
[Bug]: Missing recipes while "Crafting Table" is set to hidden in JEI (1.16.5)

### ISSUE THREAD

**Issue by AscensionVibe** [mezz/JustEnoughItems#2876]
### Steps to Reproduce the Bug

1. Open up your inventory
2. Enable Hide/Edit Mode
3. Hide the Vanilla "Crafting Table"
4. Turn off Hide/Edit Mode
5. You can no longer see any recipes when clicking on a certain item

### Expected Behavior

Following the steps to reproduce the bug, JEI should still be able to show me all the recipes

### Actual Behavior

Nothing happens; it's as if the feature would be completely disabled

### latest.log

https://gist.github.com/AscensionVibe/82bf43e8c163c5bf65bb632031f9ce12

**Comment by delveticas** [comment]
thank you so much i fixed the issue thanks to you, i just deleted the config file
