### ISSUE TITLE
[Other]: rendering problem jei 1.12.2

### ISSUE THREAD

**Issue by mellern04** [mezz/JustEnoughItems#2878]
### Other

![2022-07-07_14 05 59](https://user-images.githubusercontent.com/51051415/177771703-aff0b913-d63e-442f-9593-eb31a61bc673.png)
![2022-07-07_14 01 28](https://user-images.githubusercontent.com/51051415/177771707-1260c20d-3890-4c2c-8c83-fbf4d012abca.png)
[latest.log](https://github.com/mezz/JustEnoughItems/files/9063447/latest.log)

**Comment by mezz** [comment]
Thanks for the report!
I think this issue is coming from Pixelmon, can you report it to them?
