### ISSUE TITLE
JEI crashing world when most recent Bookshelf API is used. JEI module 'moreoverlays'

### ISSUE THREAD

**Issue by Gunner76th** [mezz/JustEnoughItems#288]
Thank you for reporting!

Please do not suggest features from NEI that are not about recipes, JEI is a recipe viewer. [NotEnoughWidgets](https://github.com/TheCBProject/NotEnoughWidgets) will have those features.

If there is an issue:
- It may already be fixed, please try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files).
- If JEI crashed, please paste the crash log to [gist](https://gist.github.com/) and link it in this issue.

Due to an update in the latest Bookshelf API, JEI is crashing if version 251 of Bookshelf is being used. Version 250 works with no issues. as per iLexiconn's information ( https://github.com/Darkhax-Minecraft/Bookshelf/issues/35 ), this bug report is being passed over to JEI as the cause for the crash. Original crash report is here: http://pastebin.com/t3Lp3aNw

**Comment by mezz** [comment]
JEI does not use BookShelf. This crash originates from `darkhax.darkutils.items.ItemBlockCake`. [Please report to DarkUtils here.](https://github.com/Darkhax-Minecraft/Dark-Utilities/issues?q=is%3Aopen+is%3Aissue) Sorry for the runaround @Gunner76th !

**Comment by Gunner76th** [comment]
I am aware that JEI does not use Bookshelf. However their mod was updated recently to a newer version, and JEI has not received any updates in the last 6 days since it's initial release to 1.9.4 As a result, iLexiconn is showing JEI as being the cause for the crash as in its current state it is not compatible with his update.

This issue has already been initially reported to Bookshelf's Github (as it is Bookshelf and not Dark Utilities causing the crash) as noted in the original post for this issue. https://github.com/Darkhax-Minecraft/Bookshelf/issues/35

If Bookshelf version 250 is used against your version of JEI (and the only version listed for 1.9.4) then the client has not problems. If Bookshelf 251 is used against your version of JEI (again, the only version for 1.9.4) the client crashes stating that JEI cannot start. 

Also, as per ILexiconn's investigation, "It's the JEI module 'moreoverlays' causing the crash, not JEI itself."

**Comment by mezz** [comment]
Replied in the other thread so you don't have to play telephone.
