### ISSUE TITLE
[Bug]: Double Instance of JEI Causing issues and crashing

### ISSUE THREAD

**Issue by onspeed8** [mezz/JustEnoughItems#2880]
### Steps to Reproduce the Bug

Im using the jei-1.19-fabric-11.0.0.206 version

In my inventory i believe there is 2 JEI's layered overtop eachother.
What i mean by this is that:
- if i switch to tab 2 i can still see the items of tab one but items of tab 2 are Clipping/Zfighting inside of them.
- hovering over the settings button and activating cheat mode shows the standard "JEI config" hovertext AND another "JEI config" hovertext but with the cheats are enabled subtext.

Finally if:
1. Im in creative Mode
2. JEI cheat mode is enabled

the game crashes on clicking an item

### Expected Behavior

Only one instance of JEI

### Actual Behavior

2 Instances

### Extra Notes (Optional)

I will admit i am using a big bunch of other mods and there is a possibility of a confict, but this bug was so outlandishly weird i figured i'd report it in case there is some sort of logical explanation that i'm missing.

If this issue needs to be removed/closed due to the fact I'm running (a lot of) other mods that's fine.

### latest.log

https://gist.github.com/onspeed8/2cfafb1cf253520132e62d2eb4469cc3

**Comment by onspeed8** [comment]
updated 3 mods today:
Architectury
Biomemakover
McDungeonsArmor
= Problem was fixed.

Downgraded the mods again
= Problem was back

I'll close the issue since it's resolved now

**Comment by onspeed8** [comment]
Yeah nevermind my previous comment, it just happened again. At first there was 1 instance, now there's 2 again..

**Comment by onspeed8** [comment]
Diving a little deeper i got some data:
-Restarting Minecraft Resets the amount of JEI windows back to 1
-Recovering from a crash trough NotEnoughCrashes (not crashing the game but going back to the main menu) does NOT reset the amount of JEI windows
-The "Generation" of a new JEI instance seems to happen on the click event (grabbing an item in cheat mode). I closely monitored the opacity of the top bar to see when a new instance layered atop the other. I couldn't see a 2nd instance until after i've crashed and returned to the world in my last test.
-Crashes only happen in creative
-Creating another JEI instance only happens in creative
-"Succesfully" picking up an item causes it to immidiatly be trown on the floor unless you hold the mousebutton

Further Data to follow once i find out more

**Comment by mezz** [comment]
Thanks for the report!
Hmm from your logs it looks like JEI is starting and stopping like 20 times.
I'm not sure why, can you try removing some mods from your pack to see if there is a conflict from another mod?
