### ISSUE TITLE
[Crash]: Issue rendering item.

### ISSUE THREAD

**Issue by inf31** [mezz/JustEnoughItems#2884]
### Steps to Reproduce the Crash

1. Install JEI for 1.16.5, Immersive Railroading for 1.16.5 & and its dependencies.
2. Open your inventory and search for "ir" in the JEI menu.
3. Game crashed.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/automation-nation

### Mod Pack Version (Optional)

Newest. I can't check because curseforge is down for me.

### Extra Notes (Optional)

I wasn't sure if I was supposed to post it here, or on the Immersive Railroading discord server.
I've tried downgrading JEI for no avail.
This probably also happens for other search results, though, I haven't tested any others yet.

### Crash Report

https://gist.github.com/inf31/369e482acb5b03610e649b8fd72688ff

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Mod Name: Immersive Railroading
	Registry Name: immersiverailroading:item_rail
	Display Name: Track Blueprint
	String Name: 1 item_rail
```
This does look like an issue from immersive railroading, can you please report it to them?
