### ISSUE TITLE
[Bug]: Crash on Launch (Forge, 1.19)

### ISSUE THREAD

**Issue by ESatrom** [mezz/JustEnoughItems#2887]
### Steps to Reproduce the Bug

Crashed on launch with JEI as only installed mod (Forge 1.19-41.0.94, JEI 1.19-forge-11.0.0.206)

Settings used were identical to settings I use for vanilla, and work with an empty forge install

JVM Args: -Xmx4G -Xms2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

JDK 17.0.2, shouldn't be an issue?

Using dir separate from .minecraft, forge installed on both .minecraft and this dir.

[Crash report log](https://github.com/mezz/JustEnoughItems/files/9093436/crash-2022-07-12_08.32.46-client.txt)

I believe this is everything I am able to supply. Windows 10 machine running an i5 and 16gig ram, new 3 years ago or so

I figure I've given everything that could possibly be helpful and then some, so hopefully it helps. Not a super big concern, thanks for the work you're putting in for the community!

### Expected Behavior

Minecraft crashed upon launch, it should not do this, but rather reach the main menu

### Actual Behavior

Minecraft crashed before reaching the main menu

### latest.log

https://github.com/mezz/JustEnoughItems/files/9093494/latest.log

**Comment by mezz** [comment]
Thanks for the report!
I think the crash comes from changes in Forge: `ClassNotFoundException: net.minecraftforge.client.model.data.IModelData`
Please try updating JEI and Forge to the latest versions available.

**Comment by ESatrom** [comment]
Thanks! Looks like I had a slightly outdated version of JEI.
