### ISSUE TITLE
[Suggestion]: Adding a new Info tab

### ISSUE THREAD

**Issue by chrisgates301** [mezz/JustEnoughItems#2889]
### Suggestion: Adding a new Info tab

It would be great if you can add an option to also view a little info about the block or item, just like there is R for recipes and U for uses, there could be I for info, info that can be useful for the player but the only way to learn it is by going into the wiki, for example, in the Gold Ore item, you could say that it's easier to find it in a Badlands biome, just an example. If you decide to do this, i can give you an entire list with each block or item that i consider needs info, plus the actual content of that info. Thanks in advance for taking your time to read this, and congratulations for creating such a great mod!

**Comment by mezz** [comment]
Thanks for the suggestion!
Info recipes are already part of JEI, you can look them up with R or U and the info will show up.
This can be easily added by an addon mod for JEI, there is an API method to create these info recipes.
