### ISSUE TITLE
Unable to use JEI Cheat's (Unable to spawn items, buttons greyed out)

### ISSUE THREAD

**Issue by nekomaster** [mezz/JustEnoughItems#289]
I started using Minecraf 1.8.9 yesterday and decided to set up my own personal modpack, and I'm having an issue with JEI that I had with Not Enough items in the past... except I can't figure out how to fix it.

I'm using Forge 1.8.9 - 1902 with JEI version "jei_1.8.9-2.28.18.186.jar" on Windows 10 (x64)

My problem is that the buttons for changing player game mode, setting the time of day, healing, etc are all greyed out and cannot be clicked on, and I can't spawn items at all... even though JEI is set to "Cheat Mode". The same goes for Utility mode, buttons greyed out and disabled. Clicking on items only brings up their recipe (or usage if I right click).

Heres what I've tried so far to no avail.
- Swtiching JEI modes (Cheat Mode, Utility Mode, Recipe Mode)
- Switching Minecraft Gamemodes between Creative and Survival
- Messing around with the options (Enable Item Cheating mode does nothing)
- Deleted the Config files for JEI, JEI Addon, Forever Enough Items.
- Redoing minecraft modpack

I haven't tried minecraft with just JEI yet, but Just Enough Items did work before with all the mods I have and then suddenly stopped working after I made a couple of minecraft worlds. 

Also, running my world on a Forge Server didn't solve anything either, I still have greyed out disabled buttons, even if I op myself on the server.

I have no idea whats going on anymore and why things just stopped working...

If any extra information or logs are needed, just let me know.

**Comment by KnightMiner** [comment]
The various utility buttons are not a JEI feature. As for the item cheating, try reproducing the issue with just JEI, then add more mods until you can find the conflicting mod

**Comment by mezz** [comment]
Thanks for the report!
JEI does not have those butons, modes, or issues, I assume Forever Enough Items adds them. 
You should report this to them here: https://github.com/elix-x/Forever-Enough-Items/issues
In the meantime you should try without FEI, it seems to be pretty buggy still.
