### ISSUE TITLE
[Crash]: Pressing the "go back a recipe" keybind too many times crashes on 1.18.2

### ISSUE THREAD

**Issue by kd8lvt** [mezz/JustEnoughItems#2890]
### Steps to Reproduce the Crash

1. Look through a couple recipes. If it matters, I was using the recipe keybind (default R) - not clicking.
2. Press the "go back a recipe" (default Backspace) more times than recipes you looked at

### Extra Notes (Optional)

Quick Version List:
Forge: 40.1.60
JEI: 1.18.2-5.8.5-forge
JER: 1.18.2-0.14.1.171

### Crash Report

https://gist.github.com/kd8lvt/98aaf250a0593ed28a2f32f5998c3442

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix for this crash, it was coming from a broken recipe transfer handler.
Now JEI should log the error instead of crashing completely.
