### ISSUE TITLE
[Bug]: Fluid recipes from mods break in latest version

### ISSUE THREAD

**Issue by meelock** [mezz/JustEnoughItems#2892]
### Steps to Reproduce the Bug

Recipes that use fluids no longer show up when I update to either of the latest two versions, but reappear when I backdate to jei-1.18.2-9.7.0.209. 

### Expected Behavior

Expected fluids to show up in recipes as normal in a minor bugfix update, fluid recipes seem to have broken while fixing #2890, or maybe something else caused them to break.

### Actual Behavior

Tinkers construct recipes and several other mods' machine recipes disappear when JEI is updated.
[14Jul2022 01:19:37.557] [Render thread/ERROR] [mezz.jei.common.util.IngredientSupplierHelper/]: Found a broken recipe, failed to set Ingredients: org.cyclops.evilcraftcompat.modcompat.jei.bloodinfuser.BloodInfuserRecipeJEI@6434713

java.lang.NoSuchFieldError: FLUID

### Extra Notes (Optional)

Gist kicked me out, so used google drive instead.
07/08/2022  04:59 PM           806,652 advancedperipherals-1.18.2-0.7.15b.jar
07/09/2022  12:03 AM           206,336 AdvancementPlaques-1.18.2-1.4.5.1.jar
07/13/2022  07:49 PM           873,536 advgenerators-1.1.0.6-mc1.18.2.jar
07/08/2022  02:44 PM            29,374 AI-Improvements-1.18.2-0.5.0.jar
07/08/2022  03:57 PM            42,265 AkashicTome-1.5-20.jar
07/08/2022  02:51 PM            29,126 alexsdelight-1.18.2-1.2.3.jar
07/08/2022  02:45 PM        22,436,427 alexsmobs-1.18.6.jar
07/12/2022  07:29 PM           441,924 alloyed-1.18.2-v1.4b.jar
07/10/2022  07:42 PM            53,413 alternate-current-mc1.18-1.2.1.jar
07/10/2022  07:33 PM           149,022 antighost-1.18.1-forge39.0.9-1.1.2.jar
07/08/2022  02:45 PM         1,007,363 Apotheosis-1.18.2-5.3.6.jar
07/08/2022  02:37 PM            46,235 appleskin-forge-mc1.18-2.4.0.jar
07/08/2022  02:43 PM         4,843,503 appliedenergistics2-11.1.4.jar
07/09/2022  12:02 AM        18,194,204 Aquamirae 3.2.0 (Forge 1.18.2).jar
07/08/2022  04:55 PM           211,125 archers_paradox-1.18.2-1.6.1.6.jar
07/08/2022  02:46 PM           531,208 architectury-4.5.76-forge.jar
07/12/2022  07:28 PM            29,933 ars_creo-1.18.2-1.0.5.jar
07/11/2022  08:22 PM         4,424,216 ars_nouveau-1.18.2-2.6.5.jar
07/09/2022  12:04 AM           129,495 art_of_forging-1.4.8-1.18.2.jar
07/08/2022  09:19 PM            20,394 AttributeFix-Forge-1.18.2-14.0.2.jar
07/08/2022  02:37 PM            42,733 AutoRegLib-1.7-53.jar
07/08/2022  02:43 PM           616,070 balm-3.1.0+0.jar
07/08/2022  03:48 PM         1,255,404 bdlib-1.19.3.7-mc1.18.2.jar
07/10/2022  07:34 PM            30,891 BeeFix-1.18-1.0.6.jar
07/08/2022  02:48 PM            71,020 BetterAdvancements-1.18.2-0.2.1.132.jar
07/09/2022  09:13 PM        21,244,934 BiomesOPlenty-1.18.2-16.0.0.134.jar
07/08/2022  03:47 PM           178,407 Blood-Smeltery-1.18.2-1.1.4.jar
07/09/2022  09:11 PM        10,583,874 BloodMagic-1.18.2-3.2.3-38.jar
07/08/2022  02:50 PM           918,452 blueprint-1.18.2-5.4.0.jar
07/08/2022  09:27 PM        82,794,983 blue_skies-1.18.2-1.3.12.jar
07/08/2022  02:53 PM           116,715 boneequipment-forge-1.18.2-v1.0.1.jar
07/11/2022  04:57 PM           285,156 Bookshelf-Forge-1.18.2-13.2.37.jar
07/08/2022  02:43 PM        11,283,865 Botania-1.18.2-434.jar
07/08/2022  09:19 PM           895,205 buildinggadgets-3.13.0-build.5+mc1.18.2.jar
07/09/2022  12:05 AM            37,157 caelus-forge-1.18.1-3.0.0.2.jar
07/08/2022  02:47 PM         1,904,293 cc-tweaked-1.18.2-1.100.8.jar
07/13/2022  07:49 PM         1,988,310 ChiselsBits-forge-1.18.2-1.2.113-universal.jar
07/08/2022  02:44 PM           503,137 citadel-1.11.3-1.18.2.jar
07/10/2022  07:38 PM             5,801 cleancut-mc1.18.2-4.0-forge.jar
07/08/2022  02:49 PM           121,455 clienttweaks-forge-1.18.1-7.1.0.jar
07/08/2022  03:46 PM         1,133,101 cloth-config-6.2.62-forge.jar
07/08/2022  02:48 PM            10,334 Clumps-forge-1.18.2-8.0.0+10.jar
07/08/2022  02:49 PM           868,487 CodeChickenLib-1.18.2-4.1.1.462-universal.jar
07/08/2022  02:43 PM         1,379,250 cofh_core-1.18.2-1.6.4.21.jar
07/08/2022  05:07 PM           225,123 ColossalChests-1.18.2-1.8.3.jar
07/08/2022  02:43 PM           225,164 comforts-forge-1.18.2-5.0.0.4.jar
07/08/2022  02:50 PM           243,173 CommonCapabilities-1.18.2-2.8.2.jar
07/08/2022  03:48 PM           125,794 compacter-1.6.0.2-mc1.18.2.jar
07/08/2022  02:50 PM           545,444 compactmachines-4.3.0.jar
07/09/2022  09:11 PM         1,650,475 Compat-O-Plenty-1.18.2-1.5.2.jar
07/08/2022  04:58 PM           200,187 constructionwand-1.18.2-2.7.jar
07/08/2022  02:37 PM           116,376 Controlling-forge-1.18.2-9.0+21.jar
07/08/2022  02:43 PM           656,573 cookingforblockheads-forge-1.18.2-12.0.2.jar
07/08/2022  02:53 PM           226,720 Copperized-1.18.2-2.2.jar
07/08/2022  02:51 PM           159,729 corn_delight-1.0.4-1.18.2.jar
07/08/2022  09:19 PM            88,360 CosmeticArmorReworked-1.18.2-v2.jar
07/08/2022  02:49 PM           178,181 craftingtweaks-forge-1.18.2-14.0.3.jar
07/08/2022  02:55 PM         2,312,846 create-confectionery1.18.2_v1.0.8.jar
07/08/2022  02:55 PM           315,340 create-factory-1.18.2-v1.6.jar
07/12/2022  07:29 PM        14,509,736 create-mc1.18.2_v0.5.0c.jar
07/08/2022  11:49 PM           630,197 create-stuff-additions1.18.2_v1.1.7.jar
07/11/2022  07:08 PM           812,971 createaddition-1.18.2-20220712a.jar
07/12/2022  07:29 PM           138,502 createbb-1.18.2-1.4.1.jar
07/08/2022  02:55 PM           218,749 createcafe-1.4-1.18.2.jar
07/09/2022  09:06 PM         2,715,456 createdeco-1.2.8-1.18.2.jar
07/08/2022  04:59 PM           161,053 creeperoverhaul-1.18.2-1.3.0-forge.jar
07/08/2022  02:51 PM           280,529 culturaldelights-1.18.2-0.11.jar
07/08/2022  02:43 PM           270,867 curios-forge-1.18.2-5.0.7.1.jar
07/09/2022  03:53 AM            32,640 CuriosQuarkOBP-1.18.2-1.1.4.jar
07/08/2022  02:50 PM           860,603 CyclopsCore-1.18.2-1.15.1.jar
07/08/2022  09:19 PM           164,318 DarkUtilities-Forge-1.18.2-10.0.5.jar
07/08/2022  02:44 PM           467,722 Decorative Blocks-forge-1.18.2-2.1.0.jar
07/08/2022  03:50 PM           786,095 deepresonance-3.0.10.jar
07/09/2022  09:11 PM           177,420 Delightful-1.18.2-1.7.jar
07/08/2022  02:40 PM            10,458 Ding-1.18-1.3.0.jar
07/08/2022  03:45 PM            17,172 DrawersTooltip-1.18.2-forge-5.0.0.jar
07/08/2022  03:49 PM           185,669 elevatorid-1.18.2-1.8.4.jar
07/08/2022  02:45 PM            60,289 EnchantmentDescriptions-Forge-1.18.2-10.0.5.jar
07/08/2022  02:59 PM           224,689 enderchests-1.18-1.9.5.jar
07/08/2022  02:59 PM           255,783 endertanks-1.18-1.11.7.jar
07/09/2022  12:05 AM         7,018,774 EnigmaticLegacy-2.24.1.jar
07/08/2022  03:02 PM         4,092,764 Enlightened End BB V1.5.jar
07/08/2022  04:55 PM           126,734 ensorcellation-1.18.2-1.6.1.8.jar
07/09/2022  09:11 PM         3,132,303 EvilCraft-1.18.2-1.2.3.jar
07/08/2022  02:44 PM         2,579,873 FarmersDelight-1.18.2-1.1.2.jar
07/08/2022  03:21 PM           398,220 FarmersRespite-1.18.2-1.3.0.jar
07/08/2022  03:21 PM           546,951 farmingforblockheads-forge-1.18.2-10.0.2.jar
07/08/2022  09:20 PM             5,459 FastFurnace-1.18.2-6.0.3.jar
07/08/2022  02:43 PM             8,873 FastLeafDecay-28.jar
07/10/2022  07:43 PM            11,185 FastSuite-1.18.2-3.0.2.jar
07/08/2022  03:49 PM            22,921 FastWorkbench-1.18.2-6.0.2.jar
07/08/2022  02:45 PM            14,792 feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
07/12/2022  07:29 PM         1,286,923 flywheel-forge-1.18-0.6.4.jar
07/08/2022  11:40 PM            78,714 ftb-essentials-1802.1.7-build.42.jar
07/08/2022  11:40 PM           575,881 ftb-library-forge-1802.3.6-build.123.jar
07/08/2022  03:50 PM           118,501 fxcontrol-1.18-3.0.2.jar
07/08/2022  04:59 PM         2,954,595 geckolib-forge-1.18-3.0.28.jar
07/08/2022  03:46 PM           508,526 grappling_hook_mod-1.18.2-v13.jar
07/10/2022  07:29 PM            74,987 gravelminer-forge-1.18.2-12.1.1.jar
07/09/2022  12:04 AM            69,259 grimoire_of_tetra-1.2.2.jar
07/08/2022  11:58 PM         3,394,431 hexerei-0.1.19.jar
07/08/2022  02:51 PM            39,556 honeyexpansion-1.1.1.jar
07/09/2022  12:06 AM           228,610 Hyle-forge-1.18.2-0.1.0.jar
07/09/2022  12:03 AM            96,233 Iceberg-1.18.2-1.0.44.jar
07/08/2022  02:43 PM         8,811,642 ImmersiveEngineering-1.18.2-8.0.2-149.jar
07/08/2022  03:49 PM           200,611 incontrol-1.18-6.0.12.jar
07/08/2022  02:44 PM         4,495,231 industrial-foregoing-1.18.2-3.3.1.4-8.jar
07/08/2022  02:50 PM           269,830 IntegratedCrafting-1.18.2-1.0.23.jar
07/08/2022  02:50 PM         3,258,815 IntegratedDynamics-1.18.2-1.11.5.jar
07/08/2022  02:50 PM           138,742 integratednbt-1.18.2-1.5.1.jar
07/08/2022  02:50 PM           137,990 IntegratedREST-1.18.2-1.1.5.jar
07/08/2022  02:50 PM           488,585 IntegratedTerminals-1.18.2-1.3.0.jar
07/08/2022  02:50 PM           605,857 IntegratedTunnels-1.18.2-1.8.12.jar
07/09/2022  09:07 PM           298,801 Jade-1.18.2-forge-5.2.3.jar
07/11/2022  04:58 PM            34,905 JadeAddons-1.18.2-2.2.0.jar
07/14/2022  12:48 AM           993,424 jei-1.18.2-9.7.0.216.jar
07/08/2022  02:37 PM         7,022,067 journeymap-1.18.2-5.8.5-forge.jar
07/08/2022  02:37 PM           254,745 JustEnoughResources-1.18.2-0.14.1.171.jar
07/08/2022  02:47 PM            20,121 kubejs-create-forge-1802.2.2-build.26.jar
07/08/2022  02:46 PM         1,052,328 kubejs-forge-1802.5.4-build.510.jar
07/08/2022  02:47 PM            29,048 kubejs-immersive-engineering-1802.2.1-build.35.jar
07/08/2022  02:46 PM            38,258 kubejs-mekanism-1802.1.3-build.8.jar
07/08/2022  02:47 PM            21,057 kubejs-thermal-1802.1.5-build.14.jar
07/08/2022  02:47 PM            57,515 kubejs-ui-forge-1802.1.8-build.17.jar
07/08/2022  02:47 PM            30,653 kubejsadditions-2.0.2.jar
07/08/2022  02:51 PM            38,956 largemeals-1.18.2-0.2.jar
07/09/2022  12:03 AM            36,855 LegendaryTooltips-1.18.2-1.2.5.jar
07/13/2022  07:50 PM           279,279 lootr-1.18.2-0.2.18.55.jar
07/10/2022  07:27 PM           993,981 lostcities-1.18-5.3.2.jar
07/08/2022  03:50 PM            32,109 lostsouls-1.18-2.0.0.jar
07/09/2022  12:00 AM         9,695,381 malum-1.18.2-1.3.7.jar
07/08/2022  02:43 PM           916,021 Mantle-1.18.2-1.9.27.jar
07/08/2022  05:07 PM           142,507 markdown_manual-1.18.2-forge-1.2.1+59006bb.jar
07/08/2022  03:49 PM           650,911 mcjtylib-1.18-6.0.15.jar
07/08/2022  02:44 PM        11,619,363 Mekanism-1.18.2-10.2.4.464.jar
07/08/2022  02:46 PM         1,085,856 MekanismAdditions-1.18.2-10.2.4.464.jar
07/08/2022  02:44 PM           991,220 MekanismGenerators-1.18.2-10.2.4.464.jar
07/08/2022  02:45 PM           373,773 MekanismTools-1.18.2-10.2.4.464.jar
07/08/2022  02:51 PM           287,799 mmlib-1.0.5-1.18.2.jar
07/08/2022  05:45 PM           134,770 MmmMmmMmmMmm-1.18.2-1.5.2.jar
07/08/2022  11:59 PM        26,154,206 mna-1.7.2.5.jar
07/13/2022  07:49 PM         1,335,919 mob_grinding_utils-1.18.2-0.4.41.jar
07/08/2022  03:46 PM            11,966 modnametooltip-1.18.1-1.18.0.jar
07/08/2022  05:00 PM           689,112 moreminecarts-1.4.6.jar
07/08/2022  11:46 PM         1,330,726 morestoragedrawers-1.18.2-1.1.2.jar
07/08/2022  03:47 PM            33,272 Morph-o-Tool-1.5-32.jar
07/08/2022  02:48 PM            76,344 MouseTweaks-forge-mc1.18-2.21.jar
07/08/2022  03:03 PM           910,154 multibeds-1.18-1.9.6.jar
07/09/2022  12:04 AM            91,081 mutil-1.18.2-4.5.0.jar
07/08/2022  11:47 PM         1,392,010 NaturesAura-36.2.jar
07/08/2022  02:48 PM           206,034 NaturesCompass-1.18.2-1.9.7-forge.jar
07/08/2022  02:39 PM            24,007 Neat-1.8-31.jar
07/08/2022  02:49 PM           216,339 netherportalfix-forge-1.18-9.0.0.jar
07/08/2022  02:51 PM           301,093 NethersDelight-1.18.2-2.2.0.jar
07/10/2022  07:40 PM           149,012 notenoughcrashes-4.1.4+1.18.2-forge.jar
07/08/2022  04:55 PM            12,502 no_nv_flash-1.18.2-1.4.0.2.jar
07/09/2022  12:01 AM         2,239,347 Obscuria's Essentials 3.2.0 (Forge 1.18.2).jar
07/09/2022  12:01 AM            46,297 Obscuria's Tooltips 1.4.1 (1.18.2).jar
07/13/2022  07:49 PM         4,841,274 occultism-1.18.2-1.36.3.jar
07/10/2022  07:13 PM        36,388,215 Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.2.jar
07/08/2022  04:55 PM           140,037 omgourd-1.18.2-1.6.1.5.jar
07/08/2022  03:22 PM            21,632 OpenLoader-Forge-1.18.2-12.0.1.jar
07/09/2022  12:00 AM           342,312 ortus-1.18.2-1.0.jar
07/09/2022  09:05 PM           403,507 Paraglider-1.18.2-1.6.0.0.jar
07/08/2022  02:43 PM           631,415 Patchouli-1.18.2-71.1.jar
07/08/2022  05:11 PM           349,698 Pehkui-3.3.3+1.18.2-forge.jar
07/08/2022  09:19 PM            10,260 PigPen-Forge-1.18.2-8.0.1.jar
07/08/2022  02:45 PM           181,808 Placebo-1.18.2-6.4.1.jar
07/08/2022  03:02 PM           526,995 platforms-1.18-1.9.4.jar
07/09/2022  12:14 AM           255,494 polymorph-forge-1.18.2-0.44.jar
07/08/2022  02:47 PM            63,360 ponderjs-1.18.2-1.1.7.jar
07/10/2022  07:36 PM             7,610 potionidpacketfixer-1.18.1-v1.0.1.jar
07/08/2022  02:37 PM        13,743,162 Quark-3.2-358.jar
07/09/2022  03:53 AM             1,892 QuarkOddities-1.18.jar
07/08/2022  02:49 PM         3,235,367 refinedstorage-1.10.2.jar
07/08/2022  02:50 PM            32,396 refinedstorageaddons-0.8.2.jar
07/08/2022  02:45 PM         2,127,869 reliquary-1.18.2-2.0.8.1139.jar
07/08/2022  02:45 PM         6,217,276 repurposed_structures_forge-5.1.14+1.18.2.jar
07/08/2022  03:50 PM            49,174 restrictions-1.18-4.0.0.jar
07/08/2022  03:50 PM           411,181 rftoolsbase-1.18-3.0.9.jar
07/08/2022  03:49 PM           637,932 rftoolsbuilder-1.18-4.0.13.jar
07/08/2022  03:50 PM           594,930 rftoolscontrol-1.18-5.0.6.jar
07/08/2022  03:50 PM         1,728,485 rftoolsdim-1.18-8.0.7.jar
07/08/2022  03:50 PM           561,477 rftoolspower-1.18-4.0.5.jar
07/08/2022  03:49 PM           367,575 rftoolsstorage-1.18-3.0.8.jar
07/08/2022  03:49 PM         1,610,330 rftoolsutility-1.18-4.0.16.jar
07/08/2022  02:46 PM         1,057,541 rhino-forge-1802.1.14-build.190.jar
07/08/2022  04:55 PM           180,206 right_click_get_crops-1.18.2-1.2.2.6.jar
07/08/2022  09:19 PM            14,146 Runelic-Forge-1.18.2-11.0.1.jar
07/08/2022  03:48 PM        17,516,908 ScalableCatsForce-2.13.8-build-4-with-library.jar
07/08/2022  05:07 PM           348,274 scannable-1.18.2-forge-1.7.6+135af8a.jar
07/08/2022  02:44 PM           456,163 selene-1.18.2-1.17.9.jar
07/08/2022  02:59 PM           452,551 shetiphiancore-1.18-3.10.10.jar
07/09/2022  01:10 AM         1,151,303 simple-rpc-1.18.2-3.0.1.jar
07/08/2022  09:16 PM           450,622 SimplyHouses-1.1.0-1.18.2-forge.jar
07/10/2022  07:18 PM           710,186 sophisticatedbackpacks-1.18.2-3.17.10.621.jar
07/10/2022  07:18 PM           879,507 sophisticatedcore-1.18.2-0.3.7.59.jar
07/10/2022  07:22 PM           521,342 sophisticatedstorage-1.18.2-0.3.4.49.jar
07/08/2022  02:43 PM           578,059 StorageDrawers-1.18.2-10.2.1.jar
07/08/2022  09:15 PM           213,626 structures_compass-1.18.2-1.4.1.jar
07/08/2022  04:59 PM           672,584 structure_gel-1.18.2-2.4.6.jar
07/11/2022  10:55 PM        13,466,755 supplementaries-1.18.2-1.4.8.jar
07/08/2022  02:43 PM        13,135,523 TConstruct-1.18.2-3.5.1.31.jar
07/08/2022  02:43 PM            99,002 TerraBlender-forge-1.18.2-1.1.0.102.jar
07/08/2022  03:02 PM         7,883,366 terraqueous-1.18-1.9.10.jar
07/09/2022  12:04 AM         2,970,428 tetra-1.18.2-4.9.3.jar
07/08/2022  04:59 PM         5,378,049 the-conjurer-1.18.2-1.1.1.jar
07/08/2022  02:45 PM           679,560 thermal_cultivation-1.18.2-1.6.3.11.jar
07/08/2022  02:43 PM           598,666 thermal_expansion-1.18.2-1.6.3.13.jar
07/08/2022  02:43 PM         4,673,576 thermal_foundation-1.18.2-1.6.3.28.jar
07/08/2022  02:45 PM           230,130 thermal_innovation-1.18.2-1.6.3.12.jar
07/08/2022  02:47 PM           285,634 thermal_integration-1.18.2-1.6.3.7.jar
07/08/2022  02:46 PM           229,382 thermal_locomotion-1.18.2-1.6.3.8.jar
07/08/2022  05:07 PM           582,206 tis3d-1.18.2-forge-1.6.8+2ac5c5f.jar
07/08/2022  02:44 PM           595,535 titanium-1.18.2-3.5.6-38.jar
07/08/2022  03:49 PM            24,697 ToastControl-1.18.2-6.0.2.jar
07/10/2022  07:28 PM         1,446,788 tombstone-7.4.9-1.18.2.jar
07/10/2022  07:36 PM             3,880 toofast-1.18-0.0.1.3.jar
07/08/2022  04:55 PM           399,207 tools_complement-1.18.2-1.1.2.9.jar
07/08/2022  03:49 PM            98,651 torchmaster-18.1.0.jar
07/11/2022  04:58 PM           340,897 TwilightDelight-1.18.2-1.2.0-Alpha.jar
07/13/2022  07:49 PM        32,921,376 twilightforest-1.18.2-4.1.1184-universal.jar
07/08/2022  04:55 PM             9,974 uneffectual-1.18.2-1.0.0.1.jar
07/08/2022  09:15 PM           622,497 valhelsia_core-1.18.2-0.3.1.jar
07/08/2022  09:15 PM         1,620,690 valhelsia_structures-forge-1.18.2-0.1.0.jar
07/08/2022  02:48 PM           357,620 waystones-forge-1.18.2-10.1.0.jar
07/08/2022  04:59 PM            27,841 WitherSkeletonTweaks-1.18.2-7.1.2.jar
07/08/2022  03:49 PM           527,782 xnet-1.18-4.0.5.jar
07/08/2022  02:43 PM           141,972 YungsApi-1.18.2-Forge-2.0.8.jar
07/08/2022  02:46 PM         1,487,782 YungsBetterDesertTemples-1.18.2-Forge-1.2.jar
07/08/2022  02:45 PM         1,024,281 YungsBetterDungeons-1.18.2-Forge-2.1.0.jar
07/08/2022  02:43 PM           274,075 YungsBetterMineshafts-1.18.2-Forge-2.2.jar
07/08/2022  02:46 PM           593,261 YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar
07/08/2022  02:46 PM           150,021 YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar
07/08/2022  02:46 PM         1,062,051 YungsBridges-1.18.2-Forge-2.1.0.jar
07/08/2022  02:46 PM           868,254 YungsExtras-1.18.2-Forge-2.1.0.jar

### latest.log

https://drive.google.com/file/d/1-lC2YEJjV8Qj920YOFIoW0STKvWSMD6N/view?usp=sharing

**Comment by mezz** [comment]
Thanks for the report!
JEI 10 alpha has some breaking changes to Fluid handling in order to support Fabric and Forge.
Please use JEI 9 for 1.18, it should be compatible with all mods.

**Comment by mezz** [comment]
I have submitted an update for Tinker's Construct here: https://github.com/SlimeKnights/TinkersConstruct/pull/4980

**Comment by mezz** [comment]
and I have submitted an update for EvilCraft here: https://github.com/CyclopsMC/EvilCraft-Compat/pull/9

**Comment by mezz** [comment]
These issues should be resolved now. Please open a new issue if you run across more mods that have an incompatibility.
