### ISSUE TITLE
[Bug]: The Create Recipe Bug is back

### ISSUE THREAD

**Issue by Foxydapirate12** [mezz/JustEnoughItems#2893]
### Steps to Reproduce the Bug

1. Enter Minecraft World
2. Open inventory
3. Hover over Crushing Wheel
4. Press 'R'

### Expected Behavior

It should display the crafting recipe for the Crushing Wheel

### Actual Behavior

Nothing happens upon Pressing 'R'

### latest.log

https://gist.github.com/Foxydapirate12/eb7063db88536c11932ab24e0e40eac0

**Comment by mezz** [comment]
Thanks for the report!
Not every mod is compatible with the JEI 10 alpha. Try using the stable JEI version 9.

**Comment by Foxydapirate12** [comment]
Thanks, Will do!
