### ISSUE TITLE
[Other]: JEI not working on 1.18.2

### ISSUE THREAD

**Issue by noskincz** [mezz/JustEnoughItems#2894]
### Other

I made a small modpack for myself and i added JEI and when i loaded the game it didnt show up on the list of downloaded mods in minecraft but the jar file was in the mod files i dont know if this is caused by one of the mods
list of mods:
![moid](https://user-images.githubusercontent.com/84130850/179237630-64e0a656-5fa4-4321-b4a9-3d02ec6b2102.PNG)

**Comment by mezz** [comment]
Thanks for the report!

It looks like you have a mix of Forge and Fabric mods. I don't think that is going to work the way you want it to. Are you intending to use Forge or to use Fabric?

**Comment by noskincz** [comment]
both are good but i dont know wich are forge and wich are fabric
