### ISSUE TITLE
[Crash]: clicking options in the main menu crashes minecraft

### ISSUE THREAD

**Issue by donoya** [mezz/JustEnoughItems#2895]
### Steps to Reproduce the Crash

Launch minecraft with JEI version 10.1.0.223 and Forge version 40.1.60. After reaching the title screen, click on options.

Latest.log:https://pastebin.com/SC37H0Qq

### Extra Notes (Optional)

I am playing with a bunch of other mods. If you need a full list, let me know.

### Crash Report

https://pastebin.com/CDHaJi5e

**Comment by mezz** [comment]
Thanks for the report!
This seems to be caused by another mod: `com.lowdragmc.lowdraglib.jei.JEIClientEventHandler`.
It is referencing a JEI internal class that moved.
Please report the issue to them here: https://github.com/Low-Drag-MC/LDLib/issues

**Comment by mezz** [comment]
Opened a meta-issue for this kind of problem in LDLib here: https://github.com/Low-Drag-MC/LDLib-Architectury/issues/29
