### ISSUE TITLE
[Bug]: Pressing Escape key while the mouse is hovering over an item tab does not close the inventory

### ISSUE THREAD

**Issue by MarioSMB** [mezz/JustEnoughItems#2897]
### Steps to Reproduce the Bug

1. Press the Uses or Recipes button while hovering over an item
2. Hover the mouse over one of the tabs of the different crafting stations able to make the item
3. Press the Escape key

### Expected Behavior

The menu should close and return to gameplay

### Actual Behavior

The menu acts as if a click was made and instead directs to the tab the mouse is hovering over

**Comment by mezz** [comment]
Thanks for the report!
What version of JEI has this issue?

**Comment by MarioSMB** [comment]
I'm currently using 1.18.2-9.7.0.209.

**Comment by mezz** [comment]
Thanks. I was able to reproduce the bug and have pushed a fix in the next version of 1.18.2-9.7.0
