### ISSUE TITLE
[Suggestion]: please expose two of the keybindings through the api 

### ISSUE THREAD

**Issue by Lothrazar** [mezz/JustEnoughItems#2898]
### Suggestion

Use case:

When i am in my custom inventory screen (example, storage network or any chest), and the user presses a key such as KeyBindings.showRecipe or KeyBindings.showUses , then events in my containers code will want to check if your keybinds are active and forward the message along.  in old minecraft and JEI versions such as 1.18.2 it worked this way by importing directly from core and not the API https://github.com/Lothrazar/Storage-Network/blob/trunk/1.18/src/main/java/com/lothrazar/storagenetwork/jei/JeiHooks.java#L61
And this function would be called from a keyPressed(..) function in the Screen such as this https://github.com/Lothrazar/Storage-Network/blob/49bb94c04271d001b1b0fc12bd6053dbe7c4ed59/src/main/java/com/lothrazar/storagenetwork/item/remote/GuiNetworkRemote.java#L166

So in Minecraft 1.19 and JEI 9.7.0.209+ i would like to carry this feature forward while still only using the JEI API and not pulling internals 

From discord 
![disco](https://user-images.githubusercontent.com/621529/179441351-23175fc4-7b7e-4968-b4c8-0320b31a3e98.png)

**Comment by mezz** [comment]
Thanks for the suggestion!
This has been added in JEI for 1.19

**Comment by Demerso** [comment]
@mezz Do you think this could be ported back to JEI for 1.18? Thanks
