### ISSUE TITLE
[Bug]: Can't retrieve items from JEI on dedicated server (1.19)

### ISSUE THREAD

**Issue by desht** [mezz/JustEnoughItems#2899]
### Steps to Reproduce the Bug

As an op'd player on a dedicated server, try to use JEI to give yourself an item (having ctrl-clicked the wrench button so it's red).

### Expected Behavior

For items to be retrievable as normal.

### Actual Behavior

Nothing will appear to happen clientside, but the server logs a (non-fatal) stacktrace from JEI.

### Extra Notes (Optional)

Looks like JEI is trying to use the clientside `LocalPlayer` class on dedicated server, which won't work, of course.  Tracked it down to `mezz.jei.forge.platform.ItemStackHelper` which contains references to `LocalPlayer` and `Minecraft`, but is still  loaded on the dedicated server.

### latest.log

https://gist.github.com/desht/be1acb21242250b5dc8face939807093

**Comment by desht** [comment]
Should also mention that this is with JEI 11.0.0.225 running on Forge 41.0.100.

**Comment by mezz** [comment]
Thank for the report!
This should be fixed in the latest version, which should be released shortly.
