### ISSUE TITLE
"Crash" with highlands mod installed

### ISSUE THREAD

**Issue by BionicFelps** [mezz/JustEnoughItems#29]
paste of log: http://www.hastebin.com/ziduhaqoba.hs

Steps to reproduce: Start a singleplayer map (maybe multiplayer too, didn't test), game will not start, and drop you back at title screen.

I'm not married to highlands personally, my fix is to remove it... But, figured I'd make a report anyway. (so no rush on this one)

(I also expected more problems given how new the mod is, and being thrown in with 10 or 12 other new/lesser known mods)

**Comment by mezz** [comment]
JEI is now only for Minecraft 1.8 so I am closing this.
