### ISSUE TITLE
[Bug]: JEI doesn't show items unless there are characters in the search bar. Clicking on the JEI area still opens recipes from those items.

### ISSUE THREAD

**Issue by richtigerfeger** [mezz/JustEnoughItems#2900]
### Steps to Reproduce the Bug

Just starting Minecraft works. I haven't tried reinstalling JEI yet.

### Expected Behavior

Blocks and items should be visible in the JEI area when I am not actively searching for something.

### Actual Behavior

JEI doesn't show items unless there are characters in the search bar. Clicking on the JEI area still opens recipes from those items.
So the items are still there, they are just invisible.

### Extra Notes (Optional)

Playing Create in 1.18 with a few extra mods.
Edit: spelling

### latest.log

https://gist.github.com/richtigerfeger/56a9d8db20259dbba2f7f86c8bebeda2

**Comment by Wertyhappy27** [comment]
Im having this same issue, hopefully this can be fixed. Using a few bigger content mods, so not sure if its one of them.

**Comment by rmnaderdev** [comment]
Had this same issue. My friends and I were using the [rubidum extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) mod and after removing it we don't have this issue. Hope this helps.

**Comment by Wertyhappy27** [comment]
I have Rubidum extras too, so maybe it is that.

**Comment by Wertyhappy27** [comment]
Seems that this is a feature of rubidium extras, go to config for the mod, find misc, then change "Hide JEI Until Searching" to false

**Comment by rmnaderdev** [comment]
Makes sense. That would help with lag when opening your inventory. @richtigerfeger, if this solves your issue, this issue can be closed.

**Comment by richtigerfeger** [comment]
My inventory doesn't lag when opening though, it's just the character thing in the searchbar. But I'll see my issue as solved, thanks for your help!

**Comment by mezz** [comment]
Thanks for the report!
I have no idea why that mod is changing how JEI works, it's just confusing people for very questionable benefit.
Please report to them that this feature shouldn't be enabled by default, it should be something pack makers or players choose for themselves https://github.com/TeamDeusVult/MagnesiumExtras/issues

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
