### ISSUE TITLE
[Suggestion]: Make Crafting Grid Helper return the slots it fills

### ISSUE THREAD

**Issue by Darkere** [mezz/JustEnoughItems#2901]
### Suggestion

The crafting grid helper creates the slots for the crafting grid but does not make them accessible, making it not possible to attach a focus link when using it. 

ideally `craftingGridHelper.setInputs(builder, VanillaTypes.ITEM_STACK, inputs, 3, 3);`  would return a list of slots.

**Comment by mezz** [comment]
Thanks for the suggestion!
I have implemented this in 1.19. Please let me know if you need it back-ported to an older version of JEI.

**Comment by Darkere** [comment]
Ah I'm currently still working on the 1.18 version. So a backport would be nice.

**Comment by mezz** [comment]
Ok, I have backported this to JEI 9 and 10 for 1.18.2
