### ISSUE TITLE
[Bug]: mod name in tooltip not displayed

### ISSUE THREAD

**Issue by bigheadonthebeat** [mezz/JustEnoughItems#2902]
### Steps to Reproduce the Bug

mod name is not displayed in the inventory and chests but is in the mod GUI

### Expected Behavior

i think it should print the mod name i haven't fiddled with any settings

### Actual Behavior

it just displays the name of the item and the other unralated info

### Mod Pack Version (Optional)

2.5

### Extra Notes (Optional)

![2022-07-18_19 41 37](https://user-images.githubusercontent.com/109543002/179561158-63092d03-90f2-4a2f-8d9b-9d67718abc92.png)
![2022-07-18_19 41 51](https://user-images.githubusercontent.com/109543002/179561169-8a8f2f11-170e-4855-baac-15293e57a4ad.png)
![2022-07-18_19 47 46](https://user-images.githubusercontent.com/109543002/179562575-f642d3a5-abb0-4101-add3-9c98e3e5b78f.png)

 MODS:
[mods.pdf](https://github.com/mezz/JustEnoughItems/files/9133795/mods.pdf)

**Comment by Greg-21** [comment]
IMHO it is not a bug. For this, mezz has a separate mod called Mod Name Tooltip.

**Comment by mezz** [comment]
Thanks for the report!
Right, JEI only applies this to its own tooltips.
To have mod names on all tooltips, you can use https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip
