### ISSUE TITLE
[Crash]: my minecraft server crashes when i use the crafting table

### ISSUE THREAD

**Issue by brainzwb** [mezz/JustEnoughItems#2903]
### Steps to Reproduce the Crash

hello.

my server with minecraft mods with friends crashes when we use the crafting tables, we use the mod pack of better minecraft in version 1.16.5 and about 3 or 4 mods that I added myself.

and use Magma Foundation for the server to have mods and plugins.

I have been investigating but have not found a solution.

I need help please.

this is the server crash report.

[crash-2022-07-18_23.05.46-server.txt](https://github.com/mezz/JustEnoughItems/files/9136955/crash-2022-07-18_23.05.46-server.txt)

if you need any other file or information I will be glad to give it to you.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/better-mc-modpack

### Mod Pack Version (Optional)

v57.5

### Crash Report

https://gist.github.com/brainzwb/6af84c2e1074c24de1018153145b3079

**Comment by mezz** [comment]
Thanks for the report!
Sorry but JEI is not involved in this crash log. 
Please try reporting here instead: https://github.com/Fuzss/visualworkbench/issues
