### ISSUE TITLE
[Bug]: 1.18.1 Fabric | mod is not loading when starting the game

### ISSUE THREAD

**Issue by SmarteOwl** [mezz/JustEnoughItems#2905]
### Steps to Reproduce the Bug

I wanted to add jre to my mods im using. So i dragged it into my mods folder, and started Minecraft. It didnt crash the game but didnt show up in the loaded mods either. I really dont know what it causing it. I even tryed just launching the mod without any other mod but fabric api in the folder and it still didnt work.
![w](https://user-images.githubusercontent.com/109593705/179737382-e73479ea-dbd5-4012-8050-1c7195a3dbe8.PNG)

### Expected Behavior

I guess it would show up in the loaded mods menu and also work ingame

### Actual Behavior

Nothing happens lmao

### latest.log

https://gist.github.com/SmarteOwl/f1b4d2e2a826bad2501f1287c6fccc0b

**Comment by RbDrache** [comment]
It is because you have installed the forge version of JEI.

**Comment by mezz** [comment]
Thanks for the report!
JEI 10 (alpha) has a version available for Fabric, please use that one.
