### ISSUE TITLE
The same recipe as the Forge version of the Fabric version 1.18.2 "Creation" mod

### ISSUE THREAD

**Issue by sbeom0308** [mezz/JustEnoughItems#2907]
### Other

In the Forge version of Creation Mode, you can check out the various recipes with Just Enough Items. For example, mechanical combinations in creation mode, items that can be crushed, items that can be obtained with a mixer or presser..

But all of the above are not shown in the Create Fabric version. I'd like all recipes to be displayed like the forge version of the creation mod.

**Comment by mezz** [comment]
Thanks for the report!
Can you please report this to the developers of Create? I do not control how mods integrate with JEI, maybe they didn't know JEI is on Fabric or they haven't written the code to support it yet.
