### ISSUE TITLE
[Crash]:  An unexpected critical error was encountered

### ISSUE THREAD

**Issue by PaterFrog** [mezz/JustEnoughItems#2908]
### Steps to Reproduce the Crash

Any JEI version beyond 0.226, on forge .54, MC 1.18.2:j

The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

The crash happens 100% reliably when trying to join a world (only tested single player.

Downgrading back to .226 fixes this crash for me.

I have hundreds of mods, all of them up-to date, except for this one.

I use a slightly customized version of the Better Minecraft Plus modpack, linked.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/better-mc-plus-new

### Mod Pack Version (Optional)

v12

### Extra Notes (Optional)

Added a few mods, most notably switched Magnesium/Rubidium Dynamic Lights for Lucent.

Added:
Builder Gadget
Corail Tombstone
Curios Lantern
FallingTree
Multi Mine
Macaw's everything
Passthrough Signs

### Crash Report

https://gist.github.com/PaterFrog/fc219c1f092dc078f1ffc373fb4e1a36

**Comment by mezz** [comment]
Thanks for the report!
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [rubidium_extras.mixins.json:JEI.IngredientListOverlayMixin] from phase [DEFAULT] in config [rubidium_extras.mixins.json] FAILED during APPLY
```
This appears to be caused by rubidium_extras, please report this to them: https://github.com/TeamDeusVult/MagnesiumExtras/issues

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
