### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by IfyourtherealslimshadyPleaseStandup** [mezz/JustEnoughItems#2909]
### Steps to Reproduce the Crash

Just download the mod and create a new world.

### Extra Notes (Optional)

When im using this mod it just crashes when it stars generating a world. My mc ram has been set to 6 gb.

### Crash Report

https://gist.github.com/IfyourtherealslimshadyPleaseStandup/822b5feb77b544f7d2bca6b1e48c4eca

**Comment by mezz** [comment]
Thanks for the report!
Sorry, this crash has nothing to do with JEI, it seems to be a problem with https://www.curseforge.com/minecraft/mc-mods/autoreglib
