### ISSUE TITLE
JEI startup error

### ISSUE THREAD

**Issue by astronymity** [mezz/JustEnoughItems#291]
When I start minecraft with JEI installed, an error comes up to that says:
Forge Mod Loader has found a problem with your Minecraft installation
The mods and versions listed below could not be found:
JEI : any
The file 'logs/fml-client-latest.log' contains more information.
I can't put the exact error because it won't let me screen shot it.  Please help!

**Comment by GirafiStudios** [comment]
You don't have JEI installed, that's what it's saying.

**Comment by p455w0rd** [comment]
go to your logs directory and open fml-client-latest.log, then go to pastebin.com and paste the log. come back here and paste the link. What this is telling you is that another mod is requiring JEI, but JEI isn't installed (in the mods directory). "JEI: any" means any version of JEI

**Comment by astronymity** [comment]
I have JEI installed, and I dont know how to go to the logs directory.  I will look it up.

**Comment by astronymity** [comment]
http://pastebin.com/2YaHcUBB
here

**Comment by p455w0rd** [comment]
you need to open up eula.txt in your intallation dir and set eula=false to eula=true

**Comment by astronymity** [comment]
thats different...
for my server

**Comment by astronymity** [comment]
i cant find the right file

**Comment by p455w0rd** [comment]
well wherever eula.txt, is, you need to edit it..this always happens when you first try to run a server..it generates eula.txt with default setting of false

**Comment by AEnterprise** [comment]
that can't be be the right log file at all as this file is from a server and missing mods is a client thing

**Comment by mezz** [comment]
@RoseRunner when you open the game and go to options and resource packs, there's a button to open the resource packs folder. If you go up one directory from there, you will see a bunch of files and folders including a `logs` folder, `mods` folder, and `eula.txt`.

Anyway, what the client error shows is that you do not have JEI installed on the client. You must have JEI in your `mods` folder.
The log you showed from the server is that you need to open the `eula.txt` and set it to true.
