### ISSUE TITLE
[Bug]: Alpha and beta , 10.1.1.231 and 9.7.1.232

### ISSUE THREAD

**Issue by Stryckoeurz** [mezz/JustEnoughItems#2913]
### Steps to Reproduce the Bug

Load a world with many mods/datapacks from mods (suposedly)
![image](https://user-images.githubusercontent.com/96977896/180206508-95f7516d-8f70-4591-85fa-aa009d3c31f9.png)

### Expected Behavior

The GUI should appear , and be used to check for crafts/uses

### Actual Behavior

The JEI UI doesn't appear and isn't reachable via FTB quests , Refined storage or any mods using it or directly depending on it , keys to access recipes (r) or uses (u) of an item/block don't react. (Beta) 
![image](https://user-images.githubusercontent.com/96977896/180207947-65ddfd07-25a9-4649-bae7-4b2cfe2f9c56.png)

Some mods recipes (notably , CREATE) will not show up , even tho you can use the recipes if you know them (Alpha)
(unable to provide example , spouts , deployers and other create crafts just don't show up)

### Extra Notes (Optional)

Using older versions may lead to having JEU working ... still testing which one do and which one don't in my config
It seems to be caused by RUBIDIUM EXTRAs , the problem being in other versions (not in the last BETA at least) it doesn't do that...
If there's a clear incompatibility from another mod and my dumb head wasn't able to see it , please forgive me.
due to the size of my latest log , i included something less threatening , every line including "mezz" , well , all of those seem to just repeat until i'm spawned so , idk

### latest.log

https://gist.github.com/Stryckoeurz/88aa89e1f5ed62e21b6acc071e2bae20

**Comment by mezz** [comment]
Thanks for the report!
Yes this log looks like a crash from rubidium_extras, please try removing it.

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
