### ISSUE TITLE
[Crash]: Forge 1.18.2-9.7.1.232 Incompatibility with Magnesium/Rubidium Extras

### ISSUE THREAD

**Issue by RbDrache** [mezz/JustEnoughItems#2914]
### Steps to Reproduce the Crash

Install following mods:
JEI 1.18.2-9.7.1.232
Magnesium/Rubidium Extras 1.18.2_v1.3.1

The first time I join a world minecraft straight up crashes, which is caught by not enough crash mod;
The second attempt lets me actually join the world but JEI is inactive; this is different from the "No items are shown until you type something in JEI's search bar" issues, as it seems the JEI loading process just crashes the first time, then is unable to initiate again due to JEI already being "active"

This is a latest.log file, trimmed recipe register error part to fit in the length limit, and it also seemed completely unrelated.
https://pastebin.com/dihL3F5d

### Crash Report

https://pastebin.com/k1EiMkwe

**Comment by RbDrache** [comment]
Update: 10.1.1.231 (latest alpha version on curseforge as of 2022-07-22) does not have this issue and works just fine.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Magnesium/RubidiumExtras, I think they are doing something weird with JEI.

**Comment by mezz** [comment]
I have opened an issue with RubidiumExtras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
