### ISSUE TITLE
[Crash]: JEI prevents the game from launching

### ISSUE THREAD

**Issue by Lexa013** [mezz/JustEnoughItems#2915]
### Steps to Reproduce the Crash

Open minecraft

### Extra Notes (Optional)

Crash when launching the game

### Crash Report

https://s3.eu-west-3.amazonaws.com/cdn.lexa013.dev/Media/2022/07/crash-2022-07-22_18.47.10-client.txt

**Comment by mezz** [comment]
Thanks for the report!
This looks like an incompatibility with your older version of JEI and the latest changes from Forge. 
Please update JEI and Forge to the latest available versions, this has been fixed.
