### ISSUE TITLE
[Bug]: Item hiding is completely broken.

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2916]
### Steps to Reproduce the Bug

Three issues.
A - You can only ever hide one item. (Unless you add them manually in blacklist.cfg)
B - Hiding by wildcard does not work at all.
C - Hiding all items of a mod is completely gone.

Issue A: 1. Get into a world. 2. Bind Item Edit mode to a key (since it's unbound by default). 3. Press that key and hide multiple items using CTRL+Left Click.

Issue B: Same as above, but try hiding using CTRL+Right Click this time.

Issue C: Just check the keybinds menu.

### Expected Behavior

Issue A: All items I hid are saved to blacklist.cfg.

Issue B: A wildcard is added to blacklist.cfg, instead of the singular item I clicked.

Issue C: Hiding by mod is available and working.

### Actual Behavior

Issue A: If I quit and immediately enter the same world again, everything works perfectly. However, if you check the blacklist.cfg, only the first item I hid is in there.
If I fully quit Minecraft and join again, only that one item is hidden.

Issue B: It acts exactly as if I was using CTRL+Left Click instead, even showing up in the blacklist.cfg as the full item name instead of a wildcard.

Issue C: No option for it in the keybinds menu, yet it's still mentioned in the mod's web pages.

### Extra Notes (Optional)

Was hiding entire mods removed? Are there plans to implement it again?

If these are all bugs indeed, would you mind sharing how the blacklist.cfg works?
For example, how wildcards are referenced, and how entire mods are referenced?
I tried the latter using simply "modname", then "modname:" and "modname:*", each in individual lines. Nothing worked.

(Thank you for porting to fabric, by the way. I'm actually using the forge version to generate the cfg files so I can copy them to fabric, lol)

### latest.log

https://gist.github.com/ridaway/6d1610045d912bc39ecd29ce8be78dc8

**Comment by mezz** [comment]
Thanks for the report!
This feature hasn't been used much, since CraftTweaker and KubeJS have become better solutions. You may want to use one of those as a workaround until this is fixed.
I see the report is from `jei-1.19-forge-11.0.2.230`, but are you experiencing this issue on Forge, Fabric, or both?

**Comment by ghost** [comment]
Fabric doesn't support it yet, the keybinds aren't implemented. I was using it on Forge so I could then copy the files to the Fabric version.

**Comment by ghost** [comment]
I have the same issue as OP, and I'm also trying to use the feature the same way. Do you mind elaborating on how CraftTweaker and KubeJS could be use as alternatives? A quick glance at them and it seems they're really complicated. Also, since the blacklist file technically works still, do you mind answering this from OP?

> For example, how wildcards are referenced, and how entire mods are referenced?
I tried the latter using simply "modname", then "modname:" and "modname:*", each in individual lines. Nothing worked.

**Comment by EccentricVamp** [comment]
I'm also experiencing this issue on Minecraft 1.18.2, Forge, JEI 9.7.2.259
