### ISSUE TITLE
[Bug]: Select all not working in search bar with FTB Library

### ISSUE THREAD

**Issue by Geldra** [mezz/JustEnoughItems#2919]
### Steps to Reproduce the Bug

Minecraft: **1.18.2**
Forge: **40.1.68**

JEI: **9.7.1.232** or **10.1.1.231** or **9.7.0.209**
FTB Library: **1802.3.6-build.115**
Architectury: **4.6.77** (works alone with JEI, is dependency for FTB Lib)

### Expected Behavior

Opening inventory and selecting search box --> ctrl + a --> all text in search box selected

### Actual Behavior

Opening inventory and selecting search box --> ctrl + a --> no selecting

### Extra Notes (Optional)

I'm sure this is an issue with FTB Library, but Latvian does not have an issues page on the repo. Thought I would share this here in case it is fixable from JEI.

**Comment by mezz** [comment]
Thanks for the report!
There is a place to report bugs for FTB Library, it's just not very easy to find. 
Can you please report it to them here?: https://github.com/FTBTeam/FTB-Mods-Issues/issues

**Comment by mezz** [comment]
This is probably a duplicate of https://github.com/mezz/JustEnoughItems/issues/2807 and https://github.com/mezz/JustEnoughItems/issues/3009
It has been fixed by JEI in the latest versions.
