### ISSUE TITLE
[Crash]: 1.19 Unable to Load

### ISSUE THREAD

**Issue by Shuggagaming** [mezz/JustEnoughItems#2920]
### Steps to Reproduce the Crash

Tried to open modded 1.19 minecraft. 

Other mods included (and successfully run without JEI)
- Ore Excavation for 1.19
- Macaw's Fences for 1.19
- Useful Backpacks for 1.19
- Waystones for 1.19

### Extra Notes (Optional)

Exit Code: -1
Happened with file: jei-1.19-forge-11.0.0.203.jar

### Crash Report

https://gist.github.com/Shuggagaming/873abbc1e99d014eabe49fa5d7a59a6c

**Comment by Shuggagaming** [comment]
Game was able to load after Curse Forge updated to file: jei-1.19-forge-11.1.0.235.jar

**Comment by mezz** [comment]
Thanks for the report!
Sorry your linked crash log just says "Crash Report" and nothing else, I think there is a mistake. Can you upload the full crash report?

**Comment by Shuggagaming** [comment]
Full Crash Report has been uploaded. Apologies, this is my first gist and I
did not know that was what it wanted.

**Comment by mezz** [comment]
Thanks!
It looks like you are using a really early version of JEI for 1.19. Please try updating to the latest version.

**Comment by Shuggagaming** [comment]
Yes. Right after I filed the gist my curse forge updated it and now it
works.

**Comment by mezz** [comment]
Ok sounds good, thank you for confirming.
