### ISSUE TITLE
[Crash]: 1.19 crashes with JEI

### ISSUE THREAD

**Issue by juli0cesar10** [mezz/JustEnoughItems#2923]
### Steps to Reproduce the Crash

1.- Open minecraft 1.19 forge 41.1.0

2.- Open my world saved as of yesterday

3.- Game crashes error 805306369

[crash-2022-07-27_11.27.24-server.txt](https://github.com/mezz/JustEnoughItems/files/9201046/crash-2022-07-27_11.27.24-server.txt)

### Extra Notes (Optional)

I´ve already download the newest jei version and did the same for .235 and .236

### Crash Report

https://gist.github.com/juli0cesar10/990b6a812686a79b5885546fb9ebc37e

**Comment by mezz** [comment]
Thanks for the report!
I think this is the same issue as in https://github.com/mezz/JustEnoughItems/issues/2788

It looks like your server JEI server configs are corrupted in some way.
Try deleting `jei-server.toml`, located in `saves/<world name>/serverconfig.`

**Comment by juli0cesar10** [comment]
Thanks for the quick response, i´ve done what you said and now is working perfectly fine.
(:
