### ISSUE TITLE
[Bug]: Items arent showing when inventory is open

### ISSUE THREAD

**Issue by Vaiscek** [mezz/JustEnoughItems#2924]
### Steps to Reproduce the Bug

When i open inventory there are no items on right, i see the search bar but thats all, and when  i click on the right side it will show random recepie

### Expected Behavior

i should see those items

### Actual Behavior

just cant see the items

**Comment by mezz** [comment]
Thanks for the report!
Do items show up if you type something into the search bar?

**Comment by MrTheGrem** [comment]
Actually i had the same problem, when i typed something in the search bar, items appeared. I just assumed it's a feature. But now jei just crashes on world load and disables itself. Game version is 1.18.2, Forge 40.1.68

**Comment by mezz** [comment]
I think this is caused by Rubidium Extras, I have reported it to them here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26

For now you can remove that mod and things should work normally.
