### ISSUE TITLE
[Crash]: Game crashes whenever i try to launch it from curseforge with JEI

### ISSUE THREAD

**Issue by YmeRose** [mezz/JustEnoughItems#2925]
### Steps to Reproduce the Crash

1. I download JEI on curseforgen on my profile
2. I launch the minecraft launcher from curseforge on that profile
3. I launch the game and it crashes

### Extra Notes (Optional)

whenever i disable JEI the game works fine. But whenever i enable it it just won't launch. I use other mods but those have never made my game crash before

### Crash Report

https://gist.github.com/Goerima/99f0e5fee2971dc0b7cb702a98b52bc1

**Comment by mezz** [comment]
Thanks for the report!
I do not see anything directly from JEI in the stack trace, so I think this is probably an incompatibility with multiple mods. Can you try with just JEI and Forge?

**Comment by alexania** [comment]
Edit: Moving my response to a new issue since I see this one refers to version 1.19 and I don't believe it's related.

**Comment by alexania** [comment]
To clarify above, the crash is on opening a world, not on game start. For some reason I clearly glossed over actually opening a world.

**Isolation Tests**

- Reverted JEI back to 9.7.0 -> _Works fine._
- Update to 9.7.1 and remove all mods except MineColonies and dependencies (annoying to turn off) -> _Works fine._
- Above + Rubidium 0.5.3 -> _Works fine_
- Above + Magnesium/Rubidium Extras v1.3.1 -> **Crash**

So yeah, looks like version 9.7.1 is having issues with [Magnesium/Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
