### ISSUE TITLE
[Crash]: JEI 1.18.2-9.7.1 incompatible with Magnesium/Rubidium Extras

### ISSUE THREAD

**Issue by alexania** [mezz/JustEnoughItems#2926]
### Steps to Reproduce the Crash

1. Update JEI to version 1.18.2-9.7.1.
2. Install Magnesium/Rubidium Extras v1.3.1
3. Open the game launcher from CurseForge.
4. Open the game.
5. Open an existing world (didn't test a new world).
6. Observe game crashes with error: **"Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @shadow field searchField was not located in the target class mezz.jei.gui.overlay.IngredientListOverlay. Using refmap rubidium_extras.refmap.json"**

So yeah, looks like version 9.7.1 is having issues with [Magnesium/Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)

### Extra Notes (Optional)

I isolated it as much as possible:
- Reverted JEI back to 9.7.0 -> _Works fine._
- Update to 9.7.1 and remove all mods except MineColonies and dependencies (annoying to turn off) -> _Works fine._
- Above + Rubidium 0.5.3 -> _Works fine_
- Above + Magnesium/Rubidium Extras v1.3.1 -> **Crash**

### Crash Report

https://gist.github.com/alexania/c82cbac4fcbb627d8ff04baf6d327468

**Comment by alexania** [comment]
Ah I see on their Issues board you're aware of this issue. I assumed the issue was on this side since that's all I changed. Will close it.

**Comment by mezz** [comment]
Thanks for the report!
I have reported this to Rubidium Extras here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
