### ISSUE TITLE
[Bug]: Cant search every item with an "e"

### ISSUE THREAD

**Issue by Johannes7k75** [mezz/JustEnoughItems#2927]
### Steps to Reproduce the Bug

1. Open inventory 
2. type e in search bar

### Expected Behavior

JEI should just put the "e" in the search bar.

### Actual Behavior

The inventory closes

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/create-live-3

### Extra Notes (Optional)

This just happend after a few days of playing

### latest.log

https://gist.github.com/Johannes7k75/eb9afdb6aeb04f90d4f5070895d3d4c3

**Comment by mezz** [comment]
Thanks for the report! 
Can you confirm if this happens with just JEI alone? If JEI does not have this bug by itself, there may be a mod conflict in the mod pack.

**Comment by whorsemaster** [comment]
I also had this issue. In my case, it ended up being Debugify. Specifically the bugfix for MC-147605. The way it's handled causes issues with a few other mods too apparently. Disabling that bugfix via config will make JEI work properly again.

**Comment by Johannes7k75** [comment]
It worked without any other mods.
Then i disabled the bugfix MC-147605 an it worked (Thx @whorsemaster )

**Comment by mezz** [comment]
It looks like this has been fixed in the latest version of Debugify https://github.com/isXander/Debugify/issues/74
