### ISSUE TITLE
[Bug]: configs are missing

### ISSUE THREAD

**Issue by CassieRoseZA** [mezz/JustEnoughItems#2929]
### Steps to Reproduce the Bug

Honestly im not sure becauese it just started happening

### Expected Behavior

The configs are missing

### Actual Behavior

Configs show be there

### Extra Notes (Optional)

Can't upload the latest.log due to it being 42mb
i will have to link it externally

**Comment by CassieRoseZA** [comment]
im running forge 1.18.2-40.1.60 JEI: 10.1.3.238

**Comment by CassieRoseZA** [comment]
[2022-07-29-3.log.gz](https://github.com/mezz/JustEnoughItems/files/9219626/2022-07-29-3.log.gz)

**Comment by mezz** [comment]
Thanks for the report!
Is your issue that there are no config files in the `config` directory, or is your issue the same as https://github.com/mezz/JustEnoughItems/issues/2860 ?

**Comment by CassieRoseZA** [comment]
> Thanks for the report! Is your issue that there are no config files in the `config` directory, or is your issue the same as #2860 ?

yeah it is

**Comment by CassieRoseZA** [comment]
one of the issues

**Comment by mezz** [comment]
Ok thanks, closing this as a duplicate so that we can keep conversation in just one issue.
