### ISSUE TITLE
JEI Crashed With Flux Ducts

### ISSUE THREAD

**Issue by AxolotlAccount** [mezz/JustEnoughItems#293]
I pressed R to look to the recipe of flux duct, and game crashed.

https://gist.github.com/EnderT5/60107f338dbc61636e1a70b0a4c8707b

**Comment by Sailren** [comment]
same crash here, my report is here: http://paste.ubuntu.com/16728129/

**Comment by mezz** [comment]
Thanks for the reports!
It looks like the crashing item is from Temportalist's Compression mod, it's a compressed flux duct.

```
-- Item being rendered --
Details:
    Item Type: temportalist.compression.main.common.item.ItemBlockCompressed@4afe8f90
    Item Aux: 0
    Item NBT: {size:9L,display:"Flux Duct",name:"fluxducts:fluxduct:0"}
    Item Foil: false
```

Please report here: https://github.com/TheTemportalist/Compression/issues?q=is%3Aissue+is%3Aclosed
Temportalist will have a better idea of how to solve the issue.

**Comment by TheTemportalist** [comment]
@mezz, and ideas what the null pointer is?

**Comment by mezz** [comment]
Either `model` or `model.getItemCameraTransforms()` is null.
