### ISSUE TITLE
[Crash]: JEI + Optifabric (Optifine)

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2930]
### Steps to Reproduce the Crash

Starting the game with JEI and Optifabric (Optifine) in 1.19, the game crashes.
Optifabric: [LINK](https://www.curseforge.com/minecraft/mc-mods/optifabric)

### Crash Report

https://github.com/IntMarco/Crash-JEI

**Comment by mezz** [comment]
Thanks for the report!
I see you reported this to OptiFabric as well here: https://github.com/Chocohead/OptiFabric/issues/811
I think they will be better able to resolve this problem.

**Comment by heartswampt** [comment]
bumping this, still happening 1.19.2 /:

**Comment by mezz** [comment]
I believe this issue is caused by Optifabric, please see if you can re-open https://github.com/Chocohead/OptiFabric/issues/811
