### ISSUE TITLE
[Crash]: Says invalid Java Runtime Configuration

### ISSUE THREAD

**Issue by CrypticDuckyy** [mezz/JustEnoughItems#2932]
### Steps to Reproduce the Crash

Open Minecraft

### Extra Notes (Optional)

I have a few other mods but they all load when JEI is not installed.

### Crash Report

https://gist.github.com/CrypticDuckyy/c0d089cf029110ca542ce845233563d0#file-gistfile1-txt

**Comment by mezz** [comment]
Thanks for the report!
It looks like this crash is from roughlyenoughitems, I think you should report to them instead.

**Comment by CrypticDuckyy** [comment]
oh wait wrong crash report 1 sec

**Comment by CrypticDuckyy** [comment]
https://gist.github.com/CrypticDuckyy/f72ead41816757d16b86d7959e6fde00#file-crash

**Comment by mezz** [comment]
Hmm strange! Can you please include the full report, not just the stack trace?

**Comment by CrypticDuckyy** [comment]
let me try to find it

**Comment by CrypticDuckyy** [comment]
How do i get the full thing?

**Comment by CrypticDuckyy** [comment]
https://gist.github.com/CrypticDuckyy/4eb525299ad854e1b62ddb2ed5fa0b56#file-gistfile1-txt 
this was all i could find

**Comment by mezz** [comment]
Thanks!
Please try removing opti-fabric and see if that fixes the issue.

**Comment by CrypticDuckyy** [comment]
Still does not work

**Comment by CrypticDuckyy** [comment]
nvm it did thanks

**Comment by OzdorMiZ** [comment]
Then close the issue
