### ISSUE TITLE
[Bug]: Some synthesis tables cannot be displayed

### ISSUE THREAD

**Issue by It-Ding** [mezz/JustEnoughItems#2933]
### Steps to Reproduce the Bug

When I use farmer's delight mod in 1.18.2 fabric version. JEI does not recognize a considerable part of the composition table, for example, any composition table that utilizes a cooking pot cannot be displayed in JEI, how to solve this situation

### Expected Behavior
When I look at the uses of rice, it When I look at what the rice is used for, it should show the recipe for using the cooking pot only shows the crafting table on the workbench

### Actual Behavior

When I look at the uses of rice, it only shows the crafting table on the workbench

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric

### Mod Pack Version (Optional)

1.18.2

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Farmer's Delight, it is up to each mod to add integration for their recipes to be displayed in JEI.
