### ISSUE TITLE
[Crash]: Opening inventory 1.12.2

### ISSUE THREAD

**Issue by youseffo** [mezz/JustEnoughItems#2935]
### Steps to Reproduce the Crash

1. Launch Minecraft The Classic Pack on the Technic launcher.
2. Load into the Platinum Server
3. Open the inventory menu 
4. The game crashes.

### Mod Pack URL (Optional)

https://www.technicpack.net/modpack/tc-redux.786294/mods

### Mod Pack Version (Optional)

3.3.3c-hotfix

### Extra Notes (Optional)

This issue came up shortly after interacting with a Thermal Centrifuge from Industrialcraft 2. I am not sure if it is related but it might help.

### Crash Report

https://gist.github.com/youseffo/c78fd9ef15705ad0b23c6e0ae02a1214

**Comment by mezz** [comment]
Thanks for the report!
The crash log has some details:
```
-- Item being rendered --
  Item Type: codechicken.microblock.ItemMicroPart@34b88d6d
  Item Aux: 1
  Item NBT: {mat:"minecraft:stone[variant=stone]"}
  Item Foil: false

-- Ingredient being rendered --
  Mod Name: Forge Microblocks
  Registry Name: microblockcbe:microblock
  Display Name: Stone Cover
  String Name: 1xitem.microblock@1

-- JEI render details --
  Unique Id (for Blacklist): microblockcbe:microblock:{mat:"minecraft:stone[variant=stone]"}
  Ingredient Type: class net.minecraft.item.ItemStack
  Error Info: 1xitem.microblock@1 microblockcbe:microblock nbt:{mat:"minecraft:stone[variant=stone]"}
  Filter Text: over
  Edit Mode Enabled: false
  Debug Mode Enabled: false
```

This crash seems to be caused by a specific microblock cover. I'm pretty sure it would also crash without JEI involved, but in this case it's being displayed from the JEI ingredient list next to your inventory.
You can try blacklisting the microblocks from JEI in the configs, I think you can just add `microblockcbe:microblock` there.

**Comment by youseffo** [comment]
how do I open the configs for JEI?

**Comment by youseffo** [comment]
I think I added it to the blacklist but I am not sure if the formatting is right
![Screenshot (5)](https://user-images.githubusercontent.com/110558160/182943007-7cc8afe8-b85a-42ca-a0ce-284602cf56eb.png)

**Comment by mezz** [comment]
try like this:
```
advanced {
    S:itemBlacklist <
        microblockcbe:microblock
    >
}
```
