### ISSUE TITLE
Crashing on Loading World 1.9

### ISSUE THREAD

**Issue by Levion1** [mezz/JustEnoughItems#294]
So, i had this issue a while back, and i decided to check for a newer version. Using the latest version for Minecraft 1.9. Yes i have a number of other mods and i dont know if its the other mods causing the issue, or if Jei just dosnt like me...

Heres the crash report, since i know mods cant be fixed without knowing what went wrong.
https://gist.github.com/Levion1/4b0e6d80ddca824900a1f2f42e9d17fb

If it cant be fixed then we can figure out what mods are clashing with it, and get that sorted out instead.
Thanks so much!

**Comment by Levion1** [comment]
forgot to put this in.. the issue only occured apoun opening any world or making a world. the game loads fine, the buttons all work and everything. but the moment the game is loading the chunks, it Shuts Down the internal server, and the game crashes.

**Comment by mezz** [comment]
Thanks for the report!
This crash is from `fuj1n.recmod`, please search for that in the crash report to get an idea of what it means, it might help you quickly find the right place to report in the future.
Please report this issue to them here: https://github.com/SlimeKnights/RecMod/issues
