### ISSUE TITLE
[Bug]: Win 1.16.5, JEI isn't working

### ISSUE THREAD

**Issue by OzdorMiZ** [mezz/JustEnoughItems#2940]
### Steps to Reproduce the Bug

1. Install a big amount of mods
2. See a bug(No JEI menu)

### Expected Behavior

I should see the JEI GUI

### Actual Behavior

There is no JEI GUI, like i haven't installed JEI.

### Mod Pack URL (Optional)

https://drive.google.com/drive/folders/1OdFiC4crAc3rmsHp1fLrzYcoSEMRvAgM?usp=sharing

### Extra Notes (Optional)

There are a lot of mods in my modpack, if you can't solve this issue with this big amount of them tell me.

### latest.log

https://gist.github.com/OzdorMiZ/15dc09e2d80f0e166c742add666a2ee0

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately this is probably caused by a mod conflict, and the cause is not visible in the log.
Please try removing batches of mods to see which one is causing the problem.
