### ISSUE TITLE
[Crash]: Crashing after Joining world

### ISSUE THREAD

**Issue by INooBTooMuch** [mezz/JustEnoughItems#2943]
### Steps to Reproduce the Crash

Creating and Joining world

(I'm not using a modpack but just a bunch of mods that I put together so I don't know how to give the mod list unless I write every mod by hand)

### Extra Notes (Optional)

So I had this issue before but downgrading JEI to the previous release version fixed it, but now Refined Storage has the v.9.7.1 required with the new update that fixes a couple of problems and bugs.

[Latest Log](https://gist.github.com/INooBTooMuch/c92d6f576b5ae0ff66093965261ea03b) (incase its needed)

### Crash Report

https://gist.github.com/INooBTooMuch/689911fb94e0c68fd113902e3a96d0e8

**Comment by mezz** [comment]
Thanks for the report!
This is caused by Rubidium Extras, I have reported the crash here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26

**Comment by INooBTooMuch** [comment]
I checked the latest alpha version for 1.18.2. It fixes the problem but I think the configs are not working (only based on the fact that I can't set the max columns and stuff) which is expected since its alpha version (or I'm looking in the wrong files and the [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) mod is only showing tooltip configs)

Most important is that I guess its fixed in the alpha version but that might be because its not yet released and the problem not yet implemented or something, I don't know how it works.
