### ISSUE TITLE
[Bug]: JEI doesnt show items in Industrialforegoing/Thermal Machines

### ISSUE THREAD

**Issue by TheonlyTazz** [mezz/JustEnoughItems#2949]
### Steps to Reproduce the Bug

Look up uses for Dissolution Chamber or Magma Crucible
Items are missing in the recipes, yet recipes still exist
![image](https://user-images.githubusercontent.com/3908847/183826937-6a4ae403-79b1-41ff-8184-e12a35cb8798.png)
![image](https://user-images.githubusercontent.com/3908847/183826948-0a7fc660-34d9-4652-afc8-320feddf39c2.png)
![image](https://user-images.githubusercontent.com/3908847/183826972-26cb12ab-aa95-4481-b3ba-a2d2fedfff56.png)

This also appears to be the case for Creates Processing Recipes
and tinkers:
![Uploading image.png…]()

### Expected Behavior

Show recipes, this worked in the latest release version: `jei-1.18.2-10.1.3.240.jar`

### Actual Behavior

see above

### Mod Pack URL (Optional)

https://feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18

### Mod Pack Version (Optional)

v1.9.0

### Extra Notes (Optional)

This issue has been posted on th Feed The Beast Issue tracker:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1236

This has also been tested with a minimal amount of mods:
```jei-1.18.2-forge-10.1.3.240.jar

industrial-foregoing-1.18.2-3.3.1.4-8.jar
Patchouli-1.18.2-71.1.jar

cofh_core-1.18.2-1.6.4.21.jar
thermal_expansion-1.18.2-1.6.3.13.jar
thermal_foundation-1.18.2-1.6.3.28.jar
titanium-1.18.2-3.5.6-38.jar```


### latest.log

_No response_

**Comment by mezz** [comment]
Thanks for the report!
JEI 10 is an Alpha version and has some breaking changes to fluids in the API. 
Please use JEI 9.

**Comment by mezz** [comment]
I think Thermal Expansion has updated to support JEI 10.
I submitted a PR for Industrial Foregoing here: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/1294
