### ISSUE TITLE
JEI bug about compression and flux ducts

### ISSUE THREAD

**Issue by AxolotlAccount** [mezz/JustEnoughItems#295]
Flux duct maker fixed crash issue, but there is still an issue, if you look to the usage (''u'' button) of flux duct, there is a compressed flux duct recipe, but you cant craft compressed flux duct (i think mod maker of flux ducts removed compressing flux duct).

**Comment by mezz** [comment]
Thanks for the report!
This is an issue for the Compression mod. JEI does not control the recipes, it's up to them to check the validity of their recipes. 
Please report here: https://github.com/TheTemportalist/Compression/issues
