### ISSUE TITLE
[Other]: Not Working with Controllable 

### ISSUE THREAD

**Issue by jayyms** [mezz/JustEnoughItems#2952]
### Other

Previously used controllable and JEI on Minecraft version 16.5 and they worked prefect together. 

Now since moving to Minecraft version 18.2 I cannot use the key binds for JEI. As in moving through the pages of recipes etc.

**Comment by mezz** [comment]
Thanks for the report!
Can you report this to Controllable as well and link back to this issue? They may have a better idea of what's going on.

**Comment by jayyms** [comment]
Thanks for the quick response here is the issue I reported on [Controllable GitHub](https://github.com/MrCrayfish/Controllable/issues/322 ). Some other players are experiencing this also.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/43ca4f8851c33444beef0f38aa37de1942aebe35

**Comment by mezz** [comment]
@MrCrayfish thanks for the fix.
I wasn't aware that you're depending on JEI internals to make this work. 
Can you explain what you need available in the API so I can support it better?
