### ISSUE TITLE
[Bug]: JEI doesn't show GUI on Fabric 1.19.2 (at any version of Fabric Loader)

### ISSUE THREAD

**Issue by BlackWolf00** [mezz/JustEnoughItems#2955]
### Steps to Reproduce the Bug

Install a mod that support JEI, fabric api and JEI
Start the game
Start a world
Open inventory

### Expected Behavior

Following the steps to reproduce the bug, JEI should just show the GUI

### Actual Behavior

Following the steps to reproduce the bug, JEI don't show the GUI

### Extra Notes (Optional)

I'm updating a mod from 1.19.1 to 1.19.2, maybe I'm doing something wrong

### latest.log

https://gist.github.com/BlackWolf00/b8103364680fa55271aa74ab4db24027

**Comment by BlackWolf00** [comment]
Resolved
I changed fabricApiVersion from 0.60.0 to 0.59.0

**Comment by XionioXMaster** [comment]
> Resolved
> I changed fabricApiVersion from 0.60.0 to 0.59.0

This is Forge
