### ISSUE TITLE
[Suggestion]: Adding a way to search for things that contain certain item in their recipe

### ISSUE THREAD

**Issue by Gartebex-Ugandi** [mezz/JustEnoughItems#2956]
### Suggestion

For example, you have andesite alloy from create, and you want to search for items where its used, for example andesite casing.
Dont know what to say else to it. Sorry about that.

**Comment by mezz** [comment]
Thanks for the suggestion!
You can see where ingredients are used by pressing "U" or right-clicking them in the ingredient list.

**Comment by Gartebex-Ugandi** [comment]
I know, i just mainly suggested this thing so you can bookmark them easily. But im sure some people would find the recipe list too long, so this might be useful for them.

Thanks for your positivity :)!

**Comment by vfyjxf** [comment]
I have added a similar feature to my mod [Jei Utilities](https://github.com/vfyjxf/JEI-Utilities), I call it Recipe Filter, it is basically finished but I haven't had time to perfect it and release it recently.

**Comment by Gartebex-Ugandi** [comment]
> I have added a similar feature to my mod [Jei Utilities](https://github.com/vfyjxf/JEI-Utilities), I call it Recipe Filter, it is basically finished but I haven't had time to perfect it and release it recently.

Ok, thanks for suggestion.
