### ISSUE TITLE
[Crash]: 1.18.2 JEI Crashing

### ISSUE THREAD

**Issue by LuvelyThief** [mezz/JustEnoughItems#2958]
So, I have no idea if it is another mod causing JEI to crash. When I remove JEI, everything loads up fine. I wasn't having this problem before. I was able to load up the modpack I made just fine a couple weeks ago and now it's crashing. I usually can read crash reports fine myself, but this one is just very confusing. I know that it could be a different mod that is causing the crash, but I can't figure out which one. Please, if anyone can help with it.

### Crash Report

https://gist.github.com/LuvelyThief/ba03cb37e73e5ab8c81c456bfb2623e4

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately JEI is not in the stack trace, so I'm not sure how it is involved here. Sorry I can't help narrow it down more from the log, I think you'll have to try narrowing down the mods involved to find out what is causing this issue.

**Comment by Rundas01** [comment]
I had the same issue after updating a couple of mods in my pack and was as stumped as you.
Turned out, that "jei-1.18.2-9.7.1.255.jar" was causing the game to crash on world load every time. Downgrading to
"jei-1.18.2-9.7.1.232.jar" solved the issue. Maybe that helps you.
