### ISSUE TITLE
[Bug]: 1.19.2 version incompatible with fabric-api-0.60.0+1.19.2

### ISSUE THREAD

**Issue by siyangfei** [mezz/JustEnoughItems#2959]
### Steps to Reproduce the Bug

1.19.2 version incompatible with fabric-api-0.60.0+1.19.2

### Expected Behavior

1.19.2 version incompatible with fabric-api-0.60.0+1.19.2

### Actual Behavior

1.19.2 version incompatible with fabric-api-0.60.0+1.19.2

**Comment by vandon1** [comment]
Can confirm:
Working: fabric-api-0.59.0+1.19.2.jar
No JEI in inventory: fabric-api-0.60.0+1.19.2.jar
Reverting to 0.59 brings JEI back

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next version, released shortly.
