### ISSUE TITLE
I keeping getting this error

### ISSUE THREAD

**Issue by mapyDayton22** [mezz/JustEnoughItems#2961]
### Steps to Reproduce the Crash

Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

### Crash Report

https://pastebin.com/FcY23jN6

**Comment by mezz** [comment]
Thanks for the report!
`java.lang.OutOfMemoryError: GC overhead limit exceeded`
This is not actually caused by JEI, it is because you are running out of memory for Minecraft. 

You can fix it by removing mods or allocating more memory to Minecraft, you can find more information by searching online.
