### ISSUE TITLE
[Bug]: No recipes from Create Fabric

### ISSUE THREAD

**Issue by VGamerGroup** [mezz/JustEnoughItems#2962]
### Steps to Reproduce the Bug

- The **Fabric mod loader** is used!
- When using the Create Fabric mod ( **1.18.2 v0.5.0c**) together with the JEI mod (**1.18.2-fabric-10.1.3.240**), JEI does not show craft recipes from the Create mod.

### Expected Behavior

- Following the instructions to reproduce the error, JEI should just show the recipes for **creating items** from Create Fabric mod.

### Actual Behavior

- Nothing happens, the creation recipes from the Create Fabric mod are not displayed. Even if you press the **left mouse button**
or **R**.

### Extra Notes (Optional)

- This error occurs both in a single player game and in a multiplayer game.
- The only thing that JEI shows is enchantments that can be applied to items from the Create mod.

**Comment by mezz** [comment]
Thanks for the report!
What was the issue?

**Comment by spencerfrost** [comment]
Just want to report that this is still an issue and the entire Create Fabric community has switched over to REI because of it. Plenty of `create:*` recipes are just straight up missing from JEI.
