### ISSUE TITLE
[Suggestion]: Add support with Catalouge

### ISSUE THREAD

**Issue by Ch1216** [mezz/JustEnoughItems#2963]
### Suggestion

Please add support for [Catalouge 1.18.2](https://www.curseforge.com/minecraft/mc-mods/catalogue) mod icons are compatibility with it, if I were to suggest an icon maybe a knowledge book since its the recipe book icon and this is it but better and you could say the mod gives you knowledge1

**Comment by MrCrayfish** [comment]
I've written a guide here: https://www.curseforge.com/minecraft/mc-mods/catalogue/pages/how-to-specify-a-custom-icon

**Comment by mezz** [comment]
Thanks for the suggestion!
This has been implemented in JEI for all versions on 1.18 and 1.19
