### ISSUE TITLE
[Bug]: Bookmarks appearing over main GUI when you don’t have the required items to craft a recipe

### ISSUE THREAD

**Issue by Nevrai** [mezz/JustEnoughItems#2964]
### Steps to reproduce the bug

1. Use a crafting grid from [Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
2. Open the recipe of an item that you don’t have the required items for in JEI
3. Hover over the plus button

### Expected behavior

The bookmarks should stay in place where they belong.

### Actual behavior

When hovering over the plus button when viewing a recipe in JEI, if you’re using a Refined Storage crafting grid or Refined Storage Addons wireless crafting grid, the bookmark list moves from the top left of the screen to the middle of the screen, on top of the recipe, if you don’t have the required items to craft the recipe. The rest of the JEI GUI (bookmarks button and the entire ingredient list) disappears when hovering over the plus button as well. This doesn’t happen if you do have the required items or when using any other sort of crafting table.

I’m playing [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7), but I did update JEI and Refined Storage manually. The pack is on version 9.7.0.226 of JEI and version 1.10.2 of Refined Storage, and I updated to the latest stable version of JEI for 1.18.2, 9.7.1.232, and the latest version of Refined Storage, 1.10.3, manually. This bug didn’t happen before updating JEI and RS.

### Versions
* **Minecraft:** 1.18.2
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.27—latest)
* **Forge:** 40.1.68
* **Just Enough Items:** 9.7.1.232 (latest stable release for 1.18.2)
* **Refined Storage:** 1.10.3

**Comment by mezz** [comment]
Thanks for the report!
Can you include a screenshot so I can see what you mean?

**Comment by DeleteMetaInf** [comment]
![JEI bug](https://user-images.githubusercontent.com/59761487/186071272-798dc44d-87ce-4ef8-ba2e-afdc4f2ab443.png)

**Comment by DeleteMetaInf** [comment]
Here’s a screenshot:

![JEI bug](https://user-images.githubusercontent.com/59761487/186072225-49a3868a-fccb-4696-b95f-0f8d757943b9.png)

I realized that this only happens when using Refined Storage crafting grids or wireless crafting grids and does not happen when using regular crafting tables, so I’ve reported this [on Refined Storage’s issue tracker](/refinedmods/refinedstorage/issues/3361) as well.

**Comment by Nevrai** [comment]
Here’s a screenshot:

![JEI bug](https://user-images.githubusercontent.com/59761487/186072225-49a3868a-fccb-4696-b95f-0f8d757943b9.png)

I have come to realize that this bug only happens when using [Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage) crafting grids or wireless crafting grids and does not happen when using regular crafting tables or crafting tables from other mods, so I’ve reported this [on Refined Storage’s issue tracker](/refinedmods/refinedstorage/issues/3361) as well. It didn’t happen when I was using v9.7.0.226 of JEI and v1.10.2 of RS.

**Comment by Nevrai** [comment]
Can confirm that this still occurs on the latest beta release, 9.7.2.264. It may be an issue on Refined Storage’s end.

**Comment by mezz** [comment]
I believe this issue has been resolved, please open a new issue if you encounter this again.
