### ISSUE TITLE
[Bug]: JER does not show up on servers

### ISSUE THREAD

**Issue by JoshHawley** [mezz/JustEnoughItems#2966]
### Steps to Reproduce the Bug

1. Install new fabric server following directions listed here: https://github.com/jsorrell/CarpetSkyAdditions/blob/132576e26cce3226c87761be3793a08b92f13547/docs/en_us/installation.md
2. Add mods to server: JEI, JER, JEP
3. Use CurseForge/Overwolf app to install Vanilla Sky
4. Add mods to client: JEI, JER, JEP
5. In client, create single player world and verify that JEI, JER, and JEP are working
6. Connect to server, and see that they do not work.

### Expected Behavior

JER shows up when logged into server

### Actual Behavior

Using the same client, I can connect to a single player world where JER works, but if I connect to the server, JER does not show.
The server and client have the same version of JER loaded. 
JustEnoughResources-Fabric-1.19-1.0.0.176
If you want additional versions, see the attached latest.log

There are a couple of potentially related messages in the server's latest.log:
[13:40:12] [main/WARN]: Reference map 'JustEnoughResources-Fabric-1.19-refmap.json' for jeresources.mixins.json could not be read. If this is a development environment you can ignore this message
[13:40:12] [main/WARN]: Reference map 'JustEnoughProfessions-fabric-1.19-refmap.json' for justenoughprofessions.fabric.mixins.json could not be read. If this is a development environment you can ignore this message

I'm not sure these are related though because JEP works fine.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/vanilla-sky

### Extra Notes (Optional)

the latest.log below is from the server -- let me know if you want to see the client side one, or any other logs/info. 

### latest.log

https://gist.github.com/JoshHawley/ed108fc11b43959ed79dcef15b5b6b17

**Comment by mezz** [comment]
Thanks for the report!
Please report this to JER here: https://github.com/way2muchnoise/JustEnoughResources/issues
