### ISSUE TITLE
[Suggestion]: {NEED HELLP }

### ISSUE THREAD

**Issue by anshul3485raj** [mezz/JustEnoughItems#2967]
### Suggestion

![image](https://user-images.githubusercontent.com/59793276/186775362-5171e4bb-fdb7-45a0-8a98-bafc80c3485a.png)

Any way to disable those time control button in cheat mode , i just want to make cheat mode look like normal mode is there any way to do that ? pls make a different key for it

**Comment by mezz** [comment]
Thanks for the report!
The time control buttons are not from JEI actually, they are from one of the FTB mods.
