### ISSUE TITLE
[Bug]: Brewing recipes not working in Fabric 1.19.2

### ISSUE THREAD

**Issue by AsgavinYT** [mezz/JustEnoughItems#2968]
### Steps to Reproduce the Bug

Using JEI 11.2.0.256 in Fabric 1.19.2

Fabric API: 0.60.0+ 1.19.2

### Expected Behavior

I expected to see the brewing recipes when i pressed R over a potion

### Actual Behavior

All other recipes work just fine including the ones that use said potions like the special arrows, the only thing not working is the brewing stand recipes.

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the latest version.
