### ISSUE TITLE
[Bug]: typing E even with search bar selected exits the inventory

### ISSUE THREAD

**Issue by GodzillaFan13** [mezz/JustEnoughItems#2969]
### Steps to Reproduce the Bug

![Screenshot (1559)](https://user-images.githubusercontent.com/112220126/187006808-f85ba32a-40a9-4dd9-aa21-156e68d95a3d.png)
simply done as is, with mod list in said screenshot. 

### Expected Behavior

search bar allows you to type the letter E.

### Actual Behavior

even with search bar selected and being used, pressing E exits the screen. 

### Extra Notes (Optional)

similar in overall behavior to https://github.com/mezz/JustEnoughItems/issues/2801#issuecomment-1103781736, sans the lack of debugify. 
sorry if this is incorrectly formatted in any way, shape or form, as this is my first time using Github at all. thank you. 

### latest.log

https://gist.github.com/GodzillaFan13/afec610d80370e70c9d162b17e2eaf50

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately it looks like you actually do have debugify installed, can you try removing it to see if the problem is resolved?

**Comment by GodzillaFan13** [comment]
huh, apparently i did XD. 
strange, as i don't remember installing it, but alas thank you.

**Comment by mezz** [comment]
No problem, glad that was it!
