### ISSUE TITLE
JEI GUI Overlay not opening (1.8.9)

### ISSUE THREAD

**Issue by Thatacoustic** [mezz/JustEnoughItems#297]
I can't get the JEI Gui to show in 1.8.9. I have a few mods installed. Nothing crashes, I just can't get the overlay to appear. I've changed the keybindings a few times and nothing works. I can see recipes and uses if I use "R" or "U" over an item, but no overlay will appear.
[fml-client-latest.log.txt](https://github.com/mezz/JustEnoughItems/files/288745/fml-client-latest.log.txt)

**Comment by mezz** [comment]
Thanks for the report!
The overlay will only appear when a GuiContainer is open. Try some known ones like the player inventory, vanilla crafting table, and chest. Basically anything that shows the player inventory should work, but maybe another mod broke it somehow.
If the keybind (Ctrl-O) is broken by something, you can go to the Esc menu -> Mod Options -> JustEnoughItems -> and enable the Item List Overlay.

**Comment by Thatacoustic** [comment]
Wow, super quick response, awesome.

So the Gui does open up in the crafting table, awesome. Chest works as well. Player inventory does not work, though. I can toggle the Item List Overlay in the Chest and Crafting Table, so I'm assuming some mod conflicts with the Player Inventory. 

Thanks for you help, if you need anything from me to try and decide which mod conflicts with the player inventory, let me know and I'll do what I can. Awesome work mezz.

**Comment by mezz** [comment]
If you can narrow down which mod is causing the bad interaction  with JEI, I can figure out who to talk to in order to fix it. 
My best guess is Inventory Tweaks, but I'm not familiar with a lot of the stuff you have.
Can you make a copy of your world and try removing some mods until JEI works properly?

**Comment by Thatacoustic** [comment]
Yeah, definitely! Give me a bit and I'll report back.

**Comment by Thatacoustic** [comment]
Wow, okay, I solved the problem. The mod, ArmorPlusMod, has armor that gives you nightvision. The nightvision effect disables the Gui in the player inventory screen. It's not a conflict with any mods, but a conflict with the nightvision effect from Vanilla Minecraft. The player inventory seems to be the only thing effected from the nightvision effect (chests/tables work). The invisibility effect also disables your mods Gui. I'd hop onto a creative world with just your mod installed and try different potions to see which ones disable the Gui, as I've only used Invisibility and Night vision.

**Comment by mezz** [comment]
Ah ok, what's happening is that vanilla minecraft is shifting the gui over to the right when you have potion effects, and JEI doesn't have enough space so it hides itself.
I fixed this in 1.9 by preventing the gui from being moved. Unfortunately 1.8.9 doesn't have the hook required to do that.
