### ISSUE TITLE
[Bug]: JEI not showing crafting table recipes in Valhelsia 3 modpack in multiplayer

### ISSUE THREAD

**Issue by ChewyBacon1** [mezz/JustEnoughItems#2970]
### Steps to Reproduce the Bug

Open JEI and left or right clicking items does not show how to craft or what the item is used in.

### Expected Behavior

JEI should show recipe for the items

### Actual Behavior

Other special recipes show up but none of the ones that you make in the crafting tables

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/valhelsia-3

### Mod Pack Version (Optional)

3.5.1

### Extra Notes (Optional)

Works fine in single player but not multiplayer. Other players on the server have no issue

### latest.log

https://gist.github.com/ChewyBacon1/b0a5ea53febc539b207bf570709023d7

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately it looks like this log is from some other time, where you didn't join a world yet, so JEI has not started.
Can you include a log here from a time that you encountered this issue?

**Comment by ChewyBacon1** [comment]
Sorry about that. It was the current one in the folder. How about this one.
[latest.log](https://github.com/mezz/JustEnoughItems/files/9448568/latest.log)

**Comment by mezz** [comment]
Thanks, that's better.
Try removing JustEnoughResources and see what happens, it seems like it might be causing problems with some other mods. If it's still broken, I can take a look at the new log to see if there's anything else.

**Comment by ChewyBacon1** [comment]
[latest.log](https://github.com/mezz/JustEnoughItems/files/9449433/latest.log)

Removed but still having the issue

**Comment by mezz** [comment]
Hmm dang, you were able to get rid of the crash I saw in the log, but I guess something else is going wrong.
Unfortunately I don't see anything else interesting in the log, you may need to try removing some mods to see what might eb conflicting.

**Comment by ChewyBacon1** [comment]
Found the issue. Updated Tinker's construct to the newest version. Thanks for the super quick responses Mezz.

**Comment by mezz** [comment]
Nice, glad you figured it out. Thanks for posting the solution, someone else may need it some day.
