### ISSUE TITLE
[Bug]: Select all does not work while inside a Refined Storage grid

### ISSUE THREAD

**Issue by MarioSMB** [mezz/JustEnoughItems#2975]
### Steps to Reproduce the Bug

Not sure if this is RS's doing, but when you're inside a grid or crafting grid and switch to JEI's search menu, you're unable to use CTRL+A to select all, it only directs the cursor to the end of the current text.

### Expected Behavior

CTRL+A should select all existing text in the JEI search bar.

### Actual Behavior

The cursor is moved to the end of the existing text in the search bar.

**Comment by mezz** [comment]
Thanks for the report!
Could you report this to Refined Storage and link back to this issue? They may have a better idea of what's happening and we can collaborate on a fix.

**Comment by MarioSMB** [comment]
Refined Storage's team decided this isn't an issue they wish to help resolve, given the similarities to other recent issues is this not something that can be solved on JEI's end?

**Comment by razgriz5000** [comment]
I have the same problem with JEI in ATM7 To The Sky which does not have refined storage as a mod.

**Comment by mezz** [comment]
Thanks for the report!
This was a bit complicated, but it should be resolved by the next version of JEI.
See here for more details about the bug https://github.com/mezz/JustEnoughItems/issues/3009
