### ISSUE TITLE
[Other]: Fabric: fluid rendering should use FluidVariantRendering

### ISSUE THREAD

**Issue by TropheusJ** [mezz/JustEnoughItems#2976]
### Other

[Here](https://github.com/mezz/JustEnoughItems/blob/60e90315a4d326f079334aea1aab964268614e0c/Fabric/src/main/java/mezz/jei/fabric/platform/FluidHelper.java#L65) the color of a fluid ingredient is determined with the fluid's `FluidRenderHandler`. Using the `FluidVariantRenderHandler` through `FluidVariantRendering` lets the fluid take NBT into account.
![image](https://user-images.githubusercontent.com/60247969/187739542-3f0b281f-3ad5-46b7-a067-ee90fa60764d.png)
This appears correctly on Forge and with EMI:
![image](https://user-images.githubusercontent.com/60247969/187739704-819eb276-81fb-44ad-a0ca-0b9db67dcb58.png)

FluidVariantRendering should also be used to provide default tooltips for fluids [here](https://github.com/mezz/JustEnoughItems/blob/60e90315a4d326f079334aea1aab964268614e0c/Common/src/main/java/mezz/jei/common/render/FluidTankRenderer.java#L163).

**Comment by mezz** [comment]
Thanks for the report! 
This should be fixed in the next release of JEI.
