### ISSUE TITLE
[Bug]: 1.19.2 - non fatal errors on dedicated server when deleting items

### ISSUE THREAD

**Issue by desht** [mezz/JustEnoughItems#2978]
### Steps to Reproduce the Bug

1. Be an op, and enabled JEI admin mode (red spanner icon)
2. Try to delete an item by dragging it into the JEI items tray on the right

### Expected Behavior

Item to be deleted 

### Actual Behavior

Item does appear to be deleted successfully, but the linked stacktrace is logged in the dedicated server log:

https://gist.github.com/desht/d3f124b27512ff092d2aecb1a54a2597

Looks like a reference to the client only `LocalPlayer`.  Using JEI 11.2.0.256 here. Similar issue to #2899, it would appear.

**Comment by mezz** [comment]
Thanks for the report!
I have fixed this bug and made the code around this a little more robust, so it shouldn't be as easy to make server-side mistakes with the platform handlers.
