### ISSUE TITLE
[Bug][Fabric][1.19.2]: Text in search bar cannot be deleted (back space not working).

### ISSUE THREAD

**Issue by Terminal-Access** [mezz/JustEnoughItems#2979]
### Steps to Reproduce the Bug

Unable to delete (using backspace) any text once it's typed intop the search bar.

### Expected Behavior

using the backspace key allows you to remove text in the search bar.

### Actual Behavior

pressing backspace dose absolutely nothing.

### Extra Notes (Optional)

No stack errors or trace logs to send.

**Comment by mezz** [comment]
Thanks for the report!
This is working with with just JEI installed, you must have a mod conflict. 
Please try removing mods to see which one is causing the conflict so that we can fix the issue.

**Comment by Terminal-Access** [comment]
Appeasrs to be the mod [Debugify v2.5.0](https://www.curseforge.com/minecraft/mc-mods/debugify)

Edit: Just going to go through its options and switch things off one by one to see if it's a specific part / bug fix they are offering.

**Comment by Terminal-Access** [comment]
Updatre: It appears to be MC-147605 - Fix for "Text Cursors can exist in multiple fields" causing the issue from that mod.

**Comment by mezz** [comment]
Is this fixed by updating Debugify to the latest version? They fixed a similar bug here: https://github.com/isXander/Debugify/issues/74

**Comment by Terminal-Access** [comment]
> Is this fixed by updating Debugify to the latest version? They fixed a similar bug here: [isXander/Debugify#74](https://github.com/isXander/Debugify/issues/74)

As stated above using debugify v2.5.0 for fabric that is currently the latest version. and the bug is present.

**Comment by mezz** [comment]
Ok, thanks for confirming. 
In that case, can you please open a new issue with them and link back here?

**Comment by isXander** [comment]
Can be closed!
