### ISSUE TITLE
[Crash]: crash-2022-09-08_00.26.47-client.txt

### ISSUE THREAD

**Issue by supernmgirl** [mezz/JustEnoughItems#2984]
### Steps to Reproduce the Crash

I'm using curse forge to play a mod pack called MC Eternal and every time the mod pack finishes loading it keeps giving me this error. How do I fix this?

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/minecraft-eternal

### Mod Pack Version (Optional)

1.12.2 minecraft

### Crash Report

crash-2022-09-08_00.26.47-client.txt

**Comment by mezz** [comment]
Thanks for the report!
It looks like your crash log was not linked, please upload it to https://gist.github.com/ and link the gist's url here so I can take a look.
