### ISSUE TITLE
[Bug]: Currently facing issue that was once patched

### ISSUE THREAD

**Issue by yo1nkers** [mezz/JustEnoughItems#2985]
### Steps to Reproduce the Bug

This is my first ever post on github so please don't expect a perfect description, but I was searching over the issue and found out that the issue had been recreated here;
https://github.com/mezz/JustEnoughItems/issues/2672

Each time I go into a server which is hosted from my own network, it appears JEI will not spawn items in survival, regardless of the fact I am already an Operator in the server.

### Expected Behavior

I'm just expecting it to work for me as it has in the past, most notably over singleplayer or forge servers.

### Actual Behavior

No item will spawn.

### Extra Notes (Optional)

3 notes over log

### latest.log

https://gist.github.com/yo1nkers/b6965407c751498c5f77d4359b0e00ca

**Comment by mezz** [comment]
Thanks for the report!
It looks like you are using a file named `jei-1.19.jar` but I have not published anything using that file name.

Please try downloading the latest version from CurseForge, remove your other mods, and see if that fixes the problem or if it's still present.

**Comment by yo1nkers** [comment]
Hi, the jar file was just renamed to remove the JEI version but I was sure you could still find it.

In any event if you cannot, I'll be returning home in a short hour and will post another comment letting you know if the file version fixes it.

Thanks for the quick reply.

**Comment by SamuelRUM** [comment]
Hello! Opening this up again I'm having the same issue with a custom modpack im creating. I am using jei-1.18.2-forge-10.2.1.283.jar.
Only occurs when in survival, even with cheat mode. Server is modded (obviously) 
No problems in creative mode.
