### ISSUE TITLE
Multiple IAdvancedGuiHandler's don't work together

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#299]
I'm writing a neat gui addition (a widget if you want to call it so), which is added (via events and other hackery) to all GuiContainer's.
I've registered IAdvancedGuiHandler<GuiContainer>, and it works nicely.
However, i've noticed in JEI code that if some mod (eg TE and so on) adds his own handler to their specific gui it wouldn't work, because JEI [picks](https://github.com/mezz/JustEnoughItems/blob/8b8ca69dd33af029159f4224c754ea3ce83b8160/src/main/java/mezz/jei/gui/ItemListOverlay.java#L162) the first handler and doesn't compose them.

So this is not a found bug but predicted one :)

**Comment by mezz** [comment]
Thanks for the report!
How would you propose handling it? I'm not very clear on what your handler would do or how it would work alongside the existing one, do you have a code example?

**Comment by ghost** [comment]
You can get a list of accepted handlers instead of just one ([here](https://github.com/mezz/JustEnoughItems/blob/8b8ca69dd33af029159f4224c754ea3ce83b8160/src/main/java/mezz/jei/gui/ItemListOverlay.java#L104)) and then just add rectangles from all of them to one list (`guiAreas` in your code).
Writing a snippet right now to show what i mean properly.

**Comment by mezz** [comment]
Oh I see. I thought you wanted yours to be able to always replace the existing one. Thanks.

**Comment by ghost** [comment]
Well, i've managed to do this so far in notepad =P
No needed now since you understood :)

``` java
    @Nonnull
    private List<IAdvancedGuiHandler<?>> getAdvancedGuiHandlers(@Nonnull GuiScreen guiScreen) {
        List<IAdvancedGuiHandler<?>> handlers = new ArrayList<IAdvancedGuiHandler<?>>();
        if (guiScreen instanceof GuiContainer) {
            GuiContainer guiContainer = (GuiContainer) guiScreen;
            for (IAdvancedGuiHandler<?> advancedGuiHandler : advancedGuiHandlers) {
                if (advancedGuiHandler.getGuiContainerClass().isAssignableFrom(guiContainer.getClass())) {
                    handlers.add(advancedGuiHandler);
                }
            }
        }
        return handlers;
    }
```
