### ISSUE TITLE
[Bug]: JEI calls `onRuntimeAvailable` in the wrong thread in `/reload` on Fabric

### ISSUE THREAD

**Issue by Technici4n** [mezz/JustEnoughItems#2991]
### Steps to Reproduce the Bug

Call `jeiRuntime.getIngredientManager().removeIngredientsAtRuntime()` inside of `onRuntimeAvailable` in a plugin (just install AE2 to check), run `/reload`, and notice that it complains because this is being called from the wrong thread.

### Expected Behavior

No error in the console.

### Actual Behavior

Following error appears:
![image](https://user-images.githubusercontent.com/13494793/190458144-3063a390-926e-4c93-a466-3761c6c49b2f.png)

Relevant code: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/7d400bb91c6b40dc27a6574f28a28eb96841bc24/src/main/java/appeng/integration/modules/jei/JEIPlugin.java#L257.

### Extra Notes (Optional)

I think JEI is incorrectly reloading the plugins on the server thread instead of the client thread (could be to avoid visible lag?).

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest versions for Fabric.
