### ISSUE TITLE
[Bug]: Forge extended CraftingRecipe sizes cause recipe validation explosion.

### ISSUE THREAD

**Issue by covers1624** [mezz/JustEnoughItems#2993]
### Steps to Reproduce the Bug

1, Call `ShapedRecipe.setCraftingSize(9, 9);`
2, Add a recipe that uses this new size under the vanilla crafting recipe type.
3, Load into a world, note explosion in the console from recipe validation failing

### Expected Behavior

No explosion :)

### Actual Behavior

Explosion in console :)

### Extra Notes (Optional)

Vanilla handles this recipe fine, it is completely ignored by the other tables as it has all the built-in logic required for different recipe sizes. My custom table, which has the correct grid size, works as expected with this recipe and any vanilla recipes.

### latest.log

https://gist.github.com/covers1624/a00d97b4e7559361e64aafda5decb8df

**Comment by mezz** [comment]
Thanks for the report!
I have reduced these to `debug` logs instead of `error`.
