### ISSUE TITLE
[Bug][1.19.2]: Cheat Mode doesn't seem to work

### ISSUE THREAD

**Issue by nskobelevs** [mezz/JustEnoughItems#2994]
### Steps to Reproduce the Bug

1. Install JEI
2. Create world in Creative mode
3. Try to give yourself items from the JEI menu

### Expected Behavior

Items should be given to the player in the inventory, or "grabbed" into the mouse.

### Actual Behavior

The recipe is shown if available, otherwise nothing.

### Extra Notes (Optional)

I'm sorry if I'm missing something but I can't figure out why it's not working or what I'm doing wrong.
I've tried with and without Configured mod.
I've no other mods installed.
The config menu has all the cheats enabled.

<img width="966" alt="Screenshot 2022-09-21 at 18 54 48" src="https://user-images.githubusercontent.com/34107736/191576773-7477fe43-2de5-493b-b2da-39da94eb4860.png">

I've tried shift clicking, option clicking, control clicking. Everything I could think of that you'd expect to work.

Minecraft Version: 1.19.2
Forge Version: 43.1.1.
JEI Version: jei-1.19.2-forge-11.3.0.262

### latest.log

https://mclo.gs/eUHSV4p

**Comment by cmar7945** [comment]
This has occured for me as well, i seem to be able to grab items by shift clicking, which grabs a stack for a second, or if i right click i can only grab a max of two items before they get deleted by another click. this seems like a major bug to me. but thats up to them to figure out tbh.

**Comment by P3rf3ctXZer0** [comment]
Oh good I am not the only one XD https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/14 can you grab a single item IE right click?

**Comment by nskobelevs** [comment]
> Oh good I am not the only one XD [P3rf3ctXZer0/Fiction.Friction#14](https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/14) can you grab a single item IE right click?

No can do, it just tries to show the usage of the item if I right click.

**Comment by P3rf3ctXZer0** [comment]
So it turns out for me it was a keybinding thing. I changed 1 stack to left click and bound it twice and then 1 item to right click make sure you bind both variants.
