### ISSUE TITLE
[Bug]: Changing Key Bindings doesn't work in Fabric

### ISSUE THREAD

**Issue by audaki** [mezz/JustEnoughItems#3000]
### Steps to Reproduce the Bug

Use JEI in Fabric, try to change key bindings

### Expected Behavior

I should be able to see/change key bindings in game -> options (with Fabric)

### Actual Behavior

The Key Bindings are *not* in the Options.

Finally as a last resort I tried to copy the settings from options.txt from a Forge Install into the Minecraft options.txt in the Fabric Install and even this didn't work. So it seems like not only are the key bindings not shown, additionally they are not even read from the options file.

### Mod Pack Version

jei-1.19.2-fabric-11.3.0.262 in Minecraft 1.19.2

**Comment by mezz** [comment]
This has been implemented in JEI 
for 1.20.1: `15.18.0.80`+
and 1.21.1: `19.17.0.196`+
