### ISSUE TITLE
[Crash]: crash-2022-9-28 14.52.59-clinent.txt

### ISSUE THREAD

**Issue by i7oody1** [mezz/JustEnoughItems#3001]
### Steps to Reproduce the Crash

I'm using curse forge to play a mod pack called Dungeons, Dragons and Space Shuttles and every time its finish loading its gives me an  this error .What should I do to fix this?

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles

### Mod Pack Version (Optional)

1.12.2 minecraft

### Crash Report

https://gist.github.com/i7oody1/ff5cac42a04d355fd42735f68b115f19

**Comment by mezz** [comment]
Thanks for the report!
> java.lang.OutOfMemoryError: GC overhead limit exceeded

You are running out of RAM. You will need to allocate more memory to Java, or use a mod pack with fewer mods.
