### ISSUE TITLE
[Crash]: start game is fail

### ISSUE THREAD

**Issue by skyhhjmk** [mezz/JustEnoughItems#3004]
### Steps to Reproduce the Crash

1,i download this mod on github.
2,i use "Plain Craft Launcher 2" to start the game.
now the game can not start

### Mod Pack Version (Optional)

game:1.19.2     mod:jei-1.19.2-fabric-11.3.0.260

### Extra Notes (Optional)

the url is a logs zip on onedrive https://1drv.ms/u/s!ArsTAzWCgGnMgjRqdguS_li-zRFg?e=0gF4TZ

### Crash Report

https://1drv.ms/u/s!ArsTAzWCgGnMgjRqdguS_li-zRFg?e=0gF4TZ

**Comment by mezz** [comment]
Thanks for the report!
Please upload your crash log to https://gist.github.com/
For security reasons, I do not want to download a zip file, sorry.

**Comment by skyhhjmk** [comment]
> Thanks for the report!
> Please upload your crash log to https://gist.github.com/
> For security reasons, I do not want to download a zip file, sorry.

i upload it

**Comment by skyhhjmk** [comment]
https://gist.github.com/skyhhjmk/912b05b3827171221aa8ca59ecb709f3

**Comment by mezz** [comment]
Sorry it looks like the text has been cut off before the end, this is not a complete crash log. 
Can you please upload the full crash log and link it here?

**Comment by skyhhjmk** [comment]
> Sorry it looks like the text has been cut off before the end, this is not a complete crash log. 
> Can you please upload the full crash log and link it here?

Sorry, I didn't check the completeness. Please give me some time to find out how to upload the complete file.

**Comment by skyhhjmk** [comment]
> Sorry it looks like the text has been cut off before the end, this is not a complete crash log. Can you please upload the full crash log and link it here?

it is ok now：https://gist.github.com/skyhhjmk/912b05b3827171221aa8ca59ecb709f3

**Comment by mezz** [comment]
It looks like you have JEI and REI installed together, you should try using only one at a time.

**Comment by skyhhjmk** [comment]
> It looks like you have JEI and REI installed together, you should try using only one at a time.

Thank you for your proposal. The problem has been solved.

**Comment by skyhhjmk** [comment]
But if the two are not compatible, why do they appear in an integration package? Maybe the author of the integration package made a mistake? Or can the old version of this mod coexist with it?

**Comment by mezz** [comment]
Yeah, maybe the author made a mistake.

I do not think there is a version that can coexist. 
These mods try to do basically the same thing, so you only need one of them.
