### ISSUE TITLE
[Bug]: create milling doesn't support more than 4 outputs[1.16]

### ISSUE THREAD

**Issue by blockgoblin31** [mezz/JustEnoughItems#3006]
### Steps to Reproduce the Bug

use createtweaker to make a milling recipe with more than 4 outputs

### Expected Behavior

all the items would be within the jei box, and you'd be able to see the item name by hovering over it anywhere

### Actual Behavior

![Screenshot (87)](https://user-images.githubusercontent.com/57573828/193651353-64dbf9e6-88b6-4805-9c87-e500f7a939f3.png)

### Mod Pack URL (Optional)

https://github.com/tuc56/processing-pack

### Extra Notes (Optional)

this is from my personal 1.16 modpack, which is still unfinished. that screenshot has a placeholder input item.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Create or createtweaker, JEI does not manage the code for this plugin directly.
