### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by NewCoder457** [mezz/JustEnoughItems#3008]
### Steps to Reproduce the Crash

Whenever I start the modpack it just crashes, to be honest I don't know if it's from JEI, but inside the crash notes it has JEI inside. if it isn't JEI then please tell me the mod that's causing this issue.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack

### Mod Pack Version (Optional)

1.13.9

### Crash Report

https://gist.github.com/NewCoder457/40cc0726b088b88269ce25fec82c1b43

**Comment by mezz** [comment]
Thanks for the report!
```
Mod File: jei-1.16.5-7.7.1.152.jar
	Failure message: fml.modloading.dupedmod
```

It looks like you probably have two different versions of JEI in your mods folder, and FML is crashing because of it.
