### ISSUE TITLE
[Bug]: returning negative X/Y values from getGuiExtraAreas() causes problems

### ISSUE THREAD

**Issue by desht** [mezz/JustEnoughItems#3009]
### Steps to Reproduce the Bug

As requested in #2986, I'm creating this issue. More technical detail in that issue.

Negative X/Y values in the GUI exclusion areas returned by `IGlobalGuiHandler#getGuiExtraAreas()` get clamped to 0, causing JEI to believe the values are changing on every call, leading to unnecessary updating of the left & right overlays, including resetting of the filter textfield selection (causing Ctrl-A to appear not to work).

### Expected Behavior

See linked issue

### Actual Behavior

See linked issue

### Extra Notes (Optional)
While mods shouldn't really return negative X/Y values (FTB Library currently does, but that will be fixed in next release), bad input is causing subtle problems to ripple across the mod here.

**Comment by mezz** [comment]
Thank you for the report!
