### ISSUE TITLE
When viewing a recipe with JEI, disable cheat mode

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#301]
A small difference from NEI I noticed which keeps throwing me off, in NEI when viewing a recipe it would automatically use recipe mode, so if you click on an item in JEI while viewing a recipe, it would be nice if it would use the recipe function rather than the cheat function. I really miss this feature :P

**Comment by mezz** [comment]
Interesting, I wasn't aware of that.

**Comment by ZeRT1337** [comment]
the cheat function doesn't work for me
