### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Llama0319** [mezz/JustEnoughItems#3010]
### Steps to Reproduce the Crash

1. Launching the game
2. Wait a little bit
3. gets stuck on Finishing up

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/building-exploration-and-animals

### Mod Pack Version (Optional)

1.1.3

### Extra Notes (Optional)

Its my modpack, works for me but doesn't work for my sister

### Crash Report

https://gist.github.com/Llama0319/10464388c8574fdead70a94f6a1c1cee

**Comment by mezz** [comment]
Thanks for the report!
```
Caused by: java.lang.OutOfMemoryError: Java heap space
```

You are running out of RAM when the game starts.
Please allocate more ram to Minecraft in your game launcher, or remove some mods.
