### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by joe12pro** [mezz/JustEnoughItems#3011]
### Steps to Reproduce the Crash

Open inventory with "e".
Click on JEI search bar (or hit "ctrl+f")

### Extra Notes (Optional)

Does not happen every time and does not seem to be deterministic as far as if I start entering only specific characters into the search bar.
Minecraft Java 1.19.2
jei-1.19.2-forge-11.3.0.262

### Crash Report

https://gist.github.com/joe12pro/c401ac9e588782e0f00527751c9b96f8

**Comment by mezz** [comment]
Thanks for the report!

```
-- Ingredient being rendered --
Details:
	Mod Name: Refined Storage
	Registry Name: refinedstorage:cover
	Display Name: Cover
	String Name: 1 cover
```

Please report this issue to refined storage and link back to this issue.
https://github.com/refinedmods/refinedstorage/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
