### ISSUE TITLE
JEI Wont Download ?

### ISSUE THREAD

**Issue by raturger** [mezz/JustEnoughItems#3013]
### Other

I use fabric to play modded Minecraft, and I wanted to make a personal lettle pack of stuff I like so I could play it. The whole pack is is 1.19.2, and I downloaded another pack just so I could get my hands on JEI in 1.19.2, because the other recipe viewing mod I wanted to use wasn't compatible . I tried to install it, but it told me that I had an incompatible Minecraft version, as well as an incompatible mod loader . (I'm pretty new to this sort of thing, but anything that looked like a mod loader to me that was in my pack was 1.19.2 as well) JEI even seems to work with other mod packs that are in version 1.19.2, so I have no idea what I'm doing wrong . Any ideas ?

**Comment by Jmooroof** [comment]
JEI is on Forge (you are using fabric)

**Comment by mezz** [comment]
Thanks for the report!
There are versions of JEI for Forge and for Fabric, and for many different versions of Minecraft.
The error is saying you need to find JEI for Fabric on 1.19.2.
