### ISSUE TITLE
[Bug Forge 1.19.2]: Failed to save blacklist to file (error in console when adding item to jei blacklist view)

### ISSUE THREAD

**Issue by Gbergz** [mezz/JustEnoughItems#3014]
### Steps to Reproduce the Bug

Add item to blacklist in JEI while ingame. Through the keybinding.
Item fails to save to blacklist.
Errors.
Check logs.
https://gist.github.com/Gbergz/d589acd5c46e429e59da4af325de9f6e

### Expected Behavior

That the blacklisted item gets saved to blacklist.cfg and gets applied and hidden next restart.

### Actual Behavior

Item does not save and thusfor does not get hidden. Errors in logs.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/tnp-limitless-6

### Mod Pack Version (Optional)

1.0.0

### latest.log

https://gist.github.com/Gbergz/d589acd5c46e429e59da4af325de9f6e

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next version.
