### ISSUE TITLE
[Crash]: 1.9.2 Fabric: OptiFabric, Optifind with JEI

### ISSUE THREAD

**Issue by Ortello** [mezz/JustEnoughItems#3015]
### Steps to Reproduce the Crash

1. Load Optifabric, OptiFine_1.19.2_HD_U_H9, and JEI in a custom modpack with Fabric. Just those mods.
2. Try to run the game.
3. It crashes.

### Crash Report

https://gist.github.com/Ortello/2e239c2906925984773642c05bb1c7e0

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Optifabric and link back here. I think they will be better able to understand and debug this issue.
