### ISSUE TITLE
[Bug]: Can't type anyting on search bar

### ISSUE THREAD

**Issue by Psychodeus** [mezz/JustEnoughItems#3016]
### Steps to Reproduce the Bug

-

### Expected Behavior

-

### Actual Behavior

-

### Extra Notes (Optional)

![image](https://user-images.githubusercontent.com/93028949/195903899-89a2f112-1e0a-4f69-99ba-493ceec9fae2.png)
Post installing JEI I add those 3 mods, then the issue happened, I couldn't input anything on search bar.
It works fine when I installed JEI with my previous mods, only happened recently.

Please also add config to keybind so I could have my own preference (Fabric). Right now it overlap with one of my weapon button (R).

[latest.log](https://github.com/mezz/JustEnoughItems/files/9788664/latest.log)

Thank youuu!

### latest.log

https://github.com/mezz/JustEnoughItems/files/9788664/latest.log

**Comment by mezz** [comment]
Thanks for the report!
We've had issues with Debugify in the past, can you try removing it or seeing if they have an updated version?

**Comment by Psychodeus** [comment]
It's working without debugify.
![2022-10-16_02 28 29](https://user-images.githubusercontent.com/93028949/196002500-983cebc5-418c-4f83-b46f-39dbd44679a5.png)
I'm using latest debugify.
[latest.log](https://github.com/mezz/JustEnoughItems/files/9792843/latest.log)

**Comment by mezz** [comment]
Thank you for confirming!
Please report this issue to Debugify and link back to this issue.

**Comment by mezz** [comment]
btw here's the real results of your Shrek search https://www.youtube.com/watch?v=mNFx28NGLfI

**Comment by Psychodeus** [comment]
> btw here's the real results of your Shrek search https://www.youtube.com/watch?v=mNFx28NGLfI

LMAO
![a6p04P9X_700w_0](https://user-images.githubusercontent.com/93028949/196014347-15590149-ebb9-41cc-80ef-9ec515deb717.jpg)

**Comment by Daihok41** [comment]
I am getting this problem in the 1.19.2 fabric version It will save world and crash with specific letters typed in or combination of letters.

**Comment by SuperStormer** [comment]
FWIW, JEI 11.4.0.284 and Debugify 2.8.0 still has the same bug.

**Comment by mezz** [comment]
Let's follow the Debugify issue here: https://github.com/isXander/Debugify/issues/169
