### ISSUE TITLE
[Suggestion]: Villager support

### ISSUE THREAD

**Issue by iTaeyeonKim** [mezz/JustEnoughItems#3017]
### Suggestion

Hello.

Would it be possible to add Villager trades into this mod? I think that would be awesome if it's of course possible to do so.
If click on emerald for example, to show what you can trade with emerald.

Thanks in advance and have a nice day! :)

**Comment by mezz** [comment]
Thanks for the suggestion!
This feature is covered by JER (Just Enough Resources). It is an addon mod for JEI that adds recipes like these.
https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
