### ISSUE TITLE
[Bug]: Latest update causes connection lose when opening an existing world

### ISSUE THREAD

**Issue by dreaderinyes** [mezz/JustEnoughItems#3019]
### Steps to Reproduce the Bug

1. create world
2. close world
3. attempt to reopen world

### Expected Behavior

Connect to world and continue playing

### Actual Behavior

game loads world then crashed and gives error : 
Connection Lost Internal Exception: io-netty-handler.codec-DecoderException: java.lang-NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.MinecraFt-m_91403_()" is null Back to Server List

### Extra Notes (Optional)

I reverted jei version to previous update and the problem fixed itself. I got this bug while using version 11.3.0.271

**Comment by Zelioth** [comment]
Just some advice to help with the issue. please list all versions of everything you are playing with. What other mods do you have, what modpack/custom pack? etc.
