### ISSUE TITLE
Crash when typing in search 

### ISSUE THREAD

**Issue by sidius79** [mezz/JustEnoughItems#302]
https://gist.github.com/sidius79/b730895e87d94b9b1a37df4a8c665e50

this is the link to the crash report i think it is a JEI crash i was trying to type something in the search bar and keep crashing everytime i do please help me to fix this thank you

**Comment by way2muchnoise** [comment]
`at com.InfinityRaider.maneuvergear.render.tessellation.TessellatorAbstractBase.<clinit>(TessellatorAbstractBase.java:32)`

Not cause by JEI but maneuver gear (?)

**Comment by sidius79** [comment]
ok thank you

**Comment by mezz** [comment]
Thanks! 
Link to the report: https://github.com/InfinityRaider/3DManeuverGear/issues/6
