### ISSUE TITLE
{ Had Enough Items } Crash when pressing Shift + 3 ( this gives You # symbol )

### ISSUE THREAD

**Issue by Kasia1403** [mezz/JustEnoughItems#3020]
[crash-2022-10-17_12.21.21-client.txt](https://github.com/mezz/JustEnoughItems/files/9800418/crash-2022-10-17_12.21.21-client.txt)
[crash-2022-10-17_08.42.46-client.txt](https://github.com/mezz/JustEnoughItems/files/9800419/crash-2022-10-17_08.42.46-client.txt)

**Comment by Kasia1403** [comment]
This is Had Enough Items crash, not Just Enough Items, but HEI author hasn't Github Issues page.

**Comment by mezz** [comment]
Sorry, this is not the right place to report your issue. I am not involved with that project. 
You can probably find them on Discord to send your report.
