### ISSUE TITLE
[Crash]: fml.modloading.dupemod

### ISSUE THREAD

**Issue by AiramZt** [mezz/JustEnoughItems#3021]
### Steps to Reproduce the Crash

Whenever I launch my minecraft, this message shows. I really don't know why is it happening.

I use TLauncher, version Forge OptiFine 1.16.5. Not only that, but I downloaded the version it is supposed for that version.
I don't know what else to do.

[crash-2022-10-18_16.29.56-fml.txt](https://github.com/mezz/JustEnoughItems/files/9815525/crash-2022-10-18_16.29.56-fml.txt)

### Mod Pack URL (Optional)

https://zonacraft.net/just-enough-items/

### Crash Report

https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue

**Comment by samueleitorme** [comment]
I have the same problem 😞

**Comment by mezz** [comment]
Thanks for the report!
`fml.modloading.dupedmod` means that the Forge Mod Loader has found more than one version of JEI in your `mods` folder. Please make sure there is only one, and the issue should be resolved.
