### ISSUE TITLE
[Other]: 

### ISSUE THREAD

**Issue by DAmanc123** [mezz/JustEnoughItems#3023]
### Other Crash when loading and with no crash report

hello,my game just logged when i was loading JEI,no crash report,it just stucked in this step,and i dont know if this is a bug or something else.my game version is 1.12.2 Forge version is 2855,do you know how to fix this?plz help me
![QQ图片20221020204328](https://user-images.githubusercontent.com/116050460/196952645-baf5eed5-2e81-427b-a37f-41ff655a1c21.png)

**Comment by DAmanc123** [comment]
btw my JEI is the latest version

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

Also, do you have any `hs_err_pid.log` in your minecraft folder?

**Comment by DAmanc123** [comment]
actually i change an another jei version after this,then the game didnt crash in this process,but it loaded really slowy during loading recipes,it literally takes ten minutes to load just one recipe just like what happened in the following photo,do you know how to speed this up?
![issues pic](https://user-images.githubusercontent.com/116050460/198923675-a34039b0-1d1f-4ec0-bf3a-068a1a355e15.png)

**Comment by mezz** [comment]
You are almost running out of Memory (see the red line on the right side of the memory bar, you are hitting the maximum).

When you are low on Memory like this, the game will run extremely slowly. It is constantly spending time to free up memory, which makes it run very slowly overall.
You can fix the issue by removing some mods or by giving more Memory to Java.

**Comment by DAmanc123** [comment]
ok ill try it
