### ISSUE TITLE
Cant ctrl + a

### ISSUE THREAD

**Issue by CannyFabrics** [mezz/JustEnoughItems#3024]
### Steps to Reproduce the Bug

Ctrl + a at search

### Expected Behavior

What should happen when i press ctrl + a is select all the written things to search

### Actual Behavior

So when i press ctrl + a at search nothing happens.

### Extra Notes (Optional)

it is my own modpack but it seems like it happens at other modpacks too. I want a version that works.

**Comment by mezz** [comment]
Thanks for the report!
This is probably a duplicate of https://github.com/mezz/JustEnoughItems/issues/2807 and https://github.com/mezz/JustEnoughItems/issues/3009
It has been fixed by JEI in the latest versions.
