### ISSUE TITLE
[Crash]: Minecraft dies after clicking any title screen button

### ISSUE THREAD

**Issue by Jmooroof** [mezz/JustEnoughItems#3025]
### Steps to Reproduce the Crash

1. press any title screen button

### Extra Notes (Optional)

I was running this with Just Enough Resources. I think it was this mod that was casuing it because of this line: "java.lang.NoClassDefFoundError: mezz/jei/gui/recipes/RecipesGui"

### Crash Report

https://gist.github.com/Jmooroof/e77afd6511b598d889876e848e5d0ed7

**Comment by Jmooroof** [comment]
it isn't being caused by just enough resources
i tried it without that mod

**Comment by mezz** [comment]
Thanks for the report!
Based on the crash log, this is caused by lowdragmc.lowdraglib, reported here: https://github.com/Low-Drag-MC/LDLib/issues/2
It looks like you can fix the issue by updating that mod or removing it.
