### ISSUE TITLE
[Suggestion]: Recipes for Better End, Farmer's Delight, Spirit

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#3027]
### Suggestion

JEI doesn't seem to show recipes for following workstations in Farmer's Delight and Better End:
Farmer's Delight - Cooking Pot
Better End - Infusion Pedestal
Better End - Anvils (Thallasium Anvil, Terminite Anvil, Aeternium Anvil)
Better Nether also has an anvil but I didn't test if those recipes are missing too.
EDIT: Recipes from the mod Spirit that require soul engulfing seem to be incompatible, too.

Since these mods are becoming more popular, I think this would be a great addition to this mod.

Reproduction Steps
Open Inventory
2a e.g. left click the "Noodle Soup" (Farmer's Delight)
2b e.g. left click the "Crystalite Elytra" (Better End)
2c e.g. left click the "Terminite Forged Plate" (Better End)

What I expect to see (Screenshots were made with Roughly Enough Items):

Example 2a)
![image](https://user-images.githubusercontent.com/82583202/197634174-f14f4f51-be8b-425a-a78a-be80ca345139.png)

Example 2b)
![image](https://user-images.githubusercontent.com/82583202/197634206-bf786506-a510-41a7-94ab-d69a3460e3cb.png)

Example 2c)
![image](https://user-images.githubusercontent.com/82583202/197634227-2fa5be79-f902-4bf8-a571-d89441368a0a.png)

**Comment by mezz** [comment]
Thanks for the report!
Support for mods is added by the mods themselves, support is not directly added inside JEI itself. 
I provide an API for other mods to add their recipes to JEI. Please report this to each respective mod so that they can make sure their recipes are displayed in JEI.
