### ISSUE TITLE
1.19.2 Server Side Crash - "Polymorph has a conflict with ``Bigger Stacks, JEI, Polymorph, Visual Workbench``"

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#3028]
### Steps to Reproduce the Crash

https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/17

### Mod Pack Version (Optional)

https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/17

### Extra Notes (Optional)

https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/17

### Crash Report

https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/17

**Comment by mezz** [comment]
Thanks for the report!
Based on the crash log, it does not look like JEI is involved in this bug. Please make sure to report this to Polymorph.

**Comment by P3rf3ctXZer0** [comment]
The owner straight up told me it was not theirs either XD I had a strong feeling from the beginning it was Polymoprh.

**Comment by mezz** [comment]
Please make sure to link back to this issue, it can be helpful to have mod authors discuss an issue like this instead of having you stuck in the middle. Maybe it's some 3rd mod, I'm not sure but we can find out.

**Comment by P3rf3ctXZer0** [comment]
It most likely is but I now consider the crash stale. I don't have time to deal with it. Thanks for your help.
