### ISSUE TITLE
[Bug]: JEI Fabric does not remap

### ISSUE THREAD

**Issue by vaylor27** [mezz/JustEnoughItems#3029]
### Steps to Reproduce the Bug

1. Install JEI api for fabric
2. It will not remap to yarn
<img width="636" alt="Screen Shot 2022-10-26 at 21 04 36" src="https://user-images.githubusercontent.com/89393811/198167052-ab894a00-55f7-40b0-8557-9aed41d64a13.png">

### Expected Behavior

It remaps

### Actual Behavior

It does not remap

**Comment by onyxromero** [comment]
Same issue is happening with me. Someone please respond to this issue.
