### ISSUE TITLE
[1.9.4] Client crash when viewing Tin Ore uses.

### ISSUE THREAD

**Issue by Xiaminou** [mezz/JustEnoughItems#303]
Crash Report: http://pastebin.com/gGeAn1X2

I'm able to view the simple smelting recipe but when I click the right arrow it crashes.
I know it's not actually JEI causing the crash, so is it IC² or Ender IO? Apparently there's something wrong with macerator/sag mill's recipes.
Maybe there's a way to add a security to prevent that kind of crash?
Edit: removing IC² fixes the problem. Seems like it only happens if the client has the mod but the server doesn't, unable to reproduce in SSP.

**Comment by mezz** [comment]
Thanks for the report!
Yep this is IC2.
You can tell from this line at the top of the stack trace:
`java.lang.NullPointerException: Item.itemRegistry.getNameForObject returned null for: class ic2.core.item.ItemMulti`

IC2 is just barely out for 1.9.4 so I recommend giving them a little more time to clean up. 
You can help them out by reporting any issues you find here: http://bt.industrial-craft.net/my_view_page.php
