### ISSUE TITLE
Inventory open/close button cannot be written in search bar[Other]: 

### ISSUE THREAD

**Issue by DeKogen** [mezz/JustEnoughItems#3030]
### Other

Inventory open/close button cannot be written in search bar. I have default <e> button set to open/close inventory. So when I trying to type literally anything that include <e> it just close everything... Is it a bug or is there any setting to fix it?

**Comment by mezz** [comment]
Thanks for the report!
This is probably caused by a mod conflict, please try removing other mods to see which one is causing the issue here.
