### ISSUE TITLE
[Other]: 

### ISSUE THREAD

**Issue by Merzmensch** [mezz/JustEnoughItems#3033]
### Other

Hi there!
Doesn't JEI support 1.19.2 Minecraft?
By startup I get an error loading message "Mod JEI requires Minecraft 1.18.2 or above, and below 1.19".

I have Java Edition + Forge, many other mods work.
Thank you!

**Comment by eaglek9** [comment]
same problem here

**Comment by Jmooroof** [comment]
you are supposed to use the 1.19 version of the mod

**Comment by mezz** [comment]
Thanks for the report!
The 1.19.2 version is available on CurseForge here:
https://www.curseforge.com/minecraft/mc-mods/jei/files/all?filter-status=1&filter-game-version=2020709689%3A9366
