### ISSUE TITLE
[Bug]: JEI Menu close when i press my inventory key

### ISSUE THREAD

**Issue by ExodusR** [mezz/JustEnoughItems#3035]
### Steps to Reproduce the Bug

1. Open JEI Menu
2. If I search "Emerald" for example, JEI Menu close when I press the key "e" because "e" is also my key for my inventory

### Expected Behavior

Following the steps to reproduce the bug, JEI should just write the "e" in the research bar

### Actual Behavior

JEI is linked with the inventory so when press the "e" key the inventory + JEI menu close and i'ts impossible to reseach a word with "e"

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/newcraft-fabric

### Mod Pack Version (Optional)

1.19.2

### Extra Notes (Optional)

I play with the modpack : NewCraft 1.19
I say that bug to the creator, he say's me he knows the bug and i have to ask you
(I'm French so sorry for my bad English)

### latest.log

https://gist.github.com/ExodusR/fc02d02de0daf34c2de271d2a053a522

**Comment by mezz** [comment]
Thanks for the report!
I think this is caused by a mod conflict, it does not happen with JEI alone.
Please try removing mods to figure out which mod is conflicting so that we can submit a bug report or fix the issue.

**Comment by SuperStormer** [comment]
Appears to be https://github.com/isXander/Debugify/issues/74 ? (or at least, a similar issue)

**Comment by SuperStormer** [comment]
In attempting to reproduce the issue with the latest version of Debugify and JEI, I found a similar but different bug: #3039.

**Comment by ExodusR** [comment]
I have disabled the patch for [MC-147605](https://bugs.mojang.com/browse/MC-147605) in Debugify settings and it resolves this issue for me

**Comment by mezz** [comment]
Thank you for posting the workaround. 
Please report this to Debugify to make sure they know there is a problem again, and link back here.
