### ISSUE TITLE
Singleplayer - No Permission

### ISSUE THREAD

**Issue by billybag** [mezz/JustEnoughItems#304]
"You do not have permission to use this command" while in single player and i have searched through config files and tried to op myself and i cannot fix it.

**Comment by p455w0rd** [comment]
did you set cheat mode to true when you created the world?

**Comment by billybag** [comment]
oh my glob i am such an idiot. You're right, i forgot about that option (playing MC again after a year's hiatus)  Thank you!

**Comment by p455w0rd** [comment]
please close the issue :)
