### ISSUE TITLE
[Bug]: 1.18.2 Can't save blacklist

### ISSUE THREAD

**Issue by evanbones** [mezz/JustEnoughItems#3043]
### Steps to Reproduce the Bug

1. Turn on Edit mode
2. Try to hide items from JEI
3. Error

### Expected Behavior

JEI should just save the file

### Actual Behavior

An error is thrown and the file doesn't save

### latest.log

https://gist.github.com/evanbones/f74e7a9273a44e789b7d601d839f854c

**Comment by psvmsa** [comment]
I found a temporary workaround. It seems **JEI doesn't want to overwrite** the blacklist but **is fine with saving it** if it can't find one. Thus we can:

1. Turn on Edit Mode and make your desired changes.
2. Delete blacklist.cfg (might want to make a backup lol)
3. Hide and unhide any item (this forces JEI to remake the blacklist)
4. Turn off Edit Mode
5. Blacklist.cfg should be back and contain your previous blacklist plus the changes made

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the latest version for 1.18.2.
