### ISSUE TITLE
[Bug]: Bookmarks do not persist upon rejoining a server

### ISSUE THREAD

**Issue by ChiefArug** [mezz/JustEnoughItems#3044]
### Steps to Reproduce the Bug

Join a server with JEI installed on the client
Bookmark an item.
Leave the server
Rejoin the server
See the item is no longer bookmarked

### Expected Behavior

The bookmark should persist across server rejoins

### Actual Behavior

The bookmarks.ini file for that server is overwritten each rejoin, resetting the bookmarks.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/spookyjam-2022-forge/

### Mod Pack Version (Optional)

1.0.4

### latest.log

https://gist.github.com/ChiefArug/c8dab1f6036175e50bb974c898effe74

**Comment by mezz** [comment]
Thanks for the report!
Can you try with the latest version of JEI (`11.5.2.1005`) and see if it fixes the issue for you?
If not, can you reply with the latest.log with that version?

**Comment by ChiefArug** [comment]
Yep, works as expected with `jei-1.19.2-forge-11.5.2.1007.jar`, the bookmarks persist across rejoins and restarts.

**Comment by mezz** [comment]
Thanks for confirming!
