### ISSUE TITLE
[Crash]: crash on startup when in workspace enviroment

### ISSUE THREAD

**Issue by kuba26038** [mezz/JustEnoughItems#3049]
### Steps to Reproduce the Crash

1- have the latest 1.19.2 jei mod file downloaded from curseforge in your project/run/mods folder
2- attempt launching the game

### Extra Notes (Optional)

i have seen other reports like the one you see right here, but none of the fixes provided in them seemed to work on 1.19.2. i tried using this line as a dependency: 

	implementation fg.deobf("curse.maven:jei-238222:4087658")

but it didn't do anything, unfortunately. i also tried using: 

	compileOnly fg.deobf("mezz.jei:jei_${mc_version}:${jei_version}:api")
	runtimeOnly fg.deobf("mezz.jei:jei_${mc_version}:${jei_version}")

but that just threw an error stating "Could not resolve all files for configuration ':runtimeClasspathCopy'." i basically ran out of ideas, so here i am, please help

### Crash Report

https://pastebin.com/bMickfJA

**Comment by mezz** [comment]
Thanks for the question!
I have a JEI Wiki on GitHub here that explains how to get set up. 
You can find some documentation for this part here:
https://github.com/mezz/JustEnoughItems/wiki/Getting-Started-%5BJEI-10-or-higher-for-Forge-or-Fabric%5D

**Comment by mezz** [comment]
For real-time help with questions, you can join the Discord server here: https://discord.gg/sCQcWU2
