### ISSUE TITLE
Jei Crash on Startup or Time Out Loop

### ISSUE THREAD

**Issue by captcookie** [mezz/JustEnoughItems#305]
1.9.4 Multiplayer
Clients have a delayed login (always times out upon installation) then may time out after second login. During game play, may crash them to the launcher. Here are some reports to verify the crash. 

https://cdn.discordapp.com/attachments/166151363397419019/189510506166484993/crash-2016-06-06_18.32.09-client.txt 
https://shrib.com/q214C9HY2lRVSOl?v=nc 
[crash-2016-06-06_18.32.09-client.txt](https://github.com/mezz/JustEnoughItems/files/301796/crash-2016-06-06_18.32.09-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Try out this new version http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2305823
It should run fine, and log an error saying 

> Tried to add a RecipeCategoryCraftingItem with null craftingItem

and include a stack trace that shows which mod is causing the problem.

**Comment by captcookie** [comment]
Ty for the fast reply and working this out. :) you are bae

**Comment by mezz** [comment]
Any luck, or same thing? I may need to add more logging.

**Comment by captcookie** [comment]
Well It timed out still but I'm in my server world. As soon as my mod pack uploads to Dropbox I can see if my friends can login who have been in the crash loop :)

**Comment by captcookie** [comment]
Ok well it seems to be fine for now... and getting people to play after midnight is kinda not working for me. I am about to hit the hay myself. I will update you in the morning. Its 12:20am here. Thanks again. I have a heavy mod pack on technic. Its currently number 2 called The Legend of the Squid if you want to test it yourself you can. Thanks again for all you do. More wrench please! 

    On Monday, June 6, 2016 11:56 PM, Tasha <rynzii15@yahoo.com> wrote:
 

 Well It timed out still but I'm in my server world. As soon as my mod pack uploads to Dropbox I can see if my friends can login who have been in the crash loop :)

Sent from my iPhone
On Jun 6, 2016, at 11:52 PM, mezz <notifications@github.com> wrote:


Any luck, or same thing? I may need to add more logging.—

**Comment by mezz** [comment]
Sure I'll test it out. Just grab the latest JEI in the morning.

**Comment by mezz** [comment]
Looks like the mrriegel.blockdrops mod takes forever then crashes. I recommend removing it and reporting to them, should fix the timeouts.

**Comment by captcookie** [comment]
Right on! It's fixed thanks so much! Everything is running smooth and no timeouts.

**Comment by captcookie** [comment]
I can confirm no more crashes. You fixed it. No one has had anymore multiplayer crashes. Thanks again.
