### ISSUE TITLE
[Crash]: Client crash on server join

### ISSUE THREAD

**Issue by Exophobias** [mezz/JustEnoughItems#3050]
### Steps to Reproduce the Crash

1. Start the game
2. Join my server
3. Client crash

### Mod Pack URL (Optional)

https://gist.github.com/Exophobias/e1bbcfeb9baa9663a9cbe8c62bc3fb29

### Extra Notes (Optional)

This is a custom modpack of mine, and I have not had issues until the most recent version of JEI. It is similar to another report made, but the reasoning for the crash is not the same, so I am making a new report.
No crash report was given, so I uploaded my latest.log

### Crash Report

https://gist.github.com/Exophobias/776d4707b12ce74ee87942b44cd43ca9

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately the gist links you have pasted are invalid and do not link anywhere. Can you please upload the crash log and link it here again?

**Comment by Exophobias** [comment]
> Thanks for the report! Unfortunately the gist links you have pasted are invalid and do not link anywhere. Can you please upload the crash log and link it here again?

I just left it at the version that was working and then eventually switched to REI as it provided less log spam.

**Comment by mezz** [comment]
Are you able to provide a log so that I can look into your problem? 
If you are not interested in solving it any more, please close this issue.
