### ISSUE TITLE
[Bug]: 1.19.2 version, cannot add more rows and columns, not respecting config

### ISSUE THREAD

**Issue by zachsai** [mezz/JustEnoughItems#3051]
### Steps to Reproduce the Bug

change config to 32 for rows and colums, have big monitor

### Expected Behavior

have mroe rows

### Actual Behavior

not more rows

**Comment by RConTRS** [comment]
im having this issue in 1.12.2 as well

**Comment by mezz** [comment]
Thanks for the report!
Can you please provide a screenshot of the issue?

**Comment by zachsai** [comment]
Oversight on my end, the config was working as intended, i was looking at the wrong config option

**Comment by mezz** [comment]
Ok cool, thanks for reporting back!

**Comment by WilliamTDoran** [comment]
> Oversight on my end, the config was working as intended, i was looking at the wrong config option

I've been having this exact issue, using jei-client.ini. Is this not what I should be using?
