### ISSUE TITLE
[Bug]: JEI does not remap to yarn.

### ISSUE THREAD

**Issue by onyxromero** [mezz/JustEnoughItems#3053]
### Steps to Reproduce the Bug

1. Install JEI api for fabric
2. It will not remap to yarn

### Expected Behavior

Remap to Yarn so I can actually use it.

### Actual Behavior

Does not remap to yarn.

### Extra Notes (Optional)

![image](https://user-images.githubusercontent.com/41867693/203627849-5ab83549-8d50-402f-b891-c2e49fcb2c41.png)

**Comment by FinalProduction** [comment]
Love how this issue just gets completely ignored.

**Comment by vaylor27** [comment]
duplicate of #3029
