### ISSUE TITLE
[Other]: Jei 1.16.5 does not work with Applied Energistics 2 1.16.5

### ISSUE THREAD

**Issue by Mellowes133** [mezz/JustEnoughItems#3056]
### Other

Jei does not show the GUI when there is Applied Energistics 2 installed. me and my friends noticed it when we where playing Minecraft and then we saw that there was no GUI. So we looked if we had it installed and it was installed.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
