### ISSUE TITLE
[Bug]: Crash when browsing pages

### ISSUE THREAD

**Issue by DavidX2BR** [mezz/JustEnoughItems#3059]
### Steps to Reproduce the Bug

When using some mods, which I will certainly list here, I navigate to some pages and it causes some rendering error.

### Expected Behavior

browse normally

### Actual Behavior

crashing when browsing

### latest.log

https://gist.githubusercontent.com/DavidX2BR/03f3220298e68ef1a18ec1a926f6c779/raw/2eb1372fa7ae1ab1ed0e2b837882bd40243d4bf8/latest.log

**Comment by mezz** [comment]
Thanks for the report!
I agree this looks like a rendering error, please try removing Optifine and see what happens.
You may need to remove more mods until it stops crashing, then you can figure out which mod is causing the problem.

**Comment by JJSax** [comment]
I am having this same issue, along with a friend.  He disabled optifine to see if it would fix and he still crashed.  We think it's the microblocks from BluePower saying `"sizeModel" is null`

This is the log without some of the initialization log lines. 
[log.txt](https://github.com/mezz/JustEnoughItems/files/10541040/message.txt)

**Comment by MoreThanHidden** [comment]
Blue Power Dev here, took me a while to figure out which mod was causing the issues, seems to be Fluidlogged mod, assuming it is modifying the microblocks because they are water-loggable, which is breaking the renderer.

As per the details on their github page:
> _This mod can cause issues with other mods. If you experience any crashes or other issues after installing this mod, try enabling compatibility mode in the config. This should fix most issues but will disallow waterloggables from other mods to be logged with any other fluid._

Would recommend setting the following in fluidlogged-common.toml:
```toml
# If compatibility mode is true, this mod will only apply to vanilla waterloggable block types(but will still work on modded blocks of those types).
compatibilityMode = true
```
Edit: Attempting to set compatibilityMode to true causes a crash...

**Comment by mezz** [comment]
Thanks for the info!
Can you report this to the Fluidlogged mod dev and link back here to this issue?

**Comment by MoreThanHidden** [comment]
Was going to but noticed a disclaimer on their Curseforge page that they were no longer working on the mod, I'll submit one anyhow as looks like their git is still active.

**Comment by MoreThanHidden** [comment]
Looks like the original crash on this thread isn't related, but the Blue Power crash has been fixed on my side.

**Comment by DavidX2BR** [comment]
Hello, everything is working now thank you all so much 🍷🗿

**Comment by DavidX2BR** [comment]
Hello, everything is working now thank you all so much 🍷🗿
