### ISSUE TITLE
Crash with JEI and FEI

### ISSUE THREAD

**Issue by Areorah** [mezz/JustEnoughItems#306]
I load up fine, but when I click a item for the recipe it crashes.
https://gist.github.com/Areorah/7010afbf99dbb65cf95dc44e9a314858

**Comment by mezz** [comment]
Thanks for the report!
This crash doesn't have to do with FEI.
Please update your Forge to the latest version. I forgot to mark the required version.

**Comment by Venom1987** [comment]
try'd [forge-12.16.1.1934](http://pastebin.com/BTUqN7ri) & [forge-12.16.1.1938](http://pastebin.com/hWVe8fW4) ... crashes with both...any idea's? 1938 is the latest for 1.9 as far as i know...pastebin crash reports are avalible by clicking the forge versions btw

**Comment by mezz** [comment]
@Venom1987 this is for 1.9.4.

**Comment by Venom1987** [comment]
lol ok....sry my bad. ignore my post xD i made a really silly mistake xD _blush_

_edit_ not sure who screwed up there but everytime i install the 1.9 version in the curse voice launcher, it installs the 1.9.4 version ^^ yust wanted you to know it ^^ _installs manually_

**Comment by mezz** [comment]
no worries

**Comment by Areorah** [comment]
It works now, thanks.
