### ISSUE TITLE
JEI will not load client side for my modpack

### ISSUE THREAD

**Issue by yayCollie** [mezz/JustEnoughItems#3060]
### Other

I looked at the log and im not as much of an advanced user, but it seems to assemble the libraries for recipies fine, but fails to load it at the end, something about the assembly with fabric not having a module name?
[normal startup log.txt](https://github.com/mezz/JustEnoughItems/files/10170074/normal.startup.log.txt)
https://paste.ee/d/eZx3t

**Comment by xAwnil** [comment]
> ### Other
> I looked at the log and im not as much of an advanced user, but it seems to assemble the libraries for recipies fine, but fails to load it at the end, something about the assembly with fabric not having a module name? [normal startup log.txt](https://github.com/mezz/JustEnoughItems/files/10170074/normal.startup.log.txt) https://paste.ee/d/eZx3t

**Since you are an advanced user I would like to know why JEI is shown above some mods when I open another inventory.

It is also shown above when I start a cinematic.**

**Comment by yayCollie** [comment]
I'm sorry xAwnil I don't follow what you mean, I assume you're being sarcastic about whatever the problem is, I don't know much about this stuff as this was my first time making a modpack, I've tried rei, emi, and jei in the modpack, emi loaded but will eventually crash. I genuinely don't know anything about the language when reviewing logs or general programming, I'm just looking for a simple fix, I'd just like to make a big modpack on fabric with minelittlepony on it.

**Comment by mezz** [comment]
Thanks for the report!
Sorry, based on the log there seem to be many problems and it is unclear what's wrong. Please try starting from an empty pack and adding mods one at a time to make sure they are working. That way if you add a mod that doesn't work, you can narrow the problem down more easily.
