### ISSUE TITLE
[Crash]: Game crashes on loading (1.12.2)

### ISSUE THREAD

**Issue by Crykenpie** [mezz/JustEnoughItems#3061]
### Steps to Reproduce the Crash

Loading the game with a few different of the more recent versions makes the game crash with the main thing it says being java.lang.IllegalArgumentException: recipeCategories must not be empty.

### Extra Notes (Optional)

This is my own personal modpack and it was working not too long ago, but i messed around with mods for a little, but it shouldn't have caused an issue with jei. 

### Crash Report

https://gist.github.com/Crykenpie/3f80db4d67d4e764b5962230deecf863

**Comment by Considerated** [comment]
try disabling liteloader and test?

**Comment by Crykenpie** [comment]
Tried doing what you suggested and it still crashed, but started trying to load mods, and got this as the main thing i noticed in the crash log

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
