### ISSUE TITLE
[Freeze] Apple M1 

### ISSUE THREAD

**Issue by JustSxm** [mezz/JustEnoughItems#3062]
### Steps to Reproduce the Freeze

1. Open JEI
2. Type anything
3. Possibly freeze. Other wise try again

### Mod Pack URL (Optional)

https://www.feed-the-beast.com/modpacks/95-ftb-presents-direwolf20-118

### Mod Pack Version (Optional)

1.10.2 (Latest)

### Extra Notes (Optional)

Hello. So this is one of the annoying bug to fix, but hopefully you guys can find out what the problem is.

On an M1 Apple Macbook, sometimes when you open JEI and start typing the game will completly freeze. The only way to get out of it is to task kill Minecraft and reopen it again.

With the modpack linked I can say that trying to write "cable" it happens.

The annoying part is that it doesnlt always crash. Sometimes it does and sometimes it dont. Like if something couldnt be rendered for some reasons.

Thank you so much if you look into it!

### Crash Report
none

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
