### ISSUE TITLE
[Crash]: Crash when opening JEI with More Overlays Updated

### ISSUE THREAD

**Issue by FabricTesterOnly** [mezz/JustEnoughItems#3064]
### Steps to Reproduce the Crash

Seems like there is an incompatible issue between More Overlays Updated [1.21.3] and JEI [11.5.0.292].

### Extra Notes (Optional)

Downgrading JEI to [11.5.0.290] fixed the issue.

### Crash Report

https://gist.github.com/FabricTesterOnly/98829ce9291b6fb0cfa3b0214af0eb9d

**Comment by Mitchell5200** [comment]
Confirming the same issue (with a few more mods loaded), i'll change to 11.4.0.290 then
https://mclo.gs/Fa6fKLi

**Comment by mezz** [comment]
Thanks for the report!
Please report this to `moreoverlays`, they are trying to access a class that is internal to JEI that has changed in 1.15.x.

**Comment by r8420** [comment]
An update is available for More Overlays Updated that should fix this issue.

**Comment by mezz** [comment]
Thanks @r8420 
Is there something I can add to the API that will let you stop depending on JEI internals?

**Comment by r8420** [comment]
Maybe it's an idea to add the searchField (as EditBox) to IIngredientFilter.
I use the position and size from this EditBox for detecting double-clicks and for rendering a box around it.
