### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Thewhiteninja1** [mezz/JustEnoughItems#3065]
### Steps to Reproduce the Crash

I just downloaded the mod and I go to launch the game and i get an error "The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Just Enough Items (jei) encountered an error during the common_setup event phase."

### Crash Report

https://gist.github.com/Thewhiteninja1/244635dcb90b39a145ff4bbf406153d7

**Comment by ghost** [comment]
you're using Minecraft 1.19.3. JEI has not updated to that version yet - 1.19.2 and 1.19.3 have significant changes
