### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by KingUtopain137** [mezz/JustEnoughItems#3067]
### Steps to Reproduce the Crash

having jei in the mods folder stops the game from launching properly. I am running fabric for 1.19.2
Mods Folder: 3d skin layers v1.5.2                                   fabric language kotlin 1.7.21           malilib 0.13.0
                      appleskin 2.4.1                                           freecam 1.1.6                                  mini9hud 0.23.3
                      bookshelf lib 2.4.1                                      inventoryHUD 3.4.2                        modmenu 4.1.2
                      boosted brightness 2.1.2                            InventoryProfilesNext 1.9.0             optifabric 1.13.16
                      camerautils 1.0.3                                         Jade 8.6.3                                        Optifine HD_U_H9
                      cloth config 8.2.88                                      JEP 2.0.1                                          shulkerboxtooltip 3.2.2
                     eating animations 1.9                                   JEI 11.5.0.292                                  soundphysics 1.0.15
                     enchantment descriptions 13.0.11               JER 1.1.0.179                                   Xaeros minimap 22.16.3
                     entityculling 1.5.2                                         liblPN 2.0.0                                     Xaeros Worldmap 1.28.4
                     fabric api 0.68.0                                            litematica 0.12.5

### Extra Notes (Optional)

i have troubleshooted by taking other mods such as JEP or JER out of my mods folder and the game looked as if it would start properly, it just needs JEI in to work which seems to cause crashes

### Crash Report

crash report didnt submit

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full client log to https://gist.github.com and link it here.
