### ISSUE TITLE
Add option to hide the item list overlay by default

### ISSUE THREAD

**Issue by Letiliel** [mezz/JustEnoughItems#307]
The item list adds mouse lag in the inventory window and is visually distracting and immersion-breaking when I just want to access my inventory. I'd like to hide it by default and only display it when I need it.

**Comment by kimfy** [comment]
CTRL+O hides the overlay.

**Comment by Letiliel** [comment]
I know, I have to do it every time I log in a game.

**Comment by KnightMiner** [comment]
I think more people are benefited from it being open, otherwise there will be many bug reports saying "I installed JEI, but it does not show up, help!" all with the same simple solution.

There is a config option to hide the item list though if that is what you are looking for.

**Comment by Letiliel** [comment]
> There is a config option to hide the item list though if that is what you are looking for.

Yes it's exactly what I'm asking for :). I don't see it in the config file though ¿?

**Comment by KnightMiner** [comment]
Hmm, it seems to actually show up in the automatically generated world settings rather than the main one, so in your case a new global default would be a benefit.

**Comment by Letiliel** [comment]
> the automatically generated world settings

Can I find these somewhere?

**Comment by KnightMiner** [comment]
"config/JEI/worldSettings.cfg"

**Comment by Letiliel** [comment]
Hm, I don't have a JEI folder in config, only the JEI.cfg file.

**Comment by Letiliel** [comment]
I guess it's because I'm using the version for 1.8, which is hasn't been updated since january.

**Comment by mezz** [comment]
This is already implemented, JEI will keep settings across sessions, so if you close it in your world it will still be closed when you load that world again.
https://github.com/mezz/JustEnoughItems/issues/112

**Comment by Letiliel** [comment]
Nice, can I expect this to be backported to 1.8 or I'm doomed? :)

**Comment by Prospector** [comment]
oh I assumed he meant he wanted setting to save across worlds :P

**Comment by mezz** [comment]
You're doomed, sorry. It takes a lot of time to backport features and if you tried out the 1.9.4 version you'd want them all :)
