### ISSUE TITLE
[Crash]: latest version of jei crashes at the loading screen (using minecraft forge 44.0.37/ 44.0.40 (1.19.3))

### ISSUE THREAD

**Issue by autumn-skylight** [mezz/JustEnoughItems#3075]
### Steps to Reproduce the Crash

when i go to launch minecraft using the latest version of both jei and forge , the game crashes before it has started loading and gives this error message. 

"The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Just Enough Items (jei) encountered an error during the common_setup event phase"

### Crash Report

https://gist.github.com/autumn-young/1894981875931edd04b918094882e1c3

**Comment by autumn-skylight** [comment]
just saw there was a newer version of forge released a few hours a go (44.0.40) so i tried that version with jei but getting the same error message

**Comment by ghost** [comment]
JEI is not released for 1.19.3 - 1.19.2 and 1.19.3 have breaking changes
