### ISSUE TITLE
[Crash]: Crashes as soon as you open inventory (1.19.2-forge-11.5.0.297)

### ISSUE THREAD

**Issue by LeaderbotX400** [mezz/JustEnoughItems#3076]
### Steps to Reproduce the Bug

1. Open the inventory with version 11.5.0.297
2. Crash

### Expected Behavior

The game should not crashes

### Actual Behavior

Game crashes

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/build-n-bake

### Mod Pack Version (Optional)

1.15.0

### latest.log

https://gist.github.com/LeaderbotX400/180193f431213747cd7e7ed1862c8fe3

**Comment by ghost** [comment]
same as #3064

**Comment by LeaderbotX400** [comment]
Duplicate: #3064
