### ISSUE TITLE
JEI cannot be displayed normally

### ISSUE THREAD

**Issue by blackwhita** [mezz/JustEnoughItems#3078]
### Other

![KTXYG8JY}1G)J$(63F {Z9I](https://user-images.githubusercontent.com/98508429/209905753-572e9a73-65c1-4294-a45d-9acd83c33d71.png)
ctrl+o it is no use
Changing keys is also not possible

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
