### ISSUE TITLE
[Crash]: Description: Ticking entity

### ISSUE THREAD

**Issue by Luna-Sapphire** [mezz/JustEnoughItems#3081]
### Steps to Reproduce the Crash

I was just testing this with tinkers archery, and when I shoot the bow at any mob and it doesn't kill it, I crash and get the ticking entity error. this happens with any arrow, it looks to me like the bows are compatible but not the arrows themselves, can you look into this?

### Mod Pack Version (Optional)

1

### Extra Notes (Optional)

I was working on making a pack id Id like it if the two mods actually work together

### Crash Report

https://gist.github.com/Luna-Sapphire/3a9fa90007ce865c866c897bf28afab8

**Comment by mezz** [comment]
Thanks for the report!
Sorry this doesn't appear to be related to JEI, have you reported it to the wrong GitHub project?
