### ISSUE TITLE
[Bug]: Search bar not centered

### ISSUE THREAD

**Issue by emanuele246gi** [mezz/JustEnoughItems#3082]
### Steps to Reproduce the Bug

Edit in the config the section
#Display search bar in the center
CenterSearch = false
to
#Display search bar in the center
CenterSearch = true

### Expected Behavior

The search bar should appear in the center of the inventory GUI, as always intended.

### Actual Behavior

The search bar keeps the same lateral position, under the JEI.

### Extra Notes (Optional)

Minecraft 1.18.2, latest version of JEI available on CurseForge, Forge 40.1.93

**Comment by mezz** [comment]
Thanks for the report!
Can you provide a screenshot of the issue so I can try to reproduce it?

**Comment by emanuele246gi** [comment]
Well it's a bit difficult because I don't really know the exact way to reproduce it, I just edited it in the config and it didn't work.

Here there are two screenshots: 
![2023-01-20_11 55 50](https://user-images.githubusercontent.com/61762317/213679156-9db7b61d-a843-4727-bccd-77c2bd55244c.png)

![jei-client toml - Notepad 20_01_2023 11_55_38](https://user-images.githubusercontent.com/61762317/213679195-5d15324d-96b7-4d21-9fa9-53cdcfc9a73e.png)

**Comment by emanuele246gi** [comment]
But-
