### ISSUE TITLE
[Other]: iam trying to make a 1.12.2 mod buut keep hitting my head

### ISSUE THREAD

**Issue by gamingoninsulin** [mezz/JustEnoughItems#3084]
### Other

hey i am trying to make a small mod but keep hitting my heas the IDE is yelling at me this

Could not find mezz.jei:jei-1.12.2:4.16.1.301

ive pushed even from 302 to 301 but keeps the same 
will you take a look i cant see it anymore 

and btw HAPPY NEW YEAR 

insulin,
https://github.com/gamingoninsulin/simple-machines

**Comment by mezz** [comment]
Thanks for the question!

You can find all the versions of JEI for 1.12.2 here:
https://dvs1.progwml6.com/files/maven/mezz/jei/jei_1.12.2/

Maybe you need to look for `jei_1.12.2:4.16.1.302` (with an underscore) instead of `jei-1.12.2:4.16.1.302` (with a dash).
