### ISSUE TITLE
[Bug]: [1.19.2] [Fabric] [11.5.0.297] Cannot Backspace/Delete in Search Function

### ISSUE THREAD

**Issue by LeakingAmps** [mezz/JustEnoughItems#3086]
### Steps to Reproduce the Bug

Type copp into the search function

Backspace

### Expected Behavior

Nothing happens

### Actual Behavior

Characters behind the cursor should disappear

### latest.log

https://gist.github.com/LeakingAmps/462722227fef7aa006c00422f6768e05

**Comment by Alec153** [comment]
Same issue here I have many of the same mods and many more.

**Comment by WildFyr16** [comment]
Having the same issue, along with everyone else on my server. We are using v11.5.2.1007...
