### ISSUE TITLE
[Bug]: [1.19.2] [Fabric] [11.5.0.297] Cannot type inventory key into search bar

### ISSUE THREAD

**Issue by LeakingAmps** [mezz/JustEnoughItems#3087]
### Steps to Reproduce the Bug

Open JEI and highlight the search bar

Type something to check you're in the bar (copp)

Try to type the inventory key ('e' in my case)

### Expected Behavior

JEI adds the key you've pressed to the end of your search (ie. Coppe)

### Actual Behavior

Inventory closes, and the keystroke is not added to the search.

### latest.log

https://gist.github.com/LeakingAmps/462722227fef7aa006c00422f6768e05

**Comment by soulhakr** [comment]
I see the same unexpected behavior. In addition, the edit box doesn't seem to be recognizing/responding to my Backspace key. No error messages generate in my logs when this happens. I'm running Botania on Fabric with my own modpack, on an Intel mac.

**Comment by murphyneko** [comment]
This is a compatibility issue with Debugify. You need to disable MC-147605 fix. See #3035
