### ISSUE TITLE
[Bug]: Players have different amount of pages

### ISSUE THREAD

**Issue by VindexRckstr** [mezz/JustEnoughItems#3088]
### Steps to Reproduce the Bug

I installed Jei in both the server and the CLIENT

### Expected Behavior

All the op players would have the same amount of pages

### Actual Behavior

I have 161 Jei pages while my friend has 126

### Extra Notes (Optional)

My friend copy and pasted my mods folder

### latest.log

https://gist.github.com/VindexRckstr/a32a2f761439708a763497396621ccef

**Comment by marios-andr** [comment]
It happens when you have a different gui scale or monitor size because less items can be shown at once.

**Comment by mezz** [comment]
Thanks for the report!
Can you provide a screenshot of your screen and your friend's screen?
