### ISSUE TITLE
[Suggestion]: Modrinth support

### ISSUE THREAD

**Issue by RoonMoonlight** [mezz/JustEnoughItems#3091]
### Suggestion

Hey there, your mod is amazing! Can you add support for Modrinth too, if possible? There is new modpack feature on Modrinth and it would be great if you could add support there too.

**Comment by RoonMoonlight** [comment]
@mezz Are you there?

**Comment by mezz** [comment]
Oh hey, sorry I missed this. 
JEI is on Modrinth now 🎉 
https://modrinth.com/mod/jei
