### ISSUE TITLE
[Suggestion]: Allow search to be accessed from the API

### ISSUE THREAD

**Issue by Tyrannicodin** [mezz/JustEnoughItems#3092]
### Suggestion

I'd like to make a custom gui that implements JEI's search feature, and exposing a search function through the api would be helpful. If there's already a way to do this please let me know.

**Comment by mezz** [comment]
Thanks for the suggestion!
Are you looking for `mezz.jei.api.runtime.IIngredientFilter` or do you need something else?
https://github.com/mezz/JustEnoughItems/blob/1.19/CommonApi/src/main/java/mezz/jei/api/runtime/IIngredientFilter.java

**Comment by Tyrannicodin** [comment]
Thanks for the reply, I think it is, so long as it can have prefixes.

**Comment by mezz** [comment]
Yes, this is used directly by the search bar, so it should work the same including prefixes and other operators. 
Please let me know if you run into anything unexpected.

**Comment by Tyrannicodin** [comment]
That's exactly what I needed, I'll close this for now and will send a message if anything is off.
