### ISSUE TITLE
[Bug]: Using Mouse Pickup Still Automatically Put Item In Your Inventory

### ISSUE THREAD

**Issue by SootyMeat** [mezz/JustEnoughItems#3097]
### Steps to Reproduce the Bug

For me, just use cheat mode and click it.

### Expected Behavior

When I click an item in cheat mode with MousePickup config, the item should be in my cursor.

### Actual Behavior

Right now, when I click the item it will just automatically put in my inventory.

### latest.log

https://gist.github.com/SootyMeat/317602608fee1fb0d086128c6baa77a6

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I was not able to reproduce this bug.
Can you try removing other mods and see if this happens for you with just JEI installed?
