### ISSUE TITLE
Inventory Tweaks interaction

### ISSUE THREAD

**Issue by BionicFelps** [mezz/JustEnoughItems#31]
With inventory open, a sort button from inv tweaks sits right where the right arrow to change from crafting grid to furnace recipes sits.  Clicking the right arrow will instead activate the inventory sort.

(probably related to "pressing e" and missed clicks IE: other mods/minecraft are consuming events in certain cases, I won't post anymore of these types...)

**Comment by mezz** [comment]
Yeah this will be fixed when Forge accepts my PR for this issue:
https://github.com/mezz/JustEnoughItems/issues/23

(this is why I haven't done much work on JEI, nobody is looking at the PR)
