### ISSUE TITLE
[Crash]: IC2 clasic JEI crash 1.19.2

### ISSUE THREAD

**Issue by IchigoGames** [mezz/JustEnoughItems#3106]
### Steps to Reproduce the Crash

Crashing when looking up recipe in IC2 Clasic book using jei pressing r or u when looking at any recipe will crash your clint both in server and singleplayer but will not crash server. i dont know if this is a jei issue or just a ic2 clasic issue.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/tekkit-resurrection

### Mod Pack Version (Optional)

1.0

### Extra Notes (Optional)

im the modpack creator.

Minecraft 1.19.2
Forge 43.2.3
jei-1.19.2-forge-11.5.2.1000
IC2Classic-1.19.2-2.0.2

### Crash Report

https://gist.github.com/IchigoGames/7eae0cd7d6a8343de0cc481434ac9c65

**Comment by mezz** [comment]
Thanks for the report!
From the crash log, I can see that IC2 Classic is trying to access JEI's internal classes and it is crashing. 
Please report this issue to them, they should not do that.

**Comment by IchigoGames** [comment]
ok i all ready reported it sense i was not sure if it was a jei or ic2 issue

**Comment by IchigoGames** [comment]
i think they just now fixed it with a update that came out a few hours ago
