### ISSUE TITLE
[Bug]: Incorrect capturing of inputs

### ISSUE THREAD

**Issue by Reshy** [mezz/JustEnoughItems#3107]
### Steps to Reproduce the Bug

1.  Open Inventory
2. Select the JEI search function.
3. Type in any input that involves the inventory opening hotkey (E)
4. Inventory closes.

### Expected Behavior

When typing in the search field, the game should be ignoring any inputs to close the inventory except for the ESC or other designated cancel key.

### Actual Behavior

When typing in the JEI search field, the inventory closes when attempting to type in any word with the hotkey for the inventory in it.

### Extra Notes (Optional)

jei-1.18.2-forge-10.2.1.1002.jar

**Comment by mezz** [comment]
Thanks for the report!
I have tried this out with just JEI and it works as expected. 
Can you please try removing some mods to see if one of them is causing a conflict?

**Comment by Reshy** [comment]
> Thanks for the report! I have tried this out with just JEI and it works as expected. Can you please try removing some mods to see if one of them is causing a conflict?

Seems to be a conflict with Debugify version debugify-1.11.0-forge-1.18.2.jar

**Comment by mezz** [comment]
Ok thanks! This issue was opened with debugify here: https://github.com/isXander/Debugify/issues/169
