### ISSUE TITLE
[Bug]: Move fails when using "move item(+)" in server.

### ISSUE THREAD

**Issue by KiWinger** [mezz/JustEnoughItems#3108]
### Steps to Reproduce the Bug

![javaw_VggzIYjqXP](https://user-images.githubusercontent.com/49084827/214249488-7326273b-a9cd-4933-a85d-20d7c8d4ffc2.gif)
as shown in the picture.

### Expected Behavior

<img width="235" alt="ApplicationFrameHost_b6d9OR2KV2" src="https://user-images.githubusercontent.com/49084827/214249823-9604863b-6db2-4581-b156-d6e8a618d118.png">
as shown in the picture.

### Actual Behavior

<img width="271" alt="ApplicationFrameHost_rhGLLuBsF6" src="https://user-images.githubusercontent.com/49084827/214250095-67d2c111-66d2-4fa4-bed5-a9aa91a372d3.png">
as shown in the picture.

### Mod Pack URL (Optional)

<html>
<body>
<html xmlns:x="tencent"><style type='text/css'></style><body>

英文名 | 中文名 | 版本
-- | -- | --
L_Enders_Cataclysm | 灾变 | 0.48
Alex`s mobs | 艾利克斯的生物 | 1.21
Healing campfire | 治愈篝火 | 3.9
No Hostiles Around Campifer | 无敌对篝火 | 4.5
Hand over your items | 传递物品 | 2
PlayerRevive | 玩家救援/倒地机制 | 2.0.14
The Graveyard | 墓园 | 2.2
Creeper Overhaul | 苦力怕改革 | 2.0.5
Awesome dungeons | 超棒的地牢 | 3.0.0
Yung`s Better Strongholds | 更好的要塞 | 3.2.0
Yung`s Better Mineshafts | 更好的矿道 | 3.2.0
Yung`s Better Dungeons | 更好的地牢 | 3.2.2
Musketmod | 火枪 | 1.4.5
Additional Structures | 失落遗迹 | 4.0.2
Explorify | 探险 | 1.3.0
Signpost | 路标 | 2.01
Farmer`s Delight | 农夫乐事 | 1.2
Primal Magick | 原初魔法 | 3.2.1
Born in chaos | 生于混沌 | 1
Snuffles | 魄罗 | 1.0.3
Additional Lights | 更多光源 | 2.1.5
Rotten Creature | 腐烂生物 | 1.0.1
Effective | 水效果 | 1.3.4
Decorative Blocks | 中世纪装饰 | 3.0.0
copperoverhaul | 铜改革 | 22.10.11
Alex`s Delight | 艾利克斯乐事 | 1.4
Hexerei | 巫师 | 0.2.5
Ecologics | 丰富的生态 | 2.1.10
TreeChop | 砍树皮 | 0.17.2
AllMusic | 点歌台 | 2.6.3
  |   |  
  |   |  
More Vanilla Armor | 更多原版盔甲 | 4.1.1
The Undergarden | 深暗之园 | 0.8.3
Cosmetic Armor Rework | 时装盔甲 | v1a (?
Traveler's Backpack | 旅行者背包 | 8.2.11
Better Combat | 更好的战斗动画 | 1.5.3
Combat Roll | 战术翻滚 | 1.1.1
Additional Additions | 额外拓展 | 5.1.0
Wooden Elytra | 木鞘翅 | ？
Illager Additions | 掠夺者拓展 | 0.0.1
Alexs Armoury | 武器拓展 | 1.3.1
Modular Golems | 傀儡装配 | 1.5.2
Bonfire | 魂系篝火 | 1.2.9
Just Enough Items | JEI物品管理器 | 11.2.0.256

</body></html>
</body>
</html>

### Extra Notes (Optional)

After “move item(+)”, most items are consumed, only one random item remains.
**Works fine in single player, only multiplayer.**
server core : Arclight [Horn/1.0.1](https://github.com/IzzelAliz/Arclight/releases/tag/horn%2F1.0.1) 1.19.2

### latest.log

https://gist.github.com/KiWinger/a2cabcc9566e17c20b4785d044d33ede

**Comment by mezz** [comment]
Thanks for the report!
This is working when JEI is the only mod. 
Please try removing some mods, to find which mod is causing the issue.

**Comment by KiWinger** [comment]
> Thanks for the report! This is working when JEI is the only mod. Please try removing some mods, to find which mod is causing the issue.

I tried a clean install and only kept JEI, the result is as follows.

https://gist.github.com/KiWinger/a2204d17b68d11c884736442eede017f
After “move item(+)”, error in console output.

**Comment by KiWinger** [comment]
Problem solved after updating to latest version.
