### ISSUE TITLE
Cheating items

### ISSUE THREAD

**Issue by ZeRT1337** [mezz/JustEnoughItems#311]
Not sure if this is an issue or a feature, but the buttons at the top left wont work and i cant cheat any item, i even enabled it in the options (and i am obviously in cheat mode). I managed to make it work only once. Again, not sure if it's intended or not, but if it is intended, what's the point in a cheat mode?
Update: I tried to make a save and then load it and it said in the chat:
"You do not have required permission level to load to your inventory. Required level: MODERATOR."
I can cheat items only in one world even though I did nothing. So for now I'll just tp me to a random location and start a "new world".

**Comment by KnightMiner** [comment]
Do you have cheats rnanled In the world options? It is kinda required to cheat items.

**Comment by mezz** [comment]
JEI does not have buttons in the top left. Try playing without FEI.
You can only cheat items if you have permission to /give them to yourself. This means having cheats enabled in singleplayer, or OP in multiplayer.

**Comment by Prospector** [comment]
You should add some text in the corner when FEI is instaled that says that FEI may mess with some JEI's features and that they should check with the FEI author before coming to you.

**Comment by mezz** [comment]
Making FEI worse is not really on my agenda. I may add a line about it to the github issue template though.

**Comment by ZeRT1337** [comment]
Cheats are enable and I'm playing in singleplayer, so I tried removing FEI as you said, and it worked! Thank you so much!
