### ISSUE TITLE
[Crash]: About AbyssalCraft and JEI

### ISSUE THREAD

**Issue by SuZzhi233** [mezz/JustEnoughItems#3117]
### Steps to Reproduce the Crash

[crash-2023-01-28_12.01.02-client.txt](https://github.com/mezz/JustEnoughItems/files/10525563/crash-2023-01-28_12.01.02-client.txt)

### Crash Report

https://github.com/SuZzhi233/CRASS/blob/main/crash-2023-01-28_12.01.02-client.txt

**Comment by mezz** [comment]
Thanks for the report!
This is caused by AbyssalCraft, and I see you have reported it here: https://github.com/Shinoow/AbyssalCraft/issues/507
I will follow the other issue and close this one. They can feel free to ping me if there is something I should look into on my side.
