### ISSUE TITLE
Failed loading config file jei-server.toml of type SERVER for jei-moded

### ISSUE THREAD

**Issue by Deechi-furry** [mezz/JustEnoughItems#3120]
### Steps to Reproduce the Crash

Could be an issue with starting a server but not knowing on how to shut it down. Even on Single Player, the game crashes upon trying to load a world.

### Extra Notes (Optional)

This could be from many failed attempts to start a Paper, Mohist, and Vanilla server.

### Crash Report

https://gist.github.com/Morpho-Dee-EX/fc4ece29252e300b5c57b7ccd324a8ff

**Comment by mezz** [comment]
Thanks for the report!
Please try deleting the file, it seems like something has corrupted it.
Unfortunately this file is controlled by Forge so I am not sure why it has broken here.

**Comment by Deechi-furry** [comment]
After deleting it and then re-installing it, it still proves to have the same crash error with OpenJDK not responding.

**Comment by Deechi-furry** [comment]
wait what's the needs followup tag for

**Comment by Deechi-furry** [comment]
Yup still having the same issue, here's the code: -805306369

And the file is linked.
[crash-2023-01-29_20.33.16-server.txt](https://github.com/mezz/JustEnoughItems/files/10531682/crash-2023-01-29_20.33.16-server.txt)

**Comment by Deechi-furry** [comment]
ok so its just something else that I can't figure out, happens with other mods and such
