### ISSUE TITLE
[Suggestion]: Disabling item list overlay persists

### ISSUE THREAD

**Issue by asdosmil** [mezz/JustEnoughItems#3125]
### Suggestion

Just that. Now, if you disable the overlay [Ctrl + O], it only stays hidden until you completely close the game. When you open the game, the overlay is back again. It keeps hidden if you only exit the world and go to the main menu tho.

Version: jei-1.19.2-fabric-11.5.2.1007

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately, I am not able to reproduce this bug.

There may be a conflict with another mod that you have installed.
Can you try removing other mods and see if it still happens?
