### ISSUE TITLE
[Bug]: Very specific setup of mods causes JEI's GUI to become white

### ISSUE THREAD

**Issue by Landsborough** [mezz/JustEnoughItems#3128]
### Steps to Reproduce the Bug

1. Install [Appleskin](https://www.curseforge.com/minecraft/mc-mods/appleskin/files/2987247), [Blocklings](https://www.curseforge.com/minecraft/mc-mods/blocklings/files/2806971), and [JourneyMap](https://www.curseforge.com/minecraft/mc-mods/journeymap/files/2916002) on Forge 1.12.2
2. Load a world
3. Open inventory and look at JEI's UI

### Expected Behavior

The GUI is not white and broken.

### Actual Behavior

The GUI is white and broken.

### Extra Notes (Optional)

[Screenshot of the broken GUI](https://i.imgur.com/IICutqL.png). My forge version is 14.23.5.2859 if that matters.
Removing _any_ of these mods fixes the issue.
Yes, Blocklings is required to reproduce the bug for some godforsaken reason.

### latest.log

https://gist.github.com/Landsborough/519e6c4b9bf63e5bcd787482ef33aaa2

**Comment by mezz** [comment]
Thanks for the report!
I messed around with this setup but I have no idea why it is happening.
I think one of the other mods may do something special with texture atlases. JEI creates its own texture atlas for its GUI textures, maybe one of the other mods is messing with it.
