### ISSUE TITLE
[Crash]: client crashes when using Simple Storage Network interface (1.18.2)

### ISSUE THREAD

**Issue by MoonMoonShark** [mezz/JustEnoughItems#3129]
### Steps to Reproduce the Crash

happens when trying to use simple storage network interface. right click on interface block.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/the-lighthouse

### Mod Pack Version (Optional)

The Lighthouse-18.23.2.1R.zip

### Extra Notes (Optional)

Minecraft: 1.18.2
Forge: 40.2.0
JEI: jei-1.18.2-forge-10.2.1.1002.jar
Simple Storage Network: SimpleStorageNetwork-1.18.2-1.6.2.jar

thank you for all of your hard work on this. please let me know if there is anything i can do to help you.

### Crash Report

https://gist.github.com/MoonMoonShark/aa1dc048f0b56e18cdd7abd05e6033fa

**Comment by mezz** [comment]
Thanks for the report!
`SimpleStorageNetwork` is trying to access an internal JEI class, and it is failing.
Please report this to them so that they can try to use JEI's API instead of its internal classes.
Also please link back here so that Lothrazar can discuss with me if needed.

**Comment by MoonMoonShark** [comment]
hey there! i'm so sorry, i didn't see your response sooner. apparently this was reported to SSN but it's been untouched since January. 

https://github.com/Lothrazar/Storage-Network/issues/473

**Comment by Mrbysco** [comment]
Even if SSN wants to move away from using internal classes in 1.18 it can't because it's stuck on using JEI 9.7.1.255 as  https://github.com/mezz/JustEnoughItems/issues/2898 doesn't exist in the 10.X builds of JEI so updating gets tough
