### ISSUE TITLE
Getting recipeTransfer output itemstack

### ISSUE THREAD

**Issue by AEnterprise** [mezz/JustEnoughItems#313]
This is a request for an api addition.

I am making an addon that needs to be able to look up recipes for items for compiling lists of (raw) materials. Currently it is only possible to aquire itemstacks from JEI by registering a transferhandler and registering it. That only gives me what the input of the recipe is but not what the user is trying to make (to display it as end goal).

Would it be possilbe to add a hook for that eighter in IRecipeTransferHandler or in some other place so i know what the user is trying to craft?

**Comment by mezz** [comment]
I guess this makes sense. What are you doing exactly?
As a workaround for now, you can get the recipe output from 
`CraftingManager.getInstance().findMatchingRecipe`

**Comment by AEnterprise** [comment]
I am trying to make an addon where someone can select something in JEI and i can show onscreen a list of raw materials they need to collect. If multiple recipes for sub items exist i'd have JEI show the recipes for said item and use the recipe transfer to input it in the list.

I want to use JEI functionality for this because most mods support it for custom recipes, JEI also shows what machine to make things in so i could generate a tree view crafting plan as well eventually

**Comment by mezz** [comment]
Okay I see what you're saying.
Take a look at [JustEnoughCalculation](https://github.com/Towdium/JustEnoughCalculation), it sounds like it's a simpler version of what you want to do. It might be a good place to start.
[Here is the video description.](https://www.youtube.com/watch?v=O-VCGAgBEmI)

**Comment by AEnterprise** [comment]
thanks for that, i did not know that mod existed.

i am making this mod on request, JustEnoughCalculation seems like a mod to look at for how to handle things but the goal is to have an overlay ingame that can constantly show what is needed. People tend to forget what exactly they need in complex multi-step recipes. Especially streamers or people who are doing other things at the same time can get distracted while collecting items, so having an ingame list on screen can make their lives alot easier as they don't have look up things again or regen a list

**Comment by mezz** [comment]
Yeah it sounds like a good mod if you can do it. There is some difficulty with mods that have complicated recipes that might have % chance, or with recipe loops and mods like JER that show worldgen and villagers.
One feature I want to add to JEI soon is a way to save recipes, maybe on the left side. It would help with the problem you described.

**Comment by Prospector** [comment]
A way to pin recipes sure would be nice.

**Comment by mezz** [comment]
Turns out this is possible now that I cleaned up the API using internals issue.
`IRecipeTransferHandler.transferRecipe` is given an `IRecipeLayout`
From there you can get `IRecipeLayout.getItemStacks().getGuiIngredients()` and `IRecipeLayout.getFluidStacks().getGuiIngredients()`
This gives you a map between slots and `IGuiIngredient`.
On each `IGuiIngredient` you have `isInput()` which marks if it is an input ingredient or an output ingredient.
This may seem a bit convoluted, but recipes can have multiple outputs of fluids, itemstacks, all kinds of things, and this supports it.

**Comment by AEnterprise** [comment]
thanks, i'll look into it, there might be a few other things needed but i'll need to see if i can't work around that from my end
