### ISSUE TITLE
[Bug]: Vanilla Minecraft Search interferes with JEI Search. You can type, but not delete if Vanilla Minecraft Search is open.

### ISSUE THREAD

**Issue by JoshSyx** [mezz/JustEnoughItems#3130]
### Steps to Reproduce the Bug

1. Open Minecraft Inventory (E)
2. Go to Vanilla Minecraft Search Option, and delete it again.
3. Go to Search option of JEI and type something, now try to delete it with 'backspace'. You Can't.

### Expected Behavior

Just delete what you typed in JEI Search Bar

### Actual Behavior

It deletes only in the normal Minecraft Search Bar

**Comment by xFirefalconx** [comment]
Observed this in 1.18.2 as well on Forge 40.2.0.
Jei version 
jei-1.18.2-forge-10.2.1.1002

**Comment by xFirefalconx** [comment]
Not stale. Bug persisting. 10.2.1.1004
