### ISSUE TITLE
[Crash]: Crash when using JEI 11.4.0.287 For Forge 1.19.2/ Stuck on dirt block

### ISSUE THREAD

**Issue by TheEpicDiamondMiner** [mezz/JustEnoughItems#3132]
### Steps to Reproduce the Crash

1: Have jei-1.19.2-forge-11.4.0.287 in the mods folder
2: Open the default Minecraft launcher
3: Use the forge installation of Minecraft with the mod installed
4: Press "PLAY"
5: When the game loads, press Singleplayer
6: Click on your existing world
7: Press "Play Selected World"

### Extra Notes (Optional)

Every time I load an existing world 4-5 days later, it would have me stuck on the dirt screen and freeze. [This is the image. It doesn't show the dirt for some reason](https://imgur.com/a/wxa1vD3) Then it would open a window saying "OpenJDK Platform binary is not responding", forcing me to close the program. When I reload into the default Minecraft launcher, it shows a message saying "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. This crash may be resolved by allocating additional memory in the configuration for this version of Minecraft: Java Edition.". The exit code shown is "-805306369. [This is the image](https://imgur.com/LHKWI83) No matter how much memory I allocate, it still crashes with this mod installed. I've also had this happen to my other world on all occasions. And I've had this done on other Minecraft versions.

### Crash Report

https://gist.github.com/TheEpicDiamondMiner/031086b3ff63041cf9e48c757915c3cc

**Comment by mezz** [comment]
Thanks for the report!
Based on the log, it looks like your `jei-server.toml` file is corrupted somehow. Try deleting it and things should work.

**Comment by TheEpicDiamondMiner** [comment]
> Thanks for the report!
> Based on the log, it looks like your `jei-server.toml` file is corrupted somehow. Try deleting it and things should work.

How can I delete it?

**Comment by mezz** [comment]
Sorry for the delayed response.
I think it lives in `<minecraft folder>/saves/<world name>/serverconfig/jei-server.toml`
where `<minecraft folder>` is where your minecraft installation and mods folder lives.
