### ISSUE TITLE
[Bug]: Hide mode doesn't work

### ISSUE THREAD

**Issue by RandomGuy91** [mezz/JustEnoughItems#3135]
### Steps to Reproduce the Bug

When I enter hide mode (which I have to use the keybind for, there's no option in the config for some reason) I can select things and they go red, but when I exit hide mode they stay there (I can still see them) and I can reenter hide mode and they turn red again.

### Expected Behavior

For the items to disappear when I leave hide mode

### Actual Behavior

Same as in steps to reproduce bug

### Mod Pack URL (Optional)

I am making my own

**Comment by RandomGuy91** [comment]
Nvrmind I just had to reload the game and they went away.

**Comment by Nikola920RS** [comment]
is there a way to UN-hide them?
