### ISSUE TITLE
[Suggestion]: Fabric v0.14.14 - 1.19.3 - Allow the keybinds to be changed.

### ISSUE THREAD

**Issue by jabthetab** [mezz/JustEnoughItems#3136]
### Suggestion

At the moment, there is no in-game option to change the controls for JEI. You cannot change them in config nor can you change them in the control settings. Someone else has already mentioned this at #3000 but it seems to have been mostly unanswered for. The only option is to extract the jar, manually find the keyMappings, replace them and recompress. (Which feels absolutely terrifying when you have next to no programming experience.) 
Perhaps there's an easier way to do it that I completely missed somehow, I don't know.
Thank you so much.

**Comment by vico93** [comment]
Related to #3127?

**Comment by wiviw5** [comment]
> The only option is to extract the jar, manually find the keyMappings, replace them and recompress. (Which feels absolutely terrifying when you have next to no programming experience.)

For anyone who is currently still using JEI on fabric, and is looking to edit their keybinds and you have sufficient knowledge on how to edit jars.

### **If you do not have basic knowledge on coding in Java, or have not edited classes before, please do not attempt this. (I am not liable)**

Two resources which are _very_ helpful in doing this are here:

(A link to where all the mappings are located.)
https://github.com/mezz/JustEnoughItems/blob/1.20/Gui/src/main/java/mezz/jei/gui/config/InternalKeyMappings.java#L97
(Can also be found under: mezz/jei/gui/config/InternalKeyMappings.java if you cannot find it in the jar remapper)

And the:
https://www.glfw.org/docs/3.3/group__keys.html
(these are the keybindings that are used internally [On compile they are turned from their enum status, into their numbers.])

You should with that knowledge be able to edit the class file and recompile/export out the jar file with your desired kebindings changed.

Unfortunately, there is no low tech solution now, and I hope for this to be fixed soon.

**Comment by mezz** [comment]
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3000

Key bindings for Fabric have been implemented in JEI 
for 1.20.1: `15.18.0.80`+
and 1.21.1: `19.17.0.196`+
