### ISSUE TITLE
[Crash]: vanilla plugin not found

### ISSUE THREAD

**Issue by evhub** [mezz/JustEnoughItems#3137]
### Steps to Reproduce the Crash

Happens intermittently when a player first opens their inventory upon joining the game. Seems like it happens primarily for players in the End dimension.

### Extra Notes (Optional)

Issue appeared first on 11.5.2.1007, I attempted updating to 11.6.0.1010, but the issue persisted.

### Crash Report

https://gist.github.com/evhub/a9fe36af23d2d38fcfe51aedd2e78383

**Comment by evhub** [comment]
This issue seems to have gone away after updating [moonlight](https://www.curseforge.com/minecraft/mc-mods/selene).

**Comment by mezz** [comment]
Thanks for the report!
Do you have the full client log? I may be able to protect against issues like this in the future if I can understand the conflict with `moonlight` better.

**Comment by lateuponarrival** [comment]
Hey! I'm having the same issue. The pack is Life in the Village 3 with some additional mods. 
The game crashes about half the time upon opening the inventory for the first time after joining a server. 
Moonlight is also present.
Client log:
[ClientLog.txt](https://github.com/mezz/JustEnoughItems/files/14924563/ClientLog.txt)
