### ISSUE TITLE
[Crash]: Minecraft will not open with JEI in the mod folder in 1.18.2

### ISSUE THREAD

**Issue by jinnsmc** [mezz/JustEnoughItems#3138]
### Steps to Reproduce the Crash

Having any updated version of JEI 1.18.2 in the mod folder.

### Extra Notes (Optional)

[damn.zip](https://github.com/mezz/JustEnoughItems/files/10819381/damn.zip)

This is my Modpack I made for myself. I'm not sure what the issue is, I tried removing mods that might not be compatible with JEI, but it still keeps crashing.

Please reach out to my discord jinn#0010, I need help 🙏 

### Crash Report

https://gist.github.com/jinnsmc/c3bf994438a71d5737e4168ac84a89de

**Comment by DesertCookie** [comment]
Experiencing a similar issue on 1.19.2 with the Fabric version.
