### ISSUE TITLE
Forge version crash

### ISSUE THREAD

**Issue by Berhys** [mezz/JustEnoughItems#314]
I just installed the lastest JEI from curse and forge stops loading after the launcher then gives me

"Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
Forge : [12.17.0.1946]"  

and found this in the fml lastest log

[13:05:24] [Client thread/TRACE] [FML/]: Verifying mod requirements are satisfied
[13:05:24] [Client thread/ERROR] [FML/]: The mod JEI (Just Enough Items) requires mod versions [Forge@[12.17.0.1946,)] to be available
[13:05:24] [Client thread/ERROR] [FML/]: net.minecraftforge.fml.common.MissingModsException: Mod JEI (Just Enough Items) requires [Forge@[12.17.0.1946,)]

I'm using forge-1.9.4-12.17.0.1962

i also tried to install the last forge recommended version and the version mentionned in the debug log with the same result, crash and error log

i have removed JEI and now minecraft loads and work well

**Comment by mezz** [comment]
Thanks for the report!
That's very strange. Can you paste your full client log to http://gist.github.com and link it here so I can get a better idea?

**Comment by Berhys** [comment]
Nevermind! ^^" it was my stupid bad : forgot to change the forge version **in the profile** after installation

**Comment by mezz** [comment]
Cool, thanks. I figured it might be something like that, that error message has not been wrong before. It would be better if it also showed the current version of Forge it has detected.
