### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by s1m7y** [mezz/JustEnoughItems#3140]
### Steps to Reproduce the Crash

When i open the inventory in survival and on the right side of the menu where the JEI is located, in the search bar if you type "mi" the game crashes instantly, it works if you type the 2 letters with another one in between but those 2 togeather crashes the game.

### Crash Report

https://gist.github.com/s1m7y/0766e37462e7973d7d00a00428a59213

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue with Immersive Engineering:
```
-- Ingredient being rendered --
Details:
	String Name: 1 drill
	Class Name: class net.minecraft.world.item.ItemStack
	Mod Name: Immersive Engineering
	Registry Name: immersiveengineering:drill
	Display Name: Mining Drill
```
Please report it to their github and link back to this issue. https://github.com/BluSunrize/ImmersiveEngineering/issues
