### ISSUE TITLE
[Crash]: Server, Forge: JEI fails to load correctly

### ISSUE THREAD

**Issue by Gurkenator** [mezz/JustEnoughItems#3144]
### Steps to Reproduce the Crash

Minecraft 1.19.3, Forge 44.1.20

Modlist:
AE2 13.0.10-beta
Curios API 5.1.4
GeckoLib 4.0.4
JourneyMap 5.9.3
JEI 12.3.0.18
TerraBlender 2.1.0.145
Tough as Nails 8.1.0.88

Clientside (same files) runs without issues, Server crashes upon starting. This is a custom pack on Curseforge that I wanted to use for testing my own mods, but it crashes even without them.
[crash-2023-03-03_17.40.03-fml.txt](https://github.com/mezz/JustEnoughItems/files/10884372/crash-2023-03-03_17.40.03-fml.txt)

### Crash Report

https://gist.github.com/Gurkenator/985bbca44d4b3300f2c3d4bd15b23d05

**Comment by mezz** [comment]
Thanks for the report!
This is the same as https://github.com/mezz/JustEnoughItems/issues/3145, and I have just submitted a fix for it.
