### ISSUE TITLE
[Crash]: fml.modloading.dupedmod

### ISSUE THREAD

**Issue by AyenTaro** [mezz/JustEnoughItems#3149]
### Steps to Reproduce the Crash

I started Mc with my mods and it crashed. When I remove JEI it works but playing without JEI is crazy...

### Crash Report

https://gist.github.com/AyenTaro/a6b70b923f3a43fd16c7c880f4d61638

**Comment by mezz** [comment]
Thanks for the report!
It looks like the crash log is cut short, before the mod list.
Can you check that you do not have 2 versions of JEI in your mods folder?

**Comment by AyenTaro** [comment]
No I don´t have two versions in my folder
