### ISSUE TITLE
[Crash]: JEI and Optifine (Optifabric)

### ISSUE THREAD

**Issue by Radbardur** [mezz/JustEnoughItems#3151]
### Steps to Reproduce the Crash

Minecraft 1.19.3
Fabric Loader 0.14.13
Fabric API 0.75.1
JEI 12.3.0.19
Optifabric 1.13.21
preview OptiFine 1.19.3 HD U I2 pre5

1. Copy JEI, OptiFine and Optifabric jars into the mods folder.
2. Start Minecraft

### Extra Notes (Optional)

The same as #3143

### Crash Report

https://gist.github.com/Radbardur/7036b4d5de1fb5c27a6fedbda4cd8c5e

**Comment by mezz** [comment]
Thanks for the report!
Please do not open a duplicate issue, you can add extra info into the existing issue.
