### ISSUE TITLE
[Crash]: 1.19.4 on entry of inventory 

### ISSUE THREAD

**Issue by PeterTaylorTX** [mezz/JustEnoughItems#3158]
### Steps to Reproduce the Crash

Pressing E to open inventory instantly crashes the game with the message
"The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: recipeCategories must not be empty."

### Crash Report

https://gist.github.com/PeterTaylorTX/2453c28fdd2e5f3fa1c8fa6b86df442b

**Comment by Edivad99** [comment]
Jei for 1.19.4 is not released yet
