### ISSUE TITLE
[Suggestion]: Show all items in output slot when mouse over if slot is holding multiple items

### ISSUE THREAD

**Issue by TelepathicGrunt** [mezz/JustEnoughItems#3160]
### Suggestion

Say a recipe has an input that takes any item in a tag or a modded recipe setup JEI to show a tag for a slot or output, JEI currently slowly cycles through the items that the slot is holding. This can be annoying and slow for users to see all the actual items that the slot actually has.

Suggestion is to upon hovering the mouse over the slot, a tooltip should appear with all the items shown on it to make is much faster and easier to see all the items that the slot was going to cycle through.

Example from the mod called EMI that started this new trend: 
https://www.curseforge.com/minecraft/mc-mods/emi
![image](https://user-images.githubusercontent.com/40846040/226464233-bda402a4-3d9b-43bf-9898-5379b136dc80.png)

Video in action:
https://user-images.githubusercontent.com/40846040/226464757-ad639a55-2971-423a-8693-0d35de968914.mp4

**Comment by dhyces** [comment]
A good step towards this would be to open up the different methods that handle tooltips to handle a list of ClientTooltipComponents instead of Components

**Comment by TelepathicGrunt** [comment]
Be gone bot! I think this suggestion is still good unless it was already implemented by now
