### ISSUE TITLE
[Bug]: jei crashes on searching specific letters because it poles its own hotkeys while searching

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [mezz/JustEnoughItems#3161]
### Steps to Reproduce the Bug

****[Bug]: jei crashes on searching specific letters because it poles its own hotkeys while searching

### Expected Behavior

[Fix]: jei doesnt on searching specific letters because it poles its own hotkeys while searching

### Actual Behavior

[Bug]: jei crashes on searching specific letters because it poles its own hotkeys while searching

### Extra Notes (Optional)

19.2 and several other cases in older forge versions, most of the older versions it occurered witha delay and only after the game had been memory leaking for about 20 minutes or more - literally typing random letters is likely to trigger the crash.

string examples go when searching for gold ore
keybind defaults :: o

probable solution:: disable all hotkeys temporarily while the search field is active.

**Comment by xIlH3LLlIx** [comment]
This is happening to me A LOT.
I'm playing with some mods and in my case when i type like "Dragon" i can't even finish the word because the game crashes... 

How to disable the hotkeys while on the search field?

**Comment by tails1974seeyounextgame** [comment]
fixed in latest version of jei *thumbs*
