### ISSUE TITLE
[Suggestion]: Allow mods to disable JEI's default exclusion zones for the vanilla inventory mob effect display

### ISSUE THREAD

**Issue by Fuzss** [mezz/JustEnoughItems#3168]
### Suggestion

Hello there, my [Stylish Effects](https://www.curseforge.com/minecraft/mc-mods/stylish-effects) mod completely overhauls Minecraft's mob effect display.

The problem with JEI is there is no way for disabling the exclusion zones for the vanilla effect display position which are registered directly from JEI by default.
So far I've used a mixin to disable JEI zones from registering, but since that recently broke, I guess it's a good time to ask for a proper way in the api.

It would be great to be able to disable that functionality in JEI somehow via providing an `IModPlugin`, so that only my own exclusion zones for the new display are taken into account.

Here are some screenshots of the current behavior: https://github.com/Fuzss/stylisheffects/issues/17

**Comment by SettingDust** [comment]
bump

**Comment by mezz** [comment]
Sorry for the late response. 
I have pushed an update that adds the ability to do this to the API, you can find it here:
https://github.com/mezz/JustEnoughItems/blob/593848cece1ce5b109685b90dc84ad2a82fc4a9b/CommonApi/src/main/java/mezz/jei/api/runtime/IJeiFeatures.java#L22
Let me know if you have any questions!

**Comment by Fuzss** [comment]
Thanks!

**Comment by mezz** [comment]
I have backported this change to 1.20.1 as well, it's available in JEI 15.3.0
