### ISSUE TITLE
[Other]: Two lists

### ISSUE THREAD

**Issue by swertfyuhi** [mezz/JustEnoughItems#3170]
### Other

I have no idea why this is happening. There are two lists stacked on top each other and I couldn't find anything that could help me solve this on the web.  I tried changing from creative to survival, thinking that might be the issue but didn't work,  

![sfghj](https://user-images.githubusercontent.com/96132681/228780071-69bd34d9-7294-485e-b2e8-557df74acf39.PNG)

**Comment by 837951602** [comment]
Is that because of two similar mods?
