### ISSUE TITLE
[Bug]: Can't find or rebind any of JEI's keys

### ISSUE THREAD

**Issue by thefrostypixel** [mezz/JustEnoughItems#3182]
### Steps to Reproduce the Bug

I am playing Minecraft Fabric 1.19.3 and can't rebind any of JEI's keys. It's not under _Minecraft Options -> Controls_, but the CurseForge page say

**Basic Controls:**
Inventory:
_(Minecraft Options -> Controls)_

so I am assuming, that it should be there. I have **R** set as one of my hotkeys, so having JEI overwrite it means I can't hotkey items from my inventory into my hotbar.

### Expected Behavior

I can find and change JEI's keys under _Minecraft Options -> Controls_.

### Actual Behavior

I can't find JEI's keys under _Minecraft Options -> Controls_ and it's not in the _options.txt_ file or in JEI's config folder either.

### latest.log

https://gist.github.com/thefrostypixel/f8811378dbb5c48b747646a3eb7ec4cc

**Comment by vico93** [comment]
Related somewhat with #3127?

**Comment by thefrostypixel** [comment]
Is you can change the keybinds there then yes, but if the keybinds have to be changed somewhere else, can't be changed at all or should be in the normal keybinds menu, then it should stay open.

**Comment by thefrostypixel** [comment]
I just noticed, that this is a duplicate of #3136 and that keybinds can't be changed (without editing the JAR), so I'll mark this as closed.
