### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SikiciBebek** [mezz/JustEnoughItems#3188]
### Steps to Reproduce the Bug

JEI stops showing changed recipes (Crafttweaker) on server after restarting minecraft

### Expected Behavior

join server
close minecraft
start it and join again

### Actual Behavior

U can see the items but not the recipe
(recipe still works)

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/kotd

### Mod Pack Version (Optional)

1.1.3b

### Extra Notes (Optional)

I allready tried to fix it with crafttweaker but it seems to be a JEI problem
There is no problem with the client it works fine on singleplayer 

here is the link to the issue on Crafttweaker 
https://github.com/CraftTweaker/CraftTweaker/issues/1643

### latest.log

https://gist.github.com/SikiciBebek/c431f233444b32f1239f7a94e9154906

**Comment by jaredlll08** [comment]
This issue isn't with JEI, it is with Just Enough **RESOURCES** as that is the mod with a broken JEI plugin.

The provided log is from the server, which doesn't help as JEI doesn't do anything on the server, so there is no information that can be obtained from that log.

This log is from the client and shows the issue of Just Enough Resources failing their plugin load.
https://gist.github.com/SikiciBebek/7a38f9c253f05d15e1e20f9cf68c4a0c

**Comment by SikiciBebek** [comment]
Ye but ive allready deleted Resources and it worked after that until i restarted my client.
Now i deleted RESOURCES + the configs too but it still doenst work
any idea how i can fix it?

**Comment by SikiciBebek** [comment]
i tested a bit and the recipe does only show if u go into a singleplayer world first
if u join on the server it wont work

**Comment by jaredlll08** [comment]
Provide the client log file of that happening, the server log provides very little information.

**Comment by SikiciBebek** [comment]
https://gist.github.com/SikiciBebek/8c9dc242cb4ccbdc1b9e3c5301a2ba4b : Client.log

**Comment by SikiciBebek** [comment]
:c
