### ISSUE TITLE
[Bug]: Can't drag ingredients from Bookmarks for use in mod filters

### ISSUE THREAD

**Issue by KooBaby** [mezz/JustEnoughItems#3190]
### Steps to Reproduce the Bug

Bug occuring when attempting to drag items into green item slots in the Mekansim digital miner. 

steps to reproduce:

1. enable easy digital miner in mekanism configt. default option for this config is false, it must be set to true.
2. aquire and place a digital miner from the Mekanism mod, and add new filter
3. attempt to drag an item from the left hand side of jei to the green inventory slots.

### Expected Behavior

The bug occurs when dragging a bookmarked item from the left hand side of jei. dragging something from the right hand side yields the desired outcome, that being that you can drag an item into green inventory slots. However when attempting to drag an item from the left hand side (bookmarked items) it does not work, you're completely unable to drag items on the left hand side.

### Actual Behavior

Actual behavior is as stated above. Rather than being able to frag items into the slots from the left, you cannot drag items at all.

### Mod Pack URL (Optional)

https://drive.google.com/file/d/1kR1QRLumGDmnQkIjanwrdo2Kilu825AQ/view?usp=sharing

### Mod Pack Version (Optional)

Forge 1.19.2

### Extra Notes (Optional)

IMPORTANT NOTES
*I am playing on minecraft 1.19.2 forge.
*Jei is version 1.19.2-forge-11.5.0.297
*The modpack i have linked is personal collection of mods and not some official modpack. i have linked it via a google drive. google drive is rather finicky sometimes, so i apologies if there are any issues accessing the file containing the mods, or if linking google drive is considered suspicious or untrustworthy.
*I have never made a bug report for a mod and i am not very familiar with github. i apologise if i have left out anything important, or if this report is not up to standard.

**Comment by mezz** [comment]
Thanks for the report!
I have added support for this to 1.19.2 and 1.19.4 now.

**Comment by KooBaby** [comment]
awsome! tysm
