### ISSUE TITLE
[Other]: Add JEI 1.19.4 to maven

### ISSUE THREAD

**Issue by Hardel-DW** [mezz/JustEnoughItems#3192]
### Other

I wanted to try to use JEI in development, I am in version 1.19.4 and I do not find in Maven the associated version. The last version is 1.19.2
Sorry for the inconvenience.

https://dvs1.progwml6.com/files/maven/mezz/jei/

**Comment by oitsjustjose** [comment]
Just ran into this issue as well, as per [the docs](https://github.com/mezz/JustEnoughItems/wiki/Getting-Started-%5BJEI-10-or-higher-for-Forge-or-Fabric%5D) there's a new Maven Repo that Mezz is using as of January of this year: `maven { url = "https://maven.blamejared.com" }`

Hope this helps!

**Comment by Hardel-DW** [comment]
Thank you !
