### ISSUE TITLE
[Bug]: Mod that depends on JEI hangs during datagen

### ISSUE THREAD

**Issue by noeppi-noeppi** [mezz/JustEnoughItems#3194]
### Steps to Reproduce the Bug

  1. Create a forge mod that depends on JEI and loads it in a development environemnt.
  2. Run datagen: `./gradlew runData`

### Expected Behavior

After all data providers are complete, the game should stop.

### Actual Behavior

After all data providers are complete, the game hangs forever.

### Extra Notes (Optional)

This is due to the `Timer` thread in [ConfigSchema.java](https://github.com/mezz/JustEnoughItems/blob/1.19.4/Common/src/main/java/mezz/jei/common/config/file/ConfigSchema.java#L21) not running as a daemon. This means, the game won't stop when all other threads are done.

When running the game regularly, this is no problem as `System.exit` is invoked when the main thread is about to die. When datagen is running, however this is not the case, so the JEI `Timer` thread makes the game hang indefinitely.

**Comment by Drullkus** [comment]
Can confirm this is also happening with Twilight Forest in dev, despite us being on JEI version 13.1.0.6

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix for this thread, please let me know if you into any more issues.
