### ISSUE TITLE
[1.9.4] Client crash when using JEI search

### ISSUE THREAD

**Issue by ruyanve** [mezz/JustEnoughItems#320]
Title says it all... Typing anything in the search bar results in a crash.
Using Forge 1965
jei_1.9.4-3.6.7.216
log: https://gist.github.com/ruyanve/f4ac151ab3ea4050b8654151a2197f15

**Comment by mezz** [comment]
Thanks for the report!
Please try without FEI. They are often the cause of crashes. I added a line about it in the issue template when you submit a new issue.

**Comment by ruyanve** [comment]
Will be fixed in the next FEI version,
https://github.com/elix-x/Forever-Enough-Items/issues/20
Cheers!

**Comment by Morpheus1101** [comment]
im getting same issue with searching http://pastebin.com/DZcj3hWH using latest Forge .1968  .. nvm .. i didnt realise what FEI was .. ignore
