### ISSUE TITLE
[Bug]: JEI not showcasing crafting recipes

### ISSUE THREAD

**Issue by HatoriHudso** [mezz/JustEnoughItems#3203]
### Steps to Reproduce the Bug

This is occurring on a shockbyte server the runs on forge 40.2.2 1.18.2 and uses numerous mods including JEI. However, a new bug was encountered which only happens in multiplayer.

### Expected Behavior

Usually, upon clicking any item on the JEI list you can view its recipe and the recipes it can be included in. Since the server also has create when you hold W on create structures you can usually view the recipe/structure procedure.

### Actual Behavior

Nothing happens, and absolutely none of the recipes can be viewed.

### latest.log

https://gist.github.com/HatoriHudso/9760512bc64ce409ab0306347f98d1e0

**Comment by ghost** [comment]
This is happening for me as well with fabric running mc `1.19.4`

**Comment by xFirefalconx** [comment]
I had such a bug happen to me in singleplayer the other day, I had to exit the world and reload it to fix the issue. 
1.18.2, Forge 40.2.4 and jei 10.2.1.1004

**Comment by xFirefalconx** [comment]
Not stale, still waiting for an update

**Comment by DrollestDuck88** [comment]
This happens to me on Aternos server with forge 40.2.10

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Create and link back here to this issue. It is up to each mod to display their recipes. 
I can help them out, but it is important to start in the right place.
