### ISSUE TITLE
[Bug]: Pressing E in the JEI search box exits the inventory

### ISSUE THREAD

**Issue by redkittty** [mezz/JustEnoughItems#3205]
### Steps to Reproduce the Bug

1. Click on the JEI search box in the inventory
2. Press E when typing

### Expected Behavior

It exits the inventory

### Actual Behavior

/\
 |
 |

**Comment by redkittty** [comment]
btw I was using 1.18.2

**Comment by Aceplante** [comment]
Yea same, I think this is new

**Comment by Mrabetto** [comment]
I have that same issue, but also cant delete by backspace

**Comment by HiWord9** [comment]
Duplicate of #2801

**Comment by Aceplante** [comment]
plz fix?
