### ISSUE TITLE
Suggestion : Hide by WildCard but show the first item in said wild card.

### ISSUE THREAD

**Issue by Malus-Lupo** [mezz/JustEnoughItems#321]
This way you could say hide all colored glass but still show the first one so people can still see how to craft it? You can hide all but the first one by hand but It would be amazing if maybe shift + ctrl click would hide all but the first?

Edit : Another idea to reach the same goal, as said bellow, Allow to have single items with in a Wild Card be shown. IE you Wild Card hide all Colored Class then can un-hide only White Colored Class.

**Comment by VT-14** [comment]
I think this is to avoid the tedious wait to see the item you want when looking up recipes with ore dictionary items?

If so, another option would be to pull up an page with all of the ore-dictionary compatible items and pick the item you want from there, Logistics Pipes style.  Probably make that page show when you click on one of the ore-dictionary items when trying to see how to craft it.  

It would be an extra page, but it would allow you to pick any item from the ore dictionary and not just the first one, useful if you need something like Coal Powder/dust and you have Ender IO machines, but Blood Magic's new coal powder (I'm not familiar with its name yet) could be first in the list.

EDIT: a WildCard entry on that ore-dict. page could be used to show all of the items at the same time.  a case of "I need any coal powder, what are my options?"

**Comment by Malus-Lupo** [comment]
I am not sure what you mean. I am still very unfamiliar with all the features of JEI, I was just referring to the Item Hiding Mode. It is just a lightly easier way to hide items. But not hide all of them. Kind if like the NEI Culling Inpure Core adds to 1.7.10. The idea being if every of a item type, say Colored Glass is crafted the same, 8 glass around a dye item, then you only need to see how to craft one and would then know hot to craft all 16 colors. So you could say Shift Clt click them when in Hiding Mode to make all but one of them hide. Tho after I had the thought I then saw things like Tinkers Construct, a few of there crafting like tables are all hidden by a single Wild Card but there not all the same, tho a simple fix to this would be to show all but the one item you Shift Ctrl Clicked then if you further Shift Ctrl clicked another block or item with in the same Wild Card that item or block would also be shown.

Or even more simple to all of this would be to make it so you can hide by Wild Card as you can now but then un-hide single items with in said Wild Card, IE you Wild Card hide all colored class but then can toggle White Colored Class back to shown and the rest still remain hidden. 
On a Display level, you could have it show the red Wild Card indicator on all items with in the wild card as it does now but then the items you select to remain shown could have a green indicator were the yellow normal hide indicator is normally shown.

**Comment by mezz** [comment]
I think what you want would be covered by this request: https://github.com/mezz/JustEnoughItems/issues/195

Unfortunately subitems are used in all kinds of insane ways, so having special handling for only showing the first one would only work well for certain items. Being able to hide a bunch of items and unhide one should be good enough for what you want to do.

**Comment by Malus-Lupo** [comment]
Oh I'm sorry I looked through the other things but must have missed that request. Yes that would be perfect, same goal in the end!

**Comment by mezz** [comment]
Cool. I'll probably add this soon, it's not a hard feature but it hasn't been very high priority.
