### ISSUE TITLE
[Bug]: JEI Works in singleplayer but not multiplayer

### ISSUE THREAD

**Issue by ShadOhh** [mezz/JustEnoughItems#3211]
### Steps to Reproduce the Bug

Log onto server with ip: 142.44.148.208:25599

Open inventory No JEI

### Expected Behavior

Jei to work on server

### Actual Behavior

Jei does not work on the server

### Mod Pack URL (Optional)

https://www.dropbox.com/s/o40i1lq28ezr1l0/Server%20Official-1.zip?dl=1

### latest.log

https://gist.github.com/ShadOhh/8cc510ec63493f2eb75af608241b6ba4

**Comment by cheicen** [comment]
Having same issue on latest version of JEI on 1.20.1 Fabric Server
