### ISSUE TITLE
[Crash]: server crash when opening a world (version 1.19.2)

### ISSUE THREAD

**Issue by vinnyg0621** [mezz/JustEnoughItems#3216]
### Steps to Reproduce the Crash

1. open a world and then click "play"
2. the percent loading screen never came up
3. I had to force close it

### Extra Notes (Optional)

all of a sudden, when I opened a world, the % loading screen just did not come up at all, then I had to force close it and it crashed and said "this crash may be configured by allocating more RAM in this java installation." it's only one map that's doing this now

### Crash Report

https://gist.github.com/vinnyg0621/c998fe37413161e16fee31c8f5408fb1

**Comment by vinnyg0621** [comment]
it crashed with exit code -805306369. someone please help!

**Comment by vinnyg0621** [comment]
ok, I figured how to get it back

**Comment by eatingsomthin** [comment]
> 

how did you fix it? i have the same problem
