### ISSUE TITLE
JEI not showing recipes for all items in multiplayer

### ISSUE THREAD

**Issue by jmikeboyd** [mezz/JustEnoughItems#322]
Hello, I'm testing The Pioneers R.8 on a server. Some of the item's won't show the crafting recipe when I click on them. Neotech has quite a few blocks that I can't see. 

If I create a new world in single player it's working correctly. Any ideas as to how to troubleshoot this? I've reinstalled the pack several times and the server admin says he's not seeing any issues being logged. 

Thanks for any assistance!

**Comment by mezz** [comment]
Thanks for the report!
Try asking NeoTech here: https://github.com/TeamBR-Modding/NeoTech/issues
Each mod adds their own integration, it's mostly up to them to make sure their mod's items and recipes work. Make sure to link back to this issue, I'm happy to help them with any questions.

**Comment by jmikeboyd** [comment]
It's not just NeoTech, I have issue with other mods as well. Foundry has some items that will not show the crating recipe either.

**Comment by mezz** [comment]
Then please report that to Foundry as well: https://github.com/EXTER7/Foundry/issues

At the moment there are no known bugs with JEI lookups. If the devs of those mods find something wrong or need help, they can come back here and we can work out it.

**Comment by TehNut** [comment]
Are any of the missing recipes changed via MineTweaker? I remember @BBoldt doing some of that.

**Comment by BBoldt** [comment]
I've changed barely anything with minetweaker.

https://github.com/BBoldt/ThePioneers/blob/master/scripts/RecipeTweaks.zs

@kekzor Tell me which blocks or items specifically are missing recipes so I can check myself.

**Comment by jmikeboyd** [comment]
Refractory Casing and Induction Crucible Furnace from Foundry

Neotech: Electric Furnace, Electric Crusher, Electric Crucible, Electric Solidifier, Electric Alloyer, Electric Centrifuge, Electric Pump, Electric Logger, Basic RF Storage.

These are just to name a few. I cannot see the recipes for these items. Thanks all in advance for your time.

**Comment by TheRoyalReaper** [comment]
the same thing happens with reciepes from Tinkers' Construct, Lycanites Mobs, Blood Magic and storage drawers.
only in multiplayer

**Comment by dabigmoose** [comment]
I can confirm this bug in latest .231 as well.  Here is an example. Multiplayer Miners Backpack, Icon is there and shows that I can find item in Dungeon chests but doesn't show as craftable.  I log off open in single player and Miners backpack recipe is there as well as dungeon chest loot. Go back into Multiplayer and item still doesn't show as craftable.  I know its not the server as I am server admin and I have same config as server.

**Comment by TheRoyalReaper** [comment]
I found out that the problem is that you need jei to be in the server's
mods file

**Comment by dabigmoose** [comment]
@TheRoyalReaper You mean Mods folder, yes it is in Mods folder where else would it be?

**Comment by TheRoyalReaper** [comment]
If jei is only on the client's mods folder it won't show recipes. If it's
on the server's mods folder too then it'll let you craft.
Also maybe not all the mods have support.

**Comment by dabigmoose** [comment]
@TheRoyalReaper As I mentioned above I have same setup as my server. mods and cfgs are same on both server and mod.

**Comment by mezz** [comment]
I don't think you guys are even talking about the same thing any more.

**Comment by TheRoyalReaper** [comment]
Yep.
