### ISSUE TITLE
[Bug]: cant type on recipe search bar when running with OptiFabric [1.19.4]

### ISSUE THREAD

**Issue by JonathanCheah** [mezz/JustEnoughItems#3222]
### Steps to Reproduce the Bug

1. Install optifabric mod
2. Open Inventory
3. Focus recipe search bar
4. Type(nothing happens)

Minecraft: 1.19.4
fabric-api-0.78.0+1.19.4
OptiFine_1.19.4_HD_U_I4
optifabric-1.13.24

### Expected Behavior

1. Install optifabric mod
2. Open Inventory
3. Focus recipe search bar
4. Type(search bar will get input)

### Actual Behavior

Nothing happens when you type, the search bar wont get the keyboard inputs

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/mc-mods/optifabric

### Mod Pack Version (Optional)

optifabric-1.13.24

### Extra Notes (Optional)

I tested by removing all other mods. when it only has fabric and malilib the search bar works. after i include optifine and optifabric mod the search bar doesnt get input anymore. (additional note: when the search bar dont work, copy paste can still input whats on the clipboard into the search bar, just typing wont work)

### latest.log

https://gist.github.com/JonathanCheah/afea2846624e94f6e20be87a1553f537

**Comment by sr972** [comment]
Have the same issue

**Comment by mezz** [comment]
Thanks for the report!
Please report this to optifabric and link back to this issue, they are knowledgeable about mod compatibility issues with their mod and can help identify the problem better than I can.
