### ISSUE TITLE
Already Building Crash

### ISSUE THREAD

**Issue by cjburkey01** [mezz/JustEnoughItems#323]
My friend gets this crash report when using a large amount of mods on Windows with optifine installed and views a recipe: [GIST](https://gist.github.com/cjburkey01/7b3903c48973ee3787edfe0e6e5c9684).  However, once optifine is removed, it works fine.  Also, I can use the same mods on Mac and not get the crash with optifine.

**Comment by mezz** [comment]
Please report to Optifine, I don't see JEI in the stack trace, it's just displaying items like anything else does.
https://github.com/sp614x/optifine/issues
