### ISSUE TITLE
Suggestion: 1.7.10 JEI

### ISSUE THREAD

**Issue by Wolfdemort** [mezz/JustEnoughItems#3236]
### Suggestion

Truly sorry if this question is asked alot. I would love JEI for 1.7.10 if possible as it is a lifesaver for complex mods like HBM. Cheers!

**Comment by SiverDX** [comment]
Why not use https://www.curseforge.com/minecraft/mc-mods/notenoughitems

Thats what your mod example is using, see:
https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod/screenshots

**Comment by mezz** [comment]
Thanks for the suggestion!
Sorry but I will not be porting JEI to 1.7.10, there is no support from mods on that version. Mods in current versions have written their own JEI plugins to add support, it would not be possible to get every mod to write those again for an old version.
