### ISSUE TITLE
[Crash]: 1.20 JEI crashes game with exit code 1

### ISSUE THREAD

**Issue by SorkoPiko** [mezz/JustEnoughItems#3238]
### Steps to Reproduce the Crash

1. Download fabric version 14.0.0.1 ([Modrinth Download](https://modrinth.com/mod/jei/version/14.0.0.4))
2. Place in mods folder
3. Launch

### Mod Pack Version (Optional)

14.0.0.1

### Extra Notes (Optional)

I tested with and without JEI. I can confirm this only happens when JEI is in my mods folder. Using Fabric Loader 0.14.21-1.20 and Fabric API 0.83.0. No other mods installed.

### Crash Report

None, there are no crash reports in my folder. I think the game doesn't even have time to launch, as the java binary never appears in Task Manager.

**Comment by EndDragon438** [comment]
To confirm, same error. latest.log attached.
Not just JEI in pack, but JEI is what's crashing it.
[latest.log](https://github.com/mezz/JustEnoughItems/files/11703096/latest.log)

**Comment by zorgandfroggo** [comment]
Same problem here. I can confirm as well. I am trying to run a server in this new fabric version, and JEI does load when I start my server, but I can't join the server and see if it actually applied since my game crashes as well.

**Comment by LOLcamp** [comment]
Same problem here, with only JEI installed i run into this same error

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed as part of https://github.com/mezz/JustEnoughItems/issues/3243
