### ISSUE TITLE
Error with Integration

### ISSUE THREAD

**Issue by SonarSonic** [mezz/JustEnoughItems#324]
Hey,
I've added integration for JEI perfectly in 1.8.9, I found that when I ported to 1.9.4 some of my addRecipeClickArea methods didn't work. I've narrowed this down now, it seems that only GUI classes which extends GuiContainer directly work. Ones which extend another class in the hierarchy don't work.

Thank you for a great mod
Ollie

**Comment by mezz** [comment]
Thanks for the report!
JEI is only open when a GuiContainer is open, and it has always been that way. I think the issue may be something else.

**Comment by mezz** [comment]
Any update @SonarSonic ?
