### ISSUE TITLE
[Bug]: changing ColorSearchMode from its default value in client config causes crash upon worldloading. Version 1.19.4 and 1.20

### ISSUE THREAD

**Issue by jetpacker06** [mezz/JustEnoughItems#3240]
### Steps to Reproduce the Bug

Open jei-client.ini
Set ColorSearchMode to ENABLED or REQUIRE_PREFIX
Join a single/multiplayer world
Crashes with an IllegalStateException with description: "Image is not allocated."

### Expected Behavior

Color search mode should be modified as intended

### Actual Behavior

Game crashes

### latest.log

https://gist.github.com/jetpacker06/d2a6e92592904f7a91066fc465c3487a

**Comment by mezz** [comment]
Thanks for the report!
I have submitted fixes for this for JEI for 1.19.4 and 1.20
