### ISSUE TITLE
[Crash]: 1.20 Crash Exit Code: 1

### ISSUE THREAD

**Issue by zorgandfroggo** [mezz/JustEnoughItems#3241]
### Steps to Reproduce the Crash

1. Download JEI 14.0.0.4
2. Put it in the mods folder with Fabric API
3. Run the game and get a crash "Exit Code: 1"

### Extra Notes (Optional)

I saw another bug report for this, but the version was different with 14.0.0.4 and the solution did not fix anything. You can't just link code saying it will fix it but not say how to get the code to apply to the game. ALSO the crash does not appear in m crash-reports, so here is the log file (includes the coded java file that was supposed to fix the mod).

### Crash Report

https://gist.github.com/zorgandfroggo/59f1ef546960367149b989ef812d98f8

**Comment by JackiTacki** [comment]
+1

**Comment by theterrabite** [comment]
Also having this issue with Quilt and it's api (QFAPI) I also use other mods, but it's only crashing when I have JEI installed. Here are my [logs](https://mclo.gs/GCdsvRF)

**Comment by Scionni** [comment]
I have attempted to edit the .class with the fix for #3239 on version 14.0.0.4 and it did not work for me.
Same issue, Crash w/ exit code 1.

**Comment by tmexner-dev** [comment]
+1

**Comment by RandyStevens** [comment]
+1

mods list is as follows: 
![image](https://github.com/mezz/JustEnoughItems/assets/25543498/7f98992e-9759-4d55-a827-bbfab236c694)

Game launches without JEI, by adding JEI crash with error code 1

**Comment by Briacoo** [comment]
+1

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed as part of https://github.com/mezz/JustEnoughItems/issues/3243
