### ISSUE TITLE
[Bug]: 1.20 Item count doesnt show in inventory and cant type in JEI search bar

### ISSUE THREAD

**Issue by xsolane** [mezz/JustEnoughItems#3242]
### Steps to Reproduce the Bug

When opening the inventory the count of items doesnt show. When looking at your inventory through an item like a crafting table or furnance the item counts do show. 

### Expected Behavior

When opening the inventory i should be able to see how many of each item i have and i should be able to type in the JEI search bar.

### Actual Behavior

The number/count of items you have doesnt show in the inventory. I also cant type in the JEI search bar

**Comment by LOLcamp** [comment]
+1

**Comment by LadyKathleen** [comment]
I have the no typing issue as well

**Comment by TheCraftyCoder** [comment]
same

**Comment by mezz** [comment]
Thanks for the report!
The typing issue has been fixed in https://github.com/mezz/JustEnoughItems/commit/9fda12e375f3f481e89524cdbb4781ca70087905

**Comment by mezz** [comment]
I think "Item count doesnt show in inventory" is not related to JEI, I am not able to see anything like that with only JEI installed. If you find this is still happening with only JEI installed, please open a new issue with steps to reproduce the issue and I can try again.
