### ISSUE TITLE
[Crash]: minecraft 1.20 does not launch

### ISSUE THREAD

**Issue by KoryAlbright** [mezz/JustEnoughItems#3243]
### Steps to Reproduce the Crash

Steps to reproduce:
1. run minecraft fabric 0.14.21 with these mods: fabric api 0.83.0+1.20, jei 14.0.0.4
2. the game crashes before it launches.

I have verified i have the latest version of fabric, jei, and fabric api.

### Crash Report

https://gist.github.com/DragonEater2008/438a95f4b5cf34c485c84612d87e580f

**Comment by thebigbird1979** [comment]
Exactly the same for me. MC Launcher just returns exit code 1

**Comment by Beanbag141** [comment]
This happened to me too! Also gives me exit code 1.

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next release.
