### ISSUE TITLE
[Bug]: Molten Fairy Alloy Recipe Not Fully Showing - Tinkers' / Materialis / JEI

### ISSUE THREAD

**Issue by Under031** [mezz/JustEnoughItems#3245]
### Steps to Reproduce the Bug

Open the inventory to look at the alloy recipe for Molten Fairy.

### Expected Behavior

JEI should show all three liquids required to alloy.

### Actual Behavior

Only shows milk and gold.

### latest.log

https://gist.github.com/Under031/aed32e97eddc3ff40394022d7edc24ba

**Comment by KnightMiner** [comment]
This is definitely not a JEI issue. The integration is added on Tinkers Construct side, which I will reiterate works for every other recipe, so I highly doubt just one recipe is broken. Just put the 3 ingredients in the smeltery. If you cannot find what the third is, the mod adding the recipe is the problem.

**Comment by Under031** [comment]
Thank you- it is indeed an issue on the part of Materialis.
