### ISSUE TITLE
Crash with the following error, whenever I hit the "show item uses" button

### ISSUE THREAD

**Issue by MXSteel** [mezz/JustEnoughItems#325]
http://pastebin.com/2nNJ4xne

**Comment by TehNut** [comment]
Looks like Forge needs updating, but can't tell because you cut out the majority of the useful part of the log.

**Comment by MXSteel** [comment]
http://pastebin.com/Wwxu5vat
- Error with forge 1.9.4-12.17.0.1974

Forge 1.9.4-12.17.0.1976 works fine. Apperantly I set the wrong one by mistake. My bad!

**Comment by mezz** [comment]
Any forge 12.17.0.1946 or higher should work fine. Very strange.

**Comment by AEnterprise** [comment]
forge reverted a few commits to make it's license change possible, probably that function was removed with it

**Comment by mezz** [comment]
Good guess but I don't think so, I wrote that function.
