### ISSUE TITLE
[Suggestion]: Support for recipes with insane drop quantities

### ISSUE THREAD

**Issue by kreezxil** [mezz/JustEnoughItems#3256]
### Suggestion
I'm using the Forge 1.19.2 version of JEI

In my new pack Kabbalah Block, I have the Create crushing wheels drop 26 possibilities when the kabbalah block is crushed. JEI picks this up, but since it's more than the UI appears to allow it goes off the side.

I was thinking it could show the maximum slots it can reasonably display in that field and then cycle the various slots thru all the drops.

if there is a JEI feature that handles that already, be so kind and let me know. :)

![image](https://github.com/mezz/JustEnoughItems/assets/3880072/b49a6abc-03fa-4ae6-9588-f592da843869)

**Comment by kreezxil** [comment]
No, it has not. I understand that my situation is a one-off, but I would
appreciate it if it weren't. These Create recipes can output numerous
results, as demonstrated in my Kabbalah pack. If you'll notice that the
mixers even have filters on them to limit their outputs, meaning that a dev
could use the same recipe for 10s if not 100s of outputs only requiring a
filter to differentiate it. So it'd be great if JEI could make that
discernment.

But also, yes, not game breaking, and most devs won't do that. Not yet
anyway. :)

**Comment by kreezxil** [comment]
did we already determine that what I did was edge case and it would not be
implemented? if so, you guys can directly close this.

**Comment by mezz** [comment]
Thanks for the report!
Sorry for the late response.
This code is handled by Create's JEI plugin, please ask them to support this.
There are already some JEI plugins that handle a similarly large number of outputs effectively, like [JER](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer), so it is technically possible.
