### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by Shazuli** [mezz/JustEnoughItems#326]
Hi!

I been having problems with this mod lately, it worked great before. But then one day it stopped working, I got a crash when trying to load a world on singleplayer or multiplayer. What I know is that I didn't change any codes or files that time. Anyways, heres the crash log:
Latest 1.8.9-2.28.18.186 version with no addons for JEI.

https://gist.github.com/mezz/829b5c2fda582de85df2e8a715589b34

**Comment by AEnterprise** [comment]
not a JEI issue but DummyCore, that got stuck in an infinite loop while initiating models and capabilities

**Comment by mezz** [comment]
Thanks for the report!
Please report to DummyCore here:
https://github.com/Modbder/DummyCore/issues?q=is%3Aopen+is%3Aissue
