### ISSUE TITLE
[Crash]: java.lang.NullPointerException: vanilla plugin must not be null. 

### ISSUE THREAD

**Issue by i218** [mezz/JustEnoughItems#3264]
### Steps to Reproduce the Crash

Actually, I don't know how it happens and why, but sometimes when opening the inventory there is a crash "NullPointerException: vanilla plugin must not be null." please tell me what to do with this. (crash report attached)

upd: This happens when logging out of the server and logging in again (without restarting).

### Extra Notes (Optional)

1.18.2
40.2.9

### Crash Report

https://gist.github.com/i218/ffcb592612d722101f8389757743c1f0

**Comment by i218** [comment]
*Comment for activity*

**Comment by mezz** [comment]
Thanks for the report!
Sorry for the late response.
This is probably caused by an earlier crash, can you post your full client log here?
