### ISSUE TITLE
[Suggestion]: Create a paper bridge plugin

### ISSUE THREAD

**Issue by danny99124** [mezz/JustEnoughItems#3265]
### Suggestion

Create a paper plugin that let player use "+" button around recipe.

**Comment by DoctorDinosaur** [comment]
https://github.com/drunderscore/jeibridge

Found this, but it's third party and hasn't been updated in quite a while. Plus only says "simple crafting completion", not sure what that means.


A third party plugin would be good, a la the map mod companion plugins you can find.

**Comment by danny99124** [comment]
Yeah, I've installed it on my server before, but it doesn't work. The button still tell me "The server must have JEI installed".
I guess maybe it's because the mod use some new way to verify whether server have installed jei.

**Comment by DoctorDinosaur** [comment]
REI can use the vanilla recipe book, works so long as the recipe is unlocked. Perhaps JEI could copy.
