### ISSUE TITLE
SubtypeRegistry cannot be used for damageable items

### ISSUE THREAD

**Issue by HenryLoenwind** [mezz/JustEnoughItems#327]
It is only used for items that getHasSubtypes(), so it doesn't work for swords and other damageable items that can have NBT (e.g. the upgradable Ender IO tools).

**Comment by mezz** [comment]
~~If an item does not have subtypes, JEI should ignore damage and nbt on it. I don't understand the use-case, can you please explain?~~ 
ah I get it, ok

**Comment by mezz** [comment]
The subtype interpreter will be used in all cases now, which gives much better control.
Fixed in JEI 3.7.9
