### ISSUE TITLE
[Bug]: (1.19.3) Items from some mods don't show up in the JEI list, do show up in crafting recipes

### ISSUE THREAD

**Issue by blahpers** [mezz/JustEnoughItems#3270]
### Steps to Reproduce the Bug

1. Install Corail Tombstone and/or Forbidden Arcanus.
2. Type "@tombstone" or "@forbidden" into JEI's search field.
3. Note that some items (e.g., grave dust [CT], arcane crystal [FA] do show up.
4. Note that some items (e.g., white marble [CT], lens of veritatis [FA]) do not show up.
5. Right-click on grave dust [CT] and note that the vanilla crafting recipe for white marble [CT]/lens of veritatis [FA] does show up.

### Expected Behavior

New, un-subtyped items registered in the items registry by their mod authors should show up in JEI (barring specific recipe configs or JEI integration to the contrary).

### Actual Behavior

Some items do not show up in the items registry, though they are viewable if you can navigate to the item through some other item that does show up.

### Extra Notes (Optional)

I also reproduced this by writing a trivial mod that adds several new decorative/compression blocks and basic items with no functionality.  I didn't use NBT tags or any kind of subtyping.  Some of my items show up in JEI, but some do not.  I can detect no pattern to this.

**Comment by nanonestor** [comment]
I *think* I've been encountering this same issue with my own mod trying to port it from 1.19.2 to 1.20.1. It only adds one simple item -  The log shows the mod recipes and all the etc as 'added' and 'registered', but nothing shows up in JEI. 😭
