### ISSUE TITLE
[Bug]: Crash when looking at recipes using Ender Storage's Ender Pouch

### ISSUE THREAD

**Issue by aaronhowser1** [mezz/JustEnoughItems#3276]
### Steps to Reproduce the Bug

![image](https://github.com/mezz/JustEnoughItems/assets/15698722/88aaf146-28b6-418e-a0a9-2d91d0dada61)
Hit U

### Expected Behavior

For it to not crash

### Actual Behavior

Crash report https://pastebin.com/0Q5fij7P

### latest.log

https://gist.github.com/aaronhowser1/4c3bcd8555e138b19989de16f8670eee

**Comment by aaronhowser1** [comment]
im gonna punch you right in the gob

**Comment by aaronhowser1** [comment]
I will destroy you

**Comment by mezz** [comment]
Sorry for the late response.
When you have an issue with JEI and one other mod, please report it to the other mod first.
In this case, the mod crashing in the crash report appears to be Create, you can report to them here: https://github.com/Creators-of-Create/Create/issues

**Comment by drenough** [comment]
Hi, can confirm, also posts are here: https://github.com/TheCBProject/EnderStorage/issues/222 https://github.com/Creators-of-Create/Create/issues/6368 and here https://github.com/Creators-of-Create/Create/issues/4122
