### ISSUE TITLE
Fluids are rendered without transparency into the recipe GUI

### ISSUE THREAD

**Issue by HenryLoenwind** [mezz/JustEnoughItems#328]
Fluids are rendered without transparency into the recipe GUI.

![image](https://cloud.githubusercontent.com/assets/1485873/16360192/9b4cebd8-3b53-11e6-8270-443e8ae5d14d.png)

expected (the last one in the pic above):

![image](https://cloud.githubusercontent.com/assets/1485873/16360199/ca6eccc4-3b53-11e6-9c05-422c5fa95e5b.png)

**Comment by mezz** [comment]
Thanks for the report! Fixed in the latest version.

![2016-06-26_18 12 11](https://cloud.githubusercontent.com/assets/916092/16366277/a1d92a7c-3bc9-11e6-9b72-eafe5cda3ba2.png)
