### ISSUE TITLE
Game crashes when trying to view Enderstorage recipies

### ISSUE THREAD

**Issue by FreedomFire97** [mezz/JustEnoughItems#3286]
### Steps to Reproduce the Crash

The crash is cause specifically when right clicking to see what the Ender Chest, Ender Tank, and Ender pouch can be used to craft. I've not tested very many items yet but Vanilla items seems to cause no issue. I am play on MC 1.18.2     Forge 40.2.10.

### Crash Report

https://bytebin.lucko.me/bqfYl1mOfY

**Comment by FreedomFire97** [comment]
Through more digging i've found that Enderstorage seems to be the only mod that will cause a crash like this from what I have installed. I do have a custom modpack.

**Comment by FreedomFire97** [comment]
Through more digging i've found that Enderstorage seems to be the only mod that will cause a crash like this from what I have installed. I do have a custom modpack.

**Comment by FreedomFire97** [comment]
Through more digging i've found that Enderstorage seems to be the only mod that will cause a crash like this from what I have installed. I do have a custom modpack.

**Comment by drenough** [comment]
Hi, can confirm, also posts are here: https://github.com/TheCBProject/EnderStorage/issues/222 https://github.com/Creators-of-Create/Create/issues/6368 and here https://github.com/Creators-of-Create/Create/issues/4122
