### ISSUE TITLE
[Other]: cant type in search fabric 1.20.1

### ISSUE THREAD

**Issue by ninaad7** [mezz/JustEnoughItems#3287]
### Other

when i go to type in the search, i cant type anything at all, like nothing, including numbers, characters and letters. i can type what im looking to craft somewhere outside minecraft and copy and paste it but its also a waste of time, might as well as to just scroll through the pages to find it. im clicking on it, went into configs and looked around, idk

**Comment by Hyper-Miiko** [comment]
Same issue, I'm using jei-1.20.1-fabric-15.2.0.23 (I have a lot of other mods)

**Comment by mindblaster0076** [comment]
Same issue, same version.
