### ISSUE TITLE
Crash and kick to desktop

### ISSUE THREAD

**Issue by Calsifer** [mezz/JustEnoughItems#329]
Not sure if it was mentioned somewhere earlier, not even sure if that's the place I'm runing mc with so many mods now. Anyhow here's my crash raport :

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.5.52-ex19.jar)
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  LoadingPlugin (Quark-beta-29.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 6/26/16 5:55 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: mezz/jei/gui/ingredients/IGuiIngredient
    at crazypants.enderio.jei.EnchanterRecipeCategory$EnchanterRecipeWrapper.drawInfo(EnchanterRecipeCategory.java:64)
    at mezz.jei.gui.RecipeLayout.draw(RecipeLayout.java:77)
    at mezz.jei.gui.RecipesGui.func_73863_a(RecipesGui.java:172)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1095)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: mezz.jei.gui.ingredients.IGuiIngredient
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 22 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at crazypants.enderio.jei.EnchanterRecipeCategory$EnchanterRecipeWrapper.drawInfo(EnchanterRecipeCategory.java:64)
    at mezz.jei.gui.RecipeLayout.draw(RecipeLayout.java:77)
    at mezz.jei.gui.RecipesGui.func_73863_a(RecipesGui.java:172)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)

-- Screen render details --
Details:
    Screen name: mezz.jei.gui.RecipesGui
    Mouse location: Scaled: (153, 59). Absolute: (612, 812)
    Screen size: Scaled: (461, 263). Absolute: (1842, 1052). Scale factor of 4

-- Affected level --
Details:
    Level name: MpServer
    All players: 2 total; [EntityPlayerSP['Sivid'/216997, l='MpServer', x=684.73, y=64.00, z=-2033.77], EntityOtherPlayerMP['Liladriel'/43767, l='MpServer', x=690.19, y=64.00, z=-2023.53]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-133,64,309), Chunk: (at 11,4,5 in -9,19; contains blocks -144,0,304 to -129,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 25589555 game time, 26852643 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 68 total; [EntitySpark['Spark'/0, l='MpServer', x=679.50, y=65.50, z=-2029.50], EntityHorse['Skeleton Horse'/2, l='MpServer', x=666.04, y=64.00, z=-2038.46], EntityPlayerSP['Sivid'/216997, l='MpServer', x=684.73, y=64.00, z=-2033.77], EntitySpark['Spark'/3, l='MpServer', x=664.50, y=64.50, z=-2037.50], EntitySpark['Spark'/4, l='MpServer', x=669.50, y=65.50, z=-2034.50], EntitySpark['Spark'/5, l='MpServer', x=670.50, y=65.50, z=-2033.50], EntitySpark['Spark'/6, l='MpServer', x=670.50, y=65.50, z=-2035.50], EntityZombie['Zombie'/240651, l='MpServer', x=626.74, y=68.00, z=-1960.56], EntitySpark['Spark'/11, l='MpServer', x=664.50, y=64.50, z=-2031.50], EntityOtherPlayerMP['Liladriel'/43767, l='MpServer', x=690.19, y=64.00, z=-2023.53], EntityZombie['Zombie'/240659, l='MpServer', x=654.50, y=65.00, z=-2111.50], EntitySkeleton['Skeleton'/240658, l='MpServer', x=697.32, y=55.00, z=-2057.50], EntityZombie['Zombie'/216991, l='MpServer', x=670.55, y=24.00, z=-2065.21], EntityCow['Cow'/217247, l='MpServer', x=757.80, y=129.00, z=-2104.49], EntityPig['Pig'/216990, l='MpServer', x=631.50, y=66.00, z=-2003.25], EntityZombie['Zombie'/217246, l='MpServer', x=685.81, y=56.00, z=-2054.52], EntityChicken['Chicken'/217123, l='MpServer', x=612.55, y=78.00, z=-2035.24], EntityChicken['Chicken'/217122, l='MpServer', x=617.65, y=77.00, z=-2039.17], EntityPig['Pig'/217121, l='MpServer', x=655.25, y=64.00, z=-2075.75], EntityCow['Cow'/217249, l='MpServer', x=743.21, y=128.00, z=-2105.50], EntityZombie['Zombie'/216992, l='MpServer', x=681.78, y=18.00, z=-2053.37], EntityPig['Pig'/217120, l='MpServer', x=647.50, y=67.00, z=-2072.20], EntityCow['Cow'/217248, l='MpServer', x=751.20, y=129.00, z=-2096.40], EntitySheep['Sheep'/217255, l='MpServer', x=752.73, y=80.00, z=-2079.50], EntityZombie['Zombie'/217126, l='MpServer', x=703.48, y=20.00, z=-2091.27], EntitySheep['Sheep'/217254, l='MpServer', x=762.50, y=64.00, z=-2062.80], EntityPig['Pig'/217125, l='MpServer', x=623.75, y=70.00, z=-1985.50], EntityPig['Pig'/217253, l='MpServer', x=755.51, y=69.00, z=-2071.75], EntityBat['Bat'/217131, l='MpServer', x=679.15, y=59.10, z=-2064.69], EntityPig['Pig'/217259, l='MpServer', x=740.50, y=80.00, z=-2055.50], EntityPig['Pig'/217258, l='MpServer', x=744.75, y=76.00, z=-2057.49], EntityPig['Pig'/217257, l='MpServer', x=749.45, y=69.00, z=-2052.80], EntityPig['Pig'/217256, l='MpServer', x=738.45, y=78.00, z=-2052.45], EntitySkeleton['Skeleton'/238636, l='MpServer', x=708.50, y=34.00, z=-2079.50], EntityZombie['Zombie'/217138, l='MpServer', x=692.52, y=54.00, z=-2048.74], EntitySheep['Sheep'/217271, l='MpServer', x=755.73, y=65.00, z=-2056.15], EntityPig['Pig'/217270, l='MpServer', x=754.29, y=63.00, z=-2036.42], EntityPig['Pig'/217269, l='MpServer', x=751.48, y=69.00, z=-2056.69], EntitySheep['Sheep'/217268, l='MpServer', x=761.84, y=72.00, z=-2078.74], EntityPig['Pig'/217272, l='MpServer', x=752.22, y=71.00, z=-2053.49], EntityItem['item.item.egg'/227264, l='MpServer', x=629.34, y=66.00, z=-2089.34], EntitySquid['Squid'/239815, l='MpServer', x=747.60, y=62.00, z=-1974.08], EntitySquid['Squid'/239814, l='MpServer', x=742.46, y=59.33, z=-1971.35], EntityCreeper['Creeper'/241097, l='MpServer', x=715.50, y=65.00, z=-2079.50], EntitySquid['Squid'/239816, l='MpServer', x=745.18, y=61.00, z=-1987.60], EntityZombie['Zombie'/204, l='MpServer', x=693.49, y=37.00, z=-1998.78], EntityItem['item.item.string'/241997, l='MpServer', x=624.11, y=67.00, z=-2094.38], EntityCreeper['Creeper'/241100, l='MpServer', x=673.50, y=26.00, z=-2020.50], EntityZombie['Zombie'/242636, l='MpServer', x=632.50, y=38.00, z=-2078.50], EntityZombie['Zombie'/241106, l='MpServer', x=660.24, y=26.00, z=-1961.35], EntityCreeper['Creeper'/242641, l='MpServer', x=733.50, y=14.00, z=-2113.50], EntityItem['item.item.string'/240208, l='MpServer', x=641.80, y=18.00, z=-2044.65], EntitySpider['Spider'/241104, l='MpServer', x=612.45, y=72.00, z=-1978.95], EntitySpider['Spider'/241111, l='MpServer', x=624.50, y=67.00, z=-2093.50], EntityItem['item.item.dyePowder.black'/229209, l='MpServer', x=737.59, y=49.00, z=-2017.82], EntityItem['item.item.bone'/223455, l='MpServer', x=658.70, y=53.00, z=-2008.58], EntityItem['item.item.feather'/239588, l='MpServer', x=629.64, y=66.00, z=-2088.37], EntityZombie['Zombie'/241134, l='MpServer', x=606.53, y=71.00, z=-1984.41], EntityCow['Cow'/216179, l='MpServer', x=648.15, y=66.00, z=-1965.66], EntityCow['Cow'/216178, l='MpServer', x=654.36, y=64.00, z=-2005.17], EntityCreeper['Creeper'/241143, l='MpServer', x=627.59, y=71.00, z=-1954.84], EntityPig['Pig'/216182, l='MpServer', x=722.55, y=63.00, z=-1977.55], EntitySkeleton['Skeleton'/241142, l='MpServer', x=628.69, y=67.00, z=-2083.51], EntityZombie['Zombie'/241141, l='MpServer', x=634.50, y=66.00, z=-2082.50], EntityOtherPlayerMP['Liladriel'/43767, l='MpServer', x=690.19, y=64.00, z=-2023.53], EntityChicken['Chicken'/217208, l='MpServer', x=628.50, y=67.00, z=-2088.87], EntityManaBurst['Mana Burst'/242814, l='MpServer', x=671.46, y=67.50, z=-2039.29], EntitySkeleton['Skeleton'/240636, l='MpServer', x=631.50, y=61.00, z=-2065.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:390)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2105745432 bytes (2008 MB) / 3999268864 bytes (3814 MB) up to 5607784448 bytes (5348 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx6016m
    IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
    FML: MCP 9.28 Powered by Forge 12.17.0.1987 47 mods loaded, 47 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1987-universal.jar) 
    UCHIJA  Forge{12.17.0.1987} [Minecraft Forge](forge-1.9.4-12.17.0.1987-universal.jar) 
    UCHIJA  bagginses{2.4.2c} [Bagginses](Bagginses-1.9.4-2.4.2c.jar) 
    UCHIJA  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJA  bdlib{1.12.0.2} [BD Lib](bdlib-1.12.0.2-mc1.9.4.jar) 
    UCHIJA  BiomesOPlenty{4.1.0.2031} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2031-universal.jar) 
    UCHIJA  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
    UCHIJA  JEI{3.7.0.218} [Just Enough Items](jei_1.10-3.7.0.218.jar) 
    UCHIJA  BloodMagic{1.9.4-2.0.2-46} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-46.jar) 
    UCHIJA  Botania{r1.8-311} [Botania](Botania-unofficial.r1.8-311.jar) 
    UCHIJA  Chameleon{1.9-2.1.4} [Chameleon](Chameleon-1.9-2.1.4.jar) 
    UCHIJA  chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.29.jar) 
    UCHIJA  cei{1.2} [Chunk Edge Indicator](Chunk-Edge-Indicator-Mod-1.9.4.jar) 
    UCHIJA  cookingforblockheads{3.0.7} [Cooking for Blockheads](CookingForBlockheads-mc1.9.4-3.0.7.jar) 
    UCHIJA  ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UCHIJA  deepresonance{1.2.0beta34} [DeepResonance](deepresonance-1.9.4-1.2.0beta34.jar) 
    UCHIJA  endercore{1.9.4-0.4.0.26-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.26-alpha.jar) 
    UCHIJA  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJA  EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.46_alpha.jar) 
    UCHIJA  IC2{2.5.52-ex19} [IndustrialCraft 2](industrialcraft-2-2.5.52-ex19.jar) 
    UCHIJA  forestry{5.0.23.170} [Forestry](forestry_1.9.4-5.0.23.170.jar) 
    UCHIJA  GardenOfGlass{sqrt(-1)} [Garden of Glass](GardenOfGlass.jar) 
    UCHIJA  advgenerators{0.9.20.2} [Advanced Generators](generators-0.9.20.2-mc1.9.4.jar) 
    UCHIJA  inventorytweaks{1.61-dev-53-0736dc3} [Inventory Tweaks](InventoryTweaks-1.61-dev-53.jar) 
    UCHIJA  IronChest{7.0.2.790} [Iron Chest](ironchest-1.10-7.0.2.790.jar) 
    UCHIJA  journeymap{1.9.4-5.2.3} [JourneyMap](journeymap-1.9.4-5.2.3-unlimited.jar) 
    UCHIJA  jeresources{0.4.6.36} [Just Enough Resources](JustEnoughResources-1.9.4-0.4.6.36.jar) 
    UCHIJA  llor{1.0.7-mc1.9.4} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.7-mc1.9.4.jar) 
    UCHIJA  mantle{1.9.4-0.10.2.jenkins149} [Mantle](Mantle-1.9.4-0.10.2.jar) 
    UCHIJA  Morpheus{1.9.4-3.1.3} [Morpheus](Morpheus-1.9.4-3.1.3.jar) 
    UCHIJA  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4c.jar) 
    UCHIJA  Psi{r1.0-35} [Psi](Psi-r1.0-35.jar) 
    UCHIJA  Quark{beta-29} [Quark](Quark-beta-29.jar) 
    UCHIJA  randomthings{3.7.3} [Random Things](RandomThings-MC1.9.4-3.7.3.jar) 
    UCHIJA  xreliquary{1.9.4-1.3.2.390} [Reliquary](Reliquary-1.9.4-1.3.2.390.jar) 
    UCHIJA  rftools{4.66} [RFTools](rftools-1.9.4-4.66.jar) 
    UCHIJA  rftoolsdim{4.30beta43} [RFTools Dimensions](rftoolsdim-1.9.4-4.30beta43.jar) 
    UCHIJA  runesofwizardry{1.9.4-0.6.7} [Runes of Wizardry](Runes-of-Wizardry-1.9.4-0.6.7.jar) 
    UCHIJA  runesofwizardry_classics{1.9.4-0.3.4} [Runes of Wizardry - Classic Dusts Pack](RunesofWizardry-Classics-1.9.4-0.3.4.jar) 
    UCHIJA  simpleretrogen{3.0.1+6} [Simple Retrogen](simpleretrogen-1.9.4-3.0.1+6.jar) 
    UCHIJA  StorageDrawers{1.9.4-3.1.10} [Storage Drawers](StorageDrawers-1.9.4-3.1.10.jar) 
    UCHIJA  tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct](TConstruct-1.9.4-2.3.3.jar) 
    UCHIJA  torohealthmod{1.9.4-5} [ToroHealth Damage Indicators](torohealth-1.9.4-5.jar) 
    UCHIJA  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    UCHIJA  ICSE{1.0.0.0} [I Can See Everything](Wawla-1.9.4-2.2.1.192.jar) 
    UCHIJA  wawla{2.2.1.188} [What Are We Looking At](Wawla-1.9.4-2.2.1.192.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.5.52-ex19.jar)

CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
LoadingPlugin (Quark-beta-29.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4463' Renderer: 'Intel(R) HD Graphics 4600'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.2-46.jar
    * BotaniaAPI (79) from Botania-unofficial.r1.8-311.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.5.29.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.5.29.jar
    * CoFHAPI (1.8.9R1.2.0B1) from EnderIO-1.9.4-3.0.0.46_alpha.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from forestry_1.9.4-5.0.23.170.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.2.0beta34.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
    * EnderIOAPI (0.0.2) from EnderIO-1.9.4-3.0.0.46_alpha.jar
    * EnderIOAPI|Redstone (0.0.2) from EnderIO-1.9.4-3.0.0.46_alpha.jar
    * EnderIOAPI|Teleport (0.0.2) from EnderIO-1.9.4-3.0.0.46_alpha.jar
    * EnderIOAPI|Tools (0.0.2) from EnderIO-1.9.4-3.0.0.46_alpha.jar
    * ForestryAPI|apiculture (4.8.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|arboriculture (4.2.1) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|circuits (3.1.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|core (5.0.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|farming (2.1.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|food (1.1.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|fuels (2.0.1) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|genetics (4.7.1) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|greenhouse (5.0.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|hives (4.1.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|lepidopterology (1.3.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|mail (3.0.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|multiblock (3.0.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|recipes (5.4.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|storage (3.0.0) from forestry_1.9.4-5.0.23.170.jar
    * ForestryAPI|world (2.1.0) from forestry_1.9.4-5.0.23.170.jar
    * IC2API (1.0) from industrialcraft-2-2.5.52-ex19.jar
    * jeresources|API (0.4.6.36) from JustEnoughResources-1.9.4-0.4.6.36.jar
    * journeymap|client-api (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-display (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-event (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-model (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-util (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * JustEnoughItemsAPI (4.0.0) from jei_1.10-3.7.0.218.jar
    * McJtyLib (1.9.4-1.9.0) from mcjtylib-1.9.4-1.9.0.jar
    * PsiAPI (2) from Psi-r1.0-35.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
EnderIO: No known problems detected.
Launched Version: MultiMC5
LWJGL: 2.9.1
OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4463, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: net.minecraft.client.Minecraft$15@106e5263`
```

**Comment by mezz** [comment]
Thanks for the report!
This version of JEI is intended for Minecraft 1.10. The latest one for 1.9.4 is JEI 3.6.7
http://minecraft.curseforge.com/projects/just-enough-items-jei/files

**Comment by DoughnutDev** [comment]
I am getting something similar with 1.10.2 https://hastebin.com/uvalericey.php
