### ISSUE TITLE
[Crash]: Certain combination of mods freezes the game when opening inventory

### ISSUE THREAD

**Issue by WowyDoesThings** [mezz/JustEnoughItems#3291]
### Steps to Reproduce the Crash

1. Create a survival (important) world with JEI, EMI, Architectury API, and FTB Library installed.
2. Attempt to open inventory.
3. If game hasn't froze yet, craft a double chest and open it.

### Extra Notes (Optional)

Minecraft: 1.19.2
Forge: 43.2.21
EMI: 1.0.18
JEI: 11.6.0.1016
FTB Library: 1902.4.1-build.236
Architectury API: 6.5.85

Test was done using a fresh instance and latest version of everything.

### Crash Report

https://gist.github.com/WowyDoesThings/bafa920f85b118314d4bfd4ef3a1eb8a

**Comment by hacktheplanet86** [comment]
had the same problem- have a temporary fix by adding two items from create to jeis blacklist in the config.  the two items are

create:wand_of_symmetry
create:handheld_worldshaper

each item needs its own line in the blacklist config, hope it works for you for now at least
