### ISSUE TITLE
[Crash]: JEI is not installed?

### ISSUE THREAD

**Issue by Con-scripter** [mezz/JustEnoughItems#3295]
### Steps to Reproduce the Crash

all i did was download Just Enough Items, and it said I needed to download another mod for it, what gives? (it says i need jei 9.5.0 or above)

### Crash Report

https://gist.github.com/Con-scripter/237718333bbccbfcd0509d1ff7c8259d

**Comment by way2muchnoise** [comment]
According to the log you installed Just Enough Resources, a Just Enough Items addon.
JEI: https://www.curseforge.com/minecraft/mc-mods/jei
JER: https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
