### ISSUE TITLE
Not accepting Forge 1.10-12.18.0.2000

### ISSUE THREAD

**Issue by VsnGamer** [mezz/JustEnoughItems#330]
Hello I updated JEI to the lastest version and Forge too but this comes up.
It says i need forge 1999 or above but im running forge 2000.
Heres the Print.
Thanks !

![screenshot_1](https://cloud.githubusercontent.com/assets/18006201/16376932/0a4cd25c-3c5b-11e6-865d-91c93311f045.png)

**Comment by mezz** [comment]
Did you figure out the solution?
