### ISSUE TITLE
[Bug]: recipes not showing up on 1.18.2

### ISSUE THREAD

**Issue by grimosrs** [mezz/JustEnoughItems#3302]
### Steps to Reproduce the Bug

1. boot up minecraft forge 1.18.2
2. join server hosted on mcprohosting
3. open inventory
4. click on any item

### Expected Behavior

it should show the correct recipe

### Actual Behavior

nothing happens when clicking on any item

### Extra Notes (Optional)

it only affects one person in the server, unsure why

### latest.log

https://gist.github.com/grimosrs/c3db654ecbe9bb4f7014d20c2771d324

**Comment by Koriita0** [comment]
I have the same problem, can you fixed it?

**Comment by WTFolsen** [comment]
any fix for this? just encounterd it in 1.20

**Comment by DrollestDuck88** [comment]
I have the <<same>> problem on Aternos
