### ISSUE TITLE
[Crash]: game crashes with create mod (1.20.1)

### ISSUE THREAD

**Issue by workingwithbat** [mezz/JustEnoughItems#3304]
### Steps to Reproduce the Crash

when I open up the menu and go Past the 10th tab it crashes.
![crashed game - Imgur (1)](https://github.com/mezz/JustEnoughItems/assets/71386510/1905392f-4efd-4c57-8073-1e8bf8b24b89)

### Mods Installed
![Screenshot 2023-08-16 195803 (1)](https://github.com/mezz/JustEnoughItems/assets/71386510/477dea6b-b05f-41a4-b3b6-918950353ed4)

### Extra Notes 

It says it was the create mod when it says under details (create:wand_of_symmetry)

### Crash Report

https://gist.github.com/GlaserGames/1d9125808ef43f9b8a5068020d04f74f

**Comment by workingwithbat** [comment]
just figured out it isnt only JEI, I need to go to the create Github

**Comment by lightmargin** [comment]
I also wrote an issue post earlier on this with a similar issue, with our JEI crashing with multiple different mods that appear to have '3D models' for items. What version of JEI were you using?
