### ISSUE TITLE
JEI crashing when typing in search box

### ISSUE THREAD

**Issue by Daedelious** [mezz/JustEnoughItems#331]
https://gist.github.com/Daedelious/86d089619ab0c6025f9e86cca5b5c7ed  
https://gist.github.com/Daedelious/90da6e73cd75b9123db00dbed0d82eb4

My crash log(s), I dunno which are useful, the first is from: C:...\ATLauncher\Instances\ResonantRiseDev\logs) 
while the second is copied from the ATLauncher console.

I'm playing on RR4 and have been experiencing crashes when I type in the search box(attempt to).

I open JEI,
Click the search box below the items,
press any letter and it crashes, 

I can search through JEI with the left search arrow above the items but the right arrow also crashes me.

**Comment by Daedelious** [comment]
Okay nvm something became corrupted, I deleted everything and installed from scratch, works fine now. 
Sorry for the fuss :)

**Comment by Daedelious** [comment]
I thought I had a fix for this but after I searched a few times and then it crashes. About 3-5 times I type a phrase or word into the search box and then it crashes. 

The arrow is still broken... I can click it once and then it crashes. Crash log for the right arrow is below as I don't know if both issues(arrow and searching) are the same problem or separate.
https://gist.github.com/Daedelious/8682e3b872733d41d6d916b43b0fe634

**Comment by mezz** [comment]
Thanks for the report!
This looks like an issue with Sponge. Please try without Sponge and report back.

**Comment by Daedelious** [comment]
Okay I disabled sponge and it works. The game froze at one point for about 10 seconds(didn't respond) and as I waited for a crash it fixed itself and is working 100%. 

If you want the log for when it froze(not sure if would even be in the log actually) you'll have to tell me how to get that to you. 

Thanks for the help!

**Comment by mezz** [comment]
Glad it worked!
Based on the log, I suspect someone is adding a lot of player heads to the creative item list, which can lag the game when first viewed. This is a known bug with Minecraft, see https://github.com/MinecraftForge/MinecraftForge/issues/2835
