### ISSUE TITLE
[Bug]:  Maven down

### ISSUE THREAD

**Issue by DePhoegon** [mezz/JustEnoughItems#3310]
### Steps to Reproduce the Bug

Attempt to load a project in intellij with jei in it.
 ```
maven {
    // location of the maven that hosts JEI files before January 2023
    name = "Progwml6's maven"
    url = "https://dvs1.progwml6.com/files/maven/"
  }
```

### Expected Behavior

It downloads the files

### Actual Behavior

It prevents even the fallback mavens from working.   

### Extra Notes (Optional)

Removing that maven from the build.gradle file.

**Comment by YerovaArusu** [comment]
Just enough Items seems to have switched the maven provider:
Simply change the URL like this:

    maven {
        name = "Progwml6 maven"
        url = "https://maven.blamejared.com/"
    }

**Comment by DePhoegon** [comment]
Thanks, I wasn't aware of the change.  I had that one in already.  it was listed as the fallback (but I had to remove the first one)
