### ISSUE TITLE
[Bug]: Can't write in the search bar filter (bottom right)

### ISSUE THREAD

**Issue by Guillaume-Samson** [mezz/JustEnoughItems#3312]
### Steps to Reproduce the Bug

When i focus the search bar and click on it, i'm trying to write something, but nothing happen. 

The search bar is empty. Impossible to write something on it. The navigation is still possible with the arrows, but the filter doesn't work.

### Expected Behavior

The search bar filter should work correctly :)

### Actual Behavior

Impossible to write something in the search bar filter. Nothing happen.

Impossible to filter items, i can't write in the search bar.

By the way, orther fieds like in-game chat work well. (my keyboard is plugged in ^^)

### Mod Pack Version (Optional)

jei-1.20.1-fabric-15.0.0.14

### Extra Notes (Optional)

Maybe my game configuration is broken ?

### latest.log

https://gist.github.com/Guillaume-Samson/a2d23563af47272b64a84de234b2b2ae

**Comment by F4ntommoth** [comment]
I am having the exact same issue on 1.20.1 as well

**Comment by ItIsAdam** [comment]
Same issue

**Comment by yztz** [comment]
It's most likely due to mod conflicts.
