### ISSUE TITLE
[Other]: JEI needs Configured on 1.20.x, but mod isn't out yet for that version

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#3313]
### Other

Just Enough Items reports it needs the Configured mod, but that mod hasn't been released for Forge / Fabric on 1.20.x yet.

**Comment by chunkybees** [comment]
https://www.curseforge.com/minecraft/mc-mods/jei/files/4712868

**Comment by mindblaster0076** [comment]
Still does not work.

**Comment by ChickenDestroyer** [comment]
Issue still persists in latest version.
