### ISSUE TITLE
[Other]: JEI not working correctly on server 

### ISSUE THREAD

**Issue by ThiccHomiesInc** [mezz/JustEnoughItems#3315]
### Other

Hello,
I apologize for my naivete, I'm new to creating a server. I'm running ATM 9.
JEI is displaying only a few pages of items on my new server and I'm sure why. I tried seeing if something was wrong with the config files but they match exactly with the local files. JEI works perfectly in singleplayer but not on this new server I made using Pebble Hosting. I really don't know what to do but I have access to any file on the server. If anybody has an idea of what's happening, please let me know.
![2023-08-30_02 36 46](https://github.com/mezz/JustEnoughItems/assets/73076034/07289c89-ff9a-4773-a2fc-cd6cafa72130)

Thank you for taking the time to read.

**Comment by twifft** [comment]
I have the exact same problem since i upgraded from Forge 1.20.1 47.1.0 to 1.20.1 47.2.0
It only shows fluids on the server!

**Comment by Paradigm-3** [comment]
I have the same issue.. Just set up a dedicated server yesterday with ATM 9 v0.0.61 and JEI is only displaying the same few items as in your screenshot. Though it works in single player, and I have one other player on the server who said it worked briefly, but not any more after the first relog.
