### ISSUE TITLE
[Bug]: JEI tag search only check item tags, not block tags

### ISSUE THREAD

**Issue by Pixelatedd66** [mezz/JustEnoughItems#3320]
### Steps to Reproduce the Bug

enable tag search
search for any block tag such as:
$wither_immune
or
$dragon_immune
Nothing will appear

### Expected Behavior

multiple blocks, that match those tags,  should appear

### Actual Behavior

no blocks show up

### Mod Pack URL (Optional)

All the mods 9

### Mod Pack Version (Optional)

0.0.63

### Extra Notes (Optional)
perhaps add block tag search as its own symbol, personally i think it should be "%"
example:
%dragon_immune

**Comment by mezz** [comment]
Thanks for the suggestion!
Sorry for the late reply.

I think this is similar enough to item tags to combine them under the same symbol. 
I have added a config option to turn this functionality off if desired.

![2024-01-29_11 02 15](https://github.com/mezz/JustEnoughItems/assets/916092/d77d23f8-a422-4fdc-9628-d01a9de9d17f)
