### ISSUE TITLE
[Crash]: Looking certain things up in JEI (as well as creative search bar) causing minecraft to crash

### ISSUE THREAD

**Issue by BigD57** [mezz/JustEnoughItems#3324]
### Steps to Reproduce the Crash

1. Open Inventory
2. Start Typing "Strength" (there are others but that was the most recent one)
3. Game crashes as soon as you type out the r.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond

### Mod Pack Version (Optional)

1.16.5

### Extra Notes (Optional)

I feel like its another mod causing this but JEI is triggering it and so this feels like a good place to start

### Crash Report

https://gist.github.com/BigD57/837c59131ec56f2ab7bbed2a272f341b

**Comment by mezz** [comment]
Sorry for the late reply.
You can see the item being rendered in the crash log:
```
-- Item being rendered --
Details:
	Item Type: microblock
	Registry Name: cb_microblock:microblock
	Item Damage: 0
	Item NBT: {factory_id:3,mat:"minecraft:stone",size:1}
	Item Foil: false
```

it looks like a codechicken microblock, their issue tracker is here: https://github.com/Chicken-Bones/ForgeMultipart/issues
