### ISSUE TITLE
[Crash]: Opening JEI via [E] and waiting for 30-seconds crashes the game.

### ISSUE THREAD

**Issue by SirTwsted** [mezz/JustEnoughItems#3325]
### Steps to Reproduce the Crash

1. Opening the JEI items window crashes game.
2. It does it immediately when opening JEI or waiting 30-seconds.
3. Clicking on next page causes JEI to crash.
4. Looking up entire mod list of items using @ crashes the game.
5. Searching for specific item in JEI causes game to crash.

Here is the crash log
https://pastebin.com/SveN50Za

I am not playing a specific released mod pack.
I am playing a custom mod pack I built.  Here is the list.
https://pastebin.com/FYMygaqB

Minecraft v1.20.1
Forge v47.1.46
JEI v15.2.0.27

### Crash Report

https://pastebin.com/SveN50Za

**Comment by markusmagomedov** [comment]
Have the same issue with the same version

**Comment by mezz** [comment]
Thanks for the report!
Sorry for the late response.

Please try removing rubidium and other mods, which may be causing this issue.
