### ISSUE TITLE
[Bug]:  Mod Items from recipes wont transfer to crafting grid of storage networks (server side)

### ISSUE THREAD

**Issue by Smurx** [mezz/JustEnoughItems#3328]
### Steps to Reproduce the Bug

On server
1. go to crafting grid of any storage mod
2. open crafting grid
3. lookup recipe of a mod item (for example Powah etc)
4. try to shift click the "+" button to fill in crafting recipe with items from the storage
5. only non mod items will be filled in crafting grid

### Expected Behavior

All items mod or not mod related schould be filled in to the crafting grid

### Actual Behavior

Only non mod items get filled into the crafting grid and the overlay in jei displays red color behind the items although they are rpesent in the storage system

### Mod Pack URL (Optional)

https://legacy.curseforge.com/minecraft/modpacks/kda-vanilla

### Mod Pack Version (Optional)

2.5

### Extra Notes (Optional)

It kinda just slowly occured in the last few days.
Only happens on server though so idk.
Error occurs with refined "storage network" or simple "storage network".
If u have the mod items in your inventory it doesnt shows them red in the recipe menu but it still wont shift them into the crafting grid.
The minecraft crafting table and tinkers construct crafting station works though

some mods that tend to work with it (tinkers recipes work fine, oh the biomes youll go works fine, =
some mods that dont tend to work with it (Powah, refined storage systems, storage drawers, for some reason stained glass from tinkers construct doesnt works?!?,)

### latest.log

https://gist.github.com/Smurx/246f32b14338c2280a88231159d178f7

**Comment by mezz** [comment]
Thanks for the report!
JEI recipe transfer for storage systems are handled by the storage mods directly, please report to them and link back here.
