### ISSUE TITLE
[Bug]: jei recipe not showing 

### ISSUE THREAD

**Issue by DrollestDuck88** [mezz/JustEnoughItems#3329]
### Steps to Reproduce the Bug

have an aternos server with at least jei in 1.18.2 forge version 40.2.10 and some other mods like mekanism, immersive, project e,  ae2, draconic, create, colossal chest,journey map, mystical agriculture, pneumatic craft, powah, quark, refined storage, colossal chest and botany pots. i have more i will just not put them all because it would be too long... 

### Expected Behavior

recipe for crafting and all showing

### Actual Behavior

every crafting funace and all isn't showing recipe

### Mod Pack Version (Optional)

40.2.10 forge

**Comment by Koriita0** [comment]
I have the same problem, can you fixed it?

**Comment by DrollestDuck88** [comment]
> I have the same problem, can you fixed it?

**Comment by DrollestDuck88** [comment]
I’m dumb

**Comment by DrollestDuck88** [comment]
Sorry I just pressed the button by accident

**Comment by DrollestDuck88** [comment]
> ### Steps to Reproduce the Bug
> have an aternos server with at least jei in 1.18.2 forge version 40.2.10 and some other mods like mekanism, immersive, project e, ae2, draconic, create, colossal chest,journey map, mystical agriculture, pneumatic craft, powah, quark, refined storage, colossal chest and botany pots. i have more i will just not put them all because it would be too long...
> 
> ### Expected Behavior
> recipe for crafting and all showing
> 
> ### Actual Behavior
> every crafting funace and all isn't showing recipe
> 
> ### Mod Pack URL (Optional)
> _No response_
> 
> ### Mod Pack Version (Optional)
> 40.2.10 forge
> 
> ### Extra Notes (Optional)
> _No response_
> 
> ### latest.log
> _No response_


I’m not on client at all it’s on Aternos I don’t know if the issue is present on client too or just server side

**Comment by karmanthea** [comment]
would also like to know how to fix this.

**Comment by DBlade-Requiem** [comment]
You fixed it? If not, do you has "The One Probe" mod? I removed it, and suddenly all works well.

**Comment by DrollestDuck88** [comment]
> You fixed it? If not, do you has "The One Probe" mod? I removed it, and suddenly all works well.

I will try that but I love <<The one probe>> I don’t know if it is the one responsible for the crafts not showing with JEI… if it is the one that does this I will try another version.
