### ISSUE TITLE
JEI 

### ISSUE THREAD

**Issue by xIceSlayerx** [mezz/JustEnoughItems#333]
Hello! I was wondering is there any 1.9 JEI Mod out there? Because I could not find any as Youtube Videos lead to this website and I can't find any 1.9 JEI Mod.Theres only 1.9.4 which is not what I want.Can someone tell me the answer to this?

**Comment by KnightMiner** [comment]
Go to the Curse download page and download the latest one for 1.9, you can find it easily by Google searching.

Though there really is no reason not to update your other mods to 1.9.4

**Comment by mezz** [comment]
http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2297416
