### ISSUE TITLE
[Bug]: jei doesn't show recipes from some mods

### ISSUE THREAD

**Issue by Manuelmc71** [mezz/JustEnoughItems#3336]
### Steps to Reproduce the Bug

jei doesn't show recipes for the following mods in version 1.19.2.

Let's do vinery
Let's do meadow
Let's do beachparty
Let's do backery

all the recipe using normal minecraft crafting station like crafting table and oven work fine, but the one using the mods custom crafting station refuse to show up.

### Expected Behavior

I would like to see the recipes of said mods to be able to show.

### Actual Behavior

The recipe isn't shown when the item can be crafted.

### Mod Pack Version (Optional)

1.19.2

**Comment by NekoLeila** [comment]
Starbunclemania is only showing a couple items, and Spice of Life: Apple Pie Edition isn't showing any.

Playing in 1.20.1

**Comment by mezz** [comment]
Thanks for the report!
JEI does not add support for every mod itself, instead each mod is responsible for adding its own plugin to JEI in order to display custom recipes.
If you see recipes missing from specific mods, please report the issue to them.
