### ISSUE TITLE
[Bug]: Cant access settings menu (1.20.1)

### ISSUE THREAD

**Issue by TimyIsCool** [mezz/JustEnoughItems#3338]
### Steps to Reproduce the Bug

Whenever i click on the settings it tells me to use "Configured" But I dont see a version for 1.20.1
I would like to change the width so it fills from the left to the side of my inventory and enable cheat

### Expected Behavior

Should allow me to edit settings for JEI

### Actual Behavior

Tells me to download a mod that doesn't work with my version

### Mod Pack Version (Optional)

1.20.1-forge-15.2.0.27

**Comment by Lucky-56** [comment]
you can edit the files in the config folder `./config/jei/jei-client.ini`
you can access the folder by clicking the text `Click here to open JEI config folder` as seen here
![click_here](https://github.com/mezz/JustEnoughItems/assets/55949451/0aacd5eb-992b-479f-af13-b44c3b84f733)

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878
