### ISSUE TITLE
Just Enough Items Acting Weird 

### ISSUE THREAD

**Issue by Molalli** [mezz/JustEnoughItems#334]
I opened up a world and it worked fine. After a few minutes, the side bar for the mod disappeared. I know it is still active, but it isn't working right.

**Comment by TehNut** [comment]
Did you disable it? IIRC, the default keybind is `CTRL+O`.

**Comment by Molalli** [comment]
no. Its not disabled

**Comment by mezz** [comment]
Can you paste your client log to https://gist.github.com? Maybe there is information there.
Have you tried with just JEI and no other mods? There may be a bad interaction.

**Comment by mezz** [comment]
@Molalli
Can you paste your client log to https://gist.github.com? Maybe there is information there.
Have you tried with just JEI and no other mods? There may be a bad interaction.
