### ISSUE TITLE
[Bug]: Smithing Tables dont show in 1.20.1

### ISSUE THREAD

**Issue by TheGamingDogYT7** [mezz/JustEnoughItems#3340]
### Steps to Reproduce the Bug

Type something that needs a smithing table to upgrade and click on it, just shows Anvil

### Expected Behavior

Show Smithing Table Recipes

### Actual Behavior

Just shows Anvil recipes

### Mod Pack Version (Optional)

15.2.0.27

### Extra Notes (Optional)

I was using to to test my mod out, and I noticed it didnt show any of the Smithing Table recipes and I checked them and they worked so they should be there

**Comment by ArkyFursblack** [comment]
it doesn't work with my mod too and every recipe that has nothing in smithing template slot (first slot) of smithing table.

**Comment by Jowonny** [comment]
This is still an issue

**Comment by ItzDogo** [comment]
Im not sure I dont use JEI anymore :/

**Comment by Jowonny** [comment]
*I mean it still is 😄 

What do you use now if you don't mind me asking?

**Comment by ItzDogo** [comment]
Oh sorry I read it wrong hahahah. I use JEI and EMI, EMI gets rid of a lot of bugs with JEI but still needs to to work

**Comment by Jowonny** [comment]
Ah okay thank you! ^_^

**Comment by 123ghaksd** [comment]
still an issue

**Comment by ItzDogo** [comment]
Download EMI along with JEI, it fixes alot of issues and it allows the Smithing to work :D

**Comment by mezz** [comment]
Thanks for the report!
This seems to be working fine for me, can you explain how to reproduce the issue in more detail?

![Screenshot 2024-07-18 at 6 47 34 PM](https://github.com/user-attachments/assets/183e3748-bb41-4cf9-ae7a-6d20eee04094)
