### ISSUE TITLE
Error in log [1.20.2]

### ISSUE THREAD

**Issue by moonfather1** [mezz/JustEnoughItems#3341]
### Other

i am in debugger mode in my ide and i opened a crafting table (mine) after joining world.

i have this in my console, in red letters:
[21:30:28] [Render thread/ERROR] [me.je.fo.st.StartEventObserver/]: A Screen is opening but JEI hasn't started yet.
Normally, JEI is started after ClientPlayerNetworkEvent.LoggedInEvent, TagsUpdatedEvent, and RecipesUpdatedEvent.
Something has caused one or more of these events to fail, so JEI is starting very late.

is this ok? item transfer plugin works.

**Comment by mezz** [comment]
Thanks for the report!
JEI will still work, but something is broken elsewhere.
Normally JEI will start earlier in response to the listed events, but in this case something is breaking one or more of the events. You may be able to find more information earlier in your logs.
