### ISSUE TITLE
[Bug]: JEI Config menu in game

### ISSUE THREAD

**Issue by ShadowThunder992** [mezz/JustEnoughItems#3342]
### Steps to Reproduce the Bug

I play Minecraft 1.20.1 for fabric. When I'm in JEI, I get a message to download "Configured", but for version 1.20.1 it doesn't exist. The latest Fabric version released is 1.19.3... Solutions to be able to use the configs in game?

### Expected Behavior

JEI CONFIG MENU 1.20.1 FABRIC

### Actual Behavior

I Can't open the wrench for the config. 

### Extra Notes (Optional)

![2023-10-21_21 41 46](https://github.com/mezz/JustEnoughItems/assets/33591849/96fff44c-110f-41d6-9329-c9ce3ada6f3f)

**Comment by WileyCoyote1** [comment]
I have the same issue, but I am using Forge.

**Comment by kontobaf** [comment]
`https://www.curseforge.com/minecraft/mc-mods/configured-fabric/files/4010582`
Here u can download configured for fabric

**Comment by kontobaf** [comment]
> `https://www.curseforge.com/minecraft/mc-mods/configured-fabric/files/4010582` Here u can download configured for fabric

lol, that's not work

**Comment by ShadowThunder992** [comment]
> I have the same issue, but I am using Forge.

I think you need this mods: Configured for forge.

**Comment by joex92** [comment]
> > I have the same issue, but I am using Forge.
> 
> I think you need this mods: Configured for forge.

what about fabric? is there a mod that add ingame config menu for JEI?

**Comment by mezz** [comment]
Thanks for the report!
You can edit the JEI config files directly, and JEI will update in-game automatically without needing to restart the game.
If there are well-established in-game configs that work for Forge, Fabric, and NeoForged, please let me know.

**Comment by joex92** [comment]
> Thanks for the report! You can edit the JEI config files directly, and JEI will update in-game automatically without needing to restart the game. If there are well-established in-game configs that work for Forge, Fabric, and NeoForged, please let me know.

That works, thanks...
but it's a bit bothersome to open an external program to edit it... also there might be users that could break it by making wrong changes... just saying... for me it's really rare for a mod not having a GUI for configuring it...

**Comment by ShadowThunder992** [comment]
> Thanks for the report! You can edit the JEI config files directly, and JEI will update in-game automatically without needing to restart the game. If there are well-established in-game configs that work for Forge, Fabric, and NeoForged, please let me know.

The only problem is that with configs in txt format, it's difficult to understand what to change and what not to touch. More often than not, if you touch something wrong, the mods ends up having more problems than anything else.
In game it is easier, if you have the opportunity to do it by directly modifying the mods via the settings. Also, I may be stupid, but more often than not, .config files confuse me a lot! lol

**Comment by MistressPlague** [comment]
Still an issue..
1.19.2 Fabric.
I have Configured installed, config does not open visually regardless.

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878
