### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Soughttime** [mezz/JustEnoughItems#3346]
### Steps to Reproduce the Crash

So I made this very unpolished mod pack. I asked all the guys on the Discord on Curseforge what it is. One guy told me to reach out to you guys, the devs. He told me that the issue was relating with JEI, Mekanism, and Crafttweaker. If you figure something out or anything let me know.

### Mod Pack URL (Optional)

https://legacy.curseforge.com/minecraft/modpacks/packing-the-best-mods/files/all

### Mod Pack Version (Optional)

1.0 Alpha

### Extra Notes (Optional)

The game loads up all the files but does not launch the game. Please help fix this. I'm playing on forge 1.20.1. 

### Crash Report

https://gist.github.com/Soughttime/209ff5a5ad098c37f3af82dfa4e09aa7

**Comment by mezz** [comment]
Thanks for the report!
Sorry, the problem here is unclear. Please try reducing the mods you have in the pack until the problem clears up, in order to figure out which one is responsible for the crash.
