### ISSUE TITLE
[Bug]: Search bar Unfocus when using prefix key

### ISSUE THREAD

**Issue by NanoCE** [mezz/JustEnoughItems#3347]
### Steps to Reproduce the Bug

I don't know how to reproduce the bug as the bug is permanently stuck and I have no clue what caused it. It happens every time I launch my game.

### Expected Behavior

When you press shift + 2 or 3, it should create the @ and # symbol respectively inside the JEI search bar.

### Actual Behavior

Whenever I press shift, ctrl, or alt, my focus is removed from the search bar.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/life-in-the-village-3

### Mod Pack Version (Optional)

2.4

### Extra Notes (Optional)

None of the other pack members have this bug and I've asked around in the modpack's tech support chat without luck. I have no further mods installed and at this point, Im not sure where im going wrong.

It should also be noted that this doesn't occur on any other modpack that I have installed, only this one.

### latest.log

https://gist.github.com/NanoCE/bea684c34869f41779ce56aebebe92fb

**Comment by mezz** [comment]
Thanks for the report!
Does this happen when you *only* have JEI installed, with no other mods?
There may be another mod involved that is causing this issue for you.

**Comment by NanoCE** [comment]
Hello Mezz,
    At that time I did confirm it was just happening with JEI. With that said, I no longer would like to pursue this bug report as the issue stopped happening for some reason? I still don't know why this issue occurred in the first place and everything I did at the time attempting to recreate issue didn't work.
    I appreciate the response after all this time, but nothing more can come from this unless I run into the issue again.
