### ISSUE TITLE
[Other]: keybinds on fabric..

### ISSUE THREAD

**Issue by kaxer710** [mezz/JustEnoughItems#3355]
### Other

keybinds aren't in option file on fabric 
i can see the gui but i can't do anything aside from that, which makes this mod completely useless on fabric unless you go f with the jar file

**Comment by mezz** [comment]
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3000

Key bindings for Fabric have been implemented in JEI 
for 1.20.1: `15.18.0.80`+
and 1.21.1: `19.17.0.196`+
