### ISSUE TITLE
[Crash]: vanilla server issue

### ISSUE THREAD

**Issue by caunt** [mezz/JustEnoughItems#3358]
### Steps to Reproduce the Crash

1. Connect through proxy server (velocity) to vanilla lobby
2. Change lobby to another vanilla lobby
3. Open inventory (E)

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-7-to-the-sky

### Mod Pack Version (Optional)

1.2.3

### Extra Notes (Optional)

Probably related to https://github.com/mezz/JustEnoughItems/issues/3018

Problem doesn't happen if I connect to a modded server at first. So after first connection to a modded server, I can disconnect and play through the proxy gracefully even switching between vanilla/modded servers without any issues. But if I connect to vanilla lobby through the Velocity proxy at first, than it will crash at steps described above. 

If there further need to access the lobby server, I can share IP

### Crash Report

https://gist.github.com/caunt/8bceac45af5399319fb762800afa8181

[latest.log](https://github.com/mezz/JustEnoughItems/files/13387761/2023-11-17-1.log)
[debug.log](https://github.com/mezz/JustEnoughItems/files/13387769/debug-1.log)

**Comment by TauPan** [comment]
I see the same issue with a very slightly modded server (but without server-side jei support) but it works if I open a local world and open jei there first.

Does it work for you as well if you enter a local world first?

**Comment by caunt** [comment]
> Does it work for you as well if you enter a local world first?

Yes it also works
