### ISSUE TITLE
Okay mezz, you're driving me nuts.

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#336]
mezz pls
![image](https://cloud.githubusercontent.com/assets/6166773/16478145/bd0fc2da-3e4c-11e6-82d8-e49e2fad4cf3.png)

~~Personally I think it should be the name of the block, to make it easier for compat. Most mods have it as the name of the block anyway, and not the name of the process. Whatever you do, consistancy pls (fuel is fine, but maybe change it to "Furnace Fuel" specifically. or maybe "Solid Fuel" or "Burnable Fuel")~~

Change "crafting table" to just "crafting"

**Comment by CyanideX** [comment]
Wouldn't it make more sense to change **_Crafting Table_** to **_Crafting_**?

Also, what's the big deal?

**Comment by Prospector** [comment]
~~It would make more sense logically, but almost every single JEI support I've ever seen uses the block's name, so for consistancy I'd prefer that.~~

EDIT: Upon further thinking, I figured that it would drive me crazier if they were all block name. Crafting Table just needs to change to Crafting
