### ISSUE TITLE
[Bug]: Vanilla Crafting recipes are missing

### ISSUE THREAD

**Issue by Deblin-Mallick** [mezz/JustEnoughItems#3370]
### Steps to Reproduce the Bug

![image](https://github.com/mezz/JustEnoughItems/assets/68825366/6c13c22a-9bd7-4535-8fe6-fac551a2f050)

### Expected Behavior

All the Vanilla crafting table recipes are missing but you can craft them

### Actual Behavior

When you load into the game in server it's missing all the vanilla crafting recipes

### Mod Pack URL (Optional)

https://www.technicpack.net/modpack/troa-forge-modpack.1979804

**Comment by iceystreeeeet** [comment]
This is being reported on many servers is there an ETA on a fix for this? @mezz are you still supporting this mod?

You have at least 10 topics with the same issue..

**Comment by drwoops** [comment]
indeed, JEI failing to show items or recipes has become a very frequently recurring complaint lately.

**Comment by ActualAsteroid** [comment]
This has been a headache for me as well with a 1.20.1 custom pack. Whenever I update mods JEI refuses to show crafting table recipes.

![Screenshot 2024-01-14 191037](https://github.com/mezz/JustEnoughItems/assets/128436839/82bee7ff-7c3f-4957-815b-10af54cc4ac2)

**Comment by TierraVulture** [comment]
I am having the same issue.

**Comment by mezz** [comment]
Thanks for the report!
Please include client logs, I can take a look to see what the issue may be.
