### ISSUE TITLE
[Bug]: I can't see the JEI overlay

### ISSUE THREAD

**Issue by LoneOwlFromItaly** [mezz/JustEnoughItems#3373]
### Steps to Reproduce the Bug

since i started this modpack i couldn't see JEI overlay, i even tried ctrl + o and it didn't work, i tried changing the specific key but I still couldn't see it

### Expected Behavior

i see JEI overlay

### Actual Behavior

i can't.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/mechanical-mastery

### Mod Pack Version (Optional)

1.5.0

### latest.log

https://gist.github.com/LoneOwlFromItaly/280da4d4879bb5ed1dc8193b3df21392

**Comment by ExonegeS** [comment]
I have the same issue. I play the TerraFirmaGreg modpack 1.20.1 and added this Just Enough Calculations mod. When i just use inventory i can see the overlay, but inside calculator menu i can't. I also tried pressing the hotkeys Ctrl+O but it seems to do nothing
