### ISSUE TITLE
[Crash]: Silent gear crash

### ISSUE THREAD

**Issue by loopel** [mezz/JustEnoughItems#3378]
### Steps to Reproduce the Crash

1. load up the mods I use

2. hover cursor over silent gear blueprint, blueprint package, and blueprint book in any GUI. (crash report says JEI though)

3. crash

wasnt sure how to add my modlist in words so I just put screenshots
![Screenshot_10](https://github.com/mezz/JustEnoughItems/assets/153471071/786fcf4d-2e36-400c-a907-2308aa268867)
![Screenshot_9](https://github.com/mezz/JustEnoughItems/assets/153471071/d9d710bc-a3c6-4876-807f-422220803ac2)
![Screenshot_8](https://github.com/mezz/JustEnoughItems/assets/153471071/afdb2f9f-c972-412a-be72-09f246936036)
![Screenshot_7](https://github.com/mezz/JustEnoughItems/assets/153471071/36c70862-9a24-4ed0-91cc-3e30115b7497)
![Screenshot_6](https://github.com/mezz/JustEnoughItems/assets/153471071/2b0599a6-919e-4bcb-ac41-4a811602a401)
![Screenshot_5](https://github.com/mezz/JustEnoughItems/assets/153471071/99c69f41-2c22-4cfb-8374-bc924431d44f)
![Screenshot_4](https://github.com/mezz/JustEnoughItems/assets/153471071/fee261fc-0e92-4a54-b806-4f2bd77ee59e)
![Screenshot_3](https://github.com/mezz/JustEnoughItems/assets/153471071/1e789dc3-0a1e-4a75-b2db-c4969632d8ff)

### Extra Notes (Optional)

also a lot of my textures like modded spawn eggs, silent gear parts, and gregtech ores textures are all white for some reason, like they have the models but they're just white versions and its kinda weird so if anyone knows how to fix this ill appreciate it.

### Crash Report

https://gist.github.com/loopel/4640a7d311692ec7830170d29f922597

**Comment by mezz** [comment]
Thank for the report!
Sorry there are way too many mods here to confidently make sense of this crash. 
Please take the scientific approach and narrow things down by removing mods until it works.
When you have identified which mods are always involved, then you can make a targeted report to the mod author and get it fixed.
