### ISSUE TITLE
[Crash]: game crash everytime i search ``end`` in the searchbar

### ISSUE THREAD

**Issue by Jnorm27** [mezz/JustEnoughItems#3380]
### Steps to Reproduce the Crash

1. open inventory or crafting table
2. go to the searchbar and type ''End'' 
(i dont know if its only on 1.16.5 but it always crash when i do it)

### Crash Report

https://gist.github.com/Jnorm27/612d940d551d046698a1d7676cfd973f

**Comment by ghost** [comment]
`Failure message: Mod tconstruct requires mantle 1.6.152 or above Currently, mantle is not installed`
