### ISSUE TITLE
[Bug]: Missing random recipes from Create Mod

### ISSUE THREAD

**Issue by Yovez** [mezz/JustEnoughItems#3381]
### Steps to Reproduce the Bug

Load up create and JEI, play for a random amount of time, do your thing, quit then load the game and possible missing recipes. It's completely random what recipes and when it happens, but it does.

### Expected Behavior

I expected to be able to see all the items from create unless configured otherwise.

### Actual Behavior

Random recipes are missing from the Create mod (from what I can tell it's completely random, and it usually just so happens to be things I need right then). It all happens very randomly, like earlier I was playing on my server and was able to make fluid tanks and anything I needed. Now I want to make more fluid tanks and the JEI item is gone, thankfully I know the recipe by heart now though. But now I need to make a mechanical saw from Create, and the item doesn't show in JEI, so I have no idea how to create it without doing a wiki search.

### Mod Pack URL (Optional)

https://legacy.curseforge.com/minecraft/modpacks/solonoah-smp

### Mod Pack Version (Optional)

2.0.2

**Comment by franell0** [comment]
#3381 **I have the same problem**. Sometimes they pop up sometimes not, especially happens with "the factory must grow" addon, it showes like 15 items (not enough)

**Comment by Cyber-Freg** [comment]
Could be other mods using the same tag, and JEI gets confused. Unless its random every time. But that doesn't make any sense why JEI couldn't read it properly.

**Comment by jailbreakloose** [comment]
Im having the exact same issue. Except i am on multiplayer. All of my friends have different recipes missing. For example, I can not see the wrench recipe. But my other friend can.

**Comment by lokirowan4ik** [comment]
same problem

**Comment by drakray** [comment]
Same issue, Neoforge 47.1.84, JEI 15.2.0.27, MANY mods(custom modPack)
I mainly notice when Create's item are missing from the side panel, but sometime it's other mods(page count is not consistent)
Finding the recipe by item usage is still possible though(for example, looking at Brass casing will show MechanicalCrafter, even if MechCraft is not on side panel)

**Comment by lokirowan4ik** [comment]
I just found how to solve the problem, just download EMI mod and don't delete JEI, it will emi interface with jei functionality, and it doesn't bug

**Comment by franell0** [comment]
> I just found how to solve the problem, just download EMI mod and don't delete JEI, it will emi interface with jei functionality, and it doesn't bug

from curseforge EMI page: "all you need to do is install JEI alongside EMI and they will work together to share recipes. JEI will be hidden."

so would the JEI be hidden?

**Comment by mikerooni** [comment]
This is happening with GregTech CEu Modern as well.  
We've been unable to find the issue on our side so far, and I'm afraid this may be a bug with JEI itself.

**Comment by IdrisQe** [comment]
I'm also having this issue in 1.20.1. No idea what's causing it.

Edit: Installing EMI alongside it seems to have fixed this? Not certain.

**Comment by andr9528** [comment]
I have the same issue with a number of recipes not showing on the right when searched for. One of the missing ones being 'Tripwire Hook' from vanilla, another being the 'Entangled Block' from 'Entangled'. Playing Prominence II [Classic] (Minecraft 1.20.1) pack, with a dozen extra mods.

![2024-01-22_12 52 39](https://github.com/mezz/JustEnoughItems/assets/21788044/109ed9ba-2048-4dde-aba8-6251e4e842fa)
![2024-01-22_14 32 55](https://github.com/mezz/JustEnoughItems/assets/21788044/dbaebc20-9470-4f4f-8841-f71f39ff63d8)

**Comment by mezz** [comment]
Thanks for the report!
Please report this bug to Create and link back here. 

It is generally up to each mod to add their recipes to JEI. There may be a special case here where reloading causes a problem for their JEI Plugin. I can help out with the issue if needed, but it is important to start in the right place.

**Comment by TLATER** [comment]
Issue report downstream: https://github.com/Creators-of-Create/Create/issues/5987

Seems like it's most likely create addon mods that break things.
