### ISSUE TITLE
[Crash]: when leaving crafting recipe while inside a block's inventory

### ISSUE THREAD

**Issue by ThibVP** [mezz/JustEnoughItems#3383]
### Steps to Reproduce the Crash

Enter any block's inventory
Check a crafting recipe from JEI
Press escape

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4

### Mod Pack Version (Optional)

1.20.1

### Extra Notes (Optional)

No crash if I do these steps from player inventory

### Crash Report

https://gist.github.com/ThibVP/5bd27305dce70c21a5603cf37e4802ee

**Comment by SQuirel5** [comment]
me too !

**Comment by SQuirel5** [comment]
with better mc

**Comment by mezz** [comment]
Thanks for the report!

Based on the crash log, this seems to be caused by `me.roundaround.inventorymanagement`
Please report to them and link back to here: https://github.com/Roundaround/mc-fabric-inventory-management/issues
