### ISSUE TITLE
[Suggestion]: Pull items to inventory for non Crafting table recipes 

### ISSUE THREAD

**Issue by ffuentesm** [mezz/JustEnoughItems#3386]
### Suggestion

For mods like Botania or Ars, they have non [+] quick craft functions, so it would be very useful to have an option to just pull those items on your inventory when you are looking into your storage interface. 
That way, you can get the items without needing to pick one by one.
![243037600-85fb8974-10af-4514-bafe-3b1eb908064e](https://github.com/mezz/JustEnoughItems/assets/44974827/54d4ba34-9b0b-4e91-95c8-497408bdbb6d)
![243037772-c43f6229-882a-45e2-b38a-4c0d0237b417](https://github.com/mezz/JustEnoughItems/assets/44974827/8d0d628a-3718-482c-8328-8067fb12dc10)

**Comment by mezz** [comment]
Thanks for the suggestion! 
I think this will need to be implemented by the storage system mods for it to work, please report to them and link back here.
