### ISSUE TITLE
[Suggestion]: a Button with switches to see only recipes I can craft.  thx 

### ISSUE THREAD

**Issue by thcc31** [mezz/JustEnoughItems#3387]
### Suggestion

a Button with switches to see only recipes I can craft.  thx

**Comment by qizri** [comment]
Displays all available items, Includes items that cannot currently be synthesized

**Comment by mezz** [comment]
Thanks for the request!
I have added something similar to this, a button to sort craftable recipes first.
https://x.com/mezz_mc/status/1809810314399215729

![image](https://github.com/user-attachments/assets/64a3f6f3-3b7a-4cce-94da-66ed7a17afd9)
