### ISSUE TITLE
When seeing what items come from the ground while holding the alt key caused my game to crash

### ISSUE THREAD

**Issue by DatrixTHLK** [mezz/JustEnoughItems#339]
Thank you for reporting!

When reporting:
- If you use ForeverEnoughItems, please remove it and try again or [report here instead](https://github.com/elix-x/Forever-Enough-Items/issues).  
- Please do not suggest features from NEI. [NotEnoughWidgets will have those features.](https://github.com/TheCBProject/NotEnoughItems/issues/6)
- Try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files), it may have fixed the issue already.
- If you crashed, please paste the crash log to https://gist.github.com/ and link it here.

Minecraft Version used: 1.9.4
Recent Version of JEI: (1.9.4) 3.6.7.216
Forge version: 12.0.17.1987
Crash Log: http://pastebin.com/BLb7ScGW

I'm not exactly sure your mod is the culprit but I was looking at the ground and hitting the alt key. Doing that showed me what seeds/items I could harvest from the ground. While doing so I looked at grass and the game froze up and crashed. I'll have a look at what other mod could have caused that (such as an addon to your mod if your's wasn't the culprit)

**Comment by way2muchnoise** [comment]
`me.superckl.jet` It seems to be an issue with Just Enough Tooltips

**Comment by mezz** [comment]
Thanks for the report!
Yep this is from JustEnoughTooltips, please copy your report to here: https://github.com/superckl/JustEnoughTooltips/issues?q=is%3Aopen+is%3Aissue

**Comment by DatrixTHLK** [comment]
Oh, I completely forgot about this...
