### ISSUE TITLE
[Bug]: 1.16.5 Copy item

### ISSUE THREAD

**Issue by 2929762171** [mezz/JustEnoughItems#3390]
### Steps to Reproduce the Bug

![image](https://github.com/mezz/JustEnoughItems/assets/98941945/69dc7c3c-60e1-4244-9105-4a9fbdeb28ff)
![image](https://github.com/mezz/JustEnoughItems/assets/98941945/bf6be060-6813-471c-a34a-e5188faa379e)
![image](https://github.com/mezz/JustEnoughItems/assets/98941945/4a9df77e-0769-4526-a4e5-189b4ca2e8bb)
![image](https://github.com/mezz/JustEnoughItems/assets/98941945/ea1bb8a7-2fce-492c-8012-7a5933a78995)
![image](https://github.com/mezz/JustEnoughItems/assets/98941945/536a4c4e-84d6-47bf-a1d9-b921849b87b1)

### Expected Behavior

0

### Actual Behavior

1

### Mod Pack Version (Optional)

jei-1.16.5-7.8.0.1009.jar

### Extra Notes (Optional)

Without other mods.
Can be reproduced in single-player/server.

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed by https://github.com/mezz/JustEnoughItems/pull/3306
