### ISSUE TITLE
[Bug]: not showing up

### ISSUE THREAD

**Issue by duckiessss** [mezz/JustEnoughItems#3392]
### Steps to Reproduce the Bug

make a world play for a bit 
download the mod 

### Expected Behavior

it will not show up

### Actual Behavior

it will not show up

### Mod Pack Version (Optional)

1.16.5

### Extra Notes (Optional)

can you fix this?

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
