### ISSUE TITLE
[Bug]: Out of Bounds crashing client

### ISSUE THREAD

**Issue by IamGallito** [mezz/JustEnoughItems#3394]
### Steps to Reproduce the Bug

1 ctrl click to enable cheat mode in JEI
2 select any item to spawn
3 crash

### Expected Behavior

followling steps with out crashing you should be able to spawn in items in creative mode

### Actual Behavior

trying to give yourself items crashes your game

### latest.log

https://gist.github.com/IamGallito/7037d68df7bac841b465f9ff396b368e

**Comment by mezz** [comment]
Thanks for the report!
Can you please try this with only JEI installed, to see if there is another mod causing a conflict here?
