### ISSUE TITLE
[Crash]: Mekanism mod synthesis recipe issue

### ISSUE THREAD

**Issue by onimai-oyama-mahiro** [mezz/JustEnoughItems#3396]
### Steps to Reproduce the Crash

Crash when opening the synthesis recipe of Mekanism's Metallurgical Infusion Machine and then exiting the interface

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/mc-mods/mekanism

### Mod Pack Version (Optional)

10.4.5

### Crash Report

<script src="https://gist.github.com/onimai-oyama-mahiro/2b70902ea2be62a0b063845b4c33a051.js"></script>

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Mekanism and link back here.
