### ISSUE TITLE
 [Crash]: textures.JeiTextureMap [1.12.2]

### ISSUE THREAD

**Issue by Leppan** [mezz/JustEnoughItems#3399]
### Steps to Reproduce the Crash

Hello! I am developing a mod for minecraft 1.12.2 forge 2854

An error occurs when adding jei to dependencies

`Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureMap.initMissingImage()V from class mezz.jei.gui.textures.JeiTextureMap`

This is my modid_at.cfg file:

```#rendering
public net.minecraft.client.renderer.RenderItem func_191965_a(Lnet/minecraft/client/renderer/block/model/IBakedModel;I)V # renderModel
public net.minecraft.client.renderer.RenderItem func_191961_a(Lnet/minecraft/client/renderer/block/model/IBakedModel;Lnet/minecraft/item/ItemStack;)V # renderModel

#TextureMap
protected net.minecraft.client.renderer.texture.TextureMap field_94252_e # mapUploadedSprites
protected net.minecraft.client.renderer.texture.TextureMap field_94258_i # listAnimatedSprites
protected net.minecraft.client.renderer.texture.TextureMap field_94249_f # missingImage
protected net.minecraft.client.renderer.texture.TextureMap field_94254_c # basePath
protected net.minecraft.client.renderer.texture.TextureMap field_110574_e # mapRegisteredSprites
public net.minecraft.client.renderer.texture.TextureMap func_110569_e()V # initMissingImage

#GuiRecipeBook
public net.minecraft.client.gui.recipebook.GuiRecipeBook field_191904_o # width
public net.minecraft.client.gui.recipebook.GuiRecipeBook field_191905_p # height
public net.minecraft.client.gui.recipebook.GuiRecipeBook field_191903_n # xOffset
public net.minecraft.client.gui.recipebook.GuiRecipeBook field_193018_j # recipeTabs

#Ingredient
public net.minecraft.item.crafting.Ingredient field_193371_b # matchingStacks
```
The FMLAT is spelled out correctly as far as I know. The FMLAT is spelled out correctly as far as I know
```
'FMLAT': 'nms_at.cfg',
```
I use this version of jei: implementation fg.deobf("mezz.jei:jei_1.12.2:4.16.1.301")

### Crash Report

https://drive.google.com/file/d/1vh_PBdueX5ys9ss7NTznXnAWjjJftblU/view?usp=sharing

**Comment by Leppan** [comment]
I realize it's the weekend, but I need help.

**Comment by mezz** [comment]
Thanks for the report!
It seems like you want help troubleshooting an issue with ATs, which isn't really what this bug reporting form is good for. 
I am not sure what the exact issue is here, please go to a discord with lots of modders who are around to help, like [NeoForge](https://discord.com/invite/UvedJ9m) and people should be able to help you out a bit more quickly!
