### ISSUE TITLE
Cheat Mode Not Working

### ISSUE THREAD

**Issue by BigFriendlyJakey** [mezz/JustEnoughItems#340]
So I've been dying a lot in my world and I want to cheat what I had back in. But every time I want to use cheat mode (no matter what game mode I'm in, or whether I have cheats enabled or not), the game tells me I don't have permission. :/ Any solutions? Because I've tried a fair few things (new version, old version, adding addons, removing addons, removing other mods, creative mode, new world). 

:)

PS I never crash because of JEI, it just tells me in-game that I don't have permission.

**Comment by mezz** [comment]
The permission is the same as Minecraft, JEI uses the `/give` command.
You will need OP on multiplayer, or cheats enabled on singleplayer.

**Comment by BigFriendlyJakey** [comment]
I've tried that, and it still tells me I don't have permission. Whether it's survival with cheats or just creative, neither solve the problem.

**Comment by mezz** [comment]
Try the `/give` command, it will be exactly the same. You can find more help about permissions for it online.
If it's not the same, maybe you have an addon that breaks JEI?

**Comment by mezz** [comment]
I am reopening this because I want JEI to "just work" and obviously it is not.
`/give` is not really the best way to decide permissions, because this is just like the creative item cheating, so it should just need OP or creative mode.
