### ISSUE TITLE
[Other]: JEI is unsupported on server side, according to Modrinth

### ISSUE THREAD

**Issue by Einhornyordle** [mezz/JustEnoughItems#3401]
### Other

![image](https://github.com/mezz/JustEnoughItems/assets/47315090/689cfb2c-b383-45b8-a54e-465e312598f9)
I assume this is an accident?

**Comment by mezz** [comment]
Thanks for letting me know, I have updated it with the right info now

**Comment by intiitni** [comment]
still marked as unsupported
