### ISSUE TITLE
[Crash]: JEI is crashing my game at startup

### ISSUE THREAD

**Issue by m4slanka** [mezz/JustEnoughItems#3404]
### Steps to Reproduce the Crash

Put JEI 17.0.0.30 fabric, Botany pots, and botany trees into mods folder and run the game
edit: After looking through the crash file i see that "botany pots" mod does interfere with JEI and thats what is the problem
without it, the game starts
![image](https://github.com/mezz/JustEnoughItems/assets/157158361/3b267a47-586c-49b1-99fd-3b496effa8f4)
![image](https://github.com/mezz/JustEnoughItems/assets/157158361/81f7262d-7b5d-4e77-9189-40931c3584b4)

### Crash Report

https://gist.github.com/m4slanka/ca6808cd9a99d6791e3d3890f40069b9#file-crash-2024-01-19_19-32-43-client

**Comment by m4slanka** [comment]
i see now that the botany pots mod does interfere with JEI

**Comment by DemonSamuraiZero** [comment]
I had the same issue and posted about the issue in the botany pots issue page.

I recommend post there so they know it's a problem.

**Comment by m4slanka** [comment]
The botany pots dev repaired it.
