### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AresAmigos** [mezz/JustEnoughItems#3405]
### Steps to Reproduce the Bug

Open Key Bind Menu, in Italian.

### Expected Behavior

Normal key bind menu

### Actual Behavior

Key binding menu with half the text cut off

**Comment by AresAmigos** [comment]
Bug

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately, I do not speak Italian so I cannot fix this myself. 
If you would like to make improvements, please can edit these with shorter names and I can update them:
https://github.com/mezz/JustEnoughItems/blob/99d5d0a8c88e707958c6b420f5d18b6b13ca4fc9/Common/src/main/resources/assets/jei/lang/it_it.json#L43-L86
