### ISSUE TITLE
[Bug]: pink pixels

### ISSUE THREAD

**Issue by Me4eHbN1314** [mezz/JustEnoughItems#3406]
### Steps to Reproduce the Bug

![2024-01-21_15 04 04_edited](https://github.com/mezz/JustEnoughItems/assets/157294770/06821426-0d7d-48ed-b32b-c82efcaaa202)

### Expected Behavior

pls help 

### Actual Behavior

i have this pink pixels on arrows that give me discomfort how to fix it?

**Comment by mezz** [comment]
Thanks for the report!
Which version and modloader are you using?

**Comment by AxolotlAccount** [comment]
Same issue happens to me too.
Expected Behavior: Normal button.
Actual Behovior: Button has an abnormal pink line.
Version: 1.20.1
Modloader: Forge 47.2.20
latest.log: https://gist.github.com/AxolotlAccount/86a4d8da35b068c73e602f8c78a2a5f5
Image:
![javaw](https://github.com/mezz/JustEnoughItems/assets/17953179/418fe1ea-d491-47b2-aee1-94b242e10c5f)

**Comment by Me4eHbN1314** [comment]
> Thanks for the report! Which version and modloader are you using?

im playing on 1.18.2 modloader forge40.2.17.
![image](https://github.com/mezz/JustEnoughItems/assets/157294770/da9be255-4afe-4619-9576-5da53aaf83f7)
![image](https://github.com/mezz/JustEnoughItems/assets/157294770/278acf9b-b1f7-4980-b4e2-0dd9a5462b48)
![image](https://github.com/mezz/JustEnoughItems/assets/157294770/5749fbae-f490-4fea-b074-dc9e919b6bb1)
![image](https://github.com/mezz/JustEnoughItems/assets/157294770/348013af-ad40-4ba9-a951-89343ec3fb3f)
![image](https://github.com/mezz/JustEnoughItems/assets/157294770/963d4715-1707-47d6-8958-0acc1aa473ae)
![image](https://github.com/mezz/JustEnoughItems/assets/157294770/f91d3308-f19d-441b-b88b-0406addb6cd8)
![image](https://github.com/mezz/JustEnoughItems/assets/157294770/385f723b-5343-4810-8363-eb1bd4a046cc)
this is what mods i use

**Comment by mezz** [comment]
Can you please try removing all other mods and let me know if this happens with only JEI installed?

**Comment by AxolotlAccount** [comment]
This issue does not happen with only JEI installed.

**Comment by Me4eHbN1314** [comment]
> This issue does not happen with only JEI installed.

yes i know but i dont know why this happend
:(

**Comment by Me4eHbN1314** [comment]
> This issue does not happen with only JEI installed.

same

**Comment by PoptartKing99** [comment]
The mod that causes this is Modern Fix and you can fix the issue by disabling this setting.
![Screenshot 2024-04-02 125210](https://github.com/mezz/JustEnoughItems/assets/38510287/b174e51a-be42-4ee7-bcb9-20e9bf18e122)

**Comment by AxolotlAccount** [comment]
Disabling that setting from Modern Fix fixed the issue, thanks!
