### ISSUE TITLE
[Bug]: Missing plus button

### ISSUE THREAD

**Issue by thalio08** [mezz/JustEnoughItems#3409]
### Steps to Reproduce the Bug

I am missing plus button that moves items to a crafting grid. I am using JEI with having crafting table open. I just installed JEI on newest fabric version with a few other simple mods like appleskin or clumps. 

### Expected Behavior

Having a plus button

### Actual Behavior

Missign plus button
![obraz_2024-01-24_175242301](https://github.com/mezz/JustEnoughItems/assets/89686994/c427872c-5895-45dc-8a1b-d1ee6705d357)

### latest.log

https://gist.github.com/thalio08/50f9a9e55c7c3dc924d5c54a7b8c99d6

**Comment by mezz** [comment]
Thanks for the report!
Please try removing other mods to see if any are causing this conflict.

**Comment by Fuzss** [comment]
having this issue as well on 17.2.0.41 for mc 1.20.4. tested both Fabric and NeoForge. no other mods installed

**Comment by mezz** [comment]
![Screenshot 2024-01-28 at 10 56 21 AM](https://github.com/mezz/JustEnoughItems/assets/916092/e5015af4-d7cd-43f4-a402-ccb373fcf45c)
I was able to confirm this bug. It looks like a rendering problem, the button is invisible.
