### ISSUE TITLE
[Bug]: Search feature on Fabric version  jei-1.20.4-fabric-17.1.0.39.jar

### ISSUE THREAD

**Issue by mindblaster0076** [mezz/JustEnoughItems#3411]
### Steps to Reproduce the Bug

Go into your inventory, click search box, does not let you type.

### Expected Behavior

You should be able to type and search in the search box, but you cannot.

### Actual Behavior

Doesn't let you type.

**Comment by valve-developer** [comment]
this is because of optifabric/optifine. Pasting in text does work.

**Comment by mezz** [comment]
Thanks for the report!
It looks like optifabric has this issue open here: 
* https://github.com/Chocohead/OptiFabric/issues/1312
