### ISSUE TITLE
[Bug]: Bookmark and Dark Mode button overlaps

### ISSUE THREAD

**Issue by LegendaryTicket9** [mezz/JustEnoughItems#3414]
### Steps to Reproduce the Bug

1. Have the JEI (Just Enough Items) mod and open Minecraft
2. Set the GUI scale to 3 on the sodium video settings
3. Open your inventory
4. See the Bookmark and Dark Mode button overlaps each other
![jei overlap](https://github.com/mezz/JustEnoughItems/assets/157869221/0af6ca78-9156-4b87-9203-57b55e11737b)
However, this overlap happens on my display and does not happen on GUI scale of Auto, 1, 2, and 4.

### Expected Behavior

The Bookmark and Dark Mode button should not overlap on the GUI scale of 3 of my display.

### Actual Behavior

The Bookmark and Dark Mode button overlaps on the GUI scale of 3 of my display.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

### Mod Pack Version (Optional)

0.2.39 Release

### latest.log

https://gist.github.com/LegendaryTicket9/bf9e0718cbfec3542e5c0588e10805f1

**Comment by mezz** [comment]
Thanks for the report!
Dark Mode is not added by JEI, it is a button from another mod. 
Please find the mod responsible for creating the button and open a bug with them, and link back here so I can help out if needed.

**Comment by LegendaryTicket9** [comment]
The "Dark Mode" button was from the **Dark Mode Everywhere** mod:
https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere

**Comment by mezz** [comment]
It looks like this was reported and fixed here: https://github.com/Buuz135/DarkModeEverywhere/issues/25
