### ISSUE TITLE
[Crash]: Launching infinity evolved reloaded crashing due to jei.

### ISSUE THREAD

**Issue by Someone9219231** [mezz/JustEnoughItems#3416]
### Steps to Reproduce the Crash

So you just launch it and in phase 6 it will crash on jei loading.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/infinityevolved-reloaded

### Mod Pack Version (Optional)

1.12.2

### Extra Notes (Optional)

I had already loaded it multiple times and re installed it on another pc and reinstalling jei itself but seemingly nothing will fix it.
(Im unsure of incompatible mods with jei but its in its most recent form and im unsure if any of the mods in the pack are incompadible.)

### Crash Report

https://gist.github.com/Someone9219231/fa8eb7fbecbbe1a94a1e84a323d0181c

**Comment by mezz** [comment]
Thanks for the report!
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```
You have run out of memory. Pleas allocate more memory to java using your launcher's settings.
