### ISSUE TITLE
[Crash]: "Object.getClass()" because "plugin" is null

### ISSUE THREAD

**Issue by Malganis1** [mezz/JustEnoughItems#3418]
### Steps to Reproduce the Crash

When trying to view the recipe of any item on the server - the client crashes. However, in the single-player game everything is fine. Although on the server and in the client are the same mods.

I tried using REI and everything works fine, but I want to use JEI.

### Mod Pack URL (Optional)

https://mega.nz/file/RABG0ZRD#OLk6TH_WgFK8LeDPs28Ak6hpDQ4Uu-1EyUO6lOnpaX8

### Crash Report

https://gist.github.com/Malganis1/e79864a264bf9be957229a9424bbb93c

**Comment by mezz** [comment]
Thanks for the report!
I have released a new version, [jei-1.20.1-forge-15.3.0.1.jar](https://legacy.curseforge.com/minecraft/mc-mods/jei/files/5074448) which may help with this problem.
Please try it out and let me know if you still get the crash.

The fix in the code is here: https://github.com/mezz/JustEnoughItems/commit/e8750517fb29439e1307ae1a04fce4c9409641ad

**Comment by Malganis1** [comment]
Thanks, everything works now!
