### ISSUE TITLE
[Crash]: Crash with Forge JEI in an environment with Trinkets installed via the Connector mod

### ISSUE THREAD

**Issue by thedeerirty** [mezz/JustEnoughItems#3419]
### Steps to Reproduce the Crash

On 1.20.1, using forge JEI and Trinkets via the Connector. attempting to click on an item in JEI (whether it is to cheat it in, or view the recipe, it does not matter) while you are in your creative inventory causes a hard crash. Being in another creative tab does not seem to cause this crash, nor cheating in/viewing a recipe in survival.

### Extra Notes (Optional)

Not sure if this is compatibility you guys want to deal with, but I figure I'd bring it up anyway, just in-case. I'm running more than just the two mods, and I haven't tried to just see if it causes it by itself yet. Could very well be something along those lines.

### Crash Report

https://gist.github.com/thedeerirty/a7104d5586b5b9b77738b2aa00cf49ee

**Comment by Xplodin** [comment]
Also getting this exact crash whenever I cheat mode in any item from JEI. With connector mod and trinkets also installed
