### ISSUE TITLE
Game crashes after looking up item uses [1.10]

### ISSUE THREAD

**Issue by TheMprs** [mezz/JustEnoughItems#342]
i looked up the uses for an iron ingot and my game crashed..
here's the crash log, hope you can help me, thanks in advance.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10-1.2.1.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/4/16 8:41 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
    at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1899)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1624)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1334)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
    at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1899)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1624)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Mprs'/106, l='MpServer', x=-74.50, y=81.00, z=875.50]]
    Chunk stats: MultiplayerChunkCache: 572, 572
    Level seed: 0
    Level generator: ID 04 - customized, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-144,64,256), Chunk: (at 0,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 26370 game time, 48302 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 93 total; [EntitySheep['Sheep'/256, l='MpServer', x=-24.97, y=111.00, z=877.04], EntitySkeleton['Skeleton'/265, l='MpServer', x=-43.50, y=25.00, z=896.50], EntityItem['item.tile.rail'/266, l='MpServer', x=-55.58, y=25.00, z=914.28], EntityItem['item.tile.rail'/267, l='MpServer', x=-57.07, y=25.00, z=912.13], EntityItem['item.tile.torch'/395, l='MpServer', x=-50.42, y=19.00, z=933.94], EntitySpider['Spider'/268, l='MpServer', x=-49.50, y=18.00, z=916.50], EntitySkeleton['Skeleton'/396, l='MpServer', x=-49.50, y=38.00, z=939.50], EntitySheep['Sheep'/269, l='MpServer', x=-33.50, y=108.00, z=864.50], EntityZombie['Zombie'/397, l='MpServer', x=-51.53, y=51.00, z=935.20], EntitySheep['Sheep'/270, l='MpServer', x=-32.55, y=111.00, z=869.55], EntityCreeper['Creeper'/398, l='MpServer', x=-60.45, y=51.00, z=939.63], EntityItem['item.tile.rail'/399, l='MpServer', x=-20.06, y=18.00, z=910.75], EntityItem['item.tile.rail'/400, l='MpServer', x=-17.32, y=17.00, z=909.76], EntitySpider['Spider'/401, l='MpServer', x=-29.47, y=25.00, z=911.92], EntityZombie['Zombie'/402, l='MpServer', x=-30.64, y=25.00, z=911.75], EntitySkeleton['Skeleton'/403, l='MpServer', x=-39.50, y=27.00, z=926.50], EntityCow['Cow'/275, l='MpServer', x=-107.44, y=82.00, z=939.81], EntityCow['Cow'/276, l='MpServer', x=-109.61, y=80.00, z=946.90], EntityBat['Bat'/404, l='MpServer', x=2.32, y=29.59, z=878.51], EntityZombie['Zombie'/277, l='MpServer', x=-74.45, y=23.00, z=925.20], EntitySkeleton['Skeleton'/405, l='MpServer', x=-6.50, y=44.00, z=884.50], EntityBat['Bat'/278, l='MpServer', x=-59.93, y=14.89, z=912.50], EntitySkeleton['Skeleton'/406, l='MpServer', x=-3.51, y=34.00, z=893.28], EntityPlayerSP['Mprs'/106, l='MpServer', x=-74.50, y=81.00, z=875.50], EntityCreeper['Creeper'/279, l='MpServer', x=-41.50, y=14.00, z=880.50], EntitySkeleton['Skeleton'/280, l='MpServer', x=-41.50, y=19.00, z=893.50], EntityZombie['Zombie'/408, l='MpServer', x=-0.50, y=19.00, z=939.50], EntityZombie['Zombie'/281, l='MpServer', x=-37.50, y=27.00, z=892.50], EntityBat['Bat'/409, l='MpServer', x=-11.12, y=17.08, z=938.60], EntityZombie['Zombie'/282, l='MpServer', x=-42.78, y=69.00, z=887.48], EntitySkeleton['Skeleton'/410, l='MpServer', x=-5.50, y=28.00, z=931.50], EntityCreeper['Creeper'/283, l='MpServer', x=-58.50, y=20.00, z=899.50], EntitySkeleton['Skeleton'/411, l='MpServer', x=-17.50, y=19.00, z=951.50], EntityBat['Bat'/284, l='MpServer', x=-45.01, y=18.00, z=901.73], EntityCreeper['Creeper'/412, l='MpServer', x=-22.54, y=17.00, z=942.81], EntityBat['Bat'/414, l='MpServer', x=-18.55, y=30.64, z=953.62], EntitySkeleton['Skeleton'/417, l='MpServer', x=-17.50, y=43.00, z=955.50], EntitySheep['Sheep'/162, l='MpServer', x=-152.52, y=64.00, z=845.77], EntitySkeleton['Skeleton'/291, l='MpServer', x=-151.73, y=38.00, z=925.50], EntityCow['Cow'/167, l='MpServer', x=-131.84, y=66.00, z=820.71], EntityCow['Cow'/296, l='MpServer', x=-100.37, y=64.00, z=844.55], EntityCow['Cow'/297, l='MpServer', x=-99.49, y=67.00, z=848.20], EntityCow['Cow'/176, l='MpServer', x=-129.18, y=71.00, z=859.41], EntityCow['Cow'/177, l='MpServer', x=-116.23, y=65.00, z=839.97], EntityItem['item.tile.torch'/434, l='MpServer', x=-10.69, y=22.00, z=927.28], EntityCreeper['Creeper'/435, l='MpServer', x=-9.50, y=38.00, z=913.50], EntityItem['item.tile.rail'/436, l='MpServer', x=-17.47, y=22.00, z=928.62], EntityCreeper['Creeper'/310, l='MpServer', x=-131.20, y=29.00, z=899.50], EntityBat['Bat'/438, l='MpServer', x=-26.25, y=28.10, z=933.75], EntitySpider['Spider'/311, l='MpServer', x=-46.50, y=20.00, z=823.50], EntityCow['Cow'/183, l='MpServer', x=-135.50, y=63.00, z=832.50], EntityCreeper['Creeper'/439, l='MpServer', x=-23.50, y=17.00, z=941.50], EntityCreeper['Creeper'/312, l='MpServer', x=-32.50, y=17.00, z=831.50], EntityCow['Cow'/184, l='MpServer', x=-138.73, y=62.13, z=833.13], EntityZombie['Zombie'/440, l='MpServer', x=-28.50, y=26.00, z=933.50], EntityCow['Cow'/313, l='MpServer', x=-40.55, y=67.00, z=817.35], EntityCow['Cow'/314, l='MpServer', x=-41.50, y=70.00, z=830.89], EntityMinecartChest['Minecart with Chest'/315, l='MpServer', x=-49.50, y=12.06, z=844.50], EntityZombie['Zombie'/316, l='MpServer', x=-31.09, y=31.00, z=805.29], EntityZombie['Zombie'/317, l='MpServer', x=-104.50, y=38.00, z=903.50], EntityCreeper['Creeper'/318, l='MpServer', x=-112.50, y=27.00, z=914.50], EntityBat['Bat'/319, l='MpServer', x=-112.72, y=27.37, z=909.28], EntityCreeper['Creeper'/320, l='MpServer', x=-133.50, y=42.00, z=906.50], EntityCow['Cow'/321, l='MpServer', x=-48.04, y=72.00, z=820.28], EntityCreeper['Creeper'/322, l='MpServer', x=-25.50, y=31.00, z=797.50], EntitySkeleton['Skeleton'/323, l='MpServer', x=-22.50, y=43.00, z=796.50], EntityZombie['Zombie'/324, l='MpServer', x=-26.26, y=42.00, z=801.48], EntitySkeleton['Skeleton'/327, l='MpServer', x=-36.23, y=59.00, z=801.49], EntityCow['Cow'/328, l='MpServer', x=-40.50, y=68.00, z=815.50], EntityBat['Bat'/329, l='MpServer', x=-146.12, y=47.69, z=938.73], EntityMinecartChest['Minecart with Chest'/203, l='MpServer', x=-152.51, y=29.06, z=802.50], EntitySkeleton['Skeleton'/342, l='MpServer', x=3.75, y=22.00, z=929.50], EntityZombie['Zombie'/343, l='MpServer', x=-13.80, y=17.00, z=952.51], EntitySkeleton['Skeleton'/227, l='MpServer', x=-45.20, y=71.12, z=879.49], EntityZombie['Zombie'/228, l='MpServer', x=-79.50, y=14.00, z=890.50], EntityMinecartChest['Minecart with Chest'/229, l='MpServer', x=-27.50, y=12.06, z=838.50], EntitySkeleton['Skeleton'/230, l='MpServer', x=-39.30, y=16.00, z=848.70], EntityBat['Bat'/231, l='MpServer', x=-38.30, y=18.05, z=853.38], EntityZombie['Zombie'/232, l='MpServer', x=-32.49, y=16.00, z=859.24], EntitySheep['Sheep'/233, l='MpServer', x=-40.29, y=107.00, z=859.31], EntityCow['Cow'/234, l='MpServer', x=-110.73, y=80.00, z=938.47], EntityZombie['Zombie'/235, l='MpServer', x=-53.56, y=71.00, z=882.22], EntitySkeleton['Skeleton'/236, l='MpServer', x=-67.50, y=50.00, z=907.50], EntitySpider['Spider'/237, l='MpServer', x=-37.50, y=12.00, z=835.50], EntityBat['Bat'/238, l='MpServer', x=-29.84, y=13.96, z=816.48], EntityItem['item.tile.rail'/377, l='MpServer', x=-16.90, y=19.00, z=927.64], EntityMinecartChest['Minecart with Chest'/378, l='MpServer', x=-34.50, y=22.06, z=934.50], EntityItem['item.tile.torch'/379, l='MpServer', x=-33.75, y=22.00, z=936.22], EntityCow['Cow'/251, l='MpServer', x=-125.55, y=67.00, z=943.45], EntitySheep['Sheep'/252, l='MpServer', x=-31.53, y=111.00, z=868.79], EntitySheep['Sheep'/253, l='MpServer', x=-16.73, y=108.00, z=873.46], EntitySheep['Sheep'/254, l='MpServer', x=-17.78, y=109.00, z=873.65], EntitySheep['Sheep'/255, l='MpServer', x=-23.19, y=110.00, z=874.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:491)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 464596672 bytes (443 MB) / 1928331264 bytes (1839 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.0.2000 Optifine OptiFine_1.10_HD_U_C1 26 mods loaded, 26 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10-12.18.0.2000-1.10.0.jar) 
    UCHIJAAAA   Forge{12.18.0.2000} [Minecraft Forge](forge-1.10-12.18.0.2000-1.10.0.jar) 
    UCHIJAAAA   bookshelf{1.3.0.280} [Bookshelf](Bookshelf-1.10-1.3.0.280.jar) 
    UCHIJAAAA   Chameleon{1.9.4-2.1.5} [Chameleon](Chameleon-1.9.4-2.1.5.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.29.jar) 
    UCHIJAAAA   chiselsandbits{11.4} [Chisels & Bits](chiselsandbits-11.4.jar) 
    UCHIJAAAA   cxlibrary{1.2.1} [CXLibrary](cxlibrary-1.10-1.2.1.jar) 
    UCHIJAAAA   fastleafdecay{v10} [Fast Leaf Decay](FastLeafDecay-v10.jar) 
    UCHIJAAAA   Harvest{1.9.4-1.0.1-8} [Harvest](Harvest-1.9.4-1.0.1-8.jar) 
    UCHIJAAAA   hopperducts{1.4.7} [Hopper Ducts](hopperducts-mc1.9.4-1.4.7.jar) 
    UCHIJAAAA   inventorytweaks{1.61-dev-49-c5b6395} [Inventory Tweaks](InventoryTweaks-1.61-dev-49.jar) 
    UCHIJAAAA   IronChest{7.0.5.793} [Iron Chest](ironchest-1.10-7.0.5.793.jar) 
    UCHIJAAAA   itemscroller{0.5.1} [Item Scroller](itemscroller-1.10.2-0.5.1.jar) 
    UCHIJAAAA   JEI{3.7.1.219} [Just Enough Items](jei_1.10-3.7.1.219.jar) 
    UCHIJAAAA   mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UCHIJAAAA   MoreFurnaces{1.8.1} [More Furnaces](MoreFurnaces-1.10-1.8.1.jar) 
    UCHIJAAAA   moreoverlays{1.4} [MoreOverlays](moreoverlays-1.4-mc1.9.4.jar) 
    UCHIJAAAA   StorageDrawers{1.9.4-3.1.11} [Storage Drawers](StorageDrawers-1.9.4-3.1.11.jar) 
    UCHIJAAAA   tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UCHIJAAAA   VeinMiner{0.33.1_1.9-da0f6cb} [Vein Miner](VeinMiner-0.33.1-1.9r554+da0f6cb.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.33.1_1.9-da0f6cb} [Mod Support](VeinMiner-0.33.1-1.9r554+da0f6cb.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
    UCHIJAAAA   ICSE{1.1.0.0} [I Can See Everything](Wawla-1.10-2.3.0.193.jar) 
    UCHIJAAAA   wawla{2.3.0.193} [What Are We Looking At](Wawla-1.10-2.3.0.193.jar) 
    Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10-1.2.1.jar)
  cubex2.cxlibrary.CoreModTransformer
FMLPlugin (InventoryTweaks-1.61-dev-49.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 365.19' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
Launched Version: forge-12.18.0.2000
LWJGL: 2.9.4
OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Sky Resource Pack.zip (incompatible), Faithful 1.10.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
OptiFine Version: OptiFine_1.10_HD_U_C1
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 0
Multitexture: true
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 365.19
OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by mezz** [comment]
Thanks for the report!
Looks like another mod has broken their item rendering, this is not actually a JEI issue.
Please try removing mods to see which is causing the issue, and report to them.

**Comment by TheMprs** [comment]
hi, removed a bunch of mods and discovered it to be tinkers' i think the display of the crafting station at the top is messing it up. is it a bug with jei or tinkers' ?

**Comment by mezz** [comment]
I believe this is not a JEI bug.

**Comment by KnightMiner** [comment]
Tinkers Construct is not doing anything different than what JEI uses for the vanilla crafting table and it does not give me that issue on my side, plus I don't see our model loader anywhere in the stacktrace.

I would personally guess Optifine's sharers are messing with Chisel rendering, as that is a known issue from optifine disabling the Forge rendering system which chisel uses.

**Comment by mezz** [comment]
Oh, I missed that you have Optifine. That is almost certainly the cause: bad interaction between a mod and Optifine. Chisels and Bits had this issue up until recently, and Algo had to do some fixes for it.
