### ISSUE TITLE
[Bug]: Tooltip error, see log

### ISSUE THREAD

**Issue by JLSkyzer** [mezz/JustEnoughItems#3420]
### Steps to Reproduce the Bug

Launch minecraft with my modded pack
Try to see item info on JEI list

### Expected Behavior

See the item name, description, etc..

### Actual Behavior

Tooltip Error, see log

### latest.log

https://gist.github.com/JLSkyzer/e472558313d036e4384af9a0e1243d2e

**Comment by mezz** [comment]
Thanks for the report!
There is some extra info in the log here:
```
[Render thread/ERROR] [mezz.jei.common.util.SafeIngredientUtil/]: Caught an error rendering an Ingredient's tooltip:

-- Ingredient --
Details:
	Name: Passenger Information Display System
	Mod's Name: Minecraft Transit Railway
	Registry Name: mtr:pids_1
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 pids_1
	Unique Id for JEI (for JEI Blacklist): mtr:pids_1
	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
	Error Info gathered from JEI: 1 pids_1 mtr:pids_1
```

Please report this to the `Minecraft Transit Railway` mod and link back to this issue.

**Comment by QuaxzyL** [comment]
i fixed that deleting Just Enough Resources (JER) if you still want that mod u can try change mod version.

**Comment by JLSkyzer** [comment]
> i fixed that deleting Just Enough Resources (JER) if you still want that mod u can try change mod version.

I think I will delete Minecraft Transit Railway because he stop 1.20.1 development.

**Comment by EduardoToni** [comment]
> Thanks for the report! There is some extra info in the log here:
> 
> ```
> [Render thread/ERROR] [mezz.jei.common.util.SafeIngredientUtil/]: Caught an error rendering an Ingredient's tooltip:
> 
> -- Ingredient --
> Details:
> 	Name: Passenger Information Display System
> 	Mod's Name: Minecraft Transit Railway
> 	Registry Name: mtr:pids_1
> 	Class Name: class net.minecraft.world.item.ItemStack
> 	toString Name: 1 pids_1
> 	Unique Id for JEI (for JEI Blacklist): mtr:pids_1
> 	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
> 	Error Info gathered from JEI: 1 pids_1 mtr:pids_1
> ```
> 
> Please report this to the `Minecraft Transit Railway` mod and link back to this issue.

Just want to chime in on this, in the latest version, it's happening with every item for me
I forgot to save the log but it was essentialy this but the mod was just "Minecraft" and the item was an Oak Log

**Comment by JLSkyzer** [comment]
> > Thanks for the report! There is some extra info in the log here:
> > ```
> > [Render thread/ERROR] [mezz.jei.common.util.SafeIngredientUtil/]: Caught an error rendering an Ingredient's tooltip:
> > 
> > -- Ingredient --
> > Details:
> > 	Name: Passenger Information Display System
> > 	Mod's Name: Minecraft Transit Railway
> > 	Registry Name: mtr:pids_1
> > 	Class Name: class net.minecraft.world.item.ItemStack
> > 	toString Name: 1 pids_1
> > 	Unique Id for JEI (for JEI Blacklist): mtr:pids_1
> > 	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
> > 	Error Info gathered from JEI: 1 pids_1 mtr:pids_1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please report this to the `Minecraft Transit Railway` mod and link back to this issue.
> 
> Just want to chime in on this, in the latest version, it's happening with every item for me I forgot to save the log but it was essentialy this but the mod was just "Minecraft" and the item was an Oak Log

An anomaly in the code ?

**Comment by mezz** [comment]
It sounds like your bug does not exactly match this one, please open a new issue with the full logs so that it can be investigated separately.
