### ISSUE TITLE
[Crash]: game crashes with create mod when loading an item/block on the page section

### ISSUE THREAD

**Issue by commanderdarkkirby** [mezz/JustEnoughItems#3421]
### Steps to Reproduce the Crash

install create mod and keep changing pages until the game crashes.
[latest.log](https://github.com/mezz/JustEnoughItems/files/14158323/latest.log)

### Crash Report

[latest.log](https://github.com/mezz/JustEnoughItems/files/14158323/latest.log)

**Comment by mezz** [comment]
Thanks for the report!
Please update to jei-1.20.1-forge version `15.3.0.1`, it should help with this issue.
Let me know how it goes.

**Comment by commanderdarkkirby** [comment]
well i updated to the new version but now there is a new problem. while the game doesn't crash anymore, all the GUI's of blocks and items turn into the word "ERROR" 
[latest.log](https://github.com/mezz/JustEnoughItems/files/14166128/latest.log)

**Comment by mezz** [comment]
Thanks for the update!
It looks like there is a major problem with rendering this particular item:
```
[05Feb2024 06:14:55.237] [Render thread/ERROR] [mezz.jei.common.util.SafeIngredientUtil/]: Caught an error rendering an Ingredient:

-- Ingredient --
Details:
	Name: Wand Of Symmetry
	Mod's Name: Create
	Registry Name: create:wand_of_symmetry
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 wand_of_symmetry
	Unique Id for JEI (for JEI Blacklist): create:wand_of_symmetry
	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
	Error Info gathered from JEI: 1 wand_of_symmetry create:wand_of_symmetry
```

I expect that rendering this item will crash even in the creative menu.
Please report this issue to Create and link back here.
