### ISSUE TITLE
[Bug]: Issues with the JEI config file

### ISSUE THREAD

**Issue by lSherozl** [mezz/JustEnoughItems#3422]
### Steps to Reproduce the Bug

[advanced]
	# Description: Debug mode enabled
	# Valid Values: [true, false]
	# Default Value: false
	DebugMode = false

	# Description: Display search bar in the center
	# Valid Values: [true, false]
	# Default Value: false
	CenterSearch = false

	# Description: Set low-memory mode (makes search very slow, but uses less RAM)
	# Valid Values: [true, false]
	# Default Value: false
	LowMemorySlowSearchEnabled = false

	# Description: Enable cheating items into the hotbar by using the shift+number keys.
	# Valid Values: [true, false]
	# Default Value: false
	CheatToHotbarUsingHotkeysEnabled = false

	# Description: How items should be handed to you
	# Valid Values: [INVENTORY, MOUSE_PICKUP]
	# Default Value: MOUSE_PICKUP
	GiveMode = MOUSE_PICKUP

	# Description: Max. recipe gui height
	# Valid Values: Any integer greater than or equal to 175
	# Default Value: 350
	RecipeGuiHeight = 350

[colors]
	# Description: Color values to search for
	# Valid Values: A comma-separated list containing values of:
	# Any color name and an RGB hex color, separated by a ':'
	# Default Value: White:EEEEEE, LightBlue:7492CC, Cyan:00EEEE, Blue:2222DD, LapisBlue:25418B, Teal:008080, Yellow:CACB58, GoldenYellow:EED700, Orange:D97634, Pink:D1899D, HotPink:FC0FC0, Magenta:B24BBB, Purple:813EB9, EvilPurple:2E1649, Lavender:B57EDC, Indigo:480082, Sand:DBD3A0, Tan:BB9B63, LightBrown:A0522D, Brown:634B33, DarkBrown:3A2D13, LimeGreen:43B239, SlimeGreen:83CB73, Green:008000, DarkGreen:224D22, GrassGreen:548049, Red:963430, BrickRed:B0604B, NetherBrick:2A1516, Redstone:CE3E36, Black:181515, CharcoalGray:464646, IronGray:646464, Gray:808080, Silver:C0C0C0
	SearchColors = White:EEEEEE, LightBlue:7492CC, Cyan:00EEEE, Blue:2222DD, LapisBlue:25418B, Teal:008080, Yellow:CACB58, GoldenYellow:EED700, Orange:D97634, Pink:D1899D, HotPink:FC0FC0, Magenta:B24BBB, Purple:813EB9, EvilPurple:2E1649, Lavender:B57EDC, Indigo:480082, Sand:DBD3A0, Tan:BB9B63, LightBrown:A0522D, Brown:634B33, DarkBrown:3A2D13, LimeGreen:43B239, SlimeGreen:83CB73, Green:008000, DarkGreen:224D22, GrassGreen:548049, Red:963430, BrickRed:B0604B, NetherBrick:2A1516, Redstone:CE3E36, Black:181515, CharcoalGray:464646, IronGray:646464, Gray:808080, Silver:C0C0C0

[sorting]
	# Description: Sorting order for the ingredient list
	# Valid Values: A comma-separated list containing values of:
	# [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, ARMOR, MAX_DURABILITY]
	# Default Value: MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU
	IngredientSortStages = MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU

[search]
	# Description: Search mode for Mod Names (prefix: @)
	# Valid Values: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Default Value: REQUIRE_PREFIX
	ModNameSearchMode = REQUIRE_PREFIX

	# Description: Search mode for Tooltips (prefix: #)
	# Valid Values: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Default Value: ENABLED
	TooltipSearchMode = ENABLED

	# Description: Search mode for Tag Names (prefix: $)
	# Valid Values: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Default Value: REQUIRE_PREFIX
	TagSearchMode = REQUIRE_PREFIX

	# Description: Search mode for Creative Tab Names (prefix: %)
	# Valid Values: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Default Value: DISABLED
	CreativeTabSearchMode = DISABLED

	# Description: Search mode for Colors (prefix: ^)
	# Valid Values: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Default Value: DISABLED
	ColorSearchMode = DISABLED

	# Description: Search mode for resources locations (prefix: &)
	# Valid Values: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Default Value: DISABLED
	ResourceLocationSearchMode = DISABLED

	# Description: Search advanced tooltips (visible with F3+H)
	# Valid Values: [true, false]
	# Default Value: false
	SearchAdvancedTooltips = false

[modname]
	# Description: Formatting for mod name tooltip
	# Valid Values: A chat formatting string.
	# Use these formatting colors:
	# black dark_blue dark_green dark_aqua dark_red dark_purple gold gray dark_gray blue green aqua red light_purple yellow white
	# With these formatting options:
	# obfuscated bold strikethrough underline italic
	# Default Value: blue italic
	ModNameFormat = blue italic

[IngredientList]
	# Description: Max number of rows shown
	# Valid Values: An integer in the range [1, 100] (inclusive)
	# Default Value: 16
	MaxRows = 25

	# Description: Max number of columns shown
	# Valid Values: An integer in the range [4, 100] (inclusive)
	# Default Value: 9
	MaxColumns = 9

	# Description: Horizontal alignment of the ingredient grid inside the available area
	# Valid Values: [LEFT, CENTER, RIGHT]
	# Default Value: RIGHT
	HorizontalAlignment = RIGHT

	# Description: Vertical alignment of the ingredient grid inside the available area
	# Valid Values: [TOP, CENTER, BOTTOM]
	# Default Value: TOP
	VerticalAlignment = TOP

	# Description: Visibility of the top page buttons. Use AUTO_HIDE to only show it when there are multiple pages.
	# Valid Values: [ENABLED, AUTO_HIDE, DISABLED]
	# Default Value: ENABLED
	ButtonNavigationVisibility = ENABLED

	# Description: Set to true to draw a background texture behind the gui.
	# Valid Values: [true, false]
	# Default Value: false
	DrawBackground = false

[BookmarkList]
	# Description: Max number of rows shown
	# Valid Values: An integer in the range [1, 100] (inclusive)
	# Default Value: 16
	MaxRows = 16

	# Description: Max number of columns shown
	# Valid Values: An integer in the range [4, 100] (inclusive)
	# Default Value: 9
	MaxColumns = 9

	# Description: Horizontal alignment of the ingredient grid inside the available area
	# Valid Values: [LEFT, CENTER, RIGHT]
	# Default Value: LEFT
	HorizontalAlignment = LEFT

	# Description: Vertical alignment of the ingredient grid inside the available area
	# Valid Values: [TOP, CENTER, BOTTOM]
	# Default Value: TOP
	VerticalAlignment = TOP

	# Description: Visibility of the top page buttons. Use AUTO_HIDE to only show it when there are multiple pages.
	# Valid Values: [ENABLED, AUTO_HIDE, DISABLED]
	# Default Value: ENABLED
	ButtonNavigationVisibility = ENABLED

	# Description: Set to true to draw a background texture behind the gui.
	# Valid Values: [true, false]
	# Default Value: false
	DrawBackground = false

[21:29:01] [Render thread/ERROR]: 'DebugMode' is not a valid config key for config category 'advanced'.
Valid keys: [CenterSearch, LowMemorySlowSearchEnabled, CheatToHotbarUsingHotkeysEnabled, AddBookmarksToFrontEnabled, GiveMode, RecipeGuiHeight]
Skipping this key.
Config file: C:\Users\Sheroz\AppData\Roaming\ATLauncher\instances\BetterMCFORGEBMC3\config\jei\jei-client.ini
Line #5: "	DebugMode = false"
[21:29:01] [Render thread/ERROR]: '[colors]' is not a valid category name.
Valid names are: [advanced, sorting, search, IngredientList, BookmarkList]
Skipping all values until the first valid category is declared.
Config file: C:\Users\Sheroz\AppData\Roaming\ATLauncher\instances\BetterMCFORGEBMC3\config\jei\jei-client.ini
Line #33: "[colors]"
[21:29:01] [Render thread/ERROR]: Expected a '[category]' here.
Configs must start with a category before defining values.
Skipping all lines until the first valid category is declared.
Config file: C:\Users\Sheroz\AppData\Roaming\ATLauncher\instances\BetterMCFORGEBMC3\config\jei\jei-client.ini
Line #38: "	SearchColors = White:EEEEEE, LightBlue:7492CC, Cyan:00EEEE, Blue:2222DD, LapisBlue:25418B, Teal:008080, Yellow:CACB58, GoldenYellow:EED700, Orange:D97634, Pink:D1899D, HotPink:FC0FC0, Magenta:B24BBB, Purple:813EB9, EvilPurple:2E1649, Lavender:B57EDC, Indigo:480082, Sand:DBD3A0, Tan:BB9B63, LightBrown:A0522D, Brown:634B33, DarkBrown:3A2D13, LimeGreen:43B239, SlimeGreen:83CB73, Green:008000, DarkGreen:224D22, GrassGreen:548049, Red:963430, BrickRed:B0604B, NetherBrick:2A1516, Redstone:CE3E36, Black:181515, CharcoalGray:464646, IronGray:646464, Gray:808080, Silver:C0C0C0"
[21:29:01] [Render thread/ERROR]: '[modname]' is not a valid category name.
Valid names are: [advanced, sorting, search, IngredientList, BookmarkList]
Skipping all values until the first valid category is declared.
Config file: C:\Users\Sheroz\AppData\Roaming\ATLauncher\instances\BetterMCFORGEBMC3\config\jei\jei-client.ini
Line #86: "[modname]"
[21:29:01] [Render thread/ERROR]: Expected a '[category]' here.
Configs must start with a category before defining values.
Skipping all lines until the first valid category is declared.
Config file: C:\Users\Sheroz\AppData\Roaming\ATLauncher\instances\BetterMCFORGEBMC3\config\jei\jei-client.ini
Line #94: "	ModNameFormat = blue italic"

### Expected Behavior

Not keep spamming the log with this message on 1.19.2 forge 43.3.5

### Actual Behavior

explained already

### latest.log

not needed

**Comment by lSherozl** [comment]
The question I have is the 1.20.1 config file for JEI is fine, can I just copy and paste the configs of that for the 1.19.2?

**Comment by mezz** [comment]
Thanks for the report!
Please delete the config files, JEI will recreate them with the correct categories and then you can edit them however you like.
