### ISSUE TITLE
[Bug]: EMI-JEI Restart 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [mezz/JustEnoughItems#3424]
### Steps to Reproduce the Bug

emi-1.1.0+1.19.2+forge.jar 
JER-Integration-4.5.0.jar
 jeimultiblocks-1.19.2-0.0.3.jar
 jei-1.19.2-forge-11.6.0.1018.jar 
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
JustEnoughResources-1.19.2-1.2.3.243.jar

### Expected Behavior

EMI + JAY are opening normally.

### Actual Behavior

When opening the inventory, EMI writes reboot. I'll take a screenshot later.

### Extra Notes (Optional)

[Render thread/ERROR] [me.je.fo.st.StartEventObserver/]: A Screen is opening but JEI hasn't started yet. Normally, JEI is started after ClientPlayerNetworkEvent.LoggedInEvent, TagsUpdatedEvent, and RecipesUpdatedEvent. Something has caused one or more of these events to fail, so JEI is starting very late.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by Krimatoria** [comment]
> Thanks for the report! I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

I don't have this log anymore. I'll try to reproduce it tomorrow.
