### ISSUE TITLE
[Bug]: Tooltip error, see logs

### ISSUE THREAD

**Issue by SenorFuego** [mezz/JustEnoughItems#3430]
### Steps to Reproduce the Bug

hover over items in jei and see 'tooltip error, see logs'

### Expected Behavior

See details, durability, etc...

### Actual Behavior

red letters that spell out 'tooltip error, see logs'

### Mod Pack Version (Optional)

1.20.1

### latest.log

<script src="https://gist.github.com/SenorFuego/051672f7212cc13e1d6c6cbae27ef907.js"></script>

**Comment by mezz** [comment]
Thanks for the report!
This is a server log so it does not have the information needed, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
