### ISSUE TITLE
[Bug]: "Tooltip error, see logs" after rejoining a server/relaunching the game [Not An Other Mod Issue Please Remove Label]

### ISSUE THREAD

**Issue by NicKnack819** [mezz/JustEnoughItems#3432]
### Steps to Reproduce the Bug

1. Create an Instance of the game with the mod join a server
2. Hover over items in JEI to see item tooltips and info working fine
3. Leave The Server Then Either:
- Join a singleplayer world and leave then go back to a server 
- Close the game and reopen
4. Hover over items in JEI and see "tooltip error, see logs" In red font... it also applies to the recipes page items.

### Expected Behavior

Being able to hover over items in JEI to see item tooltips and info 

### Actual Behavior

Hovering over items in JEI shows "tooltip error, see logs" In red font; this also applies to the recipe page items as well it will show the recipe path name on that screen however

![image](https://github.com/mezz/JustEnoughItems/assets/60555295/c8c54dc3-e61b-470c-9a8a-3c8c51d8897a)
![2024-02-13_13 48 17](https://github.com/mezz/JustEnoughItems/assets/60555295/216f1254-32af-4af0-8dab-74ff7267ac11)

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4

### Mod Pack Version (Optional)

Better MC [FORGE] 1.20.1 v26

### Extra Notes (Optional)

Added Mod Files:
appleskin-forge-mc1.20.1-2.5.1.jar
architectury-9.1.13-forge.jar
betterstats-3.8+fabric-1.20.1.jar
CerbonsAPI-Forge-1.20.1-1.1.0.jar
chesttracker-1.20.1-1.1.23.jar
Controlling-forge-1.20.1-12.0.2.jar
forge-1.20.2-optionsprofiles-v1.1.jar
InventoryProfilesNext-forge-1.20-1.10.9.jar
jeed-1.20-2.1.7.jar
jei-1.20.1-forge-15.3.0.4.jar
jepp-1.20-1.1.2.jar
jess-1.20.1-forge-1.1.0.jar
JustEnoughBeacons-Forge-1.20.4-1.2.0.jar
libIPN-forge-1.20-4.0.1.jar
malilib-fabric-1.20.1-0.16.3.jar
oauth-1.1.15-1.20.jar
Searchables-forge-1.20.1-1.0.2.jar
xaeros-map-chest-tracker-integration-mc1.20.1-v1.0.2.jar
[1.20-1.20.1]+Comics+Bubbles+Chat-1.3.4.jar

The issue happened without them as well though

### latest.log

https://gist.github.com/NicKnack819/d5c1c1d7a6c88865400fbd017d3e628c

**Comment by mezz** [comment]
Thanks for the report!
```
[13:47:53] [Render thread/ERROR]: Caught an error rendering an Ingredient's tooltip:

-- Ingredient --
Details:
	Name: Shield
	Mod's Name: Minecraft
	Registry Name: minecraft:shield
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 shield
	Unique Id for JEI (for JEI Blacklist): minecraft:shield
	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
	Error Info gathered from JEI: 1 shield minecraft:shield nbt:{Damage:0}

-- Stack Trace --

java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.ShieldExpansionEvents.getShieldValue(ShieldExpansionEvents.java:246)
	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.validate(TooltipEvents.java:61)
	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.tooltip(TooltipEvents.java:38)
	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.onTooltipCreate(TooltipEvents.java:24)
	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.__TooltipEvents_onTooltipCreate_ItemTooltipEvent.invoke(.dynamic)
	
```

It looks like the `shield` item is broken because of the `shieldexp` mod, please report the crash to them with the full client log, and link back to this issue.

**Comment by NicKnack819** [comment]
> Thanks for the report!
> 
> ```
> [13:47:53] [Render thread/ERROR]: Caught an error rendering an Ingredient's tooltip:
> 
> -- Ingredient --
> Details:
> 	Name: Shield
> 	Mod's Name: Minecraft
> 	Registry Name: minecraft:shield
> 	Class Name: class net.minecraft.world.item.ItemStack
> 	toString Name: 1 shield
> 	Unique Id for JEI (for JEI Blacklist): minecraft:shield
> 	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
> 	Error Info gathered from JEI: 1 shield minecraft:shield nbt:{Damage:0}
> 
> -- Stack Trace --
> 
> java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.ShieldExpansionEvents.getShieldValue(ShieldExpansionEvents.java:246)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.validate(TooltipEvents.java:61)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.tooltip(TooltipEvents.java:38)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.onTooltipCreate(TooltipEvents.java:24)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.__TooltipEvents_onTooltipCreate_ItemTooltipEvent.invoke(.dynamic)
> 	
> ```
> 
> It looks like the `shield` item is broken because of the `shieldexp` mod, please report the crash to them with the full client log, and link back to this issue.

but why does it work upon first loading a new instance but break after relaunching?
edit: it doesn't crash it just breaks jei's tooltips and sometimes the ones in the inventory too... also the pack installed latest Jei version but if i revert to "jei-1.20.1-forge-15.2.0.27" it fixes things

**Comment by NicKnack819** [comment]
> Thanks for the report!
> 
> ```
> [13:47:53] [Render thread/ERROR]: Caught an error rendering an Ingredient's tooltip:
> 
> -- Ingredient --
> Details:
> 	Name: Shield
> 	Mod's Name: Minecraft
> 	Registry Name: minecraft:shield
> 	Class Name: class net.minecraft.world.item.ItemStack
> 	toString Name: 1 shield
> 	Unique Id for JEI (for JEI Blacklist): minecraft:shield
> 	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
> 	Error Info gathered from JEI: 1 shield minecraft:shield nbt:{Damage:0}
> 
> -- Stack Trace --
> 
> java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.ShieldExpansionEvents.getShieldValue(ShieldExpansionEvents.java:246)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.validate(TooltipEvents.java:61)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.tooltip(TooltipEvents.java:38)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.TooltipEvents.onTooltipCreate(TooltipEvents.java:24)
> 	at TRANSFORMER/shieldexp@1.1.7a/org.infernalstudios.shieldexp.events.__TooltipEvents_onTooltipCreate_ItemTooltipEvent.invoke(.dynamic)
> 	
> ```
> 
> It looks like the `shield` item is broken because of the `shieldexp` mod, please report the crash to them with the full client log, and link back to this issue.

After looking through some other issues this is not a separate mods issue. It happens in modpacks without the `Shield Expansion` mod too seems like it happens without the `Minecraft Transit Railway` mod which was mentioned in #3420

**Comment by mezz** [comment]
Most likely there are multiple issues that cause rendering problems. Both mods may cause their own crash, which is caught and reported by JEI here.

**Comment by NicKnack819** [comment]
> Most likely there are multiple issues that cause rendering problems. Both mods may cause their own crash, which is caught and reported by JEI here.

it's not a crash though it runs mostly okay but jei refuses to work even when used alone

**Comment by mezz** [comment]
It would be a crash normally, I have JEI intervene. It will print the crash report to the logs instead of letting it break the game entirely.

**Comment by NicKnack819** [comment]
> It would be a crash normally, I have JEI intervene. It will print the crash report to the logs instead of letting it break the game entirely.

okay that's fair and all... but what about the part where it does it when used as a standalone with no other mods added?

**Comment by mezz** [comment]
What part? Sorry, you haven't reported something like that here. 
If you have an issue with JEI and nothing else, please post the details so that I can look into it. I'll need a crash log and the client log to see what's going on.

**Comment by NicKnack819** [comment]
> What part? Sorry, you haven't reported something like that here. If you have an issue with JEI and nothing else, please post the details so that I can look into it. I'll need a crash log and the client log to see what's going on.

oh my bad will make a report later it's kinda late now sorry
