### ISSUE TITLE
[Crash]:  The game crashed whilst keypressed event handler Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.gui.components.EditBox.m_94204_()" because "searchBox" is null

### ISSUE THREAD

**Issue by Virtual-Enchanter** [mezz/JustEnoughItems#3434]
### Steps to Reproduce the Crash

Open

### Mod Pack Version (Optional)

1.20.1

### Crash Report

https://gist.github.com/Virtual-Enchanter/808a5dceead37d3e3d1d10a2179f05f2

**Comment by NicKnack819** [comment]
Was this in a Luna Pixel Studios mod pack, like Prominence or Better MC?

**Comment by Virtual-Enchanter** [comment]
No it was in a custom modpack i made

**Comment by likmum001** [comment]
> Was this in a Luna Pixel Studios mod pack, like Prominence or Better MC?

I am currently having this issue in BMC 4 with few added mods.
