### ISSUE TITLE
[Bug]:  Tooltip Error, See Logs displaying on JEI

### ISSUE THREAD

**Issue by ToxicTerror86** [mezz/JustEnoughItems#3436]
### Steps to Reproduce the Bug

1. Upon Joining Server its doing it
2. 
![2024-02-15_16 50 59](https://github.com/mezz/JustEnoughItems/assets/143304159/55bd1ffd-90dd-4a05-9f91-45c3d41de22a)
![2024-02-15_16 51 04](https://github.com/mezz/JustEnoughItems/assets/143304159/823151e5-1025-4963-a523-2fa4f62e3139)

[HK 4th Wall-V-1.2.zip](https://github.com/mezz/JustEnoughItems/files/14303256/HK.4th.Wall-V-1.2.zip)

There is an Export of Mods

### Expected Behavior

Should see item Name 

### Actual Behavior

Showing Tooltip Error, See Logs

### latest.log

https://gist.github.com/ToxicTerror86/7b610b38abf5076015a084bd70877a68

**Comment by NicKnack819** [comment]
#3432 kind of the same I think

Edit: Try reverting to "jei-1.20.1-forge-15.2.0.27" it fixed things for me

**Comment by gkr0013** [comment]
I had the same issue (custom modpack) with 15.3.0.1 ans 15.3.0.4. Reverting back to 15.2.0.27 resolves the bug.

**Comment by mezz** [comment]
Please try the latest release of JEI from today, I updated it to try to contain the damage from broken tooltips a bit better.

Duplicate of #3432
