### ISSUE TITLE
[Bug]: Recipes/uses not showing on server

### ISSUE THREAD

**Issue by linalinm** [mezz/JustEnoughItems#3440]
### Steps to Reproduce the Bug

Try to check the recipe or use of any item while on a server 

### Expected Behavior

Should show the possible recipes, especially as they all work

### Actual Behavior

Only anvil recipes are shown, in the case of tools, and none in the case of other items 

### Mod Pack URL (Optional)

https://www.dropbox.com/scl/fi/f1u08uymxep2piqpdmmwv/berk-pack-3.1.zip?rlkey=d8vqlxa8lvlnx210ld2sbpwr0&dl=0

### latest.log

https://gist.github.com/Zisu124/911447535fb9463253e70b2fea34bd9b

**Comment by linalinm** [comment]
Issue was a different mod (rosia), it was corrupting the recipe sending 
after downgrading jei a bunch on the server and trying stuff out I got a detailed stacktrace which mentioned rosia 
downgrading it to 0.0.17 from 0.1.0 fixed it

**Comment by EliasRipley** [comment]
Have noticed this bug reappear on our server when using:

JEI 15.3.0.4
Create 0.5.1.f
Sometimes no Create mod recipes appear, other times, only the "unlocked" recipes appear. Sometimes everything is fine.

Temporary solution to the issue is to close down MC and restart. Does seem to be quite random though.

**Comment by EliasRipley** [comment]
Oh sorry, should have added that we don't have Rosia installed, so it definately is not the culprit in my particular instance.

**Comment by Jack67119** [comment]
Also having this issue on 1.19.2 on my own dedicated server. I don't have rosia either, I'm also on fabric. Server's mods are the exact same as client, I'm hosting the server myself on the same computer I'm running the game on.
