### ISSUE TITLE
[Bug]: Config button doesn't work in Fabric 1.20.4 even with Configured installed

### ISSUE THREAD

**Issue by thislooksfun** [mezz/JustEnoughItems#3441]
### Steps to Reproduce the Bug

1. Install Fabric for 1.20.4
2. Install JEI 17.3.0.49 for Fabric
3. Install Configured 2.2.3 for Fabric
4. Open the game
5. Click the settings button in JEI

### Expected Behavior

It should either open the Configured settings or say that Configured is not supported.

### Actual Behavior

It says that Configured is not installed, and links to the download page.

### Extra Notes (Optional)

It looks like there is just no support for detection of Configured in Fabric.

https://github.com/mezz/JustEnoughItems/blob/404514ad2e11919fde84fb784aa7ed3b758cec63/Fabric/src/main/java/mezz/jei/fabric/platform/ConfigHelper.java#L17-L20

**Comment by thislooksfun** [comment]
Still not fixed

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878
