### ISSUE TITLE
[Bug]: JEI breaks search in vanilla recipe book (Forge 1.20.1)

### ISSUE THREAD

**Issue by AltPlus30** [mezz/JustEnoughItems#3442]
### Steps to Reproduce the Bug

1. Install Forge and JEI on 1.20.1
2. Open vanilla recipe book in Crafting Table or Inventory
3. Attempt using search
4. No results show up

### Expected Behavior

Search in vanilla recipe book working.

### Actual Behavior

Vanilla recipe book doesn't show any results when searching for items.

### latest.log

https://gist.github.com/AltPlus30/4f76815bb5437677fe790b43b5a822b2

**Comment by AriaFantom** [comment]
I faced the same issue in Fabric too

**Comment by WhiteBoi1211** [comment]
Same Issue
