### ISSUE TITLE
JEI Unable to load Tool Tip

### ISSUE THREAD

**Issue by BloodyMad** [mezz/JustEnoughItems#3444]
### Other

I can't seem to see any information able the item other than the image and recipe. . . It says to check log for more information. . . :(( 

[Uploading latest.log…]()

**Comment by gkr0013** [comment]
Try reverting to "jei-1.20.1-forge-15.2.0.27" ;-)

**Comment by mezz** [comment]
Please try the latest release of JEI from today, I updated it to try to contain the damage from broken tooltips a bit better.

Duplicate of #3432
