### ISSUE TITLE
[Bug]: tooltip error 

### ISSUE THREAD

**Issue by MehanikTMYT** [mezz/JustEnoughItems#3447]
### Steps to Reproduce the Bug

Launch world, open inv, look at any item

### Expected Behavior

item name, proporties, etc

### Actual Behavior

error tooltip, see log

### Mod Pack URL (Optional)

http://92.255.108.96/ftb/1.20.4-forge/

### Extra Notes (Optional)

in first start freezes in opening inv and error starts after some time (relauch world doesn't work)

### latest.log

https://gist.github.com/MehanikTMYT/fb745404811ae8520cb8856e62e419a5

**Comment by MehanikTMYT** [comment]
![image](https://github.com/mezz/JustEnoughItems/assets/29605858/d6384da7-7a53-43a5-9245-bb4406ad5bb1)

**Comment by BeastMaster6989** [comment]
encountered the same error on 1.20.1(

**Comment by BeastMaster6989** [comment]
Edit: Try reverting to "jei-1.20.1-forge-15.2.0.27" it fixed things for me) no thx)

**Comment by MehanikTMYT** [comment]
i hope one of this verisons will work more correct 
![image](https://github.com/mezz/JustEnoughItems/assets/29605858/89fabefb-3c45-484d-87c2-dbfd7f90d38e)

**Comment by MokahTGS** [comment]
Yes, happening on 1.20.1...please fix.
