### ISSUE TITLE
[Bug]: [Bug]: Config button doesn't work in Fabric 1.20.1 even with Configured installed

### ISSUE THREAD

**Issue by Enibeatz** [mezz/JustEnoughItems#3448]
### Steps to Reproduce the Bug

i try to clic on the configue button and it send me a url to Install configue mod , i Install it and Nothing happent 

### Expected Behavior

i try to clic on the configue button and it send me a url to Install configue mod , i Install it and Nothing happent 

### Actual Behavior

i try to clic on the configue button and it send me a url to Install configue mod , i Install it and Nothing happent

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878
