### ISSUE TITLE
[Bug]: Config button does nothing, even after "Configured" mod is already installed

### ISSUE THREAD

**Issue by dhasial** [mezz/JustEnoughItems#3449]
### Steps to Reproduce the Bug

1. Install the "Configured" mod as instructed by the config button message
2. Restart minecraft
3. Get the exact same message despite the mod being installed

### Expected Behavior

I expect the config button next to the search bar to open a config menu after the quasi-dependant "Configured" mod has been installed.

### Actual Behavior

The config button gives the exact same message regardless of whether or not "Configured" is installed (and the config menu never opens, just as it didn't before)

### Mod Pack URL (Optional)

https://github.com/TheStaticVoid/StaTech-Industry

### Mod Pack Version (Optional)

1.1.11

### Extra Notes (Optional)

- Fabric mod loader
- MC version 1.19.2
- JEI version 11.6.0.1019
- Configured version 2.0.0

This is likely related to #3448 

"Configured" also never creates a config file button in the mod menu either.

It would be nice if, at the very least, keybinds were available to be edited in `jei-client.ini` so even if something breaks, they could still be edited. Though obviously it's preferable to just fix whatever has caused this.

### latest.log

https://gist.github.com/dhasial/73d082f52261fcb883dd2c228c310d7a

**Comment by Myakishow** [comment]
I get the same error, jei-1.20.1-fabric-15.3.0.4 asks to install configured, although it is installed

**Comment by hatkidchan** [comment]
Same happens to me, `Configured 2.2.3`, `JEI 15.3.0.4` on `MC 1.20.1` w/ `Fabric 0.15.7`

It happens despite this being in logs, implying that it detects it fine:
```
[10:41:34] [Render thread/INFO]: Successfully loaded config provider: com.mrcrayfish.configured.impl.framework.FrameworkConfigProvider
[10:41:34] [Render thread/INFO]: Successfully loaded config provider: com.mrcrayfish.configured.impl.jei.JeiConfigProvider
```

**Comment by DTX3** [comment]
Doesn't seem to work correctly with JEI or isn't recognised that it's installed. When I try to search within JEI, I get a message saying I need to install Configured when I do have it installed. I'm using Fabric 1.20.1.

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878
