### ISSUE TITLE
[Crash]: Something to do with occultism (java.lang.IllegalStateException: Item has no registry name: 1 air com.klikli_dev.occultism.common.item.DummyTooltipItem)

### ISSUE THREAD

**Issue by ImUnlimited** [mezz/JustEnoughItems#3456]
### Steps to Reproduce the Crash

I don't know how to reproduce it, it just randomly crashes when i'm using JEI.

### Crash Report

https://gist.github.com/ImUnlimited/1d35f3ff8f5276b4d4dd131bde1827df

**Comment by Sandriell** [comment]
Getting a similar error here. Crash seems to occur when mousing over an item. Doesn't appear to be one specific mod either, seems random.

Forge, 1.20.1

https://gist.github.com/Sandriell/be2c514b27b8f9ed82639eacc67d6fcc
https://gist.github.com/Sandriell/c276a4da3c3ada1c3697945e0ac4aa0f
