### ISSUE TITLE
Error with items

### ISSUE THREAD

**Issue by paulaa4** [mezz/JustEnoughItems#3462]
### Steps to Reproduce the Bug

<img width="386" alt="Captura de pantalla 2024-03-18 195420" src="https://github.com/mezz/JustEnoughItems/assets/163907941/b62f7e15-a300-473f-942a-ae2e2ff5902e">

Could someone tell me what's happening, I've tried everything and nothing works.

### Expected Behavior

All the items in the game should appear but it appears like this and I can't even see the crafting.

### Actual Behavior

You are left with that error image.

### Mod Pack Version (Optional)

1.20.1

**Comment by Picus25** [comment]
Same problem here and some of my friends have it too. 

No know cause for us and for now, just while playing it can happen. 

Did you find a fix by any chance ? Thanks

**Comment by erkead** [comment]
same issue occurring. only fix is to fully close client and reload.

**Comment by mezz** [comment]
Thanks for the report!
I pushed some improvement to this some time ago, please try out the latest version and you should have less issues.
