### ISSUE TITLE
[Suggestion]: a hotkey that copies the recipe id to the clipboard quickly

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#3465]
### Suggestion

Hi i am working on a modpack and was wondering if there is a way to copy the recipe id directly to my clipboard instead of typing it out letter by letter

Info:

Modloader: forge
Mc version: 1.20.1
Jei version: latest

**Comment by mezz** [comment]
Thanks for the suggestion!
There is a hotkey for this that you can set in the minecraft keybindings config screen.
