### ISSUE TITLE
[Suggestion]: [1.16.5] backport loading and reloading from 1.19+ to 1.16.5

### ISSUE THREAD

**Issue by Mysticpasta1** [mezz/JustEnoughItems#3466]
### Suggestion

Please backport the way of recipe loading (registering) from 1.19+ to 1.16.5, rn if you have a lot of mod it will take a while to go into a world due to it registers recipes before world loading instead of while you are in a world. The causes longer wait times the more mods added.

**Comment by anoomolu** [comment]
Would suggest using Modernfix, it does this for 1.16:

> 1.16 only. A key optimization. Patches JEI to perform its reloading on a background thread, completely eliminating the long delay it adds to world loading.

Been using it myself for ages and it works great.
