### ISSUE TITLE
API Filtering Paging Bug

### ISSUE THREAD

**Issue by Trcx528** [mezz/JustEnoughItems#347]
Using refined storage (RS), there is an option to synchronize the search within RS with JEI.  When searching JEI through RS it is possible to be on a page that does not exist.  For example you could easily end up on page 40 of 4.  As expected, no items will be displayed.  RS is using the api method `IItemListOverlay#setFilterText` to cause the search.  When this method is called JEI should reset the paging such that page 1 is the current page.  Implementing this change will cause JEI's behavior to be consistent between searching through the API and while searching in the default JEI search box.  

For more information please refer to https://github.com/raoulvdberge/refinedstorage/issues/166

**Comment by mezz** [comment]
Thanks for the report!
Fixed in 3.7.5
