### ISSUE TITLE
[Crash]: "String.Length()" "p_135844_"

### ISSUE THREAD

**Issue by MrSmiles-code** [mezz/JustEnoughItems#3470]
### Steps to Reproduce the Crash

game doesn't start. "jei cannot load correctly" "java.lang.nullpointerexception: cannot invoke "String.Length()" because "p_135844_" is null
please help

### Crash Report

https://gist.github.com/MrSmiles-code/0883160b4c3668faa4b9a43b129f94f9

**Comment by Dylan-Odjidja-Portfolio** [comment]
just got this same error. some help would be appreciated. it was working just until i added and updated some mods in my modpack.

Updated:
 - Lootr
 - Polymorgh
 - Simple Voice Chat
 - Twilight's Flavour & Delight
Added:
 - Ender Chests
 - Ender Tanks
 - Create: Edner Transmission
 - Botanical Machinery
 - Builder's Delight
 - Gauges and Switches

**Comment by MrSmiles-code** [comment]
seems the cause is gauges and switches witch is a shame

**Comment by Dylan-Odjidja-Portfolio** [comment]
damn well thanks for the help
