### ISSUE TITLE
[Other]: JEI is Marked "Unsupported" for Servers on Modrinth

### ISSUE THREAD

**Issue by rehashedsalt** [mezz/JustEnoughItems#3474]
### Other

Appears to be a resurfacing of #3401. [Link to Modrinth page](https://modrinth.com/mod/jei).

**Comment by MelanX** [comment]
Server files aren't created properly because of this. Would be awesome if it could be updated :)

**Comment by MelanX** [comment]
Still relevant

**Comment by TaiAurori** [comment]
This indeed causes problems with Packwiz, which by default will only ever attempt to install JEI on clients and not servers. Shouldn't it be marked as "Optional" for server-side?

**Comment by mezz** [comment]
Sorry for not getting around to this earlier, I'm not sure why it changed.
JEI is now marked as Optional for server-side 👍 
Please let me know if you run into something like this again, or any issues with the new declarations.

**Comment by different-name** [comment]
> Sorry for not getting around to this earlier, I'm not sure why it changed. JEI is now marked as Optional for server-side 👍 Please let me know if you run into something like this again, or any issues with the new declarations.

@mezz this is an issue again https://modrinth.com/mod/jei

**Comment by mezz** [comment]
@different-name thank you for notifying me. Sorry for the trouble, I'll update the settings.
I am reaching out to Modrinth now to try to get to the bottom of why this keeps happening.

**Comment by Prospector** [comment]
unfortunately, currently Optional is an unsupported option. we're working to fix it

**Comment by different-name** [comment]
> unfortunately, currently Optional is an unsupported option. we're working to fix it

[Lithium](https://modrinth.com/mod/lithium) is marked as `Client-side`, `Server-side` &  `Client and server`

![image](https://github.com/user-attachments/assets/e420d9c4-7754-4186-a682-cb54a45c2c58)

@mezz can this approach be taken instead? This would resolve the issue
