### ISSUE TITLE
[Bug]: JEI does not allow me to type in search bar

### ISSUE THREAD

**Issue by Alvar04ka** [mezz/JustEnoughItems#3478]
### Steps to Reproduce the Bug

So I went to the config file and changed to be able to center the search bar (which is awesome). However, I cannot use the search bar whatsoever. CTRL+F allows me to enter the search bar (and also clicking) but I literally cannot search for items. Also, the wrench that is there does not work.

### Expected Behavior

It should work )

### Actual Behavior

I can click on the Search bar, and there's a blinking underline as though I should be able to type in, but it doesn't respond to my keyboard at all.

**Comment by OverSavior** [comment]
Same issue, Fabric, 17.3.0.49

**Comment by calliecameron** [comment]
This is also happening for me on 11.6.0.1018 and 11.6.0.1019 on mc 1.19.2. However, 11.6.0.1018 worked in an older version of my modpack, so it might be an incompatibility with something else that's been updated.

**Comment by calliecameron** [comment]
The incompatibility in my case was with [Effortless](https://modrinth.com/mod/effortless). I removed that and the JEI search bar works again.

**Comment by MooKwai** [comment]
I was getting the same using the Fabric loader and ended up here

Removing Optifine and Optifabric meant the search bar started working again

[LambDynamicLights ](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights) gives me the dynamic lighting I wanted from Optifine

**Comment by ismael1222** [comment]
Updating this issue, i got the same issue, and i have OptiFabric+Optifine.
Mod ver: 1.2.0
Optifine: HD U I7
MC Ver: 1.20.4
OptiFabric: 1.14.3
