### ISSUE TITLE
Visual Bugs

### ISSUE THREAD

**Issue by jjc54** [mezz/JustEnoughItems#348]
JEI: jei_1.10.2-3.7.5.227 (Latest)
Screens: http://imgur.com/a/B79QR
Screen 1: Any item that has an enchantment glow is showing up weird.
Screen 2-4: There are some odd visual bugs in many items such as Vanilla Banners, Forestry Piles, and TConstruct Tool Blocks. 

This bug only appears on the latest version and persists across instance restarts.

**Comment by jjc54** [comment]
Darn upon further testing this seems to be a Optifine issue.

**Comment by AEnterprise** [comment]
@whitestarx0312 if the problem is solved you the issue should be closed, as you opened it you can also close it yourself

**Comment by jjc54** [comment]
Alright I just wanted to make sure it was Optifine and open a issue there before I did so.

**Comment by mezz** [comment]
Thanks for reporting appropriately and linking it back here!
