### ISSUE TITLE
[Crash]: singleplayer world crashes when looking through Mekanism recipes

### ISSUE THREAD

**Issue by noolaaa** [mezz/JustEnoughItems#3486]
### Steps to Reproduce the Crash

Click around through the Mekanism (seems to be only Mekanism) recipes.
Doesn't happen every time, but sometimes i will look at one recipe and it crashes, or other i could play for nearly 5-10 with no issue.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4

### Mod Pack Version (Optional)

1.20.1

### Extra Notes (Optional)

Doesn't crash every time I look at a recipe, only on occasion after I've been clicking around looking at multiple recipes.

### Crash Report

https://gist.github.com/noolaaa/c0e96da3cb100fc3b94f47a94acd7e13#file-gistfile1-txt

**Comment by Emub** [comment]
This same crash happens to me as well, when viewing exiting the inventory while viewing certain Mekanism recipes. It happens every time I view the recipe for smelting iron dust. My crash report is here:

[crash-2024-09-01_23.50.57-client.txt](https://github.com/user-attachments/files/16830603/crash-2024-09-01_23.50.57-client.txt)

**Comment by D0vine722** [comment]
Disable Inventory Management from your mod config page; this is what worked for me. It's either a conflict with that mod or JEI.
