### ISSUE TITLE
[Bug]: Config GUI wont open with Configured installed

### ISSUE THREAD

**Issue by abidbmt** [mezz/JustEnoughItems#3487]
### Steps to Reproduce the Bug

Try to access config

### Expected Behavior

Opens config

### Actual Behavior

Tells me to install Configured even tho its installed

### Extra Notes (Optional)

Modloader: Fabric
Minecraft Version: 1.20.1
JEI Version: 15.3.0.4
Configured Version: 2.2.3

### latest.log

https://gist.github.com/abidbmt/63026928feff38e3e3510d8cea3f2a72

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878
