### ISSUE TITLE
[Bug]: Tooltip Error, No clue how to fix it

### ISSUE THREAD

**Issue by LadderDCombo** [mezz/JustEnoughItems#3489]
### Steps to Reproduce the Bug

Press E to open inventory, then hover over any item in JEI's menu.

### Expected Behavior

Should be showing name and info on the item.

### Actual Behavior

Just shows "Tooltip Error, See logs" for any item, even not modded ones

### latest.log

https://mclo.gs/wvQ5bek

**Comment by Roninred** [comment]
how repair error?
