### ISSUE TITLE
Crash on 1.10 - #227 after exit JEI config page

### ISSUE THREAD

**Issue by t3f** [mezz/JustEnoughItems#349]
Was exiting from the JEI config page, then the world renderer looked like it tried to reload (? minecraft window went black like it does on res or settings changes), momentarily came back and then crashed.

Not entirely certain this is JEI crashing, but here is the gist anyway in case it helps elsewhere. 

https://gist.github.com/t3f/85a8e81d109d96f0585d998d2c693972

**Comment by mezz** [comment]
Thanks for the report!
I am not able to reproduce this crash. Do you know of any way to make it happen reliably?
