### ISSUE TITLE
[Suggestion]: jei update or add for NEOForge 1.20.1

### ISSUE THREAD

**Issue by GamingMix0** [mezz/JustEnoughItems#3490]
### Suggestion

jei update or add for NEOForge 1.20.1

There are mods in neoforge that require neoforge 1.20.1 and it would be very nice if that could be added, I can't update to neoforge 1.20.4 because otherwise half of my mods will no longer be there

**Comment by NeoForce0** [comment]
@GamingMix0 just copy the Forge 1.20.1 version into your NeoForge install. It worked for me. Both modloaders are still pretty much the same until 1.21 I hear

**Comment by AnonTheMouse** [comment]
This "solution" does not work. If it's not planned, you need to rethink your plans.
