### ISSUE TITLE
[Crash]: Crashed through looking up an item's uses with "U"

### ISSUE THREAD

**Issue by sugan-reden** [mezz/JustEnoughItems#3495]
### Steps to Reproduce the Crash

1. Open Inventory
2. Hover over item (in this case it was a log of wood)
3. Press U
4. Look through recipes and pages and eventually...
5. Crash :/

### Extra Notes (Optional)

The game was running just fine. I happened to come across a wood log from Ars Nouveau. Chopped it up. Then I wanted to look through it's uses and when I happened to stumble on a page with the "Colony Integrator" block/bench from the mod Advanced Peripherals, the game crashed.

This will also be reported to their page for good measure.

Versions:
MC 1.20.1
Forge 47.2.23
Mod 15.3.0.4

### Crash Report

https://gist.github.com/sugan-reden/ae54deda8ac001a65a5a25fb45d9ca41

**Comment by neox728** [comment]
[crash-2024-05-19_13.14.40-client.txt](https://github.com/mezz/JustEnoughItems/files/15369205/crash-2024-05-19_13.14.40-client.txt)
j'ai exactement le même problème sur un modpack custom enchanted engineers 1.19.2 des  que je fait U sur l'ender pouch le jeux plante instant et j'ai ça comme erreur 

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

**Comment by mezz** [comment]
Thanks for the report!
Please link issues together in the future so they're easier to find (like this: https://github.com/IntelligenceModding/AdvancedPeripherals/issues/591).

This is caused by a problem from Advanced Peripherals but I can try to catch the crash and keep the game running.

**Comment by mezz** [comment]
JEI should catch and log this now, in 1.20.1 and 1.21. 
The issue still needs to be fixed in the other mod, but at least the game should be playable now!

**Comment by sugan-reden** [comment]
> Thanks for the report! Please link issues together in the future so they're easier to find (like this: [IntelligenceModding/AdvancedPeripherals#591](https://github.com/IntelligenceModding/AdvancedPeripherals/issues/591)).
> 
> This is caused by a problem from Advanced Peripherals but I can try to catch the crash and keep the game running.

Forgive my inexperience, I'll definitely keep that in mind in the future :)

> JEI should catch and log this now, in 1.20.1 and 1.21. The issue still needs to be fixed in the other mod, but at least the game should be playable now!

Thank you very much, kind human :) ❤️ Please keep up the awesome work! 👍
