### ISSUE TITLE
[Bug]: Modpack multiplayer JEI doesn't show any recipes 

### ISSUE THREAD

**Issue by Sayaniku** [mezz/JustEnoughItems#3498]
### Steps to Reproduce the Bug

Going into multiplayer and try to check an recipe

### Expected Behavior

Every craft isn't showing up

### Actual Behavior

Nothing, everything explained

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/berseria-sky

### Mod Pack Version (Optional)

0.9.21HF

### Extra Notes (Optional)

Going to solo and after on multiplayer isn't patch the things, every craft is possible

### latest.log

https://gist.github.com/Sayaniku/8ff0542d69ee39184f48e76d751b08ba

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here. The log you have linked is the server log, but JEI is mostly client-side.
