### ISSUE TITLE
[Crash]: JEI crash with in cheat.

### ISSUE THREAD

**Issue by IamGallito** [mezz/JustEnoughItems#3499]
### Steps to Reproduce the Crash

start world in creative 
toggle cheat mode in GUI for JEI
crash after
 gist of crash attached

### Crash Report

https://gist.github.com/IamGallito/118b76f3376acad0b3d37a01b077912c

**Comment by mezz** [comment]
Thanks for the report!
This appears to be the same as https://github.com/mezz/JustEnoughItems/issues/3460
I will merge these two issues together, please take discussion to the other issue.
