### ISSUE TITLE
[incompatibililty] Moving items into crafting grid not showing up whenever VisibleArmorSlots mod is installed

### ISSUE THREAD

**Issue by Lothrazar** [mezz/JustEnoughItems#350]
I have the 'jei_1.10.2-3.7.5.227' build installed in single player, and noticed that this plus button stopped working after adding new mods.  I narrowed it down and it is exactly the

VisibleArmorSlots[1.10.2]-2.0.jar

mod that causes this.  I assume because it adds some slots / modifies GUI's such that you can no longer detect where the local crafting grid is in whatever GUI is open, so it hides the button.

I realize this might not be something you can even fix on your end, but just to have this on record since other people may also notice it..

**Comment by mezz** [comment]
Thanks for the report!
I'm not sure what they're doing but that's... not good. Hmm.
Nothing should mess with the vanilla slots that way. It looks like it has incompatibilities with other things as well: https://github.com/sidben/VisibleArmorSlots/issues
Can you report the issue there?

**Comment by TehNut** [comment]
They replace the vanilla GUI's, IIRC.
