### ISSUE TITLE
[Bug]: Recipes not showing, 1.20.1

### ISSUE THREAD

**Issue by muppetenergy** [mezz/JustEnoughItems#3501]
### Steps to Reproduce the Bug

press 'E' to bring up inventory/JEI menu. 
type in JEI search bar full or partial name of item 

I am playing on a dedicated server, and have made my own modpack, so there isn't a website for it to link. 

### Expected Behavior

item is brought up in the panel on the right hand side, can then click on it to see recipe, or press R

### Actual Behavior

only some recipes matching the search come up. for example, currently searching for "sheet" only brings up copper and brass (from Create), but not the iron ones from the same mod. 
Previously this was applying to the crushing wheel from Create, now it is all of the above. I don't know which other items are impacted so far. 
I haven't created this kind of ticket before, so please let me know what more information is required and thank you for your patience and time.

**Comment by muppetenergy** [comment]
I *think* this is caused by the Randomium mod? Just removed it from the server, and ...so far, so good.

**Comment by kuro-mujou** [comment]
got same issue too, just my own mod pack with full of create stuff and JEI seem like not recognize all the recipe, some of brass recipe got lost JEI menu, i have to find it manually through my memory LMAO.

**Comment by kuro-mujou** [comment]
> I _think_ this is caused by the Randomium mod? Just removed it from the server, and ...so far, so good.

hey, do you have the ad-on mod called JEI Intergration? i just add that on my mod pack and everything work again

**Comment by muppetenergy** [comment]
I do have JEI integration, and ...unfortunately the issue started again despite removing Randomium. It seemed fine, but now at least 1 random recipe is not coming up again for me
it's different every time but it behaves the same way 
if i have the item in my inventory already, i can hit R or U while hovering over it. but it doesn't come up at all from searching. and often the R/U functions don't work when i try to use them in the JEI menus

**Comment by Skyboxmonster** [comment]
I have the same issue with the items randomly disappearing during normal gameplay. 
The recipes are missing from both the creative menu and the JEI menu. 

the modpack I am using has three JEI related mods installed.
jei 1.20.1 forge 15.2.0.4
JustEnoughProfessions forge 1.20.1 -3.0.1
JustEnoughResources 1.20.1-1.4.0.247

logging out of a multiplayer server does not bring back the missing recipes.
Fully shutting down Minecraft and relaunching it temporarily returns the items. different items seem to disappear each time. 
using google I found a suggestion to use a custom script mod and code to force JEI to reload or refresh items. 
and another suggestion about changing the max number of recipes/items for JEI to display. though this suggestion was from 2017 and it refers to config entries not found in my modern copy of JEI.  

Now that I type this out I wonder if JEI's failure to display random items is just a symptom of the Creative menu's failure to display the same items. also I wonder why items would disappear during gameplay.  CREATE's small cog is a item I use a lot. and sometimes during the same session that I used it, it would disappear. during run-time. not during startup.

**Comment by muppetenergy** [comment]
yeah skyboxmonster that's the exact same things i'm having. i don't have those other 2 mods installed, but I've been trying to explore using Create and it's become basically impossible. 
large cog wheels disappeared, then I relaunched the game, then i could do those but couldn't get the recipes for rose quartz anymore. relaunched the game, nothing comes up for "chute" at all. relaunch, and only the chute from Supplementaries mod comes up, but nothing else. 
i have absolutely no clue how to make a custom script, i'm not a super tech savvy person :c 
and yeah, it seems like things will randomly disappear. available for a few searches, then gone. but once they disappear, they won't come back until you've relaunched the game at least once. 
really hope there's a fix soon, this is so sad

**Comment by kuro-mujou** [comment]
> I do have JEI integration, and ...unfortunately the issue started again despite removing Randomium. It seemed fine, but now at least 1 random recipe is not coming up again for me it's different every time but it behaves the same way if i have the item in my inventory already, i can hit R or U while hovering over it. but it doesn't come up at all from searching. and often the R/U functions don't work when i try to use them in the JEI menus

yeah so weird, today i need a plough and i try to find it from both creative menu and JEI menu, no recipe found 🥲. then i have to craft it by my self, still don't know what happening

**Comment by Halornek** [comment]
Want to note that I'm having the same issues here. Recipes are randomly not appearing, particularly in regards to Create.

Seems to be largely related to multiplayer. Logging into a single player world and then connecting to multiplayer in the same sessions seems to fix the issue until I restart the game again.

**Comment by muppetenergy** [comment]
missing recipes that i've noticed during the session right now: 
iron sheet, brass sheet, crushing wheel, crushed raw iron, rose quartz, polished rose quartz, large cogwheel, large waterwheel, spout, i don't know what else at the moment 

[latest.log](https://github.com/mezz/JustEnoughItems/files/15304699/latest.log)
[latest server log.docx](https://github.com/mezz/JustEnoughItems/files/15304710/latest.server.log.docx)
[server mod list.docx](https://github.com/mezz/JustEnoughItems/files/15306783/server.mod.list.docx)
[client mods list.odt](https://github.com/mezz/JustEnoughItems/files/15306785/client.mods.list.odt)

**Comment by muppetenergy** [comment]
<script src="https://gist.github.com/muppetenergy/109111e75b81eea96b8ebd1af52c9153.js"></script>

**Comment by blockmath** [comment]
Having an identical issue, but it's also occuring in pure singleplayer and certain items (like create's small cog) are just never appearing even after a restart. I have JEI integration, and JEP/JER in addition to JEI itself.

**Comment by mezz** [comment]
@blockmath sorry please open a new issue, this one is very old and likely has been resolved between now and when it was first reported.
