### ISSUE TITLE
[Crash]: crash on startup, on latest release

### ISSUE THREAD

**Issue by Panda78901** [mezz/JustEnoughItems#3503]
### Steps to Reproduce the Crash

open the game, crash.

### Extra Notes (Optional)

I've tried a ton of different versions of JEI, crash happens every single time. game version is 1.12.2.

### Crash Report

https://gist.github.com/Panda78901/7ad00d1ff3d18e2f22eea7e905ca963b

**Comment by mezz** [comment]
Thanks for the report!
Does this happen when only JEI is installed?
