### ISSUE TITLE
[Bug]: MCA Break Productive bees in JEI

### ISSUE THREAD

**Issue by Aoimina** [mezz/JustEnoughItems#3506]
### Steps to Reproduce the Bug

If you have MCA(Minecraft Come Alive) And Productive bees installed, productive bees bees will not show up in JEI and even their tab will be even removed from resource gathering

![image](https://github.com/mezz/JustEnoughItems/assets/128810513/3f877700-8e41-464c-83d3-c50f36338ec0)

### Expected Behavior

![image](https://github.com/mezz/JustEnoughItems/assets/128810513/3f877700-8e41-464c-83d3-c50f36338ec0)
Netherack should be farmed by the quarry bee yet i dont see it anyhere

### Actual Behavior

It seem the comp still exist but it will redirect me to genaric comb if i try to go for any comb
![image](https://github.com/mezz/JustEnoughItems/assets/128810513/21be8ba2-0363-4d6a-a71e-cc74d6281327)
it also seem to remove all Productive bees comb from base minecraft search too
![image](https://github.com/mezz/JustEnoughItems/assets/128810513/02ec39a8-017c-4304-afaa-a8f1f14292d7)
yet it still there with some loopholes

### Extra Notes (Optional)

Minecraft Forge 1.20.1 Custom modpack, its not any other mod fault as i usually test the mod alone then test it with each mod to make sure everything is compitabe and MCA+JEI+Productive bee is not compatible it seem, its JEI fault as when i tried with REI/EMI they work fine but i prefer JEI for better preformance

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Productive Bees. Each mod adds their own recipes to JEI using a plugin, maybe their plugin has an issue when MCA is installed.
To help with debugging, include a client log and link back to this issue.

**Comment by Aoimina** [comment]
Hi mezz, its been a while my apology, it seem the issue is from MCA reborn and i did report it to productive bees and MCA reborn, productive bees never responed and MCA reborn suggested using REI, so im assuming its conflict between these 2 mods rather then JEI itself, REI installing Did fix it but i prefer JEI+emi so im not going for REI, either way MCA reborn is probably the corprate and the issue solution is to install REI + no longer playing in the modpack where these installed.
