### ISSUE TITLE
[Bug]: JEI Move Items (+) does not show in AE2 crafting grid (1.20.4 Neoforge)

### ISSUE THREAD

**Issue by MikeHollisJr2021** [mezz/JustEnoughItems#3508]
### Steps to Reproduce the Bug

1. Open AE2 Crafting Grid
2. Find Item to craft in JEI
3. Look for + button

### Expected Behavior

1. Open AE2 Crafting Grid
2. Find Item to craft in JEI
3. Click + button

### Actual Behavior

1. Open AE2 Crafting Grid
2. Find Item to craft in JEI
3. The + button is not there.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/fmtt

### Mod Pack Version (Optional)

2.0.0.5

### Extra Notes (Optional)

MC: 1.20.4 (Neoforge)
Neoforge: 20.4.223
AE2: 17.13.0-beta (latest version)
JEI: 17.3.0.52 & 17.3.0.49 

### latest.log

https://gist.github.com/MikeHollisJr2021/be96b46fef6585064eea46563e1db4b3

**Comment by MikeHollisJr2021** [comment]
This has also been reported on AE2's issue tracker here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7857

**Comment by mezz** [comment]
Thanks for the report!
Support is added by each respective mod, so I will close this and follow the other issue.
