### ISSUE TITLE
[Bug]: Creative tabs disappearing, taking JEI recipes along with them

### ISSUE THREAD

**Issue by Corn-on-the-Orb** [mezz/JustEnoughItems#3509]
### Steps to Reproduce the Bug

I launch my modpack up normally, and when I go into the creative menu, the game freezes for a second, but when it does load the creative menu, one or several tabs are gone from the menu. 
![Screenshot 2024-05-12 040507](https://github.com/mezz/JustEnoughItems/assets/159181416/73a714ba-20fc-4362-9a6b-af5db519ed36)

### Expected Behavior

All recipes and creative tabs should be there

### Actual Behavior

Creative tabs disappear and also remove recipes, whilst the items do still exist and can be crafted or obtained in other ways. This seems to vary with the amount of RAM allocated and just between launches. Yesterday the tabs were there just fine, today they arent, I allocate more RAM and another one of the creative tabs disappear

### Mod Pack Version (Optional)

Custom

### latest.log

https://mclo.gs/xVsygDl

**Comment by nebulazorua** [comment]
any fixes?

**Comment by mezz** [comment]
Thanks for the report!
I do not think JEI looks like a cause of this problem, can please you try removing mods to see which ones are involved?

**Comment by nebulazorua** [comment]
> Thanks for the report! I do not think JEI looks like a cause of this problem, can please you try removing mods to see which ones are involved?


Once I'm back on the modpack I'll give it a look.
iirc Create has an issue with its creative tab when used with stuff like JEI, so it's likely a similar issue with another mod?
