### ISSUE TITLE
Crash when displaying Tinker's construct tool forge

### ISSUE THREAD

**Issue by InsaneJ** [mezz/JustEnoughItems#351]
Not sure if this is a JEI issue or a Tinker's issue. Also posted here: https://github.com/SlimeKnights/TinkersConstruct/issues/2239

Using jei_1.10.2-3.7.5.227 and TConstruct-1.10-2.3.3a the game crashes when displaying Tinker's tool forge.

Crash report: http://paste2.org/KPfzZkNV

**Comment by KnightMiner** [comment]
This was closed on Tinkers Construct's side as TechReborn's fault, they are putting a broken itemblock in the oreditionary

**Comment by mezz** [comment]
Thanks for the report! Glad it's being resolved.
