### ISSUE TITLE
[Bug]: Config option (wrench icon) not working in 1.16.1

### ISSUE THREAD

**Issue by Fireworkstars46** [mezz/JustEnoughItems#3510]
### Steps to Reproduce the Bug

Happens all the time.

### Expected Behavior

Should just work with regular clicking on it.

### Actual Behavior

When I click on it nothing happens

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878

**Comment by Fireworkstars46** [comment]
I'm in forge 1.16.1
