### ISSUE TITLE
[Crash]: Attempting to render null face

### ISSUE THREAD

**Issue by Secretname2009** [mezz/JustEnoughItems#3511]
### Steps to Reproduce the Crash

If Just Enough Items attempts to render any of the blocks from Tinkerers Construct then the crash will occur without fail.

### Mod Pack URL (Optional)

Custom

### Extra Notes (Optional)

Minecraft: 1.18.2
Forge 40.2.21
Affected Mods:
Just Enough Items 10.2.1.1006
Mantle 1.9.50
Tinkerers Construct 3.7.1.155

I will be available to provide more information if needed.
Im not sure if this is a bug report for either JEI or Mantle as both are mentioned in this crash. If neccesary i can go and report the bug in Mantle's Issue tracker

### Crash Report

https://gist.github.com/Secretname2009/c0f550e87608473229da78db0a37bf06

**Comment by mezz** [comment]
Thanks for the report!
JEI renders the same was as vanilla Minecraft, so please report this one to Mantle.
