### ISSUE TITLE
[Bug]: Tooltip error, see logs

### ISSUE THREAD

**Issue by TheJucon** [mezz/JustEnoughItems#3516]
### Steps to Reproduce the Bug

I don't no

### Expected Behavior

the names of the items should be there

### Actual Behavior

I don't no

### latest.log

<script src="https://gist.github.com/TheJucon/db22bb60bc29146a205fc526949a1382.js"></script>

**Comment by mezz** [comment]
Please try the latest release of JEI from today, I updated it to try to contain the damage from broken tooltips a bit better.

Duplicate of https://github.com/mezz/JustEnoughItems/issues/3432
