### ISSUE TITLE
[Suggestion]: Ability do add search-text to bookmarks

### ISSUE THREAD

**Issue by Eric-Schnitte** [mezz/JustEnoughItems#3519]
### Suggestion

Hello everyone. I'm currently back to playing some modded Minecraft, and when I am looking up recipes or trying to make a plan/overview of a project, I typically search for the name of the mod I am currently working on. However, due to the nature of modded Minecraft, I have to switch around a lot and look at different mods, which gets a little annoying. I would suggest an option to bookmark entire searches so that I can just press the bookmark with the search term for a particular mod or group of items, and it automatically searches it in JEI. Sorting options for the bookmarks would also be very nice to have.
Thank you very much!

**Comment by mezz** [comment]
Thanks for the suggestion!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/1527
