### ISSUE TITLE
Server connection crash

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#352]
<script src="https://gist.github.com/JohnKrell007/af2e0afca9bc06a1f3ea7bbeaf119406.js"></script>

I get this when running joining my server, which has the same mods.

**Comment by KnightMiner** [comment]
Do you have a crash log? You seem to have forgotten to add it. Please paste it on a site such as http://gist.github.com or http://pastebin.com and link it here.

**Comment by ghost** [comment]
I put it as a link, wierd think it was because of the link it gens.
https://gist.github.com/JohnKrell007/af2e0afca9bc06a1f3ea7bbeaf119406

**Comment by mezz** [comment]
I made a new version with better logging for this issue (3.7.5.229).  
Can you try it out and link the new log?

**Comment by ghost** [comment]
Sure, I'll have access to my PC later to test it.

**Comment by ghost** [comment]
Thanks! Turns it was crashing trying to get the name for the actually additions booklet.
Crashlog in case you can fix it. https://gist.github.com/JohnKrell007/988b1d9ce92a950120d50116545260ca

**Comment by mezz** [comment]
Cool. Try updating Actually Additions, and if that doesn't work report to them and link back here. This is almost certainly an issue on their side.
https://github.com/Ellpeck/ActuallyAdditions/issues
