### ISSUE TITLE
[Crash]: JEI crashes on launch

### ISSUE THREAD

**Issue by gamingdiamond982** [mezz/JustEnoughItems#3525]
### Steps to Reproduce the Crash

Happens when I try and launch the game.
I'm running OpenSuse Leap, with Java 21.0.3.
And minecraft version 1.20.6
I'm launching the fabric version using the prism launcher but I don't think that should have any effect.
The only other mod installed is the fabric API.

I encountered the same issue when I downgraded to 17.3.0.51.

### Extra Notes (Optional)

It's probably some fucky shit with my linux install, but I'm at a loss as to how to resolve it, a pointer in the right direction is all I'm looking for.

### Crash Report

https://gist.github.com/gamingdiamond982/cf970f55edb54826c67320123f78d75b

**Comment by mezz** [comment]
Thanks for the report!
You're trying to use an older version JEI on 1.20.6 but it's not compatible. 
I only just finished the code for JEI on 1.20.6 today, it should be released soon.
