### ISSUE TITLE
[Bug]: fail to load other items

### ISSUE THREAD

**Issue by erogrl** [mezz/JustEnoughItems#3528]
### Steps to Reproduce the Bug

whenever i open inventory it crashes and fails to load the other items, also kinda buggy and laggy, can only see some items . 
![e](https://github.com/mezz/JustEnoughItems/assets/140701114/f5548a44-67aa-4cf1-9c1f-d73734d23dd4)

### Expected Behavior

usually when i had this issue back then id reopen the entire game until the items load in perfectly , but in this case it does not work as my s/o's doesnt work either

### Actual Behavior

the crashing would  stop and all the items load in for a easier quicker crafting / ability to search for the item

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/mc-mods/jei

### Mod Pack Version (Optional)

15.3.0.4.

### latest.log

https://gist.github.com/erogrl/456facca4c682458863c3075089a2c59

**Comment by Telebaytix23** [comment]
Bro, problem fixed after deleting “Extra Compat” mod
