### ISSUE TITLE
[Crash]: Random Crash when looking at tooltips.

### ISSUE THREAD

**Issue by Dumpling00** [mezz/JustEnoughItems#3533]
### Steps to Reproduce the Crash

This doesn't seem to be JEI specific but the crash report references JEI so, I have nowhere else to turn.
This happens randomly, some times more often than others, whenever I hover on the side menu, creative tab or even container contents. It almost always seems to relate to equipment based items. I am struggling to recall a time in which it crashed on me while looking at blocks or other items, if this alone can be in any way telling.

### Mod Pack Version (Optional)

1.20.1 Fabric

### Extra Notes (Optional)

I have tried multiple times to take out mods, rebuild the modpack from scratch, divide the mods into categories and testing the tooltips after every addition. At some point it got so bad where it would literally give me this error in the first 10 seconds of looking at tooltips - then it became less obvious, until I thought it disappeared. Only now, three hours into a session, it happened again. And I'm honestly tired of wasting days trying to troubleshoot. 

Any help would be deeply deeply appreciated.
Thanks in advance.

### Crash Report

https://gist.github.com/Dumpling00/d896ae64f566515bdd8344b7a73f8a0f

**Comment by mezz** [comment]
Thanks for the report!
This seems pretty difficult to debug, I'll catch the error and add some extra info in the crash report so that you can identity which item is crashing.

**Comment by mezz** [comment]
Please try out `jei-1.20.1-fabric-15.3.0.6` and let me know how it goes.

The crash log should give you detailed information about which ingredient is crashing.

**Comment by Maxi90909** [comment]
This crash report looks very similar to mine. For forge 1.20.1. I would say this is almost identical.

**Comment by Dumpling00** [comment]
Hey there! managed to make it happen again after installing the update (thank you so much for this by the way! So here's what it says now. Is it of any help?

https://gist.github.com/Dumpling00/95fa8f4bdf838de79c14385bcce75f93

Thank you again for your time.

**Comment by mezz** [comment]
Ah this is  tough... it's a vanilla item so we didn't really gain any more information.
```
-- Ingredient --
Details:
	Name: Stone Hoe
	Mod's Name: Minecraft
	Registry Name: minecraft:stone_hoe
	Class Name: class net.minecraft.class_1799
	toString Name: 1 stone_hoe
	Unique Id for JEI (for JEI Blacklist): minecraft:stone_hoe
	Ingredient Type for JEI: class net.minecraft.class_1799
	Error Info gathered from JEI: 1 stone_hoe minecraft:stone_hoe nbt:{Damage:0}
```
I'll see if I can have JEI print the tooltip's data or something like that, so we can see what's there and track it down.

**Comment by Dumpling00** [comment]
Thank you so much. Yeah, the thing is, it just happened to be the stone hoe this time. It does it with any kind of equipment/weapon. Vanilla and non.

**Comment by Dumpling00** [comment]
Also worth mentioning I'm using the mod Tead, which replaces some vanilla recipes from the tools and weapons, but I've ruled it out as this issue happens even with Tead disabled.

**Comment by Dumpling00** [comment]
And it just happened again, this time with a modded item, but still a tool. Here's a fresh crashlog :)

https://gist.github.com/Dumpling00/9fc4657fb365b44de318f55e3e8c756a

**Comment by mezz** [comment]
I just pushed a new version with more debugging info in the crash report. 
It'll show the tooltip and try to figure out which lines from the tooltip crash.

It should be available in ~10 minutes or so on curseforge and modrinth.
Please try out `jei-1.20.1-fabric-15.3.0.7` and let me know how it goes.

**Comment by Dumpling00** [comment]
Once again thank you so much for this.
Here's the new report with possibly more info to hunt this thing down!

https://gist.github.com/Dumpling00/e3f8d9a98baf72d4ef98de9533fe1e1e

**Comment by mezz** [comment]
Hmm ok unfortunately this is extremely elusive.
The tooltip given to JEI has no issues and none of those line crash!

There is probably an event in Fabric to allow mods to add more to the tooltip at a later time, which isn't visible to JEI at all, and one of those things is what causes the crash. Either that or a mod is using a mixin to add to the tooltip later.

I am not sure how to hunt this down further, other than by removing mods that might add things to the tooltips, sorry.

**Comment by Dumpling00** [comment]
That's fair. Would it help if I gave a list of the Mods I'm using, to try and get some educated guesses?
The only things I can think of from the top of my head is stuff like Supplementaries adding the "Can be placed" to some items, Mods that add Spells, and the Ponder function from Create.

I keep my mod list clean and divided by Categories, so maybe this can hep:
[ModList Parsec.txt](https://github.com/user-attachments/files/15802174/ModList.Parsec.txt)

I do have "Clean Tooltips" installed, but that was after this issue - In fact, I hoped it would do some overrides and possibly fix it, but didn't.

**Comment by Camawama** [comment]
Same issue but on Forge. This is with the latest updates. 15.3.0.4 works fine. 
[crash-2024-06-12_21.52.15-client.txt](https://github.com/user-attachments/files/15813773/crash-2024-06-12_21.52.15-client.txt)

**Comment by mezz** [comment]
@Camawama it looks like this crash is unrelated, in your crash some other mod is trying to apply a mixin to JEI and failing because JEI has changed.
Please try to find out which mod it is by removing mods, and then report the issue to the author on their github.
