### ISSUE TITLE
[Crash]: 1.20.1 Fabric - Crash when trying to spawn item Via JEI in Creative mode.

### ISSUE THREAD

**Issue by Wolfability** [mezz/JustEnoughItems#3535]
### Steps to Reproduce the Crash

1. Be in creative mode.
2. Turn on JEI cheat mode
3. Right click an item in JEI to try and spawn it in.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/wolfs-phenomenamon

### Mod Pack Version (Optional)

1.0

### Extra Notes (Optional)

Error from client pasted below if it helps. Can spawn things from JEI in survival mode normally, just crashes when in creative. Can still use normal creative mode inventory fine as well.

The game crashed whilst mousereleased event handler
Error: java.lang.IndexOutOfBoundsException: Index 54 out of bounds for length 54

### Crash Report

https://gist.github.com/Wolfability/3fb0863676eea6c2c34120061b64c5d8

**Comment by LovGo** [comment]
Had the same problem, working fine when using java 21

**Comment by mezz** [comment]
Thanks for the report!
I am not able to reproduce this bug when only JEI is installed.
Can you try removing mods in order to figure out which one is conflicting?
I will be able to help fix the issue once you have identified which mods are involved.

**Comment by mezz** [comment]
This appears to be a duplicate of: https://github.com/mezz/JustEnoughItems/issues/3460
I will close this issue, please take discussion there
