### ISSUE TITLE
[Crash]: Hover over any item in JEI causes the game to crash. 

### ISSUE THREAD

**Issue by Bill545815** [mezz/JustEnoughItems#3539]
### Steps to Reproduce the Crash

Whilst creating my own mod pack (list of mods are in the crash report), whenever I hover over an item in JEI it crashes my game instantly. I can use the arrows to change pages, but the moment I hover over an item or the search bar the game crashes. 

### Extra Notes (Optional)

I am really hoping to get JEI to work, I just can't figure out which other mod is causing the crash. 

### Crash Report

https://gist.github.com/Bill545815/c1e78f934c39324f18773007fa822f83

**Comment by mezz** [comment]
Thanks for the report!
One of your other mods is trying to use Mixins to edit JEI's behavior but it is failing to find what it's looking for and crashing. 
Please try to identify which mod may be doing this by removing mods and seeing if the issue goes away. Once you find the mod, please report the issue to them.
