### ISSUE TITLE
[Suggestion] Pin recipes to show up first

### ISSUE THREAD

**Issue by chris61701** [mezz/JustEnoughItems#354]
Ability to pin/bookmark frequently used recipes to show up first in the list. Especially useful for batches of items you've not yet memorized.

Beyond that, maybe an individual list with pinned recipes that can be personally categorized.

**Comment by drunkripper** [comment]
Can't this be closed now as there's an entire tab dedicated to it?

**Comment by mezz** [comment]
I think it can be closed, yeah.
@chris61701 please try out the latest JEI beta and let me know if you have feedback on the ingredient bookmarks.
