### ISSUE TITLE
[Bug]: Can't configure JEI

### ISSUE THREAD

**Issue by Neekodesu** [mezz/JustEnoughItems#3541]
### Steps to Reproduce the Bug

I have the mod Configured installed, and JEI will spam that I need it on 1.20.1, it just doesn't work.

### Expected Behavior

Just clicking settings/configure

### Actual Behavior

Nothing happens, just say that I need the mod configured which I have

**Comment by Neekodesu** [comment]
I also saw comments saying the same thing, so I guess it's not me, everyone has the same bug. Have reading it since lot of time ago, so I guess this is an old bug that has never been fixed?

**Comment by audaki** [comment]
If you are using fabric, look here: https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-1435689878

**Comment by Neekodesu** [comment]
So how do I use the config on Fabric? What do I have to do. Why does this
happen since almost 2 years?

**Comment by mezz** [comment]
You can install the Configured mod. Please see my comment here: 
https://github.com/mezz/JustEnoughItems/issues/3127#issuecomment-2175217999
