### ISSUE TITLE
[Crash]: Hover Over Tagged Ingredients

### ISSUE THREAD

**Issue by Syrikal** [mezz/JustEnoughItems#3542]
### Steps to Reproduce the Crash

1. View a recipe that includes a tag, such as the Smoker (includes minecraft:logs).
2. Hover over the cycling tagged item.
3. Crash.

Using 1.20.6 NeoForge, JEI version 18.0.0.62.

### Crash Report

https://gist.github.com/Syrikal/7808c3db0a7faffc1ff2828afe00d84e

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix for this in 1.20.6 NeoForge
