### ISSUE TITLE
[Bug]: Forge 1.20.1, JEI randomly stops allowing me to left/right click to view recipes, as well as right click to clear the search bar

### ISSUE THREAD

**Issue by TheCuteCultist** [mezz/JustEnoughItems#3544]
### Steps to Reproduce the Bug

I dont know, i do believe its some button or action in game that causes it but im not sure at all.

### Expected Behavior

would work normally

### Actual Behavior

Stops working correctly, wont allow me to left or right click to view the crafting recipes, including not being able to right click to clear the search bar.

### Mod Pack URL (Optional)

(its a personal made pack)

### Mod Pack Version (Optional)

1.20.1

### Extra Notes (Optional)

I apologize this is so vague, im at a complete loss on whats causing the issue in the first place. The only way i can get it to fix itself is if i fully reload mc. And sometimes it happens like less than 5min after i rejoin the server my friend and i are oe, it gets really really tedious when i have to do it multiple times in a hour time frame. 

### latest.log

https://gist.github.com/TheCuteCultist/27d093e0f6eb69b8ea2255ad0c6cf895

**Comment by MartinElicegui** [comment]
i have the same issue, 
Maybe there is a problem with the update, which was a couple of days ago

**Comment by mezz** [comment]
Thanks for the report!
Does this happen when JEI is the only mod installed?

**Comment by TheCuteCultist** [comment]
I havent been able to get the issue to reproduce, (since i reported it i have yet to have it happen again)

ill try to test it more in the upcoming days ^^
