### ISSUE TITLE
Crash with Waystones Fabric 1.21[Bug]: 

### ISSUE THREAD

**Issue by Shadowpudding** [mezz/JustEnoughItems#3546]
### Steps to Reproduce the Bug

Launch the game with JEI, Waystone[Fabric Edition] and its Lib Balm

### Expected Behavior

The game should launch without issues

### Actual Behavior

The game crashes before loading

### latest.log

https://gist.github.com/Shadowpudding/2abd02d251a8f3ad85734ca9b4cce5bb#file-gistfile1-txt

**Comment by arsic-kali** [comment]
also experieincing this, error code more specifically states:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'jei'!

Running on Fabrice 1.21 loader with Waystones 1.21

**Comment by Darkslategray-lgtm** [comment]
Same problem

**Comment by BlayTheNinth** [comment]
Fixed in Waystones

**Comment by mezz** [comment]
https://github.com/TwelveIterationMods/Waystones/issues/852
