### ISSUE TITLE
[Bug]: Missing items in search

### ISSUE THREAD

**Issue by Unleashed75** [mezz/JustEnoughItems#3547]
### Steps to Reproduce the Bug

Using Fabric loader 1.21 - 0.15.11
install mods;
fabric-api-0.100.1+1.21
jei-1.21-fabric-19.0.0.1
modernfix-fabric-5.18.2+mc1.21

In a new world where you are in creative, open inventory.
In the tab for searching items, search for Lightning Rod. (It wont show up)

### Expected Behavior

I expected to see Lightning Rods in the search results.
(Unknown if other items are missing from searches)

### Actual Behavior

I did NOT see Lightning Rods in the search results.
(Unknown if other items are missing from searches)

### Extra Notes (Optional)

With both JEI and ModernFix installed, searching for Lightning Rod in the creative tab does not show up.
With either or both JEI or ModernFix is not installed things work normally.
Unsure which mod has the issue, so I am reporting to both.

FYI, Lightning Rod does show in the JEI search, but not in the Vanilla Creative Tab Search

### latest.log

https://gist.github.com/Unleashed75/baabc1364f16110eb60a9a41fa4ccf8c

**Comment by mezz** [comment]
Thanks for the report!
I see you reported it to ModernFix here: https://github.com/embeddedt/ModernFix/issues/425
Please link related issues together.

I think this is most likely not a problem with JEI. I will follow the other issue and close this one.
