### ISSUE TITLE
Missing version "1.20.3" and forge

### ISSUE THREAD

**Issue by Studiotaco** [mezz/JustEnoughItems#3549]
### Other

I wanted to get this mod because I'm new to minecraft and I wanted a little help but i can't get it for the version I'm running. Please fix ,thanks.

~I use forge

**Comment by Leclowndu93150** [comment]
skip 1.20.3 there is no point in playing it

**Comment by mezz** [comment]
Please use one of the other versions available, there isn't much support for 1.20.3.
1.20.1 and 1.20.6 may be better choices.
