### ISSUE TITLE
[Question/Suggestion] And

### ISSUE THREAD

**Issue by Dijkstra1-zz** [mezz/JustEnoughItems#355]
When I search something, I can use '@' to search meta data i.e. mod name '|' to search this or that, but how do search for this and that e.g. '@mod name && ore' would list item for that only items with contains char sequence 'ore' and the meta data contains the char sequence of the mod name. If the exits what is the operator that represent and, and if dose not exits can it been.

**Comment by mezz** [comment]
You can just type `@mod ore`. Every space is treated as an "and". This is different from how NEI did it.

**Comment by Dijkstra1-zz** [comment]
Thanks did not know been using JEI for about two days, any other operators i should know about, I assume '|' is or like in NEI, I know '@' at least searches mod names, I am assume does the mata data as well, but yes I am used to NEI, the only thing I really miss filters.

**Comment by mezz** [comment]
No problem. @ is only for mod name.
You can find the search operators here under "Search" and "Advanced Controls/Advanced Search" sections:
http://minecraft.curseforge.com/projects/just-enough-items-jei
