### ISSUE TITLE
[Bug]: Anvil Screen GUI in JEI seems to use Smithing Table format.

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [mezz/JustEnoughItems#3550]
### Steps to Reproduce the Bug

1. Install `jei-1.21-neoforge-19.0.0.2.jar`
2. load up game
3. look at anvil uses/recipes

### Expected Behavior

not an extra slot

### Actual Behavior

![image](https://github.com/mezz/JustEnoughItems/assets/132615999/f75d1913-324d-49a2-b7a1-6532c631eeb5)
this is what happens

### Mod Pack Version (Optional)

19.0.0.2 neoforge

### latest.log

https://gist.github.com/Kazuhiko-Gushiken/c78945456a1307521f1049ec5580e867

**Comment by mezz** [comment]
Thanks for the report!
