### ISSUE TITLE
[Bug]: Network errors on NeoForge 1.21

### ISSUE THREAD

**Issue by desht** [mezz/JustEnoughItems#3551]
### Steps to Reproduce the Bug

* Install JEI on a dedicated server
* Connect, and ctrl-click the wrench button to enable cheat mode
* Although the button turns red, the server logs an error, stacktrace: https://gist.github.com/desht/32b436583a688bbbd5136f563dac6240
* Attempt to pick an item in cheat mode
* Very similar error is logged and items cannot be picked

### Expected Behavior

No network errors :stuck_out_tongue: 

### Actual Behavior

See reproduction steps above

### Extra Notes (Optional)

JEI 19.0.0.3 on NeoForge 21.0.16-beta

**Comment by mezz** [comment]
Thanks for the report!
Looking into it
