### ISSUE TITLE
[Bug]: JEI doesn't show smithing recipes with no template (neo 1.21)

### ISSUE THREAD

**Issue by Leclowndu93150** [mezz/JustEnoughItems#3552]
### Steps to Reproduce the Bug

![image](https://github.com/mezz/JustEnoughItems/assets/73310949/fa09de99-89ba-4c6a-a02c-3f7b35c81b19)

### Expected Behavior

![javaw_PCdV3WFfDm](https://github.com/mezz/JustEnoughItems/assets/73310949/7b1fd6a0-32d7-4e53-a2cc-ba7c1ecd8621)

### Actual Behavior

doesn't show smithing recipes with no template

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a changed, and JEI will display incomplete smithing recipes now.
