### ISSUE TITLE
[Other]: [ne.ne.ne.ne.re.NetworkRegistry/]: Tried to send jei_to_client:cheat_permission packet to a client that does not support it. Not sending the packet.

### ISSUE THREAD

**Issue by Urahana** [mezz/JustEnoughItems#3554]
### Other

im trying to use jei cheat mode in my server and its not working and i saw this on my server log, what is this and how to solver it?

**Comment by mezz** [comment]
Thanks for the report! 
Unfortunately there is not enough information in this bug report for me to identify the problem.
Please open a new issue using the bug template so that I can help you:
https://github.com/mezz/JustEnoughItems/issues/new?template=bug.yml&title=%5BBug%5D%3A+
