### ISSUE TITLE
[Bug]: specialized maps do not appear

### ISSUE THREAD

**Issue by Danielville7777** [mezz/JustEnoughItems#3557]
### Steps to Reproduce the Bug

Villager maps like ocean explorer maps do not appear when map is searched and only the base type of map appears 

![image_2024-06-23_115736962](https://github.com/mezz/JustEnoughItems/assets/156787923/b1453ae6-f531-4fd9-8939-b99baf293008)

### Expected Behavior

When typing "map"  into the search bar the following items would appear: 
- Map
- Ocean Explorer Map
- Woodland Explorer Map
- Treasure Map

### Actual Behavior

When typing "map"  into the search bar the following items appear: 
- Map

**Comment by mezz** [comment]
Thanks for the report!
JEI only displays what is in the creative menu, are those items available there?
