### ISSUE TITLE
[Crash]: Crash on launch on new 1.21 Neoforge update

### ISSUE THREAD

**Issue by ffuentesm** [mezz/JustEnoughItems#3558]
### Steps to Reproduce the Crash

Launch Minecraft on Neoforge-21.0.30
Jei: jei-1.21-neoforge-19.0.0.9.jar 

The game does not crash if you use Neoforge-21.0.24

### Crash Report

https://pastebin.com/S7qZipbt

**Comment by SnorHook** [comment]
I am also experiencing this issue when I created a new world

**Comment by francodl20** [comment]
I got this issue too, I can provide the crash report if its needed

**Comment by mezz** [comment]
Thanks for the report!
This breaking change in the NeoForge beta caused the crash in JEI: <https://github.com/neoforged/NeoForge/pull/1137>
I have fixed the issue in the latest version: https://github.com/mezz/JustEnoughItems/commit/bc302a493ac60a3ef7ad1860c4dd7d6aa304fdcc
