### ISSUE TITLE
[Bug]: Error mensage

### ISSUE THREAD

**Issue by ImSinhue** [mezz/JustEnoughItems#3559]
### Steps to Reproduce the Bug

Well, when I go through certain pages the jei gets buged and everything shows as an error, it doesn't show the crafts well, just an error. 
![11d32925-8c3d-4add-b7e5-38db707cc8fb](https://github.com/mezz/JustEnoughItems/assets/61761533/5db7dcd6-dc07-41dc-baae-7d7011b52961)

### Expected Behavior

I pass pages are buggy and no longer go it just shows error

### Actual Behavior

Nothing only shows error

**Comment by thakyZ** [comment]
To help the dev with fixing this issue, provide which mod pack or list of mods, plus Minecraft version and Forge/Fabric/Neoforge/Quilt or whatever mod loader version you are using (while specifying a which mod loader as well). Also adding a log would be helpful, but with what you have posted there is next to nothing that the dev can do. The dev can only fix it if they or someone else encounters the same issue and provides more information.
