### ISSUE TITLE
Refined search results

### ISSUE THREAD

**Issue by Dijkstra1-zz** [mezz/JustEnoughItems#356]
If search for drum with extra utils 2 installed, I get many pages of different tier of drum each with different liquid in, when I only want to see empty drums to craft. In cheat mode I may cheat drum of said liquid, but then i search for say lava and drum.

**Comment by shadowfacts** [comment]
If what you want is the filled drums to be hidden, it is up to XU2 to do that.

**Comment by VT-14** [comment]
Mod Config options tend to only be on or off.  You can see all of the different fluids for each liquid container, or you can only see the empty one.  It's also slightly tedious to go through every mod that adds tanks and defaults to show all and turn those off.

I can't think of many applications for this other than Cheat mode.

Perhaps there could be an 'empty' keyword to express a lack of fluid? ("Empty Drum")

**Comment by mezz** [comment]
I think this is a request for Extra Utilities.
You can report here: https://github.com/rwtema/extrautilities/issues
