### ISSUE TITLE
[Bug]: Synced registries aren't available for JEI via RegistryUtil at startup

### ISSUE THREAD

**Issue by Tslat** [mezz/JustEnoughItems#3562]
Call RegistryUtil.getRegistry(Registries.ENCHANTMENT) at `onRuntimeAvailable`

It'll NPE

https://discord.com/channels/166630061217153024/418125698486632448/1255118518253256715

**Comment by mezz** [comment]
Thanks for the report!
I am not able to reproduce this issue, I tried to trigger it with my debug plugin but it worked fine.
![Screenshot 2024-07-01 at 4 44 39 PM](https://github.com/mezz/JustEnoughItems/assets/916092/35fcce77-7ee2-4541-87e0-cae58f6f14f2)

Can you please give more detailed steps to reproduce the problem?
Which loader are you using?
Are you connecting to a dedicated server, or are you doing this in singleplayer?

**Comment by Tslat** [comment]
FFS

Intellij swapped out my import - I was using a legacy class with the same name and method signature and I didn't even notice lol

Sorry, false alarm
