### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by darthvader45** [mezz/JustEnoughItems#3563]
### Steps to Reproduce the Bug

1. Hit the 'view recipes' keybind while hovering over anything that can be traded to a villager.
2. Click the 'Villager Trading' icon (the three emeralds)
3. See that the villager texture in the entity window is missing.

### Expected Behavior

The villager displayed should have their respective texture.

### Actual Behavior

The villager is missing a texture.

### latest.log

https://gist.github.com/darthvader45/9715e807dc07808d706431dfdb9819ab

**Comment by mezz** [comment]
Thanks for the report!
Villager trade recipes are added by another mod, they are not included in JEI directly.
Please report this issue to JER (Just Enough Resources): https://github.com/way2muchnoise/JustEnoughResources/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

**Comment by darthvader45** [comment]
Thank you, reported.
