### ISSUE TITLE
[Suggestion]: Add Java Docs

### ISSUE THREAD

**Issue by wolfieboy09** [mezz/JustEnoughItems#3565]
### Suggestion

When working on a mod that uses JEI for the screens and everything, there are no Java Docs. Java docs are straightforward to add, and tell the user what the function does, and how to use it.

**Comment by mezz** [comment]
Hello, JEI has java docs for every API method. Please make sure your IDE is configured to download the sources correctly.
For example: https://github.com/mezz/JustEnoughItems/blob/68f16606165b2118b493ee98847fdd00952702c0/CommonApi/src/main/java/mezz/jei/api/IModPlugin.java#L20-L23

**Comment by wolfieboy09** [comment]
Huh. I use IntelliJ, and I don't see anything with IModPlugin

![image](https://github.com/mezz/JustEnoughItems/assets/105564186/1cb71864-f68c-4d22-9213-650d764b68fe)

**Comment by wolfieboy09** [comment]
![image](https://github.com/mezz/JustEnoughItems/assets/105564186/30ca7c73-ed76-47d9-8ab2-e58e2fdf5228)
I just found that button, and it works. No idea why it did not do that in the first place.
