### ISSUE TITLE
[Suggestion]: Include examples in the Wiki

### ISSUE THREAD

**Issue by wolfieboy09** [mezz/JustEnoughItems#3566]
### Suggestion

Small examples in the Wiki to guide the user on what each function does and what it could look like.

**Comment by mezz** [comment]
Thanks for the suggestion!
I think the best examples are from the Vanilla plugin built into JEI, and other open source mods.
It is difficult to keep a wiki updated with working code, but the Vanilla plugin is always going to have up-to-date code in order for it to work.
Please find it here: https://github.com/mezz/JustEnoughItems/tree/3b2ff3a2659f4bc1b684677c219c686ff373a30f/Library/src/main/java/mezz/jei/library/plugins/vanilla
