### ISSUE TITLE
[Bug]: Error during loading 1.20.4 NeoForge in the 2 latest versions of the mod

### ISSUE THREAD

**Issue by Dinocraft1515YT** [mezz/JustEnoughItems#3568]
### Steps to Reproduce the Bug

Install:
- JEI latest version
- Vampirism or ElementalCraft
Launch the game, and you'll see this:
![2024-06-28_21 48 43](https://github.com/mezz/JustEnoughItems/assets/120250129/cb3f753a-9ffb-4f25-b399-4aa56d6de8cf)

### Expected Behavior

The version number is malformed, as you can see here, the version number somehow decreeses, instead of increase

![image](https://github.com/mezz/JustEnoughItems/assets/120250129/7c3928b8-7a57-4a67-bb4e-c40f2c528d49)

### Actual Behavior

The game will not be playable if you don't downgrade JEI to 17.3.0.56, minim

**Comment by mezz** [comment]
Thanks for the report!
This is my mistake, I'll bump the minor version on 1.20.4 to fix it.
