### ISSUE TITLE
[Suggestion] Combine items

### ISSUE THREAD

**Issue by MysticAura** [mezz/JustEnoughItems#357]
I'm coming across many items from mods which have a ton of listings in JEI, but the same recipe, or clicking on one provides the recipes for all the different types. It would be very nice to be able to only show one of each of these items in JEI. For example one of each tier of Extra Utilities Drum instead of 1/3 of a page taken up by each drum type.  Silent's Gem's tools and armor would be another such case.  These situations occur mostly when the items share the same meta and id as each other; making it impossible currently to just hide without all of them being hidden.

**Comment by mezz** [comment]
I think this is the same request as this issue: https://github.com/mezz/JustEnoughItems/issues/356
You can ask those mods to limit what they put in the creative list, or ask for names that are easier to search. There's no real reason for them to add every variant to the creative list.
