### ISSUE TITLE
[Bug]: "Connection Lost / Network Protocol Error"

### ISSUE THREAD

**Issue by PJRamaglia** [mezz/JustEnoughItems#3570]
### Steps to Reproduce the Bug

Launching a fresh game client from MultiMC and then join my local server without issue.  Disconnect from the server and return to the client main menu.  All attempts to reconnect/rejoin the server (from the second time and subsequent attempts) and I receive a "Connection Lost / Network Protocol Error" error message.
![image](https://github.com/mezz/JustEnoughItems/assets/3131378/3f0eea78-08e3-46db-8a4c-d973f0123640)

### Expected Behavior

I should be able to rejoin the server without being kicked back to the multiplayer server list screen.

### Actual Behavior

Unable to rejoin the server.  Majority of the actual behavior was described in the "Steps to Reproduce the Bug" section.  I have noticed that when I quit the client and then relaunch a fresh session I'm able to rejoin my local server without issue.

### Mod Pack URL (Optional)

N/A

### Mod Pack Version (Optional)

N/A

### latest.log

https://gist.github.com/PJRamaglia/3f40e5cb9d746bdb12d9c9b15f41da05

**Comment by mezz** [comment]
Thanks for the report!
This was caused by a breaking change in the NeoForge beta: https://github.com/neoforged/NeoForge/pull/1194
I will submit a fix for JEI shortly.

**Comment by cheddar98** [comment]
Hi, I am having this same problem but it's not on NeoForge, it's on Fabric. Was wondering what was going on.

[disconnect-2024-07-20_23.03.37-client.txt](https://github.com/user-attachments/files/16322958/disconnect-2024-07-20_23.03.37-client.txt)

**Comment by mezz** [comment]
Hi @cheddar98, sorry this one's actually a bit different. 
Please open a new issue and include your `latest.log` so that I can investigate what's wrong.
