### ISSUE TITLE
[Crash]: NullPointerException: vanilla crafting category

### ISSUE THREAD

**Issue by Phoupraw** [mezz/JustEnoughItems#3573]
### Steps to Reproduce the Crash

1. Enter a world
2. Server crashed and client disconnected

### Extra Notes (Optional)

Without JEI, with EMI only, game runs normally. Maybe some mod adds a recipe with missing category?

### Crash Report

https://gist.github.com/Phoupraw/dcd599a363aaa2be659dde7e43704eab

**Comment by wolfieboy09** [comment]
You're using Meteor Client, that's a hacked client...

**Comment by Phoupraw** [comment]
Oh, thanks for reminding me of that. Meteor is too invasive to be compatible with other mods. I have disabled it and now JEI works fine. I'll make my own mod to replace the functions of meteor.
