### ISSUE TITLE
JEI crash on startup

### ISSUE THREAD

**Issue by BenBendy0** [mezz/JustEnoughItems#3576]
everytime i try to load minecraft, it crashes and pops up with this message:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'jei'!

here's the full log:

https://gist.github.com/BenBendy0/ae06ade65ed9ce96e8f0fbb7c74d428a

**Comment by mezz** [comment]
Resolved here: https://github.com/mezz/JustEnoughItems/issues/3577
