### ISSUE TITLE
Jei crash on startup

### ISSUE THREAD

**Issue by BenBendy0** [mezz/JustEnoughItems#3577]
### Steps to Reproduce the Crash

everytime i try to load minecraft, it crashes and pops up with this message:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'jei'!

here's the full log:

https://gist.github.com/BenBendy0/ae06ade65ed9ce96e8f0fbb7c74d428a

### Crash Report

https://gist.github.com/BenBendy0/ae06ade65ed9ce96e8f0fbb7c74d428a

**Comment by embeddedt** [comment]
@mezz This is my fault (I removed my plugin and forgot that Fabric requires updating the mod json), but it would probably be worthwhile to catch a `ClassNotFoundException` when initializing plugins on Fabric and avoid the crash, at least outside of dev.

**Comment by mezz** [comment]
Thanks for the report!
@embeddedt I wouldn't count this as your fault really. You have the right idea, this should normally be caught and logged. I'll work on a quick fix.

**Comment by BenBendy0** [comment]
> @mezz This is my fault (I removed my plugin and forgot that Fabric requires updating the mod json), but it would probably be worthwhile to catch a `ClassNotFoundException` when initializing plugins on Fabric and avoid the crash, at least outside of dev.

Thanks, it now works in the latest update

**Comment by mezz** [comment]
I added some protections against this happening again, so JEI will just log an error instead of crashing.
