### ISSUE TITLE
[Crash]: IllegalArgumentException: Unknown ingredient type: class net.minecraft.class_1799

### ISSUE THREAD

**Issue by Phoupraw** [mezz/JustEnoughItems#3578]
### Steps to Reproduce the Crash

1. Enter a world
2. Server crashed and client disconnected

### Extra Notes (Optional)

This crash can't be triggered stably. After the game launches, I have enter and quit world for 2~3 times to trigger this bug.

In addition, #3573 can happen without meteor. I am not sure if there is relationship.

### Crash Report

https://gist.github.com/Phoupraw/3bd0787e79031c9a50d2ffcfd9f3f057

**Comment by mezz** [comment]
Thanks for the report!

`class_1799` is ItemStack so it should be registered.
Please provide your full client log so that I can see if something in JEI is breaking earlier and preventing this basic function from working.

**Comment by Phoupraw** [comment]
I can't find that log (wth mc saves logs) and can't trigger this crash now. I am trying.

**Comment by Phoupraw** [comment]
I successfully reproduced it, with fewer mods.
[disconnect-2024-07-05_18.26.50-client.txt](https://github.com/user-attachments/files/16108512/disconnect-2024-07-05_18.26.50-client.txt)
[latest.log](https://github.com/user-attachments/files/16108516/latest.log)

**Comment by Phoupraw** [comment]
I triggered it twice again.
[disconnect-2024-07-05_18.55.29-client.txt](https://github.com/user-attachments/files/16108784/disconnect-2024-07-05_18.55.29-client.txt)
[disconnect-2024-07-05_18.55.22-client.txt](https://github.com/user-attachments/files/16108785/disconnect-2024-07-05_18.55.22-client.txt)
[latest.log](https://github.com/user-attachments/files/16108787/latest.log)

**Comment by Phoupraw** [comment]
First time I enter a world, it doesn't error. Once I run `/reload` or `/datapack disable`, server crashes.

**Comment by mezz** [comment]
Thanks for the info!
Unfortunately there are an incredible number of errors in the log.
What client are you using?

Please try removing mods to see which one is causing a conflict. Maybe you can start by seeing if this issue occurs with just JEI installed.

**Comment by Phoupraw** [comment]
I triggered another exception with fewer mods, but I forgot to save the log...
[disconnect-2024-07-07_21.37.03-client.txt](https://github.com/user-attachments/files/16119522/disconnect-2024-07-07_21.37.03-client.txt)
[disconnect-2024-07-07_21.40.11-client.txt](https://github.com/user-attachments/files/16119523/disconnect-2024-07-07_21.40.11-client.txt)

**Comment by sdlgcorp** [comment]
iI have the same problem and here is my information 
[disconnect-2024-06-29_19.05.30-client.txt](https://github.com/user-attachments/files/16120722/disconnect-2024-06-29_19.05.30-client.txt)

**Comment by mezz** [comment]
Sorry I will need the client log in order to understand what is happening here.
Can you please try removing mods to see if there is a conflict, or if this occurs with JEI alone?

**Comment by sdlgcorp** [comment]
my client log is fabric i guess, and when it is alone the JEI mod does not fail, but I add whatever mod and it fails

**Comment by mezz** [comment]
Are you using a hacked or alternative client?

**Comment by Phoupraw** [comment]
[disconnect-2024-07-09_17.41.09-client.txt](https://github.com/user-attachments/files/16141487/disconnect-2024-07-09_17.41.09-client.txt)
[latest.log](https://github.com/user-attachments/files/16141489/latest.log)
