### ISSUE TITLE
[Crash]:  Jei 1.20.1 is not generating required jei-server.toml file

### ISSUE THREAD

**Issue by MakingStuffandThings** [mezz/JustEnoughItems#3579]
### Steps to Reproduce the Crash

1. open minecraft 
2. select desired modded world 
3. click play
 you are now stuck in the "Reading world data" screen
 

### Crash Report

https://gist.github.com/MakingStuffandThings/3b6aedfa17a184777fc61eea0cfdc17a

**Comment by mezz** [comment]
Thanks for the report!
This config file is managed by minecraft forge, [please report the issue to them here](https://github.com/MinecraftForge/MinecraftForge/issues) to get it resolved, and please link back to this issue.
