### ISSUE TITLE
[Bug]: Creative menu search is broken

### ISSUE THREAD

**Issue by Copper-Furred-Fox** [mezz/JustEnoughItems#3580]
### Steps to Reproduce the Bug

1) Open a creative 1.21 game with JEI installed
2) try to search for something in the creative menu (not the JEI menu), eg cobblestone

### Expected Behavior

Should show the results for what was input

### Actual Behavior

In the newest version nothing happens, in the second newest it shows unusual results (for example "water" shows sea grass and non solid alive coral blocks)

### latest.log

https://gist.github.com/Copper-Furred-Fox/f891630c346242c88d6b49008084a959

**Comment by mezz** [comment]
Thanks for the report!
I am not able to reproduce this issue with only JEI. 
JEI does not impact the creative menu or any vanilla code in general. 

Your logs show other mods are installed, like `modernfix`. 
Please try removing mods to see which one is causing the problem.

![2024-07-05_11 43 20](https://github.com/mezz/JustEnoughItems/assets/916092/8cbfc3fe-22e5-4157-aa69-5308ae932a45)
