### ISSUE TITLE
[Bug]: [Fabric 1.20.2] Not working in hypixel mulitplayer

### ISSUE THREAD

**Issue by Hifei1007** [mezz/JustEnoughItems#3581]
### Steps to Reproduce the Bug

1. Join a SMP
2. You will see JEI isn't working.

### Expected Behavior

JEI should work in mulitplayer.

### Actual Behavior

Nothing happens.

### Extra Notes (Optional)

Note: JEI will work after joining a single player world.

### latest.log

https://gist.github.com/Hifei1007/465e885f0b45204e1c370057ed280ba5

**Comment by Hifei1007** [comment]
This issue only found in servers like mc.hypixel.net

**Comment by ForgenDT** [comment]
I also tested it, and it seems to work when it's a vanilla server, whether in single-player or multiplayer.
However, since Hypixel has its own type of server, it seems to cause issues.
and I tested in 1.21

**Comment by Hifei1007** [comment]
I don't know why hypixel's server will disable a jei in client

**Comment by mezz** [comment]
Thanks for the report!
Even if JEI doesn't start normally, it should be able to do a "late start" when you open a GUI in the game.
I'm not sure what's different about hypixel. Is the minecraft client still the normal one?

**Comment by ForgenDT** [comment]
Personally, I reproduce the problem with the official launcher, and just with JEI without any other mod so as not to distort the result.
I just tested on about ten servers and it seems to be linked to the bungeecord version of hypixel

**Comment by mezz** [comment]
What results did you find? It's unclear to me what worked or didn't work.

**Comment by ForgenDT** [comment]
if you mean logs, i don't have any to provide since nothing loads. the only thing i can say is that JEI runs on different servers except hypixel. either it's a problem with bungeecord, or it's just the hypixel version that's causing it.
I don't have the skills to make modifications to the JEI loader, sorry, I can't help more than that.
