### ISSUE TITLE
[Suggestion]: The ability to bookmark a row of recipe

### ISSUE THREAD

**Issue by castilio20** [mezz/JustEnoughItems#3583]
### Suggestion

right now with jei you cant bookmark a row a recipe it gets weird i asume it bc you can unbookmark a recipe from the right side wich mess with that and i would hope if we can get a improvmenmt
this is with jei

https://github.com/mezz/JustEnoughItems/assets/76228548/906315ac-73db-4b63-baa8-ad2ac3a92b73

this is how it looks with like other jei like mod witch feels more clean and better bc you cant unbookmark a recipe by mistake from the right side
(aka emi)

https://github.com/mezz/JustEnoughItems/assets/76228548/f0f9d1a0-ea20-465a-a5a9-af0c51cbfee4

**Comment by wolfieboy09** [comment]
So the ability to unbook mark stuff?

**Comment by castilio20** [comment]
tehnic  removing the ability that lets you  unbookmark from the ride side side i think wich mess with mass bookmark like you can see in the video jei try to bookmark and unbookmark the recipe you cant rlly do mass bookmark recipe
if you look in the sec video with a diferent recipe view you can bookmark a row a recipe more ez
