### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Tubeclasher** [mezz/JustEnoughItems#3588]
### Steps to Reproduce the Crash

Open your Inventory

### Mod Pack URL (Optional)

a custom made one without a page, sorry

### Extra Notes (Optional)

I just opened my inventory, I am pretty sure the problem is some mod but I am simply unsure which mod it could be, if you could provide some help with that I'd be very thankful and if you cannot then I am sorry for wasting your time

### Crash Report

https://gist.github.com/Tubeclasher/9af0fe52bd9084dda16484e7d667e6fa

**Comment by Jhwx** [comment]
Try disabling the Destroy. I was having the same issue and disabling that Create addon fixed it for now.
