### ISSUE TITLE
[Crash]: The game crashed whilst rendering screen

### ISSUE THREAD

**Issue by NotAUser-1059** [mezz/JustEnoughItems#3590]
### Steps to Reproduce the Crash

Unsure, seems to happen randomly
Edit: A way I found to force it to crash is:
Search "lava" in the TMI menu
Right-click to show ways it can be used
Hover over the lava in the first shown menu

Another way I found to cause the same crash:
Search "*"
Hover over the first result

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/steam-punk

### Mod Pack Version (Optional)

V24

### Extra Notes (Optional)

In the crash report, it says that it could also be caused by "Cold Sweat" but the crash usually happens when I'm in the middle of using JEI

### Crash Report

https://gist.github.com/Banana1059/ab80d49ec66f9ac1ebc1dd27bad8be41

**Comment by mezz** [comment]
Thanks for the report!
This is an issue caused by another mod, reported here: https://github.com/Momo-Softworks/Cold-Sweat/issues/303
The problem is coming from the mod's tooltip handler, not from JEI directly.
