### ISSUE TITLE
[Crash]: Mixin error with @shadow field recipeLayours

### ISSUE THREAD

**Issue by Mysticpasta1** [mezz/JustEnoughItems#3593]
### Steps to Reproduce the Crash

1. load mod
2. open menu

### Extra Notes (Optional)

Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field recipeLayouts was not located in the target class mezz.jei.gui.recipes.RecipesGui. No refMap loaded.

it crash with a custom unreleased modpack I just made today

### Crash Report

https://gist.github.com/Mysticpasta1/a3a98ae236e7f0ddfcb6f38e1aa79b93

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue from Just Enough Mekanism Multiblocks. They are trying to edit JEI's code using mixins and failing.

Please report to them here and link back to this issue.
https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues
