### ISSUE TITLE
[Crash]: Crashes on mouseover to jei item list

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [mezz/JustEnoughItems#3594]
### Steps to Reproduce the Crash

1. launch game
2. join game
3. open bag
4. move morse to item list

### Crash Report

https://mclo.gs/dcDJmJc

**Comment by mezz** [comment]
Thanks for the report!
This is caused by `destroy` and has been reported to them and fixed here: https://github.com/petrolpark/Destroy/issues/396
