### ISSUE TITLE
[Bug]: JEI only showing fluids

### ISSUE THREAD

**Issue by tvas27** [mezz/JustEnoughItems#3598]
### Steps to Reproduce the Bug

Press E ( open the inventory)

### Expected Behavior

The menu would show all of the items as normal

### Actual Behavior

The JEI menu only show fluids from Minecraft, Mekanism, Mekanism Generators and Sophisticated Core

### Extra Notes (Optional)

Im not using a modpack, just downloaded a few bunch of mods for a singleplayer world
![image](https://github.com/user-attachments/assets/af0e5423-ee85-4165-8087-a0c644677002) (the mod list)
I already tried excluding the JEI files from the config paste, changing version of the mod, messing with thing i dont know to explaing (the paste of ingredient list mod order sort)
NOTE: Sorry if my english is bad, far from a native speaker

### latest.log

https://gist.github.com/tvas27/9528556a7200d26a7f2aca3ca0d503f9

**Comment by mezz** [comment]
Thanks for the report!
It looks like the mod "Alex's Delight" is doing something to the creative tabs that is causing them to be broken, so JEI is unable to find any items.
Please try removing the mod and see if the error goes away.

**Comment by tvas27** [comment]
wow mezz thank you very much, it now work perfectly. sorry for the late answer, bc i went to a family trip.

**Comment by mezz** [comment]
Great, glad it's fixed!

**Comment by JW2019MK** [comment]
I'm having this same issue on my aternos server. It only seems to happen on the server and not my singleplayer worlds however. Does anyone know why this is and maybe how to fix it?

**Comment by vTurnip** [comment]
This is also happening for my friend on my server but it's not happening for me. Very odd

**Comment by RamenNoodle101** [comment]
Hi vTurnip
