### ISSUE TITLE
Crash With Butterfly Mania installed

### ISSUE THREAD

**Issue by sweetsosweet** [mezz/JustEnoughItems#36]
I got this crash when I tried JEI for the first time. I'm using the 1.8 version:

http://pastebin.com/LLPUgLah

**Comment by mezz** [comment]
Thanks for trying it out and for the report! I'll try it out now and find out what's happening.

**Comment by mezz** [comment]
Fixed in the latest version for 1.8, it'll be up here shortly: 
http://minecraft.curseforge.com/projects/just-enough-items-jei/files
