### ISSUE TITLE
[Crash]: Crash on world load

### ISSUE THREAD

**Issue by MuteTiefling** [mezz/JustEnoughItems#3600]
### Steps to Reproduce the Crash

1. Open a world

### Crash Report

https://gist.github.com/MuteTiefling/8ee63b6a1213ef66e455eab8de8f7ac9

**Comment by mezz** [comment]
Thanks for the report!
This is caused by https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/12

duplicates issue: https://github.com/mezz/JustEnoughItems/issues/3593

**Comment by MuteTiefling** [comment]
Ah, my bad. thanks for looking into it just the same!
