### ISSUE TITLE
[Crash]: Crash on world load attempt

### ISSUE THREAD

**Issue by Phosphonothioic** [mezz/JustEnoughItems#3601]
### Steps to Reproduce the Crash

Just updated JEI in Curseforge for 1.20.1. Clicked to start world...dumped to desktop.

### Crash Report

https://gist.github.com/Phosphonothioic/8a038e67acc7bbb87665b0443e4a9afb

**Comment by mezz** [comment]
Thanks for the report!
This is caused by https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/12

duplicates issue: https://github.com/mezz/JustEnoughItems/issues/3593
