### ISSUE TITLE
[Bug]: Pages associated with enchanted books cannot be accessed with any key binds in MC 1.20.6

### ISSUE THREAD

**Issue by Phylogeny** [mezz/JustEnoughItems#3602]
### Steps to Reproduce the Bug

Press `U` while hovering over an enchanted book in the player's inventory.

### Expected Behavior

The usage of the enchanted book should be displayed.

### Actual Behavior

Nothing happens.

### Mod Pack URL (Optional)

N/A

### Mod Pack Version (Optional)

N/A

### Extra Notes (Optional)

This bug is present in neoforge-20.6.119 and absent in neoforge-20.4.237 and neoforge-21.0.83-beta (no other versions checked). Enchanted books still have usage pages, but they cannot be accessed by pressing `U`, and can only be accessed by scrolling through all usage pages. When adding info pages for enchanted books with a plugin, pressing either `U` or `R` should result in the info being displayed, but again nothing happens, and the info pages can only be accessed by scrolling through all info pages. Since it's the same story with both usage and info pages, I imagine it would also the same with recipe pages if an enchanted book were to be used in a recipe. Also, clicking on items found in other usage/recipe pages should display that item's usage/recipe pages, but this also doesn't happen with enchanted books. As far as I can tell, this errant behavior is only present with enchanted books.

### latest.log

https://gist.github.com/Phylogeny/30f277cd16a17cbb8f822b04b2827d05

**Comment by mezz** [comment]
Thanks for the report!
Confusingly, 1.20.6 is not a generally supported version by most mods. I only implemented a version for it as a quick stepping stone to 1.21.
Please try version 1.20.1 or 1.21 and let me know if you have the same problem.

**Comment by Phylogeny** [comment]
I previously tested it in 1.20.4 (neoforge-20.4.237) and 1.21 (neoforge-21.0.83-beta) and it works fine, so it's likely fine in 1.20.1 as well. Also, I should be sure to update my plugin to a lower version than 1.20.6 if it's not very popular (I just came back to modding after a while and simply assumed 1.20.6 was the popular 1.20 version). If you don't mind, which version of 1.20 is the go-to version right now?

**Comment by mezz** [comment]
:+1: 1.20.1 is the goto for 1.20.x right now
