### ISSUE TITLE
[Crash]: Crash When Loading Terrain After Mod Update

### ISSUE THREAD

**Issue by SunIAver** [mezz/JustEnoughItems#3603]
### Steps to Reproduce the Crash

I can't enter the server after this update. When loading the terrain on the client, the game crashes.

### Mod Pack URL (Optional)

https://drive.google.com/file/d/1mxU7uZm-nfiwp2sEwdKrvtZM2By9GJ6z/view?usp=drive_link

### Crash Report

https://gist.github.com/KickOfSilver/182989e622ef4b8c4f8ce630ed634e03

**Comment by SunIAver** [comment]
The problem started with the update: jei-1.20.1-forge-15.8.0.10.jar and also continues in: jei-1.20.1-forge-15.8.0.11.jar.

**Comment by Devilswarchild** [comment]
I am also having this issue as well on jei-1.20.1-forge-15.8.0.11

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with LDLib, I have reported it to them here: https://github.com/Low-Drag-MC/LDLib-Architectury/issues/29

**Comment by mezz** [comment]
Duplicate of https://github.com/mezz/JustEnoughItems/issues/3599

**Comment by KickOfSilver** [comment]
@mezz I don't have this mod installed

Ad-Astra-Giselle-Addon-forge-1.20.1-6.9.jar
additional_lights-1.20.1-2.1.7.jar
ad_astra-forge-1.20.1-1.15.18.jar
AE2-Things-1.2.1.jar
AE2NetworkAnalyzer-1.20-1.0.6-forge.jar
AI-Improvements-1.20-0.5.2.jar
aiotbotania-1.20.1-4.0.5.jar
alexscaves-1.1.4.jar
alexscavesdelight-1.0.9-1.20.1.jar
alexsdelight-1.5.jar
alexsmobs-1.22.8.jar
allthecompressed-1.20.1-3.0.2.jar
almostunified-forge-1.20.1-0.9.4.jar
AmbientSounds_FORGE_v6.0.3_mc1.20.1.jar
another_furniture-forge-1.20.1-3.0.1.jar
appleskin-forge-mc1.20.1-2.5.1.jar
Applied-Botanics-forge-1.5.0.jar
Applied-Mekanistics-1.4.2.jar
appliedenergistics2-forge-15.2.9.jar
AppliedFlux-1.20-1.1.8-forge.jar
Aquaculture-1.20.1-2.5.1.jar
aquaculture_delight_1.0.0_forge_1.20.1.jar
aquamirae-6.API15.jar
ArcaneLanterns-v8.0.0-1.20.1-Forge.jar
architectury-9.2.14-forge.jar
arseng-1.2.0.jar
ars_elemental-1.20.1-0.6.5.jar
ars_nouveau-1.20.1-4.12.1-all.jar
ars_ocultas-1.20.1-1.2.2-all.jar
artifacts-forge-9.5.11.jar
athena-forge-1.20.1-3.1.2.jar
AttributeFix-Forge-1.20.1-21.0.4.jar
AutoLeveling-1.20-1.19b.jar
azurelib-neo-1.20.1-2.0.30.jar
balm-forge-1.20.1-7.3.6-all.jar
basicweapons-1.2.2.jar
bbb-1.20.1-forge-1.0.1.jar
beautify-2.0.2.jar
better-trees-1.8.jar
betterarcheology-1.1.9-1.20.1.jar
bettercombat-forge-1.8.5+1.20.1.jar
BetterF3-7.0.2-Forge-1.20.1.jar
BetterPingDisplay-1.20.1-1.1.jar
bigger_ae2-1.20.1-1.3.4.jar
BiomesOPlenty-1.20.1-18.0.0.592.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
borninconfiguration-1.4.jar
born_in_chaos_[Forge]1.20.1_1.3.1.jar
Botania-1.20.1-445-FORGE.jar
BotanyPots-Forge-1.20.1-13.0.36.jar
BotanyPotsTiers-Forge-1.20.1-6.0.1.jar
BotanyTrees-Forge-1.20.1-9.0.11.jar
botarium-forge-1.20.1-2.3.4.jar
BuildersDelight-1.20.1-v.1.3.jar
bushierflowers-0.0.3-1.20.1.jar
caelus-forge-3.2.0+1.20.1.jar
callablehorses-1.20.1-1.3.0.1.jar
canary-mc1.20.1-0.3.3.jar
carryon-forge-1.20.1-2.1.2.7.jar
Chipped-forge-1.20.1-3.0.6.jar
chunksending-1.20.1-2.8.jar
citadel-2.5.4-1.20.1.jar
clientcrafting-1.20.1-1.8.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
cluttered-2.1-1.20.1.jar
cobweb-forge-1.20.1-1.0.0.jar
cofh_core-1.20.1-11.0.2.56.jar
collective-1.20.1-7.71.jar
combatroll-forge-1.3.2+1.20.1.jar
CompositeMaterial-Forge-1.20.1-1.0.1.jar
configured-forge-1.20.1-2.2.3.jar
connectedglass-1.1.11-forge-mc1.20.1.jar
connectivity-1.20.1-5.6.jar
constructionwand-1.20.1-2.11.jar
Controlling-forge-1.20.1-12.0.2.jar
cosmeticarmorreworked-1.20.1-v1a.jar
crafting-on-a-stick-1.20.1-1.1.5.jar
craftingtweaks-forge-1.20.1-18.2.4.jar
CraftTweaker-forge-1.20.1-14.0.40.jar
create-1.20.1-0.5.1.f.jar
create-confectionery1.20.1_v1.1.0.jar
Create-Dreams-n-Desires-1.20.1-0.2c.PREBETA.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createaddition-1.20.1-1.2.4d.jar
createadditionplus-1.3.0-1.20.jar
createaddoncompatibility-v0.2.1a-1.20.1-(neo)forge.jar
createdeco-2.0.2-1.20.1-forge.jar
createdieselgenerators-1.20.1-1.2i.jar
createframed-1.20.1-1.4.4.jar
creategoggles-1.20.1-0.5.5.g-[FORGE].jar
createliquidfuel-2.1.1-1.20.1.jar
CreateNumismatics-1.0.6+forge-mc1.20.1.jar
CreateTweaker-forge-1.20.1-4.0.10.jar
create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.12.jar
create_compressed_1.0.1_forge_1.20.1.jar
create_connected-0.8.2-mc1.20.1-all.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.d.jar
create_misc_and_things_ 1.20.1_4.0A.jar
create_oppenheimered-1.0.3.jar
create_tweaked_controllers-1.20.1-1.2.4.jar
create_wizardry-0.2.3-forge-1.20.1.jar
CreativeCore_FORGE_v2.11.31_mc1.20.1.jar
creeperoverhaul-3.0.2-forge.jar
cristellib-1.1.5-forge.jar
crittersandcompanions-1.20.1-2.1.6.jar
cubicracers-1.3.0.jar
Cucumber-1.20.1-7.0.9.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.9.1+1.20.1.jar
CustomPlayerModels-1.20-0.6.17b.jar
deeperdarker-forge-1.20.1-1.2.1.jar
Delightful-1.20.1-3.5.8.jar
delightfulburgers-1.20.1.jar
delightfulsandwich-1.20.1.jar
deuf-1.20.1-1.3.jar
DiagonalFences-v8.1.4-1.20.1-Forge.jar
DiagonalWalls-v8.0.3-1.20.1-Forge.jar
DiagonalWindows-v8.1.4-1.20.1-Forge.jar
diet-forge-2.1.1+1.20.1.jar
Ding-1.20.1-Forge-1.5.0.jar
domesticationinnovation-1.7.1-1.20.1.jar
dsbg-1.0-1.20.1.jar
DungeonsArise-1.20.x-2.1.58-release.jar
DungeonsAriseSevenSeas-1.20.x-1.0.2-forge.jar
durabilitytooltip-1.1.5-forge-mc1.20.jar
easy-villagers-forge-1.20.1-1.1.14.jar
EasyAnvils-v8.0.2-1.20.1-Forge.jar
EasyMagic-v8.0.1-1.20.1-Forge.jar
EffectDescriptions-v8.0.2-1.20.1-Forge.jar
embeddium-0.3.25+mc1.20.1.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.16.jar
enderchests-forge-1.20.1-1.2.jar
endermanoverhaul-forge-1.20.1-1.0.4.jar
endersdelight-1.20.1-1.0.3.jar
endertanks-forge-1.20.1-1.3.jar
ends_delight-1.20.1-2.4.jar
entityculling-forge-1.6.6-mc1.20.1.jar
EpheroLib-1.20.1-FORGE-1.2.0.jar
everycomp-1.20-2.6.67.jar
Explorify v1.6.1 f10-48.jar
ExtremeReactors2-1.20.1-2.0.83.jar
fantasyfurniture-1.20.1-9.0.0.jar
FarmersDelight-1.20.1-1.2.4.jar
fastasyncworldsave-1.20.1-2.0.jar
FastFurnace-1.20.1-8.0.2.jar
FastSuite-1.20.1-5.0.1.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
FluxNetworks-1.20.1-7.2.1.15.jar
FramedBlocks-9.3.0.jar
framework-forge-1.20.1-0.7.6.jar
friendsandfoes-forge-mc1.20.1-2.0.15.jar
ftb-chunks-forge-2001.3.1.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.2.2.jar
ftb-quests-forge-2001.4.7.jar
ftb-teams-forge-2001.3.0.jar
ftb-xmod-compat-forge-2.1.1.jar
fusion-1.1.1-forge-mc1.20.1.jar
geckolib-forge-1.20.1-4.4.7.jar
getittogetherdrops-forge-1.20-1.3.jar
Glodium-1.20-1.5-forge.jar
goblins_tyranny-1.2.1-forge-1.20.1.jar
goblintraders-forge-1.20.1-1.9.3.jar
handcrafted-forge-1.20.1-3.0.6.jar
harvest-with-ease-forge-1.20.1-9.0.1.jar
horsecombatcontrols-1.20.1-1.0.1.jar
HorseExpert-v8.1.1-1.20.1-Forge.jar
hyperbox-1.20.1-4.0.2.0.jar
iceandfire-2.1.13-1.20.1-beta-4-fix.jar
iChunUtil-1.20.1-Forge-1.0.0.jar
IllagerInvasion-v8.0.5-1.20.1-Forge.jar
ImmediatelyFast-Forge-1.2.18+1.20.4.jar
immersive_melodies-0.3.0+1.20.1-forge.jar
immersive_paintings-0.6.7+1.20.1-forge.jar
InsaneLib-1.13.5-mc1.20.1.jar
inventoryessentials-forge-1.20.1-8.2.6.jar
inventorysorter-1.20.1-23.0.1.jar
ironfurnaces-1.20.1-4.1.6.jar
irons_spellbooks-1.20.1-3.3.0.jar
itemcollectors-1.1.10-forge-mc1.20.jar
Jade-1.20.1-forge-11.9.2.jar
JadeAddons-1.20.1-forge-5.2.2.jar
jei-1.20.1-forge-15.4.0.9.jar
jmi-forge-1.20.1-0.14-45.jar
journeymap-1.20.1-5.10.1-forge.jar
JustEnoughMekanismMultiblocks-1.20.1-4.2.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
knightquest-1.4.1.jar
KryptonReforged-0.2.3.jar
LeavesBeGone-v8.0.0-1.20.1-Forge.jar
letmedespawn-forge-1.20.1-1.20.4-1.2.1.jar
lhmiracleroad-forge-1.20.1-1.6.0.jar
LibX-1.20.1-5.0.12.jar
lionfishapi-1.9.jar
lithosphere 1.2 25.06.2024.jar
lithostitched-forge-1.20.1-1.1.6.jar
loot_journal-3.1.1.jar
Lychee-1.20.1-forge-5.1.14.jar
L_Enders_Cataclysm-1.99.6-1.20.1.jar
macawsbridgesbop-1.20-1.3.jar
macawsroofsbop-1.20-1.0.jar
MagnumTorch-v8.0.2-1.20.1-Forge.jar
matc-1.6.0.jar
mcw-bridges-3.0.0-mc1.20.1forge.jar
mcw-doors-1.1.1forge-mc1.20.1.jar
mcw-fences-1.1.2-mc1.20.1forge.jar
mcw-furniture-3.2.2-mc1.20.1forge.jar
mcw-lights-1.1.0-mc1.20.1forge.jar
mcw-roofs-2.3.0-mc1.20.1forge.jar
mcw-trapdoors-1.1.3-mc1.20.1forge.jar
mcw-windows-2.2.1-mc1.20.1forge.jar
mcwfencesbop-1.20-1.1.jar
mcwfurnituresbop-1.20-1.1.jar
megacells-forge-2.4.4-1.20.1.jar
Mekanism-1.20.1-10.4.8.43.jar
MekanismAdditions-1.20.1-10.4.8.43.jar
MekanismGenerators-1.20.1-10.4.8.43.jar
MekanismTools-1.20.1-10.4.8.43.jar
merequester-forge-1.20.1-1.1.4.jar
mes-1.3.1-1.20-forge.jar
MobDespawnTimers-1.20.1-3.0.1.jar
MobLassos-v8.0.1-1.20.1-Forge.jar
modelfix-1.15.jar
modernfix-forge-5.18.6+mc1.20.1.jar
modonomicon-1.20.1-forge-1.73.1.jar
molten_metals-1.20.1-0.1.4-forge.jar
moonlight-1.20-2.12.6-forge.jar
moredragoneggs-4.0.jar
MoreMekanismProcessing-1.20.1-4.0.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
mowziesmobs-1.6.5.jar
MutantMonsters-v8.0.7-1.20.1-Forge.jar
MysticalAgradditions-1.20.1-7.0.3.jar
MysticalAgriculture-1.20.1-7.0.11.jar
MysticalCustomization-1.20.1-5.0.1.jar
MythicBotany-1.20.1-4.0.3.jar
mythicmobs-1.20.1-connector-1.4.5.jar
naturalist-forge-4.0.3-1.20.1.jar
Nether's Overhaul-1.20.1_V1.3.6.jar
nether-s-exoticism-1.20.1-1.2.8.jar
netherportalfix-forge-1.20-13.0.1.jar
nethersdelight-1.20.1-4.0.jar
NightConfigFixes-v8.0.0-1.20.1-Forge.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
noflyzone-1.20.1-1.1.0.jar
noisium-forge-2.0.3+mc1.20-1.20.1.jar
obscure_api-15.jar
occultism-1.20.1-1.132.1.jar
oceansdelight-1.0.2-1.20.jar
oculus-mc1.20.1-1.7.0.jar.disabled
offlineskins-1.20.1-v1.jar
OpenLoader-Forge-1.20.1-19.0.4.jar
OverflowingBars-v8.0.0-1.20.1-Forge.jar
packetfixer-forge-1.4.2-1.19-to-1.20.1.jar
Paraglider-forge-20.1.3.jar
Patchouli-1.20.1-84-FORGE.jar
Pehkui-3.8.2+1.20.1-forge.jar
PermanentSponges-v8.1.2-1.20.1-Forge.jar
Philips-Ruins1.20.1-4.2.jar
pipez-forge-1.20.1-1.2.15.jar
Placebo-1.20.1-8.6.2.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
PlayerRevive_FORGE_v2.0.25_mc1.20.1.jar
polyeng-forge-0.1.1-1.20.1.jar
polymorph-forge-0.49.5+1.20.1.jar
Powah-5.0.5.jar
ProgressiveBosses-3.9.7-mc1.20.1.jar
protection_pixel-1.0.1.jar
PuzzlesLib-v8.1.21-1.20.1-Forge.jar
Quark-4.0-458.jar
quark_delight_1.0.0_forge_1.20.1.jar
realistic_horse_genetics-1.20.1-13.3.jar
realmrpg_fallen_adventurers_1.0.3_forge_1.20.1.jar
realmrpg_imps_and_demons_0.9.0_forge_1.20.1.jar
realmrpg_pots_and_mimics_1.0.2_forge_1.20.1.jar
realmrpg_seadwellers_2.9.9_forge_1.20.1.jar
rechiseled-1.1.6-forge-mc1.20.jar
recipeessentials-1.20.1-3.5.jar
reliquary-1.20.1-2.0.41.1229.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.25.jar
Ribbits-1.20.1-Forge-3.0.0.jar
rustic_engineer-1.20.1-1.0.6.jar
Searchables-forge-1.20.1-1.0.3.jar
serverconfigupdater-4.0.2.jar
shetiphiancore-forge-1.20.1-1.3.jar
showcaseitem-1.20.1-1.2.jar
simplehats-forge-1.20.1-0.3.0.jar
SmartBrainLib-forge-1.20.1-1.14.2.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
sophisticatedstorage-1.20.1-0.10.25.804.jar
sound-physics-remastered-forge-1.20.1-1.4.5.jar
spark-1.10.53-forge.jar
stackrefill-1.20.1-4.4.jar
starbunclemania-1.20.1-1.2.2.0.jar
starlight-1.1.2+forge.1cda73c.jar
Steam_Rails-1.6.4+forge-mc1.20.1.jar
storagedrawers-1.20.1-12.0.3.jar
Structory_1.20.x_v1.3.5.jar
Structory_Towers_1.20.x_v1.0.7.jar
structureessentials-1.20.1-3.4.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
supplementaries-1.20-2.8.17.jar
tanukidecor-20.1.1.0.jar
TerraBlender-forge-1.20.1-3.0.1.7.jar
thermal_dynamics-1.20.1-11.0.1.23.jar
thermal_expansion-1.20.1-11.0.1.29.jar
thermal_foundation-1.20.1-11.0.6.70.jar
thermal_innovation-1.20.1-11.0.1.23.jar
thermal_integration-1.20.1-11.0.1.27.jar
thermal_locomotion-1.20.1-11.0.1.19.jar
time-in-a-bottle-4.0.4-mc1.20.1.jar
TinySkeletons-v8.0.1-1.20.1-Forge.jar
tombstone-1.20.1-8.6.7.jar
toomanyglyphs-1.20.1-2.3.2.12345.jar
totw_modded-forge-1.20.1-1.0.5.jar
trashcans-1.0.18b-forge-mc1.20.jar
Twigs-1.20.1-3.1.0.jar
UniversalBoneMeal-v8.0.1-1.20.1-Forge.jar
voicechat-forge-1.20.1-2.5.19.jar
waystones-forge-1.20-14.1.4.jar
WitherSkeletonTweaks-1.20.1-9.1.0.jar
YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar
YungsApi-1.20-Forge-4.0.5.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
ZeroCore2-1.20.1-2.1.44.jar
Zeta-1.0-19.jar
[Forge]CTOV-v3.4.5.jar

**Comment by Devilswarchild** [comment]
Update modernfix and the iissue should resolve. It worked for me

**Comment by SunIAver** [comment]
@mezz I discovered that the mod bigger_ae2 1.3.4 loads the mod ldlib as well:

bigger_ae2 1.3.4
  |-- configuration 2.2.0
  \-- ldlib 1.0.25.e
  
  I removed the mod, but even so, JEI doesn't allow entering the world on the server. I have also already updated ModernFix.
  
  Crash Report
  https://gist.github.com/KickOfSilver/cab94a03d225a677f6fc07cae8988503

**Comment by SunIAver** [comment]
I discovered that the problem was caused by an addon for JEI, "JustEnoughMekanismMultiblocks-1.20.1-4.2.jar".

**Comment by Devilswarchild** [comment]
> I discovered that the problem was caused by an addon for JEI, "JustEnoughMekanismMultiblocks-1.20.1-4.2.jar".

removing that one definitely fixed the issue with jei-1.20.1-forge-15.8.0.13.jar

staying on 15.8.0.11 and updating modernfix to the latest version fixed that one for me

**Comment by mezz** [comment]
The problems with these mods are separate issues, unrelated to the original report.

Modernfix issues were reported and fixed here: 
https://github.com/embeddedt/ModernFix/issues/428
https://github.com/embeddedt/ModernFix/issues/438

The issue with JustEnoughMekanismMultiblocks was reported and fixed here: 
https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/12

**Comment by SunIAver** [comment]
@mezz The issue may have been fixed in more recent versions of Forge, but for 1.20.1, there hasn't been an update since October 20, 2023. The problem started with jei-1.20.1-forge-15.8.0.13.jar, released on July 18, 2024.

**Comment by mezz** [comment]
Which issue?

**Comment by Klauswh1** [comment]
I think the issue that he mentioned is the crash when loading terrain. For what I understood the problem was fixed in the 1.21 version of minecraft, but it still going on the 1.20.1, even with the today update

**Comment by mezz** [comment]
The original issue from this bug report, the one with LDLib, has not been resolved. 
For that one please follow their issue I linked earlier: https://github.com/Low-Drag-MC/LDLib-Architectury/issues/29

If you are talking about something else, please open a new bug report and show me the crash log so that I know what you're talking about. There are more than 4 bugs being brought up in this report which is getting counterproductive, please make sure your discussions are in the correct report and I can try to help you out.
