### ISSUE TITLE
[Crash]: Can't open anything

### ISSUE THREAD

**Issue by That-Memer** [mezz/JustEnoughItems#3605]
### Steps to Reproduce the Crash

Literally opening any type of menu, inventory, enchanting table, backpacks, even waystones.

### Extra Notes (Optional)

It only affects me, everyone else on the server (we all use jei) is completely fine. I was also on myself for about 5 hours got off for 1hr then got back on then started crashing.

### Crash Report

https://gist.github.com/That-Memer/429956f299909318828e004fee7dc3ab

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by That-Memer** [comment]
Apologies for having taking time out of your day but I've found the issue myself after looking through latest.log
I didn't know that was a thing so thanks for your response in helping me find a solution.
My issue was that the server (and everyone else) used an older version while mine was updated.
