### ISSUE TITLE
[Bug]: Crash on load

### ISSUE THREAD

**Issue by NauctusTheOG** [mezz/JustEnoughItems#3608]
### Steps to Reproduce the Bug

create new world and wait for "Joining World text"

### Expected Behavior

Entered the world

### Actual Behavior

Crashed to launcher with exit code -1

### latest.log

https://gist.github.com/NauctusTheOG/401de5d6668c3cf13bd5f6860338b6ab

**Comment by NauctusTheOG** [comment]
[It's Sculkin Time-1.0.1.zip](https://github.com/user-attachments/files/16274826/It.s.Sculkin.Time-1.0.1.zip)

this is the modpack me an my friends are using

**Comment by mezz** [comment]
Thanks for the report!
This is caused by https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/12

duplicates issue: https://github.com/mezz/JustEnoughItems/issues/3593
