### ISSUE TITLE
sophisticated backpack recipes not showing in game

### ISSUE THREAD

**Issue by suemiom** [mezz/JustEnoughItems#3609]
### Steps to Reproduce the Bug

JEI is normal in single player. However in multiplayer I am unable to access sophisticated backpack recipes. 

### Expected Behavior

JEI should just show the recipes in multiplayer too

### Actual Behavior

Minecraft Version 1.18.2
Forge Version 40.2.14
JEI-1.18.2-forge-10.2.1.1008

mods
![image](https://github.com/user-attachments/assets/2117cef6-0864-44de-ab4d-8fc24eb0c37c)

### latest.log

https://gist.github.com/suemiom/415497beb7c65f668d9e8e25880ed39c

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Sophisticated Backpacks and link back here.
Each mod adds its own recipes to JEI and there may be an issue with their JEI plugin.
