### ISSUE TITLE
[Bug]: bugged inventory

### ISSUE THREAD

**Issue by esthaire** [mezz/JustEnoughItems#3610]
### Steps to Reproduce the Bug

open inventory and opening a chest

### Expected Behavior

pressing e -> open inventory
opening chest -> item in the correct slot of the chest

### Actual Behavior

pressing e -> save the world and crash
opening a chest -> all the item are missplaced on the side of the chest and the jei dosnt appear at all

### Extra Notes (Optional)

i dont have any log sadly i cant find any recent...

**Comment by SMY77Y** [comment]
I'm having the same issue, only started tonight.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by SMY77Y** [comment]
https://gist.github.com/SMY77Y/74bda60e9d81e33ef08501b1b7192e5b
[https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png]<https://gist.github.com/SMY77Y/74bda60e9d81e33ef08501b1b7192e5b>
gist:74bda60e9d81e33ef08501b1b7192e5b<https://gist.github.com/SMY77Y/74bda60e9d81e33ef08501b1b7192e5b>
GitHub Gist: instantly share code, notes, and snippets.
gist.github.com

________________________________

**Comment by mezz** [comment]
Sorry, this is not what I need, it is a crash report. I need the full `latest.log` client log.

**Comment by kye-code** [comment]
Hey Mezz, here is my log files, im having this same issue and I used my same modpack yesterday with no issues. Thank you.
[latest.log](https://github.com/user-attachments/files/16309869/latest.log)
[crash-2024-07-19_02.13.42-client.txt](https://github.com/user-attachments/files/16309870/crash-2024-07-19_02.13.42-client.txt)

**Comment by quiicksilver** [comment]
Also having the same issue here; here is the full `latest.log`. https://gist.github.com/quiicksilver/ab7e5a620d7f458c7a06a89660cf7eb2

**Comment by mezz** [comment]
Thank you for the log!
It looks like there is some kind of broken ingredient in the creative menu, which crashes JEI's Vanilla Plugin.
```
[19Jul2024 19:50:09.979] [Render thread/ERROR] [mezz.jei.library.load.PluginCaller/]: Caught an error from mod plugin: class mezz.jei.library.plugins.vanilla.VanillaPlugin jei:minecraft
java.lang.IllegalStateException: Item has no registry name: 1 air BlockItem(net.minecraft.world.level.block.RotatedPillarBlock)
	at mezz.jei.common.util.StackHelper.lambda$getRegistryNameForStack$0(StackHelper.java:65) ~[jei-1.20.1-forge-15.8.0.14.jar%23309!/:15.8.0.14]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at mezz.jei.common.util.StackHelper.getRegistryNameForStack(StackHelper.java:63) ~[jei-1.20.1-forge-15.8.0.14.jar%23309!/:15.8.0.14]
	at mezz.jei.common.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:43) ~[jei-1.20.1-forge-15.8.0.14.jar%23309!/:15.8.0.14]
```

Because that main plugin crashed, just about everything else is broken after that.

I have pushed some fixes that should improve this situation so that the game can continue to run.
Please try it out and let me know if the issue is fixed for you, or if you run into more things crashing.

**Comment by quiicksilver** [comment]
It seems like those fixes worked! Thank you so much!
