### ISSUE TITLE
[Crash]: Client crashes upon reloading data

### ISSUE THREAD

**Issue by Not-February** [mezz/JustEnoughItems#3611]
### Steps to Reproduce the Crash

Every time that data needs to be reloaded(whether it is from the /reload command or simply leaving and then attempting to rejoin a single player world _or_ remote server after having already loaded into a world once already), the game crashes as soon as the player opens their inventory.

Order of events to replicate:

1. Launch game
2. Join single player world
3. Leave single player world
4. Rejoin single player world
5. Open inventory

### Mod Pack URL (Optional)

https://www.dropbox.com/scl/fi/mm3mh3gt9ssct3co4c0cp/1.20.1-Magic-Chill.zip?rlkey=5t49lxmiusyr4gtz31i4p933o&dl=0

### Extra Notes (Optional)

I'm pretty sure it's a niche mod conflict since I'm having trouble replicating the problem with just JEI + the included JEI addons I have installed.

ModernFix catches the crash and keeps the game open when it happens, but it's still impossible to load into a world and safely use your inventory until the game is fully restarted.

Interestingly enough, players who are actively using Dragon Survival - which replaces the default inventory interface with a different one - doesn't _crash_, but their inventory GUI gets screwed up in a totally different way:

![image](https://github.com/user-attachments/assets/122ca161-8fae-49f7-81cc-841d36168104)

It is also possible to open other inventory interfaces like chests without crashing, but they similarly render weirdly.

![image](https://github.com/user-attachments/assets/fcf15ab0-db9a-4a52-bea5-abad2603e501)

(Note that the above images reference EMI in the corner; I have it installed alongside JEI, but I've tested and confirmed that this problem happens without EMI installed as well)

So whatever the issue is, it only actually _crashes_ if you are opening the default player inventory GUI but other inventories still get messed up either way.

Here's a gist of the [debug.log](https://gist.github.com/Not-February/48b10e7d92b8006d28e53a70309727d3) if it helps in any way

### Crash Report

https://gist.github.com/Not-February/ca2d4f591c48b7cc19df1d0b3416fe20

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I am not able to figure out what's wrong here from the log, but the newer versions of JEI might print some more info.
Can you please try with the latest version of JEI, and without JER and ModernFix?
If it still crashes, please let me see the new debug.log

**Comment by Not-February** [comment]
I've tested the new version and it looks like this issue doesn't happen anymore. Thank you for the fix!

**Comment by mezz** [comment]
Great, I'm glad it's working now. Thanks for letting me know.
