### ISSUE TITLE
[Other]: flagged as trojan

### ISSUE THREAD

**Issue by Flyingwagons** [mezz/JustEnoughItems#3612]
### Other

Whenever I download any version of 1.21 JEI my computer antivirus flags it as a trojan. I do not know if this is a problem with the mod or my computer, but my computer was fine with every other mod and every other version 1.20.6 and below. I did not know if this qualified as a bug as this not affect the game itself.

**Comment by SilenceWolf** [comment]
Same for me, it says that there is a virus that is executing command so i delted it just in case.

**Comment by bin200** [comment]
Version 15.8.0.16 for Fabric 1.20.1 had this issue for me as well.

**Comment by mezz** [comment]
Hmm thanks for letting me know. This is probably a false positive, JEI is open source and the CI builds from the source.
I'll compare 15.8.0.16 for Fabric 1.20.1 to the source code to verify that nothing has been compromised.

**Comment by mezz** [comment]
The jar from CurseForge is identical to the jar I can build from source, so this is just a false positive.

**Comment by SilenceWolf** [comment]
> The jar from CurseForge is identical to the jar I can build from source, so this is just a false positive.

And for fabric 1.21?

**Comment by VulcanDVex** [comment]
> Version 15.8.0.16 for Fabric 1.20.1 had this issue for me as well.

Forge Version of that one as well.

**Comment by mezz** [comment]
Which antivirus is flagging things? I can try to submit an appeal to them.

**Comment by bin200** [comment]
> Which antivirus is flagging things? I can try to submit an appeal to them.

Flagged by Windows 10's built-in Virus & threat protection / Microsoft Defender Antivirus

![image](https://github.com/user-attachments/assets/4098bc0a-b5ec-4998-bab5-2337406b9b86)

**Comment by SilenceWolf** [comment]
> Which antivirus is flagging things? I can try to submit an appeal to them.

Windows 11 anti-virus / microsoft defender

**Comment by mezz** [comment]
I really don't know why they're flagging it.
See the VirusTotal results here: https://www.virustotal.com/gui/file/e47d5172bdad9c74bd902c37518c98eececdaf0e69a0fa75c21c55e6b797a401

![Screenshot 2024-07-22 at 11 13 53 AM](https://github.com/user-attachments/assets/581a2e67-d5fa-49f4-8cb0-e59c81df1e75)

**Comment by mezz** [comment]
I will follow Microsoft's submission process here: https://www.microsoft.com/en-us/wdsi/filesubmission/
It looks like the only way to appeal is to make them manually analyze it, may take a while.

**Comment by TheMasterBlaster** [comment]
Seems some other mods are having a similar issue. I haven't been able to download the Collective mod from any source I have tried.

**Comment by mezz** [comment]
I haven't received any updates from Microsoft.
I assume if enough people submit these files to them, they will eventually take action.
If you have time, please submit one of these many jar files to [microsoft.com/en-us/wdsi/filesubmission](https://www.microsoft.com/en-us/wdsi/filesubmission/) so they can analyze it and fix their detection methods.

**Comment by mezz** [comment]
I still haven't received any updates from Microsoft, the case is pending.

**Comment by TheMasterBlaster** [comment]
Seems Windows Defender isn't flagging JEI or any of the other mods as a virus, like it was doing before.

**Comment by mezz** [comment]
Ok thanks, I'm glad that's over.
