### ISSUE TITLE
[Bug]: Windows Defender detects two latest versions as Trojan Wacatac.B!ml

### ISSUE THREAD

**Issue by danjustice2** [mezz/JustEnoughItems#3615]
### Steps to Reproduce the Bug

Have Windows Defender protection enabled. Download versions 15.8.0.16 or 15.8.0.15 from Modrinth/Curse Forge website via Edge. Also affects me if I try to download it via AutoModpack. The older versions work fine.

### Expected Behavior

Successful download

### Actual Behavior

Edge doesn't say anything the first time you try to download, but the .jar file is empty. If you try downloading again it says, "Couldn't download - Virus Detected". Looking in the Windows Defender menu, I am told it is detected as Trojan Wacatac.B!ml.

### Extra Notes (Optional)

Works fine if you disable Windows Defender protection. I have only tried on my own computer.

**Comment by cadeeja** [comment]
Same here. WD detected Trojan as described above. I haven't disable it though, will wait for statement.

**Comment by Satherov** [comment]
already been answered
https://github.com/mezz/JustEnoughItems/issues/3612

**Comment by mezz** [comment]
Thanks for the report!
This is a false positive, let's keep conversation in the main thread.
