### ISSUE TITLE
[Bug]: Game crashes when enabling Cheat Mode with Forge

### ISSUE THREAD

**Issue by TheEpicGamer1998** [mezz/JustEnoughItems#3618]
### Steps to Reproduce the Bug

Hold CTRL and press the Wrench icon 

### Expected Behavior

It should activate cheat mode 

### Actual Behavior

The game crashes and sends me to the multiplayer server list from Singleplayer (Error: Network Protocol Error)

### Mod Pack Version (Optional)

1.21

### latest.log

https://gist.github.com/TheEpicGamer1998/de36efc5860c8b2d68218c9815e04d22

**Comment by mezz** [comment]
Thanks for the report!
I was able to reproduce this bug, I will try to figure out why it's breaking.
This seems to work fine on Fabric and NeoForge.

**Comment by mezz** [comment]
This has been fixed and will be released in the next version (should be available in 20 minutes or so).
