### ISSUE TITLE
Trojan Virus

### ISSUE THREAD

**Issue by gyatttttttttttt** [mezz/JustEnoughItems#3619]
### Steps to Reproduce the Bug

Download 1.21 fabric JEI

### Expected Behavior

downloads well and i can use it in mc

### Actual Behavior

windows detects a TROJAN VIRUS that I have to remove with windows security check

### Extra Notes (Optional)

are you trying to gain access to my pc?

**Comment by Satherov** [comment]
read here
https://github.com/mezz/JustEnoughItems/issues/3612

**Comment by mezz** [comment]
Thanks for the report!
This is a false positive, let's keep conversation in the main thread.
