### ISSUE TITLE
 jei_1.10.2-3.7.7.233 Crashed My Game[1.10.2] java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting

### ISSUE THREAD

**Issue by 7934345** [mezz/JustEnoughItems#362]
Hi, My game crashed when create a new world  or load old the world.

I just remove the JEI and everything is ok now.

Game Version 1.10.2
Forge Version 1.10.2 - 12.18.1.2014
JEI Version jei_1.10.2-3.7.7.233

Description: JEI failed to start:
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting

Here is the full log below:
https://gist.github.com/7934345/e79307fde344aa4cfebd3ac6a69e8304

**Comment by TehNut** [comment]
https://github.com/mezz/JustEnoughItems/search?utf8=%E2%9C%93&q=realmsclient&type=Code

lol

Should be `net.minecraft.util.text.TextFormatting`

**Comment by mezz** [comment]
Thanks for the report!
I wonder why nobody else had a problem.
Fixed in JEI 3.7.8

**Comment by 7934345** [comment]
:)
