### ISSUE TITLE
[Bug]: Latest forge JEI version for 1.20.1 virus has been detected

### ISSUE THREAD

**Issue by vinnyg0621** [mezz/JustEnoughItems#3620]
### Steps to Reproduce the Bug

1. download jei 1.20.1 forge 15.8.0.16 .jar from curse forge

### Expected Behavior

the mod to download without any virus in it

### Actual Behavior

it will tell me "virus detected" on chrome. on firefox it doesn't let me download it at all.

### Extra Notes (Optional)

here is a picture
![Screenshot 2024-07-21 125914](https://github.com/user-attachments/assets/45104c47-e523-4313-b152-ae9d04431861)

**Comment by Satherov** [comment]
check here
https://github.com/mezz/JustEnoughItems/issues/3612

**Comment by mezz** [comment]
Thanks for the report!
This is a false positive, let's keep conversation in the main thread.
