### ISSUE TITLE
[Other]: Could not find method deobfProvided() for arguments [mezz.jei:jei_1.19.2:11.0.0.297:api] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

### ISSUE THREAD

**Issue by randomusert** [mezz/JustEnoughItems#3622]
### Other

Build file 'R:\custom-crafting-forge-1.19.2\build.gradle' line: 139

A problem occurred evaluating root project 'custom-crafting-forge-1.19.2'.
 Could not find method deobfProvided() for arguments [mezz.jei:jei_1.19.2:11.0.0.297:api] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

 Try:
 Run with --stacktrace option to get the stack trace.
 Run with --info or --debug option to get more log output.
 Run with --scan to get full insights.
 Get more help at https://help.gradle.org.
BUILD FAILED in 1m 5s

code on: https://github.com/tinteeam/custom-crafting-forge-1.19.2

**Comment by mezz** [comment]
Thanks for the report!

`deobfProvided` works for ForgeGradle version 2, which is only used for Minecraft 1.12.

For ForgeGradle on Minecraft 1.19.2, please follow these instructions from the wiki:
https://github.com/mezz/JustEnoughItems/wiki/Getting-Started-%5BJEI-10-or-higher-for-Forge-or-Fabric%5D#dependencies-for-forgegradle

**Comment by randomusert** [comment]
now it trows this: 
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find mezz.jei:jei-1.19.2-common-api:11.0.0.297_mapped_official_1.19.2.
     Searched in the following locations:
       - file:/C:/Users/Kone/.gradle/caches/forge_gradle/bundled_deobf_repo/mezz/jei/jei-1.19.2-common-api/11.0.0.297_mapped_official_1.19.2/jei-1.19.2-common-api-11.0.0.297_mapped_official_1.19.2.pom
       - file:/C:/Users/Kone/.gradle/caches/forge_gradle/bundled_deobf_repo/mezz/jei/jei-1.19.2-common-api/11.0.0.297_mapped_official_1.19.2/jei-1.19.2-common-api-11.0.0.297_mapped_official_1.19.2.jar
     Required by:
         project :
   > Could not find mezz.jei:jei-1.19.2-forge-api:11.0.0.297_mapped_official_1.19.2.
     Searched in the following locations:
       - file:/C:/Users/Kone/.gradle/caches/forge_gradle/bundled_deobf_repo/mezz/jei/jei-1.19.2-forge-api/11.0.0.297_mapped_official_1.19.2/jei-1.19.2-forge-api-11.0.0.297_mapped_official_1.19.2.pom
       - file:/C:/Users/Kone/.gradle/caches/forge_gradle/bundled_deobf_repo/mezz/jei/jei-1.19.2-forge-api/11.0.0.297_mapped_official_1.19.2/jei-1.19.2-forge-api-11.0.0.297_mapped_official_1.19.2.jar
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by mezz** [comment]
Here is a working (at the time) build.gradle for 1.19: https://github.com/mezz/ItemZoom/blob/da3afdd63ddd3b69648e415589103286cdbd5c42/build.gradle
Please compare your configuration to this one in order to see if there are any issues.

**Comment by mezz** [comment]
The wiki also lists another repo that isn't in your build script:
```
  maven {
    // location of the maven that hosts JEI files since January 2023
    name = "Jared's maven"
    url = "https://maven.blamejared.com/"
  }
```
Please make sure you follow all the steps on the page I linked earlier.

If it still doesn't work, send me a link to your updated build.gradle so I can try it out.

**Comment by randomusert** [comment]
i did not push it my bad

**Comment by randomusert** [comment]
it should be pushed

**Comment by randomusert** [comment]
I think it The mappings since My mod uses The official mippings not The other mappings

**Comment by randomusert** [comment]
did not work with parchment mappings

**Comment by mezz** [comment]
I will try it out and see what happens on my computer.

**Comment by mezz** [comment]
You have chosen JEI version `11.0.0.297`, which is quite old and for Minecraft 1.19.
Setting the version to `11.6.0.1024`, the latest for 1.19.2, fixes the problem.

**Comment by randomusert** [comment]
oh they are in reverse from oledest to newest i didn't notice that

**Comment by randomusert** [comment]
it works!

**Comment by mezz** [comment]
Great!

**Comment by randomusert** [comment]
but the listing in the maven repository is inverted isn't ideal

**Comment by mezz** [comment]
I think maven is sorted alphabetically, I'm not sure what the right approach is to improve it but I'll ask around.

**Comment by randomusert** [comment]
yeah thats why i had this sorry for this hastle

**Comment by mezz** [comment]
I have added a list of the latest versions to the README, check it out:
https://github.com/mezz/JustEnoughItems/blob/1.21.x/README.md#latest-versions
