### ISSUE TITLE
[Bug]: Network Protocol Error

### ISSUE THREAD

**Issue by cheddar98** [mezz/JustEnoughItems#3625]
### Steps to Reproduce the Bug

Have JEI active. Try to join single player or multiplayer world. Get network protocol error. 

### Expected Behavior

Should be able to join a single player or multiplayer world without any issues. 

### Actual Behavior

Most of the time I try to join a single player or multiplayer world, I get a network protocol error. 

### Extra Notes (Optional)

With JEI installed, about 75% of the time I try to join a multiplayer or singleplayer world, I get a network protocol error. Sometimes restarting the game will help. Sometimes changing the version of the mod will help. But all the versions I've been on in 1.21 have caused this issue. I understand that it could technically be another mod, but this problem doesn't happen when I disable JEI. 

[disconnect-2024-07-22_21.51.09-client.txt](https://github.com/user-attachments/files/16342938/disconnect-2024-07-22_21.51.09-client.txt)

### latest.log

https://gist.github.com/cheddar98/f1d1f4ea846fafd56b35fac28f4f8466

**Comment by mezz** [comment]
Thanks for the report! 
Does this happen when only JEI is installed, without EMI?

**Comment by cheddar98** [comment]
I tried disabling EMI and after joining both single player and multiplayer worlds multiple times, it doesn't appear to be showing up. It's odd because EMI won't do it by itself but somehow by adding JEI it causes this error.

**Comment by mezz** [comment]
Hm ok. It's important to try to take a scientific approach on confusing problems like this, and isolate the issue as much as we can.
The issue seems to come from JEI but it's unclear what is happening. Based on what you said so far, it doesn't sound like EMI is relevant to this bug.

Please try with just JEI (without EMI) and paste the log here when you get a network error, so I can try to determine what is happening.

**Comment by cheddar98** [comment]
Sorry, I guess I wasn't clear enough. The error wasn't happening when I tried just JEI without EMI, though trying the opposite way (EMI without JEI) it doesn't happen either. It really only seems to happen with both together, oddly.

**Comment by cheddar98** [comment]
Another note, after testing, is that the error doesn't seem to happen anymore on versions past 19.5.0.48. I checked recently after not really experiencing the bug in a few days. I've been updating to the latest version but anytime I went to version 19.5.0.48 or lower to test I would get the bug without fail. It doesn't happen with JEI by itself, even on these older versions. Adding my most recent logs, but I'm not sure if it's just a coincidence or if it was fixed somehow.
[disconnect-2024-07-28_00.54.36-client.txt](https://github.com/user-attachments/files/16402256/disconnect-2024-07-28_00.54.36-client.txt)
[latest(2).log](https://github.com/user-attachments/files/16402257/latest.2.log)

**Comment by cheddar98** [comment]
Ok, I experienced it on a newer version, so I guess it was just a coincidence. Added logs.
[disconnect-2024-07-29_19.01.15-client.txt](https://github.com/user-attachments/files/16419869/disconnect-2024-07-29_19.01.15-client.txt)
[latest.log](https://github.com/user-attachments/files/16419870/latest.log)

**Comment by mezz** [comment]
Sorry, this log still includes EMI. I can only really help if the issue is with JEI.
Please report this latest log to EMI and link back to this issue so we can work together on a solution if needed.
