### ISSUE TITLE
[Bug]:  1.20.1 mouse behaviour

### ISSUE THREAD

**Issue by netcore10** [mezz/JustEnoughItems#3627]
### Steps to Reproduce the Bug

not really sure

### Expected Behavior

no idea

### Actual Behavior

it was when i clicked on something

### latest.log

https://mclo.gs/SIjm5Cr

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3460
