### ISSUE TITLE
[Crash]: to view recipes from simplyswords mod

### ISSUE THREAD

**Issue by Rodrigo816** [mezz/JustEnoughItems#3632]
### Steps to Reproduce the Crash

Install simplyswords mod
click on runic table to view the recipe
it crashes

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/create-chronicles-bosses-and-beyond

### Mod Pack Version (Optional)

3.3.1

### Extra Notes (Optional)

JEI VERSION: 15.8.0.18
FORGE 1.20.1

### Crash Report

https://gist.github.com/Rodrigo816/0ede68c33811483f4fd2f209ef2d92b9

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the next release, available shortly. 
Please try it out and let me know if you run into any other issues.

**Comment by Rodrigo816** [comment]
I tried on the new version and its fixed :)
