### ISSUE TITLE
[Crash]: When searching for gold and browsing to a page of the results in JEI

### ISSUE THREAD

**Issue by Runburner** [mezz/JustEnoughItems#3634]
### Steps to Reproduce the Crash

1. Open inventory or crafting table
2. Search for gold
3. Go to 2nd page
4. Game crashes to desktop, no crash log created

### Extra Notes (Optional)

I cleared my logger before performing the steps. As soon as I search gold and move to the 2nd page, it just straight crashes to desktop. My mod list is extensively long as I am working on a mod pack. It's not published at this time but the mod list is below.

If needed for testing I can provide it. 

[✔] [Universal]Immersive Structures-2.0.7a
  [✔] additional_lights-1.19-2.1.6
  [✔] AdditionalBanners-Forge-1.19.2-10.1.7
  [✔] additionallanterns-1.1.1a-forge-mc1.19
  [✔] Adorn-3.9.1+1.19.2-forge
  [✔] advancednetherite-1.14.7-1.19.2
  [✔] AdvancementPlaques-1.19.2-1.4.7
  [✔] AI-Improvements-1.19.2-0.5.2
  [✔] almostunified-forge-1.19.2-0.8.1
  [✔] AmbientSounds_FORGE_v5.3.9_mc1.19.2
  [✔] another_furniture-forge-1.19.2-2.1.4
  [✔] appleskin-forge-mc1.19-2.4.2
  [✔] Architects-Palette-1.19.2-1.3.5
  [✔] architectury-6.6.92-forge
  [✔] ArmorStatues-v4.0.8-1.19.2-Forge
  [✔] ars_nouveau-1.19.2-3.22.3
  [✔] AttributeFix-Forge-1.19.2-17.2.7
  [✔] AutoRegLib-1.8.2-55
  [✔] BadOptimizations-2.1.4-1.19.1-19.2
  [✔] balm-forge-1.19.2-4.6.0
  [✔] BarteringStation-v4.0.3-1.19.2-Forge
  [✔] baubley-heart-canisters-1.19.2-2.1.0
  [✔] BetterAdvancements-1.19.2-0.3.0.148
  [✔] BetterAnimationsCollection-v4.0.5-1.19.2-Forge
  [✔] bettercombat-forge-1.7.1+1.19
  [✔] BetterCompatibilityChecker-1.0.7-build.35+mc1.19.2
  [✔] BetterF3-4.0.1-Forge-1.19.2
  [✔] BetterModsButton-v4.2.4-1.19.2-Forge
  [✔] betterstats-2.2.2+1.19.2
  [✔] BetterThirdPerson-Forge-1.19-1.9.0
  [✔] BetterTridents-v4.0.2-1.19.2-Forge
  [✔] bettervillage-forge-1.19.2-3.2.0
  [✔] biggerreactors-1.19.2-0.6.0-beta.6.4
  [✔] BiomesOPlenty-1.19.2-17.1.2.492
  [✔] BlockRunner-v4.2.2-1.19.2-Forge
  [✔] blueprint-1.19.2-6.2.0
  [✔] Bookshelf-Forge-1.19.2-16.3.20
  [✔] Botania-1.19.2-440-FORGE
  [✔] botarium-forge-1.19.2-1.9.2
  [✔] bwncr-forge-1.19.2-3.14.1
  [✔] caelus-forge-1.19.2-3.0.0.6
  [✔] camera-forge-1.19.2-1.0.12
  [✔] catalogue-1.7.0-1.19.2
  [✔] cc-tweaked-1.19.2-1.101.4
  [✔] chalk-1.19.2-1.6.3
  [✔] ChanceCubes-1.19.2-5.0.2.475
  [✔] chat_heads-0.12.8-forge-1.19.2
  [✔] chefs-delight-1.0.2-forge-1.19.2
  [✔] cherishedworlds-forge-6.0.5+1.19.4
  [✔] Chimes-v2.0.1-1.19.2
  [✔] Chunky-1.3.38
  [✔] citadel-2.1.4-1.19
  [✔] clayworks-1.19.2-2.1.0
  [✔] cloth-config-8.3.115-forge
  [✔] CodeChickenLib-1.19.2-4.3.2.490-universal
  [✔] Cognition-v2.1.0-1.19.2
  [✔] collective-1.19.2-7.64
  [✔] ColorfulAzaleas-forge-1.19.2-2.3.1
  [✔] combatroll-forge-1.1.5+1.19
  [✔] comforts-forge-6.0.7+1.19.2
  [✔] configured-2.1.1-1.19.2
  [✔] connectedness-2.0.1a
  [✔] connectivity-1.19.2-4.6
  [✔] construct-and-better-combat-1
  [✔] Controlling-forge-1.19.2-10.0+7
  [✔] cookingforblockheads-forge-1.19.2-13.3.4
  [✔] CorgiLib-forge-1.19.2-1.0.0.34
  [✔] corpse-forge-1.19.2-1.0.12
  [✔] craftingtweaks-forge-1.19.2-15.1.9
  [✔] CraftTweaker-forge-1.19.2-10.1.55
  [✔] crashutilities-6.2
  [✔] create-1.19.2-0.5.1.f
  [✔] createaddition-1.19.2-1.2.2
  [✔] create-structures-0.1.0
  [✔] CreativeCore_FORGE_v2.11.28_mc1.19.2
  [✔] creeperoverhaul-2.0.9-forge
  [✔] crittersandcompanions-1.19.2-2.1.1
  [✔] Croptopia-1.19.2-FORGE-2.2.2
  [✔] CroptopiaDelight-1.19.2_1.2.2-forge
  [✔] Cucumber-1.19.2-6.0.10
  [✔] cullleaves-forge-3.0.1
  [✔] culturaldelights-1.19.2-0.15.5
  [✔] cupboard-1.19.2-2.6
  [✔] curios-forge-1.19.2-5.1.6.3
  [✔] CustomPlayerModels-1.19-0.6.17a
  [✔] Decorative Blocks-forge-1.19.2-3.0.0
  [✔] deuf-1.19.2-1.3
  [✔] DiagonalFences-v4.2.6-1.19.2-Forge
  [✔] DiagonalWindows-v4.0.2-1.19.2-Forge
  [✔] doespotatotick-1.19.2-4.0.2
  [✔] dummmmmmy-1.19.2-1.7.2
  [✔] DungeonCrawl-1.19-2.3.12
  [✔] dungeons_plus-1.19.2-1.3.1
  [✔] dungeons-and-taverns-2.0.2
  [✔] DungeonsArise-1.19.2-2.1.56-beta
  [✔] DustrialDecor-1.3.3-1.19.2
  [✔] EasyAnvils-v4.0.11-1.19.2-Forge
  [✔] EasyMagic-v4.3.3-1.19.2-Forge
  [✔] easy-villagers-forge-1.19.2-1.1.15
  [✔] EchoChest-v4.0.2-1.19.2-Forge
  [✔] edf-remastered-4.3
  [✔] effective_fg-1.3.4
  [✔] elevatorid-1.19.2-1.8.10
  [✔] elytraslot-forge-6.1.2+1.19.2
  [✔] embeddium-0.3.18.1+mc1.19.2
  [✔] embeddiumplus-1.19.2-v1.2.13
  [✔] EnchantmentDescriptions-Forge-1.19.2-13.0.14
  [✔] EnderStorage-1.19.2-2.10.1.181-universal
  [✔] endrem_forge-5.2.1-R-1.19.X
  [✔] ends_delight-1.19.2-2.0
  [✔] Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0
  [✔] entity_model_features_forge_1.19.2-2.0.2
  [✔] entity_texture_features_forge_1.19.2-6.0.1
  [✔] entityculling-forge-1.6.1-mc1.19.2
  [✔] epicsamurai-0.0.17-1.19.2-forge
  [✔] EquipmentCompare-1.19.1-1.3.1
  [✔] essential_1-3-2-7_forge_1-19-2
  [✔] EuphoriaPatcher-0.3.4-forge
  [✔] everycomp-1.19.2-2.5.24
  [✔] ExplorersCompass-1.19.2-1.3.0-forge
  [✔] fairylights-6.0.1-1.19.2
  [✔] Fallingleaves-1.19.1-1.3.1
  [✔] FallingTree-1.19.2-3.10.1
  [✔] fantasyfurniture-1.19.2-6.7.0
  [✔] FarmersDelight-1.19.2-1.2.4
  [✔] FarmersRespite-1.19-2.0
  [✔] farmingforblockheads-forge-1.19.2-11.3.5
  [✔] fast-ip-ping-mc1.19.4-forge-v1.0.3
  [✔] Fastload-Reforged-mc1.19.2-3.4.0
  [✔] fastpaintings-1.19-1.1.3
  [✔] FastSuite-1.19.2-4.1.1
  [✔] ferritecore-5.0.3-forge
  [✔] findme-3.1.0-forge
  [✔] FluxNetworks-1.19.2-7.1.4.13
  [✔] forge-1.19.2-optionsprofiles-1.1
  [✔] freecam-forge-modrinth-1.2.3+1.19.2
  [✔] ftb-chunks-forge-1902.4.6-build.360
  [✔] ftb-library-forge-1902.4.1-build.236
  [✔] ftb-quests-forge-1902.5.9-build.399
  [✔] ftb-teams-forge-1902.2.14-build.123
  [✔] fuelgoeshere-1.19.2-0.1.0.0
  [✔] fusion-1.1.1-forge-mc1.19.2
  [✔] geckolib-forge-1.19-3.1.40
  [✔] GeckoLibOculusCompat-Forge-1.0.1
  [✔] GeophilicReforged-v1.2.0
  [✔] gpumemleakfix-1.19.2-1.6
  [✔] handcrafted-forge-1.19.2-2.0.6
  [✔] healingcampfire-1.19.2-5.3
  [✔] Highlighter-1.19.1-1.1.4
  [✔] HorseExpert-v4.0.0-1.19.2-Forge
  [✔] iceandfire-1.19.2-2.1.13-beta-2
  [✔] Iceberg-1.19.2-forge-1.1.4
  [✔] immersive_aircraft-0.7.9+1.19.2-forge
  [✔] immersive_armors-1.5.6+1.19.2-forge
  [✔] immersive_melodies-0.1.2+1.19.2-forge
  [✔] immersive_weathering-1.19.2-1.2.10-forge
  [✔] Incendium_1.19.3_v5.1.6
  [✔] inventoryhud.forge.1.19.2-3.4.24
  [✔] ironchest-1.19.2-14.2.7
  [✔] ironfurnaces-1.19.2-3.6.5
  [✔] ItemBorders-1.19.1-1.2.0
  [✔] item-filters-forge-1902.2.9-build.51
  [✔] Jade-1.19.1-forge-8.9.2
  [✔] JadeAddons-1.19.2-forge-3.6.0
  [✔] JAOPCA-1.19.2-4.2.12.30
  [✔] jei-1.19.2-forge-11.6.0.1024
  [✔] JeiTweaker-forge-1.19.2-4.0.12
  [✔] jmi-forge-1.19.2-0.13-44
  [✔] journeymap-1.19.2-5.9.7-forge
  [✔] JourneyMap-Teams-forge-1.19.2-1.0.2
  [✔] justenoughbreeding-forge-1.19.2-1.2.1
  [✔] JustEnoughProfessions-forge-1.19.2-2.0.2
  [✔] JustEnoughResources-1.19.2-1.2.3.243
  [✔] kotlinforforge-3.12.0-all
  [✔] lazydfu-1.19-1.0.2
  [✔] LeaveMyBarsAlone-v4.0.0-1.19.2-Forge
  [✔] LegendaryTooltips-1.19.2-1.3.1
  [✔] letmedespawn-1.18-forge-1.0.3
  [✔] libraryferret-forge-1.19.2-4.0.0
  [✔] lightspeed-1.19.2-1.0.5
  [✔] lmft-1.0.2+1.19-forge
  [✔] Log-Begone-Forge-1.19-1.0.6
  [✔] lootbeams-1.19.2-1.0
  [✔] lootr-forge-1.19-0.4.26.69
  [✔] MagnumTorch-v4.2.3-1.19.2-Forge
  [✔] Mantle-1.19.2-1.10.36
  [✔] mcw-bridges-3.0.1-mc1.19.2forge
  [✔] mcw-doors-1.1.1forge-mc1.19.2
  [✔] mcw-fences-1.1.2-mc1.19.2forge
  [✔] mcw-furniture-3.2.2-mc1.19.2forge
  [✔] mcw-lights-1.1.0-mc1.19.2forge
  [✔] mcw-paths-1.0.5-1.19.2forge
  [✔] mcw-roofs-2.3.0-mc1.19.2forge
  [✔] mcw-trapdoors-1.1.3-mc1.19.2forge
  [✔] mcw-windows-2.2.1-mc1.19.2forge
  [✔] Mekanism-1.19.2-10.3.9.13
  [✔] MekanismGenerators-1.19.2-10.3.9.13
  [✔] memoryleakfix-forge-1.17+-1.1.5
  [✔] MerchantMarkers-1.19.2-forge-1.3.1
  [✔] miners_delight-1.19.2-1.1.1
  [✔] MobLassos-v4.0.0-1.19.2-Forge
  [✔] modernfix-forge-5.18.0+mc1.19.2
  [✔] ModernUI-Forge-1.19.2-3.10.1.2-universal
  [✔] mods
  [✔] moonlight-1.19.2-2.3.5-forge
  [✔] MouseTweaks-forge-mc1.19-2.23
  [✔] mtetm-0.0.1-1.19.2
  [✔] mutil-1.19.2-5.2.0
  [✔] NaturesCompass-1.19.2-1.10.0-forge
  [✔] nerb-1.19.2-0.3-FORGE
  [✔] netherportalfix-forge-1.19-10.0.2
  [✔] NethersDelight-1.19-3.1
  [✔] nohostilesaroundcampfire-1.19.2-5.9
  [✔] noisium-1.0.2
  [✔] notenoughcrashes-5.0.0+1.19.2-forge
  [✔] oculus-mc1.19.2-1.6.9
  [✔] oculusparticlefix-1.0
  [✔] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.6
  [✔] origins-forge-1.19.2-1.7.1.7-all
  [✔] origins-minus-2.1.1+1.19
  [✔] origins-player-scale-3
  [✔] OverflowingBars-v4.0.1-1.19.2-Forge
  [✔] packetfixer-forge-1.4.2-1.19-to-1.20.1
  [✔] pamhc2crops-1.19.2-1.0.2
  [✔] pamhc2foodcore-1.19.2-1.0.1
  [✔] pamhc2foodextended-1.19.2-1.0.0
  [✔] pamhc2trees-1.19.2-1.0.1
  [✔] Patchouli-1.19.2-77
  [✔] Paxi-1.19.2-Forge-3.0.1
  [✔] Pehkui-3.8.2+1.19.2-forge
  [✔] phosphophyllite-1.19.2-0.6.0-beta.8
  [✔] physics-mod-2.12.5-mc-1.19.2-forge
  [✔] PickleTweaks-1.19.2-7.0.3
  [✔] Ping-Wheel-1.9.1-forge-1.19.2
  [✔] Placebo-1.19.2-7.4.0
  [✔] player-animation-lib-forge-1.0.2
  [✔] pluto-mc1.19.2-0.0.9
  [✔] polymorph-forge-0.46.6+1.19.2
  [✔] Prism-1.19.1-1.0.2
  [✔] PuzzlesLib-v4.4.3-1.19.2-Forge
  [✔] qualitysounds-forge-1.5.0-1.19.2
  [✔] Quark-3.4-418
  [✔] quartz-1.19.2-0.1.0-beta.2.3
  [✔] Reaper-1.0.5
  [✔] rechiseled-1.1.6-forge-mc1.19.2
  [✔] rechiseledcreate-1.0.2-forge-mc1.19
  [✔] redirector-5.0.0
  [✔] refinedpolymorph-0.1.1-1.19.2
  [✔] refinedstorage-1.11.7
  [✔] reforgium-1.0.12a
  [✔] repurposed_structures_forge-6.3.28+1.19.2
  [✔] resourcefulconfig-forge-1.19.2-1.0.20
  [✔] resourcefullib-forge-1.19.2-1.1.24
  [✔] Rex's-AdditionalStructures-1.19.x-(v.4.0.4)
  [✔] Rrls-1.19.2-3.1.1-forge
  [✔] saturn-mc1.19.2-0.1.4
  [✔] seasonhud-forge-1.19.2-1.9.5
  [✔] secondchanceforge-1.19-1.5.1
  [✔] SereneSeasons-1.19.2-8.1.0.24
  [✔] sereneseasonsphc2crops-1.19.2-1.0.1
  [✔] sereneseasonsphc2trees-1.19.2-1.0.0
  [✔] simplyswords-forge-1.47.0-1.19.2
  [✔] skinlayers3d-forge-1.6.6-mc1.19.2
  [✔] SkyVillages-1.0.1-1.19-forge-release
  [✔] smallships-forge-1.19.2-2.0.0-b1.3.1
  [✔] sootychimneys-1.19.2-1.2.1
  [✔] sophisticatedbackpacks-1.19.2-3.20.2.1035
  [✔] sophisticatedcore-1.19.2-0.6.4.605
  [✔] sound-physics-remastered-forge-1.19.2-1.4.5
  [✔] spark-1.10.37-forge
  [✔] spirit-forge-1.19.2-2.2.7
  [✔] starlight-1.1.1+forge.cf5b10b
  [✔] Steam_Rails-1.6.4+forge-mc1.19.2
  [✔] Stoneworks-v4.0.2-1.19.2-Forge
  [✔] Structory_1.19.3_v1.3.1a
  [✔] Structory_Towers_1.19.3_v1.0.2
  [✔] structure_gel-1.19.2-2.7.3
  [✔] supermartijn642configlib-1.1.8-forge-mc1.19
  [✔] supermartijn642corelib-1.1.17-forge-mc1.19.2
  [✔] supplementaries-1.19.2-2.4.20
  [✔] suppsquared-1.19.2-1.0.8
  [✔] TCIntegrations-1.19.2-2.0.21.7
  [✔] TConstruct-1.19.2-3.8.3.39
  [✔] tectonic-forge-1.19-2.3.5a
  [✔] TerraBlender-forge-1.19.2-2.0.1.166
  [✔] Terralith_1.19.3_v2.3.12
  [✔] tetra-1.19.2-5.6.0
  [✔] tetraextras-0.1.4-1.19
  [✔] tetranomicon-1.5.3-1.19.2
  [✔] tetrasdelight-1.19.2-2
  [✔] tinkers_delight_1.0.0_forge_1.19.2
  [✔] tlc_forge-1.0.2-R-1.19.X
  [✔] ToastControl-1.19.2-7.0.0
  [✔] TooManyOrigins-1.0.0-beta.19+1.19.2-forge
  [✔] torchslabmod-1.19.2_v1.7.4
  [✔] touhoulittlemaid-1.19.2-release-1.1.11
  [✔] TradingPost-v4.2.0-1.19.2-Forge
  [✔] TravelersTitles-1.19.2-Forge-3.1.2
  [✔] twigs-forge-1.19.2-3.0.1
  [✔] uncappedblockids-1.19.2-1.2.0
  [✔] veinmining-forge-1.1.2+1.19.2
  [✔] visuality-forge-2.0.2
  [✔] VisualWorkbench-v4.2.4-1.19.2-Forge
  [✔] vitalize-forge-1.19.2-1.1.1
  [✔] voicechat-forge-1.19.2-2.5.19
  [✔] waystones-forge-1.19.2-11.4.2
  [✔] wits-1.1.0+1.19.2-forge
  [✔] xlpackets-1.0.4-1.19.4
  [✔] yeetusexperimentus-1.0.1-build.2+mc1.19.1
  [✔] YungsApi-1.19.2-Forge-3.8.10
  [✔] YungsBetterDesertTemples-1.19.2-Forge-2.2.2
  [✔] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔] YungsBetterEndIsland-1.19.2-Forge-1.0
  [✔] YungsBetterJungleTemples-1.19.2-Forge-1.0.1
  [✔] YungsBetterMineshafts-1.19.2-Forge-3.2.1
  [✔] YungsBetterNetherFortresses-1.19.2-Forge-1.0.6
  [✔] YungsBetterOceanMonuments-1.19.2-Forge-2.1.1
  [✔] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Forge-2.1.0
  [✔] YungsBridges-1.19.2-Forge-3.1.0
  [✔] YungsExtras-1.19.2-Forge-3.1.0

### Crash Report

https://gist.github.com/Runburner/03eb1a169012708d948fd84dcff55a71

**Comment by mezz** [comment]
Thanks for the report!

In the future, please do not remove earlier parts of the log, I think JEI normally logs more information about the ingredient that is being rendered, just before the crash you see in the log here.

We can still see the crash's cause here:
```
Caused by: java.lang.ClassCastException: class me.pepperbell.continuity.client.model.EmissiveBakedModel cannot be cast to class slimeknights.mantle.client.model.RetexturedModel$Baked (me.pepperbell.continuity.client.model.EmissiveBakedModel is in module connectedness@2.0.1a of loader 'TRANSFORMER' @49a6503f; slimeknights.mantle.client.model.RetexturedModel$Baked is in module mantle@1.10.36 of loader 'TRANSFORMER' @49a6503f)
```

This seems to be a rendering issue between `pepperbell.continuity` and `slimeknights.mantle` mods. Please report this to Continuity and link back to this issue: https://github.com/PepperCode1/Continuity/issues

**Comment by Runburner** [comment]
It's probably Connectedness then instead of continuity. We are running 1.19.2 Forge. It's a Forge port. I will report it on their side.
