### ISSUE TITLE
JEI crashes on singlepalyer world startup, forge 1.20.1 [Crash]: 

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#3635]
### Steps to Reproduce the Crash

Step one: open Minecraft
Step two: open/create "New World" (super-flat void preset is what I used)
Step three: open "Crash-Client.txt"

### Extra Notes (Optional)

EMI and its addons do not affect crash log.
JEI addons do not affect crash log.
[Let's Do] API and the mods that use it does not affect crash log.

JEI crashes MineCraft 1.20.1 when the screen is on joining world.
I am using the latest version of JEI, 15.8.0.19.
I have tried changing versions of JEI.
The game works fine without JEI installed, (I can join worlds without the game crashing.)

I have no clue what i'm doing wrong plz help.

### Crash Report

https://gist.github.com/EgggyBoi/c024e044f40363d380ef1cb3a03bc294

**Comment by mezz** [comment]
Thanks for the report!
This issue is caused by LDLib:
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ldlib-common.mixins.json:jei.RecipeSlotAccessor] from phase [DEFAULT] in config [ldlib-common.mixins.json] FAILED during APPLY
```
They are using mixins to edit JEI's code but it is failing.
Please report to them here: https://github.com/Low-Drag-MC/LDLib-Architectury/issues

**Comment by EgggyBoi** [comment]
Thank you. Might be a just enough calculations peoblem

> Thanks for the report! This issue is caused by LDLib:
> 
> ```
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ldlib-common.mixins.json:jei.RecipeSlotAccessor] from phase [DEFAULT] in config [ldlib-common.mixins.json] FAILED during APPLY
> ```
> 
> They are using mixins to edit JEI's code but it is failing. Please report to them here: https://github.com/Low-Drag-MC/LDLib-Architectury/issues

**Comment by ghost** [comment]
Thanks. It doesn't seem like JEI is the problem outright but JEI, LDLib, and Gregtech have conflicts

This issue was fixed in the latest version of LDLib

> Thanks for the report! This issue is caused by LDLib:
> 
> ```
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ldlib-common.mixins.json:jei.RecipeSlotAccessor] from phase [DEFAULT] in config [ldlib-common.mixins.json] FAILED during APPLY
> ```
> 
> They are using mixins to edit JEI's code but it is failing. Please report to them here: https://github.com/Low-Drag-MC/LDLib-Architectury/issues

**Comment by EgggyBoi** [comment]
https://github.com/Low-Drag-MC/LDLib-Architectury/issues/29
