### ISSUE TITLE
[Crash]: Crash to Desktop on recipe lookup (Possibly JE Mek Multiblocks) MC 1.20.1

### ISSUE THREAD

**Issue by Phosphonothioic** [mezz/JustEnoughItems#3637]
### Steps to Reproduce the Crash

1. Click JEI menu entry for Create Mill(Cobblestone)
2. Right-click Gravel
3. Saves World -> Dumps to Desktop

### Crash Report

https://gist.github.com/Phosphonothioic/608b23613432c1b0adaf6b354140adc1

**Comment by mezz** [comment]
Thanks for the report!
I think this is the same issue: https://github.com/gisellevonbingen-Minecraft/JustEnoughMekanismMultiblocks/issues/14
