### ISSUE TITLE
IRecipe support

### ISSUE THREAD

**Issue by ThexXTURBOXx** [mezz/JustEnoughItems#364]
Hello mezz,
I want to add a custom recipe (A class, which implements IRecipe) to JEI. I have tried serveral things, but I can't figure out how it really works. Is there a way, that I can register recipes to JEI like the GameRegistry-recipes (my recipe adds some NBT, a normal recipe wouldn't work for me).
Something like JEIApi.registerShapelessRecipe(Object ... o); would be awesome!

**Comment by TehNut** [comment]
Implement a recipe wrapper.

**Comment by ThexXTURBOXx** [comment]
Wow, thanks! Didn't know those are for this purpose. Sorry
