### ISSUE TITLE
[Bug]: Armor trim visual bug

### ISSUE THREAD

**Issue by Vee-ee** [mezz/JustEnoughItems#3640]
### Steps to Reproduce the Bug

1. Click 'u' on any armor (preferrably not iron chestplate)
2. View Smithing Table Recipes
3. All armor trim recipes appear as an Iron Chestplate with Redstone Coast Armor Trims

### Expected Behavior

Displaying of the proper recipe, or at least proper armor part.

### Actual Behavior

Only iron chestplates appear to have armor trim recipes

### Mod Pack URL (Optional)

Using a custom modpack

### Extra Notes (Optional)

![image](https://github.com/user-attachments/assets/371c0f5a-8f51-46be-96fb-09f80633d79f)

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the next release, available shortly.
