### ISSUE TITLE
[Bug]: Moving receipt to crafting grid is broken in .25 version

### ISSUE THREAD

**Issue by uhloin** [mezz/JustEnoughItems#3644]
### Steps to Reproduce the Bug

Install
MC 1.20.1
Forge 47.1.100
Curios API 5.9.1
Integrated Dynamics + Integrated Terminals
or
Refined Storage + Universal Grid
Put to curious slot Portable Storage Terminal or Wireless Universal Grid
Open it
Click some craftable item in the right panel of JEI

### Expected Behavior

Receipt for item is moved to crafting grid
Until jei-1.20.1-forge-15.8.2.24.jar 

### Actual Behavior

Receipt for item is NOT moved to crafting grid
Since jei-1.20.1-forge-15.8.2.25.jar

**Comment by mezz** [comment]
Thanks for the report!
That's strange, the only change between 24 and 25 is this single line, removing an unused line of code: <https://github.com/mezz/JustEnoughItems/commit/c9249125fa98b2035f91c14ffea125fe36f61b9e>
I think it is not possible for that change to break recipe transfers, so I am not sure what the issue may be.

Can you link your latest.log here so I can see what's happening?

**Comment by uhloin** [comment]
Yes, you are right, it looks impossible. May be bug disappears, because I reloaded Minecraft after replace .jar, but not because replacement itself. I will re-check all things and will write a bit later.

**Comment by uhloin** [comment]
When I replace a JEI version again to .25, the bug is not reproduced. So, probably, the bug was from another mod and temporary. I'm sorry to disturb you :(

**Comment by mezz** [comment]
Ok strange! In any case I'm glad it's working again.
