### ISSUE TITLE
[Bug]: Move Items Doesn't Show For Adventure Backpacks

### ISSUE THREAD

**Issue by King909YT** [mezz/JustEnoughItems#3645]
### Steps to Reproduce the Bug

1.Equip an Adventure Backpack with the crafting upgrade
2.Have the crafting grind open
3.Select any recipe
4.Notice that there is no "Move Items" icon
5.Open a regular crafting table in order to verify the icon does appear when using a normal crafting table

### Expected Behavior

the "move items" icon would appear as it does in the 15.3.0.8 version of the mod

### Actual Behavior

nothing happens "move items" icon doesn't appear.

### Mod Pack Version (Optional)

1.20.1

### latest.log

https://gist.github.com/King909YT/495caa45ce7ced616c194f0d7b6da37c#file-gistfile1-txt

**Comment by mezz** [comment]
Thanks for the report!
Each mod adds their own support for this feature in their JEI plugin.
Please report this to Adventure Backpacks and link back to this issue.
