### ISSUE TITLE
[Suggestion]: Let JEI exclude from search without prepending a search

### ISSUE THREAD

**Issue by Luningor** [mezz/JustEnoughItems#3647]
### Suggestion

As of today, JEI lets you exclude things from a search with the "-" symbol. Yet, for some reason, you need to have a previous search to be able to exclude from said search. (Eg: "@create -brass" for every item of create except brass). My request is to be able to make searchs only excluding (Eg: "-logs -diamond -et cetera") to be able to filter the catalog.
I'm currently making a large modpack that adds many enchantments and potions. If I want to search for only those, i go "potion|enchantment"; but if I want everything BUT I'd have to put something like "@example -potion -enchant | @examplo -potion -enchant", and it's time consuming and outright impossible if the amount of mods is too great (which in my case, is). JEI is one of the biggest tools at my disposal for item searching, and I believe this feature would greatly benefit it.

**Comment by mezz** [comment]
Thanks for the suggestion!
This seems a little silly to me but I don't see why not!
Let me see if I can implement it real quick.

**Comment by mezz** [comment]
I have pushed this feature to 1.20.1 and 1.21, enjoy!

**Comment by Luningor** [comment]
You're great! Ily, be checking it now  ^^
