### ISSUE TITLE
JEI Key binds overwritten on startup

### ISSUE THREAD

**Issue by PaisleyP** [mezz/JustEnoughItems#365]
I'm runnning JEI .234 with a few forge versions now (.2011+). 
Toggle item list overlay default is "cmd+o " and am trying to changed it to just "o" but after restarting minecraft it always reverts back to "cmd+o". In fact changing it to any other key will revert it back to cmd+ key.

**Comment by mezz** [comment]
Thanks for the report!
JEI uses Forge's keybinding system, so this is a bug in the latest Forge. 
I'll take a look and see if I can replicate this issue and fix the bug there.

**Comment by mezz** [comment]
Actually it's already pretty late so I will check it out tomorrow. Definitely a high-priority bug though.

**Comment by mezz** [comment]
I submitted a Forge PR to fix this issue.

**Comment by OcAMD** [comment]
I just wanted to let you know this is back with jei_1.11.2-4.2.4.229.jar and forge-1.11.2-13.20.0.2227.
