### ISSUE TITLE
[Crash]: Game crashes when changing URL in Waterframes mod while JEI is installed

### ISSUE THREAD

**Issue by FrittenFrachter** [mezz/JustEnoughItems#3651]
### Steps to Reproduce the Crash

Install the Waterframes and JEI mods.
Start the game and place a TV or Projector block from the Waterframes mod.
Right-click the TV to change the URL.
After 2-5 times of changing the URL, the game crashes with the mentioned error (Error: java.lang.IllegalArgumentException: width must be >= 0)

### Mod Pack URL (Optional)

Upload in Extra Notes

### Extra Notes (Optional)

Whenever I try to change the URL on the TV in the Waterframes mod, the game crashes. This issue only occurs when I have JEI installed. The error message mentions an IllegalArgumentException: width must be >= 0. Here are the details:

Minecraft Version: 1.20.1
Forge Version: 47.3.1
Waterframes Mod Version: 2.0.14
JEI Version: 15.8.2.25
[crash-2024-08-02_17.51.28-client.txt](https://github.com/user-attachments/files/16473913/crash-2024-08-02_17.51.28-client.txt)
[Minecraft Server v2 (Shader).zip](https://github.com/user-attachments/files/16473989/Minecraft.Server.v2.Shader.zip)

### Crash Report

https://github.com/user-attachments/files/16473913/crash-2024-08-02_17.51.28-client.txt

**Comment by mezz** [comment]
Thanks for the report!
It looks like their GUI might be going off the edge of the screen for a moment and JEI crashes when trying to do the math to draw next to it, let me see if I can protect against the crash.

**Comment by mezz** [comment]
Hmm I might have already fixed this actually, can you try with the latest version of JEI?

**Comment by FrittenFrachter** [comment]
Hi mezz,

Thank you for the quick response!

I have updated JEI to the latest version on both my PC and the server, but the game still crashes with the following error:

The game crashed whilst rendering screen
Error: java.lang.ArithmeticException: integer overflow

**Comment by mezz** [comment]
Thanks for checking. 
Wow ok. I think their GUI is doing something pretty crazy, let me try to add more defenses.

**Comment by mezz** [comment]
While I try to stop this crashing on my side, can you also report this to the Waterframes mod and link back here?
There is likely something wrong with their GUI in this situation, without JEI installed.

**Comment by mezz** [comment]
I have pushed a new version, please try it out and let me know if it works.
Please include the latest client log, so I can see if JEI is properly detecting the error and logging information about it.

**Comment by SrRapero720** [comment]
CreativeCore has a small protection against it, when the gui overflows the screen size it automatically changes the GUi scale, but there's a small frame when the GUI overflows (vertically and horizontally). and that small frame is what causes the crash on JEI

**Comment by mezz** [comment]
Ok thanks, it looks like I was protecting against the wrong thing. I'll add some extra checks.

**Comment by mezz** [comment]
I'm not able to replicate the bug on the latest JEI any more, please let me know if there are some specific dimensions (guiTop, guiLeft, 		xSize, ySize, width, and height) that I can try out.

**Comment by FrittenFrachter** [comment]
Hi mezz,

Thanks for the update. The crash doesn't occur anymore on my end, it seems to be fixed. Just to clarify, do you need any additional details from me regarding specific dimensions, or is this message mainly for the SrRapero720?

Thanks again!

**Comment by mezz** [comment]
Ah, I just wanted to know if there were some situations that the new version of JEI still crashed on.
Thanks for confirming the fix!
