### ISSUE TITLE
[Crash]: Maybe still ldlib?

### ISSUE THREAD

**Issue by forteen14desu** [mezz/JustEnoughItems#3654]
### Steps to Reproduce the Crash

1. open Minecraft with gtm and jei
2. create a world
3. check any recipe in jei
4. boom

### Extra Notes (Optional)

I know they have already fixed it once, but it seems like a new problem has arisen

### Crash Report

https://gist.github.com/forteen14desu/144e5645cf074d46c130dc813faa971d

**Comment by mezz** [comment]
Thanks for the report!
I am working on a long-term solution with LDLib so that they don't have to use JEI internals (which break when JEI updates). 
The big changes on my side were just merged yesterday and now they are working on their side.
