### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Cgood19** [mezz/JustEnoughItems#3658]
### Steps to Reproduce the Bug

i do not know how i did it but it involves the mekanism mod and i think the fact that all of the machines have unique nbt data

### Expected Behavior

items show up one time on the bookmark menu

### Actual Behavior

items show up multiple times on the bookmark menu

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-to-the-sky

### Mod Pack Version (Optional)

1.0.6

### Extra Notes (Optional)

![image](https://github.com/user-attachments/assets/8ff12afa-6f78-49fd-8270-eeae6efaa915)

### latest.log

https://gist.github.com/Cgood19/7cac557e1cee83a366f3317622ea8b42

**Comment by Cgood19** [comment]
i pressed the add/remove button on the heater and it added it i dont think its exclusive to the heater but its definitely the mod

**Comment by Cgood19** [comment]
also where is the data for the bookmarks so i dont have to wait until the next update to fix this

**Comment by mezz** [comment]
Thanks for the report!
I have no idea how this is possible, there should only be one bookmark created per input (click or button press) and it shouldn't create duplicates.

Are you able to replicate this bug so that it happens again?
Can you replicate it in a pack that only has JEI and Mekanism?

**Comment by Cgood19** [comment]
i managed it and i think it has to do with the tag involving how much
energy is stored in the block but i wasnt able to magnag to recreate it to
the extent that i did in my report, only three copys
