### ISSUE TITLE
[Bug]:  JEI disappears on server when some specific mods are together.

### ISSUE THREAD

**Issue by Dumpling00** [mezz/JustEnoughItems#3659]
### Steps to Reproduce the Bug

Hello, so this is a weird one that I had happen some time ago and eventually figured I'd simply leave the incriminating mods out of the modpack but I'm starting to find this issue more and more and some of these mods I REALLY want to have.
This might not be an issue with JEI specifically as it seems to also affect the vanilla recipe book, so I'm not sure if anything can be done about it but hopefully we could shine some light on it?

The premise: To understand the kind of behaviour I'm noticing with some of these mods and the way the issue presents itself, I'd like for you to, for the sake of argument, go by the assumption that each Mod has a "hidden value" that could be X, Y or Z.

Mod A has value X and Y.
Mod B has value X and Z.
Mod C has value Y and Z.

Things work fine with Mod A and B, but adding C to the mix causes JEI to not show up on the user end.  For some reason, Deleting eather Mod A or B (sometimes both), resolves the issue, but now you have to leave those mods out.

The first case I had this happen was when I added Clutter to my modpack. Thought that Clutter was itself the problem, but I tried a new instance with only Clutter and JEI, and no issues there. So I started taking out mods, and it seemed like the mods Handcrafted and Sawmill caused this issue I'm described. I really wanted Clutter, so I had to give up Handcrafted and Sawmill for it.

More recently, I've been finding this issue with the following mods, adding them to my current modpack (individually) causes JEI to disappear.
- Hephastus
- Create Vibrant Vaults
- Regions Unexplored
- Wilder Wilds
- Biomes We've Gone (and possibly Trees We've Grown since it's a dependency)
- Enchanted Vertical Slabs

I know that one of these conflicts with BetterNether or Better End - I think either Hephastus or Regions Unexplored?

Granted this is a shot in the dark for the others, as the mods that cause conflict haven't been fully identified and the modpack is something I've been putting together personally and has 330 mods, but any chance this could be looked into? It seems to be an issue with how the client is parsing the recipes from the server but at the same time this is completely server based: JEI shows up when playing single player and, when hosting a world with Essential Mod, the host has full access to JEI while players connecting have this issue I've described. Client doesn't have to do anything to fix the issue: The host/server has to remove the mods that cause the issue.

Anything that can cast light on what causes this to happen, would make things immensely easier to troubleshoot.

Thank you so much for your time.

### Expected Behavior

Well, JEI and Vanilla recipe book working as intended.

### Actual Behavior

Described above

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
