### ISSUE TITLE
Crash upon picking world

### ISSUE THREAD

**Issue by Starrtic** [mezz/JustEnoughItems#366]
Game crashes after I pick a world in single player

crash report:
https://gist.github.com/Starrtic/c42b9064e7ccdd09c06a1614370a4e20

**Comment by TehNut** [comment]
Seems to be caused by Actually Additions

**Comment by mezz** [comment]
Thanks for the report!
Yes, please report here: https://github.com/Ellpeck/ActuallyAdditions/issues

**Comment by Starrtic** [comment]
I deleted Actually Additions and it works! Thanks! This is probably my favorite mod along with Xaeros mini map so Im so glad you helped me figure it out. :)

**Comment by mezz** [comment]
I'm glad! Please report the issue to them so they can fix it.
