### ISSUE TITLE
[Bug]: Cheat mode cannot be activated using ctrl + left click

### ISSUE THREAD

**Issue by LioxAcc** [mezz/JustEnoughItems#3660]
### Steps to Reproduce the Bug

jei-1.20.1-forge-15.10.0.29
Having the cursor over the jei config button and giving it ctrl + left click

### Expected Behavior

Cheat mode should be activated

### Actual Behavior

Nothing happens

### latest.log

https://gist.github.com/LioxAcc/b19644e81e8561ef38f1cf27cdc748db

**Comment by R15B** [comment]
seeing similar behaviours, testing rollback from todays release version.
Rolled back and behaviours persist, likely a mod conflict~

**Comment by kingslycamben** [comment]
Facing a similar problem, rolling back to version 15.8.2.26 fixed it.

**Comment by Dani20000** [comment]
Same thing, had to rollback to 15.8.2.26

**Comment by Looodon** [comment]
Facing the same problem, just downgraded as well

**Comment by mezz** [comment]
Thanks for the report!
This will be fixed in the next release, available shortly.
