### ISSUE TITLE
[Bug]: "Move Items" not working in Extended Crafting Table

### ISSUE THREAD

**Issue by jerem2772** [mezz/JustEnoughItems#3665]
### Steps to Reproduce the Bug

Open the ultimate crafting table, clic on a craft in JEI, try to add all items to craft the recipe, and nothing happens.
![Capture d'écran 2024-08-06 151514](https://github.com/user-attachments/assets/449834af-6911-44ba-b8b7-d1a4ab28e672)

### Expected Behavior

All items add in the Ultimate crafting table in right position.

### Actual Behavior

Nothing happens

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/ozone-skyblock-reborn

### Mod Pack Version (Optional)

1.9.3

### Extra Notes (Optional)

I tried with the lastest version of JEI 15.10.0.34 and this bug is always present.

I run the modpack on a server.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by jerem2772** [comment]
https://gist.github.com/jerem2772/a0a8002613729fc107f3f80c5f2f56d0

**Comment by mezz** [comment]
Thanks for the logs. Unfortunately I didn't find anything wrong there.
Can you please report this to the Extended Crafting Table devs and link back to this issue so I can follow it too?

**Comment by jerem2772** [comment]
Yes I can, but why it's work with the JEI 15.3.0.8 and didn't with the last version ?
I replaced the last version of JEI with the old one (same as 1.9 modpack release) and + button work well with ultimate crafting table

EDIT : Extended Crafting issue
[https://github.com/BlakeBr0/ExtendedCrafting/issues/189](url)

**Comment by muggleorwizard** [comment]
BlakeBr0/ExtendedCrafting#189

**Comment by muggleorwizard** [comment]
Can confirm that this was working in version 15.8.0.11, which I am downgrading my modpack to in order to get functionality back. Not working in newer releases.

**Comment by mezz** [comment]
Thanks, I was able to try this out and confirmed the bug. I'll have a fix soon.

**Comment by mezz** [comment]
This issue happens when a mod moves the recipe transfer button somewhere that overlaps the recipe.
It's a normal thing for them to do, the bug is in JEI.

**Comment by mezz** [comment]
I have pushed a fix and confirmed this is working again in JEI `15.11.0.43`
