### ISSUE TITLE
[Bug]: Tech Reborn Machine uses for ingredients do not show up

### ISSUE THREAD

**Issue by Ital1anJ** [mezz/JustEnoughItems#3666]
### Steps to Reproduce the Bug

1. Install JEI and Tech Reborn
2. Right click or tap U over an ingredient/resource

### Expected Behavior

Following the steps to reproduce the bug, there should be a GUI tab for each applicable Tech Reborn machine showing the uses for that resource with applicable Machines. This was the case in older versions of Minecraft.

### Actual Behavior

All GUI tabs appear for other mods and Vanilla Minecraft itself but not for Tech Reborn.

**Comment by mezz** [comment]
Thanks for the report!
I am not sure why, but it looks like TechReport for Fabric does not have JEI support: https://github.com/TechReborn/TechReborn/issues/3202

**Comment by mezz** [comment]
I talked to modmuss, and the project may support JEI in the future but it's understandably a lot of work to support all the different recipe viewers. Support may take some time.
