### ISSUE TITLE
[Crash]: java.util.ServiceConfigurationError

### ISSUE THREAD

**Issue by KCtops6** [mezz/JustEnoughItems#3667]
### Steps to Reproduce the Crash

Hello, after doing some mod updates on my own modpack, the game crashes on startup.  I narrowed it down to this mod, but I believe there is some incompatibilities with others.  I am not sure what the issue is specifically, so help is appreciated.

### Crash Report

https://gist.github.com/KCtops100/e6b5cc88117d4271177eda6953fc0fcc

**Comment by mezz** [comment]
Thanks for the report!

This crash is quite hard to read but I have seen it before, it appears to be caused by `gtceu` (Greg Tech CE Unofficial Modern)
```
	Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method gtceu$injectFluidTooltips(Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraft/world/item/TooltipFlag;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in gtceu.mixins.json:jei.FluidHelperMixin failed injection check, (0/1) succeeded. Scanned 2 target(s). Using refmap gtceu-1.20.1-refmap.json
```

Please report this to their issue tracker here: https://github.com/GregTechCEu/GregTech-Modern/issues
and link back to this issue
