### ISSUE TITLE
[Bug]: Fabric 1.20.1 - 15.10.0.36 "Ignoring invalid ingredient: 0 air minecraft:air" when clicking empty slot.

### ISSUE THREAD

**Issue by Sansomeness** [mezz/JustEnoughItems#3669]
### Steps to Reproduce the Bug

Boot Minecraft with just Fabric API & JEI installed.
Left Click/Right Click/R/U key while hovering over empty inventory slot.

### Expected Behavior

Nothing should be written to log.

### Actual Behavior

The log receives two of this warning:
[Render thread/WARN]: Ignoring invalid ingredient: 0 air minecraft:air

### Extra Notes (Optional)

This bug is also present in 15.10.0.35.

### latest.log

https://gist.github.com/Sansomeness/f33e6427efd2386e747ce32274c19d2a

**Comment by Zelioth** [comment]
This appears to be an issue in 1.21 NeoForge as well. 

JEI 19.7.0.90
NeoForge 21.0.163

![image](https://github.com/user-attachments/assets/d89a0063-952f-4c81-92ee-a01a7ac1c9ce)

**Comment by mezz** [comment]
Thanks for the report!
This is pretty excessive and not what I intended, I'll remove this log.

**Comment by mezz** [comment]
I have pushed fixes for this on 1.21 and 1.20.1
