### ISSUE TITLE
[Suggestion] Adding a  interface for the Click Area's like the IAdvancedGuiHandler

### ISSUE THREAD

**Issue by Nedelosk** [mezz/JustEnoughItems#367]

**Comment by shadowfacts** [comment]
You mean being able to add an area on the GUI that you can click to see a list of all the recipes? `IModRegistry#addRecipeClickArea` does that.

**Comment by Nedelosk** [comment]
Yes but there is no way to say, that a recipe area is only active when ....

**Comment by mezz** [comment]
What do you need this for? I do not understand completely.

**Comment by Nedelosk** [comment]
I require it for a gui that handle more than one recipe, but not at the same time.

**Comment by mezz** [comment]
That sounds like a good suggestion.

For now you can make your own button and call `IRecipesGui.showCategories(...)` in the API.

**Comment by codewarrior0** [comment]
GTCE uses a modular gui system where all of the GUIs are instances of the same class, so the class-based `addRecipeClickArea` isn't really usable.

**Comment by mezz** [comment]
This suggestion has been implemented in the 1.13 version of JEI:
https://github.com/mezz/JustEnoughItems/blob/4bd3727026bd448f1acba00ef3bdbf91a3a5bab7/src/api/java/mezz/jei/api/gui/handlers/IGuiContainerHandler.java#L45-L51

It is not in 1.12, it required some API and internal changes.
For 1.12 it is much less convenient, but you can make your own button and call `IRecipesGui.showCategories(...)` in the API.
