### ISSUE TITLE
[Suggestion]: Support for LOLCAT language

### ISSUE THREAD

**Issue by vvollpp** [mezz/JustEnoughItems#3671]
### Suggestion

Support for the lolcat language in-game would be an amazing feature. You should be able to type in the English word (maybe add an option where you can pick a different language than English too) for whatever you're looking for even while the game is in lolcat, because as it is now, you really can't find anything.
For example: an ender eye is called "teh evil eye" which you simply cannot know if you've never heard it. If you forgot how to craft  a powered rail and want to use JEI for it, you'd have to know that it's "PUWERD RAIL". Normal rails are called "TRAKZ", even though both are rails. Wanna know how to craft a recovery compass because it's new and you never crafted it? Good luck figuring out it's called "Deth findr v1.0". There's so many more examples as to why you can't use JEI when playing in lolcat, other great ones are all ores and, especially, potions and arrows. Some ingots are called "ingot", some "ingut". There's "shiny", "shini", "shinee", "shineee", "shineh", "glowy", etc. etc. It's really just a pain to try and find what you're looking for.
I'd really appreciate if you could at some sort of translation for the JEI search when playing lolcat since it's not an actual language.
If this has been talked about already, I apologize. The search on this github didn't show anything.

**Comment by mezz** [comment]
JEI should work properly with any language added to Minecraft, it indexes and searches strings in the language you choose. Even the Pirate language works as expected, for example.

**Comment by vvollpp** [comment]
Doesn't work for lolcat apparently. Typed "slime" in the search and only a spawn egg from a mod showed up. Neither the slime ball nor slime block show up. This is the case for every item
![image_2024-08-07_142637581](https://github.com/user-attachments/assets/4ff181e5-0f1b-47b2-a771-3c94ee2ee70f)
![image_2024-08-07_142658056](https://github.com/user-attachments/assets/e5ceac6c-dff7-46be-84f6-29b1feefcece)

**Comment by mezz** [comment]
Alright I see I misunderstood your request.

Unfortunately it is not simple to support multiple languages in the search at once, the game is really serious about changing the language when you click the setting, so I can only access one language at once. 
I recommend choosing your native language or studying to become more proficient at lolcat.

**Comment by vvollpp** [comment]
Alright, thanks a lot. I thought it'd be easier to use multiple languages, but if the game isn't allowing you to, I can see why you can't implement that. Thanks for the clarification

**Comment by vvollpp** [comment]
I now installed Roughly Enough Items (REI) because JEI doesn't show recipes for the Better End mod for some reason, but now I've also noticed that REI does indeed have my requested feature. You can type in English terms and they'll show up even with LOLCAT language selected.
Maybe you, or whoever is in charge of JEI, could reach out to the dev of REI and ask for help on how to do it, since they apparently found a way? Would be nice to see the two "competitors" help each other

**Comment by mezz** [comment]
Does REI allow searching in both languages at once, or just English?

**Comment by vvollpp** [comment]
Yes, it does. Just checked.
![image](https://github.com/user-attachments/assets/116ff740-7554-4075-b61d-9a15224ea745)
![image](https://github.com/user-attachments/assets/5dfef500-4970-470f-9d00-5272d045cf37)
