### ISSUE TITLE
[Bug]: The vanilla Minecraft search function in creative mode does not work when JEI is installed with the Better MC modpack.

### ISSUE THREAD

**Issue by Francoprox004** [mezz/JustEnoughItems#3672]
### Steps to Reproduce the Bug

1- Download the Better MC [FABRIC] modpack - BMC2 (Download it with the curseforge launcher to get all the configurations and files of the pack)

2- Install JEI for Fabric version 1.20.1 and remove REI from the modpack

3- Put yourself in creative game mode, when you put any letter in the minecraft object search engine, absolutely nothing will appear

### Expected Behavior

If the problem is solved, search results should appear in the vanilla search engine in creative mode

### Actual Behavior

Currently, when you put any letter in the vanilla search engine of Minecraft in creative mode, no results appear.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/better-mc-fabric-bmc2

### Mod Pack Version (Optional)

1.20.1 Fabric

### latest.log

https://gist.github.com/Francoprox004/72cc149c8dd4900b7a9d6fff9c9d8e39

**Comment by mezz** [comment]
Thanks for the report!

Unfortunately I was not able to reproduce this bug with only JEI installed.
It seems like another mod is conflicting with JEI or causing an issue here.
Please try removing mods to figure out which one is causing a problem.

If you find that there is only one other mod causing an issue, please report it to them and link back here.
Otherwise if you still can't figure it out, please paste your new crash log and client logs here, and I can help debug or find the right place to report to.

**Comment by Francoprox004** [comment]
> Thanks for the report!
> 
> Unfortunately I was not able to reproduce this bug with only JEI installed. It seems like another mod is conflicting with JEI or causing an issue here. Please try removing mods to figure out which one is causing a problem.
> 
> If you find that there is only one other mod causing an issue, please report it to them and link back here. Otherwise if you still can't figure it out, please paste your new crash log and client logs here, and I can help debug or find the right place to report to.

Hi! I just found where the problem is.

I was testing, removing and removing mods until I found the culprit, and the "Modern Fix" mod is the culprit.

https://www.curseforge.com/minecraft/mc-mods/modernfix

After finding the mod that causes the problem, I did a test by putting the latest version of JEI, the Fabric API and the same Modern Fix that comes with the Better Minecraft modpack in a new instance, and the error occurred again.

I've been trying several different versions of Modern Fix and the ones that cause the problem are:

modernfix-fabric-5.17.0+mc1.20.1 (this is the version that comes with the better minecraft modpack, so I tried from this version onwards)
modernfix-fabric-5.18.0+mc1.20.1
modernfix-fabric-5.18.1+mc1.20.1
modernfix-fabric-5.18.6+mc1.20.1

starting with version "modernfix-fabric-5.18.9+mc1.20.1" the JEI compatibility bug was fixed.

So that's it, I don't know if you can fix the bug for those specific versions or if it's not really a JEI problem but a modern fix problem (which has already been fixed) and the creator of better minecraft who could update the mod in his modpack (although JEI is not installed by default in the modpack)

**Comment by mezz** [comment]
Ok thanks for narrowing it down!
This isn't really a JEI problem, so I think your best option is to encourage the pack maker to update modernfix. There may be other bug fixes in there too, so it should be worth updating.

**Comment by kylelaverty** [comment]
In case anyone is looking for a temp fix, setting mixin.perf.blast_search_trees=false will fix the issue at least in 5.19.4+mc1.20.1 and 5.19.5+mc1.20.1.
