### ISSUE TITLE
[Other]: Keybinds Doesnt show

### ISSUE THREAD

**Issue by clientwareoncw** [mezz/JustEnoughItems#3675]
### Other

Hey jei staff in the keybinds menu i dont find the jei and i want to change a keybind

**Comment by clientwareoncw** [comment]
still got no help ;(

**Comment by milkyt0p** [comment]
i have the same issue :(

**Comment by mezz** [comment]
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3000

Key bindings for Fabric have been implemented in JEI 
for 1.20.1: `15.18.0.80`+
and 1.21.1: `19.17.0.196`+
