### ISSUE TITLE
[Bug]: Connection Lost, Network Protocol Error screen when enabling Cheat mode in single player vanilla 1.20.6

### ISSUE THREAD

**Issue by DreamMoon23** [mezz/JustEnoughItems#3677]
### Steps to Reproduce the Bug

Nothing, just install play try to enable cheat mode

### Expected Behavior

installed mod tried to enable cheat mode Kicked from singe player world, no crash just brought to the menu screen saying "Connection Lost Network Protocol Error"

### Actual Behavior

Kicked to menu screen sayin "Connection Lost Network Protocol Error"
![Screenshot 2024-08-09 214805](https://github.com/user-attachments/assets/eaf7efaf-b180-49bf-994c-163ad2809993)

### Extra Notes (Optional)

Never had a problem with JEI in the past till now

### latest.log

https://gist.github.com/DreamMoon23/5bd32f8f9bc8120a7811a375a7242718

**Comment by mezz** [comment]
Thanks for the report! 
Strangely, 1.20.6 is not generally supported by the mod community. 
Please use version 1.20.1 or 1.21.1 where this issue has been resolved.
