### ISSUE TITLE
[Bug]: cheat-mode mouse-pickup drops items from inventory [1.21][fabric][v19.7.0.92]

### ISSUE THREAD

**Issue by Sethgno** [mezz/JustEnoughItems#3678]
### Steps to Reproduce the Bug

- enable mouse-pickup mode
- enable cheat mode
- select an item from JEI menu
**!** upon opening inventory, the first item clicked on will be picked up as intended.
but subsequent items are dropped from players inventory

### Expected Behavior

hi

### Actual Behavior

using cheat mode while mouse-pickup is active will cause all subsequent items after the first one selected to drop outside players inventory.
this is most probably a duplicate of #3185 , but on a different version so making this issue just to be safe

### Extra Notes (Optional)

picking up items with the block-select key works fine

**Comment by mezz** [comment]
Thanks for the report!
This will be fixed in the next release, available shortly.
