### ISSUE TITLE
cant press button.

### ISSUE THREAD

**Issue by naoromi** [mezz/JustEnoughItems#368]
while i was using this mod i searched some items and after going into cheat mode to get it the menu (on the right) was frozen. even thought i can still press the buttons and hear the click it wont respond. P.S i switched it back to recipe mod in the config but it still wont respond.

**Comment by mezz** [comment]
Thanks for the report!
Are you using FEI or another mod that changes how JEI works? 
Can you paste a screenshot?

**Comment by naoromi** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/20616603/17081546/8996e4c8-5112-11e6-8b1d-8d810cc3db70.png) 
. sorry for the low res. but the mods are BetterCombat,Better sprinting mod, EnderBags,InvintoryTweaks,JustEnoughItemes,MArines Armor and Weapons, Ninjagear, Optifine, ReinforcedTools,RikMuldsCore, RoguelikeDungoens, 
theCampingMod, VeinMiner, Waila, And XaerosMiniMap. I dont think any of these mods modify JEI in anyway.

**Comment by mezz** [comment]
I'm not able to reproduce this issue. Are there any steps to cause it to happen reliably?
