### ISSUE TITLE
[Bug]: JEI not showing percentage chance of secondary outputs.

### ISSUE THREAD

**Issue by Phosphonothioic** [mezz/JustEnoughItems#3681]
### Steps to Reproduce the Bug

JEI recipes (in this case: Crushing beetroots) do not display % chance for secondary output (seeds). Not sure what is doing this.
![2024-08-12_17 46 50](https://github.com/user-attachments/assets/78eb5af5-27fc-42e7-a6e4-46fa4a3d47ad)

### Expected Behavior

Recipes shows % chance of secondary output(s)

### Actual Behavior

% chance of secondary outputs not shown.

### latest.log

https://gist.github.com/Phosphonothioic/719d3b424c7b4a357b6a838a1a9c73f2

**Comment by mezz** [comment]
Thanks for the report!
I broke something with tooltip callbacks recently, and fixed it in the latest version.
Please try out the latest version and confirm if you can see the correct tooltips again.

**Comment by Phosphonothioic** [comment]
Issue still exists. jei-1.20.1-forge-15.12.2.51.

Let me know if you'd like me to try anything.

**Comment by mezz** [comment]
This is the same underlying issue as https://github.com/mezz/JustEnoughItems/issues/3683

This bug has been resolved in JEI `15.12.2.52`
