### ISSUE TITLE
[Crash]: Fabric 1.21.1 crashing on launch

### ISSUE THREAD

**Issue by Legends0356** [mezz/JustEnoughItems#3682]
### Steps to Reproduce the Crash

So the game crashes for me right away as I launch.
![image](https://github.com/user-attachments/assets/7292933e-5178-45bc-92b5-d52ce7e32f06)
I have only the mod and the fabric API which is required.
![image](https://github.com/user-attachments/assets/e345d75e-ca50-489f-93ad-dc3c5e8c3c71)

### Crash Report

I cant find any crash report page 
![image](https://github.com/user-attachments/assets/ac7a1634-1d70-4d9c-89b0-71cf41efb0b1)
I only found some java file with crash in the name and this gist is the stuff that was inside
![image](https://github.com/user-attachments/assets/b04a5cca-e101-4319-afb3-d986a1f0c5d4)

https://gist.github.com/Legends0356/a255235698e6a4f0a0c27bd2210a15d6#file-gistfile1-txt

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by unknowncicada** [comment]
I have the same issue but i get this error 

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric API' (fabric-api) 0.102.0+1.21.1 with version 0.102.1+1.21.1 or later.
More details:
	 - Mod 'Just Enough Items' (jei) 19.8.4.113 requires version 0.102.1+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Legends0356** [comment]
> Thanks for the report! I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

Where do I get the fml latest log?

**Comment by mezz** [comment]
Logs are in the `logs` folder, next to the `mods` folder in your minecraft folder.
Depending on what launcher you use, the name of the file may be different.
