### ISSUE TITLE
[Other]: i get this ingredient crashed 

### ISSUE THREAD

**Issue by MasterQuentus** [mezz/JustEnoughItems#3684]
### Other

in jei i hover over certain items and get a red text that says this this ingredient crashed when getting its tooltip please see the client logs for detailed information i look at the logs but dont understand what's going on i crashes when hovering over the item in my inventory but not in jei  
![2024-08-13_02 10 13](https://github.com/user-attachments/assets/2b4e0ae6-be5e-4837-a3cc-010cdfe57e06)

**Comment by mezz** [comment]
Thanks for the report!
I need some more information, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by MasterQuentus** [comment]
https://gist.github.com/MasterQuentus/9d07f030b39b5521ec678fa484bf12df

**Comment by mezz** [comment]
Sorry, this log doesn't include anything from JEI.
Either it was cut short or it's from a different run of the game where you never entered a world.

In order to help, I'll need a full client log from a time where you go into a world and see the tooltip error.

**Comment by MasterQuentus** [comment]
I figured it out it was the version of the mod I was using I don't know what caused it but when I downgraded the mod it works now

**Comment by mezz** [comment]
ok, thanks for reporting back
