### ISSUE TITLE
[Suggestion]: Please Add creative tab search for newer versions of the game

### ISSUE THREAD

**Issue by Strealstud** [mezz/JustEnoughItems#3687]
### Suggestion

So in older versions of jei you can search creative tabs like 1.19.2 and below but after 1.19.2 you cant enable the search option please add that option

**Comment by mezz** [comment]
Thanks for the suggestion!
Unfortunately the way creative tabs works has changed and searching these is pretty inefficient and slow now.
I will make it disabled by default, you can enable it.

I also added the creative tab names to the tooltips in the ingredient list.

![Screenshot 2024-08-28 at 11 06 19 PM](https://github.com/user-attachments/assets/1b8299a2-168f-4616-992a-a1d255c4ec34)
