### ISSUE TITLE
[Crash]: JEI crash Minecraft Launcher when I press the inventory key

### ISSUE THREAD

**Issue by danivela12** [mezz/JustEnoughItems#3690]
### Steps to Reproduce the Crash

With mod version jei-1.21-forge-19.8.2.99, Minecraft (v.1.21) crashes when I pressing the E key to view recipes in a new world.

[crash-2024-08-15_19.26.41-client.txt](https://github.com/user-attachments/files/16628572/crash-2024-08-15_19.26.41-client.txt)

### Mod Pack Version (Optional)

jei-1.21-forge-19.8.2.99

### Crash Report

https://github.com/mezz/JustEnoughItems/issues/3690

**Comment by mezz** [comment]
Thanks for the report!
Please update your version of Forge to at least `51.0.31`
