### ISSUE TITLE
[Suggestion]: Mark 1.21.1 files as compatible with 1.21.0 (if they are compatible)

### ISSUE THREAD

**Issue by NielsPilgaard** [mezz/JustEnoughItems#3691]
### Suggestion

Hi there,

If the latest JEI versions work on MC 1.21.0, would you mind marking them as compatible? I'd prefer holding off on updating Enigmatica to 1.21.1 for a little bit if possible.

**Comment by mezz** [comment]
Thanks for the suggestion!
A new release is being built and it should be marked for NeoForge 1.21 and 1.21.1

**Comment by NielsPilgaard** [comment]
Thank you, I appreciate it 😊
