### ISSUE TITLE
[Crash]: Provider mezz.jei.forge.platform.PlatformHelper could not be instantiated

### ISSUE THREAD

**Issue by sugan-reden** [mezz/JustEnoughItems#3692]
### Steps to Reproduce the Crash

1. Open Minecraft
2. Crash before reaching menu with message saying "ERROR DURING MOD LOADING"
3. Get the following window :
![image](https://github.com/user-attachments/assets/4d5e0065-a728-4e38-b439-63694a2cdd40)

### Mod Pack URL (Optional)

https://www.akliz.net/allthemods

### Mod Pack Version (Optional)

0.3.0 + about 5 extra mods

### Extra Notes (Optional)

Hi mezz,

Hope you're doing okay <3

I just recently re-downloaded started created another modpack with ATM9 as the base.  
I updated most mods and the forge loader to the latest then tried launching.  
First launch and I got the error previously described.  

Thank you for your time, work and patience with me.

As always, I hope you have a nice day. Please take care :)

### Crash Report

https://gist.github.com/sugan-reden/3087b5c42554918a5ecd69e4ba691f03

**Comment by mezz** [comment]
Thanks for the report!
Please try updating your pack (ATM 9) to the latest version, everything should work fine.

**Comment by sugan-reden** [comment]
Hi mezz,

Can confirm that staying on versions of the mods provided by the latest version of the ATM9 modpack works.

Thank you for your time :)
And keep up the great work <3 Take care (\*-\*)

*Closing issue.*

**Comment by mezz** [comment]
Thanks for confirming the fix!
