### ISSUE TITLE
[Other]: Curseforge app attempts to "update" JEI back to older version

### ISSUE THREAD

**Issue by Terrawisp** [mezz/JustEnoughItems#3694]
### Other

On the curseforge app, it's consistently saying to update the JEI mod but when I do, it reverts the version from 19.8.5.118 (the latest that I found for neoforge on the actual curseforge webpage for JEI) to 19.8.2.99. At which point, it treats the mod as up to date, even though it's on an older version. This is the case for just about every person who is on my server and uses JEI. Our work around has just been to have people download the updated version from the main page, and then ignore the "update" button but it makes it hard to know when you _do_ release another update. 
![jeierror](https://github.com/user-attachments/assets/326dc341-e70b-4237-ab40-17a53424eede)
![jeierror2](https://github.com/user-attachments/assets/9c416e93-73cf-4529-9d39-b61145fcbfd5)

**Comment by mezz** [comment]
Thanks for the report!
Sorry please report this to CurseForge, I am not sure why it is doing that.
