### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by darrenh2** [mezz/JustEnoughItems#3696]
### Steps to Reproduce the Crash

Crash upon starting a new world

### Mod Pack URL (Optional)

ATM9

### Crash Report

https://gist.github.com/darrenh2/31ee7203b89166f8b00492d55ea236fe

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
