### ISSUE TITLE
[Crash]: On Startup it crashes

### ISSUE THREAD

**Issue by TheUndyingJester** [mezz/JustEnoughItems#3700]
### Steps to Reproduce the Crash

Crashes upon startup

![Screenshot_2024-08-20_151617](https://github.com/user-attachments/assets/3db138fb-0db6-4a33-9d9a-8314f44ada3c)

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/mc-mods/jei/files/5630570

### Mod Pack Version (Optional)

15.12.3.54

### Crash Report

https://gist.github.com/TheUndyingJester/4496cc2747660daf470ed34f40b9cf1d

**Comment by agentwolf88** [comment]
Same

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.
