### ISSUE TITLE
[Bug]: Version conflict

### ISSUE THREAD

**Issue by uhloin** [mezz/JustEnoughItems#3701]
### Steps to Reproduce the Bug

Use jei-1.20.1-forge-15.12.3.55.jar 
with Forge 47.1.100 from neoforged.net site

### Expected Behavior

Support forge 47.1.100 like previous version (.54)
Or support NeoForge for 1.20.1

### Actual Behavior

JEI want forge 47.3.6 +
Such version is present for legacy Forge for 1.20.1
but for NeoForge last version for 1.20.1 is 47.1.106

**Comment by seriousfreezing** [comment]
Fix for now: https://modrinth.com/mod/jei/version/lTsLGis7

**Comment by uhloin** [comment]
Thank you

**Comment by mezz** [comment]
Sorry, NeoForge is not directly supported on 1.20.1.
Please use NeoForge on 1.21.1 or use Forge on 1.20.1.
