### ISSUE TITLE
[Bug]: Smithing recipes are incorrect in jei

### ISSUE THREAD

**Issue by Mrthomas20121** [mezz/JustEnoughItems#3704]
### Steps to Reproduce the Bug

Click on any netherite tool/armor to see its recipes, check the smithing tab.

### Expected Behavior

The smithing recipe tab should show the normal recipe.

### Actual Behavior

it show you the netherite tool/armor in the input slot instead of the diamond tool/armor.

### Extra Notes (Optional)

JEI version 15.12.3.55 for 1.20.1
15.12.3.54 has the same issue btw.

**Comment by mezz** [comment]
Thanks for the report!
Was this resolved somehow or closed by accident?
