### ISSUE TITLE
[Crash]: Lunar Client is incompatible with JEI mod 1.21/1.21.1

### ISSUE THREAD

**Issue by KR99991** [mezz/JustEnoughItems#3709]
### Steps to Reproduce the Crash

1. Download lunar client. Select the 1.21.1 or 1.21 fabric version in lunar client.  3. Install jei mod to lunar client. 4. Launch game.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/mc-mods/jei/files/5623551

### Mod Pack Version (Optional)

jei-1.21.1-fabric-19.8.4.113

### Extra Notes (Optional)

Please fix it, thanks!

### Crash Report

https://gist.github.com/KR99991/7a9982edfe16b8328218399cd7687424

**Comment by mezz** [comment]
Thanks for the report!
The crash log has this error:
```
[2024-08-25 17:02:10.802] [error] 	 - Mod 'Just Enough Items' (jei) 19.8.4.113 requires version 0.102.1+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong versions are present: 0.100.8+1.21/0.100.8+1.21!
```
Please ask Lunar Client devs to fix their fabric-api version string, it seems to be messed up somehow.
