### ISSUE TITLE
Minecraft 1.10 crashes when I load the game with JEI!

### ISSUE THREAD

**Issue by eden-chung** [mezz/JustEnoughItems#371]
I tried using jei_1.10.2-3.7.6.231.jar and jei_1.10.2-3.7.6.232.jar and both of them crash when I start minecraft.

Crash report:
https://gist.github.com/10forever/38c8d2fb9500808642c4ce263723fc43

Forge version:
1.10.2-forge1.10.2-12.18.1.2044

**Comment by TehNut** [comment]
You are using Java 6. You need at least Java 7.

**Comment by eden-chung** [comment]
Thanks!

**Comment by mezz** [comment]
Thanks for the report!
Forge is supposed to give a better error message there, telling you to update Java. For some reason it crashed instead. I have reported it to Forge.
