### ISSUE TITLE
[Bug]: Hiding items & blocks is no longer possible, file resets when reloading world & blacklist.json file only displays "SINGLE" as ID, no actual item/block ids.

### ISSUE THREAD

**Issue by Gbergz** [mezz/JustEnoughItems#3714]
### Steps to Reproduce the Bug

1. Hide any blocks and items.
2. Quit world.
3. Rejoin world.
4. Check item/block you hid
5. Not hidden
profit..

### Expected Behavior

That hiding item and blocks is persistent between loading worlds etc.

### Actual Behavior

They are still visible, not hidden.

### JEI Version
neoforge-19.11.0.130

### Mod Pack URL (Optional)

Empty instance with just NeoForge v21.1.23 & JEI.

### Mod Pack Version (Optional)

Empty instance with just NeoForge v21.1.23 & JEI.

### Extra Notes (Optional)

Hiding blocks and items in JEI was lasing working with version `19.8.5.119`, and stops working above that version.

The blacklist.json file also no longer displays item ids in a list, but rather it displays everything as:
`["SINGLE","SINGLE","SINGLE","SINGLE","SINGLE","SINGLE","SINGLE","SINGLE","SINGLE"]`

then gets reset when rejoining world.

### latest.log

https://gist.githubusercontent.com/Gbergz/451ddfe2aefe9a623df154eb5de30380/raw/0728c05b8b56eb5ab86b6cb2b011064a6df294f9/gistfile1.txt

**Comment by mezz** [comment]
Thanks for the report!
This will be fixed in the next release, available shortly.

**Comment by Gbergz** [comment]
Awesome, thanks for the fix! 👍
