### ISSUE TITLE
[Bug]: JEI doesnt show up information about items

### ISSUE THREAD

**Issue by Gourskiy** [mezz/JustEnoughItems#3716]
### Steps to Reproduce the Bug

move mouse on item
![изображение_2024-08-29_013037650](https://github.com/user-attachments/assets/cf1276dc-6c2f-4fec-8429-6c7d2ff2dcac)

### Expected Behavior

information about item
![image](https://github.com/user-attachments/assets/7d9667f8-f589-4a45-a7af-5f8d7e1fd6f6)

### Actual Behavior

information doesnt given by JEI

### Mod Pack Version (Optional)

15.14.64

### Extra Notes (Optional)

List of mods:
3d-Skin-Layers
Another Furniture
AppleSkin
Applied Energistics 2
Bad Packets
Blood Magic
Bookshelf
Botania
Caelus API
Carry On
Cloth Config v10 API
Collective
Configured
CoroUtil
Create
Create Big Cannons
Create Crafts & Additions
Create Deco
Create Ore Excavation
Create Slice & Dice
Create: Steam 'n' Rails
Create: Structures
Create: Wizardry
Curios API
DataPack Anvil
DivineRPG
e4mc
ElementalCraft
EnchantmentDescriptions
EntityCulling
Ferrite Core
Forbidden & Arcanus
GeckoLib 4
Gravestone Mod
Health Indicator TXF
Highlighter
Iceberg
Inventory Profiles Next
Iron's Spells 'n Spellbooks
Just Enough Items
kotlinforforge-4.3.0-all
libIPN
Lodestone
Malum
Mekanism
Mekanism: Additions
Mekanism: Generators
Mekanism: Tools
ModernFix
Naturalist
OptiFine
Patchouli
Player Animator
Ribbits
Sound Physics Remastered
Terralith
Traveler's Backpack
Tree Harvester
The Twilight Forest
Valhelsia Core
What Are They Up To
wthit
Xaero's Minimap
Xaero's World Map
YUNG's API

### latest.log

https://gist.github.com/Gourskiy/f8a0f005ea78dd129543bee2a5ce189d

**Comment by Gourskiy** [comment]
Looked at logs, found that optifine ruins everything, deleted, all works

**Comment by mezz** [comment]
Thanks for the report and solution!

**Comment by mezz** [comment]
Please report this to Optifine and link back to this issue.
