### ISSUE TITLE
empty recipe freeze [Bug] [Optifine]

### ISSUE THREAD

**Issue by DanHolli** [mezz/JustEnoughItems#372]
I have over 100 mods installed on 1.10.2
every once in awhile when looking at recipes a blank recipe show up and I can't do anything, no crash, no logging about it, can only kill Minecraft and restart
happens to seemingly random items cannot track down what items specifically
also happens without Optifine

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I'm not in a good position to hunt down the issue, since there is not a good way for me to reproduce it. If you can find which item or recipe is involved I can work to solve this issue, but without that there is not much I can do to find the bug.

**Comment by DanHolli** [comment]
I will take a screenshot from outside of minecraft the next time it happens as only minecraft freezes

**Comment by VT-14** [comment]
Holding F3+C for several seconds (10?) should cause a debug crash.  That might show something useful.

**Comment by OUYEAAAAA** [comment]
I have similar problem , when searching something , it will crash . I think it is problem with IC2 

[crash-2016-08-08_14.42.20-client.txt](https://github.com/mezz/JustEnoughItems/files/406823/crash-2016-08-08_14.42.20-client.txt)

**Comment by mezz** [comment]
@OUYEAAAAA that's not the same, please make a new issue.

**Comment by DanHolli** [comment]
@VT-14  I have F3 changed to refresh in linux

**Comment by mezz** [comment]
I'm not able to reproduce this issue. Are there any steps to cause it to happen reliably?

**Comment by DanHolli** [comment]
It happens randomly, even doing the same recipe does not always recreate it (but is most reliable)
got a new computer and updated some mods will get back soon

**Comment by DanHolli** [comment]
still happening even with all mods updated
trying to get log but the last one seems to have dissappered

**Comment by DanHolli** [comment]
never mind the launcher was just lagging with the output
here's the report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  MMFMLCorePlugin (MultiMine-1.10.2.jar)
  LoadingPlugin (Quark-r1.0-55.jar)
  ShoulderPlugin (ShoulderSurfing-1.10.2-1.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.225.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 9/19/16 10:12 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
    at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1948)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1625)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
    at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1948)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1625)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['DanHolli123'/44, l='MpServer', x=74.81, y=6.00, z=2.45]]
    Chunk stats: MultiplayerChunkCache: 169, 169
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,5,-24), Chunk: (at 0,0,8 in 0,-2; contains blocks 0,0,-32 to 15,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 184005 game time, 99197 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 10 total; [EntityDroneBaby['Baby Drone'/5, l='MpServer', x=-1.50, y=7.00, z=12.50], EntityItem['item.item.droneBit'/6, l='MpServer', x=15.96, y=4.00, z=11.39], EntityItem['item.item.droneBit'/7, l='MpServer', x=12.73, y=4.00, z=8.20], EntityItem['item.item.droneModule'/8, l='MpServer', x=14.07, y=4.00, z=20.16], EntityItem['item.item.droneBit'/9, l='MpServer', x=19.94, y=4.00, z=11.27], EntityPlayerDummy['entity.rfpr.PlayerDummy.name'/106, l='MpServer', x=74.81, y=6.00, z=2.45], EntityPlayerSP['DanHolli123'/44, l='MpServer', x=74.81, y=6.00, z=2.45], EntityDroneWildItem['Wild Item Drone'/115, l='MpServer', x=10.50, y=4.00, z=6.50], EntityDroneWildItem['Wild Item Drone'/116, l='MpServer', x=10.50, y=4.00, z=10.50], EntityDroneWildItem['Wild Item Drone'/117, l='MpServer', x=12.50, y=4.00, z=12.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1528517472 bytes (1457 MB) / 2408378368 bytes (2296 MB) up to 2880700416 bytes (2747 MB)
    Mod Pack: com.mumfrey.liteloader.crashreport.CallableLiteLoaderBrand@467c15f8
    LiteLoader Mods: com.mumfrey.liteloader.crashreport.CallableLiteLoaderMods@7ec695a
    LaunchWrapper: com.mumfrey.liteloader.crashreport.CallableLaunchWrapper@73762993
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2759M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2090 Optifine OptiFine_1.10.2_HD_U_C2 118 mods loaded, 117 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2090.jar) 
    UCHIJAAAA   Forge{12.18.1.2090} [Minecraft Forge](forge-1.10.2-12.18.1.2090.jar) 
    UCHIJAAAA   Aroma1997Core{${version}} [Aroma1997Core](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   quickhotbar{1.04} [Quick Hotbar](quickhotbar_1102_1.04.jar) 
    UCHIJAAAA   bettercombatmod{1.3.0} [Better Combat]([MC_1.10.2]BetterCombat-1.3.4.jar) 
    UCHIJAAAA   JEI{3.9.7.259} [Just Enough Items](jei_1.10.2-3.9.7.259.jar) 
    UCHIJAAAA   abyssalcraft{1.9.3-pre-1} [AbyssalCraft](AbyssalCraft-1.10.2-1.9.3-pre-1.jar) 
    UCHIJAAAA   actuallyadditions{1.10.2-r50} [Actually Additions](ActuallyAdditions-1.10.2-r50.jar) 
    UCHIJAAAA   antifrontview{1.1} [AntiFrontView](AntiFrontView-1.1_MC1.9+.jar) 
    UCHIJAAAA   thedragoncore{1.1.0} [TheDragonCore](thedragoncore-1.1.0.jar) 
    UCHIJAAAA   armorplus{1.10.2-6.0.0.1} [ArmorPlus](armorplus-1.10.2-6.0.0.1.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.9.4-1.2.0.2.jar) 
    UCHIJAAAA   arrowcammod{2.2.0} [Arrow Cam Mod](ArrowCamMod-1.10.2-2.2.0.jar) 
    UCHIJAAAA   Morphtool{1.0-11} [Morph-o-Tool](Morph-o-Tool-1.0-11.jar) 
    UCHIJAAAA   Quark{r1.0-55} [Quark](Quark-r1.0-55.jar) 
    UCHIJAAAA   AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2.jar) 
    UCHIJAAAA   AutoSapling{1.3.3} [AutoSapling](Autosapling-1.3.3-MC1.10.jar) 
    UCHIJAAAA   bagginses{2.4.2d} [Bagginses](Bagginses-1.10-3.0.2a.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   bdlib{1.12.0.2} [BD Lib](bdlib-1.12.0.2-mc1.10.2.jar) 
    UCHIJAAAA   XaeroBetterPvP{1.10.2} [Better PVP Mod](BetterPvP_1.10.2.1_Forge_1.10.2.jar) 
    UCHIJAAAA   BiomeTweaker{2.1.225} [BiomeTweaker](BiomeTweaker-1.10.2-2.1.225.jar) 
    UCHIJAAAA   BiomesOPlenty{4.1.0.2065} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2065-universal.jar) 
    UCHIJAAAA   Bullseye{1.0.2} [Bullseye](Bullseye-1.9.4-1.0.2.jar) 
    UCHIJAAAA   cavern{1.1.1} [Cavern](Cavern_1.10-v1.1.1.jar) 
    UCHIJAAAA   ChunkAnimator{1.2} [Chunk Animator](ChunkAnimator-MC1.9.4-1.2.jar) 
    UCHIJAAAA   CobbleDrops{1.10.2.01} [CobbleDrops](CobbleDrops 1.10.2.01.jar) 
    UCHIJAAAA   cyclopscore{0.7.7} [Cyclops Core](CyclopsCore-1.9.4-0.7.7.jar) 
    UCHIJAAAA   colossalchests{1.3.10} [Colossal Chests](ColossalChests-1.9.4-1.3.10.jar) 
    UCHIJAAAA   commoncapabilities{1.1.2} [CommonCapabilities](CommonCapabilities-1.9.4-1.1.2.jar) 
    UCHIJAAAA   compressedbonemeal{1.10.2} [Compressed Bonemeal](compressedbonemeal-1.10.2.jar) 
    UCHIJAAAA   cosmeticarmorreworked{1.10.2-v1} [CosmeticArmorReworked](CosmeticArmorReworked-1.10.2-v1.jar) 
    UCHIJAAAA   mcmultipart{1.2.0} [MCMultiPart](MCMultiPart-1.2.0-universal.jar) 
    UCHIJAAAA   covers{0.3.0.3} [Simple Covers](covers-0.3.0.3-mc1.10.2.jar) 
    UCHIJAAAA   craftablehorsearmour{1.2} [Craftable Horse Armour [CHA&S]](CraftableHorseArmor-1.3.0-1.10.jar) 
    UCHIJAAAA   drones{1.10.2-1.5.0} [CustomDrones](CustomDrones-1.5.0-mc1.10.2.jar) 
    UCHIJAAAA   cxlibrary{1.2.2} [CXLibrary](cxlibrary-1.10.2-1.2.2.jar) 
    UCHIJAAAA   ElecCore{1.5.303} [ElecCore](ElecCore-1.9.4-1.5.303.jar) 
    UCHIJAAAA   craftelytra{1.1} [Craftable Elytra](ElytraCraft-1.1-1.10.2.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.55-beta} [EnderCore](EnderCore-1.10.2-0.4.1.55-beta.jar) 
    UCHIJAAAA   endercrop{1.9-1.2-1836} [Ender Crop](endercrop-1.9.4-1.3.1.jar) 
    UCHIJAAAA   enderutilities{0.6.5-beta.1} [Ender Utilities](enderutilities-1.10.2-0.6.5-beta.1.jar) 
    UCHIJAAAA   endmetals{1.0.4} [End Metals](EndMetals_1.9-1.0.4.jar) 
    UCHIJAAAA   ValkyrieLib{1.10-0.10.1} [Valkyrie Lib](valkyrielib-1.10-0.10.1.jar) 
    UCHIJAAAA   EnvironmentalTech{1.10-0.10.1a} [Environmental Tech](environmentaltech-1.10-0.10.1a.jar) 
    UCHIJAAAA   FFS{1.9.4-1.6.4-b28} [Fancy Fluid Storage](Fancy Fluid Storage-1.9.4-1.6.4-b28.jar) 
    UCHIJAAAA   fluidconverters{2.0.3} [FluidConverters](FluidConverters-1.9.4-2.0.3.jar) 
    UCHIJAAAA   SilentLib{1.0.11} [Silent Lib](SilentLib-1.9.4-1.0.11-19.jar) 
    UCHIJAAAA   FunOres{1.3.1} [Fun Ores](FunOres-1.9.4-1.3.1-74.jar) 
    UCHIJAAAA   advgenerators{0.9.20.4} [Advanced Generators](generators-0.9.20.4-mc1.10.2.jar) 
    UCHIJAAAA   geoactivity{2.2.3} [GeoActivity](geoactivity-2.4.jar) 
    UCHIJAAAA   exp{1.1} [Exp Seedling Mod](GiacomosExperienceSeedling1.9.4-1.1.jar) 
    UCHIJAAAA   fishing{1.4} [Fishing Net Mod](GiacomosFishingNet1.9.4-1.4.jar) 
    UCHIJAAAA   grapplemod{1.10-v7} [Grappling hook mod](grapplemod-1.10.2-v7.jar) 
    UCHIJAAAA   guideapi{@VERSION@} [Guide-API](Guide-API-1.9.4-2.0.0-40.jar) 
    UCHIJAAAA   HoloInventory{2.0.0.130} [HoloInventory](HoloInventory-1.9.4-2.0.0.130.jar) 
    UCHIJAAAA   immcraft{1.1.7} [Immersive Craft](immcraft-1.9.4-1.1.7.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   IronChest{7.0.6.794} [Iron Chest](ironchest-1.10.2-7.0.6.794.jar) 
    UCHIJAAAA   fyberbackpack{1.0.2} [Just Backpacks](justbackpacks-mc1.9.4-1.0.2.jar) 
    UCHIJAAAA   jwin{univ_compat_filler} [Just What I Needed](jwin-0.12.0_mc1.10.2.jar) 
    UCHIJAAAA   malisiscore{1.9.4-4.0.2} [MalisisCore](malisiscore-1.9.4-4.0.2.jar) 
    UCHIJAAAA   malisisblocks{1.9.4-4.0.0} [Malisis Blocks](malisisblocks-1.9.4-4.0.0.jar) 
    UCHIJAAAA   malisisdoors{1.9.4-5.0.4} [MalisisDoors](malisisdoors-1.9.4-5.0.4.jar) 
    UCHIJAAAA   mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UCHIJAAAA   RadixCore{1.10.2-2.1.3} [RadixCore](RadixCore-1.10.2-2.1.3-universal.jar) 
    UCHIJAAAA   MCA{1.10.2-5.2.3} [Minecraft Comes Alive](MCA-1.10.2-5.2.3-universal.jar) 
    UCHIJAAAA   menumobs{1.10.3} [Menu Mobs](MenuMobs-1.10.2-1.10.3.jar) 
    UCHIJAAAA   MoreFurnaces{1.8.1} [More Furnaces](MoreFurnaces-1.10-1.8.1.jar) 
    UCHIJAAAA   MouseTweaks{2.6.3} [Mouse Tweaks](MouseTweaks-2.6.3-mc1.9.4.jar) 
    UCHIJAAAA   AS_MultiMine{1.5.4} [Multi Mine](MultiMine-1.10.2.jar) 
    UCHIJAAAA   MultiPageChest{1.7.0} [Multi Page Chest](MultiPageChest-1.10-1.7.0.jar) 
    UCHIJAAAA   nethercore{1.10.2-2.0.2} [Nether Core](nethercore-1.10.2-2.0.2.jar) 
    UCHIJAAAA   yurtmod{7.01} [Nomadic Tents](NomadicTents[1.10.2]-7.01.jar) 
    UCHIJAAAA   recipehandler{0.4} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.4%281.9%29.jar) 
    UCHIJAAAA   fodc{1.9.0} [Ore Dictionary Converter](OreDictionaryConverter-1.9.0.jar) 
    UCHIJAAAA   pcb{1.5.0} [Portable Craft Bench](portablecraftbench-1.10.2-1.5.0.jar) 
    UCHIJAAAA   progressiveautomation{1.6.48} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.48.jar) 
    UCHIJAAAA   reborncore{2.5.5.3} [RebornCore](RebornCore-1.10.2-2.5.5.3-universal.jar) 
    UCHIJAAAA   QuantumStorage{3.1.0} [QuantumStorage](QuantumStorage-1.9.4-3.1.0.jar) 
    UCHIJAAAA   rfpr{7.2.0} [Real First-Person Render](Real First-Person Render-1.10.2-7.2.0.jar) 
    UCHIJAAAA   reborncore-mcmultipart{2.5.5.3} [reborncore-MCMultiPart](RebornCore-1.10.2-2.5.5.3-universal.jar) 
    UCHIJAAAA   recycler{1.3} [Corail Recycleur](recycler-1.3.1-1.9.4.jar) 
    UCHIJAAAA   redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJAAAA   refinedrelocation{@VERSION@} [Refined Relocation](RefinedRelocation-mc1.10.2-2.0.8.jar) 
    UCHIJAAAA   refinedstorage{0.8.7} [Refined Storage](refinedstorage-0.8.7.jar) 
    UCHIJAAAA   regrowableleaves{1.10.2-3.1.2} [Regrowable Leaves](regrowableleaves-1.10.2-3.1.2.jar) 
    UCHIJAAAA   rftl{1.0} [Rotten Flesh to Leather](RFTL 1.0.jar) 
    UCHIJAAAA   scenter{1.10.2-3.8.0} [Scenter](scenter-1.10.2-3.8.0.jar) 
    UCHIJAAAA   shetiphiancore{3.3.0} [ShetiPhian-Core](shetiphiancore-1.10.0-3.3.0.jar) 
    UCHIJAAAA   shouldersurfing{v1} [Shoulder Surfing](ShoulderSurfing-1.10.2-1.1.jar) 
    UCHIJAAAA   substratum{1.8.1.0} [Substratum](Substratum-1.10.2-1.8.1.0.jar) 
    UCHIJAAAA   supercraftingframe{1.2.0.85} [Super Crafting Frame](supercraftingframe-1.10.2-1.2.0.85.jar) 
    UCHIJAAAA   superminer_core{[1.10.2]-2.1.3.073} [SuperMiner](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_captivator{[1.10.2]-2.1.3.073} [SuperMiner Captivator](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_cropinator{[1.10.2]-2.1.3.073} [SuperMiner Copinator](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_excavator{[1.10.2]-2.1.3.073} [SuperMiner Excavator](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_illuminator{[1.10.2]-2.1.3.073} [SuperMiner Illuminator](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_lumbinator{[1.10.2]-2.1.3.073} [SuperMiner Lumbinator](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_shaftanator{[1.10.2]-2.1.3.073} [SuperMiner Shaftanator](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_substitutor{[1.10.2]-2.1.3.073} [SuperMiner Substitutor](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   superminer_veinator{[1.10.2]-2.1.3.073} [SuperMiner Veinator](SuperMiner-[1.10.2]-2.1.3.073.jar) 
    UCHIJAAAA   tesla{1.2.1.49} [TESLA](Tesla-1.10.2-1.2.1.49.jar) 
    UCHIJAAAA   torcharrowsmod{1.10.2-1} [TorchArrowsMod](torcharrows-1.10.2-1.jar) 
    UCHIJAAAA   Torcherino{4.0s} [Torcherino](Torcherino-4.0s.jar) 
    UCHIJAAAA   VeinMiner{0.34.1_1.9-73be663} [Vein Miner](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJAAAA   visiblearmorslots{2.0} [Visible Armor Slots](VisibleArmorSlots[1.10.2]-2.0.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
    UCHIJAAAA   waterstrainer{1.1.0} [Water Strainer](WaterStrainer-1.9.4-1.1.0.jar) 
    UCHIJAAAA   ICSE{1.0.0.0} [I Can See Everything](Wawla-1.9.4-2.2.1.192.jar) 
    UCHIJAAAA   wawla{2.2.1.188} [What Are We Looking At](Wawla-1.9.4-2.2.1.192.jar) 
    UCHIJAAAA   weaponsplus{1.9.4-3.0.0.0} [WeaponsPlus](WeaponsPlus1.9.4-3.0.0.0.jar) 
    UCHIJAAAA   UniDict{1.10.2-1.8c} [UniDict](UniDict-1.10.2-1.8c.jar) 
    UD  BiomeTweakerCore{2.1.225} [BiomeTweaker Core](minecraft.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
MMFMLCorePlugin (MultiMine-1.10.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (Quark-r1.0-55.jar)
  vazkii.quark.base.asm.ClassTransformer
ShoulderPlugin (ShoulderSurfing-1.10.2-1.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.225.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
    GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2622' Renderer: 'Intel(R) HD Graphics'
    List of loaded APIs: 
        \* AbyssalCraftAPI (1.8.2) from AbyssalCraft-1.10.2-1.9.3-pre-1.jar
        \* actuallyadditionsapi (17) from ActuallyAdditions-1.10.2-r50.jar
        \* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
        \* BiomeTweakerAPI (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* BiomeTweakerAPI|event (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* BiomeTweakerAPI|script|object (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* BiomeTweakerAPI|script|pack (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* BiomeTweakerAPI|script|wrapper (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* BiomeTweakerAPI|util (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* cavern.api (1.1.1) from Cavern_1.10-v1.1.1.jar
        \* cavern.api.event (1.1.1) from Cavern_1.10-v1.1.1.jar
        \* CoFHAPI (1.8.9R1.2.0B1) from RebornCore-1.10.2-2.5.5.3-universal.jar
        \* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.48.jar
        \* CoFHAPI|core (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.1.jar
        \* CoFHAPI|energy (1.8.9R1.2.0B1) from refinedstorage-0.8.7.jar
        \* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.1.jar
        \* CoFHAPI|item (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.1.jar
        \* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.48.jar
        \* commoncapabilities|api (0.0.1) from CommonCapabilities-1.9.4-1.1.2.jar
        \* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.303.jar
        \* environmentaltech.api (1.10-0.10.1a) from environmentaltech-1.10-0.10.1a.jar
        \* FunOresAPI (3) from FunOres-1.9.4-1.3.1-74.jar
        \* Guide-API|API (1.9.4-2.0.0-40) from Guide-API-1.9.4-2.0.0-40.jar
        \* JustEnoughItemsAPI (4.2.0) from jei_1.10.2-3.9.7.259.jar
        \* reborncoreAPI (2.5.5.3) from RebornCore-1.10.2-2.5.5.3-universal.jar
        \* RefinedRelocationAPI (2.0.0) from RefinedRelocation-mc1.10.2-2.0.8.jar
        \* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-0.8.7.jar
        \* SuperScript (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* SuperScript|command (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* SuperScript|object (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* SuperScript|util (1.0.225) from BiomeTweaker-1.10.2-2.1.225.jar
        \* ValkyrieLib.api (1.10-0.10.1) from valkyrielib-1.10-0.10.1.jar
        \* VeinMinerApi (0.3) from VeinMiner-0.34.1-1.9r571+73be663.jar
        \* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2090
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics GL version 2.1.0 - Build 8.15.10.2622, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3 CPU M 330 @ 2.13GHz
```

**Comment by DanHolli** [comment]
it is (if you haven't noticed) on a different computer and still happens
crash was achieved by checking the recipe for a stained clay i believe but as I said it's random

**Comment by mezz** [comment]
Unfortunately this is a generic item rendering error, and not caused by JEI as far as I can tell. The only thing JEI is doing here is displaying the item, the same way it would be displayed in a regular inventory. I will ask around to see if anyone knows what to do with this crash.

**Comment by DanHolli** [comment]
I will try now without Optifine
it did happen on the orange stained clay twice, the Optifine update allowed 2 recepies to be shown unlike the first time
will give you a screenie if it happens again without optifine

**Comment by DanHolli** [comment]
it's a bug with optifine :(
it works fine without optifine

**Comment by mezz** [comment]
Ok, please report to them and link back to this issue here.
https://github.com/sp614x/optifine/issues
