### ISSUE TITLE
[Crash]: When I use "A" key to add a recipe to the bookmark dedicate server Forge 1.21-51.0.33

### ISSUE THREAD

**Issue by Zilgyd** [mezz/JustEnoughItems#3728]
### Steps to Reproduce the Crash

1.- In Minecraft creative mode add several recipe items to bookmark with "A" key
2.- Use or place that item 
3.- Then remove that/those item recipes added of the bookmark and any moment crash the game.

### Crash Report

https://gist.github.com/Zilgyd/3156a5c8f024ff260fed4094c7d5e275

**Comment by mezz** [comment]
Thanks for the report!
I think this should be fixed in the latest version of JEI, can you try it out and confirm?

**Comment by Zilgyd** [comment]
yeah sure, but will there be a version for Forge 1.21? because that's the one I'm using, greetings!

**Comment by Zilgyd** [comment]
Updated: I found the version for Forge, I used this jei-1.21.1-forge-19.16.1.156, I tested it and the problem has been fixed, thank you very much! Regards.

**Comment by mezz** [comment]
Thank you for confirming the fix!
