### ISSUE TITLE
[Bug]: jei is not showing item names when i hover over

### ISSUE THREAD

**Issue by OnliLucifeer** [mezz/JustEnoughItems#3729]
### Steps to Reproduce the Bug

hover over the item in the jei menu

### Expected Behavior

to show the item name when i hover over

### Actual Behavior

the item name is not showing
![Screenshot 2024-09-01 132602](https://github.com/user-attachments/assets/559d4a44-89f6-45fd-8237-ab37fa3bc59b)

### Mod Pack Version (Optional)

jei-1.20.1-forge-15.14.0.65

### latest.log

https://gist.github.com/OnliLucifeer/f0061d956772ecf3cda3be3c4c496d2c

**Comment by jfkinslow** [comment]
@mezz Have you seen this yet. Can we kindly get a fix soon? I am having the same issue occuring both in a singleplayer world and on servers.

**Comment by mezz** [comment]
Thanks for the report!
Does this happen when only JEI is installed? If JEI works fine alone, please try to narrow down which mod is conflicting with JEI and then I can help with the fix.

**Comment by OnliLucifeer** [comment]
yesterday i download the new uploaded version of jei and it seems to be fixed for this version jei-1.20.1-forge-15.15.0.67 but on this one jei-1.20.1-forge-15.14.0.65 is still bugged

**Comment by mezz** [comment]
Thanks for confirming the fix!
