### ISSUE TITLE
[Suggestion] Show one/"default"/base item for ore dict

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#373]
It can look kind of confusing and it's normally kind of obvious that you can use different types of glass or ingots.

For example, it could default to Minecraft items for the ore dict items Forge/vanilla has and then just choose the first item found for other oredict items, or put a map in the config if you want a preference.

**Comment by mezz** [comment]
I show the oredict name on the tooltip when an ingredient is from the ore dictionary. I think limiting what's displayed would break expectations.

**Comment by ghost** [comment]
That seems fair enough. I never actually noticed the tooltip before!
