### ISSUE TITLE
[Other]: How to get rid of JustEnoughItems 100% text during game? 

### ISSUE THREAD

**Issue by Frog1en** [mezz/JustEnoughItems#3730]
### Other

How to get rid of this JustEnoughItems 100% text in the right corner under the mini map? I dont know what did i to make this appear, but this is hella annoying :(. Please help!
![gfssfsasdfafsafsddsf](https://github.com/user-attachments/assets/48f56db7-f0b4-4e7b-a849-8d0de7f0b474)

**Comment by mezz** [comment]
Thanks for the report!
The text shows REI (Roughly Enough Items) which is a different mod, please report to them instead.

**Comment by Darkere** [comment]
This is likely a pinned quest from FTB Quests
