### ISSUE TITLE
[Bug]: Custom smithing builder recipes don't show any output (continuatino 

### ISSUE THREAD

**Issue by Leclowndu93150** [mezz/JustEnoughItems#3734]
### Steps to Reproduce the Bug

use latest version of jei 
![image](https://github.com/user-attachments/assets/8a29b5f2-73b9-400f-b2b4-6b88c9da47ea)

### Expected Behavior

in **19.5.2.66** (haven't tested newer)

![image](https://github.com/user-attachments/assets/bb1ee0f4-0d49-4bf7-a168-29779e9035c7)

### Actual Behavior

not showing output

### Mod Pack URL (Optional)

https://github.com/Leclowndu93150/Modular-Angel-Ring

### Mod Pack Version (Optional)

latest

**Comment by mezz** [comment]
Thanks for the report!
Sorry, I had to make some minor breaking changes to fix https://github.com/mezz/JustEnoughItems/issues/3693
Please update JEI and implement `ISmithingCategoryExtension#setOutput` to resolve this issue.

**Comment by Leclowndu93150** [comment]
i don't have any JEI related code in my mod
do i have to do that ?

**Comment by mezz** [comment]
Oh sorry, I misunderstood your problem. 
Let me take a look, I think JEI might be able to support this without a plugin.

**Comment by mezz** [comment]
This seems to be working on JEI `19.16.4.159`
![Screenshot 2024-09-03 at 8 12 06 PM](https://github.com/user-attachments/assets/333429b8-bf8f-4ec1-a8ee-140fd668b8bc)
Please update your JEI dev version to use 1.21.1 JEI version `19.16.4.159`, which is the latest for 1.21.x

**Comment by Leclowndu93150** [comment]
i have updated the mod to fix the problem (by adding smithing templates) that means that the issue is still valid,
the broken version (of my mod) is 1.3.1 and it's the recipes for modules

**Comment by mezz** [comment]
Ok I see, there was a JEI bug. I have fixed it in version 19.16.4.163
