### ISSUE TITLE
[Crash]: JEI causes Allthemods 9 to not load

### ISSUE THREAD

**Issue by MercyOverload** [mezz/JustEnoughItems#3741]
### Steps to Reproduce the Crash

1. Open Allthemods 9
2. Get error message "Cannot read field "modid" because the return value of "de.melanx.utilitix.UtilitiX.getInstance()" is null:

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

### Mod Pack Version (Optional)

0.3.2

### Crash Report

https://gist.github.com/MercyOverload/24a6e3abde4872ee90d6601592596411

**Comment by MercyOverload** [comment]
Mods affected seems to only be JEI, but when removed 3 more mods also fail to load because JEI is missing..

**Comment by MercyOverload** [comment]
If it helps, I am on a MacBook! macOS Sonoma beta 15

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with UtilitiX, please report to them here: https://www.github.com/MelanX/UtilitiX/issues/
Please link back to this issue in case they need assistance.
