### ISSUE TITLE
[Crash]: All 1.21.x versions crash 1.21 server

### ISSUE THREAD

**Issue by Wytchcat** [mezz/JustEnoughItems#3747]
### Steps to Reproduce the Crash

When anything past 19.2.8.99 is installed server side, server refuses to start with the following errors.

This isn't just you btw. I've reported it for Blockus and Polymer in the last 48 hours.

### Crash Report

https://gist.github.com/Wytchcat/63435c61bd77321b40c8736fa900dc44

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix that should allow JEI 1.21.1 to work with Minecraft 1.21, it will be available shortly.
Please let me know if you run into any more issues.

**Comment by Wytchcat** [comment]
20:14:52  [Info] Immediate reason: [HARD_DEP_NO_CANDIDATE jei x.x.x.192 {depends fabricloader @ [fabricLoaderVersionRange]}, HARD_DEP_NO_CANDIDATE jei 19.16.5.185 {depends fabric-api @ [>=0.103.0+1.21.1]}, ROOT_FORCELOAD jei]
20:14:52  [Info] Reason: [HARD_DEP jei x.x.x.185 {depends fabric-api @ [>=0.103.0+1.21.1]}]
20:14:52  [Info] SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, modmenu, fabric-client-tags-api-v1, nemos-ambience, fabric-screen-api-v1, nether-coords, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-rendering-v0, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1]
20:14:52  [Info] Fix: add [], remove [], replace [[jei x.x.x.192, jei 19.16.5.185] -> add:jei 1 ([(-∞,∞)])]
20:14:52  [Error] Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
- Replace mod 'Just Enough Items' (jei) x.x.x.185 and mod 'Just Enough Items' (jei) 19.17.0.192 with mod 'Just Enough Items' (jei), any version.
More details:
- Mod 'Just Enough Items' (jei) x.x.x.185 requires version 0.103.0+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
20:14:52  [Info] [net.creeperhost.wailt.web.ApiWebServer]: Stopping web server..

**Comment by Wytchcat** [comment]
Fabric loader for 1.21 is still  102.0

**Comment by mezz** [comment]
It looks like you have multiple versions of JEI installed, both `19.17.0.192` and the older version `19.16.5.185` are shown.

**Comment by Wytchcat** [comment]
See open report:
https://github.com/mezz/JustEnoughItems/issues/3750#issuecomment-2337797962

includes updated server crash report. Thanks
