### ISSUE TITLE
[Crash]: (1.21.1) Typing "br" into search crashes game

### ISSUE THREAD

**Issue by Hamsolo3** [mezz/JustEnoughItems#3749]
### Steps to Reproduce the Crash

Type "br" or "rr" into JEI search. Game will crash to desktop

### Crash Report

https://gist.github.com/Hamsolo3/ca92ea35f67aa04717bcda85d186b1d8

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by Hamsolo3** [comment]
Here you go: https://gist.github.com/Hamsolo3/fdc90a77c39d0454a2b1783e4e29a526

**Comment by mezz** [comment]
uhh
```
[08Sep2024 23:08:56.336] [Render thread/ERROR] [mezz.jei.common.util.ErrorUtil/]: Caught an error getting an Ingredient's tooltip:

-- Ingredient --
Details:
	Name: JEI Error Item #TooltipCrash
	Mod's Name: Just Enough Items
	Registry Name: jei:error_tooltipcrash
	Class Name: class mezz.jei.library.plugins.debug.ingredients.ErrorIngredient
	toString Name: ErrorIngredient[crashType=TooltipCrash]
	JSON: "TooltipCrash"
	Ingredient Type for JEI: class mezz.jei.library.plugins.debug.ingredients.ErrorIngredient
	Error Info gathered from JEI: JEI Error Item #TooltipCrash
```

```
[08Sep2024 23:08:59.934] [Render thread/ERROR] [mezz.jei.common.util.SafeIngredientUtil/]: Caught an error while rendering a batch of Ingredients with ingredient renderer: class mezz.jei.library.plugins.debug.ingredients.ErrorIngredientRenderer
java.lang.RuntimeException: intentional render crash for testing
```

It looks like you set `CrashingTestItemsEnabled` to `true` in the JEI debug config file.
Please set it to `false`.
If the issue still happens, please send me your new logs.

**Comment by Hamsolo3** [comment]
Whoops... must have enabled that option by mistake. Sorry about that, issue is resolved. Thanks!
