### ISSUE TITLE
Fluids crafting recipe 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [mezz/JustEnoughItems#375]
When you look a crafting recipe that needs a fluid, it tells what fluid it is but when you click it to see how it is made, nothing happens, but you search for that liquid in JEI, click on it there to see recipes, would be possible to make, JEI to show liquid recipes, by clicking on them from other recipes, I so not believe any of the villain recipes, require this but it does seem to affects all mods, with make me thing issue lies in JEI.

**Comment by mezz** [comment]
Thanks for the report!
This should work fine, what mod's recipes are you looking at when the fluid lookup fails? 
Can you paste a screenshot?

**Comment by mezz** [comment]
I actually ran into this issue myself. It seems you can look up the fluids using the hotkeys U and R but not by clicking them.

**Comment by mezz** [comment]
Fixed in version 3.7.11
