### ISSUE TITLE
[Bug]: Still not compat with 1.21

### ISSUE THREAD

**Issue by Wytchcat** [mezz/JustEnoughItems#3750]
### Steps to Reproduce the Bug

Fabric Loader for 1.21 has not advanced beyond 0.102.0, new JEI versions require 0.103.x

20:14:52  [Info] Immediate reason: [HARD_DEP_NO_CANDIDATE jei x.x.x.192 {depends fabricloader @ [fabricLoaderVersionRange]}, HARD_DEP_NO_CANDIDATE jei 19.16.5.185 {depends fabric-api @ [>=0.103.0+1.21.1]}, ROOT_FORCELOAD jei]
20:14:52  [Info] Reason: [HARD_DEP jei x.x.x.185 {depends fabric-api @ [>=0.103.0+1.21.1]}]
20:14:52  [Info] SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, modmenu, fabric-client-tags-api-v1, nemos-ambience, fabric-screen-api-v1, nether-coords, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-rendering-v0, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1]
20:14:52  [Info] Fix: add [], remove [], replace [[jei x.x.x.192, jei 19.16.5.185] -> add:jei 1 ([(-∞,∞)])]
20:14:52  [Error] Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
- Replace mod 'Just Enough Items' (jei) x.x.x.185 and mod 'Just Enough Items' (jei) 19.17.0.192 with mod 'Just Enough Items' (jei), any version.
More details:
- Mod 'Just Enough Items' (jei) x.x.x.185 requires version 0.103.0+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
20:14:52  [Info] [net.creeperhost.wailt.web.ApiWebServer]: Stopping web server..

### Expected Behavior

Server start

### Actual Behavior

Server no start. LOL

**Comment by SweetDream21** [comment]
the same with you

The latest Fabric API version of MC1.21 is 0.102.0

When I update the Fabric loader to 0.16.5, it will prompt that the Fabric loader is incorrect

**Comment by Wytchcat** [comment]
0.16.3 loader for me but yeah ...

**Comment by Unleashed75** [comment]
Version 19.17.0.192 is not listed as being released on the Modrinth app.
The last release on Modrinth App is 19.16.5.185 but the app still wants me to update to this new version. (It's website lists many more versions for 1.21/1.21.1)
While I can update to that version and the other ones listed to support 1.21 and 1.21.1 (on Modrinth App)
Versions from 19.16.4.181 to versions 19.16.5.185, (including 19.17.0.192) do not work on 1.21 but show to support it!
I have to downgrade to version 19.8.2.99 which shows to support only 1.21 and then to keep being reminded to update the mod within the Modrinth App (This is not a big problem for me but others that do not understand may struggle)

This was tested with;
Fabric Loader 0.16.5
Fabric API 0.102.0+1.21
JEI versions listed above

I basically think you've marked versions to support 1.21 and 1.21.1 which only supports 1.21.1 and beyond, maybe?

![image](https://github.com/user-attachments/assets/d67a9a92-d07a-4fd0-acab-aedf8cb8a7e6)
![image](https://github.com/user-attachments/assets/ccb6aead-f878-4e0d-b34a-40ffae458a63)

**Comment by Wytchcat** [comment]
!p?3;4ll>?1049h0;0tl?1h=(B0rHHBOpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
06:59:55  [Info] [net.creeperhost.wailt.WhyAmILaggingTho]: Initializing WhyAmILaggingTho Agent 0.6.8.
06:59:55  [Info] [net.creeperhost.wailt.WhyAmILaggingTho]: Detected Environment: {minecraft=1.21, java=21, fabric=unknown}
06:59:56  [Info] [net.creeperhost.wailt.web.ApiWebServer]: Starting WAILT Web Server x.x.x.0:35565.
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
06:59:56  [Info] [net.creeperhost.wailt.web.ApiWebServer]: Using SSL.
06:59:56  [Info] [net.creeperhost.wailt.web.ApiWebServer]: Awaiting connections..
Sep 09, 2024 1:59:56 PM net.creeperhost.wailt.repack.io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: ed:09:6c:42:51:46:c1:81
06:59:56  [Info] [net.creeperhost.ta.TimeoutAgent]: Trying to use VERSION_JSON VersionDiscoverer to determine Minecraft version..
06:59:56  [Info] [net.creeperhost.ta.TimeoutAgent]: Success! Detected Minecraft 1.21
06:59:56  [Info] [net.creeperhost.ta.TimeoutAgent]: Instantiating transformer READ_TIMEOUT.
06:59:56  [Info] [net.creeperhost.ta.TimeoutAgent]: Instantiating transformer LOGIN_TIMEOUT.
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [WARN] Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
06:59:57  [Info] Loading Minecraft 1.21 with Fabric Loader 0.16.3
06:59:57  [Warn] Mod netherdepthsupgrade uses the version fabric-3.1.8-1.21 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
06:59:57  [Warn] Mod resolution failed
06:59:57  [Info] Immediate reason: [HARD_DEP_NO_CANDIDATE jei x.x.x.192 {depends fabricloader @ [fabricLoaderVersionRange]}, ROOT_FORCELOAD_SINGLE jei 19.17.0.192]
06:59:57  [Info] Reason: [HARD_DEP jei x.x.x.192 {depends fabricloader @ [fabricLoaderVersionRange]}, HARD_DEP jei 19.17.0.192 {depends fabric-api @ [fabricApiVersionRange]}]
06:59:57  [Info] SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, modmenu, fabric-client-tags-api-v1, nemos-ambience, fabric-screen-api-v1, nether-coords, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-rendering-v0, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1]
06:59:57  [Info] Fix: add [], remove [], replace [[jei x.x.x.192] -> add:jei 1 ([(-∞,∞)])]
06:59:57  [Error] Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
- Replace mod 'Just Enough Items' (jei) x.x.x.192 with any version that is compatible with:
- fabricloader 0.16.3
- fabric-api 0.102.0+1.21
More details:
- Mod 'Just Enough Items' (jei) x.x.x.192 requires version fabricLoaderVersionRange of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.16.3!
- Mod 'Just Enough Items' (jei) x.x.x.192 requires version fabricApiVersionRange of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
06:59:58  [Info] [net.creeperhost.wailt.web.ApiWebServer]: Stopping web server..
06:59:58  [Info] [net.creeperhost.wailt.web.ApiWebServer]: WAILT Api Web Server shutdown.
Online players: 0

**Comment by mezz** [comment]
Thanks for the report!
I was able to identify the new issue and it should be resolved in the next release.
Please let me know if you run into any more issues.

**Comment by Wytchcat** [comment]
Thank you kindly... will send along anything new! :)
