### ISSUE TITLE
[Bug]: Not showing any of potion fluids from Create mod

### ISSUE THREAD

**Issue by goshante** [mezz/JustEnoughItems#3754]
### Steps to Reproduce the Bug

1. Open Minecraft 1.20.1 with latest **Forge** (not NeoForge) version available for it. It should have **JEI** and **Create** mods installed (latest versions available from Curse).
2. Load your world or join the server
3. Open JEI interface to search for an item
4. Search for any potion

### Expected Behavior

You can see all bottled potions and their fluid versions when playing with Create mod. Every potion must have it's fluid representation in JEI interface (even if no existing crafting/processing recipes).

### Actual Behavior

Only bottled potions are visible, no fluids at all. Enabling **lookupFluidContentsEnabled** and **ShowHiddenItems** in config also doesn't helps.

### Extra Notes (Optional)

Why this is so necessary: For example, when playing with **Applied Energistics 2** the only way to make **Crafting pattern** with fluids is to drag & drop fluid icon from JEI interface (Dragging from ME interface is not possible for fluids). You can drag water, lava or milk from JEI to **AE2** Crafting pattern encoder and it works, but it's impossible to do with potion fluids from **Create** because they don't exist for JEI and not indexed in item list. But Potion fluids are exist in game, they show up in storage, you can see icons of potion fluids and stored volume, but none of them is visible in JEI interface.
You cannot also configure Export and Storage buses, because you cannot drag a liquid into filter grid.

With AE2 or without, JEI have to show all potion liquids if they are the thing in Create mod.

**Comment by mezz** [comment]
Thanks for the report!
I looked into this, and it seems like almost all of Create's fluids are "flowing". JEI only shows "source" fluids right now.
I'll see how I can add better support for this.

**Comment by mezz** [comment]
I updated JEI a bit and made a pull request to Create in order to complete the feature: https://github.com/Creators-of-Create/Create/pull/6934
It will be available for players if they review and accept the PR.

![2024-09-12_16 52 24](https://github.com/user-attachments/assets/aef8ce7b-6aba-4c0c-97d8-ecbbdeb0f061)

**Comment by goshante** [comment]
Thank you, it works! I tested your changes
They will review and merge your pull request soon as new patch will be on plans, I asked about it
