### ISSUE TITLE
[Bug]: no item name or info

### ISSUE THREAD

**Issue by SageHenryStone** [mezz/JustEnoughItems#3759]
### Steps to Reproduce the Bug

All I did was update the mod

### Expected Behavior

To see the names and tags and mods that the item has originally 

### Actual Behavior

Hovering over the item doesn't say anything.

### Extra Notes (Optional)

I've just been trying to fix models in a modpack the villagers from easy villagers models and chests and shulkers are all broken but keep alternating between fixed and not

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by SageHenryStone** [comment]
Oh I can't do that now I'm at work and won't be able to do anything for a very long time

**Comment by mezz** [comment]
No rush. Take as long as you need to

**Comment by SageHenryStone** [comment]
Hopefully other people have the same issue (in a sense of getting it fixed
not so people suffer like me) then it can get fixed

**Comment by totsomi** [comment]
I have the same issue, it worked just fine util I updated JEI, here's the link for my latest log https://gist.github.com/totsomi/33e9deba4c96b0a1ca2ab2633e7a8816
my apologies for the size of it, I've got a pretty lengthy modpack.

**Comment by totsomi** [comment]
and plus, when I go back to the previous version, it works just fine.

**Comment by mezz** [comment]
Thanks for the logs!
I have pushed a fix for this issue in the next version, available shortly.
Please try it out and let me know how it goes.

**Comment by totsomi** [comment]
it works, thank you so much)

**Comment by mezz** [comment]
Thanks for confirming!

**Comment by SageHenryStone** [comment]
Oh it's 1.20.1 that I use
