### ISSUE TITLE
Item list tool-tips not updated when recipe changes

### ISSUE THREAD

**Issue by Biochao** [mezz/JustEnoughItems#376]
When a recipe is changed by Craft Tweaker that changes it's tooltip the JEI item list still displays the original tooltip, even after a reload/restart.
![Item List](http://i.imgur.com/P7WV9Rk.png)
![New Tooltip](http://i.imgur.com/4dF2F9d.png)

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Craft Tweaker here: https://github.com/jaredlll08/CraftTweaker/issues
