### ISSUE TITLE
[Suggestion]: Not exactly for JEI, but a "Powah JEI Integration"

### ISSUE THREAD

**Issue by Jmpp2909** [mezz/JustEnoughItems#3760]
### Suggestion

I mean this since i saw one of the devs that made this mod also made JEI, so i kindly ask in the name of a big part of the community, to make a Powah JEI Integration mod

What i ask is something like this, but for Powah
AE2 JEI Integration
https://www.curseforge.com/minecraft/mc-mods/ae2-jei-integration

**Comment by mezz** [comment]
Sorry I am not able to write an integration plugin for every mod.
AE2 was simple because it was already written, just removed, and the source code license allowed us to copy it.

Please make your request to the Powah devs here: https://github.com/owmii/Powah/issues

**Comment by Jmpp2909** [comment]
Thanks for the response and totally understandable, AE2 and Powah (Technician) dropped support intentionally to force players to use EMI, i didnt know if the same case of AE2 could be applied to Powah, and though didnt hurt to ask.

**Comment by mezz** [comment]
Based on the github I linked, Technician doesn't seem to be involved with Powah. Can you explain what you mean?

**Comment by Jmpp2909** [comment]
Based on this, which is the post 1.16.5 Powah
https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected

**Comment by mezz** [comment]
Ah ok I see.

Technician's solo mod [Modern-Industrialization](https://github.com/AztechMC/Modern-Industrialization/tree/1.21.x) still has JEI  integration. I assume shartte is driving the effort to force people to use other recipe viewers, it was removed by him here: https://github.com/Technici4n/Powah/commit/ff5ddc9b0eafbaa0ebc13e3a901543248e77b73d

The Powah issue for this is here: https://github.com/Technici4n/Powah/issues/186
I'll see what I can do.

**Comment by Jmpp2909** [comment]
Thank you for considering, if you do make it, i bet it will probably get almost the same praise as the AE2 one, as many modpack makers have their hands tied when it comes to Powah recipes, and only way is having to make it custom, or migrating to EMI alltogether because of 1/2 mods.

**Comment by mezz** [comment]
Yeah understood. I want to support EMI, I think it's good to have variety. 
I believe that players and pack makers should be able to choose, so I'll keep working towards that.

**Comment by mezz** [comment]
The JEI integration wasn't very complicated, so I reimplemented it and submitted a PR to the project here:
* https://github.com/Technici4n/Powah/pull/193

**Comment by Jmpp2909** [comment]
Thank you a lot!

**Comment by Jmpp2909** [comment]
Hey, uhm, im probably being too pushy, but about the AE2 integration, could you check if the same thing happens for ExtendedAE (made by GlodBlock, so probably also just removed code)
