### ISSUE TITLE
[Other]: Items showing up in random order 

### ISSUE THREAD

**Issue by NotZimon** [mezz/JustEnoughItems#3763]
### Other

As the title says

**Comment by RoboXGamer** [comment]
This happens when we reload the resourcepacks

**Comment by RoboXGamer** [comment]
using f3+T shortcut or change any resourcepacks then also 
the order gets messed up

**Comment by PUrE-elF** [comment]
Got This problem either. Server resource packs can not changed.

**Comment by PUrE-elF** [comment]
![Uploading 1429064.jpg…]()

**Comment by PUrE-elF** [comment]
![1429064](https://github.com/user-attachments/assets/0205b493-b831-45a7-9771-08d27f95ff53)

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/3731 and has been fixed in the latest versions.
