### ISSUE TITLE
[Bug]: [1.20.1] Newer JEI Versions doesn't show some craft IDs

### ISSUE THREAD

**Issue by Blackalf** [mezz/JustEnoughItems#3767]
### Steps to Reproduce the Bug

1. Activate Advanced tooltips with F3 + H
2. Check recipes from different mods and hover their outputs to check if the craft id appears

### Expected Behavior

Every craft IDs should be shown.

### Actual Behavior

Some craft ids are no longer shown in version 15.18.0.83 and higher

### Extra Notes (Optional)

I couldn't find a pattern on what craft ids stops showing or not but I've got an example just below

Here's the Dissolver recipe for Cinnabar in Alchemistry in 15.18.0.82:
![image](https://github.com/user-attachments/assets/d7b4964f-de64-46bc-b04f-6c9e5b92724f)

And here it is in 15.18.0.83+:
![image](https://github.com/user-attachments/assets/45e6dfd3-47dc-43ab-8b52-863d798d06aa)

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix for this, which should be available shortly.
