### ISSUE TITLE
[Bug]: Resource packs make JEI random sorting items - not closed. Accidentally click close.

### ISSUE THREAD

**Issue by PUrE-elF** [mezz/JustEnoughItems#3768]
### Steps to Reproduce the Bug

When I add resource pack that require optifine. It cause the problem. like this in the example picture below :
![1429064](https://github.com/user-attachments/assets/ae659e0c-d865-4b9e-bc7d-55783bd0a9bc)

I could just remove the resource pack. But it crashing in my server resourcepack. and it cannot be undone with any way.

Resourcepack name : Better illagers, Better Farm Animals_v0.08

I need help for this .Please it is ruining my good experience with minecraft.

### Expected Behavior

Even add any resourcepacks, JEI should sorting items as usual.

### Actual Behavior

I've remove the resourcepack it was stop the bug. But i can not remove the bog from Server.

### latest.log
https://mclo.gs/UD8OGDF

**Comment by PUrE-elF** [comment]
I was accidently click close. And it cannot change.

**Comment by mezz** [comment]
Thanks for the report!
Is this the same as https://github.com/mezz/JustEnoughItems/issues/3731 ?
