### ISSUE TITLE
JEI EnderIo Crash

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#377]
Jei Crash When i install EnderIo

Full Log: 
http://paste.ee/p/0GpNL

**Comment by mezz** [comment]
After taking a close look, this appears to be a crash from EnderIO. 
Please report to them and link back to this issue https://github.com/SleepyTrousers/EnderIO/issues

**Comment by HenryLoenwind** [comment]
Looks like a bad RF API to me.
