### ISSUE TITLE
[Bug]: Block hover menu doesn't show

### ISSUE THREAD

**Issue by BlueCrafter6** [mezz/JustEnoughItems#3779]
### Steps to Reproduce the Bug

1. Look at a block

### Expected Behavior

I should see a menu that says: (e.g)
**Grass Block**
_Minecraft_

### Actual Behavior

The menu doesn't show up

### Extra Notes (Optional)

JEI Version 15.19.5.99

### latest.log

https://mclo.gs/UNAnNxs

**Comment by mezz** [comment]
Thanks for the report!
This feature is not provided by JEI. 
I think a popular mod for it is [Jade](https://www.curseforge.com/minecraft/mc-mods/jade)

**Comment by BlueCrafter6** [comment]
Oh.. sorry for the confusion 😅
