### ISSUE TITLE
JEI crash when trying to view a recipe

### ISSUE THREAD

**Issue by lOmicronl** [mezz/JustEnoughItems#378]
Hi, I just got this crash after I tried to view the recipe of the Basic Solar Panel from Inductive Automation. However, after restarting the client, it now works fine - I can't reproduce it.

Still, maybe the log will help you in some way. :) 

https://gist.github.com/lOmicronl/d1580975459bab0b06fb514181730988

(running jei_1.10.2-3.7.10.237 on Minecraft 1.10.2, with Forge 1.2.18.1.2046)

**Comment by mezz** [comment]
Thanks for the report! 
The 1.10 version of JEI changed the recipe transfer handler API slightly, and they need to update.
Please forward this on to Inductive Automation: https://github.com/CD4017BE/InductiveAutomation/issues
