### ISSUE TITLE
[Bug]: Console spam when using together with EMI

### ISSUE THREAD

**Issue by Disketaa** [mezz/JustEnoughItems#3782]
### Steps to Reproduce the Bug

Install EMI that has JEI Integration
Install JEI

![image](https://github.com/user-attachments/assets/8f909d1b-30cb-4dfe-8660-79a08b866be8)

### Expected Behavior

Clean console

### Actual Behavior

Warning spam

### Extra Notes (Optional)

JEI 19.19.0.219
EMI 1.1.12.1.21
Fabric 1.21 / 0.16.5

**Comment by mezz** [comment]
Thanks for the report!
I have lowered the log level to debug so that it will not spam your console.
