### ISSUE TITLE
1.19.2: JEI not cycling through ingredients when looking at recipes

### ISSUE THREAD

**Issue by Malazag** [mezz/JustEnoughItems#3788]
### Steps to Reproduce the Bug

Viewing any recipe which could use substitutes as allowed by oredict would normally slowly cycle through said substitutes. For some reason this stopped entirely.

### Expected Behavior

Alternative ingredients in a recipe should cycle periodically around.

### Actual Behavior

Alternative ingredients in a recipe do not cycle. They only change randomly when I close and open the recipes.

### latest.log

https://gist.github.com/Malazag/6fdabbb9c4d849b0f3b7fa598424dd1b

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed and will be available shortly in the next release.
