### ISSUE TITLE
[Bug]: Compostable recipe category broken ish

### ISSUE THREAD

**Issue by manmaed** [mezz/JustEnoughItems#3789]
### Steps to Reproduce the Bug

not sure when it was added i think 1.21 but neoforge changed how to add items to the composer via a data map so any items added this way will not show in the recipe category

### Expected Behavior

To show items that can be compoosted

### Actual Behavior

Only displays vanilla recipe 

### Mod Pack URL (Optional)

https://feed-the-beast.com/modpacks/126-ftb-presents-direwolf20-121

### Mod Pack Version (Optional)

FTB Presents Direwolf20 1.21

### Extra Notes (Optional)

To View the bug update cottonley to 16.3 for minecraft 1.21 modloader neo

**Comment by mezz** [comment]
Thanks for the report!
NeoForge composting recipes will be supported in the next release, available shortly.
