### ISSUE TITLE
[Bug]: Game crash when clicking on air.

### ISSUE THREAD

**Issue by DinnerBeef** [mezz/JustEnoughItems#3790]
### Steps to Reproduce the Bug

1. Find a recipe that has air inside it. (IE: EnderIO: Sagmill (Modifier Slot), Railcraft Reborn: Crusher (Output Slots))
2. Click a slot that has air
3. Game Crashes

### Expected Behavior

The game not to crash when clicking on air slots.

### Actual Behavior

Game crashes when clicking on air slot.

### Extra Notes (Optional)

Crash Report: https://s.dinnerbeef.com/gOXe5/vopaMIgI89.txt
Mod Version: 19.19.4.230
![image](https://github.com/user-attachments/assets/c3c9ac63-f81b-442b-b547-9ac61ac3e775)

### latest.log

https://gist.github.com/DinnerBeef/11e682b6290f6ef97c46e6efeefc75f5

**Comment by mezz** [comment]
Thanks for the report!
This will be fixed in the next release, available shortly.
