### ISSUE TITLE
[Crash]: Shick Click to move items to crafting table causes Crash

### ISSUE THREAD

**Issue by ffuentesm** [mezz/JustEnoughItems#3793]
### Steps to Reproduce the Crash

The game crashes when I try to shift-click a recipe into the crafting table.
This never happened before, but is starting to do it now. I am using polymorth and EMI alongside.
I tried to remove Polymorph, but the crash still happened. 

https://github.com/illusivesoulworks/polymorph/issues/286

### Extra Notes (Optional)

polymorph-neoforge-1.0.6+1.21.1
jei-1.21.1-neoforge-19.19.6.233
emi-1.1.14+1.21.1+neoforge
Neoforge:21.1.65

### Crash Report

https://pastebin.com/U3qrLkvz

**Comment by mezz** [comment]
Thanks for the report!
This one is on EMI's side. I have been making a lot of additions to the JEI API lately and EMI just needs some time to implement them for their compatibility layer.
