### ISSUE TITLE
[Performance]: Memory Leak of Client Player

### ISSUE THREAD

**Issue by pietro-lopes** [mezz/JustEnoughItems#3794]
### Steps to Reproduce the Bug

https://github.com/mezz/JustEnoughItems/blob/bc0098ddc81e8fe669313a13d17832990c90945c/Gui/src/main/java/mezz/jei/gui/recipes/RecipeGuiLogic.java#L44

1. Load a world
2. Open Jei
3. Change dimensions

![image](https://github.com/user-attachments/assets/27c8982c-6d3c-4c2e-b805-957cd89284d7)

### Expected Behavior

Cached objects that contain ClientPlayer should have a cleanup/update logic as ClientPlayer is discarded on Clone (dimension travel and death for example)

### Actual Behavior

Leaks Client Player, Level, everything related to player.

### latest.log

check image

**Comment by mezz** [comment]
Thanks for the report!
I have fixed the issue by avoiding storing the client player at all, and it will be released shortly.
