### ISSUE TITLE
[Performance]: Memory Leak of Client Player

### ISSUE THREAD

**Issue by pietro-lopes** [mezz/JustEnoughItems#3795]
### Steps to Reproduce the Bug

Similar to #3794 , same reproducable steps, but now looks like indirectly via InventoryMenu

![image](https://github.com/user-attachments/assets/5629f61e-0eea-4e2f-be37-e932312ac5f6)

![image](https://github.com/user-attachments/assets/bf567ed3-3baf-4e76-ba3b-dc726a242285)

### Expected Behavior

N/A

### Actual Behavior

N/A

### Extra Notes (Optional)

Using `jei-1.21.1-neoforge-19.19.6.234` which fixed last memory leak.

### latest.log

check images

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the next release, available shortly.
