### ISSUE TITLE
[Suggestion]: Allow fast cheating of items on Cheat mod with hotbar keys

### ISSUE THREAD

**Issue by Luningor** [mezz/JustEnoughItems#3796]
### Suggestion

On creative, you can fast take a stack of items and place them in your hotbar via pressing 1-9 atop an item. It's very useful due to not having to drag'n'drop said item into the inventory, saving lots of time if you were, say, in a laptop, for example.
My suggestion is adding the same behaviour into JEI's Cheat Mode: Ctrl+(1-9) to put a stack of an item in the pressed space.

Thak you for your time, as always.

**Comment by mezz** [comment]
Thanks for the suggestion!
There is a config setting, `CheatToHotbarUsingHotkeysEnabled` in the JEI client config file.
It is not enabled by default because hitting it accidentally can be confusing unless you know about it.

**Comment by Luningor** [comment]
I really ought to read the configs better. Thank you very much!

**Comment by fydar** [comment]
Would be nice to remove the chat message that is sent when doing this.
