### ISSUE TITLE
[Bug]: Items Have Different NBT or ID

### ISSUE THREAD

**Issue by Coraline774477** [mezz/JustEnoughItems#3798]
### Steps to Reproduce the Bug

1. Have a stackable item in your hot bar
2. place the item (say a fence piece)
3. break it
4. will not stack and it's a new item stack

### Expected Behavior

Items stacking like before

### Actual Behavior

When breaking stackable items (E.G: Oak Fences) thay apparently have a different NBT or ID (if everything still uses item IDs on 2024 that is?)

### Extra Notes (Optional)

Minecraft: 1.20.1
Forge: 1.20.1-47.3.10
JEI: 15.20.0.101

I don't know precisely if JEI is the cause of items not stacking like they should when I break them up.
Like say I miss placed a oak plank and I break it, it won't stack with the existing stack and make a new stack of oak planks instead..
But I don't really have any other mods in my mod lists (or personal modpacks or whatever) that could be causing this to happen and this issue started happening after I've remade my MineColonies world (my initial MineColonies world was made before JEI 15.20.0 I presume) and I'm on my new world called Cora World: TACZ w/Epic Fight (made after JEI 15.20.0)..

So on my initial Minecolonies world before the remake world that items were stacking when I break and picking them up but sometime between then and now as of JEI updates that you might have borked/broken something to cause this to happen.

If it's not JEI that's causing this issue then please point me in the right direction so that I can make a new report to whichever mod is responsible for this issue to occur during gameplay. 
Since I bet that this issue isn't going away anytime soon..
However it's just an annoyance but a problem that needs fixing neither the less.

One more thing, that's not the latest log, however that log should provide the vital information needed in order to potentially find a solution to this bug. 
Also I think that this log was made during my last gaming session. 
Since my gaming sessions tends to last till the next day sometimes.

Since the actual latest log doesn't show very much information because I literally just got to the title screen of Minecraft that I'm not in any world just yet. 
(However, by the time you read this I'll already be on Cora World: TACZ w/Epic Fight as I craft the guns from TACZ and it's addon mods and the armors from a addon mod for TACZ.)

### latest.log

https://gist.github.com/Coraline774477/b3d118fef442c308ca5f5c8e8f746a7f

**Comment by mezz** [comment]
Thanks for the report!
JEI only creates items when you cheat them in, so it is very unlikely to be causing this issue.

I think the best way to figure out an issue like this is to look at the item's NBT.
You can do this in the game by holding the item in your hand and entering this command in the game chat:
`/data get entity @s SelectedItem`
If the tags are obviously from some mod (maybe they say `minecolonies` or something easy like that) then you'll know where to report the issue.

Otherwise, you will need to narrow down your mod list to find out which mod is causing the issue.
For example, you can easily rule out JEI by removing it and seeing if the issue still occurs.
Ideally you should try to remove a small batch of mods at a time in order to save yourself some time.

**Comment by Coraline774477** [comment]
I don't think it's JEI. (Ik that you know what JEI is since you're the author of it but..) JEI is a recipe viewing mod that can also allow players to spawn in items from its built-in cheat mode much like minecraft's creative mode.

The problem is coming from a mod that manages storage.
So either Sophisticated Backpacks, Traveler's Backpack or Iron Chests.

While I was playing the game last game session, I already figured out which mod or mods is causing this issue to occur without needing to take out every single mod and individually add the mods or add in groups of mods to determine which one(s) are causing this issue to occur.

Also I already know that the items that are stackable have a different NBT tag since they're obviously not stacking like they should.

However, iron chests only adds different chests that has more storage than a regular chest. (Diamond, chrystal (see through) and obsidian (blast resistant) chests having the most storage space)

Also I don't really think it's coming from Traveler's Backpack because that mod isn't updating as often because it doesn't rely on a dependency mod such as a lib mod. Yet.

I think it's either Sophisticated Core or Sophisticated Backpacks that's causing this problem to occur.

Also to add some more details; when I have any item in my hot bar that when I right click it that an animation happens.
The item moves up and down but that's only it.

I'll copy this report and send it to pepperfly (the author of Sophisticated Core and Backpacks) and report this to him instead but I'll keep this report active till you decide to close it as completed.

EDIT: I'll do that later. Since I just woke up like almost 30 minutes ago or so while I was talking with myself about something related to minecraft (probably was the latest pre-release to minecraft 1.21.2, lol)

And I'm responding on my phone which I would have to let him know what versions of Sophisticated Core and Backpacks they are which I don't know what version they both are right off the top of my head which my "gaming" laptop has the information that I need.

So before I hop back into Cora World; TACZ w/Epic Fight, *I'll remove both mods and copy the report and paste it into a new issue report on either Sophisticated Backpacks or Sophisticated Core's issue tracker.
Since I'll be targeting both mods as the corporate of the issue of items not stacking properly in the player inventory.

*Even though I don't want to remove Sophisticated Backpacks because it's Netherite Backpack has ALOT of storage space to carry alot of stuff/loot and the backpack upgrades like the magnet upgrade are really really helpful/useful and the mod is practically the spiritual successor of Iron Backpacks mod but I need to see if Sophisticated Backpacks and/or Sophisticated Core are the mods that are causing this issue to occur however...

**Comment by Coraline774477** [comment]
One more thing, if this issue isn't coming from either Sophisticated Core or Sophisticated Backpacks or both then I guess that I will have to go through the mod list to see which mod(s) in my current world is causing the problem to occur. Since it's happening on the world I'm currently playing on as well.
Not just Cora World: MineColonies.

Why I initially thought that JEI was the corporate was because you're constantly updating it that maybe an update caused this problem to happen.
You know, update some things while potentially breaking other things at the same time or adding new problems while adding new features.

But now my focus has went to Sophisticated Core and Backpacks because P3pp3rF1y has been consistently updating both of his mods as well.
Not as often as you with JEI but still often enough.
Since Traveler's Backpacks doesn't update often and Iron Chests rarely updates as of any bug fixes.
So both of these mods aren't viable enough to be the corporates to contribute to the cause of the issue because they're not constantly updating unlike JEI, Sophisticated Core and Sophisticated Backpacks which they're constantly being updated.

**Comment by Coraline774477** [comment]
P.S. I wish that you could change the way the changelog looks like or works so that I can properly understand what you're doing with JEI.
Since all I can go by is reading the very top thing that you did to the mod.

When you do a release version of JEI then list all of the changes, additions and whatnot in the changelog but not for development builds such as beta builds.

MineColonies's changelog is similar to yours but I can understand theirs a little better than yours tho.
Since when they upload a release version of MineColonies they list everything that was changed, added, removed, etc. While they upload betas that only list what they did for a particular beta release.
That's practically how changelogs are supposed to work, so that we can understand the changelog better, because the way yours are right now that it confuses me alot and I don't properly understand what's going on with the mod as of what you're doing to it...

**Comment by Coraline774477** [comment]
UPDATE:

During mod loading that after the game reached "mod loading completed" that the game freezes up for a minute. Same happens when loading into the world.

I have took the time to figure out which mod was the corporate that's causing this whole mess and it's the main mod for the world I'm currently playing which is the gun mod TACZ (Timeless and Classics Guns: Zero)..

I think that why its happening in my MineColonies world is possibly coming from the main mod of that world MineColonies...

Before I conducted the tests to see which mod(s) was causing this issue that I had noticed a pattern when starting the game up during mod loading and during world loading which then leads to the main issue of items not stacking properly.

During the tests with just the performance mods installed on a test world that's fresh that I grabbed a stone axe and chopped two blocks of a spruce tree (since I spawned in a taiga biome in the test world) and I was right clicking with the two spruce logs in my hand and placing one back and breaking it again and it did stack.

However, when TACZ is installed I didn't even had to be in the test world because of the patterns at the start before ever entering the test world itself. The freeze during mod loading and world loading was a dead giveaway to the main issue at hand.

**Comment by Coraline774477** [comment]
I'm guessing that itll happen in my MineColonies world as well if I were to try to debunk MineColonies being the corporate to this issue as well...

I'm starting to think that it has something to do with Forge itself...
Lex did his "magic" yet again with certain mods that he screws up when he's updating forge...

Since one forge update screwed up some mods such as Player Companions for an example with bad TPS lag, like really bad that's perpetual with or without the problematic mods installed which forces me to stop playing with those mods and delete my worlds due to the bad TPS lag and now with mods like MineColonies and TACZ that what I've described above happens when they're installed!...

Now I can see why most of the mod authors  such as the Twilight Forest devs decided to dump forge for NeoForged...
Since I'm getting sick and tired of Lex's bs and I'm not a mod creator for peet sakes!

**Comment by mezz** [comment]
Sorry I'm not really able to follow all of this.
Please let me know if you have a JEI-specific issue, otherwise I think you should try to work this out in a more appropriate forum.

**Comment by Coraline774477** [comment]
I've reported this to the author of TACZ, Going to report the same thing over at MineColonies's github issue tracker.

Also with one more test of mod and world loading has been proven to be successful that the game did not freeze for a minute. So I've confirmed that it's TACZ that's causing the issues. Which also means that I've confirmed that MineColonies is also causing the same issues as with TACZ. I might also report this to McRobertx22 of Mine and Slash...

Since this issue is happening to the main mods of my worlds (other than Epic Fight world, since my TACZ world has Epic fight mod on it and during the tests that I have Epic Fight installed and did not cause the game to freeze or items to not stack.

**Comment by mezz** [comment]
You need to narrow down the mod list to figure out what mod is causing the problem before you go to everyone's issue tracker. You should be able to do that without any knowledge of how the mods work or who made them, just remove mods until the issue isn't happening.

**Comment by Coraline774477** [comment]
I did. It's the main mods of my worlds

**Comment by Coraline774477** [comment]
TACZ, MineColonies, and possibly Mine and Slash.
Lex had done it again with his magic touch and screwed up some more mods yet again

**Comment by mezz** [comment]
ok so if you remove any one of those mods individually, the problem goes away?
how can a mod be "possibly" implicated?

**Comment by Coraline774477** [comment]
Without tacz everything is fine

**Comment by Coraline774477** [comment]
With it the game freezes during mod loading and world loading and items aren't stacking properly

**Comment by Coraline774477** [comment]
I might have stumbled upon a real issue with forge itself then cause three of the five main mods for my five worlds are being affected by the same thing.

I may have to downgrade forge to a previous version when this issue didn't start happening, since I don't remember this happening on 47.3.7 or earlier versions.

I remember before the remake of my MineColonies world that everything was fine and all until I updated forge to 47.3.10. Somewhere between 3.7 and 3.10 lex did something that he didn't told us in the changelogs and now borked the main mods of my worlds

**Comment by Coraline774477** [comment]
So, I was talkin on TACZ's discord server and someone was telling me to just forget about this whole thing and move on since forge is being forge as usual with it's millions of issues that Lex wouldn't fix and I'm afraid that this particular issue won't be fixed any time soon.

So what this means that I've lost 2 of my 6 modded minecraft worlds today to some random forge issue that Lex created and possibly wouldn't be fixing any time soon...

So practically I've done all of this for nothing and wasted your time as well as mine for no particular reason pretty much...

I'm sorry for causing this whole mess,  conundrum, and commotion to begin with....

If you want too you can close this issue as whatever the label is or as "Won't Fix" since I believe that whatever I've encountered is a forge issue not particularly a mod issue. Since the problem is affecting MineColonies and TACZ but not Mine and Slash, Epic Fight and MCA Reborn😞
(those Mods are the main mods of my three remaining 1.20.1 worlds that I have while my fourth world is my 1.19.2 Immersive Engineering world)

Mezz, I'm sorry for all of this as well as wasting your time dealing with this when you could've been using that time dealing with other issue reports that are affecting JEI that you're fixing that deserves your attention more than this possibly false issue report😥

**Comment by Coraline774477** [comment]
One very last thing;
From P3pp3rf1y's issue tracker he told me that MineColonies and TACZ are possibly using a shortcut and are using getOrCreateTag on all items unintentionally which creates empty nbt tags which make those items different from nbt tags that are set to null.

**Comment by Coraline774477** [comment]
Unsecond thought, what if the right clicking bug with the item duping is possibly coming from your mod, mezz.
I'm testing out without JEI on my legitimate world called; Cora World: Epic Fight right now to debunk that claim

**Comment by Coraline774477** [comment]
Nvm.. still happening without it but I am probably getting one step closer though. Since I want this annoyance to stop once and for all

**Comment by Coraline774477** [comment]
Alright, I'll do the debugging properly by taking out all mods but the performance mods and adding back the mods in alphabetical order in groups, already starting with mods group A first until the issue happens again which then I'll focus on that specific group of mods till I find out which one ir ones is causing this issue to happen. However, it certainly is not JEI that's causing this, rest assured.

**Comment by Coraline774477** [comment]
FINALLY!!!!
Found the bugger that's causing the problem. Mo' Enchantments mod.

Plus that mod is a MCreator mod. So of course  it's gonna have shortcuts like getOrCreateTag.

So I'll be closing this issue for you Mezz. Since I've finally figured out which mod it was causing this whole mess.

Thank you for your responses and for your corporation!
