### ISSUE TITLE
Minecraft crashing when opening inventory or using crafting table etc

### ISSUE THREAD

**Issue by Reverber** [mezz/JustEnoughItems#381]
Minecraft launches fine and I can see the mod listed in the mods section in Minecraft, I can configure options for just enough items, world loads ok new world also works, but as soon as i press "e" to enter the inventory or I use a crafting table etc Minecraft crashes. used both versions that were recommended for 1.10.2 and have tried with different versions of forge and the problem is still the same. I have linked the crash log, This specific crash log mentions a couple of other mods but i get the same crash even if I'm just using forge and JEI
Cheers Dude

https://gist.github.com/Reverber/a66ead1bd073a63bd3e3cd8d1f93cb53

**Comment by mezz** [comment]
Thanks for the report!
Can you paste your full `fml-client-latest.log` to gist and link it here? I need some more information that is available there.

**Comment by Reverber** [comment]
Coolio, below are the fml log and updated crash log. i also removed all the other mods it was loading to try and make it easier for you to track down.
FML Log
https://gist.github.com/Reverber/6075c95087797a549b54e6a6cee4c0eb
Corresponding crash log
https://gist.github.com/Reverber/87e32fa40b4a5b994884e16036dd9058

**Comment by mezz** [comment]
Thanks.
This looks questionable: `Found a minecraft related file at C:\Users\Reverber\Desktop\Minecraft\MagicLauncher\Mods\ForeverEnoughItems\jei_1.10.2-3.7.11.238.jar`
Why is there a ForeverEnoughItems folder? JEI should be in the mods directory. Try moving it there.

**Comment by Reverber** [comment]
I was using a mod loader and was using just enough ast art of forever enough so put it in a named folder. Turns out that you can use just enough items with a mod loader and minecraft will start up and run and load worlds and such, but wont let you go tot the inventory, if however you move it to the mods folder in the minecraft directory it will work with modloaders just fine. I was using magiclauncher, it was just weird it loaded and said it was active. ahh well it's working now so thanks for the assist.
