### ISSUE TITLE
NPE when connecting to server if multiple people are online

### ISSUE THREAD

**Issue by utoc** [mezz/JustEnoughItems#382]
I've been having a honey of a time tracking down a crazy NPE issue in the console of MultiMC and the Skcraft Launcher, [seen here](http://pastebin.com/KDhK4dqw) and [seen here](http://pastebin.com/XiS3vXJr).  I've snipped out 98% of the log because the NPEs scroll until the process running the console crashes from being overwhelmed.

You can see the error is not especially easy to track down because it doesn't give any mod information.. I did a little profiling and [came up with this](http://pastebin.com/ri1qMMZq) (It's not very easy to read)

Preview here with exceptions over a 60s period: http://i.imgur.com/uTOQQvj.png

The full java flight recorder is here: http://bbqsauce.terron.com/npe/jfr-08Aug2016.jfr (550kb)
The full log is here: http://bbqsauce.terron.com/npe/NPE.txt (8mb)

Full mod list here: https://www.reddit.com/r/BBQSauce/wiki/modlist

This is not an especially easy bug to track down because it seems to happen only when multiple people are online.  I think this is saying JEI may be the problem but I'm not sure.  And the thing is; this error almost always happens when there is more than one person on the server so its really difficult for me to track down.  Sometimes it happens when its just one person but its its irregular.

Is this JEI or someone elses issue?

**Comment by mezz** [comment]
Unfortunately JEI is not the cause here. The exceptions you see are from JEI pre-checking item models to see if they are safe to display, the exceptions are all caught safely.

In your case, the crash comes from a `SPacketUpdateTileEntity`. This means that some tile entity in your world is creating a bad update packet that crashes. It may not require multiple people on the server, you just need to find the bad tile entity in the world.

**Comment by utoc** [comment]
Any advice how would I go about finding the TE doing that?  The server console has 0 errors, its only the client console logs I have to go on.

**Comment by mezz** [comment]
I don't think there's a good way to figure it out.
I'll make a custom Forge to try to get a better error message. Should take ~10 minutes.

**Comment by mezz** [comment]
Alright this should work, try using this on your client:
installer: https://transfer.sh/Mz68y/forge-1.10.2-12.18.1.0-tile-update-crash-installer.jar
universal: https://transfer.sh/pKeRC/forge-1.10.2-12.18.1.0-tile-update-crash-universal.jar

It should have an error message starting with `Failed to update tile entity at position` on the client. It'll have the block position, unless some mod REALLY messed it up and has it set to 0,0,0 that should let you find it.

**Comment by utoc** [comment]
Wow.  That was such a big help.  Thank you, mezz.  They're all TechReborn machines... Batbox, compressor.     I'll go submit this to their repo.

**Comment by mezz** [comment]
Cool, glad it worked. Can you link back here when you report? I'm curious to see what the issue was exactly.

**Comment by utoc** [comment]
Modmuss already responded back; see reference above.
