### ISSUE TITLE
Missing items 

### ISSUE THREAD

**Issue by OUYEAAAAA** [mezz/JustEnoughItems#383]
When searching something , there are few missing items and it immediately crash when they are on screen. I use 1.10.2 modded minecraft , updated nei to latest version  and the problem is still there , i think the problem is with the Industrial craft 2. crash report : 
[crash-2016-08-09_19.27.32-client.txt](https://github.com/mezz/JustEnoughItems/files/409555/crash-2016-08-09_19.27.32-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This is a crash from another mods, not JEI. The item would crash if it was just in your inventory, without JEI. Please try to find which mod is causing it, by removing mods until the crash goes away.

**Comment by OUYEAAAAA** [comment]
Okay , i have done some testings and it was the Industrial craft 2 mod.

**Comment by OUYEAAAAA** [comment]
So i have searched the IC 2 forum and i found that it is the optifine , problem solved . Thanks for help :)

**Comment by mezz** [comment]
Great! Glad it worked out.
