### ISSUE TITLE
[Bug]: buggy tome texture in jei (iron's)

### ISSUE THREAD

**Issue by VaporeonScripts** [mezz/JustEnoughItems#3858]
### Steps to Reproduce the Bug

https://github.com/iron431/irons-spells-n-spellbooks/issues/675

### Expected Behavior

correct texture

### Actual Behavior

![image](https://github.com/user-attachments/assets/df323dc9-a0dd-4ca8-b5ff-ad0c43b6b018)

### latest.log

no

**Comment by Luningor** [comment]
I believe this is a duplicate of #3856

**Comment by VaporeonScripts** [comment]
It is i think
