### ISSUE TITLE
Opening inventory crashes to desktop

### ISSUE THREAD

**Issue by C0rn3j** [mezz/JustEnoughItems#390]
http://pastebin.com/Dg2NPP65 JEI 242
http://pastebin.com/s1ERwxZG JEI 241

Looks like this is caused by Forge version, because 241 loaded fine on.. I believe it was 2050.

**Comment by C0rn3j** [comment]
242 crashes with server forge 2056/client forge 2053 too.

**Comment by C0rn3j** [comment]
241 works with server forge 2056/client forge 2050, so I guess it's pretty much certain it's a forge update that botched it.

**Comment by Roxforbraynz** [comment]
Able to reproduce. It happens as soon as you open your inventory and the button tries to draw on the screen.
[This is the offending line.](https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/gui/ItemListOverlay.java#L306)

It looks like something changed in GuiButtonExt in the later versions of Forge.

**Comment by TehNut** [comment]
#387

**Comment by Roxforbraynz** [comment]
Removing AppleCore solves the issue.

**Comment by C0rn3j** [comment]
AppleCore just had an update released that fixes the issue.

Now running Forge 2056 and JEI 242 without a problem.

Sorry for not checking closed issues, I assumed it's JEI since the very first lines are relevant to JEI.
