### ISSUE TITLE
[Issue] Only the black wool banner has a recipe. It also does not show the recipe/usage to add a banner to a shield.

### ISSUE THREAD

**Issue by ApedUp3** [mezz/JustEnoughItems#391]
Thank you for reporting!

When reporting:
- If you use ForeverEnoughItems, please remove it and try again or [report here instead](https://github.com/elix-x/Forever-Enough-Items/issues).  
- Please do not suggest features from NEI. [NotEnoughWidgets will have those features.](https://github.com/TheCBProject/NotEnoughItems/issues/6)
- Try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files), it may have fixed the issue already.
- If you crashed, please paste the crash log to https://gist.github.com/ and link it here.

**Comment by mezz** [comment]
Thanks for the report!
I fixed the recipe lookup for banners.
Adding recipes for decorated shields depends on this issue being fixed first: #203
