### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by dexman545** [mezz/JustEnoughItems#392]
When I go to open my inventory, the game crashes.

Crash report: https://gist.github.com/dexman545/9e7a82aa8d4faa7cb310a7fcff60d582

[this is a side thing, when I went to make this issue, it mentioned something called Not Enough Widgets, what is this? I haven't been able to find it anywhere]

**Comment by TehNut** [comment]
#387

**Comment by mezz** [comment]
Thanks for the report!
Update AppleCore  to fix the crash.

Not Enough Widgets was going to be the next version of NEI, but they decided to keep the name NEI. I'll update the issue template so it  doesn't say Not Enough Widgets anymore.
