### ISSUE TITLE
Crashing on start up, using new curse on mac

### ISSUE THREAD

**Issue by CuriousBat** [mezz/JustEnoughItems#393]
https://gist.github.com/CuriousBat/5393c620a0be50da072b6ef7a81d489a
Above is the crash report and it's only having a problem with 2 mods: JEI and Journey map. I've tried opening with with one of them disabled and they are not conflicting. I'm using curse to download the mods, except for the ones i will be adding later that are not on curse. I am on a MacBook Air with Yosemite version 10.10.2, Processor 1.7 GHz Intel Core i5, Memory 4 GB 1600 MHz DDR3, and Graphics Intel HD Graphics 4000 1024 MB.

**Comment by TehNut** [comment]
You are using Java 6. You need at least Java 7.

**Comment by mezz** [comment]
Thanks for the report!
I'm going to look at making JEI support Java 6, since there's no good way to catch this error and Forge only offers an error message for mods that require Java 8, not 7 like JEI.

**Comment by mezz** [comment]
This issue is fixed with JEI 3.9.0+, it supports Java 6 now.
You should still try to update your Java though, other mods will require Java 7 or Java 8.
