### ISSUE TITLE
NEI + JEI together bug

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#395]
After viewing some crafting recipes, i open inventory then hover mouse on every items there was no any item tool tip and i was trying to use chisel (https://minecraft.curseforge.com/projects/chisel) then it crashes. but the crash log doesnt say anything about jei or nei

**Comment by TehNut** [comment]
Post the crash log, please

**Comment by ghost** [comment]
nevermind, i searched it's nei bug
