### ISSUE TITLE
Gives this message on launch

### ISSUE THREAD

**Issue by az5008237** [mezz/JustEnoughItems#396]
"Just Enough Items is missing mods it depends on.
Include the following mods or remove Just Enough Items.

Forge 12.18.2053 or above."

Is there something I'm missing?

**Comment by az5008237** [comment]
I'm using 1.10.2 and have Java Version 8 Update 101.

**Comment by shadowfacts** [comment]
That's the minimum version of Forge you can use with JEI. You're using a version below that.

**Comment by az5008237** [comment]
I assumed it was that and tried to update it, I thought I did but I didn't lol

**Comment by az5008237** [comment]
Thanks for your help, it's working now. I had to switch the version in the profile and I didn't realize that.
