### ISSUE TITLE
1.10.2 Missing Inventory and Console Spam

### ISSUE THREAD

**Issue by MokahTGS** [mezz/JustEnoughItems#397]
JEI 3.9.0.244
Forge .2064

No crash but when I open my inventory it's all blank and the console spams errors until it stops logging.

**Comment by mezz** [comment]
Thanks for the report!
Can you paste your log to gist.github.com and link it here?

**Comment by MokahTGS** [comment]
https://dl.dropboxusercontent.com/u/9882100/Minecraft/latest.zip

Too big for pastebins...

**Comment by mezz** [comment]
Thanks!
gist.github.com allows extremely large pastes.
This is a duplicate of #387, you can fix it by updating AppleCore to the latest version.
