### ISSUE TITLE
[API Request] Remove limitation of IRecipeTransferInfo

### ISSUE THREAD

**Issue by Aroma1997** [mezz/JustEnoughItems#398]
I have multiple machines with different sets of recipes, that use the same Gui and Container Class. Right now, there is no way for a IRecipeTransferInfo to determine the recipe category allowed by this machine.
To solve that, either getRecipeUid() Gui/Container-aware or preferrably to replace getContainerClass():Class<C> with a method accepts(C):boolean, so you can register mutliple IRecipeTransferInfo instances for the same container class.

**Comment by mezz** [comment]
There is a new method like you suggested in 1.11:
`IRecipeTransferInfo.java`

``` java
boolean canHandle(C container);
```
