### ISSUE TITLE
[Idea] Re-implement the shift-click-questionmark-into-crafting-grid functionality

### ISSUE THREAD

**Issue by Vexatos** [mezz/JustEnoughItems#4]
And, if you do it in creative mode, it could automatically cheat the necessary items in for you.

**Comment by mezz** [comment]
Woo! This was very tough to implement correctly.

**Comment by asiekierka** [comment]
![](https://2982-presscdn-29-70-pagely.netdna-ssl.com/wp-content/uploads/2015/04/Shut-up-and-take-my-money.jpg)

**Comment by mezz** [comment]
[Also works with non-stacking items.](http://gfycat.com/IcyPiercingKakapo)
