### ISSUE TITLE
Crash on joining server [JEI failed to start]

### ISSUE THREAD

**Issue by robaimes** [mezz/JustEnoughItems#401]
Joining a specific server causes me to crash when logging in: http://pastebin.com/60FKrJrb

NEI is installed, but this crash happens whether it is installed or not. Also not 100% sure it's a JEI issue directly, so apologies if this is invalid.

JEI: `jei_1.10.2-3.9.0.244`
Forge: `forge-1.10.2-12.18.1.2065-universal`

**Comment by robaimes** [comment]
Update: Done some testing and found the cause of the issue.

If Botania is installed on the client, but the server you are connecting to does not have it installed, the above error occurs.

Leaving the issue open in case there is an underlying issue, but will refer the issue to the Botania repo. :)

**Comment by vladfrangu** [comment]
Thats cause it seems like it looks for the item server side? I'm not too sure.

**Comment by vladfrangu** [comment]
Yeah, seems like a client side mod breaks JEI, as whenever you look that mod up, if it isn't server side, it'll crash you.

I recommend just not joining servers without those mods installed, as its generally not intended.

**Comment by williewillus** [comment]
mezz can you tell from a glimpse at the log why this happens (to just botania according to some word of mouth reports) and if there's any way I can fix it?

**Comment by mezz** [comment]
This happened with ActuallyAdditions too. They just didn't have the mod on the server, so the item wasn't registered. I thought the game would not let you join if you have a mod in the client that requires the server, and that mod is absent from the server. I'm not entirely sure what's going on here.

**Comment by KnightMiner** [comment]
I think you have to manually block connection. I know Tinkers does not unless both have different versions as some people setup systems with Bungee Cord where you connect to a vanilla server and it redirects you to the modded one.
