### ISSUE TITLE
Walls from the quark mod show up twice in JEI, the second time with the black/purple error texture

### ISSUE THREAD

**Issue by Lothrazar** [mezz/JustEnoughItems#402]
My version is  jei_1.10.2-3.9.0.245.jar

Not a crash, just graphic issue.

Screenshot of the problem

http://i.imgur.com/AR9jhWE.png

I do not believe it is the fault of Quark however.  There is another recipe type mod called guidebook, and it does not show the error/duplicate textures:   http://i.imgur.com/r2gsE5e.png

**Comment by mezz** [comment]
Thanks for the report!
Looks fine to me with the latest JEI and Quark. Can you confirm it happens with just JEI and the latest Quark?
![2016-08-21_19 15 21](https://cloud.githubusercontent.com/assets/916092/17842047/a8151f50-67d3-11e6-8dd5-b0293eb3f949.png)

**Comment by mezz** [comment]
Thanks for the report!
This only shows up if you go to JEI's options and set "Hide Items With Missing Models" to false. If you use JEI's default settings, this error is not visible.
I'm pretty sure this is a Quark issue since no other item has that problem.

**Comment by Lothrazar** [comment]
ok cook ill check out that config option!  Yeah im guessing there might be another model for connected vs unconnected walls.
