### ISSUE TITLE
Potion Packs Recipe Issue

### ISSUE THREAD

**Issue by jjc54** [mezz/JustEnoughItems#405]
Potion Packs: PotionPacks_1.10_b6b
Forge: forge-12.18.1.2053
JEI: jei_1.10.2-3.9.0.245
 
Issue: Most of the potion pack recipes are mixed up. For instance, the pack for leaping 1 has invisibility potions in the JEI recipe. The crafting recipes are correct and yield the correct pack, but the recipe is messed up and as posted https://minecraft.curseforge.com/projects/potion-packs?gameCategorySlug=mc-mods&projectID=74078#c15 the potion packs dev believes it is a JEI issue.
Example: http://imgur.com/a/MRD89

**Comment by mezz** [comment]
Thanks for the report!
Their mod's crafting looks pretty straightforward, I'll look into it.

**Comment by mezz** [comment]
It looks like the mod uses raw potion ID numbers instead of their proper registry names. The numbers can change, most likely causing the issue you see. The mod author should use registry name strings instead of int for the `potionID` in their `Recipe_Potion` class.

**Comment by jjc54** [comment]
Oh okay, thanks for looking into it. I'll link the mod author to this report!

**Comment by Domochevsky** [comment]
Eenteresting. I have yet to actually find the proper registry names of potions. Can you point me at their general direction? They're all subtypes of the Potion item, which is water at its base.
(There's barely any documentation to be found in that regard.)

**Comment by mezz** [comment]
Have a look at `PotionType`, you can use that class to convert between the potion's registry name and its ID.

**Comment by mezz** [comment]
`PotionUtils` also has methods to get the `PotionType` from items, so that could be useful too.

**Comment by Domochevsky** [comment]
What I'm doing right now is this:

```
int potionID = Potion.getIdFromPotion(this.potion.getPotion());
ItemStack potion = PotionUtils.addPotionToItemStack(new ItemStack(Items.POTIONITEM), PotionType.getPotionTypeForID(potionID));
```

Which already utilizes both classes. Is there some intermediate step I'm not seeing?

**Comment by TehNut** [comment]
You're doing it based on the numeric ID which can change. Use the registry name.

**Comment by Domochevsky** [comment]
K, where is that? It's not in the item registry.

**Comment by TehNut** [comment]
`Potion#getRegistryName()`
