### ISSUE TITLE
Cheat Mode Not Working

### ISSUE THREAD

**Issue by HighBridRed** [mezz/JustEnoughItems#408]
Thank you for reporting!

When reporting:
- If you use ForeverEnoughItems, please remove it and try again or [report here instead](https://github.com/elix-x/Forever-Enough-Items/issues).  
- Please do not suggest features from NEI. [See this spreadsheet for the mods with those features.](https://goo.gl/MQ0f3R)
- Try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files), it may have fixed the issue already.
- If you crashed, please paste the crash log to https://gist.github.com/ and link it here.

**Comment by TehNut** [comment]
5/7 description of the issue.

**Comment by HighBridRed** [comment]
Cheat......Mode......Not.......Working..............

whats so confusing about that issue?
An answer like "Do you have cheat mode enabled in the config?" would've been a better response.

**Comment by way2muchnoise** [comment]
The fact you didn't even remove the template or write a little description that is more than the title. Some thing like is it in SP or MP and what version of MC and JEI are you using?

**Comment by AEnterprise** [comment]
also make sure you are an OP or have permission to execute the give command

**Comment by HighBridRed** [comment]
I'm an owner on my own server
i pay for a host
i have the correct 1.9.4 versions for all mods and server version.
i clicked enable cheat mode
im in creative mode
I'm using Jei & fei & excore ( the client send an error message telling me to download all these mods at once) idk why but Yes it tells me to download Forever enough items & excore & just enough items.

No idea why it would force me to download someone elses alternative mod because i would think it would conflict with each other, but hey.

**Comment by TehNut** [comment]
Now that we have some basic information, go read the first bullet point in the template you posted.

**Comment by HighBridRed** [comment]
I told you, the game gives me an error telling me to go download Forever Enough Items. Like it's a requirement or something. The client does not allow me to play Minecraft without it, it blocks the game off with that error message.

**Comment by KnightMiner** [comment]
What is the exact error message? Normally that means you have a mod that requires it which you should remove too.

**Comment by HighBridRed** [comment]
Can someone just send the 1.9.4 NEI mod please? because every website I use gives me a fked up file.

**Comment by TehNut** [comment]
The only site you should be using is CurseForge. And none of those files are "fked up"

**Comment by HighBridRed** [comment]
See what I mean.... "fked up files".....

![untitled](https://cloud.githubusercontent.com/assets/21225394/17985543/2d1b62dc-6acb-11e6-845f-aea09a0b312f.png)

**Comment by shadowfacts** [comment]
We can't even see the entire crash as you posted a screenshot, not the text itself.

**Comment by way2muchnoise** [comment]
`codechicken.nei.asm.NEICorePlugin` tbh where is the issue with JEI?

**Comment by AEnterprise** [comment]
i see what's going on: you are using mismatched versions of NEI, eighther the NEI version is for the wrong MC version or you don't have the matching version of chickencore

the official place to download NEI is http://chickenbones.net/Pages/links.html use the dropdown at the top to select the right MC version

**Comment by HighBridRed** [comment]
Do I use the Deobf? or the source? or do I use the Universal version?

**Comment by AEnterprise** [comment]
universal

**Comment by HighBridRed** [comment]
Dam that was fast ok thanks ill try that

**Comment by HighBridRed** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21225394/18010131/0fedf9b0-6b64-11e6-99b2-7966c372e913.png)

![2](https://cloud.githubusercontent.com/assets/21225394/18010153/231cff90-6b64-11e6-8616-c633647c3c92.png)

**Comment by HighBridRed** [comment]
am i suppose to be using forge? I use forge

**Comment by HighBridRed** [comment]
Fixed it, I had to download CodeChickenCore + CodeChickenLib + NotEnoughItems into the forge mods folder. They don't tell you that it's a requirement, but it is.

**Comment by way2muchnoise** [comment]
How did this issue end up on this tracker? It has literally nothing to do with JEI or any of its addons.

**Comment by HighBridRed** [comment]
Because at first I was using Just enough items and never enough items at the same time, then that guy said to remove it and keep NEI instead. :) need me to explain more obvious stuff to you?

**Comment by WayofTime** [comment]
Yeah - is your last name Trump or something?

**Comment by mezz** [comment]
Looks like I took my vacation at the right time :P
