### ISSUE TITLE
[1.10.2] Inventory View Crash 

### ISSUE THREAD

**Issue by TheXWolf** [mezz/JustEnoughItems#409]
Recently updated to forge 2073 went back as far as I could but every time I open even my regular (E) inventory, or a special inventory (i.e. a toolbox) the view crashes and JEI throws an error.
Crashlog: [http://pastebin.com/A1D2v46J](url)

Was using 246, tried 244 & 240, still having the same crash.
Most recent error came from Apple Core so I'll be reporting it to them as well, not sure if it's a compat issue or something of theirs.

**Comment by GirafiStudios** [comment]
What version of Apple Core do you have?

**Comment by TehNut** [comment]
Update AppleCore and install AppleSkin.

**Comment by TheXWolf** [comment]
Already had most recent apple core, wasn't aware of AppleSkin. Thanks that fixed it.
