### ISSUE TITLE
Toggling the GUI shortcut

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#413]
Could you make it so that pushing the o key will toggle the gui?

Also, if you could somehow sync the appearance with nei, that would be great.

**Comment by KnightMiner** [comment]
There already is a key for that, check the controlls page.

And why would JEI look like NEI? The search bar in the center only caused it to be blocked by more GUIs, and anything else is minor differences.

**Comment by ghost** [comment]
JEI is built on top of existing NEI, try pusing the O key in-game. it will toggle the NEI portion of the mod, but not the JEI portion.

**Comment by KnightMiner** [comment]
JEI is built independent of NEI. They are two separate mods.

The JEI hiding key should by default be Ctrl-O
