### ISSUE TITLE
Crash on item search

### ISSUE THREAD

**Issue by seraph-g** [mezz/JustEnoughItems#414]
I was using JEI with NEI added with no problems for a while. Then, the game crashed upon opening my inventory. Removing NEI fixed this issue. Now, when I attempt to search for an item in JEI, the game crashes after entering the third character. 

Crash log: https://gist.github.com/gwingle/51b0d7f24527e14e141c105f1f49ae27

EDIT: Attempted to simply click through the pages, crashed again on reaching page 23. Log: https://gist.github.com/gwingle/f7712ee9375a588b0815da0e2655b490

**Comment by TehNut** [comment]
A mod in your instance has a bad render.

**Comment by seraph-g** [comment]
How can I solve that issue? It was working fine and randomly broke.

**Comment by seraph-g** [comment]
Issue is magically resolved, no clue what was wrong.
