### ISSUE TITLE
JEI / NBT Data on items in recipes using CraftTweaker

### ISSUE THREAD

**Issue by utoc** [mezz/JustEnoughItems#415]
FML 2011 - 2073 (Tried several versions)
JEI 227-246 (Tried several versions)
CraftTweaker 3.0.10

```
val f1pk = <minecraft:golden_pickaxe>.onlyWithTag({ench: [{lvl: 1 as short, id: 35 as short}], RepairCost: 1});
val f3pk = <minecraft:golden_pickaxe>.onlyWithTag({ench: [{lvl: 3 as short, id: 35 as short}], RepairCost: 1});
recipes.addShaped(<minecraft:dirt>, [[null, null, null], [null, f1pk, null], [null, null, null]]);
recipes.addShaped(<minecraft:stone>, [[null, null, null], [null, f3pk, null], [null, null, null]]);
```

The above is a very simple CT script that will make 1 dirt if you feed it a Fortune 1 enchanted golden pickaxe and 1 stone if you give it a Fortune 3 enchanted golden pickaxe.  The recipe works as it should when you place the pick in a crafting table; you are given the result of a stone or dirt, depending on the pickaxe used.  Seen here: http://i.imgur.com/1BPpd4L.png

However, when you look at JEI, the pickaxe in the recipe shown isn't enchanted. http://i.imgur.com/S9ebaec.png

Whats unusual about this is that I really thought I had put this issue to bed a month ago with some simple mistakes in my CraftTweaker scripts.. but no, I've simplified these as much as possible and I think at this point I can rule user error and CraftTweaker out.  I've removed all other mods for testing as well.  Thank you!

**Comment by utoc** [comment]
@mezz, I have another that is related to ModTweaker; (botania modtweaker mana infusion recipe not showing up in JEI).  Should I post to this thread or make a new one?

**Comment by mezz** [comment]
Sorry I overlooked this first issue. It's difficult to debug because I do not have modtweaker set up, so it may take me a while to get time to check out this bug.

The second one sounds like something different, I think it's a modtweaker issue because Botania's regular recipes show up without a problem.

**Comment by utoc** [comment]
The first issue can be diagnosed with Minetweeker alone, no need for modtweaker (or was that a typo?) 

Should I forward the second issue to Modtweaker then?

**Comment by mezz** [comment]
Yes, I think you should forward it to them.

**Comment by cookta2012** [comment]
so this bug still exists im just waiting :p

**Comment by goosezilla** [comment]
https://github.com/jaredlll08/ModTweaker/issues/394

Same issue I think, would be amazing to get this fixed.

**Comment by mezz** [comment]
Please see my replies in #653 that show this is not an issue on JEI's side.
