### ISSUE TITLE
No Contact Info On Curse

### ISSUE THREAD

**Issue by jredfox** [mezz/JustEnoughItems#416]
No Contact Info On Curse. I wanted to contact you to ask how you got all of the items / blocks into the pages of JEI?  I know someone who wants to iterate through the entire list of items but, I can't seem to find out where that is.

**Comment by way2muchnoise** [comment]
You just go over both `Item.REGISTRY` and `Block.REGISTRY`

https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/ItemRegistryFactory.java#L47-L72

**Comment by TehNut** [comment]
`ForgeRegistries.ITEMS` and `ForgeRegistries.BLOCKS` are probably a safer way to get them.

**Comment by mezz** [comment]
Feel free to ask questions on IRC, you probably don't need answers from me specifically (see helpful people above).

**Comment by jredfox** [comment]
Yeah thanks I helped a person out with that statement.  I got him to make his own complex mod
