### ISSUE TITLE
inventory and other GUIs (I tried chest, golden bag, bagginses bag, mekanism, ender i/o) are partially transparent

### ISSUE THREAD

**Issue by croftyraider** [mezz/JustEnoughItems#418]
I originally reported this to Blusunrize because I thought it was an Immersive Engineering because I had just added that mod, but it turns out to be unrelated and he was helpful and suggesting some things.

Here is my final post to his github issue tracker:

Ok, it took a bit of doing, but I managed to test with the latest JEI (had to update forge and then all heck broke loose). The bug as it stands is still there, and I can't seem to point a finger at a single mod. Here is the reduced modlist using forge 2075:

Chameleon-1.9.4-2.1.6.jar*
CodeChickenCore-1.10.2-2.1.8.79-universal.jar*
EnderStorage-1.10.2-2.1.3.73-universal.jar*
jei_1.10.2-3.9.0.244.jar*
journeymap-1.10.2-5.2.4-unlimited.jar*
JustEnoughResources-1.10.2-0.4.6.41.jar*
refinedstorage-0.9.4.jar*
StorageDrawers-1.9.4-3.2.0.jar*
Waila-1.7.0-B3_1.9.4.jar*
WailaHarvestability-mc1.10-1.1.7.jar*
Wawla-1.10-2.3.0.193.jar*

What I do know is that it does happen repeatably, and that somehow by having items from EnderStorage, RefinedStorage and StorageDrawers showing on the JEI screen the bug appears (search term of @stor does it every time). Just having one mods items does not show the issue. I did notice this time that when the tooltip is flown for the items that the transparency on the GUI disappears...

One more piece of data - the creative inventory does not go transparent, so I used it to generate a chest and place it down and then right click to open the chest GUI with @stor as the search term and the problem appears.

**Comment by mezz** [comment]
Thanks for the report!
It seems like one of the items is causing issues with OpenGL.
Try searching `@ender`,  `@refined`, and `@drawers` separately to see which mod is causing the problem, then report to them.

**Comment by mezz** [comment]
@croftyraider any update?

**Comment by croftyraider** [comment]
Sorry for the delay - I was out of town on vacation. As per my original post, the JEI display needs to have all the items present I mentioned. Refining the search to a single mod's item does NOT cause the error, only when all of them are showing.

Here is an updated list using what was the current version of your mod at the time I reported the issue, using forge version 2075:

Chameleon-1.9.4-2.1.6.jar*
CodeChickenCore-1.10.2-2.1.8.79-universal.jar*
EnderStorage-1.10.2-2.1.3.73-universal.jar*
jei_1.10.2-3.9.0.244.jar*
journeymap-1.10.2-5.2.4-unlimited.jar*
JustEnoughResources-1.10.2-0.4.6.41.jar*
refinedstorage-0.8.10.jar*
StorageDrawers-1.9.4-3.2.0.jar*
Waila-1.7.0-B3_1.9.4.jar*
WailaHarvestability-mc1.10-1.1.7.jar*
Wawla-1.10-2.3.0.193.jar*

To repeat the test:

I used MultiMC, set it to use 1.10.2 for minecraft. After that I edited the instance and installed forge version 2075. Then I added in all those mods.

Once those are in the pack, I play minecraft and make a new world. Go to your inventory and type in exactly "@stor" (without the quotes). Switch from creative inventory to survival and you'll see the issue. Mouse over random items and the error goes away.

**Comment by mezz** [comment]
Thanks for narrowing it down. 
I did some testing: if I hide EnderStorage's Ender Chest and Ender Tank from the item list, the problem goes away. You can further confirm this by having those items in your inventory; it messes with the lighting of other regular items in the inventory.
Please report to EnderStorage here: https://github.com/TheCBProject/EnderStorage/issues

**Comment by croftyraider** [comment]
Thanks!
