### ISSUE TITLE
Crash in dev-env

### ISSUE THREAD

**Issue by modmuss50** [mezz/JustEnoughItems#42]
This happens when I try to open the inventory, it hard crashes the game.

https://gist.github.com/modmuss50/0f440d67192104e680ab

This was added to my 1.8 gradle in the following way:

https://gist.github.com/modmuss50/e070c8c95e3fb96a2a5d

**Comment by mezz** [comment]
After a long investigation, it looks like a ForgeGradle issue.
Temporary fix is to run: `gradlew cleanDeobfMcSRG && gradlew setupDecompWorkspace`
I'll add this to the readme.
