### ISSUE TITLE
Possebility to remove Recipes

### ISSUE THREAD

**Issue by mcenderdragon** [mezz/JustEnoughItems#420]
After I looked in several files and tried to unterstand how the API works, I have not found a way to stop JEI from adding recipes. This may sounds weird, because we want to display Recipes but in my case I am adding a custom crafting recipes only craftable at an own table with additional ressources. But only the normal recipe part is displayed in JEI, so most people shout "there is a Bug, your recipes don't work!". 
Or have I missed a part where this is possible?

Edit:
 I found the IRecipeHandler, it has a function isRecipeValid if I return false for all recipes, then they wont get displayed right?

**Comment by mezz** [comment]
If your recipe is not a crafting table recipe, you should not add it to Minecraft `CraftingManager`. This is where JEI gets the crafting recipes, they are all expected to work with the crafting table.

**Comment by mcenderdragon** [comment]
Well the dificulty is to use my recipes AND vanilla recipes. But yes I overloecked this (too simple) option ^^.
