### ISSUE TITLE
You redecorated, I don't like it

### ISSUE THREAD

**Issue by Dijkstra1-zz** [mezz/JustEnoughItems#427]
I have noticed, now a long the top of JEI instead of showing, one item at a time that can craft items you show as many as you can, I like that you have do this but it just does not look right. 

Do not change back just for me.

**Comment by mezz** [comment]
Ok, thanks for the feedback. I think the better usability here trumps the slightly derpy look of it though.

**Comment by DanHolli** [comment]
maybe have a config option to change it back?
