### ISSUE TITLE
[3.9.4] Recipe transfer not working

### ISSUE THREAD

**Issue by miuirussia** [mezz/JustEnoughItems#428]
If I click on [?] icon, nothing happens. On 3.9.3 it works normally.

Maybe problem is here:
- Split the BasicRecipeTransferHandler into client and server-side parts

**Comment by mezz** [comment]
Thanks for the report!
Confirmed. I fixed something with potion brewing but somehow broke everything else. I'll take a look.
(Also this is why I release small version updates so often, you can always use the old one heh)

**Comment by mezz** [comment]
Fixed in version 3.9.5
