### ISSUE TITLE
[Suggestion] Double-Clicking Search Bar blacks out items in inventory / bags / chests that are not searched for

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [mezz/JustEnoughItems#432]
I dunno what it's called or if I'm missing it how to enable it, but NEI used to have this feature where when you double click the search bar it blacked out the items that were NOT searched for.

For instance if I typed gold into it, double clicked it, the everything that didn't have "gold" in it's name was blacked out in my inventory, chests and bags.

**Comment by shadowfacts** [comment]
@mezz has already said that old NEI features like this won't be included in JEI. As you can see from [this spreadsheet](https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w), More Overlays provides the inventory search functionality you're looking for.

**Comment by mezz** [comment]
More Overlays works well. Their default hotkey for it is "Z".
