### ISSUE TITLE
Crash random times.

### ISSUE THREAD

**Issue by mightydanp** [mezz/JustEnoughItems#434]
This happens after letting a world load a bit and then looking around in Jui area on the right. It also sometimes happends when i open my inventory.

https://gist.github.com/mightydanp/2173a3faf37a0dec2989335e0affe119

**Comment by mezz** [comment]
Thanks for the report!
You have FEI installed, please try without it.

**Comment by mightydanp** [comment]
@mezz it still happens after i take it out but it takes way longer to happen then with just Jei on. I Think one of my mods dont like Jei

**Comment by mezz** [comment]
Please paste a full crash log when you are not using FEI so I can take a look.

**Comment by mezz** [comment]
Oh, and also try without Optifine. There was a similar crash (to what's at the bottom of your log) that was just reported to them today.

**Comment by mightydanp** [comment]
i dont have optifine installed

**Comment by mightydanp** [comment]
https://gist.github.com/mightydanp/06dbd8f674ac06ccb5e9f7025c59137b

**Comment by mightydanp** [comment]
I seem the have fixed it some how? Very odd. Thank you.

**Comment by mezz** [comment]
Hm your log posted says

```
OptiFine Version: OptiFine_1.10.2_HD_U_C3
```

Did removing it fix your issue, or was it something else? It's important to know so I can help other people with the same problem.

**Comment by mightydanp** [comment]
i removed it i totally forgot optifine was in there. The only problem i am having at the moment is some recipes you cannot see what can make it

**Comment by mezz** [comment]
Ok thanks. I think this is a dupe of #372 if it's because of Optifine.

**Comment by DanHolli** [comment]
I ve he is meaning the list of items in the right side which falls under the same error as #372  but only crashes when viewing certain blocks which is consistent unlike mine
I used to have this problem before uninstalled that mod (?covers?) and worked fine (except for bug #372 )
