### ISSUE TITLE
[Request] View all recipes of a certain category

### ISSUE THREAD

**Issue by TehNut** [mezz/JustEnoughItems#44]
As discussed on IRC

    <TehNut> Oh, thoughts on adding a way to view all recipes for a category?
    <TehNut> IE: Clicking the arrow in NEI
    <mezz> TehNut: that should be easy, thinking it'll show up when you click the category title

**Comment by mezz** [comment]
You can now click the recipe category title to see all the recipes.
![2015-12-02_14 18 30](https://cloud.githubusercontent.com/assets/916092/11546092/f9000c52-98ff-11e5-9fd2-cea618e8f27e.png)
