### ISSUE TITLE
[1.10.2] False required number recipe (abot redstone)

### ISSUE THREAD

**Issue by Gayanfalor** [mezz/JustEnoughItems#443]
Hello guys, 

just seen that this morning, wanted to craft some machines etc in my updated pack, when looking to make a piston its the default recipe but showing its using 2 redstone insted of 1 and its consuming only 1 redstone.

I didnt tested yet too fore the enderio capacitor wich defautl recipe need 4 redstone here its showing 8 redstone needed.

ps:
Using: forge  2092
JEI 261
ender io 107

![capacitor](https://cloud.githubusercontent.com/assets/10771109/18715853/087aed34-801b-11e6-91c0-b3a8d3eb2974.jpg)
![piston](https://cloud.githubusercontent.com/assets/10771109/18715852/086fb3b0-801b-11e6-9ca5-f2237d5bf9eb.jpg)

Here the chance to get dust or else in the enderio sagmill gui are not shown (but it could not come from JEI),when clicking on the recipe paper in the gui but just click on the gold dust and the chances are shown.

a bit strange ^^
![sagmill](https://cloud.githubusercontent.com/assets/10771109/18715854/087ee100-801b-11e6-83e5-3516545f22da.jpg)

**Comment by mezz** [comment]
Thanks for the report!
This is unlikely to be a JEI issue, someone is probably accidentally editing the ItemStack for redstone. Try removing mods until the piston recipe is correct again, so you can find which mod is causing the problem.

**Comment by mezz** [comment]
Any update @Gayanfalor ?

**Comment by Gayanfalor** [comment]
Hey hello, i dont know i havent played for long time, and i've seen there is many update for JEI, should i update to beta version ? usually i use the release version (the green one).

Btw there is many update too for my other mods and can possibly fix the problem too. I can try by updating all mods

**Comment by mezz** [comment]
The JEI version should not matter. The best thing to do is to try removing mods until the piston recipe is correct again, so you can find which mod is causing the problem. Once you've done that you can update it to see if anything was fixed.
