### ISSUE TITLE
[Bug][1.10.2] Rendering Screen NPE

### ISSUE THREAD

**Issue by MysticAura** [mezz/JustEnoughItems#444]
MC: 1..10.2
Forge: 2086
Mod Version: jei_1.10.2-3.10.0.262

Crash when looking through EXU2's upgrade recipes
[Crash Log](http://pastebin.com/hTYCmrKF)

On one side, maybe I should turn off color search. On the other hand.. I'm helping! (hopefully) Your job would be much easier once they clean up their npe's

**Comment by mezz** [comment]
Thanks for the report!
Fixed in JEI 3.10.0.263
