### ISSUE TITLE
Cheat mode give bypasses CommandEvent

### ISSUE THREAD

**Issue by Thutmose** [mezz/JustEnoughItems#445]
The way forge does CommandEvent, only has them sent after icommand.checkPermission(server, sender)
has returned true.  This means that to make a Permissions mod without coremod hackery, requires making that method always return true, by settings PlayerList.commandsAllowedForAll to true.

The problem then comes from when JEI checks icommand.checkPermission(server, sender), and gives the item if it is true, without sending a CommandEvent, and checking if that is canceled.  This will result in any player being able to use the cheat mode, even if a permissions mod would prevent it via cancelling CommandEvent.

See Thutmose/Thut#14 for where it was reported to me, or MinecraftModDevelopment/MMD-Dev-Server#193 for where it was discovered.

At some point I might get around to reporting this to minecraft forge itself, but I am not sure if I currently have time to get around to trying to make a PR for them.

**Comment by mezz** [comment]
This should work, let me know if something is still not right.
