### ISSUE TITLE
Show furnace fuel time in terms of how many items can be smelted

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#451]
Showing the number of ticks that an item burns is OK, but it would be better if it showed how many items can be smelted instead (since all items take the same amount of time to smelt).

**Comment by KnightMiner** [comment]
Item smelting time might be able to change if MinecraftForge/MinecraftForge#3141 gets pulled, plus since some mods use the furnace fuel registry for their own machines it might be relevant to keep time on there (maybe in seconds) even if items is stated

**Comment by mezz** [comment]
Thanks for the heads-up.
In order to take that into account, I think it makes sense to list the time next to the number of "normal" items it can smelt. That should cover everything and still be easy to read.
