### ISSUE TITLE
Crash when viewing all recipes

### ISSUE THREAD

**Issue by squirrelkiller** [mezz/JustEnoughItems#454]
Cycling through crafting types while viewing all recipes led to this crash:
http://pastebin.com/tvdy6FWF

**Comment by mezz** [comment]
Thanks for the report!
Confirmed.

**Comment by mezz** [comment]
I fixed this error by making JEI log the problem instead of crashing.
The new log let me track down which mod was causing the problem, I made a PR to fix the issue for them here:
https://github.com/WayofTime/BloodMagic/pull/933

**Comment by squirrelkiller** [comment]
You're a wizard mezz.
