### ISSUE TITLE
Crash on client launch

### ISSUE THREAD

**Issue by DMIL421** [mezz/JustEnoughItems#456]
Crashing using the most recent version of JEI from Curseforge. Crash Log: https://gist.github.com/DMIL421/4acc8444000958db1906f9979fa4eb11

Let me know if there's anything else I can provide.

**Comment by TehNut** [comment]
This is caused by More Overlays.

**Comment by DMIL421** [comment]
Oops, missed an update. I'll update that and then see if it fixes the crash. I'll update and close if so.

**Comment by DMIL421** [comment]
Yep, that fixed it. Closing ticket.
