### ISSUE TITLE
Crash - jei_1.10.2-3.11.1.273

### ISSUE THREAD

**Issue by BubbaVB** [mezz/JustEnoughItems#457]
I just updated from jei_1.10.2-3.10.0.268 to jei_1.10.2-3.11.1.273 on a modpack I'm building.  On the previous version everything worked fine.  However after the up, I'm able to load MC but it crashes when I try to open a save or create a new world.

Here is a link to the crash report via pastebin [http://pastebin.com/ivXuLbfq](http://pastebin.com/ivXuLbfq).

(Note:  I am using FEI in my modpack)

**Comment by way2muchnoise** [comment]
You'll have to use JEI 3.10 until the next Refined Storage release. I fixed it in raoulvdberge/refinedstorage#387

**Comment by BubbaVB** [comment]
Thanks, sorry for the dupe ticket.  I didn't realize it had already been reported.

**Comment by mezz** [comment]
No worries, I'd rather get duplicate reports than have nobody reporting an issue.
Duplicate of https://github.com/mezz/JustEnoughItems/issues/453
