### ISSUE TITLE
Crash when trying to view recipes for EIO Vat fluids.

### ISSUE THREAD

**Issue by DMIL421** [mezz/JustEnoughItems#458]
When trying to view recipies for EnderIO fluids, I get a client crash.

Crashlog: https://gist.github.com/DMIL421/fe6a546491cc166679869d85b3aa6b83

Let me know if there is anything else I can help with on this.

**Comment by GirafiStudios** [comment]
Have already been fixed here: https://github.com/SleepyTrousers/EnderIO/commit/86dea82f7f15373170f2f38613bd96f4a1ea9607, so it will be fixed whenever Ender IO release a new build :)

**Comment by DMIL421** [comment]
Cool, Thanks Girafi. I'll close this.

**Comment by mezz** [comment]
In the meantime you should be able to use JEI 3.10.
