### ISSUE TITLE
recipe list disappear in forge 1.10.2

### ISSUE THREAD

**Issue by xarroyo** [mezz/JustEnoughItems#459]
The recipe list disappear few seconds after open inventory but there is no log or error...

**Comment by GirafiStudios** [comment]
What version of JEI are you using ? :)

**Comment by xarroyo** [comment]
I'm using jei_1.10.2-3.11.0.269

**Comment by mezz** [comment]
Thanks for the report!

To help us figure out this issue, please:
- force a crash (hold F3+C for 10 seconds and then let go)
- paste the crash log to [gist](https://gist.github.com/)
- link it here

**Comment by xarroyo** [comment]
Thank you so much! here is the link
https://gist.github.com/xarroyo/67e876296d230383014c2da74d0103c5

**Comment by mezz** [comment]
Try removing NEI and see if that fixes it.

**Comment by xarroyo** [comment]
No, I tried with and without NEI and/or CodeChicken and the result were the same all the times :(

**Comment by mezz** [comment]
How about removing Better HUD? That's the only other "interface" mod in your list.
If that's not it, try removing more mods until you find which one is causing the conflict. JEI is working fine by itself so I assume there is a mod conflict somehow.

**Comment by xarroyo** [comment]
Perfect! You are completely right. Better HUD was causing the conflict.

Thank you so much! :)

**Comment by mezz** [comment]
Not so fast heh! Please report the bug to Better HUD and link back here.
