### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by vrork** [mezz/JustEnoughItems#464]
Minecraft crash when loading world with that crash log

http://pastebin.com/zp9qG259

**Comment by TehNut** [comment]
Caused by Armor Plus

**Comment by vrork** [comment]
Yeah, and JEI Forestry Bees too. Do i need to poke them or you here can poke them?

http://pastebin.com/LBWAK1Ab

**Comment by Unrepentant-Atheist** [comment]
Yea, can confirm. Still crashing https://gist.github.com/anonymous/c8d3dbf38182cb4f398bd8c868616625

**Comment by TehNut** [comment]
This isn't an issue to confirm here. Go report it to the respective mod authors. These are 100% not JEI's issue.

**Comment by mezz** [comment]
The latest JEI should log this error instead of crashing. Pretty sure things will still blow up later though, make sure to report the bugs to their respective authors so they can fix it.
