### ISSUE TITLE
crash upon loading multiplayer connection. jei unable to start

### ISSUE THREAD

**Issue by kain184** [mezz/JustEnoughItems#465]
https://gist.github.com/mezz/54b2054167f1a0d20e4918b8f5e60e77

**Comment by mezz** [comment]
Thanks for the report!
This is a TSON Craft issue and has already been reported to the mod author: https://minecraft.curseforge.com/projects/tson-craft/issues/8
Duplicate of https://github.com/mezz/JustEnoughItems/issues/455

I will add a check here to try to keep JEI from crashing from the issue.
