### ISSUE TITLE
(1.10.2) [Bug] Blood Magic Blood Altar Recipes not showing the required item.

### ISSUE THREAD

**Issue by jawsawn** [mezz/JustEnoughItems#467]
Blood Magic 2.1.0.63
JEI 1.10.2-3.12.0.282

Not sure if on jei or bm's end.

**Comment by TehNut** [comment]
This is on our (BM) side. It will be fixed in the next release. Please close this.

**Comment by jawsawn** [comment]
When can we expect the next release?

**Comment by mezz** [comment]
Commenting here to link this issue to the Blood Magic fix: https://github.com/WayofTime/BloodMagic/pull/933

I'm not sure when the Blood Magic release is, sorry. For now you can downgrade JEI to version 3.10 and it should run fine with Blood Magic.
