### ISSUE TITLE
JEI failed to start

### ISSUE THREAD

**Issue by YOYOK9** [mezz/JustEnoughItems#469]
So trying to join a hub server (Forge vanilla) before connecting to a modded server but when I log into it I get this error. 

mc: 1.10.2
Forge: 2092
Jei: 1.10.2-3.12.0.283

https://gist.github.com/YOYOK9/d485c6392911754662679e3057e81f8f

**Comment by mezz** [comment]
Thanks for the report!
This looks like a crash from IC2. Please try updating IC2 and see if that fixes the problem.

**Comment by YOYOK9** [comment]
Ok I have updated Ic2 to its newest version as well as jei and I am still receiving the same error

ic2: 2-2.6.69-ex110
jei: 1.10.2-3.12.0.285

**Comment by jonabrv1965** [comment]
Hello everyone, I do not know if its related, but with the newest version of JEI (jei_1.10.2-3.12.0.285.jar) my Mincraft does not even start, I got an java error (white screen), and windows close the task... Reverting to version 261, it loads ok. The problem is that the latest enderIO version requires a superior version than 261... (is feasible to get past versions somewhere)?

**Comment by mezz** [comment]
@jonabrv1965 please open a new issue and include your `fml-client-latest.log` from the minecraft logs folder (put it on https://gist.github.com/).

**Comment by jonabrv1965** [comment]
Hi Mezz What a speed! nice! I have to recreate the error, give me a couple of minutes...

**Comment by mezz** [comment]
@YOYOK9 please report the bug to IC2 here: http://bt.industrial-craft.net/

**Comment by jonabrv1965** [comment]
[fml-client-latest.zip](https://github.com/mezz/JustEnoughItems/files/501366/fml-client-latest.zip)
Hi Again Mezz, here the log... I'm trying with the .280 version (I found the old files in the "files" section of the Curse page :-), I'll let you now ASAP

**Comment by jonabrv1965** [comment]
Ah... this is the error :
![capture](https://cloud.githubusercontent.com/assets/13445986/18966011/36bad0ee-8645-11e6-8ef7-c394d0631555.JPG)

**Comment by mezz** [comment]
Sorry @jonabrv1965 this has nothing to with this issue or with JEI at all, you'll have to find another place for help. I don't know the cause of your issue.

**Comment by jonabrv1965** [comment]
Nope, with 280 same situation, I guess is a combination between the latest enderIO (EnderIO-1.10.2-3.0.1.116_beta) and the latest JEI versions, trying with jei .275, neither, same error...

**Comment by jonabrv1965** [comment]
Yes, it seems a problem with enderIO... I´ll report them then. THX!!!!

**Comment by mezz** [comment]
http://bt.industrial-craft.net/view.php?id=2005
