### ISSUE TITLE
Crash on accessing inventory - Rendering screen (NEI)

### ISSUE THREAD

**Issue by NutBurger** [mezz/JustEnoughItems#471]
Crash on accessing inventory with jei_1.10.2-3.12.0.285 in single player world

http://pastebin.com/PDvzu4KX

**Comment by TehNut** [comment]
Caused by NEI.

**Comment by NutBurger** [comment]
removing nei solved the issue, thank you.

**Comment by mezz** [comment]
Thanks for the report!
This has been reported to NEI here: https://github.com/TheCBProject/NotEnoughItems/issues/24
