### ISSUE TITLE
Enchanting is missing

### ISSUE THREAD

**Issue by aolko** [mezz/JustEnoughItems#474]
Please add it in, should be called on `X` or, in case of fei, `ctrl+X`

**Comment by mezz** [comment]
[Please see the NEI Features in 1.9+ chart here.](https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0)
NEI for 1.10 has that feature, FEI has it, JEI will not be adding features like that.
