### ISSUE TITLE
JEI 3.12.1.287 don't update when typing in search bar

### ISSUE THREAD

**Issue by Bodidl** [mezz/JustEnoughItems#475]
In version 3.12.1.287, when playing on a server, JEI GUI will not update when I type in search bar (GUI acts like a still image, even the marker blinking when you select the search bar is MIA). Need to exit and re-enter GUI for it to update. 
(Works fine in single player.)<-- sdaddy says no
Works fine in version 3.12.1.286. 
Works fine when searching from a ME-like system that synchronizes it's search bar with JEI (tested with @Correlated Potentialistics).

I'm using forge 12.18.1.2094

**Comment by MisterShawn** [comment]
I was having the same problem in single player. I downgraded to *.286 until there's a fix.

**Comment by Bodidl** [comment]
Huhh... Now I'm confused. I thought it was a server thing. Could be some other mod in my world then messing it up?

**Comment by mezz** [comment]
Confirmed, it's acting strangely.
