### ISSUE TITLE
Items Unable to be Removed from Chests, shows recipes instead. (Server only)

### ISSUE THREAD

**Issue by DMIL421** [mezz/JustEnoughItems#476]
After updating JEI this morning, I'm getting some odd occurances. I'm using the current files for all mods from Curseforge available at the time of this posting. Crashlog for reference:
https://gist.github.com/DMIL421/2852588cefc5df7b522c89c4ea0069dd

Issues Occurring:
- Crafting Grid Fill No Longer Working (regular crafting table and TiCon Crafting Station)
- IronChest Chests (Iron and larger, doesn't matter which type) has areas where if you click on an item in the slot (or shift click) it instead brings up a crafting recipe. Iron Chest is the top row, middle slot, Gold Chest is second row, middle slot. Diamond Chest is 5 slots in the middle of the second row.
- Same is true for a vanilla double chest. Top slot, middle row. Ender Chests (vanilla and from EnderStorage) are fine.

This was discovered playing on a server. Tried to duplicate in SSP and could not duplicate.

Let me know if there is anything else I can provide to assist.

**Comment by DMIL421** [comment]
Didn't say this before... that was using JEI version 287. Reverted to JEI 286 and it is working fine.

**Comment by bdew** [comment]
JEI seems to intercept clicks in all GUIs, any clicks in the upper part of the screen end up showing recipes.

**Comment by LightningLdr180** [comment]
Just wanted to agree, the latest JEI version incorrectly shows recipes for things when trying to remove items from inventory GUIs.

**Comment by mezz** [comment]
Thanks for the report!
287 introduced a bug where clients connected to a server would end up with a broken/invisible JEI over everything, messing with inputs horribly. This was fixed in 288, but I'll test with Iron Chests to make sure.

The recipe transfer bug also came from 287 but is different, and will be fixed in a second.

**Comment by mezz** [comment]
Confirmed that JEI still intercepts that area at the top of tall GUIs, but only after you've had the recipe gui open. This area is where the crafting table and other stuff goes on the recipe gui. I'll look into fixing that as well.

**Comment by mezz** [comment]
All these issues are fixed in JEI 3.12.2
