### ISSUE TITLE
3.12.1.287 Crash Report

### ISSUE THREAD

**Issue by rannday** [mezz/JustEnoughItems#477]
https://gist.github.com/rannday/882934fe6a70e0e586b8cca5b9bea373

Latest version crashes when trying to shift click recipes into EZ Storage 2 crafting frame.

Downgrading to previous version removes this issue.

**Comment by mezz** [comment]
Thanks for the report!
This is an EZ Storage issue. [Please report to EZ Storage, here.](https://github.com/zerofall/EZStorage/issues?q=is%3Aopen+is%3Aissue)

**Comment by mezz** [comment]
Reported here: https://github.com/zerofall/EZStorage/issues/40
