### ISSUE TITLE
Unintended behavior

### ISSUE THREAD

**Issue by Zhaulus** [mezz/JustEnoughItems#479]
recently noticed a bug where cheat mode was turning on randomly despite in game button stating cheat mode is disabled. to trouble shoot I turned cheat mode on went back to the game, then I turned it off again and it would then register the proper state. It was getting after dark here so I pressed the mute button on my keyboard, this toggled the error state. the mute key to my knowledge is not meant to be bound in Minecraft. I am playing a custom version of 1.10.2 unstable with jei_1.10.2-3.12.1.287 and  JustEnoughResources-1.10.2-0.5.3.60. and Forge 12.18.1.2094

**Comment by Zhaulus** [comment]
Just double checked my key binds, "Toggle Item Cheating Mode" is set to "None"

**Comment by mezz** [comment]
Thanks for the report!
That's bizarre, I think your mute button is creating a key event for the "None" key.
Try setting some other game hotkey to None (hit escape for the keybind) and see if you can trigger it with your mute button.

**Comment by Zhaulus** [comment]
Hmm... my mute button is right next to my escape Key I wonder if it is a short? Yes I can, I triggered the Waila config screen by pressing mute also volume down.

**Comment by mezz** [comment]
Hmm I think you may just have a very strange keyboard.
I will try to protect against this issue anyway... shouldn't be too difficult.

**Comment by mezz** [comment]
Looks like this is actually an issue with key handling in Forge. I'll fix it there.

**Comment by mezz** [comment]
This will be fixed by the Forge PR above.
