### ISSUE TITLE
Clicks are not blocked from underlying GUI

### ISSUE THREAD

**Issue by fnuecke** [mezz/JustEnoughItems#48]
After opening JEI, when clicking somewhere, that click apparently still gets processed by the previous GUI (where `R` was pressed to open JEI). Easily reproducible in the Creative Tabs:

http://gfycat.com/BestShinyGangesdolphin

In that clip the inputs are: `R` to open JEI, mouse wiggling, left clicking, pressing `ESC`.

**Comment by mezz** [comment]
Thanks for the report! 
Regression from earlier, I thought I was being clever...
Fixed in the latest
