### ISSUE TITLE
Forestry Squeezer recipes not showing

### ISSUE THREAD

**Issue by JunpakuRaven** [mezz/JustEnoughItems#480]
The recipes for other Forestry machines (like the Carpenter) are showing but Squeezer ones aren't anymore. Hovering over the arrow in the machine itself still shows the "show recipe" text but clicking doesn't work either.
I'm on the latest version on Curse at this time: jei_1.10.2-3.12.2.290
I am not using FEI

**Comment by mezz** [comment]
Thanks for the report!
This is most likely a Forestry issue, not sure why you sent it here instead of there.
I happen to be the Forestry dev too though, so _shrug_.

**Comment by mezz** [comment]
Fixed in Forestry 5.2.13, should be uploaded a bit later.
