### ISSUE TITLE
An item that requires for crafting experience don't show recipe

### ISSUE THREAD

**Issue by CubeTwo** [mezz/JustEnoughItems#482]
Items like "Golden Lasso" or "Magical Wood" from Extrautils2 which requires for crafting experience don't show recipe.
jei_1.10.2-3.12.2.291
JustEnoughResources-1.10.2-0.5.3.60
extrautils2-1.10.2-alpha-1.0.1
forge-12.18.1.2094
If i use jei_1.10.2-3.10.0.261 it works fine and show recipe.

**Comment by TehNut** [comment]
This would be an Extra Utils issue.

**Comment by mezz** [comment]
Thanks for the report!
Please report to Extra Utilities here: https://github.com/rwtema/extrautilities/issues

**Comment by ghost** [comment]
Linking the issue for others who may be wanting to report this 

https://github.com/rwtema/extrautilities/issues/1002
