### ISSUE TITLE
crash when alt tabing from game

### ISSUE THREAD

**Issue by Tsukiumy** [mezz/JustEnoughItems#483]
jei_1.10.2-3.12.2.291.jar
forge-1.10.2-12.18.1.2094.jar

here is the crashlog http://pastebin.com/UdNHNbfx
 i was playing normally for a good time, then i just switched the window to change a music, and when i got back the game insta crashed.
Then i done the test 2 more times to see if it was just a java bug, just doing somenthing, tabbing, getting back, after 2 or 3 changes the game crashes.

**Comment by TehNut** [comment]
Caused by JustEnoughTooltips.

**Comment by way2muchnoise** [comment]
Caused by Just Enough Tooltips (JET) `me.superckl.jet`

**Comment by Tsukiumy** [comment]
ty for the fast response, must missclicked the addition of that one mod, curse problems...

**Comment by mezz** [comment]
Bug was reported to JET here: https://github.com/superckl/JustEnoughTooltips/issues/3
