### ISSUE TITLE
crash when using recipe transfer from JEI to refined storage's crafting grid

### ISSUE THREAD

**Issue by Recaran** [mezz/JustEnoughItems#484]
[https://dl.dropboxusercontent.com/u/34643306/crashlog.txt](url) // Crashlog

When shift clicking the "+" in JEI to insert a recipe into refined storage's crafting grid, game closes with the above report. 

Had a read through the error report and couldnt find a mention of Refined Storage causing the crash, so i thought i'd head over here for help.

**Comment by way2muchnoise** [comment]
Try updating both JEI and RS to the latest version first.

**Comment by Recaran** [comment]
RS was at the latest version, updating JEI worked a treat though, thank you. Thought i had the latest version of both.
