### ISSUE TITLE
1.10.2 - Crash on load

### ISSUE THREAD

**Issue by ariosos** [mezz/JustEnoughItems#486]
http://pastebin.com/P0AZ9su1

![1 10 2_modlist_oct1](https://cloud.githubusercontent.com/assets/7917753/19021320/b845d78c-888c-11e6-9c71-95290d6a58d2.jpg)
Forge version 2094 - crashes after the Loading mods step.
Mod list is attached.

**Comment by ariosos** [comment]
EDIT: Seems it was More Overlays that was causing it - found the update for More Overlays and it's working. (Wished there was a way to delete an issue)

**Comment by way2muchnoise** [comment]
You'll have to live with the same of creating the issue now :D

**Comment by mezz** [comment]
Duplicate of https://github.com/mezz/JustEnoughItems/issues/456
