### ISSUE TITLE
Random crash when in a gui

### ISSUE THREAD

**Issue by modmuss50** [mezz/JustEnoughItems#487]
https://gist.github.com/modmuss50/4a0071fc3efd8a52e78899baa48f7fa5

I haven't got a way to reproduce this well as it seems to be random., but is been happening to me when using a Refined Storage grid.  I can provide more information if needed.

**Comment by modmuss50** [comment]
raoulvdberge said it was fixed on irc

**Comment by way2muchnoise** [comment]
See raoulvdberge/refinedstorage#394
