### ISSUE TITLE
1.10.2 crash when attempting to look at recipe for a unbreaking III enchanting book (Ender IO Recipe)

### ISSUE THREAD

**Issue by LordHellscream** [mezz/JustEnoughItems#489]
crash log:

http://pastebin.com/YMj6viPr

**Comment by TehNut** [comment]
Caused by EnderIO

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in the latest version of EnderIO.
https://minecraft.curseforge.com/projects/ender-io/files
