### ISSUE TITLE
Impossible to load Server World

### ISSUE THREAD

**Issue by HendrikJ79** [mezz/JustEnoughItems#49]
With the latest release (JEI_1.8-1.2.0.28 & JEI_1.8.8-2.2.0.15) is it impossible to login and load Spigot/Bukkit Servers, not tested on Vanilla Servers.

This is the Error what appears in MC launcher:

https://gist.github.com/mezz/858fb70202f538ab3ad1

**Comment by mezz** [comment]
Thanks for the report!

One of two things is happening:
1. I'm getting a `guiOpened` event before `FMLModIdMappingEvent`
2. The `guiOpened` event is null

Not sure why that would be but I can try to defend against it crashing at least. 
If `FMLModIdMappingEvent` is never called at any time, JEI will not load.

I'll push an update in the next few minutes to guard against the null pointer exception.

**Comment by HendrikJ79** [comment]
Forgot to mention it before, when clicking on a item in JEI it crashes the client, dont have any reports at this moment, I'll try to generate one with an previous version of JEI

**Comment by mezz** [comment]
Ok. When you do, please submit as a new issue so I can keep track

**Comment by HendrikJ79** [comment]
I will do it

**Comment by mezz** [comment]
New versions are up here, can you try them out with Spigot/Bukkit and see what happens?
http://minecraft.curseforge.com/projects/just-enough-items-jei/files

**Comment by HendrikJ79** [comment]
Both versions, for 1.8 & 1.8.8 are loading the worlds correctly in the client and no error reporting, but on both version they dont give the JEI when pressing E, probaly the other isseu

**Comment by mezz** [comment]
The gui hook I use to handle mouse and keyboard input is new to Forge in 1.8, maybe bukkit doesn't have it.

**Comment by HendrikJ79** [comment]
That's not the biggest problem I think, the world is loading with JEI enabled
