### ISSUE TITLE
Crashing when viewing recipes

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [mezz/JustEnoughItems#491]
https://gist.github.com/anonymous/ae16a5b2c5d287846dd6cbb564a149b8

**Comment by way2muchnoise** [comment]
Seems to be an EIO issue `at crazypants.enderio.integration.jei.TankRecipeCategory.setRecipe(TankRecipeCategory.java:181)`

You should go and report that on their repo

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/488
This is an EnderIO crash, reported here: SleepyTrousers/EnderIO#3741
