### ISSUE TITLE
[3.12.4.294]Pages overlapping

### ISSUE THREAD

**Issue by The-Fireplace** [mezz/JustEnoughItems#494]
![image](https://cloud.githubusercontent.com/assets/5914284/19057645/08242424-8997-11e6-8cc2-bccf7fe4aaf4.png)

To reproduce: 
1. Open inventory gui
2. Switch to another JEI page

**Comment by mezz** [comment]
Thanks for the report!
I'm not able to reproduce with those steps, is there anything else? This bug was supposed to be fixed a couple versions ago, are you certain you're on 3.12.4?

**Comment by The-Fireplace** [comment]
Certain. I do have a few other mods installed, but none that interfere with the inventory gui, that I know of. Here, have a look at my mod list, if you want:
http://www.modlister.com/user/The_Fireplace

It seems to be caused from any update to the JEI screen, not just changing pages, because searching doesn't render what you are typing as it is types, and the results seem to be a layer underneath the initial layer. Closing the inventory and re-opening causes the screen to look correct again, until you mess with it again.

It looks to me like the JEI part of the gui is loading twice, and the bottom one is the one that gets updated when you mess with it.

**Comment by mezz** [comment]
Can you link me to your client log? I have another issue open where JEI is starting up twice, once on the Server thread somehow (JEI starts on a Client Proxy, the server thread shouldn't be able to call it). I don't know the cause yet.

**Comment by The-Fireplace** [comment]
Hang on a moment. I can't seem to reproduce it anymore. One minute, I need to revert the one change I made to the environment and see if that causes it to happen again.

**Comment by The-Fireplace** [comment]
No, that wasn't it. I can't reproduce it anymore. The issue only occurred the first time I loaded the game after updating.

**Comment by mezz** [comment]
Ok. I'm guessing that somehow the upgrade was not applied at first, since this issue affects an older version of JEI. Thanks!
