### ISSUE TITLE
Cash Index out of bounds. Looking at Recipes from ender io

### ISSUE THREAD

**Issue by robertm1771** [mezz/JustEnoughItems#497]
JEI 1.102-3-12-3.293

While am unsure the exact problem am sure you don't want to catch index problems and not crash.

Thanks
https://gist.github.com/robertm1771/04bda585cd807dc81e376c03982885a6.js

**Comment by TehNut** [comment]
#488

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate issue.
I am going to protect against this crash in JEI in the next version.
