### ISSUE TITLE
Problem joining world

### ISSUE THREAD

**Issue by itsSilverlink** [mezz/JustEnoughItems#498]
Hey,

I can't join a server world with semi latest version of JEI.
If i revert to 261 i have no issues.

Console gives me this error disconnects me from the server:
io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught

Latest FML JEI part:
https://gist.github.com/XSilverlink/cc793a8755bb8ddcb69d5b3cc9efa454

Forge: 2095
JEI: 292

If you need anything else i'm glad to help :)

**Comment by mezz** [comment]
Thanks for the report!
Looks like some plugin is taking a very long time on the runtime stage, but JEI does not have timing information in the log to see which plugin is causing the issue.
I'll add that information to the log in a new JEI version now, then you can try that version and we'll be able to see what's taking too long.

**Comment by mezz** [comment]
Ok, please try out JEI 3.12.5.298+ and link the new log here.
https://minecraft.curseforge.com/projects/just-enough-items-jei/files

**Comment by itsSilverlink** [comment]
Thank you for the support. Awesome that you are working on this so quickly!

but alas the problem isn't solved for me yet.
using now the build 300 of JEI.

On the server:

```
> Exception in thread "Server Watchdog" Oct 05, 2016 8:08:41 AM io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught
WARNING: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.timeout.ReadTimeoutException
```

This is what i get in the log files of my client:
https://gist.github.com/XSilverlink/1768103779318bb6e3badf9b75870390

**Comment by mezz** [comment]
Ok the new log shows the problem:

```
[08:08:35] [Client thread/INFO] [JEI/]: Sending runtime to plugin: wanion.jeihider.JEIHider ...
[08:09:03] [Client thread/INFO] [JEI/]: Sent    runtime to plugin: wanion.jeihider.JEIHider in 28257 ms
```

That's taking waaay too long and making you time out when connecting. I'll work on fixing it up later, for now you should just remove that mod.

**Comment by itsSilverlink** [comment]
Going to test it right now.
Didn't even know that i even added that mod (shame on me)

Issue wasn't there when starting a local game fyi.

**Comment by itsSilverlink** [comment]
Yes removed the mod and it works! Thank you for the support. JEI Hider isn't coming back for me ;)

**Comment by mezz** [comment]
Cool, glad it works now.
I'm going to mark this issue as related to this one: https://github.com/mezz/JustEnoughItems/issues/353
JEI should try to load things in a way that doesn't cause you to time out, even if the addons are slow.
