### ISSUE TITLE
Client crash on Spigot/Bukkit servers when clicking on items

### ISSUE THREAD

**Issue by HendrikJ79** [mezz/JustEnoughItems#50]
When you click on an item while playing on a Spigot/Bukkit server it instantly kills the client.
The server seems not be affected.

Crash Report client:
https://gist.github.com/HendrikJ79/e8b372cc337af8bd955c

**Comment by mezz** [comment]
For now, you can disable "cheat mode" in the config and it should not crash. I'll fix this soon.

**Comment by HendrikJ79** [comment]
Thnx will fix it on that way fr this moment, the server is reporting it with:
[Disconnect] User has disconnected, reason: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
