### ISSUE TITLE
Turn off item/bloack names

### ISSUE THREAD

**Issue by hibbing** [mezz/JustEnoughItems#504]
Is there a way to turn off the display of item names underneath each block or item.
For me it always says:
**Wooden Sword
"wooden:sword"**
for example. Can't see a simple way in the config.
(apologies if this is a duplicate)

**Comment by KnightMiner** [comment]
That is a vanilla feature. Press F3 + H to hide it

**Comment by hibbing** [comment]
Thanks.
Well that's embarrassing though. Just updated to 1.10.2 and installed this. Didn't realise it was a vanilla thing. My bad.
