### ISSUE TITLE
Crash on load - JEI in eclipse

### ISSUE THREAD

**Issue by Astavie** [mezz/JustEnoughItems#505]
Hello!
I'm working on my own mod and I got a bug report saying that my item crashes JEI. No biggie, I just have to place JEI in my workspace and look... [Crash](https://gist.github.com/TheRActivator/5f8b8c70e48a158d9a58240e8ebcf74c)!
I have no idea why JEI is crashing all of a sudden. I heard that since 1.8.9 you can just put obfuscated jars into the mods folder and Forge automatically deobfuscates them.

**Comment by Astavie** [comment]
Oh, it seems I set it up wrong. Looks like I had to go into build.gradle and add it as a dependency. Well, I'm not crashing anymore!

**Comment by mezz** [comment]
Glad it worked out!
