### ISSUE TITLE
Game Crashes when switching item list page or when using the Search Bar

### ISSUE THREAD

**Issue by skyecodes** [mezz/JustEnoughItems#507]
When I'm doing that, the game freezes for 3 seconds then crashes.
Crash Report here : https://gist.github.com/Franckyi/23ee58112c914d49609c4604cae2dd85

It works well when I dont use mods or when I use 2-3 mods. I don't know which mod may cause that.

**Comment by VT-14** [comment]
Does this happen without Optifine?

**Comment by skyecodes** [comment]
@VT-14 No, removing Optifine fixed the crash. EnderIO is incompatible with Optifine, right ?

**Comment by VT-14** [comment]
Most mods don't support it due to it changing how Vanilla Minecraft renders objects.

Ender IO isn't really incompatible; it's more of "if it breaks something, we won't go out of our way to fix it."  I don't think they have been having issues with it recently.

**Comment by skyecodes** [comment]
Ok, thanks a lot anyway :+1:

**Comment by AEnterprise** [comment]
the main problem is that optifine isn't open source so we can't just go look at a github to see what changed and why things break. it can be decompiled but that's a major hassle and not exactly reliable

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/372

Please check out the Optifine issue and help the author so they can fix it: https://github.com/sp614x/optifine/issues/260
