### ISSUE TITLE
Separate ingredient use from craft-at use.

### ISSUE THREAD

**Issue by The-Arcanian** [mezz/JustEnoughItems#509]
First off let me say that I love the ability to see everything that you can create in a block, it is something that I always wished I could do in NEI. But I have encountered a problem. A lot of mods use the Crafting Table as an ingredient for at least one thing but if you use the U key on a Crafting Table it shows both what the Crafting Table can be use for as an ingredient, and anything that can be crafted **at** a Crafting Table. While I think this is only something affecting the Crafting Table right now. Could it not cause the same effect for other blocks if they just so happen to use another of themselves to make something?

Might it be a good idea to separate the two into different tabs?

**Comment by mezz** [comment]
Thanks for the suggestion!
My solution to this has been to show the recipes that use a crafting table in their recipe first, and then all the stuff that can be made on a crafting table after. I think this is good enough, since it's not a very common thing.

**Comment by The-Arcanian** [comment]
I saw that, and thought that might be the case. But it did not seam to be working properly in some cases. Now I see that it is just showing them twice, once for the Crafting Table being an ingredient, and a second time for being crafted at the Crafting Table. Which lead to my confusion.

**Comment by mezz** [comment]
They should only show once, can you show me a screenshot?

**Comment by The-Arcanian** [comment]
Here is an example using the first three recipes when I check Uses on the Crafting Table. Sorry, I am not on github too often, I just saw this.
![2016-12-05_20 40 32](https://cloud.githubusercontent.com/assets/7005184/20913366/2352dc4c-bb2c-11e6-957f-3303f0976e3f.png)
![2016-12-05_20 42 52](https://cloud.githubusercontent.com/assets/7005184/20913365/2350c2e0-bb2c-11e6-9b12-e18aa21a70e8.png)
![2016-12-05_20 43 08](https://cloud.githubusercontent.com/assets/7005184/20913367/2353fa78-bb2c-11e6-8b85-0141ac462b25.png)
![2016-12-05_20 47 38](https://cloud.githubusercontent.com/assets/7005184/20913364/23339166-bb2c-11e6-8ab4-8e7bfe922718.png)

**Comment by mezz** [comment]
Thanks, reopening this.

**Comment by mezz** [comment]
@The-Arcanian alright I scrolled through all those thousands of recipes with Botania and wasn't able to see any duplicate uses of the crafting table. I dunno if that was a cruel joke or what :P, but... make sure you have the latest JEI and please let me know if you have some other steps to reproduce this issue.

**Comment by The-Arcanian** [comment]
Sorry, just saw this (agian). Updated to the latest Botania and JEI to check for you and everything looks good now. 👍 

As a curious Computer Science student mind if I ask what you did? I am not super familiar with MC code or how JEI works, but I will get a gist.

**Comment by mezz** [comment]
I think recipe comparisons were not being done correctly, so JEI was unable to determine when two recipes were identical. 
I changed things so that there is only one instance of each recipe so that they can be compared just by checking that the instance is the same.
