### ISSUE TITLE
Make compass and clocks useless in item list and recipes

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#51]
Viewing the items instead of crafting them is a bit cheaty.

**Comment by 4rz0** [comment]
Ha!
I was always wondering about that in NEI ;D

**Comment by mezz** [comment]
Talked to fry and this should be possible in 1.9.

**Comment by Prospector** [comment]
Couldn't you simply replace the icon in JEI with a static compass icon?

**Comment by mezz** [comment]
The issue is that there is no static compass icon, I think I would have to create it.
It would be a solution for the compass and clock, but I really want a more general solution.
Maybe I can just hack something together for these two for now.

**Comment by Prospector** [comment]
Could you use the first frame of the compass/clock png?

**Comment by mezz** [comment]
From what I could see, there's some hard-coded magic with those textures when they're loaded. Mojang doesn't handle it very cleanly. I have to try it out though.

**Comment by Prospector** [comment]
I don't really think that would make a difference. There is a .png image for the two items, and just get the width of that image (by default 16x16), then get the top 16x16 (or whatever other width) used as the icon. Though this is an oversimplification, the theory would work I think.

**Comment by Darkhax** [comment]
Wouldn't it be possible to try and trick the item, similarly to how the clock goes crazy when you are in the nether?

**Comment by mezz** [comment]
This is working in 1.9
