### ISSUE TITLE
[3.12.6.304] Error when using /mt reload in a multiplayer environment

### ISSUE THREAD

**Issue by Shadows-of-Fire** [mezz/JustEnoughItems#511]
https://gist.github.com/Shadows-of-Fire/970c8c81c9688762f12f2e1ea28a8790

This error appears in client logs during the reload.  It also causes the cursor to appear on the screen as if the window was de-focused, but the cursor still controls the crosshair of minecraft, though it will fully de-focus if taken off-screen.

**Comment by mezz** [comment]
Thanks for the report!
This is caused by an ItemStack with a null item in it. Check your MineTweaker scripts, there may be an error.

**Comment by Shadows-of-Fire** [comment]
None of the scripts error in minetweaker.log, I'll check and see if I can find which script is causing it.

**Comment by mezz** [comment]
Any update @Shadows-of-Fire ?

**Comment by Shadows-of-Fire** [comment]
It just kinda stopped happening... Not sure why it was ever doing it in the first place.
