### ISSUE TITLE
ItemToolTipEvent Error

### ISSUE THREAD

**Issue by HendrikJ79** [mezz/JustEnoughItems#52]
When pointing on an item in the inventory creates many Exception caught during firing event errors.
Even no tooltip when JEI installed and enabled.

https://gist.github.com/HendrikJ79/7511e4ac89c8dd60d9f2

**Comment by mezz** [comment]
Thanks for the report!
I think this is another bukkit/spigot issue.
I'll have a fix soon. In the meantime you can disable the tooltip in the config file.
