### ISSUE TITLE
Hide Feature

### ISSUE THREAD

**Issue by WanionCane** [mezz/JustEnoughItems#521]
Hello.

I am WanionCane, author of JEI Hider and UniDict.

The issue is the following, a while ago, [an user posted a comment on JEI Hider CurseForge page](https://minecraft.curseforge.com/projects/jei-hider?comment=16), warning me that it isn't working anymore, as soon I saw it, I checked my other mod (UniDict) that also hides some things, and seems that the hiding functionality of JEI is somehow broken.

or I am doing something wrong?
[my plugin class](https://github.com/WanionCane/UniDict/blob/1.10.2/src/main/java/wanion/unidict/UniJEIPlugin.java).

thanks.

**Comment by TehNut** [comment]
Blacklisting should be done in `register()`

**Comment by WanionCane** [comment]
seems to be working now, thank you =p
