### ISSUE TITLE
[1.10.2] Errors and no GUIs

### ISSUE THREAD

**Issue by Eufranio** [mezz/JustEnoughItems#529]
I've recently updated JEI to 3.12.8.325, and the GUIs disappeared, including the inventory/item bar.

Errors:

http://hastebin.com/upezemayeg.md

Minecraft 1.10.2
Forge 12.18.2.2107
Mod list: http://www.technicpack.net/modpack/magitech-server-beta-pack.883332/mods

**Comment by mezz** [comment]
Thanks for the report!
This crash is from another mod, try updating your AppleCore.

**Comment by mezz** [comment]
@Eufranio can you confirm the fix?

**Comment by Eufranio** [comment]
Confirmed, It's fixed with latest AppleCore.
