### ISSUE TITLE
Recipe Gui Title goes black when Thaumcraft Arcane Bore item is shown

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#53]
![2015-12-07_02 02 09](https://cloud.githubusercontent.com/assets/916092/11624156/9dd10d1a-9c86-11e5-8066-f5633cf27ad9.png)

@tterrag1098 do you have any idea why it's doing this? I'm a bit stumped.

**Comment by mezz** [comment]
Looks like it messes up rendering for things with effect as well. May need to do some more OpenGL defense around item rendering, or find out what it's doing and report to Thaumcraft if it causes issues without JEI.

**Comment by tterrag1098** [comment]
Looks like someone shut off GL_BLEND, because I'm rendering a black square with 0.25 opacity.
