### ISSUE TITLE
[1.10.2] No Recipies for Mekanism

### ISSUE THREAD

**Issue by YOYOK9** [mezz/JustEnoughItems#530]
I've noticed that the last few updates to jei, Mekanism mod recipes have stopped showing. I am running the latest version of Mekanism. 

Edit: On both multiplayer server and single player.

MC: 1.10.2
JEI: jei_1.10.2-3.12.8.325
Mekanism: 1.10.2-9.2.0.292
Forge: 1.10.2-12.18.2.2105

**Comment by mezz** [comment]
Thanks for the report!
Please paste your client log to https://gist.github.com/ and link it here, there should be some information I can use to find out what's wrong.

**Comment by YOYOK9** [comment]
Client log.
https://gist.github.com/YOYOK9/e13480447d58c5505ae785f5397a2c81

**Comment by mezz** [comment]
It looks like you have tens of thousands of errors, where ItemStacks have a null item in them. I have no idea what is causing that, but I can defend against it somewhat.
Please try with JEI 3.12.8.326 and let me know if it fixes your issue.
