### ISSUE TITLE
Search bar is invisible 

### ISSUE THREAD

**Issue by xxsuperdreamxx** [mezz/JustEnoughItems#533]
Thank you for reporting!
- If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
- Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R).
- Try the latest version, it may have fixed the issue already.
- If you have FEI installed, please try without it before reporting.

**Comment by mezz** [comment]
Please include more information about your issue. Description of the problem, screenshots, mod list, steps to reproduce, any of those will be useful.

**Comment by xxsuperdreamxx** [comment]
How I can describe it I was creating modpack and I don't know why search bar is invisible when I click on E  it is invisible but I know where is located search bar and when I write something it works texture error in every build of NEI it is doing that and mods are for stoarge farming and machines

**Comment by mezz** [comment]
Try removing mods like NEI to see if they are causing a conflict. If you try with only JEI an no other mods it works fine, so it must be a conflict.

**Comment by vandench** [comment]
In the NEI Config look for the `jei` block and set `searchBoxOwner` to `1`, if the config file does not have blocks you may find it as `jei.searchBoxOwner`, you can also change it in-game by opening your inventory, clicking on the `Options` box in the bottom left corner, then click on `nei.options.jei`, then click on `nei.options.jei.searchBoxOwner.X` where `X` should have originally been `0` and is now `1`, if there are more than 2 options for the `searchBoxOwner` you may have cycle through the list until one of them works.

**Comment by mezz** [comment]
@xxsuperdreamxx can you confirm the fix?
