### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by DatrixTHLK** [mezz/JustEnoughItems#535]
https://gist.github.com/DatrixTHLK/0a6de29eaefab0bc4cd015175b7f48c8
The only mod I updated was JEI and the newest version caused me to CTD 3.12.8.328. forge 2107

**Comment by evieluvsrainbows** [comment]
@DatrixTHLK delete your config file.

**Comment by DatrixTHLK** [comment]
Are you just trolling me now? I'm not amused if you are...Thanks anyways, though.

**Comment by DatrixTHLK** [comment]
Still crashing...

**Comment by evieluvsrainbows** [comment]
@DatrixTHLK I'm on the exact same version. I'm not getting a crash.

**Comment by evieluvsrainbows** [comment]
@DatrixTHLK One of your other mods is causing JEI to CTD, as I am not getting any crash to desktop errors on my end.

**Comment by DatrixTHLK** [comment]
@KamranMackey Well...apparently, I did not read the entire crash log. It was telling me that FEI is the cause of the issue since JEI updated to a point where FEI needs to update as well. My appologies, I will let FEI's Mod author Mezz (or I meant Elix_x) know about this

**Comment by DatrixTHLK** [comment]
In the mean time, I will use JEI v: 327 since FEI still works with that.

**Comment by mezz** [comment]
Hey I'm the author of JEI, not FEI. Looks like you're on the right track though.

**Comment by DatrixTHLK** [comment]
HAHAHA... XD I must be sicker than I thought. I have a a head cold right now and my brain is having trouble registering atm. Sorry, Mezz.

**Comment by Rumpelstiltskinny** [comment]
@mezz Hey, the JEI 328 Curseforge upload is legit? (unlike the recent mDiyo/TCon malware post)

**Comment by mezz** [comment]
Yes, why?

**Comment by Rumpelstiltskinny** [comment]
Just getting confirmation that it was legit from the owner. Wasn't 100% sure, seems JEI 328 changed enough to trip other mods. Hoping they catch up soon. :D

**Comment by mezz** [comment]
Pretty sure it only broke FEI, since they mess with internal stuff inside JEI. 
Whenever I change stuff there's a decent chance that FEI breaks.

**Comment by DatrixTHLK** [comment]
@Rumpelstiltskinny It would only break FEI. I have experienced that. It is a rarity that JEI would break other mods. Well, unless you got them from a third party site that isn't suppose to host the mods listed here...

**Comment by evieluvsrainbows** [comment]
It must be one of your other mods. I'm not getting a crash.

**Comment by mezz** [comment]
@KamranMackey if you're not sure what the solution is please leave it to me, this issue has already been resolved.
