### ISSUE TITLE
r329 has some issues with minetweaker and recipe changes

### ISSUE THREAD

**Issue by utoc** [mezz/JustEnoughItems#537]
No crash!

Relevant log entries: https://gist.github.com/utoc/7720ce2543acfe057f8f5fac6a22c85d
Full client log: https://gist.github.com/utoc/9095f2eb0ef434dc8881679f29bddd56

Scripts: https://github.com/utoc/bbqscripts

Running JEI r329, FML 2109, CraftTweaker-1.10.2-3.0.13, ModTweaker2-2.0.5

Using the above with newest JEI beta release, no minetweaker tweaked recipes showed up; instead shown were only default mod recipes.  I reverted JEI to r328 and the problem was alleviated.

IE, the following blood altar recipe found here: https://github.com/utoc/BBQScripts/blob/master/bloodmagic.zs loaded correctly as seen from the log above but when clicking the item in JEI, I was given the default BM recipe.  Let me know if screenshots would do a better job of explaining.

Please let me know if I have made the above post in error.  Thank you for all the work you do, mezz.

**Comment by Shadows-of-Fire** [comment]
Can confirm MT recipes aren't shown in JEI 329, with forge 2111, and the same corresponding craftweaker and modtweaker versions.   Recipes do correctly change, attempting to craft by the default recipe still shown causes nothing to output, but JEI refuses to show them.

**Comment by BlayTheNinth** [comment]
Having the same issue here; a call to`jeiHelpers.reload()` (or reloading the resource pack, which according to source should also trigger a reload) doesn't seem to actually call `IModPlugin.register(IModRegistry)` again, so it's only called once at the moment, in mine (and MineTweaker's) case too early.

Additionally it would be nice to have `jeiHelpers.requireReloadOnWorldLoad()` or something and have JEI handle it from there. As it is now we'll have 3+ mods (examples: MineTweaker, Ex Nihilo Adscensio, Ex Compressum) each manually triggering a reload on world load, unnecessarily increasing load time.

**Comment by mezz** [comment]
JEI needs to do its heavy lifting in PostInit, if I do it at world load it's not a good user experience and can cause a server disconnect from taking too long. So far issues have been resolved in JER and Reliquary, and I'll continue to look into these problems as they come up. I've been busy with [TextureDump](https://github.com/mezz/TextureDump) today but should have some time tomorrow to start looking into these.

**Comment by mezz** [comment]
`reload()` for JEI was only ever intended for use by Mod/Mine/CraftTweaker when a player is editing recipes and does `/mt reload`. Using it during normal startup is not intended.

**Comment by mezz** [comment]
@blay09 it looks like ExNihilio Adscensio [loads registries on PostInit](https://github.com/MikeLydeamore/ExNihiloAdscensio/blob/0dc1b592a825160e347358bb65e11db2abfe0704/src/main/java/exnihiloadscensio/ExNihiloAdscensio.java#L72-L81), and JEI loads on PostInit, so you just need to sandwich yourself in between like this:
`@Mod(blahStuff, dependencies = "after:exnihiloadscensio;before:JEI")`
You should probably also bother them to load it earlier, but that's not a big deal.

I will work on the ModTweaker reload issue separately. That should clear up the problems in Ex Compressum.

**Comment by BlayTheNinth** [comment]
Right, I'll try that. It used to load in FMLModIdMappings on the 1.9 branch but it seems they've since fixed that. Didn't realize, sorry.

In case you'll be working with the *Tweaker dev, please ensure JEI is reloaded **after** MineTweaker's Reload event is handled; that's another place where I need to re-generate recipes in case scripts changed the originals from Adscensio/Omnia.

**Comment by mezz** [comment]
Yes, that makes sense. Everyone should have time to react to the minetweaker reload event before JEI is reloaded.

**Comment by AEnterprise** [comment]
as for the loading of blocks/items/...: forge is moving towards a new system where there would be a seperate event for when to load those things to avoid these kinds of issues

**Comment by jawsawn** [comment]
Also recipes doesn't show up from the Crafting Harmonics

**Comment by mezz** [comment]
@JAWSAWN please post a new issue. and link your client log from https://gist.github.com/.

**Comment by utoc** [comment]
This is working now, thank you @mezz!
