### ISSUE TITLE
Storage Drawers recipe & Some of Ender IO Recipe not showing in r331

### ISSUE THREAD

**Issue by luckyu19** [mezz/JustEnoughItems#539]
Hi, I updated JEI to the latest beta, and I can't look at the recipe at all for storage drawers, and ore processing/alloy smelting recipe for Ender IO. I am using the latest version for both mods. I tried rollback to the r324, and they reappeared. I also tried storage drawers with r330 and r329, both had failed to show me the recipe.

**Comment by NoobTaco** [comment]
Same as issue #538

**Comment by mezz** [comment]
Thanks for the report!
This has been resolved in the latest version.
