### ISSUE TITLE
Crash when loading a world with aromacore and latest version of JEI

### ISSUE THREAD

**Issue by grydian** [mezz/JustEnoughItems#540]
The game freezes and does not generate a proper crash report but I was able to copy and paste text from the console that seems to be relevant.

http://pastebin.com/rfx0K1E5

It seems aromacore is doing something with the recipes and all versions after 327 are crashing.  The game loads fine with 327 but none of the versions afterwards.

**Comment by mezz** [comment]
Thanks for the report!
Please report to aromacore here: https://bitbucket.org/Aroma1997/aroma1997core/issues
The recent versions of JEI are loading before the world is created, and aromacore is trying to check the player's name.

**Comment by mezz** [comment]
I let @Aroma1997 know about this on IRC.

**Comment by grydian** [comment]
Oh thanks.  Let me know if I need to make an official bug report on his page.  I really appreciate you looking into this.  I have found it hard to convince aroma to work on a bug if I can't get him to see how its his mods problem.
