### ISSUE TITLE
RE issue with solor flux reborn 

### ISSUE THREAD

**Issue by DaFuJosh** [mezz/JustEnoughItems#542]
Are there any dependencies to this mod? I've added it and I can see the items in JEI, but I can't see the recipes. I can spawn them in and they work fine.

I'm playing Minecraft 1.10.2 with SolarFluxReborn_1.10.2-1.4r.

Sorry if I've missed something obvious. It's my first time trying to create a mod-pack.

Last edited by flehan: 3 days ago
 Report   Reply   Quote   Multi-quote
Nalkrien's avatar
﻿
#28 Nalkrien

View User Profile
Send Message
Follow User
Ignore User
Posted 2 days ago
I had a similar issue when I updated to the latest build of JEI (which was an alpha/beta) and I couldn't look at recipes for them or some other mods, but the recipes still worked. I went back to the release build and the recipes worked again.

 Report   Reply   Quote   Multi-quote
flehan's avatar
﻿
#29 flehan

View User Profile
Send Message
Follow User
Ignore User
Posted 1 day ago
I just tried the same and it seems to work with an earlier version of JEI. Thanks for the info. I wouldn't have thought of that as other recipes worked fine.

 Report   Reply   Quote   Multi-quote
DaFu_Josh's avatar
﻿
#30 DaFu_Josh

View User Profile
Send Message
Posted 3 mins ago
which version of jei ?

**Comment by mezz** [comment]
Thanks for the report!
Try with the latest version released today, it should fix this issue.

**Comment by mezz** [comment]
@DaFuJosh can you confirm the fix?
