### ISSUE TITLE
Enable Showing the Shapeless Icon on Custom Shapeless Recipes

### ISSUE THREAD

**Issue by shartte** [mezz/JustEnoughItems#543]
We have a custom shapeless recipe that does not utilize the Vanilla shapeless recipe class, but behaves like a shapesless recipe to the end user:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/integration/modules/jei/ShapelessRecipeWrapper.java

As far as I am aware, there currently is no way to mark this as a shapeless recipe to get the shapeless icon to show up. The only way I currently see is implementing the tooltip + icon rendering ourselves.

**Comment by mezz** [comment]
You can now call `IRecipeLayout.setShapeless()` in your `IRecipeCategory.setRecipe` and it will add the shapeless icon.
Note that this feature is in 1.11 only.

**Comment by shartte** [comment]
Awesome thanks!
