### ISSUE TITLE
[r334] Crafting Harmonics recipes do not show up

### ISSUE THREAD

**Issue by jawsawn** [mezz/JustEnoughItems#547]
No crash,

On the forge 2107 latest jei 334. Custom recipes doesn't show up, 

Tried;
reloging,
relaunching,
/mt reload , /ch reload

**Comment by mezz** [comment]
Thanks for the report!

"CraftTweaker recipes doesn't show up" 
duplicate of https://github.com/mezz/JustEnoughItems/issues/537

"Crafting Harmonics recipes doesn't show up"
Please paste your client log to https://gist.github.com/ and link it here.

**Comment by jawsawn** [comment]
https://gist.githubusercontent.com/JAWSAWN/0084004a60caeb730d5c7d3914a489b1/raw/8d80f1af8909ff3a95773248856934e1fc021378/gistfile1.txt

fml latest

**Comment by jawsawn** [comment]
Rollbacking to which version should fix it temporarily?

**Comment by mezz** [comment]
You can roll back to the most recent stable release (not beta). 
https://minecraft.curseforge.com/projects/just-enough-items-jei/files

**Comment by mezz** [comment]
I have reported the issue to Crafting Harmonics here https://github.com/legendblade/CraftingHarmonics/issues/166

**Comment by mezz** [comment]
It's worth noting that there has been no development activity on Crafting Harmonics since August 5th.

**Comment by jawsawn** [comment]
Is the bug on the CH's Side? But It was just working. And Ch didn't update but JEI did.

**Comment by mezz** [comment]
I will most likely be able to fix the bug on JEI's side.
The bug report to them is for a "proper" fix that also prevents Crafting Harmonics from reloading JEI and causing people with large packs to disconnect from servers.

**Comment by mezz** [comment]
Try with JEI r335

**Comment by mezz** [comment]
@JAWSAWN can you confirm that the latest JEI fixes this issue?

**Comment by jawsawn** [comment]
Can confirm
