### ISSUE TITLE
JEI may be breaking Minetweaker's mods.jei.JEI.hide

### ISSUE THREAD

**Issue by utoc** [mezz/JustEnoughItems#548]
This issue seems to be a little different than https://github.com/mezz/JustEnoughItems/issues/537 as it seems to have started with r328 or maybe a beta release before.

Originally when the issue first showed up, it seems to have been working fine and was only broken (ie, showed the items that were requested to be hidden) when someone did /mt reload in single player or multiplayer.  Now, with the latest release, r335, it seems to be broken full time.  You can enter both SMP and SSP with `mods.jei.JEI.hide(<minecraft:stone>);` and it will still show it regardless.

We're running JEI r335, Minetweaker 3.0.13 with FML 2114

Thanks for taking a look at it when you have a spare moment and thank you for all the work you do for modded Minecraft :)

**Comment by mezz** [comment]
Yes, I think that will be resolved here: jaredlll08/CraftTweaker#69

**Comment by utoc** [comment]
Noted; I'll subscribe to that thread and close this one.  Thank you for the update mezz :)
