### ISSUE TITLE
Add an easy way to delete items when in item cheating is enabled

### ISSUE THREAD

**Issue by LuigiHutch** [mezz/JustEnoughItems#55]
Please add an easy way to delete items when item cheating is enabled.
Maybe like NEI does it what you drag and click the items back onto the item selection screen.
-LuigiHutch

**Comment by GirafiStudios** [comment]
I agree that this would be a neat feature to have. I just personally never liked the way NEI handled it.

**Comment by mezz** [comment]
I don't know the right way to implement this yet. How should it work?

**Comment by modmuss50** [comment]
Hover over item and click 'x' or something. Have a bin so you can get them back if you click the wrong button. The bin is cleared on disconnect/world close.

**Comment by GirafiStudios** [comment]
Maybe just simply when you click on an itemstack and press delete?

**Comment by mezz** [comment]
I don't want it to be too complex, I think I like the "delete" key idea. 
If you accidentally delete something, you can always cheat it back.

**Comment by mezz** [comment]
Now that there is support for JEI in creative mode, is this still needed?
You can delete items in creative mode in the player inventory tab.

**Comment by GirafiStudios** [comment]
Yeah I would say so. It would be handy in case you use cheat mode, without beeing in creative etc.

**Comment by LuigiHutch** [comment]
Why not do it so when you are in Item Cheating mode, you pick up the item you want to delete with you cursor and mouse it over the JEI 'sidebar' and release the item from your cursor to delete the item. The same way the vanilla creative gui does it but in the JEI sidebar.
