### ISSUE TITLE
Issue (i think): Taking too long to load

### ISSUE THREAD

**Issue by vrork** [mezz/JustEnoughItems#552]
Hello there, my game is taking extremelly long to load with JEI installed, it takes very long on the Adding Item Stacks Ingredients parts. Is that normal?

JEI - 3.13.0.335

**Comment by TehNut** [comment]
#538

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/mezz/JustEnoughItems/issues/538
It seems to be an issue with the Forge loading bars. The current workaround is to disable them in your `config/splash.properties` file.
