### ISSUE TITLE
Client crash when opening inventory.

### ISSUE THREAD

**Issue by seeker2921** [mezz/JustEnoughItems#555]
All,

On a fresh 1.10.2 install with minimal mods installed When pressing "E" to open the inventory the client crashes, server remains up.

Version used is 3.12.8.323

Attached is a crash log.
[crash-2016-10-30_22.17.19-client.txt](https://github.com/mezz/JustEnoughItems/files/562556/crash-2016-10-30_22.17.19-client.txt)

https://gist.github.com/mezz/fbe6ca0e7bc3b912e08f5e28813c3f64

**Comment by mezz** [comment]
Thanks for the report!
The crash log shows that NEI is crashing, please report to NEI instead.
https://github.com/TheCBProject/NotEnoughItems/issues
