### ISSUE TITLE
Texture-packs shift items in forestry centrifuge recipes out of position. 

### ISSUE THREAD

**Issue by MrNinja93** [mezz/JustEnoughItems#556]
Any centrifuge recipe that has items which are not default textures gets shifted to one side/out of position, only happens to the centrifuge from what I've experienced. (even other forestry machines work fine) I assume the issue is because the texture packs have changed the GUI screen of the centrifuge and transferred that to JEI whereas JEI ignores that change and tries to display the recipe in the original GUI.  

Is this something that is JEI's fault or just bad practice from texturepack creators? If the latter I'll raise the issue at Unity and the Sphax forestry addon creator (potentially more that I don't know of)

![2016-10-31_22 08 51](https://cloud.githubusercontent.com/assets/21979276/19873418/d22f1a46-9fb6-11e6-8b3e-df77b89d1240.png)

![2016-10-31_22 23 27](https://cloud.githubusercontent.com/assets/21979276/19873752/b89bd13a-9fb8-11e6-82b1-30f24354b5f9.png)

![2016-10-31_22 10 22](https://cloud.githubusercontent.com/assets/21979276/19873430/dbce5f3a-9fb6-11e6-9282-7e03f023f7ba.png)

![2016-10-31_22 26 03](https://cloud.githubusercontent.com/assets/21979276/19873995/f653db70-9fb9-11e6-98c5-ad2ecc80ce84.png)

**Comment by mezz** [comment]
Try putting stuff into the real centrifuge, I'm pretty sure the texture pack just needs to update their textures. The new Forestry texture should get renamed as well, so that the old texture doesn't get used.

**Comment by MrNinja93** [comment]
It's off on the centrifuge itself too (actually hadn't checked that!) I will open the issue with unity/Sphax addon So they know to change it. 

Edit - Closing
