### ISSUE TITLE
Crash while scrolling through recipes.

### ISSUE THREAD

**Issue by Zarepheth** [mezz/JustEnoughItems#559]
Was scrolling through the recipes that include the result of smelting TSON Craft Magmite ore. About 80% of the way through (some where past the 100th page of 168 or so pages) the game crashed. The active page was showing TSON craft recipes, but the crash report claims a rendering error for Tech Reborn.

I'll be cross-posting this issue on their project as well.

https://gist.github.com/Zarepheth/d6977bc7c2049fd06c9bf94ef0045678

**Comment by mezz** [comment]
Thanks for the report!
Looks like the TechReborn ItemNanosaber is crashing when rendering. 
I see you've already reported to them here: https://github.com/TechReborn/TechReborn/issues/791

**Comment by quantumsheep** [comment]
Same with Botania Floating Flower, seems happend when the model is loaded in JEI:

Crash-report: http://pastebin.com/DsK0YJRW

**Comment by mezz** [comment]
@QuantumSheep please make new issues instead of adding on to old ones.
In this case it's correct to report to Botania, JEI is not the cause.

**Comment by quantumsheep** [comment]
I've deleted Botania, same error happend, I post a new issue.
