### ISSUE TITLE
Crash when scrolling down the item list

### ISSUE THREAD

**Issue by quantumsheep** [mezz/JustEnoughItems#562]
That's happend in page 3 only

Crash-Report: http://pastebin.com/TSiprLcC

**Comment by mezz** [comment]
Thanks for the report!
This is a bug with Applied Energistics, please report here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues

**Comment by quantumsheep** [comment]
How did you know it's from AE2? I didn't find a clue in the crash-report.

Edit: Found!

**Comment by mezz** [comment]
The top of the stack trace is from `appeng` which is short for Applied Energistics 2.
