### ISSUE TITLE
[3.13.1.343] Missing Textures

### ISSUE THREAD

**Issue by gabor7d2** [mezz/JustEnoughItems#564]
I updated to this version today and all JEI textures are missing. I looked in the code and in the textures folder and found out that the 2 textures are called "recipeBackground2.png" and "recipeBackgroundTall2.png" instead of "recipeBackground.png" and "recipeBackgroundTall.png" if I would rename these textures in the jar file (remove the "2" from the end of their name) they work just fine.

JEI: 3.13.1.343
NEI: 2.1.2.162
Forge: 12.18.2.2118

Screenshot:
![2016-11-03_12 23 25](https://cloud.githubusercontent.com/assets/12859334/19964808/2b3c3e7a-a1c4-11e6-8455-d68214fbab78.png)

**Comment by miuirussia** [comment]
Confirm it!

**Comment by mezz** [comment]
Thanks for the report, I forgot to commit the critical part that points to the new textures :)
