### ISSUE TITLE
Newest version of JEI crashes with FEI

### ISSUE THREAD

**Issue by OfficialEsco** [mezz/JustEnoughItems#566]
The Newest version of JEI is crashing FEI (Yes i downgraded to jei_1.10.2-3.13.0.341 and it worked)  

I'll be reporting this to you both

https://gist.github.com/OfficalEsco/3f19b73f49b0286023730f470b808739

**Comment by GirafiStudios** [comment]
The class that FEI can't find in JEI was moved from jei/gui/RecipesGui to jei/gui/recipes/RecipesGui as part of adding recipe category tabs in the last build. FEI would have to add support to the latest version on there side.

**Comment by Elix-x** [comment]
See Elix-x/Forever-Enough-Items#54.
@mezz problem on my side. You can close.
