### ISSUE TITLE
343 Crashes during startup of client.  Server seems to be working.

### ISSUE THREAD

**Issue by TDStewart** [mezz/JustEnoughItems#567]
When launching the client it crashes with JEI 343.  The client 342 launches fine.  Server side 343 does not crash the server.

https://gist.github.com/TDStewart/893974c202a091e53313110d40c0fb2b

**Comment by TehNut** [comment]
Caused by JustEnoughTooltips.

**Comment by TDStewart** [comment]
JEI still crashes after removing JustEnoughTooltips

https://gist.github.com/TDStewart/d052befe1a39645ed9ee68906d072316

But works when both JustEnoughTooltips and FEI 17.1 are removed

**Comment by GirafiStudios** [comment]
Both JET and FEI needs to add support for latest version of JEI. Reverting to version 3.13.0.342 of JEI is probably the best solution for now.

**Comment by Elix-x** [comment]
For FEI - see Elix-x/Forever-Enough-Items#54.
For JET - see superckl/JustEnoughTooltips#5.
@mezz FEI crash on my side. JET crash on @superckl's side. You can close.
