### ISSUE TITLE
Quark Walls w/ Weird Metadata & Missing Model + Texture

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#569]
[Cross-post of this bug-report in Quark](https://github.com/Vazkii/Quark/issues/207)

Most of the information you'd need is in the original Quark report, but I think this is JEI because the older versions of JEI _don't_ cause this issue, but new versions do. Lemme know if you need more info Mezz, I just figured it'd be easier to post it here. Also, using Item Hiding to try to hide the broken texture version makes nothing happen to **that** version, but makes the properly appearing Wall (with model and texture) be hidden instead....

**Comment by mezz** [comment]
JEI no longer has a config option to hide broken item models, that's the only change. This issue was just hidden before.
