### ISSUE TITLE
Error log spam from Tinkers Construct on Failed Recipe

### ISSUE THREAD

**Issue by Ristellise** [mezz/JustEnoughItems#571]
Full gist log : https://gist.github.com/Joshwoo70/50e5b03d845e6bed7d3e1763dfce8487
shortened log : https://gist.github.com/Joshwoo70/7a2431045d35a119912e98ee18bf2729

**Comment by mezz** [comment]
Thanks for the report!
This is a Tinker's issue, reported here: https://github.com/SlimeKnights/TinkersConstruct/issues/2539
You should include your logs there to help them investigate the issue.
