### ISSUE TITLE
World stuck on loading with latest JEI 1.10.2-3.13.2.349

### ISSUE THREAD

**Issue by benten2000** [mezz/JustEnoughItems#572]
Updated my pack today with latest JEI but when loading my world the screen freezes on Building Terrain.
It was working fine before this update to JEI and upon testing it with my other mods one by one I think I found the problem with CraftTweaker-10.2-3.0.13 (if this disabled the world would load)

Using a previous version of JEI works fine also [3.13.1.346]
Here is the log with the crash and error reports to helpfully help.
http://pastebin.com/sP1gWqUQ

**Comment by mezz** [comment]
Thanks for the report!
Based on the log, JEI is crashing when it is reloaded by another mod (minetweaker). I'll have a fix shortly.

**Comment by mezz** [comment]
Fixed in JEI 3.13.2.350
