### ISSUE TITLE
Crash when middle clicking inventory

### ISSUE THREAD

**Issue by grydian** [mezz/JustEnoughItems#573]
Here is the crash http://pastebin.com/pqCKbQdA
Using the latest JEI

**Comment by mezz** [comment]
Thanks for the report!
Will fix this shortly.

**Comment by mezz** [comment]
To confirm the fix, which gui were you viewing?

**Comment by mezz** [comment]
Ah I've got it, must have been a wide one where JEI can't fit next to it, or when JEI is hidden.

**Comment by grydian** [comment]
Diamond chest from iron chests.  Thanks man :D
