### ISSUE TITLE
Add support for AbstractBrewingRecipe

### ISSUE THREAD

**Issue by zabi94** [mezz/JustEnoughItems#575]
Author of Extra Alchemy here. At the moment I'm registering my custom brewing recipes in JEI via reflection, by getting the constructor of 
`mezz.jei.plugins.vanilla.brewing.BrewingRecipeWrapper`
It would be nice to avoid, so, if it is possible to expose them, it would be awesome.

---
_I swear I saw an issue regarding this, but either I am tripping or I can't find it here on github. They might even be already exposed, I'm just too dumb to find it in the API code_

**Comment by mezz** [comment]
JEI will automatically handle `BrewingRecipe` or `BrewingOreRecipe`. Do you extend something else for your brewing recipes?

**Comment by zabi94** [comment]
Well, I implemented `net.minecraftforge.common.brewing.IBrewingRecipe` but didn't extend any other class

**Comment by mezz** [comment]
I'll see if I can offer automatic support. As long as your ingredient is an ItemStack is should work the same as any other potion recipe. I'll report back soon.

**Comment by mezz** [comment]
Ok `IBrewingRecipe` doesn't offer enough information. I could add support for you if you inherit from `AbstractBrewingRecipe` though.

**Comment by zabi94** [comment]
Yeah, I should be able to do that without a problem. Honestly, I should probably just extend `BrewingRecipe` and save you the hassle, I think I never did that because of a piece of code that doesn't even exist anymore

**Comment by mezz** [comment]
Ok. I'll add `AbstractBrewingRecipe` just because I might as well support as much as I can. I'll close this issue when I do.
Having your recipes go through JEI's handler will have the added benefit of showing the "potion step count" like the other potions.

**Comment by zabi94** [comment]
Yeah, I know, right now I'm providing it manually as a constant to the constructor, and it's the worst thing in the world to have to manually check everytime I modify a recipe and see if the step counter is still correct. I'll happily switch to the correct way of handling it
