### ISSUE TITLE
Crash (Tooltips?)

### ISSUE THREAD

**Issue by EntraptaJ** [mezz/JustEnoughItems#579]
Crash log:https://gist.github.com/Kris6699/5677a7f8302193d8018f5b725f6dc671
my game crashes when hovering over an item sometimes. Attached is my crashlog. I have no idea what is causing it. The logs seems to suggest attempting to draw a tooltip of some kind.
Running latest version. I think.

**Comment by mezz** [comment]
Thanks for the report!
This should be fixed in JEI 3.13.2.355, let me know if you still crash somehow.

**Comment by EntraptaJ** [comment]
Thank you. And will do.
