### ISSUE TITLE
UI Bug - 1.10.2

### ISSUE THREAD

**Issue by Peach774** [mezz/JustEnoughItems#580]
This isnt crashing my game, but whenever I type a second letter into the JEI search bar, it shrinks everything and makes it go to the top left corner. All of my UI then works in about 1/100th of my screen and i cant click anything. I will add a picture in a minute.
This is using the newest version of JEI and forge for 1.10.2
![2016-11-05_17 42 43](https://cloud.githubusercontent.com/assets/5171184/20033828/89a75b08-a380-11e6-81c5-7da62b04a5e7.png)
![2016-11-05_19 36 28](https://cloud.githubusercontent.com/assets/5171184/20034297/5e64145e-a38f-11e6-81bf-009581d696d3.png)
If you look closely, in the top left corner you can see all the UI elements such as the esc screen or the inventory screen. I am not sure if JEI is causing this and I am not sure why it is happening.
EDIT: after doing more testing. I am beginning to think it is a specific item because searching ii does nothing but searching mm or mu causes this to happen. I think it it mod specific, I am not sure which item because it doesnt crash.

**Comment by mezz** [comment]
Thanks for the report!
That is extremely strange. 
I think the best strategy here is to remove other mods in batches.
Then when things are working properly, you can narrow down which mod is causing the issue.

**Comment by Peach774** [comment]
I tried that. A weird thing happened so I tried removing morebees and it stopped happening. Then I relaunched again to make sure and it happened again. I really cant figure out what is causing it. It might be that I am looking through JEI before some items are fully loaded. Is that a possibility?

**Comment by mezz** [comment]
Well as long as it keeps happening, try removing more mods.
Items are loaded by the time JEI can be opened. Some textures are loaded in the background, like player skulls, but I don't think those could cause an issue like this.

**Comment by Peach774** [comment]
The mod that is causing this is forestry. This occurs right when you would render the crates in JEI. IS there a recent change that could be causing this or is this a problem on forestry's side?

**Comment by mezz** [comment]
It's unlikely to be JEI. Forestry's crate rendering recently changed so make sure you try the latest version before reporting.

**Comment by Peach774** [comment]
I'm on the newest versions of both JEI and forestry. The weirdness only occurs when viewing the items in JEI though. When looking at them in the creative menu or without JEI, there are no problems

**Comment by mezz** [comment]
Discussion has moved to Forestry here: https://github.com/ForestryMC/ForestryMC/issues/1500
