### ISSUE TITLE
at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:111) ~[GuiIngredientFast.class:?]

### ISSUE THREAD

**Issue by iTraumatik** [mezz/JustEnoughItems#581]
Pack 1.10.2 my mix of mods, Jei 3.13.2.357 , Forge 2116 (lowest forge i can use with mods i have in my pack),  Java 8v111 (java doesnt recommend lower versions due to security and performance fixes in this version), MultiMC launcher, 8gb java allocated.
I have this same crash but it references cyberware, ralicraft, and one other mod i forget (sry didnt note it) when i either scroll thru JEI with mouse wheel , or type in the search box.

Please let me know how to diagnose this or if infact it is JEI handling after 328 (i think) verison. Anything above it is when i start having problems, which you seen that i posted.  Sry for this but i dont know what is causing it.

 *crash log to [gist] https://gist.github.com/iTraumatik/c1768869fda9ed0ea5600d15f0d04e43
  * No FEI , Optifine , JER installed.

**Comment by mezz** [comment]
Thanks for the report!
This is a crash from Applied Energistics 2 facades, please report here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues

**Comment by mezz** [comment]
I pushed a change in JEI 3.13.2.359 that should log this to the console instead of crashing JEI.
The item will still crash if you have it in your inventory though, so it's worth reporting.
