### ISSUE TITLE
Item List will not re-render when pressing hotkey for visibility of JEI

### ISSUE THREAD

**Issue by hiimcody1** [mezz/JustEnoughItems#582]
In the latest release of JEI, if you press your hotkey to hide JEI, it hides properly. When you press the hotkey to show it again, it will not render until you enter another GUI Screen. This does not match behaviour of previous versions and doesn't appear to be marked as a feature change so I am opening this bug report.

To reproduce, just hide the GUI using your hotkey and try to toggle it.

I tested this without any other mods using forge-1.10.2-12.18.2.2118 and jei_1.10.2-3.13.2.357.

**Comment by mezz** [comment]
Thanks for the report! Confirmed.
