### ISSUE TITLE
Missing recipe for Simple Quarry's fuel quarry

### ISSUE THREAD

**Issue by DatrixTHLK** [mezz/JustEnoughItems#583]
Hi Mezz,

Minecraft: 1.10.2
forge: 12.18.2.2022
JEI: 3.13.2.357

FML Log: [Gist](https://gist.github.com/DatrixTHLK/732365a23e0815aff4bcad49bf280955)
At latest version already

For some odd reason I was able to see the recipe on the side screen while looking at my inventory at [Simple Quarry](https://minecraft.curseforge.com/projects/simple-quarry) mod's Fuel Quarry (before updating past 341). Now pressing R and clicking on it will not show the recipe for it. I doubt FEI's the reason for this. The item itself is in the subset menu I just can't check the recipe for it on the right side of the screen.

**Comment by mezz** [comment]
Thanks for the report!
Your log is too full of various errors for me to find what I need.
Please try again with just JEI and Simple Quarry, and send me the FML Log gist here. Thanks!

**Comment by DatrixTHLK** [comment]
Will do. I will take the errors to the various mod authors so I can, hopefully, get the log less cluttered for other mod authors if the need arises

**Comment by DatrixTHLK** [comment]
https://gist.github.com/DatrixTHLK/f138b78d1a5b5297a44fedefe3263311

**Comment by mezz** [comment]
I tested it out on my own and it looks like they're doing something with recipes from JSON config, but registering the recipe later than JEI loads (which is in `FMLLoadCompleteEvent`). 
Please report the bug to them here: https://minecraft.curseforge.com/projects/simple-quarry/issues

**Comment by DatrixTHLK** [comment]
ok will do
