### ISSUE TITLE
Crash at Startup [1.10.2] [All up to Date]

### ISSUE THREAD

**Issue by DaNeo61** [mezz/JustEnoughItems#585]
Hello i updated today everthing in my own private modpack
now it crashs evertime when i try to start it with the Errorlog

Crashreport
https://gist.github.com/DaNeo61/fb7328d58afcb1b0851a24b97149a789

Modlist:
https://gist.github.com/DaNeo61/ed159f4001d65a29967cd2e5cbd24ca4

Crash caused by:
java.lang.NoClassDefFoundError: mezz/jei/gui/IRecipeGuiLogic

**Comment by GirafiStudios** [comment]
Caused by JustEnoughTooltips.

**Comment by DaNeo61** [comment]
nice one didnt saw it maybe iam to tired xD thanks

**Comment by mezz** [comment]
Reported here: https://github.com/superckl/JustEnoughTooltips/issues/5
Duplicate of #567
