### ISSUE TITLE
Does not create configuration files on server

### ISSUE THREAD

**Issue by mmehnert** [mezz/JustEnoughItems#587]
I'm currently running forge-1.10.2-12.18.2.2122 and tried the latest available version of JEI. When I start the server, JEI does not create configuration files in the config subfolder.  Is there a way to create them?
(Also, in the log files there is no indication from JEI that something is wrong - at least nothing I could see.)

**Comment by TehNut** [comment]
JEI does not have any serverside configs.

**Comment by mmehnert** [comment]
Oh. I had hoped I could perhaps disable the cheat mode :-(

**Comment by TehNut** [comment]
Cheat mode is only available to OP's or people in Creative. Just don't give those to people you don't trust.

**Comment by mmehnert** [comment]
You're right. I don't know what went wrong before. Sorry for the spam :-)

**Comment by mezz** [comment]
This situation should be made more clear once this enhancement is added: https://github.com/mezz/JustEnoughItems/issues/470
