### ISSUE TITLE
Armor plus: armor forge recipes not showing?

### ISSUE THREAD

**Issue by DaFuJosh** [mezz/JustEnoughItems#588]
Thank you for reporting!

 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R).
 * Try the latest version, it may have fixed the issue already.
 * If you have FEI installed, please try without it before reporting.

**Comment by mezz** [comment]
Thanks for the report!
Please report to Armor plus, each mod adds their own recipes.
https://github.com/TheDragonTeam/ArmorPlus/issues
