### ISSUE TITLE
Game crashes after opening inventory

### ISSUE THREAD

**Issue by MrPsychedelic** [mezz/JustEnoughItems#589]
My game crashes every time I try to open my inventory.
[crash-2016-11-06_12.42.31-client.txt](https://github.com/mezz/JustEnoughItems/files/574059/crash-2016-11-06_12.42.31-client.txt)

**Comment by Peach774** [comment]
Are you running NEI and JEI?

**Comment by mezz** [comment]
Thanks for the report!
This is an NEI issue, please report here: https://github.com/TheCBProject/NotEnoughItems/issues
