### ISSUE TITLE
Mod Name Config

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#590]
- It would be nice to see a toggle for the mod name for users who don't want it shown.
- And maybe a config for specifying the colour/style formatting of the modname too.

###### I didn't add [Suggestion] to the title because I assume you'd rather use a label.

**Comment by mezz** [comment]
Good idea. JEI only controls the names in the ingredient list if there is not another mod adding them, but in any case it would be nice to make it configurable.
