### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Y0ungSandwich** [mezz/JustEnoughItems#591]
Crash on startup
JEI is the newest version as is Forge.

https://gist.github.com/Cuppycake/2c7338416a306f4087d5e2c3f32d3b23

**Comment by TehNut** [comment]
Caused by JustEnoughTooltips

**Comment by mezz** [comment]
Thanks for the report!
It has been reported here: https://github.com/superckl/JustEnoughTooltips/issues/5
Duplicate of #567

**Comment by P3rf3ctXZer0** [comment]
Different Cause 

https://gist.github.com/P3rf3ctXZer0/c8c4a6944347d22c089dd902327f3084

**Comment by mezz** [comment]
@P3rf3ctXZer0 that's not related to this issue or JEI. You need to increase the amount of memory you're giving java, or remove mods that are using lots of memory.
