### ISSUE TITLE
Issue with mod - Unkown cause

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#592]
Thank you for reporting!

https://gist.github.com/P3rf3ctXZer0/c8c4a6944347d22c089dd902327f3084

**Comment by mezz** [comment]
Thanks for the report!
That's not related to JEI. You need to increase the amount of memory you're giving java, or remove mods that are using lots of memory.

**Comment by P3rf3ctXZer0** [comment]
Optifine is the cause but I have no way to contact the creator.

**Comment by mezz** [comment]
You can report issues to Optifine here: https://github.com/sp614x/optifine/issues
