### ISSUE TITLE
Issue - Console Spam

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#593]
Console Spam - Client Side
https://gist.github.com/P3rf3ctXZer0/6e2373dc3eb6bb5e3c00a1912215e45a

**Comment by mezz** [comment]
Thanks for the report!
This is a Tinker's issue, reported here: SlimeKnights/TinkersConstruct#2539
Duplicate of https://github.com/mezz/JustEnoughItems/issues/571

**Comment by P3rf3ctXZer0** [comment]
Even though it only started as of your latest version?
