### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Zekken01** [mezz/JustEnoughItems#595]
Have item ids enabled by default for tooltips. Thanks for the great mod btw.

**Comment by TehNut** [comment]
What do you mean by item ids? The numbers? The string ID? Both of those are added by vanilla, nothing to do with JEI.

**Comment by Zekken01** [comment]
yes, the numbers like Stone:1 Enabled by default on the tooltips.

**Comment by TehNut** [comment]
Again, Vanilla thing. Absolutely nothing to do with JEI.

**Comment by Zekken01** [comment]
I'm asking you to enable them by default and have a config option for it with JEI.

**Comment by Zekken01** [comment]
you know what? forget it, You don't understand what I'm trying to ask.

**Comment by Zekken01** [comment]
If you want to reopen it and maybe someone else will understand.

**Comment by TehNut** [comment]
The majority of people would _not_ want those enabled by default. Just hit `F3+H`.

**Comment by ChloeDawn** [comment]
If you're going to suggest NEI features, at least suggest good ones...

**Comment by mezz** [comment]
Yes this can be activated in vanilla by pressing `F3+H` and it will remember that setting.
