### ISSUE TITLE
Crashes when trying to view inventory

### ISSUE THREAD

**Issue by GWSheridan** [mezz/JustEnoughItems#602]
Get this crash every time I look at inventory soon as I press E. I have also reported it to NEI github
Crashes me right back down to launcher 

I only installed NEI because the version of JEI does not show any items when in the inventory so cant see any recipes what so ever. Dont know if this is meant to be a thing or not 

Here link to crash report https://gist.github.com/GWSheridan/9b299dc64e7ff03e357b678a3a107488

**Comment by mezz** [comment]
Thanks for the report!
This is just an NEI issue.
If you have a separate problem without NEI, please submit a new issue. You should be able to use JEI without any other mods.

**Comment by GWSheridan** [comment]
found the problem soon as you remove Aromacore from the pack JEI shows recipes but when you add it back theres a crash so NEI is not compatible with Aroma an it stops JEI from showing recipes. So i have left Aroma out till theres a fix
