### ISSUE TITLE
Issue - Untitled (Please Check Gist for Details)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mezz/JustEnoughItems#604]
https://gist.github.com/P3rf3ctXZer0/af25d3993322c4f11f598160c7546c4c

**Comment by mezz** [comment]
Thanks for the report!
Please try with the latest Minetweaker and JEI.

**Comment by P3rf3ctXZer0** [comment]
I am working on it I hope it helps somewhat.

**Comment by P3rf3ctXZer0** [comment]
Alright so here is some more info during login to world!
https://gist.github.com/P3rf3ctXZer0/65a66951435f5032991c9c29e263ff93

https://gist.github.com/P3rf3ctXZer0/bb50e254b5a2eb9f1dd2c3d05b5fce44

https://gist.github.com/P3rf3ctXZer0/92d3e1d4cc70d6528ed8e50cc5845605

**Comment by mezz** [comment]
1. this is normal until minetweaker stops restarting JEI
2.  and 3. This is a Tinker's issue, reported here: SlimeKnights/TinkersConstruct#2539  
   Duplicate of #571
