### ISSUE TITLE
Some players are experiencing double JEIs

### ISSUE THREAD

**Issue by Saereth** [mezz/JustEnoughItems#607]
Using JEI version 1.10.2-3.13.3.371
Custom pack, modlist: 
https://github.com/breakinblocks/nutsandbolts2/blob/master/CurrentModlist.txt

This only happens to people once they connect to the server, not in singleplayer. It also doesn't happen to everyone. I've never experienced it myself but at least 3 other players have run into this now. One of the JEI's is stuck on some page that they cant change and the other JEI is overlayed over that.

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I do not have free time to look into this for a few days. 
For now they should try using an older stable release version of JEI.

**Comment by Sentrus** [comment]
Hi I'm one of the folks experiencing the bug. Not much information to add unfortunately as I cannot reliably reproduce, or find a way to consistently remedy the bug. Sometimes when I start the pack, the duplicate overlay will be there any time I'm in multiplayer. Sometimes when I restart the pack, it goes away. Other times it appears again.

Only thing I know for certain is that it has never appeared in single player.

**Comment by mezz** [comment]
When you have a chance, please reproduce the bug, upload your fml-client log to https://gist.github.com, and link it here. That should help me get a better idea of what's going wrong.

**Comment by Sentrus** [comment]
https://gist.github.com/Sentrus/5d81c1dc46825f26a3da661bab35566e
And a screenshot of what I'm seeing:
http://imgur.com/DdaVEVI

Thanks for your time mezz.

**Comment by mezz** [comment]
Thanks, the client log shows me what I need to see.
It looks like another mod is restarting JEI from the network thread.
This creates a small window of time where two JEIs can be created.
I will look into fixing this soon.

**Comment by mezz** [comment]
@Sentrus I pushed a potential fix for the problem. 
Please try with [JEI 3.13.3.373](https://dvs1.progwml6.com/jenkins/job/JustEnoughItems/lastSuccessfulBuild/artifact/build/libs/jei_1.10.2-3.13.3.373.jar) and let me know if you have any UI problems.
Instead of showing 2 JEIs, your log should say "A mod is trying to restart JEI from the wrong thread!" and print a stack trace. 
Please paste that log with the stack trace to gist and link it here.

**Comment by Sentrus** [comment]
Here you go mezz. As you said, your error popped, and a stacktrace was printed. Duplicate JEI window did not happen.

Full Log: https://gist.github.com/Sentrus/7bf1d037f806c58094c1b70770f9e215

**Comment by mezz** [comment]
Thanks, that confirms that this issue is properly defended against by JEI. 
I reported the issue to CraftTweaker because it could cause other problems too.
https://github.com/jaredlll08/CraftTweaker/issues/89
