### ISSUE TITLE
JEI is not ignoring metadata when recipe is using item with metadata of OreDictionary.WILDCARD_VALUE

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#609]
JEI is requiring metadata of 0 (+ button blacked out)

![image](https://cloud.githubusercontent.com/assets/6166773/20288231/a4e39b68-aa86-11e6-8a2d-8c804bb313f2.png)

Have proper items, but item is damaged (pressing U on the damaged item doesn't show up recipes either)

![image](https://cloud.githubusercontent.com/assets/6166773/20288235/ab6855be-aa86-11e6-8041-e357ce35b266.png)

Recipe works fine with these items

![image](https://cloud.githubusercontent.com/assets/6166773/20288241/bd398290-aa86-11e6-9e87-32f934e964e8.png)

Spoke to you on IRC about this, told me to report it.

**Comment by mezz** [comment]
Is this still an issue on the latest version of JEI?

**Comment by Prospector** [comment]
Won't be able to check for a few days. Will update then if nobody else does.

**Comment by munsta0** [comment]
@mezz I'm having this issue on the current latest Sky Factory 3 modpack. I can't figure out how to check which version of JEI is being used... 

Used to there was a view loaded mods button

**Comment by mezz** [comment]
Can you show a picture of a recipe where you have the issue?

**Comment by munsta0** [comment]
Ofc! 

Inv : http://puu.sh/trpRj/0d042a69b1.png

Crafting window : http://puu.sh/trpSA/4f9be2ff6e.jpg

Another relatedish problem : If I try to craft maximum number of times with a recipe that uses durability, it will only craft 1 at a time ( Probably because JEI doesn't understand that durability in this case = number of items actually in the slot )

**Comment by mezz** [comment]
@munsta0 this is actually a problem with that particular mod's JEI integration. They need to add a subtype interpreter to tell JEI how their item works. What is the name of that mod?

**Comment by Prospector** [comment]
lol I said I would update within a few days and 7 months later I still haven't.
