### ISSUE TITLE
Single key hotkeys do not work to toggle ingredient list

### ISSUE THREAD

**Issue by AuoroP** [mezz/JustEnoughItems#611]
I am having trouble with toggling visibility and the search bar mode; I'm using FTB Ultimate Lite1.10.

Double click on the search bar does not work. I've swapped mouse buttons left and right.

Toggle visibility works with default control+o; I use this ALOT so I'd like to use just control but I can't.

**Comment by TehNut** [comment]
Double clicking the search bar is not a feature of JEI. I believe More Overlays includes that, though.

You can rebind the visibility key in the controls menu.

**Comment by AuoroP** [comment]
Sorry, I should of done a better job explaining the toggle visibility bug. In the game options I rebound toggle visibility from control+o to just left control and JEI didn't toggle. I also tried left shift, left alt, and right control: all single key cases fail to toggle JEI.

**Comment by mezz** [comment]
Thanks for the report!
