### ISSUE TITLE
Search not working in JEI higher then version 263

### ISSUE THREAD

**Issue by MachinegunMarty** [mezz/JustEnoughItems#613]
Hey Mezz,

Just wanted to say that search isn't working if i pick a higher version then 263.

Strange thing is, i've got Refined Storage and set that to jei synchronized..... That does work ?
So if type in something in the refined storage search bar and walk away, the search result will stay but if i deleted or click in the search it doesn't work anymore.

So somehow pressing E en typing text in the search bar at the bottom does not search through the list anymore from any version higher then 263.

I got a lot of mods (171) so can't tell you which combo is doing it.

Tried all the builds after that, same problem (even the new release: jei_1.10.2-3.13.3.373.jar)

Wish i could give you an error or crash report but my console doesn't spam anything nor my clients....

**Comment by mezz** [comment]
Thanks for the report!
Please use the latest JEI and start removing mods to try to find what is interfering.
There is no better way to find out what is causing the issue, unfortunately.
I recommend removing mods in fairly large batches, or start with no mods and add them in, to help reduce the time spent loading Minecraft.

**Comment by TDStewart** [comment]
It is being caused by the FEI hotfix.

**Comment by MachinegunMarty** [comment]
Thanx TDSteward !

It is indeed FEI. Deleted ForeverEnoughItems and JEI works again !!!

Can live without FEI, not without JEI.

Was working backwards deleting mods and see if it worked. Was gonna start from "i" downwards today.

Saves me allot of work  ;-)

FEI has a Github about it to:  https://github.com/Elix-x/Forever-Enough-Items/issues/56

Thanx Mezz for the patience !

Solved for me by deleting "ForeverEnoughItems"
