### ISSUE TITLE
Add a way to add ItemStacks to JEI during runtime

### ISSUE THREAD

**Issue by Vexatos** [mezz/JustEnoughItems#617]
Some mods need to do some synchronization to send custom item configurations from the server to the client during the first tick after a player joined. These items do not appear in JEI by default as it has already loaded by then. I'd like to see a way to add ItemStacks to JEI after it has loaded, i.e. at any point in time (using `IJeiRuntime` or `IItemListOverlay`). One issue is how to handle loading recipes for these items as that would have to occur during runtime as well (maybe a new `IItemRegistry` containing only the new item(s)?).

**Comment by Vexatos** [comment]
Idea: Also allow registering recipes at runtime, after the new ItemStacks have been added. The required recipe categories and handlers could already be registered/prepared using the `IModRegistry` during postInit, only the recipes themselves might not be there, due to the missing ItemStacks.

When JEI reloads after new ItemStacks and recipes have been added, it should automatically detect them if they have been added to some creative tab, so doing any handling there shouldn't be necessary.

**Comment by mezz** [comment]
For the second part: you can add recipes at runtime with `IRecipeRegistry.addRecipe`
