### ISSUE TITLE
Issues with recipes from Mekanism

### ISSUE THREAD

**Issue by Islarf** [mezz/JustEnoughItems#618]
Example: When looking for recipe for ONLY steel casing (a ton of pages appear):

![image](https://cloud.githubusercontent.com/assets/5913081/20344781/ffa654a8-abeb-11e6-8c37-528d9f58574a.png)

Thank you for reporting!

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you have NEI or FEI installed, please try without it before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by Islarf** [comment]
Example 2: Looking for Metallurgic Infuser recipe, it shows a ton of other recipes also.

![image](https://cloud.githubusercontent.com/assets/5913081/20344842/48f59fa6-abec-11e6-8815-e68f43e5eccf.png)

**Comment by mezz** [comment]
Thanks for the report!
Mods add their own integration to JEI, so this is a Mekanism issue.
I submitted a fix here but has not been released yet: https://github.com/aidancbrady/Mekanism/pull/3925
