### ISSUE TITLE
NBT-specific itemstacks

### ISSUE THREAD

**Issue by ColinGBos** [mezz/JustEnoughItems#620]
In my mod Hammerz, all of the hammer variants are the same item, with NBT variants on the itemstacks.
There are currently over 20 variants possible. When I hover over one of the hammers in the jei overlay and then press the hotkey for finding the recipe, the list of recipes that comes up includes **all** the hammerz and you still have to iterate through them to find which one you were looking for.
I know it's an edge case because not that many mods use purely nbt to differenciate critically unique, but have you looked at adding another layer of specificity to looking at what recipes are valid for itemstacks?

**Comment by ColinGBos** [comment]
More of an inquiry than an issue.

**Comment by mezz** [comment]
See here for information https://github.com/mezz/JustEnoughItems/wiki/Item-Subtypes

**Comment by ColinGBos** [comment]
Thanks! I probably should have dug further before inquiring...

**Comment by mezz** [comment]
No problem!
