### ISSUE TITLE
Do i need other mods for this mod to work?

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#623]
Im not sure if i need to have the original mod for this to work.

**Comment by mezz** [comment]
JEI only needs Forge to run, no other mods.

**Comment by ghost** [comment]
Ok thanks.

**Comment by ghost** [comment]
what do i need to disable for if im going on a server?

**Comment by mezz** [comment]
JEI works on the client, you do not need to disable anything.

**Comment by ghost** [comment]
ok thanks so much.
