### ISSUE TITLE
JEI Team Gui Bug

### ISSUE THREAD

**Issue by Jtgroos** [mezz/JustEnoughItems#628]
Dear Mezz,

Your mod is awesome but i cant get the Team GUI to load.
its stuck in the cool looking loading animation

i downloaded your latest version to see if it was fixed but it was not

i do not know if im the only one with this problem tho

i hoop you fix it if its a bug ( or im just bad at making modpacks ) 

![team gui bug](https://cloud.githubusercontent.com/assets/23549152/20422153/d1bae864-ad68-11e6-8c24-599fd941e339.png)

Thank you for reporting!

**Comment by mezz** [comment]
Thanks for the report!
Please report this to the other mod, I don't know what Team GUI is or how I would be interfering with it. 
Link them back here to this issue if they have any questions.

**Comment by Jtgroos** [comment]
I see i thought it was a part op JEI Sorry dude

**Comment by mezz** [comment]
No problem.
