### ISSUE TITLE
JEI and AE2 (latest alpha 6 build for 1.10.2). When typing in the search box, when the mouse pointer moves away from it, it loses focus and invoked the special 'U' 'R' commands

### ISSUE THREAD

**Issue by jpeaglesandkatz** [mezz/JustEnoughItems#629]
JEI and AE2 (latest alpha 6 build for 1.10.2). When typing in the search box, when the mouse pointer moves away from it (without actually clicking somewhere else), it loses focus and invoked the special 'U' 'R' commands and pops up the special crafting windows.

According to AE2 team this is a JEI issue.

jei_1.10.2-3.13.3.373
appliedenergistics2-rv4-alpha-6
Latest forge

**Comment by mezz** [comment]
Thanks for the report!
