### ISSUE TITLE
MC Crashes whenever you open your inventory

### ISSUE THREAD

**Issue by jld312** [mezz/JustEnoughItems#633]
I do have other mods installed, but even with ONLY jei, it still crashes. I have tried the latest version (4.0.2.194) aswell as older versions that i got from the curseforge site.

http://pastebin.com/raw/9NbpCNBK

or if you only want the gist

https://gist.github.com/jld312/96bbbf92f2fafafbdc4fbd6d3029831a

sorry if this is a client bug and its nothing on you, I'm just really annoyed right now.

**Comment by mezz** [comment]
Thanks for the report!
Try without Optifine, it caused this issue before.

**Comment by jld312** [comment]
thanks that seemed to fix the issue!

**Comment by milkyskies** [comment]
Hi, I get the same, and fixed when removed optifine, However, I would like to use optifine. Is there a way?

**Comment by mezz** [comment]
Please make sure to report your bug to Optifine so they can look into it:
https://github.com/sp614x/optifine/issues
