### ISSUE TITLE
Add a way for JEI to ignore key inputs

### ISSUE THREAD

**Issue by Chocohead** [mezz/JustEnoughItems#634]
#629 fixed JEI reacting to inputs to GuiTextFields when they're in focused, but I've got a custom textbox class that the issue still applies. Could something be added to the API for textbox (or any keyboard watching GUI object) classes be registered, and if they're found a method called to see if they're in focus?
Something like
```java
interface IKeyboardWatcher<T> {
    boolean isFocused(@NotNull T instance);
}
```
where T is the textbox class maybe?

**Comment by mezz** [comment]
The `GuiTextField` addition I made is just to handle the most common case, which exists in vanilla. 

JEI uses `GuiScreenEvent.KeyboardInputEvent.Pre` to detect keys. If you subscribe to that event for keys and use a higher priority than JEI, you can cancel the event and keep JEI from getting that key. This is the proper way to handle multiple mods with key handling, instead of just between JEI and another mod.

**Comment by Chocohead** [comment]
I suppose I could do that, just seems clumsy that rather than overriding GuiScreen#keyTyped you have to subscribe to the event bus to achieve the same thing.

**Comment by mezz** [comment]
Unfortunately there is not a nicer way, because the vanilla keyTyped code does not return a boolean for if the key was used or not. If you think of a better idea for forge let me know, I'd like to improve it but haven't come up with anything.

**Comment by Chocohead** [comment]
How about ```GuiScreen``` gets a protected boolean field added to it that represents if the key was handled or not, and was set to false each time ```Keyboard.next()``` is called, and the ```GuiScreenEvent.KeyboardInputEvent.Post``` only posted if it is still false. That way the pre event is to either go before or skip the GUI's handling completely, and the post is for going after it's handling if the GUI hasn't handled it. That would probably work with minimal extra patching.

**Comment by mezz** [comment]
That sounds good. A bit messy but probably as good as we can get.
I'll mess with it and see.

**Comment by mezz** [comment]
Submitted a PR to Forge for 1.11.
