### ISSUE TITLE
Move reloading into a separate thread

### ISSUE THREAD

**Issue by Gaelan** [mezz/JustEnoughItems#635]
Would it be possible to reload JEI in a separate thread while the game continued to load? I think this would solve a bunch of the problems with Craft{*} reloading and causing multiplayer connections to fail.

**Comment by AEnterprise** [comment]
that would probably cause more issues, if any of the mods access a non threadsafe list during the loading it would completely crash the game

**Comment by mezz** [comment]
This issue will be solved soon.
https://github.com/mezz/JustEnoughItems/issues/551
