### ISSUE TITLE
OOR Exception on trying to open Recipes from a TechReborn Block

### ISSUE THREAD

**Issue by sayore** [mezz/JustEnoughItems#638]
I'm trying to use a Block from TechReborn and wanted to fetch the Recipes(per the GUI in the Block) but i get an OOR Exception as soon as i try to open it in JEI.

Using Latest Releases for 1.10
http://pastebin.com/rQpnxbSP
Screenshot:
![screenshot_27](https://cloud.githubusercontent.com/assets/6115966/20644597/81bde504-b43a-11e6-85b7-c18fd39492b8.png)

I dont know on which side the error occurs so i posted it in both of the GitHubs
Crosslink: https://github.com/TechReborn/TechReborn/issues/810

**Comment by modmuss50** [comment]
its me, this issue can be closed here. I changed a load of stuff with guis around and it broke loads of them :/ @mezz feel free to send duplicate issues my way. Sorry

**Comment by mezz** [comment]
Ok thanks
