### ISSUE TITLE
Minecraft crashes when JEI loaded

### ISSUE THREAD

**Issue by Draconvarie** [mezz/JustEnoughItems#639]
I was running into a problem with not being able to access any GUIs in game, so I removed all my mods and then added them back in one-by-one.

Everything worked fine until I loaded JEI back into the mods file folder. Help, please!

[crash-2016-11-27_11.58.11-client.txt](https://github.com/mezz/JustEnoughItems/files/614826/crash-2016-11-27_11.58.11-client.txt)

https://gist.github.com/Draconvarie/e8c23e03482005c17aee20a53d17b9b3

**Comment by mezz** [comment]
Thanks for the report!
You should update AppleCore and add [AppleSkin](https://minecraft.curseforge.com/projects/appleskin). The version you have is very outdated and I think it's causing the crash.

**Comment by Draconvarie** [comment]
Thank you so much! That was exactly the problem. Everything is working
beautifully now.

On Nov 27, 2016 1:21 PM, "mezz" <notifications@github.com> wrote:
>
> Thanks for the report!
> You should update AppleCore and add AppleSkin. The version you have is
very outdated and I think it's causing the crash.

**Comment by mezz** [comment]
Cool, glad that was it.
