### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by DatrixTHLK** [mezz/JustEnoughItems#640]
Hello

Mods Used:
* Minecraft: 1.10.2
* Forge: 2151
* JEI: 3.13.6.389
For issues:
 *[gist](https://gist.github.com/DatrixTHLK/953a1a7614323aec299e6a753698df57)
No crash occurs, but thought you'd want to know about this error. It is spammed a lot in the FML Log. If you know already, then that is one less thing I need to worry about.

**Comment by mezz** [comment]
Thanks for the report!
This seems to be an issue with FlowerTea mod's recipes. Try removing it and see if the log spam goes away.

**Comment by DatrixTHLK** [comment]
Doing that right now. 
**Edit:** This is the log spam I'm getting now:
* JEI: https://gist.github.com/DatrixTHLK/5f3b4b00db339ad51644898942096105

**Comment by mezz** [comment]
I'm not exactly sure which mod is causing that unfortunately.
Can you try removing mods until the spam goes away, to narrow it down?
I can investigate further once you narrow things down.

**Comment by DatrixTHLK** [comment]
Ok, will do.

**Comment by Peach774** [comment]
DatrixTHLK, what mods are you using, I am having the same problem.

**Comment by DatrixTHLK** [comment]
@Peach774 My modlist: http://tinypic.com/r/zvstns/9 
Minecraft 1.10.2 
I'm not sure about this but the error is thrown out on recipe ingredient 48, and the blockregistry for id: 48 is Mossy Cobblestone. Now a mod I have installed utilizes Mossy Cobble(stone) which is [Cavern](https://minecraft.curseforge.com/projects/cavern) mod. It is either that or [Ex Nihilo Omnia](https://minecraft.curseforge.com/projects/ex-nihilo-omnia) seeing as the recipe for Mossy cobblestone is vines and cobblestone/stone. I'll take out both and see if the spam is less noticable.

**EDIT:** The answer I had was not entirely wrong yet didn't relieve the spam except for maybe a few lines [JEI Spam](https://gist.github.com/DatrixTHLK/4b2438b03582ce0e01543a875935e762). Now maybe 48 means something else other than a block registry...

**Comment by Peach774** [comment]
Try removing projecte and crafttweaker. Do not test this on a world you care about since a new world should have the same problem.

**Comment by Peach774** [comment]
I dont know how to restore your world, but it shouldn't affect the issue. Also, recipe ingredient 48 could have to do with line 48 of a minetweaker script.

**Comment by DatrixTHLK** [comment]
I fixed that world deletion issue. Hence why I deleted that part from the comment. That spam is gone when I took out those mods.

**Comment by mezz** [comment]
I have added better logging for this in the latest versions of JEI. It should log which recipe has the broken itemstack, so that it's easier to hunt down which mod is causing the issue. Make sure to grab the latest JEI and then try.

**Comment by DatrixTHLK** [comment]
I will. Thanks mezz. 389 is the up-to-date version correct, for 1.10.2? That is one I've been using the last few days.

**Comment by mezz** [comment]
That's the latest for 1.10, yes.

**Comment by DatrixTHLK** [comment]
The list of mods with Broken Recipes:
RWBYM 1.0
Ebon Arts (They updated recently and I'm 3 update versions behind them)
Ex Nihilo Omnia 1.2.1
At least that is what the FML log is now telling me.
FML Log: https://gist.github.com/DatrixTHLK/749e899b2fc63c414407b6150bf9f3b0 
Thanks again Mezz I'll let the mod authors know.

**Comment by mezz** [comment]
Ok cool. Please report to them and link back here. They'll probably know what to do to fix their recipe issues, but if not they can ask here.

**Comment by DatrixTHLK** [comment]
The other two had no issues page so I put them on their curseforge page.
