### ISSUE TITLE
Backgrounds rendering weird

### ISSUE THREAD

**Issue by KeeganDeathman** [mezz/JustEnoughItems#641]
I'm not sure where else to post this so here I am.

I'm having issues with my custom plugin, where it's rendering my background as if the file was much larger.

`		return guiHelper.createDrawable(new ResourceLocation("labstuff:textures/gui/circuit-maker-jei.png"), 0, 0, 64, 64);
`

**Comment by KeeganDeathman** [comment]
![2016-11-27_21 57 30](https://cloud.githubusercontent.com/assets/5061001/20657676/8f99599e-b4ec-11e6-845d-b97e56a27777.png)
Here's a screenshot of the issue

**Comment by TehNut** [comment]
What does the image file look like?

**Comment by KeeganDeathman** [comment]
![circuit-maker-jei](https://cloud.githubusercontent.com/assets/5061001/20657906/595c7468-b4ee-11e6-81b3-c7c574b84fd5.png)
64x64

**Comment by TehNut** [comment]
Images like this need to be 256x256. Expand the canvas to 256x256 and leave your actual image content as 64x64 in the top left corner.

**Comment by KeeganDeathman** [comment]
Oh ok. Thank you

**Comment by mezz** [comment]
In JEI for 1.11 there is a new method in `IGuiHelper` to create drawables from images that are not 256x256, but until then you have to use the standard gui sized texture of 256x256.
