### ISSUE TITLE
[1.10.2] Question ItemBlacklist

### ISSUE THREAD

**Issue by YOYOK9** [mezz/JustEnoughItems#644]
This isn't really an issue more a question. In the itemBlacklist.cfg what is the proper way to format an item? Currently I'm doing this:
~CONFIG_VERSION: 0.1.0

.# List of items that should not be displayed in the item list. Format: modId[:name[:meta]]. Edit Mode will automatically add or remove entries here. [Default: []]
    S:itemBlacklist <
    appliedenergistics2[:facade[:0]]
     >

But its not working, Here's a pic of the Item I'm trying to do:
http://puu.sh/sA00r/757942e6eb.jpg

**Comment by TehNut** [comment]
Why not use the in-game editor?

**Comment by YOYOK9** [comment]
The what? is it a mod?

**Comment by TehNut** [comment]
Open the JEI config in-game by clicking the wrench and enable Edit Mode.

**Comment by YOYOK9** [comment]
yeah I found it. Now as a modpack maker will this save somewhere so my clients will also have it all disabled?

**Comment by mezz** [comment]
Yes, it automatically saves your hidden items to a config file that you can distribute.

**Comment by YOYOK9** [comment]
Thank you :D

**Comment by mezz** [comment]
No problem!

**Comment by YOYOK9** [comment]
Sorry whats the difference between hide item and hide with wildcard?

**Comment by mezz** [comment]
Hide item tries to hide one item. hide with wildcard hides all items while ignoring meta value of the item.

**Comment by YOYOK9** [comment]
ah. thanks again. Must comment on how fast you replied to this. Very impressed :D
