### ISSUE TITLE
Search Nearby Chests

### ISSUE THREAD

**Issue by BuzzfeedBlue** [mezz/JustEnoughItems#646]
This is a suggestion. I checked the spreadsheet cause you said not to suggest NEI features, and checked there were no other topics opened on this already. I believe there used to be an NEI feature for this, but it certainly doesn't work in newer versions.

I would like to be able to check the inventories of blocks around me for an item or keyword. Normally this would be used for chests, but could also be used for furnaces, dispensers, etc..

I prefer not to have to label chests, but even if I do it can be hard to know if I put wheat in a food chest or a crop/nature chest.

Hopefully this is doable and something you would actually like to implement. Thank you for taking the time to read this, and have a great day.

**Comment by mezz** [comment]
Thanks for the suggestion!
This feature was actually added by Extra Utilities.
I think this feature it outside the scope of JEI (I try to keep it simple) but it shouldn't be difficult for an addon.
You might want to ask on [reddit](https://www.reddit.com/r/feedthebeast/) or IRC to see if someone has already implemented this, or wants to implement it.
