### ISSUE TITLE
Crash on next page of recipes

### ISSUE THREAD

**Issue by Mxater** [mezz/JustEnoughItems#647]
I see the recipes usage for cooper of industrial, on pass to page 2, this crash.

This is using in a server, if use this in SP, dont crash.

Iam use version 1.61-58-a1fd884

https://gist.github.com/Mxater/af4693a93fa063f3d3a961c18348f62d

Sorry for my english...

**Comment by mezz** [comment]
Thanks for the report!
It looks like this is crashing while rendering a Railcraft item.
Please try updating Railcraft, and if that does not work, report it to them here: https://github.com/CovertJaguar/Railcraft/issues
