### ISSUE TITLE
[Suggestion] Add back the ability to recognize cheatItemsEnabled option in global config

### ISSUE THREAD

**Issue by GazbonicAcid** [mezz/JustEnoughItems#648]
Please add back the ability to recognize the B:cheatItemsEnabled option from the global jei.cfg
This is a required ease-of-life use of the B:cheatItemsEnabled option when JEI is used in conjunction with Forever Enough Items.
It had allowed me to set FEI cheat mode to globally enable cheats in jei override.
Now I have to enable JEI Cheats in FEI cheat mode individually per world.
I don't like this.
Maybe add official global jei.cfg support for the B:cheatItemsEnabled option?
If it's quicker to add back the unintentional support then do that **_*before*_** adding official support.

**Comment by mezz** [comment]
Please ask FEI to properly support what you want instead, I don't see why they couldn't make it easier to use.
https://github.com/Elix-x/Forever-Enough-Items/issues

**Comment by GazbonicAcid** [comment]
This MUST be reopened.
The cheatmode setting is inside the JEI configs, NOT FEI.
FEI uses JEI's configs for the B:cheatItemsEnabled.
In order for FEI to support what I want on their own as things stand now, they would have to dynamically add-to/change the JEI world-specific settings file everytime a player makes/joins a new world.
So NO!!!!
It's *you* that needs to make it easier to use,
as it would be exponentially more difficult to do on FEI's end then yours.
Edit:
Also, FEI did what I'm wanting back when JEI recognized the B:cheatItemsEnabled setting set in it's global config.
FEI does mode-specific JEI config overrides.
Which means they *already* do what I want.
But that you *stopped* doing what I'm wanting.
Because as things now, I have to manually enable cheating items in in JEI config on *every* world because of JEI.
NOT because of FEI.

**Comment by mezz** [comment]
It doesn't matter what FEI has to do. I do not support it in any way, they are perfectly capable of supporting themselves so far. If elix-x comes in here requesting something I will consider it, otherwise I think you should report to them first instead.
They can already hook into JEI and see if cheat mode is enabled or not, without reading the config at all.

**Comment by GazbonicAcid** [comment]
JEI *used* to support what I want.
All I ask is that that support be added back in.
FEI doesn't cheat items in its self.
It uses JEI.
And it can only override the config files,
*not* the specific settings in them.
And my statement that it would be easier to support what I want on JEI's end then FEI's is still true.
FEI doesn't even make the config override files its self.
It has JEI do that.

**Comment by mezz** [comment]
>All I ask is that that support be added back in.

All I ask is that you ask FEI first and get their response first.

**Comment by mezz** [comment]
You're being very childish about this, this is due process and it's nothing personal. 
You can't just demand things and expect that you know everything and everyone should bow to your will. 
All parties have to be a part of the conversation before the proper solution can be found.
In any case it will be fixed somehow and the details should not be so important to you.

**Comment by GazbonicAcid** [comment]
I acknowledge the fact I was being childish and a know-it-all.
And I regret making myself out to be a buffoon.
I realize now that the prior support JEI had for what I want was an unintentional bug/error in JEI.
Which means I was wrong about it being easier to do on JEI's end, since you would have to write entirely new code so as not to reintroduce any other bugs that went with this unintentional support in that older version.

**Comment by majix560** [comment]
I realize now that the prior support JEI had for what I want was an unintentional bug/error in JEI.
Which means I was wrong about it being easier to do on JEI's end, since you would have to write entirely new code so as not to reintroduce any other bugs that went with this unintentional support in that older version.

**Comment by Elix-x** [comment]
@mezz Nothing should be required on your side. It's either missunderstanding or newly appeared bug.

**Comment by GazbonicAcid** [comment]
Minecraft is still loading up.
But I've had thought of how I may have misunderstood something.
Loading up minecraft to test that right now.
I'll let you know if I was right about misunderstanding it.

**Comment by GazbonicAcid** [comment]
I would like to wholeheartedly apologize for my misunderstanding.
I added B:cheatItemsEnabled=true to the cheat mode global jei.cfg while the cheat mode profile was loaded.
It would appear that the issue I was having was that since I was already in cheat mode profile,
FEI did not see the need (which there was none) to re-override the jei config.
I didn't even originally bother to try switching profiles back and forth.
I was wrong.
I am trully sorry.
I hope that you can forgive me.
