### ISSUE TITLE
update jei_1.10.2-3.13.6.387.jar

### ISSUE THREAD

**Issue by SDUBZ** [mezz/JustEnoughItems#652]
hey just letting you know most guis that have a crafting gui dont grab items properly for recipe in this version so far ezstorage and refined storage is affected to my knowledge

**Comment by mezz** [comment]
Thanks for the report!
Sorry I don't understand what you mean. Can you explain more?

**Comment by SDUBZ** [comment]
you know when you shift click a recipe to create a recipe most of the time it fails to do so

**Comment by mezz** [comment]
Does it work in the regular crafting table?

**Comment by SDUBZ** [comment]
i will have to do more testing and get back to you on that
