### ISSUE TITLE
Can't use the search bar

### ISSUE THREAD

**Issue by Eldwen** [mezz/JustEnoughItems#658]
Hi i'm creating a modpack and i don't know why but when i enter something in the searchbar even if i press enter the item list does not change.
I don't know what to do with this bug should i also send my fml logs their ?

**Comment by mezz** [comment]
The search bar should update everything as you type, instantly.
If it isn't, then the most likely cause is another mod interfering.
Back up your pack and try removing mods until the search works properly, so we can find which mod is causing the issue.

**Comment by Thiana** [comment]
Probably FEI, see Elix-x/Forever-Enough-Items/issues/59

**Comment by Eldwen** [comment]
yes i have fei in my pack
so should i simply delete it or replace it by another version ?

**Comment by DatrixTHLK** [comment]
Until Elix_x releases another update you may want to roll back to when JEI and FEI interacted correctly with one another. I don't know what version that would be though.
Same as Elix-x/Forever-Enough-Items/issues/56
