### ISSUE TITLE
JEI seems to be causing a mod sorting cycle error

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#659]
I have about 80 mods, and something is causing a crash and it seems to be JEI. I downloaded a bunch of new mods and I opened minecraft and it gave me a mod sorting cycle error. It says "Forge Modloader had found a problem with your minecraft installation, a mod sorting cycle error was detected and loading cannot continue, the first mod in the cycle is FMLMod:JEI{3.13.6.387}" Then it continues saying mods with before after, etc. Please help.

http://pastebin.com/YgbPuHbW

**Comment by KnightMiner** [comment]
Update Immersive Engineering, issues really is not caused by JEI.

**Comment by mezz** [comment]
JEI only depends on Forge, this sorting cycle is an issue with the other mods in the cycle. 
Please report to `immersiveengineering` which says it must be `before` JEI.

This type of issue may be less of a problem if this PR is pulled: https://github.com/MinecraftForge/MinecraftForge/pull/2906
