### ISSUE TITLE
"Fast" item rendering in item list skips RenderItem#renderItemAndEffectIntoGUI

### ISSUE THREAD

**Issue by Dragon2488** [mezz/JustEnoughItems#664]
"Fast" item rendering directly gets IBakedModel and renders it. When really faster than default rendering, hooks like CodeChickenLib IItemRenderer don't get called, resulting non-hovered and fast-rendered items  invisibility.

Possible solutions:
* Add item blacklist for fast rendering.

**Comment by mezz** [comment]
Thanks for the report!
I have a couple questions:

- When is the CCL hook normally called?
- Models with `IBakedModel.isBuiltInRenderer() == true` are excluded from the JEI fast rendering. Can you set yours to true and render properly?

**Comment by Dragon2488** [comment]
Basically CCL replaces instance of ItemRenderer and catches rendering in several methods. 
And yes, I simply made my model built-in renderer and it solved an issue. Thanks!
![](http://i.imgur.com/oIg3SN7.png)
