### ISSUE TITLE
can anyone tell me the problem ? it cant load page 4 of JEI

### ISSUE THREAD

**Issue by TheSmilingMiura** [mezz/JustEnoughItems#667]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.128-ex110.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/18/16 12:19 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1947)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1625)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1947)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1625)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Xx_Davidoff_xX'/131, l='MpServer', x=123.23, y=87.00, z=411.41]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (48,86,256), Chunk: (at 0,5,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 352095 game time, 352095 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityBat['Bat'/8195, l='MpServer', x=140.42, y=27.40, z=388.51], EntityPlayerSP['Xx_Davidoff_xX'/131, l='MpServer', x=123.23, y=87.00, z=411.41], EntityBat['Bat'/8197, l='MpServer', x=70.50, y=28.47, z=450.28], EntitySquid['Squid'/156, l='MpServer', x=96.18, y=80.94, z=464.05], EntityBat['Bat'/3484, l='MpServer', x=123.39, y=29.43, z=396.40], EntityBat['Bat'/3746, l='MpServer', x=123.25, y=27.10, z=443.25], EntityItem['item.tile.sapling.oak'/43, l='MpServer', x=111.70, y=84.00, z=399.57], EntityWolf['Wolf'/44, l='MpServer', x=96.16, y=84.35, z=423.16], EntityWolf['Wolf'/45, l='MpServer', x=117.70, y=86.00, z=408.36], EntityBoat['Boat'/50, l='MpServer', x=114.16, y=84.52, z=346.33], EntityItem['item.tile.sapling.oak'/51, l='MpServer', x=125.45, y=87.00, z=363.17], EntityWolf['Wolf'/52, l='MpServer', x=118.61, y=85.00, z=373.88], EntityWolf['Wolf'/58, l='MpServer', x=110.89, y=84.56, z=376.49], EntityPig['Pig'/59, l='MpServer', x=127.18, y=87.00, z=376.71], EntityWolf['Wolf'/60, l='MpServer', x=116.56, y=85.00, z=420.51], EntityWolf['Wolf'/61, l='MpServer', x=127.39, y=86.00, z=403.66], EntityItem['item.tile.sapling.birch'/62, l='MpServer', x=122.38, y=84.00, z=423.92], EntityItem['item.tile.sapling.birch'/63, l='MpServer', x=123.58, y=85.00, z=421.29], EntityWolf['Wolf'/67, l='MpServer', x=136.42, y=87.00, z=361.72], EntityItem['item.tile.sapling.oak'/68, l='MpServer', x=139.40, y=87.00, z=366.44], EntityItem['item.tile.sapling.oak'/69, l='MpServer', x=136.51, y=96.00, z=362.53], EntityItem['item.tile.sapling.oak'/70, l='MpServer', x=137.87, y=98.00, z=364.27], EntityItem['item.tile.sapling.oak'/71, l='MpServer', x=130.26, y=100.00, z=366.84], EntityBat['Bat'/5710, l='MpServer', x=86.63, y=42.56, z=339.36], EntityBat['Bat'/8910, l='MpServer', x=177.50, y=20.00, z=413.50], EntityWolf['Wolf'/80, l='MpServer', x=114.89, y=86.00, z=392.43], EntityItem['item.tile.sapling.oak'/81, l='MpServer', x=129.28, y=85.00, z=404.87], EntityItem['item.tile.sapling.oak'/82, l='MpServer', x=135.68, y=85.00, z=412.80], EntityItem['item.tile.sapling.birch'/84, l='MpServer', x=130.80, y=84.00, z=417.50], EntityBat['Bat'/7899, l='MpServer', x=127.18, y=27.29, z=438.31], EntityBat['Bat'/7900, l='MpServer', x=128.03, y=26.07, z=438.80], EntityItem['item.tile.sapling.oak'/8160, l='MpServer', x=134.96, y=86.00, z=359.88], EntityBat['Bat'/8929, l='MpServer', x=86.50, y=40.00, z=341.50], EntityBat['Bat'/5612, l='MpServer', x=172.53, y=51.61, z=478.76], EntityItem['item.tile.sapling.oak'/6773, l='MpServer', x=129.91, y=94.00, z=358.36]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 692107176 bytes (660 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_C1 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-9} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	IC2{2.6.128-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.128-ex110.jar) 
	UCHIJAAAA	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-9} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-9.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UCHIJAAAA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.141_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.141_beta.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3a.jar) 
	UCHIJAAAA	forestry{5.2.16.335} [Forestry] (forestry_1.10.2-5.2.16.335.jar) 
	UCHIJAAAA	geographicraft{0.7.7} [GeographiCraft] (GeographiCraft-0.7.8.jar) 
	UCHIJAAAA	gravisuite{3.0.1} [Gravitation Suite] (Gravitation Suite-3.0.1.jar) 
	UCHIJAAAA	grimpack{3.4.17.52} [Grim Pack] (Grim Pack-1.10.2-3.4.17.52.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJAAAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.128-ex110.jar)
  
AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  appeng.coremod.asm.ASMIntegration
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1055.0' Renderer: 'AMD Radeon HD 8330'
	AE2 Version: alpha rv4-alpha-9 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Acer/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-1.1.3a.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 8330 GL version 4.5.13397 Compatibility Profile Context 15.200.1055.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §l§5S??????.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A4-5000 APU with Radeon(TM) HD Graphics 
	OptiFine Version: OptiFine_1.10.2_HD_U_C1
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13397 Compatibility Profile Context 15.200.1055.0
	OpenGlRenderer: AMD Radeon HD 8330
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by VT-14** [comment]
One of your mods has an item model that isn't rendering properly.  You also have Optifine, which is usually the cause of these kinds of rendering problems in mods.

If the game doesn't crash when you remove Optifine, then report it to them.  Also try to narrow down which mod is having the problem by searching "@modName" or by removing mods alphabetically until you don't crash, and include that mod's name (and version number) in your report to Optifine.  If your game still crashes without Optifine, then figure out which mod it is and report it to them.  JEI is just displaying what the mod is giving it.

Also, most mod authors prefer crash reports and logs to be uploaded in a Github Gist, Pastebin, or another text dump site.  Provide the link in the crash report.

**Comment by mezz** [comment]
Thanks for the report!
Thanks VT-14, that's all correct as far as I know. I think Optifine is the most likely cause.

**Comment by TheSmilingMiura** [comment]
Actually no it wasnt
It was just applied energistics texture bugs
I removed AE2 and it fixed itself.
But thank you guys for the help


Em 19/12/2016 00:20, "James Mitchell" <notifications@github.com> escreveu:

**Comment by VT-14** [comment]
Did you actually try it without Optifine?  Optifine is notorious for causing rendering crashes in the modded community, and you have a rendering crash.

On a different note, your Optifine is several months out of date.  I would not be surprised if the bug was already fixed. I remember the AE2 and Optifine devs were working together on compatibility about a month ago.

**Comment by TheSmilingMiura** [comment]
I did ! It worked fine.

Em 19/12/2016 05:04, "VT-14" <notifications@github.com> escreveu:
