### ISSUE TITLE
[Bug] May not be your mod

### ISSUE THREAD

**Issue by Dijkstra1-zz** [mezz/JustEnoughItems#668]
Hi Mezz, this crash is relly getting me, but have no idea what mod is causing it but JEI is my best bet, here is the crash report
https://gist.github.com/Dijkstra1/0526a7da392595237ce1cd3b613c73e4
If this is down to JEI it would be nice to get fix, if it is not then sorry for wasting your time

**Comment by TehNut** [comment]
Googling the package name comes up with https://github.com/GotoLink/RecipeHandler

**Comment by mezz** [comment]
Thanks for the report!
I think TehNut is right. This is not a JEI issue.
