### ISSUE TITLE
It says: ''loading terrain'' forever!!

### ISSUE THREAD

**Issue by WoJoosen** [mezz/JustEnoughItems#669]
Every time i try to enter a world, it says: ''Loading Terrain'' forever!!!! I enabled Cheats and it still doesnt work... I even deleted every other mod then JEI, and it still isnt loading. When i stop my Minecraft it gives me [this](https://gist.github.com/MobKill3r2006/2b1673d503445f4b3026021c9b76fe29) error!
If you know what that means, please message me back!!

Kind Regards, MobKill3r2006

Minecraft Version: 1.11
JEI Version: 1.11
Windows: 8.1
Client: Forge 1.11

**Comment by TehNut** [comment]
Have you tried updating Forge?

**Comment by WoJoosen** [comment]
I got the newest 1.11 version of forge if im right

**Comment by TehNut** [comment]
That still isn't a version number. What if you're not right?

**Comment by mezz** [comment]
Thanks for the report!
This is caused by old JEI and old Forge. Please update both to the latest versions and the problem will go away.
