### ISSUE TITLE
Game starts lagging due to JEI

### ISSUE THREAD

**Issue by ReCrunch** [mezz/JustEnoughItems#670]
I recently installed JEI and experienced the "Terrain loading" error. after installing a newer forge version it worked just fine. 
The problem I now have is that the game lags when JEI is installed. I tried it without the mod and it works fine.
I am using some other mods as well, these being:
TreeChopper-1.11-1.1.1a
Xaeros_Minimap_1.11.8.1_Forge_1.11
OptiFine_1.11_HD_U_B3_MOD
InventoryTweaks-1.62-dev-74

My forge version is 2188
I read in some other iussue that JEI had some errors with inventory tweaks so I assume that this is the problem. Since it is a dev version of InventoryTweaks the problem could be on that side as well. Just thought I'd let you know about this.

EDIT: Minecraft Version 1.11 obviously ^^

**Comment by mezz** [comment]
Thanks for the report!
Sorry I don't think this is related to JEI at all. It has no effect on terrain or anything like that.
