### ISSUE TITLE
Project-E Philosopher's Stone Shows all REcipes in JEI

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#671]
When checking the philosopher's stone recipes in JEI, it doesn't just show the crafting recipes involving the stone, it shows every recipe that can be crafted when using the stone as a crafting table.
Posted at Project-E: https://github.com/sinkillerj/ProjectE/issues/1458

**Comment by mezz** [comment]
Thanks for the report!
This is normal behavior. When you look up the uses for an item like a crafting table or a furnace, it shows all the recipes that can be crafted on it. In this case, the Philosopher's Stone can craft everything that the crafting table can.

**Comment by ghost** [comment]
Unfortunately, these items can also be crafting components. Ok. Thanks for all the hard work!

**Comment by mezz** [comment]
When they are also crafting components, they should show up at the beginning of the category.

**Comment by ghost** [comment]
That's what I thought, but I wasn't sure it was designed that way. I didn't want to assume I had seen all the crafting recipes. (The various incarnations of the Project-E/EE and spin-offs have a lot of different uses for the stone.)
