### ISSUE TITLE
[1.8.9] Hiding some itens.

### ISSUE THREAD

**Issue by InterPlay02** [mezz/JustEnoughItems#676]
Hello!

I'm using jei_1.8.9-2.28.18.186 and I realized that I can't see some items until I place the mouse over them. Especially itens from BiblioCraft and ExtaUtils2. They still craftable, and still there... But I can't see them. There is no crashes, this happens even without FEI, and... There is some texture bugs with DenseOres, but I don't think JEI has anything to do with it.

[_I don't know if you guys still working on this version of the mod, but I think a should try._]

**Comment by AEnterprise** [comment]
are you using optifine or a similar mod that messes with rendering? those have a tendancy to mess up other mods special rendering
do the items render normaly in your inventory and the world? if not it's most likely a an issue with the mod that adds the items itself

**Comment by InterPlay02** [comment]
Yes... I was using Optifine. Now I removed Optifine and BiblioCraft and ExtraUtil2 are working fine. Only MalisisDoors and Storage Drawers still not appearing. And, again: They still craftable, they render correctly in the inventory and in the world. Only in JEI interface that I can't see them, until I place the mouse over them.

**Comment by mezz** [comment]
This is a rendering bug that has been resolved in later versions of these mods. 
Not many people play 1.8.9, I guess only if you want Intangible and Buildcraft.
