### ISSUE TITLE
Search Bar suggestion 

### ISSUE THREAD

**Issue by NeosGhost** [mezz/JustEnoughItems#677]
Possibly disable the look up recipe/use functions (default 'r' & 'u' keys) when typing in search bar? If the mouse is hovering over an item in the inventory or the item panel and one of those is pressed jei pulls you out of search and into recipe view.

Thanks I love the mod though 🥇

**Comment by mezz** [comment]
Thanks for the report!
In my testing, anything you type when the search bar is highlighted will go to the search bar, I do not see the behavior you described.

Does this only happen in certain inventories? 
Are you on the latest version of JEI?
