### ISSUE TITLE
Search Bar and JEI Config button are broken

### ISSUE THREAD

**Issue by Soundtoxin** [mezz/JustEnoughItems#678]
When hovering over the JEI Config wrench button it lights up blue, so it can see my mouse. However, clicking on it results in no action. The same happens with the paging arrows in the upper right. The search bar cannot search items either.

Modlist: http://sprunge.us/Tijb
I'm using Forge 2201 on Minecraft 1.11.2. I'm running my custom modpack in MultiMC on Arch GNU/Linux. Let me know if you need any more info.

edit: the ctrl-f binding also wasn't working, but it seems to have been conflicting with my inventory binding being f. I changed the bind to ctrl-e and I can now get to the search bar that way to search, but clicking still doesn't work. I also can't view recipes of items by clicking on them after searching.

edit2: When disabling all mods aside from JEI, I do not have the issue. I will continue troubleshooting.

edit3: Well, that didn't take long. FOV Zoom is what broke it. I'll see if I can report to them next. Feel free to close this if you think it's all on their end.

**Comment by mezz** [comment]
Thanks for the report!
This seems like something on their end, JEI works fine without it.
If they have questions you can link them back here to discuss.
