### ISSUE TITLE
Rendering Bug with Charset + Wires

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#68]
Best demonstrated via photos :)

![2015-12-18_07 37 26](https://cloud.githubusercontent.com/assets/3887324/11902924/c47c4676-a57a-11e5-9b2f-68697566ec25.png)

![2015-12-18_07 37 28](https://cloud.githubusercontent.com/assets/3887324/11902925/c47e042a-a57a-11e5-8d9d-9e537343cccd.png)

![2015-12-18_07 37 22](https://cloud.githubusercontent.com/assets/3887324/11902922/c47ada48-a57a-11e5-9d15-0c94ecd8a175.png)

![2015-12-18_07 37 24](https://cloud.githubusercontent.com/assets/3887324/11902923/c47b0a68-a57a-11e5-8e10-432f0a7b8686.png)

JEI Seems to pick the most recently selected wire renderer and applies it to _all_ wires. Not sure why **exactly**, but it started after the 2.8.3 update.

**Comment by mezz** [comment]
Thanks for the report!
That's really strange. I'll take a look soon.

**Comment by BBoldt** [comment]
video version: https://dl.dropboxusercontent.com/u/134976541/ShareX/2015-12/2015-12-20_12-21-58.mp4

**Comment by mezz** [comment]
Fixed here: https://github.com/mezz/JustEnoughItems/commit/579107c352d3d02bb8cf8c8a336844c1c0669cdb
