### ISSUE TITLE
Mod Sorting Cycle Problem.

### ISSUE THREAD

**Issue by Xc4liber** [mezz/JustEnoughItems#680]
This is the Crash report and i don't know why it's happening i tired to fix it but i haven't gotten anywhere with it. Please help.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.57-universal.jar)
  CCCDeobfPlugin (unknown)
  AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.146-universal.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 12/30/16 3:12 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraftforge.fml.client.GuiModList.reloadMods(GuiModList.java:239)
	at net.minecraftforge.fml.client.GuiModList.func_73876_c(GuiModList.java:225)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1720)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.client.GuiModList.reloadMods(GuiModList.java:239)
	at net.minecraftforge.fml.client.GuiModList.func_73876_c(GuiModList.java:225)

-- Affected screen --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModList
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1720)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 183932192 bytes (175 MB) / 487063552 bytes (464 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 21 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	U	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	U	appliedenergistics2-core{rv4-alpha-9} [Applied Energistics 2 Core] (minecraft.jar) 
	U	CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
	U	NotEnoughItems{2.1.1.146} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.1.146-universal.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	U	appliedenergistics2{rv4-alpha-9} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-9.jar) 
	U	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	U	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	U	EnderIO{1.10.2-3.0.1.149_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.149_beta.jar) 
	U	excompressum{2.0.54} [Ex Compressum] (ExCompressum_1.10.2-2.0.54.jar) 
	U	exnihiloomnia{1.2.4} [Ex Nihilo Omnia] (exnihiloomnia-1.2.4.jar) 
	U	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	U	JEI{3.13.6.393} [Just Enough Items] (jei_1.10.2-3.13.6.393.jar) 
	U	journeymap{1.10.2-5.3.3} [JourneyMap] (journeymap-1.10.2-5.3.3.jar) 
	U	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	U	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	U	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	U	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	U	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.57-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)
  
AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  appeng.coremod.asm.ASMIntegration
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.146-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4454' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 20.19.15.4454, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4454
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by mezz** [comment]
Try removing NEI and anything with CodeChicken.

**Comment by Xc4liber** [comment]
the thing is i didnt have them before and it did the same thing

**Comment by mezz** [comment]
Please show me that log

**Comment by Xc4liber** [comment]
Nvm i fixed it it was a mod conflicting with it

**Comment by mezz** [comment]
Which mod? Can you report to them so the can fix it?

**Comment by Xc4liber** [comment]
its an addon for ex nihilo
