### ISSUE TITLE
Minecraft Crash!!!!

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [mezz/JustEnoughItems#685]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
  HungerTweaks (exhaustion-tweaks-1.10.2-1.1.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 1/1/17 3:38 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1477)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:415)
	at net.minecraft.world.World.func_72833_a(World.java:1468)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2207)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1582)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.getSkyColorBody(World.java:1477)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:415)
	at net.minecraft.world.World.func_72833_a(World.java:1468)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2207)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1582)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 07 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8 game time, 8 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 128312472 bytes (122 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m
	IntCache: cache: 45, tcache: 4, allocated: 1, tallocated: 20
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	bspkrscore{7.4.7} [bspkrsCore] (1.10.2.bspkrscore-7.4.7-universal.jar) 
	UCHIJAAAA	treecapitator{2.0.2} [Treecapitator] (1.10.2.treecapitator-2.0.2-universal.jar) 
	UCHIJAAAA	fenceoverhaul{1.2.1} [Fence Overhaul] ([1.10.x]FenceOverhaul-1.2.1.jar) 
	UCHIJAAAA	hud{1.3.8} [Better HUD] (Better HUD by NukeDuck [1.9.4][1.3.8].jar) 
	UCHIJAAAA	binarycraft{1.3} [BinaryCraft] (binarycraft-1.3.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	bspkrsCore{7.1.1} [bspkrsCore] (bspkrsCore_mc1.9-1.10.2_v-client-7.1.1.jar) 
	UCHIJAAAA	JEI{3.13.6.393} [Just Enough Items] (jei_1.10.2-3.13.6.393.jar) 
	UCHIJAAAA	chiselsandbits{12.9} [Chisels & Bits] (chiselsandbits-12.9.jar) 
	UCHIJAAAA	DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar) 
	UCHIJAAAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCHIJAAAA	geographicraft{0.7.5} [GeographiCraft] (GeographiCraft-1.9.4-0.7.6.jar) 
	UCHIJAAAA	grimpack{3.4.17.53} [Grim Pack] (Grim Pack-1.10.2-3.4.17.53.jar) 
	UCHIJAAAA	imc{1.12.1} [Improving Minecraft] (Improving Minecraft-1.12.1.jar) 
	UCHIJAAAA	LlamaMod{1.3} [LlamaMod] (Llama v1.3.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJAAAA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	pcb{1.5.0} [Portable Craft Bench] (portablecraftbench-1.10.2-1.5.0.jar) 
	UCHIJAAAA	reap{1.3.3} [Reap Mod] (ReapMod 1.3.3.jar) 
	UCHIJAAAA	RTG{4.1.2.1} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.1.jar) 
	UCHIJAAAA	corn{1.2.1} [Corn Crop Mod] (SimpleCorn1.10-1.2.1.jar) 
	UCHIJAAAA	spartanshields{1.1c} [Spartan Shields] (SpartanShields-1.10.2-1.1c.jar) 
	UCHIJAAAA	StatusEffectHUD{1.29.1} [StatusEffectHUD] (StatusEffectHUD_mc1.9-1.10.2_v-client-1.29.1.jar) 
	UCHIJAAAA	survivalTweaks{3.0.0} [Survival Tweaks] (SurvivalTweaks-3.0.0-1.10.2.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJAAAA	techbackpack{1.1a} [Tech Backpack] (techbackpack-1.1a-1.10.jar) 
	UCHIJAAAA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	Loaded coremods (and transformers): 
RBLoadingPlugin (RealBench-1.10.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
HungerTweaks (exhaustion-tweaks-1.10.2-1.1.jar)
  qur.tweaks.hunger.EClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 610/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.4
	OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU G3250 @ 3.20GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0
	OpenGlRenderer: GeForce GT 610/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Do not know why, after adding JEI collapse**

**Comment by mezz** [comment]
Thanks for the report!
Sorry but this crash report does not have anything to do with JEI. Try removing some mods to narrow down the problem.
