### ISSUE TITLE
Forge won't Load JEI

### ISSUE THREAD

**Issue by SuperKael** [mezz/JustEnoughItems#688]
It's a simple problem. As of 1.11.2, forge is now enforcing lowercase modids, and JEI's ID is, well, JEI. Since that id is not all lowercase, forge now ignores JEI when loading.

**Comment by shadowfacts** [comment]
JEI's mod ID has been lowercase since 9a2dba818a7d0839c12ccc0b4d2efc37c02c701f, in November. Whatever reason Forge isn't loading JEI for you, isn't caused by the mod ID being upper case.

**Comment by SuperKael** [comment]
Terribly sorry, I somehow managed to download the 1.8 version of JEI...
