### ISSUE TITLE
if you click on the recipies Button with items in hand they dissappear from inventory and are thrown when you close your inventory

### ISSUE THREAD

**Issue by bobis32** [mezz/JustEnoughItems#689]
Thank you for reporting!

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you have NEI or FEI installed, please try without it before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by pau101** [comment]
Woah... Just noticed I submitted my PR #690 to fix this after discovering this bug myself, 16 minutes after you submitted this without knowing you had. I imagine this will be resolved soon.
