### ISSUE TITLE
Blacklist mode doesen't work

### ISSUE THREAD

**Issue by Araton10** [mezz/JustEnoughItems#691]
Hello, I am creating a Modpack and I need to hide some lements by JEI, know that this function does not work there but me, I am attaching the file itemblacklist.cfg, is a test file, to see if it worked, it is not the complete file

http://pastebin.com/24GHkbaw

**Comment by TehNut** [comment]
Are you editing the file manually or using the in-game editor?

**Comment by Araton10** [comment]
i have edited the file manually actually im using jei_1.10.2-3.14.2.401and I have not found the command that you said

**Comment by TehNut** [comment]
Click the wrench to open the ingame config and turn on edit mode.

**Comment by Araton10** [comment]
Okay, but it does not work on the server and this way anyone can disable it, and the mod does not have a config file on the server I see

**Comment by mezz** [comment]
When you distribute your mod pack, include the config file. That way everyone has the blacklist config you created.
JEI works almost entirely on the client, there is no sync from server to client.

**Comment by Araton10** [comment]
Yes but the modpack works on server, everyone can modify the blacklist config

**Comment by mezz** [comment]
That is intentional, JEI's blacklist is only for convenience to players. It is not removing items from the game, just hiding them from its own list. 
If you need something enforced, you can use CraftTweaker to disable the recipes for the items.

**Comment by Araton10** [comment]
The developer of CraftTweaker told me that his code to hide objects from the JEI is broken and will remove this implementation

**Comment by mezz** [comment]
I will talk to him, this is something we have to work out.
The solution may be to have JEI allow blacklisting from the server, but I need to discuss first.

**Comment by Araton10** [comment]
If I could one enable even via server it would be a good thing if the developer of CraftTweaker give a negative result

**Comment by mezz** [comment]
Can you describe what you need this for exactly?
In any case, JEI will not be able to completely remove items from the server.

**Comment by Araton10** [comment]
I could use that JEI works with blacklists config place in the server side and not with that in the client side, so that the end user of Modpack can not change the config and then see hidden objects on the server

**Comment by Yorkforce** [comment]
Were also looking for a server side blacklist implementation, on 1.7 packs we could easily hide banned items from NEI, but as mentioned JEI doesn't seem to have that function which creates alot of problems and confusion for players (who inevitably blame us for trying to craft something we have banned).

Were not asking for JEI to remove items from the server, we can use other mods/plugins to do that, but being able to hide them from players in JEI keeps things simple for our players.
