### ISSUE TITLE
Crash (NullPointerException) when view uses of Pam's Harvestcraft items

### ISSUE THREAD

**Issue by florian-berger** [mezz/JustEnoughItems#695]
Game crashes when trying to view uses of some items out of the Pam's Harvestcraft mod (for example tomato or Saucepan). Reciepts can be displayed without any problems.

**_Versions_**
**Minecraft:** 1.8.9
**JEN:** 2.28.9.176
**Pam's HarvestCraft**: 1.8.9d

**_Other mods_**
AntiqueAtlas
Backpack
BiblioCraft
Chameleon
GraveStone
Inventory Tweaks
OptiFine
Pam's HarvestCraft
StorageDrawers
Waila

**_Crash Report_**
> ---- Minecraft Crash Report ----
>
> WARNING: coremods are present:
> Contact their authors BEFORE contacting forge
> 
> // Don't do that.
> 
> Time: 10.01.17 19:42
> Description: Updating screen events
> 
> java.lang.NullPointerException: Updating screen events
> 	at mezz.jei.gui.ingredients.GuiIngredientGroup.set(GuiIngredientGroup.java:34)
> 	at mezz.jei.gui.CraftingGridHelper.setInput(CraftingGridHelper.java:82)
> 	at mezz.jei.gui.CraftingGridHelper.setInput(CraftingGridHelper.java:44)
> 	at mezz.jei.gui.CraftingGridHelper.setInput(CraftingGridHelper.java:34)
> 	at mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory.setRecipe(CraftingRecipeCategory.java:75)
> 	at mezz.jei.gui.RecipeLayout.<init>(RecipeLayout.java:49)
> 	at mezz.jei.gui.RecipeGuiLogic.getRecipeWidgets(RecipeGuiLogic.java:230)
> 	at mezz.jei.gui.RecipesGui.updateLayout(RecipesGui.java:360)
> 	at mezz.jei.gui.RecipesGui.func_73866_w_(RecipesGui.java:114)
> 	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:501)
> 	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:930)
> 	at mezz.jei.gui.RecipesGui.open(RecipesGui.java:268)
> 	at mezz.jei.gui.RecipesGui.showUses(RecipesGui.java:291)
> 	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:227)
> 	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:188)
> 	at mezz.jei.GuiEventHandler.onGuiKeyboardEvent(GuiEventHandler.java:114)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_GuiEventHandler_onGuiKeyboardEvent_Pre.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
> 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:532)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at mezz.jei.gui.ingredients.GuiIngredientGroup.set(GuiIngredientGroup.java:34)
> 	at mezz.jei.gui.CraftingGridHelper.setInput(CraftingGridHelper.java:82)
> 	at mezz.jei.gui.CraftingGridHelper.setInput(CraftingGridHelper.java:44)
> 	at mezz.jei.gui.CraftingGridHelper.setInput(CraftingGridHelper.java:34)
> 	at mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory.setRecipe(CraftingRecipeCategory.java:75)
> 	at mezz.jei.gui.RecipeLayout.<init>(RecipeLayout.java:49)
> 	at mezz.jei.gui.RecipeGuiLogic.getRecipeWidgets(RecipeGuiLogic.java:230)
> 	at mezz.jei.gui.RecipesGui.updateLayout(RecipesGui.java:360)
> 	at mezz.jei.gui.RecipesGui.func_73866_w_(RecipesGui.java:114)
> 	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:501)
> 	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:930)
> 	at mezz.jei.gui.RecipesGui.open(RecipesGui.java:268)
> 	at mezz.jei.gui.RecipesGui.showUses(RecipesGui.java:291)
> 	at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:227)
> 	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:188)
> 	at mezz.jei.GuiEventHandler.onGuiKeyboardEvent(GuiEventHandler.java:114)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_GuiEventHandler_onGuiKeyboardEvent_Pre.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
> 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:532)
> 
> -- Affected screen --
> Details:
> 	Screen name: mezz.jei.gui.RecipesGui
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityPlayerSP['MyAccountName'/222, l='MpServer', x=464,53, y=67,00, z=664,49]]
> 	Chunk stats: MultiplayerChunkCache: 841, 841
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: 32,00,64,00,228,00 - World: (32,64,228), Chunk: (at 0,4,4 in 2,14; contains blocks 32,0,224 to 47,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 626390 game time, 772955 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> 	Forced entities: 73 total; [EntitySkeleton['Skeleton'/256, l='MpServer', x=524,50, y=33,00, z=659,50], EntityZombie['Zombie'/257, l='MpServer', x=442,50, y=30,00, z=737,22], EntitySkeleton['Skeleton'/258, l='MpServer', x=447,47, y=58,00, z=728,88], EntityBat['Bat'/259, l='MpServer', x=384,28, y=21,09, z=687,25], EntityCreeper['Creeper'/260, l='MpServer', x=390,50, y=24,00, z=646,50], EntityZombie['Zombie'/261, l='MpServer', x=397,50, y=40,00, z=642,50], EntityCreeper['Creeper'/773, l='MpServer', x=408,50, y=29,00, z=668,50], EntityZombie['Zombie'/264, l='MpServer', x=517,50, y=28,00, z=683,50], EntityHorse['Horse'/265, l='MpServer', x=410,94, y=78,00, z=614,94], EntityBat['Bat'/3851, l='MpServer', x=393,95, y=21,00, z=677,30], EntityCreeper['Creeper'/268, l='MpServer', x=392,50, y=24,00, z=690,50], EntitySkeleton['Skeleton'/269, l='MpServer', x=384,50, y=23,00, z=698,50], EntityHorse['Horse'/270, l='MpServer', x=398,03, y=63,00, z=697,00], EntityRabbit['Rabbit'/271, l='MpServer', x=394,28, y=73,00, z=633,50], EntityZombie['Zombie'/272, l='MpServer', x=518,50, y=29,00, z=688,50], EntitySkeleton['Skeleton'/273, l='MpServer', x=516,50, y=29,00, z=691,50], EntityCreeper['Creeper'/275, l='MpServer', x=486,50, y=16,00, z=729,50], EntityBat['Bat'/3731, l='MpServer', x=392,25, y=17,44, z=702,44], EntitySheep['Sheep'/278, l='MpServer', x=414,00, y=78,00, z=595,00], EntityZombie['Zombie'/280, l='MpServer', x=447,50, y=33,00, z=736,50], EntitySquid['Squid'/2841, l='MpServer', x=433,53, y=62,31, z=698,13], EntityCreeper['Creeper'/286, l='MpServer', x=530,50, y=12,00, z=640,50], EntitySpider['Spider'/3358, l='MpServer', x=414,50, y=26,00, z=658,50], EntitySkeleton['Skeleton'/2592, l='MpServer', x=447,50, y=63,00, z=744,50], EntitySkeleton['Skeleton'/3616, l='MpServer', x=488,50, y=16,00, z=728,50], EntitySkeleton['Skeleton'/289, l='MpServer', x=540,50, y=47,00, z=687,50], EntityWitch['Witch'/2598, l='MpServer', x=392,50, y=41,00, z=633,50], EntityZombie['Zombie'/2599, l='MpServer', x=533,50, y=25,00, z=618,50], EntityEnderman['Enderman'/299, l='MpServer', x=537,91, y=23,00, z=630,69], EntitySheep['Sheep'/300, l='MpServer', x=392,94, y=79,00, z=592,00], EntityCreeper['Creeper'/301, l='MpServer', x=527,50, y=52,00, z=605,50], EntitySkeleton['Skeleton'/3629, l='MpServer', x=387,50, y=23,00, z=694,50], EntityCreeper['Creeper'/308, l='MpServer', x=533,50, y=24,00, z=623,50], EntitySquid['Squid'/3124, l='MpServer', x=433,47, y=61,00, z=698,81], EntityPlayerSP['UltimateG4ming'/222, l='MpServer', x=464,53, y=67,00, z=664,49], EntityPig['Pig'/328, l='MpServer', x=387,94, y=70,00, z=740,69], EntityHorse['Horse'/329, l='MpServer', x=404,69, y=70,00, z=737,25], EntitySquid['Squid'/2764, l='MpServer', x=438,50, y=61,00, z=702,50], EntitySheep['Sheep'/336, l='MpServer', x=384,88, y=78,00, z=587,88], EntitySheep['Sheep'/337, l='MpServer', x=385,53, y=78,00, z=589,03], EntityBat['Bat'/338, l='MpServer', x=536,50, y=38,00, z=730,94], EntityCreeper['Creeper'/3033, l='MpServer', x=518,50, y=50,00, z=657,50], EntitySpider['Spider'/223, l='MpServer', x=460,03, y=50,09, z=662,28], EntityCreeper['Creeper'/225, l='MpServer', x=437,91, y=54,00, z=669,56], EntityBat['Bat'/226, l='MpServer', x=417,41, y=43,75, z=654,56], EntitySkeleton['Skeleton'/227, l='MpServer', x=448,28, y=54,00, z=659,69], EntityBat['Bat'/228, l='MpServer', x=446,53, y=56,09, z=660,06], EntityCreeper['Creeper'/229, l='MpServer', x=439,50, y=22,00, z=655,50], EntityCreeper['Creeper'/230, l='MpServer', x=437,25, y=42,00, z=646,47], EntityWitch['Witch'/231, l='MpServer', x=435,50, y=44,00, z=640,50], EntitySkeleton['Skeleton'/232, l='MpServer', x=439,53, y=46,00, z=648,09], EntitySkeleton['Skeleton'/233, l='MpServer', x=436,47, y=42,00, z=651,00], EntityItem['item.item.dyePowder.black'/234, l='MpServer', x=435,38, y=53,00, z=654,47], EntitySkeleton['Skeleton'/235, l='MpServer', x=429,50, y=39,00, z=663,84], EntityZombie['Zombie'/237, l='MpServer', x=425,84, y=41,00, z=657,22], EntitySquid['Squid'/239, l='MpServer', x=434,75, y=61,41, z=697,47], EntitySkeleton['Skeleton'/4081, l='MpServer', x=542,38, y=22,00, z=688,20], EntityChicken['Chicken'/243, l='MpServer', x=424,66, y=19,00, z=652,47], EntitySkeleton['Skeleton'/3699, l='MpServer', x=534,09, y=30,00, z=639,53], EntitySkeleton['Skeleton'/244, l='MpServer', x=423,84, y=41,00, z=650,63], EntityCreeper['Creeper'/245, l='MpServer', x=429,50, y=43,00, z=640,50], EntitySkeleton['Skeleton'/246, l='MpServer', x=438,59, y=48,00, z=635,22], EntitySkeleton['Skeleton'/247, l='MpServer', x=480,50, y=54,00, z=703,50], EntitySkeleton['Skeleton'/249, l='MpServer', x=413,28, y=43,00, z=661,28], EntityCreeper['Creeper'/3705, l='MpServer', x=402,50, y=42,00, z=657,50], EntityCreeper['Creeper'/250, l='MpServer', x=414,22, y=43,00, z=662,25], EntityBat['Bat'/3834, l='MpServer', x=534,25, y=28,69, z=641,46], EntitySquid['Squid'/251, l='MpServer', x=433,47, y=62,16, z=708,50], EntityBat['Bat'/252, l='MpServer', x=401,38, y=43,03, z=687,63], EntitySkeleton['Skeleton'/253, l='MpServer', x=413,69, y=19,00, z=654,78], EntityZombie['Zombie'/3709, l='MpServer', x=527,50, y=31,00, z=615,91], EntityBat['Bat'/254, l='MpServer', x=416,50, y=42,53, z=623,50], EntitySkeleton['Skeleton'/255, l='MpServer', x=393,47, y=27,00, z=671,59]]
> 	Retry entities: 0 total; []
> 	Server brand: fml,forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.8.9
> 	Operating System: Windows 7 (amd64) version 6.1
> 	CPU: 4x AMD Athlon(tm) II X4 640 Processor
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 155472320 bytes (148 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
> 	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
> 	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_H6 12 mods loaded, 12 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
> 	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
> 	UCHIJAAAA	antiqueatlas{@VERSION@} [Antique Atlas] (antiqueatlas-1.8.9-4.2.10.jar) 
> 	UCHIJAAAA	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.8.9.jar) 
> 	UCHIJAAAA	BiblioCraft{2.0.0} [BiblioCraft] (BiblioCraft-Mod-1.8.9.jar) 
> 	UCHIJAAAA	Chameleon{1.8.9-1.1.5} [Chameleon] (Chameleon-1.8.9-1.1.5.jar) 
> 	UCHIJAAAA	gravestone{1.1.6} [Gravestone] (GraveStone Mod 1.1.6.jar) 
> 	UCHIJAAAA	JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
> 	UCHIJAAAA	harvestcraft{1.8.9d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.8.9d.jar) 
> 	UCHIJAAAA	StorageDrawers{1.8.9-2.7.0} [Storage Drawers] (StorageDrawers-1.8.9-2.7.0.jar) 
> 	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-Mod-1.8.8.jar) 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.90' Renderer: 'GeForce GTX 670/PCIe/SSE2'
> 	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
> 	LWJGL: 2.9.4
> 	OpenGL: GeForce GTX 670/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.90, NVIDIA Corporation
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: Sphax_Harvestcraft_1.8.9e_64xA.zip, GLP TexturePack.zip
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 4x AMD Athlon(tm) II X4 640 Processor
> 	OptiFine Version: OptiFine_1.8.9_HD_U_H6
> 	Render Distance Chunks: 14
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.5.0 NVIDIA 372.90
> 	OpenGlRenderer: GeForce GTX 670/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 4

I just removed the name of my Minecraft account.

**Comment by mezz** [comment]
Try with the latest versions, I don't have any issue with JEI 2.28.18
