### ISSUE TITLE
[Suggestion] add a way to add category tab icons without registering crafting items

### ISSUE THREAD

**Issue by bdew** [mezz/JustEnoughItems#696]
Currently (unless i'm missing something) the only way to get a tab icon is by registering a crafting item.

It'd be nice to be able to specify an icon some other way.

For example for JeiBees i'd use a bee icon for bee breeding recipes, but it doesn't make sense to register it as a crafting item.

**Comment by way2muchnoise** [comment]
Can't you use [`IRecipeCategory#getIcon`](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/api/recipe/IRecipeCategory.java#L42-L50)?

**Comment by bdew** [comment]
Derp, i missed it. Sorry.
