### ISSUE TITLE
Crash when looking at recipe for crafting table on a stick in SkyFactory 3 Modpack (1.10.2) http://pastebin.com/9iyBBLsf

### ISSUE THREAD

**Issue by YusamiDC** [mezz/JustEnoughItems#697]
Thank you for reporting!

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you have NEI or FEI installed, please try without it before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by YusamiDC** [comment]
http://pastebin.com/9iyBBLsf

**Comment by mezz** [comment]
Thanks for the report!
If you update SkyFactory 3 to the beta, JEI will not crash.

There is still a bug with MoarSigns, so the recipe will not show. 
I have reported it to them here:
https://github.com/GoryMoon/MoarSigns/issues/32

**Comment by YusamiDC** [comment]
Thank you!

**Comment by mezz** [comment]
After looking more, I am actually able to fix this in JEI. The next version will have it completely fixed.

**Comment by YusamiDC** [comment]
Oh, that's great news!

**Comment by GoryMoon** [comment]
This was also already fixed in newer versions of MoarSigns, they haven't added the update to SkyFactory 3 yet though.
