### ISSUE TITLE
JEI Move Items button no longer works with adjacent inventories.

### ISSUE THREAD

**Issue by MasterRanger** [mezz/JustEnoughItems#698]
Title pretty much describes the issue.  https://youtu.be/zaRL16WDAmw Shows it in action on a single player world.  Happening with all my players on my server

**Comment by TehNut** [comment]
IIRC Tinker's Construct removed this support due to some major issues.

**Comment by mezz** [comment]
Thanks for the report!
There is an open Tinker's Construct issue for it here:
https://github.com/SlimeKnights/TinkersConstruct/issues/2627
