### ISSUE TITLE
Crafting recipe for Sanguine Scientiem not in JEI

### ISSUE THREAD

**Issue by lafflam** [mezz/JustEnoughItems#699]
Summary of the problem: Crafting recipe for Sanguine Scientiem not in JEI

ModPack: Direwolf20 1.10 Version 1.3.2

What is the bug? Crafting recipe for Sanguine Scientiem (guideapi:ItemGuideBook) does not show up in JEI.

Mod & Version: Guide-API 1.10.2-2.0.2-45

Link to log file: N/A

Is it repeatable? Yes. Search for Sanguine Scientiem in JEI and left click the item. No crafting recipe will be displayed.

Known Fix Workaround:

The crafting recipe functions as expected as long as the player knows the shapeless recipe. The problem is that there is no in-game way to discover the recipe:

1 Book (minecraft:book)
1 Feather (minecraft:feather)
1 Glass (minecraft:glass)

I reported this [here](https://forum.feed-the-beast.com/threads/crafting-recipe-for-sanguine-scientiem-not-in-jei.213283/), and it was suggested I report it here.

**Comment by TehNut** [comment]
GuideAPI issue.
