### ISSUE TITLE
Allow custom container logic when "+" button is pressed

### ISSUE THREAD

**Issue by zerofall** [mezz/JustEnoughItems#70]
It seems like currently, the "+" strictly moves items from the player's inventory to specific slots. It would be great to allow completely custom logic to happen instead. For example: my mod has a storage system with a crafting grid in the GUI, and I want to have the items pulled from the storage system instead of just the player inventory (similar to how AE2 works).

**Comment by mezz** [comment]
Hey, you're right it's not possible yet. It's on my TODO but it's good to have it here.
I need to add a more advanced transfer option in the API that lets the mod handle it however they want.

**Comment by zerofall** [comment]
I created a pull request that should take care of it. If there's a different way you would want to go about the implementation, let me know. Great mod by the way!

-Nick

**Comment by mezz** [comment]
Added in the latest build
