### ISSUE TITLE
CTD looking at villager trade tab for bayberries

### ISSUE THREAD

**Issue by xenoflot** [mezz/JustEnoughItems#700]
Hi,

I'm getting a CTD when I look at the Uses / Villager Trades _tab_ for ATLCraft Candles Mod's bayberries.
Crash log: https://gist.github.com/xenoflot/f0a4bfdc2e691ebe53fefef77ecba58f

I see in that log the following exception "Attempted to set villager profession to unregistered profession". We had SGCraft in the pack (which adds a villager) but removed it for reasons. I wonder if something isn't handling the removal of that villager elegantly.

atlcraftcandlesmod-1.10.2-ver1.5
jei-1.10.2-3.14.3.402
justenoughcalculation-1.10.2-2.3.2
justenoughresources-1.10.2-0.5.8.98
forge 2185

sgcraft-1.13.2-mc1.10.2 (no longer present in pack)

Cheers!

**Comment by mezz** [comment]
Thanks for the report!
This looks like a bug with Just Enough Resources, which adds the villager trades to JEI.
Please report to them here: https://github.com/way2muchnoise/JustEnoughResources/issues

**Comment by xenoflot** [comment]
Fabbo! Will do!
