### ISSUE TITLE
KERNEL_DATA_INPAGE_ERROR BSOD

### ISSUE THREAD

**Issue by Narkah** [mezz/JustEnoughItems#701]
I was playing on the AllTheMods pack by WhatTheDrunk when this occurred. I clicked on a pig iron nugget, and bam, BSOD.

 I am running windows 10 with a GTX 750ti, an i3 4170 CPU, and 8 gigabytes of RAM. 

In total, I had Discord, Chrome, Minecraft, Steam, Origin, MSI Afterburner, Bitdefender, SCPToolkit (An xInput wrapper so I can use my PS3 controller as if it is an XBox controller), Lightshot, Rainmeter, F.Lux, and Steelseries Engine 3 for my mouse. Only Chrome, Discord, and Minecraft were not in the background/taskbar.

The only strange variable here was my action while playing: I do not know if this is duplicable and would rather not try right now. 

I tried to include as much relevant info as possible, and I can't think of anything else right now.

**Comment by AEnterprise** [comment]
most likely it's an driver issue, try updating your graphics drivers, they might have choked on rendering something

**Comment by mezz** [comment]
Thanks for the report!

The absolute worst JEI can do is crash java. 
Anything beyond that is a problem with your computer.
I agree with AEnterprise, it does sound like a graphics driver problem.
