### ISSUE TITLE
Recipe Transfer Item Deletion

### ISSUE THREAD

**Issue by pau101** [mezz/JustEnoughItems#702]
In the update to 1.11 [InventoryHelper#addStack](https://github.com/mezz/JustEnoughItems/blob/c07689c8fce55889476e747cb3021064a3455ee0/src/main/java/mezz/jei/util/InventoryHelper.java#L11) acquired a logical error where it will replace existing items when it should be placing into empty slots.
The error is on [line 56](https://github.com/mezz/JustEnoughItems/blob/c07689c8fce55889476e747cb3021064a3455ee0/src/main/java/mezz/jei/util/InventoryHelper.java#L56):
```java
if (!inventoryStack.isEmpty()) {
	if (doAdd) {
		ItemStack stackToAdd = stack.copy();
		stackToAdd.setCount(stack.getCount() - added);
		slot.putStack(stackToAdd);
	}
	return stack.getCount();
}
```
The correct statement would be:
```java
if (inventoryStack.isEmpty()) {
	... 
}
```
The issue can be seen ingame through [this](http://imgur.com/a/MhBN9) dramatization.

**Comment by mezz** [comment]
Thanks for the report!
Confirmed that it was a porting issue, fix incoming.
