### ISSUE TITLE
Game Crash on Coming to the Last Item Page of Mod

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#703]
i typed @harvest in the search bar, which mod is harvest craft, 5 pages items resultant okay, and i came to the last page, booms ! game crashed. here is the crash report.
[crash-2017-01-20_09.55.16-client.txt](https://github.com/mezz/JustEnoughItems/files/718736/crash-2017-01-20_09.55.16-client.txt)

**Comment by ghost** [comment]
omg, it crashes more items of mods. please help :(
here is the another one of crash report
[crash-2017-01-20_14.49.41-client.txt](https://github.com/mezz/JustEnoughItems/files/719404/crash-2017-01-20_14.49.41-client.txt)

**Comment by AEnterprise** [comment]
optifine is most likely messing up the rendering of some items causing things to crash when JEI tries to display them

**Comment by ghost** [comment]
ok i deleted optifine, and came to the 5. page; it is like this...
![bug](https://cloud.githubusercontent.com/assets/24831406/22150889/251cdf48-df24-11e6-89da-c81678177dcd.PNG)
are there any way to solve this? i really want to use optifine :(

**Comment by ghost** [comment]
i think it would be enough to delete that articles on items to solve the crash. how can i disable it?

**Comment by AEnterprise** [comment]
those 'weird' items are a problem with harvestcraft, report it to them, they have invalid states for those items

**Comment by ghost** [comment]
yeah i did but they are not alone. there are also same weird items on other mods. in advanced generators, embers, and some other mods. it is really sad.. there must be a way to disable that texts on items. :(

**Comment by mezz** [comment]
The text on missing item models is caused by Forge in this PR by @RainWarrior 
https://github.com/MinecraftForge/MinecraftForge/pull/3328

**Comment by mezz** [comment]
I reported it to them, maybe they can fix it. In the meantime you can use an older version of Forge without the error text.

**Comment by ghost** [comment]
oh, okay. thanks a lot.
