### ISSUE TITLE
Crash on world load of creating world 

### ISSUE THREAD

**Issue by abdullamu** [mezz/JustEnoughItems#704]
Good day
i have crash when loading or creating world but doesnt close minecraft instance just stuck in loading world the crash happen when ender io is present i tried it with many versions of jei plus ender io from the Release versions to the experimental.
loading the two mods alone works fine but in this pack when both present it crashs, turning off ender io works so it might not be jei problem,
i assumed its JEI becasue this line "Skipping event FMLServerAboutToStartEvent and marking errored mod jeibees since required dependency JEI has errored"

http://pastebin.com/uq9KiPnc
thank you

**Comment by mezz** [comment]
Thanks for the report!
This seems to be a crash when EnderIO calls `item.getSubItems` on the Enchanting-Plus scroll.
Please report to Enchanting-Plus here: https://github.com/Darkhax-Minecraft/Enchanting-Plus/issues

**Comment by abdullamu** [comment]
i disabled enchanting plus until it gets sorted and there no problem with the loading.
