### ISSUE TITLE
JEI Still Showing Recipes Removed by Minetweaker

### ISSUE THREAD

**Issue by Boolyman** [mezz/JustEnoughItems#705]
I have tried this with and without NEI.

When I remove  a recipe with Minetweaker, and add a replacement recipe... both the deleted AND the new recipe show up in JEI.  The deleted recipe will not actually work in a crafting table... since it doesnt actually exist anymore.  This adds even more confusion.  Hiding the item in JEI would hide both recipes, so thats not a solution for me,.  I have attached a screenshot of the Minetweaker Syntax, and the recipe still showing up in JEI.

![2017-01-22 18_33_09-greenshot](https://cloud.githubusercontent.com/assets/24765883/22189458/8bbe7604-e0d1-11e6-8359-2bcbe05595db.png)

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Minetweaker and link back here.
They add and remove recipes from JEI, I do not detect the changes.

**Comment by mezz** [comment]
@Boolyman have you reported this? Has it been resolved?

**Comment by Boolyman** [comment]
It has not been resolved. The mod author for Vies Airships, one of the mods with the most frequent stubborn recipe issues, claims that he has nothing to do with JEI/NEI or Minetweaker showing the recipes... and You guys claim its the mod author.

**Comment by mezz** [comment]
This is an issue with Minetweaker integration. 
If Vies Airships adds their own Minetweaker integration, they are the only ones who can fix it.

**Comment by bookerthegeek** [comment]
@Mezz This is still an issue, with multiple mods. It is weird as I can remove some recipes, but not others. Now when I say remove, they no longer work yet still show up in JEI. And it is odd to as some mods work and other do not. Which is annoying when creating a pack that is for sure. But eh, such is life on a new version of Minecraft. bada bing bada boom.

As this issue was originally started about a specific mod I shall leave it to you. I will though create a nice bug report for you when I get the chance. Keep up the great work!

Also, I need your Paypal or Patron account please.  <- Main point of this post.

**Comment by mezz** [comment]
jared, maintainer of Minetweaker, has the best knowledge of how to create Minetweaker integration that works correctly with JEI. Any mod that has broken integration should talk to him I think.

I have a patreon [here](https://www.patreon.com/mezz), thanks.

**Comment by StoneLegion** [comment]
Sucks so many mods seem to be either doing it wrong or something else but been also having this issue with removed recipes from Calculator and Forestry and doesn't show added Metal Former and Macerator recipes from IC2.

**Comment by mezz** [comment]
I am working with jared on better integration to help alleviate this issue in the future. It seems to require changes on both sides, so it will take some time.

**Comment by mezz** [comment]
This issue should be fixed in the latest versions.

**Comment by kd8lvt** [comment]
I'm getting this issue using CT 1.12-4.0.12 and JEI 4.8.5.138
CC: Tweaked pocket computers are affected. Can not remove the recipe to initally craft them. (7 minecraft:gold_ingot or minecraft:stone, minecraft:golden_apple, minecraft:glass_pane) other pocket computer recipes can be removed fine, it's just that one. Here's my script and log: [gist](https://gist.github.com/kd8lvt/e4d9d8f6341de227abafbbd5fc30152f)
They are also still able to be used as crafting recipes, so not sure if this is a separate issue...
