### ISSUE TITLE
search enhancement JEI needs it 

### ISSUE THREAD

**Issue by abdullamu** [mezz/JustEnoughItems#708]
hello mezz
well i dont want to open new issue, but it would be nice to be able to search like the way NEI by typing the mod name or partial name and it will bring everything from that mod and related items, i understand theres @ but i have to write the very exact name of the mod to get something if theres space or no it matters!,
this is bad for people who cant remember the name of the mods so i have to study every mod name exactly with the spaces dots underscores which is quite annoying since i just left 1.7 to get into 1.10 and i dont know the names of the mods, its even bad for non fluent English speaking people e.g thermal dynamics i always had problem with the name missing one letter or word so i just type dynamics and brings up everything from that mod so easy and convenient than open browser which ganna slow everything down or try to look for my phone to see the name.

Than here starts the second problem, i forget which mods i have most of the times since the modpack im playing currently contain 170 mods, really you want me to remember all of those! . sometimes i look at the nei panel for mods and check their items and pick something to start messing up with or item than i dont know its name.

and i tried to use nei addon but i like to have the search bar on the right and i like how fast JEI in search coming from NEI 1.7 ohh boy not used to the sonic speed JEI provide but these are really necessary stuff to help people interact with the mods easily and without hassle of trying to remember.

thank you and i hope you take it into consideration and we see it soon so i can start properly my 1.10

**Comment by mezz** [comment]
Thanks for the report!

For issue 1: You can type `@thermaldynamics` or `@dynamics` or `@namic` and it will work. You can also change the search options so that the `@` sign is not required.

For issue 2: That is this request here https://github.com/mezz/JustEnoughItems/issues/163

With NEI you should be able to use JEI's search bar and disable theirs, it's in the options somewhere. You can ask them for more information.
