### ISSUE TITLE
@mod seems not to work for me

### ISSUE THREAD

**Issue by boop5** [mezz/JustEnoughItems#709]
I'm probably doing something wrong but I just can't figure it out. Still new to 1.10 and JEI. Playing Sky Factory 3.   
When I search `@refined storage` I don't see all RS items.

![Search](http://i.imgur.com/djLG92O.png)
![Search Options](http://i.imgur.com/u1Wczec.png)

If you are not familiar with RS; there are a lot of missing items. Just for example the controller here
![Controller which does not show on `@refined storage`](http://i.imgur.com/XZzntSG.png)

**Comment by way2muchnoise** [comment]
space are like an AND operation in JEI. The mod id for Refined Storage would be `@refinedstorage`, but just `@refined` should do. In your case you are looking for something in a mod with id `@refined` AND `storage` in the item name.

**Comment by boop5** [comment]
Thanks for the reply. Solved my problem.

**Comment by pambuh01** [comment]
When I want to look at the recipe for something in the game, the game crashes, can you help me?
