### ISSUE TITLE
Recipe does not appear in JEI

### ISSUE THREAD

**Issue by boop5** [mezz/JustEnoughItems#710]
Probably doing something wrong again. But when I'm looking for an item called *Furnace Generator* by exu2 I'm not able to find it per JEI.

Furnace Generator is missing
![Furnace Generator is missing](http://i.imgur.com/sW9qrbP.png)

fun fact: the first item of the search result does not include any of the words

![](http://i.imgur.com/U1ETVFc.png)

However as part of another recipe the furnace generator shows up and has a recipe
![](http://i.imgur.com/in0LL6j.png)

and it also does not appear when I search by mod

![](http://i.imgur.com/zLUDINB.png)

**Comment by way2muchnoise** [comment]
It might be hidden by the pack author, and he might not have removed the recipe. (looking at @darkosto)

**Comment by boop5** [comment]
I understand. thank you again
