### ISSUE TITLE
Cheat Option for blocks of Liquid

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [mezz/JustEnoughItems#711]
I'm using both Mekanism and Refined Storage, and I would like to use the latter to store fluids from the former.  However, if I want to be able to select a specific fluid for Refined Storage to work with (import/export/count amount) I need to be able to take a bucket of that fluid and click with it on the appropriate inventory box to select, which will then fill with a ghost copy of that type of fluid and do whatever I tell it to with that type of fluid in its inventory.

The problem is that, with the exception of three of it's fluids, mechanism doesn't have buckets for the rest of its fluids.  I'm going to talk to both them and RS about this issue, but I was REALLY hoping that one possible solution (hack) would be to just cheat in a block of fluid like I used to be able to do way back in the day with TMI and try placing that into the appropriate box in RS.  Unfortunately, even in cheat mode, clicking on a fluid does not give you a block of that fluid, but instead directs you to all the recipes for that fluid.

Could you PLEASE include a special cheat option toggle to let cheat mode give you fluid blocks instead of recopies?!?  I think that this might be useful in other situations besides just this one.  If nothing else, I miss just being able to hold a block of lava in my hand, regardless of how impossible that should have been (or perhaps precisely because of it)!

**Comment by AEnterprise** [comment]
you can try force enabeling the forge universal bucket, that should add a bucket for all of the fluids

**Comment by 7OOTnegaTerces** [comment]
Uhh, could you send me the link to the directions on how to do that, because I just looked, and everything I found was in reference to mod creators using Forge's fluid system, not how an end user could activate some mystic super fluid bucket function...

**Comment by AEnterprise** [comment]
eighter a mod activates it from code or you can force enable it in the forge config file

**Comment by 7OOTnegaTerces** [comment]
I just looked in the Forge.cfg and the only bucket setting is for disabling the vanilla bucket.  there's nothing about a universal bucket.

**Comment by AEnterprise** [comment]
yes that should dissable the vanilla bucket and replace it with the forge once iirc

**Comment by 7OOTnegaTerces** [comment]
Oh, I didn't think that was it, as the descriptor was about visual aesthetics...  Okay, I just enabled it and restarted Minecraft and...nope, still no Mekanism fluid buckets.

**Comment by AEnterprise** [comment]
is the universal bucket enabled now? if so try to pick up the fluid with it, it might just not have the items registered seperatly but iirc it should be able to pick up any fluid that does not have a bucket form registered

**Comment by cleverca22** [comment]
not sure about in 1.10, but tanks like the one in openblocks also worked for setting fluid filters in 1.7, so you can try that method

**Comment by 7OOTnegaTerces** [comment]
Two problems:
1. I don't have an item labeled "Universal Bucket".  On the assumption that the basic empty bucket is now this "Universal Bucket", there's still point number two.
2. I can't place any of the bucketless Mekanism fluids in the world because their...bucketless.  So I can't pick them back up with a bucket either.  Nor can I use something like EnderIO's fluid tank to fill a bucket with the stuff (I tried).

**Comment by mezz** [comment]
The trouble here is that Minecraft no longer has ItemStacks for fluid blocks.
They existed in 1.7.10 and earlier, you would be able to hold an ItemStack that was lava or flowing lava, etc, but that is no longer the case. You may be able to get them for modded fluids, I forget if that is Forge adding them or what.

Second major issue: in this case I think Mekanism's "fluids" that you can't get in buckets are actually Mekanism gasses. I added support for new ingredient types so that Mekanism can add its gasses, but it hasn't updated in a while so they're not in yet. Also I'm not sure refined storage or other mods work with them, since they are actually distinct from Minecraft fluids.

**Comment by 7OOTnegaTerces** [comment]
All of Mekanism's gases have a fluid counterpart, and the machine to convert back and forth between them. I've been able to work out a hack by filling up a Mekanism tank with each type of bucketless fluid to use in setting Refined Storage fluid filters, but it's a bit cumbersome since I have to keep those filled tanks permanently, fetching and returning it each time.  A lot less convenient than summoning up a water bucket from JEI whenever I need it, then banishing it again.

**Comment by mezz** [comment]
Interesting. I think this is an issue to bring up with Mekanism, no other mod seems to have this issue. There are forge buckets for all the liquids from Forestry, Tinker's, EnderIO, etc.

**Comment by mezz** [comment]
Please report this to Mekanism and link back to this issue here.
