### ISSUE TITLE
Refinment - Debug log recipes that are added by api that have no way of showing

### ISSUE THREAD

**Issue by MakerTim** [mezz/JustEnoughItems#713]
I created today an JEI plugin, for showing my items; and i got stuck for an whole hour trying to debug
and i inserted the wrong type of recipe
so a simple debug message as "there is no handler for recipe type class X" would have been nice

**Comment by mezz** [comment]
Thanks for the report!
I try to add lots of logs to the API for this kind of thing and I will support this. 
Can you show me which method call you made to the API so I can add a check there?

**Comment by MakerTim** [comment]
registry.addRecipes
when you add there new type of recipes; where there is no way to display them
there is no log / warning or something that signs that you doing sometim stupid / wrong

So my suggestion:
log/warn when you add recipes to the registery where there is no IRecipeHandler for it

**Comment by mezz** [comment]
This was added a long time ago but I forgot to close this issue.
