### ISSUE TITLE
AE2 Inscriber recipes not showing since latest JEI update

### ISSUE THREAD

**Issue by davqvist** [mezz/JustEnoughItems#715]
JEI 3.14.3.403
AE2 rv4-alpha11
Forge 12.18.3.2221
Minecraft 1.10.2

Not sure if to report here or the AE2 github, but I tracked it down that it doesn't work since one of the latest JEI updates. So I changed some inscriber recipes with the AE2 recipe config method, but since the latest JEI update, it doesn't show any inscriber recipes anymore even the ones that I haven't touched. With the same AE2 version and JEI 3.14.3.401 it does work. The recipes of course still work, but just JEI isn't showing them. If you need more info let me know. And if I should post it in the AE2 github as well, let me know and I will do so.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to the AE2 github and link back to this issue. Each mod adds their own recipe integration.
If they have questions for me or find out this is a JEI problem, they can discuss here.

**Comment by davqvist** [comment]
So yueh and me tried to figure out this issue since 2 weeks now. You can read it all in the linked issue, but let me summarize. 

I tried to figure out which mod interaction breaks the Inscriber recipes by creating a new instance and adding a few mods at a time. When it broke, I removed one mod at a time until it worked. Removing TechReborn fixed the issue but to confirm I created a new instance with AE2 and TechReborn and it worked. Well then I re-added TechReborn in the first instance and removed another random mod (Advanced Solars) and again it worked. Creating a new instance with AE2 and Advanced Solars again worked though. I tried a third time, re-adding Advanced Solars and removing Immersive Engineering for the same effect, it worked. So I seemed that it breaks when a certain mod cap is reached as it didn't matter which mod I remove. 

But since then one of my modpack dev tester reported that he switched computers. And with the same modpack (with all the same configs and such) Inscriber recipes are shown on one computer and not on the other. We tried several things to match the computers like updating Java and allocating more memory without luck. He was also certain that on the computer on which it worked it did not a few days ago. So it seems really random.

Since then also I noticed that the JEI integration for the Molecular Transformer from Advanced Solars broke as well and I haven't changed any recipes or done anything with the mod. Tests could not come to any results what the issue is. Once I had an instance with some mods. I deleted all the configs and started and the JEI integration worked. I restarted the pack immediately after and the JEI integration was not working.

Today now I heard about a similar issue that Draconic Evolution JEI integration broke for some (I think in Sky Factory 3). It was assumed that CraftTweaker/ModTweaker is the issue and Jared investigated. He found out in his dev environment that the loading order for the JEI modules is the issue. If he told Draconic Evolution to load after Immersive Engineering, it worked. See https://github.com/brandon3055/Draconic-Evolution/pull/602 

This got me thinking. Maybe loading order is the issue for the other two issues as well, especially as the 3 "random" removed mods in the AE2 issue all have custom JEI modules. I don't know in which order JEI modules are loaded but if it is random this could be the cause for the seemingly random appearing problems. So I don't know how to debug this now though and wondered if you could help. jared said he found out about it in his dev environment, debugging when JEI recipes are loaded. yueh said he currently can't run a lot of mods in his dev environment because of a Forge/FML bug which is unfortunate. Maybe you could debug it, especially as it seems JEI related? I have posted a minimal modpack in the AE2 issue. If you need extra info let me know and course if you need more info from jared or yueh please contact them.

Thanks in advance

PS: I nearly forgot. When I did the AE2 debugging I could it also get to work with an older Forge version. Forge 2215 worked, while starting with Forge 2217 it didn't anymore. So I thought it could be Forge related as well, but maybe this again was just that with another Forge version the JEI loading order was different. Hopefully this doesn't make it more complicated, but I just wanted to add it for completeness.

**Comment by mezz** [comment]
They were able to figure out the issue recently. A mod is registering a recipe handler for Object.class, which interferes with other recipe handlers because it's a fallback for every type of recipe and may get picked before other handlers. I added a check in 1.11 to prevent this, and they will fix the issue on their end.

**Comment by davqvist** [comment]
That sounds awesome, but who is they? Forge? And I kind of need the fix for 1.10 as well or will "they" fix it for 1.10?

**Comment by mezz** [comment]
Looks like immersive engineering, and yes they'll fix it soon.
https://twitter.com/brandon3055/status/832529791295246337

**Comment by mezz** [comment]
I can add the check to JEI for 1.10 too, later today.

**Comment by davqvist** [comment]
Thanks you a lot for the link and for the upcoming fix, It gave me 2 weeks of painful debugging. I hope this will indeed fix it.

**Comment by mezz** [comment]
I'm pushing the fix now, it is in JEI 1.10.2-3.14.6.409. 
It should cause bad recipe handlers to crash, so any mod plugin that tries to handle Object.class will be disabled.
Let me know if that fixes your issue or if you still have problems.

**Comment by davqvist** [comment]
Sorry for the late response, but yes the issue seems to be fixed. Thanks a lot, now I'm only waiting for the IE update.
