### ISSUE TITLE
Crash When Searching Anything Up

### ISSUE THREAD

**Issue by jimmydagumjr** [mezz/JustEnoughItems#716]
This is the latest update for JEI and I crash whenever I search anything up. Here's the crash report.

https://gist.github.com/JimmyTheRich/31341076e012aad137d5d01c63a30209

Thanks.

**Comment by jimmydagumjr** [comment]
I also reset all of my configs just in case and I get the exact same crash.

**Comment by jimmydagumjr** [comment]
After looking through previous issues, I realized that optifine was causing the crash due to it's interference with later forge builds.

**Comment by mezz** [comment]
Thanks, marking as duplicate of https://github.com/mezz/JustEnoughItems/issues/714
