### ISSUE TITLE
Add a way to configure ingredient order for recipes with multiple possibilities 

### ISSUE THREAD

**Issue by Fabbi** [mezz/JustEnoughItems#717]
It would be a nice feature to be able to configure the order for ingredient insertion when clicking on the `+` button.

For Example: Some recipes can be crafted with Smooth Stone and Diorite. So the user could configure JEI to use Diorite first.

**Comment by mezz** [comment]
Thanks for the suggestion!
I think this is getting a bit too detailed into the recipe transfer behavior. It just picks the first matching ingredient in the inventory, it's not meant to be super smart.
