### ISSUE TITLE
JEI wont start

### ISSUE THREAD

**Issue by ChienTzu** [mezz/JustEnoughItems#719]
Hallo,

i have installed JEI with Curse ( Feed the Beast Infinity Lite) the newest version. I have the newest version of JEI but when i am ingame i cant activate it. I play with 2 friends on a server, they habve the same modpack but JEI is working. I installed everything again without success. Do you have any idea what i can do now? it is hard to play Blood magic without JEI!

Greetings

**Comment by way2muchnoise** [comment]
If you can see the overlay try ctrl+O, it is the the default toggle key for the overlay.

**Comment by ChienTzu** [comment]
so. I Have it now. (Thank you way) BUT when i play in full screen JEI is gone. but when i play in an tiny window JEI is back!!!!

**Comment by mezz** [comment]
Can you show me a screenshot of tiny window, and fullscreen?
