### ISSUE TITLE
Chest page scrolling crash

### ISSUE THREAD

**Issue by bluedragonke** [mezz/JustEnoughItems#721]
When in a chest and changing pages, as I get to page for the game crashes. 
https://gist.github.com/bluedragonke/2f82d31c7c568161e5190ba2b64b1734

**Comment by mezz** [comment]
Thanks for the report!
This seems to be a duplicate of https://github.com/mezz/JustEnoughItems/issues/714
It is an Optifine bug, fixed in Optifine preview B7 for 1.11.2

**Comment by bluedragonke** [comment]
Ahh shoot, I thought I'd looked through everything too. Sorry about that!
