### ISSUE TITLE
Let buckets of fluids show up in their respective @mod searches

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#722]
I don't know if you'd be willing to do this special casing or not, but it would be a lot nicer if a mod added a fluid with a bucket, the bucket would show up in @modname (as well as @forge, like it normally does)

**Comment by TehNut** [comment]
Would it be possible to expose an API for this? Would be nice if I could have the BM book (well, all Guide-API books for their respective mods) show up under `@bloodmagic`

**Comment by bogger33** [comment]
It'd also be great if the tooltip showed the name of the mod that adds the fluid, rather than forge

**Comment by StoneLegion** [comment]
This would help Advance Solar Panels as well:
https://minecraft.curseforge.com/projects/advanced-solar-panels?comment=44

**Comment by mezz** [comment]
I created a Forge PR for this here: https://github.com/MinecraftForge/MinecraftForge/pull/4330

**Comment by mezz** [comment]
Implemented in JEI 4.8.0 https://github.com/mezz/JustEnoughItems/commit/0f4c4a50d2a0305a3172a7bd2ee812b89a7ba834
