### ISSUE TITLE
I am having problems with JEI, sometimes when I type something into JEI, it crashes. And I finally found where Skyfactory was generating the log.

### ISSUE THREAD

**Issue by ImmatureDemon** [mezz/JustEnoughItems#723]
Thank you for reporting!

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you have NEI or FEI installed, please try without it before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by ImmatureDemon** [comment]
[805b700fb9191b7819e965b8a6868306-f5abca31d1d4d3917306cb49631fd470a9aee227.zip](https://github.com/mezz/JustEnoughItems/files/753104/805b700fb9191b7819e965b8a6868306-f5abca31d1d4d3917306cb49631fd470a9aee227.zip)

**Comment by ImmatureDemon** [comment]
https://gist.github.com/ImmatureDemon/805b700fb9191b7819e965b8a6868306

**Comment by ImmatureDemon** [comment]
But I don't know if that is the correct log.

**Comment by AEnterprise** [comment]
that's a java crash, and it looks like you are using the default java version shiped with your MC launcher. could you update java on your computer and have the launcher use the updated version instead, will most likely fix your crash

**Comment by ImmatureDemon** [comment]
Ok, I will try.

**Comment by ImmatureDemon** [comment]
https://gist.github.com/ImmatureDemon/16e7c623b99ed757fbc4ea1a6785f6e4
It is still doing it.

**Comment by ImmatureDemon** [comment]
But thank you.

**Comment by mezz** [comment]
This crash is coming from codechicken.lib rendering a draconic evolution item. 
It probably does not involve JEI.

It is extremely strange for the JRE to completely crash like this, it's a Java bug really.
You may be able to find out more if you report to CodeChickenLib here: https://github.com/TheCBProject/CodeChickenLib/issues

**Comment by mezz** [comment]
Actually looking at this more closely, it seems to be your graphics driver for your intel integrated graphic card crashing (ig7icd64.dll).  
Make sure to update your graphics driver and see if it fixes this issue.

**Comment by ImmatureDemon** [comment]
It it, because I took CodeChicken Core out of the modpack, and it is still crashing.

**Comment by ImmatureDemon** [comment]
Thank you, I will try to get the drivers updated.

**Comment by mezz** [comment]
@ImmatureDemon Any luck?

**Comment by ImmatureDemon** [comment]
I don't know how to update my drivers. Is ig7icd64.dll the one I need to update to? Or is that the one I have right now?

**Comment by mezz** [comment]
That's the one you have right now, from the log you posted.
Try going here and click "Get Started" to get the latest drivers https://downloadcenter.intel.com/

**Comment by ImmatureDemon** [comment]
I followed the steps and the Intel thing updated my drivers, and it seems to be good so far. Thank you so much.

**Comment by mezz** [comment]
Glad it works, thanks for reporting back.
