### ISSUE TITLE
JEI Is Not Visible After the Update 4.2.4.230

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#727]
i am using it in my modpack, i don't know what should i do. Modpack is available in Technic Launcher, its name is MAGENJI. using game 1.11.2, forge 2227

**Comment by way2muchnoise** [comment]
Have you tried pressing ctrl+O is the default (un)hide key for JEI

**Comment by ghost** [comment]
i tried it already, didn't work.

**Comment by MisterObvious25** [comment]
I have the same problem plus in the console log it spams about broken recipies. If needed i can post it

**Comment by MisterObvious25** [comment]
The  jei_1.10.2-3.14.5.405.jar build has the same problem. Also Spamming console with broken recipies for all the mods

**Comment by Winddbourne** [comment]
I'm having the same problem. On the plus side the conflict with slugs class picker that I reported the other day seems to be fixed in this version.

**Comment by bontavi** [comment]
https://gyazo.com/2d29fe7460a717374e29b343bc6cb8a6 , i'm getting this in console .

**Comment by mezz** [comment]
Thanks for the report!
Pushing an update now, simple fix.
