### ISSUE TITLE
Suggestion: Write log of the items the player takes in cheat mode in the server console (just like MC does with the /give command)

### ISSUE THREAD

**Issue by KirillBorunov** [mezz/JustEnoughItems#728]
When JEI is not installed in the server and the player takes items from JEI then in the server console I can see what they are taking. But with JEI installed in the server I cannot see that information anymore :(
Can this be added?

**Comment by mezz** [comment]
Ah, I used to directly use the `/give` command so it would log.
When I changed to the new implementations, we lost that log.
I'll definitely add something so you can see.

**Comment by mezz** [comment]
Added in the latest JEI versions for Minecraft 1.10.2 and 1.11.2

**Comment by kz5ee** [comment]
Out of curiosity, could this be a configurable option?

**Comment by mezz** [comment]
I want it to match vanilla and the message is only visible to server admins. 
Is the vanilla message configurable?

**Comment by kz5ee** [comment]
Sorry, I hadn't had enough coffee before I asked.  The message is fine.  I was more thinking along the lines of a config option like:  `reportItemCheat=<true|false>` to toggle whether the message is sent to console or not.

**Comment by mezz** [comment]
I don't think I will add a config, I try to avoid adding them unless absolutely necessary.

**Comment by kz5ee** [comment]
It would be nice to be able to disable it when doing testing.

**Comment by rmccarthy1504** [comment]
Heya Mezz, I might be missing this but it seems this no longer happens on 1.16+

Can we get this enhancement added back? Or even a separate log for this.

Super helpful for administrating servers where we have multiple ops.

Thanks!

**Comment by mezz** [comment]
Hi @rmccarthy1504 can you open a new issue so it doesn't get lost?
