### ISSUE TITLE
[Suggestion][Feature request] can you pass mouse cordinates to ICategory#drawExtras

### ISSUE THREAD

**Issue by sp-guip** [mezz/JustEnoughItems#729]
I wanted to draw tooltips for specific region in a category I made and didn't find any non-hacky way to get the mouse x and y.

**Comment by mezz** [comment]
You can use `IRecipeWrapper#getTooltipStrings(int mouseX, int mouseY)` for this purpose. You give JEI the strings you want in the tooltip there.

**Comment by sp-guip** [comment]
Yeah but I needed it specificly in the IRecipeCategory as I don't want to do it for all RecipeWrappers.

**Comment by mezz** [comment]
Would this be solved if I add a `getTooltipStrings` method to `IRecipeCategory`?

**Comment by sp-guip** [comment]
Yes that would be great.

**Comment by mezz** [comment]
Added in JEI 4.2.5 for 1.11.2

**Comment by sp-guip** [comment]
thanks

**Comment by mezz** [comment]
Backported to JEI 3.14.6 for 1.10.2

**Comment by mezz** [comment]
No problem
