### ISSUE TITLE
JEI isn't showing up on Vanilla servers

### ISSUE THREAD

**Issue by SephirothWS** [mezz/JustEnoughItems#73]
![Mod List](http://i.imgur.com/XT5LXE0.png)

Works on single-player:
![Single Player](http://i.imgur.com/f45Jhnp.png)

Doesn't operate on multi-player: (Note: Multi-player server is a vanilla (Spigot) server)
![Multi Player](http://i.imgur.com/QFu5JUE.png)

**Comment by wlhlm** [comment]
Can confirm. JEI won't show up when playing on Vanilla servers, but _works_ when connecting to a forge server with **no** mods installed.

**Comment by GirafiStudios** [comment]
I don't think JEI was ever intended to work on vanilla servers?

**Comment by mezz** [comment]
It should be able to work fine on Vanilla servers, but I'm not sure about Spigot.

**Comment by wlhlm** [comment]
It also doesn't work with _vanilla_ Vanilla Servers ;)

**Comment by mezz** [comment]
I talked to cpw and it looks like this will actually require a fix in Forge. 
I'll keep this open until the solution is available.

**Comment by Prospector** [comment]
It worked fine for me on a spigot server (tried on two popular aervers--hypixel and mineplex)

**Comment by SephirothWS** [comment]
What version of JEI were you using, TheDoctorSoda?

**Comment by Prospector** [comment]
Sorry, I recently cleaned my pc of all my unnecessary files...including that particular minecraft profile. Not sure.

**Comment by mezz** [comment]
I'm using a different event to load JEI now. It should work fine on vanilla servers. Can you confirm? ([version 2.24.3.127](http://minecraft.curseforge.com/projects/just-enough-items-jei/files))

**Comment by xBytez** [comment]
JEI works fine on that release for me now

MC: 1.8.9
Forge: 1.8.9 - 11.15.1.1726

**Comment by mezz** [comment]
Cool. Closing this, fixed by https://github.com/mezz/JustEnoughItems/commit/159bd71af22390e7e9c8c1bb42cc1254df731331
