### ISSUE TITLE
100 Page Same Recipe For Stick

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#730]
in Advanced Sticks mod. it has bough recipe for stick crafting. And there are 100 pages same recipe.
using game 1.11.2, forge 2227, JEI 4.2.5.232

**Comment by KnightMiner** [comment]
This sounds lime an advanced stick issue, them adding redundant recipes.

**Comment by ghost** [comment]
hmm :l i was thinking it happened after updating JEI

**Comment by ghost** [comment]
hey, i´m the creator of advanced sticks, i think my mod is the problem, because other mods that i have installed has not the problem. But i have no idea why the shaped recipes in my mod have 100 page of the same recipe.

**Comment by Ruukas97** [comment]
@xXxRexRaptorxXx Is the source for your mod available? I wouldn't mind taking a look to see if anything seems off.

**Comment by ghost** [comment]
@Zerotiger That would be nice, currently not but i can show you the important parts on pastebin :>

http://pastebin.com/1NZY2GVG

**Comment by Ruukas97** [comment]
On line 75 you have a for loop which loops 100 times, creating all of the recipes 100 times.

**Comment by ghost** [comment]
oh guys, i'm so happy that you found the problem. thank you so much. waiting for the new release!

**Comment by Ruukas97** [comment]
You can mark the issue as solved, to let the JEI dev(s?) know, so they can focus on other issues.

**Comment by ghost** [comment]
yes, hope rexraptor solve the problem easily.

**Comment by ghost** [comment]
I don´t know what I was thinking about it, thanks :D
