### ISSUE TITLE
[4.2.5.233] Client crash in render while looking recipe for Reliquary

### ISSUE THREAD

**Issue by leagris** [mezz/JustEnoughItems#731]
#### Environment
* Minecraft Version: 1.11.2
* Operating System: Linux
* Java Version: 1.8.0_121 64-Bit
* `forge-1.11.2-13.20.0.2227-universal.jar`
* `Reliquary-1.11.2-1.3.3.635.jar`
* `jei_1.11.2-4.2.5.233.jar`
* Detailed [Mods-List](https://gist.github.com/leagris/dc82ac7a1a985f7b72c9a0fa941c7c67/0efb4c6ab50b17ec7e241fcf09028c6b3106311e)
#### Description
```Java
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:152)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:217)
```
#### Reports
* [crash-2017-02-12_17.11.41-client.txt](https://gist.githubusercontent.com/leagris/a5864b11a9d2a21e8926413ef5053dc2/raw/5371cbbaf7a3de91c8ffc220e4516bccdf25c19d/crash-2017-02-12_17.11.41-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the next build of JEI.
