### ISSUE TITLE
Crash client!

### ISSUE THREAD

**Issue by lerion13** [mezz/JustEnoughItems#733]
Crash JEI:
[crash-2017-02-13_09.04.57-client.txt](https://github.com/mezz/JustEnoughItems/files/769911/crash-2017-02-13_09.04.57-client.txt)

Crash occurs when you select an object that has no craft.

**Comment by mezz** [comment]
Thanks for the report!
Please remove NEI and its libraries (CodeChickenLib, CodeChickenCore) and see if it fixes the issue.

**Comment by lerion13** [comment]
Removed, nothing has changed, just as the client crashes.
[crash-2017-02-15_10.54.53-client.txt](https://github.com/mezz/JustEnoughItems/files/776005/crash-2017-02-15_10.54.53-client.txt)

**Comment by mezz** [comment]
Thanks. 
This is a Forestry crate issue, please report here: 
https://github.com/ForestryMC/ForestryMC/issues
