### ISSUE TITLE
UI Doesn't show up and JEI doesn't appear in mods 

### ISSUE THREAD

**Issue by Athos77** [mezz/JustEnoughItems#736]
I'm using Curse to run a few mods for me (which obviously uses forge) and for some reason JEI doesn't show up in the mods when I start up Minecraft, and when I use ctrl + O nothing happens. 
please help

**Comment by mezz** [comment]
Thanks for the report!
Please find your `fml-client-latest.log`, put it on https://gist.github.com, and paste the link here so I can take a look.

**Comment by Athos77** [comment]
https://gist.github.com/Athos77/e8461e0e31ff7b0592f6ca5b9cbf6e32

**Comment by mezz** [comment]
This line is strange:
`[17:54:39] [Client thread/INFO] [FML/]: FML has found a non-mod file jei_1.10.2-3.14.5.406.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.`

Try deleting it and have curse download it again.

**Comment by Athos77** [comment]
deleting the mod or the line?
sorry I'm really not good at modding haha

**Comment by mezz** [comment]
Try deleting the mod from the mods folder.

**Comment by Athos77** [comment]
The same thing is happening...

**Comment by mezz** [comment]
Even after adding the mod again?

**Comment by Athos77** [comment]
I probably should've pointed out at the start that the Curse launcher doesn't allow me to download JEI, so I download it off the website and place the .jar file in the mods folder. Sorry if you needed to know that!

**Comment by mezz** [comment]
The Curse launcher should allow you to download JEI. Why wouldn't it?

**Comment by Athos77** [comment]
I don't know, but when I put JEI or just enough items into the search bar for mods it just says "No results matching your search criteria."

**Comment by mezz** [comment]
Try "Just Enough Items" or "JustEnoughItems"

**Comment by Athos77** [comment]
None of them show up for me...

**Comment by mezz** [comment]
That can happen when it thinks you already have it installed. Check the Installed Mods for your pack.

**Comment by Athos77** [comment]
It isn't there, and I searched again and it still doesn't show up. This is really strange!

**Comment by mezz** [comment]
Make sure your pack is "unlocked" before you can add mods. 
It's under the [...] menu on the pack page, under "Profile Options" there is a "Locked" checkbox.

**Comment by Athos77** [comment]
I don't see a "locked" checkbox.

**Comment by mezz** [comment]
![dots](https://cloud.githubusercontent.com/assets/916092/22964400/57afa70e-f30d-11e6-8c13-d103bb1910ef.png)

![profile-options-select](https://cloud.githubusercontent.com/assets/916092/22964396/524b20e0-f30d-11e6-8768-bcbac16dbd93.png)

![profile-options](https://cloud.githubusercontent.com/assets/916092/22964403/5bea1318-f30d-11e6-8795-989afa51663d.png)

**Comment by Athos77** [comment]
It just isn't there for me.
![capture](https://cloud.githubusercontent.com/assets/25786020/22964490/06c561d0-f3ad-11e6-9c61-141b2acd3133.PNG)

**Comment by mezz** [comment]
Ok, so I assume it's your own pack and it's always unlocked then.
I think you should try to contact Curse support to see what is going on, they will have a better understanding.

**Comment by Athos77** [comment]
Ok, thanks anyway.

**Comment by mezz** [comment]
I had someone else look it over and you are on Minecraft 1.7.10. 
JEI only exists on 1.8.9 and higher.
For 1.7.10 you can use NEI.

**Comment by Athos77** [comment]
I think I just found the issue. My original pack was using Forge 10.13 something something because when I made it, that was the highest it could go due to the current Minecraft update. I just made a new pack that is up to date and I can download JEI normally, and it works perfectly.

**Comment by Athos77** [comment]
Yep, your comment just loaded. You are totally correct sir.
