### ISSUE TITLE
Request/Question: Unobtainable Blocks

### ISSUE THREAD

**Issue by RoksTheWolf** [mezz/JustEnoughItems#738]
May I ask, can you make it so JEI will be able to give the player unobtainable blocks? [Such as end_portal]?
If that is already a feature then how do I go about getting it? [Because I want to be able to place end_portal for a certain build I am doing.]

I already tried the /give command but thanks to 1.11.2, it isn't possible to give yourself an end portal or nether portal block by normal means. 

I could use the /setblock command for a end portal to be placed, but that in my opinion is way too slow for building since it only places one at a time, plus I have to always check the x-y-z axis for the position...

I feel that a feature that gives unobtainable blocks will be quite nice for custom portal building.

**Comment by KnightMiner** [comment]
It is unobtainable because there is no item form, and JEI is not about to change vanilla code. If commands cannot give it to you, I doubt JEI ever will.

**Comment by RoksTheWolf** [comment]
okay, thanks anyways! And dont worry, I found another command that will help me! :)

/fill

**Comment by mezz** [comment]
Yep, commands like `/setblock` and `/fill` are the only way.
It may be possible for a mod to create items to place those blocks, but I think that should be separate from JEI.
