### ISSUE TITLE
Disable JEI GUI if the open GUI is too large

### ISSUE THREAD

**Issue by TehNut** [mezz/JustEnoughItems#74]
A good example of this is the TConstruct Tool Station on large GUI scales. 

[(video)](http://gfycat.com/IdealisticGloomyBullfrog)

![hehe](http://i.imgur.com/RfTgPLO.png)

**Comment by TehNut** [comment]
Maybe as a different possible solution (or both), and interface modders can implement on a GUI class that would cause JEI to not load?

**Comment by modmuss50** [comment]
Or an API to allow the items to wrap the GUI, like in nei.

**Comment by mezz** [comment]
I like both ideas. 

If JEI can't draw a few columns of icons anywhere it should just disable itself.
