### ISSUE TITLE
Special Recipes added by CraftTweaker don't show up

### ISSUE THREAD

**Issue by Mike-T4** [mezz/JustEnoughItems#742]
Special Recipes added through CraftTweaker/Modtweaker no longer show up since the latest update. such 
With "Special" recipes I mean things such as Immersive Engineering Arc Furnace recipes and Abyssalcraft Rituals. 

It also doesn't show Furnace fuel added through CraftTweaker.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to CraftTweaker first and link back here.

**Comment by WesCook** [comment]
Just to add, I've noticed that ore dictionary recipes seem wonky as well.

Just as an example, I've set the jack o' lantern to accept any `<ore:torch>`.  I have three different items that oredict themselves as torches:

* The vanilla torch
* The Tinkers stone torch
* Realistic Torches' lit torch (via CraftTweaker)

Viewing the jack o' lanterns recipe shows them cycling correctly.  I'm also able to craft them correctly.

However, when pressing `U` to show recipes it can be used in, only the vanilla torch and stone torch shows the jack o' lantern recipe.  The third one shows no recipes.

So it seems there's still an issue where ore dictionary entries added via CraftTweaker cannot show recipes in the `U` mode.

I've had some other problems such as oredict's not being removed via ZenScripting, so I'm guessing there's some kinks on CT's side.  But I'm posting here to confirm that some issue still exists.

**Comment by Ommina** [comment]
@Mike-T4 

See  Shinoow/AbyssalCraft-Integration#9

As I understand it, IE is presently affected by another, unrelated, code change.

**Comment by mezz** [comment]
The issue the recipes not loading should be resolved in the latest IE: https://github.com/BluSunrize/ImmersiveEngineering/issues/1890
The Ore Dictionary has a different issue here: https://github.com/jaredlll08/CraftTweaker/issues/142
Anything else regarding CraftTweaker should be reported to them first, not here. Jared will know when it's a JEI issue and will talk to me.
