### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by raspirin** [mezz/JustEnoughItems#743]
Hi.
I created a new world, everything was OK, but when I open the world again, the game crashed.

This is a part of the report:
![por](https://cloud.githubusercontent.com/assets/12580506/23099188/e0a37e8c-f69b-11e6-8a36-98a602b135a1.PNG)

Then I saw 'JEI failed to start', after that, I remove JEI, it fixed.

This is the [report](https://gist.github.com/Fan-Lin/cae4cbb9522864b90f24bce72cdf5e52)

And this is my mod list:
**_Thaumcraft_** and **_Baubles_**
**_Thaumic Bases_** and **_DummyCore_**
**_JEI_** and **_JEIAddons_**
**_BuildCraft_** and **_BuildCraft-Compat_**
**_journey map
InventoryTweaks
Waila
Wawla
VeinMiner_**

**Comment by way2muchnoise** [comment]
It seems to be `DummyCore` as you can see in the [log starting from L46](https://gist.github.com/Fan-Lin/cae4cbb9522864b90f24bce72cdf5e52#file-crash-2017-02-19_11-31-35-client-L46). Something in `DummyCore.Client.IIRAwareModel` causes a `StackOverflow` (because of a recursive loop)

**Comment by mezz** [comment]
Thanks for the report!
The issue has been reported to DummyCore here: https://github.com/Modbder/DummyCore/issues/10
Please add your information there so that they can solve it.

**Comment by raspirin** [comment]
Thanks.
