### ISSUE TITLE
[1.10.2] Recipe List Building issues

### ISSUE THREAD

**Issue by Speiger** [mezz/JustEnoughItems#744]
I have a special case which isnt IC2cs fault.
When the RecipeInput & the Recipe Category are equal these recipes will be duplicated when you use the input item to  get the recipelist.

I have a ScrapBox Category which shows Scrapbox Drops. Input & CategoryItem are The Scrapbox.
I have 47 Recipe list. and it lists 3 items per page. But i have 32 Pages when i click on the scrapbox (rightclick). But it should be only 16 pages.

The reason why this is a JEI Bug is:
JEI builds the RecipeLists for the guis and not the modOwner. The only thing we have control over if the recipe is valid.

**Comment by mezz** [comment]
Can you show me a screenshot? I'm not sure what you are talking about.

**Comment by Speiger** [comment]
Sry I can't my computer broke so no access to that.

Basically to reproduce this: use a Item that is a Category Item and also a recipe Input you will see that these recipes that have this item in as input be duplicated when the uses key being used.

**Comment by mezz** [comment]
Is this a duplicate of https://github.com/mezz/JustEnoughItems/issues/509?

**Comment by Speiger** [comment]
Yes that's the issue.
Since Recipes are cached you should be able to filter the RecipeWrapper instances.
Maybe add a equals function or also cache these wrappers in a LinkedHashMap
