### ISSUE TITLE
Issues with JEIs Prefabrication system

### ISSUE THREAD

**Issue by Speiger** [mezz/JustEnoughItems#745]
I wish i could update the mod IC2Crop Plugin which creates a pre caclulate information about what combos are the best to get a Crop.
There is 1 big problem with JEI.
If i use JEIs System it would increase the World Load time by 1-15 seconds at minium conditions.
To give a example: in 1.7.10 i thread the caluclation and do not allow to access these recipes until the recipe list is finalized. Because its so many types to calculate.
Smallest calculation is: 38^2 = 1444 Possible Combos
Middel calculation is : 38^3 + 38^2 = 56316 Possible Combos
Biggest calculation is: 38^4 + 38^3 + 38^2  = 2141452 Possible Combos.
And that is Vanilla IC2 if other mods add something to it it will be bigger

It needs to create all possible combos and then on top of that prevents duplicates.
On top of that yes to give a accurate information i have to in some cases show all cases.
And if someone enables the biggest combo the Calculation would lag the game for quite some time...

JEI should add a optional way to register things later...

**Comment by mezz** [comment]
Perhaps this special information should go in a guidebook or other custom-purpose UI and not JEI.

**Comment by Speiger** [comment]
@mezz why should I reinvent a new thing instead of using what is already there.
But the problem is: how can I remove the 45 seconds (worst case without addons that add more) extra game load time/game locking?
On top of that I made a secondary system that allows player chosen calculation.
But its not as complex as the "Best Combo" System.
Sadly IC2Crops are not a alloy Furnace like Crop breeding like Agricraft.
(Its not something bad and Infinity Raider knows that)

I mean could you give me a way how I can hook a custom JEI Builder,
Like a Custom Uses/Recipe Hook when Crops being asked for.
I mean you have the filter class. Is there possible way to allow someone to add after the game loaded and JEI loaded to inject or access custom calculation that take longer then usual?

The reason why I ask that is because I am forced to start my calculation at the mod finalization event (step 7 out of 7 steps). And I don't want to increase load time longer then nessesary

**Comment by mezz** [comment]
That hook exists, see `IRecipeRegistryPlugin`.

**Comment by Speiger** [comment]
Is that the NEI variant of JEI recipe look up?
O.O

**Comment by Speiger** [comment]
If that is what I think it is.
Then thanks for implementing this :3

**Comment by Speiger** [comment]
Sadly I can't code at the moment so it has to wait.
