### ISSUE TITLE
Colored Shulker boxes recipes not showing.

### ISSUE THREAD

**Issue by DrivenInsane7** [mezz/JustEnoughItems#748]
Noticed that on 1.11.2 the recipes for colored shulker boxes are not showing in JEI.  They can still be crafted and the default shulker box, purple, does show it's recipe but the rest do not show.

**Comment by mezz** [comment]
Thanks. 
There are still several types of recipes that are not shown, they will be added eventually.

**Comment by mezz** [comment]
This was added by https://github.com/mezz/JustEnoughItems/pull/2290 but I forgot about this issue, I'll close it now.
