### ISSUE TITLE
[JEI]: Found a broken crafting recipe.

### ISSUE THREAD

**Issue by bookerthegeek** [mezz/JustEnoughItems#749]
Me again. :/

So I am having an issue with null recipes. For example... [ghist](https://gist.github.com/bookerthegeek/48caa9e38ed6180fcd1ca2cd9d18e18a)

I am wondering oh kind and merciful Mezz if you could please add in the error, if it is not to hard, the mod that is adding the null recipe? This would make it so much easier to track down. I have no idea how hard this would be, or if it is even possible, but would be amazingly helpful if it can be done.

**Comment by mezz** [comment]
This requires a patch to Forge because there's no other way to know which mod registers a recipe.
It would be really useful though, I'll look into it.

**Comment by bookerthegeek** [comment]
Just F.Y.I for anybody also seeing this in their logs... My issue was caused by [Better Agriculture][1] (link to Issue). 


[1]:https://github.com/MinecraftModDevelopmentMods/BetterAgriculture/issues/43

**Comment by mezz** [comment]
In 1.12 it's possible to see which mod recipes come from, so I will revisit this idea.

**Comment by bookerthegeek** [comment]
Thank you @mezz!
