### ISSUE TITLE
BrokenCraftingRecipeException (JEI or XTones issue?)

### ISSUE THREAD

**Issue by DeadSix27** [mezz/JustEnoughItems#752]
Versions:
`jei_1.10.2-3.14.7.415.jar`
`Xtones-1.10.2-1.0.0-2.jar`

I posted this issue on both trackers as I do not know which one of the mods is responsible.

Other Issue link:  https://github.com/TehNut/Xtones/issues/4

Stacktrace: http://pastebin.com/pmbUuhNk

**Comment by accessdenied0** [comment]
Sorry to put my text here but: your Stacktrace/crash-report is gone. Maybe replace it with a new one.

**Comment by DeadSix27** [comment]
@accessdenied0 Sorry, somewhy got removed, here is the new one: https://paste.ubuntu.com/24078914/

**Comment by mezz** [comment]
Thanks for the report!
This is an XTones issue.
