### ISSUE TITLE
JEI doesn't reflect on changes made to Tinkers Construct special recipes

### ISSUE THREAD

**Issue by Arakhor** [mezz/JustEnoughItems#753]
Hi, I don't know if it's a fault on TiC, JEI or CraftTweaker part, but any special recipe created for casting, drying etc. doesn't seem to be reflected in JEI, the recipe will work, but the panel will still only show default recipes.

Tested with all latest versions marked as "release".

**Comment by KnightMiner** [comment]
Tinkers Construct does not add CraftTweaker support, that is added by ModTweaker, so that mod is probably not properly updating JEI.

**Comment by mezz** [comment]
Thanks for the report!
Please check the existing issue here and add your information: https://github.com/jaredlll08/ModTweaker/issues/426
