### ISSUE TITLE
[Enhancement]Ctrl+A in search bar

### ISSUE THREAD

**Issue by Thyriel** [mezz/JustEnoughItems#754]
Something that bothers me since a while in JEI, would it be possible to allow ctrl+A in the search box to select the whole text ? Would make it much faster entering something new

**Comment by mezz** [comment]
Thanks for the report!
ctrl+A should work fine, I just tested to make sure. Do you have some addon like FEI or NEI that might interfere with keyboard input?

**Comment by Thyriel** [comment]
Now that you ask, yes NEI and the item panel is set to NEI too in the options. If i change it to JEI Ctrl+A works (but somehow i'd find NEI interface more handy because of the setable cheating amount) 
So the problem is on NEI sides ?

**Comment by mezz** [comment]
Yes, please do not report bugs here until you have removed NEI, it's in the text when you write a new issue :/

>Remove NEI and FEI to see if they are causing the issue before reporting.

https://github.com/TheCBProject/NotEnoughItems/issues

**Comment by VT-14** [comment]
> Would make it much faster entering something new

If all you want to do is clear the previous search, then I'm fairly certain that right clicking the search box does that (and selects it so you can start typing).
