### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by KappaKiddie** [mezz/JustEnoughItems#757]
Crash log: https://gist.github.com/KappaKiddie/2a98e4d5e0356d84c71f8de3f3c1d15d

**Comment by way2muchnoise** [comment]
Seems to be Just Enough Tooltips, try removing that. See`me.superckl.jet`

**Comment by mezz** [comment]
Thanks for the report!
Please report here to Just Enough Tooltips: https://github.com/superckl/JustEnoughTooltips/issues
