### ISSUE TITLE
Client crash on search

### ISSUE THREAD

**Issue by Gunner76th** [mezz/JustEnoughItems#759]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.
[crash-2017-03-06_22.47.06-client.txt](https://github.com/mezz/JustEnoughItems/files/823318/crash-2017-03-06_22.47.06-client.txt)
When opening the the Inventory screen by pushing E, the client crashes and generates the above crash report.

**Comment by mezz** [comment]
Thanks for the report!

From the issue template:
>Remove NEI and FEI to see if they are causing the issue before reporting.

**Comment by Gunner76th** [comment]
The issue is intermittent. Some players are reporting that not making any changes and simply starting their clients back up  allows them to play. Due to the fact that both JEI and NEI are in the stack trace, and both of the most recent releases of both mods are being used, I have posted this to both gits. This is for the pack SkyFactory 3 as created by Bacon_Donut and officially hosted on Curse/FTB

**Comment by Gunner76th** [comment]
We still have it (NEI) enabled on the server, however some players have it disabled while others have it enabled and the players seem to be able to play currently.

**Comment by covers1624** [comment]
NEI issue mezz, close.
