### ISSUE TITLE
Refresh Recipes

### ISSUE THREAD

**Issue by MisterShawn** [mezz/JustEnoughItems#76]
Is there a way to have recipes be refreshed? I thought for the longest time MineTweaker wasn't working until I realized that the recipes in JEI were still the cached versions. Thanks.

**Comment by mezz** [comment]
I'm working with MineTweaker to have better integration.
For now there is a workaround. Recipes are refreshed whenever the JEI in-game config is changed. You can turn on cheat-mode, exit the config, and then turn it off again.

**Comment by MisterShawn** [comment]
Great to hear and thanks! Keep up the great work and I applaud your commitment to keeping JEI lightweight and fast.

**Comment by Prospector** [comment]
Could you make F5 refresh the recipes?

**Comment by mezz** [comment]
I have added a method to reload JEI in the API. https://github.com/mezz/JustEnoughItems/commit/9dbac3fefd2b20b26621ec0029c7056f602a467b
Minetweaker will use it soon https://github.com/jaredlll08/CraftTweaker/issues/4#issuecomment-168991914

So you should never have to manually refresh JEI, it will just work.
