### ISSUE TITLE
JEI increased modpack load time

### ISSUE THREAD

**Issue by Crowley723** [mezz/JustEnoughItems#761]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Update to the latest version of Forge, it should fix the issue.

**Comment by Crowley723** [comment]
awesome thanks :D Ill do that now

**Comment by mezz** [comment]
Did that fix the problem?

**Comment by Crowley723** [comment]
Yes but when i updated the pack, the game cant see my ssp world so I had to downgrade.
