### ISSUE TITLE
[Request/Suggestion] Dependencies

### ISSUE THREAD

**Issue by VallenFrostweaver** [mezz/JustEnoughItems#762]
Is it much to add in the dependencies when you u/l to Curseforge? Each time I update I then have to reload the modpack 3 times to also add in a new version of JEI and then The One Probe. It would be nice is all. Feel free to close this.

**Comment by TehNut** [comment]
JEI doesn't have any dependencies

**Comment by VallenFrostweaver** [comment]
OMG. I meant to put this on Immersive Engineering's github. XD
so embarassed...
Please forgive me. Ugh.
