### ISSUE TITLE
Empty ItemStack Crash

### ISSUE THREAD

**Issue by GeekBeam** [mezz/JustEnoughItems#764]
was looking up uses for Garnet from TechReborn when this occured, not sure if it's due to TecchReborn or my habit of quickly typing multiple keys in quick succession to get an action done, resulting in things moving too fast.

crash log pointed to JEI so I'm putting it here.

https://gist.github.com/GeekBeam/b1aa9a7207555142e0828ee3ad728b61

**Comment by mezz** [comment]
Thanks for the report!
Which GUI did you have open when you looked it up?
Where did this garnet come from, was it from the creative menu, JEI item list, or some other place?

**Comment by GeekBeam** [comment]
all was from Crafting Table GUI, then looking up uses (U key) of the Garnet from TechReborn mod, U key on Garnet already extant in the Inventory. can't get much more accurate than that sadly.

**Comment by mezz** [comment]
I added some extra checks in JEI version 4.2.8.244, if you crash again with it please paste the new log here.

**Comment by GeekBeam** [comment]
@mezz new crash, was looking up uses for food items in the Cooking For Blockheads Cooking Table (the items are preview items) and got another "Empty Itemstack" crash.

https://gist.github.com/GeekBeam/8e8b91701cd1c6d201e0b640aa7dab85

**Comment by mezz** [comment]
I am still unable to reproduce this issue. I suspect there is another mod involved.
I added even more extra checks in JEI version 4.2.9.246, please try it out and let me know if you crash again.

**Comment by drakray** [comment]
EDIT; moved my thing to it's own

**Comment by mezz** [comment]
With the new logs I was able to pin down the problem.
It's caused by another mod (I don't know which) but I should be able to protect against it.
Try out JEI 4.2.10 when it has finished building, it should not be possible to crash this way any more.

**Comment by drakray** [comment]
I'd say mod that order inventory on keypress, like InventoryTweak(it happen with it to me)

**Comment by GeekBeam** [comment]
it's not due to inventory tweaker for me, sadly, I have no keybind for inventory sorting, just the button from Quark.

**Comment by drakray** [comment]
@GeekBeam are you crashing after clicking on Quark button? maybe the bug is not on keypress, but on sorting

**Comment by mezz** [comment]
JEI 4.2.10 should fix the issue no matter what mod is causing the problem. 
If you still crash please link the report here so I can look into it.

**Comment by GeekBeam** [comment]
no, I crash at random while looking up recipes, not while pressing the sorting button, which isn't an available button to press in the locations I _have_ crashed.

**Comment by mezz** [comment]
Please link the report here so I can look into it.

**Comment by GeekBeam** [comment]
was trying to reply to @drakray , sorry, I am quite sure that inventory sorting isn't what's causing these crashes.

**Comment by mezz** [comment]
If you're using JEI and it is crashing for any reason at all, please update to version 4.2.10 and link the new crash report here so I can look into it.

**Comment by GeekBeam** [comment]
I now have MORE information! @mezz 

new crash report (Empty Itemstack): https://puu.sh/uJavl/c9452e17ed.txt
whole buncha errors seconds before the crash occurred: https://puu.sh/uJar2/286db8d3cc.txt (Includes recipe errors by BWM, and quark. I had been looking up these recipes a LONG time beforehand)

 **mayhaps there's an issue with "recipe history" that is causing this error?**

**Comment by mezz** [comment]
This crash is with JEI 4.2.8.244, please try with 4.2.10.
https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2392786
