### ISSUE TITLE
Crash when looking at Excavator in Anvil

### ISSUE THREAD

**Issue by drakray** [mezz/JustEnoughItems#766]
I got a crash, when pressing U on a SparkHammer Wooden Excavator
http://pastebin.com/3FZtfqkw

R on it work, show the custom recipe fram SH, but going on Anvil crash, always

**Comment by mezz** [comment]
Thanks for the report!
This is probably an issue with another mod, but I was unable to reproduce it with SparkHammer and JEI alone.
I will push a fix to JEI so that it catches the error and logs it instead of crashing completely.

**Comment by mezz** [comment]
Try with JEI 4.2.9 once it's out, in a few minutes.

**Comment by drakray** [comment]
trying live
It doesn't crash anymore, but I found that I can't enchant Sparkhammer stuff, as it crash when I try to put a book with a excavator/hammer, so fault on Sparkhammer
Also, Enchanting cost show err, probably your new way of catching the error/crash?
