### ISSUE TITLE
Crash ItemStack value must not be empty

### ISSUE THREAD

**Issue by drakray** [mezz/JustEnoughItems#767]
http://pastebin.com/eGZjV2xf

MC 1.11.2
Forge 2255
JEI 247

I think my crash is caused by a compat trouble with InventoryTweak, as I manage to force the crash by putting things with space between in my inventory, sorting and trying to U on something in a previously empty slot(last filled slot in inventory)

**Comment by mezz** [comment]
Thanks for the report!
You were right to report it in #764, it's the same issue.
Should be fixed in version 4.2.10

**Comment by drakray** [comment]
fixed indeed, could not reproduce my way to crash :)
