### ISSUE TITLE
JEI freezing Error, caused by Pam's Harvestcraft

### ISSUE THREAD

**Issue by GeekBeam** [mezz/JustEnoughItems#768]
new error in logs, did not cause a crash, but lagged me out of server with an internal Network Dispatch exception, occured while scrolling through uses for Pam's Harvestcraft Milk in JEI.

also reported to Pam's Harvestcraft Github Issues: https://github.com/MatrexsVigil/harvestcraft/issues/248

https://puu.sh/uJ6nK/816f8b2bd8.txt

**Comment by mezz** [comment]
Thanks for the report!
From the logs, this issue seems to be caused by Harvestcraft only.
