### ISSUE TITLE
Are potion recipes still supported in 1.11.2?

### ISSUE THREAD

**Issue by Lothrazar** [mezz/JustEnoughItems#769]
I have the latest version.  And my mod adds several potion recipes using the standard forge BrewingRegistry system.  In 1.10 all recipes were visible fine. but in 1.11.2, the potion recipes are still working functionally just fine but are not visible in 1.11.

Bug report from another user on my mod Cyclic

https://github.com/PrinceOfAmber/Cyclic/issues/284

My code using forge registry that is working fine, and it includes a unit test 
https://github.com/PrinceOfAmber/Cyclic/blob/35fc1ba716cac253cf99c14b412825dc181fcb0d/src/main/java/com/lothrazar/cyclicmagic/module/ItemPotionModule.java#L289

**Comment by mezz** [comment]
Thanks for the report!
They should still be supported, I don't think I changed anything from 1.10 to 1.11. I'll take a look when I get a chance.

**Comment by mezz** [comment]
I did some debugging and it looks like you are requiring `new ItemStack(Items.POTIONITEM)` as an input, which is the uncraftable potion. 
It should be a water bottle (which is `PotionUtils.addPotionToItemStack(new ItemStack(Items.POTIONITEM), PotionTypes.WATER);`
I'm not exactly sure why vanilla handles this as if it were a water bottle, but I'll look into it a bit more.

Screenshot from a hacked dev version which shows recipes that use uncraftable potions:
![2017-03-22_16 12 27](https://cloud.githubusercontent.com/assets/916092/24224819/8a5e4560-0f1a-11e7-9616-f2f71f6f32ed.png)

**Comment by mezz** [comment]
I pushed a fix since this works in a brewing stand, it should display correctly in JEI as well.

**Comment by Lothrazar** [comment]
Thanks so much!

**Comment by VallenFrostweaver** [comment]
@mezz This seems to still be happening in some instances. I have an example of Botania's Rod of the Sea and the Blood Magic Cutting Fluid where a bottle of water is supposed to be the "uncraftable potion" that is shows.  Images below. Version 1.11.2 - 4.2.11.251
![rod of the sea](https://cloud.githubusercontent.com/assets/13642054/24609629/671afe56-1873-11e7-855a-a84be5866786.png)
![cutting fluid](https://cloud.githubusercontent.com/assets/13642054/24609633/6959a1b8-1873-11e7-8242-8a7198c9276f.png)
