### ISSUE TITLE
Port to the 1.7.10 

### ISSUE THREAD

**Issue by Tsyklop** [mezz/JustEnoughItems#77]
Please port to the 1.7.10 this mod

**Comment by TehNut** [comment]
It's not possible. The hooks needed are not there.

**Comment by BBoldt** [comment]
1.7.10?

pfft

What about beta 1.7.3?!

**Comment by mezz** [comment]
It is technically possible to port this mod to 1.7.10, it only needs one event added by ASM.
I don't want to do that though, someone else can PR it if they want. 
Also I don't really want to support 3 different versions until I have automatic builds from jenkins to curse going.

**Comment by GirafiStudios** [comment]
I see no reason for a 1.7.10 port either. It would just be a waste of time tbh.

**Comment by JamesATeasdale** [comment]
i think a 1.7.10 port would be amazing; theres a lot of amazing mods built on that version that probably won't be updated to 1.8+. If not there's always NEI, it's a bit janky but that's a small price to pay if doing 1.7.10 too much work for you.

**Comment by mezz** [comment]
I don't think 1.7.10 mods are going to spend time to add JEI integration.
1.8+ is gaining a lot of steam lately, it's just a matter of time.
