### ISSUE TITLE
JEI shows invalid anvil recipe

### ISSUE THREAD

**Issue by KidsDontPlay** [mezz/JustEnoughItems#770]
JEI: 1.11.2 4.2.8.243

![19f313936574437869becd635f45d23b](https://cloud.githubusercontent.com/assets/13290261/23949114/4f5bd656-0986-11e7-9782-0107b1d117af.png)

(the book in the picture is Unbreaking.)
but the tool isn't enchantable in an anvil.
maybe you should check `Item.isBookEnchantable()`

**Comment by mezz** [comment]
Thanks for the report!
Should be fixed in the latest version.
