### ISSUE TITLE
Just curious if this is possible

### ISSUE THREAD

**Issue by Sunconure11** [mezz/JustEnoughItems#771]
If I make a plugin for JEI within my own mod, is it possible to hide a recipe entirely? I have no knowledge of coding JEI beforehand, I just want to know for future reference.

mainlyaneastereggrecipe

**Comment by mezz** [comment]
If you create an `IRecipe` that JEI doesn't know how to process, it will be effectively hidden.
JEI only knows the built-in vanilla and forge ones, like `ShapelessRecipes`, `ShapedRecipes`, etc. 
Just copy one of those classes to create your own secret `IRecipe`.
Any new `IRecipe` from mods needs to add a JEI handler for it to show up.
