### ISSUE TITLE
[Suggestion] Backport Anvil Recipe Handler from 1.11 to 1.10.2

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#772]
Just a quick one - I wrote it up for V-Tweaks pretty generically using mostly the code you'd already written for 1.11, but the one "problem" I'm having (or foreseeing) is that if everyone uses this method, you'll eventually run into a bajillion (exaggeration intended) different Anvil Tabs, Handlers and recipe lists.

Like I said, I've already got it running, I'd just love to see a unified solution!

**Comment by mezz** [comment]
Thanks for the suggestion!
Unfortunately in this case, I think a lot of the mods on that version are not being maintained actively and I don't think we will see a unified solution there. I would rather just move forward to 1.12 and higher.
