### ISSUE TITLE
Mods bar gets clicked when in chests

### ISSUE THREAD

**Issue by lunchboxxx19** [mezz/JustEnoughItems#774]
if im using a chest with a large GUI (think diamond chest from "iron chests mod") whenever i click the top line in the GUI it also clicks the "mods" bar at the top

can i move this bar somewhere else or disable it?

is there going to be a fix for it?

thanks in advanced

**Comment by TehNut** [comment]
That is added by NEI, not JEI.

**Comment by mezz** [comment]
Please report here: https://github.com/TheCBProject/NotEnoughItems/issues

**Comment by lunchboxxx19** [comment]
i dont have NEI

**Comment by mezz** [comment]
Can I see a screenshot? JEI only adds stuff to the right of the open gui, not above.

**Comment by lunchboxxx19** [comment]
http://imgur.com/a/kbH6Z

i forgot to mention i am using the latest 1.11.2 version

**Comment by mezz** [comment]
I'm not sure which mod adds the Mods button but it is not JEI, sorry.
None of the buttons on the top left, the save inventory features, or the Mods button are from JEI.

**Comment by lunchboxxx19** [comment]
hmmm. better go do some searching then. sorry for the mistake
