### ISSUE TITLE
JEI Incompatibility

### ISSUE THREAD

**Issue by BrendanatorX** [mezz/JustEnoughItems#775]
I am trying to make a personal modpack for my friends and I with JEI in it, my issue is that when i try to load a world, it says "Loading World" forever, but does not actually do anything, minecraft just goes dead and stops using cpu. Disabling JEI removes the issue but leaves me without JEI..

Can anyone tell me what incompatibilities there might be that cause this issue? at first I thought it was Immersive Engineering but that wasn't the case.. I have even tried older versions of JEI to no avail.

**Comment by BrendanatorX** [comment]
Edit: I have reopened this issue because I have found a very complicated web of incompatibility that should be made aware of.

I have discovered so far that the mods 
'Armory - Armoring the World'
'Armory - Weaponry'
'Enchanting Plus'
'Ender I/O'
'Just Enough Items'

These are what I have found so far in this web of incompatibility. disabling one of these mods seems makes the rest work fine together in my personal modpack, but all together with no other mods in the mix seems to still work. I will by process of elimination work out a few other mods and list them here.

**Comment by BrendanatorX** [comment]
It seems one mod that caused this issue that I had was called 'Good ol' PvP' and was a mod from 1.9 that remained technically working in MC 1.10.2.
Removing this has made the rest work, so I've done that to solve it.

**Comment by mezz** [comment]
Thanks for the report!
It looks like you are still investigating.
Using the fewest mods possible, please run the game, wait a little, and then upload your `fml-client-latest.log` to https://gist.github.com/ and link it here, I can take a look.

**Comment by BrendanatorX** [comment]
Do you mean with the mod that broke everything installed?

**Comment by mezz** [comment]
I need the log when you are seeing it broken (it says "Loading World" forever).
Ideally, I want the log when you have removed as many mods as you can while still showing it broken.

**Comment by mezz** [comment]
Somehow I didn't see your last reply showing that it was a 1.9 mod issue, nevermind. 

If this is resolved, please close the issue.
