### ISSUE TITLE
Recipies still showing up in JEI after removal with CraftTweaker & ModTweaker

### ISSUE THREAD

**Issue by bookerthegeek** [mezz/JustEnoughItems#779]
### Relevant Mods list:
 - Minecraft 1.10.2
 - jei_1.10.2-3.14.7.416
 - CraftTweaker-1.10.2-3.0.24
 - ModTweaker2-2.0.10
### Secondary Mods
 - TConstruct-1.10.2-2.6.3
 - TConstruct-1.10.2-2.6.3
 - forestry_1.10.2-5.2.17.368
 - embers-0.104
 - Botania r1.9-341
 - ImmersiveEngineering-0.10-57
##### Scroll down for scripts
| Base Mod | Before | After |
| ------------ | ------------- |  ------------- | 
| Vanilla | ![normalVanilla][1] | ![scriptVanilla][2] |
| Tinkers Construct | ![normalTC][3] | ![scriptTC][4] |
| Forestry | ![normalForestry][5] | ![scripForestry][6] |
| Embers | ![normalEmbers][7] | ![scriptEmbers][8] |
| Botania | ![normalBotania][9] | No picture, was removed |
| Immersive Engineering| ![normalIE][10] | No picture, was removed |

### Scripts used 

````
// Vanilla
recipes.removeShaped(<minecraft:stone:6>, [
   [<minecraft:stone:5>, <minecraft:stone:5>, null],
   [<minecraft:stone:5>, <minecraft:stone:5>, null], 
   [null, null, null]]);

// Tinkers Construct
mods.tconstruct.Casting.removeTableRecipe(<minecraft:iron_ingot>, <liquid:iron>, <tconstruct:cast_custom>);

// Forestry
// Recipe calls for <ore:logWood>, that is why they are different in the picture
mods.forestry.Carpenter.removeRecipe(<forestry:impregnatedCasing>, <liquid:seed.oil>);

// Embers
mods.embers.Mixer.remove(<liquid:dawnstone>);

// Botania
mods.botania.PureDaisy.removeRecipe(<minecraft:obsidian>);

// Immersive Engineering
mods.immersiveengineering.MetalPress.removeRecipeByMold(<immersiveengineering:mold>);
````
So, don't know if this helps or just raises more questions. Thought you should have a decent breakdown of what is happening.

All scripts were run through Game Load (No /mt reload), no errors are thrown. All the removals worked, the crafting did go away, they just still show up in JEI. Might be a good idea to ask @jaredlll08 his opinion. (Also that way I don't have to remake this over on the other github. Centralize the issue if you know what I mean.)

[1]:http://i.imgur.com/JkpZcg7.png
[2]:http://i.imgur.com/3sxE0NK.png
[3]:http://i.imgur.com/cxPFAJO.png
[4]:http://i.imgur.com/54rmYO1.png
[5]:http://i.imgur.com/4IofZgw.png
[6]:http://i.imgur.com/XuKJb67.png
[7]:http://i.imgur.com/oC4LF5S.png
[8]:http://i.imgur.com/hR8rKES.png
[9]:http://i.imgur.com/NWnAjZr.png
[10]:http://i.imgur.com/bIEPd47.png

**Comment by AEnterprise** [comment]
there have been some changes to integration so when other mods add their own recipes to JEI but those change due to a script later those mods have to notify JEI: remove the old recipe and add in the new one, most likely not all mods have done that change

**Comment by jaredlll08** [comment]
Yea, this is on crafttweaker's side, a lot of the issues you mentioned have
been fixed in dev though, so hopefully next release all will be working well

**Comment by bookerthegeek** [comment]
Gotcha. Looking forward to the next release then.
