### ISSUE TITLE
Missing Aroma1997Core Recipes

### ISSUE THREAD

**Issue by MisterShawn** [mezz/JustEnoughItems#78]
I'm not sure if it's a JEI issue, or how Aroma1997 assigns recipes for BetterChests, but none of the recipes are showing up. I found some, but not all, of the recipes online and I'm able to craft them just fine. I tested it with a clean forge 1.8-11.14.4.1577 and only JEI, Aroma1997Core, and BetterChests.

http://minecraft.curseforge.com/projects/aroma1997core/files
http://minecraft.curseforge.com/projects/betterchest/files

**Comment by mezz** [comment]
Looks like they have their own custom recipe types.

I could add support in JEIAddons or send them a PR.

**Comment by MisterShawn** [comment]
I'm not a programmer, but I wanted to contribute in some way and so I made these Minetweaker recipes for BetterChests: http://pastebin.com/aR93kF8b

**Comment by modmuss50** [comment]
@sdaddy thats not the issue, the recipes are added but JEI didn't have support for the way they were added. This appears to have been fixed with the last commit.

**Comment by Prospector** [comment]
I think the minetweaker script was to make the better chests recipes
vanilla ahaped/shapeless recipes, therefore working with jei. But yes, it's
unnecessary now.

**Comment by MisterShawn** [comment]
The way I read the notes at the bottom of the commit was that mezz still needed Aroma1997 to add support for JEI. BetterChests hasn't been updated in 8+ months so I didn't feel confident that it would be changed soon. In any case, I got to learn Minetweaker a little more and broke in my new keyboard a bit.

**Comment by mezz** [comment]
I made the request to Aroma1997, but considering the gap in update times I will include it in JEIAddons.

**Comment by mezz** [comment]
Currently blocked by what seems to be a ForgeGradle bug: https://github.com/MinecraftForge/ForgeGradle/issues/315

**Comment by Aroma1997** [comment]
I also have deobfuscated versions prebuilt over here: http://files.aroma1997.org/mcmods/aroma1997core/version/

**Comment by mezz** [comment]
Thanks, that lets me get around the gradle issue for now.

Uploaded JEIAddons with Aroma1997Core support to curse, [you can get it here](http://minecraft.curseforge.com/projects/jeiaddons).
