### ISSUE TITLE
Crash while looking at the block list in the inventory

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#780]
hi , i have a problem with JEI

Im using a mod "armor plus" and when i change the pages of the list of blocks in the inventory , it crash at page 4

i really need help

thanks.

**Comment by mezz** [comment]
Thanks for the report!
[Please report the issue to ArmorPlus here.](https://github.com/TheDragonTeam/ArmorPlus/issues)
They will probably need a crash log as well.

**Comment by ghost** [comment]
Thanks :)
