### ISSUE TITLE
No XP from smelting dusts

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#781]
JEI tells me that one gets XP from smelting dusts, but I don’t get any XP, no matter what kind of furnace I use or what kind of dust I smelt.

I assume that this is a bug within Just Enough Items.

**Comment by mezz** [comment]
Thanks for the report!
Which mod's dusts are you having this issue with? I need to know so I can test it.

**Comment by ghost** [comment]
JEI tells me that one gets XP from smelting any kind of dust when looking at the usage of the dusts, but that’s not the case, because I don’t get any XP from smelting any kind of dust.

**Comment by mezz** [comment]
Please give an example of a dust where this happens so I can test it.

**Comment by ghost** [comment]
It happens with all dusts. JEI says that you get XP from smelting any kind of dust that you look up in-game, but you don’t actually get any XP.

**Comment by mezz** [comment]
Please name one mod that you are using that adds dusts so I can test it.

**Comment by ghost** [comment]
Immersive Engineering and IndustrialCraft 2, for example.

**Comment by mezz** [comment]
Tested with Immersive Engineering and I got experience when I smelted dusts and then pulled the ingots out of the furnace.

![2017-03-22_15 47 40](https://cloud.githubusercontent.com/assets/916092/24224185/00e39554-0f17-11e7-983e-9e457c8681b6.png)

**Comment by mezz** [comment]
I don't think this is an issue with JEI, it seems to be showing the right amount of XP.

**Comment by ghost** [comment]
Huh, you’re right. I do get XP from smelting Immersive Engineering’s dusts. I guess this is an issue with other mods, in that they forgot to implement the XP reward or intentionally omitted it for whatever reason.
