### ISSUE TITLE
[1.10.2] Furnace Recipe Crash

### ISSUE THREAD

**Issue by MokahTGS** [mezz/JustEnoughItems#782]
http://pastebin.com/a57exWzg

Getting this crash looking up recipes in the furnace.

**Comment by mezz** [comment]
Thanks for the report!
Do you crash when smelting some things? It looks like some mod has broken the smelting recipes.

**Comment by MokahTGS** [comment]
No way to know...there are hundreds of mods.  It crashes if I look up any item that has a furnace tab.  As soon as I click the tab...crash.

**Comment by mezz** [comment]
Do you crash when smelting some things in the vanilla furnace without looking up their recipes in JEI?

**Comment by MokahTGS** [comment]
I will check this and let you know.

**Comment by MokahTGS** [comment]
Well, so far everything is working for putting items into a vanilla furnace.  Tried iron and gold ore, vintium ore from Ars Magica, tin, electrum dust from Substratum, and ores from Thermal Foundation.  No crash.  Everything smelted as expected.

Moused over Iron Ore and pressed "U" and crash:  http://pastebin.com/MnPySfEg

**Comment by mezz** [comment]
Thanks for testing.
Is there somewhere I can download the pack you're using so I can debug the issue further?

**Comment by MokahTGS** [comment]
No its a private pack i put together.  Can you make a log of mods used
through the curse launcher?

**Comment by KnightMiner** [comment]
Curse allows you to export your mod list as a "pack" of sorts. Not sure exactly sure how it works, but I recall that feature existing.

**Comment by MokahTGS** [comment]
Well it's not perfect but maybe you can see something I don't.  There are Minetweaker scripts, and I'm wondering if that is the issue.

https://www.dropbox.com/s/rftiij7prijza45/DEV-Shards%20of%20Vertex-DEV-1.0.zip?dl=0

If I removed mods that the scripts are still calling, would that cause the crash?

**Comment by MokahTGS** [comment]
OK, this is beyond annoying as now everything is working.  I removed a bunch of recipes from scripts of mods I wasn't using and updated a few mods in the pack.

Thanks for helping.

I'm I weird at getting annoyed when things get fixed but I don't know what caused the issue in the first place?  At any rate, I'm closing this issue for now.  Grrrr...
