### ISSUE TITLE
Search when scroll to certain page or searching certain word

### ISSUE THREAD

**Issue by bigrice1018** [mezz/JustEnoughItems#784]
1.10.2 
jei_1.10.2-3.14.7.416 

[crash-2017-03-27_23.44.24-client.txt](https://github.com/mezz/JustEnoughItems/files/872950/crash-2017-03-27_23.44.24-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Please remove NEI before reporting.
If you still crash, post a new crash log here.

**Comment by bigrice1018** [comment]
fixed by downgrading InfinityLib [0.8.0 -> 0.7.0]
Thx for your help~

**Comment by mezz** [comment]
Thanks.
For reference to anyone else, the InfinityLib issue is here: https://github.com/InfinityRaider/InfinityLib/issues/20
