### ISSUE TITLE
[1.11 API] Any way to reload item filter at runtime?

### ISSUE THREAD

**Issue by Furgl** [mezz/JustEnoughItems#785]
I have a mod that allows items to be enabled/disabled at runtime via the in-game config and I'd like to have these items added/removed from JEI accordingly. I can add/remove them from the ingredient blacklist at runtime, but this does not update the items shown in JEI until Minecraft is restarted. Is there any way to reload the item filter at runtime, now that IJeiHelpers#reload is deprecated?

**Comment by mezz** [comment]
When you call `IIngredientRegistry#addIngredientsAtRuntime` the filter is reloaded.
I should add a similar method for removing at runtime.

**Comment by Astavie** [comment]
How is `IIngredientRegistry#removeIngredientsAtRuntime` coming along? I could also use that method by now...

**Comment by mezz** [comment]
@TheRActivator it already exists.

**Comment by Astavie** [comment]
@mezz Oh, I thought it didn't, seeing how this issue is still open

**Comment by mezz** [comment]
The reloading issue has been fixed in version 4.4.0.
The list will automatically update when ingredients are added or removed at runtime.
