### ISSUE TITLE
JEI says that magma blocks require Silk Touch to be harvested

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#787]
Magma blocks don’t require Silk Touch.

![jei bug](https://cloud.githubusercontent.com/assets/25916106/24432804/d1d22312-1424-11e7-8b2a-ee1be161b2ad.png)

**Comment by TehNut** [comment]
This is a feature of [JustEnoughResources](https://github.com/way2muchnoise/JustEnoughResources).

**Comment by ghost** [comment]
Oh, my bad. [I’ve reported it there](https://github.com/way2muchnoise/JustEnoughResources/issues/111).
