### ISSUE TITLE
Suggestion / missing compatibly

### ISSUE THREAD

**Issue by Shazuli** [mezz/JustEnoughItems#789]
***Hi!***

I firstly wanted to say thank you for continuing the progress on **NEI (JEI)** for later versions of Minecraft as well improving and adding new features in a new fresh GUI.

This is a suggestion and not really a bug. I have installed your mod and a few others in a private pack I made, one of those mods are **Engineers Workshop** *"https://mods.curse.com/mc-mods/minecraft/254916-engineers-workshop"* version 1.2.0-1.10.2 for Minecraft version 1.10.2.
You have implemented, while inside a Crafting table, a **shift-click** feature to fast complete a recipe from items in the players inventory. JEI doesn't recognize Engineers Workbench as a valid crafting station and don't offer the button.
I haven't seen a addon for either your mod or for EW mod. I would really appreciate if you could look into this and maybe do a patch in a future version of JEI. I don't want to force you to do anything but I would really appreciate it you could.

**Comment by liach** [comment]
You should ask that mod not JEI...

**Comment by mezz** [comment]
Thanks.
JEI does not add mod support, each mod adds their own support to JEI.
There is an open issue for the feature here: https://github.com/EngineersMods/EngineersWorkshop/issues/18
