### ISSUE TITLE
Collected issues from Fluidstuff

### ISSUE THREAD

**Issue by bonii-xx** [mezz/JustEnoughItems#79]
Copy of what I said on IRC so you don't lose it ;)

1) how do I display non-tank fluid output (as in, no upper bound)
2) if the fluid output overfills the output it renders completely white when hovering for some reason (http://imgur.com/rBi0oZP)
3) overlays are rendered with the same color the fluid has. is missing a setColor(1f,1f,1f,1f) before rendering the overlay over GuiFluidStack overlays
4) fluids need a minimum rendering height http://imgur.com/pQgG7if
5) 2) also happens with non-full fluids it seems. Possibly when the fluid used has a fully opaque color?

clicking on a fluid doesn't show my melting and alloying recipies :(
When clicking on a fluid in JEI, the following happens:
Focus.getOutputCategories gets passed an Itemstack containing the fluid
and a fluid of null
and therefore tries to get recipies that return an itemstack containing the fluid as output
instead of recipies returning the fluid

**Comment by mezz** [comment]
>clicking on a fluid doesn't show my melting and alloying recipies

I assuming you have some kind of fluid itemStack in the item list? I don't think those exist by default, there isn't one for lava or water.
JEI will correctly handle the fluid inside an Item if it's a `IFluidContainerItem` or responds to `FluidContainerRegistry.isFilledContainer(ItemStack)`

**Comment by mezz** [comment]
Not completely fixed yet, still getting the white highlight issue when testing with TechReborn.
Doesn't seem to have to do with the fluid level, not sure what it is yet.

**Comment by mezz** [comment]
Yay, fixed. It was OpenGL hell. 

I found that the following methods leave OpenGL blend on:
- `GuiButton.drawButton` 
- `GuiContainerCreative.func_147051_a` (disables later in `drawGuiContainerForegroundLayer`?) 
- `GuiUtils.drawContinuousTexturedBox`
- `RenderItem.renderItemIntoGUI`
