### ISSUE TITLE
OptiFine causes some weird issues with JEI

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#790]
When I hover over an item in a JEI GUI, the sky changes contrast and becomes darker, and when I move my cursor away from the item, the contrast changes back to what it should be.

# Screenshots

### Good sky; before hovering my cursor over an item
![2017-04-01_08 27 14](https://cloud.githubusercontent.com/assets/25916106/24576059/0fd86b16-16b5-11e7-9df3-a601beb78e4f.png)

### Bad sky; whilst hovering my cursor over an item
‘![2017-04-01_08 27 26](https://cloud.githubusercontent.com/assets/25916106/24576058/0fd4bd54-16b5-11e7-8fed-faabd3896612.png)

I think that this is because I’ve [OptiFine](http://optifine.net/home) installed.

**[Minecraft](https://minecraft.net/) version:** 1.10.2
**[Forge](https://files.minecraftforge.net/) version:** 12.18-3-2254 (latest for MC 1.10.2)
**[OptiFine](http://optifine.net/) version:** OptiFine 1.10.2 HD U D7 (latest for MC 1.10.2)
**[Just Enough Items](https://minecraft.curseforge.com/projects/just-enough-items-jei) version:** 3.14.7.416 (latest for MC 1.10.2)

**Comment by mezz** [comment]
Please report this to Optifine:
https://github.com/sp614x/optifine/issues
