### ISSUE TITLE
Crash/Game Won't Start After Updating from .251 to .254

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#791]
please help. thanks
[crash-2017-04-04_17.14.03-client.txt](https://github.com/mezz/JustEnoughItems/files/893391/crash-2017-04-04_17.14.03-client.txt)

**Comment by Videonauth** [comment]
Same happens on my side:

https://pastebin.com/1i1e4WyW

**Comment by way2muchnoise** [comment]
`at.feldim2425.moreoverlays` seems to be some compat issue with more overlays, you might wanna update that

**Comment by way2muchnoise** [comment]
@Videonauth different crash from @kenijey tho.  @kenijey's seems to be related to `java.lang.NoClassDefFoundError: mezz/jei/util/FakeClientPlayer`

**Comment by Videonauth** [comment]
Yes sorry i just looked at the header of this issue, and for me as well as for kenijey its that our game crashes with this newest version (i.e. after upgrading). Needless to say I'm using the latest version of More Overlays already and there's no option to upgrade to.  So instead of creating a second issue thread i posted here to not create duplicates.

**Comment by way2muchnoise** [comment]
@Videonauth for you the solution is to wait from updating JEI untill More Overlays fixes the issue, you should go and report it on their issue tracker.

**Comment by ghost** [comment]
is that solution same with me

**Comment by way2muchnoise** [comment]
No @kenijey yours seem to different from that, you'll have to wait for @mezz to take a look at it.

**Comment by ghost** [comment]
ok. hi mezz. if you r reading this comment, assume that i gave you a hug.

**Comment by mezz** [comment]
Thanks for the report!
The next version of JEI (.255) will catch this error and print a log showing which plugin is crashing, so we can report it to them. 
Please try it out and paste the `fml-client-latest.log` to https://gist.github.com/ and link it here.

**Comment by ghost** [comment]
hi mezz, i installed .256, here its crash https://gist.github.com/kenijey/716bbef5feb9e79c0085ccdb51003113

**Comment by mezz** [comment]
Thanks kenijey, we can now see that the crash is caused by BlockDrops.
This crash has been reported here: https://github.com/MrRiegel/BlockDrops/issues/28

**Comment by ghost** [comment]
oh okay
