### ISSUE TITLE
"R" and "U" become offset after changing window size

### ISSUE THREAD

**Issue by quat1024** [mezz/JustEnoughItems#792]
My monitor is 1280x1024 and I usually play 1280x720 windowed. I discovered this bug after I clicked Maximize.

* Open Minecraft
* Hover over items in the recipe list and press R
* The recipe that appears is the correct recipe.
* Resize the window.
* Hover over an item in the recipe list and press R.
* The recipe that displays is for something else.

http://i.imgur.com/kuSF0Zn.png

Oddly enough this doesn't affect left- and right-*clicking* on items to view their recipes and uses; only the R and U keys do this.

JEI 4.3.1.254 for Minecraft 1.11.

**Comment by mezz** [comment]
Thanks for the report!
That's pretty weird, I'll take a look.

**Comment by mezz** [comment]
Confirmed and fixed in the next version (4.3.1.256).
