### ISSUE TITLE
Compatibility issue with Block Drops plug-in.

### ISSUE THREAD

**Issue by Zarepheth** [mezz/JustEnoughItems#793]
I'm not sure whether the issue is with the [Block Drops](https://github.com/MrRiegel/BlockDrops/issues/28) JEI plugin or JEI itself, so I'll cross post this for both.

As the game attempts to load, I receive a LoaderExceptionModCrash exception which crashes the game to the desktop before I can even load a world. It seems to be related to the "mezz/jei/util/FakeClientPlayer" object.

Game Log with crash report: [paste.ee](https://paste.ee/p/kHJUY)

The crash only happens with newer versions of JEI - 4.3.1.255, 4.3.0.252. I can avoid it with 4.2.11.251.

**Comment by TehNut** [comment]
This is caused by Block Drops

**Comment by mezz** [comment]
Thanks for the report!
I refactored JEI and it looks like they are using its internal classes, they will need to point to the new location.
