### ISSUE TITLE
The | (or) operator in highlighting mode (yellow searchbox)

### ISSUE THREAD

**Issue by jamzam90** [mezz/JustEnoughItems#794]
The first item in a when using the or operator in the yellow search box is highlighted yet item after the or is not. For example in the yellow search box, I've typed in book | lever and looked in a chest, the book is highlighted but the lever in the same chest is not.

**Comment by mezz** [comment]
Thanks for the report!
The yellow inventory search feature is not actually added by JEI, it's hacked in by an addon.
It may be More Overlays or NEI depending on what you have installed.
NEI issue tracker is here: https://github.com/TheCBProject/NotEnoughItems/issues
More Overlays issue tracker is here: https://github.com/feldim2425/MoreOverlays/issues

**Comment by jamzam90** [comment]
I did not realize that jei didnt have that feature.
