### ISSUE TITLE
Crash on Dedicated Server

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#795]
using latest JEI... 
[crash-2017-04-06_12.42.11-server.txt](https://github.com/mezz/JustEnoughItems/files/902138/crash-2017-04-06_12.42.11-server.txt)
please help... thanks

**Comment by ghost** [comment]
and if i shouldn't install JEI to the server side, please forgive me :D

**Comment by ghost** [comment]
omg, it is xd

**Comment by canitzp** [comment]
JEI isn't only a singleplayer mod, so you should reopen it.

**Comment by ghost** [comment]
really? but it works while no JEI installed on dedicated server side if someone joined to the dedicated server too

**Comment by canitzp** [comment]
JEI does work client side only, but it has a packet handler, so it can send packet, but I don't know for what. I would expect that things like the cheat mode requires the server side, but I'm not sure

**Comment by way2muchnoise** [comment]
For the item cheating it also needs some server side things.

**Comment by ghost** [comment]
i will never use cheating, so should i install it on server side? all i want is see the item recipes.

**Comment by way2muchnoise** [comment]
Then there is no need for it on the server side.

**Comment by ghost** [comment]
ok...

**Comment by TehNut** [comment]
Ingredient placement using Shift-click requires it on the server.

**Comment by way2muchnoise** [comment]
Well that makes sense, totally didn't think about that one.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.
