### ISSUE TITLE
Crash when viewing recipe from Baubles Stuff

### ISSUE THREAD

**Issue by Liiw** [mezz/JustEnoughItems#796]
Hello!

I have experienced a client crash when trying to view a recipe of the Book of Spells from Baubles Stuff. This happened on a modded Spongeforge server. Here is the crash report:

[crash-2017-04-07_00.16.40-client.txt](https://github.com/mezz/JustEnoughItems/files/903989/crash-2017-04-07_00.16.40-client.txt)

**Comment by mezz** [comment]
Thanks for the report
This looks like a crash from JustEnoughResources. Please report here:
https://github.com/way2muchnoise/JustEnoughResources/issues
