### ISSUE TITLE
Splash Screen Bug in 1.11.2 Release

### ISSUE THREAD

**Issue by cyberpunkbln** [mezz/JustEnoughItems#801]
Hello,

after a long search time i have found the Issue that i have searched. 

[https://github.com/mezz/JustEnoughItems/issues/538](url)

Disable the Forge-SplashScreen will solve this Issue but in the 1.10.2 Releases it looked be fixed. Yes the SplashScreen are not so imported, but i like the SplashScreen:).

Is it possible to put that Fix from Fixed JEI 3.13.0.339 in one of the jenkins Builds for 1.11.2?

thx

**Comment by mezz** [comment]
Thanks for the report!
We had a longer discussion about this issue later in issue #746 which concluded in a fix in Forge.
cpw made the fix in Forge 1.10 but didn't apply it to 1.11 Forge. I just poked him and it should get updated soon.

**Comment by cyberpunkbln** [comment]
Hello,
thx for that.
