### ISSUE TITLE
how to make it show all possible recipes

### ISSUE THREAD

**Issue by hunnybunny21** [mezz/JustEnoughItems#802]
jei_1.11.2-4.2.10.248

how to make it show all possible recipes
in the screen shot it shows all possible recipes for lapis

but in my game it only shows how to get lapis

i want to see all  thing i can do with lapis(things i can combine it with to get something else)

my game only shows lapis output 
no recipes that has lapis as an input

lapis is only an  example 
its true for all items

**Comment by TehNut** [comment]
Hover over the item and either right click or press "U"

**Comment by hunnybunny21** [comment]
right click worked
thanks
