### ISSUE TITLE
Arrow cutting off when viewing Blood Magic for sigil recipes

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#803]
![jei blood magic compatability bug](https://cloud.githubusercontent.com/assets/25916106/24879349/e50329ce-1e36-11e7-81ce-978897628208.png)
****
**Minecraft version**: 1.10.2
**Just Enough Items version**: 3.14.7.417
**Blood Magic version**: 2.1.9-78

**Comment by way2muchnoise** [comment]
Every mod does their own integration for JEI, you should report it to the [Blood magic tracker](https://github.com/WayofTime/BloodMagic/issues).

Also I think that arrow is supposed to be like that.

**Comment by TehNut** [comment]
This isn't a bug.

**Comment by ghost** [comment]
@way2muchnoise Oh, I’d no idea. I’ve done that: WayofTime/BloodMagic/issues/1124.

@TehNut What is it, then? A feature?
