### ISSUE TITLE
Item interface randomly disappears when using.

### ISSUE THREAD

**Issue by PengyN15** [mezz/JustEnoughItems#805]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by PengyN15** [comment]
My interface of items randomly disappears when I'm playing MC. I found out that JEI is still active, even though the interface is not there. I can still access recipes & uses, but not the interface. Could you fix this?

**Comment by TehNut** [comment]
The toggle (by default) is `CTRL+O`. Are you accidentally pressing that? Also, what is your mod list?

**Comment by jhrldev** [comment]
Same happened with me after a restart (not randomly dissapeared), `CTRL+O` has no effect, it looks like extrautils2 issue, pls post the log and I can figure if my issue is related.

**Comment by mezz** [comment]
@JonathanxD feel free to make a new issue with your log. If we eventually find out this one is a duplicate we can close it.
