### ISSUE TITLE
JEI crashes when searching (1.10.2)

### ISSUE THREAD

**Issue by davidlud** [mezz/JustEnoughItems#808]
Not sure what is going on, been playing on my modpack for awhile, but now suddenly anytime I search for something in JEI my game crashes (doesnt happen if I @ a mod)

Heres the paste bin

[https://pastebin.com/uDDB2nt8](url)

**Comment by mezz** [comment]
Thanks for the report!
Please try with the latest JEI version for 1.10, which is 3.14.7.417. 
It should create a more informative report when you crash, please link it here.

**Comment by Xellik** [comment]
Not the same poster, but I am also having a crash issue with the latest version. 

Heres the pastebin: https://pastebin.com/DXVsqqEL Crashes anytime I search for any item

**Comment by mezz** [comment]
@Xellik please make a new issue.
