### ISSUE TITLE
Apparently JEI is required for NEI, but it crashes when i use them together.

### ISSUE THREAD

**Issue by Cloudninjakip** [mezz/JustEnoughItems#809]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by way2muchnoise** [comment]
Versions of minecraft, forge, JEI and NEI would be nice. And the crash log, cause now this issue is kinda useless.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to the NEI issue tracker, they will be able to help: https://github.com/TheCBProject/Feedback/issues
