### ISSUE TITLE
Add a way to jump from a machine gui to recipes for that machine

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#81]
It's useful to see what recipes a machine can make.
There should be a button of some kind, and a hotkey.

**Comment by Prospector** [comment]
I'm thinking T, because it's between R and U, plus nobody uses T.

What if you made the machine names click able like in the JEI recipes.

**Comment by modmuss50** [comment]
In TechReborn we added a button to open nei, the only issue with it was that sometimes there wasnt a lot of room to put it. A little widget coming of the side of the gui would fix that issue.

**Comment by Prospector** [comment]
There's already a lot of widgets on the sides in a lot of TE/Forestry
machines--widget should be on bottom. Never seen anything pit there before.
Put a little JEI logo down there and your good.

**Comment by modmuss50** [comment]
In the api, the mod author should be able to say where it goes, but I like the idea of the bottom.

**Comment by Prospector** [comment]
Do tech reborn machines have the machines process text in the GUI (like a crafting table says Crafting, and a furnace says Smelting?)

**Comment by Prospector** [comment]
The text could also be made clickable

**Comment by modmuss50** [comment]
If you mean the tile of the machine yes, otherwise I dont think they do without looking.

**Comment by ColinGBos** [comment]
I'd be comfortable with pretty much anything, I like the idea of a rectangle of the screen that creates an imaginary button like NEI has. If it's possible to move around so that it can be placed over an actual drawn button that would be handy but I think defaulting to where the container/gui name is drawn would be fine.

**Comment by mezz** [comment]
I'm leaning towards adding a very small button, like the [+] button on the recipes. Maybe with an R on it for Recipes.

**Comment by ColinGBos** [comment]
I'm definitely not opposed to that idea, if we could have control over where it draws on the gui that would potentially be nice.

**Comment by mezz** [comment]
I ended up adding clickable gui areas like the ones in NEI, since that's what people are used to. They also don't clutter up guis or get in the way at all.

**Comment by ColinGBos** [comment]
And it still leaves room the the mod author to draw whatever they like there if JEI is installed (EnderIO with nei for example) I think this is the right way to go.

**Comment by codefaux** [comment]
My problem with this implementation is that some mods have not historically supported this option. Please also implement a player-bindable hotkey, _even if it defaults un-set_, so that those of us who notice the flaw in this design can work around it. It's been four years.

**Comment by mezz** [comment]
@codefaux can you open a new issue, requesting a hotkey?
If a mod doesn't support this though, there isn't a way for JEI to know how it should work. If you are working with a mod that doesn't support this feature, please request it from them.
