### ISSUE TITLE
JEI 4.3.1xxx crashes on launch logs attached

### ISSUE THREAD

**Issue by Benedictum** [mezz/JustEnoughItems#812]
I am trying to get NEI/JEI to play nicely in a new 1.11 modpack. NEI has a 4.3.1 prereq for JEI, but any version of 4.3.1 I try crashes, with or without NEI present.

https://gist.github.com/Benedictum/61b34fa3c710f816e10ba16ecd1c09a0 , https://gist.github.com/Benedictum/2f87669fa731398363d7848987bdf0f1 , https://gist.github.com/Benedictum/5053c413cb64395267b3011eb63824c6

**Comment by TehNut** [comment]
More Overlays is causing the crash. Try updating that. If you're on the latest version, you'll have to wait for them to update.

**Comment by mezz** [comment]
The More Overlays issue is here: https://github.com/feldim2425/MoreOverlays/issues/24
It looks like they have recently fixed it.
