### ISSUE TITLE
[Suggestion] Mod List

### ISSUE THREAD

**Issue by simpson409** [mezz/JustEnoughItems#814]
Whenever i get into a new pack i have a difficult time finding out about mods that i haven't played with before, sure i can go through the mod folder or scroll through thousands of items, but i think my idea might be better.

at the top where you have the page indicator, "<" and ">", you could have a button with an "M" for "Mod List" when you click on it you will see more buttons with the mod names, including minecraft. when you click on one of the buttons JEI will show all items of this mod.
I know the same can be achieved with the "@" symbol in the search bar, but i think seeing the mods that are in the pack would help players explore mods they haven't played with before.

**Comment by LuigiHutch** [comment]
Just click escape -> mods then you can find a mod list there

**Comment by simpson409** [comment]
but does it show the mods items in the JEI list if i do it this way? i want to click on the mod name once, have all the items of this mod there, be able to go to the recipes and go back to that list.
what i want is like a more convenient @ function,

**Comment by LuigiHutch** [comment]
Duplicate of https://github.com/mezz/JustEnoughItems/issues/163

**Comment by simpson409** [comment]
the other issues referenced in that post are not really what i'm looking for. let me try to explain it again, i want some sort of drop down list of mods (similar to what we had in NEI) but i don't want to use it to disable certain items or mods, instead i want to use it to only show items of the selected mod, it could even write down e.g. `@Forestry` in the filter. the mod option list is not very good for this use for 2 reasons, 
1st: it contains mods and libraries that add no items
2nd: its simply not as convenient
i think this would help to bring more exposure to lesser known mods in a pack
