### ISSUE TITLE
Most Of The Items Are Not Showing

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#815]
Using forge 2282, latest 1.11.2 JEI. Its my modpack magenji. 
![img_2876](https://cloud.githubusercontent.com/assets/24831406/25069995/e2a54d12-2299-11e7-94f3-64a90fde0b4b.JPG)
![img_2877](https://cloud.githubusercontent.com/assets/24831406/25069997/e2ddc08e-2299-11e7-8d70-495fd8458dbd.JPG)
![img_2878](https://cloud.githubusercontent.com/assets/24831406/25069996/e2d80a7c-2299-11e7-95e4-48de505ca676.JPG)

**Comment by way2muchnoise** [comment]
Considering in it says `See log`, what does the log say?

**Comment by ghost** [comment]
I will add today when i go home.

**Comment by ghost** [comment]
[fml-client-latest.txt](https://github.com/mezz/JustEnoughItems/files/924293/fml-client-latest.txt)
here the latest fml client log.

**Comment by mezz** [comment]
There seems to be a lot of errors caused by the `igcm` mod.
I don't see anything in the log about the tooltip issue, are you sure this is the log from the same run as the screenshots?

**Comment by ghost** [comment]
this log not same as the screenshots, this screenshots coming from another launch. before i post the logs, i look at the JEI interface again, same bug happened, then post the logs, didn't care the screenshots, didn't want to take screenshots again.(should i?)
IGCM... hmm...

**Comment by ghost** [comment]
And ah, i tried deleting IGCM, nothing different. this bug is happening again.. please help

**Comment by mezz** [comment]
new log please

**Comment by ghost** [comment]
okay coming

**Comment by ghost** [comment]
and, i should give information about this one; invisible items are from Minecraft Forge, Lost Eclipse, Modern Warfare and Mr Crayfish's Furniture mods.
[fml-client-latest.log.txt](https://github.com/mezz/JustEnoughItems/files/925119/fml-client-latest.log.txt)

**Comment by mezz** [comment]
Please try removing any optimization mods and visual effect mods like Optifine, BetterFPS, and shadersmod to see if they are involved.

**Comment by mezz** [comment]
It is getting late for me, but I will check back on this thread tomorrow.

**Comment by ghost** [comment]
i tried deleting tons of mods, still happening, then it started to crash; i leaved it as it is :D i'm tired.
it is not terrible, i can use it as it is :D ... until anybody help me about it
but, you can try my modpack to detect the problem ^^ it's [here.](https://www.technicpack.net/modpack/magenji.968153) hope you at least look at it :D ...

**Comment by ghost** [comment]
hi mezz, i found what causes the bug. This bug is happening when [Modern Warfare](https://minecraft.curseforge.com/projects/vics-modern-warfare-mod?gameCategorySlug=mc-mods&projectID=243788) mod is installed. However, the invisible items are on the **same page** with modern warfare's items. Non-modern warfare-item pages are fine. So any item from MW mod disrupts the hole page on JEI. Hope it helps, thanks.

**Comment by mezz** [comment]
Ok thanks. This is an issue on their side, please find a way to report it to them.

**Comment by ghost** [comment]
ok :(
