### ISSUE TITLE
JEI not working, 252+

### ISSUE THREAD

**Issue by drakray** [mezz/JustEnoughItems#816]
I have a problem: since updating past 4.3.0.252, I can't use U or R, nor ctrl+O t o use JEI
Anybody else got these trouble?

Minecraft 1.11.2
Forge 2282
Bunch of mods that worked until 251(inclusive)

**Comment by mezz** [comment]
Thanks for the report!
Please run the game, try to use U and R, save and quit, and then paste your `fml-client-latest.log` to https://gist.github.com/ and link it here.

**Comment by drakray** [comment]
[fml latest](https://gist.githubusercontent.com/drakray/d50c089653b5ca768e5927724b7be634/raw/ef62202d7f934ca67002108d8952e2c9cb6913b9/fml-client-latest.log)

**Comment by drakray** [comment]
as mentionned in #817 deleting config/jei folder seems to fix

**Comment by mezz** [comment]
Thanks, I'll mark this as a duplicate since #817 uncovered the cause of the problem.
