### ISSUE TITLE
JEI stops working after removing a mod

### ISSUE THREAD

**Issue by jhrldev** [mezz/JustEnoughItems#817]
JEI stops working after removing a mod that the block is in the search history.

MC: `1.11.2`
JEI: `4.3.2.264`
Forge: `1.11.2-13.20.0.2282` or `1.11.2-13.20.0.2270` (I only tested with these versions)

How to reproduce:

- Install JEI
- Install any mod that adds blocks or items (I used extrautils 2)
- Searches for the block of mod and disable JEI (`CTRL+O`)
- Remove the mod
- Start minecraft, and now, JEI does not work anymore even if you restart the minecraft

Workaround:

I fixed it removing `lookupHistory.zip` and changing the option `B:overlayEnabled` to `true` in `worldSettings.cfg` (I think that the last is enough to fix the problem).

`fml-client-latest.log`: https://gist.github.com/JonathanxD/fee5271e6a11589838ad28d66248672f

**Comment by mezz** [comment]
Thanks for the report!
After some testing, this looks to be unrelated to the recipe history. 
It's just not possible to re-enable JEI if it is disabled at startup. I'll create a fix shortly.
