### ISSUE TITLE
Color Search Not Working on any setting (Custom Pack and Sky Factory 3)

### ISSUE THREAD

**Issue by followmylogic** [mezz/JustEnoughItems#818]
Are there any mods that are known to cause this problem? I've tried on disabled, enabled, and require prefix with and without the prefix (so 6 attempts).

**Comment by mezz** [comment]
Thanks for the report!
Do you have NEI installed? If so, try removing NEI.

**Comment by mezz** [comment]
Closing this issue in favor of https://github.com/mezz/JustEnoughItems/issues/843
