### ISSUE TITLE
[Suggestion] Exclude search words

### ISSUE THREAD

**Issue by Discomanco** [mezz/JustEnoughItems#820]
A small request to get the possibility to exclude results with certain words.
Currently searching through Mekanism machines, and would like to hide all the factories (as they're essentially upgraded machines anyways, and not every machine has a factory), so I maybe could search something like: 

> @mekanism -factory

and it would show me everything from Mekanism, except items that includes the word "factory"

**Comment by VT-14** [comment]
For items you never want to see, there is a hiding option available in JEI's wrench menu.  I typically use it to hide things like AE2 facades and the majority of Chisel.

There are cases where a feature like this would be nice though.

**Comment by drakray** [comment]
in the same vein of feature, being able to use quote to find/exclude group of word could be nice(useful in large mod list)
