### ISSUE TITLE
Internal ItemBlacklist - expose in API for use by Forge Mods

### ISSUE THREAD

**Issue by radfast** [mezz/JustEnoughItems#821]
Hi there, I'm attempting to add blacklisted items to the ItemBlacklist from _inside_ a Forge mod.  Possibly I'm doing this the wrong way, but I don't see any exposure of the ItemBlacklist via the API?

1)   Please provide API access to ``` Internal.getHelpers()```

2)   Please provide API access to ```JeiHelpers.getItemBlacklist()``` for the correct JeiHelpers instance.

3)   Maybe also provide API access to ```ProxyCommonClient.starter.JEIStarter.hasStarted()``` - this one is especially a problem for mods because hasStarted() is not a static method and ```starter``` in ProxyCommonClient is private.

**Comment by TehNut** [comment]
`IModRegistry#getJeiHelpers().getItemBlacklist().addItemToBlacklist(...)`

**Comment by radfast** [comment]
ok thank you, dunno how I missed that.

>  maybe also provide API access to ProxyCommonClient.starter.JEIStarter.hasStarted() 

Any chance of this one?  At present I'm sometimes getting errors trying to getHelpers() / getJeiHelpers() before JEI started.

(closing this, because there is no issue, but if you can still take a look at that it would be great!)

**Comment by radfast** [comment]
Sorry to re-open this, but this doesn't seem to work.

```IModRegistry``` is an **interface** for plugins to implement, and I guess to make their own blacklists for plugin purposes.

I don't want to do that.

I want to add something to the general (**Internal**) blacklist used by JEI itself, because JEI is showing items from our mod which we don't want to be shown.  Double slabs, impossible items with missing textures, air blocks, blocks only used by our worldgen, etc.  NEI used to give us a way to hide all these, which we used.

It looks like the JEI API does not provide any way to do this.  Currently I'm achieving it using reflection, but shouldn't the API expose a way to do it?

---

Also: why doesn't JEI set 'hide items' to true by default?  Normal players don't want to see all the impossible / hidden / untextured items

**Comment by TehNut** [comment]
Register a plugin.

**Comment by mezz** [comment]
You can hide those items, no problem.
Here is the wiki page on how to do it: https://github.com/mezz/JustEnoughItems/wiki/Hiding-Ingredients

JEI does not hide items by default because that would require every mod to create a plugin just to "opt in" to showing their stuff.

I'm closing this but feel free to ask questions if you have any.

**Comment by radfast** [comment]
Thank you @mezz.  That's pretty clear, seems like coding a plugin is the only way to do this.  We're now working on that...
