### ISSUE TITLE
Page and item selector does not get resized on big screens

### ISSUE THREAD

**Issue by jhrldev** [mezz/JustEnoughItems#823]
When the screen is bigger, the JEI GUI becomes more "thinner", but page and item selector does not fit in new size.

Minecraft: 1.11.2
Forge: 13.20.0.2282
JEI: 4.3.2.264

Screenshots:
854x480: 
![2017-04-18_21 13 36](https://cloud.githubusercontent.com/assets/5360060/25158139/741b21d4-247c-11e7-9406-59b2dfd436f2.png)
1680x1050: 
![2017-04-18_21 13 39](https://cloud.githubusercontent.com/assets/5360060/25158147/83917c1c-247c-11e7-84c1-b7a0961a76ba.png)

**Comment by mezz** [comment]
Thanks for the report!
I think this is an issue with the texture pack you're using. 
The gui should not be any thinner, just taller.
