### ISSUE TITLE
GUI search bar is frozen

### ISSUE THREAD

**Issue by jordanasch** [mezz/JustEnoughItems#824]
I am having a problem with my GUI search bar, its stuck on a specific result. I can change it but it doesn't do anything to the item catalog, it just stays with the search results. I can still see the items in the catalog and get a recipe or uses for them its just like the search bar isn't connected to the catalog anymore.

You can see my search result stuck on water, it keeps the water catalog for each screenshot:
http://imgur.com/pD0kyfz
http://imgur.com/o3BYrhS
http://imgur.com/L92dN6Y

thanks for any help in advance!
Aschy

**Comment by mezz** [comment]
Thanks for the report!
Please remove NEI and see if that fixes the issue.

**Comment by jordanasch** [comment]
Ah, I am sorry I think I may have reported this to the wrong developer!

I am using FEI, but yeah when I removed it; it fixed the problem. As soon as I added it back it broke again..

So I guess Ill let him know.

Thanks again.
