### ISSUE TITLE
Crash on launch 

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [mezz/JustEnoughItems#825]
I have no idea what is going on here I have forge installed and lite loaded installed and when I have this mod installed it claims I don't have forge installed but when I remove the mod it works perfectly here is a link to the log file I believe 

[LOG FILE](https://gist.github.com/TWIISTED-SHOPS/23850d167f5d231fa0c72313ad27960b)

**Comment by mezz** [comment]
Thanks for the report!

You should be seeing an error screen, showing that JEI needs a newer version of Forge.
The crash in your log is actually a bug with Forge, it's crashing when you click the button to show the log.

The real error with JEI is here in the log:
```
[19:32:38] [Client thread/ERROR]: The mod jei (Just Enough Items) requires mod versions [forge@[13.20.0.2282,)] to be available
[19:32:38] [Client thread/ERROR]: net.minecraftforge.fml.common.MissingModsException: Mod jei (Just Enough Items) requires [forge@[13.20.0.2282,)]
```
Just update forge to version 13.20.0.2282 or higher and it should work.

**Comment by TWIISTED-STUDIOS** [comment]
im running the latest version of forge though

**Comment by mezz** [comment]
According to the log you are using forge version 13.20.0.2228, which is the "recommended" version, not the "latest".

**Comment by TWIISTED-STUDIOS** [comment]
ahhh ok then could be the problem cheers

**Comment by TWIISTED-STUDIOS** [comment]
how to get it to show the name of the block your looking at like nei used to do

**Comment by mezz** [comment]
That was added by WAILA, the new version is here: https://minecraft.curseforge.com/projects/hwyla
