### ISSUE TITLE
Game Crashes When Being Opened

### ISSUE THREAD

**Issue by Steven314** [mezz/JustEnoughItems#826]
Every time I open Minecraft (1.10.2) it crashes.
It gives me this message.

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setBoolean(Ljava/lang/String;Z)V

The only mods I have installed are Forge (version: 1.10.2-12.18.3.2185), JEI (jei_1.10.2-3.13.2.360), NEI (NotEnoughItems-1.10.2-2.1.3.219-deobf), code chicken core (CodeChickenCore-1.10.2-2.4.1.102-deobf), and code chicken lib (CodeChickenLib-1.10.2-2.5.8.255-deobf)

Here's the crash report.

[crash-2017-04-22_12.47.35-client.txt](https://github.com/mezz/JustEnoughItems/files/949135/crash-2017-04-22_12.47.35-client.txt)

**Comment by TehNut** [comment]
You're using deobf builds of NEI, CCC, and CCL. Also the template says to remove NEI before reporting.
