### ISSUE TITLE
Smelt Recipes (from Crafttweaker) not being detected in recipe viewer

### ISSUE THREAD

**Issue by xerberus333** [mezz/JustEnoughItems#827]
Setup:

MultiMC;
Minecraft 1.11.2;
Latest Forge;
Latest JEI;
Latest Crafttweaker;

Problem:

For some reason, my custom smelting recipes aren't being detected by JEI, when in the past, that wasn't the case. Currently checking previous versions, but I can no longer find any version that detects my Smelting recipes. Note that any custom crafting recipes are appearing just fine on JEI. Only smelting recipes are undetected.

Ex. 2 Gold Blocks on Crafting table = Cake will work (You can see the recipe);
However, smelt Gold Block into Cake will not appear on JEI (but the recipe still works, you can smelt Gold Blocks into Cakes just fine, you just can't see the recipe via JEI UI)

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Crafttweaker instead. If they need something from JEI they can contact me.

**Comment by Beetrootmonkey** [comment]
I've been experiencing the same issue as you. It seems to affect all custom machine-type recipes, since all my furnace and TechReborn machine recipes DO work, but don't show up.

Just wanted to let you know. I'll report this bug to Crafttweaker, hopefully they'll have a look at it.

**Comment by schismatix** [comment]
Re the above. It worked perfectly until jei_1.11.2-4.2.11.252 was released on Apr 04/17.
Last working version of JEI: jei_1.11.2-4.2.11.251.jar released Mar 03/17.

**Comment by Boomflex** [comment]
Still not working.

Items do smelt, but the option does not show in JEI.

As schismatix said, the last working version is jei_1.11.2-4.2.11.251.jar

**Comment by Beetrootmonkey** [comment]
![replay_jared](https://user-images.githubusercontent.com/12583297/33009721-01027c1e-cdd8-11e7-8ab9-69b55e7ac726.png)
Apparently the issue got fixed. (_source: the aforementioned thread_)

**Comment by mezz** [comment]
Thanks!
