### ISSUE TITLE
Unable to search for EMC Tooltips

### ISSUE THREAD

**Issue by ZeWolfTah** [mezz/JustEnoughItems#828]
MC Version: 1.10.2
Forge Version: forge-1.10.2-12.18.3.2281
JEI Version: jei_1.10.2-3.14.7.417

Bug:
When filtering for EMC values (which are found in tooltips), the filter does not display any items that have an EMC tooltip. Refined storage and AE2 search systems are able to detect and filter the tooltip correctly, but JEI in unable to. 
Tested with ProjectE-1.10.2-PE1.2.0

**Comment by AEnterprise** [comment]
i'm guessing that jei is caching the tooltips before projectE calculated them

**Comment by ZeWolfTah** [comment]
Is there anything I can do to delay it so it caches after? Back in 1.7.10, NEI was able to filter for EMC values which allowed me to set custom values much more easily. I even installed and tried it with the NEI 1.8.+ addon for JEI, and I still can't find a way to get it to work.

**Comment by mezz** [comment]
Thanks for the report!
Without caching the tooltips, search becomes very slow. This is a big difference in the design of JEI vs NEI and can't be worked around. 
I'm not exactly sure why ProjectE adds the tooltips so late, opening an issue with them may get some better information.

**Comment by ZeWolfTah** [comment]
Is there a way to reload the cache?

**Comment by mezz** [comment]
Not currently, no.

**Comment by mezz** [comment]
This is most likely fixed in version 4.4.0.
Starting at that version, JEI loads tooltips only after the world is created.
I was unable to test because ProjectE is not on 1.11.2 yet.

**Comment by egold555** [comment]
Not working in 1.12.2 

JEI Version: 4.9.2.196
ProjectE Version: 1.12-PE1.3.0

Perhaps I am searching it wrong? Its #EMC if I am not mistaken to search tooltips for "EMC"
