### ISSUE TITLE
Microblocks rendering issue?

### ISSUE THREAD

**Issue by Karmacopper** [mezz/JustEnoughItems#829]
I am getting the following crash log when I type "sh" (not quotes) into the JEI search bar:

https://paste.ee/p/q3Vsy

The helpful folks in the EnderIO IRC pointed me at the issue, as I don't have the javafoo to diduce these things.

JEI version: 3.14.7.417

**Comment by mezz** [comment]
Thanks for the report!
Please do not report rendering bugs here, this is a crash from another mod. 
There is an open bug report here: https://github.com/TheCBProject/Feedback/issues/17
