### ISSUE TITLE
Recipe & Use screens appearing when using vanilla's Creative Search Menu

### ISSUE THREAD

**Issue by Bitmarim** [mezz/JustEnoughItems#83]
When searching for items in the creative menu, keeping the mouse over any items or blocks while searching can cause the recipe or use menus respectively to open, or if there is no valid page, it simply won't type the hotkey's letter into the box to continue searching. This is very annoying, as the mouse is in the center of the menu when you open it by default, and it gets in the way of properly using the search function if someone isn't mindful to move the cursor first.

**Comment by TehNut** [comment]
This is not fixable. Already had this conversation last night.

```
<mezz> I can't detect when the search bar is being used so I just avoid breaking it there TehNut 
```

**Comment by Bitmarim** [comment]
Bummer. Guess I'll get used to it then.

**Comment by mezz** [comment]
I dunno, it's not necessarily the end of the discussion. 
Maybe a config option to disable JEI hotkeys in the creative menu?

**Comment by Bitmarim** [comment]
That seems like a reasonable solution. Should I reopen the issue for now then?

**Comment by mezz** [comment]
Good news! Since this is such a common case, I figured out a way to do it properly with ATs.
