### ISSUE TITLE
[Suggestion] More complete hiding of items in JEI

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#830]
Preface:
Just spent four days moving up to MC1.10.2 (cracks knuckles) and I really enjoy JEI so thanks for the development and your time.  While adding/ removing mods and changing mod configs -- and quite a bit of hair pulling, I believe a feature enhancement of JEI could benefit all who like to customize.

Topic:
Using a combination of CraftTweaker (to remove a recipe) and JEI (to hide a item) is a powerful tool.  For most items you can play as if said item did not exist.  You cannot craft it, right clicking one of its ingredients will not show it in JEI (because recipe was removed) and it will not show up in JEI's list.  Perfect!  However, for more complicated items, such as a custom furnace, it can still show up in the JEI tabs by right clicking an item it can use -- such as coal for fuel.  I think these tabs should check to see if the item is blacklisted or not before showing.

EG: right click coal,
(JEI) I should show the tab for custom furnace because coal is a fuel for it.
(JEI) Is it blacklisted?  If so do not show tab.

Or, if that would be a huge hassle to add, even something simple like a new "tabs blacklist" config would be OK.  I can easily add entries myself manually.

Hope this is something you think is worth adding!

**Comment by davqvist** [comment]
I was just going to suggest something similar here, what a coincidence. If I disable the recipes to craft a specific machine with Crafttweaker, the things you can craft with the machine still show up and I like to hide them and I don't think that's possible.

The OP suggests automatically and I doubt that's possible. If yes, the better, but manually hiding all the recipes that a specific machine offers would be very helpful. 

To add to this, even the option to manually disable one specific recipe would be helpful as well. To give an example. If I disable a furnace recipe with CraftTweaker, mods like EU2 or EnderIO still show that this smelting recipe can be done in their Furnace/Alloy Smelter as - I guess - the order of loading is different. I'm not sure if this can be prevented and this is a topic of its own, but a simple solution to this would be to let the modpack dev give the option to hide prevent this recipe from showing up.

To go even further, there's is a machine that has no CraftTweaker/ModTweaker integration, but there's a recipe for that machine which you want but can't disable by any means. Being able to hide the recipe in a modpack to at least let the majority not use it, would be a big help.

**Comment by ghost** [comment]
Specifically with my suggestion I am hoping for a way to tell JEI "this item no longer exists" so it can do some backend cleanup and remove all references to said item.

`To add to this, even the option to manually disable one specific recipe would be helpful as well. To give an example. If I disable a furnace recipe with CraftTweaker, mods like EU2 or EnderIO still show that this smelting recipe can be done in their Furnace/Alloy Smelter`

This is because mod machines typically maintain their own list for compatible items.  When you disable a furnace recipe with CraftTweaker you are only changing the list maintained by the vanilla furnace.  The mods furnace/alloy smelter will still be able to use said item.

Your idea might be better directed to the dev of Mod/Craft Tweaker for better 3rd party mod integration.  Even if you could remove the recipe from JEI you could still (in world) place the item in the mods furnace/ smelter and it would work.  If it works then I would like JEI to display it.  This is why I think our ideas are different.  For an example think of EX2's pink generator.  It only consumes "pink" items which is a list maintained in the mod itself.  Removing "pink recipes" from JEI will not diable the pink generator from consuming these items.  However if a player cannot place down a pink generator itself (due to missing crafting recipe to make) I think it is safe to remove all references to it...

**Comment by davqvist** [comment]
No, the Furnace/Alloy Smelter recipes don't work as they rely on the vanilla furnace recipes but still show up in JEI, that's exactly why I'm saying this.

**Comment by ghost** [comment]
Oh hah!  My bad.  I just assumed (yeah yeah) that they would maintain their own internal lists.  Well yes then.  In that case I agree that being able to disable a specific recipe would be useful.

**Comment by ghost** [comment]
Perhaps we should combine our requests and ask for something bolder: a JEI config scripting system!

My issue could be resolved as - JEI.removeTab( <mod:block> );
Your issue could be resolved as - JEI.removeRecipe( <mod:block>, [<mod:fuel>] );

[EDIT]:
And now that I said the above I realize perhaps I should actually request JEI support in CraftTweaker instead.  JEI might need to exposed some of its API but that might be easier.

**Comment by mezz** [comment]
Thanks for the report!
For the original issue, I can fix that. Category crafting items that get blacklisted should be removed.

For the rest, this type of thing definitely belongs in CraftTweaker. I can add the API for it like I have with the other features they've needed.

**Comment by davqvist** [comment]
Okay cool, that works as well. This would be very nice.

**Comment by ghost** [comment]
Thanks so much!  Hope it will be an easy fix...
No rush either =)
I am setting all my mods up but I am waiting for TD and MFR (which from past experience will take a while hah)

**Comment by mezz** [comment]
Right now I have JEI set up to automatically hide categories if all their catalysts are hidden.
It will also remove hidden items from rotations in recipes, so if you hide all but 1 type of tin you will only see that one in recipes.

I am not removing recipes that have all-hidden ingredients, because it is too processing-intensive to do well. I am leaving hiding of recipes up to mods like CraftTweaker and GameStages, using the JEI API.
