### ISSUE TITLE
Crash when applying texture packs (Resource Packs)

### ISSUE THREAD

**Issue by Gunner76th** [mezz/JustEnoughItems#831]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.
The following crashes happen while two different resource packs were being applied. 

https://pastebin.com/a7X54t37
https://pastebin.com/Cgsdc4x1

This has been cross posted to https://github.com/Soartex/Issues/issues/9 as well as https://minecraft.curseforge.com/projects/glimmars-steampunk?comment=48 to their respective pack authors.

**Comment by mezz** [comment]
Thanks for the report!
This is a JEI issue, not caused by any specific resource pack.

**Comment by mezz** [comment]
I'm not able to reproduce this bug. Applying a resource pack makes JEI reload, and I think some mod is breaking when JEI reloads.
Can you paste your `fml-client-latest.log` to gist and link it here?

**Comment by Gunner76th** [comment]
Here is the raw file. I had to rename it as a txt file due to upload restrictions. This is the most recent one that involved the crash while applying the resource pack. I am uploading the raw file, due to that fact I am on a satellite connection, and creating gists sometimes has issues due to that. 
[fml-client-2.log.txt](https://github.com/mezz/JustEnoughItems/files/953109/fml-client-2.log.txt)

**Comment by Gunner76th** [comment]
Also, incase it helps, here is the link to the modpack in question that is having the crash. This is a modpack that I/We (TeamIHOC) are maintaining. 
If the problem is caused by a bad JSON file, then that would be because of Ex Nihilo's SieveRegistry.json file 
The file I am linking here is the corrected JSON file https://cdn.discordapp.com/attachments/289539713587609601/306168709117116416/SieveRegistry.json
Seems I some how missed a single data entry in one of the "meshLevel": lines. 

I have not retested since I corrected that particular error.

**Comment by mezz** [comment]
Thanks, based on the log I can see that the vanilla JEI plugin is crashing because of some broken smelting recipe. I should be able to prevent it from crashing.
```
[13:21:04] [Client thread/ERROR] [JEI/JEI]: Failed to register mod plugin: class mezz.jei.plugins.vanilla.VanillaPlugin
java.lang.NullPointerException: Null item in itemStack
	at mezz.jei.util.StackHelper.getSubtypes(StackHelper.java:219) ~[StackHelper.class:?]
	at mezz.jei.plugins.vanilla.furnace.SmeltingRecipeMaker.getFurnaceRecipes(SmeltingRecipeMaker.java:29) ~[SmeltingRecipeMaker.class:?]
	at mezz.jei.plugins.vanilla.VanillaPlugin.register(VanillaPlugin.java:136) ~[VanillaPlugin.class:?]
	at mezz.jei.JeiStarter.registerPlugins(JeiStarter.java:142) [JeiStarter.class:?]
	at mezz.jei.JeiStarter.start(JeiStarter.java:48) [JeiStarter.class:?]
	at mezz.jei.ProxyCommonClient.loadComplete(ProxyCommonClient.java:111) [ProxyCommonClient.class:?]
```

**Comment by mezz** [comment]
Please try with [JEI build 418](https://dvs1.progwml6.com/jenkins/job/JustEnoughItems/lastSuccessfulBuild/artifact/build/libs/jei_1.10.2-3.14.7.418.jar).
It should not crash, and you should see a log starting with "Found invalid smelting recipe: " that tries to describe the broken recipe.

**Comment by mezz** [comment]
@Gunner76th any luck?

**Comment by Gunner76th** [comment]
sorry, I have been working on installing an air conditioner this afternoon. I will load the new JEI in a few and test it once I am done.

**Comment by Gunner76th** [comment]
I just tested build 418 with loading Glimmars Steampunk pack, and it applied with no crash. 
[fml-client-latest.log.txt](https://github.com/mezz/JustEnoughItems/files/953835/fml-client-latest.log.txt)
Here is a copy of my latest log. Hope this helps.

**Comment by mezz** [comment]
Ok cool. Looks like the crash has been fixed. Now it just shows this error instead of crashing:
`[Client thread/ERROR] [JEI/JEI]: Found invalid smelting recipe: (1x (null) -> 1xitem.flint_ingot@0 tp:flint_ingot)`
