### ISSUE TITLE
[API] IRecipeRegistry#removeRecipe fails due to null RecipeHandler 

### ISSUE THREAD

**Issue by Mohron** [mezz/JustEnoughItems#833]
JEI: 4.3.3.266
Forge: 13.20.0.2282

`IRecipeRegistry#removeRecipe(IRecipeWrapper, String)` fails to remove a recipe previously added using `IRecipeRegistry#addRecipe(IRecipeWrapper, String) ` due to `RecipeHandler` coming up null. I experienced this issue while working with `IRecipeRegistry#createAnvilRecipe` & `VanillaRecipeCategoryUid.ANVIL`.

**Comment by mezz** [comment]
I pushed a fix but I wasn't able to test it as well as I would like. Please let me know how it goes.

**Comment by Mohron** [comment]
Fix worked for me! Thanks for all your hard work.
