### ISSUE TITLE
Unable to see Not Enough Potions Recipes

### ISSUE THREAD

**Issue by KIdWither** [mezz/JustEnoughItems#834]
I cannot seem to be unable to see the portion recipes with JEI 1.11.2- 4.3.3.226, Potion Core 1.11.2- 1.5.1, and Not Enough Potions 1.12.1- 1.3.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to Not Enough Potions first, they may have a better idea of why it's not working.
Link back here so they can discuss if necessary.

**Comment by KIdWither** [comment]
I already informed them of this and I did not give me a reason for the occurrence of this bug.

Link to MC forum:http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2635343-not-enough-potions-new-brewing-mechanics-and?page=3#c43

**Comment by mezz** [comment]
I think they may be loading the potion recipes after the game is already running, which is after JEI grabs them.

**Comment by Tmtravlr** [comment]
Yeah, I'm loading them when the client joins the server, since the recipes are only server-side (loaded from config files).

Is there any way I can add them to JEI manually?

**Comment by mezz** [comment]
Currently there isn't a way to add brewing recipes to JEI at runtime, but I can add an API method to allow that.

**Comment by Tmtravlr** [comment]
That would be nice. Is there a way to add crafting recipes at runtime?

Also, since we're on the topic, and I don't know much about JEI,, I also have a couple new 'recipe' types, for two new blocks (mortar and pestle, and mixing cauldron). Is there a way I could add the recipes from them?

**Comment by mezz** [comment]
I pushed JEI version 4.3.4 with a new method to create brewing recipes at runtime:
`IRecipeRegistry#createBrewingRecipe`

To get started with JEI, check out the developer wiki: https://github.com/mezz/JustEnoughItems/wiki
If you have more questions you can ask here or try to catch me on #JEI on IRC.

**Comment by Tmtravlr** [comment]
Ah, great! Is there a 1.10.2 version with support yet, or just 1.11.2?

**Comment by mezz** [comment]
Only 1.11.2, there are a lot of changes in this latest version that make it possible.

**Comment by mezz** [comment]
I think this has been fixed. Can you confirm, @Tmtravlr ?

**Comment by Tmtravlr** [comment]
Yep, it has.

**Comment by mezz** [comment]
Thanks!
