### ISSUE TITLE
Changing an item's display name via CraftTweaker creates issues with searching

### ISSUE THREAD

**Issue by belathus** [mezz/JustEnoughItems#835]
I reported this to CraftTweaker as well:
https://github.com/jaredlll08/CraftTweaker/issues/202

Essentially, if I change the displayname of an item using CraftTweaker, then search for the item using the new display name, nothing comes up. However, if I search for the old name, the item shows up. My example is that I changed EvilCraft's iron promise acceptor to a "silver promise acceptor". Searching for "Silver Promise" shows nothing, but "iron Promise" shows the item.

**Comment by jaredlll08** [comment]
@mezz this can be closed
