### ISSUE TITLE
[1.10.2] Hiding item without NBT in plugin

### ISSUE THREAD

**Issue by Matryoshika** [mezz/JustEnoughItems#836]
Hey, I'm working on a mod that makes use of NBT to store specific data.
JEI displays all of these correctly, but also the "default" itemstack without any NBT.

Using _IModRegistry::addIngredientToBlacklist()_ with an ItemStack without NBT hides them all, and calling _IModRegistry::removeIngredientFromBlacklist()_ with each and every NBT permutation does not work to bring them back.

Is it possible to hide an ItemStack with specific NBT (no / empty compound, in this case), without affecting the rest?

My IModPlugin class: [Echo](https://github.com/Matryoshika/Echo/blob/master/src/main/java/se/Matryoshika/Echo/Common/Compat/JEICompat.java)

**Comment by KnightMiner** [comment]
Are you sure you are not still adding the item without NBT to your creative tab? Tinkers Construct uses nbt on all tools for materials and we do not see the nbtless tools in JEI.

In any case, the latter part of the issue sounds like a feature that could be relevant to include if it is not already there.

**Comment by Matryoshika** [comment]
I am sure that I am not adding it myself.
Block::setCreativeTab() is never called, and all permutations (blockstate + byte) of NBT are added manually to my custom creative-tab through CreativeTabs::displayAllRelevantItems().
The creative tab, does not contain the NBT-less ItemStack; yet JEI still adds it in.

**Comment by TehNut** [comment]
I'm actually noticing this in 1.11 as well.

**Comment by mezz** [comment]
There seems to be a lot of open issues with blacklisting items with nbt, I'll have to go through and carefully fix it, but I haven't had the time recently to create a clean solution.

The way JEI gets items is by grabbing the Item and Block registries, and then trying to get all the items from creative tabs for those. I think I may be adding items from the registries directly, and not just the ones from creative tabs. This was so I could show some hidden blocks that were not normally accessible, but I may rethink this and only take things from the creative menu.

**Comment by AEnterprise** [comment]
maybe an opt-in/out option for that behaviour with the JEI plugin?
