### ISSUE TITLE
Unable to look up uses or recipes of items while in certain GUIs

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [mezz/JustEnoughItems#839]
For example, when I open a chest and try and look up the recipe, or use, of an item in the chest I am unable to do so. It works fine while in a crafting GUI or in the normal inventory GUI, but all others seem to not be working.

**Comment by mezz** [comment]
Thanks for the report!
Which version of Minecraft are you playing on? What version of JEI?
Have you tried removing other mods that might use keyboard keys while in the inventory?

**Comment by awkwaRdcaRRot** [comment]
I'm on 1.11.2 with the latest version of forge and jei that's on curse (sorry not at pc so I can't get the exact numbers). I'll try it just by itself,  but I've been on the same custom modpack and the issue just arose after I updated some of the mods in the pack. Not sure which ones would have button functionality. Maybe quark? I made sure there wasn't any keybind conflicts.

**Comment by awkwaRdcaRRot** [comment]
I figured it out, I believe. I removed crafting tweaks from the mod pack and it fixed the issue.

**Comment by mezz** [comment]
Please report this issue to Crafting Tweaks here: https://github.com/blay09/CraftingTweaks/issues
