### ISSUE TITLE
Proglem with jei!

### ISSUE THREAD

**Issue by TukanDev** [mezz/JustEnoughItems#840]
When im open inventory menu from jei not apper im using jei latest verion with forge 13.20.0.2282 1.11.2 version combinated with liteloader 1.11.2.
![mods list](https://cloud.githubusercontent.com/assets/21688086/25624050/95cc190a-2f58-11e7-9810-751812355186.png)
my mods folder ^^^
![inventory](https://cloud.githubusercontent.com/assets/21688086/25624179/e71b8bd8-2f58-11e7-83a3-e6aa43ab28fc.png)
inventory ^^^^^

**Comment by way2muchnoise** [comment]
You should try to figure out which mod is causing this interaction

**Comment by mezz** [comment]
Thanks for the report!
Please remove other mods besides JEI, I think it's caused by something else.

**Comment by TukanDev** [comment]
Yay im fixed inventory tweak making problem, and thanks for helping.
you can add support for inventory tweaks to jei be able to use in modpacks for 1.10.2 and 1.11.2, becouse a lot modpacks on any version have inventory tweaks.

**Comment by mezz** [comment]
Please report this issue to inventory tweaks here: https://github.com/Inventory-Tweaks/inventory-tweaks/issues
