### ISSUE TITLE
Color search not working

### ISSUE THREAD

**Issue by epilimic** [mezz/JustEnoughItems#843]
Hello, I'm trying to use the color search but it doesn't seem to be working. I'm playing on v1.8.1 of the DireWolf20 1.10 pack.

In my examples here you can see that the jukebox has the tag of brown, but when I search brown it doesn't appear. 3rd pic shows I have it enabled.
![2017-05-03_08 25 40](https://cloud.githubusercontent.com/assets/3755613/25660607/09d16f9e-2fdb-11e7-84ac-3c668c027e11.png)
![2017-05-03_08 25 48](https://cloud.githubusercontent.com/assets/3755613/25660606/09d1b472-2fdb-11e7-9cfb-d6034c459570.png)
![2017-05-03_08 25 58](https://cloud.githubusercontent.com/assets/3755613/25660608/09d7268c-2fdb-11e7-9fb6-17bea9ce6056.png)

Thanks!

**Comment by VT-14** [comment]
As shown in that menu, the color search prefix is ^ (shift + 6).

EDIT: Oh, wait; it's set to enabled.  Try to prefix anyway (to see if it works at all), but the enabled flag will probably need to be addressed.

**Comment by mezz** [comment]
Thanks for the report!

That's weird, I tested with just JEI on 1.10.2 and it worked fine:
![2017-05-03_14 03 14](https://cloud.githubusercontent.com/assets/916092/25681515/66cad4be-3009-11e7-8724-064bd7f14521.png)

And then I restarted the game to try again and it stopped working:
![2017-05-03_14 07 08](https://cloud.githubusercontent.com/assets/916092/25681637/d9f0e4ba-3009-11e7-8f6a-c565192cf6df.png)

I'll look into it.

**Comment by epilimic** [comment]
@VT-14 I tried both with it enabled and with using the ^ prefix with it on prefix mode, same result. Thanks!

**Comment by Alan19** [comment]
The first time I launch Minecraft after reinstalling the modpack, color search works but stops working after I restart.

**Comment by mezz** [comment]
This has been fixed in version 4.4.0

**Comment by Alan19** [comment]
Thanks @mezz!
