### ISSUE TITLE
JEI Crashing when trying to load a world.

### ISSUE THREAD

**Issue by PrinceOfIonia** [mezz/JustEnoughItems#845]
Hello hello! So today I wanted to use JEI for my Minecraft world, however when I try to load it, it takes awhile, freezes then gives me this https://pastebin.com/hnZpbj8a It seems to be some sort of memory error, which is odd cause when I take JEI out the world loads fine. Can somebody help me? Thanks!

**Comment by Ommina** [comment]
"Out of Heap Space".

Granting it is only 29 mods, and at the risk of asking the obvious, but have you tried giving it more memory?  Right now, you're only allocating it 1G, which isn't really much.

**Comment by PrinceOfIonia** [comment]
It worked! Thanks! One question though, when I checked NEI, it seems to require JEI now, why is that?

**Comment by way2muchnoise** [comment]
NEI is now an addon for JEI, it adds all the features NEI had but JEI doesn't have.

**Comment by PrinceOfIonia** [comment]
i see.

**Comment by PrinceOfIonia** [comment]
I see, Well Thanks! :D
