### ISSUE TITLE
[1.11.2 - 4.3.3.270] Hotkeys for recipe or use not functioning

### ISSUE THREAD

**Issue by VallenFrostweaver** [mezz/JustEnoughItems#846]
I _can_ right click to get the recipe. In creative mode (or survival and changed game mode to 1) and item cheating mode enabled I need to use the hotkeys to see the recipes. If I press the usual R or U to see the recipe or use nothing happens. I have removed all key conflicts and the issue is still there. I am unsure if this is a direct conflict with another mod and unsure how to find that out. I am playing on the Modded Mischief II modpack's latest version 0.3.1

**Comment by mezz** [comment]
Thanks for the report!
The best way to find out if a mod is conflicting is to remove it. Try removing mods that deal with the inventory screens or mods that can have hotkeys active while JEI is open.

**Comment by SeriousCreeper** [comment]
Had the same issue in my SeriousRemnants pack, seems to be caused by CraftingTweaks version 7.1.7. Going back to version 7.1.6 fixes it. 

Tested with forge 2282 and JEI version 4.3.4.273

**Comment by mezz** [comment]
There is Crafting Tweaks issue open now, let's move discussion there so it's all together:
https://github.com/blay09/CraftingTweaks/issues/101
