### ISSUE TITLE
Can the cheat mode be disabled on server side

### ISSUE THREAD

**Issue by inxomnyaa** [mezz/JustEnoughItems#847]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.
In theory what the title says. the owner noticed that he always gets the items via cheat mode, but we want to keep the server cheat clean. @SalmonGER can say more to this

**Comment by mezz** [comment]
Cheat mode is only enabled if the player has permission to use `/give` or the creative inventory.

**Comment by inxomnyaa** [comment]
I see, that was the reason. He still is operator. Thanks 👍 keep up the good work
