### ISSUE TITLE
[1.11.2] JEI is missing forge

### ISSUE THREAD

**Issue by meppycola** [mezz/JustEnoughItems#849]
[1.11.2] I try to download JEI, but when i start minecraft it says i can't because forge isn't being used, but i'm launching the game with forge!

**Comment by mezz** [comment]
Thanks for the report!
Please show me a screenshot or log of what you saw, so I can take a closer look.

**Comment by skiniemini** [comment]
@mezz I'm getting the same issue. I currently have Forge 13.20.0.2282 and running minecraft version 1.11.2.  I attached a screenshot of the error.
![error](https://cloud.githubusercontent.com/assets/20691184/25815833/f95531e6-33d6-11e7-9cb0-1d9066edca0a.PNG)

**Comment by TheDrawingCoder-Gamer** [comment]
Umm I also have this problem, and I have the required forge.

**Comment by TheDrawingCoder-Gamer** [comment]
![screen shot 2017-05-11 at 4 49 10 pm](https://cloud.githubusercontent.com/assets/26726264/25971319/cddb099c-3669-11e7-8d9b-a65f4288bc68.png)

**Comment by TheDrawingCoder-Gamer** [comment]
![screen shot 2017-05-11 at 4 51 26 pm](https://cloud.githubusercontent.com/assets/26726264/25971418/21d1865c-366a-11e7-876d-2e5d61af5e54.png)

**Comment by TheDrawingCoder-Gamer** [comment]
OHHH

**Comment by mezz** [comment]
Please double check your forge version.
This message has never been wrong.
Recently players have forge 2228 and think it's 2282 because they look very similar.

**Comment by mezz** [comment]
Yeah,,, lol

**Comment by TheDrawingCoder-Gamer** [comment]
I just realized

**Comment by TheDrawingCoder-Gamer** [comment]
I was using the wrong one

**Comment by TheDrawingCoder-Gamer** [comment]
The game launches correctly now, just click on latest, not recomended.

**Comment by TheDrawingCoder-Gamer** [comment]
When I open a world it crashes, but I just want to use this mod as a library for NEI, so it's frustating it won't work.

**Comment by mezz** [comment]
Please don't take over this issue for troubleshooting, open a new issue.

**Comment by TheDrawingCoder-Gamer** [comment]
Okay.
