### ISSUE TITLE
Ctrl O does nothing.

### ISSUE THREAD

**Issue by Nightskysx** [mezz/JustEnoughItems#850]
The only mods i have is forge-1.11.2-13.20.0.2294 and jei_1.11.2-4.3.4.273 

I tried to press ctrl o to bring up the overlay and nothing happened. I went to the controls section of the settings and rebound the key to different keys and none of them worked. I know the mod is installed because its in my installed mod section of forge. And I also know it is installed because I can change the hotkeys. I dont know why this mod wont work.

**Comment by mezz** [comment]
Thanks for the report!
By default the overlay should already be open when you're in an inventory.
If you already tried that, maybe something caused JEI to crash or another mod is interfering.
Please paste your `fml-client-latest.log` to https://gist.github.com/ and link it here.

**Comment by Nightskysx** [comment]
So after a bit of looking though things. And trying it out with different mods and settings. 5zigs is causing the mod to not work for some reason. Is this on your end or their end?

https://gist.github.com/Nightskysx/84da52c448fa379dce813ed7377526db.js

https://gist.github.com/Nightskysx/84da52c448fa379dce813ed7377526db

**Comment by mezz** [comment]
Yes it seems to be an issue from their byte code hook, there are a few errors in the log relating to it.
Please report to them and link back here.
