### ISSUE TITLE
Inconsistent JEI access

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#851]
JEI 1.10.2-3.14.7.419
When I open the inventory screen, clicking on JEI items has no effect, neither does clicking on the search bar. I need to use a hot key to access the search bar, then hover over an item and press 'u' to access the usual JEI functionality. This doesn't happen in TiCon crafting tables, chests, EZ Storage, etc. When I try to right click in the inventory screen it also acts as if I've right-clicked normally (opening books, activating blocks I'd be targeting, etc. Is this a known bug?
I just spent a bunch of time searching for answers and I thought I'd ask before the tortuous process of removing mods.
Thanks.

**Comment by TehNut** [comment]
Your best bet is removing mods until it works.

**Comment by ghost** [comment]
That's what I was afraid of.

**Comment by ghost** [comment]
Found it. It was a mod I was going to try called FOV Zoom.
