### ISSUE TITLE
Recipe sorting question

### ISSUE THREAD

**Issue by desht** [mezz/JustEnoughItems#852]
Hi, got a question about how JEI sorts recipes (and whether I can influence the ordering of recipes added by my mod).

I add a recipe for each module item that my mod adds - see https://github.com/desht/ModularRouters/blob/master/src/main/java/me/desht/modularrouters/recipe/ModRecipes.java#L34 for that.  That's a regular vanilla crafting recipe, either shaped or shapeless (and some modules may use oredicted ingredients).

Later on, I also add some "enhancement" recipes, where a module item can be crafted with other ingredients to modify its behaviour in some way - https://github.com/desht/ModularRouters/blob/master/src/main/java/me/desht/modularrouters/recipe/ModRecipes.java#L74.  The enhancement recipes extend a custom ModuleEnhancementRecipe class, which handles validation, NBT copying, etc.

Note that these enhancements also have their own JEI recipe handlers, mainly for the purposes of adding an informative tooltip to the output item in the JEI recipe for that enhancement.  These handlers just use the vanilla crafting category (VanillaRecipeCategoryUid.CRAFTING).

The problem I have is that JEI always shows the enhancement recipes before the primary crafting recipe for the module, which is annoying, since the crafting recipe is used more often, and therefore you end up scrolling through potentially several enhancement recipes before you find the primary recipe.

Is there a way of telling JEI that the primary recipe should always be shown first?  I'd hoped the Forge RecipeSorter might have some effect (and my enhancement recipes have a RecipeSorter dependency
of "after:forge:shapelessore"), but apparently not.

**Comment by mezz** [comment]
Sorry I overlooked this.
Recipes are grabbed from the recipe list after it has been sorted.
There isn't really anything special going on, you can see the entry point for that here if you want to look deeper into it:
https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/plugins/vanilla/VanillaPlugin.java#L123

Make sure that your recipes appear in the recipe list the way you expect after it has been sorted (end of `RecipeSorter#sortCraftManager`).

**Comment by desht** [comment]
Sorry I didn't get back sooner.  I never did manage to figure out why default recipe ordering didn't work like I expected in 1.10/1.11.  However, the problem seems to have gone away in 1.12... the primary recipe is appearing first, just as I want it.  Given I'm focusing on 1.12 for any future development, I'm taking the lazy option and calling this no longer an issue :)  Thanks for the information though.
