### ISSUE TITLE
JEI Crash on item search, possible item rendering bug

### ISSUE THREAD

**Issue by skellitor301** [mezz/JustEnoughItems#853]
I've been having issues with crashing when searching for items in JEI's inventory window. I know that there is another issue involved with JEI search crashes (#808)  but you asked for a separate issue to be made for a different user from the original poster. Also, I've been able to replicate the crash by changing pages when attempting to look for the item instead of using the search function, so it might be rendering issues for certain items. I've included a crash log here of the crash caused by changing pages, I hope this new variable to the issue helps: [Gist link](https://gist.github.com/skellitor301/16df7f609efdc3822d4d8a6e904e1d4b)

**Comment by TehNut** [comment]
Try removing NEI and CCC. This crash is in their code.

**Comment by mezz** [comment]
Thanks for the report! This is a crash with Forge Microblocks.
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Forge Microblocks
	Ingredient Info: 1xitem.microblock@1 microblockcbe:microblock nbt:{mat:"minecraft:bookshelf"}
```

Please add your crash report link to this issue here: https://github.com/TheCBProject/Feedback/issues/17
