### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by Kittykitsuna** [mezz/JustEnoughItems#854]
Hey there! soo my issue is that as im trying to get onto minecraft and use this mod it will not let me. like as it loads up it takes me to it saying it is missing mods it depends on and whatnot. also that requires forge 13.20.0.2282.. which i have and still nothing. im not sure what mods its missing at all but i have a screenshot of the message that pops up if thatll help

![image](https://cloud.githubusercontent.com/assets/28582664/25879504/fe5eeb12-34ff-11e7-989b-3818b4f59e2c.png)

**Comment by TehNut** [comment]
Are you 100% sure that you have Forge build 2282? The recommended build is 2228 and many people confuse the two.

Also I approve of your background.

**Comment by mezz** [comment]
This screen is accurate, please check your Forge version.
