### ISSUE TITLE
Unable to see and craft Avaritia Dire Crafting Table outputs

### ISSUE THREAD

**Issue by matt091498** [mezz/JustEnoughItems#857]
As the title says. When I hit r on the item I have added a dire crafting table recipe to, it does show the needed inputs, but instead of the output it just shows a blank square. No error shows up in the zenscript code. There is no crash but here is something I found in the logs: [https://pastebin.com/xJ7ZM7x7](https://pastebin.com/xJ7ZM7x7).

This was on mc version 1.10.2:
Avaritia-1.10.2-2.1.0.1-universal.jar
CraftTweaker-1.10.2-3.0.24.jar
jei_1.10.2-3.14.7.419.jar

I can give a full modlist or pics if you think they would be helpful.
Thanks for the help :)

Also if you think this should be directed towards Avaritia 1.10+ and not here just let me know.

**Comment by mezz** [comment]
Thanks for the report!
Yes, when there is an issue with just 1 mod besides JEI please report it to them first. Normally they are in a better position to understand and fix the issue, and they can tell me what I need to fix if necessary.

**Comment by matt091498** [comment]
Alright thanks! I have posted this on the Avaritia 1.10+ issue tracker.
Again, thanks for the help.
