### ISSUE TITLE
Server has not yet installed JEI?

### ISSUE THREAD

**Issue by TyeBlue** [mezz/JustEnoughItems#858]
Note i am doing this on a realm but it has the /give command so i'm not sure why it's not working
it says Server has not yet installed JEI? any help?

**Comment by EmanYm** [comment]
>Does Realms support modding?
Not at the moment. Sorry! But the PC / Mac version has support for a growing number of minigames and custom maps made by the community.

[Source](https://minecraft.net/en-us/realms/faq/)

**Comment by mezz** [comment]
Thanks for the report!
Please screenshot the error message, there is no message saying "Server has not yet installed JEI" in JEI.
