### ISSUE TITLE
How do I make it so JEI doesn't show blocks from my mod

### ISSUE THREAD

**Issue by MrAmericanMike** [mezz/JustEnoughItems#859]
So, first of all, sorry for asking here, it's not an "issue" itself, but probably something I'm missing

I know JEI doesn't display "Crops" the blocks when you search. But for my mod, when I do search for them, they show in JEI

I wonder what property or piece of code am I missing

http://imgur.com/a/Z6OXP

in 1.10.2 they show as the typical missing texture, in 1.11.2 they show that and the stage 1 of growing on top.

For the crop I have "this.setCreativeTab((CreativeTabs)null);" just like Vanilla crops, but I guess that's not what JEI looks for in order to decide wether to show them or not.

What do I need?

Thanks in advance

**Comment by TehNut** [comment]
If those are the crop blocks, you shouldn't be registering an `ItemBlock` for them. However, [here](https://github.com/mezz/JustEnoughItems/wiki/Hiding-Ingredients) is the documentation for blacklisting ingredients.

**Comment by MrAmericanMike** [comment]
Thanks TehNut, it was that I was using my regular blockRegister and registering them as item also. Removing that call fixed it ;)
