### ISSUE TITLE
Mipmap issue

### ISSUE THREAD

**Issue by InvalidUs3r** [mezz/JustEnoughItems#860]
Whenever I search anything it makes the game have no mipmapping and causes terrain to flicker.

**Comment by mezz** [comment]
Thanks for the report!
This is probably caused by a buggy item being rendered in the list.
Try narrowing down which item is causing the problem.

**Comment by InvalidUs3r** [comment]
searched @draconic it did it

**Comment by InvalidUs3r** [comment]
tried downgrading version, didn't work :(
is there any known issues with betterfps/optifine i am using both

**Comment by mezz** [comment]
Try looking at the Draconic Evolution items in the creative menu to see if you can eliminate JEI from the issue.
There is most likely an issue with Draconic Evolution alone, or a conflict between it and Optifine.
I am pretty sure JEI is not the cause here.

**Comment by InvalidUs3r** [comment]
yup reverted dracon ev version and it seems to be fixed. tried @a-z scrolling through all items and scrolling through every page with no search. also removed better fps but I don't think that did anything

**Comment by InvalidUs3r** [comment]
ty for the help

**Comment by mezz** [comment]
Ok, glad that was an easy fix. 
Please report it to Draconic Evolution here so they can fix it: 
https://github.com/brandon3055/Draconic-Evolution/issues
