### ISSUE TITLE
[1.10.2] Many recipes show duplicate items in certain slots of the crafting table

### ISSUE THREAD

**Issue by acdc787** [mezz/JustEnoughItems#861]
JEI: 3.14.7.419
Forge: 12.18.3.2297

**Firstly, this seems to be an issue with another mod, but i'm unsure which one it could be, because after writing this, I tested it with only JEI installed, and the problem vanished. I still feel like this issue should be at least mentioned.**

For most recipes, one (seemingly random) item in a recipe will show a lot more in that slot than required for said recipe (For instance, TNT shows 4 sand in the top centre slot, but the rest is normal)

Most vanilla recipes shows one slot having the total amount of that material. However, modded recipes show completely random amounts, usually double, sometimes triple the amount of material.

It's fairly minor, as it doesn't *actually* make the recipe require more stuff, but it could be a pain when it comes to things that really do require multiple materials in a slot, and not knowing which.

![2017-05-17_00 02 26](https://cloud.githubusercontent.com/assets/25849987/26138291/13d34a88-3a96-11e7-850c-91c3a1147720.png)

![2017-05-16_23 58 23](https://cloud.githubusercontent.com/assets/25849987/26138270/e3618a54-3a95-11e7-84a5-cc03fbc7e920.png)

![2017-05-16_23 58 59](https://cloud.githubusercontent.com/assets/25849987/26138323/5f587622-3a96-11e7-8be6-e474b8b7bcda.png)

(Sorry if this is a terrible report, i'm fairly new to GitHub.)

**Comment by acdc787** [comment]
Welp, I was gonna test the most likely candidates for why this is happening, and found it first try, haha.

Turns out, it's **Aether 2**. Maybe it has to do with their own UI for the inventory.

I'll send this their way as well, provided someone else hasn't already.

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately there is no way to track this down easily. The actual recipes are being edited, not just the JEI representation. Instead of forcing JEI to always show 1 item, I show the real recipe so that this type of error is more noticeable and can be fixed.
