### ISSUE TITLE
MobSpawner stuff causing crash

### ISSUE THREAD

**Issue by tavo1ga** [mezz/JustEnoughItems#862]
everytime i open a world, the game crashes, i've read the crash report and it says something about mobspawner things(not sure if thats the case),[here's the link](https://pastebin.com/RQ7HHxjk) (uses pastebin)

**Comment by EmanYm** [comment]
There is a chest that has an item
>Block type: ID # 54 (tile.chest // net.minecraft.block.BlockChest)
Block location: World: (-411,45,122),

Open the world in something like [MC Edit](http://www.mcedit-unified.net/) and find out what's in that chest

**Comment by mezz** [comment]
Sorry this is not related to JEI at all. 
Update Optifine to fix it.
