### ISSUE TITLE
Huge fps drop Jei + tinker's construct

### ISSUE THREAD

**Issue by AndreiTS** [mezz/JustEnoughItems#867]
![2017-05-24_16 09 00](https://cloud.githubusercontent.com/assets/13489837/26428746/ce4c471a-40b9-11e7-8396-83e006dc74f4.png)
![2017-05-24_16 09 08](https://cloud.githubusercontent.com/assets/13489837/26428747/ce4f9604-40b9-11e7-921f-be73451900ac.png)
![2017-05-24_16 09 14](https://cloud.githubusercontent.com/assets/13489837/26428748/ce5d8bba-40b9-11e7-9d40-41ac25c91519.png)

**Comment by mezz** [comment]
Thanks for the report!

>If the issue seems to affect only one mod, report to them instead of here.

I think Tinker's items are just slow to render, I don't think JEI is doing anything here to make it slow other than displaying a lot of them at once.

**Comment by AndreiTS** [comment]
"This can't be fixed in the mod. It's not a bug in the mod. You can only remove anything that impacts rendering and see if it gets better." -boni

**Comment by mezz** [comment]
I wonder if they can cache their rendering somehow, or if I can do it. 15 fps is pretty bad.
