### ISSUE TITLE
1.11.2-4.3.6.282 ClassCastException ItemAir (Rendering Recipe Crash)

### ISSUE THREAD

**Issue by TwitchtvCarbs** [mezz/JustEnoughItems#871]
Getting a strange rendering crash when shift clicking the + button
Also happens sometimes when simply just looking at recipes as well.

https://pastebin.com/P17uMWPZ

**Comment by mezz** [comment]
Thanks for the report!
This seems to be an issue from [Vanilla Builders Extension](https://minecraft.curseforge.com/projects/vanilla-builders-extension/issues?filter-action=&filter-tag=), try reporting to them.

**Comment by TwitchtvCarbs** [comment]
Oh whoops, sorry about that! I wasn't sure. Going to report to them now.

**Comment by mezz** [comment]
No problem. I'll close this for now since I'm pretty sure JEI is not the cause.
