### ISSUE TITLE
[Feature Request] make 'scan nearby inventories' work

### ISSUE THREAD

**Issue by LonJonn** [mezz/JustEnoughItems#876]
You can press t to scan for items in inventories **after doing a search**, but you can't scan for items in the player's inventory or in recipe screens. please add this as its extremely useful.

**Comment by KnightMiner** [comment]
I'm pretty sure the scan for items feature is not added by JEI, it is probably one of your add-ons (such as NEI)

**Comment by mezz** [comment]
A good inventory-search feature is added by [More Overlays](https://minecraft.curseforge.com/projects/more-overlays), you should try it out.
