### ISSUE TITLE
Mr.Crayfish Items Don't show Properly

### ISSUE THREAD

**Issue by aferris86** [mezz/JustEnoughItems#879]
Some of the items from Mr. Crayfish's furniture mod don't show up properly:

![2017-06-01_12 41 43](https://cloud.githubusercontent.com/assets/25187644/26690642/0b696600-46c8-11e7-91f8-e44b941c6400.png)

**Comment by KnightMiner** [comment]
Do they show up properly in the regular inventory or the creative tab? Sounds like an issue with the mod/a conflict rather than JEI (or you are seeing technical blocks that are never meant to be obtained as items)
