### ISSUE TITLE
Add a way to set the search query from the API

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#88]
AE2 wants to synchronize the search field with its own.

**Comment by Prospector** [comment]
Is AE2 1.8 already?

**Comment by mezz** [comment]
Not yet, but I might as well start thinking about this issue now.

**Comment by wlhlm** [comment]
There are similar mods like [StorageSilo](http://minecraft.curseforge.com/projects/storagesilo), that could use such a feature.
