### ISSUE TITLE
Crashing while using JEI on All The Mods v. 2.55e 

### ISSUE THREAD

**Issue by Shekinah33** [mezz/JustEnoughItems#880]
Hey there I was unsure wether you'd be able to help me with this but I hope so. I'm playing on a private whitelisted server and me and my friend (who live in different parts of the world) are having this issue where we crash every time we type certain letters into JEI ( a - L - B) etc. 
I've uploaded my crash log here
[crash-2017-06-03_18.25.31-client.txt](https://github.com/mezz/JustEnoughItems/files/1049544/crash-2017-06-03_18.25.31-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Please report this to [AgriCraft here](https://github.com/AgriCraft/AgriCraft/issues), I'm not sure JEI is involved.

**Comment by mezz** [comment]
Closing this for now, if it turns out to be a JEI issue I can reopen it.
Discussion should go on the issue here: https://github.com/AgriCraft/AgriCraft/issues/981
