### ISSUE TITLE
The reason everyone is crashing

### ISSUE THREAD

**Issue by Zentryke** [mezz/JustEnoughItems#883]
Whenever I hover my mouse over the icons in the top left such as weather, magnet mode, etc. it crashes. I noticed this happens for other popups too. I think it may be because of a font problem possibly or when the text pops up.

**Comment by Zentryke** [comment]
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

**Comment by KnightMiner** [comment]
None of those buttons are added by JEI. Determine which addon they come from (probably NEI) and make a proper report to the author including a crash report.

**Comment by mezz** [comment]
Thanks for the report!
The buttons are added by one of these mods, not JEI:
[Just Enough Buttons](https://mods.curse.com/mc-mods/minecraft/248747-just-enough-buttons)  
[Buttons](https://minecraft.curseforge.com/projects/buttonz)  
[FTB Utilities](http://minecraft.curseforge.com/projects/ftb-utilities)  
[NEI](https://minecraft.curseforge.com/projects/not-enough-items-1-8)
[FEI](https://mods.curse.com/mc-mods/minecraft/244314-forever-enough-items)
