### ISSUE TITLE
Block drops looknig for jei version 4.4.0

### ISSUE THREAD

**Issue by Kylebartaous** [mezz/JustEnoughItems#884]
Mine craft version: 1.11.2

Forge build w/ lite-loader mix in: 13.20.0.0.2314

Jei version: jei_1.11.2-4.3.5.277.jar

Block drops version: blockdrops-1.11.2-1.2.3.jar

It seems after updating block drops to version 1.1.2-1.2.3.jar , it is looking for a newer version of jei witch is  4.4.0

http://prntscr.com/fgtb46

**Comment by mezz** [comment]
You can get the latest versions of JEI here:
https://minecraft.curseforge.com/projects/just-enough-items-jei/files
