### ISSUE TITLE
1.11.2-4.5.0.287 -- Crashes when clicking on SinglePlayer

### ISSUE THREAD

**Issue by shufunk** [mezz/JustEnoughItems#885]
It doesn't even go beyond the main screen! When clicking on Single Player it just crashes the game! Downgrading one version down fixes crash. I am no coder and do not understand this crash to explain any further. 

Here is the crash log -- [gist](https://gist.github.com/shufunk/80fcf308e582ebefed22a22ecbedfadc)

**Comment by IchigoGames** [comment]
same crash
Minecraft 1.11.2
jei_1.11.2-4.5.0.287
crash report https://pastebin.com/010Xw6T6

**Comment by way2muchnoise** [comment]
Both related to NEI, you'll have to wait for NEI to move on with the 4.5+ API of JEI

 `codechicken.nei.jei.JEIIntegrationManager`

**Comment by covers1624** [comment]
Well then.. Looks like im working on NEI today.. NEI issue ref https://github.com/TheCBProject/NotEnoughItems/issues/103
