### ISSUE TITLE
Jei crash report: what is cuasing it to crash ?

### ISSUE THREAD

**Issue by Kylebartaous** [mezz/JustEnoughItems#886]
mine craft version: 1.11.2

forge version: 13.20.0.0.2314

Jei version: 4.5.0287

Other mod ran with to debug what was possible crashing it , jei , jer (just enough resources) , block drops ,(jei addon) , hwyla more overlays (shows light lvls ) , waila harvestability , wawla ( what are w  looking at )

My guess is jei , block drops , and / or more over lays is causing this but wasn't sure if it was on your or there side this time.

[crash-2017-06-07_19.24.32-client.txt](https://github.com/mezz/JustEnoughItems/files/1059657/crash-2017-06-07_19.24.32-client.txt)

**Comment by TehNut** [comment]
MoreOverlays needs to update to the 4.5 API

**Comment by Kylebartaous** [comment]
OK , thanks for the help
