### ISSUE TITLE
Just Enough Items is not compatible with some mods

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#887]
(From Poland so could be some mistakes)
Hi.

JEI is not compatible with: 
 
-Decocraft
-AdvancedRocketry
-Galacticraft
-Mr crayfish's furniture mod
-IndustrailCraft
-Chisel
-Pam's Harvest

JEI don't show recipes items/blocks but these items/blocks are in creative tab.

**Comment by way2muchnoise** [comment]
Mods are responsible for their own support, when they have complex items they need to register some subtype interpreter.

**Comment by ghost** [comment]
Can't do anythink ?

**Comment by ghost** [comment]
![2017-06-11_11 25 58](https://user-images.githubusercontent.com/29304275/27010635-4da23356-4ea9-11e7-99cd-7304bd14e78c.png)
![Uploading 2017-06-11_11.26.01.png…]()
![Uploading 2017-06-11_11.30.18.png…]()

**Comment by mezz** [comment]
Please report these issues to each mod. They are each responsible for their integration with JEI. If they have questions or find an issue they can ask here.
