### ISSUE TITLE
Item graying no longer works

### ISSUE THREAD

**Issue by jzburda** [mezz/JustEnoughItems#890]
(jei_1.11.2-4.5.0.287) Since this version, I am unable to "Item gray" that is, have items light up while all others are 'grayed out'
[Example Image](http://i.imgur.com/aGvBWkp.png)

**Comment by mezz** [comment]
Thanks for the report!
This feature is actually not added by JEI.
See the row for "Inventory Search" here to find the mod you have which adds this feature:
https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0
