### ISSUE TITLE
Crash on options : controls settings

### ISSUE THREAD

**Issue by Rambonata** [mezz/JustEnoughItems#893]
Latest version on 1.12, game crashes when you attempt to access the control settings.

**Comment by Nayashi** [comment]
Having this same issue
>>> https://pastebin.com/FmCRnrXT

**Comment by mezz** [comment]
Thanks for the report!
This was a Forge bug (https://github.com/MinecraftForge/MinecraftForge/issues/3985) and has been fixed in the latest version.
