### ISSUE TITLE
[1.12][4.6.0.61] Crash when hovering water/lava

### ISSUE THREAD

**Issue by mcenderdragon** [mezz/JustEnoughItems#898]
It crashed while I was trying to debug my mod :P

Crashreport: https://gist.github.com/mcenderdragon/63e351cbc6f853db73e42a767f00eb2a

**Comment by TehNut** [comment]
Looks like you're on outdated mappings.

**Comment by mcenderdragon** [comment]
well I use the same as forge dose.
Edit: yeah they are pretty old, but the newer ones for 1.12 are still unfinished.

**Comment by TehNut** [comment]
So? They have everything you have and more

**Comment by mcenderdragon** [comment]
I am using currently snapshot_20161220, I tried  snapshot_20170612 but there were much more func/fields everywhere.

**Comment by shadowfacts** [comment]
Of course there are, `snapshot_20170612` is for MC 1.11.

**Comment by mcenderdragon** [comment]
well methods like isEmpty() did not work, but the Advancements had names so dunno what went wrong...

**Comment by mezz** [comment]
Thanks for the report!
Hmm I probably shouldn't include anything from obfuscated Minecraft in the default API methods.
I'll fix this up so it's not a default method any more.

**Comment by mezz** [comment]
Actually... hmm. I'm not sure why ForgeGradle is not handling this case.

Anyway, for now I think you should just update your mappings. I will be updating the Forge mappings very soon.

**Comment by mcenderdragon** [comment]
Yeah updating to 0615 fixed it.
