### ISSUE TITLE
Got a question... more then an issue

### ISSUE THREAD

**Issue by koalalord9999** [mezz/JustEnoughItems#90]
So, I'm on multiplayer right? its a pure vanilla server (It's running 1.8.8 - dunno if that will affect this or not), no mods or anything on it. I open my inventory using the latest (4 hours ago) JEI 1.8.9 nothing appears. It's empty. I press ctrl+O still nothing. I press R on some iron, nothing, press U same thing.

Does the server need to have JEI installed for it to work clientside? Or is there some kind of pre-requesite that I need to have for this mod to work?

**Comment by wlhlm** [comment]
This is a known issue. See #73

JEI depends on an event, that won't get fired when connecting to a vanilla server. See MinecraftForge/MinecraftForge#2315

**Comment by koalalord9999** [comment]
Ah, alright - thanks (time to go moap in a corner while I'm unable to learn vanilla recipes xD)

**Comment by koalalord9999** [comment]
Uhhh I havn't changed anything... I'm still on a vanilla server... but...
![image](http://i.imgur.com/SsOrr2T.jpg)

**Comment by mezz** [comment]
You should be able to get it to work if you connect, disconnect, and connect again.
