### ISSUE TITLE
Pressed T

### ISSUE THREAD

**Issue by Saphirius** [mezz/JustEnoughItems#902]
While i was playing i accidentally pressed T whilst searching for an Item.
The item dissapeared and a grey shadow of the item appeared it said Item has no data.
I looked through the controls but there is no use for T.
What di i have to do  to fix this?

**Comment by mezz** [comment]
Thanks for the report!
I'm sorry I have no idea which mod is doing that.
JEI does not use T, and all the keys it uses are listed in the controls.
