### ISSUE TITLE
[1.12] RS block doesn't appear in JEI, but does in creative tab list

### ISSUE THREAD

**Issue by raoulvdberge** [mezz/JustEnoughItems#906]
In Minecraft 1.12:

![x](https://raoulvdberge.com/H9B1qg)
![x](https://raoulvdberge.com/CE57lK)

- Not found when just searching "portable grid"
- Not visible normally in the list without search
- This item has a correct recipe (not sure if that's relevant)

This has a block and a item:
- `BlockPortableGrid`: https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/block/BlockPortableGrid.java
  - No sub blocks are added from here to creative tabs
- `ItemBlockPortableGrid`: https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/item/ItemBlockPortableGrid.java
  - The sub items are added in `ItemBlockEnergyItem`, which `ItemBlockPortableGrid` extends: https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/item/ItemBlockEnergyItem.java#L70-L86

Not sure if this is an RS issue or a JEI issue.

**Comment by raoulvdberge** [comment]
It does work correctly in Minecraft 1.11, but not 1.12 (exact same code):

![x](https://raoulvdberge.com/33DOKK)

**Comment by KingLemming** [comment]
Seeing something like this in 1.11 right now too: https://github.com/CoFH/Feedback/issues/251

**Comment by mezz** [comment]
Thanks for the report!
Looks like it was a JEI bug, the latest version (as of minutes ago) seems to work fine:
![2017-06-17_14 25 22](https://user-images.githubusercontent.com/916092/27256413-df3a76f2-5368-11e7-9215-1533d18becba.png)

**Comment by raoulvdberge** [comment]
It seems to still be broken here (this is in a dev environment - didn't test in a real env yet):

![x](https://raoulvdberge.com/Uh3Ud7)

Using jei_1.12-4.6.0.63.

![y](https://raoulvdberge.com/BEQBLJ)

**Comment by mezz** [comment]
Still works fine for me. Can you upload your log to https://gist.github.com/ and link it here?
