### ISSUE TITLE
fps drop 

### ISSUE THREAD

**Issue by grahamie14** [mezz/JustEnoughItems#907]
Hello i have noticed major fps drop with random searches in jei_1.10.2-3.14.7.419.jar I just figured it was an issue with jei and certain mods like tinkers construct, but today i noticed if i drop my resolution from 4k to 1080p my frames go from 5 fps to 60 fps in the jei menu.  the game runs around 100 fps with around 100 mods installed a resource pack and shaders @3840X2160  so im sure its not a hardware issue. 
gtx 1080  on custom lcs
amd 9590 @5.0 on custom lcs
6 gigs of ram for the game 16 total 
game and OS run off different ssd`s 
only running client on local pc server is hosted
is jei not optimized for 4k or does my issue lie else were ?

**Comment by way2muchnoise** [comment]
Tinkers generally has a slow rendering process and since you likely have 100+ of them on screen it just keeps adding up.

**Comment by grahamie14** [comment]
i see what your getting at and your right.  i just noticed i was getting fps drop with everything i did in the jei menu.  if the issue is to many items overlaying the game it only makes sense to reduce the amount of item being displayed so i went into options and there are new settings that i was not aware of  :(  gui scale now has 4K settings.      problem solved  
@way2muchnoise    Thanks for pointing me in the right direction
