### ISSUE TITLE
Modding workspace crash

### ISSUE THREAD

**Issue by akayumeru** [mezz/JustEnoughItems#908]
I working in modding forge workspace and have installed JEI to see all of my recipies. But it throw crash:
[https://pastebin.com/NTamzCYp](https://pastebin.com/NTamzCYp)

**Comment by mezz** [comment]
Thanks for the report!
It looks like you might be using the obfuscated JEI in your dev environment. Can you paste your build.gradle or whatever you are using to include JEI?

**Comment by Aroma1997** [comment]
Getting the same issue.
I used the obfuscated version as well as the deobfuscated one grabbed from the gradle deobfdeps folder. Same result.
This is when starting up Minecraft, not when building the project, so jei is loaded from just the mods folder.
Full log: http://s.aroma1997.org/2syFI6n

**Comment by mezz** [comment]
I still need to see a gradle setup with this issue, can you link it here?

**Comment by Aroma1997** [comment]
The standard Forge MDK setup. (The one you get from the forge website)

1. Gradlew clean setupDecompWorkspace
2. Import into eclipse as gradle project
3. Add jei to the mods folder
4. Watch it crash.

**Comment by mezz** [comment]
Try setting up JEI using maven like this: https://github.com/mezz/JustEnoughItems/wiki/Getting-Started

**Comment by Aroma1997** [comment]
If I follow the guide you linked and therefore only specify the JEI jar in the build script and do not put it into the mods folder, JEI will not load (and there fore also not crash)

**Comment by Aroma1997** [comment]
Ok, manually adding jei to the launch configuration seems to make it possible to launch minecraft in the dev enviromnent with jei running.
Although mods should be able to load from the mods folder (even in a dev environment), I think this can be closed.

**Comment by mezz** [comment]
Thanks for confirming. I'm not sure why it doesn't work from the mods folder, it is probably a Forge issue.
