### ISSUE TITLE
[1.12] Not seeing RS recipes

### ISSUE THREAD

**Issue by ddrhckrzz** [mezz/JustEnoughItems#909]
Refined Storage items can be seen but recipes of items made only on crafting tables don't work.
![image](https://user-images.githubusercontent.com/19730799/27340536-4d030702-560d-11e7-8b0a-f1a657c4c336.png)
Only Solderer recipes are shown.

**Comment by TehNut** [comment]
Unless RS updated, the 1.12 release has no standard recipes

**Comment by ddrhckrzz** [comment]
How do I make the items then?

**Comment by TehNut** [comment]
You wait for it to update
