### ISSUE TITLE
JEI quick move

### ISSUE THREAD

**Issue by pattonga** [mezz/JustEnoughItems#910]
Is it possible to have quick move [the plus thing] client side. I am playing a really good server and to keep cheat mode off he just disabled the mod in all. So if I try to quick move it says jei not installed on server.

Other note about server:
permissions plugin; Nexus { I read that enables cheat mode so..}

**Comment by mezz** [comment]
Sorry, the transfer function requires the server to cooperate.

Cheat mode is only allowed if you meet one of these requirements:
 * you can use `/give` 
 * you are creative mode 
 * you are OP

Your server admin should not worry about people using cheat mode, and should feel safe installing the mod on the server.
