### ISSUE TITLE
Item tool tips rendering when they shouldn't be

### ISSUE THREAD

**Issue by modmuss50** [mezz/JustEnoughItems#914]
This one is a weird one to explain so have a GIF:

https://modmuss50.me/shots/2017-06-26_10-51-44.gif

How to reproduce, 

Open jei, and spawn in a item, then quickly open a modded gui (TechReborn and forestry have been tested), the tooltip will still be rendered on the mouse. Then open the player inv and mouse over the slots in the player inv, and then quickly open a modded gui.

Sorry if my explanation is shit, ask if you want some more details.

**Comment by Kris1432** [comment]
Something to back it up; https://www.youtube.com/watch?v=Lp1t4IOkPus

**Comment by mezz** [comment]
It looks like both those guis do not call `GuiScreen#drawDefaultBackground`.
Either that or JEI is breaking it somehow.

**Comment by mezz** [comment]
Ugh mojang moved all the calls to `drawDefaultBackground` so it's not done by default. This is now an issue of all modded guis looking wrong haha.

**Comment by mezz** [comment]
Fixed in Forestry https://github.com/ForestryMC/ForestryMC/commit/39290512cffb1bd1e79b5df8fd074a9fcd43ffe6

**Comment by mezz** [comment]
Fixed in the next JEI version, it will render normally beside guis that do not draw a background.
