### ISSUE TITLE
crash when clicking TIC smeltry liquids

### ISSUE THREAD

**Issue by robjw95** [mezz/JustEnoughItems#917]
when I click on a tinkers smeltry liquid such as Aluminium Brass it crashes, but if I search for smeltry alloy recipes it is listed fine.  here is the crash report.
[crash-2017-06-29_05.29.53-client.txt](https://github.com/mezz/JustEnoughItems/files/1111568/crash-2017-06-29_05.29.53-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Please report this to codechicken lib here: https://github.com/TheCBProject/Feedback/issues

**Comment by robjw95** [comment]
no need the new version of codechickenlib just release has fixed this issue.  no longer crashes
