### ISSUE TITLE
[1.11.2] Lag when opening inventory for first time with hi-res resource pack

### ISSUE THREAD

**Issue by Malkierian** [mezz/JustEnoughItems#919]
I don't even know if there's anything you can do about it, but I do know that this particular lag is only because of the resource pack, not because of any other mods (tested it with only a few cores, JEI, and JourneyMap).  For the record, I can still notice a split-second lag with no resource pack and no other mods, it's just so small it's usually not noticeable.

I also was wondering if there was a particular reason why loading JEI's item displays couldn't happen while the game was loading, or while the world was loading, instead of when you open the inventory, and why it has to do it all over again every time you close and reopen the game and open the inventory for the first time.

**Comment by mezz** [comment]
Thanks for the report!
JEI displays items pretty much the same way as a vanilla inventory.
I'm not sure why there would be a delay at all.
The only times I have seen a delay are from items that fetch extra data slowly, like player heads.
