### ISSUE TITLE
crash upon loading multiplayer

### ISSUE THREAD

**Issue by Goldentuf** [mezz/JustEnoughItems#920]
The game loads with a start screen however is any buttons are pressed it crashes. it refused to let me view crash report 
[![Screenshot from Gyazo](https://gyazo.com/d347c018d8f6ca84fb6698fff16f1afc/raw)](https://gyazo.com/d347c018d8f6ca84fb6698fff16f1afc)
This is what my error looks like 

The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/ItemListOverlay;

**Comment by mezz** [comment]
Thanks for the report!
You can find the crash log in the `crash-reports` folder in your minecraft instance.
Please upload the latest crash report to https://gist.github.com and link it here.

**Comment by KnightMiner** [comment]
The launcher is currently a bit broken when it comes to crash reports. You can find the report in your pack's directory (possibly in .minecraft or in the curse launcher pack directory

**Comment by Goldentuf** [comment]
https://gist.github.com/Goldentuf/ccc0e49da4dc97eaac3ab319826e0859

**Comment by mezz** [comment]
This crash is caused by NEI, please try removing it.
You can report this issue to NEI here: https://github.com/TheCBProject/NotEnoughItems/issues
