### ISSUE TITLE
[1.11.2] Block from Tinker Construct being hidden ?

### ISSUE THREAD

**Issue by nigrum-dente** [mezz/JustEnoughItems#923]
So I have been playing for a while in my world and I wanted to make some tool from Tinker Construct, so I pulled JEI and searched: "@tconstruct"

Only to notice that several block were not shown, their recipe are still acessible but they don't popup when searching in JEI.

Here is a screen showing it:
![2017-07-05_23 06 31](https://user-images.githubusercontent.com/28484707/27885160-49337b04-61d7-11e7-92f3-ead51da9150f.png)

And while it's not bothering me too much as I can still find the recipe by searching related item, it's still quite annoying that they are hidden, not sure why it happen as around 3 day ago it worked fine, the only reason I can think of that would create those problem would be because I added Biome O' Plenty and Forestry

But I don't see why it would cause problem (maybe the fact that each of these 2 mod add wood and that since Tinker Construct dynamically render texture using nbt tag and create varation of them using oredictionnary, forestry and Biome O' Plenty add so much wood that it decided to hide block such as the pencil table ? Not sure, don't know enough about JEI and Tinker Construct to be certain)

**Edit | _5 June 2017 23:40_:**
Checked the creative tab to see if the block where there and indeed they exist:
![2017-07-05_23 39 22](https://user-images.githubusercontent.com/28484707/27886220-6a7d3576-61db-11e7-99c4-b4a5f3bb4c4e.png)

**Comment by mezz** [comment]
Thanks for the report!
What version of JEI are you using? The latest version should work fine.
JEI hides items with more than 300 subtypes now, older versions hide items with more than 100.

**Comment by nigrum-dente** [comment]
Ah ok

I use version 4.5.0.291

But would it be possible that instead of simply hiding all the subtypes, that it would show just one of those subtypes ?

**Comment by nigrum-dente** [comment]
So using what you said I checked the item in the creative tab and looked at their id and every table (except the tool forge) in Tinker Construct exist under 1 id:

- Crafting station: #5952/0
- Stencil table: #5952/1
- Part builder: #5925/2
- Tool station: #5952/3
- Pattern chest: #5952/4
- Part chest: #5952/5

And I counted together they sum up to around 323 item, which mean that JEI see those as 1 item with 323 subsets and hide them all

A possible solution could be to show 1 subset from each metadata possible value.

**Comment by KnightMiner** [comment]
There is no way to do that on JEI's side, the table wood variants and the alternate table types are added in the same method due to how vanilla makes things.

There is a config option on Tinkers side to show just one table of each type which would fix this.

**Comment by nigrum-dente** [comment]
Ok thanks, found the config option, thanks for the help

**Comment by KnightMiner** [comment]
Glad I could help. This issue could probably be closed now since its technically not a JEI issue.

Though @mezz, out of curiosity what is the reason for this configuration? Are there specific items causing issues? Alternatively, why does it not simply ignore variants after the 300th instead of entirely removing the item from JEI?

**Comment by mezz** [comment]
Mods that generate items dynamically, like covers, multiparts, etc, can really clog up JEI and even slow it down. There's also not a lot of benefit to displaying them all, so I added a config to stop showing them once they're above a certain number. Thousands of buildcraft covers had broken, crashing models and made JEI startup much slower, so I added this config.
