### ISSUE TITLE
[1.11.2] Tooltip render bug

### ISSUE THREAD

**Issue by Endmateria** [mezz/JustEnoughItems#924]
Hey Mezz, I've been throwing this issue around and nobody seems to want to take responsibility for it, though Ellpeck seems to think that it might have something to do with JEI https://github.com/Ellpeck/ActuallyAdditions/issues/834 .  It's an overlap that occurs in the tooltip box for several items in a bunch of different mods.  I referenced two of them (Actually Additions and Underwater Utilities) in this issue thread https://github.com/Vazkii/Quark/issues/417 (see referenced sub-links as well), but there are dozens more mods affected.  It's seems to be triggered by Quark, but according to Vazkii, can also be triggered by any other mod that adds content to the tooltip render box.  I finally got a response from Vazkii, and though the initial report is kinda old, it's still happening with the most current version of JEI for 1.11.2.

**Comment by mezz** [comment]
Hmm seems you're getting the runaround I agree.
I'll reply on Quark's issue.
