### ISSUE TITLE
1.10.2 Crash when viewing recipe

### ISSUE THREAD

**Issue by JosLouis** [mezz/JustEnoughItems#925]
Every time I look up the recipe for Iron to Gold Upgrade in Iron Chests, I crash. I tried to remove NEI but I still crash. I'm not entirely sure if JEI is even the cause for this, I have optifine and foamfix installed, but I still crash without them. Any help?
Here is the crash log: https://pastebin.com/xXRc8TLp

**Comment by quinttt** [comment]
having the same error when using recipe or looking at item uses.

**Comment by GrumpNugget** [comment]
i think i'm having the same issue also 1.10.2
Crash Log: https://pastebin.com/k8JLqzY6

**Comment by KnightMiner** [comment]
You say this happens without Optifine, FoamFix, and NEI, so can you link a clean crash report without any of those mods? Reproducing this with minimal core mods would help quite a bit as the crash report would be easier to debug. Darkhax's Boofshelf API is also in the stack trace, though it could also be unrelated to the crash so removing it as well would help

From what I can tell from reading it, `mrtjp.core.block.ItemBlockCore` is the item being rendered, though being from a library mod its hard to tell which mod's item that is. This is probably not a JEI issue but rather an issue with whichever mod has a broken item renderer.

**Comment by GrumpNugget** [comment]
So i've started it up a few times now without Optifine; Foamfix; or Bookshelf API.
I've also removed most of the JEI Plugins as well.

The game is still crashing when trying to look at the recipes for items through JEI.
I've tried different items each time from different mods and it crashes on trying to view the recipe for all of them.
Item Recipe's Attempted to view so far: 
Engineers Skyhook -Immersive Engineering
Enderchest -Enderstorage
Diamond Block -Vanilla Minecraft (This one briefly showed the recipe before crashing, but showed the same error in the crash report.)
Diamond Chisel -Chisels and Bits

Latest Crash Report: https://pastebin.com/5xHcmH0Z

**Comment by JosLouis** [comment]
Here is the crash log without Optifine or NEI: https://pastebin.com/pzyYrjjL
Without Foamfix, I crash during the loading screen because I run out of memory. Also, if it matters, I've crashed no matter what item I view in JEI, even vanilla items. I did not have Optifine installed when I was testing this.

**Comment by quinttt** [comment]
interesting: so I deleted the config deleted JEI and installed version 1.10.2-3.14.7.416 the release from march of this year and it still happens.......
how exactly does this mod work? 
is it getting the data from the cloud? 

ALSO: I deleted JEI / JER and their configs and installed NEI and had the same crash 

edit: 531PM EST (  https://pastebin.com/dFWNb3Zm  ) yes it is heavily modded but I think just about any mod that changes vanilla items seems to cause this crash - just a guess -

**Comment by KnightMiner** [comment]
You still have chicken code lib/core which could be related as it's showing in the stack trace, doe sir happen without that? Try and find the minimal mods to reproduce, as it still seems unrelated to JEI, just someone breaking item rendering.

**Comment by covers1624** [comment]
Caused by someone requesting CCL models to do stuff then mod bakerys breaking due to data not existing on their blockstate, checks are being added CCL side to catch this, it can be closed, not JEI.

**Comment by JosLouis** [comment]
There are 13 other mods that are dependent on code chicken lib, I technically shouldn't remove that mod. Until there's a fix for this, I'm going back to 1.7.10.

**Comment by covers1624** [comment]
Literely just waiting for approval on curse for the hot fix to be live....

EDIT: Fixes for 1.10 and 1.11 are live.

**Comment by JosLouis** [comment]
Alright everything seems to be working again, thanks.

**Comment by quinttt** [comment]
updated CCL and ... Ha HA! it seems to be working! Thank you!

**Comment by covers1624** [comment]
Good that everything is working now. Not to be a dick at all but next time, don't get heated and ragequit to an older version just because the issue is not fixed 5 seconds after you open an issue, we have lives, and the only reason i even responded to this issue was because i was poked on Twitch messenger about it, Again not trying to be a dick, but we all have lives, and things take time.

**Comment by JosLouis** [comment]
I wasn't heated, nor did I ragequit. I simply went back to 1.7.10 because there's been a pack that I've been wanting to try that was on 1.7.10, and this was the perfect opportunity to play it.

**Comment by covers1624** [comment]
That may be the case, but from your comment and the way it was worded it didn't come across that way.

**Comment by JosLouis** [comment]
Oh, yeah that's my bad. Next time I'll work on my wording.

**Comment by GrumpNugget** [comment]
@covers1624 Oh cool. thanks for looking at this. i appreciate it. I was having the same problem myself. xD
Also confirmed working fine now.
