### ISSUE TITLE
Double Click Unresponsive in Turning Off Search Highlight

### ISSUE THREAD

**Issue by aelfwyne** [mezz/JustEnoughItems#926]
As title says... Double click often is completely unresponsive in attempting to turn off search highlight. Honestly I never even want this enabled, but it gets turned on by mistake. Then trying to turn it off I keep double clicking on the box, around the box, over the box, under the box, in the box, etc and it refuses to unhighlight. Once in a blue moon I get lucky and it will finally disable the highlight.

Please provide a RELIABLE way to disable this.

**Comment by TehNut** [comment]
This is not a feature added by JEI. [Here's a chart](https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0) that shows what mods might be adding it for you.
