### ISSUE TITLE
[1.11.2] build 291 crashes dedicated server forge build 2388 on startup

### ISSUE THREAD

**Issue by kreezxil** [mezz/JustEnoughItems#927]
Notes:
rolling back to build 290 solves the problem. Sadly neither of logs "appear" to me to indicate JEI, it was only after loading mods 1 by 1 that I found it. I'm able to reproduce it but I accept that you might not be able too.

In both of report logs
crash report:
https://gist.github.com/92e53200787996b03236cb904fd3c3c8

fml server latest:
https://gist.github.com/1c31ffc39405419f31487a944ac1331f

**Comment by mezz** [comment]
Thanks for the report!
I'm not able to reproduce this issue, please try with just JEI and Forge.
