### ISSUE TITLE
Crash when try to see some fluid recipe in 1.11.2

### ISSUE THREAD

**Issue by ghetta82** [mezz/JustEnoughItems#928]
Hi, i crash when try to see some fluid recipe. Is it possible something with your mod? or can u help me pls?

mc 1.11.2
forge 13.20.1.2393

Crash-report: https://gist.github.com/ghetta82/63a49f1cfb7fbaa3459fc75fc5c2193d

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with Advanced Rocketry, you can follow its progress here: https://github.com/zmaster587/AdvancedRocketry/issues/721
