### ISSUE TITLE
JEI overlay not even showing

### ISSUE THREAD

**Issue by xNightFoxx** [mezz/JustEnoughItems#929]
http://prntscr.com/ft6blb

I've toggled the overlay countless times and the overlay just doesn't show.

**Comment by xNightFoxx** [comment]
Ive realized that JEI does not work with 5zig, any chance that it will?

**Comment by mezz** [comment]
Did you figure out what went wrong?

**Comment by xNightFoxx** [comment]
Yes, JEI does not work with 5zig on 1.11.2 atleast.
