### ISSUE TITLE
Extra Utilities has a super super handy function, that would be great for this

### ISSUE THREAD

**Issue by koalalord9999** [mezz/JustEnoughItems#93]
When you play vanilla, or any mod pack without a centralized storage system (AKA needing hundreds of chests) it allows you to press T while hovering over an item in 'nei' or in this case, would be JEI, or your inventory, or another chest, it would highlight any chests within a chunk distance away (I believe it calculates the chunk your in, extends out a chunk, enclosing a 3x3 chunk area probably by 10 up/down) that contain the item. This highlight it just a bunch of smoke particles over the chest that contains the item. These particles can be seen through the ground/walls etc.

I think having this as a default feature could be handy, and would be a nice addition to singleplayer and even multiplayer (when forge fixes their stuff). :)

**Comment by TehNut** [comment]
This would fit more into another mod than JEI or JEI Addons, IMO.

**Comment by koalalord9999** [comment]
snip

**Comment by koalalord9999** [comment]
woops lol

**Comment by mezz** [comment]
I think this is outside the scope of JEI or JEIAddons. I really want these mods to be basic. 
Another mod could work with me to integrate with JEI and add that feature though.
