### ISSUE TITLE
Blacklist Being Partially Cleared On Startup

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#930]
JEI's blacklist is being modified, and a lot of entries are being removed when I run the game.

**JEI version:** [4.7.1.74](https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2447964)
**Forge version:** [1.12-14.21.1.2404](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2404/forge-1.12-14.21.1.2404-changelog.txt)

Blacklist contents before loading the game: [paste.ee/DV4u0](https://paste.ee/p/DV4u0)
Blacklist contents after loading the game: [paste.ee/twyhH](https://paste.ee/p/twyhH)

Game log with `B:debugModeEnabled=true` in JEI's config: [paste.ee/5n7yZ](https://paste.ee/p/5n7yZ)

**Comment by mezz** [comment]
@InsomniaKitten was this issue resolved?

**Comment by ChloeDawn** [comment]
I haven't been able to reproduce the issue since, it just kinda.. stopped happening.. and I never figured out what exactly had caused it.

**Comment by mezz** [comment]
Ok. Let me know if it comes up again.
