### ISSUE TITLE
Not Showing The Search UI.

### ISSUE THREAD

**Issue by crazyamri** [mezz/JustEnoughItems#931]
Hi there.

I just got this problem, never happen earlier today. I thought it was a bug, so i've updated into the latest version. However, the problem persist. In need help, please.

The UI shows in creative world, but not in survival. I can't figure out what the problem is. There's no crash, it just not there.

Thanks.

![screen shot 2017-07-10 at 06 19 54](https://user-images.githubusercontent.com/29984658/27998096-b15b049a-6538-11e7-8376-5a6b74bed4ee.png)
![screen shot 2017-07-10 at 06 21 33](https://user-images.githubusercontent.com/29984658/27998097-b16045f4-6538-11e7-918b-dab74cc89f0b.png)

**Comment by way2muchnoise** [comment]
Did you try the toggle? It is on ctrl+O by default

**Comment by crazyamri** [comment]
still no luck, still not showing. i also did try to change the key, still no luck.

**Comment by mezz** [comment]
Thanks for the report!
Please paste your `fml-client-latest.log` to https://gist.github.com/ and link it here.

**Comment by crazyamri** [comment]
here are the link to the gistgithub.

https://gist.github.com/crazyamri/f6fad2f45196e2aa86c1a921ec8d0b31.js

**Comment by crazyamri** [comment]
here are the link

https://gist.github.com/crazyamri/f6fad2f45196e2aa86c1a921ec8d0b31

**Comment by mezz** [comment]
Unfortunately I don't see anything strange in your log.
Try deleting the JEI config folder, that's where it stores whether the overlay is toggled on or off.
If that doesn't work, try removing some of your mods to see if one of them is causing it this to happen. Start with mods that are visible in your inventory at the same time as JEI.

**Comment by crazyamri** [comment]
thank you. it works again after deleting the config folder.
thanks again.

**Comment by mezz** [comment]
Ok, glad that was it. I wonder if you have a key conflict or something, it should be pretty easy to toggle JEI on and off with the hotkey.
