### ISSUE TITLE
[1.12] Weirdness w/ Mod Name Tooltip

### ISSUE THREAD

**Issue by SnowShock35** [mezz/JustEnoughItems#932]
Hi @mezz,

I believe I have found a bug with Just Enough Items for Minecraft 1.12. Listed below is further detail on the issue:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2407
- Just Enough Items (JEI) 1.12-4.7.1.75
- Other Mods:
  - Mod Name Tooltip 1.12-1.8.1

### Issue Description

When installed alongside Mod Name Tooltip, all fluid blocks in JEI do not show the correct mod name tooltip. Mod Name Tooltip is overriding every item/block as it should when it's installed, but it fails to do so with fluids in JEI. I noticed this after changing JEI's mod name tooltip format in the config to plain white as the italic blue looked off in the newly added recipe is from x mod tooltip. 

###### Regular Item

![](https://ss.blamesnow.co.uk/2017/07/1499892420-389d4c6c.png)

###### Fluid Block

![](https://ss.blamesnow.co.uk/2017/07/1499892596-3730e62e.png)

**Comment by mezz** [comment]
For ingredients that do not have an itemstack representation, JEI uses its own mod name formatting. You can change the formatting in the in-game config.

**Comment by SnowShock35** [comment]
@mezz I guess I wasn't clear enough. This is the config that I changed. However in doing so now fluid tiles in JEI also get that style instead of getting the mod name tooltip one.

**Comment by mezz** [comment]
The fluids for water and lava in JEI do not have an ItemStack representation. ModNameTooltip can only work on ItemStacks.
I guess what I can do is make JEI match the config of mod-name-tooltip mods when it draws the tooltip for fluids and other things.

**Comment by SnowShock35** [comment]
That could work. Or perhaps add a separate config for the tooltip in the recipe viewer for seeing what mod it's from. I could see either of those working well. 🙂

**Comment by mezz** [comment]
The tooltips will automatically match the config from mods like ModNameTooltip and Waila in the next release.
