### ISSUE TITLE
1.12 Reference to ExU2 indexer crash

### ISSUE THREAD

**Issue by DingoX3** [mezz/JustEnoughItems#934]
https://github.com/rwtema/extrautilities/issues/1578

I wasn't sure so I thought I'd let take a look at this too. Please disregard if not applicable to a jei issue. Thanks.

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with ExU2's JEI integration. It has an `IAdvancedGuiHandler` which returns an empty ItemStack.
I can protect against this issue pretty easily on my side though, so I will just do that.
