### ISSUE TITLE
Issue with seeing recipes

### ISSUE THREAD

**Issue by randomfreak11** [mezz/JustEnoughItems#935]
I don't know if it's because the modpack specifcally disables some recipes, or if it's JEI that just isn't showing them.
![image](https://user-images.githubusercontent.com/30179691/28216298-17e77df8-687f-11e7-9a1f-ab5bc045db0b.png)
This is what happens when I try to look at the recipe of a backpack from Backpack (oddly enough it doesn't happen with the bound / treated leather)
The same thing happens when trying to look at a IC2 item (most if not all)
![image](https://user-images.githubusercontent.com/30179691/28216385-888abc64-687f-11e7-93d7-a15ec6dac474.png)

**Comment by mezz** [comment]
Thanks for the report!
Please remove NEI and see if you still have any issues.

**Comment by randomfreak11** [comment]
Hmm...I guess it's just the NEI side of the mod. I didn't remove anything, but when I switched the UI back the the JEI integration (or at least I thought it was just UI) it fixed itself. Thanks anyways :P

**Comment by randomfreak11** [comment]
![image](https://user-images.githubusercontent.com/30179691/28239371-fb6291c6-6938-11e7-8240-617db5258d34.png)
![image](https://user-images.githubusercontent.com/30179691/28239377-12a08096-6939-11e7-807c-aa4c4def4efc.png)

Images to show what im talking about.

**Comment by randomfreak11** [comment]
Also:sidenote only the tier 3 backpack recipies are showing for the mod Backpack

**Comment by mezz** [comment]
NEI is a separate mod, please report to them here: https://github.com/TheCBProject/NotEnoughItems/issues

For issues with Backpack recipes, please report to the Backpack mod authors.
