### ISSUE TITLE
[1.10.2] JEI crashing when searching.

### ISSUE THREAD

**Issue by Pandomas** [mezz/JustEnoughItems#936]
JEI is crashing when i start typing in the search bar. I have tryed with and without NEI.

I'm using minecraft 1.10.2

 * Crash log [Crash](https://gist.github.com/Pandomas/19a768e228e57de6076b3aa0a564aea6)

**Comment by TehNut** [comment]
Probably related to https://github.com/AgriCraft/AgriCraft/issues/1034

**Comment by mezz** [comment]
Thanks for the report!
Yep this is an Agricraft issue unfortunately.

**Comment by Pandomas** [comment]
Thanks so much wow this Github is the best.
