### ISSUE TITLE
Having an issue just getting it to load.

### ISSUE THREAD

**Issue by NyteLyfe** [mezz/JustEnoughItems#938]
Im running the required version of forge (tried the top 3 latest versions including recommended) but JEI is saying im not running the required version. Any help? Im dying to have a mod like this back. Im running 1.12...proper forge...proper download from your site. Any help is appreciated

Roy

**Comment by mezz** [comment]
Thanks for the report!
The error screen there is never wrong, please check the version number carefully. 
You will probably need the "latest" and not the "recommended" version.
