### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#94]
If you're ever super bored and have nothing to do, make JEI uber mode. Basically it would make JEI fill up every available blank spot around a GUI.

This is half joke, half serious. Perhaps there could be a hotkey for like a "fullscreen" mode or something? It would make an overlay on top of anything (like the thaumonomicon sorta) that is just pure JEI.

**Comment by koalalord9999** [comment]
You mean something where the icons from the item list show up around an inventory? That sounds... weird but oddly interesting at the same time lol

**Comment by Prospector** [comment]
Exactly.

**Comment by mezz** [comment]
Ehh I'm not sure I like this idea. I think having a giant item list would be overwhelming. If you really like seeing tons of items you can set your gui scale smaller.

**Comment by Prospector** [comment]
I'm in the process of porting harvest craft and it would be useful to see
it all on 1 page. Even on small size it's three pages.

**Comment by Prospector** [comment]
And that's just the food

**Comment by ColinGBos** [comment]
It sounds like this would break more than would be worth, but I'm not sure how the bounds for the existing gui on any screen are actually determined, adding another dimension to the "don't draw here" area might be bad...

**Comment by mezz** [comment]
I don't really understand the need to see everything at the same time.

**Comment by Prospector** [comment]
That thing was more of a joke, but the full screen mode was not. It wouldn't wrap the GUI, it would be an overlay.

**Comment by mezz** [comment]
I don't really see full-screen mode as an essential feature, and it would be strange to use combined with looking at recipes. The more modes I add the harder it is to make changes and bug fixes, so the feature needs to have a more compelling use-case.
