### ISSUE TITLE
JEI Keeps crashing 1.11.2

### ISSUE THREAD

**Issue by possessivebob255** [mezz/JustEnoughItems#941]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by possessivebob255** [comment]
Basically, when i deleted NEI, since it caused lots of lag, i went back on minecraft. It kept saying that i was running a unsupported version of minecraft. And i was kind of frustrated after time and time deleted 2 mods that weren't the reason, searched up how to fix this, had to reinstall EVERY mod (wasn't a whole lot) and yet i come back on. It says the same thing. I deleted JEI, it was fine after that, I cant find a single good recipe viewer as they are too outdated, this other one doesn't show modded crafted things, i mean by if a modded crafting thing like the age of weapons table, it wont show the recipes for things made in the table.
Either, you can show me a new one that actually works, or you can tell me how to fix this.

**Comment by possessivebob255** [comment]
It keeps saying that im using a unsupported version of minecraft, i tried everything. And all the crashes were because of JEI, as if i uninstalled it. It would work fine, when i had it, it was crashing. This only happened after i deleted NEI

**Comment by mezz** [comment]
Thanks for the report!
Sorry but from your description I have no idea what your error is. Do you have a crash log or a screenshot? JEI should work fine on 1.11.2.

**Comment by possessivebob255** [comment]
Doesn't load the crash report, i'm probably too lazy. I will try it again.

EDIT: I tried it, once again said the same thing "You were running a unsupported version of the game"
For the last maybe 10 times. This all started happening when i deleted NEI and Codechickenlib, Also clicking "Show crash report" Does nothing.

**Comment by possessivebob255** [comment]
I tried it, once again said the same thing "You were running a unsupported version of the game"
For the last maybe 10 times. This all started happening when i deleted NEI and Codechickenlib

**Comment by mezz** [comment]
There is no message that exactly matches what you typed.
Unless I can see a crash log, I do not know what you are experiencing and I cannot fix it.

Crash logs are in your minecraft installation folder under the `crash-reports` folder. You can paste the crash log to [gist](https://gist.github.com/) and link it here.
If there are no crash logs in that folder, you can check the `logs` folder for `fml-client-latest.log` and paste that to gist instead.

**Comment by possessivebob255** [comment]
Thanks, i found the report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.6.14-universal.jar)
  IC2core (industrialcraft-2-2.7.74-ex111.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/18/17 10:40 PM
Description: Unexpected error

java.lang.IllegalStateException: Ingredient Filter has not been created yet.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at mezz.jei.Internal.getIngredientFilter(Internal.java:100)
	at mezz.jei.startup.ProxyCommonClient.onClientTick(ProxyCommonClient.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_174_ProxyCommonClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at mezz.jei.Internal.getIngredientFilter(Internal.java:100)
	at mezz.jei.startup.ProxyCommonClient.onClientTick(ProxyCommonClient.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_174_ProxyCommonClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['possessivebob255'/2336, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['possessivebob255'/2336, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: ~~NULL~~
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 423954128 bytes (404 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.1.2414 Optifine OptiFine_1.11.2_HD_U_C3 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2414.jar) 
	UCHIJAAAA	forge{13.20.1.2414} [Minecraft Forge] (forge-1.11.2-13.20.1.2414.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	dmonsters{1.52} [Deadly Monsters] (1.11.2_deadly_monsters_1.52.jar) 
	UCHIJAAAA	ageofweapons{0.9.1} [Age of Weapons] (Age of Weapons 1.11.2 (v.0.9.1).jar) 
	UCHIJAAAA	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCHIJAAAA	cofhcore{4.2.6} [CoFH Core] (CoFHCore-1.11.2-4.2.6.14-universal.jar) 
	UCHIJAAAA	animania{1.2.1} [Animania] (animania-1.11.2-1.2.1.jar) 
	UCHIJAAAA	battletowers{1.5.8} [Battle Towers] (BattleTowers-1.11.2.jar) 
	UCHIJAAAA	codechickenlib{3.0.0.284} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.5.jar) 
	UCHIJAAAA	guidebook{1.7.0} [Guide Book] (guidebook-1.7.0.jar) 
	UCHIJAAAA	ic2{2.7.74-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.74-ex111.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
	UCHIJAAAA	jei{4.5.0.293} [Just Enough Items] (jei_1.11.2-4.5.0.293.jar) 
	UCHIJAAAA	kagic{1.8.6} [KAGIC] (KAGIC-1.8.6.jar) 
	UCHIJAAAA	minecolonies{1.11.2-0.8.3136} [MineColonies] (minecolonies-universal-1.11.2-0.8.3136.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	thermalfoundation{2.2.4} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.4.15-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.2.5} [Thermal Dynamics] (ThermalDynamics-1.11.2-2.2.5.12-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.2.5} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.5.20-universal.jar) 
	UCHIJAAAA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.6.14-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
IC2core (industrialcraft-2-2.7.74-ex111.jar)
  
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1055.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: 1.11.2-forge1.11.2-13.20.1.2414
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R5 Graphics GL version 4.5.13397 Compatibility Profile Context 15.200.1055.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-7410 APU with AMD Radeon R5 Graphics 
	OptiFine Version: OptiFine_1.11.2_HD_U_C3
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13397 Compatibility Profile Context 15.200.1055.0
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by mezz** [comment]
Hmm thanks.
It looks like JEI might have died before getting to the point where you load the game.
Can you check the logs folder for `fml-client-latest.log`, paste that to https://gist.github.com/, and link it here?

**Comment by possessivebob255** [comment]
Sorry i didnt respond, but i think i may be fine without just enough items, while posting this comment. I was loading up mc, so im checking if it works. It worked when i got my xbox one. It wouldn't work, then the next day, it worked.

**Comment by bspkrs** [comment]
You've heard it here first, folks... buying an XBox One can actually fix defects in Java code!

**Comment by possessivebob255** [comment]
Already have one.
