### ISSUE TITLE
Minecraft crashes while rendering item in JEI

### ISSUE THREAD

**Issue by Garagoth** [mezz/JustEnoughItems#944]
Took me a while but seems pretty easy after all, but I am still not sure where this should be reported.
Required for crash: JEI, forge multipart, lithos core resourcepack.

Due to resourcepack providing bad texture for bookshelf microblock, JEI crashes game as soon as it wants to render bookshelf microblocks (try searching for book).

[Crash report](https://gist.github.com/Garagoth/7af94f924a0dab749a8cf58711877b84)

Removing Lithos core or using different resourcepack makes the problem disappear, but still I guess this should not crash the game?

**Comment by TehNut** [comment]
This would be an issue on their end. JEI renders items almost identically to vanilla.

**Comment by mezz** [comment]
Thanks for the report!
This seems to be cause by CodeChickenLib, make sure you have the latest version of that mod.

**Comment by Garagoth** [comment]
1.10.2-2.5.9.283, seems like latest on curse.

**Comment by mezz** [comment]
Ok thanks, I guess this is a CCL issue then.
