### ISSUE TITLE
[1.10.2] Recipes changed by CraftTweaker are not shown at the start of the game or when changed.

### ISSUE THREAD

**Issue by k1rowashere** [mezz/JustEnoughItems#945]
#### Issue Description:
 Recipes changed by CraftTweaker are not shown **at the start of the game** nor when changed even after `/mt reload`; it requires a manual reload. Instead, it shows the default recipes. 

#### What you expected to happen:
Automatically reloading after `/mt reload` and after the start of the game.

**Notes:**
I've found the same bug reported in 2016 several times, and it says that it is fixed, maybe there is something I am missing out? Please help if so.
btw, do I report it to crafttweaker too?
Thanks for helping.
#https://github.com/mezz/JustEnoughItems/issues/537
#https://github.com/mezz/JustEnoughItems/issues/705

JEI Verison: 3.14.7.420
CraftTweaker Verison: 3.0.26

**Comment by mezz** [comment]
Thanks for the report!
This is an issue on crafttweaker's side. Please make sure you have the latest version of the mods and report to them if you still experience this issue.
