### ISSUE TITLE
Crash When Attempting to Render Searched Items

### ISSUE THREAD

**Issue by Laruae** [mezz/JustEnoughItems#946]
I appear to be experiencing a crash to desktop when certain items have issues being rendered properly. Not sure which mod is actually causing the render issue, and will be posting to each mod's issues section in order to get the opinion of each author. 

Here is the gist link for the error log. Thanks for your time, love the mod!

[Error Log Gist](https://gist.github.com/Laruae/40f6a1d75d96227b0f6c81f12a59d41f)

**Comment by mezz** [comment]
Thanks for the report!
This is caused by Thermal Expansion or CodeChickenLib, but I think they have fixed it in the latest versions.
Try updating these mods and let me know if that fixes the issue.
