### ISSUE TITLE
[1.11.2] JEI list completely disorganized

### ISSUE THREAD

**Issue by TeknoKit** [mezz/JustEnoughItems#947]
After updating to 1.11.2-4.5.0.293 the entire list of items is disorganized, in a vaguely alphabetized order by the meta 0 item, but even then some items are out of place.
Going back to 1.11.2-4.5.0.292 shows a normal list sorted by ID again.

**Comment by mezz** [comment]
Thanks for the report!
Listing the version that broke really narrows down the issue. I'll take a look.

**Comment by mezz** [comment]
This is fixed in the next build.
