### ISSUE TITLE
The World Isn't Loading!

### ISSUE THREAD

**Issue by GTAtutu2001** [mezz/JustEnoughItems#949]
I tried making a mod-pack and I need JEI to see the recipes and when I try to open/create a world with the mod JEI added it only says "Loading".

**Comment by mezz** [comment]
Thanks for the report!
Can you please paste your `fml-client-latest.log` to https://gist.github.com/ and link it here?

**Comment by GTAtutu2001** [comment]
Here it is: 
https://gist.github.com/GTAtutu2001/0ab5e4e964a847b48ed0ebf8c48d7c94

**Comment by mezz** [comment]
It looks like something is causing the world to save when you join it.
I'm not exactly sure how JEI would be involved with this issue.
Can you try removing other mods besides JEI to see if one of them is involved?

**Comment by GTAtutu2001** [comment]
The mod-pack works fine without the JEI mod. And I already played it for 2 hours I think. I tried creating a world with only JEI and it works fine so it must mean one of the mods it messing with JEI or the other way. So I think I must search which mod does that.
