### ISSUE TITLE
Item hover overlay is being rendered behind the items.

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#95]
In normal GUIs, the light-grey overlay that appears when hovering over an item appears in front of an item, but in JEI it is rendered behind the item. I don't really care if this is changed or not, but it's something I noticed.

**Comment by mezz** [comment]
I remember asking @tterrag1098 about it and he implemented it that way on purpose, I don't remember why though. tterrag can you explain?

**Comment by ColinGBos** [comment]
It looks better being rendered behind?

**Comment by tterrag1098** [comment]
I wouldn't have done that on purpose. It's very tricky to get depth right in GUIs. This is a bug for sure.
