### ISSUE TITLE
Search Box Crash

### ISSUE THREAD

**Issue by FitmoGamingMC** [mezz/JustEnoughItems#952]
When i Type Pi in the search box it crashes

**Comment by mezz** [comment]
Thanks for the report!
Please paste your crash report to https://gist.github.com/ and link it here.

**Comment by jhollowe** [comment]
I have the problem also (it happened when I searched "s" while typing "seed", but I think the search term is not the issue).
https://puu.sh/x7xhH.txt

**Comment by mezz** [comment]
@JohnHollowell thanks, yours looks like a crash from Chisel, please report it here: https://github.com/Chisel-Team/Chisel/issues

**Comment by Kris1432** [comment]
You can close this issue now @mezz
