### ISSUE TITLE
JEI wont respond 1.10.2

### ISSUE THREAD

**Issue by LeatherBack101** [mezz/JustEnoughItems#954]
Jei stops responding from a compatibility issue with The Camping Mod 2 after putting a map in the designated slot of The Camping Mod 2's UI.
But pulling the map out of the UI seems to allow jei to function normally.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to The Camping Mod 2 here: https://github.com/Rikmuld/MC-Camping/issues
