### ISSUE TITLE
1.10.2 Game Crashes after typing into the search bar

### ISSUE THREAD

**Issue by ImperfMage** [mezz/JustEnoughItems#955]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.
----
as the title says it crashes my game every time i try to type something
[Crash Log](https://gist.github.com/ImperfMage/e2022ab87db876545c06cfebe0070907)

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with infinitylib, reported here: https://github.com/InfinityRaider/InfinityLib/issues/20
