### ISSUE TITLE
JEI Crashing my Custom Pack when i am just going to 3rd page!

### ISSUE THREAD

**Issue by averyrichardson** [mezz/JustEnoughItems#956]
https://gist.github.com/mezz/cf8803b22b8e2c804b492a6bf549f090

**Comment by EmanYm** [comment]
>Details:
	Atlas path: textures
	Sprite: TextureAtlasSprite{name='openblocks:items/stencil-primer', [...]

"openblocks:items/stencil-primer"
It looks like it's a texture for OpenBlocks' Stencil Primer

**Comment by Ommina** [comment]
See also https://github.com/OpenMods/OpenBlocks/issues/831

**Comment by averyrichardson** [comment]
Is there like anyway i can fix it??

**Comment by EmanYm** [comment]
Read what boq posted on that issue link

**Comment by mezz** [comment]
Thanks for the report!
For now you can remove Optifine or OpenBlocks.

Please report to Optifine here: https://github.com/sp614x/optifine/issues
and link them to the OpenBlocks issue.

**Comment by Ommina** [comment]
Remove OpenBlocks or Optifine are your two options, really.  The former you lose content.  The latter you lose the pretty goodies Optifine provides.  It's probably worth reporting to the Optifine repo so he knows, assuming it has not already been done.

**Comment by EmanYm** [comment]
It has been.

https://github.com/sp614x/optifine/issues/787
