### ISSUE TITLE
JEI - You do not have permission to use this command

### ISSUE THREAD

**Issue by Kyrislian** [mezz/JustEnoughItems#958]
A friend was using JEI fine on my server (we use this mod to view recipes) but as of a couple hours ago, every time she tries to view recipes that the item is used in/recipes on how to make them, she gets "You do not have permission to use this command."

Help please? XD

Using JEI  1.11.2-4.5.0.291 on MC 1.11.2

**Comment by TehNut** [comment]
Control click on the wrench. It toggles cheat mode.
