### ISSUE TITLE
crashes when typing words in the search bar didnt crash when add a @ sign infront

### ISSUE THREAD

**Issue by alphahui** [mezz/JustEnoughItems#959]
Hi ! I have recently created a mod pack at twitch launcher. At first everything was fined .When I type something in the search bar it crashes, but adding  a @ sign infront it won't happen. Please help!
crash report: https://pastebin.com/w0jQwCyU

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with infinitylib, reported here: InfinityRaider/InfinityLib#20
