### ISSUE TITLE
Dump items and recipe images to file

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#96]
It would be useful for modders and wiki maintainers to have some kind of image dump for items and recipes.

**Comment by ColinGBos** [comment]
I like this idea. There are some very nice features to NEI that I miss, things like setting game rules (weather and time) I used all the time.

**Comment by wlhlm** [comment]
> features to NEI that I miss, things like setting game rules (weather and time)

While those features are useful, I think they are not part of the core of what JEI is (which is item and recipe browsing) and are more suitable for a separate mod.

**Comment by mezz** [comment]
Chicken-bones intends to release the misc NEI utils as a separate mod.

**Comment by Prospector** [comment]
Also, can we have a way to dump all the items without localized names? For example, when I am modding, I make a tonne of items, then have to localize them all later. If I could just dump a list of all the unlocalized names, then I can simply copy and paste that into a lang file, and localize them.

**Comment by Darkhax** [comment]
This would be a pretty good idea, and would make maintaining my mod documentation so much easier. +1

@TheDoctorSoda I think that might be a bit outside the scope of the project. You can easily add this into your own mod/workspace and accomplish the same thing. This would also slow down loading time a bit, because you would have to loop through all the tiles and items registered.

**Comment by Prospector** [comment]
Yeah, that's true.

**Comment by mezz** [comment]
This is most likely going to be implemented as a JEI addon mod, but I'm going to leave this issue here until I do something with it.

**Comment by dmodoomsirius** [comment]
+1

**Comment by xbony2** [comment]
I'm part of the FTB Wiki, and this to me is more important then recipes :P

**Comment by wlhlm** [comment]
@xbony2 There is [BlockRenderer](http://minecraft.curseforge.com/projects/blockrenderer) if you are looking for an alternative. I'm still not sure why this is needed in JEI specifically.

**Comment by xbony2** [comment]
Interesting, but not very configurable; tiles are usually based on 64x64 dumps. Also, it can't dump groups/mods; dumping each tile manually would be awfully time consuming.

**Comment by exaskye** [comment]
@xbony2 I'm the author of BlockRenderer, and I just released [an update](http://minecraft.curseforge.com/projects/blockrenderer/files/2283690) that adds bulk rendering. Hold CTRL and press the render key. It accepts a comma-separated list of mod ids.

I don't really see the point in adding a configuration to set the size, as you can just rescale the images. Here's a quick bash script using ImageMagick's mogrify to do just that:

``` bash
for file in *; do mogrify -resize 64x64 $file; done
```

Took 10 seconds to resize a render of every item in vanilla using that script on my system.

**Comment by Darkhax** [comment]
something that could be cool, is if this could be taken one step further and turned into an Info-graphic style output. The general data that would be required such as image, recipes, and in many cases a brief description can all be provided by the mod, and in many cases they are. It is conceivable that this could all be combined to create an entire info-graphic for basic content mods. This would also be very helpful in documenting the mod on forum posts and other places.

**Comment by mezz** [comment]
I think this is a good idea, but BlockRenderer looks like a good solution already. 

Unfortunately I don't have time to create a more ambitious project based around the ideas here, so I am closing this issue. 

Feel free to continue discussion.

**Comment by xbony2** [comment]
@unascribed thanks, cool, fine for items, but 64x64 (and larger sometimes) are needed for block dumps to get the proper detail.

**Comment by exaskye** [comment]
@xbony2 The mod renders at 512x512 by default (480x480 if the window isn't large enough) — this is my point. The snippet I posted is for scaling _down_ the renders.

**Comment by xbony2** [comment]
That's probably too big o-o much thanks though.

**Comment by Prospector** [comment]
@unascribed would be cool if there was JEI integration to also save recipes to images.

**Comment by exaskye** [comment]
@ProfessorProspector It would, but that would greatly complicate the mod. Currently it's just some simple wrapper logic around vanilla rendering. I'll probably end up looking into that sometime in the future.

**Comment by ColinGBos** [comment]
@xbony2 as long as it's a multiple of 64, it'll scale well down to it.
I do think it would be a good addition to JEI as an addon just because of the how nice it is to specify the list of what gets printed, which was helpful in NEI

**Comment by KernelDeimos** [comment]
This bugs me so much. JEI has all the data I want in RAM already when the game is loaded. How is this outside the scope? JEI organises all the recipes in the game into my memory already and I just wanna get it out of there into a file.

**Comment by mezz** [comment]
I've been organizing things to make it easier to do this, but let's step back a second.
This bugs you? Don't act so entitled to free software. Pay me a salary and I'll implement it, thanks.

**Comment by xbony2** [comment]
BlockRenderer is good and we have been using it for the FTB Wiki for almost 3 years now 👍

**Comment by DarkGuardsman** [comment]
Not sure why someone sent this to me in private messages... but you can just use a separate program to batch scale images up. Someone with even java 101 experience can write a short 20 line program to do the job. As well I rather see JEI work on other issues then adding a feature that will get used by less than 1% of users.

**Comment by KernelDeimos** [comment]
Tbh I severely misunderstood something. I saw this issue linked in a thread about dumping recipe data, so every time I read "images" I was thinking "snapshots of memory" rather than literal pictures. Now I totally understand why this is out of scope of JEI.
