### ISSUE TITLE
[1.12] Deleted Items just turn invisible rather than being deleted

### ISSUE THREAD

**Issue by Marioluigi7896** [mezz/JustEnoughItems#960]
Version 1.12-4.7.2.77
In Creative Mode with Item cheating on, deleting items by clicking in the JEI menu (where the items are) just turns the item invisible and it is still in the same slot (although you can still drop other items on it and the slot moves one over)
This does not occur in survival mode with item cheating on.
Video of Bug:
https://www.youtube.com/watch?v=dQPtrBRTdpU

**Comment by Marioluigi7896** [comment]
Forge Version 14.21.1.2426

**Comment by mezz** [comment]
I tried locally and on a server but I am not able to reproduce this issue.
Have you tried without other mods installed?

**Comment by Marioluigi7896** [comment]
Just tried with only jei, still is happening
https://www.youtube.com/watch?v=32SVB6TXgGQ

**Comment by mezz** [comment]
Ah thanks I got it to happen. It has to be on that specific page of the creative inventory. Weird.

**Comment by mezz** [comment]
Hah it happens even if I use the creative inventory's "destroy item" spot.

**Comment by Marioluigi7896** [comment]
if you shift click the destroy item slot it fixes it

**Comment by Marioluigi7896** [comment]
wonder if that happens in vanilla

**Comment by mezz** [comment]
It is actually a vanilla bug!

Go on a server and open the same inventory, and use the server command window to `/give` some stone while you have the screen open. Using just that and the "destroy item" spot you can reproduce the bug.

I think it relates to this? https://bugs.mojang.com/browse/MC-87019

**Comment by mezz** [comment]
Please report this bug to Mojang, in the worst case they will mark it as a duplicate and point you at the right issue.
