### ISSUE TITLE
Minecraft crashes when I type certain things

### ISSUE THREAD

**Issue by Ministringham** [mezz/JustEnoughItems#961]
I made a modpack to play with some friends, the problem is that often when we type into JEI it crashes the entire client. This is only the case with certain things though, for example, I can manage to type "en" no problem but when I type "end" it crashes. A few pages I read said that it was due to Sponge, but I have removed that and I am still having the issue. Here are the crash logs:
[crash-2017-07-28_14.44.43-server.txt](https://github.com/mezz/JustEnoughItems/files/1184222/crash-2017-07-28_14.44.43-server.txt)
[crash-2017-07-28_14.44.42-client.txt](https://github.com/mezz/JustEnoughItems/files/1184221/crash-2017-07-28_14.44.42-client.txt)

Any help is very much appreciated, it's difficult to play modded Minecraft without JEI

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with infinitylib, reported here: InfinityRaider/InfinityLib#20
