### ISSUE TITLE
World doesn't load

### ISSUE THREAD

**Issue by UTMoStLimIt** [mezz/JustEnoughItems#962]
Version of Forge used: 14.21.1.2426
Version of Minecraft: 1.12 (release)
Version of JEI used: 1.12-4.6.0.59
Problem:

Every time I try to load a map, the loading gets stuck and the console outputs this:
```
16:22:02] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
```

I've attached the crash log below
[https://gist.github.com/UTMoStLimIt/77e2a0f108eed7658b27e03076003205](url)

**Comment by mezz** [comment]
Thanks for the report!
Please update to the latest version of JEI, the one you have is not compatible with the version of Forge you have.

**Comment by UTMoStLimIt** [comment]
So I just reinstalled JEI. It's working for now. You can close the issue.
