### ISSUE TITLE
Typing causes cursor to jump to the end of the search text box

### ISSUE THREAD

**Issue by Cup-of-Joe** [mezz/JustEnoughItems#963]
Typing anything, including the backspace key, puts the cursor at the end of the search text box

Example:
- When I type "dust"
- and then try to add "@thermal" before it...
- when I type "@", it jumps the cursor to the end
- putting the cursor back and then typing "t" jumps the cursor to the end
- etc.

It's tedious editing text in the search text box.

**Comment by mezz** [comment]
Thanks for the report!
Confirmed, I'll look into it.

**Comment by mezz** [comment]
Fixed in 1.11.2 and 1.12
