### ISSUE TITLE
[1.12] [Suggestion] Add spacing between icons in recipe viewer

### ISSUE THREAD

**Issue by SnowShock35** [mezz/JustEnoughItems#964]
Hi @mezz,

I have a small suggestion for Just Enough Items (JEI) for Minecraft 1.12 (and other versions if applicable). Here's the details of my suggestion.

### Suggestion Description

In the latest version of JEI for Minecraft 1.12 there are two small icons when viewing recipes telling you if it's a shapeless recipe and what mod the recipe comes from. However, both these are placed quite close together in the UI (see screenshot) and they look very squashed together. Perhaps see about adding some spacing to the left and right of them. 

### Suggestion Media

![](https://ss.blamesnow.co.uk/2017/07/1501410512-c81f726b.png)

**Comment by mezz** [comment]
I have been thinking of removing the `i` icon except when the mod who created the recipe did not also create the output item. That way most recipes do not show it at all.

**Comment by Virtuoel** [comment]
With regards to removing the `i`, I would hope if it's removed for those kinds of recipes that it would still show up for all recipes when Advanced Tooltips are enabled.

**Comment by mezz** [comment]
I removed the `i` and  moved all that information to the tooltip of the output item. 
It looks a lot cleaner this way. :)
