### ISSUE TITLE
[Suggestion] Provide offline "drops"

### ISSUE THREAD

**Issue by Adrigorithm** [mezz/JustEnoughItems#966]
I know I shouldn't suggest NEI features (yes I've inspected the spreadsheet) but I think this is a useful feature, especially for server administrators. 

For example: let's say you have to make changes of one item by their ID, then you'd have to load every modpack to find out those ID's (which would be ofc different). 

That's why I'm asking to include this feature. If you don't know exactly what it should look like, here's an example: https://docs.google.com/spreadsheets/d/1SNbxudzxKuQ1fELrYuvQXD-yfI-0M49NAUr6lh4DNyo/edit?usp=sharing

**Comment by mezz** [comment]
In the NEI spreadsheet, this is called "Dump Item/Block IDs"
The [TellMe](https://minecraft.curseforge.com/projects/tellme) mod does a great job of this, check it out.
Also in modern versions of Minecraft, you only need to use the name like "minecraft:stone", the actual numerical ID is not necessary.

**Comment by Adrigorithm** [comment]
This is exactly what I was looking for, thank you. And about the names yeah I'd love to use them, the problem is that I'm not in charge of dealing with plugin versions, so the (old) plugins do not support that meaning I have to use numerical ID's.
