### ISSUE TITLE
Some types of IDrawableAnimated not drawing as expected

### ISSUE THREAD

**Issue by Virtuoel** [mezz/JustEnoughItems#967]
When viewing `FurnaceSmeltingCategory` in JEI, the `arrow` animated drawable does not appear to be drawn/animated.
In `FuelRecipe`, the `flame` animated drawable is not drawn/animated either.

Also, the first frame of the `flame` animated drawable in `FurnaceSmeltingCategory` doesn't seem to last as long as the other frames in the animation. This seems to apply to other forms of `IDrawableAnimated` like `bubbles` from `BrewingRecipeCategory`, for which the last frame is affected.

The final thing I noticed was when the `animatedFlame` drawable from `FurnaceRecipeCategory` is drawn in `FurnaceSmeltingCategory`, it is one pixel too far to the right.

**Comment by mezz** [comment]
Thanks for the report!
