### ISSUE TITLE
Recipe function causes crashes 1.10.2

### ISSUE THREAD

**Issue by exultanthabit** [mezz/JustEnoughItems#968]
Searching items and clicking on them for recipes seem to cause a crash, though this crash seems to be a random corruption as not all the players on my server seem to experience it.
[Crash log](
https://gist.github.com/exultanthabit/53e1387922f30dd7183281c9cd0849a8)

forge-12.18.3.2422
jei_1.10.2-3.14.7.420.

**Comment by mezz** [comment]
Thanks for the report!
This looks like a crash from ExU2. JEI is just rendering the item in a normal way.
