### ISSUE TITLE
Add better tooltip to "+" button

### ISSUE THREAD

**Issue by SoniEx2** [mezz/JustEnoughItems#969]
The "+" button should have a more descriptive tooltip. Nobody knows that you can normal-click it to move only one item.

**Comment by mezz** [comment]
It has a tooltip already, what do you mean?

![2017-08-03_20 00 17](https://user-images.githubusercontent.com/916092/28952504-775e2d38-7886-11e7-8a4c-46b0f02cbaec.png)
![2017-08-03_20 00 28](https://user-images.githubusercontent.com/916092/28952506-78e197d0-7886-11e7-9e37-f600f688cdc7.png)

**Comment by SoniEx2** [comment]
Nobody knows about normal-click?

**Comment by SoniEx2** [comment]
this is still an issue - the tooltip does not distinguish between moving a single set of items (click on "+") and moving all sets of items (*shift*+click on "+", i.e. holding shift while hovering over it)
