### ISSUE TITLE
[1.10.2][Suggestion] Handling conflicting recipes

### ISSUE THREAD

**Issue by Liiw** [mezz/JustEnoughItems#970]
Hello!

I've been using JEI ever since I moved to 1.10.2 and I must say this is an excellent mod. A literal must-have for any pack. However I would like to see a feature implemented:

Often I have trouble with conflicting recipes. You know- two different items which have the same crafting recipe. While there is a mod that tries to resolve this, for some reason it hasn't worked recently (maybe it is because I'm using sponge on the server or it's a newer forge issue, I don't know). My point is, could a feature be implemented in JEI itself to allow switching between items that have similar crafting recipes?

**Comment by mezz** [comment]
Thanks for the suggestions!
Sorry I missed this somehow.
I think that resolving recipe conflicts it outside the scope of JEI. 
The NoMoreRecipeConflict mod does a good job already, I think.
https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict
