### ISSUE TITLE
[1.12] [Suggestion] List size, Clear text button

### ISSUE THREAD

**Issue by Andronachi-Marian** [mezz/JustEnoughItems#972]
1. If i open the inventory the list size is 8 rows. After i open a recipe, the list size is changed to 7 rows and the list position is changed a little bit.

2. Before JEI Config button, i like to see a button to clear the textbox and autofocus for fast search.

**Comment by way2muchnoise** [comment]
Textbox focus can be gotten by ctrl+F and using ctrl+A you can select all of it. That gives you some solutions for part 2.

**Comment by mezz** [comment]
Thanks for the suggestions!
The ingredient list tries to take up all the available space next to the open gui. If the next gui is smaller, it has less space to work with. I'm not sure if there is a good general solution to this problem.

**Comment by Andronachi-Marian** [comment]
way2muchnoise meybe an option for CTRL+F with autoclear. But i like to use the mouse too.
