### ISSUE TITLE
Crafting - Crash

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#973]
Hi, i have a problem today i playing on mod serwer i have 3 mods optifine security craft and jei and this is not security craft fault cuz i ask dev for this with this crash this is any log form 0:50 minute And when i try craft anything anywhere in craftingtable and in inv craft i cant game crashes and bum nothing.

Crash minute logs: https://gist.github.com/def7502/eae0e009f1436263e952aa41d1389507

**Comment by mezz** [comment]
Sorry I don't think this has to do with JEI.
Try removing JEI and see if you still have the issue.
