### ISSUE TITLE
[1.12] issue. the jei stops showing up in game. tried removing from game and adding it back in but it doesn't do anything

### ISSUE THREAD

**Issue by AJP1** [mezz/JustEnoughItems#974]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by TehNut** [comment]
Did you press `CTRL+O`? That is the default keybind to hide the item list.
