### ISSUE TITLE
So, whenever I try to use JEI to craft anthing it will crash my game. When I go through pages of recipes, it will crash my game. 

### ISSUE THREAD

**Issue by Anna-Ethelin** [mezz/JustEnoughItems#975]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Anna-Ethelin** [comment]
Crash Report: https://gist.github.com/Anna-Ethelin/fa724d7b321f900e16cebe3bed48babb

**Comment by KnightMiner** [comment]
Update Chisel and/or CTM. This does not look like a JEI issue but I know Chisel recently fixed one.

**Comment by mezz** [comment]
Thanks for the report!
Yes this is a chisel issue that I think has been solved.
