### ISSUE TITLE
[1.12] Crash when clicking certain items

### ISSUE THREAD

**Issue by NielsPilgaard** [mezz/JustEnoughItems#976]
Hey!

Minecraft 1.12
Forge 1.12-14.21.1.2443
JEI 1.12.1-4.7.5.87

I hardcrash when trying to look at recipes for certain items, this crash in particular was a Mekanism crafting component. [Crashlog](https://gist.github.com/NillerMedDild/462fdbee926c2ff9e0f4c3777a6ab3b8)

**Comment by mezz** [comment]
Thanks for the report!
This looks like a Chisel crash. I think it has been fixed, please try updating Chisel.

**Comment by NielsPilgaard** [comment]
Yup, updating Chisel fixed it, thanks :)
