### ISSUE TITLE
Minecraft 1.12.1 random crash

### ISSUE THREAD

**Issue by Realever** [mezz/JustEnoughItems#978]
Hi,
 when I search any Item with JEI, my client is crashing sometimes.
Here are the crash reports: https://pastebin.com/bUD0w5mk   and  https://pastebin.com/2U397ekA

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
    Ingredient Mod: Chisel
    Ingredient Info: 1xtile.chisel.bookshelf_oak@4 chisel:bookshelf_oak
```
```
-- Ingredient being rendered --
Details:
    Ingredient Mod: Chisel
    Ingredient Info: 1xtile.chisel.bookshelf_oak@7 chisel:bookshelf_oak
```
These seem to be Chisel issues, please report to the Chisel team here: https://github.com/Chisel-Team/Chisel/issues

**Comment by Realever** [comment]
ok i reported it to chisel.Thanks for help

**Comment by mezz** [comment]
Thanks.
For anyone following, the new issue is here: https://github.com/Chisel-Team/Chisel/issues/527
