### ISSUE TITLE
crashing when clicking on recipes 

### ISSUE THREAD

**Issue by madkingdiamond** [mezz/JustEnoughItems#979]
[crash-2017-08-20_17.42.27-client.txt](https://github.com/mezz/JustEnoughItems/files/1237374/crash-2017-08-20_17.42.27-client.txt)

Crashing when trying to view crafting recipes for anything. And yes I removed NEI already and still crashes

**Comment by madkingdiamond** [comment]
[crash-2017-08-20_17.42.27-client.txt](https://github.com/mezz/JustEnoughItems/files/1237375/crash-2017-08-20_17.42.27-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
Please try without `codechicken.lib` as well.
