### ISSUE TITLE
crash when looking up recipe for empty fluid containters

### ISSUE THREAD

**Issue by AEnterprise** [mezz/JustEnoughItems#98]
when looking up the recipe for an empty fluid container JEI crashes because it assumes that the container always has a fluid

https://gist.github.com/AEnterprise/0f1f1ce1dd1823befff8

**Comment by mezz** [comment]
Confirmed, thanks for the report!

**Comment by mezz** [comment]
This is fixed in the latest version

**Comment by AEnterprise** [comment]
alright, thanks for the quick fixing
