### ISSUE TITLE
API request: get recipe category in recipe layout

### ISSUE THREAD

**Issue by Towdium** [mezz/JustEnoughItems#981]
Hi,

The problem is I'm trying to get crafting item when using a custom universal recipe transfer handler.  Is there any related API that I have missed?

My old solution is using diffent transfer handlers for each recipe category, but it seems a little wired since I'm doing universal transfer, and it requires some extra work to get the category list.

I noticed JEI is storing the recipe category in recipe layout, so is it possible to provide API to get it? I don't know much about JEI's design, what I'm looking forward to is exposing information about recipe category to universal recipe transfer handlers.

**Comment by mezz** [comment]
Sure, that makes sense. Added.
