### ISSUE TITLE
Item panel reappearence

### ISSUE THREAD

**Issue by DrKilledalot** [mezz/JustEnoughItems#982]
Either I`am overlooking a option for this , or its a missing feature.
I like to frequently hide the jei item panel to reduce lag when going in my inv, tough it always reappears after reentering my inv
Also before actully hiding the panel it lets the options button appear at the first buton press

**Comment by mezz** [comment]
You can hide the item panel using a hotkey. By default it is `Control + O`.

**Comment by DrKilledalot** [comment]
Well thats the problem, i`ve rebound it to A , tough when i hide it, it reapears after opening my inv again instead of staying hidden
