### ISSUE TITLE
[1.12.1-4.7.8.91] GuiIngredientFast Crash

### ISSUE THREAD

**Issue by Leo40Git** [mezz/JustEnoughItems#984]
**Log:** https://gist.github.com/Leo40Git/a878befab572119c2fa080fddd59b186
Previously thought to be an issue with the combination of XU2, BetterFps and JEI, turns out it's an issue with JEI only (XU2 is installed but the log isn't pointing at it like [here](https://gist.github.com/Leo40Git/902de94a5544ed224ab79da1fd2ff145)).

**Comment by mezz** [comment]
Thanks for the report!
This seems to be caused by a mod I haven't head of before, you can see the details in the crash log:
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: JAOPCA
	Ingredient Info: 1xitem.jaopca.nugget@0 jaopca:item_nuggetredstone
```
I think you can report issues to them here: https://github.com/TheLMiffy1111/JAOPCA/issues

**Comment by Leo40Git** [comment]
It seems this error was already reported to JAOPCA.
...and was already fixed, maybe.
Oops!
By the way, JAOPCA is basically Another One Bites the Dust for 1.10+.

**Comment by mezz** [comment]
Ah ok, cool.
For anyone coming here later, the JAOPCA issue is here: https://github.com/TheLMiffy1111/JAOPCA/issues/23
