### ISSUE TITLE
[1.12.1] [jei_1.12.1-4.7.8.91] Crash upon clicking recipe of a block in JEI

### ISSUE THREAD

**Issue by MrBurd** [mezz/JustEnoughItems#985]
Crash log: https://gist.github.com/MrBurd/129cb7a83d5d9a3516709c51556d781d

Version: jei_1.12.1-4.7.8.91

Description:

I looked up the recipe for the IE transformer. Upon hovering over a nearby item, the game froze and crashed with the above log.
I have attempted to replicate the error, could not replicate. 
Reporting anyway because it might be of use, hopefully.

**Comment by MrBurd** [comment]
Crash happened again, this time while opening inventory with the JEI screen still set to look up "transf" for the transformer.

I've got the same error log, this part seems to be interesting/related:

> -- Ingredient being rendered --
Details:
	Ingredient Mod: Chisels & Bits
	Ingredient Info: 1xitem.mod.chiselsandbits.mirrorprint@0 chiselsandbits:mirrorprint

It appears that having JEI open on this search query shows a C&B item that somehow fails to render.
Not sure if this is a JEI or C&B bug.

**Comment by mezz** [comment]
Thanks for the report!
This is actually a crash from twilight forest, please report it here: https://github.com/TeamTwilight/twilightforest/issues
