### ISSUE TITLE
[1.12] Not worked

### ISSUE THREAD

**Issue by Grotrianv** [mezz/JustEnoughItems#986]
Sorry - my english is very bad!

I have forge latest version on 1.12 at this moment and optifine in my modpack. I install JEI latest 1.12 version and this mod not worked - indexing ingredients not loaded. Help me with this problem. (All other mods was worked)

**Comment by mezz** [comment]
Thanks for the report!
Do you have a crash log?
Have you tried without optifine?

**Comment by Grotrianv** [comment]
I have crash log. Without optifine Jei too not worked. (But i have my launcher minecraft - perhaps this is due to the fact that there is not a standard file location, and perhaps there is not all files)
[crash-2017-08-30_20.17.08-client.txt](https://github.com/mezz/JustEnoughItems/files/1265764/crash-2017-08-30_20.17.08-client.txt) My crash file have other mods, but with these mods and without mods the result is the same

**Comment by mezz** [comment]
I think JEI is crashing earlier but the game keeps running. It should show up in the full log.
Can you upload your `fml-client-lastest.log` to https://gist.github.com/ and link it here?

**Comment by Grotrianv** [comment]
I work on my launcher and find the problem - its my files problems.

**Comment by mezz** [comment]
Can you explain how you fixed it, for people who have the same problem?
