### ISSUE TITLE
Double mod id under the items

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#987]
My mod has with JEI installed the Mod ID double under the items..      

I know, thats not mainly your problem but it would be awesome if you can say me which could cause the problem

Thanks for the help!

**Comment by way2muchnoise** [comment]
What other mods do you have installed?

**Comment by ghost** [comment]
Ahhhh, the problem is only when JEI and Waila is installed

**Comment by ghost** [comment]
But only for my mods

**Comment by mezz** [comment]
Thanks for the report!
Do you have a screenshot? What is the name of the mod?
I need to be able to reproduce this bug before I can fix it.

**Comment by TehNut** [comment]
IIRC, if you are in the search tab of the Creative menu, Vanilla adds the item's tab name to the tooltip as well.

**Comment by ghost** [comment]
That problem has all of my mods, here as example the Advanced Sticks mod. The problem is only with JEI and Waila installed.

Here some screenshots:
In the creative tab: https://i.imgur.com/uTR3gCo.png
in the search tab: https://i.imgur.com/YSuekQp.png
in jei: https://i.imgur.com/AOWUQtx.png

**Comment by mezz** [comment]
That's pretty weird.
I'll install those mods and look into it.

**Comment by mezz** [comment]
I'm assuming you're on 1.12.1 and using Hwyla and not Waila.

**Comment by mezz** [comment]
Using JEI, Hwyla, and Advanced Sticks, I see something different:

![2017-09-10_14 50 05](https://user-images.githubusercontent.com/916092/30253335-90640cde-9637-11e7-8ed8-4f6619e1bdf4.png)
![2017-09-10_14 50 10](https://user-images.githubusercontent.com/916092/30253334-9063088e-9637-11e7-9949-e7fa21b9df54.png)


Please explain very clearly how I can reproduce this bug.

**Comment by ghost** [comment]
I used:
jei_1.11.2-4.3.5.277
waila-1.7.1_1.11.2
advanced sticks 1.11.2 v.1.4.4

**Comment by ghost** [comment]
The "?9" prefix before the mod is the color code in the mcmod.info file.... strange

**Comment by mezz** [comment]
Can you try using Hwyla instead of Waila, it's much less buggy.
Also try removing the color code from your mod name.

**Comment by ghost** [comment]
i tested Hwyla (on mc 1.12.1 & mc 1.11.2), the same problem as with Waila.   But i has not this strange prefix

**Comment by ghost** [comment]
http://i.imgur.com/oOdVtmT.png
(i changed the mod name from "Advanced Sticks Mod" to "Advanced Sticks" between versions of the mod)
