### ISSUE TITLE
Oredict recipes with no matching items show up with blank spots

### ISSUE THREAD

**Issue by josephcsible** [mezz/JustEnoughItems#988]
**Setup:** Create a recipe that uses the ore dictionary, but with no items that match the ore dictionary key. For example, in CraftTweaker:
```
recipes.addShapeless(<minecraft:clay_ball>, [<minecraft:water_bucket>, <ore:nonexistium>]);
```

**Expected Behavior:** The recipe doesn't show up at all in JEI, since it's impossible to actually use.

**Observed Behavior:** The recipe shows up in JEI, but completely missing any sign of the item corresponding to the empty oredict key. (In the example above, you see a recipe of just a water bucket becoming clay, which won't actually work if you try it.)

**Other Notes:**
JEI version 4.7.8.92. Note that this happens with any mod that adds such a recipe, not just CraftTweaker.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the next release.
