### ISSUE TITLE
Possibly + button bug?

### ISSUE THREAD

**Issue by Prospector** [mezz/JustEnoughItems#99]
When watching direwolf20's latest video on forgecraft, I noticed that when he was using the + button when crafting a bed, it said he had missing items, when he actually had the three wool and three planks. Not sure how exactly you have the button working, but they were three different colours (light grey, cyan, and white) of wool, and jungle wood planks.

![image](https://cloud.githubusercontent.com/assets/6166773/12227457/ce174ebe-b7e1-11e5-9199-90a084455cdf.png)
![image](https://cloud.githubusercontent.com/assets/6166773/12227462/dd63e788-b7e1-11e5-933a-8a0811afa373.png)

EDIT: Actually just noticed something, he is using a crafting station. Could that be it?

**Comment by mezz** [comment]
It's a minor bug yeah. I will address it when I tackle https://github.com/mezz/JustEnoughItems/issues/65
