### ISSUE TITLE
Crashing when joining a server.

### ISSUE THREAD

**Issue by Skizzles** [mezz/JustEnoughItems#991]
Hello, 
I seem to be crashing when joining a server.. I looked through the crash log and it said JEI had a null pointer exception.

https://pastebin.com/iD8qNUB5

**Comment by KnightMiner** [comment]
That points to NEI in their JEI integration.

**Comment by Skizzles** [comment]
So this would be an NEI issue?

**Comment by KnightMiner** [comment]
Yep, report it to the [NEI issue tracker](/TheCBProject/NotEnoughItems/issues)

**Comment by mezz** [comment]
Closing this issue, anyone with the same problem please follow the NEI issue here: https://github.com/TheCBProject/NotEnoughItems/issues/122
