### ISSUE TITLE
[Suggestion]Advanced Search Filter with profiles

### ISSUE THREAD

**Issue by Thretcha** [mezz/JustEnoughItems#992]
It would be nice to have the ability to hide certain mods from the list without the use of the search bar.
For example as a user I would love to be able to hide all those chisel entries to just one per block. Or just hide certain items that I know I don't need to look up, so it's easier to actually find what I am looking for. Having the options to save those list of hidden items(in profiles) could be really handy.
If I can implement this myself and you can show me how I would gladly do so. :)

**Comment by TehNut** [comment]
Click the wrench at the bottom right and enable edit mode. Hide the items you don't want. Disable edit mode when you're done.
