### ISSUE TITLE
ColorNamer API

### ISSUE THREAD

**Issue by exaskye** [mezz/JustEnoughItems#994]
It would be nice to have an API to access ColorNamer instead of having to use the Internal class.

Use case: I'm implementing a JEI-like search system and want to leverage JEI's color system if available.

I would prefer to use JEI's search system itself, but I figure a much easier goal is to just expose color names in the API. As it stands, there's API to get a list of colors, but not a list of color *names*.

**Comment by mezz** [comment]
Hmm I wonder if it would be worthwhile to split the color stuff off into its own optional library. 
I don't think it makes a ton of sense to tie it directly to JEI in the API.

**Comment by mezz** [comment]
I can't think of a lot of stuff that would use it though. Flat Colored Blocks already has something similar and there probably isn't another mod that would use it. I guess I'll look for a good spot to put it in the API.
