### ISSUE TITLE
[1.12] Massive fps drops in JEI with some mods

### ISSUE THREAD

**Issue by Thyriel** [mezz/JustEnoughItems#997]
Not sure if the problem is in those mods or in JEI, but as it's affecting multiple mods and only 1.12 i guess the problem may be somewhere in JEI.

On some pages of the item list of JEI the fps drop from >100 down to 10-20, in case of one mod even down to 1-2 fps where it starts to become a problem even clicking something. (no optifine installed)
Mods this is happening so far:
- Tinkers Construct: Page 1 works fine with no drops, page 2 drop to 40-50 fps, page 3 then only 1-2 fps, last page like 5-10 fps
- Immersive Engineering: 20-30 fps
- Forestry (Page 2 only): 40-50 fps (50% drop at least)

I first noticed the problem when i only had JEI and Tinkers Construct installed no other mods at this point.

JEI Version: jei_1.12.2-4.7.10.98
Forge: 14.22.1.2485

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately this is not caused by JEI. It is just rendering a lot of items, and that is relatively slow to do.
I can take a look and see if there is anything more I can do, but most likely the fix has to be on their side.

**Comment by Thyriel** [comment]
Thanks. Reported it @Tinkers then: https://github.com/SlimeKnights/TinkersConstruct/issues/3171

**Comment by mezz** [comment]
I worked on optimizing a bit more today, and I made a nice breakthrough.
Try out jei_1.12.2-4.7.10.99 and let me know how it works for you.

**Comment by Thyriel** [comment]
Much better, thanks :)
All the drops to like 50% are gone now and the one tinker page with extreme fps drops is now like 50-60 fps (so no problem at all)

**Comment by mezz** [comment]
Cool, glad it's working better now!
