### ISSUE TITLE
[1.11.2] Crash when opening inventory.

### ISSUE THREAD

**Issue by YuriKircovich** [mezz/JustEnoughItems#998]
Sorry, this is probably a waste of your time, but here's the story: Downloaded John Smith Legacy and the Jim Stone Craft edition resource packs. Messed around with it a bit so I could get the textures I wanted from both versions. Probably screwed something up with that, since it's most likely the culprit. Brother can use my edited packs just fine, except my client crashes when opening my inventory. Only difference is he is operating on a slightly older version of JEI. Read through the crash reports trying to make sense of them. Want to see what I can do to fix this so I am able to continue using my resource pack.

https://gist.github.com/YuriKircovich/45148258d9fc3b162f3da8f23e7d5551

**Comment by mezz** [comment]
Thanks for the report!
This seems to be a crash from Bibliocraft:
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: BiblioCraft
	Ingredient Info: 1xtile.BiblioCraft:Clipboard@0 bibliocraft:clipboard
```
You can report it here:  https://github.com/Nuchaz/BiblioCraft/issues

**Comment by YuriKircovich** [comment]
Thanks, I'll go report it there. JEI functioned normally before installing the resource pack. Do you have any clue why the resource pack might have caused this?

**Comment by mezz** [comment]
I'm not sure, maybe the item didn't show up on the first page before so it didn't crash.
