### ISSUE TITLE
Mod name formatting matcher not working

### ISSUE THREAD

**Issue by ChloeDawn** [mezz/JustEnoughItems#999]
JEI isn't matching the mod name formatting when Hwyla is present. I presume this is an issue with other mod name tooltip mods too although I haven't tested.

**JEI version:** [4.7.10.98](https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2482748)
**Hwyla version:** [1.8.20-B35](https://minecraft.curseforge.com/projects/hwyla/files/2462171)
**Forge version:** [1.12.1-14.22.1.2485](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.1-14.22.1.2485/forge-1.12.1-14.22.1.2485-changelog.txt)

**Related commit: 7f4160ed969fad85e8c4a14809c66402c51592b2**

**Recording of issue:**

![Recording of issue](https://thumbs.gfycat.com/UnhealthyOffensiveIcelandgull-max-14mb.gif)

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the next release, 101.
